Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Fatras/Kernel/ContinuousProcessTests.cpp File Reference
ContinuousProcessTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Units.hpp"
#include "Acts/Material/MaterialSlab.hpp"
#include "Acts/Tests/CommonHelpers/PredefinedMaterials.hpp"
#include "ActsFatras/EventData/Barcode.hpp"
#include "ActsFatras/EventData/Particle.hpp"
#include "ActsFatras/Kernel/ContinuousProcess.hpp"
#include <algorithm>
#include <array>
#include <iterator>
#include <random>
#include <vector>
Functions
BOOST_AUTO_TEST_CASE (NoSelectors)
BOOST_AUTO_TEST_CASE (WithInputSelector)
BOOST_AUTO_TEST_CASE (WithOutputSelector)
BOOST_AUTO_TEST_CASE (WithChildSelector)
Function Documentation
BOOST_AUTO_TEST_CASE (NoSelectors)
Definition at line 71 of file ContinuousProcessTests.cpp.
View newest version in sPHENIX GitHub at line 71 of file ContinuousProcessTests.cpp
References f, tgeo-response2json::process(), and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (WithInputSelector)
Definition at line 80 of file ContinuousProcessTests.cpp.
View newest version in sPHENIX GitHub at line 80 of file ContinuousProcessTests.cpp
References f, tgeo-response2json::process(), ActsFatras::ContinuousProcess< physics_t, input_particle_selector_t, output_particle_selector_t, child_particle_selector_t >::selectInputParticle, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (WithOutputSelector)
Definition at line 100 of file ContinuousProcessTests.cpp.
View newest version in sPHENIX GitHub at line 100 of file ContinuousProcessTests.cpp
References f, tgeo-response2json::process(), ActsFatras::ContinuousProcess< physics_t, input_particle_selector_t, output_particle_selector_t, child_particle_selector_t >::selectOutputParticle, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (WithChildSelector)
Definition at line 122 of file ContinuousProcessTests.cpp.
View newest version in sPHENIX GitHub at line 122 of file ContinuousProcessTests.cpp
References f, tgeo-response2json::process(), ActsFatras::ContinuousProcess< physics_t, input_particle_selector_t, output_particle_selector_t, child_particle_selector_t >::selectChildParticle, and physmon_ckf_tracking::u.