Analysis Software: Acts::SpacePointData Class Reference
Acts::SpacePointData Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/EventData/SpacePointData.hpp>
Public Member Functions
SpacePointData ()=default
Default constructor.
SpacePointData (const SpacePointData &other)=delete
No copies.
SpacePointData & operator= (const SpacePointData &other)=delete
SpacePointData (SpacePointData &&other) noexcept=default
Move operations.
SpacePointData & operator= (SpacePointData &&other) noexcept=default
~SpacePointData ()=default
Destructor.
float quality (std::size_t idx) const
Getters.
float deltaR (std::size_t idx) const
void setQuality (std::size_t idx, const float value)
Setters.
void setDeltaR (std::size_t idx, const float value)
void resize (std::size_t n, bool resizeDynamic=false)
Resize vectors.
void clear ()
clear vectors
bool hasDynamicVariable () const
const Acts::Vector3 & getTopStripVector (std::size_t idx) const
const Acts::Vector3 & getBottomStripVector (std::size_t idx) const
const Acts::Vector3 & getStripCenterDistance (std::size_t idx) const
const Acts::Vector3 & getTopStripCenterPosition (std::size_t idx) const
void setTopStripVector (std::size_t idx, const Acts::Vector3 &value)
void setBottomStripVector (std::size_t idx, const Acts::Vector3 &value)
void setStripCenterDistance (std::size_t idx, const Acts::Vector3 &value)
void setTopStripCenterPosition (std::size_t idx, const Acts::Vector3 &value)
Private Attributes
std::vector< float > m_quality {}
Mutable variables.
std::vector< float > m_deltaR {}
std::vector< Acts::Vector3 > m_topStripVector {}
dynamic variables
std::vector< Acts::Vector3 > m_bottomStripVector {}
std::vector< Acts::Vector3 > m_stripCenterDistance {}
std::vector< Acts::Vector3 > m_topStripCenterPosition {}
Detailed Description
This class contains auxiliary and mutable data associated to the external space points provided by the customers These variables are used internally by the seeding algorithm, that reads and updates them The variables collected here are also dynamic variables only present for strip space points
Definition at line 25 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 25 of file SpacePointData.hpp
Constructor & Destructor Documentation
Acts::SpacePointData::SpacePointData () default
Default constructor.
Acts::SpacePointData::SpacePointData (const SpacePointData & other) delete
No copies.
Acts::SpacePointData::SpacePointData (SpacePointData && other) default noexcept
Move operations.
Acts::SpacePointData::~SpacePointData () default
Destructor.
Member Function Documentation
void Acts::SpacePointData::clear () inline
clear vectors
Definition at line 134 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 134 of file SpacePointData.hpp
References m_bottomStripVector, m_deltaR, m_quality, m_stripCenterDistance, m_topStripCenterPosition, and m_topStripVector.
Referenced by resize().
float Acts::SpacePointData::deltaR (std::size_t idx) const inline
Definition at line 106 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 106 of file SpacePointData.hpp
References ambiguity_solver_full_chain::idx, and m_deltaR.
Referenced by Acts::SeedFilter< external_spacepoint_t >::filterSeeds_2SpFixed().
const Acts::Vector3& Acts::SpacePointData::getBottomStripVector (std::size_t idx) const inline
Definition at line 62 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 62 of file SpacePointData.hpp
References ambiguity_solver_full_chain::idx, and m_bottomStripVector.
Referenced by Acts::xyzCoordinateCheck().
const Acts::Vector3& Acts::SpacePointData::getStripCenterDistance (std::size_t idx) const inline
Definition at line 66 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 66 of file SpacePointData.hpp
References ambiguity_solver_full_chain::idx, and m_stripCenterDistance.
Referenced by Acts::xyzCoordinateCheck().
const Acts::Vector3& Acts::SpacePointData::getTopStripCenterPosition (std::size_t idx) const inline
Definition at line 70 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 70 of file SpacePointData.hpp
References ambiguity_solver_full_chain::idx, and m_topStripCenterPosition.
Referenced by Acts::xyzCoordinateCheck().
const Acts::Vector3& Acts::SpacePointData::getTopStripVector (std::size_t idx) const inline
Definition at line 58 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 58 of file SpacePointData.hpp
References ambiguity_solver_full_chain::idx, and m_topStripVector.
Referenced by Acts::xyzCoordinateCheck().
bool Acts::SpacePointData::hasDynamicVariable () const inline
Definition at line 56 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 56 of file SpacePointData.hpp
References m_topStripVector.
Referenced by Acts::xyzCoordinateCheck().
SpacePointData& Acts::SpacePointData::operator= (const SpacePointData & other) delete
SpacePointData& Acts::SpacePointData::operator= (SpacePointData && other) default noexcept
float Acts::SpacePointData::quality (std::size_t idx) const inline
Getters.
Definition at line 102 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 102 of file SpacePointData.hpp
References ambiguity_solver_full_chain::idx, and m_quality.
Referenced by Acts::SeedFilter< external_spacepoint_t >::filterSeeds_1SpFixed(), and Acts::SeedFilter< external_spacepoint_t >::filterSeeds_2SpFixed().
void Acts::SpacePointData::resize (std::size_t n, bool resizeDynamic = false) inline
Resize vectors.
Definition at line 120 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 120 of file SpacePointData.hpp
References clear(), m_bottomStripVector, m_deltaR, m_quality, m_stripCenterDistance, m_topStripCenterPosition, and m_topStripVector.
Referenced by Acts::SeedFinderOrthogonal< external_spacepoint_t >::createSeeds(), and main().
void Acts::SpacePointData::setBottomStripVector (std::size_t idx, const Acts::Vector3 & value) inline
Definition at line 78 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 78 of file SpacePointData.hpp
References ambiguity_solver_full_chain::idx, m_bottomStripVector, and value.
void Acts::SpacePointData::setDeltaR (std::size_t idx, const float value) inline
Definition at line 116 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 116 of file SpacePointData.hpp
References ambiguity_solver_full_chain::idx, m_deltaR, and value.
Referenced by Acts::SeedFinder< external_spacepoint_t, platform_t >::getCompatibleDoublets(), and Acts::transformCoordinates().
void Acts::SpacePointData::setQuality (std::size_t idx, const float value) inline
Setters.
Definition at line 110 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 110 of file SpacePointData.hpp
References ambiguity_solver_full_chain::idx, m_quality, and value.
Referenced by Acts::SeedFilter< external_spacepoint_t >::filterSeeds_1SpFixed().
void Acts::SpacePointData::setStripCenterDistance (std::size_t idx, const Acts::Vector3 & value) inline
Definition at line 82 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 82 of file SpacePointData.hpp
References ambiguity_solver_full_chain::idx, m_stripCenterDistance, and value.
void Acts::SpacePointData::setTopStripCenterPosition (std::size_t idx, const Acts::Vector3 & value) inline
Definition at line 86 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 86 of file SpacePointData.hpp
References ambiguity_solver_full_chain::idx, m_topStripCenterPosition, and value.
void Acts::SpacePointData::setTopStripVector (std::size_t idx, const Acts::Vector3 & value) inline
Definition at line 74 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 74 of file SpacePointData.hpp
References ambiguity_solver_full_chain::idx, m_topStripVector, and value.
Member Data Documentation
std::vector<Acts::Vector3> Acts::SpacePointData::m_bottomStripVector {} private
Definition at line 97 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 97 of file SpacePointData.hpp
Referenced by clear(), getBottomStripVector(), resize(), and setBottomStripVector().
std::vector<float> Acts::SpacePointData::m_deltaR {} private
Definition at line 93 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 93 of file SpacePointData.hpp
Referenced by clear(), deltaR(), resize(), and setDeltaR().
std::vector<float> Acts::SpacePointData::m_quality {} private
Mutable variables.
Definition at line 92 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 92 of file SpacePointData.hpp
Referenced by clear(), quality(), resize(), and setQuality().
std::vector<Acts::Vector3> Acts::SpacePointData::m_stripCenterDistance {} private
Definition at line 98 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 98 of file SpacePointData.hpp
Referenced by clear(), getStripCenterDistance(), resize(), and setStripCenterDistance().
std::vector<Acts::Vector3> Acts::SpacePointData::m_topStripCenterPosition {} private
Definition at line 99 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 99 of file SpacePointData.hpp
Referenced by clear(), getTopStripCenterPosition(), resize(), and setTopStripCenterPosition().
std::vector<Acts::Vector3> Acts::SpacePointData::m_topStripVector {} private
dynamic variables
Definition at line 96 of file SpacePointData.hpp.
View newest version in sPHENIX GitHub at line 96 of file SpacePointData.hpp
Referenced by clear(), getTopStripVector(), hasDynamicVariable(), resize(), and setTopStripVector().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/EventData/SpacePointData.hpp