Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Detector/DetectorVolumeBuilderTests.cpp File Reference
DetectorVolumeBuilderTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Detector/DetectorComponents.hpp"
#include "Acts/Detector/DetectorVolume.hpp"
#include "Acts/Detector/DetectorVolumeBuilder.hpp"
#include "Acts/Detector/PortalGenerators.hpp"
#include "Acts/Detector/interface/IExternalStructureBuilder.hpp"
#include "Acts/Detector/interface/IGeometryIdGenerator.hpp"
#include "Acts/Detector/interface/IInternalStructureBuilder.hpp"
#include "Acts/Geometry/CylinderVolumeBounds.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Geometry/GeometryIdentifier.hpp"
#include "Acts/Navigation/DetectorVolumeFinders.hpp"
#include "Acts/Navigation/SurfaceCandidatesUpdators.hpp"
#include "Acts/Surfaces/CylinderBounds.hpp"
#include "Acts/Surfaces/CylinderSurface.hpp"
#include "Acts/Surfaces/Surface.hpp"
#include "Acts/Utilities/Logger.hpp"
#include <memory>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>
Classes
class ExternalsBuilder< bounds_type >
Mockup external structure builder.
class InternalSurfaceBuilder< surface_type, bounds_type >
Mockup internal surface builder.
class SurfaceGeoIdGenerator
class InternalVolumeBuilder< bounds_type >
Mockup internal surface builder.
Functions
BOOST_AUTO_TEST_CASE (DetectorVolumeBuilder_Misconfigured)
BOOST_AUTO_TEST_CASE (DetectorVolumeBuilder_EmptyVolume)
BOOST_AUTO_TEST_CASE (DetectorVolumeBuilder_VolumeWithSurface)
BOOST_AUTO_TEST_CASE (DetectorVolumeBuilder_VolumeWithVolume)
BOOST_AUTO_TEST_CASE (DetectorVolumeBuilder_VolumeWithVolumeToRoot)
Variables
GeometryContext tContext
Function Documentation
BOOST_AUTO_TEST_CASE (DetectorVolumeBuilder_Misconfigured)
Definition at line 138 of file DetectorVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 138 of file DetectorVolumeBuilderTests.cpp
References KFPMath::a, Acts::Experimental::DetectorVolumeBuilder::Config::auxiliary, Acts::Experimental::DetectorVolumeBuilder::Config::externalsBuilder, Acts::Experimental::DetectorVolumeBuilder::Config::internalsBuilder, and Acts::Experimental::DetectorVolumeBuilder::Config::name.
BOOST_AUTO_TEST_CASE (DetectorVolumeBuilder_EmptyVolume)
Definition at line 150 of file DetectorVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 150 of file DetectorVolumeBuilderTests.cpp
References Acts::Experimental::DetectorVolumeBuilder::Config::auxiliary, Acts::getDefaultLogger(), tContext, physmon_ckf_tracking::u, Acts::Logging::VERBOSE, and volumes.
BOOST_AUTO_TEST_CASE (DetectorVolumeBuilder_VolumeWithSurface)
Definition at line 176 of file DetectorVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 176 of file DetectorVolumeBuilderTests.cpp
References Acts::Experimental::DetectorVolumeBuilder::Config::auxiliary, Acts::getDefaultLogger(), tContext, physmon_ckf_tracking::u, Acts::Logging::VERBOSE, and volumes.
BOOST_AUTO_TEST_CASE (DetectorVolumeBuilder_VolumeWithVolume)
Definition at line 211 of file DetectorVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 211 of file DetectorVolumeBuilderTests.cpp
References Acts::Experimental::DetectorVolumeBuilder::Config::auxiliary, Acts::getDefaultLogger(), tContext, physmon_ckf_tracking::u, Acts::Logging::VERBOSE, and volumes.
BOOST_AUTO_TEST_CASE (DetectorVolumeBuilder_VolumeWithVolumeToRoot)
Definition at line 237 of file DetectorVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 237 of file DetectorVolumeBuilderTests.cpp
References Acts::Experimental::DetectorVolumeBuilder::Config::auxiliary, Acts::getDefaultLogger(), tContext, physmon_ckf_tracking::u, Acts::Logging::VERBOSE, and volumes.
Variable Documentation
GeometryContext tContext
Definition at line 38 of file DetectorVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file DetectorVolumeBuilderTests.cpp