Analysis Software: RDBC/blob/master/rdbc/TSQLResultSet.cxx File Reference
TSQLResultSet.cxx File Reference
#include <RDBC/TSQLResultSet.h>
#include <RDBC/TSQLResultSetMetaData.h>
#include <RDBC/TSQLStatement.h>
#include <TList.h>
#include <TTree.h>
#include <TBranch.h>
#include <ctype.h>
#include <time.h>
#include <iostream>
#include <stdlib.h>
Functions
ClassImpQ (TSQLResultSet) TSQLResultSet
TString GetValueFromOption (const TString &pattern, const TString &option)
void SaveAsCSV (TSQLResultSet *rs, const TString &filename)
Function Documentation
ClassImpQ (TSQLResultSet)
Definition at line 119 of file TSQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 119 of file TSQLResultSet.cxx
TString GetValueFromOption (const TString & pattern, const TString & option)
Definition at line 181 of file TSQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 181 of file TSQLResultSet.cxx
References i, str, ambiguity_solver_full_chain::t1, ambiguity_solver_full_chain::t2, and Acts::Test::tmp().
void SaveAsCSV (TSQLResultSet * rs, const TString & filename)
Definition at line 203 of file TSQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 203 of file TSQLResultSet.cxx
References fclose(), fd, TSQLResultSetMetaData::GetColumnCount(), TSQLResultSetMetaData::GetColumnName(), TSQLResultSetMetaData::GetColumnType(), TSQLResultSet::GetMetaData(), TSQLResultSet::GetString(), i, kBIGINT, kBIT, kCHAR, kDATE, kDECIMAL, kDOUBLE, kFLOAT, kINTEGER, kLONGVARBINARY, kLONGVARCHAR, kNUMERIC, kREAL, kSMALLINT, kTIME, kTIMESTAMP, kTINYINT, kVARBINARY, kVARCHAR, TSQLResultSet::Next(), str, and parse_cmake_options::type.