Analysis Software: Acts::Svg::GridConverter Namespace Reference
Acts::Svg::GridConverter Namespace Reference
Classes
struct Options
Nested Options struct.
Typedefs
using AxisBound = std::tuple< std::array< ActsScalar, 2u >, BinningValue >
Functions
template<typename grid_type >
ProtoGrid convert (const grid_type &grid, const std::array< BinningValue, grid_type::DIM > &bValues, const GridConverter::Options &cOptions)
Typedef Documentation
using Acts::Svg::GridConverter::AxisBound = typedef std::tuple<std::array<ActsScalar, 2u>, BinningValue>
Definition at line 34 of file GridSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 34 of file GridSvgConverter.hpp
Function Documentation
template<typename grid_type > ProtoGrid Acts::Svg::GridConverter::convert (const grid_type & grid, const std::array< BinningValue, grid_type::DIM > & bValues, const GridConverter::Options & cOptions)
Convert an ACTS grid into a actsvg protogrid, it currently works with
1D: [ binX ] , [ binY ], [ binR ] , [ binPhi ]
2D: [ binX, binY ], [ binZ, binPhi ], [ binR, binPhi ]
Template Parameters
grid_type is the type of the grid to be converted
Parameters
grid the grid to be converted
bValues the binning values identifying the axes
cOptions the conversion options
Returns
an ACTSVG proto grid for displaying
Definition at line 57 of file GridSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 57 of file GridSvgConverter.hpp
References Acts::binPhi, Acts::binR, Acts::binX, Acts::binY, Acts::binZ, Acts::Svg::Style::fillAndStroke(), Acts::Svg::GridConverter::Options::optionalBound, Acts::Svg::GridConverter::Options::style, swap(), and physmon_ckf_tracking::u.
Referenced by BOOST_AUTO_TEST_CASE().