Analysis Software: TestHostCuts Class Reference
TestHostCuts Class Reference
Custom selection cuts for the test, used on the host.
#include <acts/blob/sPHENIX/Tests/UnitTests/Plugins/Cuda/Seeding2/TestHostCuts.hpp>
Public Member Functions
float seedWeight (const Acts::InternalSpacePoint< TestSpacePoint > &bottom, const Acts::InternalSpacePoint< TestSpacePoint > &middle, const Acts::InternalSpacePoint< TestSpacePoint > &top) const final
bool singleSeedCut (float weight, const Acts::InternalSpacePoint< TestSpacePoint > &bottom, const Acts::InternalSpacePoint< TestSpacePoint > &, const Acts::InternalSpacePoint< TestSpacePoint > &) const final
std::vector< typename
Acts::CandidatesForMiddleSp
< const
Acts::InternalSpacePoint
< TestSpacePoint >
>::value_type > cutPerMiddleSP (std::vector< typename Acts::CandidatesForMiddleSp< const Acts::InternalSpacePoint< TestSpacePoint >>::value_type > seedCandidates) const final
Public Member Functions inherited from Acts::IExperimentCuts< TestSpacePoint >
virtual ~IExperimentCuts ()=default
Detailed Description
Custom selection cuts for the test, used on the host.
Definition at line 18 of file TestHostCuts.hpp.
View newest version in sPHENIX GitHub at line 18 of file TestHostCuts.hpp
Member Function Documentation
std::vector< typename Acts::CandidatesForMiddleSp< const Acts::InternalSpacePoint< TestSpacePoint > >::value_type > TestHostCuts::cutPerMiddleSP (std::vector< typename Acts::CandidatesForMiddleSp< const Acts::InternalSpacePoint< TestSpacePoint >>::value_type > seedCandidates) const final virtual
Parameters
seedCandidates contains collection of seed candidates created for one middle space point in a std::tuple format
Returns
vector of seed candidates that pass the cut
Implements Acts::IExperimentCuts< TestSpacePoint >.
Definition at line 35 of file TestHostCuts.cpp.
View newest version in sPHENIX GitHub at line 35 of file TestHostCuts.cpp
References i, Acts::UnitConstants::min, and testing::internal::move().
float TestHostCuts::seedWeight (const Acts::InternalSpacePoint< TestSpacePoint > & bottom, const Acts::InternalSpacePoint< TestSpacePoint > & middle, const Acts::InternalSpacePoint< TestSpacePoint > & top) const final virtual
Returns seed weight bonus/malus depending on detector considerations.
Parameters
bottom bottom space point of the current seed
middle middle space point of the current seed
top top space point of the current seed
Returns
seed weight to be added to the seed's weight
Implements Acts::IExperimentCuts< TestSpacePoint >.
Definition at line 12 of file TestHostCuts.cpp.
View newest version in sPHENIX GitHub at line 12 of file TestHostCuts.cpp
References Acts::InternalSpacePoint< SpacePoint >::radius().
bool TestHostCuts::singleSeedCut (float weight, const Acts::InternalSpacePoint< TestSpacePoint > & bottom, const Acts::InternalSpacePoint< TestSpacePoint > & , const Acts::InternalSpacePoint< TestSpacePoint > &) const final virtual
Parameters
weight the current seed weight
bottom bottom space point of the current seed
middle middle space point of the current seed
top top space point of the current seed
Returns
true if the seed should be kept, false if the seed should be discarded
Implements Acts::IExperimentCuts< TestSpacePoint >.
Definition at line 26 of file TestHostCuts.cpp.
View newest version in sPHENIX GitHub at line 26 of file TestHostCuts.cpp
References Acts::InternalSpacePoint< SpacePoint >::radius().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Tests/UnitTests/Plugins/Cuda/Seeding2/TestHostCuts.hpp
acts/blob/sPHENIX/Tests/UnitTests/Plugins/Cuda/Seeding2/TestHostCuts.cpp