Analysis Software: SurfaceFinder Class Reference
SurfaceFinder Class Reference
#include <JETSCAPE/blob/main/external_packages/hydro_from_external_file/SurfaceFinder.h>
Public Member Functions
SurfaceFinder (void *hydroinfo_ptr_in, ParameterReader *paraRdr_in)
SurfaceFinder (void *hydroinfo_ptr_in, ParameterReader *paraRdr_in, double T_cut_in)
~SurfaceFinder ()
bool check_intersect (double T_cut, double tau, double x, double y, double dt, double dx, double dy, double ***cube)
int Find_full_hypersurface ()
Private Attributes
int hydro_type
Hydroinfo_MUSIC * hydroinfo_MUSIC_ptr
ParameterReader * paraRdr
double T_cut
Detailed Description
Definition at line 21 of file SurfaceFinder.h.
View newest version in sPHENIX GitHub at line 21 of file SurfaceFinder.h
Constructor & Destructor Documentation
SurfaceFinder::SurfaceFinder (void * hydroinfo_ptr_in, ParameterReader * paraRdr_in)
Definition at line 15 of file SurfaceFinder.cpp.
View newest version in sPHENIX GitHub at line 15 of file SurfaceFinder.cpp
References ParameterReader::getVal().
SurfaceFinder::SurfaceFinder (void * hydroinfo_ptr_in, ParameterReader * paraRdr_in, double T_cut_in)
Definition at line 29 of file SurfaceFinder.cpp.
View newest version in sPHENIX GitHub at line 29 of file SurfaceFinder.cpp
References ParameterReader::getVal().
SurfaceFinder::~SurfaceFinder ()
Definition at line 43 of file SurfaceFinder.cpp.
View newest version in sPHENIX GitHub at line 43 of file SurfaceFinder.cpp
Member Function Documentation
bool SurfaceFinder::check_intersect (double T_cut, double tau, double x, double y, double dt, double dx, double dy, double *** cube)
Definition at line 45 of file SurfaceFinder.cpp.
View newest version in sPHENIX GitHub at line 45 of file SurfaceFinder.cpp
References Acts::PlanarHelper::intersect(), and hydrofluidCell::temperature.
int SurfaceFinder::Find_full_hypersurface ()
Definition at line 141 of file SurfaceFinder.cpp.
View newest version in sPHENIX GitHub at line 141 of file SurfaceFinder.cpp
References Acts::Test::dim, Cornelius::find_surface_3d(), Cornelius::get_centroid_elem(), Cornelius::get_Nelements(), Cornelius::get_normal_elem(), i, Cornelius::init(), Acts::PlanarHelper::intersect(), j, k, nx, ny, check_smearing_config::output, hydrofluidCell::temperature, hydrofluidCell::vx, and hydrofluidCell::vy.
Referenced by FluidcellStatistic::calculate_hypersurface_3volume(), and Jetscape::FluidDynamics::FindAConstantTemperatureSurface().
Member Data Documentation
int SurfaceFinder::hydro_type private
Definition at line 23 of file SurfaceFinder.h.
View newest version in sPHENIX GitHub at line 23 of file SurfaceFinder.h
Hydroinfo_MUSIC* SurfaceFinder::hydroinfo_MUSIC_ptr private
Definition at line 27 of file SurfaceFinder.h.
View newest version in sPHENIX GitHub at line 27 of file SurfaceFinder.h
ParameterReader* SurfaceFinder::paraRdr private
Definition at line 28 of file SurfaceFinder.h.
View newest version in sPHENIX GitHub at line 28 of file SurfaceFinder.h
double SurfaceFinder::T_cut private
Definition at line 29 of file SurfaceFinder.h.
View newest version in sPHENIX GitHub at line 29 of file SurfaceFinder.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/hydro_from_external_file/SurfaceFinder.h
JETSCAPE/blob/main/external_packages/hydro_from_external_file/SurfaceFinder.cpp