Analysis Software: SvtxTruthEval Class Reference
SvtxTruthEval Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxTruthEval.h>
Public Member Functions
SvtxTruthEval (PHCompositeNode *topNode)
virtual ~SvtxTruthEval ()
void next_event (PHCompositeNode *topNode)
void do_caching (bool do_cache)
void set_strict (bool strict)
void set_verbosity (int verbosity)
std::set< PHG4Hit * > all_truth_hits ()
std::set< PHG4Hit * > all_truth_hits (PHG4Particle *particle)
PHG4Particle * get_particle (PHG4Hit *g4hit)
int get_embed (PHG4Particle *particle)
PHG4VtxPoint * get_vertex (PHG4Particle *particle)
bool is_primary (PHG4Particle *particle)
PHG4Particle * get_primary_particle (PHG4Hit *g4hit)
PHG4Particle * get_primary_particle (PHG4Particle *particle)
PHG4Particle * get_particle (const int trackid)
std::map< TrkrDefs::cluskey,
std::shared_ptr< TrkrCluster > > all_truth_clusters (PHG4Particle *particle)
bool is_g4hit_from_particle (PHG4Hit *g4hit, PHG4Particle *particle)
bool are_same_particle (PHG4Particle *p1, PHG4Particle *p2)
bool are_same_vertex (PHG4VtxPoint *vtx1, PHG4VtxPoint *vtx2)
PHG4Hit * get_innermost_truth_hit (PHG4Particle *particle)
PHG4Hit * get_outermost_truth_hit (PHG4Particle *particle)
unsigned int get_errors ()
std::set< PHG4Hit * > get_truth_hits_from_truth_cluster (TrkrDefs::cluskey ckey)
void FillTruthHitsFromParticleCache ()
Private Member Functions
void get_node_pointers (PHCompositeNode *topNode)
bool has_node_pointers ()
void LayerClusterG4Hits (const std::set< PHG4Hit * > &truth_hits, std::vector< PHG4Hit * > &contributing_hits, std::vector< double > &contributing_hits_energy, std::vector< std::vector< double >> &contributing_hits_entry, std::vector< std::vector< double >> &contributing_hits_exit, float layer, float &x, float &y, float &z, float &t, float &e)
float line_circle_intersection (float x[], float y[], float z[], float radius)
void G4ClusterSize (TrkrDefs::cluskey ckey, unsigned int layer, std::vector< std::vector< double >> contributing_hits_entry, std::vector< std::vector< double >> contributing_hits_exit, float &g4phisize, float &g4zsize)
unsigned int getAdcValue (double gedep)
Private Attributes
BaseTruthEval _basetrutheval
PHG4TruthInfoContainer * _truthinfo = nullptr
PHG4HitContainer * _g4hits_svtx = nullptr
PHG4HitContainer * _g4hits_mms = nullptr
PHG4HitContainer * _g4hits_tracker = nullptr
PHG4HitContainer * _g4hits_maps = nullptr
PHG4TpcCylinderGeomContainer * _tpc_geom_container {}
PHG4CylinderGeomContainer * _intt_geom_container {}
PHG4CylinderGeomContainer * _mvtx_geom_container {}
PHG4CylinderGeomContainer * _mms_geom_container {}
ActsGeometry * _tgeometry = nullptr
bool _strict = false
int _verbosity = 0
unsigned int _errors = 0
unsigned long iclus = 0
const unsigned int _nlayers_maps = 3
const unsigned int _nlayers_intt = 4
const unsigned int _nlayers_tpc = 48
const unsigned int _nlayers_mms = 2
std::multimap
< TrkrDefs::cluskey, PHG4Hit * > _truth_cluster_truth_hit_map
bool _do_cache = true
std::set< PHG4Hit * > _cache_all_truth_hits
std::map< PHG4Particle
*, std::set< PHG4Hit * > > _cache_all_truth_hits_g4particle
std::map< PHG4Particle
*, std::map< TrkrDefs::cluskey,
std::shared_ptr< TrkrCluster > > > _cache_all_truth_clusters_g4particle
std::map< PHG4Particle
*, PHG4Hit * > _cache_get_innermost_truth_hit
std::map< PHG4Particle
*, PHG4Hit * > _cache_get_outermost_truth_hit
std::map< PHG4Hit
*, PHG4Particle * > _cache_get_primary_particle_g4hit
Detailed Description
Definition at line 25 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 25 of file SvtxTruthEval.h
Constructor & Destructor Documentation
SvtxTruthEval::SvtxTruthEval (PHCompositeNode * topNode)
Definition at line 42 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 42 of file SvtxTruthEval.cc
References get_node_pointers().
SvtxTruthEval::~SvtxTruthEval () virtual
Definition at line 48 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 48 of file SvtxTruthEval.cc
References _errors, and _verbosity.
Member Function Documentation
std::map< TrkrDefs::cluskey, std::shared_ptr< TrkrCluster > > SvtxTruthEval::all_truth_clusters (PHG4Particle * particle)
Definition at line 258 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 258 of file SvtxTruthEval.cc
References _cache_all_truth_clusters_g4particle, _do_cache, _errors, _nlayers_intt, _nlayers_maps, _nlayers_mms, _nlayers_tpc, _strict, _truth_cluster_truth_hit_map, _verbosity, all_truth_hits(), assert, G4ClusterSize(), TrkrDefs::genClusKey(), TpcDefs::genClusKey(), InttDefs::genClusKey(), MvtxDefs::genClusKey(), MicromegasDefs::genHitSetKey(), PHG4Particle::get_track_id(), getAdcValue(), gx, gy, gz, has_node_pointers(), iclus, layer, LayerClusterG4Hits(), ng4hits, PHWHERE, PHG4InttDefs::SEGMENTATION_PHI, and tile().
Referenced by QAG4SimulationMicromegas::evaluate_clusters(), QAG4SimulationTpc::evaluate_clusters(), SvtxEvaluator::fillOutputNtuples(), SvtxClusterEval::max_truth_cluster_by_energy(), and SvtxClusterEval::max_truth_particle_by_cluster_energy().
std::set< PHG4Hit * > SvtxTruthEval::all_truth_hits ()
Definition at line 74 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 74 of file SvtxTruthEval.cc
References _cache_all_truth_hits, _do_cache, _errors, _g4hits_maps, _g4hits_mms, _g4hits_svtx, _g4hits_tracker, PHG4HitContainer::getHits(), and has_node_pointers().
Referenced by all_truth_clusters(), JetTruthEval::all_truth_hits(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), get_innermost_truth_hit(), get_outermost_truth_hit(), SvtxEvaluatorHaiwang::printInputInfo(), psTOFTimezeroEval::printInputInfo(), SvtxEvaluator::printInputInfo(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), SvtxEvaluator::printOutputInfo(), SvtxSimPerformanceCheckReco::process_event(), TrackingPerformanceCheck::process_event(), RecoInfoExport::process_event(), SimpleTrackingAnalysis::process_event(), and STACalorimeterCharacterization::process_event().
std::set< PHG4Hit * > SvtxTruthEval::all_truth_hits (PHG4Particle * particle)
Definition at line 151 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 151 of file SvtxTruthEval.cc
References _cache_all_truth_hits_g4particle, _do_cache, _errors, _strict, assert, FillTruthHitsFromParticleCache(), and has_node_pointers().
bool SvtxTruthEval::are_same_particle (PHG4Particle * p1, PHG4Particle * p2)
Definition at line 1115 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 1115 of file SvtxTruthEval.cc
References _basetrutheval, and BaseTruthEval::are_same_particle().
bool SvtxTruthEval::are_same_vertex (PHG4VtxPoint * vtx1, PHG4VtxPoint * vtx2)
Definition at line 1120 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 1120 of file SvtxTruthEval.cc
References _basetrutheval, and BaseTruthEval::are_same_vertex().
void SvtxTruthEval::do_caching (bool do_cache) inline
Definition at line 32 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 32 of file SvtxTruthEval.h
References _do_cache.
Referenced by SvtxHitEval::do_caching().
void SvtxTruthEval::FillTruthHitsFromParticleCache ()
Definition at line 189 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 189 of file SvtxTruthEval.cc
References _cache_all_truth_hits_g4particle, _g4hits_maps, _g4hits_mms, _g4hits_svtx, _g4hits_tracker, _truthinfo, PHG4Particle::get_track_id(), PHG4Hit::get_trkid(), PHG4HitContainer::getHits(), and PHG4TruthInfoContainer::GetParticleRange().
Referenced by all_truth_hits().
void SvtxTruthEval::G4ClusterSize (TrkrDefs::cluskey ckey, unsigned int layer, std::vector< std::vector< double >> contributing_hits_entry, std::vector< std::vector< double >> contributing_hits_exit, float & g4phisize, float & g4zsize) private
Definition at line 698 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 698 of file SvtxTruthEval.cc
References _intt_geom_container, _mvtx_geom_container, _tgeometry, _tpc_geom_container, double(), Acts::UnitConstants::e, CylinderGeomIntt::find_indices_from_world_location(), CylinderGeomIntt::find_strip_index_values(), CylinderGeom_Mvtx::get_local_from_world_coords(), CylinderGeomIntt::get_local_from_world_coords(), PHG4TpcCylinderGeom::get_phibin(), PHG4TpcCylinderGeom::get_phistep(), CylinderGeom_Mvtx::get_pixel_from_local_coords(), CylinderGeom_Mvtx::get_pixel_x(), CylinderGeom_Mvtx::get_pixel_z(), PHG4TpcCylinderGeom::get_radius(), CylinderGeom_Mvtx::get_sensor_indices_from_world_coords(), CylinderGeomIntt::get_strip_y_spacing(), CylinderGeomIntt::get_strip_z_spacing(), PHG4TpcCylinderGeom::get_zbin(), PHG4TpcCylinderGeom::get_zstep(), TrkrDefs::getHitSetKeyFromClusKey(), PHG4TpcCylinderGeomContainer::GetLayerCellGeom(), PHG4CylinderGeomContainer::GetLayerGeom(), ActsSurfaceMaps::getSiliconSurface(), G4CEMCALBEDO::inner_radius, ActsGeometry::maps(), G4HCALOUT::outer_radius, parse_cmake_options::rows, surf(), and swap().
Referenced by all_truth_clusters().
int SvtxTruthEval::get_embed (PHG4Particle * particle)
Definition at line 1038 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 1038 of file SvtxTruthEval.cc
References _basetrutheval, and BaseTruthEval::get_embed().
Referenced by EMCalCalib::eval_photon(), EMCalAna::eval_trk(), QAG4SimulationMicromegas::evaluate_clusters(), QAG4SimulationTpc::evaluate_clusters(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), SvtxSimPerformanceCheckReco::process_event(), QAG4SimulationUpsilon::process_event(), SimpleTrackingAnalysis::process_event(), STACalorimeterCharacterization::process_event(), QAG4SimulationTracking::process_event(), TrackClusterEvaluator::processRecoTracks(), and TrackClusterEvaluator::processTruthTracks().
unsigned int SvtxTruthEval::get_errors () inline
Definition at line 63 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 63 of file SvtxTruthEval.h
References _basetrutheval, _errors, and BaseTruthEval::get_errors().
Referenced by SvtxHitEval::get_errors().
PHG4Hit * SvtxTruthEval::get_innermost_truth_hit (PHG4Particle * particle)
Definition at line 945 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 945 of file SvtxTruthEval.cc
References _errors, _strict, all_truth_hits(), assert, has_node_pointers(), physmon_track_finding_ttbar::r, ambiguity_solver_full_chain::x, and y.
void SvtxTruthEval::get_node_pointers (PHCompositeNode * topNode) private
Definition at line 1125 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 1125 of file SvtxTruthEval.cc
References _g4hits_maps, _g4hits_mms, _g4hits_svtx, _g4hits_tracker, _intt_geom_container, _mms_geom_container, _mvtx_geom_container, _tgeometry, _tpc_geom_container, and _truthinfo.
Referenced by next_event(), and SvtxTruthEval().
PHG4Hit * SvtxTruthEval::get_outermost_truth_hit (PHG4Particle * particle)
Definition at line 982 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 982 of file SvtxTruthEval.cc
References _cache_get_outermost_truth_hit, _do_cache, _errors, _strict, all_truth_hits(), assert, has_node_pointers(), physmon_track_finding_ttbar::r, ambiguity_solver_full_chain::x, and y.
Referenced by EMCalCalib::eval_photon(), EMCalAna::eval_trk(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), and SvtxEvaluator::fillOutputNtuples().
PHG4Particle * SvtxTruthEval::get_particle (PHG4Hit * g4hit)
Definition at line 1033 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 1033 of file SvtxTruthEval.cc
References _basetrutheval, and BaseTruthEval::get_particle().
Referenced by SvtxHitEval::all_truth_particles(), SvtxClusterEval::all_truth_particles(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), SvtxTrackEval::max_truth_particle_by_nclusters(), and TPCMLDataInterface::process_event().
PHG4Particle * SvtxTruthEval::get_particle (const int trackid)
Definition at line 1105 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 1105 of file SvtxTruthEval.cc
References _basetrutheval, and BaseTruthEval::get_particle().
PHG4Particle * SvtxTruthEval::get_primary_particle (PHG4Hit * g4hit)
Definition at line 1053 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 1053 of file SvtxTruthEval.cc
References _basetrutheval, _cache_get_primary_particle_g4hit, _do_cache, _errors, _strict, assert, BaseTruthEval::get_primary_particle(), and has_node_pointers().
PHG4Particle * SvtxTruthEval::get_primary_particle (PHG4Particle * particle)
Definition at line 1100 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 1100 of file SvtxTruthEval.cc
References _basetrutheval, and BaseTruthEval::get_primary_particle().
std::set< PHG4Hit * > SvtxTruthEval::get_truth_hits_from_truth_cluster (TrkrDefs::cluskey ckey)
Definition at line 929 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 929 of file SvtxTruthEval.cc
References _truth_cluster_truth_hit_map.
Referenced by SvtxClusterEval::reco_cluster_from_truth_cluster().
PHG4VtxPoint * SvtxTruthEval::get_vertex (PHG4Particle * particle)
Definition at line 1043 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 1043 of file SvtxTruthEval.cc
References _basetrutheval, and BaseTruthEval::get_vertex().
Referenced by LeptoquarksReco::AddTrackInformation(), SvtxVertexEval::all_truth_points(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), AnaSvtxTracksForGenFit::fill_tree(), ActsEvaluator::fillG4Particle(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), KFParticle_truthAndDetTools::fillTruthBranch(), SvtxVertexEval::get_ntracks_contribution(), TrackClusterEvaluator::processRecoTracks(), and TrackClusterEvaluator::processTruthTracks().
unsigned int SvtxTruthEval::getAdcValue (double gedep) private
Definition at line 1207 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 1207 of file SvtxTruthEval.cc
References CF4_dEdx, CF4_NTotal, Ne_dEdx, and Ne_NTotal.
Referenced by all_truth_clusters().
bool SvtxTruthEval::has_node_pointers () private
Definition at line 1143 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 1143 of file SvtxTruthEval.cc
References _g4hits_maps, _g4hits_mms, _g4hits_svtx, _g4hits_tracker, _strict, _truthinfo, and assert.
Referenced by all_truth_clusters(), all_truth_hits(), get_innermost_truth_hit(), get_outermost_truth_hit(), and get_primary_particle().
bool SvtxTruthEval::is_g4hit_from_particle (PHG4Hit * g4hit, PHG4Particle * particle)
Definition at line 1110 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 1110 of file SvtxTruthEval.cc
References _basetrutheval, and BaseTruthEval::is_g4hit_from_particle().
bool SvtxTruthEval::is_primary (PHG4Particle * particle)
Definition at line 1048 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 1048 of file SvtxTruthEval.cc
References _basetrutheval, and BaseTruthEval::is_primary().
Referenced by QAG4SimulationMicromegas::evaluate_clusters(), QAG4SimulationTpc::evaluate_clusters(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), TrackClusterEvaluator::processRecoTracks(), and TrackClusterEvaluator::processTruthTracks().
void SvtxTruthEval::LayerClusterG4Hits (const std::set< PHG4Hit * > & truth_hits, std::vector< PHG4Hit * > & contributing_hits, std::vector< double > & contributing_hits_energy, std::vector< std::vector< double >> & contributing_hits_entry, std::vector< std::vector< double >> & contributing_hits_exit, float layer, float & x, float & y, float & z, float & t, float & e) private
Definition at line 417 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 417 of file SvtxTruthEval.cc
References _nlayers_intt, _nlayers_maps, _nlayers_tpc, _tpc_geom_container, _verbosity, PHG4TpcCylinderGeom::get_radius(), PHG4TpcCylinderGeom::get_thickness(), PHG4TpcCylinderGeomContainer::GetLayerCellGeom(), gr, gx, gy, gz, line_circle_intersection(), and swap().
Referenced by all_truth_clusters().
float SvtxTruthEval::line_circle_intersection (float x[], float y[], float z[], float radius) private
Definition at line 1166 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 1166 of file SvtxTruthEval.cc
References A, C, Acts::UnitConstants::e, PHWHERE, and t.
Referenced by LayerClusterG4Hits().
void SvtxTruthEval::next_event (PHCompositeNode * topNode)
Definition at line 59 of file SvtxTruthEval.cc.
View newest version in sPHENIX GitHub at line 59 of file SvtxTruthEval.cc
References _basetrutheval, _cache_all_truth_clusters_g4particle, _cache_all_truth_hits, _cache_all_truth_hits_g4particle, _cache_get_innermost_truth_hit, _cache_get_outermost_truth_hit, _cache_get_primary_particle_g4hit, get_node_pointers(), and BaseTruthEval::next_event().
Referenced by SvtxHitEval::next_event().
void SvtxTruthEval::set_strict (bool strict) inline
Definition at line 33 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 33 of file SvtxTruthEval.h
References _basetrutheval, _strict, and BaseTruthEval::set_strict().
Referenced by psTOFTimezeroEval::printInputInfo(), SvtxEvaluatorHaiwang::printInputInfo(), SvtxEvaluator::printInputInfo(), and SvtxHitEval::set_strict().
void SvtxTruthEval::set_verbosity (int verbosity) inline
Definition at line 38 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 38 of file SvtxTruthEval.h
References _basetrutheval, _verbosity, BaseTruthEval::set_verbosity(), and verbosity.
Referenced by SvtxHitEval::set_verbosity().
Member Data Documentation
BaseTruthEval SvtxTruthEval::_basetrutheval private
Definition at line 80 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 80 of file SvtxTruthEval.h
Referenced by are_same_particle(), are_same_vertex(), get_embed(), get_errors(), get_particle(), get_primary_particle(), get_vertex(), is_g4hit_from_particle(), is_primary(), next_event(), set_strict(), and set_verbosity().
std::map<PHG4Particle*, std::map<TrkrDefs::cluskey, std::shared_ptr<TrkrCluster> > > SvtxTruthEval::_cache_all_truth_clusters_g4particle private
Definition at line 109 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 109 of file SvtxTruthEval.h
Referenced by all_truth_clusters(), and next_event().
std::set<PHG4Hit*> SvtxTruthEval::_cache_all_truth_hits private
Definition at line 107 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 107 of file SvtxTruthEval.h
Referenced by all_truth_hits(), and next_event().
std::map<PHG4Particle*, std::set<PHG4Hit*> > SvtxTruthEval::_cache_all_truth_hits_g4particle private
Definition at line 108 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 108 of file SvtxTruthEval.h
Referenced by all_truth_hits(), FillTruthHitsFromParticleCache(), and next_event().
std::map<PHG4Particle*, PHG4Hit*> SvtxTruthEval::_cache_get_innermost_truth_hit private
Definition at line 110 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 110 of file SvtxTruthEval.h
Referenced by next_event().
std::map<PHG4Particle*, PHG4Hit*> SvtxTruthEval::_cache_get_outermost_truth_hit private
Definition at line 111 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 111 of file SvtxTruthEval.h
Referenced by get_outermost_truth_hit(), and next_event().
std::map<PHG4Hit*, PHG4Particle*> SvtxTruthEval::_cache_get_primary_particle_g4hit private
Definition at line 112 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 112 of file SvtxTruthEval.h
Referenced by get_primary_particle(), and next_event().
bool SvtxTruthEval::_do_cache = true private
Definition at line 106 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 106 of file SvtxTruthEval.h
Referenced by all_truth_clusters(), all_truth_hits(), do_caching(), get_outermost_truth_hit(), and get_primary_particle().
unsigned int SvtxTruthEval::_errors = 0 private
Definition at line 96 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 96 of file SvtxTruthEval.h
Referenced by all_truth_clusters(), all_truth_hits(), get_errors(), get_innermost_truth_hit(), get_outermost_truth_hit(), get_primary_particle(), and ~SvtxTruthEval().
PHG4HitContainer* SvtxTruthEval::_g4hits_maps = nullptr private
Definition at line 86 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 86 of file SvtxTruthEval.h
Referenced by all_truth_hits(), FillTruthHitsFromParticleCache(), get_node_pointers(), and has_node_pointers().
PHG4HitContainer* SvtxTruthEval::_g4hits_mms = nullptr private
Definition at line 84 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 84 of file SvtxTruthEval.h
Referenced by all_truth_hits(), FillTruthHitsFromParticleCache(), get_node_pointers(), and has_node_pointers().
PHG4HitContainer* SvtxTruthEval::_g4hits_svtx = nullptr private
Definition at line 83 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 83 of file SvtxTruthEval.h
Referenced by all_truth_hits(), FillTruthHitsFromParticleCache(), get_node_pointers(), and has_node_pointers().
PHG4HitContainer* SvtxTruthEval::_g4hits_tracker = nullptr private
Definition at line 85 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 85 of file SvtxTruthEval.h
Referenced by all_truth_hits(), FillTruthHitsFromParticleCache(), get_node_pointers(), and has_node_pointers().
PHG4CylinderGeomContainer* SvtxTruthEval::_intt_geom_container {} private
Definition at line 89 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 89 of file SvtxTruthEval.h
Referenced by G4ClusterSize(), and get_node_pointers().
PHG4CylinderGeomContainer* SvtxTruthEval::_mms_geom_container {} private
Definition at line 91 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 91 of file SvtxTruthEval.h
Referenced by get_node_pointers().
PHG4CylinderGeomContainer* SvtxTruthEval::_mvtx_geom_container {} private
Definition at line 90 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 90 of file SvtxTruthEval.h
Referenced by G4ClusterSize(), and get_node_pointers().
const unsigned int SvtxTruthEval::_nlayers_intt = 4 private
Definition at line 100 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 100 of file SvtxTruthEval.h
Referenced by all_truth_clusters(), and LayerClusterG4Hits().
const unsigned int SvtxTruthEval::_nlayers_maps = 3 private
Definition at line 99 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 99 of file SvtxTruthEval.h
Referenced by all_truth_clusters(), and LayerClusterG4Hits().
const unsigned int SvtxTruthEval::_nlayers_mms = 2 private
Definition at line 102 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 102 of file SvtxTruthEval.h
Referenced by all_truth_clusters().
const unsigned int SvtxTruthEval::_nlayers_tpc = 48 private
Definition at line 101 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 101 of file SvtxTruthEval.h
Referenced by all_truth_clusters(), and LayerClusterG4Hits().
bool SvtxTruthEval::_strict = false private
Definition at line 94 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 94 of file SvtxTruthEval.h
Referenced by all_truth_clusters(), all_truth_hits(), get_innermost_truth_hit(), get_outermost_truth_hit(), get_primary_particle(), has_node_pointers(), and set_strict().
ActsGeometry* SvtxTruthEval::_tgeometry = nullptr private
Definition at line 92 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 92 of file SvtxTruthEval.h
Referenced by G4ClusterSize(), and get_node_pointers().
PHG4TpcCylinderGeomContainer* SvtxTruthEval::_tpc_geom_container {} private
Definition at line 88 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 88 of file SvtxTruthEval.h
Referenced by G4ClusterSize(), get_node_pointers(), and LayerClusterG4Hits().
std::multimap<TrkrDefs::cluskey, PHG4Hit*> SvtxTruthEval::_truth_cluster_truth_hit_map private
Definition at line 104 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 104 of file SvtxTruthEval.h
Referenced by all_truth_clusters(), and get_truth_hits_from_truth_cluster().
PHG4TruthInfoContainer* SvtxTruthEval::_truthinfo = nullptr private
Definition at line 82 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 82 of file SvtxTruthEval.h
Referenced by FillTruthHitsFromParticleCache(), get_node_pointers(), and has_node_pointers().
int SvtxTruthEval::_verbosity = 0 private
Definition at line 95 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 95 of file SvtxTruthEval.h
Referenced by all_truth_clusters(), LayerClusterG4Hits(), set_verbosity(), and ~SvtxTruthEval().
unsigned long SvtxTruthEval::iclus = 0 private
Definition at line 97 of file SvtxTruthEval.h.
View newest version in sPHENIX GitHub at line 97 of file SvtxTruthEval.h
Referenced by all_truth_clusters().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxTruthEval.h
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxTruthEval.cc