Analysis Software: JETSCAPE/blob/main/jail/vhlle/src/hdo.cpp File Reference
hdo.cpp File Reference
#include <iostream>
#include <fstream>
#include <iomanip>
#include <algorithm>
#include <unistd.h>
#include "hdo.h"
#include "inc.h"
#include "rmn.h"
#include "fld.h"
#include "eos.h"
#include "cll.h"
#include "trancoeff.h"
Functions
double sign (double x)
Variables
bool debugRiemann
Function Documentation
double sign (double x)
Definition at line 36 of file hdo.cpp.
View newest version in sPHENIX GitHub at line 36 of file hdo.cpp
Referenced by ConstructGeometry(), Acts::Svg::PortalConverter::convert(), Matter::DoEnergyLoss(), doinstatescat(), dokinematics(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::get3DLifetimeSignOfTrack(), gbl::GblTrajectory::getFitToLocalJacobian(), Hydro::ISformal(), line_circle(), lucell(), luedit(), lustrf(), lutabu(), luthru(), lux3jt(), luxdif(), luxkfl(), luxtot(), main(), odeint(), plu(), FullJetFinder::process_event(), pyangl(), pyapps(), pycell(), pycjdc(), pydocu(), pyedit(), pygaga(), pyglui(), pyhiklim(), pyhiremn(), pyhiresd(), pyhisigh(), pyhispen(), pyhitest(), pyhithia(), pyhiwidt(), pyinbm(), pyinki(), pyinom(), pyklim(), pymsin(), pynjdc(), pyp(), pyplot(), pyptfs(), pyrand(), pyremn(), pyresd(), pyscat(), pysfdc(), pysgex(), pysghg(), pysgqc(), pysgsu(), pysgtc(), pysgwz(), pyshow(), pyslha(), pyspen(), pystrf(), pytabu(), pytbdy(), pytest(), pythrg(), pythru(), pywidt(), pywidx(), pyx3jt(), pyxdif(), pyxkfl(), pyxtee(), genfit::MplTrackRep::RKPropagate(), PHG4HcalSubsystem::SetTiltViaNcross(), PHG4HcalPrototypeDetector::SetTiltViaNcross(), ulangl(), and Acts::SeedFinderOrthogonal< external_spacepoint_t >::validTuple().
Variable Documentation
bool debugRiemann
Definition at line 13 of file rmn.cpp.
View newest version in sPHENIX GitHub at line 13 of file rmn.cpp
Referenced by Hydro::hlle_flux(), Hydro::performStep(), transformPV(), and transformPVBulk().