Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/EventData/CurvilinearTrackParametersTests.cpp File Reference
CurvilinearTrackParametersTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Definitions/Common.hpp"
#include "Acts/Definitions/TrackParametrization.hpp"
#include "Acts/Definitions/Units.hpp"
#include "Acts/EventData/Charge.hpp"
#include "Acts/EventData/GenericCurvilinearTrackParameters.hpp"
#include "Acts/EventData/TrackParameters.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Utilities/UnitVectors.hpp"
#include "Acts/Utilities/detail/periodic.hpp"
#include <cmath>
#include <limits>
#include <optional>
#include <utility>
#include <vector>
#include "TrackParametersDatasets.hpp"
Functions
BOOST_DATA_TEST_CASE (NeutralConstruct, posSymmetric *posSymmetric *posSymmetric *ts *phis *thetas *ps, x, y, z, time, phiInput, theta, p)
BOOST_DATA_TEST_CASE (ChargedConstruct, posSymmetric *posSymmetric *posSymmetric *ts *phis *thetas *ps *qsNonZero, x, y, z, time, phiInput, theta, p, q)
BOOST_DATA_TEST_CASE (AnyConstruct, posSymmetric *posSymmetric *posSymmetric *ts *phis *thetas *ps *qsAny, x, y, z, time, phiInput, theta, p, q)
Function Documentation
BOOST_DATA_TEST_CASE (NeutralConstruct , posSymmetric *posSymmetric *posSymmetric *ts *phis *thetas * ps, x , y , z , time , phiInput , theta , p)
Definition at line 76 of file CurvilinearTrackParametersTests.cpp.
View newest version in sPHENIX GitHub at line 76 of file CurvilinearTrackParametersTests.cpp
References Acts::Test::cov, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::covariance(), Acts::makeDirectionFromPhiTheta(), Acts::ParticleHypothesis::pion0(), Acts::Test::pos4(), and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (ChargedConstruct , posSymmetric *posSymmetric *posSymmetric *ts *phis *thetas *ps * qsNonZero, x , y , z , time , phiInput , theta , p , q)
Definition at line 97 of file CurvilinearTrackParametersTests.cpp.
View newest version in sPHENIX GitHub at line 97 of file CurvilinearTrackParametersTests.cpp
References Acts::Test::cov, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::covariance(), Acts::makeDirectionFromPhiTheta(), Acts::ParticleHypothesis::pionLike(), Acts::Test::pos4(), ActsTests::PropagationDatasets::theta, Acts::Test::time, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
BOOST_DATA_TEST_CASE (AnyConstruct , posSymmetric *posSymmetric *posSymmetric *ts *phis *thetas *ps * qsAny, x , y , z , time , phiInput , theta , p , q)
Definition at line 118 of file CurvilinearTrackParametersTests.cpp.
View newest version in sPHENIX GitHub at line 118 of file CurvilinearTrackParametersTests.cpp
References Acts::Test::cov, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::covariance(), Acts::makeDirectionFromPhiTheta(), particleHypothesis, Acts::ParticleHypothesis::pionLike(), Acts::Test::pos4(), ActsTests::PropagationDatasets::theta, Acts::Test::time, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.