Analysis Software: JetContainerv1 Class Reference
JetContainerv1 Class Reference
#include <coresoftware/blob/master/offline/packages/jetbase/JetContainerv1.h>
Public Member Functions
JetContainerv1 ()
~JetContainerv1 () override
void identify (std::ostream &os=std::cout) const override
JetContainerv1 (const JetContainer &jets)
JetContainerv1 & operator= (const JetContainer &jets)
void Reset () override
Clear Event.
TClonesArray * clone_data () const override
bool empty () const override
size_t size () const override
Jet * add_jet () override
Jet * get_jet (unsigned int index) override
Jet * get_UncheckedAt (unsigned int index) override
Jet * operator() (int index) override
Jet * operator[] (int index) override
std::map< Jet::PROPERTY,
Jet::PROPERTY > property_indices () const override
bool has_property (Jet::PROPERTY prop) const override
size_t size_properties () const override
size_t add_property (Jet::PROPERTY) override
size_t add_property (std::set< Jet::PROPERTY >) override
virtual Jet::PROPERTY property_index (Jet::PROPERTY) override
void print_property_types (std::ostream &os=std::cout) const override
Jet::IterJetTCA begin () override
Jet::IterJetTCA end () override
void set_algo (Jet::ALGO algo) override
Jet::ALGO get_algo () const override
void set_par (float par) override
float get_par () const override
void set_jetpar_R (float par) override
float get_jetpar_R () const override
bool empty_src () const override
void insert_src (Jet::SRC src) override
ConstSrcIter begin_src () const override
ConstSrcIter find_src (Jet::SRC src) const override
ConstSrcIter end_src () const override
SrcIter begin_src () override
SrcIter find_src (Jet::SRC src) override
SrcIter end_src () override
void print_jets (std::ostream &) override
void set_rho_median (float _) override
float get_rho_median () const override
Public Member Functions inherited from JetContainer
JetContainer ()=default
~JetContainer () override=default
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual unsigned int get_index_single () const
virtual std::vector< unsigned int > get_index_vec () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
std::string str_Jet_PROPERTY (Jet::PROPERTY) const
void resize_jet_pvecs ()
ClassDefOverride (JetContainerv1, 1)
Private Attributes
TClonesArray * m_clones {nullptr}
size_t m_njets {0}
std::map< Jet::PROPERTY,
Jet::PROPERTY > m_pindex {}
size_t m_psize {0}
Jet::ALGO m_algo {Jet::NONE}
float m_jetpar_R {0.4}
std::set< Jet::SRC > m_src
float m_RhoMedian {NAN}
Additional Inherited Members
Public Types inherited from JetContainer
typedef std::set< Jet::SRC >
::const_iterator ConstSrcIter
typedef std::set< Jet::SRC >
::iterator SrcIter
Detailed Description
Definition at line 7 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 7 of file JetContainerv1.h
Constructor & Destructor Documentation
JetContainerv1::JetContainerv1 ()
Definition at line 8 of file JetContainerv1.cc.
View newest version in sPHENIX GitHub at line 8 of file JetContainerv1.cc
References m_clones.
JetContainerv1::~JetContainerv1 () override
JetContainerv1::JetContainerv1 (const JetContainer & jets) explicit
Definition at line 21 of file JetContainerv1.cc.
View newest version in sPHENIX GitHub at line 21 of file JetContainerv1.cc
References JetContainer::size().
Member Function Documentation
Jet* JetContainerv1::add_jet () override virtual
Reimplemented from JetContainer.
Referenced by ResonanceJetTagging::findMCTaggedJets(), and ResonanceJetTagging::findTaggedJets().
size_t JetContainerv1::add_property (Jet::PROPERTY) override virtual
Reimplemented from JetContainer.
size_t JetContainerv1::add_property (std::set< Jet::PROPERTY >) override virtual
Reimplemented from JetContainer.
Jet::IterJetTCA JetContainerv1::begin () override virtual
Reimplemented from JetContainer.
ConstSrcIter JetContainerv1::begin_src () const inline override virtual
Reimplemented from JetContainer.
Definition at line 78 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 78 of file JetContainerv1.h
References m_src.
SrcIter JetContainerv1::begin_src () inline override virtual
Reimplemented from JetContainer.
Definition at line 82 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 82 of file JetContainerv1.h
References m_src.
JetContainerv1::ClassDefOverride (JetContainerv1 , 1) private
TClonesArray* JetContainerv1::clone_data () const inline override virtual
Reimplemented from JetContainer.
Definition at line 17 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 17 of file JetContainerv1.h
References m_clones.
bool JetContainerv1::empty () const inline override virtual
Reimplemented from JetContainer.
Definition at line 21 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 21 of file JetContainerv1.h
References m_njets.
bool JetContainerv1::empty_src () const inline override virtual
Reimplemented from JetContainer.
Definition at line 75 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 75 of file JetContainerv1.h
References m_src.
Jet::IterJetTCA JetContainerv1::end () override virtual
Reimplemented from JetContainer.
ConstSrcIter JetContainerv1::end_src () const inline override virtual
Reimplemented from JetContainer.
Definition at line 80 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 80 of file JetContainerv1.h
References m_src.
SrcIter JetContainerv1::end_src () inline override virtual
Reimplemented from JetContainer.
Definition at line 84 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 84 of file JetContainerv1.h
References m_src.
ConstSrcIter JetContainerv1::find_src (Jet::SRC src) const inline override virtual
Reimplemented from JetContainer.
Definition at line 79 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 79 of file JetContainerv1.h
References m_src.
SrcIter JetContainerv1::find_src (Jet::SRC src) inline override virtual
Reimplemented from JetContainer.
Definition at line 83 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 83 of file JetContainerv1.h
References m_src.
Jet::ALGO JetContainerv1::get_algo () const inline override virtual
Reimplemented from JetContainer.
Definition at line 65 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 65 of file JetContainerv1.h
References m_algo.
Jet* JetContainerv1::get_jet (unsigned int index) override virtual
Reimplemented from JetContainer.
Referenced by operator()().
float JetContainerv1::get_jetpar_R () const inline override virtual
Reimplemented from JetContainer.
Definition at line 71 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 71 of file JetContainerv1.h
References m_jetpar_R.
Referenced by get_par().
float JetContainerv1::get_par () const inline override virtual
Reimplemented from JetContainer.
Definition at line 68 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 68 of file JetContainerv1.h
References get_jetpar_R().
float JetContainerv1::get_rho_median () const inline override virtual
Reimplemented from JetContainer.
Definition at line 89 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 89 of file JetContainerv1.h
References m_RhoMedian.
Jet* JetContainerv1::get_UncheckedAt (unsigned int index) override virtual
Reimplemented from JetContainer.
Referenced by operator[]().
bool JetContainerv1::has_property (Jet::PROPERTY prop) const inline override virtual
Reimplemented from JetContainer.
Definition at line 42 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 42 of file JetContainerv1.h
References m_pindex.
void JetContainerv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from JetContainer.
Definition at line 13 of file JetContainerv1.cc.
View newest version in sPHENIX GitHub at line 13 of file JetContainerv1.cc
References m_clones, and print_property_types().
void JetContainerv1::insert_src (Jet::SRC src) inline override virtual
Reimplemented from JetContainer.
Definition at line 76 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 76 of file JetContainerv1.h
References m_src.
Jet* JetContainerv1::operator() (int index) inline override virtual
Reimplemented from JetContainer.
Definition at line 30 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 30 of file JetContainerv1.h
References get_jet().
JetContainerv1& JetContainerv1::operator= (const JetContainer & jets)
Jet* JetContainerv1::operator[] (int index) inline override virtual
Reimplemented from JetContainer.
Definition at line 31 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 31 of file JetContainerv1.h
References get_UncheckedAt().
void JetContainerv1::print_jets (std::ostream &) override virtual
Reimplemented from JetContainer.
void JetContainerv1::print_property_types (std::ostream & os = std::cout) const override virtual
Reimplemented from JetContainer.
Referenced by identify().
virtual Jet::PROPERTY JetContainerv1::property_index (Jet::PROPERTY) override virtual
Reimplemented from JetContainer.
std::map<Jet::PROPERTY, Jet::PROPERTY> JetContainerv1::property_indices () const inline override virtual
Reimplemented from JetContainer.
Definition at line 41 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 41 of file JetContainerv1.h
References m_pindex.
void JetContainerv1::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
void JetContainerv1::resize_jet_pvecs () private
void JetContainerv1::set_algo (Jet::ALGO algo) inline override virtual
Reimplemented from JetContainer.
Definition at line 64 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 64 of file JetContainerv1.h
References m_algo.
void JetContainerv1::set_jetpar_R (float par) inline override virtual
Reimplemented from JetContainer.
Definition at line 70 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 70 of file JetContainerv1.h
References m_jetpar_R.
Referenced by set_par().
void JetContainerv1::set_par (float par) inline override virtual
Reimplemented from JetContainer.
Definition at line 67 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 67 of file JetContainerv1.h
References set_jetpar_R().
void JetContainerv1::set_rho_median (float _) inline override virtual
Reimplemented from JetContainer.
Definition at line 88 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 88 of file JetContainerv1.h
References _, and m_RhoMedian.
size_t JetContainerv1::size (void) const inline override virtual
Reimplemented from JetContainer.
Definition at line 22 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 22 of file JetContainerv1.h
References m_njets.
size_t JetContainerv1::size_properties () const inline override virtual
Reimplemented from JetContainer.
Definition at line 43 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 43 of file JetContainerv1.h
References m_pindex.
std::string JetContainerv1::str_Jet_PROPERTY (Jet::PROPERTY) const private
Member Data Documentation
Jet::ALGO JetContainerv1::m_algo {Jet::NONE} private
Definition at line 104 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 104 of file JetContainerv1.h
Referenced by get_algo(), and set_algo().
TClonesArray* JetContainerv1::m_clones {nullptr} private
Definition at line 94 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 94 of file JetContainerv1.h
Referenced by clone_data(), identify(), and JetContainerv1().
float JetContainerv1::m_jetpar_R {0.4} private
Definition at line 105 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 105 of file JetContainerv1.h
Referenced by get_jetpar_R(), and set_jetpar_R().
size_t JetContainerv1::m_njets {0} private
Definition at line 95 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 95 of file JetContainerv1.h
Referenced by empty(), and size().
std::map<Jet::PROPERTY, Jet::PROPERTY > JetContainerv1::m_pindex {} private
Definition at line 98 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 98 of file JetContainerv1.h
Referenced by has_property(), property_indices(), and size_properties().
size_t JetContainerv1::m_psize {0} private
Definition at line 99 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 99 of file JetContainerv1.h
float JetContainerv1::m_RhoMedian {NAN} private
Definition at line 109 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 109 of file JetContainerv1.h
Referenced by get_rho_median(), and set_rho_median().
std::set<Jet::SRC> JetContainerv1::m_src private
Definition at line 107 of file JetContainerv1.h.
View newest version in sPHENIX GitHub at line 107 of file JetContainerv1.h
Referenced by begin_src(), empty_src(), end_src(), find_src(), and insert_src().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/jetbase/JetContainerv1.h
coresoftware/blob/master/offline/packages/jetbase/JetContainerv1.cc