Analysis Software: analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorQAMaker/macros/QuickWeirdTuplePlotter.cxx File Reference
QuickWeirdTuplePlotter.cxx File Reference
#include <string>
#include <vector>
#include <utility>
#include <iostream>
#include <TH2.h>
#include <TFile.h>
#include <TError.h>
#include <TNtuple.h>
#include <TDirectory.h>
#include <ROOT/RDataFrame.hxx>
#include <ROOT/RDF/HistoModels.hxx>
Typedefs
using TH2Def = ROOT::RDF::TH2DModel
Functions
void QuickWeirdTuplePlotter ()
Typedef Documentation
using TH2Def = ROOT::RDF::TH2DModel
Definition at line 26 of file QuickWeirdTuplePlotter.cxx.
View newest version in sPHENIX GitHub at line 26 of file QuickWeirdTuplePlotter.cxx
Function Documentation
void QuickWeirdTuplePlotter ()
Definition at line 32 of file QuickWeirdTuplePlotter.cxx.
View newest version in sPHENIX GitHub at line 32 of file QuickWeirdTuplePlotter.cxx
References KFPMath::a, KFPMath::b, bins, cd(), Close(), configureMap::data, Acts::UnitConstants::e, add_histos::hist, std::tr1::make_tuple(), and Write().