Analysis Software: prototype/blob/master/macros/prototype2/Fun4All_G4_Prototype2.C File Reference
Fun4All_G4_Prototype2.C File Reference
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <g4calo/RawTowerBuilder.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4caloprototype/Prototype2RawTowerBuilder.h>
#include <g4detectors/PHG4BlockSubsystem.h>
#include <g4detectors/PHG4FullProjSpacalCellReco.h>
#include <g4caloprototype/PHG4Prototype2HcalCellReco.h>
#include <g4caloprototype/PHG4Prototype2InnerHcalSubsystem.h>
#include <g4caloprototype/PHG4Prototype2OuterHcalSubsystem.h>
#include <g4caloprototype/PHG4SpacalPrototypeSubsystem.h>
#include <g4eval/PHG4DSTReader.h>
#include <g4histos/G4HitNtuple.h>
#include <g4main/PHG4ParticleGun.h>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4SimpleEventGenerator.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <phool/recoConsts.h>
#include <qa_modules/QAHistManagerDef.h>
#include <qa_modules/QAG4SimulationCalorimeter.h>
Functions
int Fun4All_G4_Prototype2 (int nEvents=1)
Function Documentation
int Fun4All_G4_Prototype2 (int nEvents = 1)
Definition at line 47 of file Fun4All_G4_Prototype2.C.
View newest version in sPHENIX GitHub at line 47 of file Fun4All_G4_Prototype2.C
References PHG4SimpleEventGenerator::add_particles(), G4HitNtuple::AddNode(), PHG4DSTReader::AddNode(), PHG4DSTReader::AddTower(), PHG4DetectorSubsystem::BlackHole(), cemc, RawTowerBuilder::Detector(), Prototype2RawTowerBuilder::Detector(), PHG4Prototype2HcalCellReco::Detector(), RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), PHG4FullProjSpacalCellReco::Detector(), Acts::UnitConstants::e, Fun4AllServer::End(), PHG4SimpleEventGenerator::Gaus, gen(), PHG4FullProjSpacalCellReco::get_light_collection_model(), i, in, recoConsts::instance(), Fun4AllServer::instance(), QAG4SimulationCalorimeter::kProcessG4Hit, RawTowerCalibration::kSimple_linear_calibration, RawTowerDigitizer::kSimple_photon_digitalization, LightCollectionModel::load_data_file(), momentum, nEvents, out, PHG4DetectorSubsystem::OverlapCheck(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), Fun4AllServer::run(), QAHistManagerDef::saveQARootFile(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerCalibration::set_calib_tower_node_prefix(), RawTowerDigitizer::set_digi_algorithm(), PHG4DetectorSubsystem::set_double_param(), PHG4SimpleEventGenerator::set_eta_range(), PHG4Reco::set_field(), PHG4DSTReader::set_load_active_particle(), PHG4DSTReader::set_load_all_particle(), PHG4ParticleGeneratorBase::set_mom(), PHG4ParticleGeneratorBase::set_name(), PHG4SimpleEventGenerator::set_p_range(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), PHG4SimpleEventGenerator::set_phi_range(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), RawTowerCalibration::set_raw_tower_node_prefix(), RawTowerDigitizer::set_raw_tower_node_prefix(), PHG4DSTReader::set_save_particle(), PHG4DSTReader::set_save_vertex(), Prototype2RawTowerBuilder::set_sim_tower_node_prefix(), RawTowerBuilder::set_sim_tower_node_prefix(), PHG4DetectorSubsystem::set_string_param(), PHG4FullProjSpacalCellReco::set_timing_window(), PHG4DSTReader::set_tower_zero_sup(), PHG4SimpleEventGenerator::set_vertex_distribution_function(), PHG4SimpleEventGenerator::set_vertex_distribution_mean(), PHG4SimpleEventGenerator::set_vertex_distribution_width(), PHG4ParticleGeneratorBase::set_vtx(), RawTowerDigitizer::set_zero_suppression_ADC(), RawTowerCalibration::set_zero_suppression_GeV(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetAbsorberTruth(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SetCalibrationFileDir(), PHG4DetectorSubsystem::SuperDetector(), PHG4DetectorSubsystem::UseCalibFiles(), and PHG4DetectorSubsystem::xml.