Analysis Software: SvtxTrack_v1 Class Reference
SvtxTrack_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack_v1.h>
Public Member Functions
SvtxTrack_v1 ()
SvtxTrack_v1 (const SvtxTrack &)
SvtxTrack_v1 (const SvtxTrack_v1 &track)
SvtxTrack_v1 & operator= (const SvtxTrack_v1 &track)
~SvtxTrack_v1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void CopyFrom (const SvtxTrack &) override
copy content from base class
void CopyFrom (SvtxTrack *source) override
copy content from base class
unsigned int get_id () const override
void set_id (unsigned int id) override
unsigned int get_vertex_id () const override
void set_vertex_id (unsigned int id) override
bool get_positive_charge () const override
void set_positive_charge (bool ispos) override
int get_charge () const override
void set_charge (int charge) override
float get_chisq () const override
void set_chisq (float chisq) override
unsigned int get_ndf () const override
void set_ndf (int ndf) override
float get_quality () const override
float get_dca () const override
void set_dca (float dca) override
float get_dca_error () const override
void set_dca_error (float dca_error) override
float get_dca2d () const override
void set_dca2d (float dca2d) override
float get_dca2d_error () const override
void set_dca2d_error (float error) override
float get_dca3d_xy () const override
void set_dca3d_xy (float dcaxy) override
float get_dca3d_xy_error () const override
void set_dca3d_xy_error (float error) override
float get_dca3d_z () const override
void set_dca3d_z (float dcaz) override
float get_dca3d_z_error () const override
void set_dca3d_z_error (float error) override
float get_x () const override
void set_x (float x) override
float get_y () const override
void set_y (float y) override
float get_z () const override
void set_z (float z) override
float get_pos (unsigned int i) const override
float get_px () const override
void set_px (float px) override
float get_py () const override
void set_py (float py) override
float get_pz () const override
void set_pz (float pz) override
float get_mom (unsigned int i) const override
float get_p () const override
float get_pt () const override
float get_eta () const override
float get_phi () const override
float get_error (int i, int j) const override
void set_error (int i, int j, float value) override
bool empty_states () const override
size_t size_states () const override
size_t count_states (float pathlength) const override
void clear_states () override
const SvtxTrackState * get_state (float pathlength) const override
SvtxTrackState * get_state (float pathlength) override
SvtxTrackState * insert_state (const SvtxTrackState *state) override
size_t erase_state (float pathlength) override
ConstStateIter begin_states () const override
ConstStateIter find_state (float pathlength) const override
ConstStateIter end_states () const override
StateIter begin_states () override
StateIter find_state (float pathlength) override
StateIter end_states () override
void clear_clusters () override
bool empty_clusters () const override
size_t size_clusters () const override
void insert_cluster (unsigned int clusterid) override
size_t erase_cluster (unsigned int clusterid) override
ConstClusterIter begin_clusters () const override
ConstClusterIter find_cluster (unsigned int clusterid) const override
ConstClusterIter end_clusters () const override
ClusterIter find_cluster (unsigned int clusterid) override
ClusterIter begin_clusters () override
ClusterIter end_clusters () override
void clear_cluster_keys () override
bool empty_cluster_keys () const override
size_t size_cluster_keys () const override
void insert_cluster_key (TrkrDefs::cluskey clusterid) override
size_t erase_cluster_key (TrkrDefs::cluskey clusterid) override
ConstClusterKeyIter find_cluster_key (TrkrDefs::cluskey clusterid) const override
ConstClusterKeyIter begin_cluster_keys () const override
ConstClusterKeyIter end_cluster_keys () const override
ClusterKeyIter find_cluster_keys (unsigned int clusterid) override
ClusterKeyIter begin_cluster_keys () override
ClusterKeyIter end_cluster_keys () override
float get_cal_dphi (CAL_LAYER layer) const override
void set_cal_dphi (CAL_LAYER layer, float dphi) override
float get_cal_deta (CAL_LAYER layer) const override
void set_cal_deta (CAL_LAYER layer, float deta) override
float get_cal_energy_3x3 (CAL_LAYER layer) const override
void set_cal_energy_3x3 (CAL_LAYER layer, float energy_3x3) override
float get_cal_energy_5x5 (CAL_LAYER layer) const override
void set_cal_energy_5x5 (CAL_LAYER layer, float energy_5x5) override
unsigned int get_cal_cluster_id (CAL_LAYER layer) const override
void set_cal_cluster_id (CAL_LAYER layer, unsigned int id) override
TrkrDefs::cluskey get_cal_cluster_key (CAL_LAYER layer) const override
void set_cal_cluster_key (CAL_LAYER layer, TrkrDefs::cluskey id) override
float get_cal_cluster_e (CAL_LAYER layer) const override
void set_cal_cluster_e (CAL_LAYER layer, float e) override
Public Member Functions inherited from SvtxTrack
~SvtxTrack () override=default
virtual TrackSeed * get_tpc_seed () const
virtual void set_tpc_seed (TrackSeed *)
virtual TrackSeed * get_silicon_seed () const
virtual void set_silicon_seed (TrackSeed *)
virtual short int get_crossing () const
virtual void set_crossing (short int)
virtual float get_cal_dphi (CAL_LAYER) const
virtual void set_cal_dphi (CAL_LAYER, float)
virtual float get_cal_deta (CAL_LAYER) const
virtual void set_cal_deta (CAL_LAYER, float)
virtual float get_cal_energy_3x3 (CAL_LAYER) const
virtual void set_cal_energy_3x3 (CAL_LAYER, float)
virtual float get_cal_energy_5x5 (CAL_LAYER) const
virtual void set_cal_energy_5x5 (CAL_LAYER, float)
virtual unsigned int get_cal_cluster_id (CAL_LAYER) const
virtual void set_cal_cluster_id (CAL_LAYER, unsigned int)
virtual TrkrDefs::cluskey get_cal_cluster_key (CAL_LAYER) const
virtual void set_cal_cluster_key (CAL_LAYER, TrkrDefs::cluskey)
virtual float get_cal_cluster_e (CAL_LAYER) const
virtual void set_cal_cluster_e (CAL_LAYER, float)
virtual float get_acts_covariance (unsigned int, unsigned int) const
virtual void set_acts_covariance (unsigned int, unsigned int, float)
virtual unsigned int get_truth_track_id () const
virtual void set_truth_track_id (unsigned int)
virtual void set_num_measurements (int)
virtual unsigned int get_num_measurements () const
virtual bool empty_g4hit_id () const
virtual size_t size_g4hit_id () const
virtual void add_g4hit_id (int, PHG4HitDefs::keytype)
virtual HitIdIter begin_g4hit_id ()
virtual HitIdConstIter begin_g4hit_id () const
virtual HitIdIter find_g4hit_id (int)
virtual HitIdConstIter find_g4hit_id (int) const
virtual HitIdIter end_g4hit_id ()
virtual HitIdConstIter end_g4hit_id () const
virtual size_t remove_g4hit_id (int, PHG4HitDefs::keytype)
virtual size_t remove_g4hit_volume (int)
virtual void clear_g4hit_id ()
virtual const HitIdMap & g4hit_ids () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
unsigned int _track_id = UINT_MAX
unsigned int _vertex_id = UINT_MAX
bool _is_positive_charge = false
float _chisq = NAN
unsigned int _ndf = 0
float _dca = NAN
float _dca_error = NAN
float _dca2d = NAN
float _dca2d_error = NAN
float _dca3d_xy = NAN
float _dca3d_xy_error = NAN
float _dca3d_z = NAN
float _dca3d_z_error = NAN
StateMap _states
ClusterSet _cluster_ids
ClusterKeySet _cluster_keys
std::map< CAL_LAYER, float > _cal_dphi
std::map< CAL_LAYER, float > _cal_deta
std::map< CAL_LAYER, float > _cal_energy_3x3
std::map< CAL_LAYER, float > _cal_energy_5x5
std::map< CAL_LAYER, int > _cal_cluster_id
std::map< CAL_LAYER,
TrkrDefs::cluskey > _cal_cluster_key
std::map< CAL_LAYER, float > _cal_cluster_e
Additional Inherited Members
Public Types inherited from SvtxTrack
enum CAL_LAYER {
PRES = 0, CEMC = 1, HCALIN = 2, HCALOUT = 3,
OUTER_CEMC = 4, OUTER_HCALIN = 5, OUTER_HCALOUT = 6
}
typedef std::map< float,
SvtxTrackState * > StateMap
typedef StateMap::const_iterator ConstStateIter
typedef StateMap::iterator StateIter
typedef std::set< unsigned int > ClusterSet
typedef ClusterSet::const_iterator ConstClusterIter
typedef ClusterSet::iterator ClusterIter
typedef std::set
< TrkrDefs::cluskey > ClusterKeySet
typedef
ClusterKeySet::const_iterator ConstClusterKeyIter
typedef ClusterKeySet::iterator ClusterKeyIter
typedef std::map< int,
std::set< PHG4HitDefs::keytype > > HitIdMap
typedef HitIdMap::iterator HitIdIter
typedef HitIdMap::const_iterator HitIdConstIter
Protected Member Functions inherited from SvtxTrack
SvtxTrack ()
ClassDefOverride (SvtxTrack, 1)
Detailed Description
Definition at line 17 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 17 of file SvtxTrack_v1.h
Constructor & Destructor Documentation
SvtxTrack_v1::SvtxTrack_v1 ()
Definition at line 13 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 13 of file SvtxTrack_v1.cc
References _states.
Referenced by CloneMe(), and Reset().
SvtxTrack_v1::SvtxTrack_v1 (const SvtxTrack & source)
Definition at line 19 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 19 of file SvtxTrack_v1.cc
References CopyFrom().
SvtxTrack_v1::SvtxTrack_v1 (const SvtxTrack_v1 & track)
Definition at line 25 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 25 of file SvtxTrack_v1.cc
References CopyFrom().
SvtxTrack_v1::~SvtxTrack_v1 () override
Definition at line 31 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 31 of file SvtxTrack_v1.cc
References clear_states().
Member Function Documentation
ConstClusterKeyIter SvtxTrack_v1::begin_cluster_keys () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 171 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 171 of file SvtxTrack_v1.h
References _cluster_keys.
Referenced by identify().
ClusterKeyIter SvtxTrack_v1::begin_cluster_keys () inline override virtual
Reimplemented from SvtxTrack.
Definition at line 174 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 174 of file SvtxTrack_v1.h
References _cluster_keys.
ConstClusterIter SvtxTrack_v1::begin_clusters () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 156 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 156 of file SvtxTrack_v1.h
References _cluster_ids.
Referenced by identify(), and SvtxTrack_FastSim::identify().
ClusterIter SvtxTrack_v1::begin_clusters () inline override virtual
Reimplemented from SvtxTrack.
Definition at line 160 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 160 of file SvtxTrack_v1.h
References _cluster_ids.
ConstStateIter SvtxTrack_v1::begin_states () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 137 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 137 of file SvtxTrack_v1.h
References _states.
Referenced by PHG4TrackFastSimEval::fill_track_tree(), EventEvaluator::fillOutputNtuples(), TrackProjectorPlaneECAL::get_best_state(), and TrackProjectorPlaneECAL::get_best_track().
StateIter SvtxTrack_v1::begin_states () inline override virtual
Reimplemented from SvtxTrack.
Definition at line 141 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 141 of file SvtxTrack_v1.h
References _states.
void SvtxTrack_v1::clear_cluster_keys () inline override virtual
Reimplemented from SvtxTrack.
Definition at line 164 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 164 of file SvtxTrack_v1.h
References _cluster_keys.
void SvtxTrack_v1::clear_clusters () inline override virtual
Reimplemented from SvtxTrack.
Definition at line 150 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 150 of file SvtxTrack_v1.h
References _cluster_ids.
void SvtxTrack_v1::clear_states () override virtual
Reimplemented from SvtxTrack.
Definition at line 138 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 138 of file SvtxTrack_v1.cc
References _states.
Referenced by CopyFrom(), and ~SvtxTrack_v1().
PHObject* SvtxTrack_v1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from SvtxTrack.
Definition at line 37 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 37 of file SvtxTrack_v1.h
References SvtxTrack_v1().
void SvtxTrack_v1::CopyFrom (const SvtxTrack &) override virtual
copy content from base class
Reimplemented from SvtxTrack.
Definition at line 36 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 36 of file SvtxTrack_v1.cc
References _cal_cluster_e, _cal_cluster_id, _cal_cluster_key, _cal_deta, _cal_dphi, _cal_energy_3x3, _cal_energy_5x5, _chisq, _cluster_ids, _cluster_keys, _dca, _dca2d, _dca2d_error, _dca3d_xy, _dca3d_xy_error, _dca3d_z, _dca3d_z_error, _dca_error, _is_positive_charge, _ndf, _states, _track_id, _vertex_id, SvtxTrack::begin_cluster_keys(), SvtxTrack::begin_clusters(), SvtxTrack::begin_states(), SvtxTrack::CEMC, clear_states(), SvtxTrack::CopyFrom(), SvtxTrack::end_cluster_keys(), SvtxTrack::end_clusters(), SvtxTrack::end_states(), SvtxTrack::get_cal_cluster_e(), SvtxTrack::get_cal_cluster_id(), SvtxTrack::get_cal_cluster_key(), SvtxTrack::get_cal_deta(), SvtxTrack::get_cal_dphi(), SvtxTrack::get_cal_energy_3x3(), SvtxTrack::get_cal_energy_5x5(), SvtxTrack::get_chisq(), SvtxTrack::get_dca(), SvtxTrack::get_dca2d(), SvtxTrack::get_dca2d_error(), SvtxTrack::get_dca3d_xy(), SvtxTrack::get_dca3d_xy_error(), SvtxTrack::get_dca3d_z(), SvtxTrack::get_dca3d_z_error(), SvtxTrack::get_dca_error(), SvtxTrack::get_id(), SvtxTrack::get_ndf(), SvtxTrack::get_positive_charge(), SvtxTrack::get_vertex_id(), SvtxTrack::HCALIN, SvtxTrack::HCALOUT, SvtxTrack::PRES, set_cal_cluster_e(), set_cal_cluster_id(), set_cal_cluster_key(), set_cal_deta(), set_cal_dphi(), set_cal_energy_3x3(), set_cal_energy_5x5(), and parse_cmake_options::type.
Referenced by SvtxTrack_FastSim::CopyFrom(), operator=(), and SvtxTrack_v1().
void SvtxTrack_v1::CopyFrom (SvtxTrack *) inline override virtual
copy content from base class
Reimplemented from SvtxTrack.
Definition at line 42 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 42 of file SvtxTrack_v1.h
References CopyFrom().
Referenced by CopyFrom().
size_t SvtxTrack_v1::count_states (float pathlength) const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 128 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 128 of file SvtxTrack_v1.h
References _states.
bool SvtxTrack_v1::empty_cluster_keys () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 165 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 165 of file SvtxTrack_v1.h
References _cluster_keys.
bool SvtxTrack_v1::empty_clusters () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 151 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 151 of file SvtxTrack_v1.h
References _cluster_ids.
Referenced by SvtxTrack_FastSim::identify().
bool SvtxTrack_v1::empty_states () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 126 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 126 of file SvtxTrack_v1.h
References _states.
ConstClusterKeyIter SvtxTrack_v1::end_cluster_keys () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 172 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 172 of file SvtxTrack_v1.h
References _cluster_keys.
Referenced by identify().
ClusterKeyIter SvtxTrack_v1::end_cluster_keys () inline override virtual
Reimplemented from SvtxTrack.
Definition at line 175 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 175 of file SvtxTrack_v1.h
References _cluster_keys.
ConstClusterIter SvtxTrack_v1::end_clusters () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 158 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 158 of file SvtxTrack_v1.h
References _cluster_ids.
Referenced by identify(), and SvtxTrack_FastSim::identify().
ClusterIter SvtxTrack_v1::end_clusters () inline override virtual
Reimplemented from SvtxTrack.
Definition at line 161 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 161 of file SvtxTrack_v1.h
References _cluster_ids.
ConstStateIter SvtxTrack_v1::end_states () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 139 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 139 of file SvtxTrack_v1.h
References _states.
Referenced by PHG4TrackFastSimEval::fill_track_tree(), EventEvaluator::fillOutputNtuples(), TrackProjectorPlaneECAL::get_best_state(), TrackProjectorPlaneECAL::get_best_track(), and TrackProjectorPlaneECAL::project_track().
StateIter SvtxTrack_v1::end_states () inline override virtual
Reimplemented from SvtxTrack.
Definition at line 143 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 143 of file SvtxTrack_v1.h
References _states.
size_t SvtxTrack_v1::erase_cluster (unsigned int clusterid) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 155 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 155 of file SvtxTrack_v1.h
References _cluster_ids.
size_t SvtxTrack_v1::erase_cluster_key (TrkrDefs::cluskey clusterid) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 169 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 169 of file SvtxTrack_v1.h
References _cluster_keys.
size_t SvtxTrack_v1::erase_state (float pathlength) override virtual
Reimplemented from SvtxTrack.
Definition at line 173 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 173 of file SvtxTrack_v1.cc
References _states.
ConstClusterIter SvtxTrack_v1::find_cluster (unsigned int clusterid) const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 157 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 157 of file SvtxTrack_v1.h
References _cluster_ids.
ClusterIter SvtxTrack_v1::find_cluster (unsigned int clusterid) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 159 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 159 of file SvtxTrack_v1.h
References _cluster_ids.
ConstClusterKeyIter SvtxTrack_v1::find_cluster_key (TrkrDefs::cluskey clusterid) const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 170 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 170 of file SvtxTrack_v1.h
References _cluster_keys.
ClusterKeyIter SvtxTrack_v1::find_cluster_keys (unsigned int clusterid) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 173 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 173 of file SvtxTrack_v1.h
References _cluster_keys.
ConstStateIter SvtxTrack_v1::find_state (float pathlength) const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 138 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 138 of file SvtxTrack_v1.h
References _states.
StateIter SvtxTrack_v1::find_state (float pathlength) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 142 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 142 of file SvtxTrack_v1.h
References _states.
float SvtxTrack_v1::get_cal_cluster_e (CAL_LAYER layer) const override
Definition at line 225 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 225 of file SvtxTrack_v1.cc
References _cal_cluster_e.
unsigned int SvtxTrack_v1::get_cal_cluster_id (CAL_LAYER layer) const override
Definition at line 211 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 211 of file SvtxTrack_v1.cc
References _cal_cluster_id.
TrkrDefs::cluskey SvtxTrack_v1::get_cal_cluster_key (CAL_LAYER layer) const override
Definition at line 218 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 218 of file SvtxTrack_v1.cc
References _cal_cluster_key.
float SvtxTrack_v1::get_cal_deta (CAL_LAYER layer) const override
Definition at line 190 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 190 of file SvtxTrack_v1.cc
References _cal_deta.
float SvtxTrack_v1::get_cal_dphi (CAL_LAYER layer) const override
Definition at line 183 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 183 of file SvtxTrack_v1.cc
References _cal_dphi.
float SvtxTrack_v1::get_cal_energy_3x3 (CAL_LAYER layer) const override
Definition at line 197 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 197 of file SvtxTrack_v1.cc
References _cal_energy_3x3.
float SvtxTrack_v1::get_cal_energy_5x5 (CAL_LAYER layer) const override
Definition at line 204 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 204 of file SvtxTrack_v1.cc
References _cal_energy_5x5.
int SvtxTrack_v1::get_charge () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 58 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 58 of file SvtxTrack_v1.h
References get_positive_charge().
Referenced by PHG4TrackFastSimEval::fill_track_tree(), FastTrackingEval::fill_tree(), identify(), SvtxTrack_FastSim::identify(), and DISKinematicsReco::InsertCandidateFromCluster().
float SvtxTrack_v1::get_chisq () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 61 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 61 of file SvtxTrack_v1.h
References _chisq.
Referenced by identify(), and SvtxTrack_FastSim::identify().
float SvtxTrack_v1::get_dca () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 69 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 69 of file SvtxTrack_v1.h
References _dca.
Referenced by EventEvaluator::fillOutputNtuples().
float SvtxTrack_v1::get_dca2d () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 75 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 75 of file SvtxTrack_v1.h
References _dca2d.
Referenced by PHG4TrackFastSimEval::fill_track_tree(), FastTrackingEval::fill_tree(), and EventEvaluator::fillOutputNtuples().
float SvtxTrack_v1::get_dca2d_error () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 78 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 78 of file SvtxTrack_v1.h
References _dca2d_error.
float SvtxTrack_v1::get_dca3d_xy () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 81 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 81 of file SvtxTrack_v1.h
References _dca3d_xy.
float SvtxTrack_v1::get_dca3d_xy_error () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 84 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 84 of file SvtxTrack_v1.h
References _dca3d_xy_error.
float SvtxTrack_v1::get_dca3d_z () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 87 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 87 of file SvtxTrack_v1.h
References _dca3d_z.
float SvtxTrack_v1::get_dca3d_z_error () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 90 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 90 of file SvtxTrack_v1.h
References _dca3d_z_error.
float SvtxTrack_v1::get_dca_error () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 72 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 72 of file SvtxTrack_v1.h
References _dca_error.
float SvtxTrack_v1::get_error (int i, int j) const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 120 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 120 of file SvtxTrack_v1.h
References _states.
float SvtxTrack_v1::get_eta () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 117 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 117 of file SvtxTrack_v1.h
References get_pt(), and get_pz().
Referenced by DISKinematicsReco::InsertCandidateFromCluster().
unsigned int SvtxTrack_v1::get_id () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 49 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 49 of file SvtxTrack_v1.h
References _track_id.
Referenced by PHG4TrackFastSimEval::fill_track_tree(), FastTrackingEval::fill_tree(), EventEvaluator::fillOutputNtuples(), identify(), SvtxTrack_FastSim::identify(), and TpcPrototypeGenFitTrkFinder::process_event().
float SvtxTrack_v1::get_mom (unsigned int i) const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 113 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 113 of file SvtxTrack_v1.h
References _states.
unsigned int SvtxTrack_v1::get_ndf () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 64 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 64 of file SvtxTrack_v1.h
References _ndf.
Referenced by identify(), and SvtxTrack_FastSim::identify().
float SvtxTrack_v1::get_p () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 115 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 115 of file SvtxTrack_v1.h
References get_px(), get_py(), and get_pz().
Referenced by DISKinematicsReco::InsertCandidateFromCluster().
float SvtxTrack_v1::get_phi () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 118 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 118 of file SvtxTrack_v1.h
References get_px(), and get_py().
Referenced by DISKinematicsReco::InsertCandidateFromCluster().
float SvtxTrack_v1::get_pos (unsigned int i) const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 102 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 102 of file SvtxTrack_v1.h
References _states.
bool SvtxTrack_v1::get_positive_charge () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 55 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 55 of file SvtxTrack_v1.h
References _is_positive_charge.
Referenced by get_charge().
float SvtxTrack_v1::get_pt () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 116 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 116 of file SvtxTrack_v1.h
References get_px(), and get_py().
Referenced by get_eta(), and DISKinematicsReco::InsertCandidateFromCluster().
float SvtxTrack_v1::get_px () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 104 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 104 of file SvtxTrack_v1.h
References _states.
Referenced by PHG4TrackFastSimEval::fill_track_tree(), FastTrackingEval::fill_tree(), EventEvaluator::fillOutputNtuples(), get_p(), get_phi(), get_pt(), identify(), and SvtxTrack_FastSim::identify().
float SvtxTrack_v1::get_py () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 107 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 107 of file SvtxTrack_v1.h
References _states.
Referenced by PHG4TrackFastSimEval::fill_track_tree(), FastTrackingEval::fill_tree(), EventEvaluator::fillOutputNtuples(), get_p(), get_phi(), get_pt(), identify(), and SvtxTrack_FastSim::identify().
float SvtxTrack_v1::get_pz () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 110 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 110 of file SvtxTrack_v1.h
References _states.
Referenced by PHG4TrackFastSimEval::fill_track_tree(), FastTrackingEval::fill_tree(), EventEvaluator::fillOutputNtuples(), get_eta(), get_p(), identify(), and SvtxTrack_FastSim::identify().
float SvtxTrack_v1::get_quality () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 67 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 67 of file SvtxTrack_v1.h
References _chisq, and _ndf.
const SvtxTrackState * SvtxTrack_v1::get_state (float pathlength) const override virtual
Reimplemented from SvtxTrack.
Definition at line 151 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 151 of file SvtxTrack_v1.cc
References _states.
SvtxTrackState * SvtxTrack_v1::get_state (float pathlength) override virtual
Reimplemented from SvtxTrack.
Definition at line 158 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 158 of file SvtxTrack_v1.cc
References _states.
unsigned int SvtxTrack_v1::get_vertex_id () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 52 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 52 of file SvtxTrack_v1.h
References _vertex_id.
Referenced by identify().
float SvtxTrack_v1::get_x () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 93 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 93 of file SvtxTrack_v1.h
References _states.
Referenced by PHG4TrackFastSimEval::fill_track_tree(), identify(), and SvtxTrack_FastSim::identify().
float SvtxTrack_v1::get_y () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 96 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 96 of file SvtxTrack_v1.h
References _states.
Referenced by PHG4TrackFastSimEval::fill_track_tree(), identify(), and SvtxTrack_FastSim::identify().
float SvtxTrack_v1::get_z () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 99 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 99 of file SvtxTrack_v1.h
References _states.
Referenced by PHG4TrackFastSimEval::fill_track_tree(), identify(), and SvtxTrack_FastSim::identify().
void SvtxTrack_v1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxTrack.
Definition at line 94 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 94 of file SvtxTrack_v1.cc
References _cluster_ids, _cluster_keys, begin_cluster_keys(), begin_clusters(), end_cluster_keys(), end_clusters(), get_charge(), get_chisq(), get_id(), get_ndf(), get_px(), get_py(), get_pz(), get_vertex_id(), get_x(), get_y(), and get_z().
Referenced by SvtxTrack_FastSim::identify().
void SvtxTrack_v1::insert_cluster (unsigned int clusterid) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 154 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 154 of file SvtxTrack_v1.h
References _cluster_ids.
void SvtxTrack_v1::insert_cluster_key (TrkrDefs::cluskey clusterid) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 168 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 168 of file SvtxTrack_v1.h
References _cluster_keys.
Referenced by TpcPrototypeGenFitTrkFinder::process_event().
SvtxTrackState * SvtxTrack_v1::insert_state (const SvtxTrackState * state) override virtual
Reimplemented from SvtxTrack.
Definition at line 165 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 165 of file SvtxTrack_v1.cc
References _states, SvtxTrackState::CloneMe(), and SvtxTrackState::get_pathlength().
int SvtxTrack_v1::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxTrack.
Definition at line 146 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 146 of file SvtxTrack_v1.cc
SvtxTrack_v1 & SvtxTrack_v1::operator= (const SvtxTrack_v1 & track)
Definition at line 28 of file SvtxTrack_v1.cc.
View newest version in sPHENIX GitHub at line 28 of file SvtxTrack_v1.cc
References CopyFrom().
void SvtxTrack_v1::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 35 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 35 of file SvtxTrack_v1.h
References SvtxTrack_v1().
void SvtxTrack_v1::set_cal_cluster_e (CAL_LAYER layer, float e) inline override
Definition at line 199 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 199 of file SvtxTrack_v1.h
References _cal_cluster_e, Acts::UnitConstants::e, and layer.
Referenced by CopyFrom().
void SvtxTrack_v1::set_cal_cluster_id (CAL_LAYER layer, unsigned int id) inline override
Definition at line 193 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 193 of file SvtxTrack_v1.h
References _cal_cluster_id, train_ambiguity_solver::id, and layer.
Referenced by CopyFrom().
void SvtxTrack_v1::set_cal_cluster_key (CAL_LAYER layer, TrkrDefs::cluskey id) inline override
Definition at line 196 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 196 of file SvtxTrack_v1.h
References _cal_cluster_key, train_ambiguity_solver::id, and layer.
Referenced by CopyFrom().
void SvtxTrack_v1::set_cal_deta (CAL_LAYER layer, float deta) inline override
Definition at line 184 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 184 of file SvtxTrack_v1.h
References _cal_deta, and layer.
Referenced by CopyFrom().
void SvtxTrack_v1::set_cal_dphi (CAL_LAYER layer, float dphi) inline override
Definition at line 181 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 181 of file SvtxTrack_v1.h
References _cal_dphi, INTTVtxZ::dphi, and layer.
Referenced by CopyFrom().
void SvtxTrack_v1::set_cal_energy_3x3 (CAL_LAYER layer, float energy_3x3) inline override
Definition at line 187 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 187 of file SvtxTrack_v1.h
References _cal_energy_3x3, and layer.
Referenced by CopyFrom().
void SvtxTrack_v1::set_cal_energy_5x5 (CAL_LAYER layer, float energy_5x5) inline override
Definition at line 190 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 190 of file SvtxTrack_v1.h
References _cal_energy_5x5, and layer.
Referenced by CopyFrom().
void SvtxTrack_v1::set_charge (int charge) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 59 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 59 of file SvtxTrack_v1.h
References set_positive_charge().
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
void SvtxTrack_v1::set_chisq (float chisq) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 62 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 62 of file SvtxTrack_v1.h
References _chisq.
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
void SvtxTrack_v1::set_dca (float dca) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 70 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 70 of file SvtxTrack_v1.h
References _dca, and INTTVtxZ::dca.
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
void SvtxTrack_v1::set_dca2d (float dca2d) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 76 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 76 of file SvtxTrack_v1.h
References _dca2d.
Referenced by SVReco::MakeSvtxTrack(), and PHG4TrackFastSim::MakeSvtxTrack().
void SvtxTrack_v1::set_dca2d_error (float error) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 79 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 79 of file SvtxTrack_v1.h
References _dca2d_error, and acts::error.
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
void SvtxTrack_v1::set_dca3d_xy (float dcaxy) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 82 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 82 of file SvtxTrack_v1.h
References _dca3d_xy.
void SvtxTrack_v1::set_dca3d_xy_error (float error) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 85 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 85 of file SvtxTrack_v1.h
References _dca3d_xy_error, and acts::error.
void SvtxTrack_v1::set_dca3d_z (float dcaz) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 88 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 88 of file SvtxTrack_v1.h
References _dca3d_z.
void SvtxTrack_v1::set_dca3d_z_error (float error) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 91 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 91 of file SvtxTrack_v1.h
References _dca3d_z_error, and acts::error.
void SvtxTrack_v1::set_dca_error (float dca_error) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 73 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 73 of file SvtxTrack_v1.h
References _dca_error.
void SvtxTrack_v1::set_error (int i, int j, float value) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 121 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 121 of file SvtxTrack_v1.h
References _states.
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
void SvtxTrack_v1::set_id (unsigned int id) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 50 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 50 of file SvtxTrack_v1.h
References _track_id, and train_ambiguity_solver::id.
Referenced by TpcPrototypeGenFitTrkFinder::process_event().
void SvtxTrack_v1::set_ndf (int ndf) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 65 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 65 of file SvtxTrack_v1.h
References _ndf.
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
void SvtxTrack_v1::set_positive_charge (bool ispos) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 56 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 56 of file SvtxTrack_v1.h
References _is_positive_charge.
Referenced by set_charge().
void SvtxTrack_v1::set_px (float px) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 105 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 105 of file SvtxTrack_v1.h
References _states.
Referenced by PHG4TrackFastSim::MakeSvtxTrack(), and TpcPrototypeGenFitTrkFinder::process_event().
void SvtxTrack_v1::set_py (float py) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 108 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 108 of file SvtxTrack_v1.h
References _states.
Referenced by PHG4TrackFastSim::MakeSvtxTrack(), and TpcPrototypeGenFitTrkFinder::process_event().
void SvtxTrack_v1::set_pz (float pz) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 111 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 111 of file SvtxTrack_v1.h
References _states.
Referenced by PHG4TrackFastSim::MakeSvtxTrack(), and TpcPrototypeGenFitTrkFinder::process_event().
void SvtxTrack_v1::set_vertex_id (unsigned int id) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 53 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 53 of file SvtxTrack_v1.h
References _vertex_id, and train_ambiguity_solver::id.
void SvtxTrack_v1::set_x (float x) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 94 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 94 of file SvtxTrack_v1.h
References _states.
Referenced by PHG4TrackFastSim::MakeSvtxTrack(), and TpcPrototypeGenFitTrkFinder::process_event().
void SvtxTrack_v1::set_y (float y) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 97 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 97 of file SvtxTrack_v1.h
References _states.
Referenced by PHG4TrackFastSim::MakeSvtxTrack(), and TpcPrototypeGenFitTrkFinder::process_event().
void SvtxTrack_v1::set_z (float z) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 100 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 100 of file SvtxTrack_v1.h
References _states.
Referenced by PHG4TrackFastSim::MakeSvtxTrack(), and TpcPrototypeGenFitTrkFinder::process_event().
size_t SvtxTrack_v1::size_cluster_keys () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 166 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 166 of file SvtxTrack_v1.h
References _cluster_keys.
size_t SvtxTrack_v1::size_clusters () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 152 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 152 of file SvtxTrack_v1.h
References _cluster_ids.
Referenced by PHG4TrackFastSimEval::fill_track_tree(), and FastTrackingEval::fill_tree().
size_t SvtxTrack_v1::size_states () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 127 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 127 of file SvtxTrack_v1.h
References _states.
Referenced by TrackProjectorPlaneECAL::project_track().
Member Data Documentation
std::map<CAL_LAYER, float> SvtxTrack_v1::_cal_cluster_e private
Definition at line 235 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 235 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_cal_cluster_e(), and set_cal_cluster_e().
std::map<CAL_LAYER, int> SvtxTrack_v1::_cal_cluster_id private
Definition at line 233 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 233 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_cal_cluster_id(), and set_cal_cluster_id().
std::map<CAL_LAYER, TrkrDefs::cluskey> SvtxTrack_v1::_cal_cluster_key private
Definition at line 234 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 234 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_cal_cluster_key(), and set_cal_cluster_key().
std::map<CAL_LAYER, float> SvtxTrack_v1::_cal_deta private
Definition at line 230 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 230 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_cal_deta(), and set_cal_deta().
std::map<CAL_LAYER, float> SvtxTrack_v1::_cal_dphi private
Definition at line 229 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 229 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_cal_dphi(), and set_cal_dphi().
std::map<CAL_LAYER, float> SvtxTrack_v1::_cal_energy_3x3 private
Definition at line 231 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 231 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_cal_energy_3x3(), and set_cal_energy_3x3().
std::map<CAL_LAYER, float> SvtxTrack_v1::_cal_energy_5x5 private
Definition at line 232 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 232 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_cal_energy_5x5(), and set_cal_energy_5x5().
float SvtxTrack_v1::_chisq = NAN private
Definition at line 206 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 206 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_chisq(), get_quality(), and set_chisq().
ClusterSet SvtxTrack_v1::_cluster_ids private
Definition at line 225 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 225 of file SvtxTrack_v1.h
Referenced by begin_clusters(), clear_clusters(), CopyFrom(), empty_clusters(), end_clusters(), erase_cluster(), find_cluster(), identify(), insert_cluster(), and size_clusters().
ClusterKeySet SvtxTrack_v1::_cluster_keys private
Definition at line 226 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 226 of file SvtxTrack_v1.h
Referenced by begin_cluster_keys(), clear_cluster_keys(), CopyFrom(), empty_cluster_keys(), end_cluster_keys(), erase_cluster_key(), find_cluster_key(), find_cluster_keys(), identify(), insert_cluster_key(), and size_cluster_keys().
float SvtxTrack_v1::_dca = NAN private
Definition at line 210 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 210 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_dca(), and set_dca().
float SvtxTrack_v1::_dca2d = NAN private
Definition at line 212 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 212 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_dca2d(), and set_dca2d().
float SvtxTrack_v1::_dca2d_error = NAN private
Definition at line 213 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 213 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_dca2d_error(), and set_dca2d_error().
float SvtxTrack_v1::_dca3d_xy = NAN private
Definition at line 214 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 214 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_dca3d_xy(), and set_dca3d_xy().
float SvtxTrack_v1::_dca3d_xy_error = NAN private
Definition at line 215 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 215 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_dca3d_xy_error(), and set_dca3d_xy_error().
float SvtxTrack_v1::_dca3d_z = NAN private
Definition at line 216 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 216 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_dca3d_z(), and set_dca3d_z().
float SvtxTrack_v1::_dca3d_z_error = NAN private
Definition at line 217 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 217 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_dca3d_z_error(), and set_dca3d_z_error().
float SvtxTrack_v1::_dca_error = NAN private
Definition at line 211 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 211 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_dca_error(), and set_dca_error().
bool SvtxTrack_v1::_is_positive_charge = false private
Definition at line 205 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 205 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_positive_charge(), and set_positive_charge().
unsigned int SvtxTrack_v1::_ndf = 0 private
Definition at line 207 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 207 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_ndf(), get_quality(), and set_ndf().
StateMap SvtxTrack_v1::_states private
Definition at line 222 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 222 of file SvtxTrack_v1.h
Referenced by begin_states(), clear_states(), CopyFrom(), count_states(), empty_states(), end_states(), erase_state(), find_state(), get_error(), get_mom(), get_pos(), get_px(), get_py(), get_pz(), get_state(), get_x(), get_y(), get_z(), insert_state(), set_error(), set_px(), set_py(), set_pz(), set_x(), set_y(), set_z(), size_states(), and SvtxTrack_v1().
unsigned int SvtxTrack_v1::_track_id = UINT_MAX private
Definition at line 203 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 203 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_id(), and set_id().
unsigned int SvtxTrack_v1::_vertex_id = UINT_MAX private
Definition at line 204 of file SvtxTrack_v1.h.
View newest version in sPHENIX GitHub at line 204 of file SvtxTrack_v1.h
Referenced by CopyFrom(), get_vertex_id(), and set_vertex_id().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack_v1.cc