Analysis Software: mvtx::ChipPixelData Class Reference
mvtx::ChipPixelData Class Reference
#include <online_distribution/blob/master/newbasic/mvtx_decoder/PixelData.h>
Public Member Functions
ChipPixelData ()=default
~ChipPixelData ()=default
uint16_t getChipID () const
const std::vector< PixelData > & getData () const
std::vector< PixelData > & getData ()
void setChipID (uint16_t id)
void setError (ChipStat::DecErrors i)
void addErrorInfo (uint64_t b)
void setErrorFlags (uint32_t f)
bool isErrorSet (ChipStat::DecErrors i) const
bool isErrorSet () const
auto getErrorFlags () const
auto getErrorInfo () const
auto getNBytesInRawBuff () const
void setNBytesInRawBuff (int n)
auto & getRawErrBuff ()
auto & getRawErrBuff () const
std::string getErrorDetails (int pos) const
void resetChipID ()
void clear ()
void swap (ChipPixelData &other)
void print () const
Static Public Attributes
static constexpr size_t MAXDATAERRBYTES = 16
static constexpr size_t MAXDATAERRBYTES_AFTER = 2
Private Attributes
uint16_t mChipID = 0
uint32_t mErrors = 0
uint64_t mErrorInfo = 0
std::array< uint8_t,
MAXDATAERRBYTES > mRawBuff {}
std::vector< PixelData > mPixels
Detailed Description
Definition at line 33 of file PixelData.h.
View newest version in sPHENIX GitHub at line 33 of file PixelData.h
Constructor & Destructor Documentation
mvtx::ChipPixelData::ChipPixelData () default
mvtx::ChipPixelData::~ChipPixelData () default
Member Function Documentation
void mvtx::ChipPixelData::addErrorInfo (uint64_t b) inline
Definition at line 50 of file PixelData.h.
View newest version in sPHENIX GitHub at line 50 of file PixelData.h
References KFPMath::b, and mErrorInfo.
void mvtx::ChipPixelData::clear () inline
Definition at line 67 of file PixelData.h.
View newest version in sPHENIX GitHub at line 67 of file PixelData.h
References mErrorInfo, mErrors, mPixels, and resetChipID().
uint16_t mvtx::ChipPixelData::getChipID () const inline
Definition at line 41 of file PixelData.h.
View newest version in sPHENIX GitHub at line 41 of file PixelData.h
References mChipID.
const std::vector<PixelData>& mvtx::ChipPixelData::getData () const inline
Definition at line 42 of file PixelData.h.
View newest version in sPHENIX GitHub at line 42 of file PixelData.h
References mPixels.
std::vector<PixelData>& mvtx::ChipPixelData::getData () inline
Definition at line 43 of file PixelData.h.
View newest version in sPHENIX GitHub at line 43 of file PixelData.h
References mPixels.
std::string ChipPixelData::getErrorDetails (int pos) const
Definition at line 23 of file PixelData.cxx.
View newest version in sPHENIX GitHub at line 23 of file PixelData.cxx
References getNBytesInRawBuff(), getRawErrBuff(), i, mErrorInfo, mvtx::ChipStat::RepeatingPixel, and mvtx::ChipStat::UnknownWord.
auto mvtx::ChipPixelData::getErrorFlags () const inline
Definition at line 54 of file PixelData.h.
View newest version in sPHENIX GitHub at line 54 of file PixelData.h
References mErrors.
Referenced by mvtx::ChipStat::addErrors().
auto mvtx::ChipPixelData::getErrorInfo () const inline
Definition at line 55 of file PixelData.h.
View newest version in sPHENIX GitHub at line 55 of file PixelData.h
References mErrorInfo.
auto mvtx::ChipPixelData::getNBytesInRawBuff () const inline
Definition at line 56 of file PixelData.h.
View newest version in sPHENIX GitHub at line 56 of file PixelData.h
References mErrorInfo.
Referenced by getErrorDetails().
auto& mvtx::ChipPixelData::getRawErrBuff () inline
Definition at line 58 of file PixelData.h.
View newest version in sPHENIX GitHub at line 58 of file PixelData.h
References mRawBuff.
Referenced by getErrorDetails().
auto& mvtx::ChipPixelData::getRawErrBuff () const inline
Definition at line 59 of file PixelData.h.
View newest version in sPHENIX GitHub at line 59 of file PixelData.h
References mRawBuff.
bool mvtx::ChipPixelData::isErrorSet (ChipStat::DecErrors i) const inline
Definition at line 52 of file PixelData.h.
View newest version in sPHENIX GitHub at line 52 of file PixelData.h
References i, and mErrors.
bool mvtx::ChipPixelData::isErrorSet () const inline
Definition at line 53 of file PixelData.h.
View newest version in sPHENIX GitHub at line 53 of file PixelData.h
References mErrors.
void ChipPixelData::print () const
Definition at line 12 of file PixelData.cxx.
View newest version in sPHENIX GitHub at line 12 of file PixelData.cxx
References InttDefs::getCol(), InttDefs::getRow(), i, mChipID, mPixels, and printf().
void mvtx::ChipPixelData::resetChipID () inline
Definition at line 62 of file PixelData.h.
View newest version in sPHENIX GitHub at line 62 of file PixelData.h
References mChipID.
Referenced by clear().
void mvtx::ChipPixelData::setChipID (uint16_t id) inline
Definition at line 46 of file PixelData.h.
View newest version in sPHENIX GitHub at line 46 of file PixelData.h
References train_ambiguity_solver::id, and mChipID.
void mvtx::ChipPixelData::setError (ChipStat::DecErrors i) inline
Definition at line 49 of file PixelData.h.
View newest version in sPHENIX GitHub at line 49 of file PixelData.h
References i, and mErrors.
void mvtx::ChipPixelData::setErrorFlags (uint32_t f) inline
Definition at line 51 of file PixelData.h.
View newest version in sPHENIX GitHub at line 51 of file PixelData.h
References f, and mErrors.
void mvtx::ChipPixelData::setNBytesInRawBuff (int n) inline
Definition at line 57 of file PixelData.h.
View newest version in sPHENIX GitHub at line 57 of file PixelData.h
References mErrorInfo.
void mvtx::ChipPixelData::swap (ChipPixelData & other) inline
Definition at line 75 of file PixelData.h.
View newest version in sPHENIX GitHub at line 75 of file PixelData.h
References mChipID, mErrors, mPixels, and swap().
Member Data Documentation
constexpr size_t mvtx::ChipPixelData::MAXDATAERRBYTES = 16 static
Definition at line 38 of file PixelData.h.
View newest version in sPHENIX GitHub at line 38 of file PixelData.h
constexpr size_t mvtx::ChipPixelData::MAXDATAERRBYTES_AFTER = 2 static
Definition at line 38 of file PixelData.h.
View newest version in sPHENIX GitHub at line 38 of file PixelData.h
uint16_t mvtx::ChipPixelData::mChipID = 0 private
Definition at line 85 of file PixelData.h.
View newest version in sPHENIX GitHub at line 85 of file PixelData.h
Referenced by getChipID(), print(), resetChipID(), setChipID(), and swap().
uint64_t mvtx::ChipPixelData::mErrorInfo = 0 private
Definition at line 87 of file PixelData.h.
View newest version in sPHENIX GitHub at line 87 of file PixelData.h
Referenced by addErrorInfo(), clear(), getErrorDetails(), getErrorInfo(), getNBytesInRawBuff(), and setNBytesInRawBuff().
uint32_t mvtx::ChipPixelData::mErrors = 0 private
Definition at line 86 of file PixelData.h.
View newest version in sPHENIX GitHub at line 86 of file PixelData.h
Referenced by clear(), getErrorFlags(), isErrorSet(), setError(), setErrorFlags(), and swap().
std::vector<PixelData> mvtx::ChipPixelData::mPixels private
Definition at line 89 of file PixelData.h.
View newest version in sPHENIX GitHub at line 89 of file PixelData.h
Referenced by clear(), getData(), print(), and swap().
std::array<uint8_t, MAXDATAERRBYTES> mvtx::ChipPixelData::mRawBuff {} private
Definition at line 88 of file PixelData.h.
View newest version in sPHENIX GitHub at line 88 of file PixelData.h
Referenced by getRawErrBuff().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/mvtx_decoder/PixelData.h
online_distribution/blob/master/newbasic/mvtx_decoder/PixelData.cxx