Analysis Software: MatrixCache< T > Class Template Reference
MatrixCache< T > Class Template Reference
#include <prototype/blob/master/offline/packages/MvtxPrototype2/MvtxPrototype2Geom.h>
Public Member Functions
MatrixCache ()=default
~MatrixCache ()=default
MatrixCache (const MatrixCache &src)=delete
MatrixCache & operator= (const MatrixCache src)=delete
void setSize (int s)
set size of matrix cache
int getSize () const
get the size of the cache
void setMatrix (const T &mat, int sensID)
assign matrix to a slot
const T & getMatrix (int sensID) const
bool isFilled () const
Private Attributes
std::vector< T > m_cache
Detailed Description
template<typename T = TGeoHMatrix>
class MatrixCache< T >
Definition at line 24 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 24 of file MvtxPrototype2Geom.h
Constructor & Destructor Documentation
template<typename T = TGeoHMatrix> MatrixCache< T >::MatrixCache () default
template<typename T = TGeoHMatrix> MatrixCache< T >::~MatrixCache () default
template<typename T = TGeoHMatrix> MatrixCache< T >::MatrixCache (const MatrixCache< T > & src) delete
Member Function Documentation
template<typename T = TGeoHMatrix> const T& MatrixCache< T >::getMatrix (int sensID) const inline
Definition at line 51 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 51 of file MvtxPrototype2Geom.h
Referenced by MvtxPrototype2Geom::getMatrixL2G().
template<typename T = TGeoHMatrix> int MatrixCache< T >::getSize () const inline
get the size of the cache
Definition at line 40 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 40 of file MvtxPrototype2Geom.h
template<typename T = TGeoHMatrix> bool MatrixCache< T >::isFilled () const inline
Definition at line 52 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 52 of file MvtxPrototype2Geom.h
template<typename T = TGeoHMatrix> MatrixCache& MatrixCache< T >::operator= (const MatrixCache< T > src) delete
template<typename T = TGeoHMatrix> void MatrixCache< T >::setMatrix (const T & mat, int sensID) inline
assign matrix to a slot
Definition at line 42 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 42 of file MvtxPrototype2Geom.h
Referenced by MvtxPrototype2Geom::fillMatrixCache().
template<typename T = TGeoHMatrix> void MatrixCache< T >::setSize (int s) inline
set size of matrix cache
Definition at line 33 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 33 of file MvtxPrototype2Geom.h
Referenced by MvtxPrototype2Geom::fillMatrixCache().
Member Data Documentation
template<typename T = TGeoHMatrix> std::vector<T> MatrixCache< T >::m_cache private
Definition at line 55 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 55 of file MvtxPrototype2Geom.h
Referenced by MatrixCache< TGeoHMatrix >::getMatrix(), MatrixCache< TGeoHMatrix >::getSize(), MatrixCache< TGeoHMatrix >::isFilled(), MatrixCache< TGeoHMatrix >::setMatrix(), and MatrixCache< TGeoHMatrix >::setSize().
The documentation for this class was generated from the following file:
prototype/blob/master/offline/packages/MvtxPrototype2/MvtxPrototype2Geom.h