Analysis Software: test_examples Namespace Reference
test_examples Namespace Reference
Functions
def field
def seq
def assert_csv_output
def assert_entries
def assert_has_entries
def test_pythia8
def test_fatras
def test_geant4
def test_seeding
def test_seeding_orthogonal
def test_itk_seeding
def test_propagation
def test_material_recording
def test_event_recording
def test_truth_tracking_kalman
def test_truth_tracking_gsf
def test_particle_gun
def test_material_mapping
def test_volume_material_mapping
def test_geometry_example
def test_digitization_example
def test_digitization_example_input
def test_digitization_config_example
def test_ckf_tracks_example
def test_full_chain_odd_example
def test_full_chain_odd_example_pythia_geant4
def test_ML_Ambiguity_Solver
def test_bfield_writing
def test_exatrkx
Variables
tuple pytestmark pytest.mark.skipif(not rootEnabled, reason="ROOT not set up")
u acts.UnitConstants
tuple DIGI_SHARE_DIR
list ids ["smeared", "geometric"]
Function Documentation
def test_examples.assert_csv_output (csv_path, stem)
Definition at line 52 of file test_examples.py.
View newest version in sPHENIX GitHub at line 52 of file test_examples.py
Referenced by test_fatras(), test_geant4(), test_itk_seeding(), test_pythia8(), test_seeding(), and test_seeding_orthogonal().
def test_examples.assert_entries (root_file, tree_name, exp = None, non_zero = False)
Definition at line 59 of file test_examples.py.
View newest version in sPHENIX GitHub at line 59 of file test_examples.py
References print(), and str.
Referenced by assert_has_entries(), test_bfield_writing(), test_digitization_example(), test_digitization_example_input(), test_material_mapping(), test_material_recording(), test_particle_gun(), test_propagation(), test_pythia8(), and test_volume_material_mapping().
def test_examples.assert_has_entries (root_file, tree_name)
Definition at line 76 of file test_examples.py.
View newest version in sPHENIX GitHub at line 76 of file test_examples.py
References assert_entries().
Referenced by test_digitization_example(), test_digitization_example_input(), test_fatras(), test_itk_seeding(), test_seeding(), test_seeding_orthogonal(), and test_truth_tracking_kalman().
def test_examples.field ()
Definition at line 43 of file test_examples.py.
View newest version in sPHENIX GitHub at line 43 of file test_examples.py
def test_examples.seq ()
Definition at line 48 of file test_examples.py.
View newest version in sPHENIX GitHub at line 48 of file test_examples.py
def test_examples.test_bfield_writing (tmp_path, seq, assert_root_hash)
Definition at line 1256 of file test_examples.py.
View newest version in sPHENIX GitHub at line 1256 of file test_examples.py
References assert_entries(), conftest.assert_root_hash(), and bfield_writing.runBFieldWriting().
def test_examples.test_ckf_tracks_example (tmp_path, assert_root_hash, truthSmeared, truthEstimated, detector_config)
Definition at line 1077 of file test_examples.py.
View newest version in sPHENIX GitHub at line 1077 of file test_examples.py
References conftest.assert_root_hash(), Acts::Concepts.exists, and ckf.runCKFTracks().
Referenced by test_digitization_config_example().
def test_examples.test_digitization_config_example (trk_geo, tmp_path)
Definition at line 1038 of file test_examples.py.
View newest version in sPHENIX GitHub at line 1038 of file test_examples.py
References digitization_config.runDigitizationConfig(), and test_ckf_tracks_example().
def test_examples.test_digitization_example (trk_geo, tmp_path, assert_root_hash, digi_config_file)
Definition at line 914 of file test_examples.py.
View newest version in sPHENIX GitHub at line 914 of file test_examples.py
References assert_entries(), assert_has_entries(), conftest.assert_root_hash(), digitization.runDigitization(), and test_digitization_example_input().
def test_examples.test_digitization_example_input (trk_geo, tmp_path, assert_root_hash, digi_config_file)
Definition at line 970 of file test_examples.py.
View newest version in sPHENIX GitHub at line 970 of file test_examples.py
References assert_entries(), assert_has_entries(), conftest.assert_root_hash(), digitization.runDigitization(), particle_gun.runParticleGun(), and str.
Referenced by test_digitization_example().
def test_examples.test_event_recording (tmp_path)
Definition at line 503 of file test_examples.py.
View newest version in sPHENIX GitHub at line 503 of file test_examples.py
References print(), str, and test_truth_tracking_kalman().
def test_examples.test_exatrkx (tmp_path, trk_geo, field, assert_root_hash, backend, hardware)
Definition at line 1281 of file test_examples.py.
View newest version in sPHENIX GitHub at line 1281 of file test_examples.py
References conftest.assert_root_hash(), Acts::Concepts.exists, print(), and str.
def test_examples.test_fatras (trk_geo, tmp_path, field, assert_root_hash)
Definition at line 107 of file test_examples.py.
View newest version in sPHENIX GitHub at line 107 of file test_examples.py
References assert_csv_output(), assert_has_entries(), conftest.assert_root_hash(), Acts::Concepts.exists, utils.run, runFatras(), and str.
def test_examples.test_full_chain_odd_example (tmp_path)
Definition at line 1147 of file test_examples.py.
View newest version in sPHENIX GitHub at line 1147 of file test_examples.py
References acts.examples.odd.getOpenDataDetector(), common.getOpenDataDetectorDirectory(), print(), and str.
def test_examples.test_full_chain_odd_example_pythia_geant4 (tmp_path)
Definition at line 1179 of file test_examples.py.
View newest version in sPHENIX GitHub at line 1179 of file test_examples.py
References acts.examples.odd.getOpenDataDetector(), common.getOpenDataDetectorDirectory(), print(), and str.
def test_examples.test_geant4 (tmp_path, assert_root_hash)
Definition at line 155 of file test_examples.py.
View newest version in sPHENIX GitHub at line 155 of file test_examples.py
References assert_csv_output(), conftest.assert_root_hash(), Acts::Concepts.exists, acts.examples.odd.getOpenDataDetector(), common.getOpenDataDetectorDirectory(), print(), and str.
def test_examples.test_geometry_example (geoFactory, nobj, tmp_path)
Definition at line 846 of file test_examples.py.
View newest version in sPHENIX GitHub at line 846 of file test_examples.py
References geometry.runGeometry(), and str.
def test_examples.test_itk_seeding (tmp_path, trk_geo, field, assert_root_hash)
Definition at line 326 of file test_examples.py.
View newest version in sPHENIX GitHub at line 326 of file test_examples.py
References acts.examples.simulation.addDigitization(), acts.examples.simulation.addFatras(), acts.examples.simulation.addParticleGun(), acts.examples.reconstruction.addSeeding(), assert_csv_output(), assert_has_entries(), conftest.assert_root_hash(), acts.examples.simulation.EtaConfig, acts.examples.itk.itkSeedingAlgConfig(), acts.examples.simulation.MomentumConfig, acts.examples.simulation.ParticleConfig, str, and acts.examples.reconstruction.TruthSeedRanges.
def test_examples.test_material_mapping (material_recording, tmp_path, assert_root_hash)
Definition at line 674 of file test_examples.py.
View newest version in sPHENIX GitHub at line 674 of file test_examples.py
References assert_entries(), conftest.assert_root_hash(), acts.examples.odd.getOpenDataDetector(), common.getOpenDataDetectorDirectory(), runMaterialMapping(), material_validation.runMaterialValidation(), and str.
def test_examples.test_material_recording (tmp_path, material_recording, assert_root_hash)
Definition at line 481 of file test_examples.py.
View newest version in sPHENIX GitHub at line 481 of file test_examples.py
References assert_entries(), and conftest.assert_root_hash().
def test_examples.test_ML_Ambiguity_Solver (tmp_path, assert_root_hash)
Definition at line 1220 of file test_examples.py.
View newest version in sPHENIX GitHub at line 1220 of file test_examples.py
References conftest.assert_root_hash(), Acts::Concepts.exists, acts.examples.odd.getOpenDataDetector(), common.getOpenDataDetectorDirectory(), print(), and str.
def test_examples.test_particle_gun (tmp_path, assert_root_hash)
Definition at line 647 of file test_examples.py.
View newest version in sPHENIX GitHub at line 647 of file test_examples.py
References assert_entries(), conftest.assert_root_hash(), utils.run, particle_gun.runParticleGun(), and str.
def test_examples.test_propagation (tmp_path, trk_geo, field, seq, assert_root_hash)
Definition at line 445 of file test_examples.py.
View newest version in sPHENIX GitHub at line 445 of file test_examples.py
References assert_entries(), conftest.assert_root_hash(), utils.run, propagation.runPropagation(), and str.
def test_examples.test_pythia8 (tmp_path, seq, assert_root_hash)
Definition at line 83 of file test_examples.py.
View newest version in sPHENIX GitHub at line 83 of file test_examples.py
References assert_csv_output(), assert_entries(), conftest.assert_root_hash(), Acts::Concepts.exists, utils.run, pythia8.runPythia8(), and str.
def test_examples.test_seeding (tmp_path, trk_geo, field, assert_root_hash)
Definition at line 206 of file test_examples.py.
View newest version in sPHENIX GitHub at line 206 of file test_examples.py
References assert_csv_output(), assert_has_entries(), conftest.assert_root_hash(), utils.run, runSeeding(), and str.
def test_examples.test_seeding_orthogonal (tmp_path, trk_geo, field, assert_root_hash)
Definition at line 263 of file test_examples.py.
View newest version in sPHENIX GitHub at line 263 of file test_examples.py
References assert_csv_output(), assert_has_entries(), conftest.assert_root_hash(), utils.run, runSeeding(), and str.
def test_examples.test_truth_tracking_gsf (tmp_path, assert_root_hash, detector_config)
Definition at line 598 of file test_examples.py.
View newest version in sPHENIX GitHub at line 598 of file test_examples.py
References conftest.assert_root_hash(), helpers.failure_threshold(), and truth_tracking_gsf.runTruthTrackingGsf().
def test_examples.test_truth_tracking_kalman (tmp_path, assert_root_hash, revFiltMomThresh, detector_config)
Definition at line 559 of file test_examples.py.
View newest version in sPHENIX GitHub at line 559 of file test_examples.py
References assert_has_entries(), conftest.assert_root_hash(), and truth_tracking_kalman.runTruthTrackingKalman().
Referenced by test_event_recording().
def test_examples.test_volume_material_mapping (material_recording, tmp_path, assert_root_hash)
Definition at line 747 of file test_examples.py.
View newest version in sPHENIX GitHub at line 747 of file test_examples.py
References assert_entries(), conftest.assert_root_hash(), acts.examples.odd.getOpenDataDetector(), common.getOpenDataDetectorDirectory(), runMaterialMapping(), material_validation.runMaterialValidation(), and str.
Variable Documentation
tuple test_examples.DIGI_SHARE_DIR
Initial value:
 (
     Path(__file__).parent.parent.parent.parent
     / "Examples/Algorithms/Digitization/share"
 )
Definition at line 900 of file test_examples.py.
View newest version in sPHENIX GitHub at line 900 of file test_examples.py
list test_examples.ids ["smeared", "geometric"]
Definition at line 912 of file test_examples.py.
View newest version in sPHENIX GitHub at line 912 of file test_examples.py
Referenced by X_Event.change_id(), Acts::GeometryView3D.drawTrackingVolume(), and CDBTTree.WriteMultipleCDBTTree().
tuple test_examples.pytestmark pytest.mark.skipif(not rootEnabled, reason="ROOT not set up")
Definition at line 26 of file test_examples.py.
View newest version in sPHENIX GitHub at line 26 of file test_examples.py
test_examples.u acts.UnitConstants
Definition at line 39 of file test_examples.py.
View newest version in sPHENIX GitHub at line 39 of file test_examples.py