Analysis Software: InttDeadMapv1 Class Reference
InttDeadMapv1 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4intt/InttDeadMapv1.h>
Public Member Functions
InttDeadMapv1 ()
~InttDeadMapv1 () override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
void addDeadChannel (PHG4CellDefs::keytype key) override
bool isDeadChannel (PHG4CellDefs::keytype key) const override
const Map & getDeadChannels (void) const override
return all towers
Map & getDeadChannels (void) override
unsigned int size () const override
Public Member Functions inherited from InttDeadMap
~InttDeadMap () override
void addDeadChannelIntt (const int layer, const int ladder_phi, const int ladder_z, const int strip_z, const int strip_phi)
bool isDeadChannelIntt (const int layer, const int ladder_phi, const int ladder_z, const int strip_z, const int strip_phi) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
Map m_DeadChannels
Additional Inherited Members
Public Types inherited from InttDeadMap
typedef std::set
< PHG4CellDefs::keytype > Map
Static Public Member Functions inherited from InttDeadMap
static PHG4CellDefs::keytype getInttKey (int layer, int ladder_phi, int ladder_z, int strip_z, int strip_phi)
static int getWildCardID ()
Protected Member Functions inherited from InttDeadMap
InttDeadMap ()
Detailed Description
Definition at line 10 of file InttDeadMapv1.h.
View newest version in sPHENIX GitHub at line 10 of file InttDeadMapv1.h
Constructor & Destructor Documentation
InttDeadMapv1::InttDeadMapv1 () inline
Definition at line 13 of file InttDeadMapv1.h.
View newest version in sPHENIX GitHub at line 13 of file InttDeadMapv1.h
InttDeadMapv1::~InttDeadMapv1 () inline override
Definition at line 16 of file InttDeadMapv1.h.
View newest version in sPHENIX GitHub at line 16 of file InttDeadMapv1.h
Member Function Documentation
void InttDeadMapv1::addDeadChannel (PHG4CellDefs::keytype key) override virtual
Reimplemented from InttDeadMap.
Definition at line 20 of file InttDeadMapv1.cc.
View newest version in sPHENIX GitHub at line 20 of file InttDeadMapv1.cc
References m_DeadChannels.
const InttDeadMapv1::Map & InttDeadMapv1::getDeadChannels (void) const override virtual
return all towers
Reimplemented from InttDeadMap.
Definition at line 9 of file InttDeadMapv1.cc.
View newest version in sPHENIX GitHub at line 9 of file InttDeadMapv1.cc
References m_DeadChannels.
InttDeadMapv1::Map & InttDeadMapv1::getDeadChannels (void) override virtual
Reimplemented from InttDeadMap.
Definition at line 15 of file InttDeadMapv1.cc.
View newest version in sPHENIX GitHub at line 15 of file InttDeadMapv1.cc
References m_DeadChannels.
void InttDeadMapv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from InttDeadMap.
Definition at line 45 of file InttDeadMapv1.cc.
View newest version in sPHENIX GitHub at line 45 of file InttDeadMapv1.cc
References size().
bool InttDeadMapv1::isDeadChannel (PHG4CellDefs::keytype key) const override virtual
Reimplemented from InttDeadMap.
Definition at line 25 of file InttDeadMapv1.cc.
View newest version in sPHENIX GitHub at line 25 of file InttDeadMapv1.cc
References it, and m_DeadChannels.
int InttDeadMapv1::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from InttDeadMap.
Definition at line 35 of file InttDeadMapv1.cc.
View newest version in sPHENIX GitHub at line 35 of file InttDeadMapv1.cc
References size().
void InttDeadMapv1::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 40 of file InttDeadMapv1.cc.
View newest version in sPHENIX GitHub at line 40 of file InttDeadMapv1.cc
References m_DeadChannels.
unsigned int InttDeadMapv1::size (void) const inline override virtual
Reimplemented from InttDeadMap.
Definition at line 30 of file InttDeadMapv1.h.
View newest version in sPHENIX GitHub at line 30 of file InttDeadMapv1.h
References m_DeadChannels.
Referenced by identify(), and isValid().
Member Data Documentation
Map InttDeadMapv1::m_DeadChannels private
Definition at line 33 of file InttDeadMapv1.h.
View newest version in sPHENIX GitHub at line 33 of file InttDeadMapv1.h
Referenced by addDeadChannel(), getDeadChannels(), isDeadChannel(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4intt/InttDeadMapv1.h
coresoftware/blob/master/simulation/g4simulation/g4intt/InttDeadMapv1.cc