Analysis Software: ActsTrackFittingAlgorithm Exception Reference
ActsTrackFittingAlgorithm Exception Reference final
#include <coresoftware/blob/master/offline/packages/trackbase/ActsTrackFittingAlgorithm.h>
Classes
struct Config
class DirectedTrackFitterFunction
struct GeneralFitterOptions
class TrackFitterFunction
Public Types
using TrackParameters = ::Acts::BoundTrackParameters
using Measurement = ::Acts::BoundVariantMeasurement
using MeasurementContainer = std::vector< Measurement >
using TrackContainer = Acts::TrackContainer< Acts::VectorTrackContainer, Acts::VectorMultiTrajectory, std::shared_ptr >
using TrackFitterResult = Acts::Result< TrackContainer::TrackProxy >
Public Member Functions
ActsTrackFittingAlgorithm (Config config, Acts::Logging::Level level)
const Config & config () const
Get readonly access to the config parameters.
Static Public Member Functions
static std::shared_ptr
< TrackFitterFunction > makeKalmanFitterFunction (std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, std::shared_ptr< const Acts::MagneticFieldProvider > magneticField, bool multipleScattering=true, bool energyLoss=true, double reverseFilteringMomThreshold=0.0, Acts::FreeToBoundCorrection freeToBoundCorrection=Acts::FreeToBoundCorrection(), const Acts::Logger &logger=*Acts::getDefaultLogger("Kalman", Acts::Logging::FATAL))
static std::shared_ptr
< DirectedTrackFitterFunction > makeDirectedKalmanFitterFunction (std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, std::shared_ptr< const Acts::MagneticFieldProvider > magneticField, bool multipleScattering=true, bool energyLoss=true, double reverseFilteringMomThreshold=0.0, Acts::FreeToBoundCorrection freeToBoundCorrection=Acts::FreeToBoundCorrection(), const Acts::Logger &logger=*Acts::getDefaultLogger("Kalman", Acts::Logging::FATAL))
Private Member Functions
TrackFitterResult fitTrack (const std::vector< Acts::SourceLink > &sourceLinks, const TrackParameters &initialParameters, const GeneralFitterOptions &options, const std::vector< const Acts::Surface * > &surfSequence, const CalibratorAdapter &calibrator, TrackContainer &tracks) const
Helper function to call correct FitterFunction.
Private Attributes
Config m_cfg
Detailed Description
Definition at line 39 of file ActsTrackFittingAlgorithm.h.
View newest version in sPHENIX GitHub at line 39 of file ActsTrackFittingAlgorithm.h
Member Typedef Documentation
using ActsTrackFittingAlgorithm::Measurement = ::Acts::BoundVariantMeasurement
Definition at line 43 of file ActsTrackFittingAlgorithm.h.
View newest version in sPHENIX GitHub at line 43 of file ActsTrackFittingAlgorithm.h
using ActsTrackFittingAlgorithm::MeasurementContainer = std::vector<Measurement>
Definition at line 44 of file ActsTrackFittingAlgorithm.h.
View newest version in sPHENIX GitHub at line 44 of file ActsTrackFittingAlgorithm.h
using ActsTrackFittingAlgorithm::TrackContainer = Acts::TrackContainer<Acts::VectorTrackContainer, Acts::VectorMultiTrajectory, std::shared_ptr>
Definition at line 48 of file ActsTrackFittingAlgorithm.h.
View newest version in sPHENIX GitHub at line 48 of file ActsTrackFittingAlgorithm.h
using ActsTrackFittingAlgorithm::TrackFitterResult = Acts::Result<TrackContainer::TrackProxy>
Definition at line 50 of file ActsTrackFittingAlgorithm.h.
View newest version in sPHENIX GitHub at line 50 of file ActsTrackFittingAlgorithm.h
using ActsTrackFittingAlgorithm::TrackParameters = ::Acts::BoundTrackParameters
Definition at line 42 of file ActsTrackFittingAlgorithm.h.
View newest version in sPHENIX GitHub at line 42 of file ActsTrackFittingAlgorithm.h
Constructor & Destructor Documentation
ActsTrackFittingAlgorithm::ActsTrackFittingAlgorithm (Config config, Acts::Logging::Level level)
Constructor of the fitting algorithm
Parameters
config is the config struct to configure the algorihtm
level is the logging level
Member Function Documentation
const Config& ActsTrackFittingAlgorithm::config () const inline
Get readonly access to the config parameters.
Definition at line 112 of file ActsTrackFittingAlgorithm.h.
View newest version in sPHENIX GitHub at line 112 of file ActsTrackFittingAlgorithm.h
References m_cfg.
ActsTrackFittingAlgorithm::TrackFitterResult ActsTrackFittingAlgorithm::fitTrack (const std::vector< Acts::SourceLink > & sourceLinks, const TrackParameters & initialParameters, const GeneralFitterOptions & options, const std::vector< const Acts::Surface * > & surfSequence, const CalibratorAdapter & calibrator, TrackContainer & tracks) const inline private
Helper function to call correct FitterFunction.
Definition at line 157 of file ActsTrackFittingAlgorithm.h.
View newest version in sPHENIX GitHub at line 157 of file ActsTrackFittingAlgorithm.h
References ActsTrackFittingAlgorithm::Config::dFit, ActsTrackFittingAlgorithm::Config::directNavigation, ActsTrackFittingAlgorithm::Config::fit, m_cfg, ckf::options, and tracks().
std::shared_ptr< ActsTrackFittingAlgorithm::DirectedTrackFitterFunction > ActsTrackFittingAlgorithm::makeDirectedKalmanFitterFunction (std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, std::shared_ptr< const Acts::MagneticFieldProvider > magneticField, bool multipleScattering = true, bool energyLoss = true, double reverseFilteringMomThreshold = 0.0, Acts::FreeToBoundCorrection freeToBoundCorrection = Acts::FreeToBoundCorrection(), const Acts::Logger & logger = *Acts::getDefaultLogger("Kalman", Acts::Logging::FATAL)) static
Definition at line 237 of file TrackFittingAlgorithmFunctionsKalman.cc.
View newest version in sPHENIX GitHub at line 237 of file TrackFittingAlgorithmFunctionsKalman.cc
References Acts::Logger::cloneWithSuffix(), testing::internal::move(), Acts::Test::navigator, propagation_timing::stepper, and digitization_config::trackingGeometry.
Referenced by PHActsTrkFitter::InitRun().
std::shared_ptr< ActsTrackFittingAlgorithm::TrackFitterFunction > ActsTrackFittingAlgorithm::makeKalmanFitterFunction (std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, std::shared_ptr< const Acts::MagneticFieldProvider > magneticField, bool multipleScattering = true, bool energyLoss = true, double reverseFilteringMomThreshold = 0.0, Acts::FreeToBoundCorrection freeToBoundCorrection = Acts::FreeToBoundCorrection(), const Acts::Logger & logger = *Acts::getDefaultLogger("Kalman", Acts::Logging::FATAL)) static
Create the track fitter function implementation.
The magnetic field is intentionally given by-value since the variant contains shared_ptr anyways.
Parameters
trackingGeometry
multipleScattering correct for MCS (mainly for debugging)
energyLoss correct for e-loss
reverseFilteringMomThreshold at which threshold
freeToBoundCorrection Correction for non-linearity effect during transform from free to bound
Definition at line 203 of file TrackFittingAlgorithmFunctionsKalman.cc.
View newest version in sPHENIX GitHub at line 203 of file TrackFittingAlgorithmFunctionsKalman.cc
References cfg, Acts::Logger::cloneWithSuffix(), testing::internal::move(), Acts::Test::navigator, propagation_timing::stepper, and digitization_config::trackingGeometry.
Referenced by PHCosmicsTrkFitter::InitRun(), and PHActsTrkFitter::InitRun().
Member Data Documentation
Config ActsTrackFittingAlgorithm::m_cfg private
Definition at line 153 of file ActsTrackFittingAlgorithm.h.
View newest version in sPHENIX GitHub at line 153 of file ActsTrackFittingAlgorithm.h
Referenced by config(), and fitTrack().
The documentation for this exception was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/ActsTrackFittingAlgorithm.h
coresoftware/blob/master/offline/packages/trackbase/TrackFittingAlgorithmFunctionsKalman.cc