Analysis Software: PHTpcResiduals Class Reference
PHTpcResiduals Class Reference
#include <coresoftware/blob/master/offline/packages/tpccalib/PHTpcResiduals.h>
Public Member Functions
PHTpcResiduals (const std::string &name="PHTpcResiduals")
~PHTpcResiduals () override=default
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void setMaxTrackAlpha (float maxTAlpha)
Option for setting distortion correction calculation limits.
void setMaxTrackBeta (float maxTBeta)
void setMaxTrackResidualDrphi (float maxResidualDrphi)
void setMaxTrackResidualDz (float maxResidualDz)
void setGridDimensions (const int phiBins, const int rBins, const int zBins)
void setSavehistograms (bool value)
set to true to store evaluation histograms and ntuples
void setOutputfile (std::string outputfile)
output file name for storing the space charge reconstruction matrices
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int getNodes (PHCompositeNode *topNode)
int createNodes (PHCompositeNode *topNode)
int processTracks (PHCompositeNode *topNode)
bool checkTrack (SvtxTrack *track)
void processTrack (SvtxTrack *track)
void calculateTpcResiduals (const Acts::BoundTrackParameters &params, const TrkrCluster *cluster)
BoundTrackParamPtrResult propagateTrackState (const Acts::BoundTrackParameters &params, const SourceLink &sl)
int getCell (const Acts::Vector3D &loc)
Gets distortion cell for identifying bins in TPC.
void makeHistograms ()
SourceLink makeSourceLink (TrkrCluster *cluster)
Acts::BoundTrackParameters makeTrackParams (SvtxTrack *track)
Surface getSurface (TrkrDefs::cluskey cluskey, TrkrDefs::subsurfkey)
Surface getSiliconSurface (TrkrDefs::hitsetkey hitsetkey)
Surface getTpcSurface (TrkrDefs::hitsetkey hitsetkey, TrkrDefs::subsurfkey surfkey)
Surface getMMSurface (TrkrDefs::hitsetkey hitsetkey)
Acts::Vector3D getVertex (SvtxTrack *track)
Private Attributes
SvtxVertexMap * m_vertexMap = nullptr
SvtxTrackMap * m_trackMap = nullptr
ActsTrackingGeometry * m_tGeometry = nullptr
TrkrClusterContainer * m_clusterContainer = nullptr
ActsSurfaceMaps * m_surfMaps = nullptr
float m_maxTAlpha = 0.6
float m_maxResidualDrphi = 0.5
float m_maxTBeta = 1.5
float m_maxResidualDz = 0.5
std::unique_ptr
< TpcSpaceChargeMatrixContainer > m_matrix_container
matrix container
int m_event = 0
int m_nBadProps = 0
Counter for number of bad propagations from propagateTrackState()
std::string m_outputfile = "TpcSpaceChargeMatrices.root"
bool m_savehistograms = false
Output root histograms.
TH2 * h_rphiResid = nullptr
TH2 * h_zResid = nullptr
TH2 * h_etaResidLayer = nullptr
TH2 * h_zResidLayer = nullptr
TH2 * h_etaResid = nullptr
TH1 * h_index = nullptr
TH2 * h_alpha = nullptr
TH2 * h_beta = nullptr
TTree * residTup = nullptr
std::string m_histogramfilename = "PHTpcResiduals.root"
std::unique_ptr< TFile > m_histogramfile = nullptr
double tanAlpha = 0
For diagnostics.
double tanBeta = 0
double drphi = 0
double dz = 0
double clusR = 0
double clusPhi = 0
double clusZ = 0
double statePhi = 0
double stateZ = 0
double stateRPhiErr = 0
double stateZErr = 0
double clusRPhiErr = 0
double clusZErr = 0
double stateR = 0
unsigned int cluskey = 0
Static Private Attributes
static constexpr float m_phiMin = 0
static constexpr float m_phiMax = 2. * M_PI
static constexpr float m_rMin = 20
static constexpr float m_rMax = 78
static constexpr int m_minClusCount = 10
static constexpr unsigned int m_nLayersTpc = 48
Tpc geometry.
static constexpr float m_zMin = -105.5
static constexpr float m_zMax = 105.5
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
This class takes preliminary fits from PHActsTrkFitter to the silicon + MM clusters and calculates the residuals in the TPC from that track fit. The TPC state has to be explicitly determined here since the Acts::DirectNavigator does not visit the TPC states
Definition at line 46 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 46 of file PHTpcResiduals.h
Constructor & Destructor Documentation
PHTpcResiduals::PHTpcResiduals (const std::string & name = "PHTpcResiduals")
Definition at line 60 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 60 of file PHTpcResiduals.cc
PHTpcResiduals::~PHTpcResiduals () override default
Member Function Documentation
void PHTpcResiduals::calculateTpcResiduals (const Acts::BoundTrackParameters & params, const TrkrCluster * cluster) private
Calculates TPC residuals given an Acts::Propagation result to a TPC surface
Definition at line 428 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 428 of file PHTpcResiduals.cc
References kdfinder::abs(), Acts::SingleBoundTrackParameters< charge_t >::absoluteMomentum(), clusPhi, clusR, clusRPhiErr, clusZ, clusZErr, Acts::UnitConstants::cm, Acts::SingleBoundTrackParameters< charge_t >::covariance(), drphi, dz, Acts::eBoundLoc0, Acts::eBoundLoc1, ActsTrackingGeometry::geoContext, getCell(), TrkrCluster::getClusKey(), TrkrCluster::getRPhiError(), TrkrCluster::getX(), TrkrCluster::getY(), TrkrCluster::getZ(), TrkrCluster::getZError(), h_alpha, h_beta, h_etaResid, h_etaResidLayer, h_index, h_rphiResid, h_zResid, h_zResidLayer, index, m_matrix_container, m_maxResidualDrphi, m_maxResidualDz, m_maxTAlpha, m_maxTBeta, m_savehistograms, m_tGeometry, Acts::SingleBoundTrackParameters< charge_t >::momentum(), Acts::SingleBoundTrackParameters< charge_t >::position(), residTup, square(), statePhi, stateR, stateRPhiErr, stateZ, stateZErr, tanAlpha, tanBeta, and Fun4AllBase::Verbosity().
Referenced by processTrack().
bool PHTpcResiduals::checkTrack (SvtxTrack * track) private
Definition at line 141 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 141 of file PHTpcResiduals.cc
References SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), SvtxTrack::get_pt(), TrkrDefs::getTrkrId(), TrkrDefs::inttId, TrkrDefs::micromegasId, TrkrDefs::mvtxId, and Fun4AllBase::Verbosity().
Referenced by processTracks().
int PHTpcResiduals::createNodes (PHCompositeNode * topNode) private
Definition at line 621 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 621 of file PHTpcResiduals.cc
References Fun4AllReturnCodes::EVENT_OK.
Referenced by InitRun().
int PHTpcResiduals::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 103 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 103 of file PHTpcResiduals.cc
References Fun4AllReturnCodes::EVENT_OK, m_matrix_container, m_nBadProps, m_outputfile, and Fun4AllBase::Verbosity().
int PHTpcResiduals::getCell (const Acts::Vector3D & loc) private
Gets distortion cell for identifying bins in TPC.
Definition at line 591 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 591 of file PHTpcResiduals.cc
References QAG4Util::get_r(), loc, m_matrix_container, m_phiMax, m_phiMin, M_PI, m_rMax, m_rMin, m_zMax, m_zMin, phi, MATSCAN::phibins, r, and z.
Referenced by calculateTpcResiduals().
Surface PHTpcResiduals::getMMSurface (TrkrDefs::hitsetkey hitsetkey) private
Definition at line 263 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 263 of file PHTpcResiduals.cc
References m_surfMaps, and ActsSurfaceMaps::mmSurfaceMap.
Referenced by getSurface().
int PHTpcResiduals::getNodes (PHCompositeNode * topNode) private
Definition at line 627 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 627 of file PHTpcResiduals.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_clusterContainer, m_surfMaps, m_tGeometry, m_trackMap, m_vertexMap, and PHWHERE.
Referenced by InitRun().
Surface PHTpcResiduals::getSiliconSurface (TrkrDefs::hitsetkey hitsetkey) private
Definition at line 234 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 234 of file PHTpcResiduals.cc
References m_surfMaps, and ActsSurfaceMaps::siliconSurfaceMap.
Referenced by getSurface().
Surface PHTpcResiduals::getSurface (TrkrDefs::cluskey cluskey, TrkrDefs::subsurfkey surfkey) private
Definition at line 212 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 212 of file PHTpcResiduals.cc
References TrkrDefs::getHitSetKeyFromClusKey(), getMMSurface(), getSiliconSurface(), getTpcSurface(), TrkrDefs::getTrkrId(), TrkrDefs::inttId, TrkrDefs::micromegasId, TrkrDefs::mvtxId, and TrkrDefs::tpcId.
Referenced by makeSourceLink().
Surface PHTpcResiduals::getTpcSurface (TrkrDefs::hitsetkey hitsetkey, TrkrDefs::subsurfkey surfkey) private
Definition at line 249 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 249 of file PHTpcResiduals.cc
References m_surfMaps, and ActsSurfaceMaps::tpcSurfaceMap.
Referenced by getSurface().
Acts::Vector3D PHTpcResiduals::getVertex (SvtxTrack * track) private
Definition at line 270 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 270 of file PHTpcResiduals.cc
References Acts::UnitConstants::cm, SvtxVertexMap::get(), SvtxTrack::get_vertex_id(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), m_vertexMap, and Fun4AllBase::Verbosity().
Referenced by makeTrackParams().
int PHTpcResiduals::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 65 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 65 of file PHTpcResiduals.cc
References Fun4AllReturnCodes::EVENT_OK, m_savehistograms, and makeHistograms().
int PHTpcResiduals::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 71 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 71 of file PHTpcResiduals.cc
References Fun4AllReturnCodes::ABORTEVENT, createNodes(), Fun4AllReturnCodes::EVENT_OK, and getNodes().
void PHTpcResiduals::makeHistograms () private
Definition at line 678 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 678 of file PHTpcResiduals.cc
References clusPhi, clusR, clusRPhiErr, clusZ, clusZErr, drphi, dz, h_alpha, h_beta, h_etaResid, h_etaResidLayer, h_index, h_rphiResid, h_zResid, h_zResidLayer, m_event, m_histogramfile, m_histogramfilename, m_matrix_container, residTup, statePhi, stateR, stateRPhiErr, stateZ, stateZErr, tanAlpha, and tanBeta.
Referenced by Init().
SourceLink PHTpcResiduals::makeSourceLink (TrkrCluster * cluster) private
Definition at line 181 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 181 of file PHTpcResiduals.cc
References Acts::UnitConstants::cm, Acts::UnitConstants::cm2, Acts::Test::cov, Acts::eBoundLoc0, Acts::eBoundLoc1, TrkrCluster::getActsLocalError(), TrkrCluster::getClusKey(), TrkrCluster::getLocalX(), TrkrCluster::getLocalY(), TrkrCluster::getSubSurfKey(), getSurface(), loc, and surf().
Referenced by processTrack().
Acts::BoundTrackParameters PHTpcResiduals::makeTrackParams (SvtxTrack * track) private
Definition at line 287 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 287 of file PHTpcResiduals.cc
References Acts::Test::cov, Acts::UnitConstants::e, ActsTrackingGeometry::geoContext, SvtxTrack::get_acts_covariance(), SvtxTrack::get_charge(), SvtxTrack::get_p(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), getVertex(), i, j, m_tGeometry, momentum, Acts::UnitConstants::ns, p, and TauVsDIS_MachineLearning_Differentiation::seed.
Referenced by processTrack().
int PHTpcResiduals::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 82 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 82 of file PHTpcResiduals.cc
References m_event, processTracks(), and Fun4AllBase::Verbosity().
void PHTpcResiduals::processTrack (SvtxTrack * track) private
Definition at line 320 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 320 of file PHTpcResiduals.cc
References SvtxTrack::begin_cluster_keys(), calculateTpcResiduals(), SvtxTrack::end_cluster_keys(), TrkrClusterContainer::findCluster(), ActsTrackingGeometry::geoContext, SvtxTrack::get_p(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), TrkrDefs::getTrkrId(), m_clusterContainer, m_nBadProps, m_tGeometry, makeSourceLink(), makeTrackParams(), testing::internal::move(), propagateTrackState(), TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
Referenced by processTracks().
int PHTpcResiduals::processTracks (PHCompositeNode * topNode) private
Definition at line 123 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 123 of file PHTpcResiduals.cc
References checkTrack(), Fun4AllReturnCodes::EVENT_OK, m_trackMap, processTrack(), SvtxTrackMap::size(), and Fun4AllBase::Verbosity().
Referenced by process_event().
BoundTrackParamPtrResult PHTpcResiduals::propagateTrackState (const Acts::BoundTrackParameters & params, const SourceLink & sl) private
Propagates the silicon+MM track fit to the surface on which an available source link in the TPC exists, added from the stub matching propagation
Definition at line 386 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 386 of file PHTpcResiduals.cc
References Acts::Logging::FATAL, ActsTrackingGeometry::geoContext, Acts::getDefaultLogger(), m_tGeometry, ActsTrackingGeometry::magFieldContext, testing::internal::move(), options, ActsExamples::TrkrClusterSourceLink::referenceSurface(), propagation_timing::stepper, Acts::Logging::VERBOSE, and Fun4AllBase::Verbosity().
Referenced by processTrack().
void PHTpcResiduals::setGridDimensions (const int phiBins, const int rBins, const int zBins)
Definition at line 722 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 722 of file PHTpcResiduals.cc
References m_matrix_container.
void PHTpcResiduals::setMaxTrackAlpha (float maxTAlpha) inline
Option for setting distortion correction calculation limits.
Definition at line 60 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 60 of file PHTpcResiduals.h
References m_maxTAlpha.
void PHTpcResiduals::setMaxTrackBeta (float maxTBeta) inline
Definition at line 62 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 62 of file PHTpcResiduals.h
References m_maxTBeta.
void PHTpcResiduals::setMaxTrackResidualDrphi (float maxResidualDrphi) inline
Definition at line 64 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 64 of file PHTpcResiduals.h
References m_maxResidualDrphi.
void PHTpcResiduals::setMaxTrackResidualDz (float maxResidualDz) inline
Definition at line 67 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 67 of file PHTpcResiduals.h
References m_maxResidualDz.
void PHTpcResiduals::setOutputfile (std::string outputfile) inline
output file name for storing the space charge reconstruction matrices
Definition at line 77 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 77 of file PHTpcResiduals.h
References m_outputfile.
Referenced by Tracking_Reco().
void PHTpcResiduals::setSavehistograms (bool value) inline
set to true to store evaluation histograms and ntuples
Definition at line 74 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 74 of file PHTpcResiduals.h
References m_savehistograms, and value.
Member Data Documentation
unsigned int PHTpcResiduals::cluskey = 0 private
Definition at line 171 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 171 of file PHTpcResiduals.h
double PHTpcResiduals::clusPhi = 0 private
Definition at line 167 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 167 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
double PHTpcResiduals::clusR = 0 private
Definition at line 167 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 167 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
double PHTpcResiduals::clusRPhiErr = 0 private
Definition at line 169 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 169 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
double PHTpcResiduals::clusZ = 0 private
Definition at line 168 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 168 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
double PHTpcResiduals::clusZErr = 0 private
Definition at line 169 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 169 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
double PHTpcResiduals::drphi = 0 private
Definition at line 167 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 167 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
double PHTpcResiduals::dz = 0 private
Definition at line 167 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 167 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
TH2* PHTpcResiduals::h_alpha = nullptr private
Definition at line 160 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 160 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
TH2* PHTpcResiduals::h_beta = nullptr private
Definition at line 161 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 161 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
TH2* PHTpcResiduals::h_etaResid = nullptr private
Definition at line 158 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 158 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
TH2* PHTpcResiduals::h_etaResidLayer = nullptr private
Definition at line 156 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 156 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
TH1* PHTpcResiduals::h_index = nullptr private
Definition at line 159 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 159 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
TH2* PHTpcResiduals::h_rphiResid = nullptr private
Definition at line 154 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 154 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
TH2* PHTpcResiduals::h_zResid = nullptr private
Definition at line 155 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 155 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
TH2* PHTpcResiduals::h_zResidLayer = nullptr private
Definition at line 157 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 157 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
TrkrClusterContainer* PHTpcResiduals::m_clusterContainer = nullptr private
Definition at line 120 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 120 of file PHTpcResiduals.h
Referenced by getNodes(), and processTrack().
int PHTpcResiduals::m_event = 0 private
Definition at line 145 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 145 of file PHTpcResiduals.h
Referenced by makeHistograms(), and process_event().
std::unique_ptr<TFile> PHTpcResiduals::m_histogramfile = nullptr private
Definition at line 164 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 164 of file PHTpcResiduals.h
Referenced by makeHistograms().
std::string PHTpcResiduals::m_histogramfilename = "PHTpcResiduals.root" private
Definition at line 163 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 163 of file PHTpcResiduals.h
Referenced by makeHistograms().
std::unique_ptr<TpcSpaceChargeMatrixContainer> PHTpcResiduals::m_matrix_container private
matrix container
Definition at line 142 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 142 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), End(), getCell(), makeHistograms(), and setGridDimensions().
float PHTpcResiduals::m_maxResidualDrphi = 0.5 private
Definition at line 124 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 124 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and setMaxTrackResidualDrphi().
float PHTpcResiduals::m_maxResidualDz = 0.5 private
Definition at line 126 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 126 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and setMaxTrackResidualDz().
float PHTpcResiduals::m_maxTAlpha = 0.6 private
Definition at line 123 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 123 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and setMaxTrackAlpha().
float PHTpcResiduals::m_maxTBeta = 1.5 private
Definition at line 125 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 125 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and setMaxTrackBeta().
constexpr int PHTpcResiduals::m_minClusCount = 10 static private
Definition at line 134 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 134 of file PHTpcResiduals.h
int PHTpcResiduals::m_nBadProps = 0 private
Counter for number of bad propagations from propagateTrackState()
Definition at line 148 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 148 of file PHTpcResiduals.h
Referenced by End(), and processTrack().
constexpr unsigned int PHTpcResiduals::m_nLayersTpc = 48 static private
Tpc geometry.
Definition at line 137 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 137 of file PHTpcResiduals.h
std::string PHTpcResiduals::m_outputfile = "TpcSpaceChargeMatrices.root" private
Definition at line 150 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 150 of file PHTpcResiduals.h
Referenced by End(), and setOutputfile().
constexpr float PHTpcResiduals::m_phiMax = 2. * M_PI static private
Definition at line 129 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 129 of file PHTpcResiduals.h
Referenced by getCell().
constexpr float PHTpcResiduals::m_phiMin = 0 static private
Definition at line 128 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 128 of file PHTpcResiduals.h
Referenced by getCell().
constexpr float PHTpcResiduals::m_rMax = 78 static private
Definition at line 132 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 132 of file PHTpcResiduals.h
Referenced by getCell().
constexpr float PHTpcResiduals::m_rMin = 20 static private
Definition at line 131 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 131 of file PHTpcResiduals.h
Referenced by getCell().
bool PHTpcResiduals::m_savehistograms = false private
Output root histograms.
Definition at line 153 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 153 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), Init(), and setSavehistograms().
ActsSurfaceMaps* PHTpcResiduals::m_surfMaps = nullptr private
Definition at line 121 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 121 of file PHTpcResiduals.h
Referenced by getMMSurface(), getNodes(), getSiliconSurface(), and getTpcSurface().
ActsTrackingGeometry* PHTpcResiduals::m_tGeometry = nullptr private
Definition at line 119 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 119 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), getNodes(), makeTrackParams(), processTrack(), and propagateTrackState().
SvtxTrackMap* PHTpcResiduals::m_trackMap = nullptr private
Definition at line 118 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 118 of file PHTpcResiduals.h
Referenced by getNodes(), and processTracks().
SvtxVertexMap* PHTpcResiduals::m_vertexMap = nullptr private
Node information for Acts tracking geometry and silicon+MM track fit
Definition at line 117 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 117 of file PHTpcResiduals.h
Referenced by getNodes(), and getVertex().
constexpr float PHTpcResiduals::m_zMax = 105.5 static private
Definition at line 139 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 139 of file PHTpcResiduals.h
Referenced by getCell().
constexpr float PHTpcResiduals::m_zMin = -105.5 static private
Definition at line 138 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 138 of file PHTpcResiduals.h
Referenced by getCell().
TTree* PHTpcResiduals::residTup = nullptr private
Definition at line 162 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 162 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
double PHTpcResiduals::statePhi = 0 private
Definition at line 168 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 168 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
double PHTpcResiduals::stateR = 0 private
Definition at line 169 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 169 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
double PHTpcResiduals::stateRPhiErr = 0 private
Definition at line 168 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 168 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
double PHTpcResiduals::stateZ = 0 private
Definition at line 168 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 168 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
double PHTpcResiduals::stateZErr = 0 private
Definition at line 168 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 168 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
double PHTpcResiduals::tanAlpha = 0 private
For diagnostics.
Definition at line 167 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 167 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
double PHTpcResiduals::tanBeta = 0 private
Definition at line 167 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 167 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and makeHistograms().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/tpccalib/PHTpcResiduals.h
coresoftware/blob/master/offline/packages/tpccalib/PHTpcResiduals.cc