Analysis Software: ActsExamples::Geant4MaterialRecording Exception Reference
ActsExamples::Geant4MaterialRecording Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/Geant4/include/ActsExamples/Geant4/Geant4Simulation.hpp>
Classes
struct Config
Public Member Functions
Geant4MaterialRecording (const Config &cfg, Acts::Logging::Level level=Acts::Logging::INFO)
~Geant4MaterialRecording () override
ActsExamples::ProcessCode execute (const ActsExamples::AlgorithmContext &ctx) const final
const Config & config () const final
Readonly access to the configuration.
Public Member Functions inherited from ActsExamples::Geant4SimulationBase
Geant4SimulationBase (const Config &cfg, std::string name, Acts::Logging::Level level)
~Geant4SimulationBase () override
ProcessCode initialize () final
Initialize the algorithm.
std::shared_ptr< Geant4Handle > geant4Handle () const
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
WriteDataHandle
< std::unordered_map< size_t,
Acts::RecordedMaterialTrack > > m_outputMaterialTracks {this, "OutputMaterialTracks"}
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::Geant4SimulationBase
void commonInitialization ()
G4RunManager & runManager () const
EventStore & eventStore () const
Protected Attributes inherited from ActsExamples::Geant4SimulationBase
std::unique_ptr< const
Acts::Logger > m_logger
std::shared_ptr< EventStore > m_eventStore
int m_geant4Level {}
std::shared_ptr< Geant4Handle > m_geant4Instance
G4VUserDetectorConstruction * m_detectorConstruction {}
ReadDataHandle
< SimParticleContainer > m_inputParticles {this, "InputParticles"}
Detailed Description
Definition at line 178 of file Geant4Simulation.hpp.
View newest version in sPHENIX GitHub at line 178 of file Geant4Simulation.hpp
Constructor & Destructor Documentation
ActsExamples::Geant4MaterialRecording::Geant4MaterialRecording (const Config & cfg, Acts::Logging::Level level = Acts::Logging::INFO)
Material recording constructor
Parameters
config is the configuration struct
level is the logging level to be used
Definition at line 325 of file Geant4Simulation.cpp.
View newest version in sPHENIX GitHub at line 325 of file Geant4Simulation.cpp
References ActsExamples::Geant4SimulationBase::commonInitialization(), ActsExamples::Geant4Manager::createHandle(), ActsExamples::ParticleTrackingAction::Config::eventStore, ActsExamples::MaterialSteppingAction::Config::eventStore, ActsExamples::SimParticleTranslation::Config::eventStore, ActsExamples::MaterialSteppingAction::Config::excludeMaterials, ActsExamples::Geant4MaterialRecording::Config::excludeMaterials, ActsExamples::SimParticleTranslation::Config::forcedCharge, ActsExamples::SimParticleTranslation::Config::forcedMass, ActsExamples::SimParticleTranslation::Config::forcedPdgCode, ActsExamples::Geant4SimulationBase::Config::geant4Handle, ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::Geant4SimulationBase::Config::inputParticles, ActsExamples::Geant4Manager::instance(), ActsExamples::ParticleTrackingAction::Config::keepParticlesWithoutHits, m_cfg, ActsExamples::Geant4SimulationBase::m_eventStore, ActsExamples::Geant4SimulationBase::m_geant4Instance, ActsExamples::Geant4SimulationBase::m_geant4Level, ActsExamples::Geant4SimulationBase::m_inputParticles, ActsExamples::Geant4SimulationBase::m_logger, m_outputMaterialTracks, and ActsExamples::Geant4SimulationBase::runManager().
ActsExamples::Geant4MaterialRecording::~Geant4MaterialRecording () override default
Member Function Documentation
const Config& ActsExamples::Geant4MaterialRecording::config () const inline final virtual
Readonly access to the configuration.
Implements ActsExamples::Geant4SimulationBase.
Definition at line 204 of file Geant4Simulation.hpp.
View newest version in sPHENIX GitHub at line 204 of file Geant4Simulation.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::Geant4MaterialRecording::execute (const ActsExamples::AlgorithmContext & ctx) const final virtual
Algorithm execute method, called once per event with context
Parameters
ctx the AlgorithmContext for this event
Reimplemented from ActsExamples::Geant4SimulationBase.
Definition at line 401 of file Geant4Simulation.cpp.
View newest version in sPHENIX GitHub at line 401 of file Geant4Simulation.cpp
References ActsExamples::Geant4SimulationBase::execute(), and SUCCESS.
Member Data Documentation
Config ActsExamples::Geant4MaterialRecording::m_cfg private
Definition at line 207 of file Geant4Simulation.hpp.
View newest version in sPHENIX GitHub at line 207 of file Geant4Simulation.hpp
Referenced by config(), and Geant4MaterialRecording().
WriteDataHandle<std::unordered_map<size_t, Acts::RecordedMaterialTrack> > ActsExamples::Geant4MaterialRecording::m_outputMaterialTracks {this, "OutputMaterialTracks"} private
Definition at line 210 of file Geant4Simulation.hpp.
View newest version in sPHENIX GitHub at line 210 of file Geant4Simulation.hpp
Referenced by Geant4MaterialRecording().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Geant4/include/ActsExamples/Geant4/Geant4Simulation.hpp
acts/blob/sPHENIX/Examples/Algorithms/Geant4/src/Geant4Simulation.cpp