Analysis Software: analysis/blob/master/JS-Jet/FastJetMedianBkg/src_JetMedianTree/macro/loc_lib/noi_fnc.h File Reference
noi_fnc.h File Reference
#include "noiDict.h"
#include "noi_fmt.h"
Functions
string voi_stem (const string &path, const string &ext="")
const char * noiUniqueName (int i=0, const char *prefix="__pause_")
void noiPause (int i=0)
void noiDrawTLatex (const char *msg, double x, double y, noiDict options={}, noiDict dict={{"TextColor", kBlack,"TextColorAlpha", kBlack, 1.,"TextSize", 22,"TextFont", 43,"TextAlign", 12,"TextAngle", 0.,}})
TLine * noiDrawTLine (double x0, double y0, double x1, double y1, noiDict options, noiDict dict={{"LineColorAlpha", kBlack, 1.0,"LineStyle", 1,"LineWidth", 1}})
string noiStripEnd (string word, string sub)
string noiStripEnds (string word, vector< string > endings)
string noiStripStart (string word, string sub)
string noiStripStarts (string word, vector< string > startings)
const char * noi_geant05_ascii (int geantid)
int noi_geant05 (int geantid)
const char * noi_geant05_greek (int geantid)
TH1 * noiDivide (TH1 *num, TH1 *den, noiDict opt={}, noiDict dict={})
string noiStripExtension (const char *in)
TGraph * noiMakeTGraph (vector< double > &x, vector< double > &y)
Function Documentation
int noi_geant05 (int geantid)
Definition at line 101 of file noi_fnc.h.
View newest version in sPHENIX GitHub at line 101 of file noi_fnc.h
const char* noi_geant05_ascii (int geantid)
Definition at line 83 of file noi_fnc.h.
View newest version in sPHENIX GitHub at line 83 of file noi_fnc.h
const char* noi_geant05_greek (int geantid)
Definition at line 112 of file noi_fnc.h.
View newest version in sPHENIX GitHub at line 112 of file noi_fnc.h
TH1* noiDivide (TH1 * num, TH1 * den, noiDict opt = {}, noiDict dict = {})
Definition at line 131 of file noi_fnc.h.
View newest version in sPHENIX GitHub at line 131 of file noi_fnc.h
void noiDrawTLatex (const char * msg, double x, double y, noiDict options = {}, noiDict dict = {{ "TextColor",kBlack, "TextColorAlpha",kBlack, 1., "TextSize",22, "TextFont",43, "TextAlign",12, "TextAngle",0., }})
Definition at line 31 of file noi_fnc.h.
View newest version in sPHENIX GitHub at line 31 of file noi_fnc.h
TLine* noiDrawTLine (double x0, double y0, double x1, double y1, noiDict options, noiDict dict = {{ "LineColorAlpha",kBlack,1.0, "LineStyle",1, "LineWidth",1 }})
Definition at line 45 of file noi_fnc.h.
View newest version in sPHENIX GitHub at line 45 of file noi_fnc.h
TGraph* noiMakeTGraph (vector< double > & x, vector< double > & y)
Definition at line 175 of file noi_fnc.h.
View newest version in sPHENIX GitHub at line 175 of file noi_fnc.h
References i, and n.
void noiPause (int i = 0)
Definition at line 23 of file noi_fnc.h.
View newest version in sPHENIX GitHub at line 23 of file noi_fnc.h
References Acts::PhysicalConstants::c, i, and noiUniqueName().
string noiStripEnd (string word, string sub)
Definition at line 54 of file noi_fnc.h.
View newest version in sPHENIX GitHub at line 54 of file noi_fnc.h
Referenced by noiStripEnds().
string noiStripEnds (string word, vector< string > endings)
Definition at line 62 of file noi_fnc.h.
View newest version in sPHENIX GitHub at line 62 of file noi_fnc.h
References noiStripEnd().
string noiStripExtension (const char * in)
Definition at line 169 of file noi_fnc.h.
View newest version in sPHENIX GitHub at line 169 of file noi_fnc.h
References in.
string noiStripStart (string word, string sub)
Definition at line 68 of file noi_fnc.h.
View newest version in sPHENIX GitHub at line 68 of file noi_fnc.h
Referenced by noiStripStarts().
string noiStripStarts (string word, vector< string > startings)
Definition at line 77 of file noi_fnc.h.
View newest version in sPHENIX GitHub at line 77 of file noi_fnc.h
References noiStripStart().
const char* noiUniqueName (int i = 0, const char * prefix = "__pause_")
Definition at line 19 of file noi_fnc.h.
View newest version in sPHENIX GitHub at line 19 of file noi_fnc.h
References i, and prefix.
Referenced by noiPads::add_pad(), emb_eff_per_zdcx_binnedby3(), hg_abs_delta(), hg_abs_deltarat(), hg_abs_max(), noiPads::init(), noiPause(), rebin_TH1D(), and sparse_proj().
string voi_stem (const string & path, const string & ext = "")
Definition at line 10 of file noi_fnc.h.
View newest version in sPHENIX GitHub at line 10 of file noi_fnc.h
References merge_hashes::p.
Referenced by Sub1rhoA::Loop(), and RhoFluct::Loop().