Analysis Software: OnlMon Class Reference
OnlMon Class Reference
#include <OnlMon/blob/main/onlmonserver/OnlMon.h>
Public Types
enum { ACTIVE = -1, OK = 0, WARNING = 1, ERROR = 2 }
Public Member Functions
OnlMon (const std::string &name="NONE")
~OnlMon () override
virtual int process_event_common (Event *evt)
virtual int process_event (Event *evt)
virtual int InitCommon (OnlMonServer *se)
virtual int Init ()
virtual int Reset ()
virtual void identify (std::ostream &out=std::cout) const
virtual int BeginRunCommon (const int runno, OnlMonServer *se)
virtual int BeginRun (const int)
virtual int EndRun (const int)
virtual void SetStatus (const int newstatus)
virtual int ResetEvent ()
virtual void SetMonitorServerId (unsigned int i)
virtual unsigned int MonitorServerId () const
Public Member Functions inherited from OnlMonBase
OnlMonBase (const std::string &name="NONE")
virtual ~OnlMonBase ()
const std::string Name () const
void Name (const std::string &name)
virtual void Verbosity (const int i)
virtual int Verbosity () const
Protected Attributes
int status
unsigned int m_MonitorServerId = 0
TH1 * m_LocalFrameWorkVars = nullptr
Protected Attributes inherited from OnlMonBase
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 14 of file OnlMon.h.
View newest version in sPHENIX GitHub at line 14 of file OnlMon.h
Member Enumeration Documentation
anonymous enum
Enumerator:
ACTIVE
OK
WARNING
ERROR
Definition at line 20 of file OnlMon.h.
View newest version in sPHENIX GitHub at line 20 of file OnlMon.h
Constructor & Destructor Documentation
OnlMon::OnlMon (const std::string & name = "NONE")
Definition at line 14 of file OnlMon.cc.
View newest version in sPHENIX GitHub at line 14 of file OnlMon.cc
References ACTIVE, and status.
OnlMon::~OnlMon () inline override
Definition at line 18 of file OnlMon.h.
View newest version in sPHENIX GitHub at line 18 of file OnlMon.h
Member Function Documentation
virtual int OnlMon::BeginRun (const int) inline virtual
Reimplemented in MvtxMon, InttMon, TpcMon, TpotMon, CemcMon, HcalMon, ZdcMon, SepdMon, BbcMon, MyMon, DaqMon, and LL1Mon.
Definition at line 34 of file OnlMon.h.
View newest version in sPHENIX GitHub at line 34 of file OnlMon.h
int OnlMon::BeginRunCommon (const int runno, OnlMonServer * se) virtual
Definition at line 57 of file OnlMon.cc.
View newest version in sPHENIX GitHub at line 57 of file OnlMon.cc
References OK, and SetStatus().
virtual int OnlMon::EndRun (const int) inline virtual
Reimplemented in BbcMon, and PktSizeMon.
Definition at line 35 of file OnlMon.h.
View newest version in sPHENIX GitHub at line 35 of file OnlMon.h
void OnlMon::identify (std::ostream & out = std::cout) const virtual
Definition at line 44 of file OnlMon.cc.
View newest version in sPHENIX GitHub at line 44 of file OnlMon.cc
virtual int OnlMon::Init () inline virtual
Reimplemented in MvtxMon, InttMon, TpcMon, TpotMon, CemcMon, HcalMon, ZdcMon, SepdMon, BbcMon, PktSizeMon, MyMon, DaqMon, and LL1Mon.
Definition at line 30 of file OnlMon.h.
View newest version in sPHENIX GitHub at line 30 of file OnlMon.h
Referenced by OnlMonServer::registerMonitor().
int OnlMon::InitCommon (OnlMonServer * se) virtual
Definition at line 50 of file OnlMon.cc.
View newest version in sPHENIX GitHub at line 50 of file OnlMon.cc
References OnlMonServer::getCommonHisto(), and OnlMonServer::registerHisto().
Referenced by OnlMonServer::registerMonitor().
virtual unsigned int OnlMon::MonitorServerId () const inline virtual
Definition at line 39 of file OnlMon.h.
View newest version in sPHENIX GitHub at line 39 of file OnlMon.h
References m_MonitorServerId.
Referenced by TpcMon::Init(), MvtxMon::Init(), TpcMon::process_event(), and MvtxMon::process_event().
int OnlMon::process_event (Event * evt) virtual
Reimplemented in InttMon, MvtxMon, TpcMon, TpotMon, CemcMon, HcalMon, ZdcMon, SepdMon, BbcMon, PktSizeMon, MyMon, DaqMon, and LL1Mon.
Definition at line 32 of file OnlMon.cc.
View newest version in sPHENIX GitHub at line 32 of file OnlMon.cc
Referenced by process_event_common().
int OnlMon::process_event_common (Event * evt) virtual
Definition at line 26 of file OnlMon.cc.
View newest version in sPHENIX GitHub at line 26 of file OnlMon.cc
References process_event().
int OnlMon::Reset () virtual
Reimplemented in MvtxMon, InttMon, TpcMon, TpotMon, CemcMon, HcalMon, SepdMon, ZdcMon, BbcMon, PktSizeMon, MyMon, DaqMon, and LL1Mon.
Definition at line 38 of file OnlMon.cc.
View newest version in sPHENIX GitHub at line 38 of file OnlMon.cc
virtual int OnlMon::ResetEvent () inline virtual
Definition at line 37 of file OnlMon.h.
View newest version in sPHENIX GitHub at line 37 of file OnlMon.h
void OnlMon::SetMonitorServerId (unsigned int i) virtual
Definition at line 74 of file OnlMon.cc.
View newest version in sPHENIX GitHub at line 74 of file OnlMon.cc
References i, m_MonitorServerId, OnlMonBase::Name(), and to_string().
Referenced by run_bbc_server(), run_cemc_server(), run_cemc_server_SEB00(), run_cemc_server_SEB01(), run_daq_server(), run_example_server0(), run_example_server1(), run_intt_server(), run_ll1_server(), run_mvtx_server(), run_pktsize_server(), run_sepd_server(), run_tpc_server(), and run_zdc_server().
void OnlMon::SetStatus (const int newstatus) virtual
Definition at line 63 of file OnlMon.cc.
View newest version in sPHENIX GitHub at line 63 of file OnlMon.cc
References OnlMonServer::instance(), OnlMonServer::SetSubsystemRunStatus(), and status.
Referenced by BeginRunCommon().
Member Data Documentation
TH1* OnlMon::m_LocalFrameWorkVars = nullptr protected
Definition at line 44 of file OnlMon.h.
View newest version in sPHENIX GitHub at line 44 of file OnlMon.h
unsigned int OnlMon::m_MonitorServerId = 0 protected
Definition at line 43 of file OnlMon.h.
View newest version in sPHENIX GitHub at line 43 of file OnlMon.h
Referenced by MonitorServerId(), and SetMonitorServerId().
int OnlMon::status protected
Definition at line 42 of file OnlMon.h.
View newest version in sPHENIX GitHub at line 42 of file OnlMon.h
Referenced by OnlMon(), and SetStatus().
The documentation for this class was generated from the following files:
OnlMon/blob/main/onlmonserver/OnlMon.h
OnlMon/blob/main/onlmonserver/OnlMon.cc