Analysis Software: JETSCAPE/blob/main/external_packages/gtl/include/GTL/gml_parser.h File Reference
gml_parser.h File Reference
#include <GTL/GTL.h>
#include <GTL/gml_scanner.h>
Classes
union GML_pair_val
struct GML_pair
struct GML_list_elem
struct GML_stat
Functions
GTL_EXTERN GML_pair * GML_parser (FILE *, GML_stat *, int)
GTL_EXTERN void GML_free_list (GML_pair *, GML_list_elem *)
GTL_EXTERN void GML_print_list (GML_pair *, int)
Function Documentation
GTL_EXTERN void GML_free_list (GML_pair * , GML_list_elem *)
Definition at line 216 of file gml_parser.cpp.
View newest version in sPHENIX GitHub at line 216 of file gml_parser.cpp
References GML_free_list(), GML_LIST, GML_STRING, GML_list_elem::key, GML_pair::kind, GML_pair_val::list, GML_pair::next, GML_list_elem::next, GML_pair_val::str, Acts::Test::tmp(), and GML_pair::value.
Referenced by GML_free_list(), and graph::load().
GTL_EXTERN GML_pair* GML_parser (FILE * , GML_stat * , int) read
Definition at line 31 of file gml_parser.cpp.
View newest version in sPHENIX GitHub at line 31 of file gml_parser.cpp
References assert, GML_error::column, GML_stat::err, GML_tok_val::err, GML_error::err_num, GML_pair_val::floating, GML_tok_val::floating, GML_column, GML_DOUBLE, GML_END, GML_ERROR, GML_INT, GML_KEY, GML_L_BRACKET, GML_line, GML_LIST, GML_OK, GML_OPEN_BRACKET, GML_parser(), GML_R_BRACKET, GML_scanner(), GML_STRING, GML_SYNTAX, GML_TOO_MANY_BRACKETS, GML_pair_val::integer, GML_tok_val::integer, GML_pair::key, GML_list_elem::key, GML_stat::key_list, GML_pair::kind, GML_token::kind, GML_error::line, GML_pair_val::list, GML_pair::next, GML_list_elem::next, GML_pair_val::str, GML_tok_val::str, Acts::Test::tmp(), GML_pair::value, and GML_token::value.
Referenced by GML_parser(), and graph::load().
GTL_EXTERN void GML_print_list (GML_pair * , int)
Definition at line 251 of file gml_parser.cpp.
View newest version in sPHENIX GitHub at line 251 of file gml_parser.cpp
References GML_pair_val::floating, GML_DOUBLE, GML_INT, GML_LIST, GML_print_list(), GML_STRING, i, GML_pair_val::integer, GML_pair::key, GML_pair::kind, physmon_simulation::level, GML_pair_val::list, GML_pair::next, printf(), GML_pair_val::str, Acts::Test::tmp(), and GML_pair::value.
Referenced by GML_print_list().