Analysis Software: Jetscape::JetScapeLogger Class Reference
Jetscape::JetScapeLogger Class Reference
#include <JETSCAPE/blob/main/src/framework/JetScapeLogger.h>
Public Member Functions
LogStreamer Info ()
LogStreamer InfoNice ()
LogStreamer Warn ()
LogStreamer Debug ()
LogStreamerThread DebugThread ()
LogStreamer Remark ()
LogStreamer Verbose (unsigned short m_vlevel)
LogStreamer VerboseShower (unsigned short m_vlevel)
LogStreamer VerboseParton (unsigned short m_vlevel, Parton &p)
LogStreamer VerboseVertex (unsigned short m_vlevel, Vertex &v)
void SetDebug (bool m_debug)
void SetRemark (bool m_remark)
void SetInfo (bool m_info)
void SetVerboseLevel (unsigned short m_vlevel)
bool GetDebug ()
bool GetRemark ()
bool GetInfo ()
unsigned short GetVerboseLevel ()
Static Public Member Functions
static JetScapeLogger * Instance ()
Private Member Functions
JetScapeLogger ()
JetScapeLogger (JetScapeLogger const &)
Private Attributes
bool debug
bool remark
bool info
unsigned short vlevel
Static Private Attributes
static JetScapeLogger * m_pInstance = NULL
Detailed Description
Definition at line 189 of file JetScapeLogger.h.
View newest version in sPHENIX GitHub at line 189 of file JetScapeLogger.h
Constructor & Destructor Documentation
Jetscape::JetScapeLogger::JetScapeLogger () inline private
Definition at line 219 of file JetScapeLogger.h.
View newest version in sPHENIX GitHub at line 219 of file JetScapeLogger.h
References debug, info, remark, and vlevel.
Jetscape::JetScapeLogger::JetScapeLogger (JetScapeLogger const &) inline private
Definition at line 225 of file JetScapeLogger.h.
View newest version in sPHENIX GitHub at line 225 of file JetScapeLogger.h
Member Function Documentation
LogStreamer Jetscape::JetScapeLogger::Debug ()
Definition at line 126 of file JetScapeLogger.cc.
View newest version in sPHENIX GitHub at line 126 of file JetScapeLogger.cc
References BLUE, Acts::Test::debug, getMemoryUsage(), Jetscape::null, physmon_simulation::s, and to_string().
LogStreamerThread Jetscape::JetScapeLogger::DebugThread ()
Definition at line 112 of file JetScapeLogger.cc.
View newest version in sPHENIX GitHub at line 112 of file JetScapeLogger.cc
References BLUE, Acts::Test::debug, getMemoryUsage(), physmon_simulation::s, Jetscape::safe_cout, Jetscape::safe_null, and to_string().
bool Jetscape::JetScapeLogger::GetDebug () inline
Definition at line 213 of file JetScapeLogger.h.
View newest version in sPHENIX GitHub at line 213 of file JetScapeLogger.h
References debug.
bool Jetscape::JetScapeLogger::GetInfo () inline
Definition at line 215 of file JetScapeLogger.h.
View newest version in sPHENIX GitHub at line 215 of file JetScapeLogger.h
References info.
bool Jetscape::JetScapeLogger::GetRemark () inline
Definition at line 214 of file JetScapeLogger.h.
View newest version in sPHENIX GitHub at line 214 of file JetScapeLogger.h
References remark.
unsigned short Jetscape::JetScapeLogger::GetVerboseLevel () inline
Definition at line 216 of file JetScapeLogger.h.
View newest version in sPHENIX GitHub at line 216 of file JetScapeLogger.h
References vlevel.
LogStreamer Jetscape::JetScapeLogger::Info ()
Definition at line 139 of file JetScapeLogger.cc.
View newest version in sPHENIX GitHub at line 139 of file JetScapeLogger.cc
References getMemoryUsage(), Jetscape::null, physmon_simulation::s, and to_string().
LogStreamer Jetscape::JetScapeLogger::InfoNice ()
Definition at line 154 of file JetScapeLogger.cc.
View newest version in sPHENIX GitHub at line 154 of file JetScapeLogger.cc
References Jetscape::null, and physmon_simulation::s.
JetScapeLogger * Jetscape::JetScapeLogger::Instance () static
Definition at line 98 of file JetScapeLogger.cc.
View newest version in sPHENIX GitHub at line 98 of file JetScapeLogger.cc
Referenced by ColoredHadronization::Init(), main(), Jetscape::PartonShower::PrintEdges(), Jetscape::PartonShower::PrintNodes(), and Jetscape::JetScape::ReadGeneralParametersFromXML().
LogStreamer Jetscape::JetScapeLogger::Remark ()
Definition at line 166 of file JetScapeLogger.cc.
View newest version in sPHENIX GitHub at line 166 of file JetScapeLogger.cc
References BOLDMAGENTA, Jetscape::null, and physmon_simulation::s.
void Jetscape::JetScapeLogger::SetDebug (bool m_debug) inline
Definition at line 209 of file JetScapeLogger.h.
View newest version in sPHENIX GitHub at line 209 of file JetScapeLogger.h
References debug.
Referenced by main(), and Jetscape::JetScape::ReadGeneralParametersFromXML().
void Jetscape::JetScapeLogger::SetInfo (bool m_info) inline
Definition at line 211 of file JetScapeLogger.h.
View newest version in sPHENIX GitHub at line 211 of file JetScapeLogger.h
References info.
Referenced by main().
void Jetscape::JetScapeLogger::SetRemark (bool m_remark) inline
Definition at line 210 of file JetScapeLogger.h.
View newest version in sPHENIX GitHub at line 210 of file JetScapeLogger.h
References remark.
Referenced by main(), and Jetscape::JetScape::ReadGeneralParametersFromXML().
void Jetscape::JetScapeLogger::SetVerboseLevel (unsigned short m_vlevel) inline
Definition at line 212 of file JetScapeLogger.h.
View newest version in sPHENIX GitHub at line 212 of file JetScapeLogger.h
References vlevel.
Referenced by main(), and Jetscape::JetScape::ReadGeneralParametersFromXML().
LogStreamer Jetscape::JetScapeLogger::Verbose (unsigned short m_vlevel)
Definition at line 176 of file JetScapeLogger.cc.
View newest version in sPHENIX GitHub at line 176 of file JetScapeLogger.cc
References getMemoryUsage(), GREEN, Jetscape::null, physmon_simulation::s, and to_string().
LogStreamer Jetscape::JetScapeLogger::VerboseParton (unsigned short m_vlevel, Parton & p)
Definition at line 206 of file JetScapeLogger.cc.
View newest version in sPHENIX GitHub at line 206 of file JetScapeLogger.cc
References GREEN, Jetscape::null, physmon_simulation::s, and to_string().
LogStreamer Jetscape::JetScapeLogger::VerboseShower (unsigned short m_vlevel)
Definition at line 191 of file JetScapeLogger.cc.
View newest version in sPHENIX GitHub at line 191 of file JetScapeLogger.cc
References BOLDCYAN, getMemoryUsage(), Jetscape::null, physmon_simulation::s, and to_string().
LogStreamer Jetscape::JetScapeLogger::VerboseVertex (unsigned short m_vlevel, Vertex & v)
Definition at line 219 of file JetScapeLogger.cc.
View newest version in sPHENIX GitHub at line 219 of file JetScapeLogger.cc
References GREEN, Jetscape::null, physmon_simulation::s, and to_string().
LogStreamer Jetscape::JetScapeLogger::Warn ()
Definition at line 105 of file JetScapeLogger.cc.
View newest version in sPHENIX GitHub at line 105 of file JetScapeLogger.cc
References BOLDRED, and physmon_simulation::s.
Member Data Documentation
bool Jetscape::JetScapeLogger::debug private
Definition at line 228 of file JetScapeLogger.h.
View newest version in sPHENIX GitHub at line 228 of file JetScapeLogger.h
Referenced by GetDebug(), JetScapeLogger(), and SetDebug().
bool Jetscape::JetScapeLogger::info private
Definition at line 230 of file JetScapeLogger.h.
View newest version in sPHENIX GitHub at line 230 of file JetScapeLogger.h
Referenced by GetInfo(), JetScapeLogger(), and SetInfo().
JetScapeLogger * Jetscape::JetScapeLogger::m_pInstance = NULL static private
Definition at line 225 of file JetScapeLogger.h.
View newest version in sPHENIX GitHub at line 225 of file JetScapeLogger.h
bool Jetscape::JetScapeLogger::remark private
Definition at line 229 of file JetScapeLogger.h.
View newest version in sPHENIX GitHub at line 229 of file JetScapeLogger.h
Referenced by GetRemark(), JetScapeLogger(), and SetRemark().
unsigned short Jetscape::JetScapeLogger::vlevel private
Definition at line 231 of file JetScapeLogger.h.
View newest version in sPHENIX GitHub at line 231 of file JetScapeLogger.h
Referenced by GetVerboseLevel(), JetScapeLogger(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/JetScapeLogger.h
JETSCAPE/blob/main/src/framework/JetScapeLogger.cc