Analysis Software: PHHepMCGenEventv1 Class Reference
PHHepMCGenEventv1 Class Reference
#include <coresoftware/blob/master/generators/phhepmc/PHHepMCGenEventv1.h>
Public Member Functions
PHHepMCGenEventv1 ()
PHHepMCGenEventv1 (const PHHepMCGenEventv1 &event)
PHHepMCGenEventv1 & operator= (const PHHepMCGenEventv1 &event)
~PHHepMCGenEventv1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
const HepMC::ThreeVector & get_boost_beta_vector () const final
boost beta vector for Lorentz Transform, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
void set_boost_beta_vector (const HepMC::ThreeVector &v) final
boost beta vector for Lorentz Transform, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
const HepMC::ThreeVector & get_rotation_vector () const final
rotation axis vector, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
void set_rotation_vector (const HepMC::ThreeVector &v) final
rotation axis vector, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
double get_rotation_angle () const final
rotation angle, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
void set_rotation_angle (const double a) final
rotation angle, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
CLHEP::HepLorentzRotation get_LorentzRotation_EvtGen2Lab () const final
LorentzRotation to translate from hepmc event frame to lab frame.
CLHEP::HepLorentzRotation get_LorentzRotation_Lab2EvtGen () const final
LorentzRotation to translate from lab frame to hepmc event frame.
Public Member Functions inherited from PHHepMCGenEvent
PHHepMCGenEvent ()
PHHepMCGenEvent (const PHHepMCGenEvent &event)
PHHepMCGenEvent & operator= (const PHHepMCGenEvent &event)
~PHHepMCGenEvent () override
HepMC::GenEvent * getEvent ()
const HepMC::GenEvent * getEvent () const
int get_embedding_id () const
void set_embedding_id (int id)
bool is_simulated () const
whether this event has been processed in Geant4 simulation
void is_simulated (bool v)
whether this event has been processed in Geant4 simulation
const HepMC::FourVector & get_collision_vertex () const
collision vertex position in the Hall coordinate system, use PHENIX units of cm, ns
void set_collision_vertex (const HepMC::FourVector &v)
collision vertex position in the Hall coordinate system, use PHENIX units of cm, ns
bool addEvent (HepMC::GenEvent *evt)
host an HepMC event
bool addEvent (HepMC::GenEvent &evt)
bool swapEvent (HepMC::GenEvent *&evt)
void clearEvent ()
virtual void moveVertex (double x, double y, double z, double t=0)
move the collision vertex position in the Hall coordinate system, use PHENIX units of cm, ns
virtual int size (void) const
virtual int vertexSize (void) const
void print (std::ostream &os=std::cout) const
void PrintEvent ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
HepMC::ThreeVector m_boost_beta_vector
boost beta vector for Lorentz Transform, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
HepMC::ThreeVector m_rotation_vector
rotation axis vector, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
double m_rotation_angle
rotation angle, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
Protected Attributes inherited from PHHepMCGenEvent
int _embedding_id
Embedding ID for this generated event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background.
bool _isSimulated
whether this event has been processed in Geant4 simulation
HepMC::FourVector _collisionVertex
collision vertex position in the Hall coordinate system, use PHENIX units of cm, ns
HepMC::GenEvent * _theEvt
The HEP MC record from event generator. Note the units are recorded in GenEvent.
Detailed Description
Definition at line 6 of file PHHepMCGenEventv1.h.
View newest version in sPHENIX GitHub at line 6 of file PHHepMCGenEventv1.h
Constructor & Destructor Documentation
PHHepMCGenEventv1::PHHepMCGenEventv1 ()
Definition at line 16 of file PHHepMCGenEventv1.cc.
View newest version in sPHENIX GitHub at line 16 of file PHHepMCGenEventv1.cc
Referenced by CloneMe().
PHHepMCGenEventv1::PHHepMCGenEventv1 (const PHHepMCGenEventv1 & event)
Definition at line 23 of file PHHepMCGenEventv1.cc.
View newest version in sPHENIX GitHub at line 23 of file PHHepMCGenEventv1.cc
PHHepMCGenEventv1::~PHHepMCGenEventv1 () override
Definition at line 45 of file PHHepMCGenEventv1.cc.
View newest version in sPHENIX GitHub at line 45 of file PHHepMCGenEventv1.cc
Member Function Documentation
PHObject* PHHepMCGenEventv1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHHepMCGenEvent.
Definition at line 22 of file PHHepMCGenEventv1.h.
View newest version in sPHENIX GitHub at line 22 of file PHHepMCGenEventv1.h
References PHHepMCGenEventv1().
const HepMC::ThreeVector& PHHepMCGenEventv1::get_boost_beta_vector () const inline final virtual
boost beta vector for Lorentz Transform, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
Reimplemented from PHHepMCGenEvent.
Definition at line 25 of file PHHepMCGenEventv1.h.
View newest version in sPHENIX GitHub at line 25 of file PHHepMCGenEventv1.h
References m_boost_beta_vector.
CLHEP::HepLorentzRotation PHHepMCGenEventv1::get_LorentzRotation_EvtGen2Lab () const final virtual
LorentzRotation to translate from hepmc event frame to lab frame.
Reimplemented from PHHepMCGenEvent.
Definition at line 79 of file PHHepMCGenEventv1.cc.
View newest version in sPHENIX GitHub at line 79 of file PHHepMCGenEventv1.cc
References m_boost_beta_vector, m_rotation_angle, and m_rotation_vector.
Referenced by get_LorentzRotation_Lab2EvtGen(), and identify().
CLHEP::HepLorentzRotation PHHepMCGenEventv1::get_LorentzRotation_Lab2EvtGen () const final virtual
LorentzRotation to translate from lab frame to hepmc event frame.
Reimplemented from PHHepMCGenEvent.
Definition at line 88 of file PHHepMCGenEventv1.cc.
View newest version in sPHENIX GitHub at line 88 of file PHHepMCGenEventv1.cc
References get_LorentzRotation_EvtGen2Lab().
double PHHepMCGenEventv1::get_rotation_angle () const inline final virtual
rotation angle, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
Reimplemented from PHHepMCGenEvent.
Definition at line 37 of file PHHepMCGenEventv1.h.
View newest version in sPHENIX GitHub at line 37 of file PHHepMCGenEventv1.h
References m_rotation_angle.
const HepMC::ThreeVector& PHHepMCGenEventv1::get_rotation_vector () const inline final virtual
rotation axis vector, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
Reimplemented from PHHepMCGenEvent.
Definition at line 31 of file PHHepMCGenEventv1.h.
View newest version in sPHENIX GitHub at line 31 of file PHHepMCGenEventv1.h
References m_rotation_vector.
void PHHepMCGenEventv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHHepMCGenEvent.
Definition at line 59 of file PHHepMCGenEventv1.cc.
View newest version in sPHENIX GitHub at line 59 of file PHHepMCGenEventv1.cc
References get_LorentzRotation_EvtGen2Lab(), PHHepMCGenEvent::identify(), m_boost_beta_vector, m_rotation_angle, and m_rotation_vector.
int PHHepMCGenEventv1::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHHepMCGenEvent.
Definition at line 17 of file PHHepMCGenEventv1.h.
View newest version in sPHENIX GitHub at line 17 of file PHHepMCGenEventv1.h
References PHOOL_VIRTUAL_WARNING.
PHHepMCGenEventv1 & PHHepMCGenEventv1::operator= (const PHHepMCGenEventv1 & event)
Definition at line 32 of file PHHepMCGenEventv1.cc.
View newest version in sPHENIX GitHub at line 32 of file PHHepMCGenEventv1.cc
References PHHepMCGenEvent::_embedding_id, PHHepMCGenEvent::_isSimulated, PHHepMCGenEvent::_theEvt, PHHepMCGenEvent::getEvent(), and Reset().
void PHHepMCGenEventv1::Reset () override virtual
Clear Event.
Reimplemented from PHHepMCGenEvent.
Definition at line 49 of file PHHepMCGenEventv1.cc.
View newest version in sPHENIX GitHub at line 49 of file PHHepMCGenEventv1.cc
References m_boost_beta_vector, m_rotation_angle, m_rotation_vector, and PHHepMCGenEvent::Reset().
Referenced by operator=().
void PHHepMCGenEventv1::set_boost_beta_vector (const HepMC::ThreeVector & v) inline final virtual
boost beta vector for Lorentz Transform, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
Reimplemented from PHHepMCGenEvent.
Definition at line 28 of file PHHepMCGenEventv1.h.
View newest version in sPHENIX GitHub at line 28 of file PHHepMCGenEventv1.h
References m_boost_beta_vector, and testSigmaEff::v.
void PHHepMCGenEventv1::set_rotation_angle (const double a) inline final virtual
rotation angle, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
Reimplemented from PHHepMCGenEvent.
Definition at line 40 of file PHHepMCGenEventv1.h.
View newest version in sPHENIX GitHub at line 40 of file PHHepMCGenEventv1.h
References KFPMath::a, and m_rotation_angle.
void PHHepMCGenEventv1::set_rotation_vector (const HepMC::ThreeVector & v) inline final virtual
rotation axis vector, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
Reimplemented from PHHepMCGenEvent.
Definition at line 34 of file PHHepMCGenEventv1.h.
View newest version in sPHENIX GitHub at line 34 of file PHHepMCGenEventv1.h
References m_rotation_vector, and testSigmaEff::v.
Member Data Documentation
HepMC::ThreeVector PHHepMCGenEventv1::m_boost_beta_vector protected
boost beta vector for Lorentz Transform, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
Definition at line 50 of file PHHepMCGenEventv1.h.
View newest version in sPHENIX GitHub at line 50 of file PHHepMCGenEventv1.h
Referenced by get_boost_beta_vector(), get_LorentzRotation_EvtGen2Lab(), identify(), Reset(), and set_boost_beta_vector().
double PHHepMCGenEventv1::m_rotation_angle protected
rotation angle, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
Definition at line 56 of file PHHepMCGenEventv1.h.
View newest version in sPHENIX GitHub at line 56 of file PHHepMCGenEventv1.h
Referenced by get_LorentzRotation_EvtGen2Lab(), get_rotation_angle(), identify(), Reset(), and set_rotation_angle().
HepMC::ThreeVector PHHepMCGenEventv1::m_rotation_vector protected
rotation axis vector, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
Definition at line 53 of file PHHepMCGenEventv1.h.
View newest version in sPHENIX GitHub at line 53 of file PHHepMCGenEventv1.h
Referenced by get_LorentzRotation_EvtGen2Lab(), get_rotation_vector(), identify(), Reset(), and set_rotation_vector().
The documentation for this class was generated from the following files:
coresoftware/blob/master/generators/phhepmc/PHHepMCGenEventv1.h
coresoftware/blob/master/generators/phhepmc/PHHepMCGenEventv1.cc