Analysis Software: SvtxAlignmentStateMap_v1 Class Reference
SvtxAlignmentStateMap_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxAlignmentStateMap_v1.h>
Public Member Functions
SvtxAlignmentStateMap_v1 ()
~SvtxAlignmentStateMap_v1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
bool empty () const override
std::size_t size () const override
std::size_t count (unsigned int track) const override
void clear () override
const StateVec get (unsigned int track) const override
StateVec get (unsigned int track) override
StateVec insertWithKey (unsigned int track, StateVec states) override
std::size_t erase (unsigned int track) override
ConstIter begin () const override
ConstIter find (unsigned int track) const override
ConstIter end () const override
Iter begin () override
Iter find (unsigned int track) override
Iter end () override
Public Member Functions inherited from SvtxAlignmentStateMap
~SvtxAlignmentStateMap () override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (SvtxAlignmentStateMap_v1, 1)
Private Attributes
StateMap m_map
Additional Inherited Members
Public Types inherited from SvtxAlignmentStateMap
typedef std::vector
< SvtxAlignmentState * > StateVec
typedef std::map< unsigned int,
StateVec > StateMap
typedef StateMap::const_iterator ConstIter
typedef StateMap::iterator Iter
Protected Member Functions inherited from SvtxAlignmentStateMap
SvtxAlignmentStateMap ()
Detailed Description
Definition at line 9 of file SvtxAlignmentStateMap_v1.h.
View newest version in sPHENIX GitHub at line 9 of file SvtxAlignmentStateMap_v1.h
Constructor & Destructor Documentation
SvtxAlignmentStateMap_v1::SvtxAlignmentStateMap_v1 ()
Definition at line 7 of file SvtxAlignmentStateMap_v1.cc.
View newest version in sPHENIX GitHub at line 7 of file SvtxAlignmentStateMap_v1.cc
Referenced by CloneMe().
SvtxAlignmentStateMap_v1::~SvtxAlignmentStateMap_v1 () override
Definition at line 12 of file SvtxAlignmentStateMap_v1.cc.
View newest version in sPHENIX GitHub at line 12 of file SvtxAlignmentStateMap_v1.cc
References Reset().
Member Function Documentation
ConstIter SvtxAlignmentStateMap_v1::begin (void) const inline override virtual
Reimplemented from SvtxAlignmentStateMap.
Definition at line 31 of file SvtxAlignmentStateMap_v1.h.
View newest version in sPHENIX GitHub at line 31 of file SvtxAlignmentStateMap_v1.h
References m_map.
Iter SvtxAlignmentStateMap_v1::begin (void) inline override virtual
Reimplemented from SvtxAlignmentStateMap.
Definition at line 35 of file SvtxAlignmentStateMap_v1.h.
View newest version in sPHENIX GitHub at line 35 of file SvtxAlignmentStateMap_v1.h
References m_map.
SvtxAlignmentStateMap_v1::ClassDefOverride (SvtxAlignmentStateMap_v1 , 1) private
void SvtxAlignmentStateMap_v1::clear () inline override virtual
Reimplemented from SvtxAlignmentStateMap.
Definition at line 24 of file SvtxAlignmentStateMap_v1.h.
View newest version in sPHENIX GitHub at line 24 of file SvtxAlignmentStateMap_v1.h
References Reset().
PHObject* SvtxAlignmentStateMap_v1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from SvtxAlignmentStateMap.
Definition at line 19 of file SvtxAlignmentStateMap_v1.h.
View newest version in sPHENIX GitHub at line 19 of file SvtxAlignmentStateMap_v1.h
References SvtxAlignmentStateMap_v1().
std::size_t SvtxAlignmentStateMap_v1::count (unsigned int track) const inline override virtual
Reimplemented from SvtxAlignmentStateMap.
Definition at line 23 of file SvtxAlignmentStateMap_v1.h.
View newest version in sPHENIX GitHub at line 23 of file SvtxAlignmentStateMap_v1.h
References m_map.
bool SvtxAlignmentStateMap_v1::empty () const inline override virtual
Reimplemented from SvtxAlignmentStateMap.
Definition at line 21 of file SvtxAlignmentStateMap_v1.h.
View newest version in sPHENIX GitHub at line 21 of file SvtxAlignmentStateMap_v1.h
References m_map.
ConstIter SvtxAlignmentStateMap_v1::end (void) const inline override virtual
Reimplemented from SvtxAlignmentStateMap.
Definition at line 33 of file SvtxAlignmentStateMap_v1.h.
View newest version in sPHENIX GitHub at line 33 of file SvtxAlignmentStateMap_v1.h
References m_map.
Iter SvtxAlignmentStateMap_v1::end (void) inline override virtual
Reimplemented from SvtxAlignmentStateMap.
Definition at line 37 of file SvtxAlignmentStateMap_v1.h.
View newest version in sPHENIX GitHub at line 37 of file SvtxAlignmentStateMap_v1.h
References m_map.
std::size_t SvtxAlignmentStateMap_v1::erase (unsigned int track) override virtual
Reimplemented from SvtxAlignmentStateMap.
Definition at line 31 of file SvtxAlignmentStateMap_v1.cc.
View newest version in sPHENIX GitHub at line 31 of file SvtxAlignmentStateMap_v1.cc
References m_map, and filter::state.
ConstIter SvtxAlignmentStateMap_v1::find (unsigned int track) const inline override virtual
Reimplemented from SvtxAlignmentStateMap.
Definition at line 32 of file SvtxAlignmentStateMap_v1.h.
View newest version in sPHENIX GitHub at line 32 of file SvtxAlignmentStateMap_v1.h
References m_map.
Iter SvtxAlignmentStateMap_v1::find (unsigned int track) inline override virtual
Reimplemented from SvtxAlignmentStateMap.
Definition at line 36 of file SvtxAlignmentStateMap_v1.h.
View newest version in sPHENIX GitHub at line 36 of file SvtxAlignmentStateMap_v1.h
References m_map.
const SvtxAlignmentStateMap::StateVec SvtxAlignmentStateMap_v1::get (unsigned int track) const override virtual
Reimplemented from SvtxAlignmentStateMap.
Definition at line 51 of file SvtxAlignmentStateMap_v1.cc.
View newest version in sPHENIX GitHub at line 51 of file SvtxAlignmentStateMap_v1.cc
References m_map.
SvtxAlignmentStateMap::StateVec SvtxAlignmentStateMap_v1::get (unsigned int track) override virtual
Reimplemented from SvtxAlignmentStateMap.
Definition at line 62 of file SvtxAlignmentStateMap_v1.cc.
View newest version in sPHENIX GitHub at line 62 of file SvtxAlignmentStateMap_v1.cc
References m_map.
void SvtxAlignmentStateMap_v1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxAlignmentStateMap.
Definition at line 46 of file SvtxAlignmentStateMap_v1.cc.
View newest version in sPHENIX GitHub at line 46 of file SvtxAlignmentStateMap_v1.cc
References m_map.
SvtxAlignmentStateMap::StateVec SvtxAlignmentStateMap_v1::insertWithKey (unsigned int track, SvtxAlignmentStateMap::StateVec states) override virtual
Reimplemented from SvtxAlignmentStateMap.
Definition at line 73 of file SvtxAlignmentStateMap_v1.cc.
View newest version in sPHENIX GitHub at line 73 of file SvtxAlignmentStateMap_v1.cc
References m_map.
int SvtxAlignmentStateMap_v1::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxAlignmentStateMap.
Definition at line 18 of file SvtxAlignmentStateMap_v1.h.
View newest version in sPHENIX GitHub at line 18 of file SvtxAlignmentStateMap_v1.h
void SvtxAlignmentStateMap_v1::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 17 of file SvtxAlignmentStateMap_v1.cc.
View newest version in sPHENIX GitHub at line 17 of file SvtxAlignmentStateMap_v1.cc
References m_map, and filter::state.
Referenced by clear(), and ~SvtxAlignmentStateMap_v1().
std::size_t SvtxAlignmentStateMap_v1::size (void) const inline override virtual
Reimplemented from SvtxAlignmentStateMap.
Definition at line 22 of file SvtxAlignmentStateMap_v1.h.
View newest version in sPHENIX GitHub at line 22 of file SvtxAlignmentStateMap_v1.h
References m_map.
Member Data Documentation
StateMap SvtxAlignmentStateMap_v1::m_map private
Definition at line 40 of file SvtxAlignmentStateMap_v1.h.
View newest version in sPHENIX GitHub at line 40 of file SvtxAlignmentStateMap_v1.h
Referenced by begin(), count(), empty(), end(), erase(), find(), get(), identify(), insertWithKey(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxAlignmentStateMap_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxAlignmentStateMap_v1.cc