Analysis Software: oamlBuffer Class Reference
oamlBuffer Class Reference
#include <online_distribution/blob/master/newbasic/oamlBuffer.h>
Public Member Functions
oamlBuffer (const char *host, const int port, PHDWORD *where, const int length, const int irun=0, const int iseq=0)
oamlBuffer (const char *hostport, PHDWORD *where, const int length, const int irun=0, const int iseq=0)
virtual ~oamlBuffer ()
virtual int writeout ()
Public Member Functions inherited from olzoBuffer
olzoBuffer (int fdin, PHDWORD *where, const int length, const int irun=1, const int iseq=0)
virtual ~olzoBuffer ()
Public Member Functions inherited from ophBuffer
ophBuffer ()
ophBuffer (int fd, PHDWORD *where, const int length, const int irun=1, const int iseq=0)
ophBuffer (const char *filename, PHDWORD *where, const int length, int &status, const int irun=1, const int iseq=0)
~ophBuffer ()
int nextEvent (const unsigned int evtsize, const int etype=0, const int evtseq=0)
int addRawEvent (unsigned int *)
int addEvent (Event *)
int addFrame (PHDWORD *)
int addPacket (const Packet *p)
int addUnstructPacketData (PHDWORD *data, const int length, const int id, const int wordsize, const int hitformat)
int writeout ()
int setMaxSize (const int size)
int getMaxSize () const
unsigned long long getBytesWritten () const
int addEoB ()
Public Member Functions inherited from oBuffer
oBuffer ()
virtual ~oBuffer ()
Protected Member Functions
int connect_aml ()
int begin_run ()
Static Protected Member Functions
static int readn (int, char *, int)
static int writen (int, char *, int)
Protected Attributes
int has_begun
int RunNumber
int DontOverrideRunNumber
char HostName [256]
int ThePort
int sockfd
Protected Attributes inherited from olzoBuffer
int _broken
lzo_byte * wrkmem
PHDWORD * outputarray
lzo_uint outputarraylength
Protected Attributes inherited from ophBuffer
buffer_ptr bptr
buffer_ptr bptr_being_written
buffer_ptr bptr0
buffer_ptr bptr1
PHDWORD * data_ptr
int current_index
int max_length
int max_size
unsigned int left
int sequence
int runnumber
unsigned long long byteswritten
oEvent * current_event
int eventsequence
int current_etype
int has_end
int dirty
int fd
int our_fd
int good_object
Additional Inherited Members
Static Protected Attributes inherited from olzoBuffer
static int lzo_initialized = 0
Detailed Description
Definition at line 13 of file oamlBuffer.h.
View newest version in sPHENIX GitHub at line 13 of file oamlBuffer.h
Constructor & Destructor Documentation
oamlBuffer::oamlBuffer (const char * host, const int port, PHDWORD * where, const int length, const int irun = 0, const int iseq = 0)
Definition at line 18 of file oamlBuffer.cc.
View newest version in sPHENIX GitHub at line 18 of file oamlBuffer.cc
References connect_aml(), DontOverrideRunNumber, ophBuffer::good_object, has_begun, HostName, RunNumber, and ThePort.
oamlBuffer::oamlBuffer (const char * hostport, PHDWORD * where, const int length, const int irun = 0, const int iseq = 0)
Definition at line 43 of file oamlBuffer.cc.
View newest version in sPHENIX GitHub at line 43 of file oamlBuffer.cc
References connect_aml(), DontOverrideRunNumber, ophBuffer::good_object, has_begun, HostName, RunNumber, t, ThePort, and token.
oamlBuffer::~oamlBuffer () virtual
Definition at line 194 of file oamlBuffer.cc.
View newest version in sPHENIX GitHub at line 194 of file oamlBuffer.cc
References CTRL_CLOSE, CTRL_ENDRUN, ophBuffer::dirty, i, readn(), sockfd, writen(), and writeout().
Member Function Documentation
int oamlBuffer::begin_run () protected
Definition at line 120 of file oamlBuffer.cc.
View newest version in sPHENIX GitHub at line 120 of file oamlBuffer.cc
References CTRL_BEGINRUN, DontOverrideRunNumber, has_begun, i, readn(), RunNumber, ophBuffer::runnumber, sockfd, and writen().
Referenced by writeout().
int oamlBuffer::connect_aml () protected
Definition at line 81 of file oamlBuffer.cc.
View newest version in sPHENIX GitHub at line 81 of file oamlBuffer.cc
References ophBuffer::good_object, HostName, physmon_simulation::s, sockfd, and ThePort.
Referenced by oamlBuffer().
int oamlBuffer::readn (int fd, char * ptr, int nbytes) static protected
Definition at line 216 of file oamlBuffer.cc.
View newest version in sPHENIX GitHub at line 216 of file oamlBuffer.cc
References ActsExamples::JsonSurfacesReader::read().
Referenced by begin_run(), writeout(), and ~oamlBuffer().
int oamlBuffer::writen (int fd, char * ptr, int nbytes) static protected
Definition at line 234 of file oamlBuffer.cc.
View newest version in sPHENIX GitHub at line 234 of file oamlBuffer.cc
References write().
Referenced by begin_run(), writeout(), and ~oamlBuffer().
int oamlBuffer::writeout () virtual
Reimplemented from olzoBuffer.
Definition at line 145 of file oamlBuffer.cc.
View newest version in sPHENIX GitHub at line 145 of file oamlBuffer.cc
References ophBuffer::addEoB(), begin_run(), ophBuffer::bptr, BUFFERHEADERLENGTH, oBuffer::buffer_ptr::Bufseq, ophBuffer::byteswritten, CTRL_DATA, ophBuffer::dirty, ophBuffer::good_object, has_begun, ophBuffer::has_end, i, oBuffer::buffer_ptr::Length, LZO1XBUFFERMARKER, olzoBuffer::outputarray, olzoBuffer::outputarraylength, readn(), sockfd, writen(), and olzoBuffer::wrkmem.
Referenced by ~oamlBuffer().
Member Data Documentation
int oamlBuffer::DontOverrideRunNumber protected
Definition at line 48 of file oamlBuffer.h.
View newest version in sPHENIX GitHub at line 48 of file oamlBuffer.h
Referenced by begin_run(), and oamlBuffer().
int oamlBuffer::has_begun protected
Definition at line 46 of file oamlBuffer.h.
View newest version in sPHENIX GitHub at line 46 of file oamlBuffer.h
Referenced by begin_run(), oamlBuffer(), and writeout().
char oamlBuffer::HostName[256] protected
Definition at line 54 of file oamlBuffer.h.
View newest version in sPHENIX GitHub at line 54 of file oamlBuffer.h
Referenced by connect_aml(), and oamlBuffer().
int oamlBuffer::RunNumber protected
Definition at line 47 of file oamlBuffer.h.
View newest version in sPHENIX GitHub at line 47 of file oamlBuffer.h
Referenced by begin_run(), and oamlBuffer().
int oamlBuffer::sockfd protected
Definition at line 57 of file oamlBuffer.h.
View newest version in sPHENIX GitHub at line 57 of file oamlBuffer.h
Referenced by begin_run(), connect_aml(), writeout(), and ~oamlBuffer().
int oamlBuffer::ThePort protected
Definition at line 55 of file oamlBuffer.h.
View newest version in sPHENIX GitHub at line 55 of file oamlBuffer.h
Referenced by connect_aml(), and oamlBuffer().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/oamlBuffer.h
online_distribution/blob/master/newbasic/oamlBuffer.cc