Analysis Software: MbdVertexv2 Class Reference
MbdVertexv2 Class Reference
#include <coresoftware/blob/master/offline/packages/globalvertex/MbdVertexv2.h>
Public Member Functions
MbdVertexv2 ()
~MbdVertexv2 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
unsigned int get_id () const override
void set_id (unsigned int id) override
float get_t () const override
void set_t (float t) override
float get_t_err () const override
void set_t_err (float t_err) override
float get_x () const override
float get_y () const override
float get_z () const override
void set_z (float z) override
float get_z_err () const override
void set_z_err (float z_err) override
float get_position (unsigned int coor) const override
unsigned int get_beam_crossing () const override
void set_beam_crossing (unsigned int bco) override
Public Member Functions inherited from MbdVertex
~MbdVertex () override
virtual void set_bbc_ns (int, int, float, float) override
virtual int get_bbc_npmt (int) const override
virtual float get_bbc_q (int) const override
virtual float get_bbc_t (int) const override
Public Member Functions inherited from Vertex
~Vertex () override
void identify (std::ostream &os=std::cout) const override
PHObject * CloneMe () const override
Virtual copy constructor.
int isValid () const override
isValid returns non zero if object contains vailid data
virtual float get_t0 () const
virtual void set_t0 (float t0)
virtual void set_x (float)
virtual void set_y (float)
virtual float get_chisq () const
virtual void set_chisq (float)
virtual unsigned int get_ndof () const
virtual void set_ndof (unsigned int)
virtual void set_position (unsigned int, float)
virtual float get_error (unsigned int, unsigned int) const
virtual void set_error (unsigned int, unsigned int, float)
virtual void clear_tracks ()
virtual bool empty_tracks ()
virtual size_t size_tracks () const
virtual void insert_track (unsigned int)
virtual size_t erase_track (unsigned int)
virtual ConstTrackIter begin_tracks () const
virtual ConstTrackIter find_track (unsigned int trackid) const
virtual ConstTrackIter end_tracks () const
virtual TrackIter begin_tracks ()
virtual TrackIter find_track (unsigned int trackid)
virtual TrackIter end_tracks ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (MbdVertexv2, 1)
Private Attributes
unsigned int _id
unsigned int _bco
float _t
float _t_err
float _z
float _z_err
Additional Inherited Members
Public Types inherited from Vertex
typedef std::set< unsigned int > TrackSet
typedef std::set< unsigned int >
::const_iterator ConstTrackIter
typedef std::set< unsigned int >
::iterator TrackIter
Protected Member Functions inherited from MbdVertex
MbdVertex ()
Detailed Description
Definition at line 8 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 8 of file MbdVertexv2.h
Constructor & Destructor Documentation
MbdVertexv2::MbdVertexv2 ()
Definition at line 7 of file MbdVertexv2.cc.
View newest version in sPHENIX GitHub at line 7 of file MbdVertexv2.cc
Referenced by CloneMe(), and Reset().
MbdVertexv2::~MbdVertexv2 () override default
Member Function Documentation
MbdVertexv2::ClassDefOverride (MbdVertexv2 , 1) private
PHObject* MbdVertexv2::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from MbdVertex.
Definition at line 19 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 19 of file MbdVertexv2.h
References MbdVertexv2().
unsigned int MbdVertexv2::get_beam_crossing () const inline override virtual
Reimplemented from MbdVertex.
Definition at line 44 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 44 of file MbdVertexv2.h
References _bco.
unsigned int MbdVertexv2::get_id () const inline override virtual
Reimplemented from MbdVertex.
Definition at line 23 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 23 of file MbdVertexv2.h
References _id.
Referenced by identify().
float MbdVertexv2::get_position (unsigned int coor) const override virtual
Reimplemented from Vertex.
Definition at line 56 of file MbdVertexv2.cc.
View newest version in sPHENIX GitHub at line 56 of file MbdVertexv2.cc
References get_x(), get_y(), and get_z().
float MbdVertexv2::get_t () const inline override virtual
Reimplemented from MbdVertex.
Definition at line 26 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 26 of file MbdVertexv2.h
References _t.
Referenced by identify().
float MbdVertexv2::get_t_err () const inline override virtual
Reimplemented from MbdVertex.
Definition at line 29 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 29 of file MbdVertexv2.h
References _t_err.
Referenced by identify().
float MbdVertexv2::get_x () const inline override virtual
Reimplemented from Vertex.
Definition at line 33 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 33 of file MbdVertexv2.h
Referenced by get_position().
float MbdVertexv2::get_y () const inline override virtual
Reimplemented from Vertex.
Definition at line 34 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 34 of file MbdVertexv2.h
Referenced by get_position().
float MbdVertexv2::get_z () const inline override virtual
Reimplemented from MbdVertex.
Definition at line 36 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 36 of file MbdVertexv2.h
References _z.
Referenced by get_position(), and identify().
float MbdVertexv2::get_z_err () const inline override virtual
Reimplemented from MbdVertex.
Definition at line 39 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 39 of file MbdVertexv2.h
References _z_err.
Referenced by identify().
void MbdVertexv2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from MbdVertex.
Definition at line 19 of file MbdVertexv2.cc.
View newest version in sPHENIX GitHub at line 19 of file MbdVertexv2.cc
References get_id(), get_t(), get_t_err(), get_z(), and get_z_err().
int MbdVertexv2::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from MbdVertex.
Definition at line 30 of file MbdVertexv2.cc.
View newest version in sPHENIX GitHub at line 30 of file MbdVertexv2.cc
References _id, _t, _t_err, _z, and _z_err.
void MbdVertexv2::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 17 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 17 of file MbdVertexv2.h
References MbdVertexv2().
void MbdVertexv2::set_beam_crossing (unsigned int bco) inline override virtual
Reimplemented from MbdVertex.
Definition at line 45 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 45 of file MbdVertexv2.h
References _bco.
void MbdVertexv2::set_id (unsigned int id) inline override virtual
Reimplemented from MbdVertex.
Definition at line 24 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 24 of file MbdVertexv2.h
References _id, and train_ambiguity_solver::id.
void MbdVertexv2::set_t (float t) inline override virtual
Reimplemented from MbdVertex.
Definition at line 27 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 27 of file MbdVertexv2.h
References _t, and t.
void MbdVertexv2::set_t_err (float t_err) inline override virtual
Reimplemented from MbdVertex.
Definition at line 30 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 30 of file MbdVertexv2.h
References _t_err.
void MbdVertexv2::set_z (float z) inline override virtual
Reimplemented from MbdVertex.
Definition at line 37 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 37 of file MbdVertexv2.h
References _z, and physmon_track_finding_ttbar::z.
void MbdVertexv2::set_z_err (float z_err) inline override virtual
Reimplemented from MbdVertex.
Definition at line 40 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 40 of file MbdVertexv2.h
References _z_err.
Member Data Documentation
unsigned int MbdVertexv2::_bco private
Definition at line 48 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 48 of file MbdVertexv2.h
Referenced by get_beam_crossing(), and set_beam_crossing().
unsigned int MbdVertexv2::_id private
Definition at line 47 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 47 of file MbdVertexv2.h
Referenced by get_id(), isValid(), and set_id().
float MbdVertexv2::_t private
Definition at line 49 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 49 of file MbdVertexv2.h
Referenced by get_t(), isValid(), and set_t().
float MbdVertexv2::_t_err private
Definition at line 50 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 50 of file MbdVertexv2.h
Referenced by get_t_err(), isValid(), and set_t_err().
float MbdVertexv2::_z private
Definition at line 51 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 51 of file MbdVertexv2.h
Referenced by get_z(), isValid(), and set_z().
float MbdVertexv2::_z_err private
Definition at line 52 of file MbdVertexv2.h.
View newest version in sPHENIX GitHub at line 52 of file MbdVertexv2.h
Referenced by get_z_err(), isValid(), and set_z_err().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/globalvertex/MbdVertexv2.h
coresoftware/blob/master/offline/packages/globalvertex/MbdVertexv2.cc