Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Plugins/Json/GeometryHierarchyMapJsonConverterTests.cpp File Reference
GeometryHierarchyMapJsonConverterTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Geometry/GeometryHierarchyMap.hpp"
#include "Acts/Geometry/GeometryIdentifier.hpp"
#include "Acts/Plugins/Json/GeometryHierarchyMapJsonConverter.hpp"
#include "Acts/Tests/CommonHelpers/DataDirectory.hpp"
#include <algorithm>
#include <fstream>
#include <initializer_list>
#include <stdexcept>
#include <string>
#include <vector>
#include <nlohmann/json.hpp>
Functions
BOOST_AUTO_TEST_CASE (ToJson)
BOOST_AUTO_TEST_CASE (FromJson)
BOOST_AUTO_TEST_CASE (FromJsonMissingHeader)
BOOST_AUTO_TEST_CASE (FromJsonInvalidFormatVersion)
BOOST_AUTO_TEST_CASE (FromJsonInvalidValueIdentifier)
BOOST_AUTO_TEST_CASE (FromJsonMissingEntries)
BOOST_AUTO_TEST_CASE (Roundtrip)
BOOST_AUTO_TEST_CASE (FromFile)
Function Documentation
BOOST_AUTO_TEST_CASE (ToJson)
Definition at line 92 of file GeometryHierarchyMapJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 92 of file GeometryHierarchyMapJsonConverterTests.cpp
References Acts::PhysicalConstants::c, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (FromJson)
Definition at line 117 of file GeometryHierarchyMapJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 117 of file GeometryHierarchyMapJsonConverterTests.cpp
References Acts::PhysicalConstants::c, and it.
BOOST_AUTO_TEST_CASE (FromJsonMissingHeader)
Definition at line 161 of file GeometryHierarchyMapJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 161 of file GeometryHierarchyMapJsonConverterTests.cpp
References Acts::Transform3JsonConverter::fromJson().
BOOST_AUTO_TEST_CASE (FromJsonInvalidFormatVersion)
Definition at line 169 of file GeometryHierarchyMapJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 169 of file GeometryHierarchyMapJsonConverterTests.cpp
References Acts::Transform3JsonConverter::fromJson().
BOOST_AUTO_TEST_CASE (FromJsonInvalidValueIdentifier)
Definition at line 184 of file GeometryHierarchyMapJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 184 of file GeometryHierarchyMapJsonConverterTests.cpp
References Acts::Transform3JsonConverter::fromJson().
BOOST_AUTO_TEST_CASE (FromJsonMissingEntries)
Definition at line 199 of file GeometryHierarchyMapJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 199 of file GeometryHierarchyMapJsonConverterTests.cpp
References Acts::Transform3JsonConverter::fromJson().
BOOST_AUTO_TEST_CASE (Roundtrip)
Definition at line 213 of file GeometryHierarchyMapJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 213 of file GeometryHierarchyMapJsonConverterTests.cpp
References i, and Acts::UnitConstants::min.
BOOST_AUTO_TEST_CASE (FromFile)
Definition at line 230 of file GeometryHierarchyMapJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 230 of file GeometryHierarchyMapJsonConverterTests.cpp
References Acts::PhysicalConstants::c, file, Acts::Test::getDataPath(), in, j, and path.