Analysis Software: Acts::detail::stepper_extension_list_impl< N > Struct Template Reference
Acts::detail::stepper_extension_list_impl< N > Struct Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Propagator/detail/stepper_extension_list_implementation.hpp>
Static Public Member Functions
template<typename propagator_state_t , typename stepper_t , typename... T>
static void bid (const std::tuple< T...> &obs_tuple, const propagator_state_t &state, const stepper_t &stepper, std::array< int, sizeof...(T)> &bids)
template<typename propagator_state_t , typename stepper_t , typename... T>
static bool k (std::tuple< T...> &obs_tuple, const propagator_state_t &state, const stepper_t &stepper, Vector3D &knew, const Vector3D &bField, std::array< double, 4 > &kQoP, const std::array< bool, sizeof...(T)> &validExtensions, const int i=0, const double h=0, const Vector3D &kprev=Vector3D())
template<typename propagator_state_t , typename stepper_t , typename... T>
static bool finalize (const std::tuple< T...> &obs_tuple, propagator_state_t &state, const stepper_t &stepper, const double h, FreeMatrix &D, const std::array< bool, sizeof...(T)> &validExtensions)
template<typename propagator_state_t , typename stepper_t , typename... T>
static bool finalize (const std::tuple< T...> &obs_tuple, propagator_state_t &state, const stepper_t &stepper, const double h, const std::array< bool, sizeof...(T)> &validExtensions)
Detailed Description
template<unsigned int N>
struct Acts::detail::stepper_extension_list_impl< N >
The extension list call implementation
it calls 'validExtensionsForStep()' on the current entry of the tuple
it stores the result in validExtensions
then broadcasts the extension call to the remaining tuple
Definition at line 43 of file stepper_extension_list_implementation.hpp.
View newest version in sPHENIX GitHub at line 43 of file stepper_extension_list_implementation.hpp
Member Function Documentation
template<unsigned int N> template<typename propagator_state_t , typename stepper_t , typename... T> static void Acts::detail::stepper_extension_list_impl< N >::bid (const std::tuple< T...> & obs_tuple, const propagator_state_t & state, const stepper_t & stepper, std::array< int, sizeof...(T)> & bids) inline static
Definition at line 45 of file stepper_extension_list_implementation.hpp.
View newest version in sPHENIX GitHub at line 45 of file stepper_extension_list_implementation.hpp
References nlohmann::detail::get(), and N.
Referenced by Acts::StepperExtensionList< extensions >::validExtensionForStep().
template<unsigned int N> template<typename propagator_state_t , typename stepper_t , typename... T> static bool Acts::detail::stepper_extension_list_impl< N >::finalize (const std::tuple< T...> & obs_tuple, propagator_state_t & state, const stepper_t & stepper, const double h, FreeMatrix & D, const std::array< bool, sizeof...(T)> & validExtensions) inline static
The extension list call implementation
it calls 'finalize()' on the current entry of the tuple
then broadcasts the extension call to the remaining tuple
Definition at line 85 of file stepper_extension_list_implementation.hpp.
View newest version in sPHENIX GitHub at line 85 of file stepper_extension_list_implementation.hpp
Referenced by Acts::detail::stepper_extension_list_impl< N >::finalize(), and Acts::StepperExtensionList< extensions >::finalize().
template<unsigned int N> template<typename propagator_state_t , typename stepper_t , typename... T> static bool Acts::detail::stepper_extension_list_impl< N >::finalize (const std::tuple< T...> & obs_tuple, propagator_state_t & state, const stepper_t & stepper, const double h, const std::array< bool, sizeof...(T)> & validExtensions) inline static
The extension list call implementation
it calls 'finalize()' on the current entry of the tuple
then broadcasts the extension call to the remaining tuple
Definition at line 109 of file stepper_extension_list_implementation.hpp.
View newest version in sPHENIX GitHub at line 109 of file stepper_extension_list_implementation.hpp
References Acts::detail::stepper_extension_list_impl< N >::finalize().
template<unsigned int N> template<typename propagator_state_t , typename stepper_t , typename... T> static bool Acts::detail::stepper_extension_list_impl< N >::k (std::tuple< T...> & obs_tuple, const propagator_state_t & state, const stepper_t & stepper, Vector3D & knew, const Vector3D & bField, std::array< double, 4 > & kQoP, const std::array< bool, sizeof...(T)> & validExtensions, const int i = 0, const double h = 0, const Vector3D & kprev = Vector3D()) inline static
The extension list call implementation
it calls 'k()' on the current entry of the tuple
then broadcasts the extension call to the remaining tuple
Definition at line 56 of file stepper_extension_list_implementation.hpp.
View newest version in sPHENIX GitHub at line 56 of file stepper_extension_list_implementation.hpp
References Acts::UnitConstants::h, and i.
Referenced by Acts::StepperExtensionList< extensions >::k1(), Acts::StepperExtensionList< extensions >::k2(), Acts::StepperExtensionList< extensions >::k3(), and Acts::StepperExtensionList< extensions >::k4().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Propagator/detail/stepper_extension_list_implementation.hpp