Analysis Software: TpcTpotEventInfo Class Reference
TpcTpotEventInfo Class Reference
Base class for TPC and TPOT event level information.
#include <coresoftware/blob/master/offline/packages/trackbase/TpcTpotEventInfo.h>
Public Types
enum SectorID {
kTPCSector0 = 0, kTPCSector1, kTPCSector2, kTPCSector3,
kTPCSector4, kTPCSector5, kTPCSector6, kTPCSector7,
kTPCSector8, kTPCSector9, kTPCSector10, kTPCSector11,
kTPCSector12, kTPCSector13, kTPCSector14, kTPCSector15,
kTPCSector16, kTPCSector17, kTPCSector18, kTPCSector19,
kTPCSector20, kTPCSector21, kTPCSector22, kTPCSector23,
kTPOT = 24
}
enum PCIeEndPointID { kEndPoint0 = 0, kEndPoint1 = 1 }
enum TaggerID { kLVL1Tagger = 0, kEnDatTagger = 1 }
Public Member Functions
~TpcTpotEventInfo () override=default
dtor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
virtual void CopyFrom (const TpcTpotEventInfo &)
copy content from base class
virtual void CopyFrom (TpcTpotEventInfo *)
copy content from base class
virtual void checkIndexes (SectorID, PCIeEndPointID, TaggerID)
virtual uint64_t getBCO (SectorID, PCIeEndPointID, TaggerID) const
virtual void setBCO (uint64_t, SectorID, PCIeEndPointID, TaggerID)
virtual uint32_t getLevel1Count (SectorID, PCIeEndPointID, TaggerID) const
virtual void setLevel1Count (uint32_t, SectorID, PCIeEndPointID, TaggerID)
virtual uint32_t getEnDatCount (SectorID, PCIeEndPointID, TaggerID) const
virtual void setEnDatCount (uint32_t, SectorID, PCIeEndPointID, TaggerID)
virtual uint64_t getLastBCO (SectorID, PCIeEndPointID, TaggerID) const
virtual void setLastBCO (uint64_t, SectorID, PCIeEndPointID, TaggerID)
virtual uint8_t getModebits (SectorID, PCIeEndPointID, TaggerID) const
virtual void setModebits (uint8_t, SectorID, PCIeEndPointID, TaggerID)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
TpcTpotEventInfo ()=default
Detailed Description
Base class for TPC and TPOT event level information.
Virtual base class for TPC and TPOT event level information for use in error checking and debugging
Definition at line 26 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 26 of file TpcTpotEventInfo.h
Member Enumeration Documentation
enum TpcTpotEventInfo::PCIeEndPointID
Enumerator:
kEndPoint0
kEndPoint1
Definition at line 63 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 63 of file TpcTpotEventInfo.h
enum TpcTpotEventInfo::SectorID
Enumerator:
kTPCSector0
kTPCSector1
kTPCSector2
kTPCSector3
kTPCSector4
kTPCSector5
kTPCSector6
kTPCSector7
kTPCSector8
kTPCSector9
kTPCSector10
kTPCSector11
kTPCSector12
kTPCSector13
kTPCSector14
kTPCSector15
kTPCSector16
kTPCSector17
kTPCSector18
kTPCSector19
kTPCSector20
kTPCSector21
kTPCSector22
kTPCSector23
kTPOT
Definition at line 57 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 57 of file TpcTpotEventInfo.h
enum TpcTpotEventInfo::TaggerID
Enumerator:
kLVL1Tagger
kEnDatTagger
Definition at line 64 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 64 of file TpcTpotEventInfo.h
Constructor & Destructor Documentation
TpcTpotEventInfo::~TpcTpotEventInfo () override default
dtor
TpcTpotEventInfo::TpcTpotEventInfo () protected default
Member Function Documentation
virtual void TpcTpotEventInfo::checkIndexes (SectorID , PCIeEndPointID , TaggerID) inline virtual
Reimplemented in TpcTpotEventInfov1.
Definition at line 66 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 66 of file TpcTpotEventInfo.h
virtual void TpcTpotEventInfo::CopyFrom (const TpcTpotEventInfo &) inline virtual
copy content from base class
Reimplemented in TpcTpotEventInfov1.
Definition at line 46 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 46 of file TpcTpotEventInfo.h
Referenced by TpcTpotEventInfov1::CopyFrom().
virtual void TpcTpotEventInfo::CopyFrom (TpcTpotEventInfo *) inline virtual
copy content from base class
Reimplemented in TpcTpotEventInfov1.
Definition at line 50 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 50 of file TpcTpotEventInfo.h
virtual uint64_t TpcTpotEventInfo::getBCO (SectorID , PCIeEndPointID , TaggerID) const inline virtual
Reimplemented in TpcTpotEventInfov1.
Definition at line 69 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 69 of file TpcTpotEventInfo.h
Referenced by TpcTpotEventInfov1::CopyFrom().
virtual uint32_t TpcTpotEventInfo::getEnDatCount (SectorID , PCIeEndPointID , TaggerID) const inline virtual
Reimplemented in TpcTpotEventInfov1.
Definition at line 73 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 73 of file TpcTpotEventInfo.h
Referenced by TpcTpotEventInfov1::CopyFrom().
virtual uint64_t TpcTpotEventInfo::getLastBCO (SectorID , PCIeEndPointID , TaggerID) const inline virtual
Reimplemented in TpcTpotEventInfov1.
Definition at line 75 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 75 of file TpcTpotEventInfo.h
Referenced by TpcTpotEventInfov1::CopyFrom().
virtual uint32_t TpcTpotEventInfo::getLevel1Count (SectorID , PCIeEndPointID , TaggerID) const inline virtual
Reimplemented in TpcTpotEventInfov1.
Definition at line 71 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 71 of file TpcTpotEventInfo.h
Referenced by TpcTpotEventInfov1::CopyFrom().
virtual uint8_t TpcTpotEventInfo::getModebits (SectorID , PCIeEndPointID , TaggerID) const inline virtual
Reimplemented in TpcTpotEventInfov1.
Definition at line 77 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 77 of file TpcTpotEventInfo.h
Referenced by TpcTpotEventInfov1::CopyFrom().
void TpcTpotEventInfo::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in TpcTpotEventInfov1.
Definition at line 34 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 34 of file TpcTpotEventInfo.h
References os.
int TpcTpotEventInfo::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in TpcTpotEventInfov1.
Definition at line 39 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 39 of file TpcTpotEventInfo.h
void TpcTpotEventInfo::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in TpcTpotEventInfov1.
Definition at line 38 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 38 of file TpcTpotEventInfo.h
virtual void TpcTpotEventInfo::setBCO (uint64_t , SectorID , PCIeEndPointID , TaggerID) inline virtual
Reimplemented in TpcTpotEventInfov1.
Definition at line 70 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 70 of file TpcTpotEventInfo.h
virtual void TpcTpotEventInfo::setEnDatCount (uint32_t , SectorID , PCIeEndPointID , TaggerID) inline virtual
Reimplemented in TpcTpotEventInfov1.
Definition at line 74 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 74 of file TpcTpotEventInfo.h
virtual void TpcTpotEventInfo::setLastBCO (uint64_t , SectorID , PCIeEndPointID , TaggerID) inline virtual
Reimplemented in TpcTpotEventInfov1.
Definition at line 76 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 76 of file TpcTpotEventInfo.h
virtual void TpcTpotEventInfo::setLevel1Count (uint32_t , SectorID , PCIeEndPointID , TaggerID) inline virtual
Reimplemented in TpcTpotEventInfov1.
Definition at line 72 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 72 of file TpcTpotEventInfo.h
virtual void TpcTpotEventInfo::setModebits (uint8_t , SectorID , PCIeEndPointID , TaggerID) inline virtual
Reimplemented in TpcTpotEventInfov1.
Definition at line 78 of file TpcTpotEventInfo.h.
View newest version in sPHENIX GitHub at line 78 of file TpcTpotEventInfo.h
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase/TpcTpotEventInfo.h