Analysis Software: TowerBackground Class Reference
TowerBackground Class Reference
#include <coresoftware/blob/master/offline/packages/jetbackground/TowerBackground.h>
Public Member Functions
~TowerBackground () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
virtual void set_UE (int, const std::vector< float > &)
virtual void set_v2 (float)
virtual void set_Psi2 (float)
virtual void set_nStripsUsedForFlow (int)
virtual void set_nTowersUsedForBkg (int)
virtual std::vector< float > get_UE (int)
virtual float get_v2 ()
virtual float get_Psi2 ()
virtual int get_nStripsUsedForFlow ()
virtual int get_nTowersUsedForBkg ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
TowerBackground ()
Private Member Functions
ClassDefOverride (TowerBackground, 1)
Detailed Description
Definition at line 8 of file TowerBackground.h.
View newest version in sPHENIX GitHub at line 8 of file TowerBackground.h
Constructor & Destructor Documentation
TowerBackground::~TowerBackground () inline override
Definition at line 11 of file TowerBackground.h.
View newest version in sPHENIX GitHub at line 11 of file TowerBackground.h
TowerBackground::TowerBackground () inline protected
Definition at line 29 of file TowerBackground.h.
View newest version in sPHENIX GitHub at line 29 of file TowerBackground.h
Member Function Documentation
TowerBackground::ClassDefOverride (TowerBackground , 1) private
virtual int TowerBackground::get_nStripsUsedForFlow () inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 25 of file TowerBackground.h.
View newest version in sPHENIX GitHub at line 25 of file TowerBackground.h
virtual int TowerBackground::get_nTowersUsedForBkg () inline virtual
Definition at line 26 of file TowerBackground.h.
View newest version in sPHENIX GitHub at line 26 of file TowerBackground.h
virtual float TowerBackground::get_Psi2 () inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 24 of file TowerBackground.h.
View newest version in sPHENIX GitHub at line 24 of file TowerBackground.h
Referenced by SubtractTowers::process_event(), SubtractTowersCS::process_event(), CopyAndSubtractJets::process_event(), UEvsEtaCentrality::process_event(), JetUnderlyingEvent::process_event(), JetBkgdSub::process_event(), JetValidation::process_event(), EMJetVal::process_event(), and DumpTowerBackground::process_Node().
virtual std::vector<float> TowerBackground::get_UE (int) inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 22 of file TowerBackground.h.
View newest version in sPHENIX GitHub at line 22 of file TowerBackground.h
Referenced by SubtractTowers::process_event(), SubtractTowersCS::process_event(), CopyAndSubtractJets::process_event(), UEvsEtaCentrality::process_event(), JetUnderlyingEvent::process_event(), JetBkgdSub::process_event(), JetValidation::process_event(), and EMJetVal::process_event().
virtual float TowerBackground::get_v2 () inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 23 of file TowerBackground.h.
View newest version in sPHENIX GitHub at line 23 of file TowerBackground.h
Referenced by SubtractTowers::process_event(), SubtractTowersCS::process_event(), CopyAndSubtractJets::process_event(), UEvsEtaCentrality::process_event(), JetUnderlyingEvent::process_event(), JetBkgdSub::process_event(), JetValidation::process_event(), EMJetVal::process_event(), and DumpTowerBackground::process_Node().
void TowerBackground::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in TowerBackgroundv1.
Definition at line 13 of file TowerBackground.h.
View newest version in sPHENIX GitHub at line 13 of file TowerBackground.h
References os.
int TowerBackground::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in TowerBackgroundv1.
Definition at line 14 of file TowerBackground.h.
View newest version in sPHENIX GitHub at line 14 of file TowerBackground.h
virtual void TowerBackground::set_nStripsUsedForFlow (int) inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 19 of file TowerBackground.h.
View newest version in sPHENIX GitHub at line 19 of file TowerBackground.h
Referenced by DetermineTowerBackground::FillNode().
virtual void TowerBackground::set_nTowersUsedForBkg (int) inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 20 of file TowerBackground.h.
View newest version in sPHENIX GitHub at line 20 of file TowerBackground.h
Referenced by DetermineTowerBackground::FillNode().
virtual void TowerBackground::set_Psi2 (float) inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 18 of file TowerBackground.h.
View newest version in sPHENIX GitHub at line 18 of file TowerBackground.h
Referenced by DetermineTowerBackground::FillNode().
virtual void TowerBackground::set_UE (int , const std::vector< float > &) inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 16 of file TowerBackground.h.
View newest version in sPHENIX GitHub at line 16 of file TowerBackground.h
Referenced by DetermineTowerBackground::FillNode().
virtual void TowerBackground::set_v2 (float) inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 17 of file TowerBackground.h.
View newest version in sPHENIX GitHub at line 17 of file TowerBackground.h
Referenced by DetermineTowerBackground::FillNode().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/jetbackground/TowerBackground.h