Analysis Software: Acts::Geant4PhysicalVolumeConverter Struct Reference
Acts::Geant4PhysicalVolumeConverter Struct Reference
#include <acts/blob/sPHENIX/Plugins/Geant4/include/Acts/Plugins/Geant4/Geant4Converters.hpp>
Public Member Functions
std::shared_ptr< Surface > surface (const G4VPhysicalVolume &g4PhysVol, const Transform3 &toGlobal, bool convertMaterial=false, ActsScalar compressed=0.)
Convert a Geant4 phsyical volume to a surface.
Public Attributes
Surface::SurfaceType forcedType = Surface::SurfaceType::Other
Optionally allow to foce a type, throws exception if not possible.
Detailed Description
Definition at line 139 of file Geant4Converters.hpp.
View newest version in sPHENIX GitHub at line 139 of file Geant4Converters.hpp
Member Function Documentation
std::shared_ptr< Acts::Surface > Acts::Geant4PhysicalVolumeConverter::surface (const G4VPhysicalVolume & g4PhysVol, const Transform3 & toGlobal, bool convertMaterial = false, ActsScalar compressed = 0.)
Convert a Geant4 phsyical volume to a surface.
Parameters
g4PhysVol the physical volume to be constructed
toGlobal the global transformation before the volume
convertMaterial a material conversion flag
compressed the compressed thickness of the converted material
Returns
a shared surface object
Definition at line 276 of file Geant4Converters.cpp.
View newest version in sPHENIX GitHub at line 276 of file Geant4Converters.cpp
References Acts::Surface::assignSurfaceMaterial(), bounds, Acts::Geant4ShapeConverter::cylinderBounds(), g4Material, Acts::Geant4ShapeConverter::lineBounds(), testing::internal::move(), Acts::Geant4ShapeConverter::radialBounds(), Acts::Geant4ShapeConverter::rectangleBounds(), writeMapConfig::surface, Acts::Geant4MaterialConverter::surfaceMaterial(), and Acts::Geant4ShapeConverter::trapezoidBounds().
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::Geant4DetectorSurfaceFactory::construct().
Member Data Documentation
Surface::SurfaceType Acts::Geant4PhysicalVolumeConverter::forcedType = Surface::SurfaceType::Other
Optionally allow to foce a type, throws exception if not possible.
Definition at line 141 of file Geant4Converters.hpp.
View newest version in sPHENIX GitHub at line 141 of file Geant4Converters.hpp
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Plugins/Geant4/include/Acts/Plugins/Geant4/Geant4Converters.hpp
acts/blob/sPHENIX/Plugins/Geant4/src/Geant4Converters.cpp