Analysis Software: PHG4CylinderCellv2 Class Reference
PHG4CylinderCellv2 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellv2.h>
Public Member Functions
PHG4CylinderCellv2 ()
~PHG4CylinderCellv2 () override
void identify (std::ostream &os=std::cout) const override
void set_sensor_index (const std::string &si) override
std::string get_sensor_index () const override
void set_ladder_phi_index (const int i) override
int get_ladder_phi_index () const override
void set_ladder_z_index (const int i) override
int get_ladder_z_index () const override
Public Member Functions inherited from PHG4CylinderCellv1
PHG4CylinderCellv1 ()
~PHG4CylinderCellv1 () override
EdepConstRange get_g4hits () override
void add_edep (const PHG4HitDefs::keytype g4hitid, const float edep) override
void add_edep (const PHG4HitDefs::keytype g4hitid, const float edep, const float light_yield) override
ShowerEdepConstRange get_g4showers () override
void add_shower_edep (const int g4showerid, const float edep) override
void set_cell_id (const PHG4CylinderCellDefs::keytype id) override
void set_layer (const unsigned int i) override
double get_edep () const override
unsigned int get_layer () const override
PHG4CylinderCellDefs::keytype get_cell_id () const override
int get_binz () const override
int get_binphi () const override
int get_bineta () const override
float get_light_yield () const override
void set_zbin (const int i) override
void set_etabin (const int i) override
void set_phibin (const int i) override
void set_light_yield (const float lightYield) override
Public Member Functions inherited from PHG4CylinderCell
~PHG4CylinderCell () override
virtual void set_fiber_ID (int)
virtual int get_fiber_ID () const
virtual int get_j_index () const
virtual void set_j_index (const int)
virtual int get_k_index () const
virtual void set_k_index (const int)
virtual int get_l_index () const
virtual void set_l_index (const int)
Public Member Functions inherited from PHG4Cell
~PHG4Cell () override
void CopyFrom (const PHObject *phobj) override
void Reset () override
Clear Event.
virtual void set_cellid (const PHG4CellDefs::keytype)
virtual PHG4CellDefs::keytype get_cellid () const
virtual bool has_binning (const PHG4CellDefs::CellBinning) const
virtual void add_edep (const PHG4HitDefs::keytype, const int, const float)
virtual short int get_detid () const
short int get_layer () const
virtual void add_edep (const float)
virtual void add_eion (const float)
virtual double get_eion () const
virtual void add_light_yield (const float)
virtual void add_raw_light_yield (const float)
virtual float get_raw_light_yield () const
virtual void set_chip_index (const int)
virtual int get_chip_index () const
virtual void set_half_stave_index (const int)
virtual int get_half_stave_index () const
virtual void set_module_index (const int)
virtual int get_module_index () const
virtual int get_phibin () const
virtual void set_pixel_index (const int)
virtual int get_pixel_index () const
virtual void set_stave_index (const int)
virtual int get_stave_index () const
virtual int get_zbin () const
virtual void print () const
virtual bool has_property (const PROPERTY) const
virtual float get_property_float (const PROPERTY) const
virtual int get_property_int (const PROPERTY) const
virtual unsigned int get_property_uint (const PROPERTY) const
virtual void set_property (const PROPERTY, const float)
virtual void set_property (const PROPERTY, const int)
virtual void set_property (const PROPERTY, const unsigned int)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
Protected Attributes
int ladder_phi_index
int ladder_z_index
std::string sensor_index
Protected Attributes inherited from PHG4CylinderCellv1
unsigned int layer
PHG4CylinderCellDefs::keytype cellid
int binz
int binphi
EdepMap edeps
ShowerEdepMap showeredeps
float light_yield
Additional Inherited Members
Public Types inherited from PHG4Cell
enum PROPERTY {
prop_stave_index = 1, prop_half_stave_index = 2, prop_module_index = 3, prop_chip_index = 4,
prop_pixel_index = 5, prop_phibin = 6, prop_zbin = 7, prop_ladder_z_index = 8,
prop_ladder_phi_index = 9, prop_edep = 21, prop_eion = 22, prop_light_yield = 23,
prop_raw_light_yield = 24, prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
typedef std::map
< PHG4HitDefs::keytype, float > EdepMap
typedef EdepMap::iterator EdepIterator
typedef EdepMap::const_iterator EdepConstIterator
typedef std::pair
< EdepIterator, EdepIterator > EdepRange
typedef std::pair
< EdepConstIterator,
EdepConstIterator > EdepConstRange
typedef std::map< int, float > ShowerEdepMap
typedef ShowerEdepMap::iterator ShowerEdepIterator
typedef
ShowerEdepMap::const_iterator ShowerEdepConstIterator
typedef std::pair
< ShowerEdepIterator,
ShowerEdepIterator > ShowerEdepRange
typedef std::pair
< ShowerEdepConstIterator,
ShowerEdepConstIterator > ShowerEdepConstRange
Static Public Member Functions inherited from PHG4Cell
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Protected Member Functions inherited from PHG4CylinderCell
PHG4CylinderCell ()
Detailed Description
Definition at line 11 of file PHG4CylinderCellv2.h.
View newest version in sPHENIX GitHub at line 11 of file PHG4CylinderCellv2.h
Constructor & Destructor Documentation
PHG4CylinderCellv2::PHG4CylinderCellv2 ()
Definition at line 5 of file PHG4CylinderCellv2.cc.
View newest version in sPHENIX GitHub at line 5 of file PHG4CylinderCellv2.cc
PHG4CylinderCellv2::~PHG4CylinderCellv2 () inline override
Definition at line 15 of file PHG4CylinderCellv2.h.
View newest version in sPHENIX GitHub at line 15 of file PHG4CylinderCellv2.h
Member Function Documentation
int PHG4CylinderCellv2::get_ladder_phi_index () const inline override virtual
Reimplemented from PHG4CylinderCell.
Definition at line 24 of file PHG4CylinderCellv2.h.
View newest version in sPHENIX GitHub at line 24 of file PHG4CylinderCellv2.h
References ladder_phi_index.
Referenced by identify().
int PHG4CylinderCellv2::get_ladder_z_index () const inline override virtual
Reimplemented from PHG4CylinderCell.
Definition at line 27 of file PHG4CylinderCellv2.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4CylinderCellv2.h
References ladder_z_index.
Referenced by identify().
std::string PHG4CylinderCellv2::get_sensor_index () const inline override virtual
Reimplemented from PHG4CylinderCell.
Definition at line 21 of file PHG4CylinderCellv2.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4CylinderCellv2.h
References sensor_index.
Referenced by identify().
void PHG4CylinderCellv2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4CylinderCellv1.
Definition at line 13 of file PHG4CylinderCellv2.cc.
View newest version in sPHENIX GitHub at line 13 of file PHG4CylinderCellv2.cc
References PHG4CylinderCellv1::binphi, PHG4CylinderCellv1::binz, PHG4CylinderCellv1::cellid, PHG4CylinderCellv1::get_edep(), get_ladder_phi_index(), get_ladder_z_index(), get_sensor_index(), and PHG4CylinderCellv1::layer.
void PHG4CylinderCellv2::set_ladder_phi_index (const int i) inline override virtual
Reimplemented from PHG4CylinderCell.
Definition at line 23 of file PHG4CylinderCellv2.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4CylinderCellv2.h
References i, and ladder_phi_index.
void PHG4CylinderCellv2::set_ladder_z_index (const int i) inline override virtual
Reimplemented from PHG4CylinderCell.
Definition at line 26 of file PHG4CylinderCellv2.h.
View newest version in sPHENIX GitHub at line 26 of file PHG4CylinderCellv2.h
References i, and ladder_z_index.
void PHG4CylinderCellv2::set_sensor_index (const std::string & si) inline override virtual
Reimplemented from PHG4CylinderCell.
Definition at line 20 of file PHG4CylinderCellv2.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4CylinderCellv2.h
References sensor_index.
Member Data Documentation
int PHG4CylinderCellv2::ladder_phi_index protected
Definition at line 30 of file PHG4CylinderCellv2.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4CylinderCellv2.h
Referenced by get_ladder_phi_index(), and set_ladder_phi_index().
int PHG4CylinderCellv2::ladder_z_index protected
Definition at line 31 of file PHG4CylinderCellv2.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4CylinderCellv2.h
Referenced by get_ladder_z_index(), and set_ladder_z_index().
std::string PHG4CylinderCellv2::sensor_index protected
Definition at line 32 of file PHG4CylinderCellv2.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4CylinderCellv2.h
Referenced by get_sensor_index(), and set_sensor_index().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellv2.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellv2.cc