Analysis Software: TPCMLDataInterface Class Reference
TPCMLDataInterface Class Reference
TPCMLDataInterface.
#include <analysis/blob/master/TPC/DAQ/TPCMLDataInterface/TPCMLDataInterface.h>
Public Member Functions
TPCMLDataInterface (unsigned int minLayer, unsigned int m_maxLayer, const std::string &outputfilenamebase="TPCMLDataInterface")
virtual ~TPCMLDataInterface ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void maxLayer (int maxLayer)
void minLayer (int minLayer)
void outputFileNameBase (const std::string &outputFileNameBase)
void saveDataStreamFile (bool saveDataStreamFile)
double getEtaAcceptanceCut () const
void setEtaAcceptanceCut (double etaAcceptanceCut)
double getVertexZAcceptanceCut () const
void setVertexZAcceptanceCut (double vertexZAcceptanceCut)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
Fun4AllHistoManager * getHistoManager ()
int writeWavelet (int layer, int side, int phibin, int hittime, const std::vector< unsigned int > &wavelet)
Private Attributes
SvtxEvalStack * m_svtxevalstack
bool m_strict
bool m_saveDataStreamFile
std::string m_outputFileNameBase
H5::H5File * m_h5File
int m_minLayer
int m_maxLayer
int m_evtCounter
double m_vertexZAcceptanceCut
double m_etaAcceptanceCut
double m_momentumCut
bool m_use_initial_vertex = true
bool m_use_genfit_vertex = false
TH1 * m_hDataSize
TH1 * m_hWavelet
TH1 * m_hNChEta
TH2 * m_hLayerWaveletSize
TH2 * m_hLayerHit
TH2 * m_hLayerZBinHit
TH2 * m_hLayerZBinADC
TH2 * m_hLayerDataSize
TH2 * m_hLayerSumHit
TH2 * m_hLayerSumDataSize
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
TPCMLDataInterface.
Definition at line 31 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 31 of file TPCMLDataInterface.h
Constructor & Destructor Documentation
TPCMLDataInterface::TPCMLDataInterface (unsigned int minLayer, unsigned int m_maxLayer, const std::string & outputfilenamebase = "TPCMLDataInterface")
Definition at line 76 of file TPCMLDataInterface.cc.
View newest version in sPHENIX GitHub at line 76 of file TPCMLDataInterface.cc
TPCMLDataInterface::~TPCMLDataInterface () virtual
Definition at line 105 of file TPCMLDataInterface.cc.
View newest version in sPHENIX GitHub at line 105 of file TPCMLDataInterface.cc
References m_h5File.
Member Function Documentation
int TPCMLDataInterface::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 115 of file TPCMLDataInterface.cc.
View newest version in sPHENIX GitHub at line 115 of file TPCMLDataInterface.cc
References assert, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), Fun4AllHistoManager::getHisto(), getHistoManager(), i, m_h5File, m_outputFileNameBase, Fun4AllHistoManager::nHistos(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
double TPCMLDataInterface::getEtaAcceptanceCut () const inline
Definition at line 65 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 65 of file TPCMLDataInterface.h
References m_etaAcceptanceCut.
Fun4AllHistoManager * TPCMLDataInterface::getHistoManager () private
Definition at line 785 of file TPCMLDataInterface.cc.
View newest version in sPHENIX GitHub at line 785 of file TPCMLDataInterface.cc
References assert, Fun4AllServer::getHistoManager(), Fun4AllServer::instance(), and Fun4AllServer::registerHistoManager().
Referenced by End(), InitRun(), and process_event().
double TPCMLDataInterface::getVertexZAcceptanceCut () const inline
Definition at line 75 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 75 of file TPCMLDataInterface.h
References m_vertexZAcceptanceCut.
int TPCMLDataInterface::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 110 of file TPCMLDataInterface.cc.
View newest version in sPHENIX GitHub at line 110 of file TPCMLDataInterface.cc
References Fun4AllReturnCodes::EVENT_OK.
int TPCMLDataInterface::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 140 of file TPCMLDataInterface.cc.
View newest version in sPHENIX GitHub at line 140 of file TPCMLDataInterface.cc
References assert, Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), PHG4CylinderCellGeom::get_zbins(), getHistoManager(), PHG4CylinderCellGeomContainer::GetLayerCellGeom(), h, i, layer, m_h5File, m_hDataSize, m_hLayerDataSize, m_hLayerHit, m_hLayerSumDataSize, m_hLayerSumHit, m_hLayerWaveletSize, m_hLayerZBinADC, m_hLayerZBinHit, m_hNChEta, m_hWavelet, m_maxLayer, m_minLayer, m_outputFileNameBase, PHTFileServer::open(), Fun4AllHistoManager::registerHisto(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
void TPCMLDataInterface::maxLayer (int maxLayer) inline
Definition at line 45 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 45 of file TPCMLDataInterface.h
void TPCMLDataInterface::minLayer (int minLayer) inline
Definition at line 50 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 50 of file TPCMLDataInterface.h
References m_minLayer.
void TPCMLDataInterface::outputFileNameBase (const std::string & outputFileNameBase) inline
Definition at line 55 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 55 of file TPCMLDataInterface.h
References m_outputFileNameBase.
int TPCMLDataInterface::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 271 of file TPCMLDataInterface.cc.
View newest version in sPHENIX GitHub at line 271 of file TPCMLDataInterface.cc
References Fun4AllReturnCodes::ABORTRUN, SvtxHitEval::all_truth_hits(), assert, configureMap::data, DataSet, eta, Fun4AllReturnCodes::EVENT_OK, material_mapping_optimisation::format, SvtxEvalStack::get_hit_eval(), SvtxTruthEval::get_particle(), PHG4CylinderCellGeom::get_phibins(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4CylinderCellGeom::get_radius(), SvtxEvalStack::get_truth_eval(), PHG4CylinderCellGeom::get_zbins(), PHG4CylinderCellGeom::get_zcenter(), Fun4AllHistoManager::getHisto(), getHistoManager(), PHG4HitContainer::getHits(), TrkrHitSet::getHits(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4CylinderCellGeomContainer::GetLayerCellGeom(), TpcDefs::getPad(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), TpcDefs::getTBin(), gpx, gpy, gpz, TrkrHitSet::identify(), layer, m_etaAcceptanceCut, m_evtCounter, m_h5File, m_hDataSize, m_hLayerDataSize, m_hLayerHit, m_hLayerSumDataSize, m_hLayerSumHit, m_hLayerZBinADC, m_hLayerZBinHit, m_hNChEta, m_hWavelet, m_maxLayer, m_minLayer, m_momentumCut, m_strict, m_svtxevalstack, m_use_genfit_vertex, m_use_initial_vertex, m_vertexZAcceptanceCut, SvtxEvalStack::next_event(), merge_hashes::p, PHWHERE, physmon_track_finding_ttbar::r, SvtxEvalStack::set_strict(), SvtxEvalStack::set_use_genfit_vertex(), SvtxEvalStack::set_use_initial_vertex(), SvtxEvalStack::set_verbosity(), PHHepMCGenEventMap::size(), TrkrHitSet::size(), size, str, TrkrDefs::tpcId, Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_A_LOT, Fun4AllBase::VERBOSITY_MORE, and writeWavelet().
void TPCMLDataInterface::saveDataStreamFile (bool saveDataStreamFile) inline
Definition at line 60 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 60 of file TPCMLDataInterface.h
References m_saveDataStreamFile.
void TPCMLDataInterface::setEtaAcceptanceCut (double etaAcceptanceCut) inline
Definition at line 70 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 70 of file TPCMLDataInterface.h
References m_etaAcceptanceCut.
void TPCMLDataInterface::setVertexZAcceptanceCut (double vertexZAcceptanceCut) inline
Definition at line 80 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 80 of file TPCMLDataInterface.h
References m_vertexZAcceptanceCut.
Referenced by Fun4All_ReadDST_TPCML().
int TPCMLDataInterface::writeWavelet (int layer, int side, int phibin, int hittime, const std::vector< unsigned int > & wavelet) private
Definition at line 769 of file TPCMLDataInterface.cc.
View newest version in sPHENIX GitHub at line 769 of file TPCMLDataInterface.cc
References assert, and m_hLayerWaveletSize.
Referenced by process_event().
Member Data Documentation
double TPCMLDataInterface::m_etaAcceptanceCut private
Definition at line 106 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 106 of file TPCMLDataInterface.h
Referenced by getEtaAcceptanceCut(), process_event(), and setEtaAcceptanceCut().
int TPCMLDataInterface::m_evtCounter private
Definition at line 103 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 103 of file TPCMLDataInterface.h
Referenced by process_event().
H5::H5File* TPCMLDataInterface::m_h5File private
Definition at line 98 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 98 of file TPCMLDataInterface.h
Referenced by End(), InitRun(), process_event(), and ~TPCMLDataInterface().
TH1* TPCMLDataInterface::m_hDataSize private
Definition at line 113 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 113 of file TPCMLDataInterface.h
Referenced by InitRun(), and process_event().
TH2* TPCMLDataInterface::m_hLayerDataSize private
Definition at line 120 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 120 of file TPCMLDataInterface.h
Referenced by InitRun(), and process_event().
TH2* TPCMLDataInterface::m_hLayerHit private
Definition at line 117 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 117 of file TPCMLDataInterface.h
Referenced by InitRun(), and process_event().
TH2* TPCMLDataInterface::m_hLayerSumDataSize private
Definition at line 122 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 122 of file TPCMLDataInterface.h
Referenced by InitRun(), and process_event().
TH2* TPCMLDataInterface::m_hLayerSumHit private
Definition at line 121 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 121 of file TPCMLDataInterface.h
Referenced by InitRun(), and process_event().
TH2* TPCMLDataInterface::m_hLayerWaveletSize private
Definition at line 116 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 116 of file TPCMLDataInterface.h
Referenced by InitRun(), and writeWavelet().
TH2* TPCMLDataInterface::m_hLayerZBinADC private
Definition at line 119 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 119 of file TPCMLDataInterface.h
Referenced by InitRun(), and process_event().
TH2* TPCMLDataInterface::m_hLayerZBinHit private
Definition at line 118 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 118 of file TPCMLDataInterface.h
Referenced by InitRun(), and process_event().
TH1* TPCMLDataInterface::m_hNChEta private
Definition at line 115 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 115 of file TPCMLDataInterface.h
Referenced by InitRun(), and process_event().
TH1* TPCMLDataInterface::m_hWavelet private
Definition at line 114 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 114 of file TPCMLDataInterface.h
Referenced by InitRun(), and process_event().
int TPCMLDataInterface::m_maxLayer private
Definition at line 101 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 101 of file TPCMLDataInterface.h
Referenced by InitRun(), and process_event().
int TPCMLDataInterface::m_minLayer private
Definition at line 100 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 100 of file TPCMLDataInterface.h
Referenced by InitRun(), minLayer(), and process_event().
double TPCMLDataInterface::m_momentumCut private
Definition at line 107 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 107 of file TPCMLDataInterface.h
Referenced by process_event().
std::string TPCMLDataInterface::m_outputFileNameBase private
Definition at line 97 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 97 of file TPCMLDataInterface.h
Referenced by End(), InitRun(), and outputFileNameBase().
bool TPCMLDataInterface::m_saveDataStreamFile private
Definition at line 95 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 95 of file TPCMLDataInterface.h
Referenced by saveDataStreamFile().
bool TPCMLDataInterface::m_strict private
Definition at line 94 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 94 of file TPCMLDataInterface.h
Referenced by process_event().
SvtxEvalStack* TPCMLDataInterface::m_svtxevalstack private
Definition at line 92 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 92 of file TPCMLDataInterface.h
Referenced by process_event().
bool TPCMLDataInterface::m_use_genfit_vertex = false private
Definition at line 109 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 109 of file TPCMLDataInterface.h
Referenced by process_event().
bool TPCMLDataInterface::m_use_initial_vertex = true private
Definition at line 108 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 108 of file TPCMLDataInterface.h
Referenced by process_event().
double TPCMLDataInterface::m_vertexZAcceptanceCut private
Definition at line 105 of file TPCMLDataInterface.h.
View newest version in sPHENIX GitHub at line 105 of file TPCMLDataInterface.h
Referenced by getVertexZAcceptanceCut(), process_event(), and setVertexZAcceptanceCut().
The documentation for this class was generated from the following files:
analysis/blob/master/TPC/DAQ/TPCMLDataInterface/TPCMLDataInterface.h
analysis/blob/master/TPC/DAQ/TPCMLDataInterface/TPCMLDataInterface.cc