Analysis Software: analysis/blob/master/AndersonAnalysisModules/TrackStudies/STrackMatchingComparator/macros/CompareOldVsNewPlots.cxx File Reference
CompareOldVsNewPlots.cxx File Reference
#include <cmath>
#include <array>
#include <string>
#include <vector>
#include <utility>
#include <iostream>
#include "TH1.h"
#include "TH2.h"
#include "TPad.h"
#include "TFile.h"
#include "TLine.h"
#include "TError.h"
#include "TString.h"
#include "TLegend.h"
#include "TCanvas.h"
#include "TPaveText.h"
#include "TDirectory.h"
Functions
void CompareOldVsNewPlots ()
Variables
static const size_t NDir = 4
static const size_t NVtx = 4
static const size_t NSide = 4
static const size_t NAxes = 3
Function Documentation
void CompareOldVsNewPlots ()
Definition at line 41 of file CompareOldVsNewPlots.cxx.
View newest version in sPHENIX GitHub at line 41 of file CompareOldVsNewPlots.cxx
References AddEntry(), cd(), Close(), configureMap::data, Draw(), GetXaxis(), GetYaxis(), GetZaxis(), leg, Acts::UnitConstants::min, NAxes, NDir, NSide, NVtx, Old, Reset(), SetBorderMode(), SetBorderSize(), SetBottomMargin(), SetFillColor(), SetFillStyle(), SetFrameBorderMode(), SetLeftMargin(), SetLineColor(), SetLineStyle(), SetLineWidth(), SetLogy(), SetMarkerColor(), SetMarkerStyle(), SetName(), SetRightMargin(), SetTextFont(), SetTitle(), SetTopMargin(), and Write().
Variable Documentation
const size_t NAxes = 3 static
Definition at line 37 of file CompareOldVsNewPlots.cxx.
View newest version in sPHENIX GitHub at line 37 of file CompareOldVsNewPlots.cxx
Referenced by CompareOldVsNewPlots().
const size_t NDir = 4 static
Definition at line 34 of file CompareOldVsNewPlots.cxx.
View newest version in sPHENIX GitHub at line 34 of file CompareOldVsNewPlots.cxx
Referenced by CompareOldVsNewPlots().
const size_t NSide = 4 static
Definition at line 36 of file CompareOldVsNewPlots.cxx.
View newest version in sPHENIX GitHub at line 36 of file CompareOldVsNewPlots.cxx
Referenced by CompareOldVsNewPlots().
const size_t NVtx = 4 static
Definition at line 35 of file CompareOldVsNewPlots.cxx.
View newest version in sPHENIX GitHub at line 35 of file CompareOldVsNewPlots.cxx
Referenced by CompareOldVsNewPlots().