Analysis Software: TransportCoeff Class Reference
TransportCoeff Class Reference
#include <JETSCAPE/blob/main/jail/vhlle/src/trancoeff.h>
Public Member Functions
TransportCoeff (double _etaS, double _zetaS, EoS *_eos)
~TransportCoeff ()
void getEta (double e, double T, double &_etaS, double &_zetaS)
void getTau (double T, double &_taupi, double &_tauPi)
bool isViscous ()
Private Attributes
double etaS
double zetaS
double taupi
double tauPi
EoS * eos
Detailed Description
Definition at line 6 of file trancoeff.h.
View newest version in sPHENIX GitHub at line 6 of file trancoeff.h
Constructor & Destructor Documentation
TransportCoeff::TransportCoeff (double _etaS, double _zetaS, EoS * _eos)
Definition at line 5 of file trancoeff.cpp.
View newest version in sPHENIX GitHub at line 5 of file trancoeff.cpp
References eos, etaS, and zetaS.
TransportCoeff::~TransportCoeff () inline
Definition at line 12 of file trancoeff.h.
View newest version in sPHENIX GitHub at line 12 of file trancoeff.h
Member Function Documentation
void TransportCoeff::getEta (double e, double T, double & _etaS, double & _zetaS)
Definition at line 12 of file trancoeff.cpp.
View newest version in sPHENIX GitHub at line 12 of file trancoeff.cpp
References EoS::cs2(), eos, etaS, and zetaS.
Referenced by Hydro::NSquant(), and Hydro::setNSvalues().
void TransportCoeff::getTau (double T, double & _taupi, double & _tauPi)
Definition at line 19 of file trancoeff.cpp.
View newest version in sPHENIX GitHub at line 19 of file trancoeff.cpp
References etaS.
Referenced by Hydro::ISformal().
bool TransportCoeff::isViscous () inline
Definition at line 18 of file trancoeff.h.
View newest version in sPHENIX GitHub at line 18 of file trancoeff.h
References etaS, false, true, and zetaS.
Referenced by Fluid::calcTotals(), and Hydro::performStep().
Member Data Documentation
EoS* TransportCoeff::eos private
Definition at line 9 of file trancoeff.h.
View newest version in sPHENIX GitHub at line 9 of file trancoeff.h
Referenced by getEta(), and TransportCoeff().
double TransportCoeff::etaS private
Definition at line 8 of file trancoeff.h.
View newest version in sPHENIX GitHub at line 8 of file trancoeff.h
Referenced by getEta(), getTau(), isViscous(), and TransportCoeff().
double TransportCoeff::tauPi private
Definition at line 8 of file trancoeff.h.
View newest version in sPHENIX GitHub at line 8 of file trancoeff.h
double TransportCoeff::taupi private
Definition at line 8 of file trancoeff.h.
View newest version in sPHENIX GitHub at line 8 of file trancoeff.h
double TransportCoeff::zetaS private
Definition at line 8 of file trancoeff.h.
View newest version in sPHENIX GitHub at line 8 of file trancoeff.h
Referenced by getEta(), isViscous(), and TransportCoeff().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/jail/vhlle/src/trancoeff.h
JETSCAPE/blob/main/jail/vhlle/src/trancoeff.cpp