Analysis Software: ActsExamples::JsonMaterialWriter Class Reference
ActsExamples::JsonMaterialWriter Class Reference
#include <acts/blob/sPHENIX/Examples/Io/Json/include/ActsExamples/Io/Json/JsonMaterialWriter.hpp>
Classes
struct Config
Public Member Functions
JsonMaterialWriter (const Config &config, Acts::Logging::Level level)
~JsonMaterialWriter () override
Virtual destructor.
void writeMaterial (const Acts::DetectorMaterialMaps &detMaterial) override
void write (const Acts::TrackingGeometry &tGeometry)
const Config & config () const
Readonly access to the config.
Public Member Functions inherited from ActsExamples::IMaterialWriter
virtual ~IMaterialWriter ()=default
Virtual Destructor.
Private Member Functions
const Acts::Logger & logger () const
Private Attributes
std::unique_ptr< const
Acts::Logger > m_logger {nullptr}
The logger instance.
Config m_cfg
The config of the writer.
std::unique_ptr
< Acts::MaterialMapJsonConverter > m_converter {nullptr}
The material converter.
Detailed Description
Definition at line 59 of file JsonMaterialWriter.hpp.
View newest version in sPHENIX GitHub at line 59 of file JsonMaterialWriter.hpp
Constructor & Destructor Documentation
ActsExamples::JsonMaterialWriter::JsonMaterialWriter (const Config & config, Acts::Logging::Level level)
Constructor
Parameters
config The configuration struct of the writer
level The log level
Definition at line 20 of file JsonMaterialWriter.cpp.
View newest version in sPHENIX GitHub at line 20 of file JsonMaterialWriter.cpp
References Acts::getDefaultLogger().
ActsExamples::JsonMaterialWriter::~JsonMaterialWriter () override
Virtual destructor.
Member Function Documentation
const Config& ActsExamples::JsonMaterialWriter::config () const inline
Readonly access to the config.
Definition at line 90 of file JsonMaterialWriter.hpp.
View newest version in sPHENIX GitHub at line 90 of file JsonMaterialWriter.hpp
References m_cfg().
const Acts::Logger& ActsExamples::JsonMaterialWriter::logger () const inline private
Definition at line 93 of file JsonMaterialWriter.hpp.
View newest version in sPHENIX GitHub at line 93 of file JsonMaterialWriter.hpp
References m_logger.
void ActsExamples::JsonMaterialWriter::write (const Acts::TrackingGeometry & tGeometry)
Write out the material map from Geometry
Parameters
tGeometry is the TrackingGeometry
Definition at line 50 of file JsonMaterialWriter.cpp.
View newest version in sPHENIX GitHub at line 50 of file JsonMaterialWriter.cpp
References ACTS_CHECK_BIT, m_cfg(), m_converter, and out.
Referenced by processGeometry().
void ActsExamples::JsonMaterialWriter::writeMaterial (const Acts::DetectorMaterialMaps & detMaterial) override virtual
Write out the material map
Parameters
detMaterial is the SurfaceMaterial and VolumeMaterial maps
Implements ActsExamples::IMaterialWriter.
Definition at line 30 of file JsonMaterialWriter.cpp.
View newest version in sPHENIX GitHub at line 30 of file JsonMaterialWriter.cpp
References ACTS_CHECK_BIT, ACTS_VERBOSE, m_cfg(), m_converter, and out.
Member Data Documentation
Config ActsExamples::JsonMaterialWriter::m_cfg private
The config of the writer.
Definition at line 99 of file JsonMaterialWriter.hpp.
View newest version in sPHENIX GitHub at line 99 of file JsonMaterialWriter.hpp
std::unique_ptr<Acts::MaterialMapJsonConverter> ActsExamples::JsonMaterialWriter::m_converter {nullptr} private
The material converter.
Definition at line 102 of file JsonMaterialWriter.hpp.
View newest version in sPHENIX GitHub at line 102 of file JsonMaterialWriter.hpp
std::unique_ptr<const Acts::Logger> ActsExamples::JsonMaterialWriter::m_logger {nullptr} private
The logger instance.
Definition at line 96 of file JsonMaterialWriter.hpp.
View newest version in sPHENIX GitHub at line 96 of file JsonMaterialWriter.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Io/Json/include/ActsExamples/Io/Json/JsonMaterialWriter.hpp
acts/blob/sPHENIX/Examples/Io/Json/src/JsonMaterialWriter.cpp