Analysis Software: TowerJetInput Class Reference
TowerJetInput Class Reference
#include <coresoftware/blob/master/offline/packages/jetbase/TowerJetInput.h>
Public Member Functions
TowerJetInput (Jet::SRC input)
~TowerJetInput () override
void identify (std::ostream &os=std::cout) override
Jet::SRC get_src () override
std::vector< Jet * > get_input (PHCompositeNode *topNode) override
Public Member Functions inherited from JetInput
virtual ~JetInput ()
virtual int Verbosity () const
virtual void Verbosity (int i)
Private Attributes
Jet::SRC m_input
RawTowerDefs::CalorimeterId geocaloid
bool m_use_towerinfo = false
Additional Inherited Members
Protected Member Functions inherited from JetInput
JetInput ()
Detailed Description
Definition at line 14 of file TowerJetInput.h.
View newest version in sPHENIX GitHub at line 14 of file TowerJetInput.h
Constructor & Destructor Documentation
TowerJetInput::TowerJetInput (Jet::SRC input)
Definition at line 25 of file TowerJetInput.cc.
View newest version in sPHENIX GitHub at line 25 of file TowerJetInput.cc
TowerJetInput::~TowerJetInput () inline override
Definition at line 18 of file TowerJetInput.h.
View newest version in sPHENIX GitHub at line 18 of file TowerJetInput.h
Member Function Documentation
std::vector< Jet * > TowerJetInput::get_input (PHCompositeNode * topNode) override virtual
Reimplemented from JetInput.
Definition at line 60 of file TowerJetInput.cc.
View newest version in sPHENIX GitHub at line 60 of file TowerJetInput.cc
References assert, GlobalVertexMap::begin(), Enable::CEMC, Jet::CEMC_TOWER, Jet::CEMC_TOWER_RETOWER, Jet::CEMC_TOWER_SUB1, Jet::CEMC_TOWER_SUB1CS, Jet::CEMC_TOWERINFO, Jet::CEMC_TOWERINFO_EMBED, Jet::CEMC_TOWERINFO_RETOWER, Jet::CEMC_TOWERINFO_SIM, Jet::CEMC_TOWERINFO_SUB1, channel(), Jet::EEMC_TOWER, GlobalVertexMap::empty(), TowerInfoContainer::encode_key(), RawTowerDefs::encode_towerid(), eta, Jet::FEMC_TOWER, Jet::FHCAL_TOWER, geocaloid, RawTowerGeom::get_center_radius(), RawTowerGeom::get_center_x(), RawTowerGeom::get_center_y(), RawTowerGeom::get_center_z(), TowerInfo::get_energy(), RawTower::get_energy(), RawTower::get_id(), RawTower::get_key(), TowerInfo::get_time(), TowerInfoContainer::get_tower_at_channel(), RawTowerGeomContainer::get_tower_geometry(), GlobalVertex::get_z(), TowerInfoContainer::getTowerEtaBin(), TowerInfoContainer::getTowerPhiBin(), RawTowerContainer::getTowers(), RawTowerDefs::HCALIN, Jet::HCALIN_TOWER, Jet::HCALIN_TOWER_SUB1, Jet::HCALIN_TOWER_SUB1CS, Jet::HCALIN_TOWERINFO, Jet::HCALIN_TOWERINFO_EMBED, Jet::HCALIN_TOWERINFO_SIM, Jet::HCALIN_TOWERINFO_SUB1, RawTowerDefs::HCALOUT, Jet::HCALOUT_TOWER, Jet::HCALOUT_TOWER_SUB1, Jet::HCALOUT_TOWER_SUB1CS, Jet::HCALOUT_TOWERINFO, Jet::HCALOUT_TOWERINFO_EMBED, Jet::HCALOUT_TOWERINFO_SIM, Jet::HCALOUT_TOWERINFO_SUB1, Jet::insert_comp(), m_input, m_use_towerinfo, ActsTests::PropagationDatasets::phi, physmon_track_finding_ttbar::pt, physmon_track_finding_ttbar::r, Jet::set_e(), Jet::set_px(), Jet::set_py(), Jet::set_pz(), TowerInfoContainer::size(), JetInput::Verbosity(), and physmon_track_finding_ttbar::z.
Jet::SRC TowerJetInput::get_src () inline override virtual
Reimplemented from JetInput.
Definition at line 22 of file TowerJetInput.h.
View newest version in sPHENIX GitHub at line 22 of file TowerJetInput.h
References m_input.
void TowerJetInput::identify (std::ostream & os = std::cout) override virtual
Reimplemented from JetInput.
Definition at line 30 of file TowerJetInput.cc.
View newest version in sPHENIX GitHub at line 30 of file TowerJetInput.cc
References Jet::CEMC_TOWER, Jet::EEMC_TOWER, Jet::FEMC_TOWER, Jet::FHCAL_TOWER, Jet::HCALIN_TOWER, Jet::HCALOUT_TOWER, and m_input.
Member Data Documentation
RawTowerDefs::CalorimeterId TowerJetInput::geocaloid private
Definition at line 28 of file TowerJetInput.h.
View newest version in sPHENIX GitHub at line 28 of file TowerJetInput.h
Referenced by get_input().
Jet::SRC TowerJetInput::m_input private
Definition at line 27 of file TowerJetInput.h.
View newest version in sPHENIX GitHub at line 27 of file TowerJetInput.h
Referenced by get_input(), get_src(), and identify().
bool TowerJetInput::m_use_towerinfo = false private
Definition at line 29 of file TowerJetInput.h.
View newest version in sPHENIX GitHub at line 29 of file TowerJetInput.h
Referenced by get_input().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/jetbase/TowerJetInput.h
coresoftware/blob/master/offline/packages/jetbase/TowerJetInput.cc