Analysis Software: TSQLTime Class Reference
TSQLTime Class Reference
#include <RDBC/blob/master/include/RDBC/TSQLTypes.h>
Public Member Functions
TSQLTime (Int_t hour, Int_t minute, Int_t second)
TSQLTime ()
TSQLTime (UInt_t t)
TSQLTime (const TSQLTime &t)
virtual ~TSQLTime ()
TSQLTime & operator= (const TSQLTime &d)
Int_t GetHour () const
Int_t GetMinute () const
Int_t GetSecond () const
void SetHour (Int_t h)
void SetMinute (Int_t m)
void SetSecond (Int_t s)
TString ToString () const
Detailed Description
Definition at line 75 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 75 of file TSQLTypes.h
Constructor & Destructor Documentation
TSQLTime::TSQLTime (Int_t hour, Int_t minute, Int_t second)
Definition at line 87 of file TSQLTypes.cxx.
View newest version in sPHENIX GitHub at line 87 of file TSQLTypes.cxx
References Set().
TSQLTime::TSQLTime () inline
Definition at line 80 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 80 of file TSQLTypes.h
TSQLTime::TSQLTime (UInt_t t) inline
Definition at line 81 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 81 of file TSQLTypes.h
References t.
TSQLTime::TSQLTime (const TSQLTime & t) inline
Definition at line 83 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 83 of file TSQLTypes.h
virtual TSQLTime::~TSQLTime () inline virtual
Definition at line 84 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 84 of file TSQLTypes.h
Member Function Documentation
Int_t TSQLTime::GetHour () const inline
Definition at line 89 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 89 of file TSQLTypes.h
Referenced by SetMinute(), SetSecond(), ODBCPreparedStatement::SetTime(), ODBCCallableStatement::SetTime(), and ODBCResultSet::UpdateTime().
Int_t TSQLTime::GetMinute () const inline
Definition at line 90 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 90 of file TSQLTypes.h
Referenced by SetHour(), SetSecond(), ODBCPreparedStatement::SetTime(), ODBCCallableStatement::SetTime(), and ODBCResultSet::UpdateTime().
Int_t TSQLTime::GetSecond () const inline
Definition at line 91 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 91 of file TSQLTypes.h
Referenced by SetHour(), SetMinute(), ODBCPreparedStatement::SetTime(), ODBCCallableStatement::SetTime(), and ODBCResultSet::UpdateTime().
TSQLTime & TSQLTime::operator= (const TSQLTime & d) inline
Definition at line 152 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 152 of file TSQLTypes.h
void TSQLTime::SetHour (Int_t h)
Definition at line 95 of file TSQLTypes.cxx.
View newest version in sPHENIX GitHub at line 95 of file TSQLTypes.cxx
References GetMinute(), GetSecond(), and Set().
void TSQLTime::SetMinute (Int_t m)
Definition at line 103 of file TSQLTypes.cxx.
View newest version in sPHENIX GitHub at line 103 of file TSQLTypes.cxx
References GetHour(), GetSecond(), and Set().
void TSQLTime::SetSecond (Int_t s)
Definition at line 111 of file TSQLTypes.cxx.
View newest version in sPHENIX GitHub at line 111 of file TSQLTypes.cxx
References GetHour(), GetMinute(), and Set().
TString TSQLTime::ToString () const
Definition at line 119 of file TSQLTypes.cxx.
View newest version in sPHENIX GitHub at line 119 of file TSQLTypes.cxx
References str.
The documentation for this class was generated from the following files:
RDBC/blob/master/include/RDBC/TSQLTypes.h
RDBC/blob/master/rdbc/TSQLTypes.cxx