Analysis Software: acts/blob/sPHENIX/Core/src/Geometry/Volume.cpp File Reference
Volume.cpp File Reference
#include "Acts/Geometry/Volume.hpp"
#include "Acts/Definitions/Units.hpp"
#include "Acts/Geometry/VolumeBounds.hpp"
#include <iostream>
#include <utility>
Functions
m_transform (shift *vol.m_transform)
m_itransform (m_transform.inverse())
m_center (m_transform.translation())
m_volumeBounds (vol.m_volumeBounds)
m_orientedBoundingBox (m_volumeBounds->boundingBox(nullptr,{0.05_mm, 0.05_mm, 0.05_mm}, this))
Variables
this
Function Documentation
m_center (m_transform. translation())
Referenced by Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::center(), Acts::Volume::operator=(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::svg(), and Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::toStream().
m_itransform (m_transform. inverse())
m_orientedBoundingBox (m_volumeBounds-> boundingBoxnullptr,{0.05_mm, 0.05_mm, 0.05_mm}, this)
Definition at line 35 of file Volume.cpp.
View newest version in sPHENIX GitHub at line 35 of file Volume.cpp
Referenced by Acts::Volume::orientedBoundingBox().
m_transform (shift *vol. m_transform)
Referenced by Acts::Surface::assignDetectorElement(), Acts::Volume::boundingBox(), ExternalsBuilder< bounds_type >::construct(), CylindricalVolumeBuilder< surface_type, surface_bounds_type >::construct(), InternalSurfaceBuilder< surface_type, bounds_type >::construct(), InternalVolumeBuilder< bounds_type >::construct(), Acts::AbstractVolume::createBoundarySurfaces(), Acts::TrackingVolume::createBoundarySurfaces(), Acts::DiscLayer::DiscLayer(), MultivariateNormalDistribution< T, D >::MultivariateNormalDistribution(), MultivariateNormalDistribution< T, D >::operator()(), Acts::Volume::operator=(), Acts::Surface::operator=(), Acts::Surface::operator==(), Acts::Surface::transform(), and Acts::Experimental::DetectorVolume::transform().
m_volumeBounds (vol. m_volumeBounds)
Referenced by Acts::Volume::binningPosition(), Acts::Volume::boundingBox(), CylindricalVolumeBuilder< surface_type, surface_bounds_type >::construct(), and Acts::Volume::operator=().
Variable Documentation
this
Initial value:
{}
Acts::Volume::Volume(const Volume& vol, const Transform3& shift)
    : GeometryObject()
Definition at line 27 of file Volume.cpp.
View newest version in sPHENIX GitHub at line 27 of file Volume.cpp
Referenced by genfit::Track::checkConsistency(), and ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::interact().