Analysis Software: G4CellNtuple Class Reference
G4CellNtuple Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4histos/G4CellNtuple.h>
Public Member Functions
G4CellNtuple (const std::string &name="G4CellNtuple", const std::string &filename="G4CellNtuple.root")
constructor
~G4CellNtuple () override
destructor
int Init (PHCompositeNode *) override
full initialization
int process_event (PHCompositeNode *) override
event processing method
int End (PHCompositeNode *) override
end of run method
void AddNode (const std::string &name, const int detid=0)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
int nblocks
Fun4AllHistoManager * hm
std::vector< TH1 * > nhits
std::vector< TH1 * > eloss
std::string _filename
std::set< std::string > _node_postfix
std::map< std::string, int > _detid
TNtuple * ntup
TFile * outfile
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 18 of file G4CellNtuple.h.
View newest version in sPHENIX GitHub at line 18 of file G4CellNtuple.h
Constructor & Destructor Documentation
G4CellNtuple::G4CellNtuple (const std::string & name = "G4CellNtuple", const std::string & filename = "G4CellNtuple.root")
constructor
Definition at line 26 of file G4CellNtuple.cc.
View newest version in sPHENIX GitHub at line 26 of file G4CellNtuple.cc
G4CellNtuple::~G4CellNtuple () override
destructor
Definition at line 36 of file G4CellNtuple.cc.
View newest version in sPHENIX GitHub at line 36 of file G4CellNtuple.cc
References hm.
Member Function Documentation
void G4CellNtuple::AddNode (const std::string & name, const int detid = 0)
Definition at line 145 of file G4CellNtuple.cc.
View newest version in sPHENIX GitHub at line 145 of file G4CellNtuple.cc
References _detid, _node_postfix, and perf_headwind::name.
int G4CellNtuple::End (PHCompositeNode *) override virtual
end of run method
Reimplemented from SubsysReco.
Definition at line 134 of file G4CellNtuple.cc.
View newest version in sPHENIX GitHub at line 134 of file G4CellNtuple.cc
References _filename, Fun4AllHistoManager::dumpHistos(), hm, ntup, and outfile.
int G4CellNtuple::Init (PHCompositeNode *) override virtual
full initialization
Reimplemented from SubsysReco.
Definition at line 42 of file G4CellNtuple.cc.
View newest version in sPHENIX GitHub at line 42 of file G4CellNtuple.cc
References _filename, eloss, h1, hm, Fun4AllBase::Name(), ntup, and outfile.
int G4CellNtuple::process_event (PHCompositeNode * topNode) override virtual
event processing method
Reimplemented from SubsysReco.
Definition at line 55 of file G4CellNtuple.cc.
View newest version in sPHENIX GitHub at line 55 of file G4CellNtuple.cc
References _detid, _node_postfix, assert, eloss, eta, KF_timing::etabin, PHG4CellDefs::etaphibinning, PHG4CellDefs::EtaPhiBinning::get_etabin(), PHG4TpcCylinderGeom::get_etacenter(), PHG4CellDefs::SizeBinning::get_phibin(), PHG4CellDefs::EtaPhiBinning::get_phibin(), PHG4TpcCylinderGeom::get_phicenter(), PHG4CellDefs::SizeBinning::get_zbin(), PHG4TpcCylinderGeom::get_zcenter(), PHG4CellContainer::getCells(), PHG4TpcCylinderGeomContainer::GetLayerCellGeom(), layer, ntup, ActsTests::PropagationDatasets::phi, and PHG4CellDefs::sizebinning.
Member Data Documentation
std::map<std::string, int> G4CellNtuple::_detid protected
Definition at line 46 of file G4CellNtuple.h.
View newest version in sPHENIX GitHub at line 46 of file G4CellNtuple.h
Referenced by AddNode(), and process_event().
std::string G4CellNtuple::_filename protected
Definition at line 44 of file G4CellNtuple.h.
View newest version in sPHENIX GitHub at line 44 of file G4CellNtuple.h
Referenced by End(), and Init().
std::set<std::string> G4CellNtuple::_node_postfix protected
Definition at line 45 of file G4CellNtuple.h.
View newest version in sPHENIX GitHub at line 45 of file G4CellNtuple.h
Referenced by AddNode(), and process_event().
std::vector<TH1 *> G4CellNtuple::eloss protected
Definition at line 42 of file G4CellNtuple.h.
View newest version in sPHENIX GitHub at line 42 of file G4CellNtuple.h
Referenced by Init(), and process_event().
Fun4AllHistoManager* G4CellNtuple::hm protected
Definition at line 40 of file G4CellNtuple.h.
View newest version in sPHENIX GitHub at line 40 of file G4CellNtuple.h
Referenced by End(), Init(), and ~G4CellNtuple().
int G4CellNtuple::nblocks protected
Definition at line 39 of file G4CellNtuple.h.
View newest version in sPHENIX GitHub at line 39 of file G4CellNtuple.h
std::vector<TH1 *> G4CellNtuple::nhits protected
Definition at line 41 of file G4CellNtuple.h.
View newest version in sPHENIX GitHub at line 41 of file G4CellNtuple.h
TNtuple* G4CellNtuple::ntup protected
Definition at line 47 of file G4CellNtuple.h.
View newest version in sPHENIX GitHub at line 47 of file G4CellNtuple.h
Referenced by End(), Init(), and process_event().
TFile* G4CellNtuple::outfile protected
Definition at line 48 of file G4CellNtuple.h.
View newest version in sPHENIX GitHub at line 48 of file G4CellNtuple.h
Referenced by End(), and Init().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4histos/G4CellNtuple.h
coresoftware/blob/master/simulation/g4simulation/g4histos/G4CellNtuple.cc