Analysis Software: Jetscape::JetScapeModuleBase Class Reference
Jetscape::JetScapeModuleBase Class Reference
#include <JETSCAPE/blob/main/src/framework/JetScapeModuleBase.h>
Public Member Functions
JetScapeModuleBase ()
JetScapeModuleBase (string m_name)
virtual ~JetScapeModuleBase ()
virtual void Init ()
virtual void Exec ()
virtual void Clear ()
void SetXMLMainFileName (string m_name)
string GetXMLMainFileName ()
void SetXMLUserFileName (string m_name)
string GetXMLUserFileName ()
shared_ptr< std::mt19937 > GetMt19937Generator ()
tinyxml2::XMLElement * GetXMLElement (std::initializer_list< const char * > path, bool isRequired=true)
std::string GetXMLElementText (std::initializer_list< const char * > path, bool isRequired=true)
int GetXMLElementInt (std::initializer_list< const char * > path, bool isRequired=true)
double GetXMLElementDouble (std::initializer_list< const char * > path, bool isRequired=true)
Public Member Functions inherited from Jetscape::JetScapeTask
JetScapeTask ()
virtual ~JetScapeTask ()
virtual void Finish ()
virtual void ExecuteTasks ()
virtual void ExecuteTask ()
virtual void InitTask ()
virtual void InitTasks ()
virtual void ClearTasks ()
virtual void ClearTask ()
virtual void FinishTask ()
virtual void FinishTasks ()
virtual void WriteTasks (weak_ptr< JetScapeWriter > w)
virtual void WriteTask (weak_ptr< JetScapeWriter > w)
virtual void CollectHeader (weak_ptr< JetScapeWriter > w)
virtual void CollectHeaders (weak_ptr< JetScapeWriter > w)
virtual void Add (shared_ptr< JetScapeTask > m_tasks)
virtual const int GetMyTaskNumber () const
const vector< shared_ptr
< JetScapeTask > > GetTaskList () const
shared_ptr< JetScapeTask > GetTaskAt (int i)
void EraseTaskLast ()
void EraseTaskAt (int i)
void ResizeTaskList (int i)
void ClearTaskList ()
int GetNumberOfTasks ()
const bool GetActive () const
void SetActive (bool m_active_exec)
void SetId (string m_id)
const string GetId () const
const shared_ptr
< JetScapeModuleMutex > GetMutex () const
void SetMutex (shared_ptr< JetScapeModuleMutex > m_mutex)
Public Member Functions inherited from sigslot::has_slots< sigslot::multi_threaded_local >
has_slots ()
has_slots (const has_slots &hs)
void signal_connect (_signal_base< sigslot::multi_threaded_local > *sender)
void signal_disconnect (_signal_base< sigslot::multi_threaded_local > *sender)
virtual ~has_slots ()
void disconnect_all ()
Static Public Member Functions
static int GetCurrentEvent ()
static void IncrementCurrentEvent ()
Private Attributes
std::string xml_main_file_name
std::string xml_user_file_name
shared_ptr< std::mt19937 > mt19937_generator_
Static Private Attributes
static int current_event = 0
Detailed Description
Definition at line 32 of file JetScapeModuleBase.h.
View newest version in sPHENIX GitHub at line 32 of file JetScapeModuleBase.h
Constructor & Destructor Documentation
Jetscape::JetScapeModuleBase::JetScapeModuleBase ()
Default constructor to create a JetScapeModuleBase. It sets the XML file name to a default string value.
Definition at line 34 of file JetScapeModuleBase.cc.
View newest version in sPHENIX GitHub at line 34 of file JetScapeModuleBase.cc
Jetscape::JetScapeModuleBase::JetScapeModuleBase (string m_name)
This is a constructor to create a JetScapeModuleBase. It sets the XML file name to "m_name" to be used to read input parameters.
Jetscape::JetScapeModuleBase::~JetScapeModuleBase () virtual
This is a destructor for the JetScapeModuleBase.
Definition at line 41 of file JetScapeModuleBase.cc.
View newest version in sPHENIX GitHub at line 41 of file JetScapeModuleBase.cc
References sigslot::has_slots< sigslot::multi_threaded_local >::disconnect_all().
Member Function Documentation
virtual void Jetscape::JetScapeModuleBase::Clear (void) inline virtual
A virtual function to define a default Clear() function for a JetScapeModuleBase. It can be overridden by different modules/tasks.
Reimplemented from Jetscape::JetScapeTask.
Reimplemented in Jetscape::FluidDynamics, Jetscape::JetEnergyLoss, Jetscape::TrentoInitial, Jetscape::PreequilibriumDynamics, Jetscape::HardProcess, Jetscape::InitialState, InitialFromFile, IPGlasmaWrapper, NcollListFromFile, iSpectraSamplerWrapper, Jetscape::Hadronization, AdSCFT, Jetscape::HadronPrinter, Jetscape::HadronizationManager, Jetscape::SoftParticlization, and Jetscape::PartonPrinter.
Definition at line 60 of file JetScapeModuleBase.h.
View newest version in sPHENIX GitHub at line 60 of file JetScapeModuleBase.h
virtual void Jetscape::JetScapeModuleBase::Exec () inline virtual
A virtual function to define a default Exec() function for a JetScapeModuleBase. It can be overridden by different modules/tasks.
Reimplemented from Jetscape::JetScapeTask.
Reimplemented in Jetscape::FluidDynamics, Jetscape::JetEnergyLoss, Jetscape::TrentoInitial, epemGun, Jetscape::PreequilibriumDynamics, PythiaGun, Jetscape::JetScapeWriterHepMC, Jetscape::JetScapeWriterRootHepMC, Jetscape::HardProcess, Jetscape::InitialState, InitialFromFile, Jetscape::JetScapeWriterFinalStateStream< T >, Jetscape::JetScape, iSpectraSamplerWrapper, IPGlasmaWrapper, Jetscape::JetScapeWriterStream< T >, NcollListFromFile, PGun, Jetscape::Afterburner, Jetscape::HadronPrinter, Jetscape::HadronizationManager, Jetscape::SoftParticlization, Jetscape::Hadronization, Jetscape::JetScapeWriterAsciiGZ, and Jetscape::PartonPrinter.
Definition at line 56 of file JetScapeModuleBase.h.
View newest version in sPHENIX GitHub at line 56 of file JetScapeModuleBase.h
static int Jetscape::JetScapeModuleBase::GetCurrentEvent () inline static
This function returns the current event number.
Definition at line 80 of file JetScapeModuleBase.h.
View newest version in sPHENIX GitHub at line 80 of file JetScapeModuleBase.h
References current_event.
Referenced by Jetscape::JetScapeWriterHepMC::WriteEvent(), Jetscape::JetScapeWriterRootHepMC::WriteEvent(), and Jetscape::JetScapeWriterAsciiGZ::WriteHeaderToFile().
shared_ptr< std::mt19937 > Jetscape::JetScapeModuleBase::GetMt19937Generator ()
This function returns a random number based on Mersenne-Twister algorithm.
Definition at line 60 of file JetScapeModuleBase.cc.
View newest version in sPHENIX GitHub at line 60 of file JetScapeModuleBase.cc
References Jetscape::JetScapeTaskSupport::GetMt19937Generator(), Jetscape::JetScapeTask::GetMyTaskNumber(), Jetscape::JetScapeTaskSupport::Instance(), and mt19937_generator_.
Referenced by Jetscape::TrentoInitial::InitTask(), NcollListFromFile::SampleABinaryCollisionPoint(), IPGlasmaWrapper::SampleABinaryCollisionPoint(), and Jetscape::InitialState::SampleABinaryCollisionPoint().
tinyxml2::XMLElement* Jetscape::JetScapeModuleBase::GetXMLElement (std::initializer_list< const char * > path, bool isRequired = true) inline
Helper functions for XML parsing, wrapping functionality in JetScapeXML:
Definition at line 92 of file JetScapeModuleBase.h.
View newest version in sPHENIX GitHub at line 92 of file JetScapeModuleBase.h
References Jetscape::JetScapeXML::GetElement(), and Jetscape::JetScapeXML::Instance().
Referenced by Brick::InitTask(), and Jetscape::TrentoInitial::InitTask().
double Jetscape::JetScapeModuleBase::GetXMLElementDouble (std::initializer_list< const char * > path, bool isRequired = true) inline
Definition at line 104 of file JetScapeModuleBase.h.
View newest version in sPHENIX GitHub at line 104 of file JetScapeModuleBase.h
References Jetscape::JetScapeXML::GetElementDouble(), and Jetscape::JetScapeXML::Instance().
Referenced by Jetscape::SoftParticlization::check_boost_invariance(), AdSCFT::Init(), Jetscape::InitialState::Init(), PGun::InitTask(), and Brick::InitTask().
int Jetscape::JetScapeModuleBase::GetXMLElementInt (std::initializer_list< const char * > path, bool isRequired = true) inline
Definition at line 100 of file JetScapeModuleBase.h.
View newest version in sPHENIX GitHub at line 100 of file JetScapeModuleBase.h
References Jetscape::JetScapeXML::GetElementInt(), and Jetscape::JetScapeXML::Instance().
Referenced by Jetscape::JetScape::ReadGeneralParametersFromXML().
std::string Jetscape::JetScapeModuleBase::GetXMLElementText (std::initializer_list< const char * > path, bool isRequired = true) inline
Definition at line 96 of file JetScapeModuleBase.h.
View newest version in sPHENIX GitHub at line 96 of file JetScapeModuleBase.h
References Jetscape::JetScapeXML::GetElementText(), and Jetscape::JetScapeXML::Instance().
Referenced by Jetscape::JetScape::CheckForWriterFromXML(), Jetscape::JetScape::DetermineTaskListFromXML(), Jetscape::JetScape::DetermineWritersFromXML(), NcollListFromFile::Exec(), InitialFromFile::Exec(), AdSCFT::Init(), PGun::InitTask(), Brick::InitTask(), and Jetscape::JetScape::ReadGeneralParametersFromXML().
string Jetscape::JetScapeModuleBase::GetXMLMainFileName () inline
This function returns the XML file name. This file contains the output data for the modules/tasks of a JetScapeTask.
Definition at line 68 of file JetScapeModuleBase.h.
View newest version in sPHENIX GitHub at line 68 of file JetScapeModuleBase.h
References xml_main_file_name.
Referenced by Jetscape::JetScape::Init().
string Jetscape::JetScapeModuleBase::GetXMLUserFileName () inline
This function returns the XML file name. This file contains the output data for the modules/tasks of a JetScapeTask.
Definition at line 76 of file JetScapeModuleBase.h.
View newest version in sPHENIX GitHub at line 76 of file JetScapeModuleBase.h
References xml_user_file_name.
Referenced by Jetscape::JetScape::Init().
static void Jetscape::JetScapeModuleBase::IncrementCurrentEvent () inline static
This function increases the current event number by one.
Definition at line 84 of file JetScapeModuleBase.h.
View newest version in sPHENIX GitHub at line 84 of file JetScapeModuleBase.h
References current_event.
Referenced by Jetscape::JetScape::Exec().
void Jetscape::JetScapeModuleBase::Init () virtual
A virtual function for a default initialization of a JetScapeModuleBase. It also checks whether a XML file is loaded or not.
Reimplemented from Jetscape::JetScapeTask.
Reimplemented in Martini, Jetscape::FluidDynamics, Jetscape::JetEnergyLoss, Jetscape::JetScapeWriterHepMC, Jetscape::PreequilibriumDynamics, Jetscape::JetScapeWriterRootHepMC, LBT, Jetscape::HardProcess, Jetscape::JetScapeWriterFinalStateStream< T >, Jetscape::InitialState, Jetscape::JetScapeWriterStream< T >, AdSCFT, Jetscape::Afterburner, Jetscape::JetScape, Jetscape::HadronPrinter, Jetscape::HadronizationManager, Jetscape::SoftParticlization, Jetscape::Hadronization, HybridHadronization, Jetscape::JetScapeWriterAsciiGZ, Jetscape::PartonPrinter, ColorlessHadronization, Matter, ColoredHadronization, and ElossValidate.
Definition at line 46 of file JetScapeModuleBase.cc.
View newest version in sPHENIX GitHub at line 46 of file JetScapeModuleBase.cc
References Jetscape::JetScapeXML::Instance(), and JSWARN.
Referenced by Jetscape::SoftParticlization::Init(), and Jetscape::InitialState::Init().
void Jetscape::JetScapeModuleBase::SetXMLMainFileName (string m_name) inline
This function sets the name of the XML file to be used to store output information for the modules/tasks of a JetScapeTask.
Definition at line 64 of file JetScapeModuleBase.h.
View newest version in sPHENIX GitHub at line 64 of file JetScapeModuleBase.h
References m_name(), and xml_main_file_name.
void Jetscape::JetScapeModuleBase::SetXMLUserFileName (string m_name) inline
This function sets the name of the XML file to be used to store output information for the modules/tasks of a JetScapeTask.
Definition at line 72 of file JetScapeModuleBase.h.
View newest version in sPHENIX GitHub at line 72 of file JetScapeModuleBase.h
References m_name(), and xml_user_file_name.
Member Data Documentation
int Jetscape::JetScapeModuleBase::current_event = 0 static private
Definition at line 112 of file JetScapeModuleBase.h.
View newest version in sPHENIX GitHub at line 112 of file JetScapeModuleBase.h
Referenced by GetCurrentEvent(), and IncrementCurrentEvent().
shared_ptr<std::mt19937> Jetscape::JetScapeModuleBase::mt19937_generator_ private
Definition at line 113 of file JetScapeModuleBase.h.
View newest version in sPHENIX GitHub at line 113 of file JetScapeModuleBase.h
Referenced by GetMt19937Generator().
std::string Jetscape::JetScapeModuleBase::xml_main_file_name private
Definition at line 110 of file JetScapeModuleBase.h.
View newest version in sPHENIX GitHub at line 110 of file JetScapeModuleBase.h
Referenced by GetXMLMainFileName(), and SetXMLMainFileName().
std::string Jetscape::JetScapeModuleBase::xml_user_file_name private
Definition at line 111 of file JetScapeModuleBase.h.
View newest version in sPHENIX GitHub at line 111 of file JetScapeModuleBase.h
Referenced by GetXMLUserFileName(), and SetXMLUserFileName().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/JetScapeModuleBase.h
JETSCAPE/blob/main/src/framework/JetScapeModuleBase.cc