Analysis Software: ActsExamples::CKFPerformanceWriter Exception Reference
ActsExamples::CKFPerformanceWriter Exception Reference final
#include <acts/blob/sPHENIX/Examples/Io/Performance/ActsExamples/Io/Performance/CKFPerformanceWriter.hpp>
Classes
struct Config
Public Types
using HitParticlesMap = IndexMultimap< ActsFatras::Barcode >
Public Member Functions
CKFPerformanceWriter (Config cfg, Acts::Logging::Level lvl)
Construct from configuration and log level.
~CKFPerformanceWriter () override
ProcessCode finalize () override
Finalize plots.
const Config & config () const
Get readonly access to the config parameters.
Public Member Functions inherited from ActsExamples::WriterT< TrajectoriesContainer >
WriterT (std::string objectName, std::string writerName, Acts::Logging::Level level)
std::string name () const override
Provide the name of the writer.
ProcessCode write (const AlgorithmContext &context) override
Read the object and call the type-specific member function.
ProcessCode finalize () override
No-op default implementation.
Public Member Functions inherited from ActsExamples::IWriter
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Fulfil the algorithm interface.
Public Member Functions inherited from ActsExamples::SequenceElement
virtual ~SequenceElement ()=default
const std::vector< const
DataHandleBase * > & writeHandles () const
const std::vector< const
DataHandleBase * > & readHandles () const
Private Member Functions
ProcessCode writeT (const AlgorithmContext &ctx, const TrajectoriesContainer &trajectories) override
Private Attributes
Config m_cfg
std::mutex m_writeMutex
Mutex used to protect multi-threaded writes.
TFile * m_outputFile {nullptr}
EffPlotTool m_effPlotTool
Plot tool for efficiency.
EffPlotTool::EffPlotCache m_effPlotCache
FakeRatePlotTool m_fakeRatePlotTool
Plot tool for fake rate.
FakeRatePlotTool::FakeRatePlotCache m_fakeRatePlotCache {}
DuplicationPlotTool m_duplicationPlotTool
Plot tool for duplication rate.
DuplicationPlotTool::DuplicationPlotCache m_duplicationPlotCache {}
TrackSummaryPlotTool m_trackSummaryPlotTool
Plot tool for track hit info.
TrackSummaryPlotTool::TrackSummaryPlotCache m_trackSummaryPlotCache {}
size_t m_nTotalTracks = 0
size_t m_nTotalMatchedTracks = 0
size_t m_nTotalFakeTracks = 0
size_t m_nTotalDuplicateTracks = 0
size_t m_nTotalParticles = 0
size_t m_nTotalMatchedParticles = 0
size_t m_nTotalDuplicateParticles = 0
size_t m_nTotalFakeParticles = 0
ReadDataHandle
< SimParticleContainer > m_inputParticles {this, "InputParticles"}
ReadDataHandle< HitParticlesMap > m_inputMeasurementParticlesMap
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::WriterT< TrajectoriesContainer >
const Acts::Logger & logger () const
Detailed Description
Write out the performance of CombinatorialKalmanFilter (CKF), e.g. track efficiency, fake rate etc. : add duplication plots
A common file can be provided for the writer to attach his TTree, this is done by setting the Config::rootFile pointer to an existing file
Safe to use from multiple writer threads - uses a std::mutex lock.
Definition at line 48 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 48 of file CKFPerformanceWriter.hpp
Member Typedef Documentation
using ActsExamples::CKFPerformanceWriter::HitParticlesMap = IndexMultimap<ActsFatras::Barcode>
Definition at line 50 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 50 of file CKFPerformanceWriter.hpp
Constructor & Destructor Documentation
ActsExamples::CKFPerformanceWriter::CKFPerformanceWriter (Config cfg, Acts::Logging::Level lvl)
Construct from configuration and log level.
Definition at line 36 of file CKFPerformanceWriter.cpp.
View newest version in sPHENIX GitHub at line 36 of file CKFPerformanceWriter.cpp
References ActsExamples::EffPlotTool::book(), ActsExamples::TrackSummaryPlotTool::book(), ActsExamples::DuplicationPlotTool::book(), ActsExamples::FakeRatePlotTool::book(), ActsExamples::CKFPerformanceWriter::Config::fileMode, ActsExamples::CKFPerformanceWriter::Config::filePath, ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::CKFPerformanceWriter::Config::inputMeasurementParticlesMap, ActsExamples::CKFPerformanceWriter::Config::inputParticles, m_cfg, m_duplicationPlotCache, m_duplicationPlotTool, m_effPlotCache, m_effPlotTool, m_fakeRatePlotCache, m_fakeRatePlotTool, m_inputMeasurementParticlesMap, m_inputParticles, m_outputFile, m_trackSummaryPlotCache, and m_trackSummaryPlotTool.
ActsExamples::CKFPerformanceWriter::~CKFPerformanceWriter () override
Definition at line 73 of file CKFPerformanceWriter.cpp.
View newest version in sPHENIX GitHub at line 73 of file CKFPerformanceWriter.cpp
Member Function Documentation
const Config& ActsExamples::CKFPerformanceWriter::config () const inline
Get readonly access to the config parameters.
Definition at line 87 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 87 of file CKFPerformanceWriter.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::CKFPerformanceWriter::finalize () override virtual
Finalize plots.
Implements ActsExamples::SequenceElement.
Definition at line 83 of file CKFPerformanceWriter.cpp.
View newest version in sPHENIX GitHub at line 83 of file CKFPerformanceWriter.cpp
References ACTS_DEBUG, ACTS_INFO, f, perf_headwind::name, SUCCESS, and testSigmaEff::v.
ActsExamples::ProcessCode ActsExamples::CKFPerformanceWriter::writeT (const AlgorithmContext & context, const TrajectoriesContainer & t) override private virtual
Type-specific write function implementation this method is implemented in the user implementation
Parameters
[in] context is the algorithm context that guarantees event consistency
Template Parameters
[in] is the templated collection to be written
Implements ActsExamples::WriterT< TrajectoriesContainer >.
Definition at line 136 of file CKFPerformanceWriter.cpp.
View newest version in sPHENIX GitHub at line 136 of file CKFPerformanceWriter.cpp
References _, ACTS_DEBUG, ACTS_WARNING, ActsExamples::identifyContributingParticles(), check_smearing_config::lhs, m_cfg(), particle, particles, Acts::VectorHelpers::perp(), train_ambiguity_solver::pid, check_smearing_config::rhs, Acts::Experimental::detail::BlueprintHelper::sort(), SUCCESS, and Acts::MultiTrajectoryHelpers::trajectoryState().
Member Data Documentation
Config ActsExamples::CKFPerformanceWriter::m_cfg private
Definition at line 93 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 93 of file CKFPerformanceWriter.hpp
Referenced by CKFPerformanceWriter(), and config().
DuplicationPlotTool::DuplicationPlotCache ActsExamples::CKFPerformanceWriter::m_duplicationPlotCache {} private
Definition at line 105 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 105 of file CKFPerformanceWriter.hpp
Referenced by CKFPerformanceWriter().
DuplicationPlotTool ActsExamples::CKFPerformanceWriter::m_duplicationPlotTool private
Plot tool for duplication rate.
Definition at line 104 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 104 of file CKFPerformanceWriter.hpp
Referenced by CKFPerformanceWriter().
EffPlotTool::EffPlotCache ActsExamples::CKFPerformanceWriter::m_effPlotCache private
Definition at line 99 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 99 of file CKFPerformanceWriter.hpp
Referenced by CKFPerformanceWriter().
EffPlotTool ActsExamples::CKFPerformanceWriter::m_effPlotTool private
Plot tool for efficiency.
Definition at line 98 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 98 of file CKFPerformanceWriter.hpp
Referenced by CKFPerformanceWriter().
FakeRatePlotTool::FakeRatePlotCache ActsExamples::CKFPerformanceWriter::m_fakeRatePlotCache {} private
Definition at line 102 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 102 of file CKFPerformanceWriter.hpp
Referenced by CKFPerformanceWriter().
FakeRatePlotTool ActsExamples::CKFPerformanceWriter::m_fakeRatePlotTool private
Plot tool for fake rate.
Definition at line 101 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 101 of file CKFPerformanceWriter.hpp
Referenced by CKFPerformanceWriter().
ReadDataHandle<HitParticlesMap> ActsExamples::CKFPerformanceWriter::m_inputMeasurementParticlesMap private
Initial value:
{
      this, "InputMeasurementParticlesMap"}
Definition at line 121 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 121 of file CKFPerformanceWriter.hpp
Referenced by CKFPerformanceWriter().
ReadDataHandle<SimParticleContainer> ActsExamples::CKFPerformanceWriter::m_inputParticles {this, "InputParticles"} private
Definition at line 120 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 120 of file CKFPerformanceWriter.hpp
Referenced by CKFPerformanceWriter().
size_t ActsExamples::CKFPerformanceWriter::m_nTotalDuplicateParticles = 0 private
Definition at line 117 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 117 of file CKFPerformanceWriter.hpp
size_t ActsExamples::CKFPerformanceWriter::m_nTotalDuplicateTracks = 0 private
Definition at line 114 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 114 of file CKFPerformanceWriter.hpp
size_t ActsExamples::CKFPerformanceWriter::m_nTotalFakeParticles = 0 private
Definition at line 118 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 118 of file CKFPerformanceWriter.hpp
size_t ActsExamples::CKFPerformanceWriter::m_nTotalFakeTracks = 0 private
Definition at line 113 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 113 of file CKFPerformanceWriter.hpp
size_t ActsExamples::CKFPerformanceWriter::m_nTotalMatchedParticles = 0 private
Definition at line 116 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 116 of file CKFPerformanceWriter.hpp
size_t ActsExamples::CKFPerformanceWriter::m_nTotalMatchedTracks = 0 private
Definition at line 112 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 112 of file CKFPerformanceWriter.hpp
size_t ActsExamples::CKFPerformanceWriter::m_nTotalParticles = 0 private
Definition at line 115 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 115 of file CKFPerformanceWriter.hpp
size_t ActsExamples::CKFPerformanceWriter::m_nTotalTracks = 0 private
Definition at line 111 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 111 of file CKFPerformanceWriter.hpp
TFile* ActsExamples::CKFPerformanceWriter::m_outputFile {nullptr} private
Definition at line 96 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 96 of file CKFPerformanceWriter.hpp
Referenced by CKFPerformanceWriter().
TrackSummaryPlotTool::TrackSummaryPlotCache ActsExamples::CKFPerformanceWriter::m_trackSummaryPlotCache {} private
Definition at line 108 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 108 of file CKFPerformanceWriter.hpp
Referenced by CKFPerformanceWriter().
TrackSummaryPlotTool ActsExamples::CKFPerformanceWriter::m_trackSummaryPlotTool private
Plot tool for track hit info.
Definition at line 107 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 107 of file CKFPerformanceWriter.hpp
Referenced by CKFPerformanceWriter().
std::mutex ActsExamples::CKFPerformanceWriter::m_writeMutex private
Mutex used to protect multi-threaded writes.
Definition at line 95 of file CKFPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 95 of file CKFPerformanceWriter.hpp
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Io/Performance/ActsExamples/Io/Performance/CKFPerformanceWriter.hpp
acts/blob/sPHENIX/Examples/Io/Performance/ActsExamples/Io/Performance/CKFPerformanceWriter.cpp