Analysis Software: Acts::TrackingGeometryBuilder Class Reference
Acts::TrackingGeometryBuilder Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Geometry/TrackingGeometryBuilder.hpp>
Classes
struct Config
Public Member Functions
TrackingGeometryBuilder (const Config &cgbConfig, std::unique_ptr< const Logger > logger=getDefaultLogger("TrackingGeometryBuilder", Logging::INFO))
~TrackingGeometryBuilder () override=default
Destructor.
std::unique_ptr< const
TrackingGeometry > trackingGeometry (const GeometryContext &gctx) const final
void setConfiguration (const Config &cgbConfig)
const Config & getConfiguration () const
void setLogger (std::unique_ptr< const Logger > newLogger)
Public Member Functions inherited from Acts::ITrackingGeometryBuilder
virtual ~ITrackingGeometryBuilder ()=default
Virtual destructor.
Private Member Functions
const Logger & logger () const
Private access method to the logger.
Private Attributes
Config m_cfg
Configuration member.
std::unique_ptr< const Logger > m_logger
the logging instance
Detailed Description
The Acts::TrackingGeometry Builder for volumes that wrap around another
It retrieves an array of std::functions that build the TrackingGeometry sequentially in order, with the following options:
contained (e.g. a final insertion of a beam pipe of longer extend)
wrapped (e.g. an outer detector wrapping an inner one)
attached (e.g. a neighbor detector attaching to the previous one)
The returned volume of each step must be processable by the previous step
Definition at line 36 of file TrackingGeometryBuilder.hpp.
View newest version in sPHENIX GitHub at line 36 of file TrackingGeometryBuilder.hpp
Constructor & Destructor Documentation
Acts::TrackingGeometryBuilder::TrackingGeometryBuilder (const Config & cgbConfig, std::unique_ptr< const Logger > logger = getDefaultLogger("TrackingGeometryBuilder", Logging::INFO))
Constructor
Parameters
[in] cgbConfig is the configuration struct for this builder
[in] logger logging instance
Definition at line 17 of file TrackingGeometryBuilder.cpp.
View newest version in sPHENIX GitHub at line 17 of file TrackingGeometryBuilder.cpp
References setConfiguration().
Acts::TrackingGeometryBuilder::~TrackingGeometryBuilder () override default
Destructor.
Member Function Documentation
const Acts::TrackingGeometryBuilder::Config & Acts::TrackingGeometryBuilder::getConfiguration () const
Get configuration method
Returns
the current configuration
Definition at line 25 of file TrackingGeometryBuilder.cpp.
View newest version in sPHENIX GitHub at line 25 of file TrackingGeometryBuilder.cpp
References m_cfg().
const Logger& Acts::TrackingGeometryBuilder::logger () const inline private
Private access method to the logger.
Definition at line 96 of file TrackingGeometryBuilder.hpp.
View newest version in sPHENIX GitHub at line 96 of file TrackingGeometryBuilder.hpp
References m_logger.
void Acts::TrackingGeometryBuilder::setConfiguration (const Config & cgbConfig)
Set configuration method
Parameters
cgbConfig is the new configuration struct
Definition at line 29 of file TrackingGeometryBuilder.cpp.
View newest version in sPHENIX GitHub at line 29 of file TrackingGeometryBuilder.cpp
References m_cfg(), and Acts::TrackingGeometryBuilder::Config::trackingVolumeBuilders.
Referenced by TrackingGeometryBuilder().
void Acts::TrackingGeometryBuilder::setLogger (std::unique_ptr< const Logger > newLogger)
set logging instance
Parameters
newLogger the new logging instance
Definition at line 37 of file TrackingGeometryBuilder.cpp.
View newest version in sPHENIX GitHub at line 37 of file TrackingGeometryBuilder.cpp
References m_logger, and testing::internal::move().
std::unique_ptr< const Acts::TrackingGeometry > Acts::TrackingGeometryBuilder::trackingGeometry (const GeometryContext & gctx) const final virtual
TrackingGeometry Interface method
Parameters
gctx geometry context of that building call
Returns
a unique pointer to a TrackingGeometry
Implements Acts::ITrackingGeometryBuilder.
Definition at line 43 of file TrackingGeometryBuilder.cpp.
View newest version in sPHENIX GitHub at line 43 of file TrackingGeometryBuilder.cpp
References ACTS_INFO, logger(), m_cfg(), and testing::internal::move().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::EventDataView3DTest::createDetector(), and Acts::Test::makeToyDetector().
Member Data Documentation
Config Acts::TrackingGeometryBuilder::m_cfg private
Configuration member.
Definition at line 93 of file TrackingGeometryBuilder.hpp.
View newest version in sPHENIX GitHub at line 93 of file TrackingGeometryBuilder.hpp
std::unique_ptr<const Logger> Acts::TrackingGeometryBuilder::m_logger private
the logging instance
Definition at line 99 of file TrackingGeometryBuilder.hpp.
View newest version in sPHENIX GitHub at line 99 of file TrackingGeometryBuilder.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Geometry/TrackingGeometryBuilder.hpp
acts/blob/sPHENIX/Core/src/Geometry/TrackingGeometryBuilder.cpp