Analysis Software: ReadSynRadFiles Class Reference
ReadSynRadFiles Class Reference
#include <analysis/blob/master/EIC-SynRad/SynRadAna/ReadSynRadFiles.h>
Public Member Functions
ReadSynRadFiles (const std::string &name="ReadSynRadFiles")
virtual ~ReadSynRadFiles ()
int Init (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
bool OpenInputFile (const std::string &name)
void SetEntryPerEvent (int e)
void SetNodeName (const std::string &s)
void set_vertex_distribution_function (PHHepMCGenHelper::VTXFUNC x, PHHepMCGenHelper::VTXFUNC y, PHHepMCGenHelper::VTXFUNC z, PHHepMCGenHelper::VTXFUNC t)
toss a new vertex according to a Uniform or Gaus distribution
void set_vertex_distribution_mean (const double x, const double y, const double z, const double t)
set the mean value of the vertex distribution, use PHENIX units of cm, ns
void set_vertex_distribution_width (const double x, const double y, const double z, const double t)
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
void set_reuse_vertex (int src_embedding_id)
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
int get_embedding_id () const
void set_embedding_id (int id)
void set_reverseXZ (bool b=true)
whether to reverse x and z axis directions (rotate around y bay pi)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
void GetTree ()
int CreateNodeTree (PHCompositeNode *topNode)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
std::string filename
std::ifstream m_csv_input
int nEntries
int entry
erhic::EventMC * GenEvent
std::string _node_name
PHHepMCGenHelper hepmc_helper
helper for insert HepMC event to DST node and add vertex smearing
bool m_reverseXZ = false
whether to reverse x and z axis directions (rotate around y bay pi)
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Detailed Description
Definition at line 21 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 21 of file ReadSynRadFiles.h
Constructor & Destructor Documentation
ReadSynRadFiles::ReadSynRadFiles (const std::string & name = "ReadSynRadFiles")
Definition at line 39 of file ReadSynRadFiles.cc.
View newest version in sPHENIX GitHub at line 39 of file ReadSynRadFiles.cc
References hepmc_helper, and PHHepMCGenHelper::set_embedding_id().
ReadSynRadFiles::~ReadSynRadFiles () virtual
Definition at line 53 of file ReadSynRadFiles.cc.
View newest version in sPHENIX GitHub at line 53 of file ReadSynRadFiles.cc
Member Function Documentation
int ReadSynRadFiles::CreateNodeTree (PHCompositeNode * topNode) protected
Creade node on node tree
Definition at line 242 of file ReadSynRadFiles.cc.
View newest version in sPHENIX GitHub at line 242 of file ReadSynRadFiles.cc
References PHHepMCGenHelper::create_node_tree(), Fun4AllReturnCodes::EVENT_OK, and hepmc_helper.
Referenced by Init().
int ReadSynRadFiles::get_embedding_id () const inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 65 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 65 of file ReadSynRadFiles.h
References PHHepMCGenHelper::get_embedding_id(), and hepmc_helper.
void ReadSynRadFiles::GetTree () protected
Get tree from input file
int ReadSynRadFiles::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 72 of file ReadSynRadFiles.cc.
View newest version in sPHENIX GitHub at line 72 of file ReadSynRadFiles.cc
References CreateNodeTree().
bool ReadSynRadFiles::OpenInputFile (const std::string & name)
Specify name of input file to open
Definition at line 59 of file ReadSynRadFiles.cc.
View newest version in sPHENIX GitHub at line 59 of file ReadSynRadFiles.cc
References assert, filename, line, m_csv_input, and perf_headwind::name.
int ReadSynRadFiles::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 79 of file ReadSynRadFiles.cc.
View newest version in sPHENIX GitHub at line 79 of file ReadSynRadFiles.cc
References Fun4AllReturnCodes::ABORTRUN, assert, entry, filename, hepmc_helper, PHHepMCGenHelper::insert_event(), line, m_csv_input, m_reverseXZ, nEntries, testSigmaEff::v, vec, and Fun4AllBase::Verbosity().
void ReadSynRadFiles::set_embedding_id (int id) inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 71 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 71 of file ReadSynRadFiles.h
References hepmc_helper, and PHHepMCGenHelper::set_embedding_id().
void ReadSynRadFiles::set_reuse_vertex (int src_embedding_id) inline
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
Definition at line 56 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 56 of file ReadSynRadFiles.h
References hepmc_helper, and PHHepMCGenHelper::set_reuse_vertex().
void ReadSynRadFiles::set_reverseXZ (bool b = true) inline
whether to reverse x and z axis directions (rotate around y bay pi)
Definition at line 74 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 74 of file ReadSynRadFiles.h
References KFPMath::b, and m_reverseXZ.
void ReadSynRadFiles::set_vertex_distribution_function (PHHepMCGenHelper::VTXFUNC x, PHHepMCGenHelper::VTXFUNC y, PHHepMCGenHelper::VTXFUNC z, PHHepMCGenHelper::VTXFUNC t) inline
toss a new vertex according to a Uniform or Gaus distribution
Definition at line 38 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 38 of file ReadSynRadFiles.h
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_function().
void ReadSynRadFiles::set_vertex_distribution_mean (const double x, const double y, const double z, const double t) inline
set the mean value of the vertex distribution, use PHENIX units of cm, ns
Definition at line 44 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 44 of file ReadSynRadFiles.h
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_mean().
void ReadSynRadFiles::set_vertex_distribution_width (const double x, const double y, const double z, const double t) inline
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
Definition at line 50 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 50 of file ReadSynRadFiles.h
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_width().
void ReadSynRadFiles::SetEntryPerEvent (int e) inline
Set first entry from input tree to be used
Definition at line 34 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 34 of file ReadSynRadFiles.h
References Acts::UnitConstants::e, and nEntries.
void ReadSynRadFiles::SetNodeName (const std::string & s) inline
Set name of output node
Definition at line 36 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 36 of file ReadSynRadFiles.h
References _node_name, and physmon_simulation::s.
Member Data Documentation
std::string ReadSynRadFiles::_node_name protected
Definition at line 101 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 101 of file ReadSynRadFiles.h
Referenced by SetNodeName().
int ReadSynRadFiles::entry protected
Number of current event being used from input tree
Definition at line 93 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 93 of file ReadSynRadFiles.h
Referenced by process_event().
std::string ReadSynRadFiles::filename protected
Name of file containing input tree
Definition at line 84 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 84 of file ReadSynRadFiles.h
Referenced by cpp.ast.Include::__str__(), cpp.ast.AstBuilder::_GetClass(), cpp.ast.AstBuilder::HandleError(), OpenInputFile(), and process_event().
erhic::EventMC* ReadSynRadFiles::GenEvent protected
Pinter to event record in tree (= branch). Use 'abstract' EventMC class pointer from which all event types (erhic::EventMilou etc) inherit from.
Definition at line 98 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 98 of file ReadSynRadFiles.h
PHHepMCGenHelper ReadSynRadFiles::hepmc_helper protected
helper for insert HepMC event to DST node and add vertex smearing
Definition at line 104 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 104 of file ReadSynRadFiles.h
Referenced by CreateNodeTree(), get_embedding_id(), process_event(), ReadSynRadFiles(), set_embedding_id(), set_reuse_vertex(), set_vertex_distribution_function(), set_vertex_distribution_mean(), and set_vertex_distribution_width().
std::ifstream ReadSynRadFiles::m_csv_input protected
Input tree created with eic-smear tree builder
Definition at line 87 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 87 of file ReadSynRadFiles.h
Referenced by OpenInputFile(), and process_event().
bool ReadSynRadFiles::m_reverseXZ = false protected
whether to reverse x and z axis directions (rotate around y bay pi)
Definition at line 107 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 107 of file ReadSynRadFiles.h
Referenced by process_event(), and set_reverseXZ().
int ReadSynRadFiles::nEntries protected
Number of events in input tree
Definition at line 90 of file ReadSynRadFiles.h.
View newest version in sPHENIX GitHub at line 90 of file ReadSynRadFiles.h
Referenced by process_event(), and SetEntryPerEvent().
The documentation for this class was generated from the following files:
analysis/blob/master/EIC-SynRad/SynRadAna/ReadSynRadFiles.h
analysis/blob/master/EIC-SynRad/SynRadAna/ReadSynRadFiles.cc