Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/EventData/TrackContainerComplianceTests.cpp File Reference
TrackContainerComplianceTests.cpp File Reference
#include "Acts/EventData/MultiTrajectory.hpp"
#include "Acts/EventData/TrackContainer.hpp"
#include "Acts/EventData/VectorMultiTrajectory.hpp"
#include "Acts/EventData/VectorTrackContainer.hpp"
#include "Acts/Tests/CommonHelpers/NonCompileTestHelpers.hpp"
#include "Acts/Utilities/ThrowAssert.hpp"
Functions
ACTS_DOES_NOT_COMPILE_SUITE_BEGIN (BuildFromConstRef)
for (const auto track:tc)
caccNMeasuements (t)
ctc getTrack (idx).covariance().setRandom()
ctp covariance ().setRandom()
Variables
VectorMultiTrajectory mtj
ConstVectorTrackContainer cvtc {std::move(vtc)}
ConstVectorMultiTrajectory cmtj {std::move(mtj)}
TrackContainer tc {vtc, mtj}
auto t = tc.getTrack(tc.addTrack())
ConstTrackAccessor< unsigned int > caccNMeasuements ("nMeasurements")
const auto & ctc = tc
const auto & ctp = t
Function Documentation
ACTS_DOES_NOT_COMPILE_SUITE_BEGIN (BuildFromConstRef)
Definition at line 18 of file TrackContainerComplianceTests.cpp.
View newest version in sPHENIX GitHub at line 18 of file TrackContainerComplianceTests.cpp
References ACTS_DOES_NOT_COMPILE_BEGIN, ACTS_DOES_NOT_COMPILE_END, ctc, testing::internal::move(), mtj, and t.
caccNMeasuements (t)
ctp covariance ()
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), ActsExamples::detail::NuclearInteractionParametrisation::calculateMeanAndCovariance(), Acts::EventDataView3D::decomposeCovariance(), Acts::EventDataView3D::drawBoundTrackParameters(), Acts::EventDataView3D::drawMultiTrajectory(), ActsExamples::SeedingAlgorithm::execute(), ActsExamples::ResPlotTool::fill(), ActsEvaluator::fillFittedTrackParams(), main(), Acts::Vertex< input_track_t >::setFullCovariance(), Acts::transportCovarianceToBound(), Acts::transportCovarianceToCurvilinear(), Acts::transportCovarianceToFree(), Acts::StraightLineStepper::update(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::update(), Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy::update(), ActsEvaluator::visitTrackStates(), ActsExamples::EDM4hepUtil::writeMeasurement(), ActsExamples::CsvMeasurementWriter::writeT(), ActsExamples::RootTrajectorySummaryWriter::writeT(), and ActsExamples::RootTrajectoryStatesWriter::writeT().
for (const auto track:tc)
Initial value:
{
    TrackContainer tc{cvtc, cmtj}
Definition at line 50 of file TrackContainerComplianceTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file TrackContainerComplianceTests.cpp
Referenced by oncsSub_iddrs4v1::decode(), oncsSub_iduppetparams::decode(), oncsSub_idfnalmwpc::decode(), oncsSub_idfnalmwpcv2::decode(), MvtxMon::process_event(), daq_device_random::put_data(), daq_device_pluginexample::put_data(), daq_device_gauss::put_data(), testEventiterator::testEventiterator(), and tileHelper::updateMap().
ctc getTrack (idx)
Variable Documentation
ConstTrackAccessor<unsigned int> caccNMeasuements("nMeasurements")
Referenced by BOOST_AUTO_TEST_CASE_TEMPLATE().
ConstVectorMultiTrajectory cmtj {std::move(mtj)}
Definition at line 57 of file TrackContainerComplianceTests.cpp.
View newest version in sPHENIX GitHub at line 57 of file TrackContainerComplianceTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
const auto& ctc = tc
Definition at line 82 of file TrackContainerComplianceTests.cpp.
View newest version in sPHENIX GitHub at line 82 of file TrackContainerComplianceTests.cpp
Referenced by ACTS_DOES_NOT_COMPILE_SUITE_BEGIN(), and BOOST_AUTO_TEST_CASE().
const auto& ctp = t
Definition at line 87 of file TrackContainerComplianceTests.cpp.
View newest version in sPHENIX GitHub at line 87 of file TrackContainerComplianceTests.cpp
ConstVectorTrackContainer cvtc {std::move(vtc)}
Definition at line 56 of file TrackContainerComplianceTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file TrackContainerComplianceTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
VectorMultiTrajectory mtj
Initial value:
{
  VectorTrackContainer vtc
Definition at line 43 of file TrackContainerComplianceTests.cpp.
View newest version in sPHENIX GitHub at line 43 of file TrackContainerComplianceTests.cpp
Referenced by ACTS_DOES_NOT_COMPILE_SUITE_BEGIN(), and BOOST_AUTO_TEST_CASE().
void t = tc.getTrack(tc.addTrack())
Definition at line 73 of file TrackContainerComplianceTests.cpp.
View newest version in sPHENIX GitHub at line 73 of file TrackContainerComplianceTests.cpp
Referenced by ACTS_DOES_NOT_COMPILE_SUITE_BEGIN(), TrackEvaluation::add_truth_information(), Acts::Python::addExaTrkXTrackFinding(), alphas(), avscatcen(), Jetscape::BilinearInt(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE_TEMPLATE(), byteReverse(), calccorr(), Fluid::calcTotals(), CaloTemplateFit::calo_processing_perchnl(), CaloWaveformFitting::calo_processing_templatefit(), Jetscape::JetScapeWriterHepMC::castVtxToHepMC(), Jetscape::JetScapeWriterRootHepMC::castVtxToHepMC(), CentralCalorimeterRate(), BbcCheck::CheckDST(), checkExtrapolateToCylinder(), TpcClusterBuilder::cluster_hits(), trento::Event::compute_observables(), trento::Event::compute_reduced_thickness(), PHG4Sector::PHG4SectorConstructor::Construct_Sectors(), BEmcRecCEMC::CorrectPosition(), Acts::Sycl::createSeedsForGroupSycl(), Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::createTrackGrid(), CrossSection2RAA_Proposal(), CrystallBall2(), Acts::TGeoSurfaceConverter::cylinderComponents(), daq_begin_immediate(), daq_end_immediate(), daq_shutdown(), oncsSub_iduppetdata::decode(), oncsSub_iduppetdata_v104::decode(), graph::del_edge(), deriv(), Acts::deriveEnergyLossLandauQOverP(), AZigzag::DetermineQ(), Acts::TGeoSurfaceConverter::discComponents(), do_eta_fit2_emc(), do_eta_fit2_ihcal(), do_eta_fit2_ohcal(), do_eta_fit_emc(), doCompression(), ElossValidate::DoEnergyLoss(), Matter::DoEnergyLoss(), AdSCFT::DoEnergyLoss(), Martini::DoEnergyLoss(), dokinematics(), draw_corr(), Draw_EICRate(), Draw_HFJetTruth(), Draw_HFJetTruth3yr(), Draw_HFJetTruth_InvMass(), draw_histogram(), Draw_PHG4DSTReader(), DrawCluster_Res_2Fit(), DrawCluster_Res_2Fit_Electron_NoSVX(), DrawEcal_Likelihood(), DrawEcal_pDST(), DrawEMCalTower(), DrawEMCalTower_LineShape(), DrawEMCalTower_Resolution(), DrawEnergyDensity(), DrawEnergyDensityXY(), DrawGraph(), DrawPrototype2EMCalTower(), DrawPrototype2EMCalTower_Resolution(), DrawPrototype2EMCalTower_ResolutionRecalib(), DrawPrototype2MIPAnalysis(), DrawPrototype2ShowerCalib(), DrawPrototype3EMCalTower(), DrawPrototype3ShowerCalib(), DrawPrototype4EMCalTower(), DrawPrototype4ShowerCalib(), DrawTower_EMCDistribution(), DrawTower_EMCDistribution5x5(), DrawTower_EMCTrigEff(), DrawTower_EMCTrigEff_SlideingWindow2(), DrawTower_Load(), DrawTpcPrototypeGenFitTrkFitter(), DrawTpcPrototypeUnpacker(), DrawTrackingEval(), dvcs_plot(), eicsmear_dvmp_plot2(), eicsmear_dvmp_tree(), EMC_HodoScope_Calibration(), EMCDistribution(), EMCDistribution_ADC(), EMCDistribution_Fast(), EMCDistribution_HCalCalibration(), EMCDistribution_PeakSample_Fast(), EMCDistribution_ShowShape(), EMCDistribution_SUM(), EMCDistribution_SUM_RawADC(), EMCDistributionVSBeam_SUM(), emptyTrackTest(), event_topology_reco(), EvtVtx_map_tklcluster(), ExampleAnalysisDSTReader(), ExampleAnalysisModulePlot(), ActsExamples::PrototracksToSeeds::execute(), ActsExamples::PrototracksToParameters::execute(), ActsExamples::PropagationAlgorithm::execute(), ffdeu(), ffhe3(), ffpro(), ffquas(), FillEnergy(), SingleTpcPoolInput::FillPool(), SingleMicromegasPoolInput::FillPool(), Acts::SeedFinder< external_spacepoint_t, platform_t >::filterCandidates(), Acts::SeedFinderOrthogonal< external_spacepoint_t >::filterCandidates(), ActsExamples::TrackFindingAlgorithmExaTrkX::finalize(), Proto4SampleFrac::find_max(), Proto4ShowerCalib::find_max(), Proto2ShowerCalib::find_max(), Proto3ShowerCalib::find_max(), Proto4TowerCalib::find_max(), ExampleAnalysisModule::find_max(), Acts::GaussianSumFitter< propagator_t, bethe_heitler_approx_t, traj_t >::fit_impl(), FitVerticalScan(), ForwardCalorimeterRate(), Acts::Transform3JsonConverter::fromJson(), Acts::PortalJsonConverter::fromJson(), fullMaterial(), g(), GaussLegendre_getWeight(), Matter::generate_vac_t(), Matter::generate_vac_t_w_M(), Matter::generate_vac_z(), Matter::generate_vac_z_w_M(), PHTimer::get_clock_counts(), RawTower_Temperature::get_temperature_from_time(), UpsilonPair::get_trk(), GetBeamMom(), KFParticleBase::GetDecayLength(), KFParticleBaseSIMD::GetDecayLength(), KFParticleBase::GetDecayLengthXY(), KFParticleBaseSIMD::GetDecayLengthXY(), GubserHydro::GetHydroInfo(), HydroFromFile::GetHydroInfo(), Hydroinfo_MUSIC::getHydroValues(), getinsudakov(), getnatmdmin(), getpnorad1(), getproba(), getqvec(), Fun4AllUtils::GetRunSegment(), getscatterer(), getsscat(), getsudakov(), gett(), A_Event::getTime(), gphoton(), std::tr1::GTEST_1_TUPLE_(), std::tr1::GTEST_2_TUPLE_(), std::tr1::GTEST_3_TUPLE_(), std::tr1::GTEST_4_TUPLE_(), std::tr1::GTEST_5_TUPLE_(), std::tr1::GTEST_6_TUPLE_(), std::tr1::GTEST_7_TUPLE_(), std::tr1::GTEST_8_TUPLE_(), std::tr1::GTEST_9_TUPLE_(), HodoscopeCheck(), PHG4CylinderGeom_Spacalv3::ImportParameters(), QAG4SimulationDistortions::Init(), CaloWaveformFitting::initialize_processing(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::intersect(), graph::is_acyclic(), KinematicsChecks(), layerMaterial(), likelihood(), likelihood_topology(), PHTruthClustering::line_circle_intersection(), SvtxTruthEval::line_circle_intersection(), LineShapeCompare(), LineShapeCompare_Electron(), LineShapeData(), LineShapeSim(), Jetscape::PartonShower::load_node_info_handler(), loadTree(), MachineLearning_CSV(), main(), make_GEM_station(), MakeFile(), makehist(), Fun4AllHistoManager::makeHisto(), Mat_map(), md5_process(), MD5_Update(), mg_http_send_file2(), mg_print_props(), Matter::Mgc2gc(), LBT::Mgc2gc(), testing::internal::move(), PHHepMCGenEvent::moveVertex(), Matter::Mqc2qc(), LBT::Mqc2qc(), MVTXStavePositionXY(), Acts::Logging::TimedOutputDecorator::now(), oamlBuffer::oamlBuffer(), Acts::TorchTruthGraphMetricsHook::operator()(), Acts::Sycl::detail::TripletSearch::operator()(), Fluid::outputGnuplot(), pathfinder::pathfinder(), Acts::TGeoSurfaceConverter::planeComponents(), genfit::RKTrackRep::pocaOnLine(), PositionDependenceData(), PositionDependenceSim(), PHG4Hitv1::print(), Prototype2_DSTReader::Process(), BbcCheck::process_emcal(), RecoInfoExport::process_event(), TpcCombinedRawDataUnpacker::process_event(), BJetModule::process_event(), DetermineTowerBackground::process_event(), TPCRawDataTree::process_event(), TpcRawDataTree::process_event(), PHG4MicromegasHitReco::process_event(), tpc_hits::process_event(), MicromegasRawDataEvaluation::process_event(), TpcRawDataDecoder::process_event(), TpcPrototypeUnpacker::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), PHGenFitTrkFitter::process_event(), BbcCheck::process_ihcal(), BbcCheck::process_ohcal(), TpcDirectLaserReconstruction::process_track(), Acts::Legacy::AtlasSeedFinder< SpacePoint >::production3Sp(), ActsExamples::prototrackToSeed(), tinyxml2::DynArray< char, 20 >::Push(), pygfxx(), pyhistfu(), pypdga(), pypdpo(), pypole(), pyprep(), pyr(), pyreco(), pysubh(), pythag(), quarkonia_reconstruction_embedded(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryInt64Text(), tinyxml2::XMLElement::QueryIntText(), tinyxml2::XMLElement::QueryUnsignedText(), HybridHadronization::recomb(), reconstructionPerformance(), RejectionCompare(), UpsilonPair::Reset(), vector2D< T >::resize(), vector3D< T >::resize(), Jetscape::CausalLiquefier::rho_delta(), rings_do_eta_fit2_emc(), rings_do_eta_fit2_ihcal(), rings_do_eta_fit2_ohcal(), rlu(), planarity::run(), st_number::run(), Jetscape::PartonShower::SaveAsGV(), sHelix::SaveTracktoRootScript(), scatprimfunc(), Acts::TGeoParser::select(), MbdVertexv1::set_t(), MbdVertexv2::set_t(), BbcVertexv1::set_t(), BbcVertexv2::set_t(), GlobalVertexv1::set_t(), PHG4ParticleGeneratorBase::set_t0(), PHG4CylinderGeomv1::set_thickness(), PHG4CylinderCellGeom::set_thickness(), PHG4TpcCylinderGeom::set_thickness(), RawTowerGeomContainer_Cylinderv1::set_thickness(), TowerInfov1::set_time(), RawTowerv1::set_time(), RawTower_Prototype2::set_time(), RawTower_Prototype4::set_time(), RawTower_Prototype3::set_time(), CaloAna::set_timing_cut_width(), CaloValid::set_timing_cut_width(), pi0EtaByEta::set_timing_cut_width(), BbcPmtInfoV1::set_tq(), BbcPmtInfoV1::set_tt(), PHHepMCGenHelper::set_vertex_distribution_function(), PHHepMCGenHelper::set_vertex_distribution_mean(), PHHepMCGenHelper::set_vertex_distribution_width(), PHTimeStamp::setBinTics(), CaloCalibration::SetFitType(), CaloTemplateFit::SetFitType(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::CstInfo::SetInfo(), PHG4TpcPadPlaneReadout::SetReadoutTime(), SimPositionCheck(), Jetscape::CausalLiquefier::smearing_kernel(), genfit::DetPlane::straightLineToPlane(), strdup(), strf(), HybridHadronization::stringprep(), subcrs1(), subcrs2(), subcrs3(), subcrs4(), subcrs5(), subcrs6(), subcrs7(), supst(), TEST(), testing::gmock_more_actions_test::TEST(), TEST_CASE(), Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testAddTrackStateWithBitMask(), Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testApplyWithAbort(), Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testBuild(), Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testClear(), Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testProxyAssignment(), Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testTrackStateProxyAllocations(), Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testTrackStateProxyStorage(), Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testTrackStateReassignment(), Acts::detail_vmt::VectorMultiTrajectoryBase::Statistics::toStream(), TrackCaloDist(), TrackerRate(), TSQLResultSet::Tree(), Jetscape::TrilinearInt(), TSQLDate::TSQLDate(), TSQLTime::TSQLTime(), TSQLTimestamp::TSQLTimestamp(), VertexChecks(), sHelix::w(), while(), ActsExamples::RootMaterialWriter::writeMaterial(), writeTimeOrderedDistortions(), HybridHadronization::HHparton::x(), HybridHadronization::HHhadron::x(), simpleRandom::xMD5Update(), HybridHadronization::HHparton::y(), HybridHadronization::HHhadron::y(), HybridHadronization::HHparton::z(), and HybridHadronization::HHhadron::z().
TrackContainer tc {vtc, mtj}
Definition at line 72 of file TrackContainerComplianceTests.cpp.
View newest version in sPHENIX GitHub at line 72 of file TrackContainerComplianceTests.cpp
Referenced by RecoConversionEval::approachDistance(), Conversion::approachDistance(), BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE_TEMPLATE(), calcta(), calcxsection(), DISKinematicsReco::CollectEmCandidatesFromTruth(), draw_corr(), draw_G4_bjet_truth_tagging(), draw_G4_dibjet_truth_tagging(), oncsSub_idfnalmwpc::dump(), oncsSub_idfnalmwpcv2::dump(), getltimemax(), getmdmin(), getnatmdmin(), getneff(), getneffmax(), getscatterer(), gettemp(), gettempmax(), DISKinematicsReco::InsertCandidateFromCluster(), medderiv(), medinit(), mednextevt(), npart(), nthick(), LeptoquarksReco::process_event(), pyreco(), ActsExamples::RootAthenaNTupleReader::read(), and readJetTree().