Analysis Software: ActsExamples::PrintHits Class Reference
ActsExamples::PrintHits Class Reference
Print hits within some geometric region-of-interest.
#include <acts/blob/sPHENIX/Examples/Algorithms/Printers/ActsExamples/Printers/PrintHits.hpp>
Classes
struct Config
Public Member Functions
PrintHits (const Config &cfg, Acts::Logging::Level level)
ProcessCode execute (const AlgorithmContext &ctx) const
Public Member Functions inherited from ActsExamples::BareAlgorithm
BareAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const finaloverride
The algorithm name.
Private Attributes
Config m_cfg
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::BareAlgorithm
const Acts::Logger & logger () const
Detailed Description
Print hits within some geometric region-of-interest.
Definition at line 19 of file PrintHits.hpp.
View newest version in sPHENIX GitHub at line 19 of file PrintHits.hpp
Constructor & Destructor Documentation
ActsExamples::PrintHits::PrintHits (const Config & cfg, Acts::Logging::Level level)
Definition at line 21 of file PrintHits.cpp.
View newest version in sPHENIX GitHub at line 21 of file PrintHits.cpp
Member Function Documentation
ActsExamples::ProcessCode ActsExamples::PrintHits::execute (const AlgorithmContext & context) const virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Implements ActsExamples::BareAlgorithm.
Definition at line 25 of file PrintHits.cpp.
View newest version in sPHENIX GitHub at line 25 of file PrintHits.cpp
References ACTS_INFO, c, Acts::PlanarModuleCluster::digitizationCells(), ActsExamples::AlgorithmContext::eventStore, ActsExamples::WhiteBoard::get(), ActsExamples::makeRange(), p, ActsExamples::selectLayer(), ActsExamples::selectModule(), ActsExamples::selectVolume(), and SUCCESS.
Member Data Documentation
Config ActsExamples::PrintHits::m_cfg private
Definition at line 43 of file PrintHits.hpp.
View newest version in sPHENIX GitHub at line 43 of file PrintHits.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Printers/ActsExamples/Printers/PrintHits.hpp
acts/blob/sPHENIX/Examples/Algorithms/Printers/ActsExamples/Printers/PrintHits.cpp