Analysis Software: CaloWaveformProcessing Class Reference
CaloWaveformProcessing Class Reference
#include <coresoftware/blob/master/offline/packages/CaloReco/CaloWaveformProcessing.h>
Public Types
enum process { NONE = 0, TEMPLATE = 1, ONNX = 2, FAST = 3 }
Public Member Functions
CaloWaveformProcessing ()=default
~CaloWaveformProcessing () override
void set_processing_type (CaloWaveformProcessing::process modelno)
CaloWaveformProcessing::process get_processing_type ()
void set_template_file (const std::string &template_input_file)
void set_template_name (const std::string &template_name)
void set_model_file (const std::string &model_name)
void set_nthreads (int nthreads)
int get_nthreads ()
void set_softwarezerosuppression (bool usezerosuppression, int softwarezerosuppression)
std::vector< std::vector< float > > process_waveform (std::vector< std::vector< float >> waveformvector)
std::vector< std::vector< float > > calo_processing_ONNX (std::vector< std::vector< float >> chnlvector)
void initialize_processing ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int InitRun (PHCompositeNode *)
virtual int process_event (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
CaloWaveformFitting * m_Fitter = nullptr
CaloWaveformProcessing::process m_processingtype = CaloWaveformProcessing::TEMPLATE
int _nthreads = 1
int _nsoftwarezerosuppression = 40
bool _bdosoftwarezerosuppression = false
std::string m_template_input_file
std::string url_template
std::string m_template_name = "NONE"
std::string url_onnx
std::string m_model_name = "CEMC_ONNX"
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 11 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 11 of file CaloWaveformProcessing.h
Member Enumeration Documentation
enum CaloWaveformProcessing::process
Enumerator:
NONE
TEMPLATE
ONNX
FAST
Definition at line 14 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 14 of file CaloWaveformProcessing.h
Constructor & Destructor Documentation
CaloWaveformProcessing::CaloWaveformProcessing () default
CaloWaveformProcessing::~CaloWaveformProcessing () override
Definition at line 17 of file CaloWaveformProcessing.cc.
View newest version in sPHENIX GitHub at line 17 of file CaloWaveformProcessing.cc
References m_Fitter.
Member Function Documentation
std::vector< std::vector< float > > CaloWaveformProcessing::calo_processing_ONNX (std::vector< std::vector< float >> chnlvector)
Definition at line 70 of file CaloWaveformProcessing.cc.
View newest version in sPHENIX GitHub at line 70 of file CaloWaveformProcessing.cc
References i, k, Acts::UnitConstants::m, nsamples, onnxInference(), onnxmodule, and testSigmaEff::v.
Referenced by process_waveform().
int CaloWaveformProcessing::get_nthreads ()
Definition at line 99 of file CaloWaveformProcessing.cc.
View newest version in sPHENIX GitHub at line 99 of file CaloWaveformProcessing.cc
References _nthreads, CaloWaveformFitting::get_nthreads(), and m_Fitter.
Referenced by initialize_processing().
CaloWaveformProcessing::process CaloWaveformProcessing::get_processing_type () inline
Definition at line 31 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 31 of file CaloWaveformProcessing.h
References m_processingtype.
void CaloWaveformProcessing::initialize_processing ()
Definition at line 22 of file CaloWaveformProcessing.cc.
View newest version in sPHENIX GitHub at line 22 of file CaloWaveformProcessing.cc
References _bdosoftwarezerosuppression, _nsoftwarezerosuppression, assert, get_nthreads(), CDBInterface::getUrl(), CaloWaveformFitting::initialize_processing(), CDBInterface::instance(), m_Fitter, m_model_name, m_processingtype, m_template_input_file, m_template_name, ONNX, onnxmodule, onnxSession(), CaloWaveformFitting::set_nthreads(), CaloWaveformFitting::set_softwarezerosuppression(), TEMPLATE, url_onnx, and url_template.
Referenced by CaloWaveFormSim::Init(), CaloTowerBuilder::InitRun(), and LEDTowerBuilder::InitRun().
std::vector< std::vector< float > > CaloWaveformProcessing::process_waveform (std::vector< std::vector< float >> waveformvector)
Definition at line 47 of file CaloWaveformProcessing.cc.
View newest version in sPHENIX GitHub at line 47 of file CaloWaveformProcessing.cc
References CaloWaveformFitting::calo_processing_fast(), calo_processing_ONNX(), CaloWaveformFitting::calo_processing_templatefit(), FAST, i, m_Fitter, m_processingtype, ONNX, and TEMPLATE.
Referenced by CaloTowerBuilder::process_event(), LEDTowerBuilder::process_event(), CaloWaveFormSim::process_g4hits(), and CaloTowerBuilder::process_sim().
void CaloWaveformProcessing::set_model_file (const std::string & model_name) inline
Definition at line 47 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 47 of file CaloWaveformProcessing.h
References m_model_name.
void CaloWaveformProcessing::set_nthreads (int nthreads)
Definition at line 107 of file CaloWaveformProcessing.cc.
View newest version in sPHENIX GitHub at line 107 of file CaloWaveformProcessing.cc
References _nthreads, m_Fitter, and CaloWaveformFitting::set_nthreads().
void CaloWaveformProcessing::set_processing_type (CaloWaveformProcessing::process modelno) inline
Definition at line 25 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 25 of file CaloWaveformProcessing.h
References m_processingtype.
Referenced by CaloWaveFormSim::Init(), CaloTowerBuilder::InitRun(), and LEDTowerBuilder::InitRun().
void CaloWaveformProcessing::set_softwarezerosuppression (bool usezerosuppression, int softwarezerosuppression) inline
Definition at line 57 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 57 of file CaloWaveformProcessing.h
References _bdosoftwarezerosuppression, and _nsoftwarezerosuppression.
Referenced by CaloTowerBuilder::InitRun().
void CaloWaveformProcessing::set_template_file (const std::string & template_input_file) inline
Definition at line 36 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 36 of file CaloWaveformProcessing.h
References m_template_input_file.
Referenced by CaloWaveFormSim::Init(), and LEDTowerBuilder::InitRun().
void CaloWaveformProcessing::set_template_name (const std::string & template_name) inline
Definition at line 42 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 42 of file CaloWaveformProcessing.h
References m_template_name.
Referenced by CaloTowerBuilder::InitRun().
Member Data Documentation
bool CaloWaveformProcessing::_bdosoftwarezerosuppression = false private
Definition at line 75 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 75 of file CaloWaveformProcessing.h
Referenced by initialize_processing(), and set_softwarezerosuppression().
int CaloWaveformProcessing::_nsoftwarezerosuppression = 40 private
Definition at line 74 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 74 of file CaloWaveformProcessing.h
Referenced by initialize_processing(), and set_softwarezerosuppression().
int CaloWaveformProcessing::_nthreads = 1 private
Definition at line 73 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 73 of file CaloWaveformProcessing.h
Referenced by get_nthreads(), and set_nthreads().
CaloWaveformFitting* CaloWaveformProcessing::m_Fitter = nullptr private
Definition at line 70 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 70 of file CaloWaveformProcessing.h
Referenced by get_nthreads(), initialize_processing(), process_waveform(), set_nthreads(), and ~CaloWaveformProcessing().
std::string CaloWaveformProcessing::m_model_name = "CEMC_ONNX" private
Definition at line 82 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 82 of file CaloWaveformProcessing.h
Referenced by initialize_processing(), and set_model_file().
CaloWaveformProcessing::process CaloWaveformProcessing::m_processingtype = CaloWaveformProcessing::TEMPLATE private
Definition at line 72 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 72 of file CaloWaveformProcessing.h
Referenced by get_processing_type(), initialize_processing(), process_waveform(), and set_processing_type().
std::string CaloWaveformProcessing::m_template_input_file private
Definition at line 77 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 77 of file CaloWaveformProcessing.h
Referenced by initialize_processing(), and set_template_file().
std::string CaloWaveformProcessing::m_template_name = "NONE" private
Definition at line 79 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 79 of file CaloWaveformProcessing.h
Referenced by initialize_processing(), and set_template_name().
std::string CaloWaveformProcessing::url_onnx private
Definition at line 81 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 81 of file CaloWaveformProcessing.h
Referenced by initialize_processing().
std::string CaloWaveformProcessing::url_template private
Definition at line 78 of file CaloWaveformProcessing.h.
View newest version in sPHENIX GitHub at line 78 of file CaloWaveformProcessing.h
Referenced by initialize_processing().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/CaloWaveformProcessing.h
coresoftware/blob/master/offline/packages/CaloReco/CaloWaveformProcessing.cc