Analysis Software: testing::internal::FilePath Class Reference
testing::internal::FilePath Class Reference
#include <JETSCAPE/blob/main/external_packages/googletest/googletest/include/gtest/internal/gtest-filepath.h>
Public Member Functions
FilePath ()
FilePath (const FilePath &rhs)
FilePath (const std::string &pathname)
FilePath & operator= (const FilePath &rhs)
void Set (const FilePath &rhs)
const std::string & string () const
const char * c_str () const
bool IsEmpty () const
FilePath RemoveTrailingPathSeparator () const
FilePath RemoveDirectoryName () const
FilePath RemoveFileName () const
FilePath RemoveExtension (const char *extension) const
bool CreateDirectoriesRecursively () const
bool CreateFolder () const
bool FileOrDirectoryExists () const
bool DirectoryExists () const
bool IsDirectory () const
bool IsRootDirectory () const
bool IsAbsolutePath () const
Static Public Member Functions
static FilePath GetCurrentDir ()
static FilePath MakeFileName (const FilePath &directory, const FilePath &base_name, int number, const char *extension)
static FilePath ConcatPaths (const FilePath &directory, const FilePath &relative_path)
static FilePath GenerateUniqueFileName (const FilePath &directory, const FilePath &base_name, const char *extension)
Private Member Functions
void Normalize ()
const char * FindLastPathSeparator () const
Private Attributes
std::string pathname_
Detailed Description
Definition at line 59 of file gtest-filepath.h.
View newest version in sPHENIX GitHub at line 59 of file gtest-filepath.h
Constructor & Destructor Documentation
testing::internal::FilePath::FilePath () inline
Definition at line 61 of file gtest-filepath.h.
View newest version in sPHENIX GitHub at line 61 of file gtest-filepath.h
Referenced by ConcatPaths(), GetCurrentDir(), MakeFileName(), RemoveDirectoryName(), RemoveExtension(), RemoveFileName(), and RemoveTrailingPathSeparator().
testing::internal::FilePath::FilePath (const FilePath & rhs) inline
Definition at line 62 of file gtest-filepath.h.
View newest version in sPHENIX GitHub at line 62 of file gtest-filepath.h
testing::internal::FilePath::FilePath (const std::string & pathname) inline explicit
Definition at line 64 of file gtest-filepath.h.
View newest version in sPHENIX GitHub at line 64 of file gtest-filepath.h
Member Function Documentation
const char* testing::internal::FilePath::c_str (void) const inline
Definition at line 78 of file gtest-filepath.h.
View newest version in sPHENIX GitHub at line 78 of file gtest-filepath.h
Referenced by CreateFolder(), DirectoryExists(), FindLastPathSeparator(), testing::UnitTest::original_working_dir(), and RemoveFileName().
FilePath testing::internal::FilePath::ConcatPaths (const FilePath & directory, const FilePath & relative_path) static
Definition at line 199 of file gtest-filepath.cc.
View newest version in sPHENIX GitHub at line 199 of file gtest-filepath.cc
References FilePath(), IsEmpty(), testing::internal::kPathSeparator, RemoveTrailingPathSeparator(), and string().
Referenced by testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), and MakeFileName().
bool testing::internal::FilePath::CreateDirectoriesRecursively () const
Definition at line 308 of file gtest-filepath.cc.
View newest version in sPHENIX GitHub at line 308 of file gtest-filepath.cc
References CreateDirectoriesRecursively(), CreateFolder(), DirectoryExists(), IsDirectory(), pathname_, RemoveFileName(), and RemoveTrailingPathSeparator().
Referenced by CreateDirectoriesRecursively().
bool testing::internal::FilePath::CreateFolder () const
Definition at line 325 of file gtest-filepath.cc.
View newest version in sPHENIX GitHub at line 325 of file gtest-filepath.cc
References c_str(), DirectoryExists(), pathname_, and RemoveTrailingPathSeparator().
Referenced by CreateDirectoriesRecursively().
bool testing::internal::FilePath::DirectoryExists () const
Definition at line 223 of file gtest-filepath.cc.
View newest version in sPHENIX GitHub at line 223 of file gtest-filepath.cc
References c_str(), testing::internal::posix::IsDir(), IsRootDirectory(), path, RemoveTrailingPathSeparator(), and testing::internal::posix::Stat().
Referenced by CreateDirectoriesRecursively(), and CreateFolder().
bool testing::internal::FilePath::FileOrDirectoryExists () const
Definition at line 209 of file gtest-filepath.cc.
View newest version in sPHENIX GitHub at line 209 of file gtest-filepath.cc
References pathname_, and testing::internal::posix::Stat().
Referenced by GenerateUniqueFileName().
const char * testing::internal::FilePath::FindLastPathSeparator () const private
Definition at line 136 of file gtest-filepath.cc.
View newest version in sPHENIX GitHub at line 136 of file gtest-filepath.cc
References c_str(), and testing::internal::kPathSeparator.
Referenced by RemoveDirectoryName(), and RemoveFileName().
FilePath testing::internal::FilePath::GenerateUniqueFileName (const FilePath & directory, const FilePath & base_name, const char * extension) static
Definition at line 286 of file gtest-filepath.cc.
View newest version in sPHENIX GitHub at line 286 of file gtest-filepath.cc
References FileOrDirectoryExists(), MakeFileName(), and Set().
Referenced by testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile().
FilePath testing::internal::FilePath::GetCurrentDir () static
Definition at line 99 of file gtest-filepath.cc.
View newest version in sPHENIX GitHub at line 99 of file gtest-filepath.cc
References conf::cwd, FilePath(), GTEST_PATH_MAX_, and testing::internal::kCurrentDirectoryString.
Referenced by testing::internal::UnitTestImpl::AddTestInfo().
bool testing::internal::FilePath::IsAbsolutePath () const
Definition at line 265 of file gtest-filepath.cc.
View newest version in sPHENIX GitHub at line 265 of file gtest-filepath.cc
References testing::internal::IsPathSeparator(), perf_headwind::name, and pathname_.
Referenced by testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), and IsRootDirectory().
bool testing::internal::FilePath::IsDirectory () const
Definition at line 300 of file gtest-filepath.cc.
View newest version in sPHENIX GitHub at line 300 of file gtest-filepath.cc
References testing::internal::IsPathSeparator(), and pathname_.
Referenced by CreateDirectoriesRecursively(), testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), and RemoveTrailingPathSeparator().
bool testing::internal::FilePath::IsEmpty () const inline
Definition at line 111 of file gtest-filepath.h.
View newest version in sPHENIX GitHub at line 111 of file gtest-filepath.h
Referenced by ConcatPaths().
bool testing::internal::FilePath::IsRootDirectory () const
Definition at line 253 of file gtest-filepath.cc.
View newest version in sPHENIX GitHub at line 253 of file gtest-filepath.cc
References IsAbsolutePath(), testing::internal::IsPathSeparator(), and pathname_.
Referenced by DirectoryExists().
FilePath testing::internal::FilePath::MakeFileName (const FilePath & directory, const FilePath & base_name, int number, const char * extension) static
Definition at line 183 of file gtest-filepath.cc.
View newest version in sPHENIX GitHub at line 183 of file gtest-filepath.cc
References ConcatPaths(), extension, file, FilePath(), testing::internal::StreamableToString(), and string().
Referenced by GenerateUniqueFileName().
void testing::internal::FilePath::Normalize () private
Definition at line 356 of file gtest-filepath.cc.
View newest version in sPHENIX GitHub at line 356 of file gtest-filepath.cc
References upload::dest, testing::internal::IsPathSeparator(), testing::internal::kPathSeparator, and pathname_.
FilePath& testing::internal::FilePath::operator= (const FilePath & rhs) inline
Definition at line 68 of file gtest-filepath.h.
View newest version in sPHENIX GitHub at line 68 of file gtest-filepath.h
References Set().
FilePath testing::internal::FilePath::RemoveDirectoryName () const
Definition at line 155 of file gtest-filepath.cc.
View newest version in sPHENIX GitHub at line 155 of file gtest-filepath.cc
References FilePath(), and FindLastPathSeparator().
Referenced by testing::internal::GetCurrentExecutableName().
FilePath testing::internal::FilePath::RemoveExtension (const char * extension) const
Definition at line 124 of file gtest-filepath.cc.
View newest version in sPHENIX GitHub at line 124 of file gtest-filepath.cc
References testing::internal::String::EndsWithCaseInsensitive(), extension, FilePath(), and pathname_.
FilePath testing::internal::FilePath::RemoveFileName () const
Definition at line 166 of file gtest-filepath.cc.
View newest version in sPHENIX GitHub at line 166 of file gtest-filepath.cc
References c_str(), FilePath(), FindLastPathSeparator(), and testing::internal::kCurrentDirectoryString.
Referenced by CreateDirectoriesRecursively(), and testing::internal::XmlUnitTestResultPrinter::OnTestIterationEnd().
FilePath testing::internal::FilePath::RemoveTrailingPathSeparator () const
Definition at line 346 of file gtest-filepath.cc.
View newest version in sPHENIX GitHub at line 346 of file gtest-filepath.cc
References FilePath(), IsDirectory(), and pathname_.
Referenced by ConcatPaths(), CreateDirectoriesRecursively(), CreateFolder(), and DirectoryExists().
void testing::internal::FilePath::Set (const FilePath & rhs) inline
Definition at line 73 of file gtest-filepath.h.
View newest version in sPHENIX GitHub at line 73 of file gtest-filepath.h
References pathname_.
Referenced by GenerateUniqueFileName(), and testing::internal::GetCurrentExecutableName().
const std::string& testing::internal::FilePath::string (void) const inline
Definition at line 77 of file gtest-filepath.h.
View newest version in sPHENIX GitHub at line 77 of file gtest-filepath.h
Referenced by ConcatPaths(), testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), and MakeFileName().
Member Data Documentation
std::string testing::internal::FilePath::pathname_ private
Definition at line 200 of file gtest-filepath.h.
View newest version in sPHENIX GitHub at line 200 of file gtest-filepath.h
Referenced by CreateDirectoriesRecursively(), CreateFolder(), FileOrDirectoryExists(), IsAbsolutePath(), IsDirectory(), IsRootDirectory(), Normalize(), RemoveExtension(), RemoveTrailingPathSeparator(), and Set().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/googletest/googletest/include/gtest/internal/gtest-filepath.h
JETSCAPE/blob/main/external_packages/googletest/googletest/src/gtest-filepath.cc