Analysis Software: JetSeedCount Class Reference
JetSeedCount Class Reference
#include <analysis/blob/master/JS-Jet/JetSeedCount/src/JetSeedCount.h>
Public Member Functions
JetSeedCount (const std::string &recojetname="AntiKt_Tower_r04", const std::string &truthjetname="AntiKt_Truth_r04", const std::string &outputfilename="myjetanalysis.root")
~JetSeedCount () override
void setEtaRange (double low, double high)
void setPtRange (double low, double high)
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int ResetEvent (PHCompositeNode *topNode) override
Clean up internals after each event.
int EndRun (const int runnumber) override
Called at the end of each run.
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
int Reset (PHCompositeNode *) override
Reset.
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from SubsysReco
~SubsysReco () override
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
std::string m_recoJetName
std::string m_truthJetName
std::string m_outputFileName
std::pair< double, double > m_etaRange
std::pair< double, double > m_ptRange
std::vector< int > m_centrality
std::vector< int > m_centrality_diff
int m_event = 0
int m_seed_sub
int m_seed_raw
std::vector< int > m_raw_counts
std::vector< int > m_sub_counts
std::vector< double > m_rawenergy
std::vector< double > m_subenergy
std::vector< double > m_rawcent
std::vector< double > m_subcent
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 14 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 14 of file JetSeedCount.h
Constructor & Destructor Documentation
JetSeedCount::JetSeedCount (const std::string & recojetname = "AntiKt_Tower_r04", const std::string & truthjetname = "AntiKt_Truth_r04", const std::string & outputfilename = "myjetanalysis.root")
Definition at line 28 of file JetSeedCount.cc.
View newest version in sPHENIX GitHub at line 28 of file JetSeedCount.cc
JetSeedCount::~JetSeedCount () override
Definition at line 39 of file JetSeedCount.cc.
View newest version in sPHENIX GitHub at line 39 of file JetSeedCount.cc
Member Function Documentation
int JetSeedCount::End (PHCompositeNode * topNode) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 166 of file JetSeedCount.cc.
View newest version in sPHENIX GitHub at line 166 of file JetSeedCount.cc
References PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), j, m_centrality, m_outputFileName, m_raw_counts, m_rawcent, m_rawenergy, m_sub_counts, m_subcent, and m_subenergy.
int JetSeedCount::EndRun (const int runnumber) override virtual
Called at the end of each run.
Reimplemented from SubsysReco.
Definition at line 159 of file JetSeedCount.cc.
View newest version in sPHENIX GitHub at line 159 of file JetSeedCount.cc
References Fun4AllReturnCodes::EVENT_OK.
int JetSeedCount::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 45 of file JetSeedCount.cc.
View newest version in sPHENIX GitHub at line 45 of file JetSeedCount.cc
References Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), m_outputFileName, and PHTFileServer::open().
int JetSeedCount::InitRun (PHCompositeNode * topNode) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.
Reimplemented from SubsysReco.
Definition at line 55 of file JetSeedCount.cc.
View newest version in sPHENIX GitHub at line 55 of file JetSeedCount.cc
References Fun4AllReturnCodes::EVENT_OK.
void JetSeedCount::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 263 of file JetSeedCount.cc.
View newest version in sPHENIX GitHub at line 263 of file JetSeedCount.cc
int JetSeedCount::process_event (PHCompositeNode * topNode) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 62 of file JetSeedCount.cc.
View newest version in sPHENIX GitHub at line 62 of file JetSeedCount.cc
References JetMap::begin(), JetMap::end(), Fun4AllReturnCodes::EVENT_OK, CentralityInfo::get_centile(), Jet::get_e(), Jet::get_property(), m_centrality, m_event, m_raw_counts, m_rawcent, m_rawenergy, m_seed_raw, m_seed_sub, m_sub_counts, m_subcent, and m_subenergy.
int JetSeedCount::Reset (PHCompositeNode * topNode) override virtual
Reset.
Reimplemented from SubsysReco.
Definition at line 256 of file JetSeedCount.cc.
View newest version in sPHENIX GitHub at line 256 of file JetSeedCount.cc
References Fun4AllReturnCodes::EVENT_OK.
int JetSeedCount::ResetEvent (PHCompositeNode * topNode) override virtual
Clean up internals after each event.
Reimplemented from SubsysReco.
Definition at line 152 of file JetSeedCount.cc.
View newest version in sPHENIX GitHub at line 152 of file JetSeedCount.cc
References Fun4AllReturnCodes::EVENT_OK.
void JetSeedCount::setEtaRange (double low, double high) inline
Definition at line 25 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 25 of file JetSeedCount.h
References m_etaRange.
Referenced by Fun4All_JetSeedCount().
void JetSeedCount::setPtRange (double low, double high) inline
Definition at line 31 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 31 of file JetSeedCount.h
References m_ptRange.
Referenced by Fun4All_JetSeedCount().
Member Data Documentation
std::vector<int> JetSeedCount::m_centrality private
Definition at line 71 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 71 of file JetSeedCount.h
Referenced by End(), and process_event().
std::vector<int> JetSeedCount::m_centrality_diff private
Definition at line 72 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 72 of file JetSeedCount.h
std::pair<double, double> JetSeedCount::m_etaRange private
Definition at line 69 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 69 of file JetSeedCount.h
Referenced by setEtaRange().
int JetSeedCount::m_event = 0 private
Definition at line 74 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 74 of file JetSeedCount.h
Referenced by process_event().
std::string JetSeedCount::m_outputFileName private
Definition at line 68 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 68 of file JetSeedCount.h
Referenced by End(), and Init().
std::pair<double, double> JetSeedCount::m_ptRange private
Definition at line 70 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 70 of file JetSeedCount.h
Referenced by setPtRange().
std::vector<int> JetSeedCount::m_raw_counts private
Definition at line 77 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 77 of file JetSeedCount.h
Referenced by End(), and process_event().
std::vector<double> JetSeedCount::m_rawcent private
Definition at line 81 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 81 of file JetSeedCount.h
Referenced by End(), and process_event().
std::vector<double> JetSeedCount::m_rawenergy private
Definition at line 79 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 79 of file JetSeedCount.h
Referenced by End(), and process_event().
std::string JetSeedCount::m_recoJetName private
Definition at line 66 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 66 of file JetSeedCount.h
int JetSeedCount::m_seed_raw private
Definition at line 76 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 76 of file JetSeedCount.h
Referenced by process_event().
int JetSeedCount::m_seed_sub private
Definition at line 75 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 75 of file JetSeedCount.h
Referenced by process_event().
std::vector<int> JetSeedCount::m_sub_counts private
Definition at line 78 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 78 of file JetSeedCount.h
Referenced by End(), and process_event().
std::vector<double> JetSeedCount::m_subcent private
Definition at line 82 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 82 of file JetSeedCount.h
Referenced by End(), and process_event().
std::vector<double> JetSeedCount::m_subenergy private
Definition at line 80 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 80 of file JetSeedCount.h
Referenced by End(), and process_event().
std::string JetSeedCount::m_truthJetName private
Definition at line 67 of file JetSeedCount.h.
View newest version in sPHENIX GitHub at line 67 of file JetSeedCount.h
The documentation for this class was generated from the following files:
analysis/blob/master/JS-Jet/JetSeedCount/src/JetSeedCount.h
analysis/blob/master/JS-Jet/JetSeedCount/src/JetSeedCount.cc