Analysis Software: Acts::detail::GlobalNeighborHoodIndices< DIM > Class Template Reference
Acts::detail::GlobalNeighborHoodIndices< DIM > Class Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Utilities/detail/grid_helper.hpp>
Classes
class iterator
Public Member Functions
GlobalNeighborHoodIndices (std::array< NeighborHoodIndices, DIM > &neighborIndices, const std::array< size_t, DIM > &nBinsArray)
iterator begin () const
iterator end () const
size_t size () const
auto collect () const
std::vector< size_t > collectVector () const
Private Attributes
std::array
< NeighborHoodIndices, DIM > m_localIndices {}
std::array< size_t, DIM-1 > m_globalStrides {}
Detailed Description
template<size_t DIM>
class Acts::detail::GlobalNeighborHoodIndices< DIM >
Definition at line 42 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 42 of file grid_helper.hpp
Constructor & Destructor Documentation
template<size_t DIM> Acts::detail::GlobalNeighborHoodIndices< DIM >::GlobalNeighborHoodIndices (std::array< NeighborHoodIndices, DIM > & neighborIndices, const std::array< size_t, DIM > & nBinsArray) inline
Definition at line 47 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 47 of file grid_helper.hpp
References i, and Acts::detail::GlobalNeighborHoodIndices< DIM >::m_globalStrides.
Member Function Documentation
template<size_t DIM> iterator Acts::detail::GlobalNeighborHoodIndices< DIM >::begin () const inline
Definition at line 119 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 119 of file grid_helper.hpp
References i, Acts::detail::GlobalNeighborHoodIndices< DIM >::m_localIndices, and testing::internal::move().
template<size_t DIM> auto Acts::detail::GlobalNeighborHoodIndices< DIM >::collect () const inline
Definition at line 139 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 139 of file grid_helper.hpp
References ambiguity_solver_full_chain::idx, and Acts::detail::GlobalNeighborHoodIndices< DIM >::size().
Referenced by Acts::detail::GlobalNeighborHoodIndices< DIM >::collectVector().
template<size_t DIM> std::vector<size_t> Acts::detail::GlobalNeighborHoodIndices< DIM >::collectVector () const inline
Definition at line 148 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 148 of file grid_helper.hpp
References Acts::detail::GlobalNeighborHoodIndices< DIM >::collect().
template<size_t DIM> iterator Acts::detail::GlobalNeighborHoodIndices< DIM >::end () const inline
Definition at line 127 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 127 of file grid_helper.hpp
Referenced by Acts::detail::GlobalNeighborHoodIndices< DIM >::iterator::operator++().
template<size_t DIM> size_t Acts::detail::GlobalNeighborHoodIndices< DIM >::size () const inline
Definition at line 130 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 130 of file grid_helper.hpp
References i, and Acts::detail::GlobalNeighborHoodIndices< DIM >::m_localIndices.
Referenced by Acts::detail::GlobalNeighborHoodIndices< DIM >::collect().
Member Data Documentation
template<size_t DIM> std::array<size_t, DIM - 1> Acts::detail::GlobalNeighborHoodIndices< DIM >::m_globalStrides {} private
Definition at line 155 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 155 of file grid_helper.hpp
Referenced by Acts::detail::GlobalNeighborHoodIndices< DIM >::GlobalNeighborHoodIndices(), and Acts::detail::GlobalNeighborHoodIndices< DIM >::iterator::operator*().
template<size_t DIM> std::array<NeighborHoodIndices, DIM> Acts::detail::GlobalNeighborHoodIndices< DIM >::m_localIndices {} private
Definition at line 154 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 154 of file grid_helper.hpp
Referenced by Acts::detail::GlobalNeighborHoodIndices< DIM >::begin(), Acts::detail::GlobalNeighborHoodIndices< DIM >::iterator::isEqual(), Acts::detail::GlobalNeighborHoodIndices< DIM >::iterator::operator++(), and Acts::detail::GlobalNeighborHoodIndices< DIM >::size().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Utilities/detail/grid_helper.hpp