Analysis Software: ActsExamples::CsvPlanarClusterReader Exception Reference
ActsExamples::CsvPlanarClusterReader Exception Reference final
#include <acts/blob/sPHENIX/Examples/Io/Csv/include/ActsExamples/Io/Csv/CsvPlanarClusterReader.hpp>
Classes
struct Config
Public Member Functions
CsvPlanarClusterReader (const Config &config, Acts::Logging::Level level)
std::string name () const override
The algorithm name.
std::pair< size_t, size_t > availableEvents () const override
Return the available events range.
ProcessCode read (const ActsExamples::AlgorithmContext &ctx) override
Read out data from the input stream.
const Config & config () const
Readonly access to the config.
Public Member Functions inherited from ActsExamples::IReader
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Fulfill the algorithm interface.
ProcessCode finalize () override
Fulfill the algorithm interface.
Public Member Functions inherited from ActsExamples::SequenceElement
virtual ~SequenceElement ()=default
const std::vector< const
DataHandleBase * > & writeHandles () const
const std::vector< const
DataHandleBase * > & readHandles () const
Private Member Functions
const Acts::Logger & logger () const
Private Attributes
Config m_cfg
std::pair< size_t, size_t > m_eventsRange
std::unique_ptr< const
Acts::Logger > m_logger
WriteDataHandle
< GeometryIdMultimap
< Acts::PlanarModuleCluster > > m_outputClusters {this, "OutputClusters"}
WriteDataHandle< IndexMultimap
< ActsFatras::Barcode > > m_outputMeasurementParticlesMap {this, "OutputMeasurementParticlesMap"}
WriteDataHandle< SimHitContainer > m_outputSimHits {this, "OutputSimHits"}
WriteDataHandle< std::vector
< uint64_t > > m_outputHitIds {this, "OutputHitIds"}
Detailed Description
Read in a planar cluster collection in comma-separated-value format.
This reads three files per event file in the configured input directory. By default it reads file in the current working directory. Files are assumed to be named using the following schema
event000000001-cells.csv
event000000001-hits.csv
event000000001-truth.csv
event000000002-cells.csv
event000000002-hits.csv
event000000002-truth.csv
and each line in the file corresponds to one hit/cluster.
Definition at line 56 of file CsvPlanarClusterReader.hpp.
View newest version in sPHENIX GitHub at line 56 of file CsvPlanarClusterReader.hpp
Constructor & Destructor Documentation
ActsExamples::CsvPlanarClusterReader::CsvPlanarClusterReader (const Config & config, Acts::Logging::Level level)
Construct the cluster reader.
Parameters
config is the configuration object
level is the logging level
Definition at line 41 of file CsvPlanarClusterReader.cpp.
View newest version in sPHENIX GitHub at line 41 of file CsvPlanarClusterReader.cpp
References ActsExamples::WriteDataHandle< T >::initialize(), m_cfg, m_outputClusters, m_outputHitIds, m_outputMeasurementParticlesMap, m_outputSimHits, ActsExamples::CsvPlanarClusterReader::Config::outputClusters, ActsExamples::CsvPlanarClusterReader::Config::outputHitIds, ActsExamples::CsvPlanarClusterReader::Config::outputMeasurementParticlesMap, ActsExamples::CsvPlanarClusterReader::Config::outputSimHits, and ActsExamples::CsvPlanarClusterReader::Config::trackingGeometry.
Member Function Documentation
std::pair< size_t, size_t > ActsExamples::CsvPlanarClusterReader::availableEvents () const override virtual
Return the available events range.
Implements ActsExamples::IReader.
Definition at line 77 of file CsvPlanarClusterReader.cpp.
View newest version in sPHENIX GitHub at line 77 of file CsvPlanarClusterReader.cpp
const Config& ActsExamples::CsvPlanarClusterReader::config () const inline
Readonly access to the config.
Definition at line 88 of file CsvPlanarClusterReader.hpp.
View newest version in sPHENIX GitHub at line 88 of file CsvPlanarClusterReader.hpp
References m_cfg.
const Acts::Logger& ActsExamples::CsvPlanarClusterReader::logger () const inline private
Definition at line 102 of file CsvPlanarClusterReader.hpp.
View newest version in sPHENIX GitHub at line 102 of file CsvPlanarClusterReader.hpp
References m_logger.
std::string ActsExamples::CsvPlanarClusterReader::name () const override virtual
The algorithm name.
Implements ActsExamples::SequenceElement.
ActsExamples::ProcessCode ActsExamples::CsvPlanarClusterReader::read (const ActsExamples::AlgorithmContext & ctx) override virtual
Read out data from the input stream.
Implements ActsExamples::IReader.
Definition at line 166 of file CsvPlanarClusterReader.cpp.
View newest version in sPHENIX GitHub at line 166 of file CsvPlanarClusterReader.cpp
References ACTS_FATAL, Acts::PhysicalConstants::c, clusters, Acts::Test::cov, ActsExamples::AlgorithmContext::eventNumber, ActsExamples::AlgorithmContext::geoContext, Acts::Surface::getSharedPtr(), Acts::UnitConstants::GeV, Acts::Surface::globalToLocal(), m_cfg(), ActsExamples::makeRange(), Acts::UnitConstants::mm, testing::internal::move(), next, Acts::UnitConstants::ns, Acts::Test::pos, SUCCESS, writeMapConfig::surface, and Acts::Test::time.
Member Data Documentation
Config ActsExamples::CsvPlanarClusterReader::m_cfg private
Definition at line 91 of file CsvPlanarClusterReader.hpp.
View newest version in sPHENIX GitHub at line 91 of file CsvPlanarClusterReader.hpp
Referenced by config(), and CsvPlanarClusterReader().
std::pair<size_t, size_t> ActsExamples::CsvPlanarClusterReader::m_eventsRange private
Definition at line 92 of file CsvPlanarClusterReader.hpp.
View newest version in sPHENIX GitHub at line 92 of file CsvPlanarClusterReader.hpp
std::unique_ptr<const Acts::Logger> ActsExamples::CsvPlanarClusterReader::m_logger private
Definition at line 93 of file CsvPlanarClusterReader.hpp.
View newest version in sPHENIX GitHub at line 93 of file CsvPlanarClusterReader.hpp
Referenced by logger().
WriteDataHandle<GeometryIdMultimap<Acts::PlanarModuleCluster> > ActsExamples::CsvPlanarClusterReader::m_outputClusters {this, "OutputClusters"} private
Definition at line 96 of file CsvPlanarClusterReader.hpp.
View newest version in sPHENIX GitHub at line 96 of file CsvPlanarClusterReader.hpp
Referenced by CsvPlanarClusterReader().
WriteDataHandle<std::vector<uint64_t> > ActsExamples::CsvPlanarClusterReader::m_outputHitIds {this, "OutputHitIds"} private
Definition at line 100 of file CsvPlanarClusterReader.hpp.
View newest version in sPHENIX GitHub at line 100 of file CsvPlanarClusterReader.hpp
Referenced by CsvPlanarClusterReader().
WriteDataHandle<IndexMultimap<ActsFatras::Barcode> > ActsExamples::CsvPlanarClusterReader::m_outputMeasurementParticlesMap {this, "OutputMeasurementParticlesMap"} private
Definition at line 98 of file CsvPlanarClusterReader.hpp.
View newest version in sPHENIX GitHub at line 98 of file CsvPlanarClusterReader.hpp
Referenced by CsvPlanarClusterReader().
WriteDataHandle<SimHitContainer> ActsExamples::CsvPlanarClusterReader::m_outputSimHits {this, "OutputSimHits"} private
Definition at line 99 of file CsvPlanarClusterReader.hpp.
View newest version in sPHENIX GitHub at line 99 of file CsvPlanarClusterReader.hpp
Referenced by CsvPlanarClusterReader().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Io/Csv/include/ActsExamples/Io/Csv/CsvPlanarClusterReader.hpp
acts/blob/sPHENIX/Examples/Io/Csv/src/CsvPlanarClusterReader.cpp