Analysis Software: PktSizeDBodbc Class Reference
PktSizeDBodbc Class Reference
#include <OnlMon/blob/main/subsystems/pktsize/PktSizeDBodbc.h>
Public Member Functions
PktSizeDBodbc (const std::string &name)
virtual ~PktSizeDBodbc ()
int CheckAndCreateTable (const std::string &name, const std::map< unsigned int, unsigned int > &packetsize)
int CheckAndAddColumns (const std::string &table, const std::map< unsigned int, unsigned int > &packetsize)
int AddRow (const std::string &granulename, const int runnumber, const int nevnts, const std::map< unsigned int, unsigned int > &packetsize)
int GetPacketContent (std::map< unsigned int, float > &packetsize, const int runnumber, const std::string &table)
Public Member Functions inherited from OnlMonBase
OnlMonBase (const std::string &name="NONE")
virtual ~OnlMonBase ()
const std::string Name () const
void Name (const std::string &name)
virtual void Verbosity (const int i)
virtual int Verbosity () const
Private Member Functions
int GetConnection ()
Private Attributes
std::string dbname
std::string dbowner
std::string dbpasswd
std::string tableprefix
Additional Inherited Members
Protected Attributes inherited from OnlMonBase
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 11 of file PktSizeDBodbc.h.
View newest version in sPHENIX GitHub at line 11 of file PktSizeDBodbc.h
Constructor & Destructor Documentation
PktSizeDBodbc::PktSizeDBodbc (const std::string & name)
Definition at line 24 of file PktSizeDBodbc.cc.
View newest version in sPHENIX GitHub at line 24 of file PktSizeDBodbc.cc
PktSizeDBodbc::~PktSizeDBodbc () virtual
Definition at line 30 of file PktSizeDBodbc.cc.
View newest version in sPHENIX GitHub at line 30 of file PktSizeDBodbc.cc
References con.
Member Function Documentation
int PktSizeDBodbc::AddRow (const std::string & granulename, const int runnumber, const int nevnts, const std::map< unsigned int, unsigned int > & packetsize)
Definition at line 99 of file PktSizeDBodbc.cc.
View newest version in sPHENIX GitHub at line 99 of file PktSizeDBodbc.cc
References CheckAndAddColumns(), CheckAndCreateTable(), runCondor_beamspot::cmd, odbc::Connection::createStatement(), Acts::UnitConstants::e, physmon_vertexing::events, odbc::Statement::executeQuery(), odbc::Statement::executeUpdate(), GetConnection(), odbc::ResultSet::getInt(), odbc::SQLException::getMessage(), odbc::ResultSet::next(), runnumber, and tableprefix.
Referenced by PktSizeMon::UpdateDB().
int PktSizeDBodbc::CheckAndAddColumns (const std::string & table, const std::map< unsigned int, unsigned int > & packetsize)
Definition at line 268 of file PktSizeDBodbc.cc.
View newest version in sPHENIX GitHub at line 268 of file PktSizeDBodbc.cc
References runCondor_beamspot::cmd, odbc::Connection::createStatement(), Acts::UnitConstants::e, odbc::Statement::executeQuery(), odbc::Statement::executeUpdate(), odbc::ResultSetMetaData::getColumnCount(), odbc::ResultSetMetaData::getColumnName(), GetConnection(), odbc::SQLException::getMessage(), odbc::ResultSet::getMetaData(), and i.
Referenced by AddRow().
int PktSizeDBodbc::CheckAndCreateTable (const std::string & name, const std::map< unsigned int, unsigned int > & packetsize)
Definition at line 36 of file PktSizeDBodbc.cc.
View newest version in sPHENIX GitHub at line 36 of file PktSizeDBodbc.cc
References runCondor_beamspot::cmd, odbc::Connection::createStatement(), Acts::UnitConstants::e, odbc::Statement::executeQuery(), odbc::Statement::executeUpdate(), GetConnection(), odbc::SQLException::getMessage(), perf_headwind::name, odbc::ResultSet::next(), Acts::Test::transform, and OnlMonBase::verbosity.
Referenced by AddRow().
int PktSizeDBodbc::GetConnection () private
Definition at line 242 of file PktSizeDBodbc.cc.
View newest version in sPHENIX GitHub at line 242 of file PktSizeDBodbc.cc
References con, dbname, dbowner, dbpasswd, Acts::UnitConstants::e, odbc::DriverManager::getConnection(), odbc::SQLException::getMessage(), PHWHERE, and printf().
Referenced by AddRow(), CheckAndAddColumns(), CheckAndCreateTable(), and GetPacketContent().
int PktSizeDBodbc::GetPacketContent (std::map< unsigned int, float > & packetsize, const int runnumber, const std::string & table)
Definition at line 183 of file PktSizeDBodbc.cc.
View newest version in sPHENIX GitHub at line 183 of file PktSizeDBodbc.cc
References runCondor_beamspot::cmd, odbc::Connection::createStatement(), Acts::UnitConstants::e, odbc::Statement::executeQuery(), odbc::ResultSetMetaData::getColumnCount(), odbc::ResultSetMetaData::getColumnName(), GetConnection(), odbc::ResultSet::getFloat(), odbc::SQLException::getMessage(), odbc::ResultSet::getMetaData(), i, odbc::ResultSet::next(), runnumber, size, tableprefix, OnlMonBase::verbosity, and odbc::ResultSet::wasNull().
Referenced by PktSizeMonDraw::FillRunPacketList().
Member Data Documentation
std::string PktSizeDBodbc::dbname private
Definition at line 23 of file PktSizeDBodbc.h.
View newest version in sPHENIX GitHub at line 23 of file PktSizeDBodbc.h
Referenced by GetConnection().
std::string PktSizeDBodbc::dbowner private
Definition at line 24 of file PktSizeDBodbc.h.
View newest version in sPHENIX GitHub at line 24 of file PktSizeDBodbc.h
Referenced by GetConnection().
std::string PktSizeDBodbc::dbpasswd private
Definition at line 25 of file PktSizeDBodbc.h.
View newest version in sPHENIX GitHub at line 25 of file PktSizeDBodbc.h
Referenced by GetConnection().
std::string PktSizeDBodbc::tableprefix private
Definition at line 26 of file PktSizeDBodbc.h.
View newest version in sPHENIX GitHub at line 26 of file PktSizeDBodbc.h
Referenced by AddRow(), and GetPacketContent().
The documentation for this class was generated from the following files:
OnlMon/blob/main/subsystems/pktsize/PktSizeDBodbc.h
OnlMon/blob/main/subsystems/pktsize/PktSizeDBodbc.cc