Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Fatras/Kernel/InteractionListTests.cpp File Reference
InteractionListTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Units.hpp"
#include "Acts/Material/MaterialSlab.hpp"
#include "Acts/Tests/CommonHelpers/PredefinedMaterials.hpp"
#include "ActsFatras/EventData/Barcode.hpp"
#include "ActsFatras/EventData/Particle.hpp"
#include "ActsFatras/Kernel/InteractionList.hpp"
#include <cstdint>
#include <limits>
#include <random>
#include <utility>
#include <vector>
Typedefs
using Scalar = Particle::Scalar
Functions
BOOST_AUTO_TEST_CASE (Empty)
BOOST_AUTO_TEST_CASE (ContinuousSterile)
BOOST_AUTO_TEST_CASE (ContinuousFatal)
BOOST_AUTO_TEST_CASE (ContinuousSterileFatal)
BOOST_AUTO_TEST_CASE (PointLikeX0)
BOOST_AUTO_TEST_CASE (PointLikeL0)
BOOST_AUTO_TEST_CASE (PointLikeX0L0)
BOOST_AUTO_TEST_CASE (Disable)
Typedef Documentation
using Scalar = Particle::Scalar
Definition at line 28 of file InteractionListTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file InteractionListTests.cpp
Function Documentation
BOOST_AUTO_TEST_CASE (Empty)
Definition at line 123 of file InteractionListTests.cpp.
View newest version in sPHENIX GitHub at line 123 of file InteractionListTests.cpp
References ActsFatras::InteractionList< processes_t >::armPointLike(), f, ActsFatras::InteractionList< processes_t >::runContinuous(), ActsFatras::InteractionList< processes_t >::runPointLike(), and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (ContinuousSterile)
Definition at line 146 of file InteractionListTests.cpp.
View newest version in sPHENIX GitHub at line 146 of file InteractionListTests.cpp
References f, and ActsFatras::InteractionList< processes_t >::runContinuous().
BOOST_AUTO_TEST_CASE (ContinuousFatal)
Definition at line 154 of file InteractionListTests.cpp.
View newest version in sPHENIX GitHub at line 154 of file InteractionListTests.cpp
References f, and ActsFatras::InteractionList< processes_t >::runContinuous().
BOOST_AUTO_TEST_CASE (ContinuousSterileFatal)
Definition at line 162 of file InteractionListTests.cpp.
View newest version in sPHENIX GitHub at line 162 of file InteractionListTests.cpp
References ActsFatras::InteractionList< processes_t >::disable(), f, and ActsFatras::InteractionList< processes_t >::runContinuous().
BOOST_AUTO_TEST_CASE (PointLikeX0)
Definition at line 174 of file InteractionListTests.cpp.
View newest version in sPHENIX GitHub at line 174 of file InteractionListTests.cpp
References ActsFatras::InteractionList< processes_t >::armPointLike(), f, ActsFatras::InteractionList< processes_t >::runPointLike(), and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (PointLikeL0)
Definition at line 193 of file InteractionListTests.cpp.
View newest version in sPHENIX GitHub at line 193 of file InteractionListTests.cpp
References ActsFatras::InteractionList< processes_t >::armPointLike(), f, ActsFatras::InteractionList< processes_t >::runPointLike(), and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (PointLikeX0L0)
Definition at line 212 of file InteractionListTests.cpp.
View newest version in sPHENIX GitHub at line 212 of file InteractionListTests.cpp
References ActsFatras::InteractionList< processes_t >::armPointLike(), f, ActsFatras::InteractionList< processes_t >::runPointLike(), and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (Disable)
Definition at line 236 of file InteractionListTests.cpp.
View newest version in sPHENIX GitHub at line 236 of file InteractionListTests.cpp
References ActsFatras::InteractionList< processes_t >::armPointLike(), ActsFatras::InteractionList< processes_t >::disable(), f, and physmon_ckf_tracking::u.