Analysis Software: PHParameterContainerInterface Class Reference
PHParameterContainerInterface Class Reference abstract
#include <coresoftware/blob/master/offline/database/PHParameter/PHParameterContainerInterface.h>
Public Member Functions
PHParameterContainerInterface (const std::string &name)
PHParameterContainerInterface (const PHParameterContainerInterface &)=delete
PHParameterContainerInterface & operator= (PHParameterContainerInterface const &)=delete
virtual ~PHParameterContainerInterface ()
void set_name (const std::string &name)
virtual void SetDefaultParameters ()=0
void set_double_param (const int id, const std::string &name, const double dval)
double get_double_param (const int id, const std::string &name) const
void set_int_param (const int id, const std::string &name, const int ival)
int get_int_param (const int id, const std::string &name) const
void set_string_param (const int id, const std::string &name, const std::string &sval)
std::string get_string_param (const int id, const std::string &name) const
void UpdateParametersWithMacro ()
void CreateInitialize (const int detid)
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
int ExistDetid (const int detid) const
Protected Member Functions
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
const PHParametersContainer * GetParamsContainer ()
PHParametersContainer * GetParamsContainerModify ()
const PHParameters * GetDefaultParameters ()
Private Attributes
PHParametersContainer * paramscontainer = nullptr
PHParameters * defaultparams = nullptr
std::map< int, PHParameters * > macroparams
Detailed Description
Definition at line 13 of file PHParameterContainerInterface.h.
View newest version in sPHENIX GitHub at line 13 of file PHParameterContainerInterface.h
Constructor & Destructor Documentation
PHParameterContainerInterface::PHParameterContainerInterface (const std::string & name)
Definition at line 15 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 15 of file PHParameterContainerInterface.cc
References defaultparams, and pname().
PHParameterContainerInterface::PHParameterContainerInterface (const PHParameterContainerInterface &) delete
PHParameterContainerInterface::~PHParameterContainerInterface () virtual
Definition at line 23 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 23 of file PHParameterContainerInterface.cc
References defaultparams, macroparams, and paramscontainer.
Member Function Documentation
void PHParameterContainerInterface::CreateInitialize (const int detid)
Definition at line 238 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 238 of file PHParameterContainerInterface.cc
References PHParametersContainer::AddPHParameters(), defaultparams, PHParametersContainer::GetParametersToModify(), PHParametersContainer::Name(), and paramscontainer.
Referenced by UpdateParametersWithMacro().
int PHParameterContainerInterface::ExistDetid (const int detid) const
Definition at line 251 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 251 of file PHParameterContainerInterface.cc
References PHParametersContainer::ExistDetid(), and paramscontainer.
Referenced by PHG4BlockCellReco::InitRun(), and PHG4CylinderCellReco::InitRun().
double PHParameterContainerInterface::get_double_param (const int id, const std::string & name) const
Definition at line 103 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 103 of file PHParameterContainerInterface.cc
References PHParameters::get_double_param(), PHParametersContainer::GetParameters(), PHParametersContainer::Name(), and paramscontainer.
Referenced by PHG4BlockCellReco::InitRun(), and PHG4CylinderCellReco::InitRun().
int PHParameterContainerInterface::get_int_param (const int id, const std::string & name) const
Definition at line 141 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 141 of file PHParameterContainerInterface.cc
References PHParameters::get_int_param(), PHParametersContainer::GetParameters(), PHParametersContainer::Name(), paramscontainer, and x0.
std::string PHParameterContainerInterface::get_string_param (const int id, const std::string & name) const
Definition at line 181 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 181 of file PHParameterContainerInterface.cc
References PHParameters::get_string_param(), PHParametersContainer::GetParameters(), PHParametersContainer::Name(), and paramscontainer.
const PHParameters* PHParameterContainerInterface::GetDefaultParameters () inline protected
Definition at line 48 of file PHParameterContainerInterface.h.
View newest version in sPHENIX GitHub at line 48 of file PHParameterContainerInterface.h
References defaultparams.
const PHParametersContainer* PHParameterContainerInterface::GetParamsContainer () inline protected
Definition at line 46 of file PHParameterContainerInterface.h.
View newest version in sPHENIX GitHub at line 46 of file PHParameterContainerInterface.h
References paramscontainer.
Referenced by PHG4BlockCellReco::InitRun(), and PHG4CylinderCellReco::InitRun().
PHParametersContainer* PHParameterContainerInterface::GetParamsContainerModify () inline protected
Definition at line 47 of file PHParameterContainerInterface.h.
View newest version in sPHENIX GitHub at line 47 of file PHParameterContainerInterface.h
References paramscontainer.
Referenced by PHG4BlockCellReco::InitRun(), and PHG4CylinderCellReco::InitRun().
void PHParameterContainerInterface::InitializeParameters () protected
Definition at line 233 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 233 of file PHParameterContainerInterface.cc
References SetDefaultParameters().
PHParameterContainerInterface& PHParameterContainerInterface::operator= (PHParameterContainerInterface const &) delete
void PHParameterContainerInterface::PutOnParNode (PHCompositeNode * parNode, const std::string & nodename)
Definition at line 228 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 228 of file PHParameterContainerInterface.cc
References PHCompositeNode::addNode(), and paramscontainer.
void PHParameterContainerInterface::SaveToNodeTree (PHCompositeNode * runNode, const std::string & nodename)
Definition at line 222 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 222 of file PHParameterContainerInterface.cc
References paramscontainer, and PHParametersContainer::SaveToNodeTree().
Referenced by PHG4BlockCellReco::InitRun(), and PHG4CylinderCellReco::InitRun().
void PHParameterContainerInterface::set_default_double_param (const std::string & name, const double dval) protected
Definition at line 40 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 40 of file PHParameterContainerInterface.cc
References defaultparams, PHParameters::exist_double_param(), PHParameters::get_double_param(), and PHParameters::set_double_param().
Referenced by PHG4BlockCellReco::SetDefaultParameters(), and PHG4CylinderCellReco::SetDefaultParameters().
void PHParameterContainerInterface::set_default_int_param (const std::string & name, const int ival) protected
Definition at line 52 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 52 of file PHParameterContainerInterface.cc
References defaultparams, PHParameters::exist_int_param(), PHParameters::get_int_param(), and PHParameters::set_int_param().
void PHParameterContainerInterface::set_default_string_param (const std::string & name, const std::string & sval) protected
Definition at line 64 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 64 of file PHParameterContainerInterface.cc
References defaultparams, PHParameters::exist_string_param(), PHParameters::get_string_param(), and PHParameters::set_string_param().
void PHParameterContainerInterface::set_double_param (const int id, const std::string & name, const double dval)
Definition at line 76 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 76 of file PHParameterContainerInterface.cc
References defaultparams, PHParameters::exist_double_param(), macroparams, PHParametersContainer::Name(), paramscontainer, PHParameters::printdouble(), and PHParameters::set_double_param().
Referenced by PHG4CylinderCellReco::cellsize(), PHG4CylinderCellReco::etaphisize(), PHG4BlockCellReco::etaxsize(), PHG4BlockCellReco::set_timing_window(), and PHG4CylinderCellReco::set_timing_window().
void PHParameterContainerInterface::set_int_param (const int id, const std::string & name, const int ival)
Definition at line 115 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 115 of file PHParameterContainerInterface.cc
References PHParametersContainer::AddPHParameters(), defaultparams, PHParameters::exist_int_param(), macroparams, PHParametersContainer::Name(), paramscontainer, PHParameters::printint(), and PHParameters::set_int_param().
void PHParameterContainerInterface::set_name (const std::string & name)
Definition at line 35 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 35 of file PHParameterContainerInterface.cc
References paramscontainer, and PHParametersContainer::set_name().
void PHParameterContainerInterface::set_string_param (const int id, const std::string & name, const std::string & sval)
Definition at line 153 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 153 of file PHParameterContainerInterface.cc
References PHParametersContainer::AddPHParameters(), defaultparams, PHParameters::exist_string_param(), macroparams, PHParametersContainer::Name(), paramscontainer, PHParameters::printstring(), and PHParameters::set_string_param().
virtual void PHParameterContainerInterface::SetDefaultParameters () pure virtual
Implemented in PHG4CylinderCellReco, and PHG4BlockCellReco.
Referenced by InitializeParameters().
void PHParameterContainerInterface::UpdateParametersWithMacro ()
Definition at line 193 of file PHParameterContainerInterface.cc.
View newest version in sPHENIX GitHub at line 193 of file PHParameterContainerInterface.cc
References CreateInitialize(), PHParametersContainer::GetParametersToModify(), macroparams, paramscontainer, PHParameters::set_double_param(), PHParameters::set_int_param(), and PHParameters::set_string_param().
Referenced by PHG4BlockCellReco::InitRun(), and PHG4CylinderCellReco::InitRun().
Member Data Documentation
PHParameters* PHParameterContainerInterface::defaultparams = nullptr private
Definition at line 52 of file PHParameterContainerInterface.h.
View newest version in sPHENIX GitHub at line 52 of file PHParameterContainerInterface.h
Referenced by CreateInitialize(), GetDefaultParameters(), PHParameterContainerInterface(), set_default_double_param(), set_default_int_param(), set_default_string_param(), set_double_param(), set_int_param(), set_string_param(), and ~PHParameterContainerInterface().
std::map<int, PHParameters *> PHParameterContainerInterface::macroparams private
Definition at line 53 of file PHParameterContainerInterface.h.
View newest version in sPHENIX GitHub at line 53 of file PHParameterContainerInterface.h
Referenced by set_double_param(), set_int_param(), set_string_param(), UpdateParametersWithMacro(), and ~PHParameterContainerInterface().
PHParametersContainer* PHParameterContainerInterface::paramscontainer = nullptr private
Definition at line 51 of file PHParameterContainerInterface.h.
View newest version in sPHENIX GitHub at line 51 of file PHParameterContainerInterface.h
Referenced by CreateInitialize(), ExistDetid(), get_double_param(), get_int_param(), get_string_param(), GetParamsContainer(), GetParamsContainerModify(), PutOnParNode(), SaveToNodeTree(), set_double_param(), set_int_param(), set_name(), set_string_param(), UpdateParametersWithMacro(), and ~PHParameterContainerInterface().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/PHParameter/PHParameterContainerInterface.h
coresoftware/blob/master/offline/database/PHParameter/PHParameterContainerInterface.cc