Analysis Software: PdbParameterMap Class Reference
PdbParameterMap Class Reference
#include <coresoftware/blob/master/offline/database/pdbcal/base/PdbParameterMap.h>
Public Types
typedef std::map< const
std::string, double > dMap
typedef std::map< const
std::string, int > iMap
typedef std::map< const
std::string, std::string > strMap
typedef dMap::const_iterator dIter
typedef iMap::const_iterator iIter
typedef strMap::const_iterator strIter
typedef std::pair< dIter, dIter > dConstRange
typedef std::pair< iIter, iIter > iConstRange
typedef std::pair< strIter,
strIter > strConstRange
Public Member Functions
PdbParameterMap ()
~PdbParameterMap () override
PHObject * CloneMe () const override
Virtual copy constructor.
void print () const override
void Reset () override
Clear Event.
size_t get_hash () const
hash of binary information for checking purpose
dConstRange get_dparam_iters () const
iConstRange get_iparam_iters () const
strConstRange get_cparam_iters () const
void set_int_param (const std::string &name, const int ival)
void set_double_param (const std::string &name, const double dval)
void set_string_param (const std::string &name, const std::string &str)
Public Member Functions inherited from PdbCalChan
PdbCalChan ()
~PdbCalChan () override
ClassDefOverride (PdbCalChan, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
dMap dparams
iMap iparams
strMap cparams
Detailed Description
Definition at line 13 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 13 of file PdbParameterMap.h
Member Typedef Documentation
typedef std::pair<dIter, dIter> PdbParameterMap::dConstRange
Definition at line 22 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 22 of file PdbParameterMap.h
typedef dMap::const_iterator PdbParameterMap::dIter
Definition at line 19 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 19 of file PdbParameterMap.h
typedef std::map<const std::string, double> PdbParameterMap::dMap
Definition at line 16 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 16 of file PdbParameterMap.h
typedef std::pair<iIter, iIter> PdbParameterMap::iConstRange
Definition at line 23 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 23 of file PdbParameterMap.h
typedef iMap::const_iterator PdbParameterMap::iIter
Definition at line 20 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 20 of file PdbParameterMap.h
typedef std::map<const std::string, int> PdbParameterMap::iMap
Definition at line 17 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 17 of file PdbParameterMap.h
typedef std::pair<strIter, strIter> PdbParameterMap::strConstRange
Definition at line 24 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 24 of file PdbParameterMap.h
typedef strMap::const_iterator PdbParameterMap::strIter
Definition at line 21 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 21 of file PdbParameterMap.h
typedef std::map<const std::string, std::string> PdbParameterMap::strMap
Definition at line 18 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 18 of file PdbParameterMap.h
Constructor & Destructor Documentation
PdbParameterMap::PdbParameterMap () inline
Definition at line 26 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 26 of file PdbParameterMap.h
Referenced by CloneMe().
PdbParameterMap::~PdbParameterMap () inline override
Definition at line 27 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 27 of file PdbParameterMap.h
Member Function Documentation
PHObject* PdbParameterMap::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 29 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 29 of file PdbParameterMap.h
References PdbParameterMap().
strConstRange PdbParameterMap::get_cparam_iters () const inline
Definition at line 44 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 44 of file PdbParameterMap.h
References cparams.
Referenced by PHParameters::FillFrom(), and DumpPdbParameterMap::process_Node().
dConstRange PdbParameterMap::get_dparam_iters () const inline
Definition at line 37 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 37 of file PdbParameterMap.h
References dparams.
Referenced by PHParameters::FillFrom(), and DumpPdbParameterMap::process_Node().
size_t PdbParameterMap::get_hash () const
hash of binary information for checking purpose
Definition at line 53 of file PdbParameterMap.cc.
View newest version in sPHENIX GitHub at line 53 of file PdbParameterMap.cc
References seed.
Referenced by PHParameters::ReadFromFile().
iConstRange PdbParameterMap::get_iparam_iters () const inline
Definition at line 40 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 40 of file PdbParameterMap.h
References iparams.
Referenced by PHParameters::FillFrom(), HFMLTriggerInterface::process_event(), and DumpPdbParameterMap::process_Node().
void PdbParameterMap::print () const override virtual
Implements PdbCalChan.
Definition at line 8 of file PdbParameterMap.cc.
View newest version in sPHENIX GitHub at line 8 of file PdbParameterMap.cc
void PdbParameterMap::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 29 of file PdbParameterMap.cc.
View newest version in sPHENIX GitHub at line 29 of file PdbParameterMap.cc
Referenced by PHParameters::SaveToNodeTree().
void PdbParameterMap::set_double_param (const std::string & name, const double dval)
Definition at line 42 of file PdbParameterMap.cc.
View newest version in sPHENIX GitHub at line 42 of file PdbParameterMap.cc
References perf_headwind::name.
Referenced by PHParameters::CopyToPdbParameterMap().
void PdbParameterMap::set_int_param (const std::string & name, const int ival)
Definition at line 37 of file PdbParameterMap.cc.
View newest version in sPHENIX GitHub at line 37 of file PdbParameterMap.cc
References perf_headwind::name.
Referenced by PHParameters::CopyToPdbParameterMap(), and HFMLTriggerHepMCTrigger::process_event().
void PdbParameterMap::set_string_param (const std::string & name, const std::string & str)
Definition at line 47 of file PdbParameterMap.cc.
View newest version in sPHENIX GitHub at line 47 of file PdbParameterMap.cc
References perf_headwind::name, and str.
Referenced by PHParameters::CopyToPdbParameterMap().
Member Data Documentation
strMap PdbParameterMap::cparams protected
Definition at line 55 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 55 of file PdbParameterMap.h
Referenced by get_cparam_iters().
dMap PdbParameterMap::dparams protected
Definition at line 53 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 53 of file PdbParameterMap.h
Referenced by get_dparam_iters().
iMap PdbParameterMap::iparams protected
Definition at line 54 of file PdbParameterMap.h.
View newest version in sPHENIX GitHub at line 54 of file PdbParameterMap.h
Referenced by get_iparam_iters().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/pdbcal/base/PdbParameterMap.h
coresoftware/blob/master/offline/database/pdbcal/base/PdbParameterMap.cc