Analysis Software: TilingExtent Class Reference
TilingExtent Class Reference
Public Member Functions
TilingExtent (ClusterSequence &cs)
TilingExtent (const std::vector< PseudoJet > &particles)
double minrap () const
double maxrap () const
double sum_of_binned_squared_multiplicity () const
Private Member Functions
void _determine_rapidity_extent (const std::vector< PseudoJet > &particles)
Private Attributes
double _minrap
double _maxrap
double _cumul2
Detailed Description
Definition at line 1146 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1146 of file fjcore.cc
Constructor & Destructor Documentation
FJCORE_BEGIN_NAMESPACE TilingExtent::TilingExtent (ClusterSequence & cs)
Definition at line 6109 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 6109 of file fjcore.cc
TilingExtent::TilingExtent (const std::vector< PseudoJet > & particles)
Definition at line 6112 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 6112 of file fjcore.cc
Member Function Documentation
void TilingExtent::_determine_rapidity_extent (const std::vector< PseudoJet > & particles) private
Definition at line 6115 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 6115 of file fjcore.cc
References assert, E, i, configureMap::ibin, nbins, and y.
double TilingExtent::maxrap () const inline
Definition at line 1151 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1151 of file fjcore.cc
Referenced by LazyTiling9::_initialise_tiles(), LazyTiling25::_initialise_tiles(), and ClusterSequence::_initialise_tiles().
double TilingExtent::minrap () const inline
Definition at line 1150 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1150 of file fjcore.cc
Referenced by LazyTiling9::_initialise_tiles(), LazyTiling25::_initialise_tiles(), and ClusterSequence::_initialise_tiles().
double TilingExtent::sum_of_binned_squared_multiplicity () const inline
Definition at line 1152 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1152 of file fjcore.cc
Member Data Documentation
double TilingExtent::_cumul2 private
Definition at line 1154 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1154 of file fjcore.cc
double TilingExtent::_maxrap private
Definition at line 1154 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1154 of file fjcore.cc
double TilingExtent::_minrap private
Definition at line 1154 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1154 of file fjcore.cc
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/fjcore.cc