Analysis Software: Jetscape::TrentoCollision Class Reference
Jetscape::TrentoCollision Class Reference
#include <JETSCAPE/blob/master/src/initialstate/TrentoCollision.h>
Public Member Functions
TrentoCollision (const VarMap &var_map)
~TrentoCollision ()
Declare a destructor to properly handle the std::unique_ptr<Nucleus>
std::tuple< double, double > JetProductionPosition ()
void Sample (double smin, double smax)
Public Attributes
Event event_
The event instance.
EventInfo info_
Private Member Functions
VarMap TrentoOptions (str cmd)
double SampleImpactParam ()
Sample a min-bias impact parameter within the set range.
Private Attributes
std::unique_ptr< Nucleus > nucleusA_
Pair of nucleus projectiles.
std::unique_ptr< Nucleus > nucleusB_
NucleonProfile nucleon_profile_
The nucleon profile instance.
const int nevents_
Number of events to run.
const double bmin_
Minimum and maximum impact parameter.
const double bmax_
const double asymmetry_
Output output_
The output instance.
Detailed Description
Definition at line 60 of file TrentoCollision.h.
View newest version in sPHENIX GitHub at line 60 of file TrentoCollision.h
Constructor & Destructor Documentation
Jetscape::TrentoCollision::TrentoCollision (const VarMap & var_map) explicit
Definition at line 90 of file TrentoCollision.cc.
View newest version in sPHENIX GitHub at line 90 of file TrentoCollision.cc
References engine, and TauVsDIS_MachineLearning_Differentiation::seed.
Jetscape::TrentoCollision::~TrentoCollision () default
Declare a destructor to properly handle the std::unique_ptr<Nucleus>
Member Function Documentation
std::tuple<double, double> Jetscape::TrentoCollision::JetProductionPosition ()
void Jetscape::TrentoCollision::Sample (double smin, double smax)
Definition at line 111 of file TrentoCollision.cc.
View newest version in sPHENIX GitHub at line 111 of file TrentoCollision.cc
References KFPMath::b, trento::Event::compute(), Jetscape::EventInfo::ecc, trento::Event::eccentricity(), event_, Jetscape::EventInfo::impact_parameter, info_, trento::Event::mass_center_index(), trento::Event::multiplicity(), trento::Event::npart(), nucleon_profile_, nucleusA_, nucleusB_, Jetscape::EventInfo::num_participant, trento::Event::participant_plane(), Jetscape::EventInfo::psi, SampleImpactParam(), Jetscape::EventInfo::total_entropy, Jetscape::EventInfo::xmid, and Jetscape::EventInfo::ymid.
Referenced by Jetscape::TrentoInitial::PreDefined(), and Jetscape::TrentoInitial::UserDefined().
double Jetscape::TrentoCollision::SampleImpactParam () private
Sample a min-bias impact parameter within the set range.
Definition at line 136 of file TrentoCollision.cc.
View newest version in sPHENIX GitHub at line 136 of file TrentoCollision.cc
References asymmetry_, KFPMath::b, bmax_, bmin_, nucleon_profile_, nucleusA_, nucleusB_, and trento::NucleonProfile::participate().
Referenced by Sample().
VarMap Jetscape::TrentoCollision::TrentoOptions (str cmd) private
Member Data Documentation
const double Jetscape::TrentoCollision::asymmetry_ private
Parameterizes the degree of asymmetry between the two projectiles. Used to apportion the total impact parameter to each projectile so that the resulting overlap is approximately centered. Given the two nuclear radii rA and rB (see Nucleus::radius()), the parameter is
asymmetry = rA / (rA + rB)
and the impact parameter b is apportioned
offset_A = asymmetry * b offset_B = (asymmetry-1) * b
So for example, two identical projectiles would have asymmetry = 0.5, and each would be offset by half the impact parameter. A proton-lead system would have asymmetry = 1, meaning the lead nucleus would be offset by the entire impact parameter and the proton would not be offset at all.
Definition at line 129 of file TrentoCollision.h.
View newest version in sPHENIX GitHub at line 129 of file TrentoCollision.h
Referenced by SampleImpactParam().
const double Jetscape::TrentoCollision::bmax_ private
Definition at line 111 of file TrentoCollision.h.
View newest version in sPHENIX GitHub at line 111 of file TrentoCollision.h
Referenced by SampleImpactParam().
const double Jetscape::TrentoCollision::bmin_ private
Minimum and maximum impact parameter.
Definition at line 111 of file TrentoCollision.h.
View newest version in sPHENIX GitHub at line 111 of file TrentoCollision.h
Referenced by SampleImpactParam().
Event Jetscape::TrentoCollision::event_
The event instance.
Definition at line 87 of file TrentoCollision.h.
View newest version in sPHENIX GitHub at line 87 of file TrentoCollision.h
Referenced by Jetscape::TrentoInitial::PreDefined(), Sample(), and Jetscape::TrentoInitial::UserDefined().
EventInfo Jetscape::TrentoCollision::info_
Definition at line 89 of file TrentoCollision.h.
View newest version in sPHENIX GitHub at line 89 of file TrentoCollision.h
Referenced by Jetscape::TrentoInitial::PreDefined(), Sample(), and Jetscape::TrentoInitial::UserDefined().
const int Jetscape::TrentoCollision::nevents_ private
Number of events to run.
Definition at line 108 of file TrentoCollision.h.
View newest version in sPHENIX GitHub at line 108 of file TrentoCollision.h
NucleonProfile Jetscape::TrentoCollision::nucleon_profile_ private
The nucleon profile instance.
Definition at line 105 of file TrentoCollision.h.
View newest version in sPHENIX GitHub at line 105 of file TrentoCollision.h
Referenced by Sample(), and SampleImpactParam().
std::unique_ptr<Nucleus> Jetscape::TrentoCollision::nucleusA_ private
Pair of nucleus projectiles.
Definition at line 102 of file TrentoCollision.h.
View newest version in sPHENIX GitHub at line 102 of file TrentoCollision.h
Referenced by Sample(), and SampleImpactParam().
std::unique_ptr<Nucleus> Jetscape::TrentoCollision::nucleusB_ private
Definition at line 102 of file TrentoCollision.h.
View newest version in sPHENIX GitHub at line 102 of file TrentoCollision.h
Referenced by Sample(), and SampleImpactParam().
Output Jetscape::TrentoCollision::output_ private
The output instance.
Definition at line 133 of file TrentoCollision.h.
View newest version in sPHENIX GitHub at line 133 of file TrentoCollision.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/master/src/initialstate/TrentoCollision.h
JETSCAPE/blob/master/src/initialstate/TrentoCollision.cc