Analysis Software: SvtxTrack_FastSim Class Reference
SvtxTrack_FastSim Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack_FastSim.h>
Public Member Functions
SvtxTrack_FastSim ()=default
~SvtxTrack_FastSim () override=default
SvtxTrack_FastSim (const SvtxTrack &)
void CopyFrom (const SvtxTrack &) override
copy content from base class
void CopyFrom (SvtxTrack *source) override
copy content from base class
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
accessors
unsigned int get_truth_track_id () const override
unsigned int get_num_measurements () const override
modifiers
void set_truth_track_id (unsigned int truthTrackId) override
void set_num_measurements (int nmeas) override
Public Member Functions inherited from SvtxTrack_v1
SvtxTrack_v1 ()
SvtxTrack_v1 (const SvtxTrack &)
SvtxTrack_v1 (const SvtxTrack_v1 &track)
SvtxTrack_v1 & operator= (const SvtxTrack_v1 &track)
~SvtxTrack_v1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void CopyFrom (const SvtxTrack &) override
copy content from base class
void CopyFrom (SvtxTrack *source) override
copy content from base class
unsigned int get_id () const override
void set_id (unsigned int id) override
unsigned int get_vertex_id () const override
void set_vertex_id (unsigned int id) override
bool get_positive_charge () const override
void set_positive_charge (bool ispos) override
int get_charge () const override
void set_charge (int charge) override
float get_chisq () const override
void set_chisq (float chisq) override
unsigned int get_ndf () const override
void set_ndf (int ndf) override
float get_quality () const override
float get_dca () const override
void set_dca (float dca) override
float get_dca_error () const override
void set_dca_error (float dca_error) override
float get_dca2d () const override
void set_dca2d (float dca2d) override
float get_dca2d_error () const override
void set_dca2d_error (float error) override
float get_dca3d_xy () const override
void set_dca3d_xy (float dcaxy) override
float get_dca3d_xy_error () const override
void set_dca3d_xy_error (float error) override
float get_dca3d_z () const override
void set_dca3d_z (float dcaz) override
float get_dca3d_z_error () const override
void set_dca3d_z_error (float error) override
float get_x () const override
void set_x (float x) override
float get_y () const override
void set_y (float y) override
float get_z () const override
void set_z (float z) override
float get_pos (unsigned int i) const override
float get_px () const override
void set_px (float px) override
float get_py () const override
void set_py (float py) override
float get_pz () const override
void set_pz (float pz) override
float get_mom (unsigned int i) const override
float get_p () const override
float get_pt () const override
float get_eta () const override
float get_phi () const override
float get_error (int i, int j) const override
void set_error (int i, int j, float value) override
bool empty_states () const override
size_t size_states () const override
size_t count_states (float pathlength) const override
void clear_states () override
const SvtxTrackState * get_state (float pathlength) const override
SvtxTrackState * get_state (float pathlength) override
SvtxTrackState * insert_state (const SvtxTrackState *state) override
size_t erase_state (float pathlength) override
ConstStateIter begin_states () const override
ConstStateIter find_state (float pathlength) const override
ConstStateIter end_states () const override
StateIter begin_states () override
StateIter find_state (float pathlength) override
StateIter end_states () override
void clear_clusters () override
bool empty_clusters () const override
size_t size_clusters () const override
void insert_cluster (unsigned int clusterid) override
size_t erase_cluster (unsigned int clusterid) override
ConstClusterIter begin_clusters () const override
ConstClusterIter find_cluster (unsigned int clusterid) const override
ConstClusterIter end_clusters () const override
ClusterIter find_cluster (unsigned int clusterid) override
ClusterIter begin_clusters () override
ClusterIter end_clusters () override
void clear_cluster_keys () override
bool empty_cluster_keys () const override
size_t size_cluster_keys () const override
void insert_cluster_key (TrkrDefs::cluskey clusterid) override
size_t erase_cluster_key (TrkrDefs::cluskey clusterid) override
ConstClusterKeyIter find_cluster_key (TrkrDefs::cluskey clusterid) const override
ConstClusterKeyIter begin_cluster_keys () const override
ConstClusterKeyIter end_cluster_keys () const override
ClusterKeyIter find_cluster_keys (unsigned int clusterid) override
ClusterKeyIter begin_cluster_keys () override
ClusterKeyIter end_cluster_keys () override
float get_cal_dphi (CAL_LAYER layer) const override
void set_cal_dphi (CAL_LAYER layer, float dphi) override
float get_cal_deta (CAL_LAYER layer) const override
void set_cal_deta (CAL_LAYER layer, float deta) override
float get_cal_energy_3x3 (CAL_LAYER layer) const override
void set_cal_energy_3x3 (CAL_LAYER layer, float energy_3x3) override
float get_cal_energy_5x5 (CAL_LAYER layer) const override
void set_cal_energy_5x5 (CAL_LAYER layer, float energy_5x5) override
unsigned int get_cal_cluster_id (CAL_LAYER layer) const override
void set_cal_cluster_id (CAL_LAYER layer, unsigned int id) override
TrkrDefs::cluskey get_cal_cluster_key (CAL_LAYER layer) const override
void set_cal_cluster_key (CAL_LAYER layer, TrkrDefs::cluskey id) override
float get_cal_cluster_e (CAL_LAYER layer) const override
void set_cal_cluster_e (CAL_LAYER layer, float e) override
Public Member Functions inherited from SvtxTrack
~SvtxTrack () override=default
virtual TrackSeed * get_tpc_seed () const
virtual void set_tpc_seed (TrackSeed *)
virtual TrackSeed * get_silicon_seed () const
virtual void set_silicon_seed (TrackSeed *)
virtual short int get_crossing () const
virtual void set_crossing (short int)
virtual float get_cal_dphi (CAL_LAYER) const
virtual void set_cal_dphi (CAL_LAYER, float)
virtual float get_cal_deta (CAL_LAYER) const
virtual void set_cal_deta (CAL_LAYER, float)
virtual float get_cal_energy_3x3 (CAL_LAYER) const
virtual void set_cal_energy_3x3 (CAL_LAYER, float)
virtual float get_cal_energy_5x5 (CAL_LAYER) const
virtual void set_cal_energy_5x5 (CAL_LAYER, float)
virtual unsigned int get_cal_cluster_id (CAL_LAYER) const
virtual void set_cal_cluster_id (CAL_LAYER, unsigned int)
virtual TrkrDefs::cluskey get_cal_cluster_key (CAL_LAYER) const
virtual void set_cal_cluster_key (CAL_LAYER, TrkrDefs::cluskey)
virtual float get_cal_cluster_e (CAL_LAYER) const
virtual void set_cal_cluster_e (CAL_LAYER, float)
virtual float get_acts_covariance (unsigned int, unsigned int) const
virtual void set_acts_covariance (unsigned int, unsigned int, float)
virtual bool empty_g4hit_id () const
virtual size_t size_g4hit_id () const
virtual void add_g4hit_id (int, PHG4HitDefs::keytype)
virtual HitIdIter begin_g4hit_id ()
virtual HitIdConstIter begin_g4hit_id () const
virtual HitIdIter find_g4hit_id (int)
virtual HitIdConstIter find_g4hit_id (int) const
virtual HitIdIter end_g4hit_id ()
virtual HitIdConstIter end_g4hit_id () const
virtual size_t remove_g4hit_id (int, PHG4HitDefs::keytype)
virtual size_t remove_g4hit_volume (int)
virtual void clear_g4hit_id ()
virtual const HitIdMap & g4hit_ids () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
unsigned int _truth_track_id = UINT_MAX
unsigned int _nmeas = 0
Additional Inherited Members
Public Types inherited from SvtxTrack
enum CAL_LAYER {
PRES = 0, CEMC = 1, HCALIN = 2, HCALOUT = 3,
OUTER_CEMC = 4, OUTER_HCALIN = 5, OUTER_HCALOUT = 6
}
typedef std::map< float,
SvtxTrackState * > StateMap
typedef StateMap::const_iterator ConstStateIter
typedef StateMap::iterator StateIter
typedef std::set< unsigned int > ClusterSet
typedef ClusterSet::const_iterator ConstClusterIter
typedef ClusterSet::iterator ClusterIter
typedef std::set
< TrkrDefs::cluskey > ClusterKeySet
typedef
ClusterKeySet::const_iterator ConstClusterKeyIter
typedef ClusterKeySet::iterator ClusterKeyIter
typedef std::map< int,
std::set< PHG4HitDefs::keytype > > HitIdMap
typedef HitIdMap::iterator HitIdIter
typedef HitIdMap::const_iterator HitIdConstIter
Protected Member Functions inherited from SvtxTrack
SvtxTrack ()
ClassDefOverride (SvtxTrack, 1)
Detailed Description
Definition at line 15 of file SvtxTrack_FastSim.h.
View newest version in sPHENIX GitHub at line 15 of file SvtxTrack_FastSim.h
Constructor & Destructor Documentation
SvtxTrack_FastSim::SvtxTrack_FastSim () default
Referenced by CloneMe(), and Reset().
SvtxTrack_FastSim::~SvtxTrack_FastSim () override default
SvtxTrack_FastSim::SvtxTrack_FastSim (const SvtxTrack & source)
Definition at line 16 of file SvtxTrack_FastSim.cc.
View newest version in sPHENIX GitHub at line 16 of file SvtxTrack_FastSim.cc
References CopyFrom().
Member Function Documentation
PHObject* SvtxTrack_FastSim::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from SvtxTrack.
Reimplemented in SvtxTrack_FastSim_v1.
Definition at line 38 of file SvtxTrack_FastSim.h.
View newest version in sPHENIX GitHub at line 38 of file SvtxTrack_FastSim.h
References SvtxTrack_FastSim().
void SvtxTrack_FastSim::CopyFrom (const SvtxTrack &) override virtual
copy content from base class
Reimplemented from SvtxTrack.
Reimplemented in SvtxTrack_FastSim_v1.
Definition at line 19 of file SvtxTrack_FastSim.cc.
View newest version in sPHENIX GitHub at line 19 of file SvtxTrack_FastSim.cc
References _nmeas, _truth_track_id, SvtxTrack_v1::CopyFrom(), SvtxTrack::get_num_measurements(), and SvtxTrack::get_truth_track_id().
Referenced by SvtxTrack_FastSim_v1::CopyFrom(), and SvtxTrack_FastSim().
void SvtxTrack_FastSim::CopyFrom (SvtxTrack *) inline override virtual
copy content from base class
Reimplemented from SvtxTrack.
Reimplemented in SvtxTrack_FastSim_v1.
Definition at line 31 of file SvtxTrack_FastSim.h.
View newest version in sPHENIX GitHub at line 31 of file SvtxTrack_FastSim.h
References CopyFrom().
Referenced by CopyFrom().
unsigned int SvtxTrack_FastSim::get_num_measurements () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 46 of file SvtxTrack_FastSim.h.
View newest version in sPHENIX GitHub at line 46 of file SvtxTrack_FastSim.h
References _nmeas.
unsigned int SvtxTrack_FastSim::get_truth_track_id () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 43 of file SvtxTrack_FastSim.h.
View newest version in sPHENIX GitHub at line 43 of file SvtxTrack_FastSim.h
References _truth_track_id.
Referenced by SvtxTrackEval::all_truth_particles(), PHG4TrackFastSimEval::fill_track_tree(), FastTrackingEval::fill_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), EventEvaluator::fillOutputNtuples(), identify(), and SvtxTrackEval::max_truth_particle_by_nclusters().
void SvtxTrack_FastSim::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxTrack.
Reimplemented in SvtxTrack_FastSim_v1.
Definition at line 31 of file SvtxTrack_FastSim.cc.
View newest version in sPHENIX GitHub at line 31 of file SvtxTrack_FastSim.cc
References SvtxTrack_v1::begin_clusters(), SvtxTrack_v1::empty_clusters(), SvtxTrack_v1::end_clusters(), SvtxTrack_v1::get_charge(), SvtxTrack_v1::get_chisq(), SvtxTrack_v1::get_id(), SvtxTrack_v1::get_ndf(), SvtxTrack_v1::get_px(), SvtxTrack_v1::get_py(), SvtxTrack_v1::get_pz(), get_truth_track_id(), SvtxTrack_v1::get_x(), SvtxTrack_v1::get_y(), SvtxTrack_v1::get_z(), and SvtxTrack_v1::identify().
Referenced by PHG4TrackFastSimEval::fill_track_tree(), and SvtxTrack_FastSim_v1::identify().
int SvtxTrack_FastSim::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxTrack.
Reimplemented in SvtxTrack_FastSim_v1.
Definition at line 65 of file SvtxTrack_FastSim.cc.
View newest version in sPHENIX GitHub at line 65 of file SvtxTrack_FastSim.cc
void SvtxTrack_FastSim::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SvtxTrack_FastSim_v1.
Definition at line 36 of file SvtxTrack_FastSim.h.
View newest version in sPHENIX GitHub at line 36 of file SvtxTrack_FastSim.h
References SvtxTrack_FastSim().
void SvtxTrack_FastSim::set_num_measurements (int nmeas) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 57 of file SvtxTrack_FastSim.h.
View newest version in sPHENIX GitHub at line 57 of file SvtxTrack_FastSim.h
References _nmeas.
void SvtxTrack_FastSim::set_truth_track_id (unsigned int truthTrackId) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 54 of file SvtxTrack_FastSim.h.
View newest version in sPHENIX GitHub at line 54 of file SvtxTrack_FastSim.h
References _truth_track_id.
Member Data Documentation
unsigned int SvtxTrack_FastSim::_nmeas = 0 private
Definition at line 64 of file SvtxTrack_FastSim.h.
View newest version in sPHENIX GitHub at line 64 of file SvtxTrack_FastSim.h
Referenced by CopyFrom(), get_num_measurements(), and set_num_measurements().
unsigned int SvtxTrack_FastSim::_truth_track_id = UINT_MAX private
Definition at line 63 of file SvtxTrack_FastSim.h.
View newest version in sPHENIX GitHub at line 63 of file SvtxTrack_FastSim.h
Referenced by CopyFrom(), get_truth_track_id(), and set_truth_track_id().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack_FastSim.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack_FastSim.cc