Analysis Software: truth_tracking_gsf Namespace Reference
truth_tracking_gsf Namespace Reference
Functions
def runTruthTrackingGsf
Variables
u acts.UnitConstants
tuple srcdir Path(__file__)
tuple field acts.ConstantBField(acts.Vector3(0, 0, 2 * u.T))
tuple inputParticlePath Path("particles.root")
trackingGeometry trackingGeometry,
digiConfigFile srcdir
tuple outputDir Path.cwd()
Function Documentation
def truth_tracking_gsf.runTruthTrackingGsf (trackingGeometry)
Definition at line 13 of file truth_tracking_gsf.py.
View newest version in sPHENIX GitHub at line 13 of file truth_tracking_gsf.py
References acts.examples.simulation.addDigitization(), acts.examples.simulation.addFatras(), acts.examples.simulation.addParticleGun(), acts.examples.reconstruction.addSeeding(), acts.examples.reconstruction.addTruthTrackingGsf(), acts.examples.simulation.EtaConfig, acts.examples.simulation.MomentumConfig, acts.examples.simulation.ParticleConfig, acts.examples.simulation.PhiConfig, str, and acts.examples.reconstruction.TruthSeedRanges.
Referenced by test_examples.test_truth_tracking_gsf().
Variable Documentation
truth_tracking_gsf.digiConfigFile srcdir
Definition at line 179 of file truth_tracking_gsf.py.
View newest version in sPHENIX GitHub at line 179 of file truth_tracking_gsf.py
truth_tracking_gsf.field acts.ConstantBField(acts.Vector3(0, 0, 2 * u.T))
Definition at line 170 of file truth_tracking_gsf.py.
View newest version in sPHENIX GitHub at line 170 of file truth_tracking_gsf.py
truth_tracking_gsf.inputParticlePath Path("particles.root")
Definition at line 172 of file truth_tracking_gsf.py.
View newest version in sPHENIX GitHub at line 172 of file truth_tracking_gsf.py
tuple truth_tracking_gsf.outputDir Path.cwd()
Definition at line 182 of file truth_tracking_gsf.py.
View newest version in sPHENIX GitHub at line 182 of file truth_tracking_gsf.py
tuple truth_tracking_gsf.srcdir Path(__file__)
Definition at line 166 of file truth_tracking_gsf.py.
View newest version in sPHENIX GitHub at line 166 of file truth_tracking_gsf.py
truth_tracking_gsf.trackingGeometry trackingGeometry,
Definition at line 177 of file truth_tracking_gsf.py.
View newest version in sPHENIX GitHub at line 177 of file truth_tracking_gsf.py
truth_tracking_gsf.u acts.UnitConstants
Definition at line 9 of file truth_tracking_gsf.py.
View newest version in sPHENIX GitHub at line 9 of file truth_tracking_gsf.py