Analysis Software: analysis/blob/master/A_N/sPHENIX_BUP20/han_BUP2020.C File Reference
han_BUP2020.C File Reference
#include <fstream>
#include <iostream>
#include "stdio.h"
#include <TChain.h>
#include <TFile.h>
#include <TGraphAsymmErrors.h>
#include <TGraphErrors.h>
#include <TLatex.h>
#include <TLegend.h>
#include <TLine.h>
#include <TMath.h>
#include <TROOT.h>
#include <TString.h>
#include <TTree.h>
#include <TVectorD.h>
#include <TVirtualFitter.h>
#include <cassert>
#include <cmath>
#include <vector>
#include "SaveCanvas.C"
#include "sPhenixStyle.C"
Functions
TGraphErrors * GraphShiftScaling (TGraphErrors *gr_src, const double x_shift, const double err_scaling)
void draw_phenix (float an)
void han_BUP2020 ()
Variables
const double pp_inelastic_crosssec = 42e-3
const double pp_rec_3year = 6.2e12
const double pp_rec_5year = pp_rec_3year + 80e12
const double pp_beam_pol = 0.57
Function Documentation
void draw_phenix (float an)
Definition at line 68 of file han_BUP2020.C.
View newest version in sPHENIX GitHub at line 68 of file han_BUP2020.C
References gr.
TGraphErrors* GraphShiftScaling (TGraphErrors * gr_src, const double x_shift, const double err_scaling)
Definition at line 31 of file han_BUP2020.C.
View newest version in sPHENIX GitHub at line 31 of file han_BUP2020.C
References assert, gr, i, vx, vy, and ambiguity_solver_full_chain::x.
Referenced by han_BUP2020(), makeV1_BUP2020(), and plot_sPHENIX_A_N_dp_BUP2020().
void han_BUP2020 ()
Definition at line 101 of file han_BUP2020.C.
View newest version in sPHENIX GitHub at line 101 of file han_BUP2020.C
References draw_phenix(), dy, f, GraphShiftScaling(), i, ambiguity_solver_full_chain::idx, leg, merge_hashes::p, pp_beam_pol, pp_rec_3year, SaveCanvas(), SetsPhenixStyle(), str, and tex.
Variable Documentation
const double pp_beam_pol = 0.57
Definition at line 29 of file han_BUP2020.C.
View newest version in sPHENIX GitHub at line 29 of file han_BUP2020.C
Referenced by han_BUP2020(), and plot_sPHENIX_A_N_dp_BUP2020().
const double pp_inelastic_crosssec = 42e-3
Definition at line 26 of file han_BUP2020.C.
View newest version in sPHENIX GitHub at line 26 of file han_BUP2020.C
Referenced by CrossSection2RAA(), CrossSection2RAA_Proposal(), CrossSection2v2(), CrossSection2zg(), makeLcD0_BUP2020(), and makeLcD0_BUP2022().
const double pp_rec_3year = 6.2e12
Definition at line 27 of file han_BUP2020.C.
View newest version in sPHENIX GitHub at line 27 of file han_BUP2020.C
Referenced by han_BUP2020(), makeLcD0_BUP2020(), makeLcD0_BUP2022(), and plot_sPHENIX_A_N_dp_BUP2020().
const double pp_rec_5year = pp_rec_3year + 80e12
Definition at line 28 of file han_BUP2020.C.
View newest version in sPHENIX GitHub at line 28 of file han_BUP2020.C