Analysis Software: coresoftware/blob/master/offline/packages/tpc/TpcClusterizer.cc File Reference
TpcClusterizer.cc File Reference
#include "TpcClusterizer.h"
#include "TpcDefs.h"
#include <trackbase/TrkrClusterContainerv3.h>
#include <trackbase/TrkrClusterv2.h>
#include <trackbase/TrkrClusterHitAssocv3.h>
#include <trackbase/TrkrDefs.h>
#include <trackbase/TrkrHitv2.h>
#include <trackbase/TrkrHitSet.h>
#include <trackbase/TrkrHitSetContainer.h>
#include <fun4all/Fun4AllReturnCodes.h>
#include <fun4all/SubsysReco.h>
#include <g4detectors/PHG4CylinderCellGeom.h>
#include <g4detectors/PHG4CylinderCellGeomContainer.h>
#include <Acts/Utilities/Units.hpp>
#include <Acts/Surfaces/Surface.hpp>
#include <phool/PHCompositeNode.h>
#include <phool/PHIODataNode.h>
#include <phool/PHNode.h>
#include <phool/PHNodeIterator.h>
#include <phool/PHObject.h>
#include <phool/getClass.h>
#include <phool/phool.h>
#include <TMatrixFfwd.h>
#include <TMatrixT.h>
#include <TMatrixTUtils.h>
#include <TFile.h>
#include <cmath>
#include <iostream>
#include <map>
#include <string>
#include <utility>
#include <array>
#include <vector>
#include <pthread.h>
Classes
struct thread_data
Typedefs
typedef std::pair< unsigned
short, unsigned short > iphiz
typedef std::pair< unsigned
short, iphiz > ihit
Functions
void remove_hit (double adc, int phibin, int zbin, std::multimap< unsigned short, ihit > &all_hit_map, std::vector< std::vector< unsigned short >> &adcval)
void remove_hits (std::vector< ihit > &ihit_list, std::multimap< unsigned short, ihit > &all_hit_map, std::vector< std::vector< unsigned short >> &adcval)
void find_z_range (int phibin, int zbin, int NZBinsMax, std::vector< std::vector< unsigned short >> &adcval, int &zdown, int &zup)
void find_phi_range (int phibin, int zbin, int NPhiBinsMax, std::vector< std::vector< unsigned short >> &adcval, int &phidown, int &phiup)
void get_cluster (int phibin, int zbin, int NPhiBinsMax, int NZBinsMax, std::vector< std::vector< unsigned short >> &adcval, std::vector< ihit > &ihit_list)
Surface get_tpc_surface_from_coords (TrkrDefs::hitsetkey hitsetkey, Acts::Vector3D world, ActsSurfaceMaps *surfMaps, ActsTrackingGeometry *tGeometry, TrkrDefs::subsurfkey &subsurfkey)
void calc_cluster_parameter (std::vector< ihit > &ihit_list, int iclus, PHG4CylinderCellGeom *layergeom, TrkrHitSet *hitset, unsigned short phioffset, unsigned short zoffset, std::pair< double, double > par0_neg, std::pair< double, double > par0_pos, std::pair< double, double > par1_neg, std::pair< double, double > par1_pos, std::map< TrkrDefs::cluskey, TrkrCluster * > *clusterlist, std::multimap< TrkrDefs::cluskey, TrkrDefs::hitkey > *clusterhitassoc, bool do_assoc, ActsTrackingGeometry *tGeometry, ActsSurfaceMaps *surfMaps)
void * ProcessSector (void *threadarg)
Variables
pthread_mutex_t mythreadlock
Typedef Documentation
typedef std::pair<unsigned short, iphiz> ihit
Definition at line 52 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 52 of file TpcClusterizer.cc
typedef std::pair<unsigned short, unsigned short> iphiz
Definition at line 51 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 51 of file TpcClusterizer.cc
Function Documentation
void calc_cluster_parameter (std::vector< ihit > & ihit_list, int iclus, PHG4CylinderCellGeom * layergeom, TrkrHitSet * hitset, unsigned short phioffset, unsigned short zoffset, std::pair< double, double > par0_neg, std::pair< double, double > par0_pos, std::pair< double, double > par1_neg, std::pair< double, double > par1_pos, std::map< TrkrDefs::cluskey, TrkrCluster * > * clusterlist, std::multimap< TrkrDefs::cluskey, TrkrDefs::hitkey > * clusterhitassoc, bool do_assoc, ActsTrackingGeometry * tGeometry, ActsSurfaceMaps * surfMaps)
Get the surface key to find the surface from the map
If the surface can't be found, we can't track with it. So just return and don't add the cluster to the container
no conversion needed, only used in acts
Prefer Acts transformation since we build the TPC surfaces manually
otherwise take the manual calculation
Definition at line 278 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 278 of file TpcClusterizer.cc
References Acts::UnitConstants::cm, double(), Jetscape::ERR, TpcDefs::genClusKey(), TpcDefs::genHitKey(), TpcDefs::genHitSetKey(), ActsTrackingGeometry::geoContext, PHG4CylinderCellGeom::get_phicenter(), PHG4CylinderCellGeom::get_phistep(), PHG4CylinderCellGeom::get_radius(), get_tpc_surface_from_coords(), PHG4CylinderCellGeom::get_zcenter(), PHG4CylinderCellGeom::get_zstep(), TrkrHitSet::getHitSetKey(), TrkrDefs::getLayer(), TpcDefs::getSectorId(), TpcDefs::getSide(), i, layer, square(), and z.
Referenced by ProcessSector().
void find_phi_range (int phibin, int zbin, int NPhiBinsMax, std::vector< std::vector< unsigned short >> & adcval, int & phidown, int & phiup)
Definition at line 150 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 150 of file TpcClusterizer.cc
Referenced by get_cluster().
void find_z_range (int phibin, int zbin, int NZBinsMax, std::vector< std::vector< unsigned short >> & adcval, int & zdown, int & zup)
Definition at line 103 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 103 of file TpcClusterizer.cc
Referenced by get_cluster().
void get_cluster (int phibin, int zbin, int NPhiBinsMax, int NZBinsMax, std::vector< std::vector< unsigned short >> & adcval, std::vector< ihit > & ihit_list)
Definition at line 201 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 201 of file TpcClusterizer.cc
References find_phi_range(), and find_z_range().
Referenced by ProcessSector().
Surface get_tpc_surface_from_coords (TrkrDefs::hitsetkey hitsetkey, Acts::Vector3D world, ActsSurfaceMaps * surfMaps, ActsTrackingGeometry * tGeometry, TrkrDefs::subsurfkey & subsurfkey)
Definition at line 221 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 221 of file TpcClusterizer.cc
References ActsTrackingGeometry::geoContext, i, PHWHERE, ActsSurfaceMaps::tpcSurfaceMap, ActsTrackingGeometry::tpcSurfStepPhi, and ActsTrackingGeometry::tpcSurfStepZ.
Referenced by calc_cluster_parameter().
void* ProcessSector (void * threadarg)
Definition at line 526 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 526 of file TpcClusterizer.cc
References calc_cluster_parameter(), thread_data::clusterhitassoc, thread_data::clusterlist, thread_data::do_assoc, get_cluster(), TrkrHitSet::getHits(), TpcDefs::getPad(), TpcDefs::getTBin(), thread_data::hitset, thread_data::layergeom, thread_data::par0_neg, thread_data::par0_pos, thread_data::par1_neg, thread_data::par1_pos, thread_data::pedestal, pedestal(), MATSCAN::phibins, thread_data::phibins, thread_data::phioffset, remove_hits(), thread_data::surfmaps, thread_data::tGeometry, Acts::Test::tGeometry, thread_data::zbins, and thread_data::zoffset.
Referenced by TpcClusterizer::process_event().
void remove_hit (double adc, int phibin, int zbin, std::multimap< unsigned short, ihit > & all_hit_map, std::vector< std::vector< unsigned short >> & adcval)
Definition at line 79 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 79 of file TpcClusterizer.cc
References it.
Referenced by remove_hits().
void remove_hits (std::vector< ihit > & ihit_list, std::multimap< unsigned short, ihit > & all_hit_map, std::vector< std::vector< unsigned short >> & adcval)
Definition at line 93 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 93 of file TpcClusterizer.cc
References remove_hit().
Referenced by HelixHough::findHelices(), HelixHough::findHelicesByPairs(), HelixHough::findSeededHelices(), and ProcessSector().
Variable Documentation
pthread_mutex_t mythreadlock
Definition at line 77 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 77 of file TpcClusterizer.cc
Referenced by TpcClusterizer::process_event().