Analysis Software: macros/blob/master/calibrations/calo/tower_slope_macro/G4_CEmc_Spacal.C File Reference
G4_CEmc_Spacal.C File Reference
#include <GlobalVariables.C>
#include <QA.C>
#include <g4detectors/PHG4CylinderCellReco.h>
#include <g4detectors/PHG4CylinderGeom_Spacalv1.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4detectors/PHG4FullProjSpacalCellReco.h>
#include <g4detectors/PHG4SpacalSubsystem.h>
#include <g4calo/RawTowerBuilder.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4Utils.h>
#include <caloreco/RawClusterBuilderGraph.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawClusterPositionCorrection.h>
#include <caloreco/RawTowerCalibration.h>
#include <qa_modules/QAG4SimulationCalorimeter.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4CEMC
Macros
#define MACRO_G4CEMCSPACAL_C
Enumerations
enum G4CEMC::enu_Cemc_clusterizer {
G4CEMC::kCemcGraphClusterizer, G4CEMC::kCemcTemplateClusterizer, G4CEMC::kCemcGraphClusterizer, G4CEMC::kCemcTemplateClusterizer,
G4CEMC::kCemcGraphClusterizer, G4CEMC::kCemcTemplateClusterizer, G4CEMC::kCemcGraphClusterizer, G4CEMC::kCemcTemplateClusterizer
}
Functions
double CEmc_1DProjectiveSpacal (PHG4Reco *g4Reco, double radius, const int crossings)
EMCal setup macro - 1D azimuthal projective SPACAL.
double CEmc_2DProjectiveSpacal (PHG4Reco *g4Reco, double radius, const int crossings)
2D full projective SPACAL
void CEmcInit (const int i=0)
double CEmc (PHG4Reco *g4Reco, double radius, const int crossings)
EMCal main setup macro.
void CEMC_Cells ()
void CEMC_Towers ()
void CEMC_Clusters ()
void CEMC_Eval (const std::string &outputfile)
void CEMC_QA ()
Macro Definition Documentation
#define MACRO_G4CEMCSPACAL_C
Definition at line 2 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 2 of file G4_CEmc_Spacal.C
Function Documentation
double CEmc (PHG4Reco * g4Reco, double radius, const int crossings)
EMCal main setup macro.
Definition at line 97 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 97 of file G4_CEmc_Spacal.C
References CEmc_1DProjectiveSpacal(), CEmc_2DProjectiveSpacal(), G4CEMC::Cemc_spacal_configuration, PHG4CylinderGeom_Spacalv1::k1DProjectiveSpacal, and PHG4CylinderGeom_Spacalv1::k2DProjectiveSpacal.
double CEmc_1DProjectiveSpacal (PHG4Reco * g4Reco, double radius, const int crossings)
EMCal setup macro - 1D azimuthal projective SPACAL.
double CEmc_2DProjectiveSpacal (PHG4Reco * g4Reco, double radius, const int crossings)
2D full projective SPACAL
void CEMC_Cells ()
Definition at line 286 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 286 of file G4_CEmc_Spacal.C
References PHG4CylinderCellReco::cellsize(), G4CEMC::Cemc_spacal_configuration, Enable::CEMC_VERBOSITY, PHG4CylinderCellReco::Detector(), PHG4FullProjSpacalCellReco::Detector(), PHG4FullProjSpacalCellReco::get_light_collection_model(), i, Fun4AllServer::instance(), PHG4CylinderGeom_Spacalv1::k1DProjectiveSpacal, PHG4CylinderGeom_Spacalv1::k2DProjectiveSpacal, LightCollectionModel::load_data_file(), G4CEMC::Max_cemc_layer, G4CEMC::Min_cemc_layer, Fun4AllServer::registerSubsystem(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void CEMC_Clusters ()
Definition at line 518 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 518 of file G4_CEmc_Spacal.C
References G4CEMC::Cemc_clusterizer, Enable::CEMC_VERBOSITY, RawClusterBuilderGraph::Detector(), RawClusterBuilderTemplate::Detector(), Fun4AllServer::instance(), G4CEMC::kCemcGraphClusterizer, G4CEMC::kCemcTemplateClusterizer, RawClusterBuilderTemplate::LoadProfile(), Fun4AllServer::registerSubsystem(), RawClusterBuilderTemplate::set_threshold_energy(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void CEMC_Eval (const std::string & outputfile)
Definition at line 563 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 563 of file G4_CEmc_Spacal.C
References Enable::CEMC_VERBOSITY, Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void CEMC_QA ()
Definition at line 576 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 576 of file G4_CEmc_Spacal.C
References Enable::CEMC_VERBOSITY, Fun4AllServer::instance(), Enable::QA_VERBOSITY, Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
void CEMC_Towers ()
Definition at line 326 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 326 of file G4_CEmc_Spacal.C
References G4CEMC::Cemc_spacal_configuration, Enable::CEMC_VERBOSITY, RawTowerBuilder::Detector(), RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), Acts::UnitConstants::e, RawTowerCalibration::GetCalibrationParameters(), RawTowerDigitizer::GetParameters(), Fun4AllServer::instance(), PHG4CylinderGeom_Spacalv1::k1DProjectiveSpacal, PHG4CylinderGeom_Spacalv1::k2DProjectiveSpacal, RawTowerCalibration::kDbfile_tbt_gain_corr, RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, RawTowerCalibration::kTower_by_tower_calibration, PHParameters::ReadFromFile(), Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerCalibration::set_CalibrationFileName(), RawTowerDigitizer::set_digi_algorithm(), RawTowerDigitizer::set_DoTowerDecal(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), RawTowerBuilder::set_sim_tower_node_prefix(), RawTowerCalibration::set_UseConditionsDB(), RawTowerDigitizer::set_UseConditionsDB(), RawTowerCalibration::set_variable_GeV_ADC(), RawTowerCalibration::set_variable_pedestal(), RawTowerDigitizer::set_variable_pedestal(), RawTowerDigitizer::set_variable_zero_suppression(), G4CEMC::TowerDigi, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void CEmcInit (const int i = 0)
Definition at line 91 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 91 of file G4_CEmc_Spacal.C