Analysis Software: Acts::SurfaceStub Class Reference
Acts::SurfaceStub Class Reference
Surface derived class stub.
#include <acts/blob/sPHENIX/Tests/UnitTests/Core/Surfaces/SurfaceStub.hpp>
Public Member Functions
SurfaceStub (const Transform3 &htrans=Transform3::Identity())
SurfaceStub (const GeometryContext &gctx, const SurfaceStub &sf, const Transform3 &transf)
SurfaceStub (const DetectorElementBase &detelement)
~SurfaceStub () override=default
SurfaceType type () const final
Return method for the Surface type to avoid dynamic casts.
Vector3 normal (const GeometryContext &gctx, const Vector2 &) const final
Return method for the normal vector of the surface.
Vector3 normal (const GeometryContext &gctx, const Vector3 &) const final
Vector3 normal (const GeometryContext &) const final
const SurfaceBounds & bounds () const final
Return method for SurfaceBounds.
Vector3 localToGlobal (const GeometryContext &, const Vector2 &, const Vector3 &) const final
Local to global transformation.
Result< Vector2 > globalToLocal (const GeometryContext &, const Vector3 &, const Vector3 &, double) const final
Global to local transformation.
double pathCorrection (const GeometryContext &, const Vector3 &, const Vector3 &) const final
Calculation of the path correction for incident.
Vector3 binningPosition (const GeometryContext &, BinningValue) const final
Inherited from GeometryObject base.
SurfaceMultiIntersection intersect (const GeometryContext &, const Vector3 &, const Vector3 &, const BoundaryCheck &, const ActsScalar) const final
Surface intersction.
std::string name () const final
Return properly formatted class name.
bool constructedOk () const
Simply return true to check a method can be called on a constructed object.
Polyhedron polyhedronRepresentation (const GeometryContext &, size_t) const final
Return a Polyhedron for the surfaces.
ActsMatrix< 2, 3 > localCartesianToBoundLocalDerivative (const GeometryContext &, const Vector3 &) const final
Public Member Functions inherited from Acts::Surface
virtual ~Surface ()
std::shared_ptr< Surface > getSharedPtr ()
std::shared_ptr< const Surface > getSharedPtr () const
Surface & operator= (const Surface &other)
virtual bool operator== (const Surface &other) const
virtual bool operator!= (const Surface &sf) const
virtual const Transform3 & transform (const GeometryContext &gctx) const
virtual Vector3 center (const GeometryContext &gctx) const
const DetectorElementBase * associatedDetectorElement () const
const Layer * associatedLayer () const
void associateLayer (const Layer &lay)
const ISurfaceMaterial * surfaceMaterial () const
const std::shared_ptr< const
ISurfaceMaterial > & surfaceMaterialSharedPtr () const
void assignDetectorElement (const DetectorElementBase &detelement)
void assignSurfaceMaterial (std::shared_ptr< const ISurfaceMaterial > material)
bool isOnSurface (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction, const BoundaryCheck &bcheck=true) const
virtual bool insideBounds (const Vector2 &lposition, const BoundaryCheck &bcheck=true) const
virtual Acts::RotationMatrix3 referenceFrame (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction) const
virtual BoundToFreeMatrix boundToFreeJacobian (const GeometryContext &gctx, const BoundVector &boundParams) const
virtual FreeToBoundMatrix freeToBoundJacobian (const GeometryContext &gctx, const FreeVector &parameters) const
virtual FreeToPathMatrix freeToPathDerivative (const GeometryContext &gctx, const FreeVector &parameters) const
virtual std::ostream & toStream (const GeometryContext &gctx, std::ostream &sl) const
std::string toString (const GeometryContext &gctx) const
AlignmentToBoundMatrix alignmentToBoundDerivative (const GeometryContext &gctx, const FreeVector &parameters, const FreeVector &pathDerivative) const
virtual AlignmentToPathMatrix alignmentToPathDerivative (const GeometryContext &gctx, const FreeVector &parameters) const
Public Member Functions inherited from Acts::GeometryObject
GeometryObject ()=default
Defaulted constructor.
GeometryObject (const GeometryObject &)=default
Defaulted copy constructor.
GeometryObject (const GeometryIdentifier &geometryId)
GeometryObject & operator= (const GeometryObject &geometryId)
const GeometryIdentifier & geometryId () const
virtual double binningPositionValue (const GeometryContext &gctx, BinningValue bValue) const
void assignGeometryId (const GeometryIdentifier &geometryId)
Private Attributes
std::shared_ptr< const
PlanarBounds > m_bounds
the bounds of this surface
Additional Inherited Members
Public Types inherited from Acts::Surface
enum SurfaceType {
Cone = 0, Cylinder = 1, Disc = 2, Perigee = 3,
Plane = 4, Straw = 5, Curvilinear = 6, Other = 7
}
Static Public Member Functions inherited from Acts::Surface
template<class T , typename... Args>
static std::shared_ptr< T > makeShared (Args &&...args)
Static Public Attributes inherited from Acts::Surface
static std::array< std::string,
SurfaceType::Other > s_surfaceTypeNames
Helper strings for screen output.
Protected Member Functions inherited from Acts::Surface
Surface (const Transform3 &transform=Transform3::Identity())
Surface (const Surface &other)
Surface (const DetectorElementBase &detelement)
Surface (const GeometryContext &gctx, const Surface &other, const Transform3 &shift)
Protected Attributes inherited from Acts::Surface
Transform3 m_transform = Transform3::Identity()
const DetectorElementBase * m_associatedDetElement {nullptr}
Pointer to the a DetectorElementBase.
const Layer * m_associatedLayer {nullptr}
const TrackingVolume * m_associatedTrackingVolume {nullptr}
std::shared_ptr< const
ISurfaceMaterial > m_surfaceMaterial
Possibility to attach a material description.
Detailed Description
Surface derived class stub.
Definition at line 20 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 20 of file SurfaceStub.hpp
Constructor & Destructor Documentation
Acts::SurfaceStub::SurfaceStub (const Transform3 & htrans = Transform3::Identity()) inline
Definition at line 22 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 22 of file SurfaceStub.hpp
Acts::SurfaceStub::SurfaceStub (const GeometryContext & gctx, const SurfaceStub & sf, const Transform3 & transf) inline
Definition at line 24 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 24 of file SurfaceStub.hpp
Acts::SurfaceStub::SurfaceStub (const DetectorElementBase & detelement) inline
Definition at line 27 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 27 of file SurfaceStub.hpp
Acts::SurfaceStub::~SurfaceStub () override default
Member Function Documentation
Vector3 Acts::SurfaceStub::binningPosition (const GeometryContext & , BinningValue) const inline final virtual
Inherited from GeometryObject base.
Implements Acts::GeometryObject.
Definition at line 77 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 77 of file SurfaceStub.hpp
References testSigmaEff::v.
const SurfaceBounds& Acts::SurfaceStub::bounds () const inline final virtual
Return method for SurfaceBounds.
Implements Acts::Surface.
Definition at line 51 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 51 of file SurfaceStub.hpp
References Acts::s_noBounds.
bool Acts::SurfaceStub::constructedOk () const inline
Simply return true to check a method can be called on a constructed object.
Definition at line 98 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 98 of file SurfaceStub.hpp
Result<Vector2> Acts::SurfaceStub::globalToLocal (const GeometryContext & , const Vector3 & , const Vector3 & , double) const inline final virtual
Global to local transformation.
Implements Acts::Surface.
Definition at line 63 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 63 of file SurfaceStub.hpp
SurfaceMultiIntersection Acts::SurfaceStub::intersect (const GeometryContext & , const Vector3 & , const Vector3 & , const BoundaryCheck & , const ActsScalar) const inline final virtual
Surface intersction.
Implements Acts::Surface.
Definition at line 84 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 84 of file SurfaceStub.hpp
References Acts::Intersection< 3 >::invalid().
ActsMatrix<2, 3> Acts::SurfaceStub::localCartesianToBoundLocalDerivative (const GeometryContext & gctx, const Vector3 & position) const inline final virtual
Calculate the derivative of bound track parameters local position w.r.t. position in local 3D Cartesian coordinates
Parameters
gctx The current geometry context object, e.g. alignment
position The position of the parameters in global
Returns
Derivative of bound local position w.r.t. position in local 3D cartesian coordinates
Implements Acts::Surface.
Definition at line 111 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 111 of file SurfaceStub.hpp
Vector3 Acts::SurfaceStub::localToGlobal (const GeometryContext & , const Vector2 & , const Vector3 &) const inline final virtual
Local to global transformation.
Implements Acts::Surface.
Definition at line 56 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 56 of file SurfaceStub.hpp
std::string Acts::SurfaceStub::name () const inline final virtual
Return properly formatted class name.
Implements Acts::Surface.
Definition at line 95 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 95 of file SurfaceStub.hpp
Vector3 Acts::SurfaceStub::normal (const GeometryContext & gctx, const Vector2 &) const inline final virtual
Return method for the normal vector of the surface.
Implements Acts::Surface.
Definition at line 36 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 36 of file SurfaceStub.hpp
Referenced by normal().
Vector3 Acts::SurfaceStub::normal (const GeometryContext & gctx, const Vector3 & position) const inline final virtual
Return method for the normal vector of the surface The normal vector can only be generally defined at a given local position It requires a local position to be given (in general)
Parameters
position is the global position where the normal vector is constructed
gctx The current geometry context object, e.g. alignment
Returns
normal vector by value
Reimplemented from Acts::Surface.
Definition at line 41 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 41 of file SurfaceStub.hpp
References normal().
Vector3 Acts::SurfaceStub::normal (const GeometryContext & gctx) const inline final virtual
Return method for the normal vector of the surface
It will return a normal vector at the center() position
Parameters
gctx The current geometry context object, e.g. alignment
Returns
normal vector by value
Reimplemented from Acts::Surface.
Definition at line 46 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 46 of file SurfaceStub.hpp
double Acts::SurfaceStub::pathCorrection (const GeometryContext & , const Vector3 & , const Vector3 &) const inline final virtual
Calculation of the path correction for incident.
Implements Acts::Surface.
Definition at line 71 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 71 of file SurfaceStub.hpp
Polyhedron Acts::SurfaceStub::polyhedronRepresentation (const GeometryContext & , size_t) const inline final virtual
Return a Polyhedron for the surfaces.
Implements Acts::Surface.
Definition at line 101 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 101 of file SurfaceStub.hpp
References ActsExamples::HepMC3Event::vertices().
SurfaceType Acts::SurfaceStub::type () const inline final virtual
Return method for the Surface type to avoid dynamic casts.
Implements Acts::Surface.
Definition at line 33 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 33 of file SurfaceStub.hpp
References Acts::Surface::Other.
Member Data Documentation
std::shared_ptr<const PlanarBounds> Acts::SurfaceStub::m_bounds private
the bounds of this surface
Definition at line 115 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 115 of file SurfaceStub.hpp
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Tests/UnitTests/Core/Surfaces/SurfaceStub.hpp