Analysis Software: ActsExamples::MeasurementCalibratorAdapter Class Reference
ActsExamples::MeasurementCalibratorAdapter Class Reference
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/EventData/MeasurementCalibration.hpp>
Public Member Functions
MeasurementCalibratorAdapter (const MeasurementCalibrator &calibrator, const MeasurementContainer &measurements, const ClusterContainer *clusters=nullptr)
MeasurementCalibratorAdapter ()=delete
void calibrate (const Acts::GeometryContext &gctx, const Acts::CalibrationContext &cctx, const Acts::SourceLink &sourceLink, Acts::VectorMultiTrajectory::TrackStateProxy trackState) const
Private Attributes
const MeasurementCalibrator & m_calibrator
const MeasurementContainer & m_measurements
const ClusterContainer * m_clusters
Detailed Description
Definition at line 58 of file MeasurementCalibration.hpp.
View newest version in sPHENIX GitHub at line 58 of file MeasurementCalibration.hpp
Constructor & Destructor Documentation
ActsExamples::MeasurementCalibratorAdapter::MeasurementCalibratorAdapter (const MeasurementCalibrator & calibrator, const MeasurementContainer & measurements, const ClusterContainer * clusters = nullptr)
Definition at line 41 of file MeasurementCalibration.cpp.
View newest version in sPHENIX GitHub at line 41 of file MeasurementCalibration.cpp
ActsExamples::MeasurementCalibratorAdapter::MeasurementCalibratorAdapter () delete
Member Function Documentation
void ActsExamples::MeasurementCalibratorAdapter::calibrate (const Acts::GeometryContext & gctx, const Acts::CalibrationContext & cctx, const Acts::SourceLink & sourceLink, Acts::VectorMultiTrajectory::TrackStateProxy trackState) const
Referenced by ActsExamples::TrackFindingFromPrototrackAlgorithm::execute(), ActsExamples::AlignmentAlgorithm::execute(), and ActsExamples::TrackFindingAlgorithm::execute().
Member Data Documentation
const MeasurementCalibrator& ActsExamples::MeasurementCalibratorAdapter::m_calibrator private
Definition at line 72 of file MeasurementCalibration.hpp.
View newest version in sPHENIX GitHub at line 72 of file MeasurementCalibration.hpp
const ClusterContainer* ActsExamples::MeasurementCalibratorAdapter::m_clusters private
Definition at line 74 of file MeasurementCalibration.hpp.
View newest version in sPHENIX GitHub at line 74 of file MeasurementCalibration.hpp
const MeasurementContainer& ActsExamples::MeasurementCalibratorAdapter::m_measurements private
Definition at line 73 of file MeasurementCalibration.hpp.
View newest version in sPHENIX GitHub at line 73 of file MeasurementCalibration.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/EventData/MeasurementCalibration.hpp
acts/blob/sPHENIX/Examples/Framework/src/EventData/MeasurementCalibration.cpp