Analysis Software: Acts::VolumeBounds Class Reference
Acts::VolumeBounds Class Reference abstract
#include <acts/blob/sPHENIX/Core/include/Acts/Geometry/VolumeBounds.hpp>
Public Types
enum BoundsType : int {
eCone = 0, eCuboid = 1, eCutoutCylinder = 2, eCylinder = 3,
eGenericCuboid = 4, eTrapezoid = 5, eOther = 6
}
Public Member Functions
VolumeBounds ()=default
virtual ~VolumeBounds ()=default
virtual BoundsType type () const =0
virtual std::vector< double > values () const =0
virtual bool inside (const Vector3 &gpos, double tol=0.) const =0
virtual OrientedSurfaces orientedSurfaces (const Transform3 &transform=Transform3::Identity()) const =0
virtual Volume::BoundingBox boundingBox (const Transform3 *trf=nullptr, const Vector3 &envelope={0, 0, 0}, const Volume *entity=nullptr) const =0
virtual Vector3 binningOffset (BinningValue bValue) const
Binning offset - overloaded for some R-binning types.
virtual double binningBorder (BinningValue bValue) const
virtual std::ostream & toStream (std::ostream &sl) const =0
Detailed Description
Pure Absract Base Class for Volume bounds.
Acts::VolumeBounds are a set of up to six confining Surfaces that are stored in a std::vector. Each type of Acts::VolumeBounds has to implement a orientedSurfaces() and a inside() method.
The Volume, retrieving a set of Surfaces from the VolumeBounds, can turn the Surfaces into BoundarySurfaces.
Definition at line 54 of file VolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 54 of file VolumeBounds.hpp
Member Enumeration Documentation
enum Acts::VolumeBounds::BoundsType : int
This is nested to the VolumeBounds, as also SurfaceBounds will have Bounds Type.
Enumerator:
eCone
eCuboid
eCutoutCylinder
eCylinder
eGenericCuboid
eTrapezoid
eOther
Definition at line 59 of file VolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 59 of file VolumeBounds.hpp
Constructor & Destructor Documentation
Acts::VolumeBounds::VolumeBounds () default
virtual Acts::VolumeBounds::~VolumeBounds () virtual default
Member Function Documentation
double Acts::VolumeBounds::binningBorder (BinningValue bValue) const inline virtual
Binning borders in double
Parameters
bValue is the binning schema used
Returns
float offset to be used for the binning
Reimplemented in Acts::CylinderVolumeBounds, and Acts::CuboidVolumeBounds.
Definition at line 140 of file VolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 140 of file VolumeBounds.hpp
Referenced by Acts::CylinderVolumeBounds::binningBorder().
Vector3 Acts::VolumeBounds::binningOffset (BinningValue bValue) const inline virtual
Binning offset - overloaded for some R-binning types.
Binning offset - overloaded for some R-binning types
Parameters
bValue is the binning schema used
Returns
vector 3D to be used for the binning
Reimplemented in Acts::CylinderVolumeBounds.
Definition at line 135 of file VolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 135 of file VolumeBounds.hpp
Referenced by Acts::CylinderVolumeBounds::binningOffset().
virtual Volume::BoundingBox Acts::VolumeBounds::boundingBox (const Transform3 * trf = nullptr, const Vector3 & envelope = {0, 0, 0}, const Volume * entity = nullptr) const pure virtual
Construct bounding box for this shape
Parameters
trf Optional transform
envelope Optional envelope to add / subtract from min/max
entity Entity to associate this bounding box with
Returns
Constructed bounding box
Implemented in Acts::CylinderVolumeBounds, Acts::TrapezoidVolumeBounds, Acts::ConeVolumeBounds, Acts::CuboidVolumeBounds, Acts::CutoutCylinderVolumeBounds, and Acts::GenericCuboidVolumeBounds.
virtual bool Acts::VolumeBounds::inside (const Vector3 & gpos, double tol = 0.) const pure virtual
Checking if position given in volume frame is inside
Parameters
gpos is the global position to be checked
tol is the tolerance applied for the inside check
Returns
boolean indicating if the position is inside
Implemented in Acts::CylinderVolumeBounds, Acts::TrapezoidVolumeBounds, Acts::ConeVolumeBounds, Acts::CuboidVolumeBounds, Acts::CutoutCylinderVolumeBounds, and Acts::GenericCuboidVolumeBounds.
virtual OrientedSurfaces Acts::VolumeBounds::orientedSurfaces (const Transform3 & transform = Transform3::Identity()) const pure virtual
Oriented surfaces, i.e. the decomposed boundary surfaces and the according navigation direction into the volume given the normal vector on the surface
Parameters
transform is the 3D transform to be applied to the boundary surfaces to position them in 3D space
It will throw an exception if the orientation prescription is not adequate
Returns
a vector of surfaces bounding this volume
Implemented in Acts::CylinderVolumeBounds, Acts::TrapezoidVolumeBounds, Acts::ConeVolumeBounds, Acts::CuboidVolumeBounds, Acts::CutoutCylinderVolumeBounds, and Acts::GenericCuboidVolumeBounds.
Referenced by Acts::AbstractVolume::createBoundarySurfaces(), Acts::TrackingVolume::createBoundarySurfaces(), and Acts::DetectorVolumeJsonConverter::toJsonDetray().
virtual std::ostream& Acts::VolumeBounds::toStream (std::ostream & sl) const pure virtual
Output Method for std::ostream, to be overloaded by child classes
Parameters
sl is the output stream to be dumped into
Implemented in Acts::CylinderVolumeBounds, Acts::ConeVolumeBounds, Acts::CuboidVolumeBounds, Acts::TrapezoidVolumeBounds, Acts::CutoutCylinderVolumeBounds, and Acts::GenericCuboidVolumeBounds.
Referenced by Acts::operator<<().
virtual BoundsType Acts::VolumeBounds::type () const pure virtual
Return the bounds type - for persistency optimization
Returns
is a BoundsType enum
Implemented in Acts::CylinderVolumeBounds, Acts::TrapezoidVolumeBounds, Acts::ConeVolumeBounds, Acts::CuboidVolumeBounds, Acts::CutoutCylinderVolumeBounds, and Acts::GenericCuboidVolumeBounds.
Referenced by Acts::Svg::DetectorVolumeConverter::convert(), Acts::operator==(), Acts::to_json(), and Acts::DetectorVolumeJsonConverter::toJsonDetray().
virtual std::vector<double> Acts::VolumeBounds::values () const pure virtual
Access method for bound values, this is a dynamically sized vector containing the parameters needed to describe these bounds
Returns
of the stored values for this SurfaceBounds object
Implemented in Acts::CylinderVolumeBounds, Acts::TrapezoidVolumeBounds, Acts::ConeVolumeBounds, Acts::CuboidVolumeBounds, Acts::CutoutCylinderVolumeBounds, and Acts::GenericCuboidVolumeBounds.
Referenced by Acts::Svg::DetectorVolumeConverter::convert(), Acts::operator==(), and Acts::to_json().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Geometry/VolumeBounds.hpp