Analysis Software: Acts::IVisualization3D Class Reference
Acts::IVisualization3D Class Reference abstract
#include <acts/blob/sPHENIX/Core/include/Acts/Visualization/IVisualization3D.hpp>
Public Types
using FaceType = std::vector< size_t >
Public Member Functions
virtual void vertex (const Vector3D &vtx, ColorRGB color={120, 120, 120})=0
virtual void face (const std::vector< Vector3D > &vtxs, ColorRGB color={120, 120, 120})=0
virtual void faces (const std::vector< Vector3D > &vtxs, const std::vector< FaceType > &faces, ColorRGB color={120, 120, 120})=0
virtual void line (const Vector3D &a, const Vector3D &b, ColorRGB color={120, 120, 120})=0
virtual void write (std::ostream &os) const =0
virtual void write (const std::string &path) const =0
virtual void clear ()=0
void vertex (const Vector3F &vtx, ColorRGB color={120, 120, 120})
void face (const std::vector< Vector3F > &vtxs, ColorRGB color={120, 120, 120})
void line (const Vector3F &a, const Vector3F &b, ColorRGB color={120, 120, 120})
(const Vector3F&, const Vector3F&,
Protected Member Functions
bool hasExtension (const std::string &path) const
void replaceExtension (std::string &path, const std::string &suffix) const
Detailed Description
Partially abstract base class which provides an interface to visualization helper classes. It provides a number of methods that all the helpers need to conform to.
Definition at line 24 of file IVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 24 of file IVisualization3D.hpp
Member Typedef Documentation
using Acts::IVisualization3D::FaceType = std::vector<size_t>
Definition at line 26 of file IVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 26 of file IVisualization3D.hpp
Member Function Documentation
virtual void Acts::IVisualization3D::clear () pure virtual
Remove all contents of this helper
Implemented in Acts::ObjVisualization3D< T >, and Acts::PlyVisualization3D< T >.
Referenced by Acts::GeometryView3D::drawLayer(), Acts::GeometryView3D::drawSurfaceArray(), Acts::GeometryView3D::drawTrackingVolume(), Acts::VolumeView3DTest::run(), Acts::PrimitivesView3DTest::run(), and Acts::SurfaceView3DTest::run().
virtual void Acts::IVisualization3D::face (const std::vector< Vector3D > & vtxs, ColorRGB color = {120, 120, 120}) pure virtual
Draw a face that connects a list of vertices.
Note
Depending on the helper implementation, out of plane vertices might be handled differently.
Parameters
vtxs The vertices that make up the face
color The color of the face
Implemented in Acts::ObjVisualization3D< T >, and Acts::PlyVisualization3D< T >.
Referenced by Acts::Frustum< value_t, DIM, SIDES >::draw(), Acts::GenericCuboidVolumeBounds::draw(), and Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::draw().
void Acts::IVisualization3D::face (const std::vector< Vector3F > & vtxs, ColorRGB color = {120, 120, 120})
Definition at line 16 of file IVisualization3D.cpp.
View newest version in sPHENIX GitHub at line 16 of file IVisualization3D.cpp
References Acts::Test::transform, and v.
virtual void Acts::IVisualization3D::faces (const std::vector< Vector3D > & vtxs, const std::vector< FaceType > & faces, ColorRGB color = {120, 120, 120}) pure virtual
Draw a faces that connects a list of vertices - expert only
Note
Depending on the helper implementation, out of plane vertices might be handled differently.
Parameters
vtxs The vertices that make up the faceS
faces The face presectiotions (i.e. connecting vertices)
color The color of the face
Implemented in Acts::ObjVisualization3D< T >, and Acts::PlyVisualization3D< T >.
Referenced by Acts::GeometryView3D::drawPolyhedron().
bool Acts::IVisualization3D::hasExtension (const std::string & path) const protected
Helper: check for extension
Note
this is a placeholder for std::filesystem::has_extension which needs special linking until gcc9
Parameters
path the path to be checked
Definition at line 31 of file IVisualization3D.cpp.
View newest version in sPHENIX GitHub at line 31 of file IVisualization3D.cpp
virtual void Acts::IVisualization3D::line (const Vector3D & a, const Vector3D & b, ColorRGB color = {120, 120, 120}) pure virtual
Draw a line from a vertex to another
Parameters
a The start vertex
b The end vertex
color The color of the line
Implemented in Acts::ObjVisualization3D< T >, and Acts::PlyVisualization3D< T >.
Referenced by Acts::Ray< value_t, DIM >::draw(), and Acts::GeometryView3D::drawSegmentBase().
void Acts::IVisualization3D::line (const Vector3F & a, const Vector3F & b, ColorRGB color = {120, 120, 120})
(const Vector3F&, const Vector3F&,
Draw a line from a vertex to another
Parameters
a The start vertex
b The end vertex
color The color of the line
(const Vector3F&, const Vector3F&, ColorRGB)
Definition at line 24 of file IVisualization3D.cpp.
View newest version in sPHENIX GitHub at line 24 of file IVisualization3D.cpp
References line.
void Acts::IVisualization3D::replaceExtension (std::string & path, const std::string & suffix) const protected
Helper: replace the extension
Note
this is a placeholder for std::filesystem::replace_extension which needs special linking until gcc9
Parameters
path [in,out] the path to be changed
suffix the extension to be added
Definition at line 35 of file IVisualization3D.cpp.
View newest version in sPHENIX GitHub at line 35 of file IVisualization3D.cpp
virtual void Acts::IVisualization3D::vertex (const Vector3D & vtx, ColorRGB color = {120, 120, 120}) pure virtual
Draw a vertex at a given location and a color.
Parameters
vtx The vertex position
color The color
Implemented in Acts::ObjVisualization3D< T >, and Acts::PlyVisualization3D< T >.
Referenced by vertex().
void Acts::IVisualization3D::vertex (const Vector3F & vtx, ColorRGB color = {120, 120, 120})
Below are helper functions, which share the same interface as the ones above, but explicitly accept float values (instead of double), converts them and calls the above methods.Draw a vertex at a given location and a color.
Parameters
vtx The vertex position
color The color
Definition at line 11 of file IVisualization3D.cpp.
View newest version in sPHENIX GitHub at line 11 of file IVisualization3D.cpp
References vertex().
virtual void Acts::IVisualization3D::write (std::ostream & os) const pure virtual
Write the content of the helper to an outstream.
Parameters
os The output stream for file
Implemented in Acts::ObjVisualization3D< T >, and Acts::PlyVisualization3D< T >.
Referenced by Acts::GeometryView3D::drawLayer(), Acts::GeometryView3D::drawSurfaceArray(), Acts::GeometryView3D::drawTrackingVolume(), Acts::operator<<(), Acts::VolumeView3DTest::run(), Acts::TrackingGeometryView3DTest::run(), Acts::PrimitivesView3DTest::run(), Acts::SurfaceView3DTest::run(), Acts::EventDataView3DTest::testBoundTrackParameters(), and Acts::EventDataView3DTest::testMultiTrajectory().
virtual void Acts::IVisualization3D::write (const std::string & path) const pure virtual
Write the content of the helper to an outstream.
Parameters
path is the file system path for writing the file
Note
wil change to std::filesystem::path once gcc9 is standard
Implemented in Acts::ObjVisualization3D< T >, and Acts::PlyVisualization3D< T >.
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Visualization/IVisualization3D.hpp
acts/blob/sPHENIX/Core/src/Visualization/IVisualization3D.cpp