Analysis Software: Acts::AdaptiveGridDensityVertexFinder< trkGridSize, vfitter_t > Class Template Reference
Acts::AdaptiveGridDensityVertexFinder< trkGridSize, vfitter_t > Class Template Reference
Vertex finder that makes use of a track density grid. Each single track is modelled as a 2-dim Gaussian distribution grid in the d0-z0 plane, but only the overlap with the z-axis (i.e. a 1-dim density vector) needs to be calculated. All track contributions along the beam axis (main density vector) are superimposed and the z-value of the bin with the highest track density is returned as a vertex candidate. Unlike the GridDensityVertexFinder, this seeder implements an adaptive version where the density grid grows bigger with added tracks.
#include <acts/blob/sPHENIX/Core/include/Acts/Vertexing/AdaptiveGridDensityVertexFinder.hpp>
Classes
struct Config
The Config struct.
struct State
The State struct.
Public Types
using DensityMap = typename GridDensity::DensityMap
Public Member Functions
Result< std::vector< Vertex
< InputTrack_t > > > find (const std::vector< const InputTrack_t * > &trackVector, const VertexingOptions< InputTrack_t > &vertexingOptions, State &state) const
Function that finds single vertex candidate.
template<typename T = InputTrack_t, std::enable_if_t< std::is_same< T, BoundTrackParameters >::value, int > = 0>
AdaptiveGridDensityVertexFinder (const Config &cfg)
Constructor used if InputTrack_t type == BoundTrackParameters.
m_extractParameters (func)
AdaptiveGridDensityVertexFinder (const std::function< BoundTrackParameters(InputTrack_t)> &func)
Constructor for user-defined InputTrack_t type =! BoundTrackParameters with default Config object.
Private Types
using InputTrack_t = typename vfitter_t::InputTrack_t
using GridDensity = AdaptiveGridTrackDensity< trkGridSize >
Private Member Functions
bool doesPassTrackSelection (const BoundTrackParameters &trk) const
Checks if a track passes the selection criteria for seeding.
Private Attributes
const Config m_cfg
std::function
< BoundTrackParameters(InputTrack_t)> m_extractParameters
Function to extract track parameters, InputTrack_t objects are BoundTrackParameters by default, function to be overwritten to return BoundTrackParameters for other InputTrack_t objects.
Detailed Description
template<int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>>
class Acts::AdaptiveGridDensityVertexFinder< trkGridSize, vfitter_t >
Vertex finder that makes use of a track density grid. Each single track is modelled as a 2-dim Gaussian distribution grid in the d0-z0 plane, but only the overlap with the z-axis (i.e. a 1-dim density vector) needs to be calculated. All track contributions along the beam axis (main density vector) are superimposed and the z-value of the bin with the highest track density is returned as a vertex candidate. Unlike the GridDensityVertexFinder, this seeder implements an adaptive version where the density grid grows bigger with added tracks.
Template Parameters
trkGridSize The 2-dim grid size of a single track, i.e. a single track is modelled as a (trkGridSize x trkGridSize) grid in the d0-z0 plane. Note: trkGridSize has to be an odd value.
Definition at line 37 of file AdaptiveGridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 37 of file AdaptiveGridDensityVertexFinder.hpp
Member Typedef Documentation
template<int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>> using Acts::AdaptiveGridDensityVertexFinder< trkGridSize, vfitter_t >::DensityMap = typename GridDensity::DensityMap
Definition at line 45 of file AdaptiveGridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 45 of file AdaptiveGridDensityVertexFinder.hpp
template<int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>> using Acts::AdaptiveGridDensityVertexFinder< trkGridSize, vfitter_t >::GridDensity = AdaptiveGridTrackDensity<trkGridSize> private
Definition at line 42 of file AdaptiveGridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 42 of file AdaptiveGridDensityVertexFinder.hpp
template<int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>> using Acts::AdaptiveGridDensityVertexFinder< trkGridSize, vfitter_t >::InputTrack_t = typename vfitter_t::InputTrack_t private
Definition at line 41 of file AdaptiveGridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 41 of file AdaptiveGridDensityVertexFinder.hpp
Constructor & Destructor Documentation
template<int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>> template<typename T = InputTrack_t, std::enable_if_t< std::is_same< T, BoundTrackParameters >::value, int > = 0> Acts::AdaptiveGridDensityVertexFinder< trkGridSize, vfitter_t >::AdaptiveGridDensityVertexFinder (const Config & cfg) inline
Constructor used if InputTrack_t type == BoundTrackParameters.
Parameters
cfg Configuration object
Definition at line 117 of file AdaptiveGridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 117 of file AdaptiveGridDensityVertexFinder.hpp
template<int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>> Acts::AdaptiveGridDensityVertexFinder< trkGridSize, vfitter_t >::AdaptiveGridDensityVertexFinder (const std::function< BoundTrackParameters(InputTrack_t)> & func) inline
Constructor for user-defined InputTrack_t type =! BoundTrackParameters with default Config object.
Parameters
func Function extracting BoundTrackParameters from InputTrack_t object
Definition at line 144 of file AdaptiveGridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 144 of file AdaptiveGridDensityVertexFinder.hpp
Member Function Documentation
template<int trkGridSize, typename vfitter_t > auto Acts::AdaptiveGridDensityVertexFinder< trkGridSize, vfitter_t >::doesPassTrackSelection (const BoundTrackParameters & trk) const private
Checks if a track passes the selection criteria for seeding.
Parameters
trk The track
Returns
Bool track passes selection
Definition at line 103 of file AdaptiveGridDensityVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 103 of file AdaptiveGridDensityVertexFinder.ipp
References Acts::eBoundLoc0, Acts::eBoundLoc1, and m_cfg().
template<int trkGridSize, typename vfitter_t > auto Acts::AdaptiveGridDensityVertexFinder< trkGridSize, vfitter_t >::find (const std::vector< const InputTrack_t * > & trackVector, const VertexingOptions< InputTrack_t > & vertexingOptions, State & state) const
Function that finds single vertex candidate.
Parameters
trackVector Input track collection
vertexingOptions Vertexing options
state The state object to cache the density grid and density contributions of each track, to be used if cacheGridStateForTrackRemoval == true
Returns
Vector of vertices, filled with a single vertex (for consistent interfaces)
Definition at line 10 of file AdaptiveGridDensityVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 10 of file AdaptiveGridDensityVertexFinder.ipp
References Acts::Vertex< input_track_t >::fullCovariance(), m_cfg(), Acts::Vertex< input_track_t >::setFullCovariance(), filter::state, width, and physmon_track_finding_ttbar::z.
template<int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>> Acts::AdaptiveGridDensityVertexFinder< trkGridSize, vfitter_t >::m_extractParameters (func) inline
Definition at line 137 of file AdaptiveGridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 137 of file AdaptiveGridDensityVertexFinder.hpp
Member Data Documentation
template<int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>> const Config Acts::AdaptiveGridDensityVertexFinder< trkGridSize, vfitter_t >::m_cfg private
Definition at line 157 of file AdaptiveGridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 157 of file AdaptiveGridDensityVertexFinder.hpp
template<int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>> std::function<BoundTrackParameters(InputTrack_t)> Acts::AdaptiveGridDensityVertexFinder< trkGridSize, vfitter_t >::m_extractParameters private
Function to extract track parameters, InputTrack_t objects are BoundTrackParameters by default, function to be overwritten to return BoundTrackParameters for other InputTrack_t objects.
Definition at line 162 of file AdaptiveGridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 162 of file AdaptiveGridDensityVertexFinder.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Vertexing/AdaptiveGridDensityVertexFinder.hpp
acts/blob/sPHENIX/Core/include/Acts/Vertexing/AdaptiveGridDensityVertexFinder.ipp