Analysis Software: SyncObjectv1 Class Reference
SyncObjectv1 Class Reference
#include <coresoftware/blob/master/offline/framework/ffaobjects/SyncObjectv1.h>
Public Member Functions
SyncObjectv1 ()=default
ctor
SyncObjectv1 (const SyncObject &source)
PHObject * CloneMe () const override
Virtual copy constructor.
~SyncObjectv1 () override=default
dtor
void Reset () override
Clear Event.
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains valid data
void EventCounter (const int ival) override
set Event Counter
void EventNumber (const int ival) override
set Event Number
void RunNumber (const int ival) override
set Run Number
void SegmentNumber (const int ival) override
set Segment Number
Public Member Functions inherited from SyncObject
SyncObject ()=default
ctor - daughter class copy ctor needs this
SyncObject (const SyncObject &source)=default
copy ctor daughter class copy ctor needs also this
~SyncObject () override
dtor
SyncObject & operator= (const SyncObject &source)
virtual int Different (const SyncObject *other) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
int EventCounter () const override
get Event Counter
int EventNumber () const override
get Event Number
int RunNumber () const override
get Run Number
int SegmentNumber () const override
get Segment Number
Private Attributes
int eventcounter = 0
int eventnumber = 0
int runnumber = 0
int segmentnumber = -999999
Detailed Description
Definition at line 12 of file SyncObjectv1.h.
View newest version in sPHENIX GitHub at line 12 of file SyncObjectv1.h
Constructor & Destructor Documentation
SyncObjectv1::SyncObjectv1 () default
ctor
Referenced by CloneMe().
SyncObjectv1::SyncObjectv1 (const SyncObject & source) explicit
Definition at line 3 of file SyncObjectv1.cc.
View newest version in sPHENIX GitHub at line 3 of file SyncObjectv1.cc
References SyncObject::EventCounter(), EventCounter(), SyncObject::EventNumber(), EventNumber(), SyncObject::RunNumber(), RunNumber(), SyncObject::SegmentNumber(), and SegmentNumber().
SyncObjectv1::~SyncObjectv1 () override default
dtor
Member Function Documentation
PHObject* SyncObjectv1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from SyncObject.
Definition at line 19 of file SyncObjectv1.h.
View newest version in sPHENIX GitHub at line 19 of file SyncObjectv1.h
References SyncObjectv1().
void SyncObjectv1::EventCounter (const int ival) inline override virtual
set Event Counter
Reimplemented from SyncObject.
Definition at line 36 of file SyncObjectv1.h.
View newest version in sPHENIX GitHub at line 36 of file SyncObjectv1.h
References eventcounter.
int SyncObjectv1::EventCounter () const inline override protected virtual
get Event Counter
Reimplemented from SyncObject.
Definition at line 52 of file SyncObjectv1.h.
View newest version in sPHENIX GitHub at line 52 of file SyncObjectv1.h
References eventcounter.
Referenced by SyncObjectv1().
void SyncObjectv1::EventNumber (const int ival) inline override virtual
set Event Number
Reimplemented from SyncObject.
Definition at line 40 of file SyncObjectv1.h.
View newest version in sPHENIX GitHub at line 40 of file SyncObjectv1.h
References eventnumber.
int SyncObjectv1::EventNumber () const inline override protected virtual
get Event Number
Reimplemented from SyncObject.
Definition at line 54 of file SyncObjectv1.h.
View newest version in sPHENIX GitHub at line 54 of file SyncObjectv1.h
References eventnumber.
Referenced by SyncObjectv1().
void SyncObjectv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SyncObject.
Definition at line 20 of file SyncObjectv1.cc.
View newest version in sPHENIX GitHub at line 20 of file SyncObjectv1.cc
References eventcounter, eventnumber, runnumber, and segmentnumber.
int SyncObjectv1::isValid () const override virtual
isValid returns non zero if object contains valid data
Reimplemented from SyncObject.
Definition at line 32 of file SyncObjectv1.cc.
View newest version in sPHENIX GitHub at line 32 of file SyncObjectv1.cc
References eventcounter.
void SyncObjectv1::Reset () override virtual
Clear Event.
Reimplemented from SyncObject.
Definition at line 11 of file SyncObjectv1.cc.
View newest version in sPHENIX GitHub at line 11 of file SyncObjectv1.cc
References eventcounter, eventnumber, runnumber, and segmentnumber.
void SyncObjectv1::RunNumber (const int ival) inline override virtual
set Run Number
Reimplemented from SyncObject.
Definition at line 44 of file SyncObjectv1.h.
View newest version in sPHENIX GitHub at line 44 of file SyncObjectv1.h
References runnumber.
int SyncObjectv1::RunNumber () const inline override protected virtual
get Run Number
Reimplemented from SyncObject.
Definition at line 56 of file SyncObjectv1.h.
View newest version in sPHENIX GitHub at line 56 of file SyncObjectv1.h
References runnumber.
Referenced by SyncObjectv1().
void SyncObjectv1::SegmentNumber (const int ival) inline override virtual
set Segment Number
Reimplemented from SyncObject.
Definition at line 48 of file SyncObjectv1.h.
View newest version in sPHENIX GitHub at line 48 of file SyncObjectv1.h
References segmentnumber.
int SyncObjectv1::SegmentNumber () const inline override protected virtual
get Segment Number
Reimplemented from SyncObject.
Definition at line 58 of file SyncObjectv1.h.
View newest version in sPHENIX GitHub at line 58 of file SyncObjectv1.h
References segmentnumber.
Referenced by SyncObjectv1().
Member Data Documentation
int SyncObjectv1::eventcounter = 0 private
Definition at line 61 of file SyncObjectv1.h.
View newest version in sPHENIX GitHub at line 61 of file SyncObjectv1.h
Referenced by EventCounter(), identify(), isValid(), and Reset().
int SyncObjectv1::eventnumber = 0 private
Definition at line 62 of file SyncObjectv1.h.
View newest version in sPHENIX GitHub at line 62 of file SyncObjectv1.h
Referenced by EventNumber(), identify(), and Reset().
int SyncObjectv1::runnumber = 0 private
Definition at line 63 of file SyncObjectv1.h.
View newest version in sPHENIX GitHub at line 63 of file SyncObjectv1.h
Referenced by identify(), Reset(), and RunNumber().
int SyncObjectv1::segmentnumber = -999999 private
Definition at line 64 of file SyncObjectv1.h.
View newest version in sPHENIX GitHub at line 64 of file SyncObjectv1.h
Referenced by identify(), Reset(), and SegmentNumber().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/ffaobjects/SyncObjectv1.h
coresoftware/blob/master/offline/framework/ffaobjects/SyncObjectv1.cc