Analysis Software: TrkrHitSetContainer Class Reference
TrkrHitSetContainer Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrHitSetContainer.h>
Public Types
using Map = std::map< TrkrDefs::hitsetkey, TrkrHitSet * >
using Iterator = Map::iterator
using ConstIterator = Map::const_iterator
using Range = std::pair< Iterator, Iterator >
using ConstRange = std::pair< ConstIterator, ConstIterator >
Public Member Functions
~TrkrHitSetContainer () override=default
dtir
void Reset () override
PHObject functions.
virtual ConstIterator addHitSet (TrkrHitSet *)
Add a TrkrHitSet to the container.
virtual ConstIterator addHitSetSpecifyKey (const TrkrDefs::hitsetkey, TrkrHitSet *)
virtual void removeHitSet (TrkrDefs::hitsetkey key)
preferred removal method, key is currently the hit id
virtual void removeHitSet (TrkrHitSet *)
inefficent, use key where possible instead
virtual Iterator findOrAddHitSet (TrkrDefs::hitsetkey)
find or add HitSet
virtual ConstRange getHitSets (const TrkrDefs::TrkrId) const
return all HitSets matching a given detid
virtual ConstRange getHitSets (const TrkrDefs::TrkrId trackerid, const uint8_t layer) const
return all HitSets matching a given detid, layer
virtual ConstRange getHitSets () const
return all HitSets
virtual TrkrHitSet * findHitSet (TrkrDefs::hitsetkey)
return a given HitSet based on its key
virtual unsigned int size () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
TrkrHitSetContainer ()=default
ctor
Detailed Description
Container for TrkrHitSet objects
Definition at line 23 of file TrkrHitSetContainer.h.
View newest version in sPHENIX GitHub at line 23 of file TrkrHitSetContainer.h
Member Typedef Documentation
using TrkrHitSetContainer::ConstIterator = Map::const_iterator
Definition at line 29 of file TrkrHitSetContainer.h.
View newest version in sPHENIX GitHub at line 29 of file TrkrHitSetContainer.h
using TrkrHitSetContainer::ConstRange = std::pair<ConstIterator, ConstIterator>
Definition at line 31 of file TrkrHitSetContainer.h.
View newest version in sPHENIX GitHub at line 31 of file TrkrHitSetContainer.h
using TrkrHitSetContainer::Iterator = Map::iterator
Definition at line 28 of file TrkrHitSetContainer.h.
View newest version in sPHENIX GitHub at line 28 of file TrkrHitSetContainer.h
using TrkrHitSetContainer::Map = std::map<TrkrDefs::hitsetkey, TrkrHitSet *>
Definition at line 27 of file TrkrHitSetContainer.h.
View newest version in sPHENIX GitHub at line 27 of file TrkrHitSetContainer.h
using TrkrHitSetContainer::Range = std::pair<Iterator, Iterator>
Definition at line 30 of file TrkrHitSetContainer.h.
View newest version in sPHENIX GitHub at line 30 of file TrkrHitSetContainer.h
Constructor & Destructor Documentation
TrkrHitSetContainer::~TrkrHitSetContainer () override default
dtir
TrkrHitSetContainer::TrkrHitSetContainer () protected default
ctor
Member Function Documentation
TrkrHitSetContainer::ConstIterator TrkrHitSetContainer::addHitSet (TrkrHitSet * newhit) virtual
Add a TrkrHitSet to the container.
Reimplemented in TrkrHitSetContainerv1.
Definition at line 27 of file TrkrHitSetContainer.cc.
View newest version in sPHENIX GitHub at line 27 of file TrkrHitSetContainer.cc
TrkrHitSetContainer::ConstIterator TrkrHitSetContainer::addHitSetSpecifyKey (const TrkrDefs::hitsetkey key, TrkrHitSet * newhit) virtual
Reimplemented in TrkrHitSetContainerv1.
Definition at line 31 of file TrkrHitSetContainer.cc.
View newest version in sPHENIX GitHub at line 31 of file TrkrHitSetContainer.cc
virtual TrkrHitSet* TrkrHitSetContainer::findHitSet (TrkrDefs::hitsetkey) inline virtual
return a given HitSet based on its key
Reimplemented in TrkrHitSetContainerv1.
Definition at line 65 of file TrkrHitSetContainer.h.
View newest version in sPHENIX GitHub at line 65 of file TrkrHitSetContainer.h
Referenced by PHG4TpcDigitizer::DigitizeCylinderCells(), and MvtxPrototype2UnpackPRDF::process_event().
TrkrHitSetContainer::Iterator TrkrHitSetContainer::findOrAddHitSet (TrkrDefs::hitsetkey key) virtual
find or add HitSet
Reimplemented in TrkrHitSetContainerv1.
Definition at line 35 of file TrkrHitSetContainer.cc.
View newest version in sPHENIX GitHub at line 35 of file TrkrHitSetContainer.cc
Referenced by TpcPrototypeUnpacker::exportDSTHits(), PHG4TpcPadPlaneReadout::MapToPadPlane(), and PHG4TpcElectronDrift::process_event().
TrkrHitSetContainer::ConstRange TrkrHitSetContainer::getHitSets (const TrkrDefs::TrkrId trackerid) const virtual
return all HitSets matching a given detid
Reimplemented in TrkrHitSetContainerv1.
Definition at line 39 of file TrkrHitSetContainer.cc.
View newest version in sPHENIX GitHub at line 39 of file TrkrHitSetContainer.cc
Referenced by SvtxClusterEval::all_clusters_from(), SvtxHitEval::all_hits_from(), SvtxHitEval::all_truth_hits(), SvtxClusterEval::best_cluster_by_nhit(), PHGenFitTrkProp::BuildLayerZPhiHitMap(), HFTrigger::calculateMultiplicity(), HFTriggerMVA::calculateMultiplicity(), InttClusterizer::ClusterLadderCells(), MvtxPrototype2Clusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtx(), PHTpcTrackerUtil::convert_clusters_to_hits(), PHG4TpcDigitizer::DigitizeCylinderCells(), PHG4InttDigitizer::DigitizeLadderCells(), PHG4MvtxDigitizer::DigitizeMvtxLadderCells(), QAG4SimulationIntt::evaluate_clusters(), QAG4SimulationMvtx::evaluate_clusters(), QAG4SimulationMicromegas::evaluate_clusters(), TrackEvaluation::evaluate_clusters(), TrackEvaluation::evaluate_event(), QAG4SimulationMicromegas::evaluate_hits(), PHTpcEventExporter::exportEvent(), SvtxClusterEval::fill_cluster_layer_map(), SvtxEvaluator::fillOutputNtuples(), SvtxClusterEval::FillRecoClusterFromG4HitCache(), PHRTreeSeeding::FillTree(), PHCASeeding::FillTree(), PHActsSiliconSeeding::getMvtxSpacePoints(), PHTruthSiliconAssociation::getSiliconClustersFromParticle(), PHActsSiliconSeeding::matchInttClusters(), PHSimpleKFProp::PrepareKDTrees(), SvtxEvaluator::printInputInfo(), SvtxEvaluator::printOutputInfo(), PHSiliconTruthTrackSeeding::Process(), TpcPrototypeClusterizer::process_event(), TpcClusterCleaner::process_event(), TpcClusterizer::process_event(), QAG4SimulationTracking::process_event(), PHG4TpcElectronDrift::process_event(), SynRadAna::process_event(), TPCMLDataInterface::process_event(), PHTruthClustering::process_event(), AnaMvtxTestBeam2019::process_event(), DumpTrkrHitSetContainer::process_Node(), TpcSpaceChargeCorrection::transform_clusters(), PHInitZVertexing::translate_input(), PHPatternReco::translate_input(), and PHHoughSeeding::translate_input().
TrkrHitSetContainer::ConstRange TrkrHitSetContainer::getHitSets (const TrkrDefs::TrkrId trackerid, const uint8_t layer) const virtual
return all HitSets matching a given detid, layer
Reimplemented in TrkrHitSetContainerv1.
Definition at line 43 of file TrkrHitSetContainer.cc.
View newest version in sPHENIX GitHub at line 43 of file TrkrHitSetContainer.cc
TrkrHitSetContainer::ConstRange TrkrHitSetContainer::getHitSets () const virtual
return all HitSets
Reimplemented in TrkrHitSetContainerv1.
Definition at line 47 of file TrkrHitSetContainer.cc.
View newest version in sPHENIX GitHub at line 47 of file TrkrHitSetContainer.cc
virtual void TrkrHitSetContainer::removeHitSet (TrkrDefs::hitsetkey key) inline virtual
preferred removal method, key is currently the hit id
Reimplemented in TrkrHitSetContainerv1.
Definition at line 45 of file TrkrHitSetContainer.h.
View newest version in sPHENIX GitHub at line 45 of file TrkrHitSetContainer.h
virtual void TrkrHitSetContainer::removeHitSet (TrkrHitSet *) inline virtual
inefficent, use key where possible instead
Reimplemented in TrkrHitSetContainerv1.
Definition at line 49 of file TrkrHitSetContainer.h.
View newest version in sPHENIX GitHub at line 49 of file TrkrHitSetContainer.h
void TrkrHitSetContainer::Reset () override virtual
PHObject functions.
Reimplemented from PHObject.
Reimplemented in TrkrHitSetContainerv1.
Definition at line 20 of file TrkrHitSetContainer.cc.
View newest version in sPHENIX GitHub at line 20 of file TrkrHitSetContainer.cc
virtual unsigned int TrkrHitSetContainer::size (void) const inline virtual
Reimplemented in TrkrHitSetContainerv1.
Definition at line 68 of file TrkrHitSetContainer.h.
View newest version in sPHENIX GitHub at line 68 of file TrkrHitSetContainer.h
Referenced by AnaMvtxTestBeam2019::process_event(), and DumpTrkrHitSetContainer::process_Node().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrHitSetContainer.h
coresoftware/blob/master/offline/packages/trackbase/TrkrHitSetContainer.cc