Analysis Software: MvtxAlign Class Reference
MvtxAlign Class Reference
#include <prototype/blob/master/offline/packages/MvtxPrototype1/MvtxAlign.h>
Classes
struct AlignmentPar
Public Member Functions
MvtxAlign (const std::string &name="MvtxAlign")
virtual ~MvtxAlign ()
int Init (PHCompositeNode *topNode)
module initialization
int InitRun (PHCompositeNode *topNode)
run initialization
int process_event (PHCompositeNode *topNode)
event processing
int End (PHCompositeNode *topNode)
end of process
void AddAlignmentPar (TrkrDefs::hitsetkey key, double dx, double dy, double dz)
put in misalignment by hand
void PrintAlignmentPars (std::ostream &os=std::cout) const
print stored misalignments
void SetAlignmentParFileDir (const std::string fdir)
set the directory for alignment parameter files
void SetAlignmentParFromFile (const bool yn)
set boolean to read from file rather than setting by hand
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int ReadAlignmentParFile ()
Private Attributes
TrkrClusterContainer * clusters_
std::map< TrkrDefs::hitsetkey,
AlignmentPar > alignmap_
std::string fdir_
int runnumber_
bool apff_
PHTimeServer::timer _timer
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 14 of file MvtxAlign.h.
View newest version in sPHENIX GitHub at line 14 of file MvtxAlign.h
Constructor & Destructor Documentation
MvtxAlign::MvtxAlign (const std::string & name = "MvtxAlign")
Definition at line 22 of file MvtxAlign.C.
View newest version in sPHENIX GitHub at line 22 of file MvtxAlign.C
virtual MvtxAlign::~MvtxAlign () inline virtual
Definition at line 26 of file MvtxAlign.h.
View newest version in sPHENIX GitHub at line 26 of file MvtxAlign.h
Member Function Documentation
void MvtxAlign::AddAlignmentPar (TrkrDefs::hitsetkey key, double dx, double dy, double dz)
put in misalignment by hand
Definition at line 109 of file MvtxAlign.C.
View newest version in sPHENIX GitHub at line 109 of file MvtxAlign.C
References alignmap_, MvtxAlign::AlignmentPar::dx, MvtxAlign::AlignmentPar::dy, dy, MvtxAlign::AlignmentPar::dz, dz, PHWHERE, and verbosity.
Referenced by ReadAlignmentParFile().
int MvtxAlign::End (PHCompositeNode * topNode) inline virtual
end of process
Reimplemented from SubsysReco.
Definition at line 38 of file MvtxAlign.h.
View newest version in sPHENIX GitHub at line 38 of file MvtxAlign.h
int MvtxAlign::Init (PHCompositeNode * topNode) inline virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 29 of file MvtxAlign.h.
View newest version in sPHENIX GitHub at line 29 of file MvtxAlign.h
int MvtxAlign::InitRun (PHCompositeNode * topNode) virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 33 of file MvtxAlign.C.
View newest version in sPHENIX GitHub at line 33 of file MvtxAlign.C
References apff_, Fun4AllReturnCodes::EVENT_OK, PHFlag::get_IntFlag(), recoConsts::instance(), PHWHERE, ReadAlignmentParFile(), and runnumber_.
void MvtxAlign::PrintAlignmentPars (std::ostream & os = std::cout) const
print stored misalignments
Definition at line 147 of file MvtxAlign.C.
View newest version in sPHENIX GitHub at line 147 of file MvtxAlign.C
References alignmap_, dz, and PHWHERE.
Referenced by Fun4All_TestBeam(), and ReadAlignmentParFile().
int MvtxAlign::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 47 of file MvtxAlign.C.
View newest version in sPHENIX GitHub at line 47 of file MvtxAlign.C
References _timer, Fun4AllReturnCodes::ABORTRUN, alignmap_, clusters_, dy, dz, Fun4AllReturnCodes::EVENT_OK, PHTimeServer::timer::get(), TrkrClusterv1::identify(), PHWHERE, PHTimer::restart(), PHTimer::stop(), and verbosity.
int MvtxAlign::ReadAlignmentParFile () private
Definition at line 168 of file MvtxAlign.C.
View newest version in sPHENIX GitHub at line 168 of file MvtxAlign.C
References AddAlignmentPar(), double(), dy, dz, fdir_, INTTVtxZ::fname, line, PHWHERE, PrintAlignmentPars(), runnumber_, and verbosity.
Referenced by InitRun().
void MvtxAlign::SetAlignmentParFileDir (const std::string fdir) inline
set the directory for alignment parameter files
Definition at line 47 of file MvtxAlign.h.
View newest version in sPHENIX GitHub at line 47 of file MvtxAlign.h
References fdir_.
Referenced by Fun4All_TestBeam().
void MvtxAlign::SetAlignmentParFromFile (const bool yn) inline
set boolean to read from file rather than setting by hand
Definition at line 50 of file MvtxAlign.h.
View newest version in sPHENIX GitHub at line 50 of file MvtxAlign.h
References apff_, and yn.
Member Data Documentation
PHTimeServer::timer MvtxAlign::_timer private
Definition at line 68 of file MvtxAlign.h.
View newest version in sPHENIX GitHub at line 68 of file MvtxAlign.h
Referenced by process_event().
std::map<TrkrDefs::hitsetkey, AlignmentPar> MvtxAlign::alignmap_ private
Definition at line 61 of file MvtxAlign.h.
View newest version in sPHENIX GitHub at line 61 of file MvtxAlign.h
Referenced by AddAlignmentPar(), PrintAlignmentPars(), and process_event().
bool MvtxAlign::apff_ private
Definition at line 66 of file MvtxAlign.h.
View newest version in sPHENIX GitHub at line 66 of file MvtxAlign.h
Referenced by InitRun(), and SetAlignmentParFromFile().
TrkrClusterContainer* MvtxAlign::clusters_ private
Definition at line 58 of file MvtxAlign.h.
View newest version in sPHENIX GitHub at line 58 of file MvtxAlign.h
Referenced by process_event().
std::string MvtxAlign::fdir_ private
Definition at line 64 of file MvtxAlign.h.
View newest version in sPHENIX GitHub at line 64 of file MvtxAlign.h
Referenced by ReadAlignmentParFile(), and SetAlignmentParFileDir().
int MvtxAlign::runnumber_ private
Definition at line 65 of file MvtxAlign.h.
View newest version in sPHENIX GitHub at line 65 of file MvtxAlign.h
Referenced by InitRun(), and ReadAlignmentParFile().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/MvtxPrototype1/MvtxAlign.h
prototype/blob/master/offline/packages/MvtxPrototype1/MvtxAlign.C