Analysis Software: Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t > Class Template Reference
Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t > Class Template Reference
Vertex finder that makes use of a track density grid. Each single track is modelled as a 2(!)-dim Gaussian distribution grid in the d0-z0 plane, but only the overlap with the z-axis (i.e. a 1-dim density vector) needs to be calculated. All track contributions along the beam axis (main density grid) a superimposed and the z-value of the bin with the highest track density is returned as a vertex candidate.
#include <acts/blob/sPHENIX/Core/include/Acts/Vertexing/GridDensityVertexFinder.hpp>
Classes
struct Config
The Config struct.
struct State
The State struct.
Public Types
using MainGridVector = typename GridDensity::MainGridVector
using TrackGridVector = typename GridDensity::TrackGridVector
Public Member Functions
Result< std::vector< Vertex
< InputTrack_t > > > find (const std::vector< const InputTrack_t * > &trackVector, const VertexingOptions< InputTrack_t > &vertexingOptions, State &state) const
Function that finds single vertex candidate.
template<typename T = InputTrack_t, std::enable_if_t< std::is_same< T, BoundTrackParameters >::value, int > = 0>
GridDensityVertexFinder (const Config &cfg)
Constructor used if InputTrack_t type == BoundTrackParameters.
m_extractParameters (func)
GridDensityVertexFinder (const std::function< BoundTrackParameters(InputTrack_t)> &func)
Constructor for user-defined InputTrack_t type =! BoundTrackParameters with default Config object.
Private Types
using InputTrack_t = typename vfitter_t::InputTrack_t
using GridDensity = GaussianGridTrackDensity< mainGridSize, trkGridSize >
Private Member Functions
bool doesPassTrackSelection (const BoundTrackParameters &trk) const
Checks if a track passes the selection criteria for seeding.
Private Attributes
const Config m_cfg
std::function
< BoundTrackParameters(InputTrack_t)> m_extractParameters
Function to extract track parameters, InputTrack_t objects are BoundTrackParameters by default, function to be overwritten to return BoundTrackParameters for other InputTrack_t objects.
Detailed Description
template<int mainGridSize = 2000, int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>>
class Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t >
Vertex finder that makes use of a track density grid. Each single track is modelled as a 2(!)-dim Gaussian distribution grid in the d0-z0 plane, but only the overlap with the z-axis (i.e. a 1-dim density vector) needs to be calculated. All track contributions along the beam axis (main density grid) a superimposed and the z-value of the bin with the highest track density is returned as a vertex candidate.
Template Parameters
mainGridSize The size of the z-axis 1-dim main density grid
trkGridSize The 2(!)-dim grid size of a single track, i.e. a single track is modelled as a (trkGridSize x trkGridSize) grid in the d0-z0 plane. Note: trkGridSize has to be an odd value.
Definition at line 36 of file GridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 36 of file GridDensityVertexFinder.hpp
Member Typedef Documentation
template<int mainGridSize = 2000, int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>> using Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t >::GridDensity = GaussianGridTrackDensity<mainGridSize, trkGridSize> private
Definition at line 43 of file GridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 43 of file GridDensityVertexFinder.hpp
template<int mainGridSize = 2000, int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>> using Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t >::InputTrack_t = typename vfitter_t::InputTrack_t private
Definition at line 42 of file GridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 42 of file GridDensityVertexFinder.hpp
template<int mainGridSize = 2000, int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>> using Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t >::MainGridVector = typename GridDensity::MainGridVector
Definition at line 46 of file GridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 46 of file GridDensityVertexFinder.hpp
template<int mainGridSize = 2000, int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>> using Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t >::TrackGridVector = typename GridDensity::TrackGridVector
Definition at line 47 of file GridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 47 of file GridDensityVertexFinder.hpp
Constructor & Destructor Documentation
template<int mainGridSize = 2000, int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>> template<typename T = InputTrack_t, std::enable_if_t< std::is_same< T, BoundTrackParameters >::value, int > = 0> Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t >::GridDensityVertexFinder (const Config & cfg) inline
Constructor used if InputTrack_t type == BoundTrackParameters.
Parameters
cfg Configuration object
Definition at line 120 of file GridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 120 of file GridDensityVertexFinder.hpp
template<int mainGridSize = 2000, int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>> Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t >::GridDensityVertexFinder (const std::function< BoundTrackParameters(InputTrack_t)> & func) inline
Constructor for user-defined InputTrack_t type =! BoundTrackParameters with default Config object.
Parameters
func Function extracting BoundTrackParameters from InputTrack_t object
Definition at line 147 of file GridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 147 of file GridDensityVertexFinder.hpp
Member Function Documentation
template<int mainGridSize, int trkGridSize, typename vfitter_t > auto Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t >::doesPassTrackSelection (const BoundTrackParameters & trk) const private
Checks if a track passes the selection criteria for seeding.
Parameters
trk The track
Returns
Bool track passes selection
Definition at line 103 of file GridDensityVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 103 of file GridDensityVertexFinder.ipp
References Acts::eBoundLoc0, Acts::eBoundLoc1, and m_cfg().
template<int mainGridSize, int trkGridSize, typename vfitter_t > auto Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t >::find (const std::vector< const InputTrack_t * > & trackVector, const VertexingOptions< InputTrack_t > & vertexingOptions, State & state) const
Function that finds single vertex candidate.
Parameters
trackVector Input track collection
vertexingOptions Vertexing options
state The state object to cache the density grid and density contributions of each track, to be used if cacheGridStateForTrackRemoval == true
Returns
Vector of vertices, filled with a single vertex (for consistent interfaces)
Definition at line 10 of file GridDensityVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 10 of file GridDensityVertexFinder.ipp
References Acts::Vertex< input_track_t >::fullCovariance(), m_cfg(), Acts::Vertex< input_track_t >::setFullCovariance(), filter::state, width, and physmon_track_finding_ttbar::z.
template<int mainGridSize = 2000, int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>> Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t >::m_extractParameters (func) inline
Definition at line 140 of file GridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 140 of file GridDensityVertexFinder.hpp
Member Data Documentation
template<int mainGridSize = 2000, int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>> const Config Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t >::m_cfg private
Definition at line 160 of file GridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 160 of file GridDensityVertexFinder.hpp
template<int mainGridSize = 2000, int trkGridSize = 15, typename vfitter_t = DummyVertexFitter<>> std::function<BoundTrackParameters(InputTrack_t)> Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t >::m_extractParameters private
Function to extract track parameters, InputTrack_t objects are BoundTrackParameters by default, function to be overwritten to return BoundTrackParameters for other InputTrack_t objects.
Definition at line 165 of file GridDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 165 of file GridDensityVertexFinder.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Vertexing/GridDensityVertexFinder.hpp
acts/blob/sPHENIX/Core/include/Acts/Vertexing/GridDensityVertexFinder.ipp