Analysis Software: RDBC/blob/master/macros/RDBCscroll.C File Reference
RDBCscroll.C File Reference
#include <TError.h>
#include <TString.h>
#include <TSQLDriverManager.h>
#include <TSQLConnection.h>
#include <TSQLDatabaseMetaData.h>
#include <TSQLResultSet.h>
#include <TSQLResultSetMetaData.h>
#include <TSQLPreparedStatement.h>
#include <TROOT.h>
#include <TInterpreter.h>
Functions
void CreateStuff (TSQLConnection *con)
void DropStuff (TSQLConnection *con)
TString MakeName (Int_t n)
void Populate (TSQLConnection *con)
void Compare (TSQLConnection *con)
Int_t RDBCscroll (const Text_t *dsn, const Text_t *usr, const Text_t *pwd)
void Catch (TSQLException *e)
Variables
const TString tableName = "odbcxx_test"
const Int_t tableRows = 1000
Function Documentation
void Catch (TSQLException * e)
Definition at line 232 of file RDBCscroll.C.
View newest version in sPHENIX GitHub at line 232 of file RDBCscroll.C
References TSQLException::GetMessage(), printf(), and str.
void Compare (TSQLConnection * con)
Definition at line 122 of file RDBCscroll.C.
View newest version in sPHENIX GitHub at line 122 of file RDBCscroll.C
References TSQLResultSet::AfterLast(), testing::internal::Assert(), TSQLConnection::CreateStatement(), TSQLStatement::ExecuteQuery(), TSQLResultSet::First(), TSQLResultSet::GetInt(), TSQLConnection::GetMetaData(), TSQLResultSet::GetRow(), TSQLResultSet::GetString(), i, TSQLResultSet::IsAfterLast(), TSQLResultSet::IsBeforeFirst(), TSQLResultSet::IsFirst(), TSQLResultSet::IsLast(), kCONCUR_READ_ONLY, kCONCUR_UPDATABLE, kTYPE_SCROLL_INSENSITIVE, kTYPE_SCROLL_SENSITIVE, TSQLResultSet::Last(), MakeName(), perf_headwind::name, TSQLResultSet::Previous(), printf(), str, TSQLDatabaseMetaData::SupportsResultSetConcurrency(), TSQLDatabaseMetaData::SupportsResultSetType(), tableName, and tableRows.
Referenced by TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::followTrack(), and RDBCscroll().
void CreateStuff (TSQLConnection * con)
Definition at line 49 of file RDBCscroll.C.
View newest version in sPHENIX GitHub at line 49 of file RDBCscroll.C
References TSQLConnection::CreateStatement(), TSQLStatement::ExecuteUpdate(), printf(), str, and tableName.
void DropStuff (TSQLConnection * con)
Definition at line 69 of file RDBCscroll.C.
View newest version in sPHENIX GitHub at line 69 of file RDBCscroll.C
References TSQLConnection::CreateStatement(), TSQLStatement::ExecuteUpdate(), printf(), str, and tableName.
TString MakeName (Int_t n)
Definition at line 87 of file RDBCscroll.C.
View newest version in sPHENIX GitHub at line 87 of file RDBCscroll.C
References str.
Referenced by Compare(), and Populate().
void Populate (TSQLConnection * con)
Definition at line 99 of file RDBCscroll.C.
View newest version in sPHENIX GitHub at line 99 of file RDBCscroll.C
References TSQLConnection::Commit(), TSQLStatement::ExecuteUpdate(), i, MakeName(), TSQLConnection::PrepareStatement(), printf(), TSQLPreparedStatement::SetInt(), TSQLPreparedStatement::SetString(), str, tableName, and tableRows.
Referenced by RDBCscroll().
Int_t RDBCscroll (const Text_t * dsn, const Text_t * usr, const Text_t * pwd)
Definition at line 190 of file RDBCscroll.C.
View newest version in sPHENIX GitHub at line 190 of file RDBCscroll.C
References Compare(), con, CreateStuff(), DropStuff(), TSQLDriverManager::GetConnection(), gSQLDriverManager, Populate(), printf(), TSQL::SetHandler(), and str.
Variable Documentation
const TString tableName = "odbcxx_test"
Definition at line 45 of file RDBCscroll.C.
View newest version in sPHENIX GitHub at line 45 of file RDBCscroll.C
const Int_t tableRows = 1000
Definition at line 46 of file RDBCscroll.C.
View newest version in sPHENIX GitHub at line 46 of file RDBCscroll.C
Referenced by Compare(), and Populate().