Analysis Software: ActsExamples::ObjTrackingGeometryWriter Class Reference
ActsExamples::ObjTrackingGeometryWriter Class Reference
#include <acts/blob/sPHENIX/Examples/Io/Obj/include/ActsExamples/Plugins/Obj/ObjTrackingGeometryWriter.hpp>
Classes
class Config
Public Member Functions
ObjTrackingGeometryWriter (const Config &config, Acts::Logging::Level level)
std::string name () const
ActsExamples::ProcessCode write (const AlgorithmContext &context, const Acts::TrackingGeometry &tGeometry)
Private Member Functions
void write (const AlgorithmContext &context, const Acts::TrackingVolume &tVolume)
const Acts::Logger & logger () const
Private access to the logging instance.
Private Attributes
std::unique_ptr< const
Acts::Logger > m_logger
the logger instance
Config m_cfg
the config class
Detailed Description
An Obj writer for the geometry: TrackingGeometry master It delegates the writing of surfaces to the surface writers
Definition at line 35 of file ObjTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 35 of file ObjTrackingGeometryWriter.hpp
Constructor & Destructor Documentation
ActsExamples::ObjTrackingGeometryWriter::ObjTrackingGeometryWriter (const Config & config, Acts::Logging::Level level)
Constructor
Parameters
config is the configuration class
level the log level
Definition at line 17 of file ObjTrackingGeometryWriter.cpp.
View newest version in sPHENIX GitHub at line 17 of file ObjTrackingGeometryWriter.cpp
Member Function Documentation
const Acts::Logger& ActsExamples::ObjTrackingGeometryWriter::logger () const inline private
Private access to the logging instance.
Definition at line 81 of file ObjTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 81 of file ObjTrackingGeometryWriter.hpp
References m_logger.
std::string ActsExamples::ObjTrackingGeometryWriter::name () const
Framework name() method
Returns
the name of the tool
Definition at line 22 of file ObjTrackingGeometryWriter.cpp.
View newest version in sPHENIX GitHub at line 22 of file ObjTrackingGeometryWriter.cpp
ActsExamples::ProcessCode ActsExamples::ObjTrackingGeometryWriter::write (const AlgorithmContext & context, const Acts::TrackingGeometry & tGeometry)
The write interface
Parameters
context the Algorithm/Event context of this call
tGeometry is the geometry to be written out
Returns
ProcessCode to indicate success/failure
Definition at line 26 of file ObjTrackingGeometryWriter.cpp.
View newest version in sPHENIX GitHub at line 26 of file ObjTrackingGeometryWriter.cpp
References ACTS_DEBUG, Acts::TrackingGeometry::highestTrackingVolume(), SUCCESS, and write().
void ActsExamples::ObjTrackingGeometryWriter::write (const AlgorithmContext & context, const Acts::TrackingVolume & tVolume) private
process this volume
Parameters
context the Algorithm/Event context for this call
tVolume the volume to be processed
Definition at line 37 of file ObjTrackingGeometryWriter.cpp.
View newest version in sPHENIX GitHub at line 37 of file ObjTrackingGeometryWriter.cpp
References ACTS_DEBUG, Acts::GeometryView3D::drawTrackingVolume(), ActsExamples::AlgorithmContext::geoContext, and m_cfg().
Member Data Documentation
Config ActsExamples::ObjTrackingGeometryWriter::m_cfg private
the config class
Definition at line 72 of file ObjTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 72 of file ObjTrackingGeometryWriter.hpp
std::unique_ptr<const Acts::Logger> ActsExamples::ObjTrackingGeometryWriter::m_logger private
the logger instance
Definition at line 70 of file ObjTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 70 of file ObjTrackingGeometryWriter.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Io/Obj/include/ActsExamples/Plugins/Obj/ObjTrackingGeometryWriter.hpp
acts/blob/sPHENIX/Examples/Io/Obj/src/ObjTrackingGeometryWriter.cpp