Analysis Software: Acts::VolumeBoundsJsonConverter Namespace Reference
Acts::VolumeBoundsJsonConverter Namespace Reference
Functions
nlohmann::json toJson (const VolumeBounds &bounds)
template<typename bounds_t >
std::unique_ptr< bounds_t > fromJson (const nlohmann::json &jVolumeBounds)
The Transform converter from json.
Function Documentation
template<typename bounds_t > std::unique_ptr< Acts::VolumeBounds > Acts::VolumeBoundsJsonConverter::fromJson (const nlohmann::json & jVolumeBounds)
The Transform converter from json.
The Surface converter from json.
Convert the single delegate if it is of the type of the reference.
Conversion to volume bounds from json
The type is given as a template argument in order to be able to construct the correct fitting types for surfaces.
Parameters
jVolumeBounds the read-in json object
Returns
a unique_ptr to a volume bounds object for type polymorphism
Conversion to volume bounds from json
Parameters
jVolumeBounds the read-in json object
Returns
a unique_ptr to a volume bounds object for type polymorphism
Unroll the types
Definition at line 50 of file VolumeBoundsJsonConverter.hpp.
View newest version in sPHENIX GitHub at line 50 of file VolumeBoundsJsonConverter.hpp
References bins, Acts::from_json(), Acts::Transform3JsonConverter::fromJson(), grid(), j, std::tr1::make_tuple(), testing::internal::move(), t, throw_assert, to_string(), Acts::Test::transform, Acts::Experimental::tryAllPortalsAndSurfaces(), and physmon_ckf_tracking::u.
Referenced by BOOST_AUTO_TEST_CASE(), Acts::from_json(), Acts::DetectorJsonConverter::fromJson(), Acts::DetectorVolumeJsonConverter::fromJson(), Acts::PortalJsonConverter::fromJson(), Acts::SurfaceJsonConverter::fromJson(), Acts::IndexedSurfacesJsonConverter::fromJson(), ActsExamples::JsonSurfacesReader::read(), and Acts::surfaceFromJsonT().
nlohmann::json Acts::VolumeBoundsJsonConverter::toJson (const VolumeBounds & bounds)
Conversion to Json from volume bounds
Parameters
bounds is the bounds object
Returns
the json object
Definition at line 27 of file VolumeBoundsJsonConverter.cpp.
View newest version in sPHENIX GitHub at line 27 of file VolumeBoundsJsonConverter.cpp
Referenced by BOOST_AUTO_TEST_CASE().