Analysis Software: Acts::detail::VoidNavigator Struct Reference
Acts::detail::VoidNavigator Struct Reference
The void navigator struct as a default navigator.
#include <acts/blob/sPHENIX/Core/include/Acts/Propagator/detail/VoidPropagatorComponents.hpp>
Classes
struct State
Nested State struct, minimal requirement.
Public Types
using state_type = State
Unique typedef to publish to the Propagator.
Public Member Functions
State makeState (const Surface *startSurface, const Surface *targetSurface) const
const Surface * currentSurface (const State &state) const
const Surface * startSurface (const State &state) const
const Surface * targetSurface (const State &state) const
bool targetReached (const State &state) const
bool navigationBreak (const State &state) const
void currentSurface (State &state, const Surface *surface) const
void targetReached (State &state, bool targetReached) const
void navigationBreak (State &state, bool navigationBreak) const
template<typename propagator_state_t , typename stepper_t >
void initialize (propagator_state_t &, const stepper_t &) const
template<typename propagator_state_t , typename stepper_t >
void preStep (propagator_state_t &, const stepper_t &) const
template<typename propagator_state_t , typename stepper_t >
void postStep (propagator_state_t &, const stepper_t &) const
Detailed Description
The void navigator struct as a default navigator.
It does not provide any navigation action, the compiler should eventually optimise that the function call is not done
Definition at line 19 of file VoidPropagatorComponents.hpp.
View newest version in sPHENIX GitHub at line 19 of file VoidPropagatorComponents.hpp
Member Typedef Documentation
using Acts::detail::VoidNavigator::state_type = State
Unique typedef to publish to the Propagator.
Definition at line 39 of file VoidPropagatorComponents.hpp.
View newest version in sPHENIX GitHub at line 39 of file VoidPropagatorComponents.hpp
Member Function Documentation
const Surface* Acts::detail::VoidNavigator::currentSurface (const State & state) const inline
Definition at line 49 of file VoidPropagatorComponents.hpp.
View newest version in sPHENIX GitHub at line 49 of file VoidPropagatorComponents.hpp
References Acts::detail::VoidNavigator::State::currentSurface.
void Acts::detail::VoidNavigator::currentSurface (State & state, const Surface * surface) const inline
Definition at line 67 of file VoidPropagatorComponents.hpp.
View newest version in sPHENIX GitHub at line 67 of file VoidPropagatorComponents.hpp
References Acts::detail::VoidNavigator::State::currentSurface, and writeMapConfig::surface.
template<typename propagator_state_t , typename stepper_t > void Acts::detail::VoidNavigator::initialize (propagator_state_t & , const stepper_t &) const inline
Navigation call - void
Template Parameters
propagator_state_t is the type of Propagatgor state
stepper_t Type of the Stepper
Empty call, compiler should optimise that
Definition at line 86 of file VoidPropagatorComponents.hpp.
View newest version in sPHENIX GitHub at line 86 of file VoidPropagatorComponents.hpp
State Acts::detail::VoidNavigator::makeState (const Surface * startSurface, const Surface * targetSurface) const inline
Definition at line 41 of file VoidPropagatorComponents.hpp.
View newest version in sPHENIX GitHub at line 41 of file VoidPropagatorComponents.hpp
References Acts::detail::VoidNavigator::State::startSurface, startSurface(), Acts::detail::VoidNavigator::State::targetSurface, and targetSurface().
bool Acts::detail::VoidNavigator::navigationBreak (const State & state) const inline
Definition at line 63 of file VoidPropagatorComponents.hpp.
View newest version in sPHENIX GitHub at line 63 of file VoidPropagatorComponents.hpp
References Acts::detail::VoidNavigator::State::navigationBreak.
Referenced by navigationBreak().
void Acts::detail::VoidNavigator::navigationBreak (State & state, bool navigationBreak) const inline
Definition at line 75 of file VoidPropagatorComponents.hpp.
View newest version in sPHENIX GitHub at line 75 of file VoidPropagatorComponents.hpp
References Acts::detail::VoidNavigator::State::navigationBreak, and navigationBreak().
template<typename propagator_state_t , typename stepper_t > void Acts::detail::VoidNavigator::postStep (propagator_state_t & , const stepper_t &) const inline
Navigation call - void
Template Parameters
propagator_state_t is the type of Propagatgor state
stepper_t Type of the Stepper
Empty call, compiler should optimise that
Definition at line 106 of file VoidPropagatorComponents.hpp.
View newest version in sPHENIX GitHub at line 106 of file VoidPropagatorComponents.hpp
template<typename propagator_state_t , typename stepper_t > void Acts::detail::VoidNavigator::preStep (propagator_state_t & , const stepper_t &) const inline
Navigation call - void
Template Parameters
propagator_state_t is the type of Propagatgor state
stepper_t Type of the Stepper
Empty call, compiler should optimise that
Definition at line 96 of file VoidPropagatorComponents.hpp.
View newest version in sPHENIX GitHub at line 96 of file VoidPropagatorComponents.hpp
const Surface* Acts::detail::VoidNavigator::startSurface (const State & state) const inline
Definition at line 53 of file VoidPropagatorComponents.hpp.
View newest version in sPHENIX GitHub at line 53 of file VoidPropagatorComponents.hpp
References Acts::detail::VoidNavigator::State::startSurface.
Referenced by makeState().
bool Acts::detail::VoidNavigator::targetReached (const State & state) const inline
Definition at line 61 of file VoidPropagatorComponents.hpp.
View newest version in sPHENIX GitHub at line 61 of file VoidPropagatorComponents.hpp
References Acts::detail::VoidNavigator::State::targetReached.
Referenced by targetReached().
void Acts::detail::VoidNavigator::targetReached (State & state, bool targetReached) const inline
Definition at line 71 of file VoidPropagatorComponents.hpp.
View newest version in sPHENIX GitHub at line 71 of file VoidPropagatorComponents.hpp
References Acts::detail::VoidNavigator::State::targetReached, and targetReached().
const Surface* Acts::detail::VoidNavigator::targetSurface (const State & state) const inline
Definition at line 57 of file VoidPropagatorComponents.hpp.
View newest version in sPHENIX GitHub at line 57 of file VoidPropagatorComponents.hpp
References Acts::detail::VoidNavigator::State::targetSurface.
Referenced by makeState().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Propagator/detail/VoidPropagatorComponents.hpp