Analysis Software: Fun4AllInputManager Class Reference
Fun4AllInputManager Class Reference
#include <coresoftware/blob/master/offline/framework/fun4all/Fun4AllInputManager.h>
Public Member Functions
~Fun4AllInputManager () override
virtual int fileopen (const std::string &)
virtual int fileclose ()
virtual int run (const int)
virtual int ReadInRunNode (PHCompositeNode *)
std::string FileName () const
void FileName (const std::string &fn)
virtual int GetSyncObject (SyncObject **)
virtual int SyncIt (const SyncObject *)
virtual int BranchSelect (const std::string &, const int)
virtual int setBranches ()
void Print (const std::string &what="ALL") const override
virtual int PushBackEvents (const int)
virtual int skip (const int nevt)
virtual int NoSyncPushBackEvents (const int)
int AddFile (const std::string &filename)
int AddListFile (const std::string &filename, const int do_it=0)
int registerSubsystem (SubsysReco *subsystem)
virtual int RejectEvent ()
void Repeat (const int i=-1)
virtual void setSyncManager (Fun4AllSyncManager *master)
virtual int ResetFileList ()
virtual int ResetEvent ()
virtual void SetRunNumber (const int runno)
virtual int RunNumber () const
void AddToFileOpened (const std::string &filename)
std::pair< std::list
< std::string >
::const_iterator, std::list
< std::string >
::const_iterator > FileOpenListBeginEnd ()
std::string InputNode ()
void InputNode (const std::string &innode)
std::string TopNodeName () const
bool FileListEmpty () const
virtual int IsOpen () const
virtual int SkipForThisManager (const int)
virtual int HasSyncObject () const
virtual std::string GetString (const std::string &) const
const std::list< std::string > GetFileList () const
const std::list< std::string > GetFileOpenedList () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
Fun4AllInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
void UpdateFileList ()
int OpenNextFile ()
void IsOpen (const int i)
Fun4AllSyncManager * MySyncManager ()
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Private Attributes
Fun4AllSyncManager * m_MySyncManager = nullptr
int m_IsOpen = 0
int m_Repeat = 0
int m_MyRunNumber = 0
int m_InitRun = 0
std::vector< SubsysReco * > m_SubsystemsVector
std::string m_InputNode
std::string m_FileName
std::string m_TopNodeName
std::list< std::string > m_FileList
std::list< std::string > m_FileListCopy
std::list< std::string > m_FileListOpened
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Detailed Description
Definition at line 20 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 20 of file Fun4AllInputManager.h
Constructor & Destructor Documentation
Fun4AllInputManager::~Fun4AllInputManager () override
Definition at line 22 of file Fun4AllInputManager.cc.
View newest version in sPHENIX GitHub at line 22 of file Fun4AllInputManager.cc
References m_SubsystemsVector, and Fun4AllBase::Verbosity().
Fun4AllInputManager::Fun4AllInputManager (const std::string & name = "DUMMY", const std::string & nodename = "DST", const std::string & topnodename = "TOP") protected
Definition at line 14 of file Fun4AllInputManager.cc.
View newest version in sPHENIX GitHub at line 14 of file Fun4AllInputManager.cc
Member Function Documentation
int Fun4AllInputManager::AddFile (const std::string & filename)
Definition at line 35 of file Fun4AllInputManager.cc.
View newest version in sPHENIX GitHub at line 35 of file Fun4AllInputManager.cc
References m_FileList, m_FileListCopy, Fun4AllBase::Name(), and Fun4AllBase::Verbosity().
Referenced by AddListFile(), dst_simple_towerslope_runmacro(), Fun4All_CaloProduction_PreQM23(), Fun4All_CaloTreeGen(), Fun4All_EMCalBadTowerID(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_GeoExtract(), Fun4All_hijbkg(), Fun4All_RTrack(), Fun4All_single_particle(), Fun4All_testingGround(), Fun4All_TPC_EventDisplayPrep(), Fun4All_TPC_UnpackPRDF(), Fun4All_TrkrClusteringSeeding(), Fun4All_TrkrHitSet_Unpacker(), Fun4All_Year1(), hcal_toweridmacro(), InputManagers(), Jin_BJet(), run(), Run_BbcCheck(), runall(), runanajpsi(), runanapythiaupsilon(), RunBDiJetModule(), RunBJetModule(), rundata(), RunGenFitTrackProp(), runmb(), runpairs(), srundst_mdc2_clustest(), toweridmacro(), and wholeIter_Pi0EtaByEta().
int Fun4AllInputManager::AddListFile (const std::string & filename, const int do_it = 0)
Definition at line 47 of file Fun4AllInputManager.cc.
View newest version in sPHENIX GitHub at line 47 of file Fun4AllInputManager.cc
References AddFile(), Acts::Concepts::exists, in, infile, Fun4AllBase::Name(), PHWHERE, and Fun4AllBase::Verbosity().
Referenced by dst_simple_towerslope_runmacro(), Fun4All(), Fun4All_Calo(), Fun4All_CaloTreeGen(), Fun4All_EMCal(), Fun4All_EMCal_Hist(), Fun4All_EMCal_sp(), Fun4All_EMCalLikelihood(), Fun4All_EMJetVal(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Pi0_Tbt(), Fun4All_G4_SlopeCal(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_HCalCalib_sim(), Fun4All_IsolatedTrackAnalysis(), Fun4All_JetAna_MDC(), Fun4All_JetBkgd(), Fun4All_JetBkgd_Embed(), Fun4All_JetNconst(), Fun4All_JetRhoMedian(), Fun4All_JetSeedCount(), Fun4All_JetSub(), Fun4All_JetVal(), Fun4All_LEDTowerBuilder(), Fun4All_MBDTreeGen(), Fun4All_MDCTreeMaker(), Fun4All_pythiaEMCalAna(), Fun4All_quickHijing_Prod(), Fun4All_RhoFluct(), Fun4All_TestBeam_HCAL_SampleFrac(), Fun4All_TestBeam_HCAL_TowerCalib(), Fun4All_TestBeam_ShowerCalib(), Fun4All_testEtIso_Hijing(), Fun4All_testEtIso_Pythia(), Fun4All_UE_v2_Psi2(), G4_HIJetReco(), InputManagers(), MakeShowerSize(), run(), Run_BbcCheck(), runanae(), runanaK(), runanapi(), RunBDiJetModule(), RunBJetModule(), RunGenFitTrackProp(), towerslope_dst_runner(), tsdst_plus_tsfit(), wholeIter_Pi0EtaByEta(), and Wrapper().
void Fun4AllInputManager::AddToFileOpened (const std::string & filename) inline
Definition at line 50 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 50 of file Fun4AllInputManager.h
References m_FileListOpened.
Referenced by Fun4AllDstInputManager::fileopen(), Fun4AllPrdfInputManager::fileopen(), Fun4AllOscarInputManager::fileopen(), Fun4AllHepMCInputManager::fileopen(), Fun4AllDstPileupInputManager::fileopen(), and Fun4AllSingleDstPileupInputManager::fileopen().
virtual int Fun4AllInputManager::BranchSelect (const std::string & , const int) inline virtual
Reimplemented in Fun4AllDstPileupInputManager, Fun4AllSingleDstPileupInputManager, and Fun4AllDstInputManager.
Definition at line 32 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 32 of file Fun4AllInputManager.h
virtual int Fun4AllInputManager::fileclose () inline virtual
Reimplemented in Fun4AllStreamingInputManager, Fun4AllDstPileupInputManager, Fun4AllSingleDstPileupInputManager, Fun4AllHepMCInputManager, Fun4AllPrdfInputPoolManager, Fun4AllOscarInputManager, Fun4AllPrdfInputManager, Fun4AllDstInputManager, and Fun4AllDummyInputManager.
Definition at line 25 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 25 of file Fun4AllInputManager.h
bool Fun4AllInputManager::FileListEmpty () const inline
Definition at line 55 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 55 of file Fun4AllInputManager.h
References m_FileList.
Referenced by Fun4AllDstInputManager::run(), Fun4AllRunNodeInputManager::run(), Fun4AllHepMCPileupInputManager::run(), Fun4AllPrdfInputManager::run(), Fun4AllOscarInputManager::run(), Fun4AllHepMCInputManager::run(), Fun4AllSingleDstPileupInputManager::run(), and Fun4AllDstPileupInputManager::runOne().
std::string Fun4AllInputManager::FileName () const inline
Definition at line 28 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 28 of file Fun4AllInputManager.h
References m_FileName.
Referenced by Fun4AllDstInputManager::fileopen(), Fun4AllPrdfInputManager::fileopen(), Fun4AllRunNodeInputManager::fileopen(), Fun4AllSingleDstPileupInputManager::fileopen(), Fun4AllDstPileupInputManager::fileopen(), and Fun4AllDummyInputManager::Fun4AllDummyInputManager().
void Fun4AllInputManager::FileName (const std::string & fn) inline
Definition at line 29 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 29 of file Fun4AllInputManager.h
References m_FileName.
virtual int Fun4AllInputManager::fileopen (const std::string &) inline virtual
Reimplemented in Fun4AllStreamingInputManager, Fun4AllDstPileupInputManager, Fun4AllSingleDstPileupInputManager, Fun4AllHepMCInputManager, Fun4AllPrdfInputPoolManager, Fun4AllOscarInputManager, Fun4AllRunNodeInputManager, Fun4AllDstInputManager, Fun4AllDummyInputManager, and Fun4AllPrdfInputManager.
Definition at line 24 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 24 of file Fun4AllInputManager.h
Referenced by clus_dst_simple_superfastcalib(), ConfigureInput(), dst_simple_towerslope_runmacro(), Fun4All_Analysis(), Fun4All_AnaTutorial_DSTReadBack(), Fun4All_CaloAna(), Fun4All_CaloProduction(), Fun4All_CaloWaveFormSim(), Fun4All_CentralityValidation(), Fun4All_Condor(), Fun4All_EICAnalysis_DIS(), Fun4All_EICAnalysis_DISReco(), Fun4All_EICAnalysis_DVCS(), Fun4All_EICAnalysis_Exclusive(), Fun4All_EICAnalysis_Leptoquarks(), Fun4All_EICAnalysis_Quarkonia(), Fun4All_EICAnalysis_TrackEval(), Fun4All_ExportGeom(), Fun4All_FillChargesMap_300evts_MDC2(), Fun4All_FillDCMap(), Fun4All_G4_Clusters(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_analysis(), Fun4All_G4_EICDetector_LQ_analysis_nf(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_HCalCalib(), Fun4All_JetAna(), Fun4All_PRDF(), Fun4All_Read_Dst(), Fun4All_RICHReco(), Fun4All_single_particle(), Fun4All_Templates(), Fun4All_TestBeam(), Fun4All_TestBeam_Ana(), Fun4All_TestBeam_ExampleAnalysisModule(), Fun4All_TestBeam_HCAL_ShowerCalib(), Fun4All_TestBeam_TPC(), G4TTree(), InputManagers(), Jin_BJet(), MakeEdepNtuple(), MakeHijingCountNtuple(), MakeHijingShowerSize(), MakeHitCountNtuple(), MakeShowerSize(), MakeSigmaTimingNtuple(), MakeTimingNtuple(), MakeTowerTiming(), MyHitTTree(), OpenNextFile(), PHGeom_DSTInspection(), ReadFieldMap(), run_macro(), run_macro_2(), towerslope_dst_runner(), tsdst_plus_tsfit(), and wholeIter_Pi0EtaByEta().
std::pair<std::list<std::string>::const_iterator, std::list<std::string>::const_iterator> Fun4AllInputManager::FileOpenListBeginEnd () inline
Definition at line 51 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 51 of file Fun4AllInputManager.h
References m_FileListOpened.
const std::list<std::string> Fun4AllInputManager::GetFileList () const inline
Definition at line 60 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 60 of file Fun4AllInputManager.h
References m_FileListCopy.
Referenced by OnCalServer::FillRunListFromFileList(), and OnCalServer::Print().
const std::list<std::string> Fun4AllInputManager::GetFileOpenedList () const inline
Definition at line 61 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 61 of file Fun4AllInputManager.h
References m_FileListOpened.
Referenced by OnCalServer::End().
virtual std::string Fun4AllInputManager::GetString (const std::string &) const inline virtual
Reimplemented in Fun4AllStreamingInputManager, Fun4AllPrdfInputPoolManager, and Fun4AllPrdfInputManager.
Definition at line 59 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 59 of file Fun4AllInputManager.h
Referenced by EventCombiner::AddPrdfInputNodeFromManager().
virtual int Fun4AllInputManager::GetSyncObject (SyncObject **) inline virtual
Reimplemented in Fun4AllStreamingInputManager, Fun4AllHepMCInputManager, Fun4AllDstPileupInputManager, Fun4AllSingleDstPileupInputManager, Fun4AllOscarInputManager, Fun4AllPrdfInputPoolManager, Fun4AllPrdfInputManager, Fun4AllRunNodeInputManager, Fun4AllNoSyncDstInputManager, Fun4AllDummyInputManager, and Fun4AllDstInputManager.
Definition at line 30 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 30 of file Fun4AllInputManager.h
virtual int Fun4AllInputManager::HasSyncObject () const inline virtual
Reimplemented in Fun4AllStreamingInputManager, Fun4AllPrdfInputPoolManager, Fun4AllNoSyncDstInputManager, Fun4AllRunNodeInputManager, Fun4AllPrdfInputManager, and Fun4AllDstInputManager.
Definition at line 58 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 58 of file Fun4AllInputManager.h
std::string Fun4AllInputManager::InputNode () inline
Definition at line 52 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 52 of file Fun4AllInputManager.h
References m_InputNode.
Referenced by Fun4AllDstInputManager::fileopen(), Fun4AllDstPileupInputManager::fileopen(), Fun4AllSingleDstPileupInputManager::fileopen(), Fun4AllHepMCInputManager::Fun4AllHepMCInputManager(), Fun4AllOscarInputManager::Fun4AllOscarInputManager(), and Fun4AllDstPileupInputManager::run().
void Fun4AllInputManager::InputNode (const std::string & innode) inline
Definition at line 53 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 53 of file Fun4AllInputManager.h
References m_InputNode.
virtual int Fun4AllInputManager::IsOpen () const inline virtual
Reimplemented in Fun4AllDummyInputManager.
Definition at line 56 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 56 of file Fun4AllInputManager.h
References m_IsOpen.
Referenced by Fun4AllDstInputManager::BranchSelect(), Fun4AllDstInputManager::fileclose(), Fun4AllPrdfInputManager::fileclose(), Fun4AllOscarInputManager::fileclose(), Fun4AllHepMCInputManager::fileclose(), Fun4AllDstPileupInputManager::fileclose(), Fun4AllSingleDstPileupInputManager::fileclose(), Fun4AllDstInputManager::fileopen(), Fun4AllPrdfInputManager::fileopen(), Fun4AllRunNodeInputManager::fileopen(), Fun4AllOscarInputManager::fileopen(), Fun4AllHepMCInputManager::fileopen(), Fun4AllDstPileupInputManager::fileopen(), Fun4AllSingleDstPileupInputManager::fileopen(), Fun4AllDstInputManager::HasSyncObject(), Fun4AllNoSyncDstInputManager::NoRunTTree(), Fun4AllHepMCInputManager::PushBackEvents(), Fun4AllDstInputManager::run(), Fun4AllRunNodeInputManager::run(), Fun4AllPrdfInputManager::run(), Fun4AllHepMCPileupInputManager::run(), Fun4AllOscarInputManager::run(), Fun4AllHepMCInputManager::run(), Fun4AllSingleDstPileupInputManager::run(), Fun4AllDstPileupInputManager::runOne(), Fun4AllPrdfInputManager::~Fun4AllPrdfInputManager(), Fun4AllPrdfInputPoolManager::~Fun4AllPrdfInputPoolManager(), and Fun4AllStreamingInputManager::~Fun4AllStreamingInputManager().
void Fun4AllInputManager::IsOpen (const int i) inline protected
Definition at line 67 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 67 of file Fun4AllInputManager.h
References i, and m_IsOpen.
Fun4AllSyncManager* Fun4AllInputManager::MySyncManager () inline protected
Definition at line 68 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 68 of file Fun4AllInputManager.h
References m_MySyncManager.
Referenced by Fun4AllOscarInputManager::fileopen(), Fun4AllHepMCInputManager::fileopen(), Fun4AllDummyInputManager::run(), Fun4AllPrdfInputManager::run(), Fun4AllHepMCInputManager::run(), and Fun4AllDummyInputManager::setSyncManager().
virtual int Fun4AllInputManager::NoSyncPushBackEvents (const int) inline virtual
Reimplemented in Fun4AllHepMCInputManager, Fun4AllDstPileupInputManager, Fun4AllSingleDstPileupInputManager, Fun4AllOscarInputManager, Fun4AllRunNodeInputManager, Fun4AllDummyInputManager, and Fun4AllNoSyncDstInputManager.
Definition at line 39 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 39 of file Fun4AllInputManager.h
int Fun4AllInputManager::OpenNextFile () protected
Definition at line 213 of file Fun4AllInputManager.cc.
View newest version in sPHENIX GitHub at line 213 of file Fun4AllInputManager.cc
References fileopen(), m_FileList, PHWHERE, and Fun4AllBase::Verbosity().
Referenced by Fun4AllDstInputManager::ReadNextEventSyncObject(), Fun4AllDstInputManager::run(), Fun4AllRunNodeInputManager::run(), Fun4AllHepMCPileupInputManager::run(), Fun4AllPrdfInputManager::run(), Fun4AllOscarInputManager::run(), Fun4AllHepMCInputManager::run(), Fun4AllSingleDstPileupInputManager::run(), and Fun4AllDstPileupInputManager::runOne().
void Fun4AllInputManager::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Reimplemented in Fun4AllStreamingInputManager, Fun4AllDstPileupInputManager, Fun4AllSingleDstPileupInputManager, Fun4AllPrdfInputPoolManager, and Fun4AllPrdfInputManager.
Definition at line 112 of file Fun4AllInputManager.cc.
View newest version in sPHENIX GitHub at line 112 of file Fun4AllInputManager.cc
References file, m_FileList, m_SubsystemsVector, and Fun4AllBase::Name().
Referenced by Fun4AllPrdfInputManager::Print(), Fun4AllDstInputManager::Print(), Fun4AllOscarInputManager::Print(), Fun4AllHepMCInputManager::Print(), Fun4AllSingleDstPileupInputManager::Print(), Fun4AllDstPileupInputManager::Print(), and Fun4AllStreamingInputManager::Print().
virtual int Fun4AllInputManager::PushBackEvents (const int) inline virtual
Reimplemented in Fun4AllStreamingInputManager, Fun4AllHepMCPileupInputManager, Fun4AllDstPileupInputManager, Fun4AllSingleDstPileupInputManager, Fun4AllHepMCInputManager, Fun4AllPrdfInputPoolManager, Fun4AllOscarInputManager, Fun4AllRunNodeInputManager, Fun4AllDstInputManager, Fun4AllPrdfInputManager, and Fun4AllDummyInputManager.
Definition at line 35 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 35 of file Fun4AllInputManager.h
Referenced by skip().
virtual int Fun4AllInputManager::ReadInRunNode (PHCompositeNode *) inline virtual
Definition at line 27 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 27 of file Fun4AllInputManager.h
int Fun4AllInputManager::registerSubsystem (SubsysReco * subsystem)
Definition at line 141 of file Fun4AllInputManager.cc.
View newest version in sPHENIX GitHub at line 141 of file Fun4AllInputManager.cc
References SubsysReco::Init(), Fun4AllServer::instance(), m_SubsystemsVector, m_TopNodeName, Fun4AllBase::Name(), PHWHERE, Fun4AllServer::topNode(), and Fun4AllBase::Verbosity().
int Fun4AllInputManager::RejectEvent () virtual
Definition at line 159 of file Fun4AllInputManager.cc.
View newest version in sPHENIX GitHub at line 159 of file Fun4AllInputManager.cc
References Fun4AllReturnCodes::DISCARDEVENT, Fun4AllReturnCodes::EVENT_OK, Fun4AllServer::instance(), m_InitRun, m_SubsystemsVector, m_TopNodeName, Fun4AllBase::Name(), Fun4AllServer::topNode(), and Fun4AllBase::Verbosity().
Referenced by Fun4AllDstInputManager::run(), Fun4AllHepMCPileupInputManager::run(), Fun4AllPrdfInputManager::run(), Fun4AllOscarInputManager::run(), Fun4AllHepMCInputManager::run(), Fun4AllSingleDstPileupInputManager::run(), and Fun4AllDstPileupInputManager::runOne().
void Fun4AllInputManager::Repeat (const int i = -1) inline
Definition at line 44 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 44 of file Fun4AllInputManager.h
References i, and m_Repeat.
Referenced by Fun4AllHepMCPileupInputManager::Fun4AllHepMCPileupInputManager(), and InputManagers().
virtual int Fun4AllInputManager::ResetEvent () inline virtual
Reimplemented in Fun4AllStreamingInputManager, Fun4AllHepMCInputManager, Fun4AllPrdfInputPoolManager, Fun4AllOscarInputManager, Fun4AllPrdfInputManager, and Fun4AllHepMCPileupInputManager.
Definition at line 47 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 47 of file Fun4AllInputManager.h
int Fun4AllInputManager::ResetFileList () virtual
Reimplemented in Fun4AllDummyInputManager.
Definition at line 184 of file Fun4AllInputManager.cc.
View newest version in sPHENIX GitHub at line 184 of file Fun4AllInputManager.cc
References m_FileList, m_FileListCopy, and Fun4AllBase::Name().
virtual int Fun4AllInputManager::run (const int) inline virtual
Reimplemented in Fun4AllStreamingInputManager, Fun4AllDstPileupInputManager, Fun4AllSingleDstPileupInputManager, Fun4AllHepMCInputManager, Fun4AllPrdfInputPoolManager, Fun4AllOscarInputManager, Fun4AllPrdfInputManager, Fun4AllDummyInputManager, Fun4AllRunNodeInputManager, Fun4AllHepMCPileupInputManager, and Fun4AllDstInputManager.
Definition at line 26 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 26 of file Fun4AllInputManager.h
virtual int Fun4AllInputManager::RunNumber () const inline virtual
Definition at line 49 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 49 of file Fun4AllInputManager.h
References m_MyRunNumber.
virtual int Fun4AllInputManager::setBranches () inline virtual
Reimplemented in Fun4AllDstPileupInputManager, Fun4AllSingleDstPileupInputManager, and Fun4AllDstInputManager.
Definition at line 33 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 33 of file Fun4AllInputManager.h
virtual void Fun4AllInputManager::SetRunNumber (const int runno) inline virtual
Definition at line 48 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 48 of file Fun4AllInputManager.h
References m_MyRunNumber.
Referenced by Fun4AllDstInputManager::fileopen(), Fun4AllRunNodeInputManager::fileopen(), Fun4AllSingleDstPileupInputManager::fileopen(), Fun4AllDstPileupInputManager::fileopen(), Fun4AllStreamingInputManager::FillGl1(), Fun4AllStreamingInputManager::FillInttPool(), Fun4AllStreamingInputManager::FillMicromegasPool(), Fun4AllStreamingInputManager::FillMvtxPool(), Fun4AllStreamingInputManager::FillTpcPool(), Fun4AllPrdfInputManager::run(), and Fun4AllPrdfInputPoolManager::run().
virtual void Fun4AllInputManager::setSyncManager (Fun4AllSyncManager * master) inline virtual
Reimplemented in Fun4AllDummyInputManager.
Definition at line 45 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 45 of file Fun4AllInputManager.h
References m_MySyncManager.
Referenced by Fun4AllSyncManager::registerInputManager(), and Fun4AllDummyInputManager::setSyncManager().
virtual int Fun4AllInputManager::skip (const int nevt) inline virtual
Reimplemented in Fun4AllOscarInputManager.
Definition at line 38 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 38 of file Fun4AllInputManager.h
References PushBackEvents().
virtual int Fun4AllInputManager::SkipForThisManager (const int) inline virtual
Reimplemented in Fun4AllHepMCInputManager, Fun4AllHepMCPileupInputManager, Fun4AllNoSyncDstInputManager, and Fun4AllRunNodeInputManager.
Definition at line 57 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 57 of file Fun4AllInputManager.h
virtual int Fun4AllInputManager::SyncIt (const SyncObject *) inline virtual
Reimplemented in Fun4AllStreamingInputManager, Fun4AllHepMCInputManager, Fun4AllDstPileupInputManager, Fun4AllSingleDstPileupInputManager, Fun4AllOscarInputManager, Fun4AllPrdfInputPoolManager, Fun4AllPrdfInputManager, Fun4AllRunNodeInputManager, Fun4AllDummyInputManager, Fun4AllDstInputManager, and Fun4AllNoSyncDstInputManager.
Definition at line 31 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 31 of file Fun4AllInputManager.h
References Fun4AllReturnCodes::SYNC_FAIL.
std::string Fun4AllInputManager::TopNodeName () const inline
Definition at line 54 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 54 of file Fun4AllInputManager.h
References m_TopNodeName.
Referenced by Fun4AllDstInputManager::fileopen(), Fun4AllRunNodeInputManager::fileopen(), Fun4AllSingleDstPileupInputManager::fileopen(), Fun4AllDstPileupInputManager::fileopen(), Fun4AllPrdfInputManager::Fun4AllPrdfInputManager(), Fun4AllPrdfInputPoolManager::Fun4AllPrdfInputPoolManager(), Fun4AllStreamingInputManager::Fun4AllStreamingInputManager(), and Fun4AllDstPileupInputManager::run().
void Fun4AllInputManager::UpdateFileList () protected
Definition at line 196 of file Fun4AllInputManager.cc.
View newest version in sPHENIX GitHub at line 196 of file Fun4AllInputManager.cc
References m_FileList, and m_Repeat.
Referenced by Fun4AllDstInputManager::fileclose(), Fun4AllPrdfInputManager::fileclose(), Fun4AllOscarInputManager::fileclose(), Fun4AllHepMCInputManager::fileclose(), Fun4AllDstPileupInputManager::fileclose(), and Fun4AllSingleDstPileupInputManager::fileclose().
Member Data Documentation
std::list<std::string> Fun4AllInputManager::m_FileList private
Definition at line 80 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 80 of file Fun4AllInputManager.h
Referenced by AddFile(), FileListEmpty(), OpenNextFile(), Print(), ResetFileList(), and UpdateFileList().
std::list<std::string> Fun4AllInputManager::m_FileListCopy private
Definition at line 81 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 81 of file Fun4AllInputManager.h
Referenced by AddFile(), GetFileList(), and ResetFileList().
std::list<std::string> Fun4AllInputManager::m_FileListOpened private
Definition at line 82 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 82 of file Fun4AllInputManager.h
Referenced by AddToFileOpened(), FileOpenListBeginEnd(), and GetFileOpenedList().
std::string Fun4AllInputManager::m_FileName private
Definition at line 78 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 78 of file Fun4AllInputManager.h
Referenced by FileName().
int Fun4AllInputManager::m_InitRun = 0 private
Definition at line 75 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 75 of file Fun4AllInputManager.h
Referenced by RejectEvent().
std::string Fun4AllInputManager::m_InputNode private
Definition at line 77 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 77 of file Fun4AllInputManager.h
Referenced by InputNode().
int Fun4AllInputManager::m_IsOpen = 0 private
Definition at line 72 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 72 of file Fun4AllInputManager.h
Referenced by IsOpen().
int Fun4AllInputManager::m_MyRunNumber = 0 private
Definition at line 74 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 74 of file Fun4AllInputManager.h
Referenced by RunNumber(), and SetRunNumber().
Fun4AllSyncManager* Fun4AllInputManager::m_MySyncManager = nullptr private
Definition at line 71 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 71 of file Fun4AllInputManager.h
Referenced by MySyncManager(), and setSyncManager().
int Fun4AllInputManager::m_Repeat = 0 private
Definition at line 73 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 73 of file Fun4AllInputManager.h
Referenced by Repeat(), and UpdateFileList().
std::vector<SubsysReco *> Fun4AllInputManager::m_SubsystemsVector private
Definition at line 76 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 76 of file Fun4AllInputManager.h
Referenced by Print(), registerSubsystem(), RejectEvent(), and ~Fun4AllInputManager().
std::string Fun4AllInputManager::m_TopNodeName private
Definition at line 79 of file Fun4AllInputManager.h.
View newest version in sPHENIX GitHub at line 79 of file Fun4AllInputManager.h
Referenced by registerSubsystem(), RejectEvent(), and TopNodeName().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4all/Fun4AllInputManager.h
coresoftware/blob/master/offline/framework/fun4all/Fun4AllInputManager.cc