Analysis Software: Acts::PlyVisualization3D< T > Class Template Reference
Acts::PlyVisualization3D< T > Class Template Reference
Helper to write out PlyVisualization3D visualization format.
#include <acts/blob/sPHENIX/Core/include/Acts/Visualization/PlyVisualization3D.hpp>
Public Types
using ValueType = T
Stored value type, should be double or float.
using VertexType = ActsVector< ValueType, 3 >
Type of a vertex based on the value type.
Public Types inherited from Acts::IVisualization3D
using FaceType = std::vector< size_t >
Public Member Functions
void vertex (const Vector3D &vtx, ColorRGB color={120, 120, 120}) final
void face (const std::vector< Vector3D > &vtxs, ColorRGB color={120, 120, 120}) final
void faces (const std::vector< Vector3D > &vtxs, const std::vector< FaceType > &, ColorRGB color={120, 120, 120}) final
void line (const Vector3D &a, const Vector3D &b, ColorRGB color={120, 120, 120}) final
void write (const std::string &path) const final
void write (std::ostream &os) const final
void clear () final
Public Member Functions inherited from Acts::IVisualization3D
void vertex (const Vector3F &vtx, ColorRGB color={120, 120, 120})
void face (const std::vector< Vector3F > &vtxs, ColorRGB color={120, 120, 120})
void line (const Vector3F &a, const Vector3F &b, ColorRGB color={120, 120, 120})
(const Vector3F&, const Vector3F&,
Private Attributes
std::vector< std::pair
< VertexType, ColorRGB > > m_vertices
std::vector< FaceType > m_faces
std::vector< std::pair
< std::pair< size_t, size_t >
, ColorRGB > > m_edges
Additional Inherited Members
Protected Member Functions inherited from Acts::IVisualization3D
bool hasExtension (const std::string &path) const
void replaceExtension (std::string &path, const std::string &suffix) const
Detailed Description
template<typename T = double>
class Acts::PlyVisualization3D< T >
Helper to write out PlyVisualization3D visualization format.
Definition at line 26 of file PlyVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 26 of file PlyVisualization3D.hpp
Member Typedef Documentation
template<typename T = double> using Acts::PlyVisualization3D< T >::ValueType = T
Stored value type, should be double or float.
Definition at line 32 of file PlyVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 32 of file PlyVisualization3D.hpp
template<typename T = double> using Acts::PlyVisualization3D< T >::VertexType = ActsVector<ValueType, 3>
Type of a vertex based on the value type.
Definition at line 35 of file PlyVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 35 of file PlyVisualization3D.hpp
Member Function Documentation
template<typename T > void Acts::PlyVisualization3D< T >::clear () final virtual
Remove all contents of this helper
Implements Acts::IVisualization3D.
Definition at line 98 of file PlyVisualization3D.ipp.
View newest version in sPHENIX GitHub at line 98 of file PlyVisualization3D.ipp
References Acts::PlyVisualization3D< T >::clear().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::PlyVisualization3D< T >::clear().
template<typename T > void Acts::PlyVisualization3D< T >::face (const std::vector< Vector3D > & vtxs, ColorRGB color = {120, 120, 120}) final virtual
Draw a line from a vertex to another
Parameters
a The start vertex
b The end vertex
color The color of the line
Implements Acts::IVisualization3D.
Definition at line 15 of file PlyVisualization3D.ipp.
View newest version in sPHENIX GitHub at line 15 of file PlyVisualization3D.ipp
References testing::internal::move().
template<typename T > void Acts::PlyVisualization3D< T >::faces (const std::vector< Vector3D > & vtxs, const std::vector< FaceType > & , ColorRGB color = {120, 120, 120}) final virtual
Draw a faces that connects a list of vertices - expert only
Note
Depending on the helper implementation, out of plane vertices might be handled differently.
Parameters
vtxs The vertices that make up the faceS
faces The face presectiotions (i.e. connecting vertices)
color The color of the face
Implements Acts::IVisualization3D.
Definition at line 27 of file PlyVisualization3D.ipp.
View newest version in sPHENIX GitHub at line 27 of file PlyVisualization3D.ipp
template<typename T > void Acts::PlyVisualization3D< T >::line (const Vector3D & a, const Vector3D & b, ColorRGB color = {120, 120, 120}) final virtual
Draw a face that connects a list of vertices.
Note
Depending on the helper implementation, out of plane vertices might be handled differently.
Parameters
vtxs The vertices that make up the face
color The color of the face
Implements Acts::IVisualization3D.
Definition at line 34 of file PlyVisualization3D.ipp.
View newest version in sPHENIX GitHub at line 34 of file PlyVisualization3D.ipp
template<typename T > void Acts::PlyVisualization3D< T >::vertex (const Vector3D & vtx, ColorRGB color = {120, 120, 120}) final virtual
Draw a vertex at a given location and a color.
Parameters
vtx The vertex position
color The color
Implements Acts::IVisualization3D.
Definition at line 10 of file PlyVisualization3D.ipp.
View newest version in sPHENIX GitHub at line 10 of file PlyVisualization3D.ipp
template<typename T > void Acts::PlyVisualization3D< T >::write (const std::string & path) const final virtual
Write the content of the helper to an outstream.
Parameters
os The output stream for file
Implements Acts::IVisualization3D.
Definition at line 45 of file PlyVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 45 of file PlyVisualization3D.hpp
template<typename T > void Acts::PlyVisualization3D< T >::write (std::ostream & os) const final virtual
Write the content of the helper to an outstream.
Parameters
os The output stream for file
Implements Acts::IVisualization3D.
Definition at line 57 of file PlyVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 57 of file PlyVisualization3D.hpp
Member Data Documentation
template<typename T = double> std::vector<std::pair<std::pair<size_t, size_t>, ColorRGB> > Acts::PlyVisualization3D< T >::m_edges private
Definition at line 64 of file PlyVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 64 of file PlyVisualization3D.hpp
template<typename T = double> std::vector<FaceType> Acts::PlyVisualization3D< T >::m_faces private
Definition at line 63 of file PlyVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 63 of file PlyVisualization3D.hpp
template<typename T = double> std::vector<std::pair<VertexType, ColorRGB> > Acts::PlyVisualization3D< T >::m_vertices private
Definition at line 62 of file PlyVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 62 of file PlyVisualization3D.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Visualization/PlyVisualization3D.hpp
acts/blob/sPHENIX/Core/include/Acts/Visualization/detail/PlyVisualization3D.ipp