Analysis Software: PHG4SimpleEventGenerator Class Reference
PHG4SimpleEventGenerator Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4SimpleEventGenerator.h>
Public Types
enum FUNCTION { Uniform, Gaus }
supported function distributions
Public Member Functions
PHG4SimpleEventGenerator (const std::string &name="EVTGENERATOR")
~PHG4SimpleEventGenerator () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
void add_particles (const std::string &name, const unsigned int count)
interface for adding particles by name
void add_particles (const int pid, const unsigned int count)
interface for adding particle by pid
void set_eta_range (const double eta_min, const double eta_max)
range of randomized eta values (mutually exclusive with theta range)
void set_theta_range (const double theta_min, const double theta_max)
range of randomized theta values (mutually exclusive with eta range)
void set_phi_range (const double phi_min, const double phi_max)
range of randomized phi values
void set_power_law_n (const double n)
power law value of distribution to sample from for pt values
void set_pt_range (const double pt_min, const double pt_max, const double pt_gaus_width=0)
void set_p_range (const double p_min, const double p_max, const double p_gaus_width=0)
void set_vertex_distribution_function (FUNCTION x, FUNCTION y, FUNCTION z)
toss a new vertex according to a Uniform or Gaus distribution
void set_vertex_distribution_mean (const double x, const double y, const double z)
set the mean value of the vertex distribution
void set_vertex_distribution_width (const double x, const double y, const double z)
set the width of the vertex distribution function about the mean
void set_existing_vertex_offset_vector (const double x, const double y, const double z)
set an offset vector from the existing vertex
void set_vertex_size_function (FUNCTION r)
set the distribution function of particles about the vertex
void set_vertex_size_parameters (const double mean, const double width)
set the dimensions of the distribution of particles about the vertex
Public Member Functions inherited from PHG4ParticleGeneratorBase
~PHG4ParticleGeneratorBase () override
virtual void set_name (const std::string &particle="proton")
virtual void set_pid (const int pid)
virtual void set_mom (const double x, const double y, const double z)
virtual void set_vtx (const double x, const double y, const double z)
virtual void set_vtx_z (const double z)
virtual void set_t0 (const double t)
virtual double get_vtx_x () const
virtual double get_vtx_y () const
virtual double get_vtx_z () const
virtual double get_t0 () const
void Print (const std::string &what="ALL") const override
virtual void PrintParticles (const std::string &what="ALL") const
virtual void AddParticle (const std::string &particle, const double x, const double y, const double z)
virtual void AddParticle (const int pid, const double x, const double y, const double z)
virtual void Embed (const int i=1)
virtual int ReuseExistingVertex (PHCompositeNode *topNode)
int get_reuse_existing_vertex () const
void set_reuse_existing_vertex (const int i=1)
void set_seed (const unsigned int iseed)
unsigned int get_seed () const
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
double smearvtx (const double position, const double width, FUNCTION dist) const
Private Attributes
std::vector< std::pair< int,
unsigned int > > _particle_codes
std::vector< std::pair
< std::string, unsigned int > > _particle_names
std::map< FUNCTION, std::string > m_FunctionNames = {{Uniform, "Uniform"}, {Gaus, "Gaus"}}
PHG4InEvent * m_InEvent = nullptr
FUNCTION m_VertexFunc_x = Uniform
FUNCTION m_VertexFunc_y = Uniform
FUNCTION m_VertexFunc_z = Uniform
double m_Vertex_x = 0.
double m_Vertex_y = 0.
double m_Vertex_z = 0.
double m_VertexWidth_x = 0.
double m_VertexWidth_y = 0.
double m_VertexWidth_z = 0.
double m_VertexOffset_x = 0.
double m_VertexOffset_y = 0.
double m_VertexOffset_z = 0.
FUNCTION m_VertexSizeFunc_r = Uniform
double m_VertexSizeMean = 0.
double m_VertexSizeWidth = 0.
double m_EtaMin = -1.25
double m_EtaMax = 1.25
double m_ThetaMin = NAN
double m_ThetaMax = NAN
double m_PhiMin = -M_PI
double m_PhiMax = M_PI
double m_Pt_Min = 0.
double m_Pt_Max = 10.
double m_Pt_GausWidth = 0.
double m_P_Min = NAN
double m_P_Max = NAN
double m_P_GausWidth = NAN
double m_powerLawN = NAN
Additional Inherited Members
Protected Member Functions inherited from PHG4ParticleGeneratorBase
PHG4ParticleGeneratorBase (const std::string &name="GENERATORBASE")
int get_pdgcode (const std::string &name) const
std::string get_pdgname (const int pdgcode) const
double get_mass (const int pdgcode) const
void CheckAndCreateParticleVector ()
void SetParticleId (PHG4Particle *particle, PHG4InEvent *ineve)
gsl_rng * RandomGenerator () const
int EmbedFlag () const
std::vector< PHG4Particle * >
::iterator particlelist_begin ()
std::vector< PHG4Particle * >
::iterator particlelist_end ()
void ResetParticleList ()
Detailed Description
Definition at line 17 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4SimpleEventGenerator.h
Member Enumeration Documentation
enum PHG4SimpleEventGenerator::FUNCTION
supported function distributions
Enumerator:
Uniform
Gaus
Definition at line 21 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4SimpleEventGenerator.h
Constructor & Destructor Documentation
PHG4SimpleEventGenerator::PHG4SimpleEventGenerator (const std::string & name = "EVTGENERATOR")
Definition at line 29 of file PHG4SimpleEventGenerator.cc.
View newest version in sPHENIX GitHub at line 29 of file PHG4SimpleEventGenerator.cc
PHG4SimpleEventGenerator::~PHG4SimpleEventGenerator () inline override
Definition at line 28 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4SimpleEventGenerator.h
Member Function Documentation
void PHG4SimpleEventGenerator::add_particles (const std::string & name, const unsigned int count)
interface for adding particles by name
Definition at line 35 of file PHG4SimpleEventGenerator.cc.
View newest version in sPHENIX GitHub at line 35 of file PHG4SimpleEventGenerator.cc
References _particle_names.
Referenced by ConfigureInput(), ConstructGeometry(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void PHG4SimpleEventGenerator::add_particles (const int pid, const unsigned int count)
interface for adding particle by pid
Definition at line 41 of file PHG4SimpleEventGenerator.cc.
View newest version in sPHENIX GitHub at line 41 of file PHG4SimpleEventGenerator.cc
References _particle_codes.
int PHG4SimpleEventGenerator::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from PHG4ParticleGeneratorBase.
Definition at line 188 of file PHG4SimpleEventGenerator.cc.
View newest version in sPHENIX GitHub at line 188 of file PHG4SimpleEventGenerator.cc
References _particle_codes, _particle_names, PHCompositeNode::addNode(), test_fpe::count, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHG4ParticleGeneratorBase::get_pdgname(), PHG4ParticleGeneratorBase::get_reuse_existing_vertex(), PHG4ParticleGeneratorBase::get_seed(), PHG4ParticleGeneratorBase::get_t0(), i, m_EtaMax, m_EtaMin, m_FunctionNames, m_InEvent, m_P_Max, m_P_Min, m_PhiMax, m_PhiMin, m_Pt_Max, m_Pt_Min, m_ThetaMax, m_ThetaMin, m_Vertex_x, m_Vertex_y, m_Vertex_z, m_VertexFunc_x, m_VertexFunc_y, m_VertexFunc_z, m_VertexOffset_x, m_VertexOffset_y, m_VertexOffset_z, m_VertexSizeFunc_r, m_VertexSizeMean, m_VertexSizeWidth, m_VertexWidth_x, m_VertexWidth_y, m_VertexWidth_z, PHWHERE, and Fun4AllBase::Verbosity().
int PHG4SimpleEventGenerator::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from PHG4ParticleGeneratorBase.
Definition at line 286 of file PHG4SimpleEventGenerator.cc.
View newest version in sPHENIX GitHub at line 286 of file PHG4SimpleEventGenerator.cc
References _particle_names, PHG4InEvent::AddEmbeddedParticle(), PHG4InEvent::AddParticle(), PHG4InEvent::AddVtx(), Acts::UnitConstants::e, PHG4ParticleGeneratorBase::EmbedFlag(), eta, Fun4AllReturnCodes::EVENT_OK, PHG4Utils::get_eta(), PHG4ParticleGeneratorBase::get_mass(), PHG4ParticleGeneratorBase::get_pdgcode(), PHG4ParticleGeneratorBase::get_reuse_existing_vertex(), PHG4ParticleGeneratorBase::get_t0(), PHG4ParticleGeneratorBase::get_vtx_x(), PHG4ParticleGeneratorBase::get_vtx_y(), PHG4ParticleGeneratorBase::get_vtx_z(), i, PHG4InEvent::identify(), j, Acts::UnitConstants::m, m_EtaMax, m_EtaMin, m_InEvent, m_P_GausWidth, m_P_Max, m_P_Min, m_PhiMax, m_PhiMin, m_powerLawN, m_Pt_GausWidth, m_Pt_Max, m_Pt_Min, m_ThetaMax, m_ThetaMin, m_Vertex_x, m_Vertex_y, m_Vertex_z, m_VertexFunc_x, m_VertexFunc_y, m_VertexFunc_z, m_VertexOffset_x, m_VertexOffset_y, m_VertexOffset_z, m_VertexSizeFunc_r, m_VertexSizeMean, m_VertexSizeWidth, m_VertexWidth_x, m_VertexWidth_y, m_VertexWidth_z, nparticles, particle, ActsTests::PropagationDatasets::phi, PHWHERE, physmon_track_finding_ttbar::pt, physmon_track_finding_ttbar::r, PHG4ParticleGeneratorBase::RandomGenerator(), PHG4ParticleGeneratorBase::ReuseExistingVertex(), PHG4Particle::set_e(), PHG4Particle::set_name(), PHG4Particle::set_parent_id(), PHG4Particle::set_pid(), PHG4Particle::set_px(), PHG4Particle::set_py(), PHG4Particle::set_pz(), PHG4Particle::set_track_id(), PHG4ParticleGeneratorBase::set_vtx(), PHG4Particle::set_vtx_id(), smearvtx(), ActsTests::PropagationDatasets::theta, Fun4AllBase::Verbosity(), ambiguity_solver_full_chain::x, x0, y, and physmon_track_finding_ttbar::z.
void PHG4SimpleEventGenerator::set_eta_range (const double eta_min, const double eta_max)
range of randomized eta values (mutually exclusive with theta range)
Definition at line 47 of file PHG4SimpleEventGenerator.cc.
View newest version in sPHENIX GitHub at line 47 of file PHG4SimpleEventGenerator.cc
References m_EtaMax, m_EtaMin, m_ThetaMax, m_ThetaMin, and Acts::UnitConstants::min.
Referenced by ConfigureInput(), ConstructGeometry(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void PHG4SimpleEventGenerator::set_existing_vertex_offset_vector (const double x, const double y, const double z)
set an offset vector from the existing vertex
Definition at line 173 of file PHG4SimpleEventGenerator.cc.
View newest version in sPHENIX GitHub at line 173 of file PHG4SimpleEventGenerator.cc
References m_VertexOffset_x, m_VertexOffset_y, m_VertexOffset_z, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by ConfigureInput(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void PHG4SimpleEventGenerator::set_p_range (const double p_min, const double p_max, const double p_gaus_width = 0)
range of randomized p values (mutually exclusive with pt range)
Parameters
[in] p_gaus_width if non-zero, further apply a Gauss smearing to the p_min - p_max flat distribution
Definition at line 127 of file PHG4SimpleEventGenerator.cc.
View newest version in sPHENIX GitHub at line 127 of file PHG4SimpleEventGenerator.cc
References m_P_GausWidth, m_P_Max, m_P_Min, m_Pt_GausWidth, m_Pt_Max, m_Pt_Min, and Acts::UnitConstants::min.
Referenced by ConstructGeometry(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_TPC(), Fun4All_G4_W(), and Jin_BJet().
void PHG4SimpleEventGenerator::set_phi_range (const double phi_min, const double phi_max)
range of randomized phi values
Definition at line 80 of file PHG4SimpleEventGenerator.cc.
View newest version in sPHENIX GitHub at line 80 of file PHG4SimpleEventGenerator.cc
References m_PhiMax, m_PhiMin, and Acts::UnitConstants::min.
Referenced by ConfigureInput(), ConstructGeometry(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void PHG4SimpleEventGenerator::set_power_law_n (const double n)
power law value of distribution to sample from for pt values
Definition at line 99 of file PHG4SimpleEventGenerator.cc.
View newest version in sPHENIX GitHub at line 99 of file PHG4SimpleEventGenerator.cc
References m_powerLawN, and n.
void PHG4SimpleEventGenerator::set_pt_range (const double pt_min, const double pt_max, const double pt_gaus_width = 0)
range of randomized pt values (mutually exclusive with momentum range)
Parameters
[in] pt_gaus_width if non-zero, further apply a Gauss smearing to the pt_min - pt_max flat distribution
Definition at line 104 of file PHG4SimpleEventGenerator.cc.
View newest version in sPHENIX GitHub at line 104 of file PHG4SimpleEventGenerator.cc
References m_P_GausWidth, m_P_Max, m_P_Min, m_Pt_GausWidth, m_Pt_Max, m_Pt_Min, and Acts::UnitConstants::min.
Referenced by ConfigureInput(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_Generator_Display(), Fun4All_single_particle(), and Wrapper().
void PHG4SimpleEventGenerator::set_theta_range (const double theta_min, const double theta_max)
range of randomized theta values (mutually exclusive with eta range)
Definition at line 61 of file PHG4SimpleEventGenerator.cc.
View newest version in sPHENIX GitHub at line 61 of file PHG4SimpleEventGenerator.cc
References m_EtaMax, m_EtaMin, m_ThetaMax, m_ThetaMin, and Acts::UnitConstants::min.
void PHG4SimpleEventGenerator::set_vertex_distribution_function (FUNCTION x, FUNCTION y, FUNCTION z)
toss a new vertex according to a Uniform or Gaus distribution
Definition at line 149 of file PHG4SimpleEventGenerator.cc.
View newest version in sPHENIX GitHub at line 149 of file PHG4SimpleEventGenerator.cc
References m_VertexFunc_x, m_VertexFunc_y, m_VertexFunc_z, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by ConfigureInput(), ConstructGeometry(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void PHG4SimpleEventGenerator::set_vertex_distribution_mean (const double x, const double y, const double z)
set the mean value of the vertex distribution
Definition at line 157 of file PHG4SimpleEventGenerator.cc.
View newest version in sPHENIX GitHub at line 157 of file PHG4SimpleEventGenerator.cc
References m_Vertex_x, m_Vertex_y, m_Vertex_z, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by ConfigureInput(), ConstructGeometry(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void PHG4SimpleEventGenerator::set_vertex_distribution_width (const double x, const double y, const double z)
set the width of the vertex distribution function about the mean
Definition at line 165 of file PHG4SimpleEventGenerator.cc.
View newest version in sPHENIX GitHub at line 165 of file PHG4SimpleEventGenerator.cc
References m_VertexWidth_x, m_VertexWidth_y, m_VertexWidth_z, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by ConfigureInput(), ConstructGeometry(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void PHG4SimpleEventGenerator::set_vertex_size_function (FUNCTION r) inline
set the distribution function of particles about the vertex
Definition at line 72 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4SimpleEventGenerator.h
References m_VertexSizeFunc_r, and physmon_track_finding_ttbar::r.
Referenced by ConfigureInput(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void PHG4SimpleEventGenerator::set_vertex_size_parameters (const double mean, const double width)
set the dimensions of the distribution of particles about the vertex
Definition at line 181 of file PHG4SimpleEventGenerator.cc.
View newest version in sPHENIX GitHub at line 181 of file PHG4SimpleEventGenerator.cc
References m_VertexSizeMean, m_VertexSizeWidth, mean(), and width.
Referenced by ConfigureInput(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
double PHG4SimpleEventGenerator::smearvtx (const double position, const double width, FUNCTION dist) const private
Definition at line 425 of file PHG4SimpleEventGenerator.cc.
View newest version in sPHENIX GitHub at line 425 of file PHG4SimpleEventGenerator.cc
References Gaus, m_FunctionNames, position, PHG4ParticleGeneratorBase::RandomGenerator(), Uniform, and width.
Referenced by process_event().
Member Data Documentation
std::vector<std::pair<int, unsigned int> > PHG4SimpleEventGenerator::_particle_codes private
Definition at line 82 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 82 of file PHG4SimpleEventGenerator.h
Referenced by add_particles(), and InitRun().
std::vector<std::pair<std::string, unsigned int> > PHG4SimpleEventGenerator::_particle_names private
Definition at line 83 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 83 of file PHG4SimpleEventGenerator.h
Referenced by add_particles(), InitRun(), and process_event().
double PHG4SimpleEventGenerator::m_EtaMax = 1.25 private
Definition at line 105 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 105 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), set_eta_range(), and set_theta_range().
double PHG4SimpleEventGenerator::m_EtaMin = -1.25 private
Definition at line 104 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 104 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), set_eta_range(), and set_theta_range().
std::map<FUNCTION, std::string> PHG4SimpleEventGenerator::m_FunctionNames = {{Uniform, "Uniform"}, {Gaus, "Gaus"}} private
Definition at line 86 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 86 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), and smearvtx().
PHG4InEvent* PHG4SimpleEventGenerator::m_InEvent = nullptr private
Definition at line 88 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 88 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), and process_event().
double PHG4SimpleEventGenerator::m_P_GausWidth = NAN private
Definition at line 115 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 115 of file PHG4SimpleEventGenerator.h
Referenced by process_event(), set_p_range(), and set_pt_range().
double PHG4SimpleEventGenerator::m_P_Max = NAN private
Definition at line 114 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 114 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), set_p_range(), and set_pt_range().
double PHG4SimpleEventGenerator::m_P_Min = NAN private
Definition at line 113 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 113 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), set_p_range(), and set_pt_range().
double PHG4SimpleEventGenerator::m_PhiMax = M_PI private
Definition at line 109 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 109 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), and set_phi_range().
double PHG4SimpleEventGenerator::m_PhiMin = -M_PI private
Definition at line 108 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 108 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), and set_phi_range().
double PHG4SimpleEventGenerator::m_powerLawN = NAN private
Definition at line 116 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 116 of file PHG4SimpleEventGenerator.h
Referenced by process_event(), and set_power_law_n().
double PHG4SimpleEventGenerator::m_Pt_GausWidth = 0. private
Definition at line 112 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 112 of file PHG4SimpleEventGenerator.h
Referenced by process_event(), set_p_range(), and set_pt_range().
double PHG4SimpleEventGenerator::m_Pt_Max = 10. private
Definition at line 111 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 111 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), set_p_range(), and set_pt_range().
double PHG4SimpleEventGenerator::m_Pt_Min = 0. private
Definition at line 110 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 110 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), set_p_range(), and set_pt_range().
double PHG4SimpleEventGenerator::m_ThetaMax = NAN private
Definition at line 107 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 107 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), set_eta_range(), and set_theta_range().
double PHG4SimpleEventGenerator::m_ThetaMin = NAN private
Definition at line 106 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 106 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), set_eta_range(), and set_theta_range().
double PHG4SimpleEventGenerator::m_Vertex_x = 0. private
Definition at line 92 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 92 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), and set_vertex_distribution_mean().
double PHG4SimpleEventGenerator::m_Vertex_y = 0. private
Definition at line 93 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 93 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), and set_vertex_distribution_mean().
double PHG4SimpleEventGenerator::m_Vertex_z = 0. private
Definition at line 94 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 94 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), and set_vertex_distribution_mean().
FUNCTION PHG4SimpleEventGenerator::m_VertexFunc_x = Uniform private
Definition at line 89 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 89 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), and set_vertex_distribution_function().
FUNCTION PHG4SimpleEventGenerator::m_VertexFunc_y = Uniform private
Definition at line 90 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 90 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), and set_vertex_distribution_function().
FUNCTION PHG4SimpleEventGenerator::m_VertexFunc_z = Uniform private
Definition at line 91 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 91 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), and set_vertex_distribution_function().
double PHG4SimpleEventGenerator::m_VertexOffset_x = 0. private
Definition at line 98 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 98 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), and set_existing_vertex_offset_vector().
double PHG4SimpleEventGenerator::m_VertexOffset_y = 0. private
Definition at line 99 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 99 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), and set_existing_vertex_offset_vector().
double PHG4SimpleEventGenerator::m_VertexOffset_z = 0. private
Definition at line 100 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 100 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), and set_existing_vertex_offset_vector().
FUNCTION PHG4SimpleEventGenerator::m_VertexSizeFunc_r = Uniform private
Definition at line 101 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 101 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), and set_vertex_size_function().
double PHG4SimpleEventGenerator::m_VertexSizeMean = 0. private
Definition at line 102 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 102 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), and set_vertex_size_parameters().
double PHG4SimpleEventGenerator::m_VertexSizeWidth = 0. private
Definition at line 103 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 103 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), and set_vertex_size_parameters().
double PHG4SimpleEventGenerator::m_VertexWidth_x = 0. private
Definition at line 95 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 95 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), and set_vertex_distribution_width().
double PHG4SimpleEventGenerator::m_VertexWidth_y = 0. private
Definition at line 96 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 96 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), and set_vertex_distribution_width().
double PHG4SimpleEventGenerator::m_VertexWidth_z = 0. private
Definition at line 97 of file PHG4SimpleEventGenerator.h.
View newest version in sPHENIX GitHub at line 97 of file PHG4SimpleEventGenerator.h
Referenced by InitRun(), process_event(), and set_vertex_distribution_width().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4SimpleEventGenerator.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4SimpleEventGenerator.cc