Analysis Software: CentralityInfo Class Reference
CentralityInfo Class Reference
#include <coresoftware/blob/master/offline/packages/centrality/CentralityInfo.h>
Public Types
enum PROP {
mbd_N = 0, mbd_S = 1, mbd_NS = 2, epd_N = 3,
epd_S = 4, epd_NS = 5, bimp = 6
}
Public Member Functions
~CentralityInfo () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
virtual bool has_quantity (const PROP) const
virtual float get_quantity (const PROP) const
virtual void set_quantity (const PROP, const float)
virtual bool has_centile (const PROP) const
virtual float get_centile (const PROP) const
virtual void set_centile (const PROP, const float)
virtual bool has_centrality_bin (const PROP) const
virtual int get_centrality_bin (const PROP) const
virtual void set_centrality_bin (const PROP, const int)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
CentralityInfo ()
Private Member Functions
ClassDefOverride (CentralityInfo, 1)
Detailed Description
Definition at line 12 of file CentralityInfo.h.
View newest version in sPHENIX GitHub at line 12 of file CentralityInfo.h
Member Enumeration Documentation
enum CentralityInfo::PROP
Enumerator:
mbd_N
Minimum Bias Detector (MBD) North-side charge sum.
mbd_S
MBD South-side charge sum.
mbd_NS
MBD North+South charge sum.
epd_N
sPHENIX Event Plane Detector (sEPD) North-side energy sum
epd_S
sEPD South-side energy sum
epd_NS
sEPD North+South energy sum
bimp
Impact parameter (b) in HIJING event.
Definition at line 20 of file CentralityInfo.h.
View newest version in sPHENIX GitHub at line 20 of file CentralityInfo.h
Constructor & Destructor Documentation
CentralityInfo::~CentralityInfo () inline override
Definition at line 15 of file CentralityInfo.h.
View newest version in sPHENIX GitHub at line 15 of file CentralityInfo.h
CentralityInfo::CentralityInfo () inline protected
Definition at line 55 of file CentralityInfo.h.
View newest version in sPHENIX GitHub at line 55 of file CentralityInfo.h
Member Function Documentation
CentralityInfo::ClassDefOverride (CentralityInfo , 1) private
virtual float CentralityInfo::get_centile (const PROP) const inline virtual
Reimplemented in CentralityInfov1.
Definition at line 47 of file CentralityInfo.h.
View newest version in sPHENIX GitHub at line 47 of file CentralityInfo.h
Referenced by RandomConeAna::GetCentInfo(), JetBkgdSub::GetCentInfo(), IsolatedTrackAnalysis::getCentrality(), dNdEtaINTT::GetCentralityInfo(), CentralityValid::process_event(), UEvsEtaCentrality::process_event(), JetUnderlyingEvent::process_event(), MultiDetectorMultiplicity::process_event(), JetSeedCount::process_event(), jetrtrack::process_event(), MyJetAnalysis::process_event(), FullJetFinder::process_event(), JetKinematicCheck::process_event(), JetValidation::process_event(), EMJetVal::process_event(), and DumpCentralityInfo::process_Node().
virtual int CentralityInfo::get_centrality_bin (const PROP) const inline virtual
Reimplemented in CentralityInfov2.
Definition at line 51 of file CentralityInfo.h.
View newest version in sPHENIX GitHub at line 51 of file CentralityInfo.h
virtual float CentralityInfo::get_quantity (const PROP) const inline virtual
Reimplemented in CentralityInfov1.
Definition at line 43 of file CentralityInfo.h.
View newest version in sPHENIX GitHub at line 43 of file CentralityInfo.h
Referenced by JetBkgdSub::GetCentInfo(), dNdEtaINTT::GetCentralityInfo(), FullJetFinder::process_event(), JetValidation::process_event(), EMJetVal::process_event(), and DumpCentralityInfo::process_Node().
virtual bool CentralityInfo::has_centile (const PROP) const inline virtual
Reimplemented in CentralityInfov1.
Definition at line 46 of file CentralityInfo.h.
View newest version in sPHENIX GitHub at line 46 of file CentralityInfo.h
Referenced by CentralityValid::process_event(), and DumpCentralityInfo::process_Node().
virtual bool CentralityInfo::has_centrality_bin (const PROP) const inline virtual
Reimplemented in CentralityInfov2.
Definition at line 50 of file CentralityInfo.h.
View newest version in sPHENIX GitHub at line 50 of file CentralityInfo.h
virtual bool CentralityInfo::has_quantity (const PROP) const inline virtual
Reimplemented in CentralityInfov1.
Definition at line 42 of file CentralityInfo.h.
View newest version in sPHENIX GitHub at line 42 of file CentralityInfo.h
Referenced by DumpCentralityInfo::process_Node().
void CentralityInfo::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in CentralityInfov1, and CentralityInfov2.
Definition at line 17 of file CentralityInfo.h.
View newest version in sPHENIX GitHub at line 17 of file CentralityInfo.h
References os.
Referenced by CentralityReco::process_event().
int CentralityInfo::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in CentralityInfov1.
Definition at line 18 of file CentralityInfo.h.
View newest version in sPHENIX GitHub at line 18 of file CentralityInfo.h
Referenced by DumpCentralityInfo::process_Node().
virtual void CentralityInfo::set_centile (const PROP , const float) inline virtual
Reimplemented in CentralityInfov1.
Definition at line 48 of file CentralityInfo.h.
View newest version in sPHENIX GitHub at line 48 of file CentralityInfo.h
Referenced by CentralityReco::FillCentralityInfo(), and PHG4CentralityReco::FillNode().
virtual void CentralityInfo::set_centrality_bin (const PROP , const int) inline virtual
Reimplemented in CentralityInfov2.
Definition at line 52 of file CentralityInfo.h.
View newest version in sPHENIX GitHub at line 52 of file CentralityInfo.h
Referenced by CentralityReco::FillCentralityInfo().
virtual void CentralityInfo::set_quantity (const PROP , const float) inline virtual
Reimplemented in CentralityInfov1.
Definition at line 44 of file CentralityInfo.h.
View newest version in sPHENIX GitHub at line 44 of file CentralityInfo.h
Referenced by PHG4CentralityReco::FillNode().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/centrality/CentralityInfo.h