Analysis Software: SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo Struct Reference
SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo Struct Reference
#include <analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorUtilities/src/EvtTools.h>
Public Member Functions
void SetInfo (PHCompositeNode *topNode)
void Reset ()
RecoInfo ()
~RecoInfo ()
RecoInfo (PHCompositeNode *topNode)
Static Public Member Functions
static vector< string > GetListOfMembers ()
Public Attributes
int nTrks = numeric_limits<int>::max()
double pSumTrks = numeric_limits<double>::max()
double eSumEMCal = numeric_limits<double>::max()
double eSumIHCal = numeric_limits<double>::max()
double eSumOHCal = numeric_limits<double>::max()
double vx = numeric_limits<double>::max()
double vy = numeric_limits<double>::max()
double vz = numeric_limits<double>::max()
double vr = numeric_limits<double>::max()
Detailed Description
Definition at line 77 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 77 of file EvtTools.h
Constructor & Destructor Documentation
SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::RecoInfo () inline
Definition at line 137 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 137 of file EvtTools.h
SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::~RecoInfo () inline
Definition at line 138 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 138 of file EvtTools.h
SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::RecoInfo (PHCompositeNode * topNode) inline
Definition at line 141 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 141 of file EvtTools.h
Member Function Documentation
static vector<string> SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::GetListOfMembers () inline static
Definition at line 121 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 121 of file EvtTools.h
void SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::Reset () inline
Definition at line 108 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 108 of file EvtTools.h
References vx, vy, and vz.
void SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::SetInfo (PHCompositeNode * topNode) inline
Definition at line 90 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 90 of file EvtTools.h
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumTrks(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetRecoVtx(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetSumCaloEne(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetSumTrkMomentum(), vx, vy, and vz.
Member Data Documentation
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::eSumEMCal = numeric_limits<double>::max()
Definition at line 82 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 82 of file EvtTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::eSumIHCal = numeric_limits<double>::max()
Definition at line 83 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 83 of file EvtTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::eSumOHCal = numeric_limits<double>::max()
Definition at line 84 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 84 of file EvtTools.h
int SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::nTrks = numeric_limits<int>::max()
Definition at line 80 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 80 of file EvtTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::pSumTrks = numeric_limits<double>::max()
Definition at line 81 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 81 of file EvtTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::vr = numeric_limits<double>::max()
Definition at line 88 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 88 of file EvtTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::vx = numeric_limits<double>::max()
Definition at line 85 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 85 of file EvtTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::vy = numeric_limits<double>::max()
Definition at line 86 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 86 of file EvtTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::vz = numeric_limits<double>::max()
Definition at line 87 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 87 of file EvtTools.h
The documentation for this struct was generated from the following file:
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorUtilities/src/EvtTools.h