Analysis Software: ActsExamples::HepMC3AsciiReader Exception Reference
ActsExamples::HepMC3AsciiReader Exception Reference final
HepMC3 event reader.
#include <acts/blob/sPHENIX/Examples/Io/HepMC3/include/ActsExamples/Io/HepMC3/HepMC3Reader.hpp>
Classes
struct Config
Public Member Functions
bool readEvent (HepMC3::ReaderAscii &reader, HepMC3::GenEvent &event)
Reads an event from file.
bool status (HepMC3::ReaderAscii &reader)
Reports the status of the reader.
HepMC3AsciiReader (const Config &cfg, Acts::Logging::Level lvl)
std::string name () const override
The algorithm name.
std::pair< size_t, size_t > availableEvents () const override
Return the available events range.
ProcessCode read (const ActsExamples::AlgorithmContext &ctx) override
Read out data from the input stream.
const Config & config () const
Get readonly access to the config parameters.
Public Member Functions inherited from ActsExamples::IReader
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Fulfill the algorithm interface.
ProcessCode finalize () override
Fulfill the algorithm interface.
Public Member Functions inherited from ActsExamples::SequenceElement
virtual ~SequenceElement ()=default
const std::vector< const
DataHandleBase * > & writeHandles () const
const std::vector< const
DataHandleBase * > & readHandles () const
Private Member Functions
const Acts::Logger & logger () const
Private Attributes
Config m_cfg
The configuration of this writer.
std::pair< size_t, size_t > m_eventsRange
Number of events.
std::unique_ptr< const
Acts::Logger > m_logger
The logger.
WriteDataHandle< std::vector
< HepMC3::GenEvent > > m_outputEvents
Detailed Description
HepMC3 event reader.
Definition at line 21 of file HepMC3Reader.hpp.
View newest version in sPHENIX GitHub at line 21 of file HepMC3Reader.hpp
Constructor & Destructor Documentation
ActsExamples::HepMC3AsciiReader::HepMC3AsciiReader (const Config & cfg, Acts::Logging::Level lvl)
Construct the particle reader.
Parameters
[in] cfg The configuration object
[in] lvl The logging level
Definition at line 26 of file HepMC3Reader.cpp.
View newest version in sPHENIX GitHub at line 26 of file HepMC3Reader.cpp
References ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::HepMC3AsciiReader::Config::inputStem, m_cfg, m_outputEvents, and ActsExamples::HepMC3AsciiReader::Config::outputEvents.
Member Function Documentation
std::pair< size_t, size_t > ActsExamples::HepMC3AsciiReader::availableEvents () const override virtual
Return the available events range.
Implements ActsExamples::IReader.
Definition at line 47 of file HepMC3Reader.cpp.
View newest version in sPHENIX GitHub at line 47 of file HepMC3Reader.cpp
const Config& ActsExamples::HepMC3AsciiReader::config () const inline
Get readonly access to the config parameters.
Definition at line 58 of file HepMC3Reader.hpp.
View newest version in sPHENIX GitHub at line 58 of file HepMC3Reader.hpp
References m_cfg.
const Acts::Logger& ActsExamples::HepMC3AsciiReader::logger () const inline private
Definition at line 68 of file HepMC3Reader.hpp.
View newest version in sPHENIX GitHub at line 68 of file HepMC3Reader.hpp
References m_logger.
std::string ActsExamples::HepMC3AsciiReader::name () const override virtual
The algorithm name.
Implements ActsExamples::SequenceElement.
ActsExamples::ProcessCode ActsExamples::HepMC3AsciiReader::read (const ActsExamples::AlgorithmContext & ctx) override virtual
Read out data from the input stream.
Implements ActsExamples::IReader.
Definition at line 52 of file HepMC3Reader.cpp.
View newest version in sPHENIX GitHub at line 52 of file HepMC3Reader.cpp
References ACTS_DEBUG, ACTS_VERBOSE, event, ActsExamples::AlgorithmContext::eventNumber, physmon_vertexing::events, m_cfg(), testing::internal::move(), path, ActsExamples::perEventFilepath(), summary::reader, and SUCCESS.
bool ActsExamples::HepMC3AsciiReader::readEvent (HepMC3::ReaderAscii & reader, HepMC3::GenEvent & event)
Reads an event from file.
Parameters
reader reader of run files
event storage of the read event
Returns
boolean indicator if the reading was successful
Definition at line 16 of file HepMC3Reader.cpp.
View newest version in sPHENIX GitHub at line 16 of file HepMC3Reader.cpp
Referenced by main().
bool ActsExamples::HepMC3AsciiReader::status (HepMC3::ReaderAscii & reader)
Reports the status of the reader.
Parameters
reader reader of run files
Returns
boolean status indicator
Definition at line 22 of file HepMC3Reader.cpp.
View newest version in sPHENIX GitHub at line 22 of file HepMC3Reader.cpp
Referenced by main().
Member Data Documentation
Config ActsExamples::HepMC3AsciiReader::m_cfg private
The configuration of this writer.
Definition at line 62 of file HepMC3Reader.hpp.
View newest version in sPHENIX GitHub at line 62 of file HepMC3Reader.hpp
Referenced by config(), and HepMC3AsciiReader().
std::pair<size_t, size_t> ActsExamples::HepMC3AsciiReader::m_eventsRange private
Number of events.
Definition at line 64 of file HepMC3Reader.hpp.
View newest version in sPHENIX GitHub at line 64 of file HepMC3Reader.hpp
std::unique_ptr<const Acts::Logger> ActsExamples::HepMC3AsciiReader::m_logger private
The logger.
Definition at line 66 of file HepMC3Reader.hpp.
View newest version in sPHENIX GitHub at line 66 of file HepMC3Reader.hpp
Referenced by logger().
WriteDataHandle<std::vector<HepMC3::GenEvent> > ActsExamples::HepMC3AsciiReader::m_outputEvents private
Initial value:
{this,
                                                                "OutputEvents"}
Definition at line 70 of file HepMC3Reader.hpp.
View newest version in sPHENIX GitHub at line 70 of file HepMC3Reader.hpp
Referenced by HepMC3AsciiReader().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Io/HepMC3/include/ActsExamples/Io/HepMC3/HepMC3Reader.hpp
acts/blob/sPHENIX/Examples/Io/HepMC3/src/HepMC3Reader.cpp