Analysis Software: TrkrClusterIterationMapv1 Class Reference
TrkrClusterIterationMapv1 Class Reference
Class for associating clusters to the hits that went into them.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrClusterIterationMapv1.h>
Public Member Functions
TrkrClusterIterationMapv1 ()=default
void Reset () override
Clear Event.
void identify (std::ostream &os=std::cout) const override
void addIteration (TrkrDefs::cluskey, short int) override
Add association between cluster andthe tracking iteration it was used in.
short int getIteration (TrkrDefs::cluskey ckey) override
unsigned int size (void) const override
ConstIter begin () const override
ConstIter end () const override
Private Member Functions
ClassDefOverride (TrkrClusterIterationMapv1, 1)
Private Attributes
Map m_map
Additional Inherited Members
Public Types inherited from TrkrClusterIterationMap
using Map = std::map< TrkrDefs::cluskey, short int >
using ConstIter = Map::const_iterator
Protected Member Functions inherited from TrkrClusterIterationMap
TrkrClusterIterationMap ()=default
Detailed Description
Class for associating clusters to the hits that went into them.
Store the associations between clusters and the hits that went into them.
Definition at line 25 of file TrkrClusterIterationMapv1.h.
View newest version in sPHENIX GitHub at line 25 of file TrkrClusterIterationMapv1.h
Constructor & Destructor Documentation
TrkrClusterIterationMapv1::TrkrClusterIterationMapv1 () default
Member Function Documentation
void TrkrClusterIterationMapv1::addIteration (TrkrDefs::cluskey , short int) override virtual
Add association between cluster andthe tracking iteration it was used in.
Parameters
[in] ckey Cluster key
[in] tracking iteration
Reimplemented from TrkrClusterIterationMap.
Definition at line 34 of file TrkrClusterIterationMapv1.cc.
View newest version in sPHENIX GitHub at line 34 of file TrkrClusterIterationMapv1.cc
References m_map.
Referenced by PHTrackSelector::process_event().
ConstIter TrkrClusterIterationMapv1::begin (void) const inline override virtual
Reimplemented from TrkrClusterIterationMap.
Definition at line 40 of file TrkrClusterIterationMapv1.h.
View newest version in sPHENIX GitHub at line 40 of file TrkrClusterIterationMapv1.h
References m_map.
TrkrClusterIterationMapv1::ClassDefOverride (TrkrClusterIterationMapv1 , 1) private
ConstIter TrkrClusterIterationMapv1::end (void) const inline override virtual
Reimplemented from TrkrClusterIterationMap.
Definition at line 41 of file TrkrClusterIterationMapv1.h.
View newest version in sPHENIX GitHub at line 41 of file TrkrClusterIterationMapv1.h
References m_map.
short int TrkrClusterIterationMapv1::getIteration (TrkrDefs::cluskey ckey) override virtual
Reimplemented from TrkrClusterIterationMap.
Definition at line 39 of file TrkrClusterIterationMapv1.cc.
View newest version in sPHENIX GitHub at line 39 of file TrkrClusterIterationMapv1.cc
References m_map.
Referenced by PHCASeeding::FillTree(), PHActsKDTreeSeeding::getMvtxSpacePoints(), PHActsSiliconSeeding::getSiliconSpacePoints(), PHActsSiliconSeeding::matchInttClusters(), PHSimpleKFProp::PrepareKDTrees(), and PHMicromegasTpcTrackMatching::process_event().
void TrkrClusterIterationMapv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 17 of file TrkrClusterIterationMapv1.cc.
View newest version in sPHENIX GitHub at line 17 of file TrkrClusterIterationMapv1.cc
References entry, and m_map.
void TrkrClusterIterationMapv1::Reset () override virtual
Clear Event.
Reimplemented from TrkrClusterIterationMap.
Definition at line 12 of file TrkrClusterIterationMapv1.cc.
View newest version in sPHENIX GitHub at line 12 of file TrkrClusterIterationMapv1.cc
References m_map.
Referenced by PHTrackSelector::process_event().
unsigned int TrkrClusterIterationMapv1::size (void) const override virtual
Reimplemented from TrkrClusterIterationMap.
Definition at line 52 of file TrkrClusterIterationMapv1.cc.
View newest version in sPHENIX GitHub at line 52 of file TrkrClusterIterationMapv1.cc
References m_map.
Member Data Documentation
Map TrkrClusterIterationMapv1::m_map private
Definition at line 44 of file TrkrClusterIterationMapv1.h.
View newest version in sPHENIX GitHub at line 44 of file TrkrClusterIterationMapv1.h
Referenced by addIteration(), begin(), end(), getIteration(), identify(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterIterationMapv1.h
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterIterationMapv1.cc