Analysis Software: TrkrDefs Namespace Reference
TrkrDefs Namespace Reference
Define a namespace for Trkr typedefs.
Typedefs
typedef uint32_t hitkey
Key types.
typedef uint32_t hitsetkey
typedef uint64_t cluskey
typedef uint32_t clushitkey
typedef uint16_t subsurfkey
Enumerations
enum TrkrId {
mvtxId = 0, inttId = 1, tpcId = 2, micromegasId = 3,
ttl = 4
}
Enumeration for tracker id to easily maintain consistency.
Functions
static double EdepScaleFactor __attribute__ ((unused)) = 5.0e8
Max values for keys (used as defaults or invalid values)
void printBits (const TrkrDefs::hitsetkey key, std::ostream &os=std::cout)
Print the bits for each key type.
void printBits (const TrkrDefs::cluskey key, std::ostream &os=std::cout)
uint8_t getTrkrId (const TrkrDefs::hitsetkey key)
Get the tracker ID from either key type.
uint8_t getTrkrId (const TrkrDefs::cluskey key)
uint8_t getLayer (const TrkrDefs::hitsetkey key)
Get the layer number from either key type.
uint8_t getLayer (const TrkrDefs::cluskey key)
uint32_t getClusIndex (const TrkrDefs::cluskey key)
Get the lower 32 bits for cluster keys only.
TrkrDefs::hitsetkey genHitSetKey (const TrkrDefs::TrkrId trkrId, const uint8_t lyr)
generate the common upper 16 bits for hitsetkey
TrkrDefs::cluskey genClusKey (const TrkrDefs::hitsetkey hskey, const uint32_t clusid)
generate cluster key from hitset key and cluster index
uint32_t getHitSetKeyFromClusKey (const TrkrDefs::cluskey key)
Get the upper 32 bits from cluster keys.
TrkrDefs::hitsetkey getHitSetKeyLo (const TrkrDefs::TrkrId trkrId)
Get a valid low / hi range for hitsetkey given tracker id & layer.
TrkrDefs::hitsetkey getHitSetKeyHi (const TrkrDefs::TrkrId trkrId)
TrkrDefs::hitsetkey getHitSetKeyLo (const TrkrDefs::TrkrId trkrId, const uint8_t lyr)
TrkrDefs::hitsetkey getHitSetKeyHi (const TrkrDefs::TrkrId trkrId, const uint8_t lyr)
TrkrDefs::cluskey getClusKeyLo (const TrkrDefs::TrkrId trkrId)
Get a valid low / hi range for cluskey given tracker id & layer.
TrkrDefs::cluskey getClusKeyHi (const TrkrDefs::TrkrId trkrId)
TrkrDefs::cluskey getClusKeyLo (const TrkrDefs::TrkrId trkrId, const uint8_t lyr)
TrkrDefs::cluskey getClusKeyHi (const TrkrDefs::TrkrId trkrId, const uint8_t lyr)
uint8_t getPhiElement (TrkrDefs::hitsetkey key)
uint8_t getZElement (TrkrDefs::hitsetkey key)
uint8_t getPhiElement (TrkrDefs::cluskey key)
uint8_t getZElement (TrkrDefs::cluskey key)
Detailed Description
Define a namespace for Trkr typedefs.
Typedef Documentation
typedef uint32_t TrkrDefs::clushitkey
Definition at line 26 of file TrkrDefs.h.
View newest version in sPHENIX GitHub at line 26 of file TrkrDefs.h
typedef uint64_t TrkrDefs::cluskey
Definition at line 25 of file TrkrDefs.h.
View newest version in sPHENIX GitHub at line 25 of file TrkrDefs.h
typedef uint32_t TrkrDefs::hitkey
Key types.
Definition at line 23 of file TrkrDefs.h.
View newest version in sPHENIX GitHub at line 23 of file TrkrDefs.h
typedef uint32_t TrkrDefs::hitsetkey
Definition at line 24 of file TrkrDefs.h.
View newest version in sPHENIX GitHub at line 24 of file TrkrDefs.h
typedef uint16_t TrkrDefs::subsurfkey
Definition at line 27 of file TrkrDefs.h.
View newest version in sPHENIX GitHub at line 27 of file TrkrDefs.h
Enumeration Type Documentation
enum TrkrDefs::TrkrId
Enumeration for tracker id to easily maintain consistency.
Enumerator:
mvtxId
inttId
tpcId
micromegasId
ttl
Definition at line 50 of file TrkrDefs.h.
View newest version in sPHENIX GitHub at line 50 of file TrkrDefs.h
Function Documentation
static const unsigned int kBitShiftZElement TrkrDefs::__attribute__ ((unused)) = 5.0e8 static pure virtual
Max values for keys (used as defaults or invalid values)
TrkrDefs::cluskey TrkrDefs::genClusKey (const TrkrDefs::hitsetkey hskey, const uint32_t clusid)
generate cluster key from hitset key and cluster index
Definition at line 119 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 119 of file TrkrDefs.cc
References Acts::Test::tmp().
Referenced by PHTruthClustering::all_truth_clusters(), SvtxTruthEval::all_truth_clusters(), TpcClusterBuilder::cluster_hits(), PHG4InttHitReco::cluster_truthhits(), PHG4MvtxHitReco::cluster_truthhits(), InttClusterizer::ClusterLadderCells(), InttClusterizer::ClusterLadderCellsRaw(), MvtxClusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtxRaw(), TpcDefs::genClusKey(), InttDefs::genClusKey(), MvtxDefs::genClusKey(), TrkrClusterContainerv4::getClusters(), TpcSimpleClusterizer::process_event(), MicromegasClusterizer::process_event(), and TpcClusterizer::process_event().
TrkrDefs::hitsetkey TrkrDefs::genHitSetKey (const TrkrDefs::TrkrId trkrId, const uint8_t lyr)
generate the common upper 16 bits for hitsetkey
Definition at line 109 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 109 of file TrkrDefs.cc
References Acts::Test::tmp().
Referenced by MicromegasDefs::genHitSetKey(), TpcDefs::genHitSetKey(), InttDefs::genHitSetKey(), and MvtxDefs::genHitSetKey().
uint32_t TrkrDefs::getClusIndex (const TrkrDefs::cluskey key)
Get the lower 32 bits for cluster keys only.
Definition at line 45 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 45 of file TrkrDefs.cc
Referenced by TrkrClusterContainerv4::addClusterSpecifyKey(), SvtxEvaluator::fillOutputNtuples(), TrkrClusterContainerv4::findCluster(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), TpcClusterBuilder::print(), TpcClusterBuilder::print_file(), PHG4MvtxHitReco::process_event(), and TrkrClusterContainerv4::removeCluster().
TrkrDefs::cluskey TrkrDefs::getClusKeyHi (const TrkrDefs::TrkrId trkrId)
Definition at line 88 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 88 of file TrkrDefs.cc
References MicromegasDefs::genHitSetKey(), and Acts::Test::tmp().
TrkrDefs::cluskey TrkrDefs::getClusKeyHi (const TrkrDefs::TrkrId trkrId, const uint8_t lyr)
Definition at line 102 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 102 of file TrkrDefs.cc
References MicromegasDefs::genHitSetKey(), and Acts::Test::tmp().
TrkrDefs::cluskey TrkrDefs::getClusKeyLo (const TrkrDefs::TrkrId trkrId)
Get a valid low / hi range for cluskey given tracker id & layer.
Definition at line 81 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 81 of file TrkrDefs.cc
References MicromegasDefs::genHitSetKey(), and Acts::Test::tmp().
TrkrDefs::cluskey TrkrDefs::getClusKeyLo (const TrkrDefs::TrkrId trkrId, const uint8_t lyr)
Definition at line 95 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 95 of file TrkrDefs.cc
References MicromegasDefs::genHitSetKey(), and Acts::Test::tmp().
uint32_t TrkrDefs::getHitSetKeyFromClusKey (const TrkrDefs::cluskey key)
Get the upper 32 bits from cluster keys.
Definition at line 51 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 51 of file TrkrDefs.cc
Referenced by TrkrClusterHitAssocv3::addAssoc(), TrackClusEvaluator::addClusKeys(), TrkrClusterContainerv3::addClusterSpecifyKey(), TrkrClusterContainerv4::addClusterSpecifyKey(), MakeMilleFiles::addTrackToMilleFile(), SvtxClusterEval::all_truth_hits(), SvtxClusterEval::all_truth_hits_by_nhit(), DSTEmulator::evaluate_tracks(), TrackResiduals::fillClusterBranches(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), QAG4SimulationIntt::find_g4hits(), QAG4SimulationMvtx::find_g4hits(), QAG4SimulationMicromegas::find_g4hits(), QAG4SimulationTpc::find_g4hits(), QAG4SimulationTracking::find_g4hits(), DSTEmulator::find_g4hits(), TrackEvaluation::find_g4hits(), TrkrClusterContainerv3::findCluster(), TrkrClusterContainerv4::findCluster(), PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), PHTruthSiliconAssociation::getG4PrimaryParticle(), TrkrClusterHitAssocv3::getHits(), PHActsKDTreeSeeding::getMvtxSpacePoints(), PHTruthSiliconAssociation::getSiliconClustersFromParticle(), PHActsSiliconSeeding::getSiliconSpacePoints(), ActsSurfaceMaps::getSurface(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), TrkrTruthTrackv1::identify(), TrkrTruthTrackv1::CompHitSetKey::operator()(), TpcClusterBuilder::print(), TpcClusterBuilder::print_file(), PHSiliconTruthTrackSeeding::Process(), PHTpcClusterMover::process_event(), MvtxPrototype2Align::process_event(), PHG4MvtxHitReco::process_event(), PHGenFitTrkFitter::ReFitTrack(), TrkrClusterContainerv4::removeCluster(), and TrkrClusterContainerv3::removeCluster().
TrkrDefs::hitsetkey TrkrDefs::getHitSetKeyHi (const TrkrDefs::TrkrId trkrId)
Definition at line 63 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 63 of file TrkrDefs.cc
References MicromegasDefs::genHitSetKey().
Referenced by TrkrClusterContainerv3::getHitSetKeys(), TrkrClusterContainerv4::getHitSetKeys(), TrkrHitSetContainerv1::getHitSets(), and RawHitSetContainerv1::getHitSets().
TrkrDefs::hitsetkey TrkrDefs::getHitSetKeyHi (const TrkrDefs::TrkrId trkrId, const uint8_t lyr)
Definition at line 75 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 75 of file TrkrDefs.cc
References MicromegasDefs::genHitSetKey().
TrkrDefs::hitsetkey TrkrDefs::getHitSetKeyLo (const TrkrDefs::TrkrId trkrId)
Get a valid low / hi range for hitsetkey given tracker id & layer.
Definition at line 57 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 57 of file TrkrDefs.cc
References MicromegasDefs::genHitSetKey().
Referenced by TrkrClusterContainerv3::getHitSetKeys(), TrkrClusterContainerv4::getHitSetKeys(), TrkrHitSetContainerv1::getHitSets(), and RawHitSetContainerv1::getHitSets().
TrkrDefs::hitsetkey TrkrDefs::getHitSetKeyLo (const TrkrDefs::TrkrId trkrId, const uint8_t lyr)
Definition at line 69 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 69 of file TrkrDefs.cc
References MicromegasDefs::genHitSetKey().
uint8_t TrkrDefs::getLayer (const TrkrDefs::hitsetkey key)
Get the layer number from either key type.
Definition at line 31 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 31 of file TrkrDefs.cc
References Acts::Test::tmp().
Referenced by TrkrClusterHitAssocv2::addAssoc(), TrackFitUtils::addClusters(), TrackFitUtils::addClustersOnLine(), TrkrClusterContainerv2::addClusterSpecifyKey(), MakeMilleFiles::addTrackToMilleFile(), ALICEKF::ALICEKalmanFilter(), SvtxClusterEval::all_clusters_from(), SvtxHitEval::all_hits_from(), SvtxClusterEval::all_truth_clusters(), SvtxClusterEval::all_truth_hits_by_nhit(), SvtxClusterEval::best_cluster_by_nhit(), g4evalfn::calc_match_statistic(), Calibrator::calibrate(), TrackSeed_v1::circleFitByTaubin(), g4evalfn::clusloc_PHG4(), G4Eval::TrkrClusterComparer::clusloc_PHG4(), g4evalfn::clusloc_SVTX(), G4Eval::TrkrClusterComparer::clusloc_SVTX(), TpcClusterBuilder::cluster_hits(), PHG4InttHitReco::cluster_truthhits(), PHG4MvtxHitReco::cluster_truthhits(), InttClusterizer::ClusterLadderCells(), InttClusterizer::ClusterLadderCellsRaw(), MvtxClusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtxRaw(), TrackEvaluation::create_cluster(), AlignmentTransformation::createMap(), PHG4TpcDigitizer::DigitizeCylinderCells(), PHG4InttDigitizer::DigitizeLadderCells(), PHG4MvtxDigitizer::DigitizeMvtxLadderCells(), TpcPrototypeGenFitTrkFitter::DisplayCluster(), QAG4SimulationIntt::evaluate_clusters(), QAG4SimulationMvtx::evaluate_clusters(), QAG4SimulationMicromegas::evaluate_clusters(), QAG4SimulationTpc::evaluate_clusters(), TrackEvaluation::evaluate_event(), QAG4SimulationMicromegas::evaluate_hits(), DSTTrackInfoWriter::evaluate_track_info(), DSTEmulator::evaluate_tracks(), SvtxClusterEval::fill_cluster_layer_map(), helixResiduals::fill_residuals(), TrackResiduals::fillClusterBranches(), TrackResiduals::fillClusterTree(), KFParticle_truthAndDetTools::fillDetectorBranch(), TrackResiduals::fillHitTree(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHCASeeding::FillTree(), PHCASeeding::FindBiLinks(), TrkrClusterContainerv2::findCluster(), Conversion::firstLayer(), PHCASeeding::FollowBiLinks(), ClusterErrorPara::get_cluster_error(), ClusterErrorPara::get_clusterv5_modified_error(), ClusterErrorPara::get_fix_tpc_cluster_error(), SvtxTrackEval::get_layer_range_contribution(), SvtxTrackEval::get_nclusters_contribution_by_layer(), ClusterErrorPara::get_si_cluster_error(), ClusterErrorPara::get_simple_cluster_error(), ActsGeometry::get_tpc_surface_from_coords(), TpcPrototypeGenFitTrkFinder::getChi2Ndf(), MvtxPrototype2Geom::getChipIndex(), TrkrClusterHitAssocv2::getClusterMap(), TrkrClusterContainerv2::getClusters(), MultiDetectorMultiplicity::getFilteredNtracks(), TrkrClusterHitAssocv2::getHits(), PHSiliconTpcTrackMatching::getInttCrossings(), PHTruthSiliconAssociation::getInttCrossings(), PHTruthTrackSeeding::getInttCrossings(), getLayer(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumClust(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetNumClust(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumLayer(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetNumLayer(), dNdEtaINTT::GetRecoClusterInfo(), PHTruthSiliconAssociation::getSiliconClustersFromParticle(), MakeSourceLinks::getSourceLinks(), ActsSurfaceMaps::getTpcSurface(), HelicalFitter::getTrackletClusterList(), dNdEtaINTT::GetTrkrHitInfo(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), RecoConversionEval::hitCuts(), TrkrClusterContainerv3::identify(), TrkrClusterContainerv4::identify(), TrkrClusterContainerv2::identify(), TrkrHitSetv1::identify(), RawHitSetv1::identify(), TrkrClusterHitAssocv2::identify(), TrkrClusterHitAssocv3::identify(), TrkrHitTruthAssocv1::identify(), TrkrClusterCrossingAssocv1::identify(), RawHitSetContainerv1::identify(), TrkrHitSetContainerv1::identify(), TrkrClusterContainerv1::identify(), TrkrTruthTrackv1::identify(), SVReco::InitEvent(), TrackSeed_v1::lineFit(), SVReco::MakeGenFitTrack(), TrackerEventDisplay::makeJsonFile(), PHGenFitTrkFitter::MakeSvtxTrack(), MakeActsGeometry::makeTpcMapPairs(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), PHActsSiliconSeeding::matchInttClusters(), SvtxClusterEval::max_truth_cluster_by_energy(), SvtxClusterEval::max_truth_particle_by_cluster_energy(), TrkrClusterIsMatcher::operator()(), G4Eval::TrkrClusterComparer::operator()(), PHSimpleKFProp::PrepareKDTrees(), FillTruthRecoMatchTree::print_mvtx_diagnostics(), TrkrNtuplizer::printOutputInfo(), SvtxEvaluator::printOutputInfo(), PHSiliconTruthTrackSeeding::Process(), PHHybridSeeding::Process(), PHSiliconHelicalPropagator::process_event(), TpcPrototypeClusterizer::process_event(), TpcClusterQA::process_event(), PHCosmicSiliconPropagator::process_event(), QAG4SimulationDistortions::process_event(), QAG4SimulationVertex::process_event(), TpcClusterCleaner::process_event(), MicromegasClusterizer::process_event(), TpcSimpleClusterizer::process_event(), PHG4TpcPadBaselineShift::process_event(), BJetModule::process_event(), TpcRawWriter::process_event(), MicromegasRawDataDecoder::process_event(), QAG4SimulationTracking::process_event(), MicromegasCombinedDataDecoder::process_event(), TPCGemGainCalb::process_event(), TpcClusterizer::process_event(), MvtxHitPruner::process_event(), PHTpcClusterMover::process_event(), SynRadAna::process_event(), TPCMLDataInterface::process_event(), PHG4TpcElectronDrift::process_event(), PHMicromegasTpcTrackMatching::process_event(), MicromegasCombinedDataEvaluation::process_event(), PHTruthClustering::process_event(), MicromegasRawDataEvaluation::process_event(), readDigitalCurrents::process_event(), PHTpcCentralMembraneClusterizer::process_event(), AnaMvtxTestBeam2019::process_event(), HelicalFitter::process_event(), FillTruthRecoMatchTree::process_event(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), TpcDirectLaserReconstruction::process_track(), TpcSpaceChargeReconstruction::process_track(), TrackClusterEvaluator::processRecoTracks(), TpcClusterMover::processTrack(), PHTpcResiduals::processTrack(), TruthConversionEval::processTrackBackground(), TrackClusterEvaluator::processTruthTracks(), PHSimpleKFProp::PropagateTrack(), SvtxClusterEval::reco_cluster_from_truth_cluster(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), PHGenFitTrkFitter::ReFitTrack(), TrkrClusterContainerv2::removeCluster(), Conversion::trackDLayer(), G4Eval::trklayer_0123(), g4evalfn::trklayer_det(), and PHG4MvtxHitReco::zero_strobe_bits().
uint8_t TrkrDefs::getLayer (const TrkrDefs::cluskey key)
Definition at line 38 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 38 of file TrkrDefs.cc
References getLayer(), and Acts::Test::tmp().
uint8_t TrkrDefs::getPhiElement (TrkrDefs::hitsetkey key)
Definition at line 127 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 127 of file TrkrDefs.cc
References Acts::Test::tmp().
Referenced by TrkrClusterHitAssocv2::addAssoc(), TrkrClusterContainerv2::addClusterSpecifyKey(), TrkrClusterContainerv2::findCluster(), TrkrClusterHitAssocv2::getClusterMap(), TrkrClusterContainerv2::getClusters(), TrkrClusterHitAssocv2::getHits(), getPhiElement(), TrkrClusterContainerv2::identify(), TPCGemGainCalb::process_event(), and TrkrClusterContainerv2::removeCluster().
uint8_t TrkrDefs::getPhiElement (TrkrDefs::cluskey key)
Definition at line 141 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 141 of file TrkrDefs.cc
References getPhiElement(), and Acts::Test::tmp().
uint8_t TrkrDefs::getTrkrId (const TrkrDefs::hitsetkey key)
Get the tracker ID from either key type.
Definition at line 17 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 17 of file TrkrDefs.cc
References Acts::Test::tmp().
Referenced by MakeMilleFiles::addTrackToMilleFile(), SvtxHitEval::all_truth_hits(), SvtxClusterEval::all_truth_hits(), SvtxClusterEval::all_truth_hits_by_nhit(), PHTruthSiliconAssociation::buildTrackSeed(), PHTruthTrackSeeding::buildTrackSeed(), PHSimpleVertexFinder::checkDCAs(), HelicalFitter::correctTpcGlobalPositions(), AlignmentTransformation::createMap(), QAG4SimulationMicromegas::evaluate_clusters(), QAG4SimulationTpc::evaluate_clusters(), TrackEvaluation::evaluate_clusters(), TrackEvaluation::evaluate_event(), DSTEmulator::evaluate_tracks(), TrackEvaluation::evaluate_tracks(), ActsAlignmentStates::fillAlignmentStateMap(), TrackResiduals::fillClusterBranches(), KFParticle_truthAndDetTools::fillDetectorBranch(), TrackResiduals::fillHitTree(), TrkrNtuplizer::fillOutputNtuples(), ActsEvaluator::fillProtoTrack(), PHActsKDTreeSeeding::fillTrackSeedContainer(), PHCosmicsTrkFitter::fillVectors(), QAG4SimulationIntt::find_g4hits(), QAG4SimulationMvtx::find_g4hits(), QAG4SimulationMicromegas::find_g4hits(), QAG4SimulationTpc::find_g4hits(), QAG4SimulationTracking::find_g4hits(), DSTEmulator::find_g4hits(), TrackEvaluation::find_g4hits(), TrackFitUtils::fitClusters(), ClusterErrorPara::get_cluster_error(), ClusterErrorPara::get_clusterv5_modified_error(), TpcSpaceChargeReconstruction::get_global_position(), ClusterErrorPara::get_si_cluster_error(), ClusterErrorPara::get_simple_cluster_error(), PHSiliconTpcTrackMatching::getBunchCrossing(), PHTruthSiliconAssociation::getG4PrimaryParticle(), ActsGeometry::getGlobalPosition(), PHMicromegasTpcTrackMatching::getGlobalPosition(), PHTpcResiduals::getGlobalPosition(), PHGenFitTrkFitter::getGlobalPosition(), ActsGeometry::getGlobalPositionTpc(), PHSiliconTpcTrackMatching::getInttCrossings(), PHTruthSiliconAssociation::getInttCrossings(), PHTruthTrackSeeding::getInttCrossings(), ActsGeometry::getLocalCoords(), dNdEtaINTT::GetRecoClusterInfo(), PHTruthSiliconAssociation::getSiliconClustersFromParticle(), ActsSurfaceMaps::getSiliconSurface(), MakeSourceLinks::getSourceLinks(), ActsSurfaceMaps::getSurface(), PHActsVertexFinder::getTracks(), getTrkrId(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), TrkrHitSetv1::identify(), RawHitSetv1::identify(), PairMaker::isElectron(), KFParticle_Tools::makeAllDaughterParticles(), SVReco::MakeGenFitTrack(), TrackerEventDisplay::makeJsonFile(), PHActsSiliconSeeding::makeSvtxTracks(), PHSiliconTruthTrackSeeding::Process(), PHTruthTrackSeeding::Process(), PHSiliconHelicalPropagator::process_event(), PHCosmicSiliconPropagator::process_event(), PHSiliconSeedMerger::process_event(), QAG4SimulationVertex::process_event(), TpcClusterCleaner::process_event(), BJetModule::process_event(), PHTrackSelector::process_event(), QAG4SimulationTracking::process_event(), PHTpcClusterMover::process_event(), TrackResiduals::process_event(), PHTruthClustering::process_event(), PHSimpleKFProp::process_event(), ElectronID::process_event(), readDigitalCurrents::process_event(), HelicalFitter::process_event(), PHRaveVertexing::process_event(), FullJetFinder::process_event(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), PHTpcDeltaZCorrection::process_track(), TpcSpaceChargeReconstruction::process_track(), TpcClusterMover::processTrack(), PHTpcResiduals::processTrack(), PHSimpleKFProp::PropagateTrack(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), PHGenFitTrkFitter::ReFitTrack(), and sPHElectronv1::sPHElectronv1().
uint8_t TrkrDefs::getTrkrId (const TrkrDefs::cluskey key)
Definition at line 24 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 24 of file TrkrDefs.cc
References getTrkrId(), and Acts::Test::tmp().
uint8_t TrkrDefs::getZElement (TrkrDefs::hitsetkey key)
Definition at line 135 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 135 of file TrkrDefs.cc
References Acts::Test::tmp().
Referenced by TrkrClusterHitAssocv2::addAssoc(), TrkrClusterContainerv2::addClusterSpecifyKey(), TrkrClusterContainerv2::findCluster(), TrkrClusterHitAssocv2::getClusterMap(), TrkrClusterContainerv2::getClusters(), TrkrClusterHitAssocv2::getHits(), getZElement(), TrkrClusterContainerv2::identify(), TPCGemGainCalb::process_event(), and TrkrClusterContainerv2::removeCluster().
uint8_t TrkrDefs::getZElement (TrkrDefs::cluskey key)
Definition at line 147 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 147 of file TrkrDefs.cc
References getZElement(), and Acts::Test::tmp().
void TrkrDefs::printBits (const TrkrDefs::hitsetkey key, std::ostream & os = std::cout)
Print the bits for each key type.
Definition at line 6 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 6 of file TrkrDefs.cc
void TrkrDefs::printBits (const TrkrDefs::cluskey key, std::ostream & os = std::cout)
Definition at line 11 of file TrkrDefs.cc.
View newest version in sPHENIX GitHub at line 11 of file TrkrDefs.cc