Analysis Software: SingleMicromegasPoolInput Class Reference
SingleMicromegasPoolInput Class Reference
#include <coresoftware/blob/master/offline/framework/fun4allraw/SingleMicromegasPoolInput.h>
Classes
class bco_alignment_t
keep track of matching between fee and gtm_bco
Public Member Functions
SingleMicromegasPoolInput (const std::string &name="SingleMicromegasPoolInput")
~SingleMicromegasPoolInput () override
void FillPool (const unsigned int nevents=1) override
void CleanupUsedPackets (const uint64_t bclk) override
void ClearCurrentEvent () override
bool GetSomeMoreEvents ()
void Print (const std::string &what="ALL") const override
void CreateDSTNode (PHCompositeNode *topNode) override
void SetBcoRange (const unsigned int value)
void ConfigureStreamingInputManager () override
void SetNegativeBco (const unsigned int value)
Public Member Functions inherited from SingleStreamingInput
SingleStreamingInput (const std::string &name, Fun4AllEvtInputPoolManager *inman)
SingleStreamingInput (const std::string &name)
~SingleStreamingInput () override
virtual Eventiterator * GetEventIterator ()
virtual void FillPool (const uint64_t)
virtual void RunNumber (const int runno)
virtual int RunNumber () const
virtual int fileopen (const std::string &filename) override
virtual int fileclose () override
virtual int AllDone () const
virtual void AllDone (const int i)
virtual void EventNumberOffset (const int i)
virtual bool CheckPoolDepth (const uint64_t bclk)
virtual Eventiterator * GetEventiterator () const
virtual
Fun4AllEvtInputPoolManager * InputManager ()
virtual void InputManager (Fun4AllEvtInputPoolManager *in)
virtual
Fun4AllStreamingInputManager * StreamingInputManager ()
virtual void StreamingInputManager (Fun4AllStreamingInputManager *in)
virtual void SubsystemEnum (const int id)
virtual int SubsystemEnum () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from InputFileHandler
InputFileHandler ()=default
virtual ~InputFileHandler ()=default
int OpenNextFile ()
int AddListFile (const std::string &filename)
int AddFile (const std::string &filename)
void AddToFileOpened (const std::string &filename)
void Print (const std::string &what="ALL") const
int IsOpen () const
void IsOpen (const int i)
void SetVerbosity (const int i)
int GetVerbosity () const
void UpdateFileList ()
void FileName (const std::string &fn)
const std::string FileName () const
Private Attributes
Packet ** plist {nullptr}
unsigned int m_NumSpecialEvents {0}
unsigned int m_BcoRange {0}
unsigned int m_NegativeBco {0}
std::map< uint64_t, std::set
< int > > m_BeamClockFEE
std::map< uint64_t,
std::vector< MicromegasRawHit * > > m_MicromegasRawHitMap
std::map< int, uint64_t > m_FEEBclkMap
std::set< uint64_t > m_BclkStack
std::array< bco_alignment_t,
m_max_fee > m_bco_alignment_list
keep one bco alignment object per fee
Static Private Attributes
static constexpr unsigned short m_max_fee {26}
max number of fees per single micromegas input
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Detailed Description
Definition at line 17 of file SingleMicromegasPoolInput.h.
View newest version in sPHENIX GitHub at line 17 of file SingleMicromegasPoolInput.h
Constructor & Destructor Documentation
SingleMicromegasPoolInput::SingleMicromegasPoolInput (const std::string & name = "SingleMicromegasPoolInput") explicit
Definition at line 57 of file SingleMicromegasPoolInput.cc.
View newest version in sPHENIX GitHub at line 57 of file SingleMicromegasPoolInput.cc
References Fun4AllStreamingInputManager::MICROMEGAS, plist, and SingleStreamingInput::SubsystemEnum().
SingleMicromegasPoolInput::~SingleMicromegasPoolInput () override
Definition at line 65 of file SingleMicromegasPoolInput.cc.
View newest version in sPHENIX GitHub at line 65 of file SingleMicromegasPoolInput.cc
References plist.
Member Function Documentation
void SingleMicromegasPoolInput::CleanupUsedPackets (const uint64_t bclk) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 350 of file SingleMicromegasPoolInput.cc.
View newest version in sPHENIX GitHub at line 350 of file SingleMicromegasPoolInput.cc
References m_BclkStack, m_BeamClockFEE, and m_MicromegasRawHitMap.
Referenced by ClearCurrentEvent().
void SingleMicromegasPoolInput::ClearCurrentEvent () override virtual
Reimplemented from SingleStreamingInput.
Definition at line 379 of file SingleMicromegasPoolInput.cc.
View newest version in sPHENIX GitHub at line 379 of file SingleMicromegasPoolInput.cc
References CleanupUsedPackets(), and m_BclkStack.
void SingleMicromegasPoolInput::ConfigureStreamingInputManager () override virtual
Reimplemented from SingleStreamingInput.
Definition at line 439 of file SingleMicromegasPoolInput.cc.
View newest version in sPHENIX GitHub at line 439 of file SingleMicromegasPoolInput.cc
References m_BcoRange, m_NegativeBco, Fun4AllStreamingInputManager::SetMicromegasBcoRange(), Fun4AllStreamingInputManager::SetMicromegasNegativeBco(), and SingleStreamingInput::StreamingInputManager().
void SingleMicromegasPoolInput::CreateDSTNode (PHCompositeNode * topNode) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 411 of file SingleMicromegasPoolInput.cc.
View newest version in sPHENIX GitHub at line 411 of file SingleMicromegasPoolInput.cc
References PHCompositeNode::addNode(), container, and PHNodeIterator::findFirst().
void SingleMicromegasPoolInput::FillPool (const unsigned int nevents = 1) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 71 of file SingleMicromegasPoolInput.cc.
View newest version in sPHENIX GitHub at line 71 of file SingleMicromegasPoolInput.cc
References Fun4AllStreamingInputManager::AddMicromegasRawHit(), SingleStreamingInput::AllDone(), DATAEVENT, SingleStreamingInput::fileclose(), SingleStreamingInput::GetEventiterator(), Event::getEvtSequence(), Event::getEvtType(), Packet::getIdentifier(), Event::getPacketList(), Event::getRunNumber(), GetSomeMoreEvents(), i, Event::identify(), m_BclkStack, m_bco_alignment_list, m_BeamClockFEE, m_FEEBclkMap, m_MicromegasRawHitMap, m_NumSpecialEvents, InputFileHandler::OpenNextFile(), plist, SingleStreamingInput::RunNumber(), SingleStreamingInput::StreamingInputManager(), t, and Fun4AllBase::Verbosity().
bool SingleMicromegasPoolInput::GetSomeMoreEvents ()
Definition at line 387 of file SingleMicromegasPoolInput.cc.
View newest version in sPHENIX GitHub at line 387 of file SingleMicromegasPoolInput.cc
References SingleStreamingInput::AllDone(), m_BcoRange, m_FEEBclkMap, and m_MicromegasRawHitMap.
Referenced by FillPool().
void SingleMicromegasPoolInput::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from SingleStreamingInput.
Definition at line 302 of file SingleMicromegasPoolInput.cc.
View newest version in sPHENIX GitHub at line 302 of file SingleMicromegasPoolInput.cc
References m_BclkStack, m_BeamClockFEE, m_FEEBclkMap, and m_MicromegasRawHitMap.
void SingleMicromegasPoolInput::SetBcoRange (const unsigned int value) inline
Definition at line 29 of file SingleMicromegasPoolInput.h.
View newest version in sPHENIX GitHub at line 29 of file SingleMicromegasPoolInput.h
References m_BcoRange, and value.
Referenced by Fun4All_Stream_Combiner().
void SingleMicromegasPoolInput::SetNegativeBco (const unsigned int value) inline
Definition at line 31 of file SingleMicromegasPoolInput.h.
View newest version in sPHENIX GitHub at line 31 of file SingleMicromegasPoolInput.h
References m_NegativeBco, and value.
Referenced by Fun4All_Stream_Combiner().
Member Data Documentation
std::set<uint64_t> SingleMicromegasPoolInput::m_BclkStack private
Definition at line 42 of file SingleMicromegasPoolInput.h.
View newest version in sPHENIX GitHub at line 42 of file SingleMicromegasPoolInput.h
Referenced by CleanupUsedPackets(), ClearCurrentEvent(), FillPool(), and Print().
std::array<bco_alignment_t, m_max_fee> SingleMicromegasPoolInput::m_bco_alignment_list private
keep one bco alignment object per fee
Definition at line 62 of file SingleMicromegasPoolInput.h.
View newest version in sPHENIX GitHub at line 62 of file SingleMicromegasPoolInput.h
Referenced by FillPool().
unsigned int SingleMicromegasPoolInput::m_BcoRange {0} private
Definition at line 36 of file SingleMicromegasPoolInput.h.
View newest version in sPHENIX GitHub at line 36 of file SingleMicromegasPoolInput.h
Referenced by ConfigureStreamingInputManager(), GetSomeMoreEvents(), and SetBcoRange().
std::map<uint64_t, std::set<int> > SingleMicromegasPoolInput::m_BeamClockFEE private
Definition at line 39 of file SingleMicromegasPoolInput.h.
View newest version in sPHENIX GitHub at line 39 of file SingleMicromegasPoolInput.h
Referenced by CleanupUsedPackets(), FillPool(), and Print().
std::map<int, uint64_t> SingleMicromegasPoolInput::m_FEEBclkMap private
Definition at line 41 of file SingleMicromegasPoolInput.h.
View newest version in sPHENIX GitHub at line 41 of file SingleMicromegasPoolInput.h
Referenced by FillPool(), GetSomeMoreEvents(), and Print().
constexpr unsigned short SingleMicromegasPoolInput::m_max_fee {26} static private
max number of fees per single micromegas input
Definition at line 59 of file SingleMicromegasPoolInput.h.
View newest version in sPHENIX GitHub at line 59 of file SingleMicromegasPoolInput.h
std::map<uint64_t, std::vector<MicromegasRawHit *> > SingleMicromegasPoolInput::m_MicromegasRawHitMap private
Definition at line 40 of file SingleMicromegasPoolInput.h.
View newest version in sPHENIX GitHub at line 40 of file SingleMicromegasPoolInput.h
Referenced by CleanupUsedPackets(), FillPool(), GetSomeMoreEvents(), and Print().
unsigned int SingleMicromegasPoolInput::m_NegativeBco {0} private
Definition at line 37 of file SingleMicromegasPoolInput.h.
View newest version in sPHENIX GitHub at line 37 of file SingleMicromegasPoolInput.h
Referenced by ConfigureStreamingInputManager(), and SetNegativeBco().
unsigned int SingleMicromegasPoolInput::m_NumSpecialEvents {0} private
Definition at line 35 of file SingleMicromegasPoolInput.h.
View newest version in sPHENIX GitHub at line 35 of file SingleMicromegasPoolInput.h
Referenced by FillPool().
Packet** SingleMicromegasPoolInput::plist {nullptr} private
Definition at line 34 of file SingleMicromegasPoolInput.h.
View newest version in sPHENIX GitHub at line 34 of file SingleMicromegasPoolInput.h
Referenced by FillPool(), SingleMicromegasPoolInput(), and ~SingleMicromegasPoolInput().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4allraw/SingleMicromegasPoolInput.h
coresoftware/blob/master/offline/framework/fun4allraw/SingleMicromegasPoolInput.cc