Analysis Software: RDBC/blob/master/macros/RDBCmysql.C File Reference
RDBCmysql.C File Reference
#include <RDBC/TSQLDriverManager.h>
#include <RDBC/TSQLConnection.h>
#include <RDBC/TSQLResultSet.h>
#include <RDBC/TSQLResultSetMetaData.h>
#include <RDBC/TSQLPreparedStatement.h>
#include "../src/dtconv.h"
Classes
class ValueGen1
class ValueGen2
Functions
Bool_t feq (const double &a, const double &b)
Bool_t compareStreams (TBuffer *s1, TBuffer *s2)
void createTables (TSQLConnection *con)
void populateTables (TSQLConnection *con)
void checkTables (TSQLConnection *con)
Bool_t dropTable (TSQLConnection *con, const TString &tableName)
void dropTables (TSQLConnection *con)
int main (int argc, char **argv)
Variables
const char * testchars ="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
const int odbctestRows =5000
const int longtestRows =30
const int longtestSize =123456
int assertionsFailed =0
Function Documentation
void checkTables (TSQLConnection * con)
Definition at line 273 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 273 of file RDBCmysql.C
References testing::internal::Assert(), ValueGen1::cnt(), compareStreams(), ValueGen1::d1(), ValueGen1::dt(), ValueGen1::f1(), ValueGen1::f2(), ValueGen1::f3(), feq(), material_mapping_optimisation::flush, ValueGen1::i1(), ValueGen1::i2(), ValueGen1::i3(), ValueGen1::i4(), ValueGen1::i5(), longtestRows, ValueGen1::Next(), odbctestRows, ValueGen1::s1(), ValueGen1::s2(), ValueGen1::s3(), ValueGen1::s4(), ValueGen1::t(), Acts::Test::tmp(), and ValueGen1::ts().
Referenced by main().
Bool_t compareStreams (TBuffer * s1, TBuffer * s2)
Definition at line 141 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 141 of file RDBCmysql.C
References c2, i, longtestSize, r1, and r2.
Referenced by checkTables().
void createTables (TSQLConnection * con)
Definition at line 169 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 169 of file RDBCmysql.C
References material_mapping_optimisation::flush, and TSQLConnection::PrepareStatement().
Referenced by main().
Bool_t dropTable (TSQLConnection * con, const TString & tableName)
Definition at line 370 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 370 of file RDBCmysql.C
References Acts::UnitConstants::e, TSQLConnection::PrepareStatement(), and physmon_track_finding_ttbar::r.
Referenced by dropTables().
void dropTables (TSQLConnection * con)
Definition at line 384 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 384 of file RDBCmysql.C
References dropTable(), and material_mapping_optimisation::flush.
Referenced by main().
Bool_t feq (const double & a, const double & b)
Definition at line 30 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 30 of file RDBCmysql.C
Referenced by checkTables().
int main (int argc, char ** argv)
Definition at line 401 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 401 of file RDBCmysql.C
References assertionsFailed, checkTables(), con, createTables(), dropTables(), Acts::UnitConstants::e, material_mapping_optimisation::flush, TSQLDriverManager::GetConnection(), and populateTables().
void populateTables (TSQLConnection * con)
Definition at line 209 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 209 of file RDBCmysql.C
References ValueGen2::b(), ValueGen2::c(), ValueGen1::d1(), ValueGen1::dt(), ValueGen1::f1(), ValueGen1::f2(), ValueGen1::f3(), material_mapping_optimisation::flush, ValueGen1::i1(), ValueGen1::i2(), ValueGen1::i3(), ValueGen1::i4(), ValueGen1::i5(), ValueGen2::id(), longtestRows, longtestSize, ValueGen1::Next(), ValueGen2::Next(), odbctestRows, TSQLConnection::PrepareStatement(), ValueGen1::s1(), ValueGen1::s2(), ValueGen1::s3(), ValueGen1::s4(), ValueGen1::t(), and ValueGen1::ts().
Referenced by main().
Variable Documentation
int assertionsFailed =0
Definition at line 27 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 27 of file RDBCmysql.C
Referenced by main().
const int longtestRows =30
Definition at line 24 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 24 of file RDBCmysql.C
Referenced by checkTables(), and populateTables().
const int longtestSize =123456
Definition at line 25 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 25 of file RDBCmysql.C
Referenced by ValueGen2::b(), ValueGen2::c(), compareStreams(), and populateTables().
const int odbctestRows =5000
Definition at line 22 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 22 of file RDBCmysql.C
Referenced by checkTables(), and populateTables().
const char* testchars ="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
Definition at line 20 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 20 of file RDBCmysql.C
Referenced by ValueGen2::c(), and ValueGen1::s1().