Analysis Software: STrackMatcherComparatorHistContent Struct Reference
STrackMatcherComparatorHistContent Struct Reference
#include <analysis/blob/master/AndersonAnalysisModules/TrackStudies/STrackMatchingComparator/src/STrackMatcherComparatorHistContent.h>
Public Attributes
double nTot = numeric_limits<double>::min()
double nIntt = numeric_limits<double>::min()
double nMvtx = numeric_limits<double>::min()
double nTpc = numeric_limits<double>::min()
double rTot = numeric_limits<double>::min()
double rIntt = numeric_limits<double>::min()
double rMvtx = numeric_limits<double>::min()
double rTpc = numeric_limits<double>::min()
double phi = numeric_limits<double>::min()
double eta = numeric_limits<double>::min()
double pt = numeric_limits<double>::min()
double ptFrac = numeric_limits<double>::min()
double quality = numeric_limits<double>::min()
double ptErr = numeric_limits<double>::min()
double etaErr = numeric_limits<double>::min()
double phiErr = numeric_limits<double>::min()
double ptRes = numeric_limits<double>::min()
double etaRes = numeric_limits<double>::min()
double phiRes = numeric_limits<double>::min()
Detailed Description
Definition at line 22 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 22 of file STrackMatcherComparatorHistContent.h
Member Data Documentation
double STrackMatcherComparatorHistContent::eta = numeric_limits<double>::min()
Definition at line 33 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 33 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::etaErr = numeric_limits<double>::min()
Definition at line 38 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 38 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::etaRes = numeric_limits<double>::min()
Definition at line 41 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 41 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::nIntt = numeric_limits<double>::min()
Definition at line 25 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 25 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::nMvtx = numeric_limits<double>::min()
Definition at line 26 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 26 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::nTot = numeric_limits<double>::min()
Definition at line 24 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 24 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::nTpc = numeric_limits<double>::min()
Definition at line 27 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 27 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::phi = numeric_limits<double>::min()
Definition at line 32 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 32 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::phiErr = numeric_limits<double>::min()
Definition at line 39 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 39 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::phiRes = numeric_limits<double>::min()
Definition at line 42 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 42 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::pt = numeric_limits<double>::min()
Definition at line 34 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 34 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::ptErr = numeric_limits<double>::min()
Definition at line 37 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 37 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::ptFrac = numeric_limits<double>::min()
Definition at line 35 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 35 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::ptRes = numeric_limits<double>::min()
Definition at line 40 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 40 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::quality = numeric_limits<double>::min()
Definition at line 36 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 36 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::rIntt = numeric_limits<double>::min()
Definition at line 29 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 29 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::rMvtx = numeric_limits<double>::min()
Definition at line 30 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 30 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::rTot = numeric_limits<double>::min()
Definition at line 28 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 28 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
double STrackMatcherComparatorHistContent::rTpc = numeric_limits<double>::min()
Definition at line 31 of file STrackMatcherComparatorHistContent.h.
View newest version in sPHENIX GitHub at line 31 of file STrackMatcherComparatorHistContent.h
Referenced by STrackMatcherComparator::FillHistogram1D(), and STrackMatcherComparator::FillHistogram2D().
The documentation for this struct was generated from the following file:
analysis/blob/master/AndersonAnalysisModules/TrackStudies/STrackMatchingComparator/src/STrackMatcherComparatorHistContent.h