Analysis Software: BEmcRec Class Reference
BEmcRec Class Reference
#include <coresoftware/blob/master/offline/packages/CaloReco/BEmcRec.h>
Public Member Functions
BEmcRec ()
BEmcRec & operator= (const BEmcRec &)=delete
virtual ~BEmcRec ()
void SetVertex (const float *vv)
void SetDim (int nx, int ny)
bool SetTowerGeometry (int ix, int iy, float xx, float yy, float zz)
bool GetTowerGeometry (int ix, int iy, TowerGeom &geom)
bool CompleteTowerGeometry ()
void PrintTowerGeometry (const std::string &fname)
void SetPlanarGeometry ()
void SetCylindricalGeometry ()
bool isCylindrical () const
void SetProfileProb (bool bprob)
void SetCalotype (int caloid)
void SetScinSize (float S_S)
int GetNx () const
int GetNy () const
int GetCalotype () const
float GetScinSize () const
float GetVx () const
float GetVy () const
float GetVz () const
void SetPeakThreshold (float Thresh)
float GetPeakThreshold ()
void SetTowerThreshold (float Thresh)
float GetTowerThreshold ()
void SetModules (const std::vector< EmcModule > *modules)
std::vector< EmcModule > * GetModules ()
std::vector< EmcCluster > * GetClusters ()
int iTowerDist (int ix1, int ix2)
float fTowerDist (float x1, float x2)
int FindClusters ()
void Momenta (std::vector< EmcModule > *, float &, float &, float &, float &, float &, float &, float thresh=0)
void Tower2Global (float E, float xC, float yC, float &xA, float &yA, float &zA)
float GetTowerEnergy (int iy, int iz, std::vector< EmcModule > *plist)
float PredictEnergy (float, float, float, int, int)
float PredictEnergyProb (float en, float xcg, float ycg, int ix, int iy)
virtual float PredictEnergyParam (float, float, float)
virtual void CorrectEnergy (float energy, float, float, float &ecorr)
virtual void CorrectECore (float ecore, float, float, float &ecorecorr)
virtual void CorrectPosition (float, float x, float y, float &xcorr, float &ycorr)
virtual void CorrectShowerDepth (float, float x, float y, float z, float &xc, float &yc, float &zc)
virtual void LoadProfile (const std::string &fname)
virtual void GetImpactThetaPhi (float, float, float, float &theta, float &phi)
float GetProb (std::vector< EmcModule > HitList, float e, float xg, float yg, float zg, float &chi2, int &ndf)
void SetProbNoiseParam (float rn)
float GetProbNoiseParam ()
virtual std::string Name () const
virtual void Name (const std::string &name)
Static Public Member Functions
static int HitNCompare (const void *, const void *)
static int HitACompare (const void *, const void *)
static void CopyVector (const int *, int *, int)
static void CopyVector (const EmcModule *, EmcModule *, int)
static void ZeroVector (int *, int)
static void ZeroVector (float *, int)
static void ZeroVector (EmcModule *, int)
Protected Attributes
bool bCYL = true
bool bProfileProb = false
int fNx = -1
int fNy = -1
std::map< int, TowerGeom > fTowerGeom
float fVx = 0.
float fVy = 0.
float fVz = 0.
std::vector< EmcModule > * fModules
std::vector< EmcCluster > * fClusters
float fgProbNoiseParam = 0.04
float fgTowerThresh = 0.01
float fgMinPeakEnergy = 0.08
BEmcProfile * _emcprof = nullptr
Static Protected Attributes
static int const fgMaxLen = 1000
Private Member Functions
BEmcRec (const BEmcRec &)=delete
Private Attributes
std::string m_ThisName = "NOTSET"
int Calorimeter_ID = 0
float Scin_size = NAN
Detailed Description
Definition at line 31 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 31 of file BEmcRec.h
Constructor & Destructor Documentation
BEmcRec::BEmcRec ()
Definition at line 23 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 23 of file BEmcRec.cc
References fClusters, fModules, and fTowerGeom.
BEmcRec::~BEmcRec () virtual
Definition at line 32 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 32 of file BEmcRec.cc
References _emcprof, fClusters, and fModules.
BEmcRec::BEmcRec (const BEmcRec &) private delete
Member Function Documentation
bool BEmcRec::CompleteTowerGeometry ()
Definition at line 128 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 128 of file BEmcRec.cc
References TowerGeom::dX, TowerGeom::dY, TowerGeom::dZ, fNx, fTowerGeom, GetTowerGeometry(), ambiguity_solver_full_chain::idx, it, TowerGeom::Xcenter, TowerGeom::Ycenter, and TowerGeom::Zcenter.
Referenced by RawClusterBuilderTemplate::InitRun().
void BEmcRec::CopyVector (const int * from, int * to, int N) static
Definition at line 947 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 947 of file BEmcRec.cc
References i, and N.
Referenced by FindClusters().
void BEmcRec::CopyVector (const EmcModule * from, EmcModule * to, int N) static
Definition at line 961 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 961 of file BEmcRec.cc
References i, and N.
virtual void BEmcRec::CorrectECore (float ecore, float , float , float & ecorecorr) inline virtual
Reimplemented in BEmcRecCEMC.
Definition at line 96 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 96 of file BEmcRec.h
Referenced by EmcCluster::GetECoreCorrected().
virtual void BEmcRec::CorrectEnergy (float energy, float , float , float & ecorr) inline virtual
Reimplemented in BEmcRecCEMC.
Definition at line 95 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 95 of file BEmcRec.h
References energy.
virtual void BEmcRec::CorrectPosition (float , float x, float y, float & xcorr, float & ycorr) inline virtual
Reimplemented in BEmcRecCEMC.
Definition at line 97 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 97 of file BEmcRec.h
References ambiguity_solver_full_chain::x, and y.
Referenced by EmcCluster::GetCorrPos().
virtual void BEmcRec::CorrectShowerDepth (float , float x, float y, float z, float & xc, float & yc, float & zc) inline virtual
Reimplemented in BEmcRecCEMC.
Definition at line 102 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 102 of file BEmcRec.h
References ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by Tower2Global().
int BEmcRec::FindClusters ()
Definition at line 315 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 315 of file BEmcRec.cc
References bCYL, CopyVector(), fClusters, fgMaxLen, fModules, fNx, HitNCompare(), i, add_histos_bX::ib, EmcModule::ich, next, EmcCluster::ReInitialize(), and ZeroVector().
Referenced by RawClusterBuilderTemplate::process_event().
float BEmcRec::fTowerDist (float x1, float x2)
Definition at line 292 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 292 of file BEmcRec.cc
References bCYL, dist(), and fNx.
Referenced by EmcCluster::GetSubClusters(), PredictEnergy(), and PredictEnergyProb().
int BEmcRec::GetCalotype () const inline
Definition at line 65 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 65 of file BEmcRec.h
References Calorimeter_ID.
std::vector<EmcCluster>* BEmcRec::GetClusters () inline
Definition at line 77 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 77 of file BEmcRec.h
References fClusters.
Referenced by RawClusterBuilderTemplate::process_event().
virtual void BEmcRec::GetImpactThetaPhi (float , float , float , float & theta, float & phi) inline virtual
Reimplemented in BEmcRecCEMC.
Definition at line 109 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 109 of file BEmcRec.h
Referenced by GetProb(), and PredictEnergyProb().
std::vector<EmcModule>* BEmcRec::GetModules () inline
Definition at line 76 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 76 of file BEmcRec.h
References fModules.
int BEmcRec::GetNx () const inline
Definition at line 63 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 63 of file BEmcRec.h
References fNx.
Referenced by EmcCluster::GetE9(), EmcCluster::GetECore(), EmcCluster::GetSubClusters(), and EmcCluster::GetTowerEnergy().
int BEmcRec::GetNy () const inline
Definition at line 64 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 64 of file BEmcRec.h
References fNy.
float BEmcRec::GetPeakThreshold () inline
Definition at line 71 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 71 of file BEmcRec.h
References fgMinPeakEnergy.
Referenced by EmcCluster::GetSubClusters().
float BEmcRec::GetProb (std::vector< EmcModule > HitList, float e, float xg, float yg, float zg, float & chi2, int & ndf)
Definition at line 773 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 773 of file BEmcRec.cc
References _emcprof, check_license::err(), GetImpactThetaPhi(), GetProbNoiseParam(), GetTowerEnergy(), GetTowerThreshold(), BEmcProfile::IsLoaded(), Momenta(), NP, ActsTests::PropagationDatasets::phi, BEmcProfile::PredictEnergy(), and ActsTests::PropagationDatasets::theta.
Referenced by EmcCluster::GetProb(), and CaloRecoUtility::ProbCorrsZVertex().
float BEmcRec::GetProbNoiseParam () inline
Definition at line 117 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 117 of file BEmcRec.h
References fgProbNoiseParam.
Referenced by GetProb().
float BEmcRec::GetScinSize () const inline
Definition at line 66 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 66 of file BEmcRec.h
References Scin_size.
float BEmcRec::GetTowerEnergy (int iy, int iz, std::vector< EmcModule > * plist)
Definition at line 751 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 751 of file BEmcRec.cc
References fNx, i, and izt.
Referenced by GetProb().
bool BEmcRec::GetTowerGeometry (int ix, int iy, TowerGeom & geom)
Definition at line 90 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 90 of file BEmcRec.cc
References fNx, fNy, fTowerGeom, and it.
Referenced by CompleteTowerGeometry(), and Tower2Global().
float BEmcRec::GetTowerThreshold () inline
Definition at line 73 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 73 of file BEmcRec.h
References fgTowerThresh.
Referenced by GetProb().
float BEmcRec::GetVx () const inline
Definition at line 67 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 67 of file BEmcRec.h
References fVx.
float BEmcRec::GetVy () const inline
Definition at line 68 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 68 of file BEmcRec.h
References fVy.
float BEmcRec::GetVz () const inline
Definition at line 69 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 69 of file BEmcRec.h
References fVz.
int BEmcRec::HitACompare (const void * h1, const void * h2) static
Definition at line 902 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 902 of file BEmcRec.cc
References h1, and h2.
int BEmcRec::HitNCompare (const void * h1, const void * h2) static
Definition at line 895 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 895 of file BEmcRec.cc
Referenced by FindClusters(), and EmcCluster::GetSubClusters().
bool BEmcRec::isCylindrical () const inline
Definition at line 57 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 57 of file BEmcRec.h
References bCYL.
int BEmcRec::iTowerDist (int ix1, int ix2)
Definition at line 269 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 269 of file BEmcRec.cc
References bCYL, and fNx.
Referenced by EmcCluster::GetE9(), EmcCluster::GetSubClusters(), Momenta(), and PredictEnergyProb().
void BEmcRec::LoadProfile (const std::string & fname) virtual
Reimplemented in BEmcRecCEMC.
Definition at line 51 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 51 of file BEmcRec.cc
References Name().
Referenced by CaloRecoUtility::LoadProfile(), and RawClusterBuilderTemplate::LoadProfile().
void BEmcRec::Momenta (std::vector< EmcModule > * phit, float & pe, float & px, float & py, float & pxx, float & pyy, float & pyx, float thresh = 0)
Definition at line 475 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 475 of file BEmcRec.cc
References KFPMath::a, Acts::UnitConstants::e, fNx, ambiguity_solver_full_chain::idx, iTowerDist(), ambiguity_solver_full_chain::x, and y.
Referenced by EmcCluster::GetCorrPos(), EmcCluster::GetE4(), EmcCluster::GetE9(), EmcCluster::GetECore(), EmcCluster::GetECoreCorrected(), EmcCluster::GetMoments(), and GetProb().
virtual std::string BEmcRec::Name () const inline virtual
Definition at line 119 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 119 of file BEmcRec.h
References m_ThisName.
Referenced by BEmcRecCEMC::BEmcRecCEMC(), and LoadProfile().
virtual void BEmcRec::Name (const std::string & name) inline virtual
Definition at line 120 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 120 of file BEmcRec.h
References m_ThisName, and perf_headwind::name.
BEmcRec& BEmcRec::operator= (const BEmcRec &) delete
float BEmcRec::PredictEnergy (float en, float xcg, float ycg, int ix, int iy)
Definition at line 581 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 581 of file BEmcRec.cc
References _emcprof, bProfileProb, dy, fTowerDist(), PredictEnergyParam(), and PredictEnergyProb().
Referenced by EmcCluster::GetECore(), and EmcCluster::GetSubClusters().
float BEmcRec::PredictEnergyParam (float , float xc, float yc) virtual
Definition at line 593 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 593 of file BEmcRec.cc
References dy, Acts::UnitConstants::e, r1, r2, and r3.
Referenced by PredictEnergy().
float BEmcRec::PredictEnergyProb (float en, float xcg, float ycg, int ix, int iy)
Definition at line 645 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 645 of file BEmcRec.cc
References _emcprof, dy, Acts::UnitConstants::e, check_license::err(), fNx, fTowerDist(), GetImpactThetaPhi(), ambiguity_solver_full_chain::idx, iTowerDist(), ActsTests::PropagationDatasets::phi, BEmcProfile::PredictEnergy(), BEmcProfile::PredictEnergyR(), ActsTests::PropagationDatasets::theta, and Tower2Global().
Referenced by PredictEnergy().
void BEmcRec::PrintTowerGeometry (const std::string & fname)
Definition at line 56 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 56 of file BEmcRec.cc
References TowerGeom::dX, TowerGeom::dY, TowerGeom::dZ, fNx, fNy, fTowerGeom, it, add_histos::outfile, TowerGeom::Xcenter, TowerGeom::Ycenter, and TowerGeom::Zcenter.
Referenced by RawClusterBuilderTemplate::InitRun().
void BEmcRec::SetCalotype (int caloid) inline
Definition at line 60 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 60 of file BEmcRec.h
References Calorimeter_ID.
Referenced by RawClusterBuilderTemplate::InitRun().
void BEmcRec::SetCylindricalGeometry () inline
Definition at line 56 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 56 of file BEmcRec.h
References bCYL.
Referenced by BEmcRecCEMC::BEmcRecCEMC(), and RawClusterBuilderTemplate::SetCylindricalGeometry().
void BEmcRec::SetDim (int nx, int ny) inline
Definition at line 44 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 44 of file BEmcRec.h
References fNx, fNy, nx, and ny.
Referenced by CaloRecoUtility::CaloRecoUtility(), RawClusterBuilderTemplate::InitRun(), and CaloRecoUtility::operator=().
void BEmcRec::SetModules (const std::vector< EmcModule > * modules) inline
Definition at line 75 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 75 of file BEmcRec.h
References fModules.
Referenced by RawClusterBuilderTemplate::process_event().
void BEmcRec::SetPeakThreshold (float Thresh) inline
Definition at line 70 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 70 of file BEmcRec.h
References fgMinPeakEnergy.
void BEmcRec::SetPlanarGeometry () inline
Definition at line 55 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 55 of file BEmcRec.h
References bCYL.
Referenced by RawClusterBuilderTemplate::SetPlanarGeometry().
void BEmcRec::SetProbNoiseParam (float rn) inline
Definition at line 116 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 116 of file BEmcRec.h
References fgProbNoiseParam.
Referenced by CaloRecoUtility::CaloRecoUtility(), RawClusterBuilderTemplate::Detector(), CaloRecoUtility::operator=(), and RawClusterBuilderTemplate::process_event().
void BEmcRec::SetProfileProb (bool bprob) inline
Definition at line 59 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 59 of file BEmcRec.h
References bProfileProb.
Referenced by RawClusterBuilderTemplate::process_event().
void BEmcRec::SetScinSize (float S_S) inline
Definition at line 61 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 61 of file BEmcRec.h
References Scin_size.
Referenced by RawClusterBuilderTemplate::InitRun().
bool BEmcRec::SetTowerGeometry (int ix, int iy, float xx, float yy, float zz)
Definition at line 108 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 108 of file BEmcRec.cc
References TowerGeom::dX, TowerGeom::dY, TowerGeom::dZ, fNx, fNy, fTowerGeom, TowerGeom::Xcenter, TowerGeom::Ycenter, and TowerGeom::Zcenter.
Referenced by RawClusterBuilderTemplate::InitRun().
void BEmcRec::SetTowerThreshold (float Thresh) inline
Definition at line 72 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 72 of file BEmcRec.h
References fgTowerThresh.
Referenced by CaloRecoUtility::CaloRecoUtility(), RawClusterBuilderTemplate::Detector(), CaloRecoUtility::operator=(), and RawClusterBuilderTemplate::process_event().
void BEmcRec::SetVertex (const float * vv) inline
Definition at line 38 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 38 of file BEmcRec.h
References fVx, fVy, and fVz.
Referenced by RawClusterBuilderTemplate::Detector(), CaloRecoUtility::ProbCorrsZVertex(), and RawClusterBuilderTemplate::process_event().
void BEmcRec::Tower2Global (float E, float xC, float yC, float & xA, float & yA, float & zA)
Definition at line 193 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 193 of file BEmcRec.cc
References CorrectShowerDepth(), TowerGeom::dX, TowerGeom::dY, TowerGeom::dZ, fNx, fNy, GetTowerGeometry(), ambiguity_solver_full_chain::idx, m_ThisName, TowerGeom::Xcenter, TowerGeom::Ycenter, and TowerGeom::Zcenter.
Referenced by EmcCluster::GetGlobalPos(), and PredictEnergyProb().
void BEmcRec::ZeroVector (int * v, int N) static
Definition at line 912 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 912 of file BEmcRec.cc
References i, N, merge_hashes::p, and testSigmaEff::v.
Referenced by FindClusters(), and EmcCluster::GetSubClusters().
void BEmcRec::ZeroVector (float * v, int N) static
Definition at line 923 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 923 of file BEmcRec.cc
References i, N, merge_hashes::p, and testSigmaEff::v.
void BEmcRec::ZeroVector (EmcModule * v, int N) static
Definition at line 934 of file BEmcRec.cc.
View newest version in sPHENIX GitHub at line 934 of file BEmcRec.cc
References EmcModule::amp, i, EmcModule::ich, N, and EmcModule::tof.
Member Data Documentation
BEmcProfile* BEmcRec::_emcprof = nullptr protected
Definition at line 150 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 150 of file BEmcRec.h
Referenced by GetProb(), BEmcRecCEMC::LoadProfile(), PredictEnergy(), PredictEnergyProb(), and ~BEmcRec().
bool BEmcRec::bCYL = true protected
Definition at line 133 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 133 of file BEmcRec.h
Referenced by FindClusters(), fTowerDist(), isCylindrical(), iTowerDist(), SetCylindricalGeometry(), and SetPlanarGeometry().
bool BEmcRec::bProfileProb = false protected
Definition at line 134 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 134 of file BEmcRec.h
Referenced by PredictEnergy(), and SetProfileProb().
int BEmcRec::Calorimeter_ID = 0 private
Definition at line 154 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 154 of file BEmcRec.h
Referenced by GetCalotype(), and SetCalotype().
std::vector<EmcCluster>* BEmcRec::fClusters protected
Definition at line 143 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 143 of file BEmcRec.h
Referenced by BEmcRec(), FindClusters(), GetClusters(), and ~BEmcRec().
int const BEmcRec::fgMaxLen = 1000 static protected
Definition at line 148 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 148 of file BEmcRec.h
Referenced by FindClusters().
float BEmcRec::fgMinPeakEnergy = 0.08 protected
Definition at line 147 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 147 of file BEmcRec.h
Referenced by GetPeakThreshold(), and SetPeakThreshold().
float BEmcRec::fgProbNoiseParam = 0.04 protected
Definition at line 145 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 145 of file BEmcRec.h
Referenced by GetProbNoiseParam(), and SetProbNoiseParam().
float BEmcRec::fgTowerThresh = 0.01 protected
Definition at line 146 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 146 of file BEmcRec.h
Referenced by GetTowerThreshold(), and SetTowerThreshold().
std::vector<EmcModule>* BEmcRec::fModules protected
Definition at line 142 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 142 of file BEmcRec.h
Referenced by BEmcRec(), FindClusters(), GetModules(), SetModules(), and ~BEmcRec().
int BEmcRec::fNx = -1 protected
Definition at line 135 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 135 of file BEmcRec.h
Referenced by CompleteTowerGeometry(), BEmcRecCEMC::CorrectPosition(), FindClusters(), fTowerDist(), GetNx(), GetTowerEnergy(), GetTowerGeometry(), iTowerDist(), Momenta(), PredictEnergyProb(), PrintTowerGeometry(), SetDim(), SetTowerGeometry(), and Tower2Global().
int BEmcRec::fNy = -1 protected
Definition at line 136 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 136 of file BEmcRec.h
Referenced by GetNy(), GetTowerGeometry(), PrintTowerGeometry(), SetDim(), SetTowerGeometry(), and Tower2Global().
std::map<int, TowerGeom> BEmcRec::fTowerGeom protected
Definition at line 137 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 137 of file BEmcRec.h
Referenced by BEmcRec(), CompleteTowerGeometry(), GetTowerGeometry(), PrintTowerGeometry(), and SetTowerGeometry().
float BEmcRec::fVx = 0. protected
Definition at line 138 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 138 of file BEmcRec.h
Referenced by GetVx(), and SetVertex().
float BEmcRec::fVy = 0. protected
Definition at line 139 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 139 of file BEmcRec.h
Referenced by GetVy(), and SetVertex().
float BEmcRec::fVz = 0. protected
Definition at line 140 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 140 of file BEmcRec.h
Referenced by BEmcRecCEMC::CorrectShowerDepth(), BEmcRecCEMC::GetImpactThetaPhi(), GetVz(), and SetVertex().
std::string BEmcRec::m_ThisName = "NOTSET" private
Definition at line 153 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 153 of file BEmcRec.h
Referenced by Name(), and Tower2Global().
float BEmcRec::Scin_size = NAN private
Definition at line 155 of file BEmcRec.h.
View newest version in sPHENIX GitHub at line 155 of file BEmcRec.h
Referenced by GetScinSize(), and SetScinSize().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/BEmcRec.h
coresoftware/blob/master/offline/packages/CaloReco/BEmcRec.cc