Analysis Software: JETSCAPE/blob/main/external_packages/gtl/include/GTL/gml_scanner.h File Reference
gml_scanner.h File Reference
#include <GTL/GTL.h>
#include <cstdio>
Classes
struct GML_error
Reason and position of an error in a GML file.
union GML_tok_val
struct GML_token
Macros
#define INITIAL_SIZE 1024
Enumerations
enum GML_value {
GML_KEY, GML_INT, GML_DOUBLE, GML_STRING,
GML_L_BRACKET, GML_R_BRACKET, GML_END, GML_LIST,
GML_ERROR
}
enum GML_error_value {
GML_UNEXPECTED, GML_SYNTAX, GML_PREMATURE_EOF, GML_TOO_MANY_DIGITS,
GML_OPEN_BRACKET, GML_TOO_MANY_BRACKETS, GML_OK, GML_FILE_NOT_FOUND
}
Functions
GTL_EXTERN void GML_init ()
GTL_EXTERN struct GML_token GML_scanner (FILE *)
Variables
GTL_EXTERN unsigned int GML_line
GTL_EXTERN unsigned int GML_column
GTL_EXTERN const char * GML_table []
Macro Definition Documentation
#define INITIAL_SIZE 1024
Definition at line 23 of file gml_scanner.h.
View newest version in sPHENIX GitHub at line 23 of file gml_scanner.h
Referenced by GML_scanner().
Enumeration Type Documentation
enum GML_error_value
Possible errors while parsing a GML file.
Enumerator:
GML_UNEXPECTED
GML_SYNTAX
GML_PREMATURE_EOF
GML_TOO_MANY_DIGITS
GML_OPEN_BRACKET
GML_TOO_MANY_BRACKETS
GML_OK
GML_FILE_NOT_FOUND
Definition at line 34 of file gml_scanner.h.
View newest version in sPHENIX GitHub at line 34 of file gml_scanner.h
enum GML_value
Enumerator:
GML_KEY
GML_INT
GML_DOUBLE
GML_STRING
GML_L_BRACKET
GML_R_BRACKET
GML_END
GML_LIST
GML_ERROR
Definition at line 25 of file gml_scanner.h.
View newest version in sPHENIX GitHub at line 25 of file gml_scanner.h
Function Documentation
GTL_EXTERN void GML_init ()
Definition at line 167 of file gml_scanner.cpp.
View newest version in sPHENIX GitHub at line 167 of file gml_scanner.cpp
References GML_column, and GML_line.
Referenced by graph::load().
GTL_EXTERN struct GML_token GML_scanner (FILE *) read
Definition at line 175 of file gml_scanner.cpp.
View newest version in sPHENIX GitHub at line 175 of file gml_scanner.cpp
References assert, GML_error::column, test_fpe::count, GML_tok_val::err, GML_error::err_num, GML_tok_val::floating, GML_column, GML_DOUBLE, GML_END, GML_ERROR, GML_INT, GML_KEY, GML_L_BRACKET, GML_line, GML_PREMATURE_EOF, GML_R_BRACKET, GML_scanner(), GML_search_ISO(), GML_STRING, GML_TOO_MANY_DIGITS, GML_UNEXPECTED, INITIAL_SIZE, GML_tok_val::integer, GML_token::kind, GML_error::line, next, parse_cmake_options::source, GML_tok_val::str, Acts::Test::tmp(), token, and GML_token::value.
Referenced by GML_parser(), and GML_scanner().
Variable Documentation
GTL_EXTERN unsigned int GML_column
Definition at line 134 of file gml_scanner.cpp.
View newest version in sPHENIX GitHub at line 134 of file gml_scanner.cpp
Referenced by GML_init(), GML_parser(), and GML_scanner().
GTL_EXTERN unsigned int GML_line
Definition at line 133 of file gml_scanner.cpp.
View newest version in sPHENIX GitHub at line 133 of file gml_scanner.cpp
Referenced by GML_init(), GML_parser(), and GML_scanner().
GTL_EXTERN const char* GML_table[]
Definition at line 33 of file gml_scanner.cpp.
View newest version in sPHENIX GitHub at line 33 of file gml_scanner.cpp
Referenced by GML_search_ISO().