Analysis Software: BbcOut Class Reference
BbcOut Class Reference
#include <coresoftware/blob/master/offline/packages/mbd/BbcOut.h>
Public Member Functions
~BbcOut () override
void identify (std::ostream &os=std::cout) const override
virtual void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
virtual Float_t get_zvtx () const
get ZVertex determined by Bbc
virtual Float_t get_zvtxerr () const
get Error on ZVertex determined by Bbc
virtual Float_t get_t0 () const
get T0 determined by Bbc
virtual Float_t get_t0err () const
get Error on T0 determined by Bbc
virtual void set_t0zvtx (const Float_t t0, const Float_t t0err, const Float_t vtx, const Float_t vtxerr)
virtual void set_t0 (const Float_t t0, const Float_t t0err=0)
virtual void set_zvtx (const Float_t vtx, const Float_t vtxerr)
set vertex
virtual void set_zvtxerr (const Float_t vtxerr)
virtual void set_arm (const int iarm, const Short_t npmt, const Float_t ncharge, const Float_t timing)
virtual void set_clocks (const Int_t ievt, const UShort_t iclk, const UShort_t ifemclk)
virtual Short_t get_npmt (const int iarm) const
virtual Float_t get_q (const int iarm) const
virtual Float_t get_time (const int iarm) const
virtual Int_t get_evt () const
virtual UShort_t get_clock () const
virtual UShort_t get_femclock () const
virtual void FillFromClass (const BbcOut &old)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
void virtual_warning (const std::string &funcname) const
Detailed Description
Definition at line 11 of file BbcOut.h.
View newest version in sPHENIX GitHub at line 11 of file BbcOut.h
Constructor & Destructor Documentation
BbcOut::~BbcOut () inline override
Definition at line 15 of file BbcOut.h.
View newest version in sPHENIX GitHub at line 15 of file BbcOut.h
Member Function Documentation
void BbcOut::FillFromClass (const BbcOut & old) virtual
Definition at line 126 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 126 of file BbcOut.cc
References get_npmt(), get_q(), get_t0(), get_t0err(), get_time(), get_zvtx(), get_zvtxerr(), set_arm(), and set_t0zvtx().
UShort_t BbcOut::get_clock () const virtual
get XMIT Clock Counter
Reimplemented in BbcOutV2.
Definition at line 108 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 108 of file BbcOut.cc
References virtual_warning().
Int_t BbcOut::get_evt () const virtual
get Event Number
Reimplemented in BbcOutV2.
Definition at line 102 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 102 of file BbcOut.cc
References virtual_warning().
UShort_t BbcOut::get_femclock () const virtual
get FEM Clock Counter
Reimplemented in BbcOutV2.
Definition at line 114 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 114 of file BbcOut.cc
References virtual_warning().
Short_t BbcOut::get_npmt (const int iarm) const virtual
get Number of PMT's fired in North/South Bbc
Parameters
iarm Arm, use Bbc::North and Bbc::South
Reimplemented in BbcOutV2, and BbcOutV1.
Definition at line 84 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 84 of file BbcOut.cc
References BbcReturnCodes::BBC_INVALID_SHORT, and virtual_warning().
Referenced by FillFromClass().
Float_t BbcOut::get_q (const int iarm) const virtual
get Number of Charged Particles into North/South Bbc
Parameters
iarm Arm, use Bbc::North and Bbc::South
Reimplemented in BbcOutV2, and BbcOutV1.
Definition at line 90 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 90 of file BbcOut.cc
References virtual_warning().
Referenced by FillFromClass().
Float_t BbcOut::get_t0 () const virtual
get T0 determined by Bbc
Reimplemented in BbcOutV1, and BbcOutV2.
Definition at line 37 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 37 of file BbcOut.cc
References virtual_warning().
Referenced by FillFromClass().
Float_t BbcOut::get_t0err () const virtual
get Error on T0 determined by Bbc
Reimplemented in BbcOutV1, and BbcOutV2.
Definition at line 44 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 44 of file BbcOut.cc
References virtual_warning().
Referenced by FillFromClass().
Float_t BbcOut::get_time (const int iarm) const virtual
get Timing of North/South Bbc
Parameters
iarm Arm, use Bbc::North and Bbc::South
Reimplemented in BbcOutV2, and BbcOutV1.
Definition at line 96 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 96 of file BbcOut.cc
References virtual_warning().
Referenced by FillFromClass().
Float_t BbcOut::get_zvtx () const virtual
get ZVertex determined by Bbc
Reimplemented in BbcOutV1, and BbcOutV2.
Definition at line 25 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 25 of file BbcOut.cc
References virtual_warning().
Referenced by FillFromClass().
Float_t BbcOut::get_zvtxerr () const virtual
get Error on ZVertex determined by Bbc
Reimplemented in BbcOutV1, and BbcOutV2.
Definition at line 31 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 31 of file BbcOut.cc
References virtual_warning().
Referenced by FillFromClass().
void BbcOut::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in BbcOutV1, and BbcOutV2.
Definition at line 7 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 7 of file BbcOut.cc
int BbcOut::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in BbcOutV1, and BbcOutV2.
Definition at line 19 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 19 of file BbcOut.cc
References virtual_warning().
void BbcOut::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in BbcOutV1, and BbcOutV2.
Definition at line 13 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 13 of file BbcOut.cc
void BbcOut::set_arm (const int iarm, const Short_t npmt, const Float_t ncharge, const Float_t timing) virtual
Add Bbc North/South data containing Number of pmt's, Energy and Timing
Parameters
npmt Number of PMT's fired
ncharge Number of Charged Particles into North/South
timing Timing of North/South
iarm Arm, use Bbc::North and Bbc::South
Reimplemented in BbcOutV1, and BbcOutV2.
Definition at line 72 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 72 of file BbcOut.cc
References virtual_warning().
Referenced by FillFromClass().
void BbcOut::set_clocks (const Int_t ievt, const UShort_t iclk, const UShort_t ifemclk) virtual
Add Bbc data containing evt, clk, and femclk
Parameters
ievt Event number
iclk XMIT clock
ifemclk FEM clock
Reimplemented in BbcOutV2.
Definition at line 78 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 78 of file BbcOut.cc
References virtual_warning().
void BbcOut::set_t0 (const Float_t t0, const Float_t t0err = 0) virtual
set T0 for Bbc
Parameters
t0 Bbc T0
t0err Bbc T0 error
Reimplemented in BbcOutV1, and BbcOutV2.
Definition at line 51 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 51 of file BbcOut.cc
References virtual_warning().
Referenced by set_t0zvtx().
virtual void BbcOut::set_t0zvtx (const Float_t t0, const Float_t t0err, const Float_t vtx, const Float_t vtxerr) inline virtual
set T0, Error on T0, ZVertex and Error on ZVertex
Parameters
t0 Bbc T0
t0err Bbc Error on T0
vtx Bbc ZVertex
vtxerr Bbc Error on ZVertex
Definition at line 46 of file BbcOut.h.
View newest version in sPHENIX GitHub at line 46 of file BbcOut.h
References set_t0(), and set_zvtx().
Referenced by FillFromClass().
void BbcOut::set_zvtx (const Float_t vtx, const Float_t vtxerr) virtual
set vertex
Reimplemented in BbcOutV1, and BbcOutV2.
Definition at line 58 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 58 of file BbcOut.cc
References virtual_warning().
Referenced by set_t0zvtx().
void BbcOut::set_zvtxerr (const Float_t vtxerr) virtual
set Vtx Error for Bbc
Parameters
vtxerr Bbc Vtx Error
Reimplemented in BbcOutV1, and BbcOutV2.
Definition at line 65 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 65 of file BbcOut.cc
References virtual_warning().
void BbcOut::virtual_warning (const std::string & funcname) const private
Definition at line 120 of file BbcOut.cc.
View newest version in sPHENIX GitHub at line 120 of file BbcOut.cc
Referenced by get_clock(), get_evt(), get_femclock(), get_npmt(), get_q(), get_t0(), get_t0err(), get_time(), get_zvtx(), get_zvtxerr(), isValid(), set_arm(), set_clocks(), set_t0(), set_zvtx(), and set_zvtxerr().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mbd/BbcOut.h
coresoftware/blob/master/offline/packages/mbd/BbcOut.cc