Analysis Software: quick_view Namespace Reference
quick_view Namespace Reference
Functions
def help
def plot
def main
Function Documentation
def quick_view.help ()
  This script plots
    (1) transverse intergated entropy/density as function of rapidity
    (2) Projection of entropy/density onto x-y (eta=0) plane
    (3) ............................. onto y-eta (x=0) plane.
    (4) ............................. onto x-eta (y=0) plane.
  Usage:
    {:s} trento3d-hdf5-output [list-of-event-id-to-convert]
  For example, to view all events:
    {:s} ic.hdf5
  To view only events #2 and #3:
    {:s} ic.hdf5 2 3
Definition at line 6 of file quick_view.py.
View newest version in sPHENIX GitHub at line 6 of file quick_view.py
References print().
Referenced by main().
def quick_view.main (void)
Definition at line 61 of file quick_view.py.
View newest version in sPHENIX GitHub at line 61 of file quick_view.py
References material_mapping_optimisation.format, help(), and plot().
def quick_view.plot (dataset)
Definition at line 25 of file quick_view.py.
View newest version in sPHENIX GitHub at line 25 of file quick_view.py
References Acts.zip().
Referenced by main().