Analysis Software: macros/blob/master/common/G4_BeamLine.C File Reference
G4_BeamLine.C File Reference
#include <GlobalVariables.C>
#include <G4_Pipe.C>
#include <g4detectors/BeamLineMagnetSubsystem.h>
#include <g4detectors/PHG4BlockSubsystem.h>
#include <g4detectors/PHG4ConeSubsystem.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4detectors/PHG4ZDCSubsystem.h>
#include <g4detectors/PHG4DetectorSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <TSystem.h>
Namespaces
namespace Enable
namespace G4BEAMLINE
Macros
#define MACRO_G4BEAMLINE_C
Functions
float PosFlip (float pos)
float AngleFlip (float angle)
float MagFieldFlip (float Bfield)
PHG4CylinderSubsystem * G4BEAMLINE::ForwardBeamLineEnclosure (nullptr)
PHG4CylinderSubsystem * G4BEAMLINE::BackwardBeamLineEnclosure (nullptr)
void BeamLineInit ()
void BeamLineDefineMagnets (PHG4Reco *g4Reco)
void BeamLineDefineBeamPipe (PHG4Reco *g4Reco)
Variables
bool Enable::BEAMLINE = false
bool Enable::BEAMLINE_ABSORBER = false
bool Enable::BEAMLINE_BLACKHOLE = false
bool Enable::BEAMLINE_OVERLAPCHECK = false
int Enable::BEAMLINE_VERBOSITY = 0
double G4BEAMLINE::starting_z = G4PIPE::max_z + 2*no_overlapp
double G4BEAMLINE::enclosure_z_max = 2050. + (800-starting_z)
double G4BEAMLINE::enclosure_r_max = 30.
double G4BEAMLINE::enclosure_center = 0.5 * (starting_z + enclosure_z_max)
double G4BEAMLINE::skin_thickness = 0.
int G4BEAMLINE::pipe_id_offset = 100
int G4BEAMLINE::roman_pot_pipe_id_offset = 200
Macro Definition Documentation
#define MACRO_G4BEAMLINE_C
Definition at line 2 of file G4_BeamLine.C.
View newest version in sPHENIX GitHub at line 2 of file G4_BeamLine.C
Function Documentation
float AngleFlip (float angle)
Definition at line 337 of file G4_BeamLine.C.
View newest version in sPHENIX GitHub at line 337 of file G4_BeamLine.C
Referenced by BeamLineDefineMagnets().
void BeamLineDefineBeamPipe (PHG4Reco * g4Reco)
Definition at line 235 of file G4_BeamLine.C.
View newest version in sPHENIX GitHub at line 235 of file G4_BeamLine.C
References Enable::ABSORBER, G4BEAMLINE::BackwardBeamLineEnclosure(), Enable::BEAMLINE_ABSORBER, Enable::BEAMLINE_BLACKHOLE, Enable::BEAMLINE_OVERLAPCHECK, Enable::BEAMLINE_VERBOSITY, PHG4DetectorSubsystem::BlackHole(), G4BEAMLINE::enclosure_center, G4BEAMLINE::ForwardBeamLineEnclosure(), i, perf_headwind::name, Acts::UnitConstants::nm, PHG4DetectorSubsystem::OverlapCheck(), Enable::OVERLAPCHECK, G4BEAMLINE::pipe_id_offset, PosFlip(), PHG4Reco::registerSubsystem(), G4BEAMLINE::roman_pot_pipe_id_offset, PHG4ConeSubsystem::set_color(), PHG4CylinderSubsystem::set_color(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4Subsystem::SetMotherSubsystem(), PHG4DetectorSubsystem::SuperDetector(), to_string(), verbosity, and Enable::VERBOSITY.
Referenced by G4Setup().
void BeamLineDefineMagnets (PHG4Reco * g4Reco)
Definition at line 59 of file G4_BeamLine.C.
View newest version in sPHENIX GitHub at line 59 of file G4_BeamLine.C
References Enable::ABSORBER, AngleFlip(), G4BEAMLINE::BackwardBeamLineEnclosure(), Enable::BEAMLINE_ABSORBER, Enable::BEAMLINE_BLACKHOLE, Enable::BEAMLINE_OVERLAPCHECK, Enable::BEAMLINE_VERBOSITY, PHG4DetectorSubsystem::BlackHole(), G4BEAMLINE::enclosure_center, G4BEAMLINE::enclosure_r_max, G4BEAMLINE::enclosure_z_max, G4BEAMLINE::ForwardBeamLineEnclosure(), infile, G4PLUGDOOR::length, line, MagFieldFlip(), PHG4DetectorSubsystem::OverlapCheck(), Enable::OVERLAPCHECK, PosFlip(), PHG4Reco::registerSubsystem(), PHG4CylinderSubsystem::set_color(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4Subsystem::SetMotherSubsystem(), G4BEAMLINE::skin_thickness, G4BEAMLINE::starting_z, PHG4DetectorSubsystem::SuperDetector(), verbosity, Enable::VERBOSITY, Fun4AllBase::Verbosity(), ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by G4Setup().
void BeamLineInit ()
Definition at line 52 of file G4_BeamLine.C.
View newest version in sPHENIX GitHub at line 52 of file G4_BeamLine.C
References G4BEAMLINE::enclosure_r_max, G4BEAMLINE::enclosure_z_max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, Acts::UnitConstants::min, and BlackHoleGeometry::min_z.
Referenced by G4Init().
float MagFieldFlip (float Bfield)
Definition at line 341 of file G4_BeamLine.C.
View newest version in sPHENIX GitHub at line 341 of file G4_BeamLine.C
Referenced by BeamLineDefineMagnets().
float PosFlip (float pos)
Definition at line 333 of file G4_BeamLine.C.
View newest version in sPHENIX GitHub at line 333 of file G4_BeamLine.C
References Acts::Test::pos.
Referenced by BeamLineDefineBeamPipe(), and BeamLineDefineMagnets().