Analysis Software: DecayFinder Class Reference
DecayFinder Class Reference
#include <coresoftware/blob/master/offline/packages/decayfinder/DecayFinder.h>
Public Types
using Decay = std::vector< std::pair< std::pair< int, int >, int >>
Public Member Functions
DecayFinder ()
DecayFinder (const std::string &name)
~DecayFinder () override=default
int Init (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
int parseDecayDescriptor ()
bool findDecay (PHCompositeNode *topNode)
bool findParticle (const std::string &particle)
void searchHepMCRecord (HepMC::GenParticle *particle, std::vector< int > decayProducts, bool &breakLoop, bool &hasPhoton, bool &hasPi0, bool &failedPT, bool &failedETA, std::vector< int > &correctDecayProducts)
void searchGeant4Record (int barcode, int pid, std::vector< int > decayProducts, bool &breakLoop, bool &hasPhoton, bool &hasPi0, bool &failedPT, bool &failedETA, std::vector< int > &correctDecayProducts)
bool checkIfCorrectHepMCParticle (HepMC::GenParticle *particle, bool &trackFailedPT, bool &trackFailedETA)
bool checkIfCorrectGeant4Particle (PHG4Particle *particle, bool &hasPhoton, bool &hasPi0, bool &trackFailedPT, bool &trackFailedETA)
bool compareDecays (std::vector< int > required, std::vector< int > actual)
int deleteElement (int arr[], int n, int x)
void multiplyVectorByScalarAndSort (std::vector< int > &v, int k)
int get_pdgcode (const std::string &name)
int get_charge (const std::string &name)
bool isInRange (float min, float value, float max)
int createDecayNode (PHCompositeNode *topNode)
void fillDecayNode (PHCompositeNode *topNode, Decay &decay)
void printInfo ()
void printNode (PHCompositeNode *topNode)
void setDecayDescriptor (const std::string &decayDescriptor)
You define a particle decaying with "->", the mother on the left, the decay products on the right.
void triggerOnDecay (bool trigger)
void allowPhotons (bool allow)
void allowPi0 (bool allow)
void saveDST (bool save)
void setNodeName (const std::string &name)
void setEtaRange (float min, float max)
void setPTmin (float pt)
void useDecaySpecificEtaRange (bool use)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void recalculateEta (double py, double vertex[3])
void calculateEffectiveTPCradius (double vertex[3], double &effective_top_r, double &effective_bottom_r)
Private Attributes
PHHepMCGenEventMap * m_geneventmap = nullptr
PHHepMCGenEvent * m_genevt = nullptr
PHG4TruthInfoContainer * m_truthinfo = nullptr
bool m_recalcualteEtaRange = true
double m_tpc_r = 78.0
double m_tpc_z = 105.0
double m_effective_top_tpc_r = m_tpc_r
double m_effective_bottom_tpc_r = m_tpc_r
double m_eta_high_req = 1.1
double m_eta_low_req = -1.1
double m_pt_req = 0.2
int m_counter = 0
int m_intermediate_product_counter = 0
int m_nCandFail_pT = 0
int m_nCandFail_eta = 0
int m_nCandFail_pT_and_eta = 0
int m_nCandReconstructable = 0
int m_nCandHas_Photon = 0
int m_nCandHas_Pi0 = 0
int m_nCandHas_Photon_and_Pi0 = 0
int m_nCandHas_noPhoton_and_noPi0 = 0
bool m_getChargeConjugate = false
std::string m_decayDescriptor
bool m_triggerOnDecay = false
bool m_allowPi0 = false
bool m_allowPhotons = false
int m_mother_ID = 0
std::vector< int > m_intermediates_ID
std::vector< int > m_daughters_ID
int m_nTracksFromMother = 0
std::vector< int > m_nTracksFromIntermediates
std::vector< int > m_motherDecayProducts
bool m_save_dst
DecayFinderContainer_v1 * m_decayMap = nullptr
Decay decayChain
std::string m_nodeName
std::string m_container_name
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 25 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 25 of file DecayFinder.h
Member Typedef Documentation
using DecayFinder::Decay = std::vector<std::pair<std::pair<int, int>, int>>
Definition at line 28 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 28 of file DecayFinder.h
Constructor & Destructor Documentation
DecayFinder::DecayFinder ()
Definition at line 63 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 63 of file DecayFinder.cc
DecayFinder::DecayFinder (const std::string & name) explicit
Definition at line 69 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 69 of file DecayFinder.cc
DecayFinder::~DecayFinder () override default
Member Function Documentation
void DecayFinder::allowPhotons (bool allow) inline
Parameters
[in] allow Set to true to allow photons to be associated to your decay
Definition at line 112 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 112 of file DecayFinder.h
References m_allowPhotons.
Referenced by Fun4All_BHG(), and KFParticle_QA().
void DecayFinder::allowPi0 (bool allow) inline
Parameters
[in] allow Set to true to allow pi zero to be associated to your decay
Definition at line 116 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 116 of file DecayFinder.h
References m_allowPi0.
Referenced by Fun4All_BHG(), and KFParticle_QA().
void DecayFinder::calculateEffectiveTPCradius (double vertex[3], double & effective_top_r, double & effective_bottom_r) private
Definition at line 1184 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 1184 of file DecayFinder.cc
References m_tpc_r.
Referenced by recalculateEta().
bool DecayFinder::checkIfCorrectGeant4Particle (PHG4Particle * particle, bool & hasPhoton, bool & hasPi0, bool & trackFailedPT, bool & trackFailedETA)
Definition at line 941 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 941 of file DecayFinder.cc
References compareDecays(), distance(), eta, PHG4Particle::get_barcode(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_x(), PHG4VtxPoint::get_y(), PHG4VtxPoint::get_z(), PHG4TruthInfoContainer::GetVtx(), i, index, isInRange(), it, m_daughters_ID, m_eta_high_req, m_eta_low_req, m_intermediates_ID, m_nTracksFromIntermediates, m_pt_req, m_recalcualteEtaRange, m_truthinfo, merge_hashes::p, physmon_track_finding_ttbar::pt, recalculateEta(), searchGeant4Record(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MAX.
Referenced by searchGeant4Record().
bool DecayFinder::checkIfCorrectHepMCParticle (HepMC::GenParticle * particle, bool & trackFailedPT, bool & trackFailedETA)
Definition at line 753 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 753 of file DecayFinder.cc
References parse_cmake_options::begin, compareDecays(), decayChain, distance(), end, PHHepMCGenEvent::get_embedding_id(), i, index, isInRange(), it, listOfResonantPIDs, m_allowPhotons, m_allowPi0, m_daughters_ID, m_eta_high_req, m_eta_low_req, m_genevt, m_intermediate_product_counter, m_intermediates_ID, m_nTracksFromIntermediates, m_pt_req, m_recalcualteEtaRange, recalculateEta(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MAX.
Referenced by searchHepMCRecord().
bool DecayFinder::compareDecays (std::vector< int > required, std::vector< int > actual)
Definition at line 1038 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 1038 of file DecayFinder.cc
References i, m_getChargeConjugate, multiplyVectorByScalarAndSort(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MAX.
Referenced by checkIfCorrectGeant4Particle(), checkIfCorrectHepMCParticle(), findDecay(), and searchHepMCRecord().
int DecayFinder::createDecayNode (PHCompositeNode * topNode)
Definition at line 1214 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 1214 of file DecayFinder.cc
References PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_container_name, m_decayMap, m_nodeName, Fun4AllBase::Name(), and Acts::Test::pos.
Referenced by Init().
int DecayFinder::deleteElement (int arr[], int n, int x)
Definition at line 1104 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 1104 of file DecayFinder.cc
References i, j, and n.
Referenced by findDecay().
int DecayFinder::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 116 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 116 of file DecayFinder.cc
References printInfo(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
void DecayFinder::fillDecayNode (PHCompositeNode * topNode, Decay & decay)
Definition at line 1268 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 1268 of file DecayFinder.cc
References DecayFinderContainer_v1::insert(), m_decayMap, and m_nodeName.
Referenced by findDecay().
bool DecayFinder::findDecay (PHCompositeNode * topNode)
Definition at line 317 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 317 of file DecayFinder.cc
References compareDecays(), decayChain, deleteElement(), fillDecayNode(), PHG4Particle::get_barcode(), PHHepMCGenEvent::get_embedding_id(), PHG4Particle::get_pid(), PHG4Particle::get_primary_id(), PHHepMCGenEvent::getEvent(), PHG4TruthInfoContainer::GetParticleRange(), i, listOfResonantPIDs, m_counter, m_geneventmap, m_genevt, m_getChargeConjugate, m_intermediates_ID, m_mother_ID, m_motherDecayProducts, m_nCandFail_eta, m_nCandFail_pT, m_nCandFail_pT_and_eta, m_nCandHas_noPhoton_and_noPi0, m_nCandHas_Photon, m_nCandHas_Photon_and_Pi0, m_nCandHas_Pi0, m_nCandReconstructable, m_save_dst, m_truthinfo, n, merge_hashes::p, PHHepMCGenEventMap::rbegin(), PHHepMCGenEventMap::rend(), searchGeant4Record(), searchHepMCRecord(), Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_MAX, and Fun4AllBase::VERBOSITY_SOME.
Referenced by process_event().
bool DecayFinder::findParticle (const std::string & particle)
Definition at line 1132 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 1132 of file DecayFinder.cc
References Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by get_charge(), get_pdgcode(), and parseDecayDescriptor().
int DecayFinder::get_charge (const std::string & name)
Definition at line 1167 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 1167 of file DecayFinder.cc
References findParticle().
Referenced by parseDecayDescriptor().
int DecayFinder::get_pdgcode (const std::string & name)
Definition at line 1155 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 1155 of file DecayFinder.cc
References findParticle().
Referenced by parseDecayDescriptor().
int DecayFinder::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 75 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 75 of file DecayFinder.cc
References createDecayNode(), m_decayDescriptor, m_save_dst, Fun4AllBase::Name(), parseDecayDescriptor(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
bool DecayFinder::isInRange (float min, float value, float max)
Definition at line 1179 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 1179 of file DecayFinder.cc
Referenced by checkIfCorrectGeant4Particle(), and checkIfCorrectHepMCParticle().
void DecayFinder::multiplyVectorByScalarAndSort (std::vector< int > & v, int k)
Definition at line 1147 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 1147 of file DecayFinder.cc
References Acts::PhysicalConstants::c, k, Acts::Experimental::detail::BlueprintHelper::sort(), and Acts::Test::transform.
Referenced by compareDecays().
int DecayFinder::parseDecayDescriptor ()
Definition at line 133 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 133 of file DecayFinder.cc
References parse_cmake_options::begin, Acts::PhysicalConstants::c, Fun4AllReturnCodes::DONOTREGISTERSUBSYSTEM, end, findParticle(), get_charge(), get_pdgcode(), i, j, m_daughters_ID, m_decayDescriptor, m_getChargeConjugate, m_intermediates_ID, m_mother_ID, m_motherDecayProducts, m_nTracksFromIntermediates, m_nTracksFromMother, Fun4AllBase::Name(), Acts::Test::pos, Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_MORE, and Fun4AllBase::VERBOSITY_SOME.
Referenced by Init().
void DecayFinder::printInfo ()
Definition at line 1274 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 1274 of file DecayFinder.cc
References m_counter, m_decayDescriptor, m_nCandFail_eta, m_nCandFail_pT, m_nCandFail_pT_and_eta, m_nCandHas_noPhoton_and_noPi0, m_nCandHas_Photon, m_nCandHas_Photon_and_Pi0, m_nCandHas_Pi0, m_nCandReconstructable, and Fun4AllBase::Name().
Referenced by End().
void DecayFinder::printNode (PHCompositeNode * topNode)
Definition at line 1292 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 1292 of file DecayFinder.cc
References i, and m_nodeName.
Referenced by process_event().
int DecayFinder::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 93 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 93 of file DecayFinder.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, findDecay(), m_decayDescriptor, m_save_dst, m_triggerOnDecay, printNode(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MORE.
void DecayFinder::recalculateEta (double py, double vertex[3]) private
Definition at line 1193 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 1193 of file DecayFinder.cc
References calculateEffectiveTPCradius(), m_effective_bottom_tpc_r, m_effective_top_tpc_r, m_eta_high_req, m_eta_low_req, and m_tpc_z.
Referenced by checkIfCorrectGeant4Particle(), and checkIfCorrectHepMCParticle().
void DecayFinder::saveDST (bool save) inline
Parameters
[in] allow Set to true to save any of your decays that are found back to the node tree in a DecayFinderContainer The default name is "decay" and will automatically have "_DecayMap" added to the end
Definition at line 121 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 121 of file DecayFinder.h
References m_save_dst, and save().
Referenced by Fun4All_BHG(), and KFParticle_QA().
void DecayFinder::searchGeant4Record (int barcode, int pid, std::vector< int > decayProducts, bool & breakLoop, bool & hasPhoton, bool & hasPi0, bool & failedPT, bool & failedETA, std::vector< int > & correctDecayProducts)
Definition at line 669 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 669 of file DecayFinder.cc
References parse_cmake_options::begin, checkIfCorrectGeant4Particle(), decayChain, end, PHG4Particle::get_barcode(), PHHepMCGenEvent::get_embedding_id(), PHG4Particle::get_parent_id(), PHG4Particle::get_pid(), PHG4Particle::get_primary_id(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetParticleRange(), listOfResonantPIDs, m_allowPhotons, m_allowPi0, m_geneventmap, m_genevt, m_truthinfo, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MAX.
Referenced by checkIfCorrectGeant4Particle(), findDecay(), and searchHepMCRecord().
void DecayFinder::searchHepMCRecord (HepMC::GenParticle * particle, std::vector< int > decayProducts, bool & breakLoop, bool & hasPhoton, bool & hasPi0, bool & failedPT, bool & failedETA, std::vector< int > & correctDecayProducts)
Definition at line 534 of file DecayFinder.cc.
View newest version in sPHENIX GitHub at line 534 of file DecayFinder.cc
References parse_cmake_options::begin, checkIfCorrectHepMCParticle(), compareDecays(), decayChain, distance(), end, PHHepMCGenEvent::get_embedding_id(), i, index, it, listOfResonantPIDs, m_allowPhotons, m_allowPi0, m_daughters_ID, m_genevt, m_intermediate_product_counter, m_intermediates_ID, m_nTracksFromIntermediates, searchGeant4Record(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MAX.
Referenced by findDecay().
void DecayFinder::setDecayDescriptor (const std::string & decayDescriptor) inline
You define a particle decaying with "->", the mother on the left, the decay products on the right.
Use this function to define the decay you want to find in the HepMC record
Parameters
[in] decayDescriptor the description of the decay chain, this is a string You define the decay with these rules: Set the charge of final state tracks with "^", the particle name on the left and the charge on the right. Accepted charges are +, - and 0 Use the same rules as above for any intermediatee decays but contain the entire decay within curled brackets, "{}" If you also want to find the charge conjugate decay, contain the entire decay descriptor within "[]cc" for charge-conjugate. The "cc" is NOT case sensitive The particle names you use must be kept in the TDatabasePDG class from root (https://root.cern.ch/doc/master/classTDatabasePDG.html). Print this table to see available particles with TDatabasePDG::Instance()->Print() An example of a decay would be: "[B+ -> {D0_bar -> kaon^+ pion^-} pion^+]cc"
Note
There is an internal list of resonances which, if they appear in the record, will be further analysed. For example, the f0(980)->pipi decay is too quick to have a flight distance and so we would only see the pion pair in the detector. If you are looking for B_s0 -> J/psi pipi then the decay of the f0 will be studied for a pipi final state, basically inclusive decays are handled automatically. If you wish to study the f0 decay, add it to your decay descriptor and it will automatically be removed from the "skip list"
Definition at line 102 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 102 of file DecayFinder.h
References HeavyFlavorReco::decayDescriptor, and m_decayDescriptor.
Referenced by Fun4All_BHG(), and KFParticle_QA().
void DecayFinder::setEtaRange (float min, float max) inline
Parameters
[in] min The minimum eta threshold for track acceptance
[in] min The maximum eta threshold for track acceptance
Note
Set a pseudorapidity threshold range for tracking
Definition at line 133 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 133 of file DecayFinder.h
References m_eta_high_req, m_eta_low_req, and Acts::UnitConstants::min.
Referenced by Fun4All_BHG().
void DecayFinder::setNodeName (const std::string & name) inline
Parameters
[in] name Change the default name of the DecayFinderContainer.
Note
This name will still have "_DecayMap" added to the end, this cannot be changed
Definition at line 126 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 126 of file DecayFinder.h
References m_container_name, and perf_headwind::name.
void DecayFinder::setPTmin (float pt) inline
Parameters
[in] pt The minimum pT threshold for track acceptance
Note
Set a minimum pT threshold for tracking
Definition at line 143 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 143 of file DecayFinder.h
References m_pt_req, and physmon_track_finding_ttbar::pt.
Referenced by Fun4All_BHG().
void DecayFinder::triggerOnDecay (bool trigger) inline
Parameters
[in] trigger Set to true to allow further processing of events in which your decay appears, if your decay does not appear, all further processing of this event is skipped. This defaults to false so every event is proccessed in F4A
Definition at line 108 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 108 of file DecayFinder.h
References m_triggerOnDecay.
Referenced by Fun4All_BHG(), and KFParticle_QA().
void DecayFinder::useDecaySpecificEtaRange (bool use) inline
Set this to true to recalcualte a tracks acceptible pseudorapidity range in sPHENIX on a decay-by-decay basis using the secondary vertex position. Set to false to use the default or user specified range
Parameters
[in] True to recalculate the eta requirements per decay, false to use a fixed value (default = true)
Definition at line 151 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 151 of file DecayFinder.h
References m_recalcualteEtaRange.
Referenced by Fun4All_BHG().
Member Data Documentation
Decay DecayFinder::decayChain private
Definition at line 199 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 199 of file DecayFinder.h
Referenced by checkIfCorrectHepMCParticle(), findDecay(), searchGeant4Record(), and searchHepMCRecord().
bool DecayFinder::m_allowPhotons = false private
Definition at line 186 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 186 of file DecayFinder.h
Referenced by allowPhotons(), checkIfCorrectHepMCParticle(), searchGeant4Record(), and searchHepMCRecord().
bool DecayFinder::m_allowPi0 = false private
Definition at line 185 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 185 of file DecayFinder.h
Referenced by allowPi0(), checkIfCorrectHepMCParticle(), searchGeant4Record(), and searchHepMCRecord().
std::string DecayFinder::m_container_name private
Definition at line 201 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 201 of file DecayFinder.h
Referenced by createDecayNode(), and setNodeName().
int DecayFinder::m_counter = 0 private
Definition at line 170 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 170 of file DecayFinder.h
Referenced by findDecay(), and printInfo().
std::vector<int> DecayFinder::m_daughters_ID private
Definition at line 190 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 190 of file DecayFinder.h
Referenced by checkIfCorrectGeant4Particle(), checkIfCorrectHepMCParticle(), parseDecayDescriptor(), and searchHepMCRecord().
std::string DecayFinder::m_decayDescriptor private
Definition at line 183 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 183 of file DecayFinder.h
Referenced by Init(), parseDecayDescriptor(), printInfo(), process_event(), and setDecayDescriptor().
DecayFinderContainer_v1* DecayFinder::m_decayMap = nullptr private
Definition at line 198 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 198 of file DecayFinder.h
Referenced by createDecayNode(), and fillDecayNode().
double DecayFinder::m_effective_bottom_tpc_r = m_tpc_r private
Definition at line 164 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 164 of file DecayFinder.h
Referenced by recalculateEta().
double DecayFinder::m_effective_top_tpc_r = m_tpc_r private
Definition at line 163 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 163 of file DecayFinder.h
Referenced by recalculateEta().
double DecayFinder::m_eta_high_req = 1.1 private
Definition at line 166 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 166 of file DecayFinder.h
Referenced by checkIfCorrectGeant4Particle(), checkIfCorrectHepMCParticle(), recalculateEta(), and setEtaRange().
double DecayFinder::m_eta_low_req = -1.1 private
Definition at line 167 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 167 of file DecayFinder.h
Referenced by checkIfCorrectGeant4Particle(), checkIfCorrectHepMCParticle(), recalculateEta(), and setEtaRange().
PHHepMCGenEventMap* DecayFinder::m_geneventmap = nullptr private
Definition at line 154 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 154 of file DecayFinder.h
Referenced by findDecay(), and searchGeant4Record().
PHHepMCGenEvent* DecayFinder::m_genevt = nullptr private
Definition at line 155 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 155 of file DecayFinder.h
Referenced by checkIfCorrectHepMCParticle(), findDecay(), searchGeant4Record(), and searchHepMCRecord().
bool DecayFinder::m_getChargeConjugate = false private
Definition at line 181 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 181 of file DecayFinder.h
Referenced by compareDecays(), findDecay(), and parseDecayDescriptor().
int DecayFinder::m_intermediate_product_counter = 0 private
Definition at line 171 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 171 of file DecayFinder.h
Referenced by checkIfCorrectHepMCParticle(), and searchHepMCRecord().
std::vector<int> DecayFinder::m_intermediates_ID private
Definition at line 189 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 189 of file DecayFinder.h
Referenced by checkIfCorrectGeant4Particle(), checkIfCorrectHepMCParticle(), findDecay(), parseDecayDescriptor(), and searchHepMCRecord().
int DecayFinder::m_mother_ID = 0 private
Definition at line 188 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 188 of file DecayFinder.h
Referenced by findDecay(), and parseDecayDescriptor().
std::vector<int> DecayFinder::m_motherDecayProducts private
Definition at line 195 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 195 of file DecayFinder.h
Referenced by findDecay(), and parseDecayDescriptor().
int DecayFinder::m_nCandFail_eta = 0 private
Definition at line 173 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 173 of file DecayFinder.h
Referenced by findDecay(), and printInfo().
int DecayFinder::m_nCandFail_pT = 0 private
Definition at line 172 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 172 of file DecayFinder.h
Referenced by findDecay(), and printInfo().
int DecayFinder::m_nCandFail_pT_and_eta = 0 private
Definition at line 174 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 174 of file DecayFinder.h
Referenced by findDecay(), and printInfo().
int DecayFinder::m_nCandHas_noPhoton_and_noPi0 = 0 private
Definition at line 179 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 179 of file DecayFinder.h
Referenced by findDecay(), and printInfo().
int DecayFinder::m_nCandHas_Photon = 0 private
Definition at line 176 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 176 of file DecayFinder.h
Referenced by findDecay(), and printInfo().
int DecayFinder::m_nCandHas_Photon_and_Pi0 = 0 private
Definition at line 178 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 178 of file DecayFinder.h
Referenced by findDecay(), and printInfo().
int DecayFinder::m_nCandHas_Pi0 = 0 private
Definition at line 177 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 177 of file DecayFinder.h
Referenced by findDecay(), and printInfo().
int DecayFinder::m_nCandReconstructable = 0 private
Definition at line 175 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 175 of file DecayFinder.h
Referenced by findDecay(), and printInfo().
std::string DecayFinder::m_nodeName private
Definition at line 200 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 200 of file DecayFinder.h
Referenced by createDecayNode(), fillDecayNode(), and printNode().
std::vector<int> DecayFinder::m_nTracksFromIntermediates private
Definition at line 193 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 193 of file DecayFinder.h
Referenced by checkIfCorrectGeant4Particle(), checkIfCorrectHepMCParticle(), parseDecayDescriptor(), and searchHepMCRecord().
int DecayFinder::m_nTracksFromMother = 0 private
Definition at line 192 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 192 of file DecayFinder.h
Referenced by parseDecayDescriptor().
double DecayFinder::m_pt_req = 0.2 private
Definition at line 168 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 168 of file DecayFinder.h
Referenced by checkIfCorrectGeant4Particle(), checkIfCorrectHepMCParticle(), and setPTmin().
bool DecayFinder::m_recalcualteEtaRange = true private
Definition at line 160 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 160 of file DecayFinder.h
Referenced by checkIfCorrectGeant4Particle(), checkIfCorrectHepMCParticle(), and useDecaySpecificEtaRange().
bool DecayFinder::m_save_dst private
Definition at line 197 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 197 of file DecayFinder.h
Referenced by findDecay(), Init(), process_event(), and saveDST().
double DecayFinder::m_tpc_r = 78.0 private
Definition at line 161 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 161 of file DecayFinder.h
Referenced by calculateEffectiveTPCradius().
double DecayFinder::m_tpc_z = 105.0 private
Definition at line 162 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 162 of file DecayFinder.h
Referenced by recalculateEta().
bool DecayFinder::m_triggerOnDecay = false private
Definition at line 184 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 184 of file DecayFinder.h
Referenced by process_event(), and triggerOnDecay().
PHG4TruthInfoContainer* DecayFinder::m_truthinfo = nullptr private
Definition at line 156 of file DecayFinder.h.
View newest version in sPHENIX GitHub at line 156 of file DecayFinder.h
Referenced by checkIfCorrectGeant4Particle(), findDecay(), and searchGeant4Record().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/decayfinder/DecayFinder.h
coresoftware/blob/master/offline/packages/decayfinder/DecayFinder.cc