Analysis Software: Load/save auxiliary functions
Load/save auxiliary functions
nanoflann C++ library for ANN
Functions
template<typename T >
void nanoflann::save_value (FILE *stream, const T &value, size_t count=1)
template<typename T >
void nanoflann::save_value (FILE *stream, const std::vector< T > &value)
template<typename T >
void nanoflann::load_value (FILE *stream, T &value, size_t count=1)
template<typename T >
void nanoflann::load_value (FILE *stream, std::vector< T > &value)
Detailed Description
Function Documentation
template<typename T > void nanoflann::load_value (FILE * stream, T & value, size_t count = 1)
Definition at line 233 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 233 of file nanoflann.hpp
References nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::count.
Referenced by nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::load_tree(), and nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::loadIndex().
template<typename T > void nanoflann::load_value (FILE * stream, std::vector< T > & value)
Definition at line 243 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 243 of file nanoflann.hpp
References nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::size(), and Acts::UnitConstants::T.
template<typename T > void nanoflann::save_value (FILE * stream, const T & value, size_t count = 1)
Definition at line 219 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 219 of file nanoflann.hpp
References nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::count.
Referenced by nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::save_tree(), and nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::saveIndex().
template<typename T > void nanoflann::save_value (FILE * stream, const std::vector< T > & value)
Definition at line 225 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 225 of file nanoflann.hpp
References nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::size(), and Acts::UnitConstants::T.