Analysis Software: ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t > Class Template Reference
ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t > Class Template Reference
#include <acts/blob/sPHENIX/Examples/Detectors/GenericDetector/include/ActsExamples/GenericDetector/ProtoLayerCreatorT.hpp>
Classes
struct Config
Public Types
using LayerStore = std::vector< std::shared_ptr< detector_element_t >>
using DetectorStore = std::vector< LayerStore >
Public Member Functions
ProtoLayerCreatorT (const Config &cfg, std::unique_ptr< const Acts::Logger > logger=Acts::getDefaultLogger("ProtoLayerCreatorT", Acts::Logging::INFO))
std::vector< ProtoLayerSurfaces > negativeProtoLayers (const Acts::GeometryContext &gctx, DetectorStore &detectorStore) const
construct the negative side layers
std::vector< ProtoLayerSurfaces > centralProtoLayers (const Acts::GeometryContext &gctx, DetectorStore &detectorStore) const
construct the central layers
std::vector< ProtoLayerSurfaces > positiveProtoLayers (const Acts::GeometryContext &gctx, DetectorStore &detectorStore) const
construct the positive side layers
Private Member Functions
std::vector< ProtoLayerSurfaces > createProtoLayers (const Acts::GeometryContext &gctx, DetectorStore &detectorStore, int side) const
private helper method to create the proto layers on the left respectively right side
const Acts::Logger & logger () const
Private access to the logging instance.
Private Attributes
Config m_cfg
Configuration member.
std::unique_ptr< const
Acts::Logger > m_logger
the logging instance
Detailed Description
template<typename detector_element_t>
class ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >
The ProtoLayerCreatorT is the first setp in creating a geometry from code input, it creates the ProtoLayer and returns the created detector elements for the DetectorStore emulation
Definition at line 61 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 61 of file ProtoLayerCreatorT.hpp
Member Typedef Documentation
template<typename detector_element_t > using ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::DetectorStore = std::vector<LayerStore>
Definition at line 65 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 65 of file ProtoLayerCreatorT.hpp
template<typename detector_element_t > using ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::LayerStore = std::vector<std::shared_ptr<detector_element_t>>
Definition at line 63 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 63 of file ProtoLayerCreatorT.hpp
Constructor & Destructor Documentation
template<typename detector_element_t > ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::ProtoLayerCreatorT (const Config & cfg, std::unique_ptr< const Acts::Logger > logger = Acts::getDefaultLogger("ProtoLayerCreatorT< detector_element_t >", Acts::Logging::INFO))
Constructor
Parameters
cfg is the configuration class
logger is the logging class for screen output
Definition at line 394 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 394 of file ProtoLayerCreatorT.hpp
Member Function Documentation
template<typename detector_element_t > std::vector< ProtoLayerSurfaces > ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::centralProtoLayers (const Acts::GeometryContext & gctx, DetectorStore & detectorStore) const
construct the central layers
Parameters
gctx The geometry context for this construction call
detectorStore The reference store for the detector elements
Returns
the protolayers and surfaces on the central detector side
Definition at line 200 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 200 of file ProtoLayerCreatorT.hpp
References ACTS_DEBUG, ACTS_VERBOSE, ACTS_WARNING, Acts::binR, Acts::binZ, boost::const_pointer_cast(), Acts::ProtoLayer::envelope, m_cfg(), Acts::Test::moduleBounds, testing::internal::move(), ActsTests::PropagationDatasets::phi, and physmon_ckf_tracking::u.
template<typename detector_element_t > std::vector< ProtoLayerSurfaces > ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::createProtoLayers (const Acts::GeometryContext & gctx, DetectorStore & detectorStore, int side) const private
private helper method to create the proto layers on the left respectively right side
Parameters
gctx The geometry context for this construction call
detectorStore The reference store for the detector elements
side is the indiciator whether to build on negative/positive
Returns
the protolayers and surfaces on the neg/pos detector side
this is the loop over the layer positions
some preparation work
Definition at line 401 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 401 of file ProtoLayerCreatorT.hpp
References ACTS_DEBUG, ACTS_VERBOSE, Acts::binR, Acts::binZ, boost::const_pointer_cast(), Acts::ProtoLayer::envelope, m_cfg(), Acts::Test::moduleBounds, testing::internal::move(), ActsTests::PropagationDatasets::phi, and physmon_ckf_tracking::u.
template<typename detector_element_t > const Acts::Logger& ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::logger () const inline private
Private access to the logging instance.
Definition at line 195 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 195 of file ProtoLayerCreatorT.hpp
References ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::m_logger.
template<typename detector_element_t > std::vector< ProtoLayerSurfaces > ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::negativeProtoLayers (const Acts::GeometryContext & gctx, DetectorStore & detectorStore) const
construct the negative side layers
Parameters
gctx The geometry context for this construction call
detectorStore The reference store for the detector elements
Returns
the protolayers and surfaces on the negative detector side
Definition at line 381 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 381 of file ProtoLayerCreatorT.hpp
template<typename detector_element_t > std::vector< ProtoLayerSurfaces > ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::positiveProtoLayers (const Acts::GeometryContext & gctx, DetectorStore & detectorStore) const
construct the positive side layers
Parameters
gctx The geometry context for this construction call
detectorStore The reference store for the detector elements
Returns
the protolayers and surfaces on the positive detector side
Definition at line 388 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 388 of file ProtoLayerCreatorT.hpp
Member Data Documentation
template<typename detector_element_t > Config ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::m_cfg private
Configuration member.
Definition at line 189 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 189 of file ProtoLayerCreatorT.hpp
template<typename detector_element_t > std::unique_ptr<const Acts::Logger> ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::m_logger private
the logging instance
Definition at line 192 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 192 of file ProtoLayerCreatorT.hpp
Referenced by ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::logger().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Examples/Detectors/GenericDetector/include/ActsExamples/GenericDetector/ProtoLayerCreatorT.hpp