Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Vertexing/ImpactPointEstimatorTests.cpp File Reference
ImpactPointEstimatorTests.cpp File Reference
#include <boost/test/data/test_case.hpp>
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Definitions/Common.hpp"
#include "Acts/Definitions/Direction.hpp"
#include "Acts/Definitions/TrackParametrization.hpp"
#include "Acts/Definitions/Units.hpp"
#include "Acts/EventData/Charge.hpp"
#include "Acts/EventData/GenericBoundTrackParameters.hpp"
#include "Acts/EventData/TrackParameters.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Geometry/GeometryIdentifier.hpp"
#include "Acts/MagneticField/ConstantBField.hpp"
#include "Acts/MagneticField/MagneticFieldContext.hpp"
#include "Acts/MagneticField/MagneticFieldProvider.hpp"
#include "Acts/MagneticField/NullBField.hpp"
#include "Acts/Propagator/EigenStepper.hpp"
#include "Acts/Propagator/Propagator.hpp"
#include "Acts/Propagator/StraightLineStepper.hpp"
#include "Acts/Propagator/detail/VoidPropagatorComponents.hpp"
#include "Acts/Surfaces/PerigeeSurface.hpp"
#include "Acts/Surfaces/Surface.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Utilities/Logger.hpp"
#include "Acts/Utilities/Result.hpp"
#include "Acts/Vertexing/ImpactPointEstimator.hpp"
#include "Acts/Vertexing/TrackAtVertex.hpp"
#include "Acts/Vertexing/Vertex.hpp"
#include <algorithm>
#include <array>
#include <cmath>
#include <limits>
#include <memory>
#include <optional>
#include <tuple>
#include <utility>
#include <vector>
Functions
BOOST_DATA_TEST_CASE (SingleTrackDistanceParametersCompatibility3D, tracks, d0, l0, t0, phi, theta, p, q)
BOOST_DATA_TEST_CASE (TimeAtPca, tracksWithoutIPs *vertices, t0, phi, theta, p, q, vx0, vy0, vz0, vt0)
BOOST_DATA_TEST_CASE (VertexCompatibility4D, IPs *vertices, d0, l0, vx0, vy0, vz0, vt0)
BOOST_AUTO_TEST_CASE (SingleTrackDistanceParametersAthenaRegression)
BOOST_AUTO_TEST_CASE (Lifetimes2d3d)
BOOST_DATA_TEST_CASE (SingeTrackImpactParameters, tracks *vertices, d0, l0, t0, phi, theta, p, q, vx0, vy0, vz0, vt0)
Function Documentation
BOOST_AUTO_TEST_CASE (SingleTrackDistanceParametersAthenaRegression)
Definition at line 420 of file ImpactPointEstimatorTests.cpp.
View newest version in sPHENIX GitHub at line 420 of file ImpactPointEstimatorTests.cpp
References Acts::Surface::center(), CHECK_CLOSE_ABS, Acts::GenericBoundTrackParameters< ParticleHypothesis >::create(), distance(), Acts::ePos0, Acts::Test::geoContext, Acts::Test::magFieldContext, Acts::ParticleHypothesis::pion(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::referenceSurface(), filter::state, and value.
BOOST_AUTO_TEST_CASE (Lifetimes2d3d)
Definition at line 456 of file ImpactPointEstimatorTests.cpp.
View newest version in sPHENIX GitHub at line 456 of file ImpactPointEstimatorTests.cpp
References Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, Acts::Test::geoContext, Acts::Test::magFieldContext, and Acts::ParticleHypothesis::pion().
BOOST_DATA_TEST_CASE (SingleTrackDistanceParametersCompatibility3D , tracks , d0 , l0 , t0 , phi , theta , p , q)
Definition at line 139 of file ImpactPointEstimatorTests.cpp.
View newest version in sPHENIX GitHub at line 139 of file ImpactPointEstimatorTests.cpp
References CHECK_CLOSE_ABS, CHECK_CLOSE_REL, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, Acts::Test::geoContext, Acts::Test::magFieldContext, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::parameters(), particleHypothesis, ActsTests::PropagationDatasets::phi, Acts::ParticleHypothesis::pion(), filter::state, ActsTests::PropagationDatasets::theta, and value.
BOOST_DATA_TEST_CASE (TimeAtPca , tracksWithoutIPs * vertices, t0 , phi , theta , p , q , vx0 , vy0 , vz0 , vt0)
Definition at line 197 of file ImpactPointEstimatorTests.cpp.
View newest version in sPHENIX GitHub at line 197 of file ImpactPointEstimatorTests.cpp
References cfg, CHECK_CLOSE_ABS, CHECK_CLOSE_OR_SMALL, closest(), filter::Config, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::direction(), dist(), Acts::UnitConstants::e, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, ckf::field, Acts::Direction::fromScalarZeroAsPositive(), Acts::Test::geoContext, Acts::Test::magFieldContext, testing::internal::move(), norm, merge_hashes::p, ActsTests::PropagationDatasets::phi, Acts::ParticleHypothesis::pion(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::position(), filter::state, propagation_timing::stepper, ActsTests::PropagationDatasets::theta, and value.
BOOST_DATA_TEST_CASE (VertexCompatibility4D , IPs * vertices, d0 , l0 , vx0 , vy0 , vz0 , vt0)
Definition at line 335 of file ImpactPointEstimatorTests.cpp.
View newest version in sPHENIX GitHub at line 335 of file ImpactPointEstimatorTests.cpp
References Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundTime, gen(), Acts::Test::geoContext, Acts::ParticleHypothesis::pion(), seed, and value.
BOOST_DATA_TEST_CASE (SingeTrackImpactParameters , tracks * vertices, d0 , l0 , t0 , phi , theta , p , q , vx0 , vy0 , vz0 , vt0)
Definition at line 503 of file ImpactPointEstimatorTests.cpp.
View newest version in sPHENIX GitHub at line 503 of file ImpactPointEstimatorTests.cpp
References Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, Acts::ePos0, Acts::ePos1, Acts::ePos2, Acts::eTime, Acts::Test::geoContext, Acts::Test::magFieldContext, check_smearing_config::output, merge_hashes::p, ActsTests::PropagationDatasets::phi, Acts::ParticleHypothesis::pionLike(), filter::state, and ActsTests::PropagationDatasets::theta.