Analysis Software: Calib Class Reference
Calib Class Reference
#include <tutorials/blob/master/sPHENIX_sims/Calib/Calib.h>
Public Member Functions
Calib (const std::string &name="Calib")
int Init (PHCompositeNode *)
int InitRun (PHCompositeNode *)
int process_event (PHCompositeNode *)
int EndRun (PHCompositeNode *)
int End (PHCompositeNode *)
Called at the end of all processing.
void set_filename (const char *file)
Calib (const std::string &name="Calib")
int Init (PHCompositeNode *)
int InitRun (PHCompositeNode *)
int process_event (PHCompositeNode *)
int EndRun (PHCompositeNode *)
int End (PHCompositeNode *)
Called at the end of all processing.
void set_filename (const char *file)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void fill_tree (PHCompositeNode *)
int GetNodes (PHCompositeNode *)
void fill_tree (PHCompositeNode *)
int GetNodes (PHCompositeNode *)
Private Attributes
std::string _outfile_name
int _event
float _oCalib_ohcal
TProfile2D * hprof2d
TTree * _event_tree
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 32 of file Calib.h.
View newest version in sPHENIX GitHub at line 32 of file Calib.h
Constructor & Destructor Documentation
Calib::Calib (const std::string & name = "Calib")
Definition at line 49 of file Calib.cc.
View newest version in sPHENIX GitHub at line 49 of file Calib.cc
References _event, and _outfile_name.
Calib::Calib (const std::string & name = "Calib")
Member Function Documentation
int Calib::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 130 of file Calib.cc.
View newest version in sPHENIX GitHub at line 130 of file Calib.cc
References _outfile_name, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), and PHTFileServer::write().
int Calib::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
int Calib::EndRun (PHCompositeNode * topNode)
Definition at line 123 of file Calib.cc.
View newest version in sPHENIX GitHub at line 123 of file Calib.cc
References Fun4AllReturnCodes::EVENT_OK.
int Calib::EndRun (PHCompositeNode *)
void Calib::fill_tree (PHCompositeNode * topNode) private
Definition at line 144 of file Calib.cc.
View newest version in sPHENIX GitHub at line 144 of file Calib.cc
References _event, _event_tree, _oCalib_ohcal, _ohcal_towergeom, _ohcal_towers_o, RawTowerGeom::get_column(), RawTower::get_energy(), RawTowerGeom::get_eta(), RawTowerGeom::get_phi(), RawTowerGeom::get_row(), RawTowerGeomContainer::get_tower_geometry(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), hprof2d, i, and j.
Referenced by process_event().
void Calib::fill_tree (PHCompositeNode *) private
int Calib::GetNodes (PHCompositeNode * topNode) private
Definition at line 206 of file Calib.cc.
View newest version in sPHENIX GitHub at line 206 of file Calib.cc
References _ohcal_towergeom, _ohcal_towers_o, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by process_event().
int Calib::GetNodes (PHCompositeNode *) private
int Calib::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
int Calib::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 62 of file Calib.cc.
View newest version in sPHENIX GitHub at line 62 of file Calib.cc
References _event, _event_tree, _oCalib_ohcal, _outfile_name, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), hprof2d, PHTFileServer::open(), and PHWHERE.
int Calib::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int Calib::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 96 of file Calib.cc.
View newest version in sPHENIX GitHub at line 96 of file Calib.cc
References Fun4AllReturnCodes::EVENT_OK.
int Calib::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int Calib::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 107 of file Calib.cc.
View newest version in sPHENIX GitHub at line 107 of file Calib.cc
References _event, Fun4AllReturnCodes::EVENT_OK, fill_tree(), and GetNodes().
void Calib::set_filename (const char * file) inline
Definition at line 51 of file Calib.h.
View newest version in sPHENIX GitHub at line 51 of file Calib.h
References _outfile_name, and file.
Referenced by Fun4All_G4_sPHENIX().
void Calib::set_filename (const char * file) inline
Definition at line 51 of file Calib.h.
View newest version in sPHENIX GitHub at line 51 of file Calib.h
References _outfile_name, and file.
Member Data Documentation
int Calib::_event private
Definition at line 59 of file Calib.h.
View newest version in sPHENIX GitHub at line 59 of file Calib.h
Referenced by Calib(), fill_tree(), Init(), and process_event().
TTree * Calib::_event_tree private
Definition at line 72 of file Calib.h.
View newest version in sPHENIX GitHub at line 72 of file Calib.h
Referenced by fill_tree(), and Init().
float Calib::_oCalib_ohcal private
Definition at line 61 of file Calib.h.
View newest version in sPHENIX GitHub at line 61 of file Calib.h
Referenced by fill_tree(), and Init().
std::string Calib::_outfile_name private
Definition at line 56 of file Calib.h.
View newest version in sPHENIX GitHub at line 56 of file Calib.h
Referenced by Calib(), End(), Init(), and set_filename().
TProfile2D * Calib::hprof2d private
Definition at line 69 of file Calib.h.
View newest version in sPHENIX GitHub at line 69 of file Calib.h
Referenced by fill_tree(), and Init().
The documentation for this class was generated from the following files:
tutorials/blob/master/sPHENIX_sims/Calib/Calib.h
tutorials/blob/master/sPHENIX_sims/Calib.h
tutorials/blob/master/sPHENIX_sims/Calib/Calib.cc