Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Plugins/Json/PortalJsonConverterTests.cpp File Reference
PortalJsonConverterTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Definitions/Direction.hpp"
#include "Acts/Detector/Portal.hpp"
#include "Acts/Detector/detail/PortalHelper.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Plugins/Json/PortalJsonConverter.hpp"
#include "Acts/Surfaces/PlaneSurface.hpp"
#include "Acts/Surfaces/Surface.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include <fstream>
#include <nlohmann/json.hpp>
Classes
class Acts::Experimental::DetectorVolume
Define a dummy detector volume.
Namespaces
namespace Acts
Acts includes to create all necessary definitions.
namespace Acts::Experimental
Functions
BOOST_AUTO_TEST_CASE (PortalUnconnected)
BOOST_AUTO_TEST_CASE (PortalSingleConnected)
BOOST_AUTO_TEST_CASE (PortalMultiConnected)
Variables
Acts::GeometryContext tContext
Function Documentation
BOOST_AUTO_TEST_CASE (PortalUnconnected)
Definition at line 35 of file PortalJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file PortalJsonConverterTests.cpp
References Acts::PortalJsonConverter::fromJson(), in, Acts::Experimental::Portal::makeShared(), testing::internal::move(), out, writeMapConfig::surface, and Acts::PortalJsonConverter::toJson().
BOOST_AUTO_TEST_CASE (PortalSingleConnected)
Definition at line 64 of file PortalJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file PortalJsonConverterTests.cpp
References Acts::Experimental::detail::PortalHelper::attachDetectorVolumeUpdator(), Acts::Direction::Backward, acts.examples.mockupbuilder::detectorVolumes, Acts::Direction::Forward, Acts::PortalJsonConverter::fromJson(), in, Acts::Experimental::Portal::makeShared(), testing::internal::move(), out, writeMapConfig::surface, and Acts::PortalJsonConverter::toJson().
BOOST_AUTO_TEST_CASE (PortalMultiConnected)
Definition at line 106 of file PortalJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 106 of file PortalJsonConverterTests.cpp
References Acts::Experimental::detail::PortalHelper::attachDetectorVolumesUpdator(), Acts::Experimental::detail::PortalHelper::attachDetectorVolumeUpdator(), Acts::Direction::Backward, Acts::binX, acts.examples.mockupbuilder::detectorVolumes, Acts::Direction::Forward, Acts::Experimental::Portal::makeShared(), testing::internal::move(), out, writeMapConfig::surface, and Acts::PortalJsonConverter::toJson().
Variable Documentation
Acts::GeometryContext tContext
Definition at line 31 of file PortalJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file PortalJsonConverterTests.cpp