Analysis Software: analysis/blob/master/FrawleyTrackEvalMacros/centrality_newplotbg_newsupp.C File Reference
centrality_newplotbg_newsupp.C File Reference
Functions
double factorial (int n)
double integral (int nfg, int nbg, float lowerLimit, float upperLimit)
void error_fg_bg_pair (int nfg, int nbg, double &err_up, double &err_down)
double CBFunction (double *x, double *p)
double TripleCBFunction (double *x, double *p)
double SandB_CBFunction (double *x, double *p)
void centrality_newplotbg_newsupp ()
Function Documentation
double CBFunction (double * x, double * p)
Definition at line 118 of file centrality_newplotbg_newsupp.C.
View newest version in sPHENIX GitHub at line 118 of file centrality_newplotbg_newsupp.C
References A, alpha, k, CKF_timing_vs_mu::mu, n, norm, and sigma.
void centrality_newplotbg_newsupp ()
Definition at line 217 of file centrality_newplotbg_newsupp.C.
View newest version in sPHENIX GitHub at line 217 of file centrality_newplotbg_newsupp.C
References c2, CBFunction(), cfitall, double(), dummy, f, fmycorrbg, fSandB, i, j, k, testSigmaEff::l1, leg, testing::internal::Log(), nbins, utils::run, SandB_CBFunction(), start, AlignmentDefs::tl, Acts::Test::tmp(), and TripleCBFunction().
void error_fg_bg_pair (int nfg, int nbg, double & err_up, double & err_down)
Definition at line 36 of file centrality_newplotbg_newsupp.C.
View newest version in sPHENIX GitHub at line 36 of file centrality_newplotbg_newsupp.C
References i, and integral().
double factorial (int n)
Definition at line 1 of file centrality_newplotbg_newsupp.C.
View newest version in sPHENIX GitHub at line 1 of file centrality_newplotbg_newsupp.C
References i.
Referenced by integral().
double integral (int nfg, int nbg, float lowerLimit, float upperLimit)
Definition at line 10 of file centrality_newplotbg_newsupp.C.
View newest version in sPHENIX GitHub at line 10 of file centrality_newplotbg_newsupp.C
References factorial(), k, propagation_timing::steps, Acts::Test::tmp(), and ambiguity_solver_full_chain::x.
Referenced by AnnularFieldSim::analyticFieldIntegral(), hcal::collect(), CrossSection2RAA_Proposal(), CrystallBall2(), error_fg_bg_pair(), LaplaceSolution::FindBetamn(), Rossegger::FindBetamn(), Rossegger::FindMunk(), GetZgPrediction(), MakeCDF(), plot_kshort(), and SurveyFiles().
double SandB_CBFunction (double * x, double * p)
Definition at line 175 of file centrality_newplotbg_newsupp.C.
View newest version in sPHENIX GitHub at line 175 of file centrality_newplotbg_newsupp.C
References A, alpha, n, and sigma.
Referenced by centrality_newplotbg_newsupp(), fit_vs_directcount(), newplotbg_dAu_vscent_2022(), newplotbg_newsupp(), newplotbg_newsupp_2021(), newplotbg_newsupp_2022(), newplotbg_newsupp_2022_60pct(), and newplotbg_vscent_2022().
double TripleCBFunction (double * x, double * p)
Definition at line 141 of file centrality_newplotbg_newsupp.C.
View newest version in sPHENIX GitHub at line 141 of file centrality_newplotbg_newsupp.C
References A, alpha, n, and sigma.
Referenced by centrality_newplotbg_newsupp(), fit_vs_directcount(), newplotbg_dAu_vscent_2022(), newplotbg_newsupp(), newplotbg_newsupp_2021(), newplotbg_newsupp_2022(), newplotbg_newsupp_2022_60pct(), and newplotbg_vscent_2022().