Analysis Software: G4VtxNtuple Class Reference
G4VtxNtuple Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4histos/G4VtxNtuple.h>
Public Member Functions
G4VtxNtuple (const std::string &name="G4VtxNtuple", const std::string &filename="G4VtxNtuple.root")
constructor
~G4VtxNtuple () override
destructor
int Init (PHCompositeNode *) override
full initialization
int process_event (PHCompositeNode *) override
event processing method
int End (PHCompositeNode *) override
end of run method
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
std::string m_FileName
Fun4AllHistoManager * hm = nullptr
TNtuple * ntup = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 13 of file G4VtxNtuple.h.
View newest version in sPHENIX GitHub at line 13 of file G4VtxNtuple.h
Constructor & Destructor Documentation
G4VtxNtuple::G4VtxNtuple (const std::string & name = "G4VtxNtuple", const std::string & filename = "G4VtxNtuple.root")
constructor
Definition at line 17 of file G4VtxNtuple.cc.
View newest version in sPHENIX GitHub at line 17 of file G4VtxNtuple.cc
G4VtxNtuple::~G4VtxNtuple () override
destructor
Definition at line 23 of file G4VtxNtuple.cc.
View newest version in sPHENIX GitHub at line 23 of file G4VtxNtuple.cc
References hm.
Member Function Documentation
int G4VtxNtuple::End (PHCompositeNode *) override virtual
end of run method
Reimplemented from SubsysReco.
Definition at line 47 of file G4VtxNtuple.cc.
View newest version in sPHENIX GitHub at line 47 of file G4VtxNtuple.cc
References Fun4AllHistoManager::dumpHistos(), hm, and m_FileName.
int G4VtxNtuple::Init (PHCompositeNode *) override virtual
full initialization
Reimplemented from SubsysReco.
Definition at line 28 of file G4VtxNtuple.cc.
View newest version in sPHENIX GitHub at line 28 of file G4VtxNtuple.cc
References hm, Fun4AllBase::Name(), ntup, and Fun4AllHistoManager::registerHisto().
int G4VtxNtuple::process_event (PHCompositeNode * topNode) override virtual
event processing method
Reimplemented from SubsysReco.
Definition at line 36 of file G4VtxNtuple.cc.
View newest version in sPHENIX GitHub at line 36 of file G4VtxNtuple.cc
References PHG4VtxPoint::get_x(), PHG4VtxPoint::get_y(), PHG4VtxPoint::get_z(), PHG4TruthInfoContainer::GetPrimaryVertexIndex(), PHG4TruthInfoContainer::GetPrimaryVtx(), and ntup.
Member Data Documentation
Fun4AllHistoManager* G4VtxNtuple::hm = nullptr protected
Definition at line 33 of file G4VtxNtuple.h.
View newest version in sPHENIX GitHub at line 33 of file G4VtxNtuple.h
Referenced by End(), Init(), and ~G4VtxNtuple().
std::string G4VtxNtuple::m_FileName protected
Definition at line 32 of file G4VtxNtuple.h.
View newest version in sPHENIX GitHub at line 32 of file G4VtxNtuple.h
Referenced by End().
TNtuple* G4VtxNtuple::ntup = nullptr protected
Definition at line 34 of file G4VtxNtuple.h.
View newest version in sPHENIX GitHub at line 34 of file G4VtxNtuple.h
Referenced by Init(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4histos/G4VtxNtuple.h
coresoftware/blob/master/simulation/g4simulation/g4histos/G4VtxNtuple.cc