Analysis Software: Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t > Class Template Reference
Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t > Class Template Reference
Kalman fitter implementation of Acts as a plugin.
#include <acts/blob/sPHENIX/Core/include/Acts/TrackFitting/KalmanFitter.hpp>
Classes
class Aborter
class Actor
Propagator Actor plugin for the KalmanFilter.
Public Types
using MeasurementSurfaces = std::multimap< const Layer *, const Surface * >
Shorthand definition.
using KalmanNavigator = typename propagator_t::Navigator
The navigator type.
Public Member Functions
KalmanFitter ()=delete
Default constructor is deleted.
KalmanFitter (propagator_t pPropagator)
Constructor from arguments.
template<typename source_link_t , typename start_parameters_t , typename parameters_t = BoundTrackParameters>
auto fit (const std::vector< source_link_t > &sourcelinks, const start_parameters_t &sParameters, const KalmanFitterOptions< outlier_finder_t > &kfOptions) const -> std::enable_if_t<!isDirectNavigator, Result< KalmanFitterResult< source_link_t >>>
template<typename source_link_t , typename start_parameters_t , typename parameters_t = BoundTrackParameters>
auto fit (const std::vector< source_link_t > &sourcelinks, const start_parameters_t &sParameters, const KalmanFitterOptions< outlier_finder_t > &kfOptions, const std::vector< const Surface * > &sSequence) const -> std::enable_if_t< isDirectNavigator, Result< KalmanFitterResult< source_link_t >>>
Static Public Attributes
static constexpr bool isDirectNavigator
The navigator has DirectNavigator type or not.
Private Attributes
propagator_t m_propagator
The propgator for the transport and material update.
Detailed Description
template<typename propagator_t, typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator>
class Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t >
Kalman fitter implementation of Acts as a plugin.
to the Propgator
Template Parameters
propagator_t Type of the propagation class
updater_t Type of the kalman updater class
smoother_t Type of the kalman smoother class
outlier_finder_t Type of the outlier finder class
calibrator_t Type of the calibrator class
The Kalman filter contains an Actor and a Sequencer sub-class. The Sequencer has to be part of the Navigator of the Propagator in order to initialize and provide the measurement surfaces.
The Actor is part of the Propagation call and does the Kalman update and eventually the smoothing. Updater, Smoother and Calibrator are given to the Actor for further use:
The Updater is the implemented kalman updater formalism, it runs via a visitor pattern through the measurements.
The Smoother is called at the end of the forward fit by the Actor.
The outlier finder is called during the filtering by the Actor. It determines if the measurement is an outlier
The Calibrator is a dedicated calibration algorithm that allows to calibrate measurements using track information, this could be e.g. sagging for wires, module deformations, etc.
Measurements are not required to be ordered for the KalmanFilter, measurement ordering needs to be figured out by the navigation of the propagator.
The void components are provided mainly for unit testing.
Definition at line 195 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 195 of file KalmanFitter.hpp
Member Typedef Documentation
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator> using Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t >::KalmanNavigator = typename propagator_t::Navigator
The navigator type.
Definition at line 200 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 200 of file KalmanFitter.hpp
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator> using Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t >::MeasurementSurfaces = std::multimap<const Layer*, const Surface*>
Shorthand definition.
Definition at line 198 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 198 of file KalmanFitter.hpp
Constructor & Destructor Documentation
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator> Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t >::KalmanFitter () delete
Default constructor is deleted.
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator> Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t >::KalmanFitter (propagator_t pPropagator) inline
Constructor from arguments.
Definition at line 210 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 210 of file KalmanFitter.hpp
Member Function Documentation
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator> template<typename source_link_t , typename start_parameters_t , typename parameters_t = BoundTrackParameters> auto Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t >::fit (const std::vector< source_link_t > & sourcelinks, const start_parameters_t & sParameters, const KalmanFitterOptions< outlier_finder_t > & kfOptions) const -> std::enable_if_t<!isDirectNavigator, Result<KalmanFitterResult<source_link_t>>> inline
Fit implementation of the foward filter, calls the the forward filter and backward smoother
Template Parameters
source_link_t Source link type identifying uncalibrated input measurements.
start_parameters_t Type of the initial parameters
parameters_t Type of parameters used for local parameters
Parameters
sourcelinks The fittable uncalibrated measurements
sParameters The initial track parameters
kfOptions KalmanOptions steering the fit
Note
The input measurements are given in the form of SourceLinks. It's calibrator_t's job to turn them into calibrated measurements used in the fit.
Returns
the output as an output track
Get the result of the fit
It could happen that the fit ends in zero processed states. The result gets meaningless so such case is regarded as fit failure.
Definition at line 943 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 943 of file KalmanFitter.hpp
References Acts::PropagatorOptions< action_list_t, aborter_list_t >::actionList, ACTS_VERBOSE, Acts::GeometryObject::geometryId(), testing::internal::move(), and Acts::PropagatorOptions< action_list_t, aborter_list_t >::setPlainOptions().
Referenced by Acts::EventDataView3DTest::testMultiTrajectory().
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator> template<typename source_link_t , typename start_parameters_t , typename parameters_t = BoundTrackParameters> auto Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t >::fit (const std::vector< source_link_t > & sourcelinks, const start_parameters_t & sParameters, const KalmanFitterOptions< outlier_finder_t > & kfOptions, const std::vector< const Surface * > & sSequence) const -> std::enable_if_t<isDirectNavigator, Result<KalmanFitterResult<source_link_t>>> inline
Fit implementation of the foward filter, calls the the forward filter and backward smoother
Template Parameters
source_link_t Source link type identifying uncalibrated input measurements.
start_parameters_t Type of the initial parameters
parameters_t Type of parameters used for local parameters
Parameters
sourcelinks The fittable uncalibrated measurements
sParameters The initial track parameters
kfOptions KalmanOptions steering the fit
sSequence surface sequence used to initialize a DirectNavigator
Note
The input measurements are given in the form of SourceLinks. It's calibrator_t's job to turn them into calibrated measurements used in the fit.
Returns
the output as an output track
Get the result of the fit
It could happen that the fit ends in zero processed states. The result gets meaningless so such case is regarded as fit failure.
Definition at line 1037 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 1037 of file KalmanFitter.hpp
References Acts::PropagatorOptions< action_list_t, aborter_list_t >::actionList, ACTS_ERROR, ACTS_VERBOSE, testing::internal::move(), and Acts::PropagatorOptions< action_list_t, aborter_list_t >::setPlainOptions().
Member Data Documentation
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator> constexpr bool Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t >::isDirectNavigator static
Initial value:
=
      std::is_same<KalmanNavigator, DirectNavigator>::value
The navigator has DirectNavigator type or not.
Definition at line 203 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 203 of file KalmanFitter.hpp
Referenced by Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t >::Actor< source_link_t, parameters_t >::operator()().
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator> propagator_t Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t >::m_propagator private
The propgator for the transport and material update.
Definition at line 215 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 215 of file KalmanFitter.hpp
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/TrackFitting/KalmanFitter.hpp