Analysis Software: Fun4AllPrdfInputPoolManager Class Reference
Fun4AllPrdfInputPoolManager Class Reference
#include <coresoftware/blob/master/offline/framework/fun4allraw/Fun4AllPrdfInputPoolManager.h>
Classes
struct PacketInfo
struct SinglePrdfInputInfo
Public Member Functions
Fun4AllPrdfInputPoolManager (const std::string &name="DUMMY", const std::string &prdfnodename="PRDF", const std::string &topnodename="TOP")
~Fun4AllPrdfInputPoolManager () override
int fileopen (const std::string &) override
int fileclose () override
int run (const int nevents=0) override
void Print (const std::string &what="ALL") const override
int ResetEvent () override
int PushBackEvents (const int i) override
int GetSyncObject (SyncObject **mastersync) override
int SyncIt (const SyncObject *mastersync) override
int HasSyncObject () const override
std::string GetString (const std::string &what) const override
SinglePrdfInput * AddPrdfInputList (const std::string &listfile)
SinglePrdfInput * AddPrdfInputFile (const std::string &filename)
SinglePrdfInput * registerPrdfInput (SinglePrdfInput *prdfin)
void AddPacket (const int evtno, Packet *p)
void UpdateEventFoundCounter (const int evtno)
void UpdateDroppedPacket (const int packetid)
void AddBeamClock (const int evtno, const int bclk, SinglePrdfInput *prdfin)
void SetReferenceClock (const int evtno, const int bclk)
void SetReferenceInputMgr (SinglePrdfInput *inp)
void CreateBclkOffsets ()
int CalcDiffBclk (const int bclk1, const int bclk2)
void DitchEvent (const int eventno)
void Resynchronize ()
void ClearAllEvents ()
void SetPoolDepth (unsigned int d)
Public Member Functions inherited from Fun4AllInputManager
~Fun4AllInputManager () override
virtual int ReadInRunNode (PHCompositeNode *)
std::string FileName () const
void FileName (const std::string &fn)
virtual int BranchSelect (const std::string &, const int)
virtual int setBranches ()
virtual int skip (const int nevt)
virtual int NoSyncPushBackEvents (const int)
int AddFile (const std::string &filename)
int AddListFile (const std::string &filename, const int do_it=0)
int registerSubsystem (SubsysReco *subsystem)
virtual int RejectEvent ()
void Repeat (const int i=-1)
virtual void setSyncManager (Fun4AllSyncManager *master)
virtual int ResetFileList ()
virtual void SetRunNumber (const int runno)
virtual int RunNumber () const
void AddToFileOpened (const std::string &filename)
std::pair< std::list
< std::string >
::const_iterator, std::list
< std::string >
::const_iterator > FileOpenListBeginEnd ()
std::string InputNode ()
void InputNode (const std::string &innode)
std::string TopNodeName () const
bool FileListEmpty () const
virtual int IsOpen () const
virtual int SkipForThisManager (const int)
const std::list< std::string > GetFileList () const
const std::list< std::string > GetFileOpenedList () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
bool m_StartUpFlag = true
int m_RunNumber = 0
unsigned int m_PoolDepth = 100
unsigned int m_InitialPoolDepth = 20
std::vector< SinglePrdfInput * > m_PrdfInputVector
SyncObject * m_SyncObject = nullptr
PHCompositeNode * m_topNode = nullptr
Event * m_Event = nullptr
PHDWORD workmem [4 *1024 *1024] = {}
oEvent * oph = nullptr
SinglePrdfInput * m_RefPrdfInput = nullptr
std::map< int, PacketInfo > m_PacketMap
std::string m_PrdfNodeName
std::map< int, int > m_DroppedPacketMap
std::map< int, std::vector
< std::pair< int,
SinglePrdfInput * > > > m_ClockCounters
std::map< int, int > m_RefClockCounters
std::map< SinglePrdfInput
*, SinglePrdfInputInfo > m_SinglePrdfInputInfo
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from Fun4AllInputManager
Fun4AllInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
void UpdateFileList ()
int OpenNextFile ()
void IsOpen (const int i)
Fun4AllSyncManager * MySyncManager ()
Detailed Description
Definition at line 22 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 22 of file Fun4AllPrdfInputPoolManager.h
Constructor & Destructor Documentation
Fun4AllPrdfInputPoolManager::Fun4AllPrdfInputPoolManager (const std::string & name = "DUMMY", const std::string & prdfnodename = "PRDF", const std::string & topnodename = "TOP")
Definition at line 30 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 30 of file Fun4AllPrdfInputPoolManager.cc
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), Fun4AllServer::instance(), m_Event, m_PrdfNodeName, m_topNode, oph, Fun4AllServer::topNode(), Fun4AllInputManager::TopNodeName(), and workmem.
Fun4AllPrdfInputPoolManager::~Fun4AllPrdfInputPoolManager () override
Definition at line 48 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 48 of file Fun4AllPrdfInputPoolManager.cc
References fileclose(), Fun4AllInputManager::IsOpen(), m_PacketMap, m_PrdfInputVector, m_SyncObject, and oph.
Member Function Documentation
void Fun4AllPrdfInputPoolManager::AddBeamClock (const int evtno, const int bclk, SinglePrdfInput * prdfin)
Definition at line 403 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 403 of file Fun4AllPrdfInputPoolManager.cc
References m_ClockCounters, Fun4AllBase::Name(), and Fun4AllBase::Verbosity().
Referenced by SingleZdcInput::FillPool(), and SinglePrdfInput::FillPool().
void Fun4AllPrdfInputPoolManager::AddPacket (const int evtno, Packet * p)
Definition at line 394 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 394 of file Fun4AllPrdfInputPoolManager.cc
References Packet::getIdentifier(), m_PacketMap, and Fun4AllBase::Verbosity().
Referenced by SingleZdcInput::FillPool(), and SinglePrdfInput::FillPool().
SinglePrdfInput * Fun4AllPrdfInputPoolManager::AddPrdfInputFile (const std::string & filename)
Definition at line 372 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 372 of file Fun4AllPrdfInputPoolManager.cc
References InputFileHandler::AddFile(), m_PrdfInputVector, and to_string().
SinglePrdfInput * Fun4AllPrdfInputPoolManager::AddPrdfInputList (const std::string & listfile)
Definition at line 380 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 380 of file Fun4AllPrdfInputPoolManager.cc
References InputFileHandler::AddListFile(), m_PrdfInputVector, and to_string().
Referenced by Fun4All_Combiner().
int Fun4AllPrdfInputPoolManager::CalcDiffBclk (const int bclk1, const int bclk2)
Definition at line 487 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 487 of file Fun4AllPrdfInputPoolManager.cc
Referenced by CreateBclkOffsets(), Resynchronize(), and run().
void Fun4AllPrdfInputPoolManager::ClearAllEvents ()
Definition at line 630 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 630 of file Fun4AllPrdfInputPoolManager.cc
References m_ClockCounters, m_PacketMap, and m_RefClockCounters.
Referenced by Resynchronize().
void Fun4AllPrdfInputPoolManager::CreateBclkOffsets ()
Definition at line 428 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 428 of file Fun4AllPrdfInputPoolManager.cc
References CalcDiffBclk(), m_ClockCounters, m_RefClockCounters, m_RefPrdfInput, m_SinglePrdfInputInfo, PHWHERE, and Fun4AllBase::Verbosity().
Referenced by run().
void Fun4AllPrdfInputPoolManager::DitchEvent (const int eventno)
Definition at line 493 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 493 of file Fun4AllPrdfInputPoolManager.cc
References m_ClockCounters, m_PacketMap, m_RefClockCounters, and Fun4AllBase::Verbosity().
Referenced by Resynchronize(), and run().
int Fun4AllPrdfInputPoolManager::fileclose () override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 230 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 230 of file Fun4AllPrdfInputPoolManager.cc
References m_PrdfInputVector.
Referenced by ~Fun4AllPrdfInputPoolManager().
int Fun4AllPrdfInputPoolManager::fileopen (const std::string &) inline override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 27 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 27 of file Fun4AllPrdfInputPoolManager.h
std::string Fun4AllPrdfInputPoolManager::GetString (const std::string & what) const override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 363 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 363 of file Fun4AllPrdfInputPoolManager.cc
References m_PrdfNodeName.
int Fun4AllPrdfInputPoolManager::GetSyncObject (SyncObject ** mastersync) override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 321 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 321 of file Fun4AllPrdfInputPoolManager.cc
References assert, SyncObject::CloneMe(), m_SyncObject, and Fun4AllReturnCodes::SYNC_OK.
int Fun4AllPrdfInputPoolManager::HasSyncObject () const inline override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 37 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 37 of file Fun4AllPrdfInputPoolManager.h
void Fun4AllPrdfInputPoolManager::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllInputManager.
Definition at line 240 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 240 of file Fun4AllPrdfInputPoolManager.cc
References m_DroppedPacketMap.
Referenced by Fun4All_Combiner().
int Fun4AllPrdfInputPoolManager::PushBackEvents (const int i) override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 266 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 266 of file Fun4AllPrdfInputPoolManager.cc
SinglePrdfInput * Fun4AllPrdfInputPoolManager::registerPrdfInput (SinglePrdfInput * prdfin)
Definition at line 388 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 388 of file Fun4AllPrdfInputPoolManager.cc
References m_PrdfInputVector.
int Fun4AllPrdfInputPoolManager::ResetEvent () override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 255 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 255 of file Fun4AllPrdfInputPoolManager.cc
References PHNodeIterator::findFirst(), m_Event, m_PrdfNodeName, m_topNode, and PHDataNode< T >::setData().
void Fun4AllPrdfInputPoolManager::Resynchronize ()
Definition at line 514 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 514 of file Fun4AllPrdfInputPoolManager.cc
References CalcDiffBclk(), ClearAllEvents(), DitchEvent(), m_ClockCounters, m_PrdfInputVector, m_RefClockCounters, m_RunNumber, m_SinglePrdfInputInfo, and Fun4AllBase::Verbosity().
Referenced by run().
int Fun4AllPrdfInputPoolManager::run (const int nevents = 0) override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 69 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 69 of file Fun4AllPrdfInputPoolManager.cc
References oEvent::addPacket(), CalcDiffBclk(), CreateBclkOffsets(), DitchEvent(), PHNodeIterator::findFirst(), Event::identify(), m_ClockCounters, m_Event, m_InitialPoolDepth, m_PacketMap, m_PoolDepth, m_PrdfInputVector, m_PrdfNodeName, m_RefClockCounters, m_RunNumber, m_SinglePrdfInputInfo, m_StartUpFlag, m_topNode, oph, oEvent::prepare_next(), Resynchronize(), PHDataNode< T >::setData(), Fun4AllInputManager::SetRunNumber(), Fun4AllBase::Verbosity(), and workmem.
void Fun4AllPrdfInputPoolManager::SetPoolDepth (unsigned int d) inline
Definition at line 53 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 53 of file Fun4AllPrdfInputPoolManager.h
References m_PoolDepth.
void Fun4AllPrdfInputPoolManager::SetReferenceClock (const int evtno, const int bclk)
Definition at line 423 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 423 of file Fun4AllPrdfInputPoolManager.cc
References m_RefClockCounters.
Referenced by SingleZdcInput::FillPool(), and SinglePrdfInput::FillPool().
void Fun4AllPrdfInputPoolManager::SetReferenceInputMgr (SinglePrdfInput * inp) inline
Definition at line 47 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 47 of file Fun4AllPrdfInputPoolManager.h
References m_RefPrdfInput.
Referenced by SinglePrdfInput::MakeReference().
int Fun4AllPrdfInputPoolManager::SyncIt (const SyncObject * mastersync) override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 342 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 342 of file Fun4AllPrdfInputPoolManager.cc
References SyncObject::Different(), m_SyncObject, Fun4AllBase::Name(), PHWHERE, Fun4AllReturnCodes::SYNC_FAIL, and Fun4AllReturnCodes::SYNC_OK.
void Fun4AllPrdfInputPoolManager::UpdateDroppedPacket (const int packetid)
Definition at line 418 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 418 of file Fun4AllPrdfInputPoolManager.cc
References m_DroppedPacketMap, and packetid.
Referenced by SingleZdcInput::FillPool(), and SinglePrdfInput::FillPool().
void Fun4AllPrdfInputPoolManager::UpdateEventFoundCounter (const int evtno)
Definition at line 413 of file Fun4AllPrdfInputPoolManager.cc.
View newest version in sPHENIX GitHub at line 413 of file Fun4AllPrdfInputPoolManager.cc
References m_PacketMap.
Member Data Documentation
std::map<int, std::vector<std::pair<int, SinglePrdfInput *> > > Fun4AllPrdfInputPoolManager::m_ClockCounters private
Definition at line 81 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 81 of file Fun4AllPrdfInputPoolManager.h
Referenced by AddBeamClock(), ClearAllEvents(), CreateBclkOffsets(), DitchEvent(), Resynchronize(), and run().
std::map<int, int> Fun4AllPrdfInputPoolManager::m_DroppedPacketMap private
Definition at line 80 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 80 of file Fun4AllPrdfInputPoolManager.h
Referenced by Print(), and UpdateDroppedPacket().
Event* Fun4AllPrdfInputPoolManager::m_Event = nullptr private
Definition at line 74 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 74 of file Fun4AllPrdfInputPoolManager.h
Referenced by Fun4AllPrdfInputPoolManager(), ResetEvent(), and run().
unsigned int Fun4AllPrdfInputPoolManager::m_InitialPoolDepth = 20 private
Definition at line 70 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 70 of file Fun4AllPrdfInputPoolManager.h
Referenced by run().
std::map<int, PacketInfo> Fun4AllPrdfInputPoolManager::m_PacketMap private
Definition at line 78 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 78 of file Fun4AllPrdfInputPoolManager.h
Referenced by AddPacket(), ClearAllEvents(), DitchEvent(), run(), UpdateEventFoundCounter(), and ~Fun4AllPrdfInputPoolManager().
unsigned int Fun4AllPrdfInputPoolManager::m_PoolDepth = 100 private
Definition at line 69 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 69 of file Fun4AllPrdfInputPoolManager.h
Referenced by run(), and SetPoolDepth().
std::vector<SinglePrdfInput *> Fun4AllPrdfInputPoolManager::m_PrdfInputVector private
Definition at line 71 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 71 of file Fun4AllPrdfInputPoolManager.h
Referenced by AddPrdfInputFile(), AddPrdfInputList(), fileclose(), registerPrdfInput(), Resynchronize(), run(), and ~Fun4AllPrdfInputPoolManager().
std::string Fun4AllPrdfInputPoolManager::m_PrdfNodeName private
Definition at line 79 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 79 of file Fun4AllPrdfInputPoolManager.h
Referenced by Fun4AllPrdfInputPoolManager(), GetString(), ResetEvent(), and run().
std::map<int, int> Fun4AllPrdfInputPoolManager::m_RefClockCounters private
Definition at line 82 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 82 of file Fun4AllPrdfInputPoolManager.h
Referenced by ClearAllEvents(), CreateBclkOffsets(), DitchEvent(), Resynchronize(), run(), and SetReferenceClock().
SinglePrdfInput* Fun4AllPrdfInputPoolManager::m_RefPrdfInput = nullptr private
Definition at line 77 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 77 of file Fun4AllPrdfInputPoolManager.h
Referenced by CreateBclkOffsets(), and SetReferenceInputMgr().
int Fun4AllPrdfInputPoolManager::m_RunNumber = 0 private
Definition at line 68 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 68 of file Fun4AllPrdfInputPoolManager.h
Referenced by Resynchronize(), and run().
std::map<SinglePrdfInput *, SinglePrdfInputInfo> Fun4AllPrdfInputPoolManager::m_SinglePrdfInputInfo private
Definition at line 83 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 83 of file Fun4AllPrdfInputPoolManager.h
Referenced by CreateBclkOffsets(), Resynchronize(), and run().
bool Fun4AllPrdfInputPoolManager::m_StartUpFlag = true private
Definition at line 67 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 67 of file Fun4AllPrdfInputPoolManager.h
Referenced by run().
SyncObject* Fun4AllPrdfInputPoolManager::m_SyncObject = nullptr private
Definition at line 72 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 72 of file Fun4AllPrdfInputPoolManager.h
Referenced by GetSyncObject(), SyncIt(), and ~Fun4AllPrdfInputPoolManager().
PHCompositeNode* Fun4AllPrdfInputPoolManager::m_topNode = nullptr private
Definition at line 73 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 73 of file Fun4AllPrdfInputPoolManager.h
Referenced by Fun4AllPrdfInputPoolManager(), ResetEvent(), and run().
oEvent* Fun4AllPrdfInputPoolManager::oph = nullptr private
Definition at line 76 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 76 of file Fun4AllPrdfInputPoolManager.h
Referenced by Fun4AllPrdfInputPoolManager(), run(), and ~Fun4AllPrdfInputPoolManager().
PHDWORD Fun4AllPrdfInputPoolManager::workmem[4 *1024 *1024] = {} private
Definition at line 75 of file Fun4AllPrdfInputPoolManager.h.
View newest version in sPHENIX GitHub at line 75 of file Fun4AllPrdfInputPoolManager.h
Referenced by Fun4AllPrdfInputPoolManager(), and run().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4allraw/Fun4AllPrdfInputPoolManager.h
coresoftware/blob/master/offline/framework/fun4allraw/Fun4AllPrdfInputPoolManager.cc