Analysis Software: LazyTiling9 Class Reference
LazyTiling9 Class Reference
Public Member Functions
LazyTiling9 (ClusterSequence &cs)
void run ()
Protected Member Functions
void _initialise_tiles ()
int _tile_index (int ieta, int iphi) const
void _bj_remove_from_tiles (TiledJet *const jet)
int _tile_index (const double eta, const double phi) const
void _tj_set_jetinfo (TiledJet *const jet, const int _jets_index)
void _print_tiles (TiledJet *briefjets) const
void _add_neighbours_to_tile_union (const int tile_index, std::vector< int > &tile_union, int &n_near_tiles) const
void _add_untagged_neighbours_to_tile_union (const int tile_index, std::vector< int > &tile_union, int &n_near_tiles)
void _add_untagged_neighbours_to_tile_union_using_max_info (const TiledJet *const jet, std::vector< int > &tile_union, int &n_near_tiles)
double _distance_to_tile (const TiledJet *bj, const Tile2 *) const
void _update_jetX_jetI_NN (TiledJet *jetX, TiledJet *jetI, std::vector< TiledJet * > &jets_for_minheap)
void _set_NN (TiledJet *jetI, std::vector< TiledJet * > &jets_for_minheap)
template<class J >
double _bj_diJ (const J *const jet) const
template<class J >
void _bj_set_jetinfo (J *const jetA, const int _jets_index) const
template<class J >
double _bj_dist (const J *const jetA, const J *const jetB) const
template<class J >
double _bj_dist_not_periodic (const J *const jetA, const J *const jetB) const
Protected Attributes
ClusterSequence & _cs
const std::vector< PseudoJet > & _jets
std::vector< Tile2 > _tiles
double _Rparam
double _R2
double _invR2
double _tiles_eta_min
double _tiles_eta_max
double _tile_size_eta
double _tile_size_phi
double _tile_half_size_eta
double _tile_half_size_phi
int _n_tiles_phi
int _tiles_ieta_min
int _tiles_ieta_max
std::vector< TiledJet * > _jets_for_minheap
Detailed Description
Definition at line 973 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 973 of file fjcore.cc
Constructor & Destructor Documentation
FJCORE_BEGIN_NAMESPACE LazyTiling9::LazyTiling9 (ClusterSequence & cs)
Definition at line 5353 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5353 of file fjcore.cc
References _initialise_tiles(), _invR2, _R2, and _Rparam.
Member Function Documentation
void LazyTiling9::_add_neighbours_to_tile_union (const int tile_index, std::vector< int > & tile_union, int & n_near_tiles) const protected
Definition at line 5495 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5495 of file fjcore.cc
References _tiles.
Referenced by ClusterSequence::_tiled_N2_cluster().
void LazyTiling9::_add_untagged_neighbours_to_tile_union (const int tile_index, std::vector< int > & tile_union, int & n_near_tiles) inline protected
Definition at line 5503 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5503 of file fjcore.cc
References _tiles.
Referenced by ClusterSequence::_faster_tiled_N2_cluster(), and ClusterSequence::_minheap_faster_tiled_N2_cluster().
void LazyTiling9::_add_untagged_neighbours_to_tile_union_using_max_info (const TiledJet *const jet, std::vector< int > & tile_union, int & n_near_tiles) inline protected
Definition at line 5515 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5515 of file fjcore.cc
References _distance_to_tile(), _tiles, Tile2Base< NN >::begin_tiles, dist(), Tile2Base< NN >::end_tiles, tile_edge_security_margin, and TiledJet::tile_index.
Referenced by run().
template<class J > double LazyTiling9::_bj_diJ (const J *const jet) const inline protected
Definition at line 1014 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1014 of file fjcore.cc
Referenced by ClusterSequence::_faster_tiled_N2_cluster(), ClusterSequence::_minheap_faster_tiled_N2_cluster(), ClusterSequence::_tiled_N2_cluster(), and run().
template<class J > double LazyTiling9::_bj_dist (const J *const jetA, const J *const jetB) const inline protected
Definition at line 1028 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1028 of file fjcore.cc
References INTTVtxZ::dphi, pi, and twopi.
Referenced by ClusterSequence::_faster_tiled_N2_cluster(), ClusterSequence::_minheap_faster_tiled_N2_cluster(), _set_NN(), ClusterSequence::_tiled_N2_cluster(), _update_jetX_jetI_NN(), and run().
template<class J > double LazyTiling9::_bj_dist_not_periodic (const J *const jetA, const J *const jetB) const inline protected
Definition at line 1041 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1041 of file fjcore.cc
References INTTVtxZ::dphi.
Referenced by run().
void LazyTiling9::_bj_remove_from_tiles (TiledJet *const jet) protected
Definition at line 5471 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5471 of file fjcore.cc
References _tiles, Tile2Base< NN >::head, TiledJet::next, TiledJet::previous, and TiledJet::tile_index.
Referenced by ClusterSequence::_faster_tiled_N2_cluster(), ClusterSequence::_minheap_faster_tiled_N2_cluster(), ClusterSequence::_tiled_N2_cluster(), and run().
template<class J > void LazyTiling9::_bj_set_jetinfo (J *const jetA, const int _jets_index) const inline protected
Definition at line 1019 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1019 of file fjcore.cc
References _cs, _jets, and _R2.
double LazyTiling9::_distance_to_tile (const TiledJet * bj, const Tile2 * tile) const inline protected
Definition at line 5528 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5528 of file fjcore.cc
References INTTVtxZ::dphi, TiledJet::eta, Tile2Base< NN >::eta_centre, TiledJet::phi, Tile2Base< NN >::phi_centre, pi, TiledJet::tile_index, and twopi.
Referenced by _add_untagged_neighbours_to_tile_union_using_max_info(), _set_NN(), and run().
void LazyTiling9::_initialise_tiles () protected
Definition at line 5365 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5365 of file fjcore.cc
References _cs, _jets, _n_tiles_phi, _Rparam, _tile_half_size_eta, _tile_half_size_phi, _tile_index(), _tile_size_eta, _tile_size_phi, _tiles, _tiles_eta_max, _tiles_eta_min, _tiles_ieta_max, _tiles_ieta_min, Tile2Base< NN >::begin_tiles, Tile2Base< NN >::end_tiles, eta, Tile2Base< NN >::eta_centre, Tile2Base< NN >::head, i, Tile2Base< NN >::max_NN_dist, TilingExtent::maxrap(), TilingExtent::minrap(), Tile2Base< NN >::phi_centre, Tile2Base< NN >::RH_tiles, Tile2Base< NN >::surrounding_tiles, Tile2Base< NN >::tagged, tile(), twopi, and Tile2Base< NN >::use_periodic_delta_phi.
Referenced by ClusterSequence::_faster_tiled_N2_cluster(), ClusterSequence::_minheap_faster_tiled_N2_cluster(), ClusterSequence::_tiled_N2_cluster(), and LazyTiling9().
void LazyTiling9::_print_tiles (TiledJet * briefjets) const protected
Definition at line 5482 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5482 of file fjcore.cc
References _tiles, i, TiledJet::next, and Acts::Experimental::detail::BlueprintHelper::sort().
void LazyTiling9::_set_NN (TiledJet * jetI, std::vector< TiledJet * > & jets_for_minheap) inline protected
Definition at line 5562 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5562 of file fjcore.cc
References _bj_dist(), _distance_to_tile(), _R2, _tiles, Tile2Base< NN >::begin_tiles, dist(), Tile2Base< NN >::end_tiles, TiledJet::label_minheap_update_needed(), TiledJet::minheap_update_needed(), TiledJet::next, TiledJet::NN, TiledJet::NN_dist, and TiledJet::tile_index.
Referenced by run().
int LazyTiling9::_tile_index (int ieta, int iphi) const inline protected
Definition at line 992 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 992 of file fjcore.cc
References _n_tiles_phi, and _tiles_ieta_min.
Referenced by _initialise_tiles(), ClusterSequence::_initialise_tiles(), _tj_set_jetinfo(), and ClusterSequence::_tj_set_jetinfo().
int LazyTiling9::_tile_index (const double eta, const double phi) const protected
Definition at line 5449 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5449 of file fjcore.cc
References _n_tiles_phi, _tile_size_eta, _tile_size_phi, _tiles_eta_max, _tiles_eta_min, _tiles_ieta_max, _tiles_ieta_min, and twopi.
void LazyTiling9::_tj_set_jetinfo (TiledJet *const jet, const int _jets_index) inline protected
Definition at line 5461 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5461 of file fjcore.cc
References _tile_index(), _tiles, Tile2Base< NN >::head, TiledJet::next, and TiledJet::previous.
Referenced by ClusterSequence::_faster_tiled_N2_cluster(), ClusterSequence::_minheap_faster_tiled_N2_cluster(), ClusterSequence::_tiled_N2_cluster(), and run().
void LazyTiling9::_update_jetX_jetI_NN (TiledJet * jetX, TiledJet * jetI, std::vector< TiledJet * > & jets_for_minheap) inline protected
Definition at line 5544 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5544 of file fjcore.cc
References _bj_dist(), dist(), TiledJet::label_minheap_update_needed(), TiledJet::minheap_update_needed(), TiledJet::NN, and TiledJet::NN_dist.
Referenced by run().
void LazyTiling9::run ()
Definition at line 5582 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5582 of file fjcore.cc
References _add_untagged_neighbours_to_tile_union_using_max_info(), _bj_diJ(), _bj_dist(), _bj_dist_not_periodic(), _bj_remove_from_tiles(), _cs, _distance_to_tile(), _invR2, _jets, TiledJet::_jets_index, _set_NN(), _tiles, _tj_set_jetinfo(), _update_jetX_jetI_NN(), Tile2Base< NN >::begin_tiles, dist(), Tile2Base< NN >::end_tiles, Tile2Base< NN >::head, i, TiledJet::label_minheap_update_done(), Tile2Base< NN >::max_NN_dist, MinHeap::minloc(), MinHeap::minval(), n, TiledJet::next, TiledJet::NN, TiledJet::NN_dist, MinHeap::remove(), swap(), Tile2Base< NN >::tagged, tile(), TiledJet::tile_index, and MinHeap::update().
Referenced by ClusterSequence::_initialise_and_run_no_decant().
Member Data Documentation
ClusterSequence& LazyTiling9::_cs protected
Definition at line 978 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 978 of file fjcore.cc
Referenced by _bj_set_jetinfo(), LazyTiling25::_bj_set_jetinfo(), _initialise_tiles(), and run().
double LazyTiling9::_invR2 protected
Definition at line 985 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 985 of file fjcore.cc
Referenced by ClusterSequence::_add_ktdistance_to_map(), ClusterSequence::_CP2DChan_cluster(), ClusterSequence::_CP2DChan_limited_cluster(), ClusterSequence::_decant_options_partial(), ClusterSequence::_faster_tiled_N2_cluster(), ClusterSequence::_initialise_and_run_no_decant(), ClusterSequence::_minheap_faster_tiled_N2_cluster(), ClusterSequence::_really_dumb_cluster(), ClusterSequence::_tiled_N2_cluster(), LazyTiling9(), run(), and ClusterSequence::transfer_from_sequence().
const std::vector<PseudoJet>& LazyTiling9::_jets protected
Definition at line 979 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 979 of file fjcore.cc
Referenced by ClusterSequence::_add_ktdistance_to_map(), ClusterSequence::_add_step_to_history(), ClusterSequence::_best_strategy(), _bj_set_jetinfo(), LazyTiling25::_bj_set_jetinfo(), ClusterSequence::_bj_set_jetinfo(), ClusterSequence::_CP2DChan_cluster(), ClusterSequence::_CP2DChan_limited_cluster(), ClusterSequence::_delaunay_cluster(), ClusterSequence::_do_iB_recombination_step(), ClusterSequence::_do_ij_recombination_step(), ClusterSequence::_faster_tiled_N2_cluster(), ClusterSequence::_fill_initial_history(), ClusterSequence::_initialise_and_run_no_decant(), _initialise_tiles(), ClusterSequence::_minheap_faster_tiled_N2_cluster(), ClusterSequence::_really_dumb_cluster(), ClusterSequence::_tiled_N2_cluster(), ClusterSequence::add_constituents(), ClusterSequence::childless_pseudojets(), ClusterSequence::exclusive_jets_up_to(), ClusterSequence::exclusive_subjets_up_to(), ClusterSequence::has_parents(), ClusterSequence::has_partner(), ClusterSequence::inclusive_jets(), ClusterSequence::plugin_record_ij_recombination(), run(), ClusterSequence::transfer_from_sequence(), and ClusterSequence::unclustered_particles().
std::vector<TiledJet *> LazyTiling9::_jets_for_minheap protected
Definition at line 990 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 990 of file fjcore.cc
int LazyTiling9::_n_tiles_phi protected
Definition at line 989 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 989 of file fjcore.cc
Referenced by _initialise_tiles(), ClusterSequence::_initialise_tiles(), _tile_index(), and LazyTiling25::_tile_index().
double LazyTiling9::_R2 protected
Definition at line 985 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 985 of file fjcore.cc
Referenced by _bj_set_jetinfo(), LazyTiling25::_bj_set_jetinfo(), ClusterSequence::_bj_set_jetinfo(), ClusterSequence::_decant_options_partial(), ClusterSequence::_faster_tiled_N2_cluster(), ClusterSequence::_initialise_and_run_no_decant(), ClusterSequence::_minheap_faster_tiled_N2_cluster(), _set_NN(), ClusterSequence::_tiled_N2_cluster(), LazyTiling9(), and ClusterSequence::transfer_from_sequence().
double LazyTiling9::_Rparam protected
Definition at line 985 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 985 of file fjcore.cc
Referenced by ClusterSequence::_best_strategy(), ClusterSequence::_bj_set_jetinfo(), ClusterSequence::_CP2DChan_cluster_2pi2R(), ClusterSequence::_CP2DChan_cluster_2piMultD(), ClusterSequence::_decant_options_partial(), ClusterSequence::_delaunay_cluster(), ClusterSequence::_initialise_and_run_no_decant(), _initialise_tiles(), ClusterSequence::_initialise_tiles(), LazyTiling9(), and ClusterSequence::transfer_from_sequence().
double LazyTiling9::_tile_half_size_eta protected
Definition at line 988 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 988 of file fjcore.cc
Referenced by _initialise_tiles().
double LazyTiling9::_tile_half_size_phi protected
Definition at line 988 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 988 of file fjcore.cc
Referenced by _initialise_tiles().
double LazyTiling9::_tile_size_eta protected
Definition at line 987 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 987 of file fjcore.cc
Referenced by _initialise_tiles(), ClusterSequence::_initialise_tiles(), and _tile_index().
double LazyTiling9::_tile_size_phi protected
Definition at line 987 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 987 of file fjcore.cc
Referenced by _initialise_tiles(), ClusterSequence::_initialise_tiles(), and _tile_index().
std::vector<Tile2> LazyTiling9::_tiles protected
Definition at line 980 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 980 of file fjcore.cc
Referenced by _add_neighbours_to_tile_union(), ClusterSequence::_add_neighbours_to_tile_union(), _add_untagged_neighbours_to_tile_union(), ClusterSequence::_add_untagged_neighbours_to_tile_union(), _add_untagged_neighbours_to_tile_union_using_max_info(), _bj_remove_from_tiles(), ClusterSequence::_bj_remove_from_tiles(), ClusterSequence::_faster_tiled_N2_cluster(), _initialise_tiles(), ClusterSequence::_initialise_tiles(), ClusterSequence::_minheap_faster_tiled_N2_cluster(), _print_tiles(), ClusterSequence::_print_tiles(), _set_NN(), ClusterSequence::_tiled_N2_cluster(), _tj_set_jetinfo(), ClusterSequence::_tj_set_jetinfo(), and run().
double LazyTiling9::_tiles_eta_max protected
Definition at line 986 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 986 of file fjcore.cc
Referenced by _initialise_tiles(), ClusterSequence::_initialise_tiles(), and _tile_index().
double LazyTiling9::_tiles_eta_min protected
Definition at line 986 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 986 of file fjcore.cc
Referenced by _initialise_tiles(), ClusterSequence::_initialise_tiles(), and _tile_index().
int LazyTiling9::_tiles_ieta_max protected
Definition at line 989 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 989 of file fjcore.cc
Referenced by _initialise_tiles(), ClusterSequence::_initialise_tiles(), and _tile_index().
int LazyTiling9::_tiles_ieta_min protected
Definition at line 989 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 989 of file fjcore.cc
Referenced by _initialise_tiles(), ClusterSequence::_initialise_tiles(), _tile_index(), and LazyTiling25::_tile_index().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/fjcore.cc