Analysis Software: analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SEnergyCorrelator/macros/MakePrettyPlot.C File Reference
MakePrettyPlot.C File Reference
#include <iostream>
#include "TH1.h"
#include "TPad.h"
#include "TFile.h"
#include "TLine.h"
#include "TError.h"
#include "TString.h"
#include "TLegend.h"
#include "TCanvas.h"
#include "TPaveText.h"
Functions
static const UInt_t NNumer (14)
static const UInt_t NPlot (2)
static const UInt_t NPad (2)
static const UInt_t NVtx (4)
void MakePrettyPlot ()
Function Documentation
void MakePrettyPlot ()
Definition at line 30 of file MakePrettyPlot.C.
View newest version in sPHENIX GitHub at line 30 of file MakePrettyPlot.C
References AddEntry(), cd(), Close(), Data, Draw(), GetXaxis(), GetYaxis(), leg, line, NNumer(), NPad(), NPlot(), NVtx(), Reset(), SetBorderMode(), SetBorderSize(), SetBottomMargin(), SetFillColor(), SetFillStyle(), SetFrameBorderMode(), SetLeftMargin(), SetLineColor(), SetLineStyle(), SetLineWidth(), SetLogy(), SetMarkerColor(), SetMarkerStyle(), SetName(), SetRightMargin(), SetTextFont(), SetTitle(), SetTopMargin(), width, and Write().
static const UInt_t NNumer (14) static
Referenced by MakePrettyPlot().
static const UInt_t NPad (2) static
Referenced by MakePrettyPlot().
static const UInt_t NPlot (2) static
Referenced by MakePrettyPlot().
static const UInt_t NVtx (4) static
Referenced by MakePrettyPlot().