Analysis Software: analysis/blob/master/HF-Jet/TruthGeneration/projections/200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C File Reference
200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C File Reference
Functions
gStyle SetOptFit (1)
gStyle SetOptStat (0)
gStyle SetOptTitle (0)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 Range (0, 0, 1, 1)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetFillColor (0)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetBorderMode (0)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetBorderSize (2)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetTickx (1)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetTicky (1)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetLeftMargin (0.16)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetRightMargin (0.05)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetTopMargin (0.05)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetBottomMargin (0.16)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetFrameBorderMode (0)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 Draw ()
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 cd ()
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 Range (9.936709,-0.1810127, 41.58228, 0.3253165)
hframe__3 SetMinimum (-0.1)
hframe__3 SetMaximum (0.3)
hframe__3 SetDirectory (0)
hframe__3 SetStats (0)
hframe__3 SetLineWidth (2)
hframe__3 SetMarkerStyle (20)
hframe__3 SetMarkerSize (1.2)
hframe__3 GetXaxis () -> SetTitle("Transverse Momentum [GeV/#it
hframe__3 GetYaxis () -> SetTitle("v_
hframe__3 GetZaxis () -> SetLabelFont(42)
hframe__3 Draw (" ")
gre SetName ("ge_h_b_copyv21714636915")
gre SetTitle ("Graph")
gre SetFillColor (1)
gre SetLineColor (ci)
gre SetLineWidth (3)
gre SetMarkerColor (ci)
gre SetMarkerSize (2)
gre SetPoint (0, 16.8, 0)
gre SetPointError (0, 0, 0.005634446)
gre SetPoint (1, 21.8, 0)
gre SetPointError (1, 0, 0.01354795)
gre SetPoint (2, 26.8, 0)
gre SetPointError (2, 0, 0.03095422)
gre SetPoint (3, 31.8, 0)
gre SetPointError (3, 0, 0.06813101)
gre SetHistogram (Graph_ge_h_b_copyv217146369153)
gre Draw ("pe")
gre SetName ("ge_h_b_copyv21649760492")
gre SetMarkerStyle (33)
gre SetPoint (0, 18.2, 0)
gre SetPoint (1, 23.2, 0)
gre SetPoint (2, 28.2, 0)
gre SetPoint (3, 33.2, 0)
gre SetHistogram (Graph_ge_h_b_copyv216497604924)
leg SetBorderSize (0)
leg SetLineColor (1)
leg SetLineStyle (1)
leg SetLineWidth (1)
leg SetFillStyle (0)
entry SetMarkerColor (1)
entry SetMarkerStyle (21)
entry SetMarkerSize (1)
entry SetTextFont (42)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 Modified ()
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetSelected (Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70)
Variables
TPad * Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 = new TPad("Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70_1", "Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70_1",0.01,0.01,0.99,0.99)
TH1F * hframe__3 = new TH1F("hframe__3","",1000,15,40)
TGraphErrors * gre = new TGraphErrors(4)
Int_t ci = TColor::GetColor("#000066")
TColor * color
TH1F * Graph_ge_h_b_copyv217146369153 = new TH1F("Graph_ge_h_b_copyv217146369153","Graph",100,15.3,33.3)
TH1F * Graph_ge_h_b_copyv216497604924 = new TH1F("Graph_ge_h_b_copyv216497604924","Graph",100,16.7,34.7)
TLegend * leg = new TLegend(0,0.78,0.85,0.93,NULL,"brNDC")
TLegendEntry * entry =leg->AddEntry("NULL","#it{#bf{sPHENIX }} Simulation","")
Function Documentation
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 cd ()
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 Draw ()
hframe__3 Draw (" ")
gre Draw ("pe")
hframe__3 GetXaxis () -> SetTitle("Transverse Momentum [GeV/#it
Definition at line 45 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C.
View newest version in sPHENIX GitHub at line 45 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C
hframe__3 GetYaxis () -> SetTitle("v_
Definition at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C.
View newest version in sPHENIX GitHub at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C
hframe__3 GetZaxis () -> SetLabelFont(42)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 Modified ()
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 Range (0 , 0 , 1 , 1)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 Range (9. 936709, -0. 1810127, 41. 58228, 0. 3253165)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetBorderMode (0)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetBorderSize (2)
leg SetBorderSize (0)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetBottomMargin (0. 16)
hframe__3 SetDirectory (0)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetFillColor (0)
gre SetFillColor (1)
fTCBfordave SetFillStyle (0)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetFrameBorderMode (0)
gre SetHistogram (Graph_ge_h_b_copyv217146369153)
gre SetHistogram (Graph_ge_h_b_copyv216497604924)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetLeftMargin (0. 16)
gre SetLineColor (ci)
leg SetLineColor (1)
leg SetLineStyle (1)
hframe__3 SetLineWidth (2)
gre SetLineWidth (3)
leg SetLineWidth (1)
entry SetMarkerColor (ci)
entry SetMarkerColor (1)
hframe__3 SetMarkerSize (1. 2)
gre SetMarkerSize (2)
entry SetMarkerSize (1)
hframe__3 SetMarkerStyle (20)
entry SetMarkerStyle (33)
entry SetMarkerStyle (21)
Graph_ge_h_b_copyv216497604924 SetMaximum (0. 3)
Graph_ge_h_b_copyv216497604924 SetMinimum (-0. 1)
gre SetName ("ge_h_b_copyv21714636915")
Referenced by SDeltaPtCutStudy::CalculateEfficiencies(), SDeltaPtCutStudy::CalculateRejectionFactors(), CalculateSigmaDca(), CompareOldVsNewPlots(), SDeltaPtCutStudy::CreateSigmaGraphs(), DoPercentDifference(), draw_hists_3D(), CemcMonDraw::DrawFirst(), CemcMonDraw::DrawFourth(), CemcMonDraw::DrawSecond(), CemcMonDraw::DrawThird(), PgPostBankBackupStorage::format_name_title(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), numericInverse(), and QuickDeltaPtExtractor().
gre SetName ("ge_h_b_copyv21649760492")
gStyle SetOptFit (1)
gStyle SetOptStat (0)
gStyle SetOptTitle (0)
gre SetPoint (0 , 16. 8, 0)
Referenced by analyzeClusterEtIso(), draw_hists_3D(), hLabHelper::evDisplay(), stack::getStackTime(), and numericInverse().
gre SetPoint (1 , 21. 8, 0)
gre SetPoint (2 , 26. 8, 0)
gre SetPoint (3 , 31. 8, 0)
gre SetPoint (0 , 18. 2, 0)
gre SetPoint (1 , 23. 2, 0)
gre SetPoint (2 , 28. 2, 0)
gre SetPoint (3 , 33. 2, 0)
gre SetPointError (0 , 0 , 0. 005634446)
Referenced by analyzeClusterEtIso(), draw_hists_3D(), and numericInverse().
gre SetPointError (1 , 0 , 0. 01354795)
gre SetPointError (2 , 0 , 0. 03095422)
gre SetPointError (3 , 0 , 0. 06813101)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetRightMargin (0. 05)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetSelected (Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0. 70)
hframe__3 SetStats (0)
entry SetTextFont (42)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetTickx (1)
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetTicky (1)
gre SetTitle ("Graph")
Referenced by analyzeClusterEtIso(), towerid::CalculateCutOffs(), CalculateSigmaDca(), CompareOldVsNewPlots(), DoPercentDifference(), doSeries(), RecoPV_optimization::Draw2Dhisttable(), INTTVtxZ::Draw_1DEff(), INTTVtxZ::Draw_1DEffComp(), plotUtil::Draw_1Dhist(), plot_DataSimComp::Draw_1Dhist_datasimcomp(), plot_DataSimComp::Draw_1Dhist_datasimcomp_v2(), INTTVtxZ::Draw_1Dhist_fitGaussian(), centProxy::Draw_1Dhist_wPercentile(), RecoPV_optimization::Draw_1Dhist_wTF1(), plotUtil::Draw_1DhistsComp(), plotUtil::Draw_2Dhist(), plot_DataSimComp::Draw_2Dhist_datasimcomp(), INTTVtxZ::Draw_2Dhist_eff(), centProxy::Draw_2Dhist_wPercentile(), INTTVtxZ::Draw_HistGraph(), draw_hists_3D(), drawCorr(), PgPostBankBackupStorage::format_name_title(), STrackMatcherComparator::InitHists(), MakeNewMatcherPlots(), MakeNewMatcherTuplePlots(), MakeOldEvaluatorPlots(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), numericInverse(), plotUtil::plot_Stack(), QuickDeltaPtExtractor(), SetHistoStyle(), STrackCutStudy::SetHistStyles(), SDeltaPtCutStudy::SetStyles(), and stack::stack().
Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 SetTopMargin (0. 05)
Variable Documentation
ci = TColor::GetColor("#000066")
Definition at line 68 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C.
View newest version in sPHENIX GitHub at line 68 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C
TColor* color
Definition at line 69 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C.
View newest version in sPHENIX GitHub at line 69 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C
TPad* Draw_HFJetTruth_CrossSection2v2_3yr_EPR0 = new TPad("Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70_1", "Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70_1",0.01,0.01,0.99,0.99)
Definition at line 21 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C.
View newest version in sPHENIX GitHub at line 21 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C
entry =leg->AddEntry("NULL","#it{#bf{sPHENIX }} Simulation","")
Definition at line 168 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C.
View newest version in sPHENIX GitHub at line 168 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C
TH1F* Graph_ge_h_b_copyv216497604924 = new TH1F("Graph_ge_h_b_copyv216497604924","Graph",100,16.7,34.7)
Definition at line 135 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C.
View newest version in sPHENIX GitHub at line 135 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C
TH1F* Graph_ge_h_b_copyv217146369153 = new TH1F("Graph_ge_h_b_copyv217146369153","Graph",100,15.3,33.3)
Definition at line 87 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C.
View newest version in sPHENIX GitHub at line 87 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C
gre = new TGraphErrors(4)
Definition at line 63 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C.
View newest version in sPHENIX GitHub at line 63 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C
Referenced by AN_dp_sPHENIX(), D0_BUP2020_AN_3yr(), D0_BUP2020_AN_5yr_comparison(), D0_BUP2020_AuAu_RAA_3yr(), D0_BUP2020_AuAu_v1_5y_compare(), D0_BUP2020_AuAu_v2_3yr(), D0_BUP2020_AuAu_v2_3yr_20wk_comp(), D0_BUP2020_pAu_C0_5_v2_3yr(), D0_BUP2020_pAu_v2_3yr(), D0_BUP2020OOArAr_RAA_5yr(), D0_BUP2020OOArAr_RAA_flat_5yr(), D0_BUP2020OOArAr_v2_5yr(), Lc_BUP2020_AuAu_3yr(), Lc_BUP2022_AuAu_3yr(), and sphenix_han().
TH1F* hframe__3 = new TH1F("hframe__3","",1000,15,40)
Definition at line 37 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C.
View newest version in sPHENIX GitHub at line 37 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C
Referenced by D0_BUP2020pp_significance_3yr().
leg = new TLegend(0,0.78,0.85,0.93,NULL,"brNDC")
Definition at line 161 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C.
View newest version in sPHENIX GitHub at line 161 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_3yr_EPR0.7_deta0.70.C