Analysis Software: Acts::detail::IntersectionHelper2D Struct Reference
Acts::detail::IntersectionHelper2D Struct Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Surfaces/detail/IntersectionHelper2D.hpp>
Static Public Member Functions
static Intersection2D intersectSegment (const Vector2 &s0, const Vector2 &s1, const Vector2 &origin, const Vector2 &dir, bool boundCheck=false)
static std::array
< Intersection2D, 2 > intersectEllipse (ActsScalar Rx, ActsScalar Ry, const Vector2 &origin, const Vector2 &dir)
static std::array
< Intersection2D, 2 > intersectCircle (ActsScalar R, const Vector2 &origin, const Vector2 &dir)
static Intersection2D intersectCircleSegment (ActsScalar R, ActsScalar phiMin, ActsScalar phiMax, const Vector2 &origin, const Vector2 &dir)
Detailed Description
Definition at line 19 of file IntersectionHelper2D.hpp.
View newest version in sPHENIX GitHub at line 19 of file IntersectionHelper2D.hpp
Member Function Documentation
static std::array<Intersection2D, 2> Acts::detail::IntersectionHelper2D::intersectCircle (ActsScalar R, const Vector2 & origin, const Vector2 & dir) inline static
Intersect the circle
Parameters
R The radius
origin The Start of intersection line
dir The Direction of intersection line
Returns
the intersection points
Definition at line 53 of file IntersectionHelper2D.hpp.
View newest version in sPHENIX GitHub at line 53 of file IntersectionHelper2D.hpp
References intersectEllipse().
Referenced by Acts::Test::basicChecks(), and Acts::Test::BOOST_AUTO_TEST_CASE().
Acts::Intersection2D Acts::detail::IntersectionHelper2D::intersectCircleSegment (ActsScalar R, ActsScalar phiMin, ActsScalar phiMax, const Vector2 & origin, const Vector2 & dir) static
Intersect a circle segment
Note
only forward solution is taken
Parameters
R The radius
phiMin The minimum phi value
phiMax The maximum phi value
origin The Start of intersection line
dir The Direction of intersection line
Returns
the intersection points
Definition at line 120 of file IntersectionHelper2D.cpp.
View newest version in sPHENIX GitHub at line 120 of file IntersectionHelper2D.cpp
References Acts::Intersection< DIM >::invalid(), ActsTests::PropagationDatasets::phi, and Acts::VectorHelpers::phi().
Referenced by ActsFatras::Channelizer::segments().
std::array< Acts::Intersection2D, 2 > Acts::detail::IntersectionHelper2D::intersectEllipse (ActsScalar Rx, ActsScalar Ry, const Vector2 & origin, const Vector2 & dir) static
Intersect ellipses
Parameters
Rx The radius in x
Ry The radius in y
origin The Start of intersection line
dir The Direction of intersection line
Returns
the intersection points
Definition at line 44 of file IntersectionHelper2D.cpp.
View newest version in sPHENIX GitHub at line 44 of file IntersectionHelper2D.cpp
References alpha, autodiff::detail::copysign(), Acts::detail::RealQuadraticEquation::first, Acts::Intersection< DIM >::invalid(), k, Acts::s_epsilon, Acts::detail::RealQuadraticEquation::second, Acts::detail::RealQuadraticEquation::solutions, ambiguity_solver_full_chain::x, and x0.
Referenced by Acts::Test::basicChecks(), Acts::Test::BOOST_AUTO_TEST_CASE(), and intersectCircle().
Acts::Intersection2D Acts::detail::IntersectionHelper2D::intersectSegment (const Vector2 & s0, const Vector2 & s1, const Vector2 & origin, const Vector2 & dir, bool boundCheck = false) static
Intersect two segments
Parameters
s0 The Start of the segment
s1 The end of the segment
origin The Start of intersection line
dir The Direction of intersection line
Returns
the intersection point with status
Definition at line 17 of file IntersectionHelper2D.cpp.
View newest version in sPHENIX GitHub at line 17 of file IntersectionHelper2D.cpp
References Acts::Intersection< DIM >::invalid(), line, norm, Acts::s_epsilon, and utils::status.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and ActsFatras::Channelizer::segments().
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Surfaces/detail/IntersectionHelper2D.hpp
acts/blob/sPHENIX/Core/src/Surfaces/IntersectionHelper2D.cpp