Analysis Software: PHG4CellContainer Class Reference
PHG4CellContainer Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CellContainer.h>
Public Types
typedef std::map
< PHG4CellDefs::keytype,
PHG4Cell * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
PHG4CellContainer ()
~PHG4CellContainer () override
void Reset () override
Clear Event.
void identify (std::ostream &os=std::cout) const override
ConstIterator AddCell (PHG4Cell *newCell)
ConstIterator AddCellSpecifyKey (const PHG4CellDefs::keytype key, PHG4Cell *newCell)
void RemoveCell (PHG4CellDefs::keytype key)
preferred removal method, key is currently the cell id
void RemoveCell (PHG4Cell *cell)
inefficent, use key where possible instead
Iterator findOrAddCell (PHG4CellDefs::keytype key)
ConstRange getCells (const unsigned short int detid) const
return all Cells matching a given detid
ConstRange getCells (void) const
return all hist
PHG4Cell * findCell (PHG4CellDefs::keytype key)
unsigned int size (void) const
double getTotalEdep () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
Map cellmap
Detailed Description
Definition at line 16 of file PHG4CellContainer.h.
View newest version in sPHENIX GitHub at line 16 of file PHG4CellContainer.h
Member Typedef Documentation
typedef Map::const_iterator PHG4CellContainer::ConstIterator
Definition at line 21 of file PHG4CellContainer.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4CellContainer.h
typedef std::pair<ConstIterator, ConstIterator> PHG4CellContainer::ConstRange
Definition at line 23 of file PHG4CellContainer.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4CellContainer.h
typedef Map::iterator PHG4CellContainer::Iterator
Definition at line 20 of file PHG4CellContainer.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4CellContainer.h
typedef std::map<PHG4CellDefs::keytype, PHG4Cell *> PHG4CellContainer::Map
Definition at line 19 of file PHG4CellContainer.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4CellContainer.h
typedef std::pair<Iterator, Iterator> PHG4CellContainer::Range
Definition at line 22 of file PHG4CellContainer.h.
View newest version in sPHENIX GitHub at line 22 of file PHG4CellContainer.h
Constructor & Destructor Documentation
PHG4CellContainer::PHG4CellContainer () default
PHG4CellContainer::~PHG4CellContainer () inline override
Definition at line 27 of file PHG4CellContainer.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4CellContainer.h
Member Function Documentation
PHG4CellContainer::ConstIterator PHG4CellContainer::AddCell (PHG4Cell * newCell)
Definition at line 36 of file PHG4CellContainer.cc.
View newest version in sPHENIX GitHub at line 36 of file PHG4CellContainer.cc
References PHG4Cell::get_cellid(), and PHG4CellDefs::get_detid().
Referenced by PHG4HcalCellReco::process_event(), PHG4BlockCellReco::process_event(), PHG4CylinderCellReco::process_event(), and PHG4FullProjSpacalCellReco::process_event().
PHG4CellContainer::ConstIterator PHG4CellContainer::AddCellSpecifyKey (const PHG4CellDefs::keytype key, PHG4Cell * newCell)
Definition at line 49 of file PHG4CellContainer.cc.
View newest version in sPHENIX GitHub at line 49 of file PHG4CellContainer.cc
References PHG4Cell::set_cellid().
PHG4Cell * PHG4CellContainer::findCell (PHG4CellDefs::keytype key)
Definition at line 96 of file PHG4CellContainer.cc.
View newest version in sPHENIX GitHub at line 96 of file PHG4CellContainer.cc
References it.
Referenced by CaloRawTowerEval::all_truth_hits(), and TPCDataStreamEmulator::process_event().
PHG4CellContainer::Iterator PHG4CellContainer::findOrAddCell (PHG4CellDefs::keytype key)
Definition at line 82 of file PHG4CellContainer.cc.
View newest version in sPHENIX GitHub at line 82 of file PHG4CellContainer.cc
References it, and PHG4Cell::set_cellid().
PHG4CellContainer::ConstRange PHG4CellContainer::getCells (const unsigned short int detid) const
return all Cells matching a given detid
Definition at line 62 of file PHG4CellContainer.cc.
View newest version in sPHENIX GitHub at line 62 of file PHG4CellContainer.cc
References Acts::Test::tmp().
Referenced by PHG4BlockCellReco::CheckEnergy(), PHG4CylinderCellReco::CheckEnergy(), PHG4FullProjSpacalCellReco::CheckEnergy(), RawTowerBuilder::process_event(), TPCIntegratedCharge::process_event(), HcalRawTowerBuilder::process_event(), HCalib::process_event(), G4CellNtuple::process_event(), CaloAna::process_g4cells(), and DumpPHG4CellContainer::process_Node().
PHG4CellContainer::ConstRange PHG4CellContainer::getCells (void) const
return all hist
Definition at line 76 of file PHG4CellContainer.cc.
View newest version in sPHENIX GitHub at line 76 of file PHG4CellContainer.cc
double PHG4CellContainer::getTotalEdep () const
Definition at line 109 of file PHG4CellContainer.cc.
View newest version in sPHENIX GitHub at line 109 of file PHG4CellContainer.cc
Referenced by RawTowerBuilder::process_event(), and HcalRawTowerBuilder::process_event().
void PHG4CellContainer::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 23 of file PHG4CellContainer.cc.
View newest version in sPHENIX GitHub at line 23 of file PHG4CellContainer.cc
References identify, and size.
void PHG4CellContainer::RemoveCell (PHG4CellDefs::keytype key) inline
preferred removal method, key is currently the cell id
Definition at line 37 of file PHG4CellContainer.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4CellContainer.h
References cellmap.
void PHG4CellContainer::RemoveCell (PHG4Cell * cell) inline
inefficent, use key where possible instead
Definition at line 43 of file PHG4CellContainer.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4CellContainer.h
References cellmap.
void PHG4CellContainer::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 13 of file PHG4CellContainer.cc.
View newest version in sPHENIX GitHub at line 13 of file PHG4CellContainer.cc
unsigned int PHG4CellContainer::size (void) const inline
Definition at line 70 of file PHG4CellContainer.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4CellContainer.h
References cellmap.
Referenced by DumpPHG4CellContainer::process_Node().
Member Data Documentation
Map PHG4CellContainer::cellmap protected
Definition at line 78 of file PHG4CellContainer.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4CellContainer.h
Referenced by RemoveCell(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CellContainer.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CellContainer.cc