Analysis Software: MyMonDraw Class Reference
MyMonDraw Class Reference
#include <OnlMon/blob/main/subsystems/example/MyMonDraw.h>
Public Member Functions
MyMonDraw (const std::string &name)
~MyMonDraw () override
int Init () override
int Draw (const std::string &what="ALL") override
int MakeHtml (const std::string &what="ALL") override
int SavePlot (const std::string &what="ALL", const std::string &type="png") override
Public Member Functions inherited from OnlMonDraw
OnlMonDraw (const std::string &name="NONE")
virtual ~OnlMonDraw ()
virtual int MakePS (const std::string &what="ALL")
const std::string Name () const
void Verbosity (const int i)
int Verbosity () const
Protected Member Functions
int MakeCanvas (const std::string &name)
int DrawFirst (const std::string &what="ALL")
int DrawSecond (const std::string &what="ALL")
int DrawHistory (const std::string &what="ALL")
Protected Member Functions inherited from OnlMonDraw
virtual int DrawDeadServer (TPad *transparent)
Protected Attributes
int TimeOffsetTicks = -1
TCanvas * TC [3] = {nullptr}
TPad * transparent [3] = {nullptr}
TPad * Pad [6] = {nullptr}
TGraphErrors * gr [2] = {nullptr}
OnlMonDB * dbvars = nullptr
Protected Attributes inherited from OnlMonDraw
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 13 of file MyMonDraw.h.
View newest version in sPHENIX GitHub at line 13 of file MyMonDraw.h
Constructor & Destructor Documentation
MyMonDraw::MyMonDraw (const std::string & name)
Definition at line 23 of file MyMonDraw.cc.
View newest version in sPHENIX GitHub at line 23 of file MyMonDraw.cc
References dbvars, OnlMonDraw::ThisName, and TimeOffsetTicks.
MyMonDraw::~MyMonDraw () inline override
Definition at line 17 of file MyMonDraw.h.
View newest version in sPHENIX GitHub at line 17 of file MyMonDraw.h
Member Function Documentation
int MyMonDraw::Draw (const std::string & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 94 of file MyMonDraw.cc.
View newest version in sPHENIX GitHub at line 94 of file MyMonDraw.cc
References DrawFirst(), DrawHistory(), and DrawSecond().
Referenced by MakeHtml(), and SavePlot().
int MyMonDraw::DrawFirst (const std::string & what = "ALL") protected
Definition at line 121 of file MyMonDraw.cc.
View newest version in sPHENIX GitHub at line 121 of file MyMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::EventTime(), OnlMonClient::getHisto(), OnlMonClient::instance(), MakeCanvas(), Pad, OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int MyMonDraw::DrawHistory (const std::string & what = "ALL") protected
Definition at line 281 of file MyMonDraw.cc.
View newest version in sPHENIX GitHub at line 281 of file MyMonDraw.cc
References parse_cmake_options::begin, dbvars, end, OnlMonDB::GetVar(), gr, i, MakeCanvas(), n, Pad, runnumber, TC, Acts::Test::time, TimeOffsetTicks, CDB::timestamp, ambiguity_solver_full_chain::x, and y.
Referenced by Draw().
int MyMonDraw::DrawSecond (const std::string & what = "ALL") protected
Definition at line 168 of file MyMonDraw.cc.
View newest version in sPHENIX GitHub at line 168 of file MyMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::EventTime(), OnlMonClient::getHisto(), OnlMonClient::instance(), MakeCanvas(), Pad, OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int MyMonDraw::Init () override virtual
Reimplemented from OnlMonDraw.
Definition at line 33 of file MyMonDraw.cc.
View newest version in sPHENIX GitHub at line 33 of file MyMonDraw.cc
int MyMonDraw::MakeCanvas (const std::string & name) protected
Definition at line 38 of file MyMonDraw.cc.
View newest version in sPHENIX GitHub at line 38 of file MyMonDraw.cc
References OnlMonClient::GetDisplaySizeX(), OnlMonClient::GetDisplaySizeY(), OnlMonClient::instance(), Pad, TC, and transparent.
Referenced by DrawFirst(), DrawHistory(), and DrawSecond().
int MyMonDraw::MakeHtml (const std::string & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 239 of file MyMonDraw.cc.
View newest version in sPHENIX GitHub at line 239 of file MyMonDraw.cc
References OnlMonClient::CanvasToPng(), Draw(), OnlMonClient::htmlRegisterPage(), OnlMonClient::instance(), out, OnlMonClient::RunNumber(), OnlMonClient::SaveLogFile(), utils::status, TC, and to_string().
int MyMonDraw::SavePlot (const std::string & what = "ALL", const std::string & type = "png") override virtual
Reimplemented from OnlMonDraw.
Definition at line 215 of file MyMonDraw.cc.
View newest version in sPHENIX GitHub at line 215 of file MyMonDraw.cc
References OnlMonClient::CanvasToPng(), Draw(), filename, OnlMonClient::instance(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and to_string().
Member Data Documentation
OnlMonDB* MyMonDraw::dbvars = nullptr protected
Definition at line 34 of file MyMonDraw.h.
View newest version in sPHENIX GitHub at line 34 of file MyMonDraw.h
Referenced by DrawHistory(), and MyMonDraw().
TGraphErrors* MyMonDraw::gr[2] = {nullptr} protected
Definition at line 33 of file MyMonDraw.h.
View newest version in sPHENIX GitHub at line 33 of file MyMonDraw.h
Referenced by DrawHistory().
TPad* MyMonDraw::Pad[6] = {nullptr} protected
Definition at line 32 of file MyMonDraw.h.
View newest version in sPHENIX GitHub at line 32 of file MyMonDraw.h
Referenced by DrawFirst(), DrawHistory(), DrawSecond(), and MakeCanvas().
TCanvas* MyMonDraw::TC[3] = {nullptr} protected
Definition at line 30 of file MyMonDraw.h.
View newest version in sPHENIX GitHub at line 30 of file MyMonDraw.h
Referenced by DrawFirst(), DrawHistory(), DrawSecond(), MakeCanvas(), MakeHtml(), and SavePlot().
int MyMonDraw::TimeOffsetTicks = -1 protected
Definition at line 29 of file MyMonDraw.h.
View newest version in sPHENIX GitHub at line 29 of file MyMonDraw.h
Referenced by DrawHistory(), and MyMonDraw().
TPad* MyMonDraw::transparent[3] = {nullptr} protected
Definition at line 31 of file MyMonDraw.h.
View newest version in sPHENIX GitHub at line 31 of file MyMonDraw.h
Referenced by DrawFirst(), DrawSecond(), and MakeCanvas().
The documentation for this class was generated from the following files:
OnlMon/blob/main/subsystems/example/MyMonDraw.h
OnlMon/blob/main/subsystems/example/MyMonDraw.cc