Analysis Software: PHG4TpcCylinderGeom Class Reference
PHG4TpcCylinderGeom Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4TpcCylinderGeom.h>
Public Member Functions
PHG4TpcCylinderGeom ()
~PHG4TpcCylinderGeom ()
void identify (std::ostream &os=std::cout) const override
int get_layer () const override
double get_radius () const override
double get_thickness () const override
int get_binning () const
int get_zbins () const
int get_phibins () const
double get_zmin () const override
double get_phistep () const
double get_phimin () const
double get_zstep () const
int get_etabins () const
double get_etastep () const
double get_etamin () const
virtual std::pair< double, double > get_zbounds (const int ibin) const
virtual std::pair< double, double > get_phibounds (const int ibin) const
virtual std::pair< double, double > get_etabounds (const int ibin) const
virtual double get_etacenter (const int ibin) const
virtual double get_zcenter (const int ibin) const
virtual double get_phicenter (const int ibin) const
virtual double get_phicenter_new (const int ibin) const
virtual double get_phi (const float ibin) const
virtual int get_etabin (const double eta) const
virtual int get_zbin (const double z) const
virtual int get_phibin (const double phi, int side=0) const
virtual int get_phibin_new (const double phi) const
virtual float get_pad_float (const double phi, int side=0) const
virtual float get_tbin_float (const double z) const
virtual int find_phibin (const double phi, int side=0) const
void set_layer (const int i) override
void set_binning (const int i)
void set_radius (const double r) override
void set_thickness (const double t) override
void set_zbins (const int i)
void set_zmin (const double z) override
void set_zstep (const double z)
void set_phibins (const int i)
void set_phistep (const double phi)
void set_phimin (const double phi)
void set_etabins (const int i)
void set_etamin (const double z)
void set_etastep (const double z)
void set_r_bias (std::array< std::vector< double >, NSides > dr)
void set_phi_bias (std::array< std::vector< double >, NSides > dphi)
void set_sector_min_phi (std::array< std::vector< double >, NSides > s_min_phi)
void set_sector_max_phi (std::array< std::vector< double >, NSides > s_max_phi)
std::array< std::vector
< double >, NSides > get_sector_min_phi ()
std::array< std::vector
< double >, NSides > get_sector_max_phi ()
Public Member Functions inherited from PHG4CylinderGeom
~PHG4CylinderGeom () override
virtual double get_zmax () const
virtual int get_nscint () const
virtual double get_tiltangle () const
virtual double get_phi_slat_zero () const
virtual void set_zmax (const double)
virtual void set_nscint (const int)
virtual void set_tiltangle (const double)
virtual void set_phi_slat_zero (const double)
virtual void find_segment_center (const int, const int, double[])
virtual void find_strip_center (const int, const int, const int, const int, double[])
virtual void find_strip_index_values (const int, const double, const double, int &, int &)
virtual void find_strip_center_local_coords (const int, const int, const int, double[])
virtual double get_strip_y_spacing () const
virtual double get_strip_z_spacing () const
virtual double get_strip_tilt () const
virtual int get_N_strip_columns () const
virtual int get_N_strips_per_column () const
virtual int get_N_sensors_in_layer () const
virtual double get_pixel_z () const
virtual double get_pixel_x () const
virtual double get_pixel_thickness () const
virtual void ImportParameters (const PHParameters &)
load parameters from PHParameters, which interface to Database/XML/ROOT files
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Static Public Attributes
static const int NSides = 2
Protected Member Functions
void check_binning_method (const int i) const
void check_binning_method_eta (const std::string &src="") const
void check_binning_method_phi (const std::string &src="") const
std::string methodname (const int i) const
Protected Member Functions inherited from PHG4CylinderGeom
PHG4CylinderGeom ()
Protected Attributes
int layer {-999}
int binning {0}
double radius {std::numeric_limits<double>::quiet_NaN()}
int nzbins {-1}
double zmin {std::numeric_limits<double>::quiet_NaN()}
double zstep {std::numeric_limits<double>::quiet_NaN()}
int nphibins {-1}
double phimin {-M_PI}
double phistep {std::numeric_limits<double>::quiet_NaN()}
double thickness {std::numeric_limits<double>::quiet_NaN()}
std::array< std::vector
< double >, NSides > sector_R_bias
std::array< std::vector
< double >, NSides > sector_Phi_bias
std::array< std::vector
< double >, NSides > sector_min_Phi
std::array< std::vector
< double >, NSides > sector_max_Phi
Friends
std::ostream & operator<< (std::ostream &, const PHG4TpcCylinderGeom &)
Detailed Description
Definition at line 14 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 14 of file PHG4TpcCylinderGeom.h
Constructor & Destructor Documentation
PHG4TpcCylinderGeom::PHG4TpcCylinderGeom () inline
Definition at line 17 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4TpcCylinderGeom.h
PHG4TpcCylinderGeom::~PHG4TpcCylinderGeom () inline
Definition at line 19 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4TpcCylinderGeom.h
Member Function Documentation
void PHG4TpcCylinderGeom::check_binning_method (const int i) const protected
Definition at line 527 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 527 of file PHG4TpcCylinderGeom.cc
References binning, and methodname().
Referenced by get_tbin_float(), get_zbin(), get_zbins(), get_zbounds(), get_zcenter(), get_zmin(), get_zstep(), set_zbins(), set_zmin(), and set_zstep().
void PHG4TpcCylinderGeom::check_binning_method_eta (const std::string & src = "") const protected
Definition at line 539 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 539 of file PHG4TpcCylinderGeom.cc
References binning, PHG4CylinderCellDefs::etaphibinning, PHG4CylinderCellDefs::etaslatbinning, methodname(), and PHG4CylinderCellDefs::spacalbinning.
Referenced by get_etabin(), get_etabins(), get_etabounds(), get_etacenter(), get_etamin(), get_etastep(), set_etabins(), set_etamin(), and set_etastep().
void PHG4TpcCylinderGeom::check_binning_method_phi (const std::string & src = "") const protected
Definition at line 558 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 558 of file PHG4TpcCylinderGeom.cc
References binning, PHG4CylinderCellDefs::etaphibinning, PHG4CylinderCellDefs::etaslatbinning, methodname(), PHG4CylinderCellDefs::sizebinning, and PHG4CylinderCellDefs::spacalbinning.
Referenced by get_phi(), get_phibin_new(), get_phibins(), get_phicenter(), get_phicenter_new(), get_phimin(), get_phistep(), set_phibins(), set_phimin(), and set_phistep().
int PHG4TpcCylinderGeom::find_phibin (const double phi, int side = 0) const virtual
Definition at line 284 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 284 of file PHG4TpcCylinderGeom.cc
References nphibins, ActsTests::PropagationDatasets::phi, phimin, phistep, physmon_simulation::s, sector_max_Phi, and sector_min_Phi.
Referenced by get_phibin(), TpcCombinedRawDataUnpacker::process_event(), and TpcRawDataDecoder::process_event().
int PHG4TpcCylinderGeom::get_binning () const inline
Definition at line 27 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4TpcCylinderGeom.h
References binning.
int PHG4TpcCylinderGeom::get_etabin (const double eta) const virtual
Definition at line 260 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 260 of file PHG4TpcCylinderGeom.cc
References check_binning_method_eta(), nzbins, zmin, and zstep.
int PHG4TpcCylinderGeom::get_etabins () const
Definition at line 131 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 131 of file PHG4TpcCylinderGeom.cc
References check_binning_method_eta(), and nzbins.
std::pair< double, double > PHG4TpcCylinderGeom::get_etabounds (const int ibin) const virtual
Definition at line 220 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 220 of file PHG4TpcCylinderGeom.cc
References check_binning_method_eta(), nzbins, PHWHERE, zmin, and zstep.
double PHG4TpcCylinderGeom::get_etacenter (const int ibin) const virtual
Definition at line 433 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 433 of file PHG4TpcCylinderGeom.cc
References check_binning_method_eta(), nzbins, PHWHERE, zmin, and zstep.
Referenced by G4CellNtuple::process_event().
double PHG4TpcCylinderGeom::get_etamin () const
Definition at line 144 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 144 of file PHG4TpcCylinderGeom.cc
References check_binning_method_eta(), and zmin.
double PHG4TpcCylinderGeom::get_etastep () const
Definition at line 138 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 138 of file PHG4TpcCylinderGeom.cc
References check_binning_method_eta(), and zstep.
int PHG4TpcCylinderGeom::get_layer () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 24 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 24 of file PHG4TpcCylinderGeom.h
References layer.
Referenced by PHG4TpcCylinderGeomContainer::AddLayerCellGeom(), PHHybridSeeding::InitializeGeometry(), PHG4TpcPadPlaneReadout::MapToPadPlane(), PHG4TpcPadPlaneReadout::populate_tbins(), and PHG4TpcPadPlaneReadout::populate_zigzag_phibins().
float PHG4TpcCylinderGeom::get_pad_float (const double phi, int side = 0) const virtual
Definition at line 322 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 322 of file PHG4TpcCylinderGeom.cc
References nphibins, ActsTests::PropagationDatasets::phi, phimin, phistep, physmon_simulation::s, sector_max_Phi, and sector_min_Phi.
Referenced by TrkrNtuplizer::fillOutputNtuples().
double PHG4TpcCylinderGeom::get_phi (const float ibin) const virtual
Definition at line 483 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 483 of file PHG4TpcCylinderGeom.cc
References check_binning_method_phi(), nphibins, ActsTests::PropagationDatasets::phi, phistep, PHWHERE, and sector_max_Phi.
Referenced by TpcClusterBuilder::cluster_hits().
int PHG4TpcCylinderGeom::get_phibin (const double phi, int side = 0) const virtual
Definition at line 372 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 372 of file PHG4TpcCylinderGeom.cc
References find_phibin(), ActsTests::PropagationDatasets::phi, phimin, phistep, PHWHERE, physmon_simulation::s, sector_max_Phi, and sector_min_Phi.
Referenced by PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), and PHG4TpcPadPlaneReadout::populate_zigzag_phibins().
int PHG4TpcCylinderGeom::get_phibin_new (const double phi) const virtual
Definition at line 271 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 271 of file PHG4TpcCylinderGeom.cc
References check_binning_method_phi(), nphibins, ActsTests::PropagationDatasets::phi, phimin, and phistep.
int PHG4TpcCylinderGeom::get_phibins () const
Definition at line 93 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 93 of file PHG4TpcCylinderGeom.cc
References check_binning_method_phi(), and nphibins.
Referenced by TpcClusterBuilder::cluster_hits(), PHG4TpcDigitizer::DigitizeCylinderCells(), SvtxEvaluator::fillOutputNtuples(), TpcSimpleClusterizer::is_in_sector_boundary(), PHG4TpcPadBaselineShift::is_in_sector_boundary(), TpcClusterizer::is_in_sector_boundary(), PHG4TpcPadPlaneReadout::MapToPadPlane(), PHG4TpcPadPlaneReadout::populate_zigzag_phibins(), TrkrNtuplizer::printOutputInfo(), SvtxEvaluator::printOutputInfo(), TpcSimpleClusterizer::process_event(), PHG4TpcPadBaselineShift::process_event(), TpcRawWriter::process_event(), TpcClusterizer::process_event(), and readDigitalCurrents::process_event().
std::pair< double, double > PHG4TpcCylinderGeom::get_phibounds (const int ibin) const virtual
Definition at line 235 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 235 of file PHG4TpcCylinderGeom.cc
References nphibins, phimin, phistep, and PHWHERE.
double PHG4TpcCylinderGeom::get_phicenter (const int ibin) const virtual
Definition at line 461 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 461 of file PHG4TpcCylinderGeom.cc
References check_binning_method_phi(), nphibins, phistep, PHWHERE, and sector_max_Phi.
Referenced by TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), TrackerEventDisplay::makeJsonFile(), PHG4TpcPadPlaneReadout::MapToPadPlane(), PHG4TpcPadPlaneReadout::populate_zigzag_phibins(), G4CellNtuple::process_event(), PHG4TpcPadBaselineShift::process_event(), and readDigitalCurrents::process_event().
double PHG4TpcCylinderGeom::get_phicenter_new (const int ibin) const virtual
Definition at line 446 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 446 of file PHG4TpcCylinderGeom.cc
References check_binning_method_phi(), nphibins, phimin, phistep, and PHWHERE.
double PHG4TpcCylinderGeom::get_phimin () const
Definition at line 107 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 107 of file PHG4TpcCylinderGeom.cc
References check_binning_method_phi(), and phimin.
double PHG4TpcCylinderGeom::get_phistep () const
Definition at line 100 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 100 of file PHG4TpcCylinderGeom.cc
References check_binning_method_phi(), and phistep.
Referenced by PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), TrkrClusterIsMatcher::init(), G4Eval::TrkrClusterComparer::init(), and PHG4TpcPadPlaneReadout::populate_zigzag_phibins().
double PHG4TpcCylinderGeom::get_radius () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 25 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 25 of file PHG4TpcCylinderGeom.h
References radius.
Referenced by TrackEvaluation::add_truth_information(), TpcClusterBuilder::cluster_hits(), TrkrNtuplizer::fillOutputNtuples(), PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), PHSimpleKFProp::get_nodes(), TrkrClusterIsMatcher::init(), PHHybridSeeding::InitializeGeometry(), PHTpcClusterMover::InitRun(), TpcSimpleClusterizer::is_in_sector_boundary(), PHG4TpcPadBaselineShift::is_in_sector_boundary(), TpcClusterizer::is_in_sector_boundary(), PHTruthClustering::LayerClusterG4Hits(), SvtxTruthEval::LayerClusterG4Hits(), TrackerEventDisplay::makeJsonFile(), PHG4TpcPadPlaneReadout::populate_zigzag_phibins(), PHG4TpcPadBaselineShift::process_event(), TpcClusterizer::process_event(), readDigitalCurrents::process_event(), PHTpcCentralMembraneClusterizer::process_event(), and TpcDirectLaserReconstruction::process_track().
std::array<std::vector<double>, NSides> PHG4TpcCylinderGeom::get_sector_max_phi () inline
Definition at line 80 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 80 of file PHG4TpcCylinderGeom.h
References sector_max_Phi.
std::array<std::vector<double>, NSides> PHG4TpcCylinderGeom::get_sector_min_phi () inline
Definition at line 79 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4TpcCylinderGeom.h
References sector_min_Phi.
float PHG4TpcCylinderGeom::get_tbin_float (const double z) const virtual
Definition at line 360 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 360 of file PHG4TpcCylinderGeom.cc
References check_binning_method(), nzbins, PHG4CylinderCellDefs::sizebinning, zmin, and zstep.
Referenced by TrkrNtuplizer::fillOutputNtuples().
double PHG4TpcCylinderGeom::get_thickness () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 26 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 26 of file PHG4TpcCylinderGeom.h
References thickness.
Referenced by TrackEvaluation::add_truth_information(), PHHybridSeeding::InitializeGeometry(), PHTruthClustering::LayerClusterG4Hits(), SvtxTruthEval::LayerClusterG4Hits(), and TpcDirectLaserReconstruction::process_track().
int PHG4TpcCylinderGeom::get_zbin (const double z) const virtual
Definition at line 248 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 248 of file PHG4TpcCylinderGeom.cc
References check_binning_method(), nzbins, PHG4CylinderCellDefs::sizebinning, zmin, and zstep.
Referenced by PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), and PHG4TpcPadPlaneReadout::populate_tbins().
int PHG4TpcCylinderGeom::get_zbins () const
Definition at line 67 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 67 of file PHG4TpcCylinderGeom.cc
References check_binning_method(), nzbins, and PHG4CylinderCellDefs::sizebinning.
Referenced by TpcClusterBuilder::cluster_hits(), PHG4TpcDigitizer::DigitizeCylinderCells(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), TrackerEventDisplay::makeJsonFile(), PHG4TpcPadPlaneReadout::MapToPadPlane(), PHG4TpcPadPlaneReadout::populate_tbins(), TrkrNtuplizer::printOutputInfo(), SvtxEvaluator::printOutputInfo(), TpcSimpleClusterizer::process_event(), PHG4TpcPadBaselineShift::process_event(), TpcRawWriter::process_event(), and TpcClusterizer::process_event().
std::pair< double, double > PHG4TpcCylinderGeom::get_zbounds (const int ibin) const virtual
Definition at line 206 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 206 of file PHG4TpcCylinderGeom.cc
References check_binning_method(), nzbins, PHWHERE, PHG4CylinderCellDefs::sizebinning, zmin, and zstep.
double PHG4TpcCylinderGeom::get_zcenter (const int ibin) const virtual
Definition at line 421 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 421 of file PHG4TpcCylinderGeom.cc
References check_binning_method(), nzbins, PHWHERE, PHG4CylinderCellDefs::sizebinning, zmin, and zstep.
Referenced by TpcClusterBuilder::cluster_hits(), SvtxEvaluator::fillOutputNtuples(), PHG4TpcPadPlaneReadout::MapToPadPlane(), PHG4TpcPadPlaneReadout::populate_tbins(), G4CellNtuple::process_event(), PHG4TpcPadBaselineShift::process_event(), and readDigitalCurrents::process_event().
double PHG4TpcCylinderGeom::get_zmin () const override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 74 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 74 of file PHG4TpcCylinderGeom.cc
References check_binning_method(), PHG4CylinderCellDefs::sizebinning, and zmin.
double PHG4TpcCylinderGeom::get_zstep () const
Definition at line 81 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 81 of file PHG4TpcCylinderGeom.cc
References check_binning_method(), PHG4CylinderCellDefs::sizebinning, and zstep.
Referenced by PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), TrkrClusterIsMatcher::init(), G4Eval::TrkrClusterComparer::init(), and PHG4TpcPadPlaneReadout::populate_tbins().
void PHG4TpcCylinderGeom::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4CylinderGeom.
Definition at line 168 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 168 of file PHG4TpcCylinderGeom.cc
References binning, PHG4CylinderCellDefs::etaphibinning, PHG4CylinderCellDefs::etaslatbinning, layer, nphibins, nzbins, phimin, phistep, radius, PHG4CylinderCellDefs::sizebinning, PHG4CylinderCellDefs::spacalbinning, thickness, zmin, and zstep.
std::string PHG4TpcCylinderGeom::methodname (const int i) const protected
Definition at line 505 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 505 of file PHG4TpcCylinderGeom.cc
References PHG4CylinderCellDefs::etaphibinning, PHG4CylinderCellDefs::etaslatbinning, PHG4CylinderCellDefs::sizebinning, and PHG4CylinderCellDefs::spacalbinning.
Referenced by check_binning_method(), check_binning_method_eta(), and check_binning_method_phi().
void PHG4TpcCylinderGeom::set_binning (const int i) inline
Definition at line 57 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4TpcCylinderGeom.h
References binning, and i.
void PHG4TpcCylinderGeom::set_etabins (const int i)
Definition at line 162 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 162 of file PHG4TpcCylinderGeom.cc
References check_binning_method_eta(), i, and nzbins.
void PHG4TpcCylinderGeom::set_etamin (const double z)
Definition at line 150 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 150 of file PHG4TpcCylinderGeom.cc
References check_binning_method_eta(), physmon_track_finding_ttbar::z, and zmin.
void PHG4TpcCylinderGeom::set_etastep (const double z)
Definition at line 156 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 156 of file PHG4TpcCylinderGeom.cc
References check_binning_method_eta(), physmon_track_finding_ttbar::z, and zstep.
void PHG4TpcCylinderGeom::set_layer (const int i) inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 56 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4TpcCylinderGeom.h
References i, and layer.
Referenced by PHG4TpcDetector::add_geometry_node(), and PHG4TpcCylinderGeomContainer::AddLayerCellGeom().
void PHG4TpcCylinderGeom::set_phi_bias (std::array< std::vector< double >, NSides > dphi) inline
Definition at line 73 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4TpcCylinderGeom.h
References INTTVtxZ::dphi, and sector_Phi_bias.
void PHG4TpcCylinderGeom::set_phibins (const int i)
Definition at line 113 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 113 of file PHG4TpcCylinderGeom.cc
References check_binning_method_phi(), i, and nphibins.
void PHG4TpcCylinderGeom::set_phimin (const double phi)
Definition at line 125 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 125 of file PHG4TpcCylinderGeom.cc
References check_binning_method_phi(), phimin, and physmon_track_finding_ttbar::r.
void PHG4TpcCylinderGeom::set_phistep (const double phi)
Definition at line 119 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 119 of file PHG4TpcCylinderGeom.cc
References check_binning_method_phi(), phistep, and physmon_track_finding_ttbar::r.
void PHG4TpcCylinderGeom::set_r_bias (std::array< std::vector< double >, NSides > dr) inline
Definition at line 72 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4TpcCylinderGeom.h
References sector_R_bias.
void PHG4TpcCylinderGeom::set_radius (const double r) inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 58 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4TpcCylinderGeom.h
References physmon_track_finding_ttbar::r, and radius.
void PHG4TpcCylinderGeom::set_sector_max_phi (std::array< std::vector< double >, NSides > s_max_phi) inline
Definition at line 77 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4TpcCylinderGeom.h
References sector_max_Phi.
void PHG4TpcCylinderGeom::set_sector_min_phi (std::array< std::vector< double >, NSides > s_min_phi) inline
Definition at line 76 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4TpcCylinderGeom.h
References sector_min_Phi.
void PHG4TpcCylinderGeom::set_thickness (const double t) inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 59 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4TpcCylinderGeom.h
References t, and thickness.
void PHG4TpcCylinderGeom::set_zbins (const int i)
Definition at line 55 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 55 of file PHG4TpcCylinderGeom.cc
References check_binning_method(), i, nzbins, and PHG4CylinderCellDefs::sizebinning.
void PHG4TpcCylinderGeom::set_zmin (const double z) override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 61 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 61 of file PHG4TpcCylinderGeom.cc
References check_binning_method(), PHG4CylinderCellDefs::sizebinning, physmon_track_finding_ttbar::z, and zmin.
void PHG4TpcCylinderGeom::set_zstep (const double z)
Definition at line 87 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 87 of file PHG4TpcCylinderGeom.cc
References check_binning_method(), PHG4CylinderCellDefs::sizebinning, physmon_track_finding_ttbar::z, and zstep.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const PHG4TpcCylinderGeom & geom) friend
Definition at line 31 of file PHG4TpcCylinderGeom.cc.
View newest version in sPHENIX GitHub at line 31 of file PHG4TpcCylinderGeom.cc
Member Data Documentation
int PHG4TpcCylinderGeom::binning {0} protected
Definition at line 88 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 88 of file PHG4TpcCylinderGeom.h
Referenced by check_binning_method(), check_binning_method_eta(), check_binning_method_phi(), get_binning(), identify(), operator<<(), and set_binning().
int PHG4TpcCylinderGeom::layer {-999} protected
Definition at line 87 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 87 of file PHG4TpcCylinderGeom.h
Referenced by get_layer(), identify(), operator<<(), and set_layer().
int PHG4TpcCylinderGeom::nphibins {-1} protected
Definition at line 93 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 93 of file PHG4TpcCylinderGeom.h
Referenced by find_phibin(), get_pad_float(), get_phi(), get_phibin_new(), get_phibins(), get_phibounds(), get_phicenter(), get_phicenter_new(), identify(), operator<<(), and set_phibins().
const int PHG4TpcCylinderGeom::NSides = 2 static
Definition at line 70 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4TpcCylinderGeom.h
int PHG4TpcCylinderGeom::nzbins {-1} protected
Definition at line 90 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 90 of file PHG4TpcCylinderGeom.h
Referenced by get_etabin(), get_etabins(), get_etabounds(), get_etacenter(), get_tbin_float(), get_zbin(), get_zbins(), get_zbounds(), get_zcenter(), identify(), operator<<(), set_etabins(), and set_zbins().
double PHG4TpcCylinderGeom::phimin {-M_PI} protected
Definition at line 94 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 94 of file PHG4TpcCylinderGeom.h
Referenced by find_phibin(), get_pad_float(), get_phibin(), get_phibin_new(), get_phibounds(), get_phicenter_new(), get_phimin(), identify(), operator<<(), and set_phimin().
double PHG4TpcCylinderGeom::phistep {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 95 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 95 of file PHG4TpcCylinderGeom.h
Referenced by find_phibin(), get_pad_float(), get_phi(), get_phibin(), get_phibin_new(), get_phibounds(), get_phicenter(), get_phicenter_new(), get_phistep(), identify(), operator<<(), and set_phistep().
double PHG4TpcCylinderGeom::radius {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 89 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 89 of file PHG4TpcCylinderGeom.h
Referenced by get_radius(), identify(), operator<<(), and set_radius().
std::array<std::vector<double>, NSides> PHG4TpcCylinderGeom::sector_max_Phi protected
Definition at line 101 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 101 of file PHG4TpcCylinderGeom.h
Referenced by find_phibin(), get_pad_float(), get_phi(), get_phibin(), get_phicenter(), get_sector_max_phi(), operator<<(), and set_sector_max_phi().
std::array<std::vector<double>, NSides> PHG4TpcCylinderGeom::sector_min_Phi protected
Definition at line 100 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 100 of file PHG4TpcCylinderGeom.h
Referenced by find_phibin(), get_pad_float(), get_phibin(), get_sector_min_phi(), operator<<(), and set_sector_min_phi().
std::array<std::vector<double>, NSides> PHG4TpcCylinderGeom::sector_Phi_bias protected
Definition at line 99 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 99 of file PHG4TpcCylinderGeom.h
Referenced by operator<<(), and set_phi_bias().
std::array<std::vector<double>, NSides> PHG4TpcCylinderGeom::sector_R_bias protected
Definition at line 98 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 98 of file PHG4TpcCylinderGeom.h
Referenced by operator<<(), and set_r_bias().
double PHG4TpcCylinderGeom::thickness {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 96 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 96 of file PHG4TpcCylinderGeom.h
Referenced by get_thickness(), identify(), operator<<(), and set_thickness().
double PHG4TpcCylinderGeom::zmin {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 91 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 91 of file PHG4TpcCylinderGeom.h
Referenced by get_etabin(), get_etabounds(), get_etacenter(), get_etamin(), get_tbin_float(), get_zbin(), get_zbounds(), get_zcenter(), get_zmin(), identify(), operator<<(), set_etamin(), and set_zmin().
double PHG4TpcCylinderGeom::zstep {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 92 of file PHG4TpcCylinderGeom.h.
View newest version in sPHENIX GitHub at line 92 of file PHG4TpcCylinderGeom.h
Referenced by get_etabin(), get_etabounds(), get_etacenter(), get_etastep(), get_tbin_float(), get_zbin(), get_zbounds(), get_zcenter(), get_zstep(), identify(), operator<<(), set_etastep(), and set_zstep().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4TpcCylinderGeom.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4TpcCylinderGeom.cc