Analysis Software: PHParameters Class Reference
PHParameters Class Reference
#include <coresoftware/blob/master/offline/database/PHParameter/PHParameters.h>
Public Types
typedef std::map< const
std::string, double > dMap
typedef dMap::const_iterator dIter
typedef std::map< const
std::string, int > iMap
typedef iMap::const_iterator iIter
typedef std::map< const
std::string, std::string > strMap
typedef std::map< const
std::string, std::string >
::const_iterator strIter
Public Member Functions
PHParameters (const std::string &name)
PHParameters (const PHParameters &params, const std::string &name)
~PHParameters () override
void Reset () override
Clear Event.
void Print (Option_t *option="") const override
size_t get_hash () const
hash of binary information for checking purpose
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
bool exist_int_param (const std::string &name) const
std::pair< std::map< const
std::string, int >
::const_iterator, std::map
< const std::string, int >
::const_iterator > get_all_int_params ()
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
bool exist_double_param (const std::string &name) const
std::pair< std::map< const
std::string, double >
::const_iterator, std::map
< const std::string, double >
::const_iterator > get_all_double_params ()
void set_string_param (const std::string &name, const std::string &str)
std::string get_string_param (const std::string &name) const
bool exist_string_param (const std::string &name) const
std::pair< std::map< const
std::string, std::string >
::const_iterator, std::map
< const std::string,
std::string >::const_iterator > get_all_string_params ()
void set_name (const std::string &name)
std::string Name () const
void FillFrom (const PdbParameterMap *saveparams)
void FillFrom (const PdbParameterMapContainer *saveparamcontainer, const int layer)
void FillFrom (const PHParameters *saveparams)
void SaveToNodeTree (PHCompositeNode *topNode, const std::string &nodename)
void SaveToNodeTree (PHCompositeNode *topNode, const std::string &nodename, const int layer)
void UpdateNodeTree (PHCompositeNode *topNode, const std::string &nodename)
void UpdateNodeTree (PHCompositeNode *topNode, const std::string &nodename, const int layer)
int WriteToDB ()
int ReadFromDB ()
int ReadFromCDB (const std::string &domain)
int ReadFromDB (const std::string &name, const int layer)
int WriteToCDBFile (const std::string &filename)
int WriteToFile (const std::string &extension, const std::string &dir=".")
int ReadFromFile (const std::string &name, const std::string &extension, const std::string &dir=".")
simple read without super detector and layer structures
int ReadFromCDBFile (const std::string &name)
int ReadFromFile (const std::string &name, const std::string &extension, const int layer, const int issuper, const std::string &dir=".")
Fully fledged read.
void CopyToPdbParameterMap (PdbParameterMap *myparm)
void printint () const
void printdouble () const
void printstring () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
unsigned int ConvertStringToUint (const std::string &str) const
Private Attributes
std::string m_Detector
dMap m_DoubleParMap
iMap m_IntParMap
strMap m_StringParMap
Detailed Description
Definition at line 20 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 20 of file PHParameters.h
Member Typedef Documentation
typedef dMap::const_iterator PHParameters::dIter
Definition at line 24 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 24 of file PHParameters.h
typedef std::map<const std::string, double> PHParameters::dMap
Definition at line 23 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 23 of file PHParameters.h
typedef iMap::const_iterator PHParameters::iIter
Definition at line 26 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 26 of file PHParameters.h
typedef std::map<const std::string, int> PHParameters::iMap
Definition at line 25 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 25 of file PHParameters.h
typedef std::map<const std::string, std::string>::const_iterator PHParameters::strIter
Definition at line 28 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 28 of file PHParameters.h
typedef std::map<const std::string, std::string> PHParameters::strMap
Definition at line 27 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 27 of file PHParameters.h
Constructor & Destructor Documentation
PHParameters::PHParameters (const std::string & name) inline explicit
Definition at line 30 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 30 of file PHParameters.h
PHParameters::PHParameters (const PHParameters & params, const std::string & name)
Definition at line 46 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 46 of file PHParameters.cc
References FillFrom().
PHParameters::~PHParameters () override
Definition at line 52 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 52 of file PHParameters.cc
References m_DoubleParMap, m_IntParMap, and m_StringParMap.
Member Function Documentation
unsigned int PHParameters::ConvertStringToUint (const std::string & str) const private
Definition at line 698 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 698 of file PHParameters.cc
References str.
Referenced by ReadFromFile().
void PHParameters::CopyToPdbParameterMap (PdbParameterMap * myparm)
Definition at line 678 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 678 of file PHParameters.cc
References m_DoubleParMap, m_IntParMap, m_StringParMap, PdbParameterMap::set_double_param(), PdbParameterMap::set_int_param(), and PdbParameterMap::set_string_param().
Referenced by SaveToNodeTree(), UpdateNodeTree(), WriteToCDBFile(), WriteToDB(), and WriteToFile().
bool PHParameters::exist_double_param (const std::string & name) const
Definition at line 131 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 131 of file PHParameters.cc
References m_DoubleParMap.
Referenced by PHG4CylinderGeom_Spacalv2::ImportParameters(), PHG4CylinderGeom_Spacalv3::ImportParameters(), PHG4CylinderGeomv1::ImportParameters(), PHG4CylinderGeom_Spacalv1::ImportParameters(), PHG4CentralityReco::InitRun(), Prototype4DSTReader::process_event(), PHParameterContainerInterface::set_default_double_param(), and PHParameterContainerInterface::set_double_param().
bool PHParameters::exist_int_param (const std::string & name) const
Definition at line 88 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 88 of file PHParameters.cc
References m_IntParMap.
Referenced by PHG4CylinderGeomv2::ImportParameters(), PHG4CylinderGeom_Spacalv3::ImportParameters(), PHG4CylinderGeom_Spacalv2::ImportParameters(), PHG4CylinderGeomv1::ImportParameters(), PHG4CylinderGeom_Spacalv1::ImportParameters(), PHParameterContainerInterface::set_default_int_param(), and PHParameterContainerInterface::set_int_param().
bool PHParameters::exist_string_param (const std::string & name) const
Definition at line 214 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 214 of file PHParameters.cc
References m_StringParMap.
Referenced by PHG4CylinderGeom_Spacalv3::ImportParameters(), PHG4CylinderGeom_Spacalv1::ImportParameters(), PHG4CentralityReco::InitRun(), PHParameterContainerInterface::set_default_string_param(), and PHParameterContainerInterface::set_string_param().
void PHParameters::FillFrom (const PdbParameterMap * saveparams)
Definition at line 233 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 233 of file PHParameters.cc
References assert, PdbParameterMap::get_cparam_iters(), PdbParameterMap::get_dparam_iters(), PdbParameterMap::get_iparam_iters(), m_DoubleParMap, m_IntParMap, and m_StringParMap.
Referenced by PHParametersContainer::CreateAndFillFrom(), PHParametersContainer::FillFrom(), PHG4DetectorSubsystem::InitRun(), PHG4TrackFastSimEval::InitRun(), PHParameters(), Proto4ShowerCalib::process_event(), Proto2ShowerCalib::process_event(), Proto3ShowerCalib::process_event(), Prototype2DSTReader::process_event(), Prototype3DSTReader::process_event(), Prototype4DSTReader::process_event(), ExampleAnalysisModule::process_event(), ReadFromCDB(), ReadFromCDBFile(), ReadFromDB(), ReadFromFile(), Prototype2RawTowerBuilder::ReadParamsFromNodeTree(), and HcalRawTowerBuilder::ReadParamsFromNodeTree().
void PHParameters::FillFrom (const PdbParameterMapContainer * saveparamcontainer, const int layer)
Definition at line 265 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 265 of file PHParameters.cc
References PdbParameterMap::get_cparam_iters(), PdbParameterMap::get_dparam_iters(), PdbParameterMap::get_iparam_iters(), PdbParameterMapContainer::GetParameters(), m_DoubleParMap, m_IntParMap, and m_StringParMap.
void PHParameters::FillFrom (const PHParameters * saveparams)
Definition at line 302 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 302 of file PHParameters.cc
References assert, m_DoubleParMap, m_IntParMap, and m_StringParMap.
std::pair<std::map<const std::string, double>::const_iterator, std::map<const std::string, double>::const_iterator> PHParameters::get_all_double_params () inline
Definition at line 54 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 54 of file PHParameters.h
References m_DoubleParMap.
std::pair<std::map<const std::string, int>::const_iterator, std::map<const std::string, int>::const_iterator> PHParameters::get_all_int_params () inline
Definition at line 49 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 49 of file PHParameters.h
References m_IntParMap.
Referenced by PHG4InttDeadMapLoader::InitRun(), and PHG4TrackFastSimEval::InitRun().
std::pair<std::map<const std::string, std::string>::const_iterator, std::map<const std::string, std::string>::const_iterator> PHParameters::get_all_string_params () inline
Definition at line 59 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 59 of file PHParameters.h
References m_StringParMap.
double PHParameters::get_double_param (const std::string & name) const
Definition at line 113 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 113 of file PHParameters.cc
References m_DoubleParMap, and PHWHERE.
Referenced by PHG4TpcDetector::add_geometry_node(), PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4InttDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4TpcEndCapDetector::AddLayer(), PHG4OuterHcalDetector::ConsistencyCheck(), PHG4TpcEndCapDetector::ConstructElectronics(), PHG4InnerHcalDetector::ConstructHcalScintillatorAssembly(), PHG4OuterHcalDetector::ConstructHcalScintillatorAssembly(), PHG4OuterHcalDetector::ConstructHcalSingleScintillators(), PHG4InnerHcalDetector::ConstructHcalSingleScintillators(), PHG4InttDetector::ConstructIntt(), G4Example02Detector::ConstructMe(), PHG4PSTOFDetector::ConstructMe(), G4Example03Detector::ConstructMe(), PHG4BeamlineMagnetDetector::ConstructMe(), PHG4BlockDetector::ConstructMe(), PHG4ConeDetector::ConstructMe(), PHG4CylinderDetector::ConstructMe(), PHG4Prototype3InnerHcalDetector::ConstructMe(), BeamLineMagnetDetector::ConstructMe(), PHG4Prototype2InnerHcalDetector::ConstructMe(), PHG4Prototype2OuterHcalDetector::ConstructMe(), PHG4EPDDetector::ConstructMe(), PHG4ZDCDetector::ConstructMe(), PHG4TpcEndCapDetector::ConstructMe(), PHG4TpcDetector::ConstructMe(), PHG4IHCalDetector::ConstructMe(), PHG4OHCalDetector::ConstructMe(), PHG4SpacalPrototype4Detector::ConstructMe(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4InnerHcalDetector::ConstructMe(), PHG4OuterHcalDetector::ConstructMe(), PHG4TpcDetector::ConstructTpcCageVolume(), PHG4TpcDetector::ConstructTpcExternalSupports(), PHG4TpcDetector::ConstructTpcGasVolume(), PHG4TpcEndCapDetector::ConstructWagonWheel(), PHParameterInterface::get_double_param(), PHParameterContainerInterface::get_double_param(), PHG4DetectorSubsystem::get_double_param(), PHG4DetectorGroupSubsystem::get_double_param(), PHG4CylinderGeom_Spacalv2::ImportParameters(), PHG4CylinderGeom_Spacalv3::ImportParameters(), PHG4CylinderGeomv1::ImportParameters(), PHG4CylinderGeom_Spacalv1::ImportParameters(), PHG4CylinderGeom_Spacalv3::geom_tower::ImportParameters(), PHG4CentralityReco::InitRun(), PHG4TpcElectronDrift::InitRun(), PHG4CylinderSubsystem::InitRunSubsystem(), PHG4EICMvtxDetector::PHG4EICMvtxDetector(), PHG4IHCalSteppingAction::PHG4IHCalSteppingAction(), PHG4InnerHcalSteppingAction::PHG4InnerHcalSteppingAction(), PHG4InttSteppingAction::PHG4InttSteppingAction(), PHG4MvtxDetector::PHG4MvtxDetector(), PHG4OHCalDetector::PHG4OHCalDetector(), PHG4OHCalSteppingAction::PHG4OHCalSteppingAction(), PHG4OuterHcalSteppingAction::PHG4OuterHcalSteppingAction(), PHG4Prototype3InnerHcalSteppingAction::PHG4Prototype3InnerHcalSteppingAction(), PHG4TpcSteppingAction::PHG4TpcSteppingAction(), CaloCalibration::process_event(), RawTowerCalibration::process_event(), Proto4ShowerCalib::process_event(), RawTowerDigitizer::process_event(), Proto2ShowerCalib::process_event(), Proto3ShowerCalib::process_event(), Prototype2DSTReader::process_event(), Prototype4DSTReader::process_event(), Prototype3DSTReader::process_event(), ExampleAnalysisModule::process_event(), HcalRawTowerBuilder::ReadParamsFromNodeTree(), and PHParameterContainerInterface::set_default_double_param().
size_t PHParameters::get_hash () const
hash of binary information for checking purpose
Definition at line 150 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 150 of file PHParameters.cc
References m_DoubleParMap, m_IntParMap, m_StringParMap, and seed.
int PHParameters::get_int_param (const std::string & name) const
Definition at line 71 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 71 of file PHParameters.cc
References m_IntParMap, and PHWHERE.
Referenced by PHG4TpcDetector::add_geometry_node(), PHG4MicromegasDetector::add_geometry_node(), PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4InttDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4BlockDisplayAction::ApplyDisplayAction(), PHG4ConeDisplayAction::ApplyDisplayAction(), PHG4CylinderDisplayAction::ApplyDisplayAction(), G4Example03DisplayAction::ApplyDisplayAction(), PHG4TpcEndCapDetector::ConstructElectronics(), PHG4TpcEndCapDetector::ConstructEndCapAssembly(), PHG4OuterHcalDetector::ConstructHcalSingleScintillators(), PHG4Prototype3InnerHcalDetector::ConstructInnerHcal(), PHG4Prototype2InnerHcalDetector::ConstructInnerHcal(), PHG4InttDetector::ConstructIntt(), PHG4BeamlineMagnetDetector::ConstructMe(), PHG4IHCalDetector::ConstructMe(), PHG4OHCalDetector::ConstructMe(), PHG4FullProjTiltedSpacalDetector::ConstructMe(), PHG4InnerHcalDetector::ConstructMe(), PHG4OuterHcalDetector::ConstructMe(), PHG4OHCalDetector::ConstructOHCal(), PHG4Prototype2OuterHcalDetector::ConstructOuterHcal(), PHG4TpcEndCapDetector::ConstructWagonWheel(), PHParameterInterface::get_int_param(), PHParameterContainerInterface::get_int_param(), PHG4DetectorGroupSubsystem::get_int_param(), PHG4DetectorSubsystem::get_int_param(), PHG4CylinderGeomv2::ImportParameters(), PHG4CylinderGeom_Spacalv2::ImportParameters(), PHG4CylinderGeom_Spacalv3::ImportParameters(), PHG4CylinderGeomv1::ImportParameters(), PHG4CylinderGeom_Spacalv1::ImportParameters(), PHG4CylinderGeom_Spacalv3::geom_tower::ImportParameters(), PHG4OuterHcalSubsystem::InitRunSubsystem(), PHG4InnerHcalSubsystem::InitRunSubsystem(), PHG4Prototype2OuterHcalSubsystem::InitRunSubsystem(), PHG4Prototype2InnerHcalSubsystem::InitRunSubsystem(), PHG4Prototype3InnerHcalSubsystem::InitRunSubsystem(), PHG4MvtxSubsystem::InitRunSubsystem(), PHG4EICMvtxSubsystem::InitRunSubsystem(), PHG4InttSubsystem::InitRunSubsystem(), PHG4SpacalSubsystem::InitRunSubsystem(), PHG4OuterHcalSteppingAction::InitWithNode(), PHG4OHCalSteppingAction::InitWithNode(), PHG4EICMvtxDetector::PHG4EICMvtxDetector(), PHG4InnerHcalDetector::PHG4InnerHcalDetector(), PHG4InttDetector::PHG4InttDetector(), PHG4InttSteppingAction::PHG4InttSteppingAction(), PHG4MvtxDetector::PHG4MvtxDetector(), PHG4MvtxSteppingAction::PHG4MvtxSteppingAction(), PHG4PSTOFDetector::PHG4PSTOFDetector(), PHG4SpacalPrototype4Detector::PHG4SpacalPrototype4Detector(), PHG4TpcEndCapDetector::PHG4TpcEndCapDetector(), CaloCalibration::process_event(), Prototype2RawTowerBuilder::ReadParamsFromNodeTree(), HcalRawTowerBuilder::ReadParamsFromNodeTree(), PHParameterContainerInterface::set_default_int_param(), PHG4BbcSteppingAction::SetInterfacePointers(), PHG4MicromegasSteppingAction::SetInterfacePointers(), PHG4OuterHcalDetector::SetTiltViaNcross(), and PHG4InnerHcalDetector::SetTiltViaNcross().
std::string PHParameters::get_string_param (const std::string & name) const
Definition at line 197 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 197 of file PHParameters.cc
References m_StringParMap, and PHWHERE.
Referenced by PHG4BlockDisplayAction::ApplyDisplayAction(), PHG4ConeDisplayAction::ApplyDisplayAction(), PHG4CylinderDisplayAction::ApplyDisplayAction(), G4Example03DisplayAction::ApplyDisplayAction(), PHG4TpcEndCapDetector::ConstructElectronics(), PHG4InnerHcalDetector::ConstructInnerHcal(), PHG4BeamlineMagnetDetector::ConstructMe(), PHG4ConeDetector::ConstructMe(), PHG4CylinderDetector::ConstructMe(), PHG4BlockDetector::ConstructMe(), BeamLineMagnetDetector::ConstructMe(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4SpacalPrototype4Detector::ConstructMe(), PHG4OuterHcalDetector::ConstructOuterHcal(), PHG4Prototype3InnerHcalDetector::ConstructSteelPlate(), PHG4TpcDetector::ConstructTpcCageVolume(), PHG4TpcDetector::ConstructTpcGasVolume(), PHG4TpcEndCapDetector::ConstructWagonWheel(), PHParameterInterface::get_string_param(), PHParameterContainerInterface::get_string_param(), PHG4DetectorGroupSubsystem::get_string_param(), PHG4DetectorSubsystem::get_string_param(), PHG4CylinderGeom_Spacalv3::ImportParameters(), PHG4CylinderGeom_Spacalv1::ImportParameters(), PHG4CylinderGeom_Spacalv3::geom_tower::ImportParameters(), PHG4CentralityReco::InitRun(), PHG4OuterHcalSteppingAction::InitWithNode(), PHG4InnerHcalSteppingAction::InitWithNode(), PHG4IHCalSteppingAction::InitWithNode(), PHG4OHCalSteppingAction::InitWithNode(), PHG4OHCalDetector::PHG4OHCalDetector(), and PHParameterContainerInterface::set_default_string_param().
std::string PHParameters::Name () const inline
Definition at line 62 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 62 of file PHParameters.h
References m_Detector.
Referenced by PHG4DetectorSubsystem::InitRun(), and PHParameterInterface::PutOnParNode().
void PHParameters::Print (Option_t * option = "") const override
Definition at line 140 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 140 of file PHParameters.cc
References m_Detector, printdouble(), printint(), and printstring().
Referenced by CaloCalibration::InitRun(), CaloTemplateFit::InitRun(), PHG4TrackFastSimEval::InitRun(), G4Example02Detector::Print(), G4Example03Detector::Print(), PHG4TpcEndCapDetector::Print(), PHG4MicromegasDetector::Print(), PHParameterInterface::Print(), PHG4OuterHcalSubsystem::Print(), PHG4OHCalSubsystem::Print(), PHG4InnerHcalSubsystem::Print(), PHG4IHCalSubsystem::Print(), PHG4TpcSubsystem::Print(), PHG4Prototype2OuterHcalSubsystem::Print(), PHG4BeamlineMagnetSubsystem::Print(), PHG4Prototype2InnerHcalSubsystem::Print(), PHG4Prototype3InnerHcalSubsystem::Print(), BeamLineMagnetSubsystem::Print(), PHG4CylinderSubsystem::Print(), PHG4SpacalPrototype4Subsystem::Print(), PHG4SpacalPrototypeSubsystem::Print(), PHG4GDMLSubsystem::Print(), PHG4BbcSubsystem::Print(), EventInfoSummary::process_event(), RunInfoUnpackPRDF::process_event(), and MvtxRunInfoUnpackPRDF::process_event().
void PHParameters::printdouble () const
Definition at line 181 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 181 of file PHParameters.cc
References m_DoubleParMap.
Referenced by Print(), and PHParameterContainerInterface::set_double_param().
void PHParameters::printint () const
Definition at line 97 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 97 of file PHParameters.cc
References m_IntParMap.
Referenced by Print(), and PHParameterContainerInterface::set_int_param().
void PHParameters::printstring () const
Definition at line 223 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 223 of file PHParameters.cc
References m_StringParMap.
Referenced by Print(), and PHParameterContainerInterface::set_string_param().
int PHParameters::ReadFromCDB (const std::string & domain)
Definition at line 503 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 503 of file PHParameters.cc
References f, FillFrom(), CDBInterface::getUrl(), CDBInterface::instance(), and summary::url.
Referenced by CEMC_Towers(), Centrality(), and PHG4DetectorSubsystem::ReadParamsFromCDB().
int PHParameters::ReadFromCDBFile (const std::string & name)
Definition at line 668 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 668 of file PHParameters.cc
References f, and FillFrom().
int PHParameters::ReadFromDB ()
Definition at line 469 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 469 of file PHParameters.cc
References PdbApplication::abort(), PdbBankManager::fetchBank(), FillFrom(), PdbBankManager::getApplication(), PdbBankManager::instance(), m_Detector, PHWHERE, PdbApplication::startRead(), and Acts::Test::transform.
Referenced by PHG4DetectorSubsystem::ReadParamsFromDB().
int PHParameters::ReadFromDB (const std::string & name, const int layer)
Definition at line 436 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 436 of file PHParameters.cc
References PdbApplication::abort(), PdbBankManager::fetchBank(), FillFrom(), PdbBankManager::getApplication(), PdbBankManager::instance(), PHWHERE, PdbApplication::startRead(), and Acts::Test::transform.
int PHParameters::ReadFromFile (const std::string & name, const std::string & extension, const std::string & dir = ".") inline
simple read without super detector and layer structures
Definition at line 84 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 84 of file PHParameters.h
Referenced by CEMC_Towers(), Centrality(), Fun4All(), Fun4All_EMJetVal(), Fun4All_G4_sPHENIX(), Fun4All_JetBkgd(), Fun4All_JetNconst(), Fun4All_JetRhoMedian(), Fun4All_JetSeedCount(), Fun4All_JetSub(), Fun4All_JetVal(), Fun4All_PRDF(), Fun4All_RhoFluct(), Fun4All_RTrack(), Fun4All_TestBeam(), Fun4All_UE_v2_Psi2(), G4_HIJetReco(), PHG4InttDeadMapLoader::InitRun(), and PHG4DetectorSubsystem::ReadParamsFromFile().
int PHParameters::ReadFromFile (const std::string & name, const std::string & extension, const int layer, const int issuper, const std::string & dir = ".")
Fully fledged read.
Definition at line 575 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 575 of file PHParameters.cc
References assert, ConvertStringToUint(), f, FillFrom(), INTTVtxZ::fname, PdbParameterMap::get_hash(), PdbBankID::getInternalValue(), PdbParameterMapContainer::GetParameters(), i, path, and Acts::Test::transform.
void PHParameters::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 59 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 59 of file PHParameters.cc
References m_DoubleParMap, m_IntParMap, and m_StringParMap.
void PHParameters::SaveToNodeTree (PHCompositeNode * topNode, const std::string & nodename)
Definition at line 323 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 323 of file PHParameters.cc
References CopyToPdbParameterMap(), and PdbParameterMap::Reset().
Referenced by CaloCalibration::CreateNodeTree(), CaloTemplateFit::CreateNodeTree(), PHG4DetectorSubsystem::InitRun(), RunInfoUnpackPRDF::process_event(), EventInfoSummary::process_event(), MvtxRunInfoUnpackPRDF::process_event(), and PHParameterInterface::SaveToNodeTree().
void PHParameters::SaveToNodeTree (PHCompositeNode * topNode, const std::string & nodename, const int layer)
Definition at line 354 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 354 of file PHParameters.cc
References PdbParameterMapContainer::AddPdbParameterMap(), CopyToPdbParameterMap(), PdbParameterMapContainer::GetParametersToModify(), and PdbParameterMap::Reset().
void PHParameters::set_double_param (const std::string & name, const double dval)
Definition at line 107 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 107 of file PHParameters.cc
References m_DoubleParMap, and perf_headwind::name.
Referenced by PHG4InnerHcalDetector::ConstructHcalSingleScintillators(), DrawEcal_BlockCalibration(), Fun4All_PRDF(), Fun4All_TestBeam(), PHParameterInterface::InitializeParameters(), PHG4DetectorGroupSubsystem::InitializeParameters(), PHG4DetectorSubsystem::InitializeParameters(), PHG4CylinderSubsystem::InitRunSubsystem(), EventInfoSummary::process_event(), RunInfoUnpackPRDF::process_event(), PHParameterContainerInterface::set_default_double_param(), PHParameterContainerInterface::set_double_param(), CaloCalibration::SetDefaultParameters(), CaloTemplateFit::SetDefaultParameters(), PHG4OuterHcalDetector::SetTiltViaNcross(), PHG4InnerHcalDetector::SetTiltViaNcross(), PHParameterInterface::UpdateParametersWithMacro(), PHParameterContainerInterface::UpdateParametersWithMacro(), PHG4DetectorGroupSubsystem::UpdateParametersWithMacro(), and PHG4DetectorSubsystem::UpdateParametersWithMacro().
void PHParameters::set_int_param (const std::string & name, const int ival)
Definition at line 66 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 66 of file PHParameters.cc
References m_IntParMap, and perf_headwind::name.
Referenced by DrawEcal_BlockCalibration(), Fun4All_PRDF(), Fun4All_TestBeam(), PHParameterInterface::InitializeParameters(), PHG4DetectorGroupSubsystem::InitializeParameters(), PHG4DetectorSubsystem::InitializeParameters(), PHG4CylinderSubsystem::InitRunSubsystem(), PHG4InnerHcalDetector::PHG4InnerHcalDetector(), EventInfoSummary::process_event(), RunInfoUnpackPRDF::process_event(), MvtxRunInfoUnpackPRDF::process_event(), PHParameterContainerInterface::set_default_int_param(), PHParameterContainerInterface::set_int_param(), CaloCalibration::SetDefaultParameters(), CaloTemplateFit::SetDefaultParameters(), PHG4OuterHcalDetector::SetTiltViaNcross(), PHG4InnerHcalDetector::SetTiltViaNcross(), PHParameterInterface::UpdateParametersWithMacro(), PHParameterContainerInterface::UpdateParametersWithMacro(), PHG4DetectorGroupSubsystem::UpdateParametersWithMacro(), and PHG4DetectorSubsystem::UpdateParametersWithMacro().
void PHParameters::set_name (const std::string & name) inline
Definition at line 61 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 61 of file PHParameters.h
References m_Detector, and perf_headwind::name.
Referenced by RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), Fun4All_PRDF(), Fun4All_TestBeam(), PHG4DetectorSubsystem::Init(), and PHParameterInterface::set_paramname().
void PHParameters::set_string_param (const std::string & name, const std::string & str)
Definition at line 191 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 191 of file PHParameters.cc
References m_StringParMap, perf_headwind::name, and str.
Referenced by DrawEcal_BlockCalibration(), PHParameterInterface::InitializeParameters(), PHG4DetectorGroupSubsystem::InitializeParameters(), PHG4DetectorSubsystem::InitializeParameters(), PHG4CylinderSubsystem::InitRunSubsystem(), MvtxRunInfoUnpackPRDF::process_event(), PHParameterContainerInterface::set_default_string_param(), PHParameterContainerInterface::set_string_param(), PHParameterInterface::UpdateParametersWithMacro(), PHParameterContainerInterface::UpdateParametersWithMacro(), PHG4DetectorGroupSubsystem::UpdateParametersWithMacro(), and PHG4DetectorSubsystem::UpdateParametersWithMacro().
void PHParameters::UpdateNodeTree (PHCompositeNode * topNode, const std::string & nodename)
Definition at line 341 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 341 of file PHParameters.cc
References CopyToPdbParameterMap(), and PHWHERE.
Referenced by PHG4DetectorSubsystem::InitRun().
void PHParameters::UpdateNodeTree (PHCompositeNode * topNode, const std::string & nodename, const int layer)
Definition at line 379 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 379 of file PHParameters.cc
References CopyToPdbParameterMap(), PdbParameterMapContainer::GetParametersToModify(), and PHWHERE.
int PHParameters::WriteToCDBFile (const std::string & filename)
Definition at line 525 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 525 of file PHParameters.cc
References CopyToPdbParameterMap(), and f.
int PHParameters::WriteToDB ()
Definition at line 399 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 399 of file PHParameters.cc
References PdbApplication::abort(), PdbApplication::commit(), CopyToPdbParameterMap(), PdbBankManager::createBank(), PdbBankManager::getApplication(), PdbBankManager::instance(), m_Detector, PHWHERE, PdbCalBank::setLength(), PdbApplication::startUpdate(), and Acts::Test::transform.
Referenced by PHG4DetectorSubsystem::SaveParamsToDB().
int PHParameters::WriteToFile (const std::string & extension, const std::string & dir = ".")
Definition at line 536 of file PHParameters.cc.
View newest version in sPHENIX GitHub at line 536 of file PHParameters.cc
References CopyToPdbParameterMap(), extension, f, INTTVtxZ::fname, PdbBankID::getInternalValue(), PHTimeStamp::getTics(), m_Detector, Acts::Test::time, and Acts::Test::transform.
Referenced by DrawEcal_BlockCalibration(), and PHG4DetectorSubsystem::SaveParamsToFile().
Member Data Documentation
std::string PHParameters::m_Detector private
Definition at line 99 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 99 of file PHParameters.h
Referenced by Name(), Print(), ReadFromDB(), set_name(), WriteToDB(), and WriteToFile().
dMap PHParameters::m_DoubleParMap private
Definition at line 100 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 100 of file PHParameters.h
Referenced by CopyToPdbParameterMap(), exist_double_param(), FillFrom(), get_all_double_params(), get_double_param(), get_hash(), printdouble(), Reset(), set_double_param(), and ~PHParameters().
iMap PHParameters::m_IntParMap private
Definition at line 101 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 101 of file PHParameters.h
Referenced by CopyToPdbParameterMap(), exist_int_param(), FillFrom(), get_all_int_params(), get_hash(), get_int_param(), printint(), Reset(), set_int_param(), and ~PHParameters().
strMap PHParameters::m_StringParMap private
Definition at line 102 of file PHParameters.h.
View newest version in sPHENIX GitHub at line 102 of file PHParameters.h
Referenced by CopyToPdbParameterMap(), exist_string_param(), FillFrom(), get_all_string_params(), get_hash(), get_string_param(), printstring(), Reset(), set_string_param(), and ~PHParameters().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/PHParameter/PHParameters.h
coresoftware/blob/master/offline/database/PHParameter/PHParameters.cc