Analysis Software: analysis/blob/master/dNdEta_Run2023/macros/Fun4All_G4_sPHENIX.C File Reference
Fun4All_G4_sPHENIX.C File Reference
#include <GlobalVariables.C>
#include <G4Setup_sPHENIX.C>
#include <G4_Centrality.C>
#include <G4_Input.C>
#include <Trkr_Clustering.C>
#include <Trkr_RecoInit.C>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <g4centrality/PHG4CentralityReco.h>
#include <trackreco/PHTruthVertexing.h>
#include <dndetaintt/dNdEtaINTT.h>
#include <phool/recoConsts.h>
Macros
#define MACRO_FUN4ALLG4SPHENIX_C
Functions
int Fun4All_G4_sPHENIX (const bool rundata=true, const string generator="HIJING", const int nEvents=-1, const string &outputFile="dataNtuple.root", const int process=0)
Macro Definition Documentation
#define MACRO_FUN4ALLG4SPHENIX_C
Definition at line 2 of file Fun4All_G4_sPHENIX.C.
View newest version in sPHENIX GitHub at line 2 of file Fun4All_G4_sPHENIX.C
Function Documentation
int Fun4All_G4_sPHENIX (const bool rundata = true, const string generator = "HIJING", const int nEvents = -1, const string & outputFile = "dataNtuple.root", const int process = 0)
Definition at line 29 of file Fun4All_G4_sPHENIX.C.
View newest version in sPHENIX GitHub at line 29 of file Fun4All_G4_sPHENIX.C
References PHTruthVertexing::associate_tracks(), Enable::CDB, Data, Fun4AllServer::End(), INPUTREADHITS::filename, G4Init(), G4Setup(), Fatras::Test::generator, PHG4CentralityReco::GetCalibrationParameters(), dNdEtaINTT::GetCentrality(), dNdEtaINTT::GetRecoCluster(), dNdEtaINTT::GetTrkrHit(), dNdEtaINTT::GetTruthPV(), CDB::global_tag, infile, InputManagers(), recoConsts::instance(), Fun4AllServer::instance(), Enable::INTT, Intt_Clustering(), Enable::MBD, Enable::MICROMEGAS, Enable::MVTX, Enable::PIPE, tgeo-response2json::process(), PHParameters::ReadFromFile(), Input::READHITS, Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), rundata(), PHFlag::set_StringFlag(), PHFlag::set_uint64Flag(), Acts::Test::skip, Fun4AllServer::skip(), CDB::timestamp, Enable::TPC, TrackingInit(), Enable::VERBOSITY, Fun4AllBase::Verbosity(), and Input::VERBOSITY.
Referenced by main().