Analysis Software: ResonanceJetTagging Class Reference
ResonanceJetTagging Class Reference
Definition of this analysis module class.
#include <coresoftware/blob/master/offline/packages/ResonanceJetTagging/ResonanceJetTagging.h>
Public Types
enum ALGO { ANTIKT = 0, KT = 1, CAMBRIDGE = 2 }
enum RECOMB {
E_SCHEME = 0, PT_SCHEME = 1, PT2_SCHEME = 2, ET_SCHEME = 3,
ET2_SCHEME = 4
}
enum TAG {
D0 = 0, D0TOK3PI = 1, DPLUS = 2, DSTAR = 3,
JPSY = 4, K0 = 5, GAMMA = 6, ELECTRON = 7,
LAMBDAC = 8
}
Public Member Functions
ResonanceJetTagging (const std::string &name="ResonanceJetTagging", const TAG tag=TAG::D0, const std::string &KFparticle_Container_name="")
Constructor.
virtual ~ResonanceJetTagging ()
int Init (PHCompositeNode *)
SubsysReco initialize processing method.
int process_event (PHCompositeNode *)
SubsysReco event processing method.
int End (PHCompositeNode *)
SubsysReco end processing method.
void setParticleFlowEtaAcc (double etamin, double etamax)
void setParticleFlowMinEta (double etamin)
void setParticleFlowMaxEta (double etamax)
double getParticleFlowMinEta ()
double getParticleFlowMaxEta ()
void setTrackPtAcc (double ptmin, double ptmax)
void setTrackMinPt (double ptmin)
void setTrackMaxPt (double ptmax)
double getTrackMinPt ()
double getTrackMaxPt ()
void setTrackEtaAcc (double etamin, double etamax)
void setTrackMinEta (double etamin)
void setTrackMaxEta (double etamax)
double getTrackMinEta ()
double getTrackMaxEta ()
void setEMCalClusterPtAcc (double ptmin, double ptmax)
void setEMCalClusterMinPt (double ptmin)
void setEMCalClusterMaxPt (double ptmax)
double getEMCalClusterMinPt ()
double getEMCalClusterMaxPt ()
void setEMCalClusterEtaAcc (double etamin, double etamax)
void setEMCalClusterMinEta (double etamin)
void setEMCalClusterMaxEta (double etamax)
double getEMCalClusterMinEta ()
double getEMCalClusterMaxEta ()
void setHCalClusterPtAcc (double ptmin, double ptmax)
void setHCalClusterMinPt (double ptmin)
void setHCalClusterMaxPt (double ptmax)
double getHCalClusterMinPt ()
double getHCalClusterMaxPt ()
void setHCalClusterEtaAcc (double etamin, double etamax)
void setHCalClusterMinEta (double etamin)
void setHCalClusterMaxEta (double etamax)
double getHCalClusterMinEta ()
double getHCalClusterMaxEta ()
void setAddParticleFlow (bool b)
bool getAddParticleFlow ()
void setAddTracks (bool b)
bool getAddTracks ()
void setAddEMCalClusters (bool b)
bool getAddEMCalClusters ()
void setAddHCalClusters (bool b)
bool getAddHCalClusters ()
void setR (double r)
double getR (double)
void setJetAlgo (ALGO jetalgo)
fastjet::JetAlgorithm getJetAlgo ()
void setRecombScheme (RECOMB recomb_scheme)
fastjet::RecombinationScheme getRecombScheme ()
void setJetParameters (double r, ALGO jetalgo, RECOMB recomb_scheme)
void setJetContainerName (const std::string &n)
std::string getJetContainerName ()
void setDoRecunstructed (bool b)
bool getDoRecunstructed ()
void setDoTruth (bool b)
bool getDoTruth ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int tagHFHadronic (PHCompositeNode *topNode)
Methods for grabbing the data.
void findTaggedJets (PHCompositeNode *topNode, PHG4Particlev2 *Tag, const std::vector< PHG4Particlev2 * > &TagDecays)
void addParticleFlow (PHCompositeNode *topNode, std::vector< fastjet::PseudoJet > &particles, const std::vector< PHG4Particlev2 * > &TagDecays, std::map< int, std::pair< Jet::SRC, int >> &fjMap)
void addTracks (PHCompositeNode *topNode, std::vector< fastjet::PseudoJet > &particles, const std::vector< PHG4Particlev2 * > &TagDecays, std::map< int, std::pair< Jet::SRC, int >> &fjMap)
void addClusters (PHCompositeNode *topNode, std::vector< fastjet::PseudoJet > &particles, std::map< int, std::pair< Jet::SRC, int >> &fjMap)
void findMCTaggedJets (PHCompositeNode *topNode)
bool isAcceptableParticleFlow (ParticleFlowElement *pfPart)
bool isAcceptableTrack (SvtxTrack *track)
bool isAcceptableEMCalCluster (CLHEP::Hep3Vector &E_vec_cluster)
bool isAcceptableHCalCluster (CLHEP::Hep3Vector &E_vec_cluster)
bool isDecay (HepMC::GenParticle *particle, const std::vector< PHG4Particlev2 * > &decays)
bool isDecay (SvtxTrack *track, const std::vector< PHG4Particlev2 * > &decays)
int createJetNode (PHCompositeNode *topNode)
Private Attributes
std::string m_jetcontainer_name
String to contain the jetcontainer name containing the tagged jets.
double m_particleflow_mineta
Particle Flow selection and acceptance.
double m_particleflow_maxeta
double m_track_minpt
Track selection and acceptance.
double m_track_maxpt
double m_track_mineta
double m_track_maxeta
double m_EMCal_cluster_minpt
EMCal Cluster selection and acceptance.
double m_EMCal_cluster_maxpt
double m_EMCal_cluster_mineta
double m_EMCal_cluster_maxeta
double m_HCal_cluster_minpt
HCal Cluster selection and acceptance.
double m_HCal_cluster_maxpt
double m_HCal_cluster_mineta
double m_HCal_cluster_maxeta
bool m_add_particleflow
Add Tracks and Clusters.
bool m_add_tracks
bool m_add_EMCal_clusters
bool m_add_HCal_clusters
double m_jetr
fastjet::JetAlgorithm m_jetalgo
fastjet::RecombinationScheme m_recomb_scheme
JetContainerv1 * m_taggedJetContainer = nullptr
JetContainerv1 * m_truth_taggedJetContainer = nullptr
int m_tag_pdg
unsigned int m_jet_id = 0
unsigned int m_truth_jet_id = 0
bool m_dorec
bool m_dotruth
int m_nDaughters
TAG m_tag_particle
std::string m_KFparticle_name
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition of this analysis module class.
Definition at line 37 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 37 of file ResonanceJetTagging.h
Member Enumeration Documentation
enum ResonanceJetTagging::ALGO
Enumerator:
ANTIKT
KT
CAMBRIDGE
Definition at line 40 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 40 of file ResonanceJetTagging.h
enum ResonanceJetTagging::RECOMB
Enumerator:
E_SCHEME
PT_SCHEME
PT2_SCHEME
ET_SCHEME
ET2_SCHEME
Definition at line 47 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 47 of file ResonanceJetTagging.h
enum ResonanceJetTagging::TAG
Enumerator:
D0
D0TOK3PI
DPLUS
DSTAR
JPSY
K0
GAMMA
ELECTRON
LAMBDAC
Definition at line 56 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 56 of file ResonanceJetTagging.h
Constructor & Destructor Documentation
ResonanceJetTagging::ResonanceJetTagging (const std::string & name = "ResonanceJetTagging", const TAG tag = TAG::D0, const std::string & KFparticle_Container_name = "")
Constructor.
ResonanceJetTagging is a class developed to reconstruct jets containing a D-meson The class can be adapted to tag jets using any kind of particle Author: Antonio Silva (anton.nosp@m.io.s.nosp@m.pheni.nosp@m.x@gm.nosp@m.ail.c.nosp@m.om) Contributor: Jakub Kvapil (jakub.nosp@m..kva.nosp@m.pil@c.nosp@m.ern..nosp@m.ch) Constructor of module
Definition at line 79 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 79 of file ResonanceJetTagging.cc
References m_nDaughters, m_tag_particle, and m_tag_pdg.
ResonanceJetTagging::~ResonanceJetTagging () virtual
Destructor of module
Definition at line 152 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 152 of file ResonanceJetTagging.cc
Member Function Documentation
void ResonanceJetTagging::addClusters (PHCompositeNode * topNode, std::vector< fastjet::PseudoJet > & particles, std::map< int, std::pair< Jet::SRC, int >> & fjMap) private
Loop over the EMCal clusters
Loop over the EMCal clusters
Get this cluster
Loop over the EMCal clusters
Get this cluster
Get cluster characteristics This helper class determines the photon characteristics depending on the vertex position This is important for e.g. eta determination and E_T determination
Definition at line 452 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 452 of file ResonanceJetTagging.cc
References assert, GlobalVertexMap::begin(), Enable::CEMC_CLUSTER, GlobalVertexMap::empty(), RawCluster::get_id(), GlobalVertex::get_x(), GlobalVertex::get_y(), GlobalVertex::get_z(), RawClusterContainer::getClusters(), RawClusterUtility::GetECoreVec(), isAcceptableEMCalCluster(), isAcceptableHCalCluster(), m_add_EMCal_clusters, m_add_HCal_clusters, and PHWHERE.
Referenced by findTaggedJets().
void ResonanceJetTagging::addParticleFlow (PHCompositeNode * topNode, std::vector< fastjet::PseudoJet > & particles, const std::vector< PHG4Particlev2 * > & TagDecays, std::map< int, std::pair< Jet::SRC, int >> & fjMap) private
Definition at line 337 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 337 of file ResonanceJetTagging.cc
References ParticleFlowElement::get_e(), ParticleFlowElement::get_id(), ParticleFlowElement::get_px(), ParticleFlowElement::get_py(), ParticleFlowElement::get_pz(), ParticleFlowElement::get_track(), ParticleFlowElementContainer::getParticleFlowElements(), isAcceptableParticleFlow(), isDecay(), and PHWHERE.
Referenced by findTaggedJets().
void ResonanceJetTagging::addTracks (PHCompositeNode * topNode, std::vector< fastjet::PseudoJet > & particles, const std::vector< PHG4Particlev2 * > & TagDecays, std::map< int, std::pair< Jet::SRC, int >> & fjMap) private
Definition at line 399 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 399 of file ResonanceJetTagging.cc
References SvtxTrack::get_id(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), isAcceptableTrack(), isDecay(), and PHWHERE.
Referenced by findTaggedJets().
int ResonanceJetTagging::createJetNode (PHCompositeNode * topNode) private
Definition at line 853 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 853 of file ResonanceJetTagging.cc
References PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_jetcontainer_name, m_taggedJetContainer, m_truth_taggedJetContainer, and Acts::Test::pos.
Referenced by Init().
int ResonanceJetTagging::End (PHCompositeNode *) virtual
SubsysReco end processing method.
End the module and finish any data collection. Clean up any remaining loose ends
Reimplemented from SubsysReco.
Definition at line 207 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 207 of file ResonanceJetTagging.cc
References Fun4AllBase::Verbosity().
void ResonanceJetTagging::findMCTaggedJets (PHCompositeNode * topNode) private
If the node was not properly put on the tree, return
Definition at line 678 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 678 of file ResonanceJetTagging.cc
References JetContainerv1::add_jet(), Best, Jet::clear_comp(), mvtx_utils::comp(), PHHepMCGenEventMap::get(), PHG4Particle::get_barcode(), PHG4Particle::get_parent_id(), PHG4Particle::get_pid(), PHHepMCGenEvent::getEvent(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetParticleRange(), Jet::insert_comp(), it, m_EMCal_cluster_maxpt, m_EMCal_cluster_minpt, m_jetalgo, m_jetr, m_recomb_scheme, m_tag_pdg, m_track_maxeta, m_track_maxpt, m_track_mineta, m_track_minpt, m_truth_jet_id, m_truth_taggedJetContainer, merge_hashes::p, particles, PHWHERE, Jet::set_e(), Jet::set_id(), Jet::set_px(), Jet::set_py(), and Jet::set_pz().
Referenced by tagHFHadronic().
void ResonanceJetTagging::findTaggedJets (PHCompositeNode * topNode, PHG4Particlev2 * Tag, const std::vector< PHG4Particlev2 * > & TagDecays) private
Definition at line 275 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 275 of file ResonanceJetTagging.cc
References JetContainerv1::add_jet(), addClusters(), addParticleFlow(), addTracks(), Best, Jet::clear_comp(), mvtx_utils::comp(), PHG4Particlev1::get_barcode(), PHG4Particlev2::get_e(), PHG4Particlev1::get_px(), PHG4Particlev1::get_py(), PHG4Particlev1::get_pz(), Jet::insert_comp(), m_add_EMCal_clusters, m_add_HCal_clusters, m_add_particleflow, m_add_tracks, m_jet_id, m_jetalgo, m_jetr, m_recomb_scheme, m_taggedJetContainer, particles, Jet::set_e(), Jet::set_id(), Jet::set_px(), Jet::set_py(), and Jet::set_pz().
Referenced by tagHFHadronic().
bool ResonanceJetTagging::getAddEMCalClusters () inline
Definition at line 164 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 164 of file ResonanceJetTagging.h
References m_add_EMCal_clusters.
bool ResonanceJetTagging::getAddHCalClusters () inline
Definition at line 166 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 166 of file ResonanceJetTagging.h
References m_add_HCal_clusters.
bool ResonanceJetTagging::getAddParticleFlow () inline
Definition at line 160 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 160 of file ResonanceJetTagging.h
References m_add_particleflow.
bool ResonanceJetTagging::getAddTracks () inline
Definition at line 162 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 162 of file ResonanceJetTagging.h
References m_add_tracks.
bool ResonanceJetTagging::getDoRecunstructed () inline
Definition at line 218 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 218 of file ResonanceJetTagging.h
References m_dorec.
bool ResonanceJetTagging::getDoTruth () inline
Definition at line 220 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 220 of file ResonanceJetTagging.h
References m_dotruth.
double ResonanceJetTagging::getEMCalClusterMaxEta () inline
Definition at line 135 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 135 of file ResonanceJetTagging.h
References m_EMCal_cluster_maxeta.
double ResonanceJetTagging::getEMCalClusterMaxPt () inline
Definition at line 125 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 125 of file ResonanceJetTagging.h
References m_EMCal_cluster_maxpt.
double ResonanceJetTagging::getEMCalClusterMinEta () inline
Definition at line 134 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 134 of file ResonanceJetTagging.h
References m_EMCal_cluster_mineta.
double ResonanceJetTagging::getEMCalClusterMinPt () inline
Definition at line 124 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 124 of file ResonanceJetTagging.h
References m_EMCal_cluster_minpt.
double ResonanceJetTagging::getHCalClusterMaxEta () inline
Definition at line 156 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 156 of file ResonanceJetTagging.h
References m_HCal_cluster_maxeta.
double ResonanceJetTagging::getHCalClusterMaxPt () inline
Definition at line 146 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 146 of file ResonanceJetTagging.h
References m_HCal_cluster_maxpt.
double ResonanceJetTagging::getHCalClusterMinEta () inline
Definition at line 155 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 155 of file ResonanceJetTagging.h
References m_HCal_cluster_mineta.
double ResonanceJetTagging::getHCalClusterMinPt () inline
Definition at line 145 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 145 of file ResonanceJetTagging.h
References m_HCal_cluster_minpt.
fastjet::JetAlgorithm ResonanceJetTagging::getJetAlgo () inline
Definition at line 186 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 186 of file ResonanceJetTagging.h
References m_jetalgo.
std::string ResonanceJetTagging::getJetContainerName () inline
Definition at line 216 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 216 of file ResonanceJetTagging.h
References m_jetcontainer_name.
double ResonanceJetTagging::getParticleFlowMaxEta () inline
Definition at line 93 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 93 of file ResonanceJetTagging.h
References m_particleflow_maxeta.
double ResonanceJetTagging::getParticleFlowMinEta () inline
Definition at line 92 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 92 of file ResonanceJetTagging.h
References m_particleflow_mineta.
double ResonanceJetTagging::getR (double) inline
Definition at line 170 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 170 of file ResonanceJetTagging.h
References m_jetr.
fastjet::RecombinationScheme ResonanceJetTagging::getRecombScheme () inline
Definition at line 208 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 208 of file ResonanceJetTagging.h
References m_recomb_scheme.
double ResonanceJetTagging::getTrackMaxEta () inline
Definition at line 114 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 114 of file ResonanceJetTagging.h
References m_track_maxeta.
double ResonanceJetTagging::getTrackMaxPt () inline
Definition at line 104 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 104 of file ResonanceJetTagging.h
References m_track_maxpt.
double ResonanceJetTagging::getTrackMinEta () inline
Definition at line 113 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 113 of file ResonanceJetTagging.h
References m_track_mineta.
double ResonanceJetTagging::getTrackMinPt () inline
Definition at line 103 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 103 of file ResonanceJetTagging.h
References m_track_minpt.
int ResonanceJetTagging::Init (PHCompositeNode * topNode) virtual
SubsysReco initialize processing method.
Initialize the module and prepare looping over events
Reimplemented from SubsysReco.
Definition at line 160 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 160 of file ResonanceJetTagging.cc
References createJetNode(), and Fun4AllBase::Verbosity().
bool ResonanceJetTagging::isAcceptableEMCalCluster (CLHEP::Hep3Vector & E_vec_cluster) private
Definition at line 626 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 626 of file ResonanceJetTagging.cc
References m_EMCal_cluster_maxeta, m_EMCal_cluster_maxpt, m_EMCal_cluster_mineta, and m_EMCal_cluster_minpt.
Referenced by addClusters().
bool ResonanceJetTagging::isAcceptableHCalCluster (CLHEP::Hep3Vector & E_vec_cluster) private
Definition at line 640 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 640 of file ResonanceJetTagging.cc
References m_HCal_cluster_maxeta, m_HCal_cluster_maxpt, m_HCal_cluster_mineta, and m_HCal_cluster_minpt.
Referenced by addClusters().
bool ResonanceJetTagging::isAcceptableParticleFlow (ParticleFlowElement * pfPart) private
Definition at line 389 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 389 of file ResonanceJetTagging.cc
References ParticleFlowElement::get_eta(), m_particleflow_maxeta, and m_particleflow_mineta.
Referenced by addParticleFlow().
bool ResonanceJetTagging::isAcceptableTrack (SvtxTrack * track) private
Definition at line 438 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 438 of file ResonanceJetTagging.cc
References SvtxTrack::get_eta(), SvtxTrack::get_pt(), m_track_maxeta, m_track_maxpt, m_track_mineta, and m_track_minpt.
Referenced by addTracks().
bool ResonanceJetTagging::isDecay (HepMC::GenParticle * particle, const std::vector< PHG4Particlev2 * > & decays) private
Definition at line 666 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 666 of file ResonanceJetTagging.cc
Referenced by addParticleFlow(), and addTracks().
bool ResonanceJetTagging::isDecay (SvtxTrack * track, const std::vector< PHG4Particlev2 * > & decays) private
Definition at line 654 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 654 of file ResonanceJetTagging.cc
References SvtxTrack::get_id().
int ResonanceJetTagging::process_event (PHCompositeNode * topNode) virtual
SubsysReco event processing method.
Main workhorse function where each event is looped over and data from each event is collected from the node tree for analysis
Reimplemented from SubsysReco.
Definition at line 176 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 176 of file ResonanceJetTagging.cc
References Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, m_nDaughters, m_tag_particle, and tagHFHadronic().
void ResonanceJetTagging::setAddEMCalClusters (bool b) inline
Definition at line 163 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 163 of file ResonanceJetTagging.h
References KFPMath::b, and m_add_EMCal_clusters.
void ResonanceJetTagging::setAddHCalClusters (bool b) inline
Definition at line 165 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 165 of file ResonanceJetTagging.h
References KFPMath::b, and m_add_HCal_clusters.
void ResonanceJetTagging::setAddParticleFlow (bool b) inline
Definition at line 159 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 159 of file ResonanceJetTagging.h
References KFPMath::b, and m_add_particleflow.
void ResonanceJetTagging::setAddTracks (bool b) inline
Definition at line 161 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 161 of file ResonanceJetTagging.h
References KFPMath::b, and m_add_tracks.
void ResonanceJetTagging::setDoRecunstructed (bool b) inline
Definition at line 217 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 217 of file ResonanceJetTagging.h
References KFPMath::b, and m_dorec.
void ResonanceJetTagging::setDoTruth (bool b) inline
Definition at line 219 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 219 of file ResonanceJetTagging.h
References KFPMath::b, and m_dotruth.
void ResonanceJetTagging::setEMCalClusterEtaAcc (double etamin, double etamax) inline
Definition at line 127 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 127 of file ResonanceJetTagging.h
References etamax, etamin, m_EMCal_cluster_maxeta, and m_EMCal_cluster_mineta.
void ResonanceJetTagging::setEMCalClusterMaxEta (double etamax) inline
Definition at line 133 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 133 of file ResonanceJetTagging.h
References etamax, and m_EMCal_cluster_maxeta.
void ResonanceJetTagging::setEMCalClusterMaxPt (double ptmax) inline
Definition at line 123 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 123 of file ResonanceJetTagging.h
References m_EMCal_cluster_maxpt.
void ResonanceJetTagging::setEMCalClusterMinEta (double etamin) inline
Definition at line 132 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 132 of file ResonanceJetTagging.h
References etamin, and m_EMCal_cluster_mineta.
void ResonanceJetTagging::setEMCalClusterMinPt (double ptmin) inline
Definition at line 122 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 122 of file ResonanceJetTagging.h
References m_EMCal_cluster_minpt.
void ResonanceJetTagging::setEMCalClusterPtAcc (double ptmin, double ptmax) inline
Definition at line 117 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 117 of file ResonanceJetTagging.h
References m_EMCal_cluster_maxpt, and m_EMCal_cluster_minpt.
void ResonanceJetTagging::setHCalClusterEtaAcc (double etamin, double etamax) inline
Definition at line 148 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 148 of file ResonanceJetTagging.h
References etamax, etamin, m_HCal_cluster_maxeta, and m_HCal_cluster_mineta.
void ResonanceJetTagging::setHCalClusterMaxEta (double etamax) inline
Definition at line 154 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 154 of file ResonanceJetTagging.h
References etamax, and m_HCal_cluster_maxeta.
void ResonanceJetTagging::setHCalClusterMaxPt (double ptmax) inline
Definition at line 144 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 144 of file ResonanceJetTagging.h
References m_HCal_cluster_maxpt.
void ResonanceJetTagging::setHCalClusterMinEta (double etamin) inline
Definition at line 153 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 153 of file ResonanceJetTagging.h
References etamin, and m_HCal_cluster_mineta.
void ResonanceJetTagging::setHCalClusterMinPt (double ptmin) inline
Definition at line 143 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 143 of file ResonanceJetTagging.h
References m_HCal_cluster_minpt.
void ResonanceJetTagging::setHCalClusterPtAcc (double ptmin, double ptmax) inline
Definition at line 138 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 138 of file ResonanceJetTagging.h
References m_HCal_cluster_maxpt, and m_HCal_cluster_minpt.
void ResonanceJetTagging::setJetAlgo (ALGO jetalgo) inline
Definition at line 171 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 171 of file ResonanceJetTagging.h
References antikt_algorithm, cambridge_algorithm, kt_algorithm, and m_jetalgo.
Referenced by setJetParameters().
void ResonanceJetTagging::setJetContainerName (const std::string & n) inline
Definition at line 215 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 215 of file ResonanceJetTagging.h
References m_jetcontainer_name, and n.
void ResonanceJetTagging::setJetParameters (double r, ALGO jetalgo, RECOMB recomb_scheme) inline
Definition at line 209 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 209 of file ResonanceJetTagging.h
References setJetAlgo(), setR(), and setRecombScheme().
void ResonanceJetTagging::setParticleFlowEtaAcc (double etamin, double etamax) inline
Definition at line 85 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 85 of file ResonanceJetTagging.h
References etamax, etamin, m_particleflow_maxeta, and m_particleflow_mineta.
void ResonanceJetTagging::setParticleFlowMaxEta (double etamax) inline
Definition at line 91 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 91 of file ResonanceJetTagging.h
References etamax, and m_particleflow_maxeta.
void ResonanceJetTagging::setParticleFlowMinEta (double etamin) inline
Definition at line 90 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 90 of file ResonanceJetTagging.h
References etamin, and m_particleflow_mineta.
void ResonanceJetTagging::setR (double r) inline
Definition at line 169 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 169 of file ResonanceJetTagging.h
References m_jetr, and physmon_track_finding_ttbar::r.
Referenced by setJetParameters().
void ResonanceJetTagging::setRecombScheme (RECOMB recomb_scheme) inline
Definition at line 187 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 187 of file ResonanceJetTagging.h
References E_scheme, Et2_scheme, Et_scheme, m_recomb_scheme, pt2_scheme, and pt_scheme.
Referenced by setJetParameters().
void ResonanceJetTagging::setTrackEtaAcc (double etamin, double etamax) inline
Definition at line 106 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 106 of file ResonanceJetTagging.h
References etamax, etamin, m_track_maxeta, and m_track_mineta.
void ResonanceJetTagging::setTrackMaxEta (double etamax) inline
Definition at line 112 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 112 of file ResonanceJetTagging.h
References etamax, and m_track_maxeta.
void ResonanceJetTagging::setTrackMaxPt (double ptmax) inline
Definition at line 102 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 102 of file ResonanceJetTagging.h
References m_track_maxpt.
void ResonanceJetTagging::setTrackMinEta (double etamin) inline
Definition at line 111 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 111 of file ResonanceJetTagging.h
References etamin, and m_track_mineta.
void ResonanceJetTagging::setTrackMinPt (double ptmin) inline
Definition at line 101 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 101 of file ResonanceJetTagging.h
References m_track_minpt.
void ResonanceJetTagging::setTrackPtAcc (double ptmin, double ptmax) inline
Definition at line 96 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 96 of file ResonanceJetTagging.h
References m_track_maxpt, and m_track_minpt.
int ResonanceJetTagging::tagHFHadronic (PHCompositeNode * topNode) private
Methods for grabbing the data.
Definition at line 217 of file ResonanceJetTagging.cc.
View newest version in sPHENIX GitHub at line 217 of file ResonanceJetTagging.cc
References Fun4AllReturnCodes::ABORTEVENT, KFParticle::E(), Fun4AllReturnCodes::EVENT_OK, findMCTaggedJets(), findTaggedJets(), KFParticle_Container::get(), KFParticleBase::GetPDG(), i, m_dorec, m_dotruth, m_jet_id, m_KFparticle_name, m_nDaughters, m_tag_pdg, KFParticle::Px(), KFParticle::Py(), KFParticle::Pz(), PHG4Particlev1::set_barcode(), PHG4Particlev2::set_e(), PHG4Particlev1::set_px(), PHG4Particlev1::set_py(), PHG4Particlev1::set_pz(), and KFParticle_Container::size().
Referenced by process_event().
Member Data Documentation
bool ResonanceJetTagging::m_add_EMCal_clusters private
Definition at line 251 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 251 of file ResonanceJetTagging.h
Referenced by addClusters(), findTaggedJets(), getAddEMCalClusters(), and setAddEMCalClusters().
bool ResonanceJetTagging::m_add_HCal_clusters private
Definition at line 252 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 252 of file ResonanceJetTagging.h
Referenced by addClusters(), findTaggedJets(), getAddHCalClusters(), and setAddHCalClusters().
bool ResonanceJetTagging::m_add_particleflow private
Add Tracks and Clusters.
Definition at line 249 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 249 of file ResonanceJetTagging.h
Referenced by findTaggedJets(), getAddParticleFlow(), and setAddParticleFlow().
bool ResonanceJetTagging::m_add_tracks private
Definition at line 250 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 250 of file ResonanceJetTagging.h
Referenced by findTaggedJets(), getAddTracks(), and setAddTracks().
bool ResonanceJetTagging::m_dorec private
Definition at line 265 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 265 of file ResonanceJetTagging.h
Referenced by getDoRecunstructed(), setDoRecunstructed(), and tagHFHadronic().
bool ResonanceJetTagging::m_dotruth private
Definition at line 266 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 266 of file ResonanceJetTagging.h
Referenced by getDoTruth(), setDoTruth(), and tagHFHadronic().
double ResonanceJetTagging::m_EMCal_cluster_maxeta private
Definition at line 240 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 240 of file ResonanceJetTagging.h
Referenced by getEMCalClusterMaxEta(), isAcceptableEMCalCluster(), setEMCalClusterEtaAcc(), and setEMCalClusterMaxEta().
double ResonanceJetTagging::m_EMCal_cluster_maxpt private
Definition at line 238 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 238 of file ResonanceJetTagging.h
Referenced by findMCTaggedJets(), getEMCalClusterMaxPt(), isAcceptableEMCalCluster(), setEMCalClusterMaxPt(), and setEMCalClusterPtAcc().
double ResonanceJetTagging::m_EMCal_cluster_mineta private
Definition at line 239 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 239 of file ResonanceJetTagging.h
Referenced by getEMCalClusterMinEta(), isAcceptableEMCalCluster(), setEMCalClusterEtaAcc(), and setEMCalClusterMinEta().
double ResonanceJetTagging::m_EMCal_cluster_minpt private
EMCal Cluster selection and acceptance.
Definition at line 237 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 237 of file ResonanceJetTagging.h
Referenced by findMCTaggedJets(), getEMCalClusterMinPt(), isAcceptableEMCalCluster(), setEMCalClusterMinPt(), and setEMCalClusterPtAcc().
double ResonanceJetTagging::m_HCal_cluster_maxeta private
Definition at line 246 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 246 of file ResonanceJetTagging.h
Referenced by getHCalClusterMaxEta(), isAcceptableHCalCluster(), setHCalClusterEtaAcc(), and setHCalClusterMaxEta().
double ResonanceJetTagging::m_HCal_cluster_maxpt private
Definition at line 244 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 244 of file ResonanceJetTagging.h
Referenced by getHCalClusterMaxPt(), isAcceptableHCalCluster(), setHCalClusterMaxPt(), and setHCalClusterPtAcc().
double ResonanceJetTagging::m_HCal_cluster_mineta private
Definition at line 245 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 245 of file ResonanceJetTagging.h
Referenced by getHCalClusterMinEta(), isAcceptableHCalCluster(), setHCalClusterEtaAcc(), and setHCalClusterMinEta().
double ResonanceJetTagging::m_HCal_cluster_minpt private
HCal Cluster selection and acceptance.
Definition at line 243 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 243 of file ResonanceJetTagging.h
Referenced by getHCalClusterMinPt(), isAcceptableHCalCluster(), setHCalClusterMinPt(), and setHCalClusterPtAcc().
unsigned int ResonanceJetTagging::m_jet_id = 0 private
Definition at line 263 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 263 of file ResonanceJetTagging.h
Referenced by findTaggedJets(), and tagHFHadronic().
fastjet::JetAlgorithm ResonanceJetTagging::m_jetalgo private
Definition at line 256 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 256 of file ResonanceJetTagging.h
Referenced by findMCTaggedJets(), findTaggedJets(), getJetAlgo(), and setJetAlgo().
std::string ResonanceJetTagging::m_jetcontainer_name private
String to contain the jetcontainer name containing the tagged jets.
Definition at line 224 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 224 of file ResonanceJetTagging.h
Referenced by createJetNode(), getJetContainerName(), and setJetContainerName().
double ResonanceJetTagging::m_jetr private
Definition at line 255 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 255 of file ResonanceJetTagging.h
Referenced by findMCTaggedJets(), findTaggedJets(), getR(), and setR().
std::string ResonanceJetTagging::m_KFparticle_name private
Definition at line 269 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 269 of file ResonanceJetTagging.h
Referenced by tagHFHadronic().
int ResonanceJetTagging::m_nDaughters private
Definition at line 267 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 267 of file ResonanceJetTagging.h
Referenced by process_event(), ResonanceJetTagging(), and tagHFHadronic().
double ResonanceJetTagging::m_particleflow_maxeta private
Definition at line 228 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 228 of file ResonanceJetTagging.h
Referenced by getParticleFlowMaxEta(), isAcceptableParticleFlow(), setParticleFlowEtaAcc(), and setParticleFlowMaxEta().
double ResonanceJetTagging::m_particleflow_mineta private
Particle Flow selection and acceptance.
Definition at line 227 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 227 of file ResonanceJetTagging.h
Referenced by getParticleFlowMinEta(), isAcceptableParticleFlow(), setParticleFlowEtaAcc(), and setParticleFlowMinEta().
fastjet::RecombinationScheme ResonanceJetTagging::m_recomb_scheme private
Definition at line 257 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 257 of file ResonanceJetTagging.h
Referenced by findMCTaggedJets(), findTaggedJets(), getRecombScheme(), and setRecombScheme().
TAG ResonanceJetTagging::m_tag_particle private
Definition at line 268 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 268 of file ResonanceJetTagging.h
Referenced by process_event(), and ResonanceJetTagging().
int ResonanceJetTagging::m_tag_pdg private
Definition at line 262 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 262 of file ResonanceJetTagging.h
Referenced by findMCTaggedJets(), ResonanceJetTagging(), and tagHFHadronic().
JetContainerv1* ResonanceJetTagging::m_taggedJetContainer = nullptr private
Definition at line 259 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 259 of file ResonanceJetTagging.h
Referenced by createJetNode(), and findTaggedJets().
double ResonanceJetTagging::m_track_maxeta private
Definition at line 234 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 234 of file ResonanceJetTagging.h
Referenced by findMCTaggedJets(), getTrackMaxEta(), isAcceptableTrack(), setTrackEtaAcc(), and setTrackMaxEta().
double ResonanceJetTagging::m_track_maxpt private
Definition at line 232 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 232 of file ResonanceJetTagging.h
Referenced by findMCTaggedJets(), getTrackMaxPt(), isAcceptableTrack(), setTrackMaxPt(), and setTrackPtAcc().
double ResonanceJetTagging::m_track_mineta private
Definition at line 233 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 233 of file ResonanceJetTagging.h
Referenced by findMCTaggedJets(), getTrackMinEta(), isAcceptableTrack(), setTrackEtaAcc(), and setTrackMinEta().
double ResonanceJetTagging::m_track_minpt private
Track selection and acceptance.
Definition at line 231 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 231 of file ResonanceJetTagging.h
Referenced by findMCTaggedJets(), getTrackMinPt(), isAcceptableTrack(), setTrackMinPt(), and setTrackPtAcc().
unsigned int ResonanceJetTagging::m_truth_jet_id = 0 private
Definition at line 264 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 264 of file ResonanceJetTagging.h
Referenced by findMCTaggedJets().
JetContainerv1* ResonanceJetTagging::m_truth_taggedJetContainer = nullptr private
Definition at line 260 of file ResonanceJetTagging.h.
View newest version in sPHENIX GitHub at line 260 of file ResonanceJetTagging.h
Referenced by createJetNode(), and findMCTaggedJets().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/ResonanceJetTagging/ResonanceJetTagging.h
coresoftware/blob/master/offline/packages/ResonanceJetTagging/ResonanceJetTagging.cc