Analysis Software: Jetscape::JetScapeEvent Class Reference
Jetscape::JetScapeEvent Class Reference
#include <JETSCAPE/blob/main/src/framework/JetScapeEvent.h>
Public Member Functions
JetScapeEvent ()
JetScapeEvent (const JetScapeEvent &c)
~JetScapeEvent ()
const Parton & getParton (int idx) const
const vector< Parton > & getPartonCollection () const
void addParton (Parton &p)
void addPartonShower (shared_ptr< PartonShower > ps)
void deleteParton (int idx)
Private Attributes
vector< Parton > partonCollection
Detailed Description
Definition at line 24 of file JetScapeEvent.h.
View newest version in sPHENIX GitHub at line 24 of file JetScapeEvent.h
Constructor & Destructor Documentation
Jetscape::JetScapeEvent::JetScapeEvent ()
Definition at line 23 of file JetScapeEvent.cc.
View newest version in sPHENIX GitHub at line 23 of file JetScapeEvent.cc
Jetscape::JetScapeEvent::JetScapeEvent (const JetScapeEvent & c)
Definition at line 25 of file JetScapeEvent.cc.
View newest version in sPHENIX GitHub at line 25 of file JetScapeEvent.cc
References getParton(), getPartonCollection(), and Acts::Test::tmp().
Jetscape::JetScapeEvent::~JetScapeEvent ()
Definition at line 33 of file JetScapeEvent.cc.
View newest version in sPHENIX GitHub at line 33 of file JetScapeEvent.cc
Member Function Documentation
void Jetscape::JetScapeEvent::addParton (Parton & p)
Definition at line 43 of file JetScapeEvent.cc.
View newest version in sPHENIX GitHub at line 43 of file JetScapeEvent.cc
void Jetscape::JetScapeEvent::addPartonShower (shared_ptr< PartonShower > ps)
Definition at line 45 of file JetScapeEvent.cc.
View newest version in sPHENIX GitHub at line 45 of file JetScapeEvent.cc
void Jetscape::JetScapeEvent::deleteParton (int idx)
Definition at line 51 of file JetScapeEvent.cc.
View newest version in sPHENIX GitHub at line 51 of file JetScapeEvent.cc
References ambiguity_solver_full_chain::idx.
const Parton & Jetscape::JetScapeEvent::getParton (int idx) const
Definition at line 39 of file JetScapeEvent.cc.
View newest version in sPHENIX GitHub at line 39 of file JetScapeEvent.cc
Referenced by JetScapeEvent().
const vector< Parton > & Jetscape::JetScapeEvent::getPartonCollection () const
Definition at line 35 of file JetScapeEvent.cc.
View newest version in sPHENIX GitHub at line 35 of file JetScapeEvent.cc
Referenced by JetScapeEvent().
Member Data Documentation
vector<Parton> Jetscape::JetScapeEvent::partonCollection private
Definition at line 38 of file JetScapeEvent.h.
View newest version in sPHENIX GitHub at line 38 of file JetScapeEvent.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/JetScapeEvent.h
JETSCAPE/blob/main/src/framework/JetScapeEvent.cc