Analysis Software: analysis/blob/master/isoCluster/offline/analyzeClusterEtIso.C File Reference
analyzeClusterEtIso.C File Reference
#include <sPhenixStyle.h>
#include <sPhenixStyle.C>
Functions
void analyzeClusterEtIso (int pass)
Function Documentation
void analyzeClusterEtIso (int pass)
Definition at line 14 of file analyzeClusterEtIso.C.
View newest version in sPHENIX GitHub at line 14 of file analyzeClusterEtIso.C
References AddEntry(), Acts::Test::at, c2, cd(), myAnalysis::clusterE, myAnalysis::clusterEta, myAnalysis::clusterPhi, myAnalysis::clusterPt, Draw(), Acts::UnitConstants::e, eBins, Fill(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEntry(), GetParameter(), GetXaxis(), GetYaxis(), i, j, k, leg, CKF_timing_vs_mu::mu, nEvents, ProjectionY, purity(), physmon_simulation::s, SetBorderSize(), SetBranchAddress(), SetFillStyle(), SetLineColor(), SetLineStyle(), SetLogy(), SetMarkerColor(), SetParameter(), SetPoint(), SetPointError(), SetsPhenixStyle(), SetTitle(), sigma, size, and Acts::UnitConstants::T.