Analysis Software: gtest_shuffle_test.GTestShuffleUnitTest Class Reference
gtest_shuffle_test.GTestShuffleUnitTest Class Reference
Public Member Functions
def setUp
def testShufflePreservesNumberOfTests
def testShuffleChangesTestOrder
def testShuffleChangesTestCaseOrder
def testShuffleDoesNotRepeatTest
def testShuffleDoesNotCreateNewTest
def testShuffleIncludesAllTests
def testShuffleLeavesDeathTestsAtFront
def testShuffleDoesNotInterleaveTestCases
def testShuffleRestoresOrderAfterEachIteration
def testShuffleGeneratesNewOrderInEachIteration
def testShuffleShardedTestsPreservesPartition
Private Member Functions
def _VerifyTestCasesDoNotInterleave
Detailed Description
Tests test shuffling.
Definition at line 169 of file gtest_shuffle_test.py.
View newest version in sPHENIX GitHub at line 169 of file gtest_shuffle_test.py
Member Function Documentation
def gtest_shuffle_test.GTestShuffleUnitTest._VerifyTestCasesDoNotInterleave (self, tests) private
Definition at line 245 of file gtest_shuffle_test.py.
View newest version in sPHENIX GitHub at line 245 of file gtest_shuffle_test.py
Referenced by gtest_shuffle_test.GTestShuffleUnitTest.testShuffleDoesNotInterleaveTestCases().
def gtest_shuffle_test.GTestShuffleUnitTest.setUp (self)
Definition at line 172 of file gtest_shuffle_test.py.
View newest version in sPHENIX GitHub at line 172 of file gtest_shuffle_test.py
References gtest_shuffle_test.CalculateTestLists().
def gtest_shuffle_test.GTestShuffleUnitTest.testShuffleChangesTestCaseOrder (self)
Definition at line 189 of file gtest_shuffle_test.py.
View newest version in sPHENIX GitHub at line 189 of file gtest_shuffle_test.py
References gtest_shuffle_test.GetTestCases().
def gtest_shuffle_test.GTestShuffleUnitTest.testShuffleChangesTestOrder (self)
Definition at line 181 of file gtest_shuffle_test.py.
View newest version in sPHENIX GitHub at line 181 of file gtest_shuffle_test.py
def gtest_shuffle_test.GTestShuffleUnitTest.testShuffleDoesNotCreateNewTest (self)
Definition at line 216 of file gtest_shuffle_test.py.
View newest version in sPHENIX GitHub at line 216 of file gtest_shuffle_test.py
def gtest_shuffle_test.GTestShuffleUnitTest.testShuffleDoesNotInterleaveTestCases (self)
Definition at line 255 of file gtest_shuffle_test.py.
View newest version in sPHENIX GitHub at line 255 of file gtest_shuffle_test.py
References gtest_shuffle_test.GTestShuffleUnitTest._VerifyTestCasesDoNotInterleave().
def gtest_shuffle_test.GTestShuffleUnitTest.testShuffleDoesNotRepeatTest (self)
Definition at line 202 of file gtest_shuffle_test.py.
View newest version in sPHENIX GitHub at line 202 of file gtest_shuffle_test.py
def gtest_shuffle_test.GTestShuffleUnitTest.testShuffleGeneratesNewOrderInEachIteration (self)
Definition at line 293 of file gtest_shuffle_test.py.
View newest version in sPHENIX GitHub at line 293 of file gtest_shuffle_test.py
References gtest_shuffle_test.GetTestsForAllIterations(), gtest_shuffle_test.RandomSeedFlag(), gtest_shuffle_test.RepeatFlag(), and gtest_shuffle_test.ShuffleFlag().
def gtest_shuffle_test.GTestShuffleUnitTest.testShuffleIncludesAllTests (self)
Definition at line 226 of file gtest_shuffle_test.py.
View newest version in sPHENIX GitHub at line 226 of file gtest_shuffle_test.py
def gtest_shuffle_test.GTestShuffleUnitTest.testShuffleLeavesDeathTestsAtFront (self)
Definition at line 236 of file gtest_shuffle_test.py.
View newest version in sPHENIX GitHub at line 236 of file gtest_shuffle_test.py
def gtest_shuffle_test.GTestShuffleUnitTest.testShufflePreservesNumberOfTests (self)
Definition at line 175 of file gtest_shuffle_test.py.
View newest version in sPHENIX GitHub at line 175 of file gtest_shuffle_test.py
def gtest_shuffle_test.GTestShuffleUnitTest.testShuffleRestoresOrderAfterEachIteration (self)
Definition at line 261 of file gtest_shuffle_test.py.
View newest version in sPHENIX GitHub at line 261 of file gtest_shuffle_test.py
References gtest_shuffle_test.GetTestsForAllIterations(), gtest_shuffle_test.RandomSeedFlag(), gtest_shuffle_test.RepeatFlag(), and gtest_shuffle_test.ShuffleFlag().
def gtest_shuffle_test.GTestShuffleUnitTest.testShuffleShardedTestsPreservesPartition (self)
Definition at line 305 of file gtest_shuffle_test.py.
View newest version in sPHENIX GitHub at line 305 of file gtest_shuffle_test.py
References gtest_shuffle_test.GetTestsForAllIterations(), gtest_test_utils.Main(), gtest_shuffle_test.RandomSeedFlag(), and gtest_shuffle_test.ShuffleFlag().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/googletest/googletest/test/gtest_shuffle_test.py