Analysis Software: PHFieldConfigv1 Class Reference
PHFieldConfigv1 Class Reference
PHFieldConfigv1 implements field configuration information for input a field map file.
#include <coresoftware/blob/master/offline/packages/PHField/PHFieldConfigv1.h>
Public Member Functions
PHFieldConfigv1 (FieldConfigTypes field_config, const std::string &filename, double magfield_rescale=1.)
PHFieldConfigv1 ()
default constructor for ROOT file IO
~PHFieldConfigv1 () override
PHObject * CloneMe () const override
Virtual copy constructor.
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Content.
int isValid () const override
isValid returns non zero if object contains vailid data
FieldConfigTypes get_field_config () const override
void set_field_config (FieldConfigTypes fieldConfig) override
const std::string & get_filename () const override
void set_filename (const std::string &filename) override
double get_magfield_rescale () const override
void set_magfield_rescale (double magfieldRescale) override
Public Member Functions inherited from PHFieldConfig
~PHFieldConfig () override
std::string get_field_config_description () const
virtual void set_field_config (FieldConfigTypes)
virtual double get_field_mag_x () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_x (double)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual double get_field_mag_y () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_y (double)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual double get_field_mag_z () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_z (double)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
FieldConfigTypes field_config_
std::string filename_
double magfield_rescale_
Additional Inherited Members
Public Types inherited from PHFieldConfig
enum FieldConfigTypes {
kFieldUniform = 0, kField2D = 2, kField3DCylindrical = 3, kFieldBeast = 4,
kFieldCleo = 5, Field3DCartesian = 1, kFieldInvalid = 9999
}
Protected Member Functions inherited from PHFieldConfig
PHFieldConfig ()
pure virtual interface class. not for direct use
Static Protected Attributes inherited from PHFieldConfig
static const std::string kInvalid_FileName
Detailed Description
PHFieldConfigv1 implements field configuration information for input a field map file.
Definition at line 23 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 23 of file PHFieldConfigv1.h
Constructor & Destructor Documentation
PHFieldConfigv1::PHFieldConfigv1 (FieldConfigTypes field_config, const std::string & filename, double magfield_rescale = 1.)
Definition at line 15 of file PHFieldConfigv1.cc.
View newest version in sPHENIX GitHub at line 15 of file PHFieldConfigv1.cc
PHFieldConfigv1::PHFieldConfigv1 () inline
default constructor for ROOT file IO
Definition at line 32 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 32 of file PHFieldConfigv1.h
Referenced by CloneMe().
PHFieldConfigv1::~PHFieldConfigv1 () inline override
Definition at line 37 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 37 of file PHFieldConfigv1.h
Member Function Documentation
PHObject* PHFieldConfigv1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 40 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 40 of file PHFieldConfigv1.h
References PHFieldConfigv1().
FieldConfigTypes PHFieldConfigv1::get_field_config () const inline override virtual
Reimplemented from PHFieldConfig.
Definition at line 54 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 54 of file PHFieldConfigv1.h
References field_config_.
const std::string& PHFieldConfigv1::get_filename () const inline override virtual
Reimplemented from PHFieldConfig.
Definition at line 63 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 63 of file PHFieldConfigv1.h
References filename_.
Referenced by identify().
double PHFieldConfigv1::get_magfield_rescale () const inline override virtual
Reimplemented from PHFieldConfig.
Definition at line 73 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 73 of file PHFieldConfigv1.h
References magfield_rescale_.
Referenced by identify().
void PHFieldConfigv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHFieldConfig.
Definition at line 27 of file PHFieldConfigv1.cc.
View newest version in sPHENIX GitHub at line 27 of file PHFieldConfigv1.cc
References PHFieldConfig::get_field_config_description(), get_filename(), get_magfield_rescale(), and isValid().
int PHFieldConfigv1::isValid () const override virtual
isValid returns non zero if object contains vailid data
isValid returns non zero if object contains valid data
Reimplemented from PHObject.
Definition at line 44 of file PHFieldConfigv1.cc.
View newest version in sPHENIX GitHub at line 44 of file PHFieldConfigv1.cc
References filename_.
Referenced by identify().
void PHFieldConfigv1::Reset () inline override virtual
Clear Content.
Reimplemented from PHObject.
Definition at line 49 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 49 of file PHFieldConfigv1.h
void PHFieldConfigv1::set_field_config (FieldConfigTypes fieldConfig) inline override
Definition at line 58 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 58 of file PHFieldConfigv1.h
References field_config_.
Referenced by PHSimpleKFProp::InitRun(), and PHCASeeding::Setup().
void PHFieldConfigv1::set_filename (const std::string & filename) inline override virtual
Reimplemented from PHFieldConfig.
Definition at line 68 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 68 of file PHFieldConfigv1.h
References filename, and filename_.
Referenced by PHSimpleKFProp::InitRun(), and PHCASeeding::Setup().
void PHFieldConfigv1::set_magfield_rescale (double magfieldRescale) inline override virtual
Reimplemented from PHFieldConfig.
Definition at line 78 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 78 of file PHFieldConfigv1.h
References magfield_rescale_.
Member Data Documentation
FieldConfigTypes PHFieldConfigv1::field_config_ protected
Definition at line 84 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 84 of file PHFieldConfigv1.h
Referenced by get_field_config(), and set_field_config().
std::string PHFieldConfigv1::filename_ protected
Definition at line 85 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 85 of file PHFieldConfigv1.h
Referenced by get_filename(), isValid(), and set_filename().
double PHFieldConfigv1::magfield_rescale_ protected
Definition at line 86 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 86 of file PHFieldConfigv1.h
Referenced by get_magfield_rescale(), and set_magfield_rescale().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/PHField/PHFieldConfigv1.h
coresoftware/blob/master/offline/packages/PHField/PHFieldConfigv1.cc