Analysis Software: ActsExamples::DigitizationConfigurator Struct Reference
ActsExamples::DigitizationConfigurator Struct Reference
#include <acts/blob/sPHENIX/Examples/Algorithms/Digitization/include/ActsExamples/Digitization/DigitizationConfigurator.hpp>
Public Member Functions
void operator() (const Acts::Surface *surface)
Public Attributes
Acts::GeometryHierarchyMap
< DigiComponentsConfig > inputDigiComponents
Simplified input components for digitization.
std::vector< std::pair
< Acts::GeometryIdentifier,
DigiComponentsConfig > > outputDigiComponents
Final collection of output components.
bool compactify = false
This tries to compactify the output map.
std::map
< Acts::GeometryIdentifier,
DigiComponentsConfig > volumeLayerComponents
High level reference configurations for compactification.
Detailed Description
Helper configurator that takes a simplified (per volume, per layer) Input digitization file and creates a full fletched per module digitization configuration file.
It acts as a visitor and then builds a fully developed digitization file for the geometric digitization, filling in the correct dimensions and number of bins.
The simplified file is assumed to have just one bin for the geometric digitization, which is then used to calculate the number of bins with respect to the bounds range.
Definition at line 47 of file DigitizationConfigurator.hpp.
View newest version in sPHENIX GitHub at line 47 of file DigitizationConfigurator.hpp
Member Function Documentation
void ActsExamples::DigitizationConfigurator::operator() (const Acts::Surface * surface)
The visitor call for the geometry
Parameters
surface is the surfaces that is visited
it adds an appropriate entry into the digitisation configuration
Definition at line 52 of file DigitizationConfigurator.cpp.
View newest version in sPHENIX GitHub at line 52 of file DigitizationConfigurator.cpp
References alpha, Acts::Surface::associatedDetectorElement(), Acts::binPhi, Acts::binR, Acts::binX, Acts::binY, Acts::Surface::bounds(), ActsExamples::GeometricConfig::chargeSmearer, compactify, ActsExamples::GeometricConfig::digital, Acts::SurfaceBounds::eAnnulus, Acts::RadialBounds::eAveragePhi, Acts::DiscTrapezoidBounds::eAveragePhi, Acts::AnnulusBounds::eAveragePhi, Acts::SurfaceBounds::eDisc, Acts::SurfaceBounds::eDiscTrapezoid, Acts::DiscTrapezoidBounds::eHalfLengthXmaxR, Acts::DiscTrapezoidBounds::eHalfLengthXminR, Acts::TrapezoidBounds::eHalfLengthXnegY, Acts::TrapezoidBounds::eHalfLengthXposY, Acts::TrapezoidBounds::eHalfLengthY, Acts::RadialBounds::eHalfPhiSector, Acts::AnnulusBounds::eMaxPhiRel, Acts::RadialBounds::eMaxR, Acts::DiscTrapezoidBounds::eMaxR, Acts::AnnulusBounds::eMaxR, Acts::RectangleBounds::eMaxX, Acts::RectangleBounds::eMaxY, Acts::AnnulusBounds::eMinPhiRel, Acts::RadialBounds::eMinR, Acts::DiscTrapezoidBounds::eMinR, Acts::AnnulusBounds::eMinR, Acts::RectangleBounds::eMinX, Acts::RectangleBounds::eMinY, Acts::GeometryHierarchyMap< value_t >::end(), Acts::SurfaceBounds::eRectangle, Acts::SurfaceBounds::eTrapezoid, Acts::GeometryHierarchyMap< value_t >::find(), ActsExamples::DigiComponentsConfig::geometricDigiConfig, Acts::GeometryObject::geometryId(), ActsExamples::GeometricConfig::indices, inputDigiComponents, Acts::GeometryIdentifier::layer(), Acts::Test::maxPhi, maxR, Acts::Test::minPhi, minR, Acts::open, outputDigiComponents, round(), ActsExamples::GeometricConfig::segmentation, Acts::GeometryIdentifier::setLayer(), Acts::GeometryIdentifier::setVolume(), ActsExamples::DigiComponentsConfig::smearingDigiConfig, ActsExamples::GeometricConfig::thickness, Acts::SurfaceBounds::type(), Acts::SurfaceBounds::values(), Acts::GeometryIdentifier::volume(), and volumeLayerComponents.
Member Data Documentation
bool ActsExamples::DigitizationConfigurator::compactify = false
This tries to compactify the output map.
Definition at line 56 of file DigitizationConfigurator.hpp.
View newest version in sPHENIX GitHub at line 56 of file DigitizationConfigurator.hpp
Referenced by operator()(), and runDigitizationConfigExample().
Acts::GeometryHierarchyMap<DigiComponentsConfig> ActsExamples::DigitizationConfigurator::inputDigiComponents
Simplified input components for digitization.
Definition at line 49 of file DigitizationConfigurator.hpp.
View newest version in sPHENIX GitHub at line 49 of file DigitizationConfigurator.hpp
Referenced by operator()(), and runDigitizationConfigExample().
std::vector<std::pair<Acts::GeometryIdentifier, DigiComponentsConfig> > ActsExamples::DigitizationConfigurator::outputDigiComponents
Final collection of output components.
Definition at line 53 of file DigitizationConfigurator.hpp.
View newest version in sPHENIX GitHub at line 53 of file DigitizationConfigurator.hpp
Referenced by operator()(), and runDigitizationConfigExample().
std::map<Acts::GeometryIdentifier, DigiComponentsConfig> ActsExamples::DigitizationConfigurator::volumeLayerComponents
High level reference configurations for compactification.
Definition at line 60 of file DigitizationConfigurator.hpp.
View newest version in sPHENIX GitHub at line 60 of file DigitizationConfigurator.hpp
Referenced by operator()().
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Digitization/include/ActsExamples/Digitization/DigitizationConfigurator.hpp
acts/blob/sPHENIX/Examples/Algorithms/Digitization/src/DigitizationConfigurator.cpp