Analysis Software: TRDBCServer Class Reference
TRDBCServer Class Reference
#include <RDBC/blob/master/include/RDBC/TRDBCServer.h>
Public Member Functions
TRDBCServer (const char *db, const char *uid, const char *pw)
~TRDBCServer ()
void Close (Option_t *opt="")
TSQLResultSet * Query (const char *sql)
Int_t SelectDataBase (const char *dbname)
TSQLResultSet * GetDataBases (const char *wild=0)
TSQLResultSet * GetTables (const char *dbname, const char *wild=0)
TSQLResultSet * GetColumns (const char *dbname, const char *table, const char *wild=0)
Int_t CreateDataBase (const char *dbname)
Int_t DropDataBase (const char *dbname)
Int_t Reload ()
Int_t Shutdown ()
const char * ServerInfo ()
TSQLConnection * GetConnection () const
Private Attributes
TSQLConnection * fConnection
TString fDbName
Detailed Description
Definition at line 18 of file TRDBCServer.h.
View newest version in sPHENIX GitHub at line 18 of file TRDBCServer.h
Constructor & Destructor Documentation
TRDBCServer::TRDBCServer (const char * db, const char * uid, const char * pw)
TRDBCServer::~TRDBCServer ()
Definition at line 45 of file TRDBCServer.cxx.
View newest version in sPHENIX GitHub at line 45 of file TRDBCServer.cxx
References Close().
Member Function Documentation
void TRDBCServer::Close (Option_t * opt = "")
Definition at line 53 of file TRDBCServer.cxx.
View newest version in sPHENIX GitHub at line 53 of file TRDBCServer.cxx
References TSQLConnection::Close(), fConnection, and TSQLConnection::IsClosed().
Referenced by ~TRDBCServer().
Int_t TRDBCServer::CreateDataBase (const char * dbname)
Definition at line 184 of file TRDBCServer.cxx.
View newest version in sPHENIX GitHub at line 184 of file TRDBCServer.cxx
References TSQLConnection::CreateStatement(), TSQLStatement::Execute(), and fConnection.
Int_t TRDBCServer::DropDataBase (const char * dbname)
Definition at line 207 of file TRDBCServer.cxx.
View newest version in sPHENIX GitHub at line 207 of file TRDBCServer.cxx
References TSQLConnection::CreateStatement(), TSQLStatement::Execute(), and fConnection.
TSQLResultSet * TRDBCServer::GetColumns (const char * dbname, const char * table, const char * wild = 0)
Definition at line 152 of file TRDBCServer.cxx.
View newest version in sPHENIX GitHub at line 152 of file TRDBCServer.cxx
References fDbName, Query(), and SelectDataBase().
TSQLConnection* TRDBCServer::GetConnection () const inline
Definition at line 41 of file TRDBCServer.h.
View newest version in sPHENIX GitHub at line 41 of file TRDBCServer.h
References fConnection.
TSQLResultSet * TRDBCServer::GetDataBases (const char * wild = 0)
Definition at line 97 of file TRDBCServer.cxx.
View newest version in sPHENIX GitHub at line 97 of file TRDBCServer.cxx
References fDbName, and Query().
TSQLResultSet * TRDBCServer::GetTables (const char * dbname, const char * wild = 0)
Definition at line 120 of file TRDBCServer.cxx.
View newest version in sPHENIX GitHub at line 120 of file TRDBCServer.cxx
References fDbName, Query(), and SelectDataBase().
TSQLResultSet * TRDBCServer::Query (const char * sql)
Definition at line 63 of file TRDBCServer.cxx.
View newest version in sPHENIX GitHub at line 63 of file TRDBCServer.cxx
References TSQLConnection::CreateStatement(), TSQLStatement::ExecuteQuery(), and fConnection.
Referenced by GetColumns(), GetDataBases(), GetTables(), and ServerInfo().
Int_t TRDBCServer::Reload ()
Definition at line 230 of file TRDBCServer.cxx.
View newest version in sPHENIX GitHub at line 230 of file TRDBCServer.cxx
References TSQLConnection::CreateStatement(), TSQLStatement::Execute(), fConnection, and fDbName.
Int_t TRDBCServer::SelectDataBase (const char * dbname)
Definition at line 77 of file TRDBCServer.cxx.
View newest version in sPHENIX GitHub at line 77 of file TRDBCServer.cxx
References TSQLConnection::CreateStatement(), TSQLStatement::Execute(), and fConnection.
Referenced by GetColumns(), and GetTables().
const char * TRDBCServer::ServerInfo ()
Definition at line 267 of file TRDBCServer.cxx.
View newest version in sPHENIX GitHub at line 267 of file TRDBCServer.cxx
References fDbName, TSQLResultSet::GetString(), TSQLResultSet::Next(), Query(), and str.
Int_t TRDBCServer::Shutdown ()
Definition at line 254 of file TRDBCServer.cxx.
View newest version in sPHENIX GitHub at line 254 of file TRDBCServer.cxx
Member Data Documentation
TSQLConnection* TRDBCServer::fConnection private
Definition at line 21 of file TRDBCServer.h.
View newest version in sPHENIX GitHub at line 21 of file TRDBCServer.h
Referenced by Close(), CreateDataBase(), DropDataBase(), GetConnection(), Query(), Reload(), and SelectDataBase().
TString TRDBCServer::fDbName private
Definition at line 22 of file TRDBCServer.h.
View newest version in sPHENIX GitHub at line 22 of file TRDBCServer.h
Referenced by GetColumns(), GetDataBases(), GetTables(), Reload(), and ServerInfo().
The documentation for this class was generated from the following files:
RDBC/blob/master/include/RDBC/TRDBCServer.h
RDBC/blob/master/rdbc/TRDBCServer.cxx