Analysis Software: caloTowerEmbed Class Reference
caloTowerEmbed Class Reference
#include <analysis/blob/master/CalorimeterEmbedding/src/caloTowerEmbed.h>
Public Types
enum DetectorSystem { CEMC = 0, HCALIN = 1, HCALOUT = 2, EPD = 3 }
Public Member Functions
caloTowerEmbed (const std::string &name="caloTowerEmbed")
~caloTowerEmbed () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void CreateNodeTree (PHCompositeNode *topNode)
void set_useRetower (bool a)
caloTowerEmbed (const std::string &name="caloTowerEmbed")
~caloTowerEmbed () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void CreateNodeTree (PHCompositeNode *topNode)
void set_detector_type (CaloTowerDefs::DetectorSystem dettype)
void set_inputNodePrefix (const std::string &name)
void set_useRetower (bool a)
void set_removeBadTowers (bool a)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
TowerInfoContainer * _data_towers [3] = {nullptr,nullptr,nullptr}
TowerInfoContainer * _sim_towers [3] = {nullptr,nullptr,nullptr}
RawTowerGeomContainer * tower_geom = nullptr
RawTowerGeomContainer * tower_geomIH = nullptr
RawTowerGeomContainer * tower_geomOH = nullptr
bool m_useRetower = false
int m_runNumber {0}
int m_eventNumber {-1}
TowerInfoContainer * _embed_towers_out {nullptr}
TowerInfoContainer * _sim_towers_out {nullptr}
bool m_removeBadTowers {false}
CaloTowerDefs::DetectorSystem m_dettype {CaloTowerDefs::DETECTOR_INVALID}
std::string m_detector
std::string m_inputNodePrefix {"TOWERINFO_CALIB_"}
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 27 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 27 of file caloTowerEmbed.h
Member Enumeration Documentation
enum caloTowerEmbed::DetectorSystem
Enumerator:
CEMC
HCALIN
HCALOUT
EPD
Definition at line 42 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 42 of file caloTowerEmbed.h
Constructor & Destructor Documentation
caloTowerEmbed::caloTowerEmbed (const std::string & name = "caloTowerEmbed")
Definition at line 38 of file caloTowerEmbed.cc.
View newest version in sPHENIX GitHub at line 38 of file caloTowerEmbed.cc
caloTowerEmbed::~caloTowerEmbed () override
Definition at line 47 of file caloTowerEmbed.cc.
View newest version in sPHENIX GitHub at line 47 of file caloTowerEmbed.cc
caloTowerEmbed::caloTowerEmbed (const std::string & name = "caloTowerEmbed")
caloTowerEmbed::~caloTowerEmbed () override
Member Function Documentation
void caloTowerEmbed::CreateNodeTree (PHCompositeNode * topNode)
void caloTowerEmbed::CreateNodeTree (PHCompositeNode * topNode)
Definition at line 206 of file caloTowerEmbed.cc.
View newest version in sPHENIX GitHub at line 206 of file caloTowerEmbed.cc
References _data_towers, _sim_towers, PHNodeIterator::findFirst(), i, Fun4AllServer::instance(), m_useRetower, Fun4AllBase::Name(), Fun4AllServer::topNode(), tower_geom, tower_geomIH, and tower_geomOH.
Referenced by InitRun().
int caloTowerEmbed::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
int caloTowerEmbed::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 199 of file caloTowerEmbed.cc.
View newest version in sPHENIX GitHub at line 199 of file caloTowerEmbed.cc
References Fun4AllReturnCodes::EVENT_OK.
int caloTowerEmbed::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int caloTowerEmbed::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 53 of file caloTowerEmbed.cc.
View newest version in sPHENIX GitHub at line 53 of file caloTowerEmbed.cc
References Fun4AllReturnCodes::ABORTRUN, CreateNodeTree(), Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, EventHeader::get_RunNumber(), Fun4AllServer::instance(), m_runNumber, PHCompositeNode::print(), Fun4AllServer::topNode(), and Fun4AllBase::Verbosity().
int caloTowerEmbed::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int caloTowerEmbed::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 88 of file caloTowerEmbed.cc.
View newest version in sPHENIX GitHub at line 88 of file caloTowerEmbed.cc
References _data_towers, _sim_towers, Fun4AllReturnCodes::ABORTEVENT, Enable::CEMC, channel(), TowerInfoContainer::encode_key(), RawTowerDefs::encode_towerid(), Fun4AllReturnCodes::EVENT_OK, TowerInfo::get_energy(), RawTowerGeom::get_eta(), RawTowerGeom::get_phi(), TowerInfoContainer::get_tower_at_channel(), RawTowerGeomContainer::get_tower_geometry(), TowerInfoContainer::getTowerEtaBin(), TowerInfoContainer::getTowerPhiBin(), RawTowerDefs::HCALIN, RawTowerDefs::HCALOUT, m_eventNumber, m_useRetower, TowerInfo::set_energy(), TowerInfoContainer::size(), tower_geom, tower_geomIH, tower_geomOH, and Fun4AllBase::Verbosity().
void caloTowerEmbed::set_detector_type (CaloTowerDefs::DetectorSystem dettype) inline
Definition at line 35 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 35 of file caloTowerEmbed.h
References m_dettype.
Referenced by Fun4All_JetBkgd_Embed().
void caloTowerEmbed::set_inputNodePrefix (const std::string & name) inline
Definition at line 41 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 41 of file caloTowerEmbed.h
References m_inputNodePrefix, and perf_headwind::name.
Referenced by Fun4All_JetBkgd_Embed().
void caloTowerEmbed::set_removeBadTowers (bool a) inline
Definition at line 53 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 53 of file caloTowerEmbed.h
References KFPMath::a, and m_removeBadTowers.
Referenced by Fun4All_JetBkgd_Embed().
void caloTowerEmbed::set_useRetower (bool a) inline
Definition at line 40 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 40 of file caloTowerEmbed.h
References KFPMath::a, and m_useRetower.
void caloTowerEmbed::set_useRetower (bool a) inline
Definition at line 47 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 47 of file caloTowerEmbed.h
References KFPMath::a, and m_useRetower.
Member Data Documentation
TowerInfoContainer * caloTowerEmbed::_data_towers = {nullptr,nullptr,nullptr} private
Definition at line 51 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 51 of file caloTowerEmbed.h
Referenced by CreateNodeTree(), and process_event().
TowerInfoContainer* caloTowerEmbed::_embed_towers_out {nullptr} private
Definition at line 65 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 65 of file caloTowerEmbed.h
TowerInfoContainer * caloTowerEmbed::_sim_towers = {nullptr,nullptr,nullptr} private
Definition at line 52 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 52 of file caloTowerEmbed.h
Referenced by CreateNodeTree(), and process_event().
TowerInfoContainer* caloTowerEmbed::_sim_towers_out {nullptr} private
Definition at line 66 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 66 of file caloTowerEmbed.h
std::string caloTowerEmbed::m_detector private
Definition at line 75 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 75 of file caloTowerEmbed.h
CaloTowerDefs::DetectorSystem caloTowerEmbed::m_dettype {CaloTowerDefs::DETECTOR_INVALID} private
Definition at line 73 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 73 of file caloTowerEmbed.h
Referenced by set_detector_type().
int caloTowerEmbed::m_eventNumber {-1} private
Definition at line 63 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 63 of file caloTowerEmbed.h
Referenced by process_event().
std::string caloTowerEmbed::m_inputNodePrefix {"TOWERINFO_CALIB_"} private
Definition at line 76 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 76 of file caloTowerEmbed.h
Referenced by set_inputNodePrefix().
bool caloTowerEmbed::m_removeBadTowers {false} private
Definition at line 71 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 71 of file caloTowerEmbed.h
Referenced by set_removeBadTowers().
int caloTowerEmbed::m_runNumber {0} private
Definition at line 62 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 62 of file caloTowerEmbed.h
Referenced by InitRun().
bool caloTowerEmbed::m_useRetower = false private
Definition at line 58 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 58 of file caloTowerEmbed.h
Referenced by CreateNodeTree(), process_event(), and set_useRetower().
RawTowerGeomContainer * caloTowerEmbed::tower_geom = nullptr private
Definition at line 54 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 54 of file caloTowerEmbed.h
Referenced by CreateNodeTree(), and process_event().
RawTowerGeomContainer* caloTowerEmbed::tower_geomIH = nullptr private
Definition at line 55 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 55 of file caloTowerEmbed.h
Referenced by CreateNodeTree(), and process_event().
RawTowerGeomContainer* caloTowerEmbed::tower_geomOH = nullptr private
Definition at line 56 of file caloTowerEmbed.h.
View newest version in sPHENIX GitHub at line 56 of file caloTowerEmbed.h
Referenced by CreateNodeTree(), and process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/CalorimeterEmbedding/src/caloTowerEmbed.h
coresoftware/blob/master/offline/packages/CaloEmbedding/caloTowerEmbed.h
analysis/blob/master/CalorimeterEmbedding/src/caloTowerEmbed.cc
coresoftware/blob/master/offline/packages/CaloEmbedding/caloTowerEmbed.cc