Analysis Software: RDBC/blob/master/rdbc/TSQLConnection.cxx File Reference
TSQLConnection.cxx File Reference
#include <RDBC/TSQLConnection.h>
#include <RDBC/TSQLResultSet.h>
#include <RDBC/TSQLDatabaseMetaData.h>
#include <RDBC/TSQLDriverManager.h>
#include <TList.h>
Functions
ClassImpQ (TSQLConnection) TSQLConnection
const char * s (Bool_t b)
TString maybeQuote (const TString &str, const TString &qc)
void rsInfo (TSQLDatabaseMetaData *md, Int_t rsType, const char *name)
void transactionInfo (TSQLDatabaseMetaData *md)
void catalogInfo (TSQLDatabaseMetaData *md)
void schemaInfo (TSQLDatabaseMetaData *md)
void productInfo (TSQLDatabaseMetaData *md)
void driverInfo (TSQLDatabaseMetaData *md)
void funcInfo (TSQLDatabaseMetaData *md)
void keywordInfo (TSQLDatabaseMetaData *md)
Variables
struct {
int id
const char * name
} levels []
Function Documentation
void catalogInfo (TSQLDatabaseMetaData * md)
Definition at line 352 of file TSQLConnection.cxx.
View newest version in sPHENIX GitHub at line 352 of file TSQLConnection.cxx
References Jetscape::cid, Data, TSQLDatabaseMetaData::GetCatalogSeparator(), TSQLDatabaseMetaData::GetCatalogTerm(), TSQLDatabaseMetaData::GetTableTerm(), train_ambiguity_solver::id, TSQLDatabaseMetaData::IsCatalogAtStart(), printf(), physmon_simulation::s, TSQLDatabaseMetaData::SupportsCatalogsInDataManipulation(), TSQLDatabaseMetaData::SupportsCatalogsInIndexDefinitions(), TSQLDatabaseMetaData::SupportsCatalogsInPrivilegeDefinitions(), TSQLDatabaseMetaData::SupportsCatalogsInProcedureCalls(), and TSQLDatabaseMetaData::SupportsCatalogsInTableDefinitions().
ClassImpQ (TSQLConnection)
Definition at line 135 of file TSQLConnection.cxx.
View newest version in sPHENIX GitHub at line 135 of file TSQLConnection.cxx
References TSQL::fImp, and TSQLResultSet::fMetaData.
void driverInfo (TSQLDatabaseMetaData * md)
Definition at line 437 of file TSQLConnection.cxx.
View newest version in sPHENIX GitHub at line 437 of file TSQLConnection.cxx
References TSQLDatabaseMetaData::GetDriverName(), TSQLDatabaseMetaData::GetDriverVersion(), printf(), and str.
void funcInfo (TSQLDatabaseMetaData * md)
Definition at line 451 of file TSQLConnection.cxx.
View newest version in sPHENIX GitHub at line 451 of file TSQLConnection.cxx
References TSQLDatabaseMetaData::GetNumericFunctions(), TSQLDatabaseMetaData::GetStringFunctions(), TSQLDatabaseMetaData::GetSystemFunctions(), TSQLDatabaseMetaData::GetTimeDateFunctions(), printf(), and str.
void keywordInfo (TSQLDatabaseMetaData * md)
Definition at line 479 of file TSQLConnection.cxx.
View newest version in sPHENIX GitHub at line 479 of file TSQLConnection.cxx
References TSQLDatabaseMetaData::GetSQLKeywords(), printf(), and str.
TString maybeQuote (const TString & str, const TString & qc)
Definition at line 258 of file TSQLConnection.cxx.
View newest version in sPHENIX GitHub at line 258 of file TSQLConnection.cxx
References str.
void productInfo (TSQLDatabaseMetaData * md)
Definition at line 423 of file TSQLConnection.cxx.
View newest version in sPHENIX GitHub at line 423 of file TSQLConnection.cxx
References TSQLDatabaseMetaData::GetDatabaseProductName(), TSQLDatabaseMetaData::GetDatabaseProductVersion(), printf(), and str.
void rsInfo (TSQLDatabaseMetaData * md, Int_t rsType, const char * name)
Definition at line 269 of file TSQLConnection.cxx.
View newest version in sPHENIX GitHub at line 269 of file TSQLConnection.cxx
References kCONCUR_READ_ONLY, kCONCUR_UPDATABLE, TSQLDatabaseMetaData::OwnDeletesAreVisible(), TSQLDatabaseMetaData::OwnInsertsAreVisible(), TSQLDatabaseMetaData::OwnUpdatesAreVisible(), printf(), TSQLDatabaseMetaData::SupportsResultSetConcurrency(), and TSQLDatabaseMetaData::SupportsResultSetType().
const char* s (Bool_t b)
Definition at line 250 of file TSQLConnection.cxx.
View newest version in sPHENIX GitHub at line 250 of file TSQLConnection.cxx
void schemaInfo (TSQLDatabaseMetaData * md)
Definition at line 392 of file TSQLConnection.cxx.
View newest version in sPHENIX GitHub at line 392 of file TSQLConnection.cxx
References TSQLDatabaseMetaData::GetIdentifierQuoteString(), TSQLDatabaseMetaData::GetTableTerm(), printf(), physmon_simulation::s, Jetscape::sid, TSQLDatabaseMetaData::SupportsSchemasInDataManipulation(), TSQLDatabaseMetaData::SupportsSchemasInIndexDefinitions(), TSQLDatabaseMetaData::SupportsSchemasInPrivilegeDefinitions(), TSQLDatabaseMetaData::SupportsSchemasInProcedureCalls(), and TSQLDatabaseMetaData::SupportsSchemasInTableDefinitions().
void transactionInfo (TSQLDatabaseMetaData * md)
Definition at line 311 of file TSQLConnection.cxx.
View newest version in sPHENIX GitHub at line 311 of file TSQLConnection.cxx
References TSQLDatabaseMetaData::DataDefinitionCausesTransactionCommit(), TSQLDatabaseMetaData::DataDefinitionIgnoredInTransactions(), TSQLDatabaseMetaData::GetDefaultTransactionIsolation(), i, levels, printf(), physmon_simulation::s, str, TSQLDatabaseMetaData::SupportsDataDefinitionAndDataManipulationTransactions(), TSQLDatabaseMetaData::SupportsDataManipulationTransactionsOnly(), TSQLDatabaseMetaData::SupportsTransactionIsolationLevel(), and TSQLDatabaseMetaData::SupportsTransactions().
Variable Documentation
int id
Definition at line 300 of file TSQLConnection.cxx.
View newest version in sPHENIX GitHub at line 300 of file TSQLConnection.cxx
struct { ... } levels[]
Initial value:
= {
      { kTRANSACTION_READ_UNCOMMITTED, "kTRANSACTION_READ_UNCOMMITTED" },
      { kTRANSACTION_READ_COMMITTED, "kTRANSACTION_READ_COMMITTED" },
      { kTRANSACTION_REPEATABLE_READ, "kTRANSACTION_REPEATABLE_READ" },
      { kTRANSACTION_SERIALIZABLE, "kTRANSACTION_SERIALIZABLE" },
      { 0,NULL }
   }
const char* name
Definition at line 301 of file TSQLConnection.cxx.
View newest version in sPHENIX GitHub at line 301 of file TSQLConnection.cxx