Analysis Software: TPC_Cluster_Drift_Animator Namespace Reference
TPC_Cluster_Drift_Animator Namespace Reference
Functions
def TPC_surface
def TPC_endcap
def raddist_cluster
def theLoop
def animate_scatters
def animate_clusters
def read_cluster_pos
Variables
tuple iterations int((no_events-1)*mean_eventtime*time_scale/(iteration_time*1000)+len_TPC/drift_speed_posz[2])
Function Documentation
def TPC_Cluster_Drift_Animator.animate_clusters (data, animation_name = "Animated_clusters_TPC.mp4", save = False, start_iteration = 0, no_iterations = 1)
Definition at line 132 of file TPC_Cluster_Drift_Animator.py.
View newest version in sPHENIX GitHub at line 132 of file TPC_Cluster_Drift_Animator.py
References print(), and TPC_surface().
def TPC_Cluster_Drift_Animator.animate_scatters (iteration, data, scatters, fig_text, time_scale, iteration_time, start_iteration)
Definition at line 85 of file TPC_Cluster_Drift_Animator.py.
View newest version in sPHENIX GitHub at line 85 of file TPC_Cluster_Drift_Animator.py
References if(), print(), round(), str, theLoop(), and Acts.zip().
Referenced by theLoop().
def TPC_Cluster_Drift_Animator.raddist_cluster (cluster_pos)
Definition at line 54 of file TPC_Cluster_Drift_Animator.py.
View newest version in sPHENIX GitHub at line 54 of file TPC_Cluster_Drift_Animator.py
Referenced by read_cluster_pos().
def TPC_Cluster_Drift_Animator.read_cluster_pos (inFile)
Definition at line 207 of file TPC_Cluster_Drift_Animator.py.
View newest version in sPHENIX GitHub at line 207 of file TPC_Cluster_Drift_Animator.py
References if(), Acts.open, print(), and raddist_cluster().
def TPC_Cluster_Drift_Animator.theLoop (iteration, dataPoint, scatter)
Definition at line 58 of file TPC_Cluster_Drift_Animator.py.
View newest version in sPHENIX GitHub at line 58 of file TPC_Cluster_Drift_Animator.py
References animate_scatters(), and if().
Referenced by animate_scatters().
def TPC_Cluster_Drift_Animator.TPC_endcap (inner_radius, outer_radius, length_z)
Definition at line 37 of file TPC_Cluster_Drift_Animator.py.
View newest version in sPHENIX GitHub at line 37 of file TPC_Cluster_Drift_Animator.py
def TPC_Cluster_Drift_Animator.TPC_surface (inner_radius, outer_radius, length_z)
Definition at line 25 of file TPC_Cluster_Drift_Animator.py.
View newest version in sPHENIX GitHub at line 25 of file TPC_Cluster_Drift_Animator.py
Referenced by animate_clusters().
Variable Documentation
tuple TPC_Cluster_Drift_Animator.iterations int((no_events-1)*mean_eventtime*time_scale/(iteration_time*1000)+len_TPC/drift_speed_posz[2])
Definition at line 298 of file TPC_Cluster_Drift_Animator.py.
View newest version in sPHENIX GitHub at line 298 of file TPC_Cluster_Drift_Animator.py
Referenced by genfit::RKTrackRep.extrapolateBy(), genfit::RKTrackRep.extrapolateToCone(), genfit::RKTrackRep.extrapolateToCylinder(), genfit::RKTrackRep.extrapolateToLine(), genfit::RKTrackRep.extrapolateToSphere(), genfit::RKTrackRep.extrapToPoint(), main(), and PHActsInitialVertexFinder.setIterations().