Analysis Software: PHObject Class Reference
PHObject Class Reference
#include <coresoftware/blob/master/offline/framework/phool/PHObject.h>
Inherits TObject.
Inherited by AssocInfoContainer, BbcGeom, BbcOut, BbcPmtContainer, BbcPmtHit, BbcVertex, BbcVertexMap, CaloTriggerInfo, CdbUrlSave, CentralityInfo, ClusHitsVerbose, CMFlashCluster, CMFlashClusterContainer, CMFlashDifference, CMFlashDifferenceContainer, DecayFinderContainerBase, EicEventHeader, EmbRecoMatch, EmbRecoMatchContainer, EMCalTrk, EpdGeom, EventHeader, Eventplaneinfo, EventplaneinfoMap, FlagSave, FullJetFinder::Container, FullJetFinder::CutSelection, G4RootHitContainer, G4RootRawTower, G4RootRawTowerContainer, G4RootScintillatorSlat, G4RootScintillatorSlatContainer, G4RootScintillatorTower, G4RootScintillatorTowerContainer, Gl1RawHit, GlobalVertex, GlobalVertexMap, InttDeadMap, InttEventInfo, InttMap, InttMaskedChannelSet, InttRawHit, InttRawHitContainer, InttSurveyMap, InttVertex, InttVertexMap, Jet, JetContainer, JetMap, KFParticle_Container, MbdGeom, MbdOut, MbdPmtContainer, MbdPmtHit, MbdVertexMap, MCPhoton, MicromegasCombinedDataEvaluation::Container, MicromegasRawDataEvaluation::Container, MicromegasRawHit, MicromegasRawHitContainer, MicromegasTile, MinimumBiasInfo, MvtxEventInfo, MvtxRawEvtHeader, MvtxRawHit, MvtxRawHitContainer, MySimpleTree, MyTClonesArray, ParticleFlowElement, ParticleFlowElementContainer, PdbBankID, PdbCalBank, PdbCalChan, PHFieldConfig, PHG4BlockCellGeom, PHG4BlockCellGeomContainer, PHG4BlockGeom, PHG4BlockGeomContainer, PHG4Cell, PHG4CellContainer, PHG4CylinderCellContainer, PHG4CylinderCellGeom, PHG4CylinderCellGeomContainer, PHG4CylinderGeom, PHG4CylinderGeomContainer, PHG4EventHeader, PHG4GDMLConfig, PHG4Hit, PHG4HitContainer, PHG4InEvent, PHG4Particle, PHG4ParticleSvtxMap, PHG4ScintillatorSlat, PHG4ScintillatorSlatContainer, PHG4Shower, PHG4TpcCylinderGeomContainer, PHG4TruthInfoContainer, PHG4VtxPoint, PHGenIntegral, PHGeomIOTGeo, PHGeomTGeo, PHHepMCGenEvent, PHHepMCGenEventMap, PhotonPair, PHParameters, PHParametersContainer, PHTimeStamp, PidCandidate, PidInfo, PidInfoContainer, PJContainer, RawCluster, RawClusterContainer, RawHit, RawHitSet, RawHitSetContainer, RawTower, RawTowerContainer, RawTowerDeadMap, RawTowerGeom, RawTowerGeomContainer, RunHeader, sPHElectron, sPHElectronPair, sPHElectronPairContainer, SubjetIndices, SvtxAlignmentState, SvtxAlignmentStateMap, SvtxPHG4ParticleMap, SvtxTrack, SvtxTrackCaloClusterMap, SvtxTrackInfo, SvtxTrackMap, SvtxTrackState, SvtxVertexMap, SyncObject, TowerBackground, TowerInfo, TowerInfoContainer, TpcPrototypeTrack, TpcRawHit, TpcRawHitContainer, TpcSeedTrackMap, TpcSpaceChargeMatrixContainer, TpcTpotEventInfo, TrackEvaluationContainer, TrackInfoContainer, TrackPidAssoc, TrackSeed, TrackSeedContainer, TrackStateInfo, TrainingHits, TrainingHitsContainer, TrkrCluster, TrkrClusterContainer, TrkrClusterCrossingAssoc, TrkrClusterHitAssoc, TrkrClusterIterationMap, TrkrHit, TrkrHitSet, TrkrHitSetContainer, TrkrHitTruthAssoc, TrkrTruthTrack, TrkrTruthTrackContainer, UpsilonPair, VariableArray, VariableArrayContainer, and Vertex.
Public Member Functions
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
Definition at line 13 of file PHObject.h.
View newest version in sPHENIX GitHub at line 13 of file PHObject.h
Constructor & Destructor Documentation
PHObject::PHObject () inline
ctor
Definition at line 17 of file PHObject.h.
View newest version in sPHENIX GitHub at line 17 of file PHObject.h
PHObject::~PHObject () inline override
dtor
Definition at line 20 of file PHObject.h.
View newest version in sPHENIX GitHub at line 20 of file PHObject.h
Member Function Documentation
PHObject * PHObject::clone () const final virtual
Definition at line 20 of file PHObject.cc.
View newest version in sPHENIX GitHub at line 20 of file PHObject.cc
References PHWHERE.
Referenced by OnCalServer::CopySnglTableNewBankId().
PHObject * PHObject::Clone (const char * newname = "") const final
Definition at line 67 of file PHObject.cc.
View newest version in sPHENIX GitHub at line 67 of file PHObject.cc
References PHWHERE.
Referenced by PgPostBankBackupStorage::createBank(), and PgPostBankBackupManager::SQLResultSet2BackupStorage().
PHObject * PHObject::CloneMe () const virtual
Virtual copy constructor.
Reimplemented in Jet, SvtxTrackInfo_v1, Jetv2, SvtxTrack, GlobalVertex, PHHepMCGenEventMap, PHFieldConfigv1, PHFieldConfigv2, TpcTpotEventInfov1, TrackStateInfo_v1, TpcPrototypeCluster, SvtxTrack_v4, KFParticle_Container, SvtxTrack_FastSim, SvtxTrack_FastSim_v1, SvtxTrack_v2, SvtxTrack_v3, TrkrClusterv1, TrkrClusterv4, TrkrClusterv5, SvtxTrack_v1, DecayFinderContainerBase, Jetv1, TrkrClusterv2, TrkrClusterv3, JetMap, CMFlashClusterv2, SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, PHG4Shower, PHHepMCGenEvent, CMFlashClusterv1, RawCluster, PHGeomIOTGeo, CMFlashClusterv3, SvtxAlignmentState, JetContainer, TrackSeed, sPHElectronPairContainerv1, PHGenIntegralv1, SyncObject, TrackStateInfo, EventHeaderv2, CMFlashDifferencev1, MvtxEventInfo, MvtxEventInfov1, MvtxEventInfov2, PdbParameterMap, DecayFinderContainer_v1, GlobalVertexv2, TrackSeed_v1, sPHElectronPairContainer, GlobalVertexv1, PHG4ParticleSvtxMap, SvtxPHG4ParticleMap, SvtxTrackInfo, SvtxVertex, SvtxAlignmentStateMap, SvtxTrackCaloClusterMap, TrackSeedContainer, sPHElectronv1, PdbCalBank, PgPostBankWrapper, FlagSavev1, SvtxVertexMap_v1, JetMapv1, SvtxTrackMap, SvtxTrackSeed_v1, SvtxTrackSeed_v2, EventHeaderv1, RawClusterv1, Eventplaneinfov1, SvtxVertexMap, SvtxTrackMap_v1, SvtxTrackMap_v2, PHG4Showerv1, CdbUrlSavev1, SvtxVertex_v1, SvtxVertex_v2, Vertex, SvtxTrackCaloClusterMap_v1, TrackSeed_FastSim_v1, TrackSeedContainer_v1, sPHElectronPairv1, PHHepMCGenEventv1, SvtxTrackState_v1, SvtxTrackState_v2, sPHElectronPair, CdbUrlSave, Eventplaneinfo, InttVertexv1, SvtxAlignmentState_v1, SvtxTrackState, sPHElectron, RunHeader, SyncObjectv1, MbdVertexv1, MbdVertexv2, BbcVertexv1, BbcVertexv2, SvtxAlignmentStateMap_v1, TowerInfoContainerv1, TowerInfoContainerv2, TowerInfoContainerv3, PHG4ParticleSvtxMap_v1, MbdVertex, InttVertex, BbcVertex, and SvtxPHG4ParticleMap_v1.
Definition at line 12 of file PHObject.cc.
View newest version in sPHENIX GitHub at line 12 of file PHObject.cc
References PHWHERE.
Referenced by SubtractTowers::CreateNode(), CaloTowerCalib::CreateNodeTree(), PHFieldUtility::GetFieldConfigNode(), PHNodeIntegrate::perform(), FilterEventsUpsilon::process_event(), FilterEvents::process_event(), and PHTruthClustering::process_event().
void PHObject::Copy (TObject & object) const final
Definition at line 75 of file PHObject.cc.
View newest version in sPHENIX GitHub at line 75 of file PHObject.cc
References PHWHERE.
void PHObject::CopyFrom (const PHObject * obj) virtual
Reimplemented in PHGenIntegralv1, PHG4Cell, PHG4HitEval, PHG4Hit, and EicEventHeader.
Definition at line 60 of file PHObject.cc.
View newest version in sPHENIX GitHub at line 60 of file PHObject.cc
References PHWHERE.
Referenced by PHNodeIntegrate::perform().
void PHObject::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented in Jet, EmbRecoMatchv1, TrkrTruthTrack, SvtxTrackInfo_v1, CylinderGeomIntt, Jetv2, BbcPmtHit, MbdPmtHit, PHG4CylinderGeomv4, EmbRecoMatchContainer, TrkrTruthTrackv1, SvtxTrack, PHFieldConfigv1, PHFieldConfigv2, MbdPmtHitV1, ClusHitsVerbose, PHG4TruthInfoContainer, RawTower, BbcPmtHitV1, TrkrClusterContainer, ClusHitsVerbosev1, PHG4VtxPointv1, EventHeaderv2, GlobalVertex, CylinderGeomMicromegas, RawHitSet, TrkrHitTruthAssoc, RawCluster, CylinderGeom_Mvtx, TrkrTruthTrackContainer, PHGeomIOTGeo, CMFlashClusterContainer, CMFlashDifferenceContainer, TrkrClusterContainerv1, TrkrHitSet, CMFlashClusterContainerv1, CMFlashDifferenceContainerv1, MvtxEventInfo, MvtxEventInfov1, MvtxEventInfov2, PHG4GDMLConfig, TrackPidAssoc, PHG4Cell, PHG4CylinderGeom_Spacalv1, TpcPrototypeCluster, PHHepMCGenEventMap, ParticleFlowElement, SvtxTrack_v4, PHG4HitContainer, ParticleFlowElementContainer, PHGeomTGeo, TpcTpotEventInfo, SvtxTrack_FastSim, SvtxTrack_v2, SvtxTrack_v3, TrackStateInfo_v1, FlagSavev1, KFParticle_Container, TpcSpaceChargeMatrixContainer, RawHitTpc, RawHitv1, TrkrCluster, TrkrClusterv1, TrkrClusterv4, TrkrClusterv5, TrkrHitv2, SvtxTrack_v1, PHG4Shower, EmbRecoMatchContainerv1, PHGenIntegralv1, RawTowerGeomContainer, JetMap, Jetv1, TPC_RawHit, RawHit, RawHitSetContainerv1, TrkrClusterCrossingAssocv1, TrkrClusterv2, TrkrClusterv3, TrkrHit, TrkrHitSetContainerv1, PHG4CylinderCellContainer, PHG4ScintillatorSlatContainer, EventHeaderv1, RawTowerContainer, TpcSpaceChargeMatrixContainerv1, CMFlashClusterv2, TrkrClusterHitAssocv1, TrkrClusterHitAssocv3, TrkrClusterIterationMapv1, TrkrHitTruthAssocv1, PHG4CylinderGeom_Spacalv2, PHG4CylinderGeom_Spacalv3, TrkrTruthTrackContainerv1, CdbUrlSavev1, DecayFinderContainerBase, CMFlashClusterv1, TrkrClusterHitAssocv2, SvtxTrack_FastSim_v1, PHG4CellContainer, PHG4CylinderCellGeom_Spacalv1, PHG4EventHeader, TowerInfoContainer, JetContainer, CMFlashCluster, CMFlashClusterv3, CMFlashDifference, RawHitSetv1, TpcTpotEventInfov1, TrkrHitSetv1, SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, CdbUrlSave, FlagSave, SyncObjectv1, EventplaneinfoMap, TrkrHitv1, PHHepMCGenEvent, EventHeader, RawClusterContainer, BbcOutV1, BbcOutV2, MbdOutV1, PHFieldConfig, SvtxAlignmentState, PHG4CylinderGeomContainer, PHG4CylinderGeomv1, PidInfoContainer, RunHeader, InttSurveyMap, CMFlashDifferencev1, TrkrClusterContainerv2, TrkrClusterContainerv3, TrkrClusterContainerv4, TrackSeed, PHG4BlockCellGeomContainer, PHG4BlockGeomContainer, PHG4CylinderCellGeomContainer, PHG4TpcCylinderGeomContainer, RawTower_Prototype3, RawTower_Prototype4, SyncObject, RawClusterv1, RawTowerv1, RawTowerv2, BbcPmtContainerV1, MbdOutV2, MbdPmtContainerV1, ParticleFlowElementv1, TrackStateInfo, PHG4EventHeaderv1, RawTower_Prototype2, RawTower_Prototype4, sPHElectronPairContainerv1, DecayFinderContainer_v1, GlobalVertexv2, PHG4CylinderGeomv2, PHG4CylinderGeomv3, MvtxRawEvtHeaderv1, RawTowerGeomContainerv1, GlobalVertexv1, PHG4Cellv1, PHG4CylinderCell, RawTower_Temperature, RawTower_Temperature, RawTower_Temperature, MicromegasRawHitv1, TpcRawHitv1, RawTowerGeomContainer_Cylinderv1, TowerInfoContainerv1, TowerInfoContainerv2, TowerInfoContainerv3, BbcPmtContainer, MbdPmtContainer, TrackSeed_v1, AssocInfoContainerv1, PHG4CylinderCellv1, PHG4Showerv1, RawTower_Temperature, sPHElectronv1, PidInfo, Gl1RawHitv1, Eventplaneinfov1, Vertex, JetMapv1, BbcPmtInfoV1, InttEventInfov1, PHG4ParticleSvtxMap, SvtxAlignmentStateMap, SvtxPHG4ParticleMap, SvtxTrackCaloClusterMap, SvtxTrackInfo, TrackSeedContainer, PHG4BlockGeomv1, PHG4ScintillatorSlatv1, PHG4TpcCylinderGeom, PHG4Hit, PHG4Particlev2, PidCandidatev1, InttRawHitContainerv1, InttRawHitv1, MicromegasRawHitContainerv1, MvtxRawHitContainerv1, MvtxRawHitv1, TpcRawHitContainerv1, RawTowerDeadMap, GlobalVertexMap, SvtxVertex, SvtxVertexMap_v1, InttSurveyMapv1, InttEventInfo, SvtxTrackMap, PHG4CylinderCellGeom, PHG4CylinderGeom, PHG4ScintillatorSlat, G4RootScintillatorTower, InttDeadMapv1, EicEventHeader, PHG4Hitv1, PHG4InEvent, PHG4Particlev3, sPHElectronPairContainer, RawTowerDeadMapv1, RawTowerGeomv4, GlobalVertexMapv1, MbdVertexMap, SvtxVertex_v1, SvtxVertex_v2, SvtxVertexMap, InttVertexMap, BbcOut, BbcVertexMap, MbdOut, SvtxTrackMap_v1, SvtxTrackMap_v2, SvtxTrackSeed_v1, SvtxTrackSeed_v2, TrackInfoContainer_v1, AssocInfoContainer, PHG4BlockCellGeom, PHG4Particlev1, sPHElectronPairv1, RunHeaderv1, EventplaneinfoMapv1, InttMaskedChannelSet, InttMaskedChannelSetv1, SvtxTrackCaloClusterMap_v1, SvtxTrackState_v1, SvtxTrackState_v2, TrackSeedContainer_v1, PHG4BlockGeom, G4RootScintillatorSlat, G4RootScintillatorTowerContainer, InttDeadMap, sPHElectronPair, PidInfo_RICH_v1, RawTowerGeomv1, RawTowerGeomv3, MbdVertexMapv1, InttVertexMapv1, InttVertexv1, BbcVertexMapv1, TrackInfoContainer, PHG4CylinderCellv2, G4RootHitContainer, G4RootRawTowerContainer, G4RootScintillatorSlatContainer, PHG4Particle, RawTowerGeom, RawTowerGeomv2, CentralityInfo, Eventplaneinfo, SvtxAlignmentState_v1, TrackSeed_FastSim_v1, VariableArrayContainer, PHG4CylinderCellv3, G4RootRawTower, PHG4VtxPoint, sPHElectron, MbdVertex, MbdVertexv1, MbdVertexv2, InttVertex, BbcVertex, BbcVertexv1, BbcVertexv2, PHG4ParticleSvtxMap_v1, PHHepMCGenEventv1, CentralityInfov1, CentralityInfov2, TowerBackgroundv1, SvtxAlignmentStateMap_v1, SvtxPHG4ParticleMap_v1, SvtxTrackState, MinimumBiasInfov1, VariableArray, PidCandidate, CaloTriggerInfov1, TowerBackground, JetContainerv1, CaloTriggerInfo, and MinimumBiasInfo.
Definition at line 26 of file PHObject.cc.
View newest version in sPHENIX GitHub at line 26 of file PHObject.cc
Referenced by InttClusterizer::ClusterLadderCells(), InttClusterizer::ClusterLadderCellsRaw(), MvtxPrototype2Clusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtxRaw(), PHGenIntegralv1::CopyFrom(), PHPythia8::create_node_tree(), PHPythia8::End(), HFFastSim::End(), Fun4AllStreamingInputManager::FillGl1(), PHGenIntegralv1::Integrate(), MvtxUnpackPRDF::MakeHits(), Fun4AllServer::NodeIdentify(), TpcPrototypeClusterizer::process_event(), StreamingCheck::process_event(), TpcCheck::process_event(), InttRawDataDecoder::process_event(), MvtxUnpackPRDF::process_event(), MvtxCombinedRawDataDecoder::process_event(), DumpTrkrClusterHitAssoc::process_Node(), RawTowerDigitizer::simple_photon_digitization(), and RawTowerDigitizer::sipm_photon_digitization().
virtual int PHObject::Integrate () const inline virtual
Reimplemented in PHGenIntegralv1.
Definition at line 39 of file PHObject.h.
View newest version in sPHENIX GitHub at line 39 of file PHObject.h
Referenced by PHNodeIntegrate::perform().
virtual int PHObject::Integrate (PHObject *) inline virtual
Reimplemented in PHGenIntegralv1.
Definition at line 40 of file PHObject.h.
View newest version in sPHENIX GitHub at line 40 of file PHObject.h
int PHObject::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented in Jet, Jetv2, BbcPmtHit, MbdPmtHit, PHFieldConfigv1, PHFieldConfigv2, SvtxTrack, MbdPmtHitV1, BbcPmtHitV1, PHGeomIOTGeo, GlobalVertex, PHGeomTGeo, MvtxEventInfo, MvtxEventInfov1, MvtxEventInfov2, TPC_RawHit, PHHepMCGenEventMap, RawTower, TpcTpotEventInfo, TpcTpotEventInfov1, TpcPrototypeCluster, RawHitTpc, RawHitv1, TrkrCluster, TrkrHitv2, SvtxTrack_v4, PHG4EventHeader, KFParticle_Container, ParticleFlowElement, RawHit, TrkrHit, SvtxTrack_FastSim, SvtxTrack_v2, SvtxTrack_v3, PHG4Shower, FlagSave, RawCluster, TrkrClusterv1, TrkrClusterv4, TrkrClusterv5, SvtxTrack_v1, PHG4GDMLConfig, EventHeaderv1, DecayFinderContainerBase, Jetv1, TrkrClusterv2, TrkrClusterv3, SvtxTrack_FastSim_v1, CdbUrlSavev1, JetMap, ParticleFlowElementContainer, CMFlashCluster, CMFlashClusterv2, CMFlashDifference, CMFlashClusterv1, TrkrHitv1, PHGenIntegralv1, CdbUrlSave, SyncObjectv1, CMFlashClusterv3, SvtxAlignmentState, SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, PHHepMCGenEvent, EventHeader, RawTowerContainer, JetContainer, BbcOutV1, BbcOutV2, MbdOutV1, TrackSeed, RunHeader, TrackStateInfo, FlagSavev1, SyncObject, BbcPmtContainer, BbcPmtContainerV1, MbdOutV2, MbdPmtContainer, MbdPmtContainerV1, CMFlashDifferencev1, PHG4EventHeaderv1, sPHElectronPairContainerv1, DecayFinderContainer_v1, ParticleFlowElementv1, MvtxRawEvtHeaderv1, RawClusterContainer, GlobalVertexv2, PidInfoContainer, GlobalVertexv1, BbcOut, BbcPmtInfoV1, MbdOut, PHG4ParticleSvtxMap, SvtxPHG4ParticleMap, SvtxTrackInfo, PHG4Showerv1, RawTower_Prototype3, RawTower_Prototype4, RawClusterv1, RawTowerv1, RawTowerv2, SvtxVertex, SvtxAlignmentStateMap, SvtxTrackCaloClusterMap, TrackSeed_v1, TrackSeedContainer, RawTower_Prototype2, RawTower_Prototype4, sPHElectronPairContainer, sPHElectronv1, InttRawHitContainerv1, MicromegasRawHitContainerv1, MvtxRawHitContainerv1, TpcRawHitContainerv1, SvtxVertexMap_v1, Vertex, JetMapv1, SvtxTrackMap, RawTowerGeomContainerv1, SvtxVertexMap, SvtxTrackMap_v1, SvtxTrackMap_v2, RawTower_Temperature, RawTower_Temperature, RawTower_Temperature, GlobalVertexMap, GlobalVertexMapv1, SvtxVertex_v1, SvtxVertex_v2, SvtxTrackCaloClusterMap_v1, SvtxTrackSeed_v1, SvtxTrackSeed_v2, TrackSeedContainer_v1, RawTower_Temperature, sPHElectronPairv1, PidInfo, MbdVertexMap, InttVertexMap, BbcVertexMap, SvtxTrackState_v1, SvtxTrackState_v2, sPHElectronPair, RunHeaderv1, MbdVertexMapv1, InttVertexMapv1, InttVertexv1, BbcVertexMapv1, G4RootScintillatorTower, RawTowerDeadMap, RawTowerDeadMapv1, SvtxAlignmentState_v1, SvtxTrackState, TrackSeed_FastSim_v1, MinimumBiasInfov1, InttDeadMapv1, sPHElectron, PHHepMCGenEventv1, CentralityInfo, MbdVertex, MbdVertexv1, MbdVertexv2, InttVertex, BbcVertex, BbcVertexv1, BbcVertexv2, SvtxAlignmentStateMap_v1, G4RootScintillatorSlat, InttDeadMap, CentralityInfov1, TowerBackgroundv1, PHG4ParticleSvtxMap_v1, PidInfo_RICH_v1, SvtxPHG4ParticleMap_v1, CaloTriggerInfov1, G4RootRawTower, TowerBackground, MinimumBiasInfo, and CaloTriggerInfo.
Definition at line 49 of file PHObject.cc.
View newest version in sPHENIX GitHub at line 49 of file PHObject.cc
References PHWHERE.
Referenced by DumpBbcPmtInfoContainer::process_Node(), and DumpPHFieldConfig::process_Node().
void PHObject::Reset () virtual
Clear Event.
Reimplemented in FullJetFinder::Container, MicromegasCombinedDataEvaluation::Container, MicromegasRawDataEvaluation::Container, TpcSpaceChargeMatrixContainer, SvtxTrackInfo_v1, TpcSpaceChargeMatrixContainerv1, Jetv2, PHFieldConfigv1, PHFieldConfigv2, RawHitSet, PHGeomIOTGeo, TrkrHitSet, PHG4TruthInfoContainer, TrkrClusterContainer, TrackEvaluationContainerv1, PHParameters, TPC_RawHit, PHG4Cell, PHHepMCGenEventMap, PHGeomTGeo, TpcTpotEventInfo, TrkrHitTruthAssoc, TrackStateInfo_v1, TpcPrototypeCluster, RawTower, RawHitSetContainer, RawHitTpc, RawHitv1, TrkrCluster, TrkrClusterContainerv1, TrkrHitSetContainer, TrkrHitv2, SvtxTrack_v4, KFParticle_Container, CMFlashClusterContainer, CMFlashClusterContainerv1, CMFlashDifferenceContainer, CMFlashDifferenceContainerv1, RawHit, TrkrHit, SvtxTrack_FastSim, SvtxTrack_v2, SvtxTrack_v3, PHG4Shower, TrackPidAssoc, EventHeaderv2, TrkrClusterv1, TrkrClusterv4, TrkrClusterv5, SvtxTrack_v1, PHGenIntegralv1, DecayFinderContainerBase, Jetv1, TrkrClusterv2, TrkrClusterv3, PHG4CylinderCellContainer, PHG4ScintillatorSlatContainer, PHG4HitContainer, ParticleFlowElementContainer, CMFlashCluster, CMFlashClusterv2, CMFlashDifference, MvtxEventInfo, MvtxEventInfov1, MvtxEventInfov2, SvtxTrack_FastSim_v1, PdbParameterMap, TowerInfoContainer, MbdGeom, CMFlashClusterv1, RawHitSetv1, TpcTpotEventInfov1, TrkrClusterCrossingAssoc, TrkrHitSetv1, TrkrHitv1, PHG4GDMLConfig, EMCalTrk, MCPhoton, PhotonPair, RawCluster, CMFlashClusterv3, RawHitSetContainerv1, TrkrClusterCrossingAssocv1, TrkrClusterHitAssoc, TrkrClusterIterationMap, TrkrHitSetContainerv1, SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, UpsilonPair, RawTowerContainer, TrkrClusterHitAssocv1, TrkrClusterHitAssocv3, TrkrClusterIterationMapv1, TrkrHitTruthAssocv1, PHG4CellContainer, MySimpleTree, PHHepMCGenEvent, TrkrClusterHitAssocv2, FlagSavev1, CMFlashDifferencev1, PHG4ParticleSvtxMap, SvtxPHG4ParticleMap, EventHeaderv1, DecayFinderContainer_v1, ParticleFlowElementv1, sPHElectronPairContainerv1, CdbUrlSavev1, RawClusterContainer, RawTowerGeomContainer_Cylinderv1, GlobalVertexv2, BbcPmtContainer, MbdPmtContainer, PidInfoContainer, TowerInfoContainerv1, TowerInfoContainerv2, TowerInfoContainerv3, GlobalVertexv1, MbdGeomV1, TrkrClusterContainerv2, TrkrClusterContainerv3, TrkrClusterContainerv4, PHG4Cellv1, PHG4Hit, PHG4Showerv1, RawTower_Prototype3, RawTower_Prototype4, PdbParameterMapContainer, CdbUrlSave, SyncObjectv1, RawTowerv1, RawTowerv2, TrackSeed_v1, EicEventHeader, TrkrTruthTrackContainer, RawTower_Prototype2, RawTower_Prototype4, PidCandidatev1, sPHElectronv1, RawClusterv1, Eventplaneinfov1, SvtxVertexMap_v1, JetMapv1, BbcOut, BbcOutV1, BbcOutV2, MbdOut, MbdOutV1, InttEventInfov1, VariableArray, MyTClonesArray, sPHElectronPairContainer, EventHeader, RunHeader, RawTowerGeomContainerv1, InttEventInfo, TpcSeedTrackMapv1, SvtxTrackMap_v1, SvtxTrackMap_v2, TrackInfoContainer, TrackInfoContainer_v1, AssocInfoContainerv1, PHG4EventHeader, PHG4Hitv1, PHG4InEvent, EmbRecoMatchContainer, RawTower_Temperature, RawTower_Temperature, RawTower_Temperature, SyncObject, GlobalVertexMapv1, SvtxVertex_v1, SvtxVertex_v2, BbcPmtContainerV1, MbdOutV2, MbdPmtContainerV1, ClusHitsVerbosev1, SvtxTrackCaloClusterMap_v1, SvtxTrackSeed_v1, SvtxTrackSeed_v2, TrackSeedContainer_v1, PHG4EventHeaderv1, TrkrTruthTrackContainerv1, RawTower_Temperature, PidCandidate, sPHElectronPairv1, PidInfo, FlagSave, EventplaneinfoMapv1, BbcPmtInfoContainerV1, TpcSeedTrackMap, PHG4ParticleSvtxMap_v1, SvtxTrackState_v1, SvtxTrackState_v2, VariableArrayContainer, EicEventHeaderv1, sPHElectronPair, MvtxRawEvtHeaderv1, MbdVertexMapv1, InttVertexMapv1, InttVertexv1, BbcVertexMapv1, ClusHitsVerbose, SvtxPHG4ParticleMap_v1, G4RootHitContainer, G4RootRawTowerContainer, G4RootScintillatorSlatContainer, G4RootScintillatorTower, RunHeaderv1, Gl1RawHitv1, RawTowerDeadMap, RawTowerDeadMapv1, SvtxAlignmentState_v1, TrackSeed_FastSim_v1, G4RootScintillatorTowerContainer, InttDeadMapv1, sPHElectron, MbdVertexv1, MbdVertexv2, BbcVertexv1, BbcVertexv2, MbdPmtHitV1, SvtxAlignmentStateMap_v1, MinimumBiasInfov1, G4RootScintillatorSlat, PHHepMCGenEventv1, InttRawHitContainerv1, MicromegasRawHitContainerv1, MvtxRawHitContainerv1, TpcRawHitContainerv1, TowerInfov1, CentralityInfov1, CentralityInfov2, TowerBackgroundv1, JetContainerv1, BbcPmtHitV1, BbcPmtInfoV1, PidInfo_RICH_v1, TowerInfov3, CaloTriggerInfov1, G4RootRawTower, TowerInfov2, TowerInfo, TrainingHits, TrainingHitsContainer, MinimumBiasInfo, EmbRecoMatchContainerv1, and SubjetIndicesv1.
Definition at line 31 of file PHObject.cc.
View newest version in sPHENIX GitHub at line 31 of file PHObject.cc
References PHWHERE.
Referenced by RawTowerCombiner::CreateNodes(), KFParticle_DST::fillParticleNode_Track(), PHCosmicSiliconPropagator::process_event(), TrackSeedTrackMapConverter::process_event(), FilterEventsUpsilon::process_event(), FilterEvents::process_event(), PHTruthSiliconAssociation::process_event(), PHSimpleKFProp::process_event(), and PHGenFitTrkFitter::process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/phool/PHObject.h
coresoftware/blob/master/offline/framework/phool/PHObject.cc