Analysis Software: PHTruthClustering Class Reference
PHTruthClustering Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHTruthClustering.h>
Public Member Functions
PHTruthClustering (const std::string &name="PHTruthClustering")
~PHTruthClustering () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void UsePrimaryTrackClustersOnly (bool flag)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
fetch node pointers
std::map< TrkrDefs::cluskey,
TrkrCluster * > all_truth_clusters (PHG4Particle *particle)
std::set< PHG4Hit * > all_truth_hits (PHG4Particle *particle)
void LayerClusterG4Hits (std::set< PHG4Hit * > truth_hits, std::vector< PHG4Hit * > &contributing_hits, std::vector< double > &contributing_hits_energy, std::vector< std::vector< double >> &contributing_hits_entry, std::vector< std::vector< double >> &contributing_hits_exit, float layer, float &x, float &y, float &z, float &t, float &e)
void G4ClusterSize (TrkrDefs::cluskey &ckey, unsigned int layer, std::vector< std::vector< double >> contributing_hits_entry, std::vector< std::vector< double >> contributing_hits_exit, float &g4phisize, float &g4zsize)
float line_circle_intersection (float x[], float y[], float z[], float radius)
unsigned int getTpcSector (double x, double y)
unsigned int getAdcValue (double gedep)
Private Attributes
int iclus = 0
TrkrClusterContainer * _reco_cluster_map {nullptr}
PHG4TruthInfoContainer * _g4truth_container {nullptr}
PHG4HitContainer * _g4hits_svtx {nullptr}
PHG4HitContainer * _g4hits_mms {nullptr}
PHG4HitContainer * _g4hits_tracker {nullptr}
PHG4HitContainer * _g4hits_maps {nullptr}
PHG4TpcCylinderGeomContainer * _tpc_geom_container {nullptr}
PHG4CylinderGeomContainer * _intt_geom_container {nullptr}
PHG4CylinderGeomContainer * _mvtx_geom_container {nullptr}
PHG4CylinderGeomContainer * _mms_geom_container {nullptr}
ActsGeometry * _tgeometry {nullptr}
const unsigned int _nlayers_maps = 3
const unsigned int _nlayers_intt = 4
const unsigned int _nlayers_tpc = 48
const unsigned int _nlayers_mms = 2
double clus_err_rphi [57] = {0}
double clus_err_z [57] = {0}
double mvtx_clus_err_rphi = 5e-04
double mvtx_clus_err_z = 5e-04
double intt_clus_err_rphi = 25e-04
double intt_clus_err_z = 1.0
double tpc_inner_clus_err_rphi = 200e-04
double tpc_inner_clus_err_z = 750e-04
double tpc_outer_clus_err_rphi = 150e-04
double tpc_outer_clus_err_z = 500e-04
double mms_layer55_clus_err_rphi = 100e-04
double mms_layer55_clus_err_z = 25.0
double mms_layer56_clus_err_rphi = 12.5
double mms_layer56_clus_err_z = 200e-04
bool _primary_clusters_only = false
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 36 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 36 of file PHTruthClustering.h
Constructor & Destructor Documentation
PHTruthClustering::PHTruthClustering (const std::string & name = "PHTruthClustering")
Definition at line 63 of file PHTruthClustering.cc.
View newest version in sPHENIX GitHub at line 63 of file PHTruthClustering.cc
PHTruthClustering::~PHTruthClustering () override
Definition at line 68 of file PHTruthClustering.cc.
View newest version in sPHENIX GitHub at line 68 of file PHTruthClustering.cc
Member Function Documentation
std::map< TrkrDefs::cluskey, TrkrCluster * > PHTruthClustering::all_truth_clusters (PHG4Particle * particle) private
Definition at line 239 of file PHTruthClustering.cc.
View newest version in sPHENIX GitHub at line 239 of file PHTruthClustering.cc
References _nlayers_intt, _nlayers_maps, _nlayers_mms, _nlayers_tpc, all_truth_hits(), clus_err_rphi, clus_err_z, Jetscape::ERR, G4ClusterSize(), TrkrDefs::genClusKey(), TpcDefs::genClusKey(), InttDefs::genClusKey(), MvtxDefs::genClusKey(), MicromegasDefs::genHitSetKey(), PHG4Particle::get_track_id(), getAdcValue(), getTpcSector(), gx, gy, gz, iclus, layer, LayerClusterG4Hits(), PHWHERE, PHG4InttDefs::SEGMENTATION_PHI, tile(), and Fun4AllBase::Verbosity().
Referenced by process_event().
std::set< PHG4Hit * > PHTruthClustering::all_truth_hits (PHG4Particle * particle) private
Definition at line 925 of file PHTruthClustering.cc.
View newest version in sPHENIX GitHub at line 925 of file PHTruthClustering.cc
References _g4hits_maps, _g4hits_mms, _g4hits_svtx, _g4hits_tracker, PHG4Particle::get_track_id(), PHG4Hit::get_trkid(), and PHG4HitContainer::getHits().
Referenced by all_truth_clusters().
int PHTruthClustering::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 1120 of file PHTruthClustering.cc.
View newest version in sPHENIX GitHub at line 1120 of file PHTruthClustering.cc
References Fun4AllReturnCodes::EVENT_OK.
void PHTruthClustering::G4ClusterSize (TrkrDefs::cluskey & ckey, unsigned int layer, std::vector< std::vector< double >> contributing_hits_entry, std::vector< std::vector< double >> contributing_hits_exit, float & g4phisize, float & g4zsize) private
Definition at line 712 of file PHTruthClustering.cc.
View newest version in sPHENIX GitHub at line 712 of file PHTruthClustering.cc
References _intt_geom_container, _mvtx_geom_container, _tgeometry, _tpc_geom_container, double(), Acts::UnitConstants::e, CylinderGeomIntt::find_indices_from_world_location(), CylinderGeomIntt::find_strip_index_values(), CylinderGeom_Mvtx::get_local_from_world_coords(), CylinderGeomIntt::get_local_from_world_coords(), PHG4TpcCylinderGeom::get_phibin(), PHG4TpcCylinderGeom::get_phistep(), CylinderGeom_Mvtx::get_pixel_from_local_coords(), CylinderGeom_Mvtx::get_pixel_x(), CylinderGeom_Mvtx::get_pixel_z(), PHG4TpcCylinderGeom::get_radius(), CylinderGeom_Mvtx::get_sensor_indices_from_world_coords(), CylinderGeomIntt::get_strip_y_spacing(), CylinderGeomIntt::get_strip_z_spacing(), PHG4TpcCylinderGeom::get_zbin(), PHG4TpcCylinderGeom::get_zstep(), TrkrDefs::getHitSetKeyFromClusKey(), PHG4TpcCylinderGeomContainer::GetLayerCellGeom(), PHG4CylinderGeomContainer::GetLayerGeom(), ActsSurfaceMaps::getSiliconSurface(), G4CEMCALBEDO::inner_radius, ActsGeometry::maps(), G4HCALOUT::outer_radius, parse_cmake_options::rows, surf(), and swap().
Referenced by all_truth_clusters().
unsigned int PHTruthClustering::getAdcValue (double gedep) private
Definition at line 1035 of file PHTruthClustering.cc.
View newest version in sPHENIX GitHub at line 1035 of file PHTruthClustering.cc
References CF4_dEdx, CF4_NTotal, Ne_dEdx, and Ne_NTotal.
Referenced by all_truth_clusters().
int PHTruthClustering::GetNodes (PHCompositeNode * topNode) private
fetch node pointers
Definition at line 1062 of file PHTruthClustering.cc.
View newest version in sPHENIX GitHub at line 1062 of file PHTruthClustering.cc
References _g4hits_maps, _g4hits_mms, _g4hits_svtx, _g4hits_tracker, _g4truth_container, _intt_geom_container, _mms_geom_container, _mvtx_geom_container, _reco_cluster_map, _tgeometry, _tpc_geom_container, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHCompositeNode::PHCompositeNode(), and PHWHERE.
Referenced by InitRun().
unsigned int PHTruthClustering::getTpcSector (double x, double y) private
Definition at line 1028 of file PHTruthClustering.cc.
View newest version in sPHENIX GitHub at line 1028 of file PHTruthClustering.cc
References ActsTests::PropagationDatasets::phi.
Referenced by all_truth_clusters().
int PHTruthClustering::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 73 of file PHTruthClustering.cc.
View newest version in sPHENIX GitHub at line 73 of file PHTruthClustering.cc
References _nlayers_intt, _nlayers_maps, _nlayers_tpc, clus_err_rphi, clus_err_z, Fun4AllReturnCodes::EVENT_OK, GetNodes(), intt_clus_err_rphi, intt_clus_err_z, layer, mms_layer55_clus_err_rphi, mms_layer55_clus_err_z, mms_layer56_clus_err_rphi, mms_layer56_clus_err_z, mvtx_clus_err_rphi, mvtx_clus_err_z, tpc_inner_clus_err_rphi, tpc_inner_clus_err_z, tpc_outer_clus_err_rphi, tpc_outer_clus_err_z, and Fun4AllBase::Verbosity().
void PHTruthClustering::LayerClusterG4Hits (std::set< PHG4Hit * > truth_hits, std::vector< PHG4Hit * > & contributing_hits, std::vector< double > & contributing_hits_energy, std::vector< std::vector< double >> & contributing_hits_entry, std::vector< std::vector< double >> & contributing_hits_exit, float layer, float & x, float & y, float & z, float & t, float & e) private
Definition at line 429 of file PHTruthClustering.cc.
View newest version in sPHENIX GitHub at line 429 of file PHTruthClustering.cc
References _nlayers_intt, _nlayers_maps, _nlayers_tpc, _tpc_geom_container, PHG4Hit::get_avg_t(), PHG4Hit::get_avg_x(), PHG4Hit::get_avg_y(), PHG4Hit::get_avg_z(), PHG4Hit::get_edep(), PHG4Hit::get_layer(), PHG4TpcCylinderGeom::get_radius(), PHG4TpcCylinderGeom::get_thickness(), PHG4Hit::get_x(), PHG4Hit::get_y(), PHG4Hit::get_z(), PHG4TpcCylinderGeomContainer::GetLayerCellGeom(), gr, gx, gy, gz, line_circle_intersection(), swap(), and Fun4AllBase::Verbosity().
Referenced by all_truth_clusters().
float PHTruthClustering::line_circle_intersection (float x[], float y[], float z[], float radius) private
Definition at line 992 of file PHTruthClustering.cc.
View newest version in sPHENIX GitHub at line 992 of file PHTruthClustering.cc
References A, C, Acts::UnitConstants::e, PHWHERE, and t.
Referenced by LayerClusterG4Hits().
int PHTruthClustering::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 119 of file PHTruthClustering.cc.
View newest version in sPHENIX GitHub at line 119 of file PHTruthClustering.cc
References _primary_clusters_only, _reco_cluster_map, Fun4AllReturnCodes::ABORTRUN, all_truth_clusters(), PHObject::CloneMe(), Fun4AllReturnCodes::EVENT_OK, PHG4Particle::get_parent_id(), PHG4Particle::get_pid(), PHG4Particle::get_primary_id(), PHG4Particle::get_track_id(), geta, TrkrClusterContainer::getClusters(), TrkrClusterContainer::getHitSetKeys(), TrkrDefs::getLayer(), PHG4TruthInfoContainer::GetParticleRange(), PHG4TruthInfoContainer::GetPrimaryParticle(), TrkrDefs::getTrkrId(), gflavor, gpos, gr, gtrackID, gx, gy, gz, TrkrCluster::identify(), PHG4TruthInfoContainer::isEmbeded(), layer, ng4hits, PHWHERE, TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
void PHTruthClustering::UsePrimaryTrackClustersOnly (bool flag) inline
Definition at line 46 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 46 of file PHTruthClustering.h
References _primary_clusters_only.
Member Data Documentation
PHG4HitContainer* PHTruthClustering::_g4hits_maps {nullptr} private
Definition at line 72 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 72 of file PHTruthClustering.h
Referenced by all_truth_hits(), and GetNodes().
PHG4HitContainer* PHTruthClustering::_g4hits_mms {nullptr} private
Definition at line 70 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 70 of file PHTruthClustering.h
Referenced by all_truth_hits(), and GetNodes().
PHG4HitContainer* PHTruthClustering::_g4hits_svtx {nullptr} private
Definition at line 69 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 69 of file PHTruthClustering.h
Referenced by all_truth_hits(), and GetNodes().
PHG4HitContainer* PHTruthClustering::_g4hits_tracker {nullptr} private
Definition at line 71 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 71 of file PHTruthClustering.h
Referenced by all_truth_hits(), and GetNodes().
PHG4TruthInfoContainer* PHTruthClustering::_g4truth_container {nullptr} private
Definition at line 67 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 67 of file PHTruthClustering.h
Referenced by GetNodes().
PHG4CylinderGeomContainer* PHTruthClustering::_intt_geom_container {nullptr} private
Definition at line 75 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 75 of file PHTruthClustering.h
Referenced by G4ClusterSize(), and GetNodes().
PHG4CylinderGeomContainer* PHTruthClustering::_mms_geom_container {nullptr} private
Definition at line 77 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 77 of file PHTruthClustering.h
Referenced by GetNodes().
PHG4CylinderGeomContainer* PHTruthClustering::_mvtx_geom_container {nullptr} private
Definition at line 76 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 76 of file PHTruthClustering.h
Referenced by G4ClusterSize(), and GetNodes().
const unsigned int PHTruthClustering::_nlayers_intt = 4 private
Definition at line 80 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 80 of file PHTruthClustering.h
Referenced by all_truth_clusters(), InitRun(), and LayerClusterG4Hits().
const unsigned int PHTruthClustering::_nlayers_maps = 3 private
Definition at line 79 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 79 of file PHTruthClustering.h
Referenced by all_truth_clusters(), InitRun(), and LayerClusterG4Hits().
const unsigned int PHTruthClustering::_nlayers_mms = 2 private
Definition at line 82 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 82 of file PHTruthClustering.h
Referenced by all_truth_clusters().
const unsigned int PHTruthClustering::_nlayers_tpc = 48 private
Definition at line 81 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 81 of file PHTruthClustering.h
Referenced by all_truth_clusters(), InitRun(), and LayerClusterG4Hits().
bool PHTruthClustering::_primary_clusters_only = false private
Definition at line 100 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 100 of file PHTruthClustering.h
Referenced by process_event(), and UsePrimaryTrackClustersOnly().
TrkrClusterContainer* PHTruthClustering::_reco_cluster_map {nullptr} private
Definition at line 66 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 66 of file PHTruthClustering.h
Referenced by GetNodes(), and process_event().
ActsGeometry* PHTruthClustering::_tgeometry {nullptr} private
Definition at line 78 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 78 of file PHTruthClustering.h
Referenced by G4ClusterSize(), and GetNodes().
PHG4TpcCylinderGeomContainer* PHTruthClustering::_tpc_geom_container {nullptr} private
Definition at line 74 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 74 of file PHTruthClustering.h
Referenced by G4ClusterSize(), GetNodes(), and LayerClusterG4Hits().
double PHTruthClustering::clus_err_rphi[57] = {0} private
Definition at line 84 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 84 of file PHTruthClustering.h
Referenced by all_truth_clusters(), and InitRun().
double PHTruthClustering::clus_err_z[57] = {0} private
Definition at line 85 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 85 of file PHTruthClustering.h
Referenced by all_truth_clusters(), and InitRun().
int PHTruthClustering::iclus = 0 private
Definition at line 64 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 64 of file PHTruthClustering.h
Referenced by all_truth_clusters().
double PHTruthClustering::intt_clus_err_rphi = 25e-04 private
Definition at line 89 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 89 of file PHTruthClustering.h
Referenced by InitRun().
double PHTruthClustering::intt_clus_err_z = 1.0 private
Definition at line 90 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 90 of file PHTruthClustering.h
Referenced by InitRun().
double PHTruthClustering::mms_layer55_clus_err_rphi = 100e-04 private
Definition at line 95 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 95 of file PHTruthClustering.h
Referenced by InitRun().
double PHTruthClustering::mms_layer55_clus_err_z = 25.0 private
Definition at line 96 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 96 of file PHTruthClustering.h
Referenced by InitRun().
double PHTruthClustering::mms_layer56_clus_err_rphi = 12.5 private
Definition at line 97 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 97 of file PHTruthClustering.h
Referenced by InitRun().
double PHTruthClustering::mms_layer56_clus_err_z = 200e-04 private
Definition at line 98 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 98 of file PHTruthClustering.h
Referenced by InitRun().
double PHTruthClustering::mvtx_clus_err_rphi = 5e-04 private
Definition at line 87 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 87 of file PHTruthClustering.h
Referenced by InitRun().
double PHTruthClustering::mvtx_clus_err_z = 5e-04 private
Definition at line 88 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 88 of file PHTruthClustering.h
Referenced by InitRun().
double PHTruthClustering::tpc_inner_clus_err_rphi = 200e-04 private
Definition at line 91 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 91 of file PHTruthClustering.h
Referenced by InitRun().
double PHTruthClustering::tpc_inner_clus_err_z = 750e-04 private
Definition at line 92 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 92 of file PHTruthClustering.h
Referenced by InitRun().
double PHTruthClustering::tpc_outer_clus_err_rphi = 150e-04 private
Definition at line 93 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 93 of file PHTruthClustering.h
Referenced by InitRun().
double PHTruthClustering::tpc_outer_clus_err_z = 500e-04 private
Definition at line 94 of file PHTruthClustering.h.
View newest version in sPHENIX GitHub at line 94 of file PHTruthClustering.h
Referenced by InitRun().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHTruthClustering.h
coresoftware/blob/master/offline/packages/trackreco/PHTruthClustering.cc