Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Examples/Io/Csv/MeasurementReaderWriterTests.cpp File Reference
MeasurementReaderWriterTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/TrackParametrization.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Tests/CommonHelpers/WhiteBoardUtilities.hpp"
#include "Acts/Utilities/BinUtility.hpp"
#include "Acts/Utilities/Zip.hpp"
#include "ActsExamples/Digitization/DigitizationConfig.hpp"
#include "ActsExamples/Digitization/Smearers.hpp"
#include "ActsExamples/EventData/Cluster.hpp"
#include "ActsExamples/EventData/Measurement.hpp"
#include "ActsExamples/Io/Csv/CsvMeasurementReader.hpp"
#include "ActsExamples/Io/Csv/CsvMeasurementWriter.hpp"
#include <fstream>
#include <iostream>
#include <random>
Functions
BOOST_AUTO_TEST_CASE (CsvMeasurementRoundTrip)
Function Documentation
BOOST_AUTO_TEST_CASE (CsvMeasurementRoundTrip)
Definition at line 30 of file MeasurementReaderWriterTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file MeasurementReaderWriterTests.cpp
References KFPMath::a, Acts::Test::GenericReadWriteTool< val_tuple_t, str_tuple_t >::add(), KFPMath::b, Acts::PhysicalConstants::c, Acts::Test::cb, ActsExamples::Cluster::channels, CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::eBoundLoc0, Acts::eBoundLoc1, gen(), i, ActsExamples::CsvMeasurementWriter::Config::inputClusters, ActsExamples::CsvMeasurementReader::Config::inputDir, ActsExamples::CsvMeasurementWriter::Config::inputMeasurements, ActsExamples::CsvMeasurementWriter::Config::inputMeasurementSimHitsMap, Acts::UnitConstants::m, Acts::UnitConstants::m2, Acts::makeMeasurement(), ActsExamples::CsvMeasurementReader::Config::outputClusters, ActsExamples::CsvMeasurementWriter::Config::outputDir, ActsExamples::CsvMeasurementReader::Config::outputMeasurements, ActsExamples::CsvMeasurementReader::Config::outputMeasurementSimHitsMap, ActsExamples::CsvMeasurementReader::Config::outputSourceLinks, merge_hashes::p, summary::reader, size, ActsExamples::Cluster::sizeLoc0, ActsExamples::Cluster::sizeLoc1, Acts::Logging::WARNING, writer, and Acts::zip().