Analysis Software: TrkrTruthTrack Class Reference
TrkrTruthTrack Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4tracking/TrkrTruthTrack.h>
Classes
struct Comp
Public Member Functions
~TrkrTruthTrack () override=default
dtor
TrkrTruthTrack ()
virtual unsigned int getTrackid () const
virtual float getX0 () const
virtual float getY0 () const
virtual float getZ0 () const
virtual float getPseudoRapidity () const
virtual float getPt () const
virtual float getPhi () const
virtual std::vector
< TrkrDefs::cluskey > & getClusters ()
virtual void addCluster (TrkrDefs::cluskey)
virtual bool has_hitsetkey (TrkrDefs::hitsetkey) const
virtual bool has_hitsetkey (TrkrDefs::cluskey) const
virtual std::pair< bool,
TrkrDefs::cluskey > get_cluskey (TrkrDefs::hitsetkey) const
virtual void setTrackid (unsigned int)
virtual void setX0 (float)
virtual void setY0 (float)
virtual void setZ0 (float)
virtual void setPseudoRapity (float)
virtual void setPt (float)
virtual void setPhi (float)
void identify (std::ostream &os=std::cout) const override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
Definition at line 12 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 12 of file TrkrTruthTrack.h
Constructor & Destructor Documentation
TrkrTruthTrack::~TrkrTruthTrack () override default
dtor
TrkrTruthTrack::TrkrTruthTrack () inline
Definition at line 17 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 17 of file TrkrTruthTrack.h
Member Function Documentation
virtual void TrkrTruthTrack::addCluster (TrkrDefs::cluskey) inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 30 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 30 of file TrkrTruthTrack.h
Referenced by TpcClusterBuilder::cluster_hits(), PHG4InttHitReco::cluster_truthhits(), and PHG4MvtxHitReco::cluster_truthhits().
virtual std::pair<bool, TrkrDefs::cluskey> TrkrTruthTrack::get_cluskey (TrkrDefs::hitsetkey) const inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 34 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 34 of file TrkrTruthTrack.h
std::vector< TrkrDefs::cluskey > & TrkrTruthTrack::getClusters (void) virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 8 of file TrkrTruthTrack.cc.
View newest version in sPHENIX GitHub at line 8 of file TrkrTruthTrack.cc
Referenced by TrackClusEvaluator::addClusKeys().
virtual float TrkrTruthTrack::getPhi () const inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 27 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 27 of file TrkrTruthTrack.h
virtual float TrkrTruthTrack::getPseudoRapidity () const inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 25 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 25 of file TrkrTruthTrack.h
virtual float TrkrTruthTrack::getPt () const inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 26 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 26 of file TrkrTruthTrack.h
Referenced by TpcClusterBuilder::cluster_hits().
virtual unsigned int TrkrTruthTrack::getTrackid () const inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 19 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 19 of file TrkrTruthTrack.h
Referenced by TrkrTruthTrackContainerv1::addTruthTrack(), TpcClusterBuilder::cluster_hits(), and TrkrTruthTrack::Comp::operator()().
virtual float TrkrTruthTrack::getX0 () const inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 21 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 21 of file TrkrTruthTrack.h
virtual float TrkrTruthTrack::getY0 () const inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 22 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 22 of file TrkrTruthTrack.h
virtual float TrkrTruthTrack::getZ0 () const inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 23 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 23 of file TrkrTruthTrack.h
virtual bool TrkrTruthTrack::has_hitsetkey (TrkrDefs::hitsetkey) const inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 32 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 32 of file TrkrTruthTrack.h
virtual bool TrkrTruthTrack::has_hitsetkey (TrkrDefs::cluskey) const inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 33 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 33 of file TrkrTruthTrack.h
void TrkrTruthTrack::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in TrkrTruthTrackv1.
Definition at line 62 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 62 of file TrkrTruthTrack.h
References os.
virtual void TrkrTruthTrack::setPhi (float) inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 43 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 43 of file TrkrTruthTrack.h
virtual void TrkrTruthTrack::setPseudoRapity (float) inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 41 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 41 of file TrkrTruthTrack.h
virtual void TrkrTruthTrack::setPt (float) inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 42 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 42 of file TrkrTruthTrack.h
virtual void TrkrTruthTrack::setTrackid (unsigned int) inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 36 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 36 of file TrkrTruthTrack.h
virtual void TrkrTruthTrack::setX0 (float) inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 37 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 37 of file TrkrTruthTrack.h
virtual void TrkrTruthTrack::setY0 (float) inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 38 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 38 of file TrkrTruthTrack.h
virtual void TrkrTruthTrack::setZ0 (float) inline virtual
Reimplemented in TrkrTruthTrackv1.
Definition at line 39 of file TrkrTruthTrack.h.
View newest version in sPHENIX GitHub at line 39 of file TrkrTruthTrack.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4tracking/TrkrTruthTrack.h
coresoftware/blob/master/simulation/g4simulation/g4tracking/TrkrTruthTrack.cc