Analysis Software: MvtxRawHitv1 Class Reference
MvtxRawHitv1 Class Reference
#include <coresoftware/blob/master/offline/framework/ffarawobjects/MvtxRawHitv1.h>
Public Member Functions
MvtxRawHitv1 ()
MvtxRawHitv1 (MvtxRawHit *mvtxhit)
~MvtxRawHitv1 () override
void identify (std::ostream &os=std::cout) const override
uint64_t get_bco () const override
void set_bco (const uint64_t val) override
uint32_t get_strobe_bc () const override
void set_strobe_bc (const uint32_t val) override
uint32_t get_chip_bc () const override
void set_chip_bc (const uint32_t val) override
uint8_t get_layer_id () const override
void set_layer_id (uint8_t val) override
uint8_t get_stave_id () const override
void set_stave_id (uint8_t val) override
uint8_t get_chip_id () const override
void set_chip_id (uint8_t val) override
uint16_t get_row () const override
void set_row (uint16_t val) override
uint16_t get_col () const override
void set_col (uint16_t val) override
Public Member Functions inherited from MvtxRawHit
MvtxRawHit ()=default
virtual ~MvtxRawHit ()=default
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
uint64_t bco = std::numeric_limits<uint64_t>::max()
uint32_t strobe_bc = std::numeric_limits<uint32_t>::max()
uint32_t chip_bc = std::numeric_limits<uint32_t>::max()
uint8_t layer_id = std::numeric_limits<uint8_t>::max()
uint8_t stave_id = std::numeric_limits<uint8_t>::max()
uint8_t chip_id = std::numeric_limits<uint8_t>::max()
uint16_t row = std::numeric_limits<uint16_t>::max()
uint16_t col = std::numeric_limits<uint16_t>::max()
Detailed Description
Definition at line 9 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 9 of file MvtxRawHitv1.h
Constructor & Destructor Documentation
MvtxRawHitv1::MvtxRawHitv1 () inline
Definition at line 14 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 14 of file MvtxRawHitv1.h
MvtxRawHitv1::MvtxRawHitv1 (MvtxRawHit * mvtxhit)
Definition at line 3 of file MvtxRawHitv1.cc.
View newest version in sPHENIX GitHub at line 3 of file MvtxRawHitv1.cc
References MvtxRawHit::get_bco(), MvtxRawHit::get_chip_bc(), MvtxRawHit::get_chip_id(), MvtxRawHit::get_col(), MvtxRawHit::get_layer_id(), MvtxRawHit::get_row(), MvtxRawHit::get_stave_id(), MvtxRawHit::get_strobe_bc(), set_bco(), set_chip_bc(), set_chip_id(), set_col(), set_layer_id(), set_row(), set_stave_id(), and set_strobe_bc().
MvtxRawHitv1::~MvtxRawHitv1 () inline override
Definition at line 16 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 16 of file MvtxRawHitv1.h
Member Function Documentation
uint64_t MvtxRawHitv1::get_bco () const inline override virtual
Reimplemented from MvtxRawHit.
Definition at line 23 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 23 of file MvtxRawHitv1.h
References bco.
uint32_t MvtxRawHitv1::get_chip_bc () const inline override virtual
Reimplemented from MvtxRawHit.
Definition at line 31 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 31 of file MvtxRawHitv1.h
References chip_bc.
uint8_t MvtxRawHitv1::get_chip_id () const inline override virtual
Reimplemented from MvtxRawHit.
Definition at line 43 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 43 of file MvtxRawHitv1.h
References chip_id.
uint16_t MvtxRawHitv1::get_col () const inline override virtual
Reimplemented from MvtxRawHit.
Definition at line 51 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 51 of file MvtxRawHitv1.h
References col.
uint8_t MvtxRawHitv1::get_layer_id () const inline override virtual
Reimplemented from MvtxRawHit.
Definition at line 35 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 35 of file MvtxRawHitv1.h
References layer_id.
uint16_t MvtxRawHitv1::get_row () const inline override virtual
Reimplemented from MvtxRawHit.
Definition at line 47 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 47 of file MvtxRawHitv1.h
References row.
uint8_t MvtxRawHitv1::get_stave_id () const inline override virtual
Reimplemented from MvtxRawHit.
Definition at line 39 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 39 of file MvtxRawHitv1.h
References stave_id.
uint32_t MvtxRawHitv1::get_strobe_bc () const inline override virtual
Reimplemented from MvtxRawHit.
Definition at line 27 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 27 of file MvtxRawHitv1.h
References strobe_bc.
void MvtxRawHitv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 15 of file MvtxRawHitv1.cc.
View newest version in sPHENIX GitHub at line 15 of file MvtxRawHitv1.cc
References bco, chip_bc, chip_id, col, layer_id, row, stave_id, and strobe_bc.
void MvtxRawHitv1::set_bco (const uint64_t val) inline override virtual
Reimplemented from MvtxRawHit.
Definition at line 25 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 25 of file MvtxRawHitv1.h
References bco.
Referenced by MvtxRawHitv1().
void MvtxRawHitv1::set_chip_bc (const uint32_t val) inline override virtual
Reimplemented from MvtxRawHit.
Definition at line 33 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 33 of file MvtxRawHitv1.h
References chip_bc.
Referenced by MvtxRawHitv1().
void MvtxRawHitv1::set_chip_id (uint8_t val) inline override virtual
Reimplemented from MvtxRawHit.
Definition at line 45 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 45 of file MvtxRawHitv1.h
References chip_id.
Referenced by MvtxRawHitv1().
void MvtxRawHitv1::set_col (uint16_t val) inline override virtual
Reimplemented from MvtxRawHit.
Definition at line 53 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 53 of file MvtxRawHitv1.h
References col.
Referenced by MvtxRawHitv1().
void MvtxRawHitv1::set_layer_id (uint8_t val) inline override virtual
Reimplemented from MvtxRawHit.
Definition at line 37 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 37 of file MvtxRawHitv1.h
References layer_id.
Referenced by MvtxRawHitv1().
void MvtxRawHitv1::set_row (uint16_t val) inline override virtual
Reimplemented from MvtxRawHit.
Definition at line 49 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 49 of file MvtxRawHitv1.h
References row.
Referenced by MvtxRawHitv1().
void MvtxRawHitv1::set_stave_id (uint8_t val) inline override virtual
Reimplemented from MvtxRawHit.
Definition at line 41 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 41 of file MvtxRawHitv1.h
References stave_id.
Referenced by MvtxRawHitv1().
void MvtxRawHitv1::set_strobe_bc (const uint32_t val) inline override virtual
Reimplemented from MvtxRawHit.
Definition at line 29 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 29 of file MvtxRawHitv1.h
References strobe_bc.
Referenced by MvtxRawHitv1().
Member Data Documentation
uint64_t MvtxRawHitv1::bco = std::numeric_limits<uint64_t>::max() protected
Definition at line 56 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 56 of file MvtxRawHitv1.h
Referenced by get_bco(), identify(), and set_bco().
uint32_t MvtxRawHitv1::chip_bc = std::numeric_limits<uint32_t>::max() protected
Definition at line 58 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 58 of file MvtxRawHitv1.h
Referenced by get_chip_bc(), identify(), and set_chip_bc().
uint8_t MvtxRawHitv1::chip_id = std::numeric_limits<uint8_t>::max() protected
Definition at line 61 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 61 of file MvtxRawHitv1.h
Referenced by get_chip_id(), identify(), and set_chip_id().
uint16_t MvtxRawHitv1::col = std::numeric_limits<uint16_t>::max() protected
Definition at line 63 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 63 of file MvtxRawHitv1.h
Referenced by item.Item::__eq__(), item.Item::__hash__(), get_col(), identify(), and set_col().
uint8_t MvtxRawHitv1::layer_id = std::numeric_limits<uint8_t>::max() protected
Definition at line 59 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 59 of file MvtxRawHitv1.h
Referenced by get_layer_id(), identify(), and set_layer_id().
uint16_t MvtxRawHitv1::row = std::numeric_limits<uint16_t>::max() protected
Definition at line 62 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 62 of file MvtxRawHitv1.h
Referenced by get_row(), identify(), and set_row().
uint8_t MvtxRawHitv1::stave_id = std::numeric_limits<uint8_t>::max() protected
Definition at line 60 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 60 of file MvtxRawHitv1.h
Referenced by get_stave_id(), identify(), and set_stave_id().
uint32_t MvtxRawHitv1::strobe_bc = std::numeric_limits<uint32_t>::max() protected
Definition at line 57 of file MvtxRawHitv1.h.
View newest version in sPHENIX GitHub at line 57 of file MvtxRawHitv1.h
Referenced by get_strobe_bc(), identify(), and set_strobe_bc().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/ffarawobjects/MvtxRawHitv1.h
coresoftware/blob/master/offline/framework/ffarawobjects/MvtxRawHitv1.cc