Analysis Software: gtest_filter_unittest Namespace Reference
gtest_filter_unittest Namespace Reference
Classes
class GTestFilterUnitTest
Functions
def SetEnvVar
def RunAndReturnOutput
def RunAndExtractTestList
def InvokeWithModifiedEnv
def RunWithSharding
Variables
string __author__ 'wan@google.com (Zhanyong Wan)'
tuple child
tuple CAN_PASS_EMPTY_ENV eval(child.output)
tuple CAN_UNSET_ENV eval(child.output)
tuple CAN_TEST_EMPTY_FILTER (CAN_PASS_EMPTY_ENV and CAN_UNSET_ENV)
string FILTER_ENV_VAR 'GTEST_FILTER'
string TOTAL_SHARDS_ENV_VAR 'GTEST_TOTAL_SHARDS'
string SHARD_INDEX_ENV_VAR 'GTEST_SHARD_INDEX'
string SHARD_STATUS_FILE_ENV_VAR 'GTEST_SHARD_STATUS_FILE'
string FILTER_FLAG 'gtest_filter'
string ALSO_RUN_DISABED_TESTS_FLAG 'gtest_also_run_disabled_tests'
tuple COMMAND gtest_test_utils.GetTestExecutablePath('gtest_filter_unittest_')
tuple PARAM_TEST_REGEX re.compile(r'/ParamTest')
tuple TEST_CASE_REGEX re.compile(r'^\[\-+\] \d+ tests? from (\w+(/\w+)?)')
tuple TEST_REGEX re.compile(r'^\[\s*RUN\s*\].*\.(\w+(/\w+)?)')
string LIST_TESTS_FLAG '--gtest_list_tests'
string SUPPORTS_DEATH_TESTS 'HasDeathTest'
list PARAM_TESTS
list DISABLED_TESTS
list DEATH_TESTS
list ACTIVE_TESTS
param_tests_present None
tuple environ os.environ.copy()
Function Documentation
def gtest_filter_unittest.InvokeWithModifiedEnv (extra_env, function, args, kwargs)
Runs the given function and arguments in a modified environment.
Definition at line 207 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 207 of file gtest_filter_unittest.py
Referenced by RunWithSharding(), gtest_filter_unittest.GTestFilterUnitTest.testShardStatusFileIsCreated(), and gtest_filter_unittest.GTestFilterUnitTest.testShardStatusFileIsCreatedWithListTests().
def gtest_filter_unittest.RunAndExtractTestList (args = None)
Runs the test program and returns its exit code and a list of tests run.
Definition at line 188 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 188 of file gtest_filter_unittest.py
Referenced by gtest_filter_unittest.GTestFilterUnitTest.RunAndVerify(), gtest_filter_unittest.GTestFilterUnitTest.RunAndVerifyAllowingDisabled(), and gtest_filter_unittest.GTestFilterUnitTest.testFlagOverridesEnvVar().
def gtest_filter_unittest.RunAndReturnOutput (args = None)
Runs the test program and returns its output.
Definition at line 181 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 181 of file gtest_filter_unittest.py
Referenced by gtest_filter_unittest.GTestFilterUnitTest.setUp().
def gtest_filter_unittest.RunWithSharding (total_shards, shard_index, command)
Runs a test program shard and returns exit code and a list of tests run.
Definition at line 218 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 218 of file gtest_filter_unittest.py
References InvokeWithModifiedEnv(), and str.
Referenced by gtest_filter_unittest.GTestFilterUnitTest.RunAndVerifyWithSharding().
def gtest_filter_unittest.SetEnvVar (env_var, value)
Sets the env variable to 'value'; unsets it when 'value' is None.
Definition at line 172 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 172 of file gtest_filter_unittest.py
Referenced by gtest_filter_unittest.GTestFilterUnitTest.RunAndVerify(), gtest_filter_unittest.GTestFilterUnitTest.RunAndVerifyWithSharding(), and gtest_filter_unittest.GTestFilterUnitTest.testFlagOverridesEnvVar().
Variable Documentation
string gtest_filter_unittest.__author__ 'wan@google.com (Zhanyong Wan)'
Definition at line 43 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 43 of file gtest_filter_unittest.py
list gtest_filter_unittest.ACTIVE_TESTS
Initial value:
 [
     'FooTest.Abc',
     'FooTest.Xyz',
     'BarTest.TestOne',
     'BarTest.TestTwo',
     'BarTest.TestThree',
     'BazTest.TestOne',
     'BazTest.TestA',
     'BazTest.TestB',
     ]
Definition at line 152 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 152 of file gtest_filter_unittest.py
string gtest_filter_unittest.ALSO_RUN_DISABED_TESTS_FLAG 'gtest_also_run_disabled_tests'
Definition at line 100 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 100 of file gtest_filter_unittest.py
tuple gtest_filter_unittest.CAN_PASS_EMPTY_ENV eval(child.output)
Definition at line 65 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 65 of file gtest_filter_unittest.py
tuple gtest_filter_unittest.CAN_TEST_EMPTY_FILTER (CAN_PASS_EMPTY_ENV and CAN_UNSET_ENV)
Definition at line 85 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 85 of file gtest_filter_unittest.py
tuple gtest_filter_unittest.CAN_UNSET_ENV eval(child.output)
Definition at line 78 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 78 of file gtest_filter_unittest.py
tuple gtest_filter_unittest.child
Initial value:
 gtest_test_utils.Subprocess(
     [sys.executable, '-c', 'import os; print(\'EMPTY_VAR\' in os.environ)'])
Definition at line 63 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 63 of file gtest_filter_unittest.py
Referenced by BOOST_AUTO_TEST_CASE(), Acts.collectCompounds_dd4hep(), Acts.collectLayers_dd4hep(), Acts.collectSubDetectors_dd4hep(), Acts::Experimental::CylindricalContainerBuilder.CylindricalContainerBuilder(), Acts::Experimental::detail::BlueprintHelper.fillGaps(), TruthTrackerHepMC.FindDaughterParticle(), IsolatedTrackAnalysis.getAddTruth(), TruthCaloTree.process_event(), Acts::DD4hepDetectorSurfaceFactory.recursiveConstruct(), Acts::Experimental::DD4hepVolumeStructure.recursiveParse(), Acts::DD4hepLayerBuilder.resolveSensitive(), Acts::Experimental::detail::BlueprintHelper.sort(), TrackCaloDist(), TruthTrackerHepMC.UpdateFinalStateParticle(), and Leptoquarks.UpdateFinalStateParticle().
tuple gtest_filter_unittest.COMMAND gtest_test_utils.GetTestExecutablePath('gtest_filter_unittest_')
Definition at line 103 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 103 of file gtest_filter_unittest.py
list gtest_filter_unittest.DEATH_TESTS
Initial value:
 [
     'HasDeathTest.Test1',
     'HasDeathTest.Test2',
     ]
Definition at line 144 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 144 of file gtest_filter_unittest.py
list gtest_filter_unittest.DISABLED_TESTS
Initial value:
 [
     'BarTest.DISABLED_TestFour',
     'BarTest.DISABLED_TestFive',
     'BazTest.DISABLED_TestC',
     'DISABLED_FoobarTest.Test1',
     'DISABLED_FoobarTest.DISABLED_Test2',
     'DISABLED_FoobarbazTest.TestA',
     ]
Definition at line 134 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 134 of file gtest_filter_unittest.py
tuple gtest_filter_unittest.environ os.environ.copy()
Definition at line 169 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 169 of file gtest_filter_unittest.py
string gtest_filter_unittest.FILTER_ENV_VAR 'GTEST_FILTER'
Definition at line 89 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 89 of file gtest_filter_unittest.py
string gtest_filter_unittest.FILTER_FLAG 'gtest_filter'
Definition at line 97 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 97 of file gtest_filter_unittest.py
string gtest_filter_unittest.LIST_TESTS_FLAG '--gtest_list_tests'
Definition at line 116 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 116 of file gtest_filter_unittest.py
tuple gtest_filter_unittest.PARAM_TEST_REGEX re.compile(r'/ParamTest')
Definition at line 106 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 106 of file gtest_filter_unittest.py
list gtest_filter_unittest.PARAM_TESTS
Initial value:
 [
     'SeqP/ParamTest.TestX/0',
     'SeqP/ParamTest.TestX/1',
     'SeqP/ParamTest.TestY/0',
     'SeqP/ParamTest.TestY/1',
     'SeqQ/ParamTest.TestX/0',
     'SeqQ/ParamTest.TestX/1',
     'SeqQ/ParamTest.TestY/0',
     'SeqQ/ParamTest.TestY/1',
     ]
Definition at line 123 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 123 of file gtest_filter_unittest.py
gtest_filter_unittest.param_tests_present None
Definition at line 165 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 165 of file gtest_filter_unittest.py
string gtest_filter_unittest.SHARD_INDEX_ENV_VAR 'GTEST_SHARD_INDEX'
Definition at line 93 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 93 of file gtest_filter_unittest.py
string gtest_filter_unittest.SHARD_STATUS_FILE_ENV_VAR 'GTEST_SHARD_STATUS_FILE'
Definition at line 94 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 94 of file gtest_filter_unittest.py
string gtest_filter_unittest.SUPPORTS_DEATH_TESTS 'HasDeathTest'
Definition at line 119 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 119 of file gtest_filter_unittest.py
tuple gtest_filter_unittest.TEST_CASE_REGEX re.compile(r'^\[\-+\] \d+ tests? from (\w+(/\w+)?)')
Definition at line 109 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 109 of file gtest_filter_unittest.py
tuple gtest_filter_unittest.TEST_REGEX re.compile(r'^\[\s*RUN\s*\].*\.(\w+(/\w+)?)')
Definition at line 112 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 112 of file gtest_filter_unittest.py
string gtest_filter_unittest.TOTAL_SHARDS_ENV_VAR 'GTEST_TOTAL_SHARDS'
Definition at line 92 of file gtest_filter_unittest.py.
View newest version in sPHENIX GitHub at line 92 of file gtest_filter_unittest.py