Analysis Software: ODBCDatabaseMetaData Class Reference
ODBCDatabaseMetaData Class Reference
#include <RDBC/blob/master/odbc/ODBCDatabaseMetaData.h>
Public Member Functions
Bool_t AllProceduresAreCallable ()
Bool_t AllTablesAreSelectable ()
TString GetUserName ()
Bool_t IsReadOnly ()
Bool_t NullsAreSortedHigh ()
Bool_t NullsAreSortedLow ()
Bool_t NullsAreSortedAtStart ()
Bool_t NullsAreSortedAtEnd ()
TString GetDatabaseProductName ()
TString GetDatabaseProductVersion ()
TString GetDriverName ()
TString GetDriverVersion ()
Int_t GetDriverMajorVersion ()
Int_t GetDriverMinorVersion ()
Bool_t UsesLocalFiles ()
Bool_t UsesLocalFilePerTable ()
Bool_t SupportsMixedCaseIdentifiers ()
Bool_t StoresUpperCaseIdentifiers ()
Bool_t StoresLowerCaseIdentifiers ()
Bool_t StoresMixedCaseIdentifiers ()
Bool_t SupportsMixedCaseQuotedIdentifiers ()
Bool_t StoresUpperCaseQuotedIdentifiers ()
Bool_t StoresLowerCaseQuotedIdentifiers ()
Bool_t StoresMixedCaseQuotedIdentifiers ()
TString GetIdentifierQuoteString ()
TString GetSQLKeywords ()
TString GetNumericFunctions ()
TString GetStringFunctions ()
TString GetSystemFunctions ()
TString GetTimeDateFunctions ()
TString GetSearchStringEscape ()
TString GetExtraNameCharacters ()
Bool_t SupportsAlterTableWithAddColumn ()
Bool_t SupportsAlterTableWithDropColumn ()
Bool_t SupportsColumnAliasing ()
Bool_t NullPlusNonNullIsNull ()
Bool_t SupportsConvert ()
Bool_t SupportsConvert (Int_t fromType, Int_t toType)
Bool_t SupportsTableCorrelationNames ()
Bool_t SupportsDifferentTableCorrelationNames ()
Bool_t SupportsExpressionsInOrderBy ()
Bool_t SupportsOrderByUnrelated ()
Bool_t SupportsGroupBy ()
Bool_t SupportsGroupByUnrelated ()
Bool_t SupportsGroupByBeyondSelect ()
Bool_t SupportsLikeEscapeClause ()
Bool_t SupportsMultipleResultSets ()
Bool_t SupportsMultipleTransactions ()
Bool_t SupportsNonNullableColumns ()
Bool_t SupportsMinimumSQLGrammar ()
Bool_t SupportsCoreSQLGrammar ()
Bool_t SupportsExtendedSQLGrammar ()
Bool_t SupportsANSI92EntryLevelSQL ()
Bool_t SupportsANSI92IntermediateSQL ()
Bool_t SupportsANSI92FullSQL ()
Bool_t SupportsIntegrityEnhancementFacility ()
Bool_t SupportsOuterJoins ()
Bool_t SupportsFullOuterJoins ()
Bool_t SupportsLimitedOuterJoins ()
TString GetSchemaTerm ()
TString GetTableTerm ()
TString GetProcedureTerm ()
TString GetCatalogTerm ()
Bool_t IsCatalogAtStart ()
TString GetCatalogSeparator ()
Bool_t SupportsSchemasInDataManipulation ()
Bool_t SupportsSchemasInProcedureCalls ()
Bool_t SupportsSchemasInTableDefinitions ()
Bool_t SupportsSchemasInIndexDefinitions ()
Bool_t SupportsSchemasInPrivilegeDefinitions ()
Bool_t SupportsCatalogsInDataManipulation ()
Bool_t SupportsCatalogsInProcedureCalls ()
Bool_t SupportsCatalogsInTableDefinitions ()
Bool_t SupportsCatalogsInIndexDefinitions ()
Bool_t SupportsCatalogsInPrivilegeDefinitions ()
Bool_t SupportsPositionedDelete ()
Bool_t SupportsPositionedUpdate ()
Bool_t SupportsSelectForUpdate ()
Bool_t SupportsStoredProcedures ()
Bool_t SupportsSubqueriesInComparisons ()
Bool_t SupportsSubqueriesInExists ()
Bool_t SupportsSubqueriesInIns ()
Bool_t SupportsSubqueriesInQuantifieds ()
Bool_t SupportsCorrelatedSubqueries ()
Bool_t SupportsUnion ()
Bool_t SupportsUnionAll ()
Bool_t SupportsOpenCursorsAcrossCommit ()
Bool_t SupportsOpenCursorsAcrossRollback ()
Bool_t SupportsOpenStatementsAcrossCommit ()
Bool_t SupportsOpenStatementsAcrossRollback ()
Int_t GetMaxBinaryLiteralLength ()
Int_t GetMaxCharLiteralLength ()
Int_t GetMaxColumnNameLength ()
Int_t GetMaxColumnsInGroupBy ()
Int_t GetMaxColumnsInIndex ()
Int_t GetMaxColumnsInOrderBy ()
Int_t GetMaxColumnsInSelect ()
Int_t GetMaxColumnsInTable ()
Int_t GetMaxConnections ()
Int_t GetMaxCursorNameLength ()
Int_t GetMaxIndexLength ()
Int_t GetMaxSchemaNameLength ()
Int_t GetMaxProcedureNameLength ()
Int_t GetMaxCatalogNameLength ()
Int_t GetMaxRowSize ()
Bool_t DoesMaxRowSizeIncludeBlobs ()
Int_t GetMaxStatementLength ()
Int_t GetMaxStatements ()
Int_t GetMaxTableNameLength ()
Int_t GetMaxTablesInSelect ()
Int_t GetMaxUserNameLength ()
Int_t GetDefaultTransactionIsolation ()
Bool_t SupportsTransactions ()
Bool_t SupportsTransactionIsolationLevel (Int_t level)
Bool_t SupportsDataDefinitionAndDataManipulationTransactions ()
Bool_t SupportsDataManipulationTransactionsOnly ()
Bool_t DataDefinitionCausesTransactionCommit ()
Bool_t DataDefinitionIgnoredInTransactions ()
TSQLResultSet * GetProcedures (const TString &catalog, const TString &schemaPattern, const TString &procedureNamePattern)
TSQLResultSet * GetProcedureColumns (const TString &catalog, const TString &schemaPattern, const TString &procedureNamePattern, const TString &columnNamePattern)
TSQLResultSet * GetTables (const TString &catalog, const TString &schemaPattern, const TString &tableNamePattern, const TString &types)
TSQLResultSet * GetSchemas ()
TSQLResultSet * GetCatalogs ()
TSQLResultSet * GetTableTypes ()
TSQLResultSet * GetColumns (const TString &catalog, const TString &schemaPattern, const TString &tableNamePattern, const TString &columnNamePattern)
TSQLResultSet * GetColumnPrivileges (const TString &catalog, const TString &schema, const TString &table, const TString &columnNamePattern)
TSQLResultSet * GetTablePrivileges (const TString &catalog, const TString &schemaPattern, const TString &tableNamePattern)
TSQLResultSet * GetBestRowIdentifier (const TString &catalog, const TString &schema, const TString &table, Int_t scope, Bool_t nullable)
TSQLResultSet * GetVersionColumns (const TString &catalog, const TString &schema, const TString &table)
TSQLResultSet * GetPrimaryKeys (const TString &catalog, const TString &schema, const TString &table)
TSQLResultSet * GetImportedKeys (const TString &catalog, const TString &schema, const TString &table)
TSQLResultSet * GetExportedKeys (const TString &catalog, const TString &schema, const TString &table)
TSQLResultSet * GetCrossReference (const TString &primaryCatalog, const TString &primarySchema, const TString &primaryTable, const TString &foreignCatalog, const TString &foreignSchema, const TString &foreignTable)
TSQLResultSet * GetTypeInfo ()
TSQLResultSet * GetIndexInfo (const TString &catalog, const TString &schema, const TString &table, Bool_t unique, Bool_t approximate)
Bool_t SupportsResultSetType (Int_t type)
Bool_t SupportsResultSetConcurrency (Int_t type, Int_t concurrency)
Bool_t OwnUpdatesAreVisible (Int_t type)
Bool_t OwnDeletesAreVisible (Int_t type)
Bool_t OwnInsertsAreVisible (Int_t type)
Bool_t OthersUpdatesAreVisible (Int_t type)
Bool_t OthersDeletesAreVisible (Int_t type)
Bool_t OthersInsertsAreVisible (Int_t type)
Bool_t UpdatesAreDetected (Int_t type)
Bool_t DeletesAreDetected (Int_t type)
Bool_t InsertsAreDetected (Int_t type)
Bool_t SupportsBatchUpdates ()
Public Member Functions inherited from TSQLDatabaseMetaData
TSQLConnection * GetConnection () const
virtual TString GetURL () const
Public Member Functions inherited from TSQL
TSQL (void *imp=0)
virtual ~TSQL ()
virtual void Throw (TSQLException *e)
TList * GetWarnings () const
void ClearWarnings ()
virtual Bool_t IsValid () const
Protected Member Functions
ODBCDatabaseMetaData (TSQLConnection *connection, void *imp=0)
virtual ~ODBCDatabaseMetaData ()
Protected Member Functions inherited from TSQLDatabaseMetaData
TSQLDatabaseMetaData (TSQLConnection *connection, void *imp=0)
virtual ~TSQLDatabaseMetaData ()
void SetURL (const TString &url)
void Set (TSQLConnection *connection, void *imp=0)
Friends
class ODBCConnection
Additional Inherited Members
Public Types inherited from TSQLDatabaseMetaData
enum EMetaDataConstants {
kBestRowTemporary = 0, kBestRowTransaction = 1, kBestRowSession = 2, kBestRowUnknown = 0,
kBestRowPseudo = 2, kBestRowNotPseudo = 1, kVersionColumnNotPseudo = 1, kVersionColumnPseudo = 2,
kVersionColumnUnknown = 0, kTypeNoNulls = 0, kTypeNullable = 1, kTypeNullableUnknown = 2,
kColumnNoNulls = 0, kColumnNullable = 1, kColumnNullableUnknown = 2, kTypePredNone = 0,
kTypePredChar = 1, kTypePredBasic = 2, kTypeSearchable = 3, kImportedKeyCascade = 0x00000020L,
kImportedKeySetNull = 2, kImportedKeySetDefault = 4, kImportedKeyNoAction = 3, kImportedKeyRestrict = 1,
kImportedKeyInitiallyDeferred = 5, kImportedKeyInitiallyImmediate = 6, kImportedKeyNotDeferrable = 7, kTableIndexClustered = 1,
kTableIndexHashed = 2, kTableIndexOther = 3, kTableIndexStatistic = 0, kProcedureColumnIn = 1,
kProcedureColumnInOut = 2, kProcedureColumnOut = 4, kProcedureColumnResult = 3, kProcedureColumnReturn = 5,
kProcedureColumnUnknown = 0, kProcedureNoNulls = 0, kProcedureNullable = 1, kProcedureNullableUnknown = 2,
kProcedureReturnsResult = 2, kProcedureNoResult = 1, kProcedureResultUnknown = 0
}
Static Public Member Functions inherited from TSQL
static Bool_t SetHandler (const TString &handler)
static Bool_t UnsetHandler (const TString &handler="")
Protected Attributes inherited from TSQLDatabaseMetaData
TSQLConnection * fConnection
TString fUrl
Detailed Description
Definition at line 15 of file ODBCDatabaseMetaData.h.
View newest version in sPHENIX GitHub at line 15 of file ODBCDatabaseMetaData.h
Constructor & Destructor Documentation
ODBCDatabaseMetaData::ODBCDatabaseMetaData (TSQLConnection * connection, void * imp = 0) protected
ODBCDatabaseMetaData::~ODBCDatabaseMetaData () protected virtual
Definition at line 446 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 446 of file ODBCDatabaseMetaData.cxx
Member Function Documentation
Bool_t ODBCDatabaseMetaData::AllProceduresAreCallable () virtual
Implements TSQLDatabaseMetaData.
Definition at line 456 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 456 of file ODBCDatabaseMetaData.cxx
References odbc::DatabaseMetaData::allProceduresAreCallable(), Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Bool_t ODBCDatabaseMetaData::AllTablesAreSelectable () virtual
Implements TSQLDatabaseMetaData.
Definition at line 484 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 484 of file ODBCDatabaseMetaData.cxx
References odbc::DatabaseMetaData::allTablesAreSelectable(), Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Bool_t ODBCDatabaseMetaData::DataDefinitionCausesTransactionCommit () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3904 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3904 of file ODBCDatabaseMetaData.cxx
References odbc::DatabaseMetaData::dataDefinitionCausesTransactionCommit(), Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Bool_t ODBCDatabaseMetaData::DataDefinitionIgnoredInTransactions () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3932 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3932 of file ODBCDatabaseMetaData.cxx
References odbc::DatabaseMetaData::dataDefinitionIgnoredInTransactions(), Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Bool_t ODBCDatabaseMetaData::DeletesAreDetected (Int_t type) virtual
Implements TSQLDatabaseMetaData.
Definition at line 5631 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 5631 of file ODBCDatabaseMetaData.cxx
References odbc::DatabaseMetaData::deletesAreDetected(), Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Bool_t ODBCDatabaseMetaData::DoesMaxRowSizeIncludeBlobs () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3575 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3575 of file ODBCDatabaseMetaData.cxx
References odbc::DatabaseMetaData::doesMaxRowSizeIncludeBlobs(), Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
TSQLResultSet * ODBCDatabaseMetaData::GetBestRowIdentifier (const TString & catalog, const TString & schema, const TString & table, Int_t scope, Bool_t nullable) virtual
Implements TSQLDatabaseMetaData.
Definition at line 4589 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 4589 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::DatabaseMetaData::getBestRowIdentifier(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, and ODBCXX_STRING_CSTR.
TSQLResultSet * ODBCDatabaseMetaData::GetCatalogs () virtual
Implements TSQLDatabaseMetaData.
Definition at line 4260 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 4260 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::DatabaseMetaData::getCatalogs(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
TString ODBCDatabaseMetaData::GetCatalogSeparator () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2358 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2358 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::DatabaseMetaData::getCatalogSeparator(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and str.
TString ODBCDatabaseMetaData::GetCatalogTerm () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2292 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2292 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::DatabaseMetaData::getCatalogTerm(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and str.
TSQLResultSet * ODBCDatabaseMetaData::GetColumnPrivileges (const TString & catalog, const TString & schema, const TString & table, const TString & columnNamePattern) virtual
Implements TSQLDatabaseMetaData.
Definition at line 4440 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 4440 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::DatabaseMetaData::getColumnPrivileges(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, and ODBCXX_STRING_CSTR.
TSQLResultSet * ODBCDatabaseMetaData::GetColumns (const TString & catalog, const TString & schemaPattern, const TString & tableNamePattern, const TString & columnNamePattern) virtual
Implements TSQLDatabaseMetaData.
Definition at line 4336 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 4336 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::DatabaseMetaData::getColumns(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, and ODBCXX_STRING_CSTR.
TSQLResultSet * ODBCDatabaseMetaData::GetCrossReference (const TString & primaryCatalog, const TString & primarySchema, const TString & primaryTable, const TString & foreignCatalog, const TString & foreignSchema, const TString & foreignTable) virtual
Implements TSQLDatabaseMetaData.
Definition at line 5017 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 5017 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::DatabaseMetaData::getCrossReference(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, and ODBCXX_STRING_CSTR.
TString ODBCDatabaseMetaData::GetDatabaseProductName () virtual
Implements TSQLDatabaseMetaData.
Definition at line 703 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 703 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::DatabaseMetaData::getDatabaseProductName(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and str.
TString ODBCDatabaseMetaData::GetDatabaseProductVersion () virtual
Implements TSQLDatabaseMetaData.
Definition at line 730 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 730 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::DatabaseMetaData::getDatabaseProductVersion(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and str.
Int_t ODBCDatabaseMetaData::GetDefaultTransactionIsolation () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3757 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3757 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::DatabaseMetaData::getDefaultTransactionIsolation(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetDriverMajorVersion () virtual
Implements TSQLDatabaseMetaData.
Definition at line 825 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 825 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::DatabaseMetaData::getDriverMajorVersion(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetDriverMinorVersion () virtual
Implements TSQLDatabaseMetaData.
Definition at line 850 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 850 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::DatabaseMetaData::getDriverMinorVersion(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
TString ODBCDatabaseMetaData::GetDriverName () virtual
Implements TSQLDatabaseMetaData.
Definition at line 764 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 764 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::DatabaseMetaData::getDriverName(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and str.
TString ODBCDatabaseMetaData::GetDriverVersion () virtual
Implements TSQLDatabaseMetaData.
Definition at line 791 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 791 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::DatabaseMetaData::getDriverVersion(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and str.
TSQLResultSet * ODBCDatabaseMetaData::GetExportedKeys (const TString & catalog, const TString & schema, const TString & table) virtual
Implements TSQLDatabaseMetaData.
Definition at line 4907 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 4907 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getExportedKeys(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, and ODBCXX_STRING_CSTR.
TString ODBCDatabaseMetaData::GetExtraNameCharacters () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1391 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1391 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getExtraNameCharacters(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and str.
TString ODBCDatabaseMetaData::GetIdentifierQuoteString () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1167 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1167 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getIdentifierQuoteString(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and str.
TSQLResultSet * ODBCDatabaseMetaData::GetImportedKeys (const TString & catalog, const TString & schema, const TString & table) virtual
Implements TSQLDatabaseMetaData.
Definition at line 4793 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 4793 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getImportedKeys(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, and ODBCXX_STRING_CSTR.
TSQLResultSet * ODBCDatabaseMetaData::GetIndexInfo (const TString & catalog, const TString & schema, const TString & table, Bool_t unique, Bool_t approximate) virtual
Implements TSQLDatabaseMetaData.
Definition at line 5230 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 5230 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getIndexInfo(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxBinaryLiteralLength () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3162 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3162 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxBinaryLiteralLength(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxCatalogNameLength () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3521 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3521 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxCatalogNameLength(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxCharLiteralLength () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3193 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3193 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxCharLiteralLength(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxColumnNameLength () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3222 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3222 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxColumnNameLength(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxColumnsInGroupBy () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3249 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3249 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxColumnsInGroupBy(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxColumnsInIndex () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3276 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3276 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxColumnsInIndex(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxColumnsInOrderBy () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3303 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3303 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxColumnsInOrderBy(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxColumnsInSelect () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3330 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3330 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxColumnsInSelect(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxColumnsInTable () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3357 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3357 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxColumnsInTable(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxConnections () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3384 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3384 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxConnections(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxCursorNameLength () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3413 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3413 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxCursorNameLength(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxIndexLength () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3440 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3440 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxIndexLength(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxProcedureNameLength () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3494 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3494 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxProcedureNameLength(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxRowSize () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3548 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3548 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxRowSize(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxSchemaNameLength () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3467 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3467 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxSchemaNameLength(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxStatementLength () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3602 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3602 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxStatementLength(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxStatements () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3629 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3629 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxStatements(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxTableNameLength () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3669 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3669 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxTableNameLength(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxTablesInSelect () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3696 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3696 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxTablesInSelect(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Int_t ODBCDatabaseMetaData::GetMaxUserNameLength () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3730 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3730 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::DatabaseMetaData::getMaxUserNameLength(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
TString ODBCDatabaseMetaData::GetNumericFunctions () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1236 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1236 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::DatabaseMetaData::getNumericFunctions(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and str.
TSQLResultSet * ODBCDatabaseMetaData::GetPrimaryKeys (const TString & catalog, const TString & schema, const TString & table) virtual
Implements TSQLDatabaseMetaData.
Definition at line 4735 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 4735 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::DatabaseMetaData::getPrimaryKeys(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, and ODBCXX_STRING_CSTR.
TSQLResultSet * ODBCDatabaseMetaData::GetProcedureColumns (const TString & catalog, const TString & schemaPattern, const TString & procedureNamePattern, const TString & columnNamePattern) virtual
Implements TSQLDatabaseMetaData.
Definition at line 4029 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 4029 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::DatabaseMetaData::getProcedureColumns(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, and ODBCXX_STRING_CSTR.
TSQLResultSet * ODBCDatabaseMetaData::GetProcedures (const TString & catalog, const TString & schemaPattern, const TString & procedureNamePattern) virtual
Implements TSQLDatabaseMetaData.
Definition at line 3959 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3959 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::DatabaseMetaData::getProcedures(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, and ODBCXX_STRING_CSTR.
TString ODBCDatabaseMetaData::GetProcedureTerm () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2261 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2261 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::DatabaseMetaData::getProcedureTerm(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and str.
TSQLResultSet * ODBCDatabaseMetaData::GetSchemas () virtual
Implements TSQLDatabaseMetaData.
Definition at line 4225 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 4225 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::DatabaseMetaData::getSchemas(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
TString ODBCDatabaseMetaData::GetSchemaTerm () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2199 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2199 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::DatabaseMetaData::getSchemaTerm(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and str.
TString ODBCDatabaseMetaData::GetSearchStringEscape () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1351 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1351 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::DatabaseMetaData::getSearchStringEscape(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and str.
TString ODBCDatabaseMetaData::GetSQLKeywords () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1209 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1209 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::DatabaseMetaData::getSQLKeywords(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and str.
TString ODBCDatabaseMetaData::GetStringFunctions () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1265 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1265 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::getStringFunctions(), ODBCXX_STRING_CSTR, and str.
TString ODBCDatabaseMetaData::GetSystemFunctions () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1294 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1294 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::getSystemFunctions(), ODBCXX_STRING_CSTR, and str.
TSQLResultSet * ODBCDatabaseMetaData::GetTablePrivileges (const TString & catalog, const TString & schemaPattern, const TString & tableNamePattern) virtual
Implements TSQLDatabaseMetaData.
Definition at line 4515 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 4515 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::getTablePrivileges(), ODBCXX_STRING_C, and ODBCXX_STRING_CSTR.
TSQLResultSet * ODBCDatabaseMetaData::GetTables (const TString & catalog, const TString & schemaPattern, const TString & tableNamePattern, const TString & types) virtual
Implements TSQLDatabaseMetaData.
Definition at line 4132 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 4132 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::getTables(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, and vec.
TString ODBCDatabaseMetaData::GetTableTerm () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2231 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2231 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::getTableTerm(), ODBCXX_STRING_CSTR, and str.
TSQLResultSet * ODBCDatabaseMetaData::GetTableTypes () virtual
Implements TSQLDatabaseMetaData.
Definition at line 4296 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 4296 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::getTableTypes(), and ODBCXX_STRING_CSTR.
TString ODBCDatabaseMetaData::GetTimeDateFunctions () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1323 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1323 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::getTimeDateFunctions(), ODBCXX_STRING_CSTR, and str.
TSQLResultSet * ODBCDatabaseMetaData::GetTypeInfo () virtual
Implements TSQLDatabaseMetaData.
Definition at line 5145 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 5145 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::getTypeInfo(), and ODBCXX_STRING_CSTR.
TString ODBCDatabaseMetaData::GetUserName () virtual
Implements TSQLDatabaseMetaData.
Definition at line 512 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 512 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::getUserName(), ODBCXX_STRING_CSTR, and str.
TSQLResultSet * ODBCDatabaseMetaData::GetVersionColumns (const TString & catalog, const TString & schema, const TString & table) virtual
Implements TSQLDatabaseMetaData.
Definition at line 4668 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 4668 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::getVersionColumns(), ODBCXX_STRING_C, and ODBCXX_STRING_CSTR.
Bool_t ODBCDatabaseMetaData::InsertsAreDetected (Int_t type) virtual
Implements TSQLDatabaseMetaData.
Definition at line 5664 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 5664 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::insertsAreDetected(), and ODBCXX_STRING_CSTR.
Bool_t ODBCDatabaseMetaData::IsCatalogAtStart () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2324 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2324 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::isCatalogAtStart(), and ODBCXX_STRING_CSTR.
Bool_t ODBCDatabaseMetaData::IsReadOnly () virtual
Implements TSQLDatabaseMetaData.
Definition at line 545 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 545 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::isReadOnly(), and ODBCXX_STRING_CSTR.
Bool_t ODBCDatabaseMetaData::NullPlusNonNullIsNull () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1506 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1506 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::nullPlusNonNullIsNull(), and ODBCXX_STRING_CSTR.
Bool_t ODBCDatabaseMetaData::NullsAreSortedAtEnd () virtual
Implements TSQLDatabaseMetaData.
Definition at line 673 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 673 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::nullsAreSortedAtEnd(), and ODBCXX_STRING_CSTR.
Bool_t ODBCDatabaseMetaData::NullsAreSortedAtStart () virtual
Implements TSQLDatabaseMetaData.
Definition at line 643 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 643 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::nullsAreSortedAtStart(), and ODBCXX_STRING_CSTR.
Bool_t ODBCDatabaseMetaData::NullsAreSortedHigh () virtual
Implements TSQLDatabaseMetaData.
Definition at line 583 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 583 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::nullsAreSortedHigh(), and ODBCXX_STRING_CSTR.
Bool_t ODBCDatabaseMetaData::NullsAreSortedLow () virtual
Implements TSQLDatabaseMetaData.
Definition at line 613 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 613 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::DatabaseMetaData::nullsAreSortedLow(), and ODBCXX_STRING_CSTR.
Bool_t ODBCDatabaseMetaData::OthersDeletesAreVisible (Int_t type) virtual
Implements TSQLDatabaseMetaData.
Definition at line 5538 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 5538 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::othersDeletesAreVisible().
Bool_t ODBCDatabaseMetaData::OthersInsertsAreVisible (Int_t type) virtual
Implements TSQLDatabaseMetaData.
Definition at line 5569 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 5569 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::othersInsertsAreVisible().
Bool_t ODBCDatabaseMetaData::OthersUpdatesAreVisible (Int_t type) virtual
Implements TSQLDatabaseMetaData.
Definition at line 5507 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 5507 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::othersUpdatesAreVisible().
Bool_t ODBCDatabaseMetaData::OwnDeletesAreVisible (Int_t type) virtual
Implements TSQLDatabaseMetaData.
Definition at line 5441 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 5441 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::ownDeletesAreVisible().
Bool_t ODBCDatabaseMetaData::OwnInsertsAreVisible (Int_t type) virtual
Implements TSQLDatabaseMetaData.
Definition at line 5474 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 5474 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::ownInsertsAreVisible().
Bool_t ODBCDatabaseMetaData::OwnUpdatesAreVisible (Int_t type) virtual
Implements TSQLDatabaseMetaData.
Definition at line 5408 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 5408 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::ownUpdatesAreVisible().
Bool_t ODBCDatabaseMetaData::StoresLowerCaseIdentifiers () virtual
Implements TSQLDatabaseMetaData.
Definition at line 997 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 997 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::storesLowerCaseIdentifiers().
Bool_t ODBCDatabaseMetaData::StoresLowerCaseQuotedIdentifiers () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1111 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1111 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::storesLowerCaseQuotedIdentifiers().
Bool_t ODBCDatabaseMetaData::StoresMixedCaseIdentifiers () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1025 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1025 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::storesMixedCaseIdentifiers().
Bool_t ODBCDatabaseMetaData::StoresMixedCaseQuotedIdentifiers () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1139 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1139 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::storesMixedCaseQuotedIdentifiers().
Bool_t ODBCDatabaseMetaData::StoresUpperCaseIdentifiers () virtual
Implements TSQLDatabaseMetaData.
Definition at line 969 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 969 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::storesUpperCaseIdentifiers().
Bool_t ODBCDatabaseMetaData::StoresUpperCaseQuotedIdentifiers () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1083 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1083 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::storesUpperCaseQuotedIdentifiers().
Bool_t ODBCDatabaseMetaData::SupportsAlterTableWithAddColumn () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1420 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1420 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsAlterTableWithAddColumn().
Bool_t ODBCDatabaseMetaData::SupportsAlterTableWithDropColumn () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1447 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1447 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsAlterTableWithDropColumn().
Bool_t ODBCDatabaseMetaData::SupportsANSI92EntryLevelSQL () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2007 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2007 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsANSI92EntryLevelSQL().
Bool_t ODBCDatabaseMetaData::SupportsANSI92FullSQL () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2062 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2062 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), and ODBCXX_STRING_CSTR.
Bool_t ODBCDatabaseMetaData::SupportsANSI92IntermediateSQL () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2035 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2035 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsANSI92IntermediateSQL().
Bool_t ODBCDatabaseMetaData::SupportsBatchUpdates () virtual
Implements TSQLDatabaseMetaData.
Definition at line 5695 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 5695 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsBatchUpdates().
Bool_t ODBCDatabaseMetaData::SupportsCatalogsInDataManipulation () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2550 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2550 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsCatalogsInDataManipulation().
Bool_t ODBCDatabaseMetaData::SupportsCatalogsInIndexDefinitions () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2647 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2647 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsCatalogsInIndexDefinitions().
Bool_t ODBCDatabaseMetaData::SupportsCatalogsInPrivilegeDefinitions () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2679 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2679 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsCatalogsInPrivilegeDefinitions().
Bool_t ODBCDatabaseMetaData::SupportsCatalogsInProcedureCalls () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2587 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2587 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsCatalogsInProcedureCalls().
Bool_t ODBCDatabaseMetaData::SupportsCatalogsInTableDefinitions () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2616 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2616 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsCatalogsInTableDefinitions().
Bool_t ODBCDatabaseMetaData::SupportsColumnAliasing () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1474 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1474 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsColumnAliasing().
Bool_t ODBCDatabaseMetaData::SupportsConvert () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1534 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1534 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsConvert().
Bool_t ODBCDatabaseMetaData::SupportsConvert (Int_t fromType, Int_t toType) virtual
Implements TSQLDatabaseMetaData.
Definition at line 1561 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1561 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsConvert().
Bool_t ODBCDatabaseMetaData::SupportsCoreSQLGrammar () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1953 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1953 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsCoreSQLGrammar().
Bool_t ODBCDatabaseMetaData::SupportsCorrelatedSubqueries () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2932 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2932 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsCorrelatedSubqueries().
Bool_t ODBCDatabaseMetaData::SupportsDataDefinitionAndDataManipulationTransactions () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3848 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3848 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsDataDefinitionAndDataManipulationTransactions().
Bool_t ODBCDatabaseMetaData::SupportsDataManipulationTransactionsOnly () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3876 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3876 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsDataManipulationTransactionsOnly().
Bool_t ODBCDatabaseMetaData::SupportsDifferentTableCorrelationNames () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1635 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1635 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsDifferentTableCorrelationNames().
Bool_t ODBCDatabaseMetaData::SupportsExpressionsInOrderBy () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1663 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1663 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsExpressionsInOrderBy().
Bool_t ODBCDatabaseMetaData::SupportsExtendedSQLGrammar () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1980 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1980 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsExtendedSQLGrammar().
Bool_t ODBCDatabaseMetaData::SupportsFullOuterJoins () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2144 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2144 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsFullOuterJoins().
Bool_t ODBCDatabaseMetaData::SupportsGroupBy () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1718 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1718 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsGroupBy().
Bool_t ODBCDatabaseMetaData::SupportsGroupByBeyondSelect () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1775 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1775 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsGroupByBeyondSelect().
Bool_t ODBCDatabaseMetaData::SupportsGroupByUnrelated () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1745 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1745 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsGroupByUnrelated().
Bool_t ODBCDatabaseMetaData::SupportsIntegrityEnhancementFacility () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2090 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2090 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsIntegrityEnhancementFacility().
Bool_t ODBCDatabaseMetaData::SupportsLikeEscapeClause () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1807 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1807 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsLikeEscapeClause().
Bool_t ODBCDatabaseMetaData::SupportsLimitedOuterJoins () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2171 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2171 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsLimitedOuterJoins().
Bool_t ODBCDatabaseMetaData::SupportsMinimumSQLGrammar () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1925 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1925 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsMinimumSQLGrammar().
Bool_t ODBCDatabaseMetaData::SupportsMixedCaseIdentifiers () virtual
Implements TSQLDatabaseMetaData.
Definition at line 940 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 940 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsMixedCaseIdentifiers().
Bool_t ODBCDatabaseMetaData::SupportsMixedCaseQuotedIdentifiers () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1053 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1053 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsMixedCaseQuotedIdentifiers().
Bool_t ODBCDatabaseMetaData::SupportsMultipleResultSets () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1836 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1836 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsMultipleResultSets().
Bool_t ODBCDatabaseMetaData::SupportsMultipleTransactions () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1863 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1863 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsMultipleTransactions().
Bool_t ODBCDatabaseMetaData::SupportsNonNullableColumns () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1891 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1891 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsNonNullableColumns().
Bool_t ODBCDatabaseMetaData::SupportsOpenCursorsAcrossCommit ()
Definition at line 3016 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3016 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsOpenCursorsAcrossCommit().
Bool_t ODBCDatabaseMetaData::SupportsOpenCursorsAcrossRollback () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3057 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3057 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsOpenCursorsAcrossRollback().
Bool_t ODBCDatabaseMetaData::SupportsOpenStatementsAcrossCommit () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3098 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3098 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsOpenStatementsAcrossCommit().
Bool_t ODBCDatabaseMetaData::SupportsOpenStatementsAcrossRollback () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3130 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3130 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsOpenStatementsAcrossRollback().
Bool_t ODBCDatabaseMetaData::SupportsOrderByUnrelated () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1690 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1690 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsOrderByUnrelated().
Bool_t ODBCDatabaseMetaData::SupportsOuterJoins () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2117 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2117 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsOuterJoins().
Bool_t ODBCDatabaseMetaData::SupportsPositionedDelete () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2711 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2711 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsPositionedDelete().
Bool_t ODBCDatabaseMetaData::SupportsPositionedUpdate () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2738 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2738 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsPositionedUpdate().
Bool_t ODBCDatabaseMetaData::SupportsResultSetConcurrency (Int_t type, Int_t concurrency) virtual
Implements TSQLDatabaseMetaData.
Definition at line 5372 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 5372 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsResultSetConcurrency().
Bool_t ODBCDatabaseMetaData::SupportsResultSetType (Int_t type) virtual
Implements TSQLDatabaseMetaData.
Definition at line 5340 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 5340 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsResultSetType().
Bool_t ODBCDatabaseMetaData::SupportsSchemasInDataManipulation () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2391 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2391 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsSchemasInDataManipulation().
Bool_t ODBCDatabaseMetaData::SupportsSchemasInIndexDefinitions () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2488 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2488 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsSchemasInIndexDefinitions().
Bool_t ODBCDatabaseMetaData::SupportsSchemasInPrivilegeDefinitions () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2518 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2518 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsSchemasInPrivilegeDefinitions().
Bool_t ODBCDatabaseMetaData::SupportsSchemasInProcedureCalls () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2428 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2428 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsSchemasInProcedureCalls().
Bool_t ODBCDatabaseMetaData::SupportsSchemasInTableDefinitions () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2455 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2455 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsSchemasInTableDefinitions().
Bool_t ODBCDatabaseMetaData::SupportsSelectForUpdate () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2765 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2765 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsStoredProcedures().
Bool_t ODBCDatabaseMetaData::SupportsStoredProcedures () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2792 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2792 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsStoredProcedures().
Bool_t ODBCDatabaseMetaData::SupportsSubqueriesInComparisons () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2820 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2820 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsSubqueriesInComparisons().
Bool_t ODBCDatabaseMetaData::SupportsSubqueriesInExists () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2848 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2848 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsSubqueriesInExists().
Bool_t ODBCDatabaseMetaData::SupportsSubqueriesInIns () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2876 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2876 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsSubqueriesInIns().
Bool_t ODBCDatabaseMetaData::SupportsSubqueriesInQuantifieds () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2904 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2904 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsSubqueriesInQuantifieds().
Bool_t ODBCDatabaseMetaData::SupportsTableCorrelationNames () virtual
Implements TSQLDatabaseMetaData.
Definition at line 1607 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1607 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsTableCorrelationNames().
Bool_t ODBCDatabaseMetaData::SupportsTransactionIsolationLevel (Int_t level) virtual
Implements TSQLDatabaseMetaData.
Definition at line 3814 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3814 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsTransactionIsolationLevel().
Bool_t ODBCDatabaseMetaData::SupportsTransactions () virtual
Implements TSQLDatabaseMetaData.
Definition at line 3786 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3786 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsTransactions().
Bool_t ODBCDatabaseMetaData::SupportsUnion () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2960 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2960 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsUnion().
Bool_t ODBCDatabaseMetaData::SupportsUnionAll () virtual
Implements TSQLDatabaseMetaData.
Definition at line 2988 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2988 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::supportsUnionAll().
Bool_t ODBCDatabaseMetaData::UpdatesAreDetected (Int_t type) virtual
Implements TSQLDatabaseMetaData.
Definition at line 5599 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 5599 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::updatesAreDetected().
Bool_t ODBCDatabaseMetaData::UsesLocalFilePerTable () virtual
Implements TSQLDatabaseMetaData.
Definition at line 907 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 907 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::usesLocalFilePerTable().
Bool_t ODBCDatabaseMetaData::UsesLocalFiles () virtual
Implements TSQLDatabaseMetaData.
Definition at line 875 of file ODBCDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 875 of file ODBCDatabaseMetaData.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and odbc::DatabaseMetaData::usesLocalFiles().
Friends And Related Function Documentation
friend class ODBCConnection friend
Definition at line 17 of file ODBCDatabaseMetaData.h.
View newest version in sPHENIX GitHub at line 17 of file ODBCDatabaseMetaData.h
The documentation for this class was generated from the following files:
RDBC/blob/master/odbc/ODBCDatabaseMetaData.h
RDBC/blob/master/odbc/ODBCDatabaseMetaData.cxx