Analysis Software: ReadBDTG Class Reference
ReadBDTG Class Reference
Public Member Functions
ReadBDTG (std::vector< std::string > &theInputVars)
virtual ~ReadBDTG ()
double GetMvaValue (const std::vector< double > &inputValues) const override
Public Member Functions inherited from IClassifierReader
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
Private Member Functions
void Clear ()
size_t GetNvar () const
char GetType (int ivar) const
double NormVariable (double x, double xmin, double xmax) const
void Initialize ()
double GetMvaValue__ (const std::vector< double > &inputValues) const
Private Attributes
const char * fClassName
const size_t fNvars
double fVmin [4]
double fVmax [4]
char fType [4]
std::vector< BDTGNode * > fForest
std::vector< double > fBoostWeights
Additional Inherited Members
Protected Attributes inherited from IClassifierReader
bool fStatusIsClean
Detailed Description
Definition at line 195 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 195 of file TMVAClassification_BDTG.class.C
Constructor & Destructor Documentation
ReadBDTG::ReadBDTG (std::vector< std::string > & theInputVars) inline
Definition at line 200 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 200 of file TMVAClassification_BDTG.class.C
References fClassName, fNvars, IClassifierReader::fStatusIsClean, fType, fVmax, fVmin, and Initialize().
virtual ReadBDTG::~ReadBDTG () inline virtual
Definition at line 251 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 251 of file TMVAClassification_BDTG.class.C
References Clear().
Member Function Documentation
void ReadBDTG::Clear () inline private
Definition at line 24000 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 24000 of file TMVAClassification_BDTG.class.C
References fForest.
Referenced by ~ReadBDTG().
double ReadBDTG::GetMvaValue (const std::vector< double > & inputValues) const inline override virtual
Implements IClassifierReader.
Definition at line 24007 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 24007 of file TMVAClassification_BDTG.class.C
References fClassName, GetMvaValue__(), and IClassifierReader::IsStatusClean().
double ReadBDTG::GetMvaValue__ (const std::vector< double > & inputValues) const private
Definition at line 292 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 292 of file TMVAClassification_BDTG.class.C
References fForest, BDTGNode::GetLeft(), BDTGNode::GetNodeType(), BDTGNode::GetResponse(), BDTGNode::GetRight(), and BDTGNode::GoesRight().
Referenced by GetMvaValue().
size_t ReadBDTG::GetNvar () const inline private
Definition at line 269 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 269 of file TMVAClassification_BDTG.class.C
References fNvars.
char ReadBDTG::GetType (int ivar) const inline private
Definition at line 270 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 270 of file TMVAClassification_BDTG.class.C
References fType.
void ReadBDTG::Initialize () private
Definition at line 306 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 306 of file TMVAClassification_BDTG.class.C
References Acts::UnitConstants::e, fBoostWeights, fForest, inf, and NN.
Referenced by ReadBDTG().
double ReadBDTG::NormVariable (double x, double xmin, double xmax) const inline private
Definition at line 275 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 275 of file TMVAClassification_BDTG.class.C
References xmin.
Member Data Documentation
std::vector<double> ReadBDTG::fBoostWeights private
Definition at line 289 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 289 of file TMVAClassification_BDTG.class.C
Referenced by Initialize().
const char* ReadBDTG::fClassName private
Definition at line 266 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 266 of file TMVAClassification_BDTG.class.C
Referenced by GetMvaValue(), and ReadBDTG().
std::vector<BDTGNode*> ReadBDTG::fForest private
Definition at line 288 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 288 of file TMVAClassification_BDTG.class.C
Referenced by Clear(), GetMvaValue__(), and Initialize().
const size_t ReadBDTG::fNvars private
Definition at line 268 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 268 of file TMVAClassification_BDTG.class.C
Referenced by GetNvar(), and ReadBDTG().
char ReadBDTG::fType[4] private
Definition at line 281 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 281 of file TMVAClassification_BDTG.class.C
Referenced by GetType(), and ReadBDTG().
double ReadBDTG::fVmax[4] private
Definition at line 274 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 274 of file TMVAClassification_BDTG.class.C
Referenced by ReadBDTG().
double ReadBDTG::fVmin[4] private
Definition at line 273 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 273 of file TMVAClassification_BDTG.class.C
Referenced by ReadBDTG().
The documentation for this class was generated from the following file:
analysis/blob/master/HF-Particle/HFTrigger/weights/woutCaloAndMinTrack/TMVAClassification_BDTG.class.C