Analysis Software: Acts::IndexedSurfacesJsonConverter Namespace Reference
Acts::IndexedSurfacesJsonConverter Namespace Reference
Functions
template<typename index_grid >
nlohmann::json convertImpl (const index_grid &indexGrid)
The actual conversion method.
template<typename instance_type >
void convert (nlohmann::json &jIndexedSurfaces, const Experimental::SurfaceCandidatesUpdator &delegate,[[maybe_unused]] const instance_type &refInstance)
Convert the single delegate if it is of the type of the reference.
template<typename tuple_type , std::size_t... I>
void unrollConvert (nlohmann::json &jIndexedSurfaces, const Experimental::SurfaceCandidatesUpdator &delegate, const tuple_type &axesTuple, std::index_sequence< I...>)
Unrolling function for catching the right instance.
static nlohmann::json toJson (const Experimental::SurfaceCandidatesUpdator &delegate)
Experimental::SurfaceCandidatesUpdator fromJson (const nlohmann::json &jSurfaceNavigation)
Convert the single delegate if it is of the type of the reference.
Variables
static auto s_possibleAxes
Function Documentation
template<typename instance_type > void Acts::IndexedSurfacesJsonConverter::convert (nlohmann::json & jIndexedSurfaces, const Experimental::SurfaceCandidatesUpdator & delegate, [[maybe_unused] ] const instance_type & refInstance)
Convert the single delegate if it is of the type of the reference.
Note
It will do nothing if the type does not match
Parameters
jIndexedSurfaces the json object to be filled
delegate the delegate to be translated
refInstance is a reference instance of potential type casting
Definition at line 86 of file IndexedSurfacesJsonConverter.hpp.
View newest version in sPHENIX GitHub at line 86 of file IndexedSurfacesJsonConverter.hpp
template<typename index_grid > nlohmann::json Acts::IndexedSurfacesJsonConverter::convertImpl (const index_grid & indexGrid)
The actual conversion method.
Definition at line 57 of file IndexedSurfacesJsonConverter.hpp.
View newest version in sPHENIX GitHub at line 57 of file IndexedSurfacesJsonConverter.hpp
References Acts::Transform3JsonConverter::toJson(), Acts::GridJsonConverter::toJson(), and physmon_ckf_tracking::u.
Acts::Experimental::SurfaceCandidatesUpdator Acts::IndexedSurfacesJsonConverter::fromJson (const nlohmann::json & jVolumeBounds)
Convert the single delegate if it is of the type of the reference.
Parameters
jSurfaceNavigation the json file to read from
Returns
the surface navigation delegate
Convert the single delegate if it is of the type of the reference.
Conversion to surfaceBounds from json
The type is given as a template argument in order to be able to construct the correct fitting types for surfaces.
Parameters
j the read-in json object
Returns
a shared_ptr to a surface object for type polymorphism
Convert the single delegate if it is of the type of the reference.
Conversion to volume bounds from json
The type is given as a template argument in order to be able to construct the correct fitting types for surfaces.
Parameters
jVolumeBounds the read-in json object
Returns
a unique_ptr to a volume bounds object for type polymorphism
Conversion to volume bounds from json
Parameters
jVolumeBounds the read-in json object
Returns
a unique_ptr to a volume bounds object for type polymorphism
Definition at line 59 of file IndexedSurfacesJsonConverter.cpp.
View newest version in sPHENIX GitHub at line 59 of file IndexedSurfacesJsonConverter.cpp
References bins, Acts::Transform3JsonConverter::fromJson(), grid(), std::tr1::make_tuple(), testing::internal::move(), Acts::Test::transform, Acts::Experimental::tryAllPortalsAndSurfaces(), and physmon_ckf_tracking::u.
static nlohmann::json Acts::IndexedSurfacesJsonConverter::toJson (const Experimental::SurfaceCandidatesUpdator & delegate) inline static
Convert a surface array into needed constituents
Parameters
delegate the delegate to be translated
Note
this is the entry point of the conversion, i.e. top of the unrolling loop
Returns
a collection of proto surface object and a grid, and associations
Definition at line 129 of file IndexedSurfacesJsonConverter.hpp.
View newest version in sPHENIX GitHub at line 129 of file IndexedSurfacesJsonConverter.hpp
References Acts::Experimental::s_possibleAxes, Acts::Svg::IndexedSurfacesConverter::unrollConvert(), and value.
template<typename tuple_type , std::size_t... I> void Acts::IndexedSurfacesJsonConverter::unrollConvert (nlohmann::json & jIndexedSurfaces, const Experimental::SurfaceCandidatesUpdator & delegate, const tuple_type & axesTuple, std::index_sequence< I...>)
Unrolling function for catching the right instance.
Parameters
jIndexedSurfaces the json object to be filled
delegate the delegate to be translated
axesTuple the tuple of axes to be unrolled
Note
parameters are as of the convertImpl method
Definition at line 114 of file IndexedSurfacesJsonConverter.hpp.
View newest version in sPHENIX GitHub at line 114 of file IndexedSurfacesJsonConverter.hpp
References Acts::Svg::DetectorConverter::convert().
Variable Documentation
auto Acts::IndexedSurfacesJsonConverter::s_possibleAxes static
Initial value:
=
    std::tuple<EqBound, EqOpen, EqClosed,
               VarBound, VarOpen, VarClosed,
               EqBoundEqBound, EqBoundEqOpen, EqBoundEqClosed, EqOpenEqBound,
               EqOpenEqOpen, EqOpenEqClosed, EqClosedEqBound, EqClosedEqOpen,
               EqClosedEqClosed,
               EqBoundVarBound, EqBoundVarOpen, EqBoundVarClosed,
               EqOpenVarBound, EqOpenVarOpen, EqOpenVarClosed, EqClosedVarBound,
               EqClosedVarOpen, EqClosedVarClosed,
               VarBoundEqBound, VarBoundEqOpen, VarBoundEqClosed,
               VarOpenEqBound, VarOpenEqOpen, VarOpenEqClosed, VarClosedEqBound,
               VarClosedEqOpen, VarClosedEqClosed,
               VarBoundVarBound, VarBoundVarOpen, VarBoundVarClosed,
               VarOpenVarBound, VarOpenVarOpen, VarOpenVarClosed,
               VarClosedVarBound, VarClosedVarOpen, VarClosedVarClosed>{}
Definition at line 34 of file IndexedSurfacesJsonConverter.hpp.
View newest version in sPHENIX GitHub at line 34 of file IndexedSurfacesJsonConverter.hpp