Analysis Software: Acts::detail::DifferenceCalculator< indices_t, kParameters > Struct Template Reference
Acts::detail::DifferenceCalculator< indices_t, kParameters > Struct Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/EventData/detail/DifferenceCalculator.hpp>
Public Types
using StorageSequence = std::make_index_sequence< sizeof...(kParameters)>
Static Public Member Functions
template<typename lhs_t , typename rhs_t >
static auto run (const Eigen::MatrixBase< lhs_t > &lhs, const Eigen::MatrixBase< rhs_t > &rhs)
template<typename lhs_t , typename rhs_t , std::size_t... kStorage>
static auto runImpl (const Eigen::MatrixBase< lhs_t > &lhs, const Eigen::MatrixBase< rhs_t > &rhs, std::index_sequence< kStorage...>) -> std::decay_t< decltype((lhs-rhs).eval())>
Detailed Description
template<typename indices_t, indices_t... kParameters>
struct Acts::detail::DifferenceCalculator< indices_t, kParameters >
Compute the minimal difference between parameters within the nominal range.
Template Parameters
indices_t Parameter indices enum type
kParameters Parameter indices pack that defines the used parameter
Definition at line 25 of file DifferenceCalculator.hpp.
View newest version in sPHENIX GitHub at line 25 of file DifferenceCalculator.hpp
Member Typedef Documentation
template<typename indices_t , indices_t... kParameters> using Acts::detail::DifferenceCalculator< indices_t, kParameters >::StorageSequence = std::make_index_sequence<sizeof...(kParameters)>
Definition at line 26 of file DifferenceCalculator.hpp.
View newest version in sPHENIX GitHub at line 26 of file DifferenceCalculator.hpp
Member Function Documentation
template<typename indices_t , indices_t... kParameters> template<typename lhs_t , typename rhs_t > static auto Acts::detail::DifferenceCalculator< indices_t, kParameters >::run (const Eigen::MatrixBase< lhs_t > & lhs, const Eigen::MatrixBase< rhs_t > & rhs) inline static
Run the difference calculation.
Parameters
rhs Right-hand-side input vector
lhs Left-hand-side input vector
Returns
minimal, corrected (lhs - rhs) difference within the nominal range
Definition at line 34 of file DifferenceCalculator.hpp.
View newest version in sPHENIX GitHub at line 34 of file DifferenceCalculator.hpp
References Acts::detail::DifferenceCalculator< indices_t, kParameters >::runImpl().
Referenced by Acts::ParameterSet< parameter_indices_t, params...>::residual().
template<typename indices_t , indices_t... kParameters> template<typename lhs_t , typename rhs_t , std::size_t... kStorage> static auto Acts::detail::DifferenceCalculator< indices_t, kParameters >::runImpl (const Eigen::MatrixBase< lhs_t > & lhs, const Eigen::MatrixBase< rhs_t > & rhs, std::index_sequence< kStorage...>) -> std::decay_t<decltype((lhs - rhs).eval())> inline static
Definition at line 40 of file DifferenceCalculator.hpp.
View newest version in sPHENIX GitHub at line 40 of file DifferenceCalculator.hpp
Referenced by Acts::detail::DifferenceCalculator< indices_t, kParameters >::run().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/EventData/detail/DifferenceCalculator.hpp