Analysis Software: acts/blob/sPHENIX/Core/src/Geometry/TrackingVolume.cpp File Reference
TrackingVolume.cpp File Reference
#include "Acts/Geometry/TrackingVolume.hpp"
#include "Acts/Definitions/Direction.hpp"
#include "Acts/Definitions/Tolerance.hpp"
#include "Acts/Geometry/GeometryIdentifier.hpp"
#include "Acts/Geometry/GlueVolumesDescriptor.hpp"
#include "Acts/Geometry/VolumeBounds.hpp"
#include "Acts/Material/IMaterialDecorator.hpp"
#include "Acts/Material/IVolumeMaterial.hpp"
#include "Acts/Material/ProtoVolumeMaterial.hpp"
#include "Acts/Propagator/Navigator.hpp"
#include "Acts/Surfaces/Surface.hpp"
#include "Acts/Utilities/BinningType.hpp"
#include "Acts/Utilities/Frustum.hpp"
#include "Acts/Utilities/Ray.hpp"
#include <algorithm>
#include <array>
#include <functional>
#include <ostream>
#include <string>
#include <tuple>
#include <type_traits>
#include <utility>
Namespaces
namespace Acts
Acts includes to create all necessary definitions.
Functions
m_name (volumeName)
Function Documentation
m_name (volumeName)
Definition at line 65 of file TrackingVolume.cpp.
View newest version in sPHENIX GitHub at line 65 of file TrackingVolume.cpp
Referenced by CylindricalVolumeBuilder< surface_type, surface_bounds_type >::construct(), PHG4MicromegasDetector::construct_fee_board(), ActsExamples::IAlgorithm::name(), Acts::Experimental::Detector::name(), Acts::Experimental::DetectorVolume::name(), Jetscape::JetScapeModuleBase::SetXMLMainFileName(), Jetscape::JetScapeXML::SetXMLMainFileName(), Jetscape::JetScapeXML::SetXMLMasterFileName(), Jetscape::JetScapeModuleBase::SetXMLUserFileName(), and Jetscape::JetScapeXML::SetXMLUserFileName().