Analysis Software: ClusterJetInput Class Reference
ClusterJetInput Class Reference
#include <coresoftware/blob/master/offline/packages/jetbase/ClusterJetInput.h>
Public Member Functions
ClusterJetInput (Jet::SRC input)
~ClusterJetInput () override
void identify (std::ostream &os=std::cout) override
Jet::SRC get_src () override
std::vector< Jet * > get_input (PHCompositeNode *topNode) override
Public Member Functions inherited from JetInput
virtual ~JetInput ()
virtual int Verbosity () const
virtual void Verbosity (int i)
Private Attributes
int m_Verbosity = 0
Jet::SRC m_Input = Jet::VOID
Additional Inherited Members
Protected Member Functions inherited from JetInput
JetInput ()
Detailed Description
Definition at line 17 of file ClusterJetInput.h.
View newest version in sPHENIX GitHub at line 17 of file ClusterJetInput.h
Constructor & Destructor Documentation
ClusterJetInput::ClusterJetInput (Jet::SRC input)
Definition at line 22 of file ClusterJetInput.cc.
View newest version in sPHENIX GitHub at line 22 of file ClusterJetInput.cc
ClusterJetInput::~ClusterJetInput () inline override
Definition at line 21 of file ClusterJetInput.h.
View newest version in sPHENIX GitHub at line 21 of file ClusterJetInput.h
Member Function Documentation
std::vector< Jet * > ClusterJetInput::get_input (PHCompositeNode * topNode) override virtual
Reimplemented from JetInput.
Definition at line 49 of file ClusterJetInput.cc.
View newest version in sPHENIX GitHub at line 49 of file ClusterJetInput.cc
References assert, GlobalVertexMap::begin(), Jet::CEMC_CLUSTER, clusters, Jet::ECAL_TOPO_CLUSTER, Jet::EEMC_CLUSTER, GlobalVertexMap::empty(), Jet::FEMC_CLUSTER, Jet::FHCAL_CLUSTER, RawCluster::get_energy(), RawCluster::get_id(), GlobalVertex::get_x(), GlobalVertex::get_y(), GlobalVertex::get_z(), RawClusterContainer::getClusters(), RawClusterUtility::GetEVec(), Jet::HCAL_TOPO_CLUSTER, Jet::HCALIN_CLUSTER, Jet::HCALOUT_CLUSTER, Jet::insert_comp(), m_Input, m_Verbosity, Jet::set_e(), Jet::set_px(), Jet::set_py(), and Jet::set_pz().
Jet::SRC ClusterJetInput::get_src () inline override virtual
Reimplemented from JetInput.
Definition at line 25 of file ClusterJetInput.h.
View newest version in sPHENIX GitHub at line 25 of file ClusterJetInput.h
References m_Input.
void ClusterJetInput::identify (std::ostream & os = std::cout) override virtual
Reimplemented from JetInput.
Definition at line 27 of file ClusterJetInput.cc.
View newest version in sPHENIX GitHub at line 27 of file ClusterJetInput.cc
References Jet::CEMC_CLUSTER, Jet::EEMC_CLUSTER, Jet::HCALIN_CLUSTER, Jet::HCALOUT_CLUSTER, and m_Input.
Member Data Documentation
Jet::SRC ClusterJetInput::m_Input = Jet::VOID private
Definition at line 31 of file ClusterJetInput.h.
View newest version in sPHENIX GitHub at line 31 of file ClusterJetInput.h
Referenced by get_input(), get_src(), and identify().
int ClusterJetInput::m_Verbosity = 0 private
Definition at line 30 of file ClusterJetInput.h.
View newest version in sPHENIX GitHub at line 30 of file ClusterJetInput.h
Referenced by get_input().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/jetbase/ClusterJetInput.h
coresoftware/blob/master/offline/packages/jetbase/ClusterJetInput.cc