Analysis Software: acts/blob/sPHENIX/Examples/Scripts/TrackingPerformance/CommonUtils.h File Reference
CommonUtils.h File Reference
#include <functional>
#include <limits>
#include <TColor.h>
#include <TDirectory.h>
#include <TH1F.h>
#include <TString.h>
Classes
struct ResidualPullHandle
struct SingleHandle
This is a s.
struct AcceptCombination
struct AcceptAll
This Struct is to accept all values - a placeholder.
struct AcceptRange
struct DirectAccessor< primitive_t >
struct DivisionAccessor< primitive_one_t, primitive_two_t >
struct ResidualAccessor
struct QopResidualAccessor
struct PtResidualAccessor
This the dedicted pT residual accessor.
struct PtErrorAccessor
Functions
template<typename hist_t >
void setHistStyle (hist_t *hist, short color=1)
template<typename eff_t >
void setEffStyle (eff_t *eff, short color=1)
template<typename hist_t >
void adaptColorPalette (hist_t *h, float rmin, float rmax, float rgood, float rwindow, int n)
template<typename eff_t >
void adaptEffRange (eff_t *eff, float minScale=1, float maxScale=1.1)
template<typename dir_t , typename tree_t >
void estimateResiudalRange (ResidualPullHandle &handle, dir_t &directory, tree_t &tree, unsigned long peakEntries, unsigned int hBarcode)
template<typename dir_t , typename tree_t >
void estimateIntegerRange (SingleHandle &handle, dir_t &directory, tree_t &tree, unsigned long peakEntries, unsigned int startBins, unsigned int addBins, unsigned int hBarcode)
void bookHistograms (ResidualPullHandle &handle, float pullRange, unsigned int hBins, unsigned int hBarcode)
template<typename tree_t >
unsigned long estimateEntries (const tree_t &tree, unsigned long configuredEntries)
Function Documentation
template<typename hist_t > void adaptColorPalette (hist_t * h, float rmin, float rmax, float rgood, float rwindow, int n)
Helper function: set color palette
Template Parameters
type of the histogram
Parameters
h the histogram in question
rmin the range min value
rmax the range max value
rgood the good value of the mistogram
rwindow the window around the good value to be declared good
n the number of divisions
Definition at line 70 of file CommonUtils.h.
View newest version in sPHENIX GitHub at line 70 of file CommonUtils.h
References Acts::Test::blue, Acts::Test::green, and Acts::Test::red.
Referenced by boundParamResolution().
template<typename eff_t > void adaptEffRange (eff_t * eff, float minScale = 1, float maxScale = 1.1)
Helper function: increase eff range by a scale factor. Note that it assumes the eff has already been drawn
Template Parameters
eff_t the efficiency histogram type
Parameters
eff the efficiency histogram
minScale the minimum of the scale
maxScale the maximum of the scale
Definition at line 98 of file CommonUtils.h.
View newest version in sPHENIX GitHub at line 98 of file CommonUtils.h
References ymax, and ymin.
void bookHistograms (ResidualPullHandle & handle, float pullRange, unsigned int hBins, unsigned int hBarcode)
Helper method to book residual and pull histograms
Parameters
handle the residual/pull handle
pullRange the symmetric pull range for plotting
hBins the number of histograms bins
hBarcoode a temporary unique barcode for ROOT memory management
Definition at line 459 of file CommonUtils.h.
View newest version in sPHENIX GitHub at line 459 of file CommonUtils.h
References ResidualPullHandle::errorStr, ResidualPullHandle::pullHist, ResidualPullHandle::range, ResidualPullHandle::residualHist, ResidualPullHandle::residualStr, ResidualPullHandle::residualUnit, and ResidualPullHandle::tag.
template<typename tree_t > unsigned long estimateEntries (const tree_t & tree, unsigned long configuredEntries)
Helper method to get and opentially overwrite the entries to be processed
Template Parameters
tree_t the type of the tree
Parameters
tree is the TTree/TChain in question
configuredEntries is a configuration parameter
Returns
the number of entries
Definition at line 493 of file CommonUtils.h.
View newest version in sPHENIX GitHub at line 493 of file CommonUtils.h
template<typename dir_t , typename tree_t > void estimateIntegerRange (SingleHandle & handle, dir_t & directory, tree_t & tree, unsigned long peakEntries, unsigned int startBins, unsigned int addBins, unsigned int hBarcode)
Range estimation for integer values
Template Parameters
dir_t the type of the directory to change into for writing
tree_t the type of the tree to Draw from
Parameters
handle the residual/pull handle to be processed
directory the writable directory
tree the tree from which is drawn
peakEntries the number of entries for the range peak
hBarcode a temporary unique ROOT barcode for memory managements
Definition at line 417 of file CommonUtils.h.
View newest version in sPHENIX GitHub at line 417 of file CommonUtils.h
References SingleHandle::bins, add_histos_bX::ib, SingleHandle::range, and SingleHandle::rangeDrawStr.
template<typename dir_t , typename tree_t > void estimateResiudalRange (ResidualPullHandle & handle, dir_t & directory, tree_t & tree, unsigned long peakEntries, unsigned int hBarcode)
Range estimation for residuals
Template Parameters
dir_t the type of the directory to change into for writing
tree_t the type of the tree to Draw from
Parameters
handle the residual/pull handle to be processed
directory the writable directory
tree the tree from which is drawn
peakEntries the number of entries for the range peak
hBarcode a temporary unique ROOT barcode for memory managements
Definition at line 383 of file CommonUtils.h.
View newest version in sPHENIX GitHub at line 383 of file CommonUtils.h
References ResidualPullHandle::range, ResidualPullHandle::rangeCutStr, ResidualPullHandle::rangeDrawStr, ResidualPullHandle::rangeHist, ResidualPullHandle::rangeMaxStr, and rms().
template<typename eff_t > void setEffStyle (eff_t * eff, short color = 1)
Helper function: function to set up the efficiency histogram style
Template Parameters
eff_t the efficiency histogram type
Parameters
eff the efficiency histogram
color the color to be set
Definition at line 51 of file CommonUtils.h.
View newest version in sPHENIX GitHub at line 51 of file CommonUtils.h
References color.
Referenced by reconstructionPerformance().
template<typename hist_t > void setHistStyle (hist_t * hist, short color = 1)
Helper function: function to set up the histogram style
Template Parameters
hist_t the histogram type
Parameters
hist the histogram
color the color
Definition at line 27 of file CommonUtils.h.
View newest version in sPHENIX GitHub at line 27 of file CommonUtils.h
References color.
Referenced by boundParamResolution(), and reconstructionPerformance().