Analysis Software: testing::internal::WhenDynamicCastToMatcherBase< To > Class Template Reference
testing::internal::WhenDynamicCastToMatcherBase< To > Class Template Reference
#include <JETSCAPE/blob/main/external_packages/googletest/googlemock/include/gmock/gmock-matchers.h>
Public Member Functions
WhenDynamicCastToMatcherBase (const Matcher< To > &matcher)
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
Static Protected Member Functions
static string GetToName ()
Protected Attributes
const Matcher< To > matcher_
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (WhenDynamicCastToMatcherBase)
Static Private Member Functions
static void GetCastTypeDescription (::std::ostream *os)
Detailed Description
template<typename To>
class testing::internal::WhenDynamicCastToMatcherBase< To >
Definition at line 2108 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 2108 of file gmock-matchers.h
Constructor & Destructor Documentation
template<typename To> testing::internal::WhenDynamicCastToMatcherBase< To >::WhenDynamicCastToMatcherBase (const Matcher< To > & matcher) inline explicit
Definition at line 2110 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 2110 of file gmock-matchers.h
Member Function Documentation
template<typename To> void testing::internal::WhenDynamicCastToMatcherBase< To >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 2118 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 2118 of file gmock-matchers.h
template<typename To> void testing::internal::WhenDynamicCastToMatcherBase< To >::DescribeTo (::std::ostream * os) const inline
Definition at line 2113 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 2113 of file gmock-matchers.h
template<typename To> static void testing::internal::WhenDynamicCastToMatcherBase< To >::GetCastTypeDescription (::std::ostream * os) inline static private
Definition at line 2135 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 2135 of file gmock-matchers.h
Referenced by testing::internal::WhenDynamicCastToMatcherBase< To & >::DescribeNegationTo(), and testing::internal::WhenDynamicCastToMatcherBase< To & >::DescribeTo().
template<typename To> static string testing::internal::WhenDynamicCastToMatcherBase< To >::GetToName () inline static protected
Definition at line 2126 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 2126 of file gmock-matchers.h
Referenced by testing::internal::WhenDynamicCastToMatcherBase< To & >::GetCastTypeDescription().
template<typename To> testing::internal::WhenDynamicCastToMatcherBase< To >::GTEST_DISALLOW_ASSIGN_ (WhenDynamicCastToMatcherBase< To >) private
Member Data Documentation
template<typename To> const Matcher<To> testing::internal::WhenDynamicCastToMatcherBase< To >::matcher_ protected
Definition at line 2124 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 2124 of file gmock-matchers.h
Referenced by testing::internal::WhenDynamicCastToMatcherBase< To & >::DescribeNegationTo(), testing::internal::WhenDynamicCastToMatcherBase< To & >::DescribeTo(), and testing::internal::WhenDynamicCastToMatcher< To >::MatchAndExplain().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/googletest/googlemock/include/gmock/gmock-matchers.h