Analysis Software: Acts::PlanarModuleStepper Class Reference
Acts::PlanarModuleStepper Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Digitization/PlanarModuleStepper.hpp>
Public Member Functions
PlanarModuleStepper (std::unique_ptr< const Logger > mlogger=getDefaultLogger("PlanarModuleStepper", Logging::INFO))
~PlanarModuleStepper ()=default
Destructor.
std::vector< DigitizationStep > cellSteps (const GeometryContext &gctx, const DigitizationModule &dmodule, const Vector3 &startPoint, const Vector3 &endPoint) const
std::vector< DigitizationStep > cellSteps (const GeometryContext &gctx, const DigitizationModule &dmodule, const Vector2 &moduleIntersection, const Vector3 &trackDirection) const
void setLogger (std::unique_ptr< const Logger > logger)
Private Member Functions
const Logger & logger () const
Private access method to the logging instance.
Private Attributes
std::unique_ptr< const Logger > m_logger
logging instance
Detailed Description
Module for fast, geometric digitization this is a planar module stepper that calculates the step length in given segmentations and retrunes digitisation steps
Definition at line 31 of file PlanarModuleStepper.hpp.
View newest version in sPHENIX GitHub at line 31 of file PlanarModuleStepper.hpp
Constructor & Destructor Documentation
Acts::PlanarModuleStepper::PlanarModuleStepper (std::unique_ptr< const Logger > mlogger = getDefaultLogger("PlanarModuleStepper", Logging::INFO))
Constructor
Parameters
mlogger is the logging instance
Definition at line 25 of file PlanarModuleStepper.cpp.
View newest version in sPHENIX GitHub at line 25 of file PlanarModuleStepper.cpp
Acts::PlanarModuleStepper::~PlanarModuleStepper () default
Destructor.
Member Function Documentation
std::vector< Acts::DigitizationStep > Acts::PlanarModuleStepper::cellSteps (const GeometryContext & gctx, const DigitizationModule & dmodule, const Vector3 & startPoint, const Vector3 & endPoint) const
Calculate the steps caused by this track - full simulation interface
Parameters
gctx The current geometry context object, e.g. alignment
dmodule is the digitization module
startPoint is the starting position of the stepping
endPoint is the end position of the stepping
Returns
is the vector of digitization steps
Definition at line 29 of file PlanarModuleStepper.cpp.
View newest version in sPHENIX GitHub at line 29 of file PlanarModuleStepper.cpp
References Acts::ACTS_VERBOSE(), Acts::DigitizationModule::digitizationStep(), Acts::Intersection< 3 >::forwardOrder(), norm, Acts::Experimental::detail::BlueprintHelper::sort(), and Acts::DigitizationModule::stepSurfaces().
Referenced by Acts::Test::BOOST_DATA_TEST_CASE().
std::vector< Acts::DigitizationStep > Acts::PlanarModuleStepper::cellSteps (const GeometryContext & gctx, const DigitizationModule & dmodule, const Vector2 & moduleIntersection, const Vector3 & trackDirection) const
Calculate the steps caused by this track - fast simulation interface
Parameters
gctx The current geometry context object, e.g. alignment
dmodule is the digitization module
moduleIntersection is the 2d intersection at the module surface
trackDirection is the track direction at the intersection
Returns
is the vector of digitization steps
Definition at line 80 of file PlanarModuleStepper.cpp.
View newest version in sPHENIX GitHub at line 80 of file PlanarModuleStepper.cpp
References Acts::ACTS_VERBOSE(), Acts::DigitizationModule::boundarySurfaces(), Acts::Intersection< 3 >::forwardOrder(), position, and Acts::Experimental::detail::BlueprintHelper::sort().
const Logger& Acts::PlanarModuleStepper::logger () const inline private
Private access method to the logging instance.
Definition at line 77 of file PlanarModuleStepper.hpp.
View newest version in sPHENIX GitHub at line 77 of file PlanarModuleStepper.hpp
References m_logger.
void Acts::PlanarModuleStepper::setLogger (std::unique_ptr< const Logger > logger) inline
Set logging instance
Parameters
logger is the logging instance to be set
Definition at line 71 of file PlanarModuleStepper.hpp.
View newest version in sPHENIX GitHub at line 71 of file PlanarModuleStepper.hpp
References m_logger, and testing::internal::move().
Member Data Documentation
std::unique_ptr<const Logger> Acts::PlanarModuleStepper::m_logger private
logging instance
Definition at line 80 of file PlanarModuleStepper.hpp.
View newest version in sPHENIX GitHub at line 80 of file PlanarModuleStepper.hpp
Referenced by logger(), and setLogger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Digitization/PlanarModuleStepper.hpp
acts/blob/sPHENIX/Core/src/Digitization/PlanarModuleStepper.cpp