Analysis Software: prototype/blob/master/macros/tpc2019/Fun4All_G4_TPC.C File Reference
Fun4All_G4_TPC.C File Reference
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/SubsysReco.h>
#include <g4eval/SvtxEvaluator.h>
#include <g4eval/TrkrEvaluator.h>
#include <g4detectors/PHG4BlockSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <phgeom/PHGeomFileImport.h>
#include <g4tpc/PHG4TpcDigitizer.h>
#include <g4tpc/PHG4TpcElectronDrift.h>
#include <g4tpc/PHG4TpcPadPlane.h>
#include <g4tpc/PHG4TpcPadPlaneReadout.h>
#include <g4tpc/PHG4TpcSubsystem.h>
#include <trackreco/PHGenFitTrkFitter.h>
#include <trackreco/PHGenFitTrkProp.h>
#include <trackreco/PHHoughSeeding.h>
#include <trackreco/PHInitVertexing.h>
#include <trackreco/PHTrackSeeding.h>
#include <trackreco/PHTruthTrackSeeding.h>
#include <trackreco/PHTruthVertexing.h>
#include <g4eval/PHG4DSTReader.h>
#include <g4histos/G4HitNtuple.h>
#include <g4main/PHG4ParticleGenerator.h>
#include <g4main/PHG4ParticleGun.h>
#include <g4main/PHG4SimpleEventGenerator.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <phool/recoConsts.h>
#include <tpc2019/TpcPrototypeClusterizer.h>
#include <tpc2019/TpcPrototypeGenFitTrkFinder.h>
#include <tpc2019/TpcPrototypeGenFitTrkFitter.h>
Functions
int Fun4All_G4_TPC (int nEvents=100, bool eventDisp=false, int verbosity=0)
void RunLoadTest ()
Variables
int n_tpc_layer_inner = 0
int tpc_layer_rphi_count_inner = 1152
int n_tpc_layer_mid = 16
int n_tpc_layer_outer = 0
int n_gas_layer = n_tpc_layer_inner + n_tpc_layer_mid + n_tpc_layer_outer
Function Documentation
int Fun4All_G4_TPC (int nEvents = 100, bool eventDisp = false, int verbosity = 0)
Definition at line 72 of file Fun4All_G4_TPC.C.
View newest version in sPHENIX GitHub at line 72 of file Fun4All_G4_TPC.C
References PHG4SimpleEventGenerator::add_particles(), PHG4DSTReader::AddNode(), PHG4DetectorSubsystem::BlackHole(), PHG4TpcElectronDrift::Detector(), SvtxEvaluator::do_cluster_eval(), SvtxEvaluator::do_eval_light(), SvtxEvaluator::do_g4hit_eval(), SvtxEvaluator::do_gpoint_eval(), SvtxEvaluator::do_hit_eval(), Acts::UnitConstants::e, Fun4AllServer::End(), eta, PHG4SimpleEventGenerator::Gaus, gen(), i, in, recoConsts::instance(), Fun4AllServer::instance(), testing::internal::Log(), momentum, nEvents, out, PHG4DetectorSubsystem::OverlapCheck(), ActsTests::PropagationDatasets::phi, Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), PHG4TpcElectronDrift::registerPadPlane(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), Fun4AllServer::run(), PHG4Reco::save_DST_geometry(), SvtxEvaluator::scan_for_embedded(), TpcPrototypeGenFitTrkFinder::set_do_eval(), TpcPrototypeGenFitTrkFitter::set_do_eval(), TpcPrototypeGenFitTrkFinder::set_do_evt_display(), TpcPrototypeGenFitTrkFitter::set_do_evt_display(), PHParameterInterface::set_double_param(), PHG4DetectorSubsystem::set_double_param(), PHG4SimpleEventGenerator::set_eta_range(), PHG4Reco::set_field(), PHParameterInterface::set_int_param(), PHFlag::set_IntFlag(), PHG4DSTReader::set_load_active_particle(), PHG4DSTReader::set_load_all_particle(), PHTruthTrackSeeding::set_min_clusters_per_track(), PHG4SimpleEventGenerator::set_p_range(), PHG4SimpleEventGenerator::set_phi_range(), PHG4DSTReader::set_save_particle(), PHG4DSTReader::set_save_vertex(), PHG4SimpleEventGenerator::set_vertex_distribution_function(), PHG4SimpleEventGenerator::set_vertex_distribution_mean(), PHG4SimpleEventGenerator::set_vertex_distribution_width(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4TpcDigitizer::SetADCThreshold(), PHG4TpcDigitizer::SetENC(), PHG4TpcDigitizer::SetTpcMinLayer(), PHG4DetectorSubsystem::SuperDetector(), ActsTests::PropagationDatasets::theta, verbosity, and Fun4AllBase::Verbosity().
void RunLoadTest ()
Definition at line 356 of file Fun4All_G4_TPC.C.
View newest version in sPHENIX GitHub at line 356 of file Fun4All_G4_TPC.C
Variable Documentation
int n_gas_layer = n_tpc_layer_inner + n_tpc_layer_mid + n_tpc_layer_outer
Definition at line 70 of file Fun4All_G4_TPC.C.
View newest version in sPHENIX GitHub at line 70 of file Fun4All_G4_TPC.C
int n_tpc_layer_inner = 0
Definition at line 66 of file Fun4All_G4_TPC.C.
View newest version in sPHENIX GitHub at line 66 of file Fun4All_G4_TPC.C
int n_tpc_layer_mid = 16
Definition at line 68 of file Fun4All_G4_TPC.C.
View newest version in sPHENIX GitHub at line 68 of file Fun4All_G4_TPC.C
int n_tpc_layer_outer = 0
Definition at line 69 of file Fun4All_G4_TPC.C.
View newest version in sPHENIX GitHub at line 69 of file Fun4All_G4_TPC.C
int tpc_layer_rphi_count_inner = 1152
Definition at line 67 of file Fun4All_G4_TPC.C.
View newest version in sPHENIX GitHub at line 67 of file Fun4All_G4_TPC.C