Analysis Software: TrkrClusterv5 Class Reference
TrkrClusterv5 Class Reference
Version 5 of TrkrCluster.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv5.h>
Public Member Functions
TrkrClusterv5 ()
ctor
~TrkrClusterv5 () override=default
dtor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void CopyFrom (const TrkrCluster &) override
copy content from base class
void CopyFrom (TrkrCluster *source) override
copy content from base class
float getPosition (int coor) const override
void setPosition (int coor, float xi) override
float getLocalX () const override
void setLocalX (float loc0) override
float getLocalY () const override
void setLocalY (float loc1) override
TrkrDefs::subsurfkey getSubSurfKey () const override
void setSubSurfKey (TrkrDefs::subsurfkey id) override
unsigned int getAdc () const override
void setAdc (unsigned int adc) override
unsigned int getMaxAdc () const override
void setMaxAdc (uint16_t maxadc) override
float getRPhiError () const override
float getZError () const override
void setPhiError (float phierror)
void setZError (float zerror)
float getX () const override
deprecated global funtions with a warning
float getY () const override
float getZ () const override
void setX (float) override
void setY (float) override
void setZ (float) override
float getSize (unsigned int, unsigned int) const override
void setSize (unsigned int, unsigned int, float) override
float getError (unsigned int, unsigned int) const override
void setError (unsigned int, unsigned int, float) override
char getSize () const override
float getPhiSize () const override
void setPhiSize (char phisize)
float getZSize () const override
void setZSize (char zsize)
char getOverlap () const override
void setOverlap (char overlap) override
char getEdge () const override
void setEdge (char edge) override
Public Member Functions inherited from TrkrCluster
~TrkrCluster () override=default
dtor
virtual void setTime (const float)
virtual float getTime () const
virtual float getPhiError () const
virtual void setActsLocalError (unsigned int, unsigned int, float)
Acts functions, for Acts modules use only.
virtual float getActsLocalError (unsigned int, unsigned int) const
virtual void setGlobal ()
virtual void setLocal ()
virtual bool isGlobal () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
float m_local [2]
TrkrDefs::subsurfkey m_subsurfkey
float m_phierr
float m_zerr
unsigned short int m_adc
unsigned short int m_maxadc
char m_phisize
char m_zsize
char m_overlap
char m_edge
Additional Inherited Members
Protected Member Functions inherited from TrkrCluster
TrkrCluster ()=default
Detailed Description
Version 5 of TrkrCluster.
This version of TrkrCluster is blown up to contain a maximum of information
Definition at line 22 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 22 of file TrkrClusterv5.h
Constructor & Destructor Documentation
TrkrClusterv5::TrkrClusterv5 ()
ctor
Definition at line 19 of file TrkrClusterv5.cc.
View newest version in sPHENIX GitHub at line 19 of file TrkrClusterv5.cc
References i, and m_local.
Referenced by CloneMe().
TrkrClusterv5::~TrkrClusterv5 () override default
dtor
Member Function Documentation
PHObject* TrkrClusterv5::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 37 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 37 of file TrkrClusterv5.h
References TrkrClusterv5().
void TrkrClusterv5::CopyFrom (const TrkrCluster & source) override virtual
copy content from base class
Reimplemented from TrkrCluster.
Definition at line 62 of file TrkrClusterv5.cc.
View newest version in sPHENIX GitHub at line 62 of file TrkrClusterv5.cc
References TrkrCluster::CopyFrom(), TrkrCluster::getAdc(), TrkrCluster::getEdge(), TrkrCluster::getLocalX(), TrkrCluster::getLocalY(), TrkrCluster::getMaxAdc(), TrkrCluster::getOverlap(), TrkrCluster::getPhiError(), TrkrCluster::getPhiSize(), TrkrCluster::getSubSurfKey(), TrkrCluster::getZError(), TrkrCluster::getZSize(), setAdc(), setEdge(), setLocalX(), setLocalY(), setMaxAdc(), setOverlap(), setPhiError(), setPhiSize(), setSubSurfKey(), setZError(), and setZSize().
void TrkrClusterv5::CopyFrom (TrkrCluster * source) inline override virtual
copy content from base class
Reimplemented from TrkrCluster.
Definition at line 46 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 46 of file TrkrClusterv5.h
References CopyFrom().
Referenced by CopyFrom().
unsigned int TrkrClusterv5::getAdc () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 65 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 65 of file TrkrClusterv5.h
References m_adc.
char TrkrClusterv5::getEdge () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 128 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 128 of file TrkrClusterv5.h
References m_edge.
float TrkrClusterv5::getError (unsigned int , unsigned int) const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 111 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 111 of file TrkrClusterv5.h
float TrkrClusterv5::getLocalX () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 54 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 54 of file TrkrClusterv5.h
References m_local.
Referenced by identify().
float TrkrClusterv5::getLocalY () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 56 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 56 of file TrkrClusterv5.h
References m_local.
Referenced by identify().
unsigned int TrkrClusterv5::getMaxAdc () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 73 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 73 of file TrkrClusterv5.h
References m_maxadc.
char TrkrClusterv5::getOverlap () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 125 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 125 of file TrkrClusterv5.h
References m_overlap.
float TrkrClusterv5::getPhiSize () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 119 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 119 of file TrkrClusterv5.h
References m_phisize.
float TrkrClusterv5::getPosition (int coor) const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 52 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 52 of file TrkrClusterv5.h
References m_local.
Referenced by isValid().
float TrkrClusterv5::getRPhiError () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 84 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 84 of file TrkrClusterv5.h
References m_phierr.
float TrkrClusterv5::getSize (unsigned int , unsigned int) const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 107 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 107 of file TrkrClusterv5.h
char TrkrClusterv5::getSize () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 116 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 116 of file TrkrClusterv5.h
References m_phisize, and m_zsize.
TrkrDefs::subsurfkey TrkrClusterv5::getSubSurfKey () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 59 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 59 of file TrkrClusterv5.h
References m_subsurfkey.
float TrkrClusterv5::getX () const inline override virtual
deprecated global funtions with a warning
Reimplemented from TrkrCluster.
Definition at line 95 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 95 of file TrkrClusterv5.h
float TrkrClusterv5::getY () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 97 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 97 of file TrkrClusterv5.h
float TrkrClusterv5::getZ () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 99 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 99 of file TrkrClusterv5.h
float TrkrClusterv5::getZError () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 86 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 86 of file TrkrClusterv5.h
References m_zerr.
float TrkrClusterv5::getZSize () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 122 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 122 of file TrkrClusterv5.h
References m_zsize.
void TrkrClusterv5::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from TrkrCluster.
Definition at line 36 of file TrkrClusterv5.cc.
View newest version in sPHENIX GitHub at line 36 of file TrkrClusterv5.cc
References getLocalX(), getLocalY(), and isValid().
int TrkrClusterv5::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from TrkrCluster.
Definition at line 51 of file TrkrClusterv5.cc.
View newest version in sPHENIX GitHub at line 51 of file TrkrClusterv5.cc
References getPosition(), i, and m_adc.
Referenced by identify().
void TrkrClusterv5::Reset () inline override virtual
Clear Event.
Reimplemented from TrkrCluster.
Definition at line 35 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 35 of file TrkrClusterv5.h
void TrkrClusterv5::setAdc (unsigned int adc) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 69 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 69 of file TrkrClusterv5.h
References m_adc.
Referenced by CopyFrom().
void TrkrClusterv5::setEdge (char edge) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 129 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 129 of file TrkrClusterv5.h
References m_edge.
Referenced by CopyFrom().
void TrkrClusterv5::setError (unsigned int , unsigned int , float) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 113 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 113 of file TrkrClusterv5.h
void TrkrClusterv5::setLocalX (float loc0) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 55 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 55 of file TrkrClusterv5.h
References physmon_track_finding_ttbar::loc0, and m_local.
Referenced by CopyFrom().
void TrkrClusterv5::setLocalY (float loc1) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 57 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 57 of file TrkrClusterv5.h
References m_local.
Referenced by CopyFrom().
void TrkrClusterv5::setMaxAdc (uint16_t maxadc) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 77 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 77 of file TrkrClusterv5.h
References m_maxadc.
Referenced by CopyFrom().
void TrkrClusterv5::setOverlap (char overlap) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 126 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 126 of file TrkrClusterv5.h
References m_overlap.
Referenced by CopyFrom().
void TrkrClusterv5::setPhiError (float phierror) inline
Definition at line 89 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 89 of file TrkrClusterv5.h
References m_phierr.
Referenced by CopyFrom().
void TrkrClusterv5::setPhiSize (char phisize) inline
Definition at line 120 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 120 of file TrkrClusterv5.h
References m_phisize, and phisize.
Referenced by CopyFrom().
void TrkrClusterv5::setPosition (int coor, float xi) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 53 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 53 of file TrkrClusterv5.h
References m_local.
void TrkrClusterv5::setSize (unsigned int , unsigned int , float) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 109 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 109 of file TrkrClusterv5.h
void TrkrClusterv5::setSubSurfKey (TrkrDefs::subsurfkey id) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 60 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 60 of file TrkrClusterv5.h
References train_ambiguity_solver::id, and m_subsurfkey.
Referenced by CopyFrom().
void TrkrClusterv5::setX (float) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 101 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 101 of file TrkrClusterv5.h
void TrkrClusterv5::setY (float) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 103 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 103 of file TrkrClusterv5.h
void TrkrClusterv5::setZ (float) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 105 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 105 of file TrkrClusterv5.h
void TrkrClusterv5::setZError (float zerror) inline
Definition at line 91 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 91 of file TrkrClusterv5.h
References m_zerr.
Referenced by CopyFrom().
void TrkrClusterv5::setZSize (char zsize) inline
Definition at line 123 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 123 of file TrkrClusterv5.h
References m_zsize, and zsize.
Referenced by CopyFrom().
Member Data Documentation
unsigned short int TrkrClusterv5::m_adc protected
Definition at line 144 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 144 of file TrkrClusterv5.h
Referenced by getAdc(), isValid(), and setAdc().
char TrkrClusterv5::m_edge protected
Definition at line 149 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 149 of file TrkrClusterv5.h
Referenced by getEdge(), and setEdge().
float TrkrClusterv5::m_local[2] protected
Definition at line 140 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 140 of file TrkrClusterv5.h
Referenced by getLocalX(), getLocalY(), getPosition(), setLocalX(), setLocalY(), setPosition(), and TrkrClusterv5().
unsigned short int TrkrClusterv5::m_maxadc protected
Definition at line 145 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 145 of file TrkrClusterv5.h
Referenced by getMaxAdc(), and setMaxAdc().
char TrkrClusterv5::m_overlap protected
Definition at line 148 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 148 of file TrkrClusterv5.h
Referenced by getOverlap(), and setOverlap().
float TrkrClusterv5::m_phierr protected
Definition at line 142 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 142 of file TrkrClusterv5.h
Referenced by getRPhiError(), and setPhiError().
char TrkrClusterv5::m_phisize protected
Definition at line 146 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 146 of file TrkrClusterv5.h
Referenced by getPhiSize(), getSize(), and setPhiSize().
TrkrDefs::subsurfkey TrkrClusterv5::m_subsurfkey protected
Definition at line 141 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 141 of file TrkrClusterv5.h
Referenced by getSubSurfKey(), and setSubSurfKey().
float TrkrClusterv5::m_zerr protected
Definition at line 143 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 143 of file TrkrClusterv5.h
Referenced by getZError(), and setZError().
char TrkrClusterv5::m_zsize protected
Definition at line 147 of file TrkrClusterv5.h.
View newest version in sPHENIX GitHub at line 147 of file TrkrClusterv5.h
Referenced by getSize(), getZSize(), and setZSize().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv5.h
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv5.cc