Analysis Software: prototype/blob/master/online/mvtx2019_pmon/mvtxOM.h File Reference
mvtxOM.h File Reference
#include <pmonitor/pmonitor.h>
#include <Event/Event.h>
#include <Event/EventTypes.h>
Functions
int process_event (Event *e)
int process_histos (float thresh=10)
int mask_pixels (float thresh=5)
int analysis ()
int OM ()
int print_canvas ()
int print_status ()
void reset_histos ()
void set_verbose (int v)
void set_refresh (int r)
void get_alignment ()
Function Documentation
int analysis ()
Definition at line 620 of file mvtxOM.cc.
View newest version in sPHENIX GitHub at line 620 of file mvtxOM.cc
References cBeamCenter, dead_chip_backward, dead_chip_forward, fg, gmpos_chip, h, h2d_chip, h2d_chip_norm, hchip, hdiffcol_chip, hdiffcol_chip_norm, hdiffrow_chip, hdiffrow_chip_norm, herr, herrrate_chip, hhitrate_chip, hnevnt, hnhit_chip, hnhit_chip_norm, hwarn, hwarnrate_chip, add_histos_bX::ib, Acts::UnitConstants::m, perf_headwind::name, nevents(), NSTAVE, ProjectionY, physmon_simulation::s, show_beam_fit, and stave_name.
Referenced by Fun4All_Analysis(), OM(), and print_status().
void get_alignment ()
Definition at line 1225 of file mvtxOM.cc.
View newest version in sPHENIX GitHub at line 1225 of file mvtxOM.cc
References INTTVtxZ::fname, fout, gmpos_chip, mvtx_run, and NSTAVE.
Referenced by mvtxBeamTestRunScan().
int mask_pixels (float thresh = 5)
Definition at line 563 of file mvtxOM.cc.
View newest version in sPHENIX GitHub at line 563 of file mvtxOM.cc
References col, flip_yaxis, h2d_chip, i, NSTAVE, printf(), and sum().
int OM ()
Definition at line 881 of file mvtxOM.cc.
View newest version in sPHENIX GitHub at line 881 of file mvtxOM.cc
References analysis(), chip_edges, chipColor, com, dead_chip_backward, dead_chip_forward, Acts::UnitConstants::e, flip_yaxis, h2d_chip_norm, haxis_chip, haxis_diff, haxis_nhit, hdiffcol_chip_norm, hdiffrow_chip_norm, herrrate_chip, hhitrate_chip, hnevnt, hnhit_chip_norm, hwarnrate_chip, i, j, ldiffcol, ldiffrow, lnevents, lnhitmean, Modified(), mvtx_run, perf_headwind::name, NSTAVE, p2d, pdiffcol, pdiffrow, phitrate, reversedaxis, and stave_name.
Referenced by ActsAlignmentStates::fillAlignmentStateMap(), HelicalFitter::getGlobalDerivativesXY(), mvtxBeamTestRunScan(), open_file(), process_event(), and run_om().
int print_canvas ()
Definition at line 1143 of file mvtxOM.cc.
View newest version in sPHENIX GitHub at line 1143 of file mvtxOM.cc
References cBeamCenter, com, mvtx_run, and show_beam_fit.
Referenced by mvtxBeamTestRunScan().
int print_status ()
Definition at line 1155 of file mvtxOM.cc.
View newest version in sPHENIX GitHub at line 1155 of file mvtxOM.cc
References analysis(), gmpos_chip, hchip, hdiffcol_chip_norm, hdiffrow_chip_norm, herr, herrrate_chip, hhitrate_chip, hnevnt, hnhit_chip, hnhit_chip_norm, hwarn, hwarnrate_chip, i, and NSTAVE.
int process_event (Event * e)
Definition at line 141 of file MyFavoriteMartin.C.
View newest version in sPHENIX GitHub at line 141 of file MyFavoriteMartin.C
References OnlMonServer::AddBadEvent(), prdfoStream::addEvent(), Quiver::AnalyzeScope, Quiver::AnalyzeSRS, AZigzag::ApplyCalibration(), OnlMonServer::BadEvents(), OnlMonServer::BeginRun(), BEGRUNEVENT, OnlMonServer::BorTicks(), BORTIMEBIN, CHhybrid, chipmap, groot::ClearTheDetector(), OnlMonServer::CurrentTicks(), CURRENTTIMEBIN, DATAEVENT, decode_col(), decode_row(), AZigzag::DetermineCommonMode(), double(), Acts::UnitConstants::e, EARLYEVENTNUMBIN, EARLYEVENTTIMEBIN, OnlMonServer::EndRun(), EORTIMEBIN, groot::event, OnlMonServer::EventNumber(), fg, FillBlobHist(), FindBlobs(), first_event_nr, flip_yaxis, FrameWorkVars, Event::getErrorCode(), Event::getEvtLength(), Event::getEvtSequence(), Event::getEvtType(), Event::getPacket(), Event::getRunNumber(), Event::getTime(), h1a, h1a_D, h1b, h1b_D, h1c, h1c_D, h1d, h1d_D, h2a, h2a_D, h2b, h2b_D, h2c, h2c_D, h2d, h2d_chip, h2d_D, h3a, h3a_D, h3b, h3b_D, h3c, h3c_D, h3d, h3d_D, h4a, h4a_D, h4b, h4b_D, h4c, h4c_D, h4d, h4d_D, hchip, hdiffcol_chip, hdiffrow_chip, hhittime_chip, hnevnt, i, IDMVTXV1_MAXRUCHN, IDMVTXV1_MAXRUID, OnlMonServer::instance(), groot::instance(), Packet::iValue(), j, max_npixels, Acts::UnitConstants::min, TauVsDIS_MachineLearning_Differentiation::msg, MSG_SEV_WARNING, mvtx_evnts, mvtx_run, mvtx_verbose, Nhybrid, NSTAVE, OM(), merge_hashes::p, OnlMonServer::process_event(), AZigzag::Raw, OnlMonServer::Reset(), reset_histos(), Quiver::RunNumber, OnlMonServer::RunNumber(), RUNNUMBERBIN, Packet::rValue(), scope0, scope1, scope2, scope3, send_message(), groot::theTraces, groot::theTracks, groot::theZigzags, Acts::Test::time, write_outHitLocations(), and OnlMonServer::WriteHistoFile().
Referenced by pprocess(), and prun().
int process_histos (float thresh = 10)
Definition at line 524 of file mvtxOM.cc.
View newest version in sPHENIX GitHub at line 524 of file mvtxOM.cc
References col, flip_yaxis, h2d_chip, i, NSTAVE, and sum().
void reset_histos ()
Definition at line 1208 of file mvtxOM.cc.
View newest version in sPHENIX GitHub at line 1208 of file mvtxOM.cc
References h2d_chip, hchip, hdiffcol_chip, hdiffrow_chip, herr, hnevnt, hnhit_chip, hwarn, i, and NSTAVE.
Referenced by process_event().
void set_refresh (int r)
Definition at line 154 of file mvtxOM.cc.
View newest version in sPHENIX GitHub at line 154 of file mvtxOM.cc
References mvtx_refresh, and physmon_track_finding_ttbar::r.
Referenced by run_om().
void set_verbose (int v)
Definition at line 147 of file mvtxOM.cc.
View newest version in sPHENIX GitHub at line 147 of file mvtxOM.cc
References mvtx_verbose, and testSigmaEff::v.