Analysis Software: ActsExamples::ParametricParticleGenerator Class Reference
ActsExamples::ParametricParticleGenerator Class Reference
#include <acts/blob/sPHENIX/Examples/Algorithms/Generators/ActsExamples/Generators/ParametricParticleGenerator.hpp>
Classes
struct Config
Public Member Functions
ParametricParticleGenerator (const Config &cfg)
SimParticleContainer operator() (RandomEngine &rng) override
Generate a single primary vertex with the given number of particles.
Public Member Functions inherited from ActsExamples::EventGenerator::ParticlesGenerator
virtual ~ParticlesGenerator ()=default
Virtual destructor required.
Private Attributes
Config m_cfg
double m_charge
double m_mass
double m_cosThetaMin
double m_cosThetaMax
double m_etaMin
double m_etaMax
Detailed Description
Generate particles from uniform parameter distributions.
Generates a single vertex with the given number of tracks. The track direction is drawn from a uniform distribution on the unit sphere (within the given limits). Its absolute momentum is drawn from a uniform distribution. Position and time are always set to zero.
Definition at line 31 of file ParametricParticleGenerator.hpp.
View newest version in sPHENIX GitHub at line 31 of file ParametricParticleGenerator.hpp
Constructor & Destructor Documentation
ActsExamples::ParametricParticleGenerator::ParametricParticleGenerator (const Config & cfg)
Definition at line 21 of file ParametricParticleGenerator.cpp.
View newest version in sPHENIX GitHub at line 21 of file ParametricParticleGenerator.cpp
Member Function Documentation
ActsExamples::SimParticleContainer ActsExamples::ParametricParticleGenerator::operator() (RandomEngine & rng) override virtual
Generate a single primary vertex with the given number of particles.
Implements ActsExamples::EventGenerator::ParticlesGenerator.
Definition at line 39 of file ParametricParticleGenerator.cpp.
View newest version in sPHENIX GitHub at line 39 of file ParametricParticleGenerator.cpp
References Acts::eMom0, Acts::eMom1, Acts::eMom2, eta, Acts::Test::etaDist(), m_cfg(), testing::internal::move(), merge_hashes::p, particle, particles, pdg, ActsTests::PropagationDatasets::phi, Acts::Test::phiDist(), train_ambiguity_solver::pid, ActsFatras::Particle::setAbsoluteMomentum(), ActsFatras::Particle::setDirection(), ActsFatras::Barcode::setParticle(), ActsTests::PropagationDatasets::theta, parse_cmake_options::type, and physmon_ckf_tracking::u.
Member Data Documentation
Config ActsExamples::ParametricParticleGenerator::m_cfg private
Definition at line 73 of file ParametricParticleGenerator.hpp.
View newest version in sPHENIX GitHub at line 73 of file ParametricParticleGenerator.hpp
double ActsExamples::ParametricParticleGenerator::m_charge private
Definition at line 75 of file ParametricParticleGenerator.hpp.
View newest version in sPHENIX GitHub at line 75 of file ParametricParticleGenerator.hpp
double ActsExamples::ParametricParticleGenerator::m_cosThetaMax private
Definition at line 78 of file ParametricParticleGenerator.hpp.
View newest version in sPHENIX GitHub at line 78 of file ParametricParticleGenerator.hpp
double ActsExamples::ParametricParticleGenerator::m_cosThetaMin private
Definition at line 77 of file ParametricParticleGenerator.hpp.
View newest version in sPHENIX GitHub at line 77 of file ParametricParticleGenerator.hpp
double ActsExamples::ParametricParticleGenerator::m_etaMax private
Definition at line 80 of file ParametricParticleGenerator.hpp.
View newest version in sPHENIX GitHub at line 80 of file ParametricParticleGenerator.hpp
double ActsExamples::ParametricParticleGenerator::m_etaMin private
Definition at line 79 of file ParametricParticleGenerator.hpp.
View newest version in sPHENIX GitHub at line 79 of file ParametricParticleGenerator.hpp
double ActsExamples::ParametricParticleGenerator::m_mass private
Definition at line 76 of file ParametricParticleGenerator.hpp.
View newest version in sPHENIX GitHub at line 76 of file ParametricParticleGenerator.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Generators/ActsExamples/Generators/ParametricParticleGenerator.hpp
acts/blob/sPHENIX/Examples/Algorithms/Generators/ActsExamples/Generators/ParametricParticleGenerator.cpp