Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Plugins/ActSVG/PortalSvgConverterTests.cpp File Reference
PortalSvgConverterTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Detector/DetectorVolume.hpp"
#include "Acts/Detector/PortalGenerators.hpp"
#include "Acts/Detector/detail/CylindricalDetectorHelper.hpp"
#include "Acts/Geometry/CylinderVolumeBounds.hpp"
#include "Acts/Navigation/SurfaceCandidatesUpdators.hpp"
#include "Acts/Plugins/ActSVG/PortalSvgConverter.hpp"
#include "Acts/Plugins/ActSVG/SvgUtils.hpp"
#include "Acts/Utilities/Enumerate.hpp"
#include <fstream>
#include <memory>
#include <vector>
Functions
BOOST_AUTO_TEST_CASE (CylinderPortalsSvg)
BOOST_AUTO_TEST_CASE (CylinderContainerPortalsSvg)
Variables
Acts::GeometryContext tContext
Function Documentation
BOOST_AUTO_TEST_CASE (CylinderPortalsSvg)
Definition at line 29 of file PortalSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file PortalSvgConverterTests.cpp
References Acts::Experimental::DetectorVolumeFactory::construct(), Acts::Svg::PortalConverter::convert(), Acts::Experimental::defaultPortalGenerator(), Acts::Svg::Style::fillColor, Acts::Svg::Style::fillOpacity, Acts::Svg::Style::highlightColor, Acts::Svg::Style::highlights, testing::internal::move(), nominal, Acts::Svg::Style::nSegments, merge_hashes::p, portalGenerator, Acts::Svg::Style::strokeColor, Acts::Svg::Style::strokeWidth, Acts::Svg::SurfaceConverter::Options::style, Acts::Svg::PortalConverter::Options::surfaceOptions, to_string(), Acts::Svg::toFile(), Acts::Experimental::tryAllPortals(), physmon_ckf_tracking::u, Acts::Svg::PortalConverter::Options::volumeIndices, Acts::Svg::View::xy(), zHalfL, and Acts::Svg::View::zr().
BOOST_AUTO_TEST_CASE (CylinderContainerPortalsSvg)
Definition at line 88 of file PortalSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 88 of file PortalSvgConverterTests.cpp
References Acts::Experimental::detail::CylindricalDetectorHelper::connectInR(), Acts::Experimental::DetectorVolumeFactory::construct(), Acts::Svg::PortalConverter::convert(), Acts::Experimental::defaultPortalGenerator(), Acts::Svg::Style::fillColor, Acts::Svg::Style::fillOpacity, Acts::Svg::Style::highlightColor, Acts::Svg::Style::highlights, testing::internal::move(), nominal, Acts::Svg::Style::nSegments, merge_hashes::p, portalGenerator, Acts::Svg::Style::strokeColor, Acts::Svg::Style::strokeWidth, Acts::Svg::SurfaceConverter::Options::style, Acts::Svg::PortalConverter::Options::surfaceOptions, to_string(), Acts::Svg::toFile(), Acts::Experimental::tryAllPortals(), physmon_ckf_tracking::u, testSigmaEff::v, Acts::Svg::PortalConverter::Options::volumeIndices, zHalfL, and Acts::Svg::View::zr().
Variable Documentation
Acts::GeometryContext tContext
Definition at line 25 of file PortalSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file PortalSvgConverterTests.cpp