Analysis Software: Jetv1 Class Reference
Jetv1 Class Reference
Jetv1.
#include <coresoftware/blob/master/offline/packages/jetbase/Jetv1.h>
Public Member Functions
Jetv1 ()
~Jetv1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
unsigned int get_id () const override
void set_id (unsigned int id) override
float get_px () const override
void set_px (float px) override
float get_py () const override
void set_py (float py) override
float get_pz () const override
void set_pz (float pz) override
float get_e () const override
void set_e (float e) override
float get_p () const override
float get_pt () const override
float get_et () const override
float get_eta () const override
float get_phi () const override
float get_mass () const override
float get_mass2 () const override
bool has_property (Jet::PROPERTY prop_id) const override
float get_property (Jet::PROPERTY prop_id) const override
void set_property (Jet::PROPERTY prop_id, float value) override
void print_property (std::ostream &os) const override
bool empty_comp () const override
size_t size_comp () const override
void clear_comp () override
size_t erase_comp (SRC source) override
void erase_comp (Iter iter) override
void erase_comp (Iter first, Iter last) override
ConstIter begin_comp () const override
ConstIter lower_bound_comp (SRC source) const override
ConstIter upper_bound_comp (SRC source) const override
ConstIter find (SRC source) const override
ConstIter end_comp () const override
Iter begin_comp () override
Iter lower_bound_comp (SRC source) override
Iter upper_bound_comp (SRC source) override
Iter find (SRC source) override
Iter end_comp () override
Public Member Functions inherited from Jet
Jet ()
~Jet () override
ClassDefOverride (Jet, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Types
typedef std::map
< Jet::PROPERTY, float > typ_property_map
Private Member Functions
void not_in_v1_msg (const std::string &method_name, std::ostream &os=std::cout) const
size_t size_properties () const override
virtual std::vector< float > & get_property_vec () override
void insert_comp (SRC source, unsigned int compid) override
void insert_comp (SRC source, unsigned int compid, bool) override
void insert_comp (TYPE_comp_vec &) override
void insert_comp (TYPE_comp_vec &, bool) override
void set_comp_sort_flag (bool) override
size_t num_comp (Jet::SRC) override
void print_comp (std::ostream &, bool) override
std::vector< Jet::SRC > comp_src_vec () override
std::map< Jet::SRC, size_t > comp_src_sizemap () override
size_t count_comp (SRC source) const override
ITER_comp_vec comp_begin (Jet::SRC) override
ITER_comp_vec comp_end (Jet::SRC) override
ITER_comp_vec comp_begin () override
ITER_comp_vec comp_end () override
TYPE_comp_vec & get_comp_vec () override
void resize_properties (size_t) override
ClassDefOverride (Jetv1, 1)
Private Attributes
unsigned int _id = ~0x0
unique identifier within container
float _mom [3]
jet momentum vector (px,py,pz)
float _e = NAN
jet energy
typ_comp_ids _comp_ids
source id -> component id
typ_property_map _property_map
map that contains extra properties
Additional Inherited Members
Public Types inherited from Jet
enum ALGO { NONE = 0, ANTIKT = 1, KT = 2, CAMBRIDGE = 3 }
enum SRC {
VOID = 0, PARTICLE = 1, TRACK = 2, CEMC_TOWER = 3,
CEMC_CLUSTER = 4, HCALIN_TOWER = 5, HCALIN_CLUSTER = 6, HCALOUT_TOWER = 7,
HCALOUT_CLUSTER = 8, FEMC_TOWER = 9, FEMC_CLUSTER = 10, FHCAL_TOWER = 11,
FHCAL_CLUSTER = 12, CEMC_TOWER_RETOWER = 13, CEMC_TOWER_SUB1 = 14, HCALIN_TOWER_SUB1 = 15,
HCALOUT_TOWER_SUB1 = 16, CEMC_TOWER_SUB1CS = 17, HCALIN_TOWER_SUB1CS = 18, HCALOUT_TOWER_SUB1CS = 19,
HEPMC_IMPORT = 20, HCAL_TOPO_CLUSTER = 21, ECAL_TOPO_CLUSTER = 22, EEMC_TOWER = 23,
EEMC_CLUSTER = 24, CEMC_TOWERINFO = 25, HCALIN_TOWERINFO = 26, HCALOUT_TOWERINFO = 27,
CEMC_TOWERINFO_RETOWER = 28, CEMC_TOWERINFO_SUB1 = 29, HCALIN_TOWERINFO_SUB1 = 30, HCALOUT_TOWERINFO_SUB1 = 31,
CEMC_TOWERINFO_EMBED = 32, CEMC_TOWERINFO_SIM = 33, HCALIN_TOWERINFO_EMBED = 34, HCALIN_TOWERINFO_SIM = 35,
HCALOUT_TOWERINFO_EMBED = 36, HCALOUT_TOWERINFO_SIM = 37, JET_PROBE = 38
}
enum PROPERTY {
prop_JetCharge = 1, prop_BFrac = 2, prop_SeedD = 3, prop_SeedItr = 4,
prop_zg = 5, prop_Rg = 6, prop_mu = 7, prop_gamma = 8,
prop_JetHadronFlavor = 9, prop_JetHadronZT = 10, prop_area = 11, no_property = 12
}
typedef std::pair< Jet::SRC,
unsigned int > TYPE_comp
typedef std::vector< TYPE_comp > TYPE_comp_vec
typedef TYPE_comp_vec::iterator ITER_comp_vec
typedef std::multimap
< Jet::SRC, unsigned int > typ_comp_ids
typedef
typ_comp_ids::const_iterator ConstIter
typedef typ_comp_ids::iterator Iter
Detailed Description
Jetv1.
Definition at line 25 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 25 of file Jetv1.h
Member Typedef Documentation
typedef std::map<Jet::PROPERTY, float> Jetv1::typ_property_map private
Definition at line 115 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 115 of file Jetv1.h
Constructor & Destructor Documentation
Jetv1::Jetv1 ()
Definition at line 18 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 18 of file Jetv1.cc
References _mom, parse_cmake_options::begin, and end.
Referenced by CloneMe().
Jetv1::~Jetv1 () inline override
Definition at line 29 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 29 of file Jetv1.h
Member Function Documentation
ConstIter Jetv1::begin_comp () const inline override virtual
Reimplemented from Jet.
Definition at line 90 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 90 of file Jetv1.h
References _comp_ids.
Referenced by identify().
Iter Jetv1::begin_comp () inline override virtual
Reimplemented from Jet.
Definition at line 96 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 96 of file Jetv1.h
References _comp_ids.
Jetv1::ClassDefOverride (Jetv1 , 1) private
void Jetv1::clear_comp () inline override virtual
Reimplemented from Jet.
Definition at line 77 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 77 of file Jetv1.h
References _comp_ids.
PHObject * Jetv1::CloneMe () const override virtual
Virtual copy constructor.
Reimplemented from Jet.
Definition at line 60 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 60 of file Jetv1.cc
References Jetv1().
Jet::ITER_comp_vec Jetv1::comp_begin (Jet::SRC) override private virtual
Reimplemented from Jet.
Definition at line 221 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 221 of file Jetv1.cc
References Jet::comp_begin(), and not_in_v1_msg().
Jet::ITER_comp_vec Jetv1::comp_begin () override private virtual
Reimplemented from Jet.
Definition at line 233 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 233 of file Jetv1.cc
References Jet::comp_begin(), and not_in_v1_msg().
Jet::ITER_comp_vec Jetv1::comp_end (Jet::SRC) override private virtual
Reimplemented from Jet.
Definition at line 227 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 227 of file Jetv1.cc
References Jet::comp_end(), and not_in_v1_msg().
Jet::ITER_comp_vec Jetv1::comp_end () override private virtual
Reimplemented from Jet.
Definition at line 238 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 238 of file Jetv1.cc
References Jet::comp_end(), and not_in_v1_msg().
std::map< Jet::SRC, size_t > Jetv1::comp_src_sizemap () override private virtual
Reimplemented from Jet.
Definition at line 215 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 215 of file Jetv1.cc
References not_in_v1_msg().
std::vector< Jet::SRC > Jetv1::comp_src_vec () override private virtual
Reimplemented from Jet.
Definition at line 209 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 209 of file Jetv1.cc
References not_in_v1_msg().
size_t Jetv1::count_comp (SRC source) const inline override private virtual
Reimplemented from Jet.
Definition at line 137 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 137 of file Jetv1.h
References _comp_ids.
bool Jetv1::empty_comp () const inline override virtual
Reimplemented from Jet.
Definition at line 74 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 74 of file Jetv1.h
References _comp_ids.
ConstIter Jetv1::end_comp () const inline override virtual
Reimplemented from Jet.
Definition at line 94 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 94 of file Jetv1.h
References _comp_ids.
Referenced by identify().
Iter Jetv1::end_comp () inline override virtual
Reimplemented from Jet.
Definition at line 100 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 100 of file Jetv1.h
References _comp_ids.
size_t Jetv1::erase_comp (SRC source) inline override virtual
Reimplemented from Jet.
Definition at line 78 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 78 of file Jetv1.h
References _comp_ids.
void Jetv1::erase_comp (Iter iter) inline override virtual
Reimplemented from Jet.
Definition at line 79 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 79 of file Jetv1.h
References _comp_ids.
void Jetv1::erase_comp (Iter first, Iter last) inline override virtual
Reimplemented from Jet.
Definition at line 84 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 84 of file Jetv1.h
References _comp_ids.
ConstIter Jetv1::find (SRC source) const inline override virtual
Reimplemented from Jet.
Definition at line 93 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 93 of file Jetv1.h
References _comp_ids.
Iter Jetv1::find (SRC source) inline override virtual
Reimplemented from Jet.
Definition at line 99 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 99 of file Jetv1.h
References _comp_ids.
Jet::TYPE_comp_vec & Jetv1::get_comp_vec () override private virtual
Reimplemented from Jet.
Definition at line 243 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 243 of file Jetv1.cc
References Jet::get_comp_vec(), and not_in_v1_msg().
float Jetv1::get_e () const inline override virtual
Reimplemented from Jet.
Definition at line 52 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 52 of file Jetv1.h
References _e.
Referenced by get_et(), get_mass2(), and identify().
float Jetv1::get_et () const override virtual
Reimplemented from Jet.
Definition at line 76 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 76 of file Jetv1.cc
References get_e(), get_p(), and get_pt().
float Jetv1::get_eta () const override virtual
Reimplemented from Jet.
Definition at line 81 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 81 of file Jetv1.cc
References get_pt(), and get_pz().
unsigned int Jetv1::get_id () const inline override virtual
Reimplemented from Jet.
Definition at line 40 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 40 of file Jetv1.h
References _id.
Referenced by identify().
float Jetv1::get_mass () const override virtual
Reimplemented from Jet.
Definition at line 91 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 91 of file Jetv1.cc
References get_mass2().
float Jetv1::get_mass2 () const override virtual
Reimplemented from Jet.
Definition at line 102 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 102 of file Jetv1.cc
References get_e(), get_px(), get_py(), and get_pz().
Referenced by get_mass().
float Jetv1::get_p () const override virtual
Reimplemented from Jet.
Definition at line 66 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 66 of file Jetv1.cc
References get_px(), get_py(), and get_pz().
Referenced by get_et().
float Jetv1::get_phi () const override virtual
Reimplemented from Jet.
Definition at line 86 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 86 of file Jetv1.cc
References get_px(), and get_py().
float Jetv1::get_property (Jet::PROPERTY prop_id) const override virtual
Reimplemented from Jet.
Definition at line 118 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 118 of file Jetv1.cc
References _property_map.
std::vector< float > & Jetv1::get_property_vec () override private virtual
Reimplemented from Jet.
Definition at line 160 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 160 of file Jetv1.cc
References DummyJetPropVecv1, and not_in_v1_msg().
float Jetv1::get_pt () const override virtual
Reimplemented from Jet.
Definition at line 71 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 71 of file Jetv1.cc
References get_px(), and get_py().
Referenced by get_et(), and get_eta().
float Jetv1::get_px () const inline override virtual
Reimplemented from Jet.
Definition at line 43 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 43 of file Jetv1.h
References _mom.
Referenced by get_mass2(), get_p(), get_phi(), get_pt(), and identify().
float Jetv1::get_py () const inline override virtual
Reimplemented from Jet.
Definition at line 46 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 46 of file Jetv1.h
References _mom.
Referenced by get_mass2(), get_p(), get_phi(), get_pt(), and identify().
float Jetv1::get_pz () const inline override virtual
Reimplemented from Jet.
Definition at line 49 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 49 of file Jetv1.h
References _mom.
Referenced by get_eta(), get_mass2(), get_p(), and identify().
bool Jetv1::has_property (Jet::PROPERTY prop_id) const override virtual
Reimplemented from Jet.
Definition at line 108 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 108 of file Jetv1.cc
References _property_map.
void Jetv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from Jet.
Definition at line 23 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 23 of file Jetv1.cc
References begin_comp(), end_comp(), get_e(), get_id(), get_px(), get_py(), get_pz(), and print_property().
void Jetv1::insert_comp (SRC source, unsigned int compid) inline override private virtual
Reimplemented from Jet.
Definition at line 126 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 126 of file Jetv1.h
References _comp_ids.
void Jetv1::insert_comp (Jet::SRC source, unsigned int compid, bool) override private virtual
Reimplemented from Jet.
Definition at line 178 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 178 of file Jetv1.cc
References not_in_v1_msg().
void Jetv1::insert_comp (Jet::TYPE_comp_vec &) override private virtual
Reimplemented from Jet.
Definition at line 183 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 183 of file Jetv1.cc
References not_in_v1_msg().
void Jetv1::insert_comp (Jet::TYPE_comp_vec & , bool) override private virtual
Reimplemented from Jet.
Definition at line 188 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 188 of file Jetv1.cc
References not_in_v1_msg().
int Jetv1::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from Jet.
Definition at line 48 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 48 of file Jetv1.cc
References _comp_ids, _e, _id, _mom, and i.
ConstIter Jetv1::lower_bound_comp (SRC source) const inline override virtual
Reimplemented from Jet.
Definition at line 91 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 91 of file Jetv1.h
References _comp_ids.
Iter Jetv1::lower_bound_comp (SRC source) inline override virtual
Reimplemented from Jet.
Definition at line 97 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 97 of file Jetv1.h
References _comp_ids.
void Jetv1::not_in_v1_msg (const std::string & method_name, std::ostream & os = std::cout) const private
Definition at line 156 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 156 of file Jetv1.cc
Referenced by comp_begin(), comp_end(), comp_src_sizemap(), comp_src_vec(), get_comp_vec(), get_property_vec(), insert_comp(), num_comp(), print_comp(), resize_properties(), and set_comp_sort_flag().
size_t Jetv1::num_comp (Jet::SRC) override private virtual
Reimplemented from Jet.
Definition at line 198 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 198 of file Jetv1.cc
References not_in_v1_msg().
void Jetv1::print_comp (std::ostream & , bool) override private virtual
Reimplemented from Jet.
Definition at line 204 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 204 of file Jetv1.cc
References not_in_v1_msg().
void Jetv1::print_property (std::ostream & os) const override virtual
Reimplemented from Jet.
Definition at line 133 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 133 of file Jetv1.cc
References _property_map, Jet::prop_BFrac, and Jet::prop_JetCharge.
Referenced by identify().
void Jetv1::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 39 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 39 of file Jetv1.cc
References _comp_ids, _e, _id, _mom, _property_map, parse_cmake_options::begin, and end.
void Jetv1::resize_properties (size_t) override private virtual
Reimplemented from Jet.
Definition at line 248 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 248 of file Jetv1.cc
References not_in_v1_msg().
void Jetv1::set_comp_sort_flag (bool) override private virtual
Reimplemented from Jet.
Definition at line 193 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 193 of file Jetv1.cc
References not_in_v1_msg().
void Jetv1::set_e (float e) inline override virtual
Reimplemented from Jet.
Definition at line 53 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 53 of file Jetv1.h
References _e, and Acts::UnitConstants::e.
void Jetv1::set_id (unsigned int id) inline override virtual
Reimplemented from Jet.
Definition at line 41 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 41 of file Jetv1.h
References _id, and train_ambiguity_solver::id.
void Jetv1::set_property (Jet::PROPERTY prop_id, float value) override virtual
Reimplemented from Jet.
Definition at line 128 of file Jetv1.cc.
View newest version in sPHENIX GitHub at line 128 of file Jetv1.cc
References _property_map, and value.
void Jetv1::set_px (float px) inline override virtual
Reimplemented from Jet.
Definition at line 44 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 44 of file Jetv1.h
References _mom.
void Jetv1::set_py (float py) inline override virtual
Reimplemented from Jet.
Definition at line 47 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 47 of file Jetv1.h
References _mom.
void Jetv1::set_pz (float pz) inline override virtual
Reimplemented from Jet.
Definition at line 50 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 50 of file Jetv1.h
References _mom.
size_t Jetv1::size_comp () const inline override virtual
Reimplemented from Jet.
Definition at line 75 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 75 of file Jetv1.h
References _comp_ids.
size_t Jetv1::size_properties () const inline override private virtual
Reimplemented from Jet.
Definition at line 122 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 122 of file Jetv1.h
References _property_map.
ConstIter Jetv1::upper_bound_comp (SRC source) const inline override virtual
Reimplemented from Jet.
Definition at line 92 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 92 of file Jetv1.h
References _comp_ids.
Iter Jetv1::upper_bound_comp (SRC source) inline override virtual
Reimplemented from Jet.
Definition at line 98 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 98 of file Jetv1.h
References _comp_ids.
Member Data Documentation
typ_comp_ids Jetv1::_comp_ids private
source id -> component id
Definition at line 113 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 113 of file Jetv1.h
Referenced by begin_comp(), clear_comp(), count_comp(), empty_comp(), end_comp(), erase_comp(), find(), insert_comp(), isValid(), lower_bound_comp(), Reset(), size_comp(), and upper_bound_comp().
float Jetv1::_e = NAN private
jet energy
Definition at line 110 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 110 of file Jetv1.h
Referenced by get_e(), isValid(), Reset(), and set_e().
unsigned int Jetv1::_id = ~0x0 private
unique identifier within container
Definition at line 104 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 104 of file Jetv1.h
Referenced by get_id(), isValid(), Reset(), and set_id().
float Jetv1::_mom[3] private
jet momentum vector (px,py,pz)
Definition at line 107 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 107 of file Jetv1.h
Referenced by get_px(), get_py(), get_pz(), isValid(), Jetv1(), Reset(), set_px(), set_py(), and set_pz().
typ_property_map Jetv1::_property_map private
map that contains extra properties
Definition at line 117 of file Jetv1.h.
View newest version in sPHENIX GitHub at line 117 of file Jetv1.h
Referenced by get_property(), has_property(), print_property(), Reset(), set_property(), and size_properties().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/jetbase/Jetv1.h
coresoftware/blob/master/offline/packages/jetbase/Jetv1.cc