Analysis Software: HelixHoughFuncs_v1 Class Reference
HelixHoughFuncs_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/HelixHoughFuncs_v1.h>
Public Member Functions
HelixHoughFuncs_v1 ()
HelixHoughFuncs_v1 (const HelixHoughFuncs_v1 &hough_funcs)
~HelixHoughFuncs_v1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void set_current_zoom (unsigned int cur_zoom) override
void set_hough_space (HelixHoughSpace *hough_space) override
void calculate_dzdl_range (float *hitpos3d, std::vector< float > &z0_range, std::vector< float > &kappa_phi_d_ranges, float *dzdl_range) override
void calculate_phi_range (float *hitpos2d, std::vector< float > &kappa_d_ranges, float *phi_r_range, float *phi_l_range) override
void calculate_phi_range (float *hitpos2d, std::vector< float > &kappa_d_ranges, int helicity, float *phi_range, float *phi_next_range) override
void calculate_phi_range (float *hitpos2d, std::vector< float > &kappa_d_ranges, int helicity, float *phi_range, float *phi_prev_range, float *phi_next_range) override
Public Member Functions inherited from HelixHoughFuncs
~HelixHoughFuncs () override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
HelixHoughSpace * _hough_space
unsigned int _cur_zoom
Additional Inherited Members
Protected Member Functions inherited from HelixHoughFuncs
HelixHoughFuncs ()
ClassDefOverride (HelixHoughFuncs, 1)
Detailed Description
Definition at line 12 of file HelixHoughFuncs_v1.h.
View newest version in sPHENIX GitHub at line 12 of file HelixHoughFuncs_v1.h
Constructor & Destructor Documentation
HelixHoughFuncs_v1::HelixHoughFuncs_v1 ()
Definition at line 8 of file HelixHoughFuncs_v1.cc.
View newest version in sPHENIX GitHub at line 8 of file HelixHoughFuncs_v1.cc
Referenced by CloneMe().
HelixHoughFuncs_v1::HelixHoughFuncs_v1 (const HelixHoughFuncs_v1 & hough_funcs)
Definition at line 14 of file HelixHoughFuncs_v1.cc.
View newest version in sPHENIX GitHub at line 14 of file HelixHoughFuncs_v1.cc
HelixHoughFuncs_v1::~HelixHoughFuncs_v1 () inline override
Definition at line 17 of file HelixHoughFuncs_v1.h.
View newest version in sPHENIX GitHub at line 17 of file HelixHoughFuncs_v1.h
Member Function Documentation
void HelixHoughFuncs_v1::calculate_dzdl_range (float * hitpos3d, std::vector< float > & z0_range, std::vector< float > & kappa_phi_d_ranges, float * dzdl_range) override virtual
Reimplemented from HelixHoughFuncs.
Definition at line 25 of file HelixHoughFuncs_v1.cc.
View newest version in sPHENIX GitHub at line 25 of file HelixHoughFuncs_v1.cc
References KFPMath::a, KFPMath::a2, d, dx, dy, dzdl, i, j, k, M_PI, Acts::UnitConstants::s, x, y, and z.
void HelixHoughFuncs_v1::calculate_phi_range (float * hitpos2d, std::vector< float > & kappa_d_ranges, float * phi_r_range, float * phi_l_range) override virtual
Reimplemented from HelixHoughFuncs.
Definition at line 136 of file HelixHoughFuncs_v1.cc.
View newest version in sPHENIX GitHub at line 136 of file HelixHoughFuncs_v1.cc
References d, fourth, i, k, M_PI, phi, twopi, x, and y.
void HelixHoughFuncs_v1::calculate_phi_range (float * hitpos2d, std::vector< float > & kappa_d_ranges, int helicity, float * phi_range, float * phi_next_range) override virtual
Reimplemented from HelixHoughFuncs.
Definition at line 291 of file HelixHoughFuncs_v1.cc.
View newest version in sPHENIX GitHub at line 291 of file HelixHoughFuncs_v1.cc
References Acts::VectorHelpers::cross(), d, fourth, i, k, M_PI, phi, twopi, x, and y.
void HelixHoughFuncs_v1::calculate_phi_range (float * hitpos2d, std::vector< float > & kappa_d_ranges, int helicity, float * phi_range, float * phi_prev_range, float * phi_next_range) override virtual
Reimplemented from HelixHoughFuncs.
Definition at line 416 of file HelixHoughFuncs_v1.cc.
View newest version in sPHENIX GitHub at line 416 of file HelixHoughFuncs_v1.cc
References Acts::VectorHelpers::cross(), d, fourth, i, k, M_PI, phi, twopi, x, and y.
PHObject* HelixHoughFuncs_v1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from HelixHoughFuncs.
Definition at line 23 of file HelixHoughFuncs_v1.h.
View newest version in sPHENIX GitHub at line 23 of file HelixHoughFuncs_v1.h
References HelixHoughFuncs_v1().
void HelixHoughFuncs_v1::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from HelixHoughFuncs.
Definition at line 20 of file HelixHoughFuncs_v1.h.
View newest version in sPHENIX GitHub at line 20 of file HelixHoughFuncs_v1.h
int HelixHoughFuncs_v1::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from HelixHoughFuncs.
Definition at line 22 of file HelixHoughFuncs_v1.h.
View newest version in sPHENIX GitHub at line 22 of file HelixHoughFuncs_v1.h
void HelixHoughFuncs_v1::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 21 of file HelixHoughFuncs_v1.h.
View newest version in sPHENIX GitHub at line 21 of file HelixHoughFuncs_v1.h
void HelixHoughFuncs_v1::set_current_zoom (unsigned int cur_zoom) inline override virtual
Reimplemented from HelixHoughFuncs.
Definition at line 25 of file HelixHoughFuncs_v1.h.
View newest version in sPHENIX GitHub at line 25 of file HelixHoughFuncs_v1.h
References _cur_zoom.
void HelixHoughFuncs_v1::set_hough_space (HelixHoughSpace * hough_space) override virtual
Reimplemented from HelixHoughFuncs.
Definition at line 19 of file HelixHoughFuncs_v1.cc.
View newest version in sPHENIX GitHub at line 19 of file HelixHoughFuncs_v1.cc
References _hough_space.
Member Data Documentation
unsigned int HelixHoughFuncs_v1::_cur_zoom private
Definition at line 46 of file HelixHoughFuncs_v1.h.
View newest version in sPHENIX GitHub at line 46 of file HelixHoughFuncs_v1.h
Referenced by set_current_zoom().
HelixHoughSpace* HelixHoughFuncs_v1::_hough_space private
Definition at line 45 of file HelixHoughFuncs_v1.h.
View newest version in sPHENIX GitHub at line 45 of file HelixHoughFuncs_v1.h
Referenced by set_hough_space().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/HelixHoughFuncs_v1.h
coresoftware/blob/master/offline/packages/trackreco/HelixHoughFuncs_v1.cc