Analysis Software: SvtxPHG4ParticleMap_v1 Class Reference
SvtxPHG4ParticleMap_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxPHG4ParticleMap_v1.h>
Public Member Functions
SvtxPHG4ParticleMap_v1 ()
SvtxPHG4ParticleMap_v1 (const SvtxPHG4ParticleMap_v1 &map)
SvtxPHG4ParticleMap_v1 & operator= (const SvtxPHG4ParticleMap_v1 &map)
~SvtxPHG4ParticleMap_v1 () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void Reset () override
Clear Event.
bool empty () const override
std::size_t size () const override
std::size_t count (const unsigned int key) const override
void clear () override
bool processed () const override
void setProcessed (const bool process) override
const WeightedTruthTrackMap & get (const unsigned int key) const override
WeightedTruthTrackMap & get (const unsigned int key) override
WeightedTruthTrackMap insert (const unsigned int key, const WeightedTruthTrackMap map) override
std::size_t erase (const unsigned int key) override
ConstIter begin () const override
ConstIter find (const unsigned int key) const override
ConstIter end () const override
Iter begin () override
Iter find (const unsigned int key) override
Iter end () override
Public Member Functions inherited from SvtxPHG4ParticleMap
~SvtxPHG4ParticleMap () override
virtual WeightedTruthTrackMap insert (const unsigned int, const WeightedTruthTrackMap)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (SvtxPHG4ParticleMap_v1, 1)
Private Attributes
SvtxPHG4ParticleMap::Map m_map
bool m_processed = false
Additional Inherited Members
Public Types inherited from SvtxPHG4ParticleMap
typedef std::map< float,
std::set< int > > WeightedTruthTrackMap
Reco->Truth map with structure <reco track key, std::map< weight, std::set<g4part id>>>
typedef std::map< unsigned int,
WeightedTruthTrackMap > Map
typedef std::map< unsigned int,
WeightedTruthTrackMap >
::const_iterator ConstIter
typedef std::map< unsigned int,
WeightedTruthTrackMap >
::iterator Iter
Protected Member Functions inherited from SvtxPHG4ParticleMap
SvtxPHG4ParticleMap ()
Detailed Description
Definition at line 7 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 7 of file SvtxPHG4ParticleMap_v1.h
Constructor & Destructor Documentation
SvtxPHG4ParticleMap_v1::SvtxPHG4ParticleMap_v1 ()
Definition at line 3 of file SvtxPHG4ParticleMap_v1.cc.
View newest version in sPHENIX GitHub at line 3 of file SvtxPHG4ParticleMap_v1.cc
Referenced by CloneMe().
SvtxPHG4ParticleMap_v1::SvtxPHG4ParticleMap_v1 (const SvtxPHG4ParticleMap_v1 & map)
Definition at line 7 of file SvtxPHG4ParticleMap_v1.cc.
View newest version in sPHENIX GitHub at line 7 of file SvtxPHG4ParticleMap_v1.cc
References begin(), end(), and m_map.
SvtxPHG4ParticleMap_v1::~SvtxPHG4ParticleMap_v1 () override
Definition at line 30 of file SvtxPHG4ParticleMap_v1.cc.
View newest version in sPHENIX GitHub at line 30 of file SvtxPHG4ParticleMap_v1.cc
References Reset().
Member Function Documentation
ConstIter SvtxPHG4ParticleMap_v1::begin (void) const inline override virtual
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 40 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 40 of file SvtxPHG4ParticleMap_v1.h
References m_map.
Referenced by operator=(), and SvtxPHG4ParticleMap_v1().
Iter SvtxPHG4ParticleMap_v1::begin (void) inline override virtual
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 47 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 47 of file SvtxPHG4ParticleMap_v1.h
References m_map.
SvtxPHG4ParticleMap_v1::ClassDefOverride (SvtxPHG4ParticleMap_v1 , 1) private
void SvtxPHG4ParticleMap_v1::clear () inline override virtual
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 24 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 24 of file SvtxPHG4ParticleMap_v1.h
References m_map.
Referenced by Reset().
PHObject* SvtxPHG4ParticleMap_v1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 17 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 17 of file SvtxPHG4ParticleMap_v1.h
References SvtxPHG4ParticleMap_v1().
std::size_t SvtxPHG4ParticleMap_v1::count (const unsigned int key) const inline override virtual
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 23 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 23 of file SvtxPHG4ParticleMap_v1.h
References m_map.
bool SvtxPHG4ParticleMap_v1::empty () const inline override virtual
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 21 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 21 of file SvtxPHG4ParticleMap_v1.h
References m_map.
ConstIter SvtxPHG4ParticleMap_v1::end (void) const inline override virtual
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 45 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 45 of file SvtxPHG4ParticleMap_v1.h
References m_map.
Referenced by operator=(), and SvtxPHG4ParticleMap_v1().
Iter SvtxPHG4ParticleMap_v1::end (void) inline override virtual
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 49 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 49 of file SvtxPHG4ParticleMap_v1.h
References m_map.
std::size_t SvtxPHG4ParticleMap_v1::erase (const unsigned int key) inline override virtual
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 35 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 35 of file SvtxPHG4ParticleMap_v1.h
References m_map.
ConstIter SvtxPHG4ParticleMap_v1::find (const unsigned int key) const inline override virtual
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 41 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 41 of file SvtxPHG4ParticleMap_v1.h
References m_map.
Iter SvtxPHG4ParticleMap_v1::find (const unsigned int key) inline override virtual
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 48 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 48 of file SvtxPHG4ParticleMap_v1.h
References m_map.
const SvtxPHG4ParticleMap::WeightedTruthTrackMap & SvtxPHG4ParticleMap_v1::get (const unsigned int key) const override virtual
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 58 of file SvtxPHG4ParticleMap_v1.cc.
View newest version in sPHENIX GitHub at line 58 of file SvtxPHG4ParticleMap_v1.cc
References SvtxPHG4ParticleMap::get(), and m_map.
Referenced by BuildResonanceJetTaggingTree::findMatchedTruthD0(), and KFParticle_truthAndDetTools::getTruthTrack().
WeightedTruthTrackMap& SvtxPHG4ParticleMap_v1::get (const unsigned int key) inline override virtual
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 30 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 30 of file SvtxPHG4ParticleMap_v1.h
References m_map.
void SvtxPHG4ParticleMap_v1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 35 of file SvtxPHG4ParticleMap_v1.cc.
View newest version in sPHENIX GitHub at line 35 of file SvtxPHG4ParticleMap_v1.cc
References m_map, and trackID.
SvtxPHG4ParticleMap::WeightedTruthTrackMap SvtxPHG4ParticleMap_v1::insert (const unsigned int key, const WeightedTruthTrackMap map) override
Definition at line 52 of file SvtxPHG4ParticleMap_v1.cc.
View newest version in sPHENIX GitHub at line 52 of file SvtxPHG4ParticleMap_v1.cc
References m_map.
int SvtxPHG4ParticleMap_v1::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 16 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 16 of file SvtxPHG4ParticleMap_v1.h
SvtxPHG4ParticleMap_v1 & SvtxPHG4ParticleMap_v1::operator= (const SvtxPHG4ParticleMap_v1 & map)
Definition at line 18 of file SvtxPHG4ParticleMap_v1.cc.
View newest version in sPHENIX GitHub at line 18 of file SvtxPHG4ParticleMap_v1.cc
References begin(), end(), m_map, and Reset().
bool SvtxPHG4ParticleMap_v1::processed () const inline override virtual
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 26 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 26 of file SvtxPHG4ParticleMap_v1.h
References m_processed.
void SvtxPHG4ParticleMap_v1::Reset () inline override virtual
Clear Event.
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 19 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 19 of file SvtxPHG4ParticleMap_v1.h
References clear(), and m_processed.
Referenced by operator=(), and ~SvtxPHG4ParticleMap_v1().
void SvtxPHG4ParticleMap_v1::setProcessed (const bool process) inline override virtual
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 27 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 27 of file SvtxPHG4ParticleMap_v1.h
References m_processed, and tgeo-response2json::process().
std::size_t SvtxPHG4ParticleMap_v1::size (void) const inline override virtual
Reimplemented from SvtxPHG4ParticleMap.
Definition at line 22 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 22 of file SvtxPHG4ParticleMap_v1.h
References m_map.
Member Data Documentation
SvtxPHG4ParticleMap::Map SvtxPHG4ParticleMap_v1::m_map private
Definition at line 52 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 52 of file SvtxPHG4ParticleMap_v1.h
Referenced by begin(), clear(), count(), empty(), end(), erase(), find(), get(), identify(), insert(), operator=(), size(), and SvtxPHG4ParticleMap_v1().
bool SvtxPHG4ParticleMap_v1::m_processed = false private
Definition at line 53 of file SvtxPHG4ParticleMap_v1.h.
View newest version in sPHENIX GitHub at line 53 of file SvtxPHG4ParticleMap_v1.h
Referenced by processed(), Reset(), and setProcessed().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxPHG4ParticleMap_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxPHG4ParticleMap_v1.cc