Analysis Software: STrackMatcherComparator Class Reference
STrackMatcherComparator Class Reference
#include <analysis/blob/master/AndersonAnalysisModules/TrackStudies/STrackMatchingComparator/src/STrackMatcherComparator.h>
Classes
struct Consts
Public Member Functions
STrackMatcherComparator (optional< STrackMatcherComparatorConfig > config=nullopt)
~STrackMatcherComparator ()
void Init ()
void Analyze ()
void End ()
void SetConfig (STrackMatcherComparatorConfig &config)
void SetHistDef (STrackMatcherComparatorHistDef &histo)
STrackMatcherComparatorConfig GetConfig ()
STrackMatcherComparatorHistDef GetHistDef ()
Private Types
enum Src { NewTree, NewTuple, OldTuple }
enum Var {
NTot, NIntt, NMvtx, NTpc,
RTot, RIntt, RMvtx, RTpc,
Phi, Eta, Pt, Frac,
Qual, PtErr, EtaErr, PhiErr,
PtRes, EtaRes, PhiRes
}
enum Type { Truth, Track, Weird, Normal }
enum Comp { VsTruthPt, VsNumTpc }
Private Member Functions
void OpenOutput ()
void OpenInput ()
void InitHists ()
void GetNewTreeHists ()
void GetNewTupleHists ()
void GetOldTupleHists ()
void MakeRatiosAndPlots (const vector< vector< TH1D * >> vecNewHists1D, const vector< vector< vector< TH2D * >>> vecNewHists2D, const int iDir, const string sLabel)
void SaveHistograms ()
void CloseInput ()
void CloseOutput ()
void FillHistogram1D (const STrackMatcherComparatorHistContent &content, const Type type, const vector< vector< TH1D * >> vecHist1D)
void FillHistogram2D (const STrackMatcherComparatorHistContent &content, const Type type, const Comp comparison, const double value, const vector< vector< vector< TH2D * >>> vecHist2D)
bool IsNearSector (const float phi)
Private Attributes
STrackMatcherComparatorConfig m_config
STrackMatcherComparatorHistDef m_hist
TFile * m_outFile = NULL
TFile * m_treeInFileTrue = NULL
TFile * m_treeInFileReco = NULL
TFile * m_tupleInFileTrue = NULL
TFile * m_tupleInFileReco = NULL
TFile * m_oldInFileTrue = NULL
TFile * m_oldInFileReco = NULL
TTree * m_tTreeTrue = NULL
TTree * m_tTreeReco = NULL
TNtuple * m_ntTupleTrue = NULL
TNtuple * m_ntTupleReco = NULL
TNtuple * m_ntOldTrue = NULL
TNtuple * m_ntOldReco = NULL
vector< TDirectory * > m_vecHistDirs
vector< TDirectory * > m_vecRatioDirs
vector< TDirectory * > m_vecPlotDirs
vector< vector< TH1D * > > m_vecTreeHists1D
vector< vector< TH1D * > > m_vecTupleHists1D
vector< vector< TH1D * > > m_vecOldHists1D
vector< vector< vector< TH2D * > > > m_vecTreeHists2D
vector< vector< vector< TH2D * > > > m_vecTupleHists2D
vector< vector< vector< TH2D * > > > m_vecOldHists2D
struct
STrackMatcherComparator::Consts m_const = {3, 2, 2, 4, 4, 3, 12}
Detailed Description
Definition at line 36 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 36 of file STrackMatcherComparator.h
Member Enumeration Documentation
enum STrackMatcherComparator::Comp private
Enumerator:
VsTruthPt
VsNumTpc
Definition at line 71 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 71 of file STrackMatcherComparator.h
enum STrackMatcherComparator::Src private
Enumerator:
NewTree
NewTuple
OldTuple
Definition at line 39 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 39 of file STrackMatcherComparator.h
enum STrackMatcherComparator::Type private
Enumerator:
Truth
Track
Weird
Normal
Definition at line 65 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 65 of file STrackMatcherComparator.h
enum STrackMatcherComparator::Var private
Enumerator:
NTot
NIntt
NMvtx
NTpc
RTot
RIntt
RMvtx
RTpc
Phi
Eta
Pt
Frac
Qual
PtErr
EtaErr
PhiErr
PtRes
EtaRes
PhiRes
Definition at line 44 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 44 of file STrackMatcherComparator.h
Constructor & Destructor Documentation
STrackMatcherComparator::STrackMatcherComparator (optional< STrackMatcherComparatorConfig > config = nullopt)
Definition at line 43 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 43 of file STrackMatcherComparator.cc
STrackMatcherComparator::~STrackMatcherComparator ()
Definition at line 64 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 64 of file STrackMatcherComparator.cc
Member Function Documentation
void STrackMatcherComparator::Analyze ()
Definition at line 91 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 91 of file STrackMatcherComparator.cc
void STrackMatcherComparator::CloseInput () private
Definition at line 2394 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 2394 of file STrackMatcherComparator.cc
References cd(), and Close().
void STrackMatcherComparator::CloseOutput () private
Definition at line 2417 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 2417 of file STrackMatcherComparator.cc
References cd(), and Close().
void STrackMatcherComparator::End ()
Definition at line 106 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 106 of file STrackMatcherComparator.cc
void STrackMatcherComparator::FillHistogram1D (const STrackMatcherComparatorHistContent & content, const Type type, const vector< vector< TH1D * >> vecHist1D) private
Definition at line 2432 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 2432 of file STrackMatcherComparator.cc
References STrackMatcherComparatorHistContent::eta, Eta, STrackMatcherComparatorHistContent::etaErr, STrackMatcherComparatorHistContent::etaRes, Fill(), STrackMatcherComparatorHistContent::nIntt, STrackMatcherComparatorHistContent::nMvtx, STrackMatcherComparatorHistContent::nTot, STrackMatcherComparatorHistContent::nTpc, STrackMatcherComparatorHistContent::phi, STrackMatcherComparatorHistContent::phiErr, STrackMatcherComparatorHistContent::phiRes, STrackMatcherComparatorHistContent::pt, Pt(), STrackMatcherComparatorHistContent::ptErr, STrackMatcherComparatorHistContent::ptFrac, STrackMatcherComparatorHistContent::ptRes, STrackMatcherComparatorHistContent::quality, STrackMatcherComparatorHistContent::rIntt, STrackMatcherComparatorHistContent::rMvtx, STrackMatcherComparatorHistContent::rTot, and STrackMatcherComparatorHistContent::rTpc.
void STrackMatcherComparator::FillHistogram2D (const STrackMatcherComparatorHistContent & content, const Type type, const Comp comparison, const double value, const vector< vector< vector< TH2D * >>> vecHist2D) private
Definition at line 2464 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 2464 of file STrackMatcherComparator.cc
References STrackMatcherComparatorHistContent::eta, Eta, STrackMatcherComparatorHistContent::etaErr, STrackMatcherComparatorHistContent::etaRes, Fill(), STrackMatcherComparatorHistContent::nIntt, STrackMatcherComparatorHistContent::nMvtx, STrackMatcherComparatorHistContent::nTot, STrackMatcherComparatorHistContent::nTpc, STrackMatcherComparatorHistContent::phi, STrackMatcherComparatorHistContent::phiErr, STrackMatcherComparatorHistContent::phiRes, STrackMatcherComparatorHistContent::pt, Pt(), STrackMatcherComparatorHistContent::ptErr, STrackMatcherComparatorHistContent::ptFrac, STrackMatcherComparatorHistContent::ptRes, STrackMatcherComparatorHistContent::quality, STrackMatcherComparatorHistContent::rIntt, STrackMatcherComparatorHistContent::rMvtx, STrackMatcherComparatorHistContent::rTot, and STrackMatcherComparatorHistContent::rTpc.
STrackMatcherComparatorConfig STrackMatcherComparator::GetConfig () inline
Definition at line 92 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 92 of file STrackMatcherComparator.h
STrackMatcherComparatorHistDef STrackMatcherComparator::GetHistDef () inline
Definition at line 93 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 93 of file STrackMatcherComparator.h
void STrackMatcherComparator::GetNewTreeHists () private
Definition at line 369 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 369 of file STrackMatcherComparator.cc
References double(), material_mapping_optimisation::flush, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEntry(), and SetBranchAddress().
void STrackMatcherComparator::GetNewTupleHists () private
Definition at line 608 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 608 of file STrackMatcherComparator.cc
References material_mapping_optimisation::flush, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEntry(), and SetBranchAddress().
void STrackMatcherComparator::GetOldTupleHists () private
Definition at line 983 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 983 of file STrackMatcherComparator.cc
References material_mapping_optimisation::flush, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEntry(), and SetBranchAddress().
void STrackMatcherComparator::Init ()
Definition at line 74 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 74 of file STrackMatcherComparator.cc
void STrackMatcherComparator::InitHists () private
Definition at line 223 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 223 of file STrackMatcherComparator.cc
References GetXaxis(), GetYaxis(), GetZaxis(), and SetTitle().
bool STrackMatcherComparator::IsNearSector (const float phi) private
Definition at line 2498 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 2498 of file STrackMatcherComparator.cc
References Acts::Test::maxPhi, and Acts::Test::minPhi.
void STrackMatcherComparator::MakeRatiosAndPlots (const vector< vector< TH1D * >> vecNewHists1D, const vector< vector< vector< TH2D * >>> vecNewHists2D, const int iDir, const string sLabel) private
Definition at line 1661 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 1661 of file STrackMatcherComparator.cc
References AddEntry(), cd(), Close(), configureMap::data, Draw(), GetXaxis(), GetYaxis(), GetZaxis(), leg, Acts::UnitConstants::min, Reset(), SetBorderMode(), SetBorderSize(), SetBottomMargin(), SetFillColor(), SetFillStyle(), SetFrameBorderMode(), SetLeftMargin(), SetLineColor(), SetLineStyle(), SetLineWidth(), SetLogy(), SetMarkerColor(), SetMarkerStyle(), SetName(), SetRightMargin(), SetTextFont(), SetTitle(), SetTopMargin(), and Write().
void STrackMatcherComparator::OpenInput () private
Definition at line 158 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 158 of file STrackMatcherComparator.cc
References assert.
void STrackMatcherComparator::OpenOutput () private
Definition at line 127 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 127 of file STrackMatcherComparator.cc
References assert.
void STrackMatcherComparator::SaveHistograms () private
Definition at line 2357 of file STrackMatcherComparator.cc.
View newest version in sPHENIX GitHub at line 2357 of file STrackMatcherComparator.cc
References cd(), and Write().
void STrackMatcherComparator::SetConfig (STrackMatcherComparatorConfig & config) inline
Definition at line 88 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 88 of file STrackMatcherComparator.h
References filter::config.
void STrackMatcherComparator::SetHistDef (STrackMatcherComparatorHistDef & histo) inline
Definition at line 89 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 89 of file STrackMatcherComparator.h
Member Data Documentation
STrackMatcherComparatorConfig STrackMatcherComparator::m_config private
Definition at line 115 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 115 of file STrackMatcherComparator.h
struct STrackMatcherComparator::Consts STrackMatcherComparator::m_const = {3, 2, 2, 4, 4, 3, 12} private
STrackMatcherComparatorHistDef STrackMatcherComparator::m_hist private
Definition at line 116 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 116 of file STrackMatcherComparator.h
TNtuple* STrackMatcherComparator::m_ntOldReco = NULL private
Definition at line 133 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 133 of file STrackMatcherComparator.h
TNtuple* STrackMatcherComparator::m_ntOldTrue = NULL private
Definition at line 132 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 132 of file STrackMatcherComparator.h
TNtuple* STrackMatcherComparator::m_ntTupleReco = NULL private
Definition at line 131 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 131 of file STrackMatcherComparator.h
TNtuple* STrackMatcherComparator::m_ntTupleTrue = NULL private
Definition at line 130 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 130 of file STrackMatcherComparator.h
TFile* STrackMatcherComparator::m_oldInFileReco = NULL private
Definition at line 125 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 125 of file STrackMatcherComparator.h
TFile* STrackMatcherComparator::m_oldInFileTrue = NULL private
Definition at line 124 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 124 of file STrackMatcherComparator.h
TFile* STrackMatcherComparator::m_outFile = NULL private
Definition at line 119 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 119 of file STrackMatcherComparator.h
TFile* STrackMatcherComparator::m_treeInFileReco = NULL private
Definition at line 121 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 121 of file STrackMatcherComparator.h
TFile* STrackMatcherComparator::m_treeInFileTrue = NULL private
Definition at line 120 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 120 of file STrackMatcherComparator.h
TTree* STrackMatcherComparator::m_tTreeReco = NULL private
Definition at line 129 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 129 of file STrackMatcherComparator.h
TTree* STrackMatcherComparator::m_tTreeTrue = NULL private
Definition at line 128 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 128 of file STrackMatcherComparator.h
TFile* STrackMatcherComparator::m_tupleInFileReco = NULL private
Definition at line 123 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 123 of file STrackMatcherComparator.h
TFile* STrackMatcherComparator::m_tupleInFileTrue = NULL private
Definition at line 122 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 122 of file STrackMatcherComparator.h
vector<TDirectory*> STrackMatcherComparator::m_vecHistDirs private
Definition at line 136 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 136 of file STrackMatcherComparator.h
vector<vector<TH1D*> > STrackMatcherComparator::m_vecOldHists1D private
Definition at line 143 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 143 of file STrackMatcherComparator.h
vector<vector<vector<TH2D*> > > STrackMatcherComparator::m_vecOldHists2D private
Definition at line 148 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 148 of file STrackMatcherComparator.h
vector<TDirectory*> STrackMatcherComparator::m_vecPlotDirs private
Definition at line 138 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 138 of file STrackMatcherComparator.h
vector<TDirectory*> STrackMatcherComparator::m_vecRatioDirs private
Definition at line 137 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 137 of file STrackMatcherComparator.h
vector<vector<TH1D*> > STrackMatcherComparator::m_vecTreeHists1D private
Definition at line 141 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 141 of file STrackMatcherComparator.h
vector<vector<vector<TH2D*> > > STrackMatcherComparator::m_vecTreeHists2D private
Definition at line 146 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 146 of file STrackMatcherComparator.h
vector<vector<TH1D*> > STrackMatcherComparator::m_vecTupleHists1D private
Definition at line 142 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 142 of file STrackMatcherComparator.h
vector<vector<vector<TH2D*> > > STrackMatcherComparator::m_vecTupleHists2D private
Definition at line 147 of file STrackMatcherComparator.h.
View newest version in sPHENIX GitHub at line 147 of file STrackMatcherComparator.h
The documentation for this class was generated from the following files:
analysis/blob/master/AndersonAnalysisModules/TrackStudies/STrackMatchingComparator/src/STrackMatcherComparator.h
analysis/blob/master/AndersonAnalysisModules/TrackStudies/STrackMatchingComparator/src/STrackMatcherComparator.cc