Analysis Software: SDeltaPtCutStudy Class Reference
SDeltaPtCutStudy Class Reference
#include <analysis/blob/master/AndersonAnalysisModules/TrackStudies/SDeltaPtCutStudy/src/SDeltaPtCutStudy.h>
Public Member Functions
SDeltaPtCutStudy ()
~SDeltaPtCutStudy ()
void Init ()
void Analyze ()
void End ()
void SetInputOutputFiles (const TString sInput, const TString sOutput)
void SetInputTuples (const TString sTrack, const TString sTruth)
void SetGeneralTrackCuts (const uint32_t nInttCut, const uint32_t nMvtxCut, const uint32_t nTpcCut, const double qualCut, const double vzCut, const double ptCut)
void SetSigmaFitGuesses (const array< float, Const::NPar > hiGuess, const array< float, Const::NPar > loGuess)
void SetNormAndFitRanges (const pair< float, float > norm, const pair< float, float > ptFit, const pair< float, float > deltaFit)
void SetPlotRanges (const pair< float, float > ptRange, const pair< float, float > fracRange, const pair< float, float > deltaRange)
void SetGeneralStyleParameters (const array< uint32_t, Const::NTypes > arrCol, const array< uint32_t, Const::NTypes > arrMar)
void SetGeneralHistParameters (const uint32_t fill, const uint32_t line, const uint32_t width, const uint32_t font, const uint32_t align, const uint32_t center)
void SetHistBaseNames (const TString sProj, const TString sDelta, const TString sTrue, const TString sReco, const TString sFrac, const TString sTrack)
void SetPlotText (const vector< TString > plotText)
void SetEffRebinParameters (const bool doRebin, const size_t nRebin=2)
void SetProjectionParameters (const vector< tuple< double, TString, uint32_t, uint32_t, uint32_t >> projParams)
void SetFlatCutParameters (const vector< tuple< double, TString, uint32_t, uint32_t, bool >> flatParams)
void SetPtDependCutParameters (const vector< tuple< double, TString, uint32_t, uint32_t, uint32_t, bool >> ptDependParams)
Private Types
enum Const {
NPad = 2, NPar = 3, NVtx = 4, NRange = 2,
NTypes = 3, NTrkCuts = 6
}
Private Member Functions
void OpenFiles ()
void GetTuples ()
void SaveOutput ()
void CloseFiles ()
void InitVectors ()
void InitTuples ()
void InitHists ()
void ApplyFlatDeltaPtCuts ()
void ApplyPtDependentDeltaPtCuts ()
void FillTruthHistograms ()
void CreateSigmaGraphs ()
void CalculateRejectionFactors ()
void CalculateEfficiencies ()
void SetStyles ()
void MakePlots ()
Private Attributes
TFile * fInput
TFile * fOutput
TNtuple * ntTrack
TNtuple * ntTruth
TString sInFile
TString sOutFile
TString sInTrack
TString sInTruth
uint32_t nInttTrkMin = 1
uint32_t nMVtxTrkMin = 2
uint32_t nTpcTrkMin = 35
double qualTrkMax = 10.
double vzTrkMax = 10.
double ptTrkMin = 0.1
array< float, Const::NPar > sigHiGuess = {1., -1., 1.}
array< float, Const::NPar > sigLoGuess = {1., -1., 1.}
array< float, Const::NRange > normRange = {0.2, 1.2}
array< float, Const::NRange > ptFitRange = {0.5, 40.}
array< float, Const::NRange > deltaFitRange = {0., 0.1}
size_t nProj = 0
vector< double > ptProj
vector< TString > sProjSuffix
vector< TString > sPtProj
vector< uint32_t > fColProj
vector< uint32_t > fMarProj
vector< uint32_t > fColFit
size_t nDPtCuts = 0
size_t iCutToDraw = 0
vector< double > ptDeltaMax
vector< TString > sDPtSuffix
vector< uint32_t > fColCut
vector< uint32_t > fMarCut
size_t nSigCuts = 0
size_t iSigToDraw = 0
vector< double > ptDeltaSig
vector< TString > sSigSuffix
vector< uint32_t > fColSig
vector< uint32_t > fMarSig
vector< uint32_t > fColSigFit
TString sPtProjBase = "DeltaPtProj"
TString sPtDeltaBase = "DeltaPt"
TString sPtTrueBase = "PtTrue"
TString sPtRecoBase = "PtReco"
TString sPtFracBase = "PtFrac"
TString sPtTrkTruBase = "PtTrkTruth"
size_t nTxt = 0
vector< TString > sInfo
array< float, Const::NRange > rPtRange = {0., 60.}
array< float, Const::NRange > rFracRange = {0., 4.}
array< float, Const::NRange > rDeltaRange = {0., 0.1}
uint32_t fFil = 0
uint32_t fLin = 1
uint32_t fWid = 1
uint32_t fTxt = 42
uint32_t fAln = 12
uint32_t fCnt = 1
uint32_t fColTrue = 923
uint32_t fColPure = 923
uint32_t fColTrk = 809
uint32_t fMarTrue = 20
uint32_t fMarPure = 20
uint32_t fMarTrk = 46
size_t nEffRebin = 5
bool doEffRebin = true
float trk_event
float trk_seed
float trk_trackID
float trk_crossing
float trk_px
float trk_py
float trk_pz
float trk_pt
float trk_eta
float trk_phi
float trk_deltapt
float trk_deltaeta
float trk_deltaphi
float trk_charge
float trk_quality
float trk_chisq
float trk_ndf
float trk_nhits
float trk_nmaps
float trk_nintt
float trk_ntpc
float trk_nmms
float trk_ntpc1
float trk_ntpc11
float trk_ntpc2
float trk_ntpc3
float trk_nlmaps
float trk_nlintt
float trk_nltpc
float trk_nlmms
float trk_layers
float trk_vertexID
float trk_vx
float trk_vy
float trk_vz
float trk_dca2d
float trk_dca2dsigma
float trk_dca3dxy
float trk_dca3dxysigma
float trk_dca3dz
float trk_dca3dzsigma
float trk_pcax
float trk_pcay
float trk_pcaz
float trk_gtrackID
float trk_gflavor
float trk_gnhits
float trk_gnmaps
float trk_gnintt
float trk_gntpc
float trk_gnmms
float trk_gnlmaps
float trk_gnlintt
float trk_gnltpc
float trk_gnlmms
float trk_gpx
float trk_gpy
float trk_gpz
float trk_gpt
float trk_geta
float trk_gphi
float trk_gvx
float trk_gvy
float trk_gvz
float trk_gvt
float trk_gfpx
float trk_gfpy
float trk_gfpz
float trk_gfx
float trk_gfy
float trk_gfz
float trk_gembed
float trk_gprimary
float trk_nfromtruth
float trk_nwrong
float trk_ntrumaps
float trk_ntruintt
float trk_ntrutpc
float trk_ntrumms
float trk_ntrutpc1
float trk_ntrutpc11
float trk_ntrutpc2
float trk_ntrutpc3
float trk_layersfromtruth
float trk_nhittpcall
float trk_nhittpcin
float trk_nhittpcmid
float trk_nhittpcout
float trk_nclusall
float trk_nclustpc
float trk_nclusintt
float trk_nclusmaps
float trk_nclusmms
float tru_event
float tru_seed
float tru_gntracks
float tru_gtrackID
float tru_gflavor
float tru_gnhits
float tru_gnmaps
float tru_gnintt
float tru_gnmms
float tru_gnintt1
float tru_gnintt2
float tru_gnintt3
float tru_gnintt4
float tru_gnintt5
float tru_gnintt6
float tru_gnintt7
float tru_gnintt8
float tru_gntpc
float tru_gnlmaps
float tru_gnlintt
float tru_gnltpc
float tru_gnlmms
float tru_gpx
float tru_gpy
float tru_gpz
float tru_gpt
float tru_geta
float tru_gphi
float tru_gvx
float tru_gvy
float tru_gvz
float tru_gvt
float tru_gfpx
float tru_gfpy
float tru_gfpz
float tru_gfx
float tru_gfy
float tru_gfz
float tru_gembed
float tru_gprimary
float tru_trackID
float tru_px
float tru_py
float tru_pz
float tru_pt
float tru_eta
float tru_phi
float tru_deltapt
float tru_deltaeta
float tru_deltaphi
float tru_charge
float tru_quality
float tru_chisq
float tru_ndf
float tru_nhits
float tru_layers
float tru_nmaps
float tru_nintt
float tru_ntpc
float tru_nmms
float tru_ntpc1
float tru_ntpc11
float tru_ntpc2
float tru_ntpc3
float tru_nlmaps
float tru_nlintt
float tru_nltpc
float tru_nlmms
float tru_vertexID
float tru_vx
float tru_vy
float tru_vz
float tru_dca2d
float tru_dca2dsigma
float tru_dca3dxy
float tru_dca3dxysigma
float tru_dca3dz
float tru_dca3dzsigma
float tru_pcax
float tru_pcay
float tru_pcaz
float tru_nfromtruth
float tru_nwrong
float tru_ntrumaps
float tru_ntruintt
float tru_ntrutpc
float tru_ntrumms
float tru_ntrutpc1
float tru_ntrutpc11
float tru_ntrutpc2
float tru_ntrutpc3
float tru_layersfromtruth
float tru_nhittpcall
float tru_nhittpcin
float tru_nhittpcmid
float tru_nhittpcout
float tru_nclusall
float tru_nclustpc
float tru_nclusintt
float tru_nclusmaps
float tru_nclusmms
vector< double > muProj
vector< double > sigProj
vector< vector< double > > muHiProj
vector< vector< double > > muLoProj
vector< uint64_t > nNormCut
vector< uint64_t > nNormSig
vector< uint64_t > nWeirdCut
vector< uint64_t > nWeirdSig
vector< double > rejCut
vector< double > rejSig
uint64_t nTrks
uint64_t nTrus
TH1D * hEff
TH1D * hPtTruth
TH1D * hPtDelta
TH1D * hPtTrack
TH1D * hPtFrac
TH1D * hPtTrkTru
vector< TH1D * > hPtDeltaProj
vector< TH1D * > hPtDeltaCut
vector< TH1D * > hPtDeltaSig
vector< TH1D * > hPtTrackCut
vector< TH1D * > hPtTrackSig
vector< TH1D * > hPtFracCut
vector< TH1D * > hPtFracSig
vector< TH1D * > hPtTrkTruCut
vector< TH1D * > hPtTrkTruSig
vector< TH1D * > hEffCut
vector< TH1D * > hEffSig
TH2D * hPtDeltaVsFrac
TH2D * hPtDeltaVsTrue
TH2D * hPtDeltaVsTrack
TH2D * hPtTrueVsTrack
vector< TH2D * > hPtDeltaVsFracCut
vector< TH2D * > hPtDeltaVsFracSig
vector< TH2D * > hPtDeltaVsTrueCut
vector< TH2D * > hPtDeltaVsTrueSig
vector< TH2D * > hPtDeltaVsTrackCut
vector< TH2D * > hPtDeltaVsTrackSig
vector< TH2D * > hPtTrueVsTrackCut
vector< TH2D * > hPtTrueVsTrackSig
vector< TF1 * > fPtDeltaProj
vector< TF1 * > fMuHiProj
vector< TF1 * > fMuLoProj
TGraph * grMuProj
TGraph * grSigProj
TGraph * grRejCut
TGraph * grRejSig
vector< TGraph * > grMuHiProj
vector< TGraph * > grMuLoProj
Detailed Description
Definition at line 46 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 46 of file SDeltaPtCutStudy.h
Member Enumeration Documentation
enum SDeltaPtCutStudy::Const private
Enumerator:
NPad
NPar
NVtx
NRange
NTypes
NTrkCuts
Definition at line 49 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 49 of file SDeltaPtCutStudy.h
Constructor & Destructor Documentation
SDeltaPtCutStudy::SDeltaPtCutStudy ()
Definition at line 27 of file SDeltaPtCutStudy.cc.
View newest version in sPHENIX GitHub at line 27 of file SDeltaPtCutStudy.cc
SDeltaPtCutStudy::~SDeltaPtCutStudy ()
Definition at line 36 of file SDeltaPtCutStudy.cc.
View newest version in sPHENIX GitHub at line 36 of file SDeltaPtCutStudy.cc
Member Function Documentation
void SDeltaPtCutStudy::Analyze ()
Definition at line 65 of file SDeltaPtCutStudy.cc.
View newest version in sPHENIX GitHub at line 65 of file SDeltaPtCutStudy.cc
void SDeltaPtCutStudy::ApplyFlatDeltaPtCuts () private
Definition at line 20 of file SDeltaPtCutStudy.ana.h.
View newest version in sPHENIX GitHub at line 20 of file SDeltaPtCutStudy.ana.h
References Fill(), material_mapping_optimisation::flush, and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEntry().
void SDeltaPtCutStudy::ApplyPtDependentDeltaPtCuts () private
Definition at line 102 of file SDeltaPtCutStudy.ana.h.
View newest version in sPHENIX GitHub at line 102 of file SDeltaPtCutStudy.ana.h
References Fill(), material_mapping_optimisation::flush, and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEntry().
void SDeltaPtCutStudy::CalculateEfficiencies () private
Definition at line 403 of file SDeltaPtCutStudy.ana.h.
View newest version in sPHENIX GitHub at line 403 of file SDeltaPtCutStudy.ana.h
References Data, Reset(), and SetName().
void SDeltaPtCutStudy::CalculateRejectionFactors () private
Definition at line 346 of file SDeltaPtCutStudy.ana.h.
View newest version in sPHENIX GitHub at line 346 of file SDeltaPtCutStudy.ana.h
References double(), and SetName().
void SDeltaPtCutStudy::CloseFiles () private
Definition at line 405 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 405 of file SDeltaPtCutStudy.io.h
References cd(), and Close().
void SDeltaPtCutStudy::CreateSigmaGraphs () private
Definition at line 216 of file SDeltaPtCutStudy.ana.h.
View newest version in sPHENIX GitHub at line 216 of file SDeltaPtCutStudy.ana.h
References Data, configureMap::data, GetParameter(), GetXaxis(), ProjectionY, SetLineColor(), SetLineStyle(), SetLineWidth(), SetName(), SetParameter(), and size.
void SDeltaPtCutStudy::End ()
Definition at line 96 of file SDeltaPtCutStudy.cc.
View newest version in sPHENIX GitHub at line 96 of file SDeltaPtCutStudy.cc
References MakePlots().
void SDeltaPtCutStudy::FillTruthHistograms () private
Definition at line 179 of file SDeltaPtCutStudy.ana.h.
View newest version in sPHENIX GitHub at line 179 of file SDeltaPtCutStudy.ana.h
References Fill(), material_mapping_optimisation::flush, and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEntry().
void SDeltaPtCutStudy::GetTuples () private
Definition at line 311 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 311 of file SDeltaPtCutStudy.io.h
References assert.
void SDeltaPtCutStudy::Init ()
Definition at line 46 of file SDeltaPtCutStudy.cc.
View newest version in sPHENIX GitHub at line 46 of file SDeltaPtCutStudy.cc
void SDeltaPtCutStudy::InitHists () private
Definition at line 302 of file SDeltaPtCutStudy.sys.h.
View newest version in sPHENIX GitHub at line 302 of file SDeltaPtCutStudy.sys.h
References Data, and NRange.
void SDeltaPtCutStudy::InitTuples () private
Definition at line 95 of file SDeltaPtCutStudy.sys.h.
View newest version in sPHENIX GitHub at line 95 of file SDeltaPtCutStudy.sys.h
References SetBranchAddress().
void SDeltaPtCutStudy::InitVectors () private
Definition at line 20 of file SDeltaPtCutStudy.sys.h.
View newest version in sPHENIX GitHub at line 20 of file SDeltaPtCutStudy.sys.h
void SDeltaPtCutStudy::MakePlots () private
Definition at line 994 of file SDeltaPtCutStudy.plot.h.
View newest version in sPHENIX GitHub at line 994 of file SDeltaPtCutStudy.plot.h
References AddEntry(), cd(), Close(), cuts, Data, Draw(), leg, line, NTrkCuts, NVtx, proj(), SetBorderMode(), SetBorderSize(), SetBottomMargin(), SetFillColor(), SetFillStyle(), SetFrameBorderMode(), SetLeftMargin(), SetLineColor(), SetLineStyle(), SetLineWidth(), SetLogy(), SetRightMargin(), SetTextFont(), SetTitle(), SetTopMargin(), width, and Write().
void SDeltaPtCutStudy::OpenFiles () private
Definition at line 292 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 292 of file SDeltaPtCutStudy.io.h
References assert.
void SDeltaPtCutStudy::SaveOutput () private
Definition at line 330 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 330 of file SDeltaPtCutStudy.io.h
References cd(), and Write().
void SDeltaPtCutStudy::SetEffRebinParameters (const bool doRebin, const size_t nRebin = 2)
Definition at line 201 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 201 of file SDeltaPtCutStudy.io.h
void SDeltaPtCutStudy::SetFlatCutParameters (const vector< tuple< double, TString, uint32_t, uint32_t, bool >> flatParams)
Definition at line 233 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 233 of file SDeltaPtCutStudy.io.h
void SDeltaPtCutStudy::SetGeneralHistParameters (const uint32_t fill, const uint32_t line, const uint32_t width, const uint32_t font, const uint32_t align, const uint32_t center)
Definition at line 142 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 142 of file SDeltaPtCutStudy.io.h
References line, and width.
void SDeltaPtCutStudy::SetGeneralStyleParameters (const array< uint32_t, Const::NTypes > arrCol, const array< uint32_t, Const::NTypes > arrMar)
Definition at line 124 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 124 of file SDeltaPtCutStudy.io.h
void SDeltaPtCutStudy::SetGeneralTrackCuts (const uint32_t nInttCut, const uint32_t nMvtxCut, const uint32_t nTpcCut, const double qualCut, const double vzCut, const double ptCut)
Definition at line 48 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 48 of file SDeltaPtCutStudy.io.h
void SDeltaPtCutStudy::SetHistBaseNames (const TString sProj, const TString sDelta, const TString sTrue, const TString sReco, const TString sFrac, const TString sTrack)
Definition at line 164 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 164 of file SDeltaPtCutStudy.io.h
void SDeltaPtCutStudy::SetInputOutputFiles (const TString sInput, const TString sOutput)
Definition at line 20 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 20 of file SDeltaPtCutStudy.io.h
void SDeltaPtCutStudy::SetInputTuples (const TString sTrack, const TString sTruth)
Definition at line 34 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 34 of file SDeltaPtCutStudy.io.h
void SDeltaPtCutStudy::SetNormAndFitRanges (const pair< float, float > norm, const pair< float, float > ptFit, const pair< float, float > deltaFit)
Definition at line 86 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 86 of file SDeltaPtCutStudy.io.h
void SDeltaPtCutStudy::SetPlotRanges (const pair< float, float > ptRange, const pair< float, float > fracRange, const pair< float, float > deltaRange)
Definition at line 105 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 105 of file SDeltaPtCutStudy.io.h
void SDeltaPtCutStudy::SetPlotText (const vector< TString > plotText)
Definition at line 186 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 186 of file SDeltaPtCutStudy.io.h
void SDeltaPtCutStudy::SetProjectionParameters (const vector< tuple< double, TString, uint32_t, uint32_t, uint32_t >> projParams)
Definition at line 215 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 215 of file SDeltaPtCutStudy.io.h
void SDeltaPtCutStudy::SetPtDependCutParameters (const vector< tuple< double, TString, uint32_t, uint32_t, uint32_t, bool >> ptDependParams)
Definition at line 261 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 261 of file SDeltaPtCutStudy.io.h
void SDeltaPtCutStudy::SetSigmaFitGuesses (const array< float, Const::NPar > hiGuess, const array< float, Const::NPar > loGuess)
Definition at line 70 of file SDeltaPtCutStudy.io.h.
View newest version in sPHENIX GitHub at line 70 of file SDeltaPtCutStudy.io.h
References NPar.
void SDeltaPtCutStudy::SetStyles () private
Definition at line 20 of file SDeltaPtCutStudy.plot.h.
View newest version in sPHENIX GitHub at line 20 of file SDeltaPtCutStudy.plot.h
References GetXaxis(), GetYaxis(), GetZaxis(), NPad, SetFillColor(), SetFillStyle(), SetLineColor(), SetLineStyle(), SetLineWidth(), SetMarkerColor(), SetMarkerStyle(), and SetTitle().
Member Data Documentation
array<float, Const::NRange> SDeltaPtCutStudy::deltaFitRange = {0., 0.1} private
Definition at line 133 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 133 of file SDeltaPtCutStudy.h
bool SDeltaPtCutStudy::doEffRebin = true private
Definition at line 192 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 192 of file SDeltaPtCutStudy.h
uint32_t SDeltaPtCutStudy::fAln = 12 private
Definition at line 183 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 183 of file SDeltaPtCutStudy.h
uint32_t SDeltaPtCutStudy::fCnt = 1 private
Definition at line 184 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 184 of file SDeltaPtCutStudy.h
vector<uint32_t> SDeltaPtCutStudy::fColCut private
Definition at line 149 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 149 of file SDeltaPtCutStudy.h
vector<uint32_t> SDeltaPtCutStudy::fColFit private
Definition at line 142 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 142 of file SDeltaPtCutStudy.h
vector<uint32_t> SDeltaPtCutStudy::fColProj private
Definition at line 140 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 140 of file SDeltaPtCutStudy.h
uint32_t SDeltaPtCutStudy::fColPure = 923 private
Definition at line 186 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 186 of file SDeltaPtCutStudy.h
vector<uint32_t> SDeltaPtCutStudy::fColSig private
Definition at line 157 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 157 of file SDeltaPtCutStudy.h
vector<uint32_t> SDeltaPtCutStudy::fColSigFit private
Definition at line 159 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 159 of file SDeltaPtCutStudy.h
uint32_t SDeltaPtCutStudy::fColTrk = 809 private
Definition at line 187 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 187 of file SDeltaPtCutStudy.h
uint32_t SDeltaPtCutStudy::fColTrue = 923 private
Definition at line 185 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 185 of file SDeltaPtCutStudy.h
uint32_t SDeltaPtCutStudy::fFil = 0 private
Definition at line 179 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 179 of file SDeltaPtCutStudy.h
TFile* SDeltaPtCutStudy::fInput private
Definition at line 111 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 111 of file SDeltaPtCutStudy.h
uint32_t SDeltaPtCutStudy::fLin = 1 private
Definition at line 180 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 180 of file SDeltaPtCutStudy.h
vector<uint32_t> SDeltaPtCutStudy::fMarCut private
Definition at line 150 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 150 of file SDeltaPtCutStudy.h
vector<uint32_t> SDeltaPtCutStudy::fMarProj private
Definition at line 141 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 141 of file SDeltaPtCutStudy.h
uint32_t SDeltaPtCutStudy::fMarPure = 20 private
Definition at line 189 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 189 of file SDeltaPtCutStudy.h
vector<uint32_t> SDeltaPtCutStudy::fMarSig private
Definition at line 158 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 158 of file SDeltaPtCutStudy.h
uint32_t SDeltaPtCutStudy::fMarTrk = 46 private
Definition at line 190 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 190 of file SDeltaPtCutStudy.h
uint32_t SDeltaPtCutStudy::fMarTrue = 20 private
Definition at line 188 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 188 of file SDeltaPtCutStudy.h
vector<TF1*> SDeltaPtCutStudy::fMuHiProj private
Definition at line 450 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 450 of file SDeltaPtCutStudy.h
vector<TF1*> SDeltaPtCutStudy::fMuLoProj private
Definition at line 451 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 451 of file SDeltaPtCutStudy.h
TFile* SDeltaPtCutStudy::fOutput private
Definition at line 112 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 112 of file SDeltaPtCutStudy.h
vector<TF1*> SDeltaPtCutStudy::fPtDeltaProj private
Definition at line 449 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 449 of file SDeltaPtCutStudy.h
uint32_t SDeltaPtCutStudy::fTxt = 42 private
Definition at line 182 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 182 of file SDeltaPtCutStudy.h
uint32_t SDeltaPtCutStudy::fWid = 1 private
Definition at line 181 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 181 of file SDeltaPtCutStudy.h
vector<TGraph*> SDeltaPtCutStudy::grMuHiProj private
Definition at line 460 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 460 of file SDeltaPtCutStudy.h
vector<TGraph*> SDeltaPtCutStudy::grMuLoProj private
Definition at line 461 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 461 of file SDeltaPtCutStudy.h
TGraph* SDeltaPtCutStudy::grMuProj private
Definition at line 454 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 454 of file SDeltaPtCutStudy.h
TGraph* SDeltaPtCutStudy::grRejCut private
Definition at line 456 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 456 of file SDeltaPtCutStudy.h
TGraph* SDeltaPtCutStudy::grRejSig private
Definition at line 457 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 457 of file SDeltaPtCutStudy.h
TGraph* SDeltaPtCutStudy::grSigProj private
Definition at line 455 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 455 of file SDeltaPtCutStudy.h
TH1D* SDeltaPtCutStudy::hEff private
Definition at line 411 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 411 of file SDeltaPtCutStudy.h
vector<TH1D*> SDeltaPtCutStudy::hEffCut private
Definition at line 428 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 428 of file SDeltaPtCutStudy.h
vector<TH1D*> SDeltaPtCutStudy::hEffSig private
Definition at line 429 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 429 of file SDeltaPtCutStudy.h
TH1D* SDeltaPtCutStudy::hPtDelta private
Definition at line 413 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 413 of file SDeltaPtCutStudy.h
vector<TH1D*> SDeltaPtCutStudy::hPtDeltaCut private
Definition at line 420 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 420 of file SDeltaPtCutStudy.h
vector<TH1D*> SDeltaPtCutStudy::hPtDeltaProj private
Definition at line 419 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 419 of file SDeltaPtCutStudy.h
vector<TH1D*> SDeltaPtCutStudy::hPtDeltaSig private
Definition at line 421 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 421 of file SDeltaPtCutStudy.h
TH2D* SDeltaPtCutStudy::hPtDeltaVsFrac private
Definition at line 433 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 433 of file SDeltaPtCutStudy.h
vector<TH2D*> SDeltaPtCutStudy::hPtDeltaVsFracCut private
Definition at line 439 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 439 of file SDeltaPtCutStudy.h
vector<TH2D*> SDeltaPtCutStudy::hPtDeltaVsFracSig private
Definition at line 440 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 440 of file SDeltaPtCutStudy.h
TH2D* SDeltaPtCutStudy::hPtDeltaVsTrack private
Definition at line 435 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 435 of file SDeltaPtCutStudy.h
vector<TH2D*> SDeltaPtCutStudy::hPtDeltaVsTrackCut private
Definition at line 443 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 443 of file SDeltaPtCutStudy.h
vector<TH2D*> SDeltaPtCutStudy::hPtDeltaVsTrackSig private
Definition at line 444 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 444 of file SDeltaPtCutStudy.h
TH2D* SDeltaPtCutStudy::hPtDeltaVsTrue private
Definition at line 434 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 434 of file SDeltaPtCutStudy.h
vector<TH2D*> SDeltaPtCutStudy::hPtDeltaVsTrueCut private
Definition at line 441 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 441 of file SDeltaPtCutStudy.h
vector<TH2D*> SDeltaPtCutStudy::hPtDeltaVsTrueSig private
Definition at line 442 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 442 of file SDeltaPtCutStudy.h
TH1D* SDeltaPtCutStudy::hPtFrac private
Definition at line 415 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 415 of file SDeltaPtCutStudy.h
vector<TH1D*> SDeltaPtCutStudy::hPtFracCut private
Definition at line 424 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 424 of file SDeltaPtCutStudy.h
vector<TH1D*> SDeltaPtCutStudy::hPtFracSig private
Definition at line 425 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 425 of file SDeltaPtCutStudy.h
TH1D* SDeltaPtCutStudy::hPtTrack private
Definition at line 414 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 414 of file SDeltaPtCutStudy.h
vector<TH1D*> SDeltaPtCutStudy::hPtTrackCut private
Definition at line 422 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 422 of file SDeltaPtCutStudy.h
vector<TH1D*> SDeltaPtCutStudy::hPtTrackSig private
Definition at line 423 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 423 of file SDeltaPtCutStudy.h
TH1D* SDeltaPtCutStudy::hPtTrkTru private
Definition at line 416 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 416 of file SDeltaPtCutStudy.h
vector<TH1D*> SDeltaPtCutStudy::hPtTrkTruCut private
Definition at line 426 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 426 of file SDeltaPtCutStudy.h
vector<TH1D*> SDeltaPtCutStudy::hPtTrkTruSig private
Definition at line 427 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 427 of file SDeltaPtCutStudy.h
TH2D* SDeltaPtCutStudy::hPtTrueVsTrack private
Definition at line 436 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 436 of file SDeltaPtCutStudy.h
vector<TH2D*> SDeltaPtCutStudy::hPtTrueVsTrackCut private
Definition at line 445 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 445 of file SDeltaPtCutStudy.h
vector<TH2D*> SDeltaPtCutStudy::hPtTrueVsTrackSig private
Definition at line 446 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 446 of file SDeltaPtCutStudy.h
TH1D* SDeltaPtCutStudy::hPtTruth private
Definition at line 412 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 412 of file SDeltaPtCutStudy.h
size_t SDeltaPtCutStudy::iCutToDraw = 0 private
Definition at line 146 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 146 of file SDeltaPtCutStudy.h
size_t SDeltaPtCutStudy::iSigToDraw = 0 private
Definition at line 154 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 154 of file SDeltaPtCutStudy.h
vector<vector<double> > SDeltaPtCutStudy::muHiProj private
Definition at line 395 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 395 of file SDeltaPtCutStudy.h
vector<vector<double> > SDeltaPtCutStudy::muLoProj private
Definition at line 396 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 396 of file SDeltaPtCutStudy.h
vector<double> SDeltaPtCutStudy::muProj private
Definition at line 393 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 393 of file SDeltaPtCutStudy.h
size_t SDeltaPtCutStudy::nDPtCuts = 0 private
Definition at line 145 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 145 of file SDeltaPtCutStudy.h
size_t SDeltaPtCutStudy::nEffRebin = 5 private
Definition at line 191 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 191 of file SDeltaPtCutStudy.h
uint32_t SDeltaPtCutStudy::nInttTrkMin = 1 private
Definition at line 121 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 121 of file SDeltaPtCutStudy.h
uint32_t SDeltaPtCutStudy::nMVtxTrkMin = 2 private
Definition at line 122 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 122 of file SDeltaPtCutStudy.h
vector<uint64_t> SDeltaPtCutStudy::nNormCut private
Definition at line 399 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 399 of file SDeltaPtCutStudy.h
vector<uint64_t> SDeltaPtCutStudy::nNormSig private
Definition at line 400 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 400 of file SDeltaPtCutStudy.h
array<float, Const::NRange> SDeltaPtCutStudy::normRange = {0.2, 1.2} private
Definition at line 131 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 131 of file SDeltaPtCutStudy.h
size_t SDeltaPtCutStudy::nProj = 0 private
Definition at line 136 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 136 of file SDeltaPtCutStudy.h
size_t SDeltaPtCutStudy::nSigCuts = 0 private
Definition at line 153 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 153 of file SDeltaPtCutStudy.h
uint32_t SDeltaPtCutStudy::nTpcTrkMin = 35 private
Definition at line 123 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 123 of file SDeltaPtCutStudy.h
uint64_t SDeltaPtCutStudy::nTrks private
Definition at line 407 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 407 of file SDeltaPtCutStudy.h
uint64_t SDeltaPtCutStudy::nTrus private
Definition at line 408 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 408 of file SDeltaPtCutStudy.h
TNtuple* SDeltaPtCutStudy::ntTrack private
Definition at line 113 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 113 of file SDeltaPtCutStudy.h
TNtuple* SDeltaPtCutStudy::ntTruth private
Definition at line 114 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 114 of file SDeltaPtCutStudy.h
size_t SDeltaPtCutStudy::nTxt = 0 private
Definition at line 170 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 170 of file SDeltaPtCutStudy.h
vector<uint64_t> SDeltaPtCutStudy::nWeirdCut private
Definition at line 401 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 401 of file SDeltaPtCutStudy.h
vector<uint64_t> SDeltaPtCutStudy::nWeirdSig private
Definition at line 402 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 402 of file SDeltaPtCutStudy.h
vector<double> SDeltaPtCutStudy::ptDeltaMax private
Definition at line 147 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 147 of file SDeltaPtCutStudy.h
vector<double> SDeltaPtCutStudy::ptDeltaSig private
Definition at line 155 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 155 of file SDeltaPtCutStudy.h
array<float, Const::NRange> SDeltaPtCutStudy::ptFitRange = {0.5, 40.} private
Definition at line 132 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 132 of file SDeltaPtCutStudy.h
vector<double> SDeltaPtCutStudy::ptProj private
Definition at line 137 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 137 of file SDeltaPtCutStudy.h
double SDeltaPtCutStudy::ptTrkMin = 0.1 private
Definition at line 126 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 126 of file SDeltaPtCutStudy.h
double SDeltaPtCutStudy::qualTrkMax = 10. private
Definition at line 124 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 124 of file SDeltaPtCutStudy.h
array<float, Const::NRange> SDeltaPtCutStudy::rDeltaRange = {0., 0.1} private
Definition at line 176 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 176 of file SDeltaPtCutStudy.h
vector<double> SDeltaPtCutStudy::rejCut private
Definition at line 403 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 403 of file SDeltaPtCutStudy.h
vector<double> SDeltaPtCutStudy::rejSig private
Definition at line 404 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 404 of file SDeltaPtCutStudy.h
array<float, Const::NRange> SDeltaPtCutStudy::rFracRange = {0., 4.} private
Definition at line 175 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 175 of file SDeltaPtCutStudy.h
array<float, Const::NRange> SDeltaPtCutStudy::rPtRange = {0., 60.} private
Definition at line 174 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 174 of file SDeltaPtCutStudy.h
vector<TString> SDeltaPtCutStudy::sDPtSuffix private
Definition at line 148 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 148 of file SDeltaPtCutStudy.h
array<float, Const::NPar> SDeltaPtCutStudy::sigHiGuess = {1., -1., 1.} private
Definition at line 129 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 129 of file SDeltaPtCutStudy.h
array<float, Const::NPar> SDeltaPtCutStudy::sigLoGuess = {1., -1., 1.} private
Definition at line 130 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 130 of file SDeltaPtCutStudy.h
vector<double> SDeltaPtCutStudy::sigProj private
Definition at line 394 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 394 of file SDeltaPtCutStudy.h
TString SDeltaPtCutStudy::sInFile private
Definition at line 115 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 115 of file SDeltaPtCutStudy.h
vector<TString> SDeltaPtCutStudy::sInfo private
Definition at line 171 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 171 of file SDeltaPtCutStudy.h
TString SDeltaPtCutStudy::sInTrack private
Definition at line 117 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 117 of file SDeltaPtCutStudy.h
TString SDeltaPtCutStudy::sInTruth private
Definition at line 118 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 118 of file SDeltaPtCutStudy.h
TString SDeltaPtCutStudy::sOutFile private
Definition at line 116 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 116 of file SDeltaPtCutStudy.h
vector<TString> SDeltaPtCutStudy::sProjSuffix private
Definition at line 138 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 138 of file SDeltaPtCutStudy.h
TString SDeltaPtCutStudy::sPtDeltaBase = "DeltaPt" private
Definition at line 163 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 163 of file SDeltaPtCutStudy.h
TString SDeltaPtCutStudy::sPtFracBase = "PtFrac" private
Definition at line 166 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 166 of file SDeltaPtCutStudy.h
vector<TString> SDeltaPtCutStudy::sPtProj private
Definition at line 139 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 139 of file SDeltaPtCutStudy.h
TString SDeltaPtCutStudy::sPtProjBase = "DeltaPtProj" private
Definition at line 162 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 162 of file SDeltaPtCutStudy.h
TString SDeltaPtCutStudy::sPtRecoBase = "PtReco" private
Definition at line 165 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 165 of file SDeltaPtCutStudy.h
TString SDeltaPtCutStudy::sPtTrkTruBase = "PtTrkTruth" private
Definition at line 167 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 167 of file SDeltaPtCutStudy.h
TString SDeltaPtCutStudy::sPtTrueBase = "PtTrue" private
Definition at line 164 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 164 of file SDeltaPtCutStudy.h
vector<TString> SDeltaPtCutStudy::sSigSuffix private
Definition at line 156 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 156 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_charge private
Definition at line 208 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 208 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_chisq private
Definition at line 210 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 210 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_crossing private
Definition at line 198 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 198 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_dca2d private
Definition at line 230 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 230 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_dca2dsigma private
Definition at line 231 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 231 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_dca3dxy private
Definition at line 232 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 232 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_dca3dxysigma private
Definition at line 233 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 233 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_dca3dz private
Definition at line 234 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 234 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_dca3dzsigma private
Definition at line 235 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 235 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_deltaeta private
Definition at line 206 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 206 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_deltaphi private
Definition at line 207 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 207 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_deltapt private
Definition at line 205 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 205 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_eta private
Definition at line 203 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 203 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_event private
Definition at line 195 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 195 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gembed private
Definition at line 266 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 266 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_geta private
Definition at line 254 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 254 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gflavor private
Definition at line 240 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 240 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gfpx private
Definition at line 260 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 260 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gfpy private
Definition at line 261 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 261 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gfpz private
Definition at line 262 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 262 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gfx private
Definition at line 263 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 263 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gfy private
Definition at line 264 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 264 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gfz private
Definition at line 265 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 265 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gnhits private
Definition at line 241 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 241 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gnintt private
Definition at line 243 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 243 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gnlintt private
Definition at line 247 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 247 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gnlmaps private
Definition at line 246 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 246 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gnlmms private
Definition at line 249 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 249 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gnltpc private
Definition at line 248 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 248 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gnmaps private
Definition at line 242 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 242 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gnmms private
Definition at line 245 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 245 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gntpc private
Definition at line 244 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 244 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gphi private
Definition at line 255 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 255 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gprimary private
Definition at line 267 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 267 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gpt private
Definition at line 253 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 253 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gpx private
Definition at line 250 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 250 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gpy private
Definition at line 251 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 251 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gpz private
Definition at line 252 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 252 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gtrackID private
Definition at line 239 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 239 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gvt private
Definition at line 259 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 259 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gvx private
Definition at line 256 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 256 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gvy private
Definition at line 257 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 257 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_gvz private
Definition at line 258 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 258 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_layers private
Definition at line 225 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 225 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_layersfromtruth private
Definition at line 278 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 278 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nclusall private
Definition at line 283 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 283 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nclusintt private
Definition at line 285 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 285 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nclusmaps private
Definition at line 286 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 286 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nclusmms private
Definition at line 287 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 287 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nclustpc private
Definition at line 284 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 284 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_ndf private
Definition at line 211 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 211 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nfromtruth private
Definition at line 268 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 268 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nhits private
Definition at line 212 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 212 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nhittpcall private
Definition at line 279 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 279 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nhittpcin private
Definition at line 280 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 280 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nhittpcmid private
Definition at line 281 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 281 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nhittpcout private
Definition at line 282 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 282 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nintt private
Definition at line 214 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 214 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nlintt private
Definition at line 222 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 222 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nlmaps private
Definition at line 221 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 221 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nlmms private
Definition at line 224 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 224 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nltpc private
Definition at line 223 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 223 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nmaps private
Definition at line 213 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 213 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nmms private
Definition at line 216 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 216 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_ntpc private
Definition at line 215 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 215 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_ntpc1 private
Definition at line 217 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 217 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_ntpc11 private
Definition at line 218 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 218 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_ntpc2 private
Definition at line 219 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 219 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_ntpc3 private
Definition at line 220 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 220 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_ntruintt private
Definition at line 271 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 271 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_ntrumaps private
Definition at line 270 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 270 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_ntrumms private
Definition at line 273 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 273 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_ntrutpc private
Definition at line 272 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 272 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_ntrutpc1 private
Definition at line 274 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 274 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_ntrutpc11 private
Definition at line 275 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 275 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_ntrutpc2 private
Definition at line 276 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 276 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_ntrutpc3 private
Definition at line 277 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 277 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_nwrong private
Definition at line 269 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 269 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_pcax private
Definition at line 236 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 236 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_pcay private
Definition at line 237 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 237 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_pcaz private
Definition at line 238 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 238 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_phi private
Definition at line 204 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 204 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_pt private
Definition at line 202 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 202 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_px private
Definition at line 199 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 199 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_py private
Definition at line 200 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 200 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_pz private
Definition at line 201 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 201 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_quality private
Definition at line 209 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 209 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_seed private
Definition at line 196 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 196 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_trackID private
Definition at line 197 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 197 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_vertexID private
Definition at line 226 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 226 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_vx private
Definition at line 227 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 227 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_vy private
Definition at line 228 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 228 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::trk_vz private
Definition at line 229 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 229 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_charge private
Definition at line 340 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 340 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_chisq private
Definition at line 342 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 342 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_dca2d private
Definition at line 362 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 362 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_dca2dsigma private
Definition at line 363 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 363 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_dca3dxy private
Definition at line 364 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 364 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_dca3dxysigma private
Definition at line 365 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 365 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_dca3dz private
Definition at line 366 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 366 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_dca3dzsigma private
Definition at line 367 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 367 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_deltaeta private
Definition at line 338 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 338 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_deltaphi private
Definition at line 339 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 339 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_deltapt private
Definition at line 337 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 337 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_eta private
Definition at line 335 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 335 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_event private
Definition at line 290 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 290 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gembed private
Definition at line 328 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 328 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_geta private
Definition at line 316 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 316 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gflavor private
Definition at line 294 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 294 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gfpx private
Definition at line 322 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 322 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gfpy private
Definition at line 323 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 323 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gfpz private
Definition at line 324 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 324 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gfx private
Definition at line 325 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 325 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gfy private
Definition at line 326 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 326 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gfz private
Definition at line 327 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 327 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gnhits private
Definition at line 295 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 295 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gnintt private
Definition at line 297 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 297 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gnintt1 private
Definition at line 299 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 299 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gnintt2 private
Definition at line 300 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 300 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gnintt3 private
Definition at line 301 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 301 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gnintt4 private
Definition at line 302 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 302 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gnintt5 private
Definition at line 303 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 303 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gnintt6 private
Definition at line 304 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 304 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gnintt7 private
Definition at line 305 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 305 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gnintt8 private
Definition at line 306 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 306 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gnlintt private
Definition at line 309 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 309 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gnlmaps private
Definition at line 308 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 308 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gnlmms private
Definition at line 311 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 311 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gnltpc private
Definition at line 310 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 310 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gnmaps private
Definition at line 296 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 296 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gnmms private
Definition at line 298 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 298 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gntpc private
Definition at line 307 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 307 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gntracks private
Definition at line 292 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 292 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gphi private
Definition at line 317 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 317 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gprimary private
Definition at line 329 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 329 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gpt private
Definition at line 315 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 315 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gpx private
Definition at line 312 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 312 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gpy private
Definition at line 313 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 313 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gpz private
Definition at line 314 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 314 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gtrackID private
Definition at line 293 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 293 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gvt private
Definition at line 321 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 321 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gvx private
Definition at line 318 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 318 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gvy private
Definition at line 319 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 319 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_gvz private
Definition at line 320 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 320 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_layers private
Definition at line 345 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 345 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_layersfromtruth private
Definition at line 381 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 381 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nclusall private
Definition at line 386 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 386 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nclusintt private
Definition at line 388 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 388 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nclusmaps private
Definition at line 389 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 389 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nclusmms private
Definition at line 390 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 390 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nclustpc private
Definition at line 387 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 387 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_ndf private
Definition at line 343 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 343 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nfromtruth private
Definition at line 371 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 371 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nhits private
Definition at line 344 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 344 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nhittpcall private
Definition at line 382 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 382 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nhittpcin private
Definition at line 383 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 383 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nhittpcmid private
Definition at line 384 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 384 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nhittpcout private
Definition at line 385 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 385 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nintt private
Definition at line 347 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 347 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nlintt private
Definition at line 355 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 355 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nlmaps private
Definition at line 354 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 354 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nlmms private
Definition at line 357 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 357 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nltpc private
Definition at line 356 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 356 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nmaps private
Definition at line 346 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 346 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nmms private
Definition at line 349 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 349 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_ntpc private
Definition at line 348 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 348 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_ntpc1 private
Definition at line 350 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 350 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_ntpc11 private
Definition at line 351 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 351 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_ntpc2 private
Definition at line 352 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 352 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_ntpc3 private
Definition at line 353 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 353 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_ntruintt private
Definition at line 374 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 374 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_ntrumaps private
Definition at line 373 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 373 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_ntrumms private
Definition at line 376 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 376 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_ntrutpc private
Definition at line 375 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 375 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_ntrutpc1 private
Definition at line 377 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 377 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_ntrutpc11 private
Definition at line 378 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 378 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_ntrutpc2 private
Definition at line 379 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 379 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_ntrutpc3 private
Definition at line 380 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 380 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_nwrong private
Definition at line 372 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 372 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_pcax private
Definition at line 368 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 368 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_pcay private
Definition at line 369 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 369 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_pcaz private
Definition at line 370 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 370 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_phi private
Definition at line 336 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 336 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_pt private
Definition at line 334 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 334 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_px private
Definition at line 331 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 331 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_py private
Definition at line 332 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 332 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_pz private
Definition at line 333 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 333 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_quality private
Definition at line 341 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 341 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_seed private
Definition at line 291 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 291 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_trackID private
Definition at line 330 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 330 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_vertexID private
Definition at line 358 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 358 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_vx private
Definition at line 359 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 359 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_vy private
Definition at line 360 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 360 of file SDeltaPtCutStudy.h
float SDeltaPtCutStudy::tru_vz private
Definition at line 361 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 361 of file SDeltaPtCutStudy.h
double SDeltaPtCutStudy::vzTrkMax = 10. private
Definition at line 125 of file SDeltaPtCutStudy.h.
View newest version in sPHENIX GitHub at line 125 of file SDeltaPtCutStudy.h
The documentation for this class was generated from the following files:
analysis/blob/master/AndersonAnalysisModules/TrackStudies/SDeltaPtCutStudy/src/SDeltaPtCutStudy.h
analysis/blob/master/AndersonAnalysisModules/TrackStudies/SDeltaPtCutStudy/src/SDeltaPtCutStudy.ana.h
analysis/blob/master/AndersonAnalysisModules/TrackStudies/SDeltaPtCutStudy/src/SDeltaPtCutStudy.cc
analysis/blob/master/AndersonAnalysisModules/TrackStudies/SDeltaPtCutStudy/src/SDeltaPtCutStudy.io.h
analysis/blob/master/AndersonAnalysisModules/TrackStudies/SDeltaPtCutStudy/src/SDeltaPtCutStudy.plot.h
analysis/blob/master/AndersonAnalysisModules/TrackStudies/SDeltaPtCutStudy/src/SDeltaPtCutStudy.sys.h