Analysis Software: Acts::GaussianTrackDensity< input_track_t > Class Template Reference
Acts::GaussianTrackDensity< input_track_t > Class Template Reference
Class to model tracks as 2D density functions based on their d0 and z0 perigee parameters (mean value) and covariance matrices (determining the width of the function)
#include <acts/blob/sPHENIX/Core/include/Acts/Vertexing/GaussianTrackDensity.hpp>
Classes
struct Config
The Config struct.
class GaussianTrackDensityStore
struct State
The State struct.
struct TrackEntry
Struct to store information for a single track.
Public Member Functions
GaussianTrackDensity ()=default
Default constructor.
GaussianTrackDensity (const Config &cfg)
Constructor with config.
std::pair< double, double > globalMaximumWithWidth (State &state, const std::vector< const input_track_t * > &trackList, const std::function< BoundTrackParameters(input_track_t)> &extractParameters) const
Calculates z position of global maximum with Gaussian width for density function. Strategy: The global maximum must be somewhere near a track. Since we can calculate the first and second derivatives, at each point we can determine a) whether the function is curved up (minimum) or down (maximum) b) the distance to nearest maximum, assuming either Newton (parabolic) or Gaussian local behavior. For each track where the second derivative is negative, find step to nearest maximum, take that step and then do one final refinement. The largest density encountered in this procedure (after checking all tracks) is considered the maximum.
double globalMaximum (State &state, const std::vector< const input_track_t * > &trackList, const std::function< BoundTrackParameters(input_track_t)> &extractParameters) const
Calculates the z position of the global maximum.
Private Member Functions
Result< void > addTracks (State &state, const std::vector< const input_track_t * > &trackList, const std::function< BoundTrackParameters(input_track_t)> &extractParameters) const
Add a track to the set being considered.
std::tuple< double, double,
double > trackDensityAndDerivatives (State &state, double z) const
Evaluate the density function and its two first derivatives at the specified coordinate along the beamline.
std::tuple< double, double,
double > updateMaximum (double newZ, double newValue, double newSecondDerivative, double maxZ, double maxValue, double maxSecondDerivative) const
Update the current maximum values.
double stepSize (double y, double dy, double ddy) const
Calculates the step size.
Private Attributes
Config m_cfg
The configuration.
Detailed Description
template<typename input_track_t>
class Acts::GaussianTrackDensity< input_track_t >
Class to model tracks as 2D density functions based on their d0 and z0 perigee parameters (mean value) and covariance matrices (determining the width of the function)
Definition at line 24 of file GaussianTrackDensity.hpp.
View newest version in sPHENIX GitHub at line 24 of file GaussianTrackDensity.hpp
Constructor & Destructor Documentation
template<typename input_track_t > Acts::GaussianTrackDensity< input_track_t >::GaussianTrackDensity () default
Default constructor.
template<typename input_track_t > Acts::GaussianTrackDensity< input_track_t >::GaussianTrackDensity (const Config & cfg) inline
Constructor with config.
Definition at line 93 of file GaussianTrackDensity.hpp.
View newest version in sPHENIX GitHub at line 93 of file GaussianTrackDensity.hpp
Member Function Documentation
template<typename input_track_t > Result< void > Acts::GaussianTrackDensity< input_track_t >::addTracks (State & state, const std::vector< const input_track_t * > & trackList, const std::function< BoundTrackParameters(input_track_t)> & extractParameters) const private
Add a track to the set being considered.
Parameters
state The track density state
trackList All input tracks
extractParameters Function extracting BoundTrackParameters from InputTrack
Definition at line 78 of file GaussianTrackDensity.ipp.
View newest version in sPHENIX GitHub at line 78 of file GaussianTrackDensity.ipp
References Acts::GenericBoundTrackParameters< particle_hypothesis_t >::covariance(), Acts::eBoundLoc0, Acts::eBoundLoc1, m_cfg(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::parameters(), and Acts::GaussianTrackDensity< input_track_t >::State::trackEntries.
template<typename input_track_t > double Acts::GaussianTrackDensity< input_track_t >::globalMaximum (State & state, const std::vector< const input_track_t * > & trackList, const std::function< BoundTrackParameters(input_track_t)> & extractParameters) const
Calculates the z position of the global maximum.
Parameters
state The track density state
trackList All input tracks
extractParameters Function extracting BoundTrackParameters from InputTrack
Returns
z position of the global maximum
Definition at line 70 of file GaussianTrackDensity.ipp.
View newest version in sPHENIX GitHub at line 70 of file GaussianTrackDensity.ipp
template<typename input_track_t > std::pair< double, double > Acts::GaussianTrackDensity< input_track_t >::globalMaximumWithWidth (State & state, const std::vector< const input_track_t * > & trackList, const std::function< BoundTrackParameters(input_track_t)> & extractParameters) const
Calculates z position of global maximum with Gaussian width for density function. Strategy: The global maximum must be somewhere near a track. Since we can calculate the first and second derivatives, at each point we can determine a) whether the function is curved up (minimum) or down (maximum) b) the distance to nearest maximum, assuming either Newton (parabolic) or Gaussian local behavior. For each track where the second derivative is negative, find step to nearest maximum, take that step and then do one final refinement. The largest density encountered in this procedure (after checking all tracks) is considered the maximum.
Parameters
state The track density state
trackList All input tracks
extractParameters Function extracting BoundTrackParameters from InputTrack
Returns
Pair of position of global maximum and Gaussian width
Definition at line 17 of file GaussianTrackDensity.ipp.
View newest version in sPHENIX GitHub at line 17 of file GaussianTrackDensity.ipp
References Acts::Test::stepSize, and Acts::GaussianTrackDensity< input_track_t >::State::trackEntries.
template<typename input_track_t > double Acts::GaussianTrackDensity< input_track_t >::stepSize (double y, double dy, double ddy) const private
Calculates the step size.
Parameters
y Position value
dy First derivative
ddy Second derivative
Returns
The step size
Definition at line 158 of file GaussianTrackDensity.ipp.
View newest version in sPHENIX GitHub at line 158 of file GaussianTrackDensity.ipp
References m_cfg().
template<typename input_track_t > std::tuple< double, double, double > Acts::GaussianTrackDensity< input_track_t >::trackDensityAndDerivatives (State & state, double z) const private
Evaluate the density function and its two first derivatives at the specified coordinate along the beamline.
Parameters
state The track density state
z z-position along the beamline
Returns
Track density, first and second derivatives
Definition at line 135 of file GaussianTrackDensity.ipp.
View newest version in sPHENIX GitHub at line 135 of file GaussianTrackDensity.ipp
References Acts::GaussianTrackDensity< input_track_t >::GaussianTrackDensityStore::addTrackToDensity(), Acts::GaussianTrackDensity< input_track_t >::GaussianTrackDensityStore::densityAndDerivatives(), and Acts::GaussianTrackDensity< input_track_t >::State::trackEntries.
template<typename input_track_t > std::tuple< double, double, double > Acts::GaussianTrackDensity< input_track_t >::updateMaximum (double newZ, double newValue, double newSecondDerivative, double maxZ, double maxValue, double maxSecondDerivative) const private
Update the current maximum values.
Parameters
newZ The new z value
newValue The new value at z position
newSecondDerivative The new second derivative
maxZ Maximum z value, will be compared against newZ
maxValue Maximum value
maxSecondDerivative Maximum of the second derivative
Returns
The max z position, the max value at z position, the max second derivative
Definition at line 146 of file GaussianTrackDensity.ipp.
View newest version in sPHENIX GitHub at line 146 of file GaussianTrackDensity.ipp
References maxZ.
Member Data Documentation
template<typename input_track_t > Config Acts::GaussianTrackDensity< input_track_t >::m_cfg private
The configuration.
Definition at line 134 of file GaussianTrackDensity.hpp.
View newest version in sPHENIX GitHub at line 134 of file GaussianTrackDensity.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Vertexing/GaussianTrackDensity.hpp
acts/blob/sPHENIX/Core/include/Acts/Vertexing/GaussianTrackDensity.ipp