Analysis Software: Acts::MeasurementHelpers Namespace Reference
Acts::MeasurementHelpers Namespace Reference
Functions
template<typename T >
const Surface * getSurface (const T &fittable_measurement)
Extract surface from a type erased measurement object.
template<typename T >
size_t getSize (const T &fittable_measurement)
Function Documentation
template<typename T > size_t Acts::MeasurementHelpers::getSize (const T & fittable_measurement)
Definition at line 31 of file MeasurementHelpers.hpp.
View newest version in sPHENIX GitHub at line 31 of file MeasurementHelpers.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
template<typename T > const Surface* Acts::MeasurementHelpers::getSurface (const T & fittable_measurement)
Extract surface from a type erased measurement object.
Template Parameters
T The FittableMeasurement type
Returns
const pointer to the extracted surface
Definition at line 25 of file MeasurementHelpers.hpp.
View newest version in sPHENIX GitHub at line 25 of file MeasurementHelpers.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::MinimalSourceLink::referenceSurface(), and Acts::Test::ExtendedMinimalSourceLink::referenceSurface().