Analysis Software: macros/blob/master/common/G4_PlugDoor.C File Reference
G4_PlugDoor.C File Reference
#include <GlobalVariables.C>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4main/PHG4Reco.h>
Namespaces
namespace Enable
namespace G4PLUGDOOR
Macros
#define MACRO_G4PLUGDOOR_C
Functions
void common_color (PHG4CylinderSubsystem *subsys)
void PlugDoorInit ()
void PlugDoor (PHG4Reco *g4Reco)
Variables
bool Enable::PLUGDOOR = false
bool Enable::PLUGDOOR_ABSORBER = false
bool Enable::PLUGDOOR_OVERLAPCHECK = false
bool Enable::PLUGDOOR_BLACKHOLE = false
double G4PLUGDOOR::z_1 = 330.81
double G4PLUGDOOR::z_2 = 360.81
double G4PLUGDOOR::r_1 = 30
double G4PLUGDOOR::r_2 = 263.5
double G4PLUGDOOR::length = z_2 - z_1
double G4PLUGDOOR::place_z = (z_1 + z_2) / 2.
double G4PLUGDOOR::thickness = 2.
Macro Definition Documentation
#define MACRO_G4PLUGDOOR_C
Definition at line 2 of file G4_PlugDoor.C.
View newest version in sPHENIX GitHub at line 2 of file G4_PlugDoor.C
Function Documentation
void common_color (PHG4CylinderSubsystem * subsys)
Definition at line 171 of file G4_PlugDoor.C.
View newest version in sPHENIX GitHub at line 171 of file G4_PlugDoor.C
References PHG4CylinderSubsystem::set_color().
Referenced by PlugDoor().
void PlugDoor (PHG4Reco * g4Reco)
Definition at line 52 of file G4_PlugDoor.C.
View newest version in sPHENIX GitHub at line 52 of file G4_PlugDoor.C
References Enable::ABSORBER, PHG4DetectorSubsystem::BlackHole(), common_color(), G4PLUGDOOR::length, material, PHG4DetectorSubsystem::OverlapCheck(), Enable::OVERLAPCHECK, G4PLUGDOOR::place_z, Enable::PLUGDOOR_ABSORBER, Enable::PLUGDOOR_BLACKHOLE, Enable::PLUGDOOR_OVERLAPCHECK, G4PLUGDOOR::r_1, G4PLUGDOOR::r_2, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), G4PLUGDOOR::thickness, G4PLUGDOOR::z_1, and G4PLUGDOOR::z_2.
Referenced by G4Setup().
void PlugDoorInit ()
Definition at line 36 of file G4_PlugDoor.C.
View newest version in sPHENIX GitHub at line 36 of file G4_PlugDoor.C
References G4PLUGDOOR::length, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, Acts::UnitConstants::min, BlackHoleGeometry::min_z, G4PLUGDOOR::place_z, Enable::PLUGDOOR_BLACKHOLE, G4PLUGDOOR::r_2, G4PLUGDOOR::thickness, G4PLUGDOOR::z_1, and G4PLUGDOOR::z_2.
Referenced by G4Init().