Analysis Software: macros/blob/master/common/Trkr_Clustering.C File Reference
Trkr_Clustering.C File Reference
#include <GlobalVariables.C>
#include <G4_TrkrVariables.C>
#include <G4_ActsGeom.C>
#include <mvtx/MvtxHitPruner.h>
#include <mvtx/MvtxClusterizer.h>
#include <intt/InttClusterizer.h>
#include <tpc/TpcClusterizer.h>
#include <tpc/TpcClusterCleaner.h>
#include <micromegas/MicromegasClusterizer.h>
#include <fun4all/Fun4AllServer.h>
Macros
#define MACRO_TRKRCLUS_C
Functions
void ClusteringInit ()
void Mvtx_Clustering ()
void Intt_Clustering ()
void TPC_Clustering ()
void Micromegas_Clustering ()
Macro Definition Documentation
#define MACRO_TRKRCLUS_C
Definition at line 2 of file Trkr_Clustering.C.
View newest version in sPHENIX GitHub at line 2 of file Trkr_Clustering.C
Function Documentation
void ClusteringInit ()
Definition at line 30 of file Trkr_Clustering.C.
View newest version in sPHENIX GitHub at line 30 of file Trkr_Clustering.C
References ACTSGEOM::ActsGeomInit().
void Intt_Clustering ()
Definition at line 52 of file Trkr_Clustering.C.
View newest version in sPHENIX GitHub at line 52 of file Trkr_Clustering.C
References i, Fun4AllServer::instance(), Enable::INTT_VERBOSITY, G4INTT::laddertype, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, Fun4AllServer::registerSubsystem(), PHG4InttDefs::SEGMENTATION_PHI, InttClusterizer::set_z_clustering(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_G4_Calo(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunCorrelatorJetTree(), Fun4All_RunCorrelatorQAModules(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4All_TrkrClusteringSeeding(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), and spiNo2().
void Micromegas_Clustering ()
Definition at line 97 of file Trkr_Clustering.C.
View newest version in sPHENIX GitHub at line 97 of file Trkr_Clustering.C
References Fun4AllServer::instance().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_G4_Calo(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunCorrelatorJetTree(), Fun4All_RunCorrelatorQAModules(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4All_TrkrClusteringSeeding(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), and spiNo2().
void Mvtx_Clustering ()
Definition at line 35 of file Trkr_Clustering.C.
View newest version in sPHENIX GitHub at line 35 of file Trkr_Clustering.C
References Fun4AllServer::instance(), Enable::MVTX_VERBOSITY, Fun4AllServer::registerSubsystem(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_G4_Calo(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunCorrelatorJetTree(), Fun4All_RunCorrelatorQAModules(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4All_TrkrClusteringSeeding(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), and spiNo2().
void TPC_Clustering ()
Definition at line 73 of file Trkr_Clustering.C.
View newest version in sPHENIX GitHub at line 73 of file Trkr_Clustering.C
References ACTSGEOM::ActsGeomInit(), G4TPC::DO_HIT_ASSOCIATION, Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), Enable::TPC_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_G4_Calo(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunCorrelatorJetTree(), Fun4All_RunCorrelatorQAModules(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), and spiNo2().