Analysis Software: analysis/blob/master/JS-Jet/jet-kinematics-mc/macros/Fun4All_Analysis.C File Reference
Fun4All_Analysis.C File Reference
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <g4jets/ClusterJetInput.h>
#include <g4jets/FastJetAlgo.h>
#include <g4jets/JetReco.h>
#include <g4jets/TowerJetInput.h>
#include <g4jets/TrackJetInput.h>
#include <g4jets/TruthJetInput.h>
#include <G4_HIJetReco.C>
#include <G4_Jets.C>
#include <analysis/analysis.h>
Macros
#define MACRO_FUN4ALLANALYSIS_C
Functions
void Fun4All_Analysis (string inputFile1="DST_TRUTH_JET_pythia8_Jet04_3MHz-0000000004-00000.root", string inputFile2="DST_CALO_CLUSTER_pythia8_Jet04_3MHz-0000000004-00000.root", string outputfilename="test.root", const int nEvents=100)
Macro Definition Documentation
#define MACRO_FUN4ALLANALYSIS_C
Definition at line 2 of file Fun4All_Analysis.C.
View newest version in sPHENIX GitHub at line 2 of file Fun4All_Analysis.C
Function Documentation
void Fun4All_Analysis (string inputFile1 = "DST_TRUTH_JET_pythia8_Jet04_3MHz-0000000004-00000.root", string inputFile2 = "DST_CALO_CLUSTER_pythia8_Jet04_3MHz-0000000004-00000.root", string outputfilename = "test.root", const int nEvents = 100)
Definition at line 22 of file Fun4All_Analysis.C.
View newest version in sPHENIX GitHub at line 22 of file Fun4All_Analysis.C
References JetReco::add_algo(), JetReco::add_input(), analysis(), Jet::ANTIKT, Jet::CEMC_TOWER, Fun4AllServer::End(), Fun4AllInputManager::fileopen(), Jet::HCALIN_TOWER, Jet::HCALOUT_TOWER, in, Fun4AllServer::instance(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), JetReco::set_algo_node(), JetReco::set_input_node(), analysis::SetOutputFileName(), and Fun4AllBase::Verbosity().