Analysis Software: ActsExamples::EffPlotTool Class Reference
ActsExamples::EffPlotTool Class Reference
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Validation/EffPlotTool.hpp>
Classes
struct Config
The nested configuration struct.
struct EffPlotCache
Nested Cache struct.
Public Member Functions
EffPlotTool (const Config &cfg, Acts::Logging::Level lvl)
void book (EffPlotCache &effPlotCache) const
book the efficiency plots
void fill (EffPlotCache &effPlotCache, const ActsFatras::Particle &truthParticle, bool status) const
fill efficiency plots
void write (const EffPlotCache &effPlotCache) const
write the efficiency plots to file
void clear (EffPlotCache &effPlotCache) const
delete the efficiency plots
Private Member Functions
const Acts::Logger & logger () const
The logger.
Private Attributes
Config m_cfg
The Config class.
std::unique_ptr< const
Acts::Logger > m_logger
The logging instance.
Detailed Description
Definition at line 29 of file EffPlotTool.hpp.
View newest version in sPHENIX GitHub at line 29 of file EffPlotTool.hpp
Constructor & Destructor Documentation
ActsExamples::EffPlotTool::EffPlotTool (const Config & cfg, Acts::Logging::Level lvl)
Constructor
Parameters
cfg Configuration struct
lvl Message level declaration
Definition at line 20 of file EffPlotTool.cpp.
View newest version in sPHENIX GitHub at line 20 of file EffPlotTool.cpp
Member Function Documentation
void ActsExamples::EffPlotTool::book (EffPlotTool::EffPlotCache & effPlotCache) const
book the efficiency plots
Parameters
effPlotCache the cache for efficiency plots
Definition at line 24 of file EffPlotTool.cpp.
View newest version in sPHENIX GitHub at line 24 of file EffPlotTool.cpp
References ACTS_DEBUG, ActsExamples::PlotHelpers::bookEff(), m_cfg(), ActsExamples::EffPlotTool::EffPlotCache::trackEff_vs_eta, ActsExamples::EffPlotTool::EffPlotCache::trackEff_vs_phi, and ActsExamples::EffPlotTool::EffPlotCache::trackEff_vs_pT.
Referenced by ActsExamples::CKFPerformanceWriter::CKFPerformanceWriter(), ActsExamples::SeedingPerformanceWriter::SeedingPerformanceWriter(), and ActsExamples::TrackFitterPerformanceWriter::TrackFitterPerformanceWriter().
void ActsExamples::EffPlotTool::clear (EffPlotCache & effPlotCache) const
delete the efficiency plots
Parameters
effPlotCache cache object for efficiency plots
Definition at line 41 of file EffPlotTool.cpp.
View newest version in sPHENIX GitHub at line 41 of file EffPlotTool.cpp
References ActsExamples::EffPlotTool::EffPlotCache::trackEff_vs_eta, ActsExamples::EffPlotTool::EffPlotCache::trackEff_vs_phi, and ActsExamples::EffPlotTool::EffPlotCache::trackEff_vs_pT.
void ActsExamples::EffPlotTool::fill (EffPlotTool::EffPlotCache & effPlotCache, const ActsFatras::Particle & truthParticle, bool status) const
fill efficiency plots
Parameters
effPlotCache cache object for efficiency plots
truthParticle the truth Particle
status the reconstruction status
Definition at line 55 of file EffPlotTool.cpp.
View newest version in sPHENIX GitHub at line 55 of file EffPlotTool.cpp
References ActsFatras::Particle::direction(), eta, ActsExamples::PlotHelpers::fillEff(), ActsTests::PropagationDatasets::phi, ActsExamples::EffPlotTool::EffPlotCache::trackEff_vs_eta, ActsExamples::EffPlotTool::EffPlotCache::trackEff_vs_phi, ActsExamples::EffPlotTool::EffPlotCache::trackEff_vs_pT, and ActsFatras::Particle::transverseMomentum().
const Acts::Logger& ActsExamples::EffPlotTool::logger () const inline private
The logger.
Definition at line 80 of file EffPlotTool.hpp.
View newest version in sPHENIX GitHub at line 80 of file EffPlotTool.hpp
References m_logger.
void ActsExamples::EffPlotTool::write (const EffPlotCache & effPlotCache) const
write the efficiency plots to file
Parameters
effPlotCache cache object for efficiency plots
Definition at line 47 of file EffPlotTool.cpp.
View newest version in sPHENIX GitHub at line 47 of file EffPlotTool.cpp
References ACTS_DEBUG, ActsExamples::EffPlotTool::EffPlotCache::trackEff_vs_eta, ActsExamples::EffPlotTool::EffPlotCache::trackEff_vs_phi, and ActsExamples::EffPlotTool::EffPlotCache::trackEff_vs_pT.
Member Data Documentation
Config ActsExamples::EffPlotTool::m_cfg private
The Config class.
Definition at line 76 of file EffPlotTool.hpp.
View newest version in sPHENIX GitHub at line 76 of file EffPlotTool.hpp
std::unique_ptr<const Acts::Logger> ActsExamples::EffPlotTool::m_logger private
The logging instance.
Definition at line 77 of file EffPlotTool.hpp.
View newest version in sPHENIX GitHub at line 77 of file EffPlotTool.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Validation/EffPlotTool.hpp
acts/blob/sPHENIX/Examples/Framework/src/Validation/EffPlotTool.cpp