Analysis Software: keywords Namespace Reference
keywords Namespace Reference
Functions
def IsKeyword
def IsBuiltinType
Variables
string __author__ 'nnorwitz@google.com (Neal Norwitz)'
tuple TYPES set('bool char int long short double float void wchar_t unsigned signed'.split())
tuple TYPE_MODIFIERS set('auto register const inline extern static virtual volatile mutable'.split())
tuple ACCESS set('public protected private friend'.split())
tuple CASTS set('static_cast const_cast dynamic_cast reinterpret_cast'.split())
tuple OTHERS set('true false asm class namespace using explicit this operator sizeof'.split())
tuple OTHER_TYPES set('new delete typedef struct union enum typeid typename template'.split())
tuple CONTROL set('case switch default if else return goto'.split())
tuple EXCEPTION set('try catch throw'.split())
tuple LOOP set('while do for break continue'.split())
ALL TYPES|TYPE_MODIFIERS|ACCESS|CASTS|OTHERS|OTHER_TYPES|CONTROL|EXCEPTION|LOOP
Function Documentation
def keywords.IsBuiltinType (token)
Definition at line 55 of file keywords.py.
View newest version in sPHENIX GitHub at line 55 of file keywords.py
Referenced by ast.AstBuilder._GenerateOne().
def keywords.IsKeyword (token)
Definition at line 52 of file keywords.py.
View newest version in sPHENIX GitHub at line 52 of file keywords.py
Referenced by ast.AstBuilder._GenerateOne(), ast.AstBuilder._GetTemplatedTypes(), ast.TypeConverter.DeclarationToParts(), ast.AstBuilder.handle_typedef(), and ast.TypeConverter.ToType().
Variable Documentation
string keywords.__author__ 'nnorwitz@google.com (Neal Norwitz)'
Definition at line 20 of file keywords.py.
View newest version in sPHENIX GitHub at line 20 of file keywords.py
tuple keywords.ACCESS set('public protected private friend'.split())
Definition at line 38 of file keywords.py.
View newest version in sPHENIX GitHub at line 38 of file keywords.py
keywords.ALL TYPES|TYPE_MODIFIERS|ACCESS|CASTS|OTHERS|OTHER_TYPES|CONTROL|EXCEPTION|LOOP
Definition at line 49 of file keywords.py.
View newest version in sPHENIX GitHub at line 49 of file keywords.py
tuple keywords.CASTS set('static_cast const_cast dynamic_cast reinterpret_cast'.split())
Definition at line 40 of file keywords.py.
View newest version in sPHENIX GitHub at line 40 of file keywords.py
tuple keywords.CONTROL set('case switch default if else return goto'.split())
Definition at line 45 of file keywords.py.
View newest version in sPHENIX GitHub at line 45 of file keywords.py
tuple keywords.EXCEPTION set('try catch throw'.split())
Definition at line 46 of file keywords.py.
View newest version in sPHENIX GitHub at line 46 of file keywords.py
tuple keywords.LOOP set('while do for break continue'.split())
Definition at line 47 of file keywords.py.
View newest version in sPHENIX GitHub at line 47 of file keywords.py
tuple keywords.OTHER_TYPES set('new delete typedef struct union enum typeid typename template'.split())
Definition at line 43 of file keywords.py.
View newest version in sPHENIX GitHub at line 43 of file keywords.py
tuple keywords.OTHERS set('true false asm class namespace using explicit this operator sizeof'.split())
Definition at line 42 of file keywords.py.
View newest version in sPHENIX GitHub at line 42 of file keywords.py
tuple keywords.TYPE_MODIFIERS set('auto register const inline extern static virtual volatile mutable'.split())
Definition at line 37 of file keywords.py.
View newest version in sPHENIX GitHub at line 37 of file keywords.py
tuple keywords.TYPES set('bool char int long short double float void wchar_t unsigned signed'.split())
Definition at line 36 of file keywords.py.
View newest version in sPHENIX GitHub at line 36 of file keywords.py