Analysis Software: analysis/blob/master/Calo_Validation_Package/macros/Fun4All_Calo.C File Reference
Fun4All_Calo.C File Reference
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <phool/recoConsts.h>
#include <fun4all/Fun4AllNoSyncDstInputManager.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <caloreco/CaloTowerBuilder.h>
#include <caloreco/CaloWaveformProcessing.h>
#include <ffamodules/FlagHandler.h>
#include <ffamodules/HeadReco.h>
#include <ffamodules/SyncReco.h>
#include <ffamodules/CDBInterface.h>
#include <caloreco/TowerInfoDeadHotMask.h>
#include <caloreco/DeadHotMapLoader.h>
#include <caloreco/RawClusterDeadHotMask.h>
#include <caloana/CaloAna.h>
#include <fun4all/Fun4AllUtils.h>
Functions
void Fun4All_Calo (int nevents=100, const std::string &fname="input.txt")
Function Documentation
void Fun4All_Calo (int nevents = 100, const std::string & fname = "input.txt")
Definition at line 38 of file Fun4All_Calo.C.
View newest version in sPHENIX GitHub at line 38 of file Fun4All_Calo.C
References Fun4AllInputManager::AddListFile(), CaloAna::apply_vertex_cut(), RawClusterBuilderTemplate::Detector(), TowerInfoDeadHotMask::detector(), RawClusterDeadHotMask::detector(), DeadHotMapLoader::detector(), Fun4AllServer::End(), file, filename, INTTVtxZ::fname, Fun4AllUtils::GetRunSegment(), in, recoConsts::instance(), Fun4AllServer::instance(), RawClusterBuilderTemplate::LoadProfile(), nevents(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), runnumber, PHFlag::set_StringFlag(), RawClusterBuilderTemplate::set_threshold_energy(), CaloAna::set_timing_cut_width(), PHFlag::set_uint64Flag(), RawClusterBuilderTemplate::set_UseTowerInfo(), CaloAna::set_vertex_cut(), verbosity, and Fun4AllBase::Verbosity().