Analysis Software: GlobalVertex Class Reference
GlobalVertex Class Reference
#include <coresoftware/blob/master/offline/packages/globalvertex/GlobalVertex.h>
Public Types
enum VTXTYPE {
UNDEFINED = 0, TRUTH = 100, SMEARED = 200, MBD = 300,
SVTX = 400, SVTX_MBD = 500
}
typedef std::vector< const
Vertex * > VertexVector
typedef std::map
< GlobalVertex::VTXTYPE,
VertexVector >::const_iterator ConstVertexIter
typedef std::map
< GlobalVertex::VTXTYPE,
VertexVector >::iterator VertexIter
typedef std::map
< GlobalVertex::VTXTYPE,
unsigned int >::const_iterator ConstVtxIter
typedef std::map
< GlobalVertex::VTXTYPE,
unsigned int >::iterator VtxIter
Public Member Functions
~GlobalVertex () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual unsigned int get_id () const
virtual void set_id (unsigned int)
virtual float get_t () const
virtual void set_t (float)
virtual float get_t_err () const
virtual void set_t_err (float)
virtual float get_x () const
virtual void set_x (float)
virtual float get_y () const
virtual void set_y (float)
virtual float get_z () const
virtual void set_z (float)
virtual float get_chisq () const
virtual void set_chisq (float)
virtual unsigned int get_ndof () const
virtual void set_ndof (unsigned int)
virtual float get_position (unsigned int) const
virtual void set_position (unsigned int, float)
virtual float get_error (unsigned int, unsigned int) const
virtual void set_error (unsigned int, unsigned int, float)
virtual unsigned int get_beam_crossing () const
virtual void set_beam_crossing (unsigned int)
virtual bool empty_vtxs () const
virtual size_t size_vtxs () const
virtual size_t count_vtxs (VTXTYPE) const
virtual void clear_vtxs ()
virtual void insert_vtx (VTXTYPE, const Vertex *)
virtual size_t erase_vtxs (VTXTYPE)
virtual void erase_vtxs (VertexIter)
virtual ConstVertexIter begin_vertexes () const
virtual ConstVertexIter find_vertexes (VTXTYPE type) const
virtual ConstVertexIter end_vertexes () const
virtual VertexIter begin_vertexes ()
virtual VertexIter find_vertexes (VTXTYPE type)
virtual VertexIter end_vertexes ()
virtual bool empty_vtxids () const
virtual size_t size_vtxids () const
virtual size_t count_vtxids (VTXTYPE) const
virtual void clear_vtxids ()
virtual void insert_vtxids (VTXTYPE, unsigned int)
virtual size_t erase_vtxids (VTXTYPE)
virtual void erase_vtxids (VtxIter)
virtual void erase_vtxids (VtxIter, VtxIter)
virtual ConstVtxIter begin_vtxids () const
virtual ConstVtxIter find_vtxids (VTXTYPE type) const
virtual ConstVtxIter end_vtxids () const
virtual VtxIter begin_vtxids ()
virtual VtxIter find_vtxids (VTXTYPE type)
virtual VtxIter end_vtxids ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
GlobalVertex ()
Private Member Functions
ClassDefOverride (GlobalVertex, 1)
Detailed Description
Definition at line 12 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 12 of file GlobalVertex.h
Member Typedef Documentation
typedef std::map<GlobalVertex::VTXTYPE, VertexVector>::const_iterator GlobalVertex::ConstVertexIter
Definition at line 27 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 27 of file GlobalVertex.h
typedef std::map<GlobalVertex::VTXTYPE, unsigned int>::const_iterator GlobalVertex::ConstVtxIter
Definition at line 31 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 31 of file GlobalVertex.h
typedef std::map<GlobalVertex::VTXTYPE, VertexVector>::iterator GlobalVertex::VertexIter
Definition at line 28 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 28 of file GlobalVertex.h
typedef std::vector<const Vertex*> GlobalVertex::VertexVector
Definition at line 26 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 26 of file GlobalVertex.h
typedef std::map<GlobalVertex::VTXTYPE, unsigned int>::iterator GlobalVertex::VtxIter
Definition at line 32 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 32 of file GlobalVertex.h
Member Enumeration Documentation
enum GlobalVertex::VTXTYPE
Enumerator:
UNDEFINED
TRUTH
SMEARED
MBD
SVTX
SVTX_MBD
Definition at line 16 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 16 of file GlobalVertex.h
Constructor & Destructor Documentation
GlobalVertex::~GlobalVertex () inline override
Definition at line 36 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 36 of file GlobalVertex.h
GlobalVertex::GlobalVertex () inline protected
Definition at line 122 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 122 of file GlobalVertex.h
Member Function Documentation
GlobalVertex::ConstVertexIter GlobalVertex::begin_vertexes () const virtual
Reimplemented in GlobalVertexv2.
Definition at line 6 of file GlobalVertex.cc.
View newest version in sPHENIX GitHub at line 6 of file GlobalVertex.cc
GlobalVertex::VertexIter GlobalVertex::begin_vertexes () virtual
Reimplemented in GlobalVertexv2.
Definition at line 18 of file GlobalVertex.cc.
View newest version in sPHENIX GitHub at line 18 of file GlobalVertex.cc
GlobalVertex::ConstVtxIter GlobalVertex::begin_vtxids () const virtual
Reimplemented in GlobalVertexv1.
Definition at line 30 of file GlobalVertex.cc.
View newest version in sPHENIX GitHub at line 30 of file GlobalVertex.cc
GlobalVertex::VtxIter GlobalVertex::begin_vtxids () virtual
Reimplemented in GlobalVertexv1.
Definition at line 45 of file GlobalVertex.cc.
View newest version in sPHENIX GitHub at line 45 of file GlobalVertex.cc
GlobalVertex::ClassDefOverride (GlobalVertex , 1) private
virtual void GlobalVertex::clear_vtxids () inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 107 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 107 of file GlobalVertex.h
virtual void GlobalVertex::clear_vtxs () inline virtual
Reimplemented in GlobalVertexv2.
Definition at line 85 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 85 of file GlobalVertex.h
PHObject* GlobalVertex::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in GlobalVertexv2, and GlobalVertexv1.
Definition at line 45 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 45 of file GlobalVertex.h
virtual size_t GlobalVertex::count_vtxids (VTXTYPE) const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 105 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 105 of file GlobalVertex.h
virtual size_t GlobalVertex::count_vtxs (VTXTYPE) const inline virtual
Reimplemented in GlobalVertexv2.
Definition at line 84 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 84 of file GlobalVertex.h
virtual bool GlobalVertex::empty_vtxids () const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 103 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 103 of file GlobalVertex.h
virtual bool GlobalVertex::empty_vtxs () const inline virtual
Reimplemented in GlobalVertexv2.
Definition at line 82 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 82 of file GlobalVertex.h
GlobalVertex::ConstVertexIter GlobalVertex::end_vertexes () const virtual
Reimplemented in GlobalVertexv2.
Definition at line 14 of file GlobalVertex.cc.
View newest version in sPHENIX GitHub at line 14 of file GlobalVertex.cc
Referenced by SvtxEvaluator::fillOutputNtuples(), KFParticle_truthAndDetTools::fillTruthBranch(), and KFParticle_Tools::makeAllPrimaryVertices().
GlobalVertex::VertexIter GlobalVertex::end_vertexes () virtual
Reimplemented in GlobalVertexv2.
Definition at line 26 of file GlobalVertex.cc.
View newest version in sPHENIX GitHub at line 26 of file GlobalVertex.cc
GlobalVertex::ConstVtxIter GlobalVertex::end_vtxids () const virtual
Reimplemented in GlobalVertexv1.
Definition at line 40 of file GlobalVertex.cc.
View newest version in sPHENIX GitHub at line 40 of file GlobalVertex.cc
Referenced by AnaTutorial::getEMCalClusters().
GlobalVertex::VtxIter GlobalVertex::end_vtxids () virtual
Reimplemented in GlobalVertexv1.
Definition at line 55 of file GlobalVertex.cc.
View newest version in sPHENIX GitHub at line 55 of file GlobalVertex.cc
virtual size_t GlobalVertex::erase_vtxids (VTXTYPE) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 109 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 109 of file GlobalVertex.h
virtual void GlobalVertex::erase_vtxids (VtxIter) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 110 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 110 of file GlobalVertex.h
virtual void GlobalVertex::erase_vtxids (VtxIter , VtxIter) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 111 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 111 of file GlobalVertex.h
virtual size_t GlobalVertex::erase_vtxs (VTXTYPE) inline virtual
Reimplemented in GlobalVertexv2.
Definition at line 87 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 87 of file GlobalVertex.h
virtual void GlobalVertex::erase_vtxs (VertexIter) inline virtual
Reimplemented in GlobalVertexv2.
Definition at line 88 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 88 of file GlobalVertex.h
GlobalVertex::ConstVertexIter GlobalVertex::find_vertexes (VTXTYPE type) const virtual
Reimplemented in GlobalVertexv2.
Definition at line 10 of file GlobalVertex.cc.
View newest version in sPHENIX GitHub at line 10 of file GlobalVertex.cc
Referenced by SvtxEvaluator::fillOutputNtuples(), KFParticle_truthAndDetTools::fillTruthBranch(), and KFParticle_Tools::makeAllPrimaryVertices().
GlobalVertex::VertexIter GlobalVertex::find_vertexes (VTXTYPE type) virtual
Reimplemented in GlobalVertexv2.
Definition at line 22 of file GlobalVertex.cc.
View newest version in sPHENIX GitHub at line 22 of file GlobalVertex.cc
GlobalVertex::ConstVtxIter GlobalVertex::find_vtxids (VTXTYPE type) const virtual
Reimplemented in GlobalVertexv1.
Definition at line 35 of file GlobalVertex.cc.
View newest version in sPHENIX GitHub at line 35 of file GlobalVertex.cc
Referenced by AnaTutorial::getEMCalClusters(), and KFParticle_Tools::getTracksFromVertex().
GlobalVertex::VtxIter GlobalVertex::find_vtxids (VTXTYPE type) virtual
Reimplemented in GlobalVertexv1.
Definition at line 50 of file GlobalVertex.cc.
View newest version in sPHENIX GitHub at line 50 of file GlobalVertex.cc
virtual unsigned int GlobalVertex::get_beam_crossing () const inline virtual
Reimplemented in GlobalVertexv2.
Definition at line 79 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 79 of file GlobalVertex.h
virtual float GlobalVertex::get_chisq () const inline virtual
Reimplemented in GlobalVertexv1, and GlobalVertexv2.
Definition at line 67 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 67 of file GlobalVertex.h
Referenced by FullJetFinder::GetDistanceFromVertexXY().
virtual float GlobalVertex::get_error (unsigned int , unsigned int) const inline virtual
Reimplemented in GlobalVertexv1, and GlobalVertexv2.
Definition at line 76 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 76 of file GlobalVertex.h
Referenced by FullJetFinder::GetDistanceFromVertexXY().
virtual unsigned int GlobalVertex::get_id () const inline virtual
Reimplemented in GlobalVertexv1, and GlobalVertexv2.
Definition at line 49 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 49 of file GlobalVertex.h
Referenced by GlobalVertexMapv1::insert(), KFParticle_Tools::makeAllPrimaryVertices(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), GlobalVertexReco::process_event(), sPHAnalysis::process_event_notracking(), sPHAnalysis_calo::process_event_test(), sPHAnalysis::process_event_test(), and sPHAnalysis::process_event_upsilons().
virtual unsigned int GlobalVertex::get_ndof () const inline virtual
Reimplemented in GlobalVertexv1, and GlobalVertexv2.
Definition at line 70 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 70 of file GlobalVertex.h
Referenced by FullJetFinder::GetDistanceFromVertexXY().
virtual float GlobalVertex::get_position (unsigned int) const inline virtual
Reimplemented in GlobalVertexv1, and GlobalVertexv2.
Definition at line 73 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 73 of file GlobalVertex.h
virtual float GlobalVertex::get_t () const inline virtual
Reimplemented in GlobalVertexv2, and GlobalVertexv1.
Definition at line 52 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 52 of file GlobalVertex.h
virtual float GlobalVertex::get_t_err () const inline virtual
Reimplemented in GlobalVertexv1, and GlobalVertexv2.
Definition at line 55 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 55 of file GlobalVertex.h
virtual float GlobalVertex::get_x () const inline virtual
Reimplemented in GlobalVertexv1, and GlobalVertexv2.
Definition at line 58 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 58 of file GlobalVertex.h
Referenced by ResonanceJetTagging::addClusters(), cemcReco::calculateTSP(), cemcReco::coneSum(), PhotonJet::ConeSum(), TrkrNtuplizer::fillOutputNtuples(), CaloEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), KFParticle_truthAndDetTools::fillTruthBranch(), ClusterJetInput::get_input(), FullJetFinder::GetDistanceFromVertexXY(), AnaTutorial::getEMCalClusters(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), CaloEvaluator::printOutputInfo(), RawClusterBuilderTemplate::process_event(), ClusterIso::process_event(), Forward_pi0s::process_event(), Photons::process_event(), PJTranslator::process_event(), Pi0MassAnalysis::process_event(), CaloCalibEmc_Pi0::process_event(), isoCluster::process_event(), singlePhotonClusterAna::process_event(), pi0ClusterAna::process_event(), pythiaEMCalAna::process_event(), PhotonJet::process_event(), pi0Efficiency::process_event(), FullJetFinder::process_event(), cemcReco::process_event(), PairMaker::process_event_test(), and PHFlowJetMaker::run_particle_flow().
virtual float GlobalVertex::get_y () const inline virtual
Reimplemented in GlobalVertexv1, and GlobalVertexv2.
Definition at line 61 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 61 of file GlobalVertex.h
Referenced by ResonanceJetTagging::addClusters(), cemcReco::calculateTSP(), cemcReco::coneSum(), PhotonJet::ConeSum(), TrkrNtuplizer::fillOutputNtuples(), CaloEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), KFParticle_truthAndDetTools::fillTruthBranch(), ClusterJetInput::get_input(), FullJetFinder::GetDistanceFromVertexXY(), AnaTutorial::getEMCalClusters(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), CaloEvaluator::printOutputInfo(), RawClusterBuilderTemplate::process_event(), ClusterIso::process_event(), Forward_pi0s::process_event(), Photons::process_event(), PJTranslator::process_event(), Pi0MassAnalysis::process_event(), CaloCalibEmc_Pi0::process_event(), isoCluster::process_event(), singlePhotonClusterAna::process_event(), pi0ClusterAna::process_event(), pythiaEMCalAna::process_event(), PhotonJet::process_event(), pi0Efficiency::process_event(), FullJetFinder::process_event(), cemcReco::process_event(), PairMaker::process_event_test(), and PHFlowJetMaker::run_particle_flow().
virtual float GlobalVertex::get_z () const inline virtual
Reimplemented in GlobalVertexv1, and GlobalVertexv2.
Definition at line 64 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 64 of file GlobalVertex.h
Referenced by ResonanceJetTagging::addClusters(), cemcReco::calculateTSP(), BbcCheck::CheckDST(), cemcReco::coneSum(), PhotonJet::ConeSum(), MinimumBiasClassifier::FillMinimumBiasInfo(), TrkrNtuplizer::fillOutputNtuples(), CaloEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), KFParticle_truthAndDetTools::fillTruthBranch(), TowerJetInput::get_input(), ClusterJetInput::get_input(), FullJetFinder::GetDistanceFromVertexXY(), AnaTutorial::getEMCalClusters(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), MultiDetectorMultiplicity::isVertexAccepted(), CaloEvaluator::printOutputInfo(), RawClusterZVertexRecorrect::process_event(), RawClusterBuilderTemplate::process_event(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), ClusterIso::process_event(), Forward_pi0s::process_event(), Photons::process_event(), PJTranslator::process_event(), Pi0MassAnalysis::process_event(), CaloCalibEmc_Pi0::process_event(), isoCluster::process_event(), singlePhotonClusterAna::process_event(), pi0ClusterAna::process_event(), PhotonJet::process_event(), pythiaEMCalAna::process_event(), pi0Efficiency::process_event(), MyJetAnalysis::process_event(), JetBkgdSub::process_event(), cemcReco::process_event(), sPHAnalysis::process_event_notracking(), PairMaker::process_event_test(), sPHAnalysis_calo::process_event_test(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), CaloAna::process_towers(), CaloValid::process_towers(), pi0EtaByEta::process_towers(), and PHFlowJetMaker::run_particle_flow().
void GlobalVertex::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in GlobalVertexv2, and GlobalVertexv1.
Definition at line 40 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 40 of file GlobalVertex.h
References os.
Referenced by GlobalVertexReco::process_event().
virtual void GlobalVertex::insert_vtx (VTXTYPE , const Vertex *) inline virtual
Reimplemented in GlobalVertexv2.
Definition at line 86 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 86 of file GlobalVertex.h
Referenced by GlobalVertexReco::process_event().
virtual void GlobalVertex::insert_vtxids (VTXTYPE , unsigned int) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 108 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 108 of file GlobalVertex.h
int GlobalVertex::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in GlobalVertexv2, and GlobalVertexv1.
Definition at line 44 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 44 of file GlobalVertex.h
Referenced by MinimumBiasClassifier::FillMinimumBiasInfo().
virtual void GlobalVertex::set_beam_crossing (unsigned int) inline virtual
Reimplemented in GlobalVertexv2.
Definition at line 80 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 80 of file GlobalVertex.h
virtual void GlobalVertex::set_chisq (float) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 68 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 68 of file GlobalVertex.h
virtual void GlobalVertex::set_error (unsigned int , unsigned int , float) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 77 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 77 of file GlobalVertex.h
Referenced by GlobalVertexFastSimReco::process_event().
virtual void GlobalVertex::set_id (unsigned int) inline virtual
Reimplemented in GlobalVertexv1, and GlobalVertexv2.
Definition at line 50 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 50 of file GlobalVertex.h
Referenced by GlobalVertexReco::process_event().
virtual void GlobalVertex::set_ndof (unsigned int) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 71 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 71 of file GlobalVertex.h
virtual void GlobalVertex::set_position (unsigned int , float) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 74 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 74 of file GlobalVertex.h
virtual void GlobalVertex::set_t (float) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 53 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 53 of file GlobalVertex.h
Referenced by GlobalVertexFastSimReco::process_event().
virtual void GlobalVertex::set_t_err (float) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 56 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 56 of file GlobalVertex.h
Referenced by GlobalVertexFastSimReco::process_event().
virtual void GlobalVertex::set_x (float) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 59 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 59 of file GlobalVertex.h
Referenced by GlobalVertexFastSimReco::process_event().
virtual void GlobalVertex::set_y (float) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 62 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 62 of file GlobalVertex.h
Referenced by GlobalVertexFastSimReco::process_event().
virtual void GlobalVertex::set_z (float) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 65 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 65 of file GlobalVertex.h
Referenced by GlobalVertexFastSimReco::process_event().
virtual size_t GlobalVertex::size_vtxids () const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 104 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 104 of file GlobalVertex.h
virtual size_t GlobalVertex::size_vtxs () const inline virtual
Reimplemented in GlobalVertexv2.
Definition at line 83 of file GlobalVertex.h.
View newest version in sPHENIX GitHub at line 83 of file GlobalVertex.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/globalvertex/GlobalVertex.h
coresoftware/blob/master/offline/packages/globalvertex/GlobalVertex.cc