Analysis Software: CDBInterface Class Reference
CDBInterface Class Reference
#include <coresoftware/blob/master/offline/framework/ffamodules/CDBInterface.h>
Public Member Functions
~CDBInterface () override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void Print (const std::string &what="ALL") const override
std::string getUrl (const std::string &domain, const std::string &filename="")
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int InitRun (PHCompositeNode *)
virtual int process_event (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Static Public Member Functions
static CDBInterface * instance ()
Private Member Functions
CDBInterface (const std::string &name="CDBInterface")
Private Attributes
SphenixClient * cdbclient = nullptr
std::set< std::tuple
< std::string, std::string,
uint64_t > > m_UrlVector
Static Private Attributes
static CDBInterface * __instance = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 16 of file CDBInterface.h.
View newest version in sPHENIX GitHub at line 16 of file CDBInterface.h
Constructor & Destructor Documentation
CDBInterface::~CDBInterface () override
Definition at line 50 of file CDBInterface.cc.
View newest version in sPHENIX GitHub at line 50 of file CDBInterface.cc
References cdbclient.
CDBInterface::CDBInterface (const std::string & name = "CDBInterface") private
Definition at line 41 of file CDBInterface.cc.
View newest version in sPHENIX GitHub at line 41 of file CDBInterface.cc
References Fun4AllServer::addNewSubsystem(), and Fun4AllServer::instance().
Referenced by instance().
Member Function Documentation
int CDBInterface::End (PHCompositeNode * topNode) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 56 of file CDBInterface.cc.
View newest version in sPHENIX GitHub at line 56 of file CDBInterface.cc
References CdbUrlSave::AddUrl(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), CdbUrlSave::identify(), m_UrlVector, PHWHERE, and Fun4AllBase::Verbosity().
std::string CDBInterface::getUrl (const std::string & domain, const std::string & filename = "")
Definition at line 116 of file CDBInterface.cc.
View newest version in sPHENIX GitHub at line 116 of file CDBInterface.cc
References cdbclient, filename, PHFlag::FlagExist(), PHFlag::get_StringFlag(), PHFlag::get_uint64Flag(), SphenixClient::getCalibration(), recoConsts::instance(), m_UrlVector, std::tr1::make_tuple(), PHWHERE, CDB::timestamp, and Fun4AllBase::Verbosity().
Referenced by MakeActsGeometry::buildActsSurfaces(), CaloGeomMapping::CreateGeomNode(), createLocalEMCalCalibFile(), AlignmentTransformation::createMap(), MbdCalib::Download_All(), EMCalDeadmap(), Fun4All_CaloProduction_PreQM23(), Fun4All_TrkrClusteringSeeding(), Fun4All_TrkrHitSet_Unpacker(), Fun4All_Year1(), TpcCombinedRawDataUnpacker::Init(), TpcRawDataDecoder::Init(), CaloWaveformSim::Init(), PHG4Reco::InitField(), CaloWaveformProcessing::initialize_processing(), RawClusterPositionCorrection::InitRun(), CentralityReco::InitRun(), CaloTowerStatus::InitRun(), CaloTowerCalib::InitRun(), DeadHotMapLoader::InitRun(), RawTowerDigitizer::InitRun(), MvtxCombinedRawDataDecoder::InitRun(), KFParticle_sPHENIX::InitRun(), PHG4InnerHcalSteppingAction::InitWithNode(), PHG4OuterHcalSteppingAction::InitWithNode(), LightCollectionModel::load_data_from_CDB(), InttMaskedChannelSet::LoadFromCDB(), InttSurveyMap::LoadFromCDB(), InttCombinedRawDataDecoder::LoadHotChannelMapRemote(), CaloRecoUtility::LoadProfile(), RawClusterBuilderTemplate::LoadProfile(), RawTowerCalibration::process_event(), PHParameters::ReadFromCDB(), TestCDBRead(), and TestCDBSubsysReco().
CDBInterface * CDBInterface::instance () static
Definition at line 30 of file CDBInterface.cc.
View newest version in sPHENIX GitHub at line 30 of file CDBInterface.cc
References __instance, and CDBInterface().
Referenced by MakeActsGeometry::buildActsSurfaces(), CaloGeomMapping::CreateGeomNode(), createLocalEMCalCalibFile(), AlignmentTransformation::createMap(), MbdCalib::Download_All(), EMCalDeadmap(), Fun4All_CaloProduction(), Fun4All_CaloProduction_PreQM23(), Fun4All_HCalCalib(), Fun4All_HCalCalib_sim(), Fun4All_TrkrClusteringSeeding(), Fun4All_TrkrHitSet_Unpacker(), Fun4All_Year1(), TpcCombinedRawDataUnpacker::Init(), TpcRawDataDecoder::Init(), CaloWaveformSim::Init(), PHG4Reco::InitField(), CaloWaveformProcessing::initialize_processing(), RawClusterPositionCorrection::InitRun(), CentralityReco::InitRun(), CaloTowerCalib::InitRun(), CaloTowerStatus::InitRun(), DeadHotMapLoader::InitRun(), RawTowerDigitizer::InitRun(), MvtxCombinedRawDataDecoder::InitRun(), KFParticle_sPHENIX::InitRun(), PHG4OuterHcalSteppingAction::InitWithNode(), PHG4InnerHcalSteppingAction::InitWithNode(), LightCollectionModel::load_data_from_CDB(), InttMaskedChannelSet::LoadFromCDB(), InttSurveyMap::LoadFromCDB(), InttCombinedRawDataDecoder::LoadHotChannelMapRemote(), CaloRecoUtility::LoadProfile(), RawClusterBuilderTemplate::LoadProfile(), RawTowerCalibration::process_event(), PHParameters::ReadFromCDB(), TestCDBRead(), and TestCDBSubsysReco().
void CDBInterface::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 106 of file CDBInterface.cc.
View newest version in sPHENIX GitHub at line 106 of file CDBInterface.cc
References m_UrlVector.
Referenced by Fun4All_CaloProduction(), Fun4All_HCalCalib(), Fun4All_HCalCalib_sim(), Fun4All_Year1(), and TestCDBSubsysReco().
Member Data Documentation
CDBInterface * CDBInterface::__instance = nullptr static private
Definition at line 33 of file CDBInterface.h.
View newest version in sPHENIX GitHub at line 33 of file CDBInterface.h
Referenced by instance().
SphenixClient* CDBInterface::cdbclient = nullptr private
Definition at line 34 of file CDBInterface.h.
View newest version in sPHENIX GitHub at line 34 of file CDBInterface.h
Referenced by getUrl(), and ~CDBInterface().
std::set<std::tuple<std::string, std::string, uint64_t> > CDBInterface::m_UrlVector private
Definition at line 35 of file CDBInterface.h.
View newest version in sPHENIX GitHub at line 35 of file CDBInterface.h
Referenced by End(), getUrl(), and Print().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/ffamodules/CDBInterface.h
coresoftware/blob/master/offline/framework/ffamodules/CDBInterface.cc