Analysis Software: MbdDigitization Class Reference
MbdDigitization Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4bbc/MbdDigitization.h>
Public Member Functions
MbdDigitization (const std::string &name="MbdDigitization")
~MbdDigitization () override
int Init (PHCompositeNode *) override
Initialization, called for at overall initialization.
int InitRun (PHCompositeNode *) override
Initialization at start of every run.
int process_event (PHCompositeNode *) override
Process Event, called for each event.
int End (PHCompositeNode *) override
Reset after every event.
void set_tres (const Float_t tr)
Set time resolution (each channel has same time resol)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CreateNodes (PHCompositeNode *topNode)
void GetNodes (PHCompositeNode *)
Private Attributes
Float_t f_vx = NAN
Float_t f_vy = NAN
Float_t f_vz = NAN
Float_t f_vt = NAN
Float_t f_pmtq [128] {}
Float_t f_pmtt0 [128] {}
Float_t f_pmtt1 [128] {}
TF1 * gaussian = nullptr
TDatabasePDG * _pdg = nullptr
gsl_rng * m_RandomGenerator = nullptr
unsigned int m_Seed = 0
Float_t _tres = NAN
std::map< int, int > _pids
PHG4TruthInfoContainer * _truth_container {nullptr}
PHG4HitContainer * _bbchits {nullptr}
MbdPmtContainer * _bbcpmts {nullptr}
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 26 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 26 of file MbdDigitization.h
Constructor & Destructor Documentation
MbdDigitization::MbdDigitization (const std::string & name = "MbdDigitization")
Definition at line 42 of file MbdDigitization.cc.
View newest version in sPHENIX GitHub at line 42 of file MbdDigitization.cc
References parse_cmake_options::begin, end, f_pmtq, f_pmtt0, f_pmtt1, gsl_rng_set(), m_RandomGenerator, and m_Seed.
MbdDigitization::~MbdDigitization () override
Definition at line 54 of file MbdDigitization.cc.
View newest version in sPHENIX GitHub at line 54 of file MbdDigitization.cc
References m_RandomGenerator.
Member Function Documentation
void MbdDigitization::CreateNodes (PHCompositeNode * topNode) private
Definition at line 234 of file MbdDigitization.cc.
View newest version in sPHENIX GitHub at line 234 of file MbdDigitization.cc
References _bbcpmts, PHCompositeNode::addNode(), PHNodeIterator::findFirst(), and PHWHERE.
Referenced by Init().
int MbdDigitization::End (PHCompositeNode *) inline override virtual
Reset after every event.
End, write and close files
Reimplemented from SubsysReco.
Definition at line 47 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 47 of file MbdDigitization.h
void MbdDigitization::GetNodes (PHCompositeNode * topNode) private
DST Objects
Definition at line 263 of file MbdDigitization.cc.
View newest version in sPHENIX GitHub at line 263 of file MbdDigitization.cc
References _bbchits, _bbcpmts, _truth_container, and PHWHERE.
Referenced by InitRun().
int MbdDigitization::Init (PHCompositeNode * topNode) override virtual
Initialization, called for at overall initialization.
Reimplemented from SubsysReco.
Definition at line 61 of file MbdDigitization.cc.
View newest version in sPHENIX GitHub at line 61 of file MbdDigitization.cc
References _pdg, _tres, CreateNodes(), gaussian, PHWHERE, and Fun4AllBase::Verbosity().
int MbdDigitization::InitRun (PHCompositeNode * topNode) override virtual
Initialization at start of every run.
Reimplemented from SubsysReco.
Definition at line 75 of file MbdDigitization.cc.
View newest version in sPHENIX GitHub at line 75 of file MbdDigitization.cc
References GetNodes().
int MbdDigitization::process_event (PHCompositeNode *) override virtual
Process Event, called for each event.
Reimplemented from SubsysReco.
Definition at line 84 of file MbdDigitization.cc.
View newest version in sPHENIX GitHub at line 84 of file MbdDigitization.cc
References _bbchits, _bbcpmts, _pdg, _pids, _tres, _truth_container, charge(), f_pmtq, f_pmtt0, f_pmtt1, f_vt, f_vx, f_vy, f_vz, PHG4Particle::get_e(), PHG4Hit::get_edep(), PHG4Particle::get_IonCharge(), PHG4Hit::get_layer(), PHG4Hit::get_path_length(), PHG4Particle::get_pid(), MbdPmtContainer::get_pmt(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4VtxPoint::get_t(), PHG4Hit::get_t(), PHG4Hit::get_trkid(), PHG4VtxPoint::get_x(), PHG4VtxPoint::get_y(), PHG4VtxPoint::get_z(), PHG4HitContainer::getHits(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetPrimaryVertexIndex(), PHG4TruthInfoContainer::GetPrimaryVtx(), PHG4Particle::isIon(), m_RandomGenerator, MbdDefs::MBD_N_PMT, PHWHERE, train_ambiguity_solver::pid, MbdPmtHit::set_pmt(), v4, MbdDefs::v_ckov, and Fun4AllBase::Verbosity().
void MbdDigitization::set_tres (const Float_t tr) inline
Set time resolution (each channel has same time resol)
Definition at line 50 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 50 of file MbdDigitization.h
References _tres.
Member Data Documentation
PHG4HitContainer* MbdDigitization::_bbchits {nullptr} private
Definition at line 76 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 76 of file MbdDigitization.h
Referenced by GetNodes(), and process_event().
MbdPmtContainer* MbdDigitization::_bbcpmts {nullptr} private
Definition at line 79 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 79 of file MbdDigitization.h
Referenced by CreateNodes(), GetNodes(), and process_event().
TDatabasePDG* MbdDigitization::_pdg = nullptr private
Definition at line 67 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 67 of file MbdDigitization.h
Referenced by Init(), and process_event().
std::map<int, int> MbdDigitization::_pids private
Definition at line 72 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 72 of file MbdDigitization.h
Referenced by process_event().
Float_t MbdDigitization::_tres = NAN private
Definition at line 70 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 70 of file MbdDigitization.h
Referenced by Init(), process_event(), and set_tres().
PHG4TruthInfoContainer* MbdDigitization::_truth_container {nullptr} private
Definition at line 75 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 75 of file MbdDigitization.h
Referenced by GetNodes(), and process_event().
Float_t MbdDigitization::f_pmtq[128] {} private
Definition at line 60 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 60 of file MbdDigitization.h
Referenced by MbdDigitization(), and process_event().
Float_t MbdDigitization::f_pmtt0[128] {} private
Definition at line 61 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 61 of file MbdDigitization.h
Referenced by MbdDigitization(), and process_event().
Float_t MbdDigitization::f_pmtt1[128] {} private
Definition at line 62 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 62 of file MbdDigitization.h
Referenced by MbdDigitization(), and process_event().
Float_t MbdDigitization::f_vt = NAN private
Definition at line 59 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 59 of file MbdDigitization.h
Referenced by process_event().
Float_t MbdDigitization::f_vx = NAN private
Definition at line 56 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 56 of file MbdDigitization.h
Referenced by process_event().
Float_t MbdDigitization::f_vy = NAN private
Definition at line 57 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 57 of file MbdDigitization.h
Referenced by process_event().
Float_t MbdDigitization::f_vz = NAN private
Definition at line 58 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 58 of file MbdDigitization.h
Referenced by process_event().
TF1* MbdDigitization::gaussian = nullptr private
Definition at line 64 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 64 of file MbdDigitization.h
Referenced by Init().
gsl_rng* MbdDigitization::m_RandomGenerator = nullptr private
Definition at line 68 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 68 of file MbdDigitization.h
Referenced by MbdDigitization(), process_event(), and ~MbdDigitization().
unsigned int MbdDigitization::m_Seed = 0 private
Definition at line 69 of file MbdDigitization.h.
View newest version in sPHENIX GitHub at line 69 of file MbdDigitization.h
Referenced by MbdDigitization().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4bbc/MbdDigitization.h
coresoftware/blob/master/simulation/g4simulation/g4bbc/MbdDigitization.cc