Analysis Software: PHG4Cell Class Reference
PHG4Cell Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4Cell.h>
Public Types
enum PROPERTY {
prop_stave_index = 1, prop_half_stave_index = 2, prop_module_index = 3, prop_chip_index = 4,
prop_pixel_index = 5, prop_phibin = 6, prop_zbin = 7, prop_ladder_z_index = 8,
prop_ladder_phi_index = 9, prop_edep = 21, prop_eion = 22, prop_light_yield = 23,
prop_raw_light_yield = 24, prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
typedef std::map
< PHG4HitDefs::keytype, float > EdepMap
typedef EdepMap::iterator EdepIterator
typedef EdepMap::const_iterator EdepConstIterator
typedef std::pair
< EdepIterator, EdepIterator > EdepRange
typedef std::pair
< EdepConstIterator,
EdepConstIterator > EdepConstRange
typedef std::map< int, float > ShowerEdepMap
typedef ShowerEdepMap::iterator ShowerEdepIterator
typedef
ShowerEdepMap::const_iterator ShowerEdepConstIterator
typedef std::pair
< ShowerEdepIterator,
ShowerEdepIterator > ShowerEdepRange
typedef std::pair
< ShowerEdepConstIterator,
ShowerEdepConstIterator > ShowerEdepConstRange
Public Member Functions
~PHG4Cell () override
void identify (std::ostream &os=std::cout) const override
void CopyFrom (const PHObject *phobj) override
void Reset () override
Clear Event.
virtual void set_cellid (const PHG4CellDefs::keytype)
virtual PHG4CellDefs::keytype get_cellid () const
virtual bool has_binning (const PHG4CellDefs::CellBinning) const
virtual void add_edep (const PHG4HitDefs::keytype, const float)
virtual void add_edep (const PHG4HitDefs::keytype, const float, const float)
virtual void add_edep (const PHG4HitDefs::keytype, const int, const float)
virtual void add_shower_edep (const int, const float)
virtual EdepConstRange get_g4hits ()
virtual ShowerEdepConstRange get_g4showers ()
virtual short int get_detid () const
short int get_layer () const
virtual void add_edep (const float)
virtual double get_edep () const
virtual void add_eion (const float)
virtual double get_eion () const
virtual void add_light_yield (const float)
virtual float get_light_yield () const
virtual void add_raw_light_yield (const float)
virtual float get_raw_light_yield () const
virtual void set_chip_index (const int)
virtual int get_chip_index () const
virtual void set_half_stave_index (const int)
virtual int get_half_stave_index () const
virtual void set_ladder_phi_index (const int)
virtual int get_ladder_phi_index () const
virtual void set_ladder_z_index (const int)
virtual int get_ladder_z_index () const
virtual void set_module_index (const int)
virtual int get_module_index () const
virtual void set_phibin (const int)
virtual int get_phibin () const
virtual void set_pixel_index (const int)
virtual int get_pixel_index () const
virtual void set_stave_index (const int)
virtual int get_stave_index () const
virtual void set_zbin (const int)
virtual int get_zbin () const
virtual void print () const
virtual bool has_property (const PROPERTY) const
virtual float get_property_float (const PROPERTY) const
virtual int get_property_int (const PROPERTY) const
virtual unsigned int get_property_uint (const PROPERTY) const
virtual void set_property (const PROPERTY, const float)
virtual void set_property (const PROPERTY, const int)
virtual void set_property (const PROPERTY, const unsigned int)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
Static Public Member Functions
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Protected Member Functions
PHG4Cell ()
virtual unsigned int get_property_nocheck (const PROPERTY) const
virtual void set_property_nocheck (const PROPERTY, const unsigned int)
Friends
std::ostream & operator<< (std::ostream &stream, const PHG4Cell *cell)
Detailed Description
Definition at line 19 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4Cell.h
Member Typedef Documentation
typedef EdepMap::const_iterator PHG4Cell::EdepConstIterator
Definition at line 24 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 24 of file PHG4Cell.h
typedef std::pair<EdepConstIterator, EdepConstIterator> PHG4Cell::EdepConstRange
Definition at line 26 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 26 of file PHG4Cell.h
typedef EdepMap::iterator PHG4Cell::EdepIterator
Definition at line 23 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4Cell.h
typedef std::map<PHG4HitDefs::keytype, float> PHG4Cell::EdepMap
Definition at line 22 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 22 of file PHG4Cell.h
typedef std::pair<EdepIterator, EdepIterator> PHG4Cell::EdepRange
Definition at line 25 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 25 of file PHG4Cell.h
typedef ShowerEdepMap::const_iterator PHG4Cell::ShowerEdepConstIterator
Definition at line 30 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4Cell.h
typedef std::pair<ShowerEdepConstIterator, ShowerEdepConstIterator> PHG4Cell::ShowerEdepConstRange
Definition at line 32 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4Cell.h
typedef ShowerEdepMap::iterator PHG4Cell::ShowerEdepIterator
Definition at line 29 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 29 of file PHG4Cell.h
typedef std::map<int, float> PHG4Cell::ShowerEdepMap
Definition at line 28 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4Cell.h
typedef std::pair<ShowerEdepIterator, ShowerEdepIterator> PHG4Cell::ShowerEdepRange
Definition at line 31 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4Cell.h
Member Enumeration Documentation
enum PHG4Cell::PROPERTY
Procedure to add a new PROPERTY tag: 1.add new tag below with unique value, 2.add a short name to PHG4Cell::get_property_info
Enumerator:
prop_stave_index
Maps coordinates.
prop_half_stave_index
prop_module_index
prop_chip_index
prop_pixel_index
prop_phibin
prop_zbin
prop_ladder_z_index
prop_ladder_phi_index
prop_edep
deposited energy
prop_eion
ionizing energy loss
prop_light_yield
for scintillation detectors, the amount of light produced
prop_raw_light_yield
for scintillation detectors, the amount of light produced
prop_MAX_NUMBER
max limit in order to fit into 8 bit unsigned number
Definition at line 112 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 112 of file PHG4Cell.h
enum PHG4Cell::PROPERTY_TYPE
Enumerator:
type_int
type_uint
type_float
type_unknown
Definition at line 141 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 141 of file PHG4Cell.h
Constructor & Destructor Documentation
PHG4Cell::~PHG4Cell () inline override
Definition at line 34 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4Cell.h
PHG4Cell::PHG4Cell () inline protected
Definition at line 161 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 161 of file PHG4Cell.h
Member Function Documentation
virtual void PHG4Cell::add_edep (const PHG4HitDefs::keytype , const float) inline virtual
Reimplemented in PHG4Cellv1, and PHG4CylinderCellv1.
Definition at line 50 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4Cell.h
Referenced by PHG4HcalCellReco::process_event(), PHG4CylinderCellReco::process_event(), and PHG4FullProjSpacalCellReco::process_event().
virtual void PHG4Cell::add_edep (const PHG4HitDefs::keytype , const float , const float) inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 51 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4Cell.h
virtual void PHG4Cell::add_edep (const PHG4HitDefs::keytype , const int , const float) inline virtual
Definition at line 52 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4Cell.h
virtual void PHG4Cell::add_edep (const float) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 64 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4Cell.h
virtual void PHG4Cell::add_eion (const float) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 67 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4Cell.h
Referenced by PHG4HcalCellReco::process_event().
virtual void PHG4Cell::add_light_yield (const float) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 70 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4Cell.h
Referenced by PHG4HcalCellReco::process_event(), PHG4CylinderCellReco::process_event(), and PHG4FullProjSpacalCellReco::process_event().
virtual void PHG4Cell::add_raw_light_yield (const float) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 73 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4Cell.h
Referenced by PHG4HcalCellReco::process_event().
virtual void PHG4Cell::add_shower_edep (const int , const float) inline virtual
Reimplemented in PHG4CylinderCellv1, and PHG4Cellv1.
Definition at line 54 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4Cell.h
Referenced by PHG4CylinderCellReco::process_event(), and PHG4FullProjSpacalCellReco::process_event().
bool PHG4Cell::check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type) static
Definition at line 92 of file PHG4Cell.cc.
View newest version in sPHENIX GitHub at line 92 of file PHG4Cell.cc
References get_property_info().
Referenced by PHG4Cellv1::add_property(), PHG4Cellv1::get_property_float(), PHG4Cellv1::get_property_int(), PHG4Cellv1::get_property_uint(), and PHG4Cellv1::set_property().
void PHG4Cell::CopyFrom (const PHObject * phobj) override virtual
Reimplemented from PHObject.
Definition at line 10 of file PHG4Cell.cc.
View newest version in sPHENIX GitHub at line 10 of file PHG4Cell.cc
References assert, get_cellid(), get_property_nocheck(), has_property(), set_cellid(), and set_property_nocheck().
virtual PHG4CellDefs::keytype PHG4Cell::get_cellid () const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 46 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4Cell.h
Referenced by PHG4CellContainer::AddCell(), CopyFrom(), RawTowerBuilder::process_event(), TPCIntegratedCharge::process_event(), HcalRawTowerBuilder::process_event(), HCalib::process_event(), and TPCDataStreamEmulator::process_event().
virtual int PHG4Cell::get_chip_index () const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 79 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4Cell.h
Referenced by BDiJetModule::MakeGenFitTrack(), HFMLTriggerOccupancy::process_event(), and HFMLTriggerInterface::process_event().
virtual short int PHG4Cell::get_detid () const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 60 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4Cell.h
Referenced by get_layer().
virtual double PHG4Cell::get_edep () const inline virtual
Reimplemented in PHG4Cellv1, and PHG4CylinderCellv1.
Definition at line 65 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4Cell.h
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), RawTowerBuilder::process_event(), TPCIntegratedCharge::process_event(), HcalRawTowerBuilder::process_event(), and PHG4CylinderCellReco::process_event().
virtual double PHG4Cell::get_eion () const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 68 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4Cell.h
Referenced by TPCIntegratedCharge::process_event(), and HcalRawTowerBuilder::process_event().
PHG4Cell::EdepConstRange PHG4Cell::get_g4hits () virtual
Reimplemented in PHG4Cellv1, and PHG4CylinderCellv1.
Definition at line 37 of file PHG4Cell.cc.
View newest version in sPHENIX GitHub at line 37 of file PHG4Cell.cc
References dummy.
Referenced by CaloRawTowerEval::all_truth_hits().
PHG4Cell::ShowerEdepConstRange PHG4Cell::get_g4showers () virtual
Reimplemented in PHG4Cellv1, and PHG4CylinderCellv1.
Definition at line 43 of file PHG4Cell.cc.
View newest version in sPHENIX GitHub at line 43 of file PHG4Cell.cc
References dummy.
Referenced by RawTowerBuilder::process_event(), and HcalRawTowerBuilder::process_event().
virtual int PHG4Cell::get_half_stave_index () const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 82 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 82 of file PHG4Cell.h
Referenced by BDiJetModule::MakeGenFitTrack(), HFMLTriggerOccupancy::process_event(), and HFMLTriggerInterface::process_event().
virtual int PHG4Cell::get_ladder_phi_index () const inline virtual
Reimplemented in PHG4Cellv1, PHG4CylinderCell, and PHG4CylinderCellv2.
Definition at line 85 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 85 of file PHG4Cell.h
Referenced by BDiJetModule::MakeGenFitTrack().
virtual int PHG4Cell::get_ladder_z_index () const inline virtual
Reimplemented in PHG4Cellv1, PHG4CylinderCell, and PHG4CylinderCellv2.
Definition at line 88 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 88 of file PHG4Cell.h
Referenced by BDiJetModule::MakeGenFitTrack().
short int PHG4Cell::get_layer () const inline
Definition at line 62 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4Cell.h
References get_detid().
Referenced by TPCIntegratedCharge::process_event().
virtual float PHG4Cell::get_light_yield () const inline virtual
Reimplemented in PHG4Cellv1, and PHG4CylinderCellv1.
Definition at line 71 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 71 of file PHG4Cell.h
Referenced by RawTowerBuilder::process_event(), HcalRawTowerBuilder::process_event(), HCalib::process_event(), and PHG4FullProjSpacalCellReco::process_event().
virtual int PHG4Cell::get_module_index () const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 91 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 91 of file PHG4Cell.h
Referenced by BDiJetModule::MakeGenFitTrack(), HFMLTriggerOccupancy::process_event(), and HFMLTriggerInterface::process_event().
virtual int PHG4Cell::get_phibin () const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 94 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 94 of file PHG4Cell.h
virtual int PHG4Cell::get_pixel_index () const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 97 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 97 of file PHG4Cell.h
Referenced by HFMLTriggerInterface::process_event(), and HFMLTriggerOccupancy::process_event().
virtual float PHG4Cell::get_property_float (const PROPERTY) const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 150 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 150 of file PHG4Cell.h
std::pair< const std::string, PHG4Cell::PROPERTY_TYPE > PHG4Cell::get_property_info (PROPERTY prop_id) static
Definition at line 56 of file PHG4Cell.cc.
View newest version in sPHENIX GitHub at line 56 of file PHG4Cell.cc
References prop_chip_index, prop_edep, prop_eion, prop_half_stave_index, prop_ladder_phi_index, prop_ladder_z_index, prop_light_yield, prop_module_index, prop_phibin, prop_pixel_index, prop_raw_light_yield, prop_stave_index, prop_zbin, type_float, and type_int.
Referenced by PHG4Cellv1::add_property(), check_property(), PHG4Cellv1::get_property_float(), PHG4Cellv1::get_property_int(), PHG4Cellv1::get_property_uint(), PHG4Cellv1::identify(), DumpPHG4CellContainer::process_Node(), and PHG4Cellv1::set_property().
virtual int PHG4Cell::get_property_int (const PROPERTY) const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 151 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 151 of file PHG4Cell.h
virtual unsigned int PHG4Cell::get_property_nocheck (const PROPERTY) const inline protected virtual
Reimplemented in PHG4Cellv1.
Definition at line 162 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 162 of file PHG4Cell.h
Referenced by CopyFrom().
std::string PHG4Cell::get_property_type (const PROPERTY_TYPE prop_type) static
Definition at line 102 of file PHG4Cell.cc.
View newest version in sPHENIX GitHub at line 102 of file PHG4Cell.cc
References type_float, type_int, and type_uint.
Referenced by PHG4Cellv1::add_property(), PHG4Cellv1::get_property_float(), PHG4Cellv1::get_property_int(), PHG4Cellv1::get_property_uint(), and PHG4Cellv1::set_property().
virtual unsigned int PHG4Cell::get_property_uint (const PROPERTY) const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 152 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 152 of file PHG4Cell.h
virtual float PHG4Cell::get_raw_light_yield () const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 74 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4Cell.h
Referenced by HcalRawTowerBuilder::process_event().
virtual int PHG4Cell::get_stave_index () const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 100 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 100 of file PHG4Cell.h
Referenced by BDiJetModule::MakeGenFitTrack(), HFMLTriggerOccupancy::process_event(), and HFMLTriggerInterface::process_event().
virtual int PHG4Cell::get_zbin () const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 105 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 105 of file PHG4Cell.h
virtual bool PHG4Cell::has_binning (const PHG4CellDefs::CellBinning) const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 47 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4Cell.h
Referenced by RawTowerBuilder::process_event().
virtual bool PHG4Cell::has_property (const PROPERTY) const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 149 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 149 of file PHG4Cell.h
Referenced by CopyFrom().
void PHG4Cell::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHG4Cellv1, PHG4CylinderCell, PHG4CylinderCellv1, PHG4CylinderCellv2, and PHG4CylinderCellv3.
Definition at line 25 of file PHG4Cell.cc.
View newest version in sPHENIX GitHub at line 25 of file PHG4Cell.cc
Referenced by RawTowerBuilder::process_event(), and TPCIntegratedCharge::process_event().
virtual void PHG4Cell::print () const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 107 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 107 of file PHG4Cell.h
void PHG4Cell::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in PHG4Cellv1.
Definition at line 49 of file PHG4Cell.cc.
View newest version in sPHENIX GitHub at line 49 of file PHG4Cell.cc
virtual void PHG4Cell::set_cellid (const PHG4CellDefs::keytype) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 44 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4Cell.h
Referenced by PHG4CellContainer::AddCellSpecifyKey(), CopyFrom(), and PHG4CellContainer::findOrAddCell().
virtual void PHG4Cell::set_chip_index (const int) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 78 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4Cell.h
virtual void PHG4Cell::set_half_stave_index (const int) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 81 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 81 of file PHG4Cell.h
virtual void PHG4Cell::set_ladder_phi_index (const int) inline virtual
Reimplemented in PHG4Cellv1, PHG4CylinderCell, and PHG4CylinderCellv2.
Definition at line 84 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 84 of file PHG4Cell.h
virtual void PHG4Cell::set_ladder_z_index (const int) inline virtual
Reimplemented in PHG4Cellv1, PHG4CylinderCell, and PHG4CylinderCellv2.
Definition at line 87 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 87 of file PHG4Cell.h
virtual void PHG4Cell::set_module_index (const int) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 90 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 90 of file PHG4Cell.h
virtual void PHG4Cell::set_phibin (const int) inline virtual
Reimplemented in PHG4Cellv1, and PHG4CylinderCellv1.
Definition at line 93 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 93 of file PHG4Cell.h
virtual void PHG4Cell::set_pixel_index (const int) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 96 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 96 of file PHG4Cell.h
virtual void PHG4Cell::set_property (const PROPERTY , const float) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 153 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 153 of file PHG4Cell.h
virtual void PHG4Cell::set_property (const PROPERTY , const int) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 154 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 154 of file PHG4Cell.h
virtual void PHG4Cell::set_property (const PROPERTY , const unsigned int) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 155 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 155 of file PHG4Cell.h
virtual void PHG4Cell::set_property_nocheck (const PROPERTY , const unsigned int) inline protected virtual
Reimplemented in PHG4Cellv1.
Definition at line 163 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 163 of file PHG4Cell.h
Referenced by CopyFrom().
virtual void PHG4Cell::set_stave_index (const int) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 99 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 99 of file PHG4Cell.h
virtual void PHG4Cell::set_zbin (const int) inline virtual
Reimplemented in PHG4Cellv1, and PHG4CylinderCellv1.
Definition at line 104 of file PHG4Cell.h.
View newest version in sPHENIX GitHub at line 104 of file PHG4Cell.h
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & stream, const PHG4Cell * cell) friend
Definition at line 31 of file PHG4Cell.cc.
View newest version in sPHENIX GitHub at line 31 of file PHG4Cell.cc
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4Cell.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4Cell.cc