Analysis Software: sigslot::has_slots< mt_policy > Class Template Reference
sigslot::has_slots< mt_policy > Class Template Reference
#include <JETSCAPE/blob/main/external_packages/sigslot.h>
Public Member Functions
has_slots ()
has_slots (const has_slots &hs)
void signal_connect (_signal_base< mt_policy > *sender)
void signal_disconnect (_signal_base< mt_policy > *sender)
virtual ~has_slots ()
void disconnect_all ()
Private Types
typedef std::set< _signal_base
< mt_policy > * > sender_set
typedef sender_set::const_iterator const_iterator
Private Attributes
sender_set m_senders
Detailed Description
template<class mt_policy = SIGSLOT_DEFAULT_MT_POLICY>
class sigslot::has_slots< mt_policy >
Definition at line 424 of file sigslot.h.
View newest version in sPHENIX GitHub at line 424 of file sigslot.h
Member Typedef Documentation
template<class mt_policy = SIGSLOT_DEFAULT_MT_POLICY> typedef sender_set::const_iterator sigslot::has_slots< mt_policy >::const_iterator private
Definition at line 428 of file sigslot.h.
View newest version in sPHENIX GitHub at line 428 of file sigslot.h
template<class mt_policy = SIGSLOT_DEFAULT_MT_POLICY> typedef std::set<_signal_base<mt_policy> *> sigslot::has_slots< mt_policy >::sender_set private
Definition at line 427 of file sigslot.h.
View newest version in sPHENIX GitHub at line 427 of file sigslot.h
Constructor & Destructor Documentation
template<class mt_policy = SIGSLOT_DEFAULT_MT_POLICY> sigslot::has_slots< mt_policy >::has_slots () inline
Definition at line 431 of file sigslot.h.
View newest version in sPHENIX GitHub at line 431 of file sigslot.h
template<class mt_policy = SIGSLOT_DEFAULT_MT_POLICY> sigslot::has_slots< mt_policy >::has_slots (const has_slots< mt_policy > & hs) inline
Definition at line 436 of file sigslot.h.
View newest version in sPHENIX GitHub at line 436 of file sigslot.h
template<class mt_policy = SIGSLOT_DEFAULT_MT_POLICY> virtual sigslot::has_slots< mt_policy >::~has_slots () inline virtual
Definition at line 463 of file sigslot.h.
View newest version in sPHENIX GitHub at line 463 of file sigslot.h
Member Function Documentation
template<class mt_policy = SIGSLOT_DEFAULT_MT_POLICY> void sigslot::has_slots< mt_policy >::disconnect_all () inline
Definition at line 468 of file sigslot.h.
View newest version in sPHENIX GitHub at line 468 of file sigslot.h
Referenced by sigslot::has_slots< sigslot::multi_threaded_local >::~has_slots().
template<class mt_policy = SIGSLOT_DEFAULT_MT_POLICY> void sigslot::has_slots< mt_policy >::signal_connect (_signal_base< mt_policy > * sender) inline
Definition at line 451 of file sigslot.h.
View newest version in sPHENIX GitHub at line 451 of file sigslot.h
template<class mt_policy = SIGSLOT_DEFAULT_MT_POLICY> void sigslot::has_slots< mt_policy >::signal_disconnect (_signal_base< mt_policy > * sender) inline
Definition at line 457 of file sigslot.h.
View newest version in sPHENIX GitHub at line 457 of file sigslot.h
Referenced by sigslot::_signal_base0< mt_policy >::disconnect(), sigslot::_signal_base1< vector< shared_ptr< Parton > > &, SIGSLOT_DEFAULT_MT_POLICY >::disconnect(), sigslot::_signal_base2< int, double, multi_threaded_local >::disconnect(), sigslot::_signal_base3< vector< vector< shared_ptr< Parton > > > &, vector< shared_ptr< Hadron > > &, vector< shared_ptr< Parton > > &, multi_threaded_local >::disconnect(), sigslot::_signal_base4< arg1_type, arg2_type, arg3_type, arg4_type, mt_policy >::disconnect(), sigslot::_signal_base5< double, double, double, vector< Parton > &, vector< Parton > &, multi_threaded_local >::disconnect(), sigslot::_signal_base6< arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, mt_policy >::disconnect(), sigslot::_signal_base7< arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::disconnect(), and sigslot::_signal_base8< arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, arg8_type, mt_policy >::disconnect().
Member Data Documentation
template<class mt_policy = SIGSLOT_DEFAULT_MT_POLICY> sender_set sigslot::has_slots< mt_policy >::m_senders private
Definition at line 484 of file sigslot.h.
View newest version in sPHENIX GitHub at line 484 of file sigslot.h
Referenced by sigslot::has_slots< sigslot::multi_threaded_local >::disconnect_all(), sigslot::has_slots< sigslot::multi_threaded_local >::has_slots(), sigslot::has_slots< sigslot::multi_threaded_local >::signal_connect(), and sigslot::has_slots< sigslot::multi_threaded_local >::signal_disconnect().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/sigslot.h