Analysis Software: Acts::SeedFinderFTF< external_spacepoint_t > Class Template Reference
Acts::SeedFinderFTF< external_spacepoint_t > Class Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Seeding/SeedFinderFTF.hpp>
Public Types
using seed_t = Seed< external_spacepoint_t >
Public Member Functions
SeedFinderFTF (const SeedFinderFTFConfig< external_spacepoint_t > &config, const TrigFTF_GNN_Geometry< external_spacepoint_t > &GNNgeo)
~SeedFinderFTF ()
SeedFinderFTF ()=default
!! is it dangerous not to use default? got def in ipp
SeedFinderFTF (const SeedFinderFTF< external_spacepoint_t > &)=delete
SeedFinderFTF
< external_spacepoint_t > & operator= (const SeedFinderFTF< external_spacepoint_t > &)=delete
void loadSpacePoints (const std::vector< FTF_SP< external_spacepoint_t >> &FTF_SP_vect)
void createSeeds (const Acts::RoiDescriptor &roi, const Acts::TrigFTF_GNN_Geometry< external_spacepoint_t > &gnngeo)
template<typename input_container_t , typename output_container_t , typename callable_t >
void createSeeds_old (const Acts::SeedFinderOptions &options, const input_container_t &spacePoints, output_container_t &out_cont, callable_t &&extract_coordinates) const
template<typename input_container_t , typename callable_t >
std::vector< seed_t > createSeeds_old (const Acts::SeedFinderOptions &options, const input_container_t &spacePoints, callable_t &&extract_coordinates) const
Static Public Attributes
static constexpr std::size_t NDims = 3
Private Types
enum Dim { DimPhi = 0, DimR = 1, DimZ = 2 }
Private Member Functions
void runGNN_TrackFinder (std::vector< GNN_TrigTracklet< external_spacepoint_t >> &vTracks, const Acts::RoiDescriptor &roi, const Acts::TrigFTF_GNN_Geometry< external_spacepoint_t > &gnngeo)
Private Attributes
SeedFinderFTFConfig
< external_spacepoint_t > m_config
TrigFTF_GNN_DataStorage
< external_spacepoint_t > * m_storage
std::vector< TrigInDetTriplet
< external_spacepoint_t > > m_triplets
Detailed Description
template<typename external_spacepoint_t>
class Acts::SeedFinderFTF< external_spacepoint_t >
Definition at line 45 of file SeedFinderFTF.hpp.
View newest version in sPHENIX GitHub at line 45 of file SeedFinderFTF.hpp
Member Typedef Documentation
template<typename external_spacepoint_t> using Acts::SeedFinderFTF< external_spacepoint_t >::seed_t = Seed<external_spacepoint_t>
Definition at line 49 of file SeedFinderFTF.hpp.
View newest version in sPHENIX GitHub at line 49 of file SeedFinderFTF.hpp
Member Enumeration Documentation
template<typename external_spacepoint_t> enum Acts::SeedFinderFTF::Dim private
Enumerator:
DimPhi
DimR
DimZ
Definition at line 84 of file SeedFinderFTF.hpp.
View newest version in sPHENIX GitHub at line 84 of file SeedFinderFTF.hpp
Constructor & Destructor Documentation
template<typename external_spacepoint_t > Acts::SeedFinderFTF< external_spacepoint_t >::SeedFinderFTF (const SeedFinderFTFConfig< external_spacepoint_t > & config, const TrigFTF_GNN_Geometry< external_spacepoint_t > & GNNgeo)
Definition at line 34 of file SeedFinderFTF.ipp.
View newest version in sPHENIX GitHub at line 34 of file SeedFinderFTF.ipp
References Acts::SeedFinderFTF< external_spacepoint_t >::m_storage.
template<typename external_spacepoint_t > Acts::SeedFinderFTF< external_spacepoint_t >::~SeedFinderFTF ()
Definition at line 42 of file SeedFinderFTF.ipp.
View newest version in sPHENIX GitHub at line 42 of file SeedFinderFTF.ipp
template<typename external_spacepoint_t> Acts::SeedFinderFTF< external_spacepoint_t >::SeedFinderFTF () default
!! is it dangerous not to use default? got def in ipp
template<typename external_spacepoint_t> Acts::SeedFinderFTF< external_spacepoint_t >::SeedFinderFTF (const SeedFinderFTF< external_spacepoint_t > &) delete
Member Function Documentation
template<typename external_spacepoint_t > void Acts::SeedFinderFTF< external_spacepoint_t >::createSeeds (const Acts::RoiDescriptor & roi, const Acts::TrigFTF_GNN_Geometry< external_spacepoint_t > & gnngeo)
Definition at line 665 of file SeedFinderFTF.ipp.
View newest version in sPHENIX GitHub at line 665 of file SeedFinderFTF.ipp
References seed.
Referenced by ActsExamples::SeedingFTFAlgorithm::execute().
template<typename external_spacepoint_t > template<typename input_container_t , typename output_container_t , typename callable_t > void Acts::SeedFinderFTF< external_spacepoint_t >::createSeeds_old (const Acts::SeedFinderOptions & options, const input_container_t & spacePoints, output_container_t & out_cont, callable_t && extract_coordinates) const
Definition at line 714 of file SeedFinderFTF.ipp.
View newest version in sPHENIX GitHub at line 714 of file SeedFinderFTF.ipp
Referenced by ActsExamples::SeedingFTFAlgorithm::execute().
template<typename external_spacepoint_t > template<typename input_container_t , typename callable_t > std::vector< Seed< external_spacepoint_t > > Acts::SeedFinderFTF< external_spacepoint_t >::createSeeds_old (const Acts::SeedFinderOptions & options, const input_container_t & spacePoints, callable_t && extract_coordinates) const
Definition at line 722 of file SeedFinderFTF.ipp.
View newest version in sPHENIX GitHub at line 722 of file SeedFinderFTF.ipp
References physmon_track_finding_ttbar::r.
template<typename external_spacepoint_t > void Acts::SeedFinderFTF< external_spacepoint_t >::loadSpacePoints (const std::vector< FTF_SP< external_spacepoint_t >> & FTF_SP_vect)
Definition at line 50 of file SeedFinderFTF.ipp.
View newest version in sPHENIX GitHub at line 50 of file SeedFinderFTF.ipp
Referenced by ActsExamples::SeedingFTFAlgorithm::execute().
template<typename external_spacepoint_t> SeedFinderFTF<external_spacepoint_t>& Acts::SeedFinderFTF< external_spacepoint_t >::operator= (const SeedFinderFTF< external_spacepoint_t > &) delete
template<typename external_spacepoint_t > void Acts::SeedFinderFTF< external_spacepoint_t >::runGNN_TrackFinder (std::vector< GNN_TrigTracklet< external_spacepoint_t >> & vTracks, const Acts::RoiDescriptor & roi, const Acts::TrigFTF_GNN_Geometry< external_spacepoint_t > & gnngeo) private
Definition at line 69 of file SeedFinderFTF.ipp.
View newest version in sPHENIX GitHub at line 69 of file SeedFinderFTF.ipp
References A, Acts::TrigFTF_GNN_Node< space_point_t >::addIn(), Acts::TrigFTF_GNN_Node< space_point_t >::addOut(), b1, deltaPhi(), dy, dz, Acts::RoiDescriptor::dzdrMinus(), Acts::RoiDescriptor::dzdrPlus(), Acts::TrigFTF_GNN_EtaBin< space_point_t >::empty(), Acts::TrigFTF_GNN_Geometry< space_point_t >::fastrack(), TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::followTrack(), Acts::TrigFTF_GNN_Layer< space_point_t >::getMaxBinRadius(), Acts::TrigFTF_GNN_Layer< space_point_t >::getMinBinRadius(), Acts::TrigFTF_GNN_Geometry< space_point_t >::getTrigFTF_GNN_LayerByKey(), Acts::TrigFTF_GNN_Node< space_point_t >::isFull(), it, Acts::TrigFTF_GNN_Layer< space_point_t >::m_bins, Acts::TrigFTF_GNN_Node< space_point_t >::m_in, TrigFTF_GNN_EdgeState< external_spacepoint_t >::m_initialized, Acts::FasTrackConnector::m_layerGroups, Acts::TrigFTF_GNN_Edge< space_point_t >::m_level, Acts::TrigFTF_GNN_Node< space_point_t >::m_maxCutOnTau, Acts::TrigFTF_GNN_Edge< space_point_t >::m_nNei, Acts::TrigFTF_GNN_Node< space_point_t >::m_out, Acts::TrigFTF_GNN_Edge< space_point_t >::m_p, Acts::TrigFTF_GNN_Node< space_point_t >::m_sp_FTF, Acts::TrigFTF_GNN_EtaBin< space_point_t >::m_vn, Acts::TrigFTF_GNN_Edge< space_point_t >::m_vNei, Acts::TrigFTF_GNN_EtaBin< space_point_t >::m_vPhiNodes, TrigFTF_GNN_EdgeState< external_spacepoint_t >::m_vs, Acts::MAX_SEG_PER_NODE, Acts::Test::maxPhi, Acts::Test::minPhi, testing::internal::move(), Acts::N_SEG_CONNS, check_smearing_config::output, Q(), r1, r2, Acts::Experimental::detail::BlueprintHelper::sort(), Acts::FTF_SP< space_point_t >::SP, tau, and yn.
Member Data Documentation
template<typename external_spacepoint_t> SeedFinderFTFConfig<external_spacepoint_t> Acts::SeedFinderFTF< external_spacepoint_t >::m_config private
Definition at line 87 of file SeedFinderFTF.hpp.
View newest version in sPHENIX GitHub at line 87 of file SeedFinderFTF.hpp
template<typename external_spacepoint_t> TrigFTF_GNN_DataStorage<external_spacepoint_t>* Acts::SeedFinderFTF< external_spacepoint_t >::m_storage private
Definition at line 95 of file SeedFinderFTF.hpp.
View newest version in sPHENIX GitHub at line 95 of file SeedFinderFTF.hpp
Referenced by Acts::SeedFinderFTF< external_spacepoint_t >::SeedFinderFTF().
template<typename external_spacepoint_t> std::vector<TrigInDetTriplet<external_spacepoint_t> > Acts::SeedFinderFTF< external_spacepoint_t >::m_triplets private
Definition at line 98 of file SeedFinderFTF.hpp.
View newest version in sPHENIX GitHub at line 98 of file SeedFinderFTF.hpp
template<typename external_spacepoint_t> constexpr std::size_t Acts::SeedFinderFTF< external_spacepoint_t >::NDims = 3 static
Definition at line 47 of file SeedFinderFTF.hpp.
View newest version in sPHENIX GitHub at line 47 of file SeedFinderFTF.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Seeding/SeedFinderFTF.hpp
acts/blob/sPHENIX/Core/include/Acts/Seeding/SeedFinderFTF.ipp