Analysis Software: ActsExamples::PropagationAlgorithm Class Reference
ActsExamples::PropagationAlgorithm Class Reference
this test algorithm performs test propagation within the Acts::Propagator
#include <acts/blob/sPHENIX/Examples/Algorithms/Propagation/include/ActsExamples/Propagation/PropagationAlgorithm.hpp>
Classes
struct Config
Public Member Functions
PropagationAlgorithm (const Config &config, Acts::Logging::Level level)
ActsExamples::ProcessCode execute (const AlgorithmContext &context) const override
const Config & config () const
Get const access to the config.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Member Functions
std::optional
< Acts::BoundSquareMatrix > generateCovariance (ActsExamples::RandomEngine &rnd, std::normal_distribution< double > &gauss) const
Private Attributes
Config m_cfg
the config class
WriteDataHandle< std::vector
< std::vector
< Acts::detail::Step > > > m_outpoutPropagationSteps {this, "OutputPropagationSteps"}
WriteDataHandle
< std::unordered_map< size_t,
Acts::RecordedMaterialTrack > > m_recordedMaterial {this, "RecordedMaterial"}
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
this test algorithm performs test propagation within the Acts::Propagator
If the propagator is equipped appropriately, it can also be used to test the Extrapolator within the geomtetry
Definition at line 69 of file PropagationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 69 of file PropagationAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::PropagationAlgorithm::PropagationAlgorithm (const Config & config, Acts::Logging::Level level)
Constructor
Parameters
[in] config is the configuration struct
[in] loglevel is the logging level
Definition at line 125 of file PropagationAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 125 of file PropagationAlgorithm.cpp
References ActsExamples::WriteDataHandle< T >::initialize(), m_cfg, m_outpoutPropagationSteps, m_recordedMaterial, ActsExamples::PropagationAlgorithm::Config::propagationMaterialCollection, ActsExamples::PropagationAlgorithm::Config::propagationStepCollection, ActsExamples::PropagationAlgorithm::Config::propagatorImpl, and ActsExamples::PropagationAlgorithm::Config::randomNumberSvc.
Member Function Documentation
const Config& ActsExamples::PropagationAlgorithm::config () const inline
Get const access to the config.
Definition at line 148 of file PropagationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 148 of file PropagationAlgorithm.hpp
References m_cfg.
ProcessCode ActsExamples::PropagationAlgorithm::execute (const AlgorithmContext & context) const override virtual
Framework execute method
Parameters
[in] the algorithm context for event consistency
Returns
is a process code indicating success or not
get the d0 and z0
Implements ActsExamples::IAlgorithm.
Definition at line 22 of file PropagationAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 22 of file PropagationAlgorithm.cpp
References charge(), Acts::Test::cov, ActsExamples::PropagationAlgorithm::Config::d0Sigma, eta, Acts::Test::etaDist(), ActsExamples::PropagationAlgorithm::Config::etaRange, Acts::EventDataView3DTest::gauss(), generateCovariance(), ActsExamples::AlgorithmContext::geoContext, it, ActsExamples::IAlgorithm::logger(), m_cfg, m_outpoutPropagationSteps, m_recordedMaterial, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::momentum(), testing::internal::move(), ActsExamples::PropagationAlgorithm::Config::ntests, merge_hashes::p, pars, ActsExamples::PropagationAlgorithm::Config::particleHypothesis, ActsTests::PropagationDatasets::phi, Acts::Test::phiDist(), ActsExamples::PropagationAlgorithm::Config::phiRange, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::position(), ActsExamples::PropagationAlgorithm::Config::propagatorImpl, physmon_track_finding_ttbar::pt, ActsExamples::PropagationAlgorithm::Config::ptRange, Acts::Test::qDist(), ActsExamples::PropagationAlgorithm::Config::randomNumberSvc, ActsExamples::PropagationAlgorithm::Config::recordMaterialInteractions, conftest::rng(), SUCCESS, writeMapConfig::surface, t, ActsTests::PropagationDatasets::theta, ActsExamples::PropagationAlgorithm::Config::tSigma, and ActsExamples::PropagationAlgorithm::Config::z0Sigma.
std::optional< Acts::BoundSquareMatrix > ActsExamples::PropagationAlgorithm::generateCovariance (ActsExamples::RandomEngine & rnd, std::normal_distribution< double > & gauss) const private
Private helper method to create a corrleated covariance matrix
Parameters
[in] rnd is the random engine
[in] gauss is a gaussian distribution to draw from
Definition at line 102 of file PropagationAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 102 of file PropagationAlgorithm.cpp
References ActsExamples::PropagationAlgorithm::Config::correlations, ActsExamples::PropagationAlgorithm::Config::covariances, ActsExamples::PropagationAlgorithm::Config::covarianceTransport, Acts::EventDataView3DTest::gauss(), i, j, k, and m_cfg.
Referenced by execute().
Member Data Documentation
Config ActsExamples::PropagationAlgorithm::m_cfg private
the config class
Definition at line 151 of file PropagationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 151 of file PropagationAlgorithm.hpp
Referenced by config(), execute(), generateCovariance(), and PropagationAlgorithm().
WriteDataHandle<std::vector<std::vector<Acts::detail::Step> > > ActsExamples::PropagationAlgorithm::m_outpoutPropagationSteps {this, "OutputPropagationSteps"} private
Definition at line 154 of file PropagationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 154 of file PropagationAlgorithm.hpp
Referenced by execute(), and PropagationAlgorithm().
WriteDataHandle<std::unordered_map<size_t, Acts::RecordedMaterialTrack> > ActsExamples::PropagationAlgorithm::m_recordedMaterial {this, "RecordedMaterial"} private
Definition at line 157 of file PropagationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 157 of file PropagationAlgorithm.hpp
Referenced by execute(), and PropagationAlgorithm().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Propagation/include/ActsExamples/Propagation/PropagationAlgorithm.hpp
acts/blob/sPHENIX/Examples/Algorithms/Propagation/src/PropagationAlgorithm.cpp