Analysis Software: plot_ecc2_ed Namespace Reference
plot_ecc2_ed Namespace Reference
Variables
tuple h5 h5py.File('pbpb2p76.h5', 'r')
int harmonic_order 2
list ecc2 h5['20_30/ecc%s/bin_edges'%harmonic_order]
list pro2 h5['20_30/ecc%s/probability'%harmonic_order]
float x 0.5
y pro2
tuple fig plt.figure(figsize=(12, 8))
tuple ax_main plt.gca()
tuple bb_data Bbox.from_bounds(x[i]-0.5*w, y[i]-0.5*h, w, h)
tuple disp_coords ax_main.transData.transform(bb_data)
tuple fig_coords fig.transFigure.inverted()
tuple rect Bbox(fig_coords)
list ed h5['20_30/ecc%s/ed_bin%d'%(harmonic_order,i)]
tuple ax fig.add_axes(rect, frameon=False, axisbg='g', aspect=1)
Variable Documentation
tuple plot_ecc2_ed.ax fig.add_axes(rect, frameon=False, axisbg='g', aspect=1)
Definition at line 42 of file plot_ecc2_ed.py.
View newest version in sPHENIX GitHub at line 42 of file plot_ecc2_ed.py
tuple plot_ecc2_ed.ax_main plt.gca()
Definition at line 27 of file plot_ecc2_ed.py.
View newest version in sPHENIX GitHub at line 27 of file plot_ecc2_ed.py
tuple plot_ecc2_ed.bb_data Bbox.from_bounds(x[i]-0.5*w, y[i]-0.5*h, w, h)
Definition at line 35 of file plot_ecc2_ed.py.
View newest version in sPHENIX GitHub at line 35 of file plot_ecc2_ed.py
tuple plot_ecc2_ed.disp_coords ax_main.transData.transform(bb_data)
Definition at line 36 of file plot_ecc2_ed.py.
View newest version in sPHENIX GitHub at line 36 of file plot_ecc2_ed.py
list plot_ecc2_ed.ecc2 h5['20_30/ecc%s/bin_edges'%harmonic_order]
Definition at line 18 of file plot_ecc2_ed.py.
View newest version in sPHENIX GitHub at line 18 of file plot_ecc2_ed.py
list plot_ecc2_ed.ed h5['20_30/ecc%s/ed_bin%d'%(harmonic_order,i)]
Definition at line 40 of file plot_ecc2_ed.py.
View newest version in sPHENIX GitHub at line 40 of file plot_ecc2_ed.py
Referenced by biconnectivity.after_recursive_call_handler(), HydroinfoH5.clean_hydro_event(), HydroinfoH5.getHydroinfo(), HydroinfoH5.getHydroinfoOnlattice(), LBT.LBT0(), HydroinfoH5.readHydroinfoBuffered_total(), HydroinfoH5.readHydroinfoH5(), and HydroinfoH5.readHydroinfoSingleframe().
tuple plot_ecc2_ed.fig plt.figure(figsize=(12, 8))
Definition at line 25 of file plot_ecc2_ed.py.
View newest version in sPHENIX GitHub at line 25 of file plot_ecc2_ed.py
tuple plot_ecc2_ed.fig_coords fig.transFigure.inverted()
Definition at line 37 of file plot_ecc2_ed.py.
View newest version in sPHENIX GitHub at line 37 of file plot_ecc2_ed.py
tuple plot_ecc2_ed.h5 h5py.File('pbpb2p76.h5', 'r')
Definition at line 14 of file plot_ecc2_ed.py.
View newest version in sPHENIX GitHub at line 14 of file plot_ecc2_ed.py
Referenced by Draw_ratio(), FillEnergy(), makePlot_track_eval(), ReadHis(), ReadHis2(), and ReadHis3().
int plot_ecc2_ed.harmonic_order 2
Definition at line 16 of file plot_ecc2_ed.py.
View newest version in sPHENIX GitHub at line 16 of file plot_ecc2_ed.py
list plot_ecc2_ed.pro2 h5['20_30/ecc%s/probability'%harmonic_order]
Definition at line 19 of file plot_ecc2_ed.py.
View newest version in sPHENIX GitHub at line 19 of file plot_ecc2_ed.py
tuple plot_ecc2_ed.rect Bbox(fig_coords)
Definition at line 38 of file plot_ecc2_ed.py.
View newest version in sPHENIX GitHub at line 38 of file plot_ecc2_ed.py
Referenced by Acts::Test.BOOST_AUTO_TEST_CASE().
float plot_ecc2_ed.x 0.5
Definition at line 22 of file plot_ecc2_ed.py.
View newest version in sPHENIX GitHub at line 22 of file plot_ecc2_ed.py
plot_ecc2_ed.y pro2
Definition at line 23 of file plot_ecc2_ed.py.
View newest version in sPHENIX GitHub at line 23 of file plot_ecc2_ed.py