Analysis Software: RDBC/blob/master/test/RDBCTestConnect/RDBCTestConnect.C File Reference
RDBCTestConnect.C File Reference
#include <TError.h>
#include <TString.h>
#include <RDBC/TSQLDriverManager.h>
#include <RDBC/TSQLConnection.h>
#include <RDBC/TSQLDatabaseMetaData.h>
#include <RDBC/TSQLResultSet.h>
#include <RDBC/TSQLResultSetMetaData.h>
#include <RDBC/TSQLPreparedStatement.h>
#include <RDBC/TSQLCallableStatement.h>
#include <RDBC/TSQLTypes.h>
#include <stdlib.h>
Functions
Int_t RDBCTestConnect (const Text_t *dsn, const Text_t *usr="", const Text_t *pwd="")
void Catch (TSQLException *e)
Function Documentation
void Catch (TSQLException * e)
Definition at line 44 of file RDBCTestConnect.C.
View newest version in sPHENIX GitHub at line 44 of file RDBCTestConnect.C
References TSQLException::GetMessage(), printf(), and str.
Int_t RDBCTestConnect (const Text_t * dsn, const Text_t * usr = "", const Text_t * pwd = "")
Definition at line 16 of file RDBCTestConnect.C.
View newest version in sPHENIX GitHub at line 16 of file RDBCTestConnect.C
References TSQLConnection::Close(), TSQLDriverManager::GetConnection(), and printf().