Analysis Software: PHG4CylinderCell Class Reference
PHG4CylinderCell Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCell.h>
Public Member Functions
~PHG4CylinderCell () override
void identify (std::ostream &os=std::cout) const override
void set_ladder_phi_index (const int) override
int get_ladder_phi_index () const override
void set_ladder_z_index (const int) override
int get_ladder_z_index () const override
virtual void set_cell_id (const PHG4CylinderCellDefs::keytype)
virtual void set_layer (const unsigned int)
virtual unsigned int get_layer () const
virtual
PHG4CylinderCellDefs::keytype get_cell_id () const
virtual int get_binz () const
virtual int get_binphi () const
virtual int get_bineta () const
virtual void set_etabin (const int)
virtual void set_light_yield (float)
virtual void set_fiber_ID (int)
virtual int get_fiber_ID () const
virtual void set_sensor_index (const std::string &)
virtual std::string get_sensor_index () const
virtual int get_j_index () const
virtual void set_j_index (const int)
virtual int get_k_index () const
virtual void set_k_index (const int)
virtual int get_l_index () const
virtual void set_l_index (const int)
Public Member Functions inherited from PHG4Cell
~PHG4Cell () override
void CopyFrom (const PHObject *phobj) override
void Reset () override
Clear Event.
virtual void set_cellid (const PHG4CellDefs::keytype)
virtual PHG4CellDefs::keytype get_cellid () const
virtual bool has_binning (const PHG4CellDefs::CellBinning) const
virtual void add_edep (const PHG4HitDefs::keytype, const float)
virtual void add_edep (const PHG4HitDefs::keytype, const float, const float)
virtual void add_edep (const PHG4HitDefs::keytype, const int, const float)
virtual void add_shower_edep (const int, const float)
virtual EdepConstRange get_g4hits ()
virtual ShowerEdepConstRange get_g4showers ()
virtual short int get_detid () const
short int get_layer () const
virtual void add_edep (const float)
virtual double get_edep () const
virtual void add_eion (const float)
virtual double get_eion () const
virtual void add_light_yield (const float)
virtual float get_light_yield () const
virtual void add_raw_light_yield (const float)
virtual float get_raw_light_yield () const
virtual void set_chip_index (const int)
virtual int get_chip_index () const
virtual void set_half_stave_index (const int)
virtual int get_half_stave_index () const
virtual void set_module_index (const int)
virtual int get_module_index () const
virtual void set_phibin (const int)
virtual int get_phibin () const
virtual void set_pixel_index (const int)
virtual int get_pixel_index () const
virtual void set_stave_index (const int)
virtual int get_stave_index () const
virtual void set_zbin (const int)
virtual int get_zbin () const
virtual void print () const
virtual bool has_property (const PROPERTY) const
virtual float get_property_float (const PROPERTY) const
virtual int get_property_int (const PROPERTY) const
virtual unsigned int get_property_uint (const PROPERTY) const
virtual void set_property (const PROPERTY, const float)
virtual void set_property (const PROPERTY, const int)
virtual void set_property (const PROPERTY, const unsigned int)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
Protected Member Functions
PHG4CylinderCell ()
Protected Member Functions inherited from PHG4Cell
PHG4Cell ()
virtual unsigned int get_property_nocheck (const PROPERTY) const
virtual void set_property_nocheck (const PROPERTY, const unsigned int)
Additional Inherited Members
Public Types inherited from PHG4Cell
enum PROPERTY {
prop_stave_index = 1, prop_half_stave_index = 2, prop_module_index = 3, prop_chip_index = 4,
prop_pixel_index = 5, prop_phibin = 6, prop_zbin = 7, prop_ladder_z_index = 8,
prop_ladder_phi_index = 9, prop_edep = 21, prop_eion = 22, prop_light_yield = 23,
prop_raw_light_yield = 24, prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
typedef std::map
< PHG4HitDefs::keytype, float > EdepMap
typedef EdepMap::iterator EdepIterator
typedef EdepMap::const_iterator EdepConstIterator
typedef std::pair
< EdepIterator, EdepIterator > EdepRange
typedef std::pair
< EdepConstIterator,
EdepConstIterator > EdepConstRange
typedef std::map< int, float > ShowerEdepMap
typedef ShowerEdepMap::iterator ShowerEdepIterator
typedef
ShowerEdepMap::const_iterator ShowerEdepConstIterator
typedef std::pair
< ShowerEdepIterator,
ShowerEdepIterator > ShowerEdepRange
typedef std::pair
< ShowerEdepConstIterator,
ShowerEdepConstIterator > ShowerEdepConstRange
Static Public Member Functions inherited from PHG4Cell
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Detailed Description
Definition at line 17 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4CylinderCell.h
Constructor & Destructor Documentation
PHG4CylinderCell::~PHG4CylinderCell () inline override
Definition at line 20 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4CylinderCell.h
PHG4CylinderCell::PHG4CylinderCell () inline protected
Definition at line 61 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4CylinderCell.h
Member Function Documentation
virtual int PHG4CylinderCell::get_bineta () const inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 42 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4CylinderCell.h
virtual int PHG4CylinderCell::get_binphi () const inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 41 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4CylinderCell.h
virtual int PHG4CylinderCell::get_binz () const inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 40 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4CylinderCell.h
virtual PHG4CylinderCellDefs::keytype PHG4CylinderCell::get_cell_id () const inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 39 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4CylinderCell.h
virtual int PHG4CylinderCell::get_fiber_ID () const inline virtual
Definition at line 48 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4CylinderCell.h
virtual int PHG4CylinderCell::get_j_index () const inline virtual
Reimplemented in PHG4CylinderCellv3.
Definition at line 53 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4CylinderCell.h
virtual int PHG4CylinderCell::get_k_index () const inline virtual
Reimplemented in PHG4CylinderCellv3.
Definition at line 55 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4CylinderCell.h
virtual int PHG4CylinderCell::get_l_index () const inline virtual
Reimplemented in PHG4CylinderCellv3.
Definition at line 57 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4CylinderCell.h
int PHG4CylinderCell::get_ladder_phi_index () const inline override virtual
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv2.
Definition at line 29 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 29 of file PHG4CylinderCell.h
int PHG4CylinderCell::get_ladder_z_index () const inline override virtual
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv2.
Definition at line 32 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4CylinderCell.h
virtual unsigned int PHG4CylinderCell::get_layer () const inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 38 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4CylinderCell.h
Referenced by PHG4CylinderCellContainer::AddCylinderCell(), PHG4CylinderCellContainer::AddCylinderCellSpecifyKey(), and PHG4CylinderCellContainer::findOrAddCylinderCell().
virtual std::string PHG4CylinderCell::get_sensor_index () const inline virtual
Reimplemented in PHG4CylinderCellv2.
Definition at line 51 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4CylinderCell.h
void PHG4CylinderCell::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv1, PHG4CylinderCellv2, and PHG4CylinderCellv3.
Definition at line 23 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4CylinderCell.h
References os.
virtual void PHG4CylinderCell::set_cell_id (const PHG4CylinderCellDefs::keytype) inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 35 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4CylinderCell.h
Referenced by PHG4CylinderCellContainer::AddCylinderCell(), PHG4CylinderCellContainer::AddCylinderCellSpecifyKey(), and PHG4CylinderCellContainer::findOrAddCylinderCell().
virtual void PHG4CylinderCell::set_etabin (const int) inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 44 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4CylinderCell.h
virtual void PHG4CylinderCell::set_fiber_ID (int) inline virtual
Definition at line 47 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4CylinderCell.h
virtual void PHG4CylinderCell::set_j_index (const int) inline virtual
Reimplemented in PHG4CylinderCellv3.
Definition at line 54 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4CylinderCell.h
virtual void PHG4CylinderCell::set_k_index (const int) inline virtual
Reimplemented in PHG4CylinderCellv3.
Definition at line 56 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4CylinderCell.h
virtual void PHG4CylinderCell::set_l_index (const int) inline virtual
Reimplemented in PHG4CylinderCellv3.
Definition at line 58 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4CylinderCell.h
void PHG4CylinderCell::set_ladder_phi_index (const int) inline override virtual
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv2.
Definition at line 28 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4CylinderCell.h
void PHG4CylinderCell::set_ladder_z_index (const int) inline override virtual
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv2.
Definition at line 31 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4CylinderCell.h
virtual void PHG4CylinderCell::set_layer (const unsigned int) inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 36 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4CylinderCell.h
virtual void PHG4CylinderCell::set_light_yield (float) inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 45 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4CylinderCell.h
virtual void PHG4CylinderCell::set_sensor_index (const std::string &) inline virtual
Reimplemented in PHG4CylinderCellv2.
Definition at line 50 of file PHG4CylinderCell.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4CylinderCell.h
The documentation for this class was generated from the following file:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCell.h