Analysis Software: CMFlashClusterv1 Class Reference
CMFlashClusterv1 Class Reference
Version 1 of CMFlashCluster.
#include <coresoftware/blob/master/offline/packages/trackbase/CMFlashClusterv1.h>
Public Member Functions
CMFlashClusterv1 ()=default
ctor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void CopyFrom (const CMFlashCluster &) override
copy content from base class
void CopyFrom (CMFlashCluster *source) override
copy content from base class
float getX () const override
void setX (float x) override
float getY () const override
void setY (float y) override
float getZ () const override
void setZ (float z) override
unsigned int getNclusters () const override
void setNclusters (unsigned int n) override
unsigned int getAdc () const override
void setAdc (unsigned int adc) override
Public Member Functions inherited from CMFlashCluster
~CMFlashCluster () override
dtor
virtual float getX1 () const
virtual void setX1 (float)
virtual float getY1 () const
virtual void setY1 (float)
virtual float getZ1 () const
virtual void setZ1 (float)
virtual float getX2 () const
virtual void setX2 (float)
virtual float getY2 () const
virtual void setY2 (float)
virtual float getZ2 () const
virtual void setZ2 (float)
virtual void setLayer1 (unsigned int)
virtual unsigned int getLayer1 () const
virtual void setLayer2 (unsigned int)
virtual unsigned int getLayer2 () const
virtual void setAdc1 (unsigned int)
virtual unsigned int getAdc1 () const
virtual void setAdc2 (unsigned int)
virtual unsigned int getAdc2 () const
virtual void setIsRGap (bool)
virtual bool getIsRGap () const
virtual void setIsPhiGap (bool)
virtual bool getIsPhiGap () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
float m_pos [3] = {NAN, NAN, NAN}
mean cluster position
unsigned int m_adc = 0xFFFFFFFF
cluster sum adc
unsigned int m_nclusters = UINT_MAX
number of TPC clusters used to create this central mebrane cluster
Additional Inherited Members
Protected Member Functions inherited from CMFlashCluster
CMFlashCluster ()=default
Detailed Description
Version 1 of CMFlashCluster.
Note - D. McGlinchey June 2018: CINT does not like "override", so ignore where CINT complains. Should be checked with ROOT 6 once migration occurs.
Definition at line 24 of file CMFlashClusterv1.h.
View newest version in sPHENIX GitHub at line 24 of file CMFlashClusterv1.h
Constructor & Destructor Documentation
CMFlashClusterv1::CMFlashClusterv1 () default
ctor
Referenced by CloneMe().
Member Function Documentation
PHObject* CMFlashClusterv1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 34 of file CMFlashClusterv1.h.
View newest version in sPHENIX GitHub at line 34 of file CMFlashClusterv1.h
References CMFlashClusterv1().
void CMFlashClusterv1::CopyFrom (const CMFlashCluster & source) override virtual
copy content from base class
Reimplemented from CMFlashCluster.
Definition at line 39 of file CMFlashClusterv1.cc.
View newest version in sPHENIX GitHub at line 39 of file CMFlashClusterv1.cc
References CMFlashCluster::CopyFrom(), CMFlashCluster::getAdc(), CMFlashCluster::getX(), CMFlashCluster::getY(), CMFlashCluster::getZ(), setAdc(), setX(), setY(), and setZ().
void CMFlashClusterv1::CopyFrom (CMFlashCluster * source) inline override virtual
copy content from base class
Reimplemented from CMFlashCluster.
Definition at line 40 of file CMFlashClusterv1.h.
View newest version in sPHENIX GitHub at line 40 of file CMFlashClusterv1.h
References CopyFrom().
Referenced by CopyFrom().
unsigned int CMFlashClusterv1::getAdc () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 58 of file CMFlashClusterv1.h.
View newest version in sPHENIX GitHub at line 58 of file CMFlashClusterv1.h
References m_adc.
Referenced by identify().
unsigned int CMFlashClusterv1::getNclusters () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 52 of file CMFlashClusterv1.h.
View newest version in sPHENIX GitHub at line 52 of file CMFlashClusterv1.h
References m_nclusters.
float CMFlashClusterv1::getX () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 46 of file CMFlashClusterv1.h.
View newest version in sPHENIX GitHub at line 46 of file CMFlashClusterv1.h
References m_pos.
Referenced by isValid().
float CMFlashClusterv1::getY () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 48 of file CMFlashClusterv1.h.
View newest version in sPHENIX GitHub at line 48 of file CMFlashClusterv1.h
References m_pos.
Referenced by isValid().
float CMFlashClusterv1::getZ () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 50 of file CMFlashClusterv1.h.
View newest version in sPHENIX GitHub at line 50 of file CMFlashClusterv1.h
References m_pos.
Referenced by isValid().
void CMFlashClusterv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from CMFlashCluster.
Definition at line 12 of file CMFlashClusterv1.cc.
View newest version in sPHENIX GitHub at line 12 of file CMFlashClusterv1.cc
References getAdc(), and m_pos.
int CMFlashClusterv1::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from CMFlashCluster.
Definition at line 28 of file CMFlashClusterv1.cc.
View newest version in sPHENIX GitHub at line 28 of file CMFlashClusterv1.cc
References getX(), getY(), getZ(), and m_adc.
void CMFlashClusterv1::Reset () inline override virtual
Clear Event.
Reimplemented from CMFlashCluster.
Definition at line 32 of file CMFlashClusterv1.h.
View newest version in sPHENIX GitHub at line 32 of file CMFlashClusterv1.h
void CMFlashClusterv1::setAdc (unsigned int adc) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 59 of file CMFlashClusterv1.h.
View newest version in sPHENIX GitHub at line 59 of file CMFlashClusterv1.h
References m_adc.
Referenced by CopyFrom().
void CMFlashClusterv1::setNclusters (unsigned int n) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 53 of file CMFlashClusterv1.h.
View newest version in sPHENIX GitHub at line 53 of file CMFlashClusterv1.h
References m_nclusters, and n.
void CMFlashClusterv1::setX (float x) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 47 of file CMFlashClusterv1.h.
View newest version in sPHENIX GitHub at line 47 of file CMFlashClusterv1.h
References m_pos, and ambiguity_solver_full_chain::x.
Referenced by CopyFrom().
void CMFlashClusterv1::setY (float y) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 49 of file CMFlashClusterv1.h.
View newest version in sPHENIX GitHub at line 49 of file CMFlashClusterv1.h
References m_pos, and y.
Referenced by CopyFrom().
void CMFlashClusterv1::setZ (float z) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 51 of file CMFlashClusterv1.h.
View newest version in sPHENIX GitHub at line 51 of file CMFlashClusterv1.h
References m_pos, and physmon_track_finding_ttbar::z.
Referenced by CopyFrom().
Member Data Documentation
unsigned int CMFlashClusterv1::m_adc = 0xFFFFFFFF protected
cluster sum adc
Definition at line 67 of file CMFlashClusterv1.h.
View newest version in sPHENIX GitHub at line 67 of file CMFlashClusterv1.h
Referenced by getAdc(), isValid(), and setAdc().
unsigned int CMFlashClusterv1::m_nclusters = UINT_MAX protected
number of TPC clusters used to create this central mebrane cluster
Definition at line 70 of file CMFlashClusterv1.h.
View newest version in sPHENIX GitHub at line 70 of file CMFlashClusterv1.h
Referenced by getNclusters(), and setNclusters().
float CMFlashClusterv1::m_pos[3] = {NAN, NAN, NAN} protected
mean cluster position
Definition at line 64 of file CMFlashClusterv1.h.
View newest version in sPHENIX GitHub at line 64 of file CMFlashClusterv1.h
Referenced by getX(), getY(), getZ(), identify(), setX(), setY(), and setZ().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/CMFlashClusterv1.h
coresoftware/blob/master/offline/packages/trackbase/CMFlashClusterv1.cc