Analysis Software: PHG4OHCalFieldSetup Class Reference
PHG4OHCalFieldSetup Class Reference
PHG4OHCalFieldSetup following Geant4 example F03FieldSetup.
#include <coresoftware/blob/master/simulation/g4simulation/g4ohcal/PHG4OHCalFieldSetup.h>
Public Member Functions
PHG4OHCalFieldSetup (const std::string &iron_fieldmap_path, const double scale=1., const double inner_radius=0., const double outer_radius=1.e10, const double size_z=1.e10)
PHG4OHCalFieldSetup (const PHG4OHCalFieldSetup &)=delete
PHG4OHCalFieldSetup & operator= (const PHG4OHCalFieldSetup &)=delete
virtual ~PHG4OHCalFieldSetup ()
G4FieldManager * get_Field_Manager_Iron () const
void set_Field_Manager_Iron (G4FieldManager *fieldManagerIron)
G4double get_Min_Step () const
void set_Min_Step (G4double minStep)
Private Attributes
G4FieldManager * fFieldManagerIron = nullptr
G4Mag_UsualEqRhs * fEquationIron = nullptr
G4ChordFinder * fChordFinderIron = nullptr
G4MagneticField * fEMfieldIron = nullptr
G4MagIntegratorStepper * fStepperIron = nullptr
G4double fMinStep = std::numeric_limits<float>::quiet_NaN()
Detailed Description
PHG4OHCalFieldSetup following Geant4 example F03FieldSetup.
Definition at line 30 of file PHG4OHCalFieldSetup.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4OHCalFieldSetup.h
Constructor & Destructor Documentation
PHG4OHCalFieldSetup::PHG4OHCalFieldSetup (const std::string & iron_fieldmap_path, const double scale = 1., const double inner_radius = 0., const double outer_radius = 1.e10, const double size_z = 1.e10)
Definition at line 31 of file PHG4OHCalFieldSetup.cc.
View newest version in sPHENIX GitHub at line 31 of file PHG4OHCalFieldSetup.cc
References assert, PHFieldUtility::BuildFieldMap(), fChordFinderIron, fEMfieldIron, fEquationIron, fFieldManagerIron, PHFieldConfig::Field3DCartesian, fMinStep, and fStepperIron.
PHG4OHCalFieldSetup::PHG4OHCalFieldSetup (const PHG4OHCalFieldSetup &) explicit delete
PHG4OHCalFieldSetup::~PHG4OHCalFieldSetup () virtual
Definition at line 55 of file PHG4OHCalFieldSetup.cc.
View newest version in sPHENIX GitHub at line 55 of file PHG4OHCalFieldSetup.cc
References fEMfieldIron.
Member Function Documentation
G4FieldManager* PHG4OHCalFieldSetup::get_Field_Manager_Iron () const inline
Definition at line 42 of file PHG4OHCalFieldSetup.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4OHCalFieldSetup.h
References fFieldManagerIron.
Referenced by PHG4OHCalDetector::ConstructOHCal().
G4double PHG4OHCalFieldSetup::get_Min_Step () const inline
Definition at line 54 of file PHG4OHCalFieldSetup.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4OHCalFieldSetup.h
References fMinStep.
PHG4OHCalFieldSetup& PHG4OHCalFieldSetup::operator= (const PHG4OHCalFieldSetup &) delete
void PHG4OHCalFieldSetup::set_Field_Manager_Iron (G4FieldManager * fieldManagerIron) inline
Definition at line 48 of file PHG4OHCalFieldSetup.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4OHCalFieldSetup.h
References fFieldManagerIron.
void PHG4OHCalFieldSetup::set_Min_Step (G4double minStep) inline
Definition at line 60 of file PHG4OHCalFieldSetup.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4OHCalFieldSetup.h
References fMinStep.
Member Data Documentation
G4ChordFinder* PHG4OHCalFieldSetup::fChordFinderIron = nullptr private
Definition at line 68 of file PHG4OHCalFieldSetup.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4OHCalFieldSetup.h
Referenced by PHG4OHCalFieldSetup().
G4MagneticField* PHG4OHCalFieldSetup::fEMfieldIron = nullptr private
Definition at line 69 of file PHG4OHCalFieldSetup.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4OHCalFieldSetup.h
Referenced by PHG4OHCalFieldSetup(), and ~PHG4OHCalFieldSetup().
G4Mag_UsualEqRhs* PHG4OHCalFieldSetup::fEquationIron = nullptr private
Definition at line 67 of file PHG4OHCalFieldSetup.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4OHCalFieldSetup.h
Referenced by PHG4OHCalFieldSetup().
G4FieldManager* PHG4OHCalFieldSetup::fFieldManagerIron = nullptr private
Definition at line 66 of file PHG4OHCalFieldSetup.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4OHCalFieldSetup.h
Referenced by get_Field_Manager_Iron(), PHG4OHCalFieldSetup(), and set_Field_Manager_Iron().
G4double PHG4OHCalFieldSetup::fMinStep = std::numeric_limits<float>::quiet_NaN() private
Definition at line 71 of file PHG4OHCalFieldSetup.h.
View newest version in sPHENIX GitHub at line 71 of file PHG4OHCalFieldSetup.h
Referenced by get_Min_Step(), PHG4OHCalFieldSetup(), and set_Min_Step().
G4MagIntegratorStepper* PHG4OHCalFieldSetup::fStepperIron = nullptr private
Definition at line 70 of file PHG4OHCalFieldSetup.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4OHCalFieldSetup.h
Referenced by PHG4OHCalFieldSetup().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4ohcal/PHG4OHCalFieldSetup.h
coresoftware/blob/master/simulation/g4simulation/g4ohcal/PHG4OHCalFieldSetup.cc