Analysis Software: ActsExamples::FakeRatePlotTool Class Reference
ActsExamples::FakeRatePlotTool Class Reference
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Validation/FakeRatePlotTool.hpp>
Classes
struct Config
The nested configuration struct.
struct FakeRatePlotCache
Nested Cache struct.
Public Member Functions
FakeRatePlotTool (const Config &cfg, Acts::Logging::Level lvl)
void book (FakeRatePlotCache &fakeRatePlotCache) const
book the fake rate plots
void fill (FakeRatePlotCache &fakeRatePlotCache, const Acts::BoundTrackParameters &fittedParameters, bool status) const
fill fake rate w.r.t. fitted track parameters
void fill (FakeRatePlotCache &fakeRatePlotCache, const ActsFatras::Particle &truthParticle, size_t nTruthMatchedTracks, size_t nFakeTracks) const
fill number of reco/truth-matched/fake tracks for a truth particle seed
void write (const FakeRatePlotCache &fakeRatePlotCache) const
write the fake rate plots to file
void clear (FakeRatePlotCache &fakeRatePlotCache) const
delete the fake rate plots
Private Member Functions
const Acts::Logger & logger () const
The logger.
Private Attributes
Config m_cfg
The Config class.
std::unique_ptr< const
Acts::Logger > m_logger
The logging instance.
Detailed Description
Definition at line 33 of file FakeRatePlotTool.hpp.
View newest version in sPHENIX GitHub at line 33 of file FakeRatePlotTool.hpp
Constructor & Destructor Documentation
ActsExamples::FakeRatePlotTool::FakeRatePlotTool (const Config & cfg, Acts::Logging::Level lvl)
Constructor
Parameters
cfg Configuration struct
lvl Message level declaration
Definition at line 23 of file FakeRatePlotTool.cpp.
View newest version in sPHENIX GitHub at line 23 of file FakeRatePlotTool.cpp
Member Function Documentation
void ActsExamples::FakeRatePlotTool::book (FakeRatePlotTool::FakeRatePlotCache & fakeRatePlotCache) const
book the fake rate plots
Parameters
fakeRatePlotCache the cache for fake rate plots
Definition at line 27 of file FakeRatePlotTool.cpp.
View newest version in sPHENIX GitHub at line 27 of file FakeRatePlotTool.cpp
References ACTS_DEBUG, ActsExamples::PlotHelpers::bookEff(), ActsExamples::PlotHelpers::bookHisto(), ActsExamples::FakeRatePlotTool::FakeRatePlotCache::fakeRate_vs_eta, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::fakeRate_vs_phi, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::fakeRate_vs_pT, m_cfg(), ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nFake_vs_eta, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nFake_vs_pT, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nReco_vs_eta, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nReco_vs_pT, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nTruthMatched_vs_eta, and ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nTruthMatched_vs_pT.
Referenced by ActsExamples::CKFPerformanceWriter::CKFPerformanceWriter().
void ActsExamples::FakeRatePlotTool::clear (FakeRatePlotCache & fakeRatePlotCache) const
delete the fake rate plots
Parameters
fakeRatePlotCache cache object for fake rate plots
Definition at line 70 of file FakeRatePlotTool.cpp.
View newest version in sPHENIX GitHub at line 70 of file FakeRatePlotTool.cpp
References ActsExamples::FakeRatePlotTool::FakeRatePlotCache::fakeRate_vs_eta, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::fakeRate_vs_phi, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::fakeRate_vs_pT, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nFake_vs_eta, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nFake_vs_pT, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nReco_vs_eta, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nReco_vs_pT, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nTruthMatched_vs_eta, and ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nTruthMatched_vs_pT.
void ActsExamples::FakeRatePlotTool::fill (FakeRatePlotTool::FakeRatePlotCache & fakeRatePlotCache, const Acts::BoundTrackParameters & fittedParameters, bool status) const
fill fake rate w.r.t. fitted track parameters
Parameters
fakeRatePlotCache cache object for fake rate plots
fittedParameters fitted track parameters of this track
status the reconstructed track is fake or not
Definition at line 97 of file FakeRatePlotTool.cpp.
View newest version in sPHENIX GitHub at line 97 of file FakeRatePlotTool.cpp
References eta, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::fakeRate_vs_eta, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::fakeRate_vs_phi, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::fakeRate_vs_pT, ActsExamples::PlotHelpers::fillEff(), momentum, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::momentum(), Acts::VectorHelpers::perp(), and ActsTests::PropagationDatasets::phi.
void ActsExamples::FakeRatePlotTool::fill (FakeRatePlotTool::FakeRatePlotCache & fakeRatePlotCache, const ActsFatras::Particle & truthParticle, size_t nTruthMatchedTracks, size_t nFakeTracks) const
fill number of reco/truth-matched/fake tracks for a truth particle seed
Parameters
fakeRatePlotCache cache object for fake rate plots
truthParticle the truth Particle
nTruthMatchedTracks the number of truth-Matched tracks
nFakeTracks the number of fake tracks
Definition at line 110 of file FakeRatePlotTool.cpp.
View newest version in sPHENIX GitHub at line 110 of file FakeRatePlotTool.cpp
References ActsFatras::Particle::direction(), eta, ActsExamples::PlotHelpers::fillHisto(), ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nFake_vs_eta, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nFake_vs_pT, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nReco_vs_eta, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nReco_vs_pT, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nTruthMatched_vs_eta, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nTruthMatched_vs_pT, and ActsFatras::Particle::transverseMomentum().
const Acts::Logger& ActsExamples::FakeRatePlotTool::logger () const inline private
The logger.
Definition at line 107 of file FakeRatePlotTool.hpp.
View newest version in sPHENIX GitHub at line 107 of file FakeRatePlotTool.hpp
References m_logger.
void ActsExamples::FakeRatePlotTool::write (const FakeRatePlotCache & fakeRatePlotCache) const
write the fake rate plots to file
Parameters
fakeRatePlotCache cache object for fake rate plots
Definition at line 83 of file FakeRatePlotTool.cpp.
View newest version in sPHENIX GitHub at line 83 of file FakeRatePlotTool.cpp
References ACTS_DEBUG, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::fakeRate_vs_eta, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::fakeRate_vs_phi, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::fakeRate_vs_pT, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nFake_vs_eta, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nFake_vs_pT, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nReco_vs_eta, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nReco_vs_pT, ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nTruthMatched_vs_eta, and ActsExamples::FakeRatePlotTool::FakeRatePlotCache::nTruthMatched_vs_pT.
Member Data Documentation
Config ActsExamples::FakeRatePlotTool::m_cfg private
The Config class.
Definition at line 103 of file FakeRatePlotTool.hpp.
View newest version in sPHENIX GitHub at line 103 of file FakeRatePlotTool.hpp
std::unique_ptr<const Acts::Logger> ActsExamples::FakeRatePlotTool::m_logger private
The logging instance.
Definition at line 104 of file FakeRatePlotTool.hpp.
View newest version in sPHENIX GitHub at line 104 of file FakeRatePlotTool.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Validation/FakeRatePlotTool.hpp
acts/blob/sPHENIX/Examples/Framework/src/Validation/FakeRatePlotTool.cpp