Analysis Software: truth_tracking_gx2f Namespace Reference
truth_tracking_gx2f Namespace Reference
Functions
def runTruthTrackingGx2f
Variables
u acts.UnitConstants
tuple srcdir Path(__file__)
tuple field acts.ConstantBField(acts.Vector3(0, 0, 2 * u.T))
trackingGeometry trackingGeometry,
digiConfigFile srcdir
tuple outputDir Path.cwd()
Function Documentation
def truth_tracking_gx2f.runTruthTrackingGx2f (trackingGeometry)
Definition at line 13 of file truth_tracking_gx2f.py.
View newest version in sPHENIX GitHub at line 13 of file truth_tracking_gx2f.py
References acts.examples.simulation.addDigitization(), acts.examples.simulation.addFatras(), acts.examples.reconstruction.addGx2fTracks(), acts.examples.simulation.addParticleGun(), acts.examples.reconstruction.addSeeding(), acts.examples.simulation.EtaConfig, acts.examples.simulation.MomentumConfig, acts.examples.simulation.ParticleConfig, str, and acts.examples.reconstruction.TruthSeedRanges.
Variable Documentation
truth_tracking_gx2f.digiConfigFile srcdir
Definition at line 160 of file truth_tracking_gx2f.py.
View newest version in sPHENIX GitHub at line 160 of file truth_tracking_gx2f.py
truth_tracking_gx2f.field acts.ConstantBField(acts.Vector3(0, 0, 2 * u.T))
Definition at line 154 of file truth_tracking_gx2f.py.
View newest version in sPHENIX GitHub at line 154 of file truth_tracking_gx2f.py
tuple truth_tracking_gx2f.outputDir Path.cwd()
Definition at line 165 of file truth_tracking_gx2f.py.
View newest version in sPHENIX GitHub at line 165 of file truth_tracking_gx2f.py
tuple truth_tracking_gx2f.srcdir Path(__file__)
Definition at line 149 of file truth_tracking_gx2f.py.
View newest version in sPHENIX GitHub at line 149 of file truth_tracking_gx2f.py
truth_tracking_gx2f.trackingGeometry trackingGeometry,
Definition at line 157 of file truth_tracking_gx2f.py.
View newest version in sPHENIX GitHub at line 157 of file truth_tracking_gx2f.py
truth_tracking_gx2f.u acts.UnitConstants
Definition at line 9 of file truth_tracking_gx2f.py.
View newest version in sPHENIX GitHub at line 9 of file truth_tracking_gx2f.py