Analysis Software: std::tr1 Namespace Reference
std::tr1 Namespace Reference
Namespaces
namespace gtest_internal
Classes
class tuple<>
class tuple
struct tuple_size< GTEST_0_TUPLE_(T) >
struct tuple_size< GTEST_1_TUPLE_(T) >
struct tuple_size< GTEST_2_TUPLE_(T) >
struct tuple_size< GTEST_3_TUPLE_(T) >
struct tuple_size< GTEST_4_TUPLE_(T) >
struct tuple_size< GTEST_5_TUPLE_(T) >
struct tuple_size< GTEST_6_TUPLE_(T) >
struct tuple_size< GTEST_7_TUPLE_(T) >
struct tuple_size< GTEST_8_TUPLE_(T) >
struct tuple_size< GTEST_9_TUPLE_(T) >
struct tuple_size< GTEST_10_TUPLE_(T) >
struct tuple_element
Functions
template<GTEST_1_TYPENAMES_(T) >
class GTEST_1_TUPLE_ (T)
template<GTEST_2_TYPENAMES_(T) >
class GTEST_2_TUPLE_ (T)
template<GTEST_3_TYPENAMES_(T) >
class GTEST_3_TUPLE_ (T)
template<GTEST_4_TYPENAMES_(T) >
class GTEST_4_TUPLE_ (T)
template<GTEST_5_TYPENAMES_(T) >
class GTEST_5_TUPLE_ (T)
template<GTEST_6_TYPENAMES_(T) >
class GTEST_6_TUPLE_ (T)
template<GTEST_7_TYPENAMES_(T) >
class GTEST_7_TUPLE_ (T)
template<GTEST_8_TYPENAMES_(T) >
class GTEST_8_TUPLE_ (T)
template<GTEST_9_TYPENAMES_(T) >
class GTEST_9_TUPLE_ (T)
tuple make_tuple ()
template<GTEST_10_TYPENAMES_(T) >
GTEST_10_TUPLE_ (T) make_tuple(const T0 &f0
template<int k, GTEST_10_TYPENAMES_(T) >
GTEST_ADD_REF_ (GTEST_TUPLE_ELEMENT_(k, GTEST_10_TUPLE_(T))) get(GTEST_10_TUPLE_(T)&t)
template<int k, GTEST_10_TYPENAMES_(T) >
GTEST_BY_REF_ (GTEST_TUPLE_ELEMENT_(k, GTEST_10_TUPLE_(T))) get(const GTEST_10_TUPLE_(T)&t)
template<GTEST_10_TYPENAMES_(T) , GTEST_10_TYPENAMES_(U) >
bool operator== (const GTEST_10_TUPLE_(T)&t, const GTEST_10_TUPLE_(U)&u)
template<GTEST_10_TYPENAMES_(T) , GTEST_10_TYPENAMES_(U) >
bool operator!= (const GTEST_10_TUPLE_(T)&t, const GTEST_10_TUPLE_(U)&u)
Variables
const T1 & f1
const T1 const T2 & f2
const T1 const T2 const T3 & f3
const T1 const T2 const T3
const T4 & f4
const T1 const T2 const T3
const T4 const T5 & f5
const T1 const T2 const T3
const T4 const T5 const T6 & f6
const T1 const T2 const T3
const T4 const T5 const T6
const T7 & f7
const T1 const T2 const T3
const T4 const T5 const T6
const T7 const T8 & f8
const T1 const T2 const T3
const T4 const T5 const T6
const T7 const T8 const T9 & f9
Function Documentation
template<GTEST_10_TYPENAMES_(T) > std::tr1::GTEST_10_TUPLE_ (T) const inline
template<GTEST_1_TYPENAMES_(T) > std::tr1::GTEST_1_TUPLE_ (T) inline
Definition at line 213 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 213 of file gtest-tuple.h
References std::tr1::tuple<>::f0_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, operator=(), and t.
template<GTEST_2_TYPENAMES_(T) > std::tr1::GTEST_2_TUPLE_ (T) inline
Definition at line 245 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 245 of file gtest-tuple.h
References std::tr1::tuple<>::f0_, f1, std::tr1::tuple<>::f1_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, operator=(), merge_hashes::p, t, and T1.
template<GTEST_3_TYPENAMES_(T) > std::tr1::GTEST_3_TUPLE_ (T) inline
Definition at line 288 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 288 of file gtest-tuple.h
References std::tr1::tuple<>::f0_, f1, std::tr1::tuple<>::f1_, f2, std::tr1::tuple<>::f2_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, operator=(), t, T1, and T2.
template<GTEST_4_TYPENAMES_(T) > std::tr1::GTEST_4_TUPLE_ (T) inline
Definition at line 325 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 325 of file gtest-tuple.h
References std::tr1::tuple<>::f0_, f1, std::tr1::tuple<>::f1_, f2, std::tr1::tuple<>::f2_, f3, std::tr1::tuple<>::f3_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, operator=(), t, T1, T2, and T3.
template<GTEST_5_TYPENAMES_(T) > std::tr1::GTEST_5_TUPLE_ (T) inline
Definition at line 366 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 366 of file gtest-tuple.h
References std::tr1::tuple<>::f0_, f1, std::tr1::tuple<>::f1_, f2, std::tr1::tuple<>::f2_, f3, std::tr1::tuple<>::f3_, f4, std::tr1::tuple<>::f4_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, operator=(), t, T1, T2, T3, and T4.
template<GTEST_6_TYPENAMES_(T) > std::tr1::GTEST_6_TUPLE_ (T) inline
Definition at line 410 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 410 of file gtest-tuple.h
References std::tr1::tuple<>::f0_, f1, std::tr1::tuple<>::f1_, f2, std::tr1::tuple<>::f2_, f3, std::tr1::tuple<>::f3_, f4, std::tr1::tuple<>::f4_, f5, std::tr1::tuple<>::f5_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, operator=(), t, T1, T2, T3, T4, and T5.
template<GTEST_7_TYPENAMES_(T) > std::tr1::GTEST_7_TUPLE_ (T) inline
Definition at line 457 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 457 of file gtest-tuple.h
References std::tr1::tuple<>::f0_, f1, std::tr1::tuple<>::f1_, f2, std::tr1::tuple<>::f2_, f3, std::tr1::tuple<>::f3_, f4, std::tr1::tuple<>::f4_, f5, std::tr1::tuple<>::f5_, f6, std::tr1::tuple<>::f6_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, operator=(), t, T1, T2, T3, T4, T5, and T6.
template<GTEST_8_TYPENAMES_(T) > std::tr1::GTEST_8_TUPLE_ (T) inline
Definition at line 506 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 506 of file gtest-tuple.h
References std::tr1::tuple<>::f0_, f1, std::tr1::tuple<>::f1_, f2, std::tr1::tuple<>::f2_, f3, std::tr1::tuple<>::f3_, f4, std::tr1::tuple<>::f4_, f5, std::tr1::tuple<>::f5_, f6, std::tr1::tuple<>::f6_, f7, std::tr1::tuple<>::f7_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, operator=(), t, T1, T2, T3, T4, T5, T6, and T7.
template<GTEST_9_TYPENAMES_(T) > std::tr1::GTEST_9_TUPLE_ (T) inline
Definition at line 558 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 558 of file gtest-tuple.h
References std::tr1::tuple<>::f0_, f1, std::tr1::tuple<>::f1_, f2, std::tr1::tuple<>::f2_, f3, std::tr1::tuple<>::f3_, f4, std::tr1::tuple<>::f4_, f5, std::tr1::tuple<>::f5_, f6, std::tr1::tuple<>::f6_, f7, std::tr1::tuple<>::f7_, f8, std::tr1::tuple<>::f8_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, operator=(), t, T1, T2, T3, T4, T5, T6, T7, and T8.
template<int k, GTEST_10_TYPENAMES_(T) > std::tr1::GTEST_ADD_REF_ (GTEST_TUPLE_ELEMENT_(k, GTEST_10_TUPLE_(T)))
Definition at line 930 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 930 of file gtest-tuple.h
References testing::Field().
template<int k, GTEST_10_TYPENAMES_(T) > std::tr1::GTEST_BY_REF_ (GTEST_TUPLE_ELEMENT_(k,GTEST_10_TUPLE_(T))) const
Definition at line 936 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 936 of file gtest-tuple.h
Referenced by GTEST_1_TUPLE_(), GTEST_2_TUPLE_(), GTEST_3_TUPLE_(), GTEST_4_TUPLE_(), GTEST_5_TUPLE_(), GTEST_6_TUPLE_(), GTEST_7_TUPLE_(), GTEST_8_TUPLE_(), and GTEST_9_TUPLE_().
tuple std::tr1::make_tuple () inline
Definition at line 675 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 675 of file gtest-tuple.h
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_FIXTURE_TEST_CASE(), Acts::detail::boundState(), KFParticle_Tools::buildMother(), ActsExamples::detail::NuclearInteractionParametrisation::calculateEigenspace(), CheckDeltaPtWithBoundaryMasks(), TrackFitUtils::circle_circle_intersection(), TrackFitUtils::circle_fit_by_taubin(), PHG4MicromegasDetector::construct_micromegas_tile(), Acts::constructCylinderVolume(), PHG4InttDetector::ConstructIntt(), Jetscape::InitialState::CoordFromIdx(), Acts::createGrid(), Acts::SpacePointGridCreator::createGrid(), Acts::detail::curvilinearState(), Acts::Geant4ShapeConverter::cylinderBounds(), DoDeltaPtCutStudy(), draw_corr(), PHG4OHCalDetector::ExtractLayerTowerId(), PHG4IHCalDetector::ExtractLayerTowerId(), Acts::fieldMapRZ(), Acts::fieldMapXYZ(), PHG4EICMvtxDetector::FillPVArray(), PHG4MvtxDetector::FillPVArray(), Acts::from_json(), Acts::IndexedSurfacesJsonConverter::fromJson(), Acts::Python::Context::get(), KFParticle_Tools::getCombination(), PHField3DCartesian::GetFieldValue(), CDBInterface::getUrl(), STrackMatcherComparatorHistDef::GetVecHistBins(), STrackMatcherComparatorHistDef::GetVecVsHistBins(), KFParticle_MVA::initMVA(), HFTriggerMVA::initMVA(), ActsExamples::TGeoITkModuleSplitter::initSplitCategories(), TrackFitUtils::line_fit(), Acts::AtlasBetheHeitlerApprox< NComponents, PolyDegree >::loadFromFiles(), MakeNewMatcherPlots(), MakeNewMatcherTuplePlots(), MakeOldEvaluatorPlots(), ActsExamples::makeParameterContainers(), Acts::SurfaceArrayCreator::makeSurfaceGridLookup2D(), Acts::mapMaterialPoints(), Acts::materialMapperRZ(), Acts::materialMapperXYZ(), MVTXStavePositionXY(), Acts::detail::CorrectedFreeToBoundTransformer::operator()(), Acts::detail::MultiTrajectoryProjector< type, traj_t >::operator()(), Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator*(), Acts::Geant4ShapeConverter::planarBounds(), QuickWeirdTuplePlotter(), Acts::Geant4ShapeConverter::radialBounds(), Acts::Test::GenericReadWriteTool< val_tuple_t, str_tuple_t >::read(), Acts::Test::readTracksAndVertexCSV(), Acts::Geant4ShapeConverter::rectangleBounds(), Acts::detail::rotationToLocalAxesDerivative(), Acts::solenoidFieldMap(), TpcSpaceChargeReconstructionHelper::split(), testing::gmock_generated_actions_test::TEST(), testing::gmock_more_actions_test::TEST(), testing::gmock_matchers_test::TEST(), test_components_modifying_accessors(), Acts::Geant4ShapeConverter::trapezoidBounds(), while(), testing::internal::FunctionMocker< R(A1)>::With(), testing::internal::FunctionMocker< R(A1, A2)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>::With(), and Acts::zip().
template<GTEST_10_TYPENAMES_(T) , GTEST_10_TYPENAMES_(U) > bool std::tr1::operator!= (const GTEST_10_TUPLE_(T)& t, const GTEST_10_TUPLE_(U)& u) inline
Definition at line 982 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 982 of file gtest-tuple.h
References physmon_ckf_tracking::u.
template<GTEST_10_TYPENAMES_(T) , GTEST_10_TYPENAMES_(U) > bool std::tr1::operator== (const GTEST_10_TUPLE_(T)& t, const GTEST_10_TUPLE_(U)& u) inline
Definition at line 974 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 974 of file gtest-tuple.h
References testing::Eq().
Variable Documentation
const T1 & std::tr1::f1
Initial value:
{
  return GTEST_2_TUPLE_(T)(f0, f1)
Definition at line 683 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 683 of file gtest-tuple.h
Referenced by Matter::colljet22(), LBT::colljet22(), DrawEMCalTower_Resolution_Compare(), ExploreTTrees(), CaloCalibEmc_Pi0::Fit_Histos(), CaloCalibEmc_Pi0::Fit_Histos_Eta_Phi_Add32(), CaloCalibEmc_Pi0::Fit_Histos_Eta_Phi_Add96(), CaloCalibEmc_Pi0::Fit_Histos_Etas96(), LiteCaloEval::FitRelativeShifts(), LBT::flavor(), PHTpcCentralMembraneMatcher::getPhiRotation_smoothed(), KFParticle::GetPseudoProperDecayTime(), KFParticleSIMD::GetPseudoProperDecayTime(), GTEST_2_TUPLE_(), GTEST_3_TUPLE_(), GTEST_4_TUPLE_(), GTEST_5_TUPLE_(), GTEST_6_TUPLE_(), GTEST_7_TUPLE_(), GTEST_8_TUPLE_(), GTEST_9_TUPLE_(), main(), genfit::MaterialEffects::noiseBetheBloch(), Matter::P_z_qg_int_w_M(), ParticleShowerSizeHistoMaker(), PHG4TpcPadBaselineShift::process_event(), LBT::read_tables(), ReadHis2(), PROTOTYPE4_FEM::SampleFit_PowerLawDoubleExp(), TPCDaqDefs::FEEv1::SampleFit_PowerLawDoubleExp(), TpcPrototypeDefs::FEEv2::SampleFit_PowerLawDoubleExp(), PHGeomIOTGeo::SetGeometry(), Matter::sud_z_QG_w_M(), TrackingQA(), Upscalc(), and VertexingQA().
const T1 const T2 & std::tr1::f2
Initial value:
{
  return GTEST_3_TUPLE_(T)(f0, f1, f2)
Definition at line 688 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 688 of file gtest-tuple.h
Referenced by Matter::colljet22(), LBT::colljet22(), DrawEMCalTower_Resolution_Compare(), CaloCalibEmc_Pi0::Fit_Histos(), CaloCalibEmc_Pi0::Fit_Histos_Eta_Phi_Add32(), CaloCalibEmc_Pi0::Fit_Histos_Eta_Phi_Add96(), CaloCalibEmc_Pi0::Fit_Histos_Etas96(), FitProfile(), FitResolution(), LBT::flavor(), PHGeomIOTGeo::GetGeometryCopy(), KFParticle::GetPseudoProperDecayTime(), KFParticleSIMD::GetPseudoProperDecayTime(), GTEST_3_TUPLE_(), GTEST_4_TUPLE_(), GTEST_5_TUPLE_(), GTEST_6_TUPLE_(), GTEST_7_TUPLE_(), GTEST_8_TUPLE_(), GTEST_9_TUPLE_(), QPileUpToy::Make(), genfit::MaterialEffects::noiseBetheBloch(), Matter::P_z_qg_int_w_M(), ParticleShowerSizeHistoMaker(), plot_resolution(), plotembed_vscent(), PROTOTYPE4_FEM::SampleFit_PowerLawDoubleExp(), TpcPrototypeDefs::FEEv2::SampleFit_PowerLawDoubleExp(), TPCDaqDefs::FEEv1::SampleFit_PowerLawDoubleExp(), ActsExamples::ModuleClusters::squash(), Matter::sud_z_QG_w_M(), Upscalc(), and VertexingQA().
const T1 const T2 const T3 & std::tr1::f3
Initial value:
{
  return GTEST_4_TUPLE_(T)(f0, f1, f2, f3)
Definition at line 694 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 694 of file gtest-tuple.h
Referenced by Jetscape::BilinearInt(), KFParticle::GetPseudoProperDecayTime(), KFParticleSIMD::GetPseudoProperDecayTime(), GTEST_4_TUPLE_(), GTEST_5_TUPLE_(), GTEST_6_TUPLE_(), GTEST_7_TUPLE_(), GTEST_8_TUPLE_(), GTEST_9_TUPLE_(), Matter::P_z_qg_int_w_M(), ParticleShowerSizeHistoMaker(), Matter::sud_z_QG_w_M(), Upscalc(), and VertexingQA().
const T1 const T2 const T3 const T4 & std::tr1::f4
Initial value:
{
  return GTEST_5_TUPLE_(T)(f0, f1, f2, f3, f4)
Definition at line 700 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 700 of file gtest-tuple.h
Referenced by KFParticle::GetPseudoProperDecayTime(), KFParticleSIMD::GetPseudoProperDecayTime(), GTEST_5_TUPLE_(), GTEST_6_TUPLE_(), GTEST_7_TUPLE_(), GTEST_8_TUPLE_(), GTEST_9_TUPLE_(), Matter::P_z_qg_int_w_M(), and Matter::sud_z_QG_w_M().
const T1 const T2 const T3 const T4 const T5 & std::tr1::f5
Initial value:
{
  return GTEST_6_TUPLE_(T)(f0, f1, f2, f3, f4, f5)
Definition at line 706 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 706 of file gtest-tuple.h
Referenced by KFParticle::GetPseudoProperDecayTime(), KFParticleSIMD::GetPseudoProperDecayTime(), GTEST_6_TUPLE_(), GTEST_7_TUPLE_(), GTEST_8_TUPLE_(), GTEST_9_TUPLE_(), and Matter::sud_z_QG_w_M().
const T1 const T2 const T3 const T4 const T5 const T6 & std::tr1::f6
Initial value:
{
  return GTEST_7_TUPLE_(T)(f0, f1, f2, f3, f4, f5, f6)
Definition at line 712 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 712 of file gtest-tuple.h
Referenced by GTEST_7_TUPLE_(), GTEST_8_TUPLE_(), GTEST_9_TUPLE_(), and Matter::P_z_qg_int_w_M().
const T1 const T2 const T3 const T4 const T5 const T6 const T7 & std::tr1::f7
Initial value:
{
  return GTEST_8_TUPLE_(T)(f0, f1, f2, f3, f4, f5, f6, f7)
Definition at line 718 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 718 of file gtest-tuple.h
Referenced by GTEST_8_TUPLE_(), GTEST_9_TUPLE_(), and Matter::P_z_qg_int_w_M().
const T1 const T2 const T3 const T4 const T5 const T6 const T7 const T8 & std::tr1::f8
Initial value:
{
  return GTEST_9_TUPLE_(T)(f0, f1, f2, f3, f4, f5, f6, f7, f8)
Definition at line 725 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 725 of file gtest-tuple.h
Referenced by GTEST_9_TUPLE_(), Matter::P_z_qg_int_w_M(), and Matter::sud_z_QG_w_M().
const T1 const T2 const T3 const T4 const T5 const T6 const T7 const T8 const T9& std::tr1::f9
Initial value:
{
  return GTEST_10_TUPLE_(T)(f0, f1, f2, f3, f4, f5, f6, f7, f8, f9)
Definition at line 732 of file gtest-tuple.h.
View newest version in sPHENIX GitHub at line 732 of file gtest-tuple.h
Referenced by Matter::P_z_qg_int_w_M(), and Matter::sud_z_QG_w_M().