Analysis Software: PHG4EPDSteppingAction Class Reference
PHG4EPDSteppingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4epd/PHG4EPDSteppingAction.h>
Public Member Functions
PHG4EPDSteppingAction (PHG4EPDDetector *, const PHParameters *parameters)
~PHG4EPDSteppingAction () override
bool UserSteppingAction (const G4Step *, bool) override
stepping action. This defines processing of a single step in a given volume
void SetInterfacePointers (PHCompositeNode *) override
void SetHitNodeName (const std::string &type, const std::string &name) override
Set the G4HIT node names from Subsystem rather than constructing your own.
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual int InitWithNode (PHCompositeNode *)
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
Private Attributes
PHG4EPDDetector * m_Detector = nullptr
PHG4HitContainer * m_HitContainer = nullptr
PHG4HitContainer * m_SupportHitContainer = nullptr
PHG4Hit * m_Hit = nullptr
G4StepStatus m_SavePostStepStatus = G4StepStatus::fUndefined
std::string m_HitNodeName
std::string m_SupportNodeName
Detailed Description
Definition at line 21 of file PHG4EPDSteppingAction.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4EPDSteppingAction.h
Constructor & Destructor Documentation
PHG4EPDSteppingAction::PHG4EPDSteppingAction (PHG4EPDDetector * detector, const PHParameters * parameters)
Definition at line 41 of file PHG4EPDSteppingAction.cc.
View newest version in sPHENIX GitHub at line 41 of file PHG4EPDSteppingAction.cc
PHG4EPDSteppingAction::~PHG4EPDSteppingAction () override
Definition at line 48 of file PHG4EPDSteppingAction.cc.
View newest version in sPHENIX GitHub at line 48 of file PHG4EPDSteppingAction.cc
References m_Hit.
Member Function Documentation
void PHG4EPDSteppingAction::SetHitNodeName (const std::string & , const std::string &) override virtual
Set the G4HIT node names from Subsystem rather than constructing your own.
Reimplemented from PHG4SteppingAction.
Definition at line 207 of file PHG4EPDSteppingAction.cc.
View newest version in sPHENIX GitHub at line 207 of file PHG4EPDSteppingAction.cc
References m_HitNodeName, m_SupportNodeName, and perf_headwind::name.
void PHG4EPDSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) override virtual
Reimplemented from PHG4SteppingAction.
Definition at line 186 of file PHG4EPDSteppingAction.cc.
View newest version in sPHENIX GitHub at line 186 of file PHG4EPDSteppingAction.cc
References m_HitContainer, m_HitNodeName, m_SupportHitContainer, m_SupportNodeName, and PHG4SteppingAction::Verbosity().
bool PHG4EPDSteppingAction::UserSteppingAction (const G4Step * step, bool was_used) override virtual
stepping action. This defines processing of a single step in a given volume
returns true if hits associated to this step was processed by this detector
Parameters
step pointer to the geant 4 step class
was_used,: true if the hit was already used by a previously registered subsystem
Implements PHG4SteppingAction.
Definition at line 53 of file PHG4EPDSteppingAction.cc.
View newest version in sPHENIX GitHub at line 53 of file PHG4EPDSteppingAction.cc
References PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4Hit::get_light_yield(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetLightCorrection(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), PHG4SteppingAction::GetVisibleEnergyDeposition(), Acts::UnitConstants::GeV, PHG4EPDDetector::IsInDetector(), m_Detector, m_Hit, m_HitContainer, m_SavePostStepStatus, PHG4EPDDetector::module_id_for(), particle, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_light_yield(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), and PHG4TrackUserInfoV1::SetKeep().
Member Data Documentation
PHG4EPDDetector* PHG4EPDSteppingAction::m_Detector = nullptr private
Definition at line 34 of file PHG4EPDSteppingAction.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4EPDSteppingAction.h
Referenced by UserSteppingAction().
PHG4Hit* PHG4EPDSteppingAction::m_Hit = nullptr private
Definition at line 38 of file PHG4EPDSteppingAction.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4EPDSteppingAction.h
Referenced by UserSteppingAction(), and ~PHG4EPDSteppingAction().
PHG4HitContainer* PHG4EPDSteppingAction::m_HitContainer = nullptr private
Definition at line 36 of file PHG4EPDSteppingAction.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4EPDSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::string PHG4EPDSteppingAction::m_HitNodeName private
Definition at line 42 of file PHG4EPDSteppingAction.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4EPDSteppingAction.h
Referenced by SetHitNodeName(), and SetInterfacePointers().
G4StepStatus PHG4EPDSteppingAction::m_SavePostStepStatus = G4StepStatus::fUndefined private
Definition at line 40 of file PHG4EPDSteppingAction.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4EPDSteppingAction.h
Referenced by UserSteppingAction().
PHG4HitContainer* PHG4EPDSteppingAction::m_SupportHitContainer = nullptr private
Definition at line 37 of file PHG4EPDSteppingAction.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4EPDSteppingAction.h
Referenced by SetInterfacePointers().
std::string PHG4EPDSteppingAction::m_SupportNodeName private
Definition at line 43 of file PHG4EPDSteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4EPDSteppingAction.h
Referenced by SetHitNodeName(), and SetInterfacePointers().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4epd/PHG4EPDSteppingAction.h
coresoftware/blob/master/simulation/g4simulation/g4epd/PHG4EPDSteppingAction.cc