Analysis Software: DD4hepTestsHelper Namespace Reference
DD4hepTestsHelper Namespace Reference
Functions
template<typename T >
T & ensureExtension (dd4hep::DetElement &elt)
helper to ensure that an extension is set, copied from the ODD detector code
Transform3D createTransform (const xml_comp_t &x_det_comp)
std::string transformToXML (const Acts::Transform3 &tf, const std::array< int, 2u > &axes={0, 1})
std::string surfaceToXML (const Acts::GeometryContext &gctx, const Acts::Surface &surface, const Acts::Transform3 &ref)
Helper method to convert a Surface into XML.
Function Documentation
dd4hep::Transform3D DD4hepTestsHelper::createTransform (const xml_comp_t & x_det_comp)
Helper method to create a Transform3D from an xml detector component
Parameters
x_det_comp the xml detector component
Returns
a Transform3D (DD4hep type, aka ROOT::Math type)
Definition at line 14 of file DD4hepTestsHelper.cpp.
View newest version in sPHENIX GitHub at line 14 of file DD4hepTestsHelper.cpp
References Acts::Svg::View::xy().
Referenced by addCylinderLayer(), create_cylinder(), create_disc(), create_disc_layer(), create_rectangle(), and create_trapezoid().
template<typename T > T& DD4hepTestsHelper::ensureExtension (dd4hep::DetElement & elt)
helper to ensure that an extension is set, copied from the ODD detector code
Template Parameters
T the type of the extension
Parameters
elt the detector element
Returns
the extracted/created extennsion
Definition at line 36 of file DD4hepTestsHelper.hpp.
View newest version in sPHENIX GitHub at line 36 of file DD4hepTestsHelper.hpp
References Acts::UnitConstants::T.
std::string DD4hepTestsHelper::surfaceToXML (const Acts::GeometryContext & gctx, const Acts::Surface & surface, const Acts::Transform3 & ref)
Helper method to convert a Surface into XML.
Parameters
gctx the geometry context of this call
surface the surface from ACTS to be written
ref the reference transform
Returns
a string representing the XML entry
Definition at line 60 of file DD4hepTestsHelper.cpp.
View newest version in sPHENIX GitHub at line 60 of file DD4hepTestsHelper.cpp
References Acts::Surface::bounds(), dy, dz, Acts::SurfaceBounds::eRectangle, Acts::SurfaceBounds::eTrapezoid, Acts::Surface::transform(), transformToXML(), Acts::SurfaceBounds::type(), physmon_ckf_tracking::u, and Acts::SurfaceBounds::values().
Referenced by BOOST_AUTO_TEST_CASE().
std::string DD4hepTestsHelper::transformToXML (const Acts::Transform3 & tf, const std::array< int, 2u > & axes = {0, 1})
Helper method to convert an ACTS transform into XML
Parameters
tf the transform in ACTS format
axes the identification which axes are building the local frame
Returns
a string representing the XML entry
Definition at line 40 of file DD4hepTestsHelper.cpp.
View newest version in sPHENIX GitHub at line 40 of file DD4hepTestsHelper.cpp
References physmon_ckf_tracking::u.
Referenced by surfaceToXML().