Analysis Software: CMFlashClusterContainerv1 Class Reference
CMFlashClusterContainerv1 Class Reference
CM flash cluster container object.
#include <coresoftware/blob/master/offline/packages/trackbase/CMFlashClusterContainerv1.h>
Public Types
typedef std::map< unsigned int,
CMFlashCluster * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Types inherited from CMFlashClusterContainer
using Map = std::map< unsigned int, CMFlashCluster * >
using Iterator = Map::iterator
using ConstIterator = Map::const_iterator
using Range = std::pair< Iterator, Iterator >
using ConstRange = std::pair< ConstIterator, ConstIterator >
Public Member Functions
CMFlashClusterContainerv1 ()=default
void Reset () override
reset method
void identify (std::ostream &os=std::cout) const override
identify object
void addClusterSpecifyKey (const unsigned int, CMFlashCluster *newClus) override
add a cluster with specific key
void removeCluster (unsigned int) override
remove cluster
ConstRange getClusters () const override
return all clusters
CMFlashCluster * findCluster (unsigned int key) const override
find cluster matching given key
unsigned int size () const override
total number of clusters
Private Attributes
Map m_clusmap
Additional Inherited Members
Protected Member Functions inherited from CMFlashClusterContainer
CMFlashClusterContainer ()=default
constructor
Detailed Description
CM flash cluster container object.
Container for CMFlashCluster objects
Definition at line 25 of file CMFlashClusterContainerv1.h.
View newest version in sPHENIX GitHub at line 25 of file CMFlashClusterContainerv1.h
Member Typedef Documentation
typedef Map::const_iterator CMFlashClusterContainerv1::ConstIterator
Definition at line 30 of file CMFlashClusterContainerv1.h.
View newest version in sPHENIX GitHub at line 30 of file CMFlashClusterContainerv1.h
typedef std::pair<ConstIterator, ConstIterator> CMFlashClusterContainerv1::ConstRange
Definition at line 32 of file CMFlashClusterContainerv1.h.
View newest version in sPHENIX GitHub at line 32 of file CMFlashClusterContainerv1.h
typedef Map::iterator CMFlashClusterContainerv1::Iterator
Definition at line 29 of file CMFlashClusterContainerv1.h.
View newest version in sPHENIX GitHub at line 29 of file CMFlashClusterContainerv1.h
typedef std::map<unsigned int, CMFlashCluster *> CMFlashClusterContainerv1::Map
Definition at line 28 of file CMFlashClusterContainerv1.h.
View newest version in sPHENIX GitHub at line 28 of file CMFlashClusterContainerv1.h
typedef std::pair<Iterator, Iterator> CMFlashClusterContainerv1::Range
Definition at line 31 of file CMFlashClusterContainerv1.h.
View newest version in sPHENIX GitHub at line 31 of file CMFlashClusterContainerv1.h
Constructor & Destructor Documentation
CMFlashClusterContainerv1::CMFlashClusterContainerv1 () default
Member Function Documentation
void CMFlashClusterContainerv1::addClusterSpecifyKey (const unsigned int, CMFlashCluster *) override virtual
add a cluster with specific key
Implements CMFlashClusterContainer.
Definition at line 34 of file CMFlashClusterContainerv1.cc.
View newest version in sPHENIX GitHub at line 34 of file CMFlashClusterContainerv1.cc
References m_clusmap.
CMFlashCluster * CMFlashClusterContainerv1::findCluster (unsigned int) const override virtual
find cluster matching given key
Reimplemented from CMFlashClusterContainer.
Definition at line 57 of file CMFlashClusterContainerv1.cc.
View newest version in sPHENIX GitHub at line 57 of file CMFlashClusterContainerv1.cc
References it, and m_clusmap.
Referenced by removeCluster().
CMFlashClusterContainer::ConstRange CMFlashClusterContainerv1::getClusters () const override virtual
return all clusters
Implements CMFlashClusterContainer.
Definition at line 53 of file CMFlashClusterContainerv1.cc.
View newest version in sPHENIX GitHub at line 53 of file CMFlashClusterContainerv1.cc
References m_clusmap.
void CMFlashClusterContainerv1::identify (std::ostream & = std::cout) const override virtual
identify object
Reimplemented from CMFlashClusterContainer.
Definition at line 20 of file CMFlashClusterContainerv1.cc.
View newest version in sPHENIX GitHub at line 20 of file CMFlashClusterContainerv1.cc
References m_clusmap, and size().
void CMFlashClusterContainerv1::removeCluster (unsigned int) override virtual
remove cluster
Reimplemented from CMFlashClusterContainer.
Definition at line 44 of file CMFlashClusterContainerv1.cc.
View newest version in sPHENIX GitHub at line 44 of file CMFlashClusterContainerv1.cc
References findCluster(), and m_clusmap.
void CMFlashClusterContainerv1::Reset () override virtual
reset method
Reimplemented from CMFlashClusterContainer.
Definition at line 12 of file CMFlashClusterContainerv1.cc.
View newest version in sPHENIX GitHub at line 12 of file CMFlashClusterContainerv1.cc
References m_clusmap.
unsigned int CMFlashClusterContainerv1::size (void) const override virtual
total number of clusters
Reimplemented from CMFlashClusterContainer.
Definition at line 63 of file CMFlashClusterContainerv1.cc.
View newest version in sPHENIX GitHub at line 63 of file CMFlashClusterContainerv1.cc
References m_clusmap.
Referenced by identify().
Member Data Documentation
Map CMFlashClusterContainerv1::m_clusmap private
Definition at line 51 of file CMFlashClusterContainerv1.h.
View newest version in sPHENIX GitHub at line 51 of file CMFlashClusterContainerv1.h
Referenced by addClusterSpecifyKey(), findCluster(), getClusters(), identify(), removeCluster(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/CMFlashClusterContainerv1.h
coresoftware/blob/master/offline/packages/trackbase/CMFlashClusterContainerv1.cc