Analysis Software: STrackCutStudy Class Reference
STrackCutStudy Class Reference
#include <analysis/blob/master/AndersonAnalysisModules/TrackStudies/STrackCutStudy/src/STrackCutStudy.h>
Public Types
enum TRKVAR {
VX = 0, VY = 1, VZ = 2, NMMS = 3,
NMAP = 4, NINT = 5, NTPC = 6, QUAL = 7,
DCAXY = 8, DCAZ = 9, DELDCAXY = 10, DELDCAZ = 11,
NCLUST = 12, AVGCLUST = 13
}
enum PHYSVAR {
PHI = 0, ETA = 1, PT = 2, DELPHI = 3,
DELETA = 4, DELPT = 5
}
enum TYPE {
TRACK = 0, TRUTH = 1, WEIRD_ALL = 2, WEIRD_SI = 3,
WEIRD_TPC = 4, NORMAL = 5, PILEUP = 6, PRIMARY = 7,
NONPRIM = 8, TRK_CUT = 9, TRU_CUT = 10, WEIRD_CUT = 11,
WEIRD_SI_CUT = 12, WEIRD_TPC_CUT = 13, NORM_CUT = 14, PILE_CUT = 15,
PRIM_CUT = 16, NONPRIM_CUT = 17
}
Public Member Functions
STrackCutStudy ()
~STrackCutStudy ()
void SetBatchMode (const Bool_t doBatch=false)
void SetInputOutputFiles (const TString sEmbedOnlyInput, const TString sPileupInput, const TString sOutput)
void SetInputTuples (const TString sEmbedOnlyTuple, const TString sPileupTuple, const TString sEmbedOnlyClusterTuple="")
void SetStudyParameters (const Bool_t plots, const Bool_t pileup, const Bool_t intNorm, const Bool_t beforeCuts, const Bool_t avgClustCalc, const Double_t weirdFracMin, const Double_t weirdFracMax)
void SetCutFlags (const Bool_t doPrimary, const Bool_t doTpc, const Bool_t doMVtx, const Bool_t doVz, const Bool_t doDcaXY, const Bool_t doDcaZ, const Bool_t doQuality)
void SetTrackCuts (const pair< UInt_t, UInt_t > nMVtxRange, const pair< UInt_t, UInt_t > nTpcRange, const pair< Double_t, Double_t > vzRange, const pair< Double_t, Double_t > dcaXyRange, const pair< Double_t, Double_t > dcaZRange, const pair< Double_t, Double_t > qualityRange)
void SetPlotText (const Ssiz_t nTxtE, const Ssiz_t nTxtP, const TString sTxtE[], const TString sTxtP[])
void Init ()
void Analyze ()
void End ()
Private Member Functions
void InitFiles ()
void InitTuples ()
void SaveHists ()
Bool_t ApplyCuts (const Bool_t isPrimary, const UInt_t trkNMVtx, const UInt_t trkNTpc, const Double_t trkVz, const Double_t trkDcaXY, const Double_t trkDcaZ, const Double_t trkQuality)
Bool_t DoClusterCalculation ()
void InitHists ()
void NormalizeHists ()
void SetHistStyles ()
void FillTrackHistograms (const Int_t type, const Double_t recoTrkVars[], const Double_t trueTrkVars[], const Double_t recoPhysVars[], const Double_t truePhysVars[])
void FillTruthHistograms (const Int_t type, const Double_t recoTrkVars[], const Double_t trueTrkVars[], const Double_t recoPhysVars[], const Double_t truePhysVars[])
void MakeCutText ()
void ConstructPlots (const Ssiz_t nToDraw, const Int_t typesToDraw[], const TString sDirToSaveTo, const TString sPlotLabel)
Private Attributes
TFile * fOut
TFile * fInEO
TFile * fInPU
Bool_t inBatchMode
TString sInFileEO
TString sInFilePU
TString sInTupleEO
TString sInTuplePU
TString sInClustEO
TString sOutfile
TNtuple * ntTrkEO
TNtuple * ntTrkPU
TNtuple * ntClustEO
Bool_t isTruth [NType]
Bool_t isPileup [NType]
Bool_t isBeforeCuts [NType]
Bool_t trkVarHasTruVal [NTrkVar]
Bool_t physVarHasTruVal [NPhysVar]
UInt_t fTypeCol [NType]
UInt_t fTypeMar [NType]
TString sTrkNames [NType]
TString sTrkLabels [NType]
TString sTrkVars [NTrkVar]
TString sPhysVars [NPhysVar]
TH1D * hTrkVar [NType][NTrkVar]
TH1D * hTrkVarDiff [NType][NTrkVar]
TH1D * hTrkVarFrac [NType][NTrkVar]
TH2D * hTrkVarVsNTpc [NType][NTrkVar]
TH2D * hTrkVarVsDcaXY [NType][NTrkVar]
TH2D * hTrkVarVsDcaZ [NType][NTrkVar]
TH2D * hTrkVarVsPtReco [NType][NTrkVar]
TH2D * hTrkVarVsPtTrue [NType][NTrkVar]
TH2D * hTrkVarVsPtFrac [NType][NTrkVar]
TH1D * hPhysVar [NType][NPhysVar]
TH1D * hPhysVarDiff [NType][NPhysVar]
TH1D * hPhysVarFrac [NType][NPhysVar]
TH2D * hPhysVarVsNTpc [NType][NPhysVar]
TH2D * hPhysVarVsDcaXY [NType][NPhysVar]
TH2D * hPhysVarVsDcaZ [NType][NPhysVar]
TH2D * hPhysVarVsPtReco [NType][NPhysVar]
TH2D * hPhysVarVsPtTrue [NType][NPhysVar]
TH2D * hPhysVarVsPtFrac [NType][NPhysVar]
Ssiz_t nTxtEO
Ssiz_t nTxtPU
TPaveText * ptCut
vector< TString > sTxtEO
vector< TString > sTxtPU
Bool_t makePlots
Bool_t doPileup
Bool_t doIntNorm
Bool_t doBeforeCuts
Bool_t doAvgClustCalc
Double_t normalPtFracMin
Double_t normalPtFracMax
Bool_t doPrimaryCut
Bool_t doMVtxCut
Bool_t doTpcCut
Bool_t doVzCut
Bool_t doDcaXyCut
Bool_t doDcaZCut
Bool_t doQualityCut
pair< UInt_t, UInt_t > nMVtxCut
pair< UInt_t, UInt_t > nTpcCut
pair< Double_t, Double_t > vzCut
pair< Double_t, Double_t > dcaXyCut
pair< Double_t, Double_t > dcaZCut
pair< Double_t, Double_t > qualityCut
Float_t event
Float_t seed
Float_t trackID
Float_t crossing
Float_t px
Float_t py
Float_t pz
Float_t pt
Float_t eta
Float_t phi
Float_t deltapt
Float_t deltaeta
Float_t deltaphi
Float_t charge
Float_t quality
Float_t chisq
Float_t ndf
Float_t nhits
Float_t nmaps
Float_t nintt
Float_t ntpc
Float_t nmms
Float_t ntpc1
Float_t ntpc11
Float_t ntpc2
Float_t ntpc3
Float_t nlmaps
Float_t nlintt
Float_t nltpc
Float_t nlmms
Float_t layers
Float_t vertexID
Float_t vx
Float_t vy
Float_t vz
Float_t dca2d
Float_t dca2dsigma
Float_t dca3dxy
Float_t dca3dxysigma
Float_t dca3dz
Float_t dca3dzsigma
Float_t pcax
Float_t pcay
Float_t pcaz
Float_t gtrackID
Float_t gflavor
Float_t gnhits
Float_t gnmaps
Float_t gnintt
Float_t gntpc
Float_t gnmms
Float_t gnlmaps
Float_t gnlintt
Float_t gnltpc
Float_t gnlmms
Float_t gpx
Float_t gpy
Float_t gpz
Float_t gpt
Float_t geta
Float_t gphi
Float_t gvx
Float_t gvy
Float_t gvz
Float_t gvt
Float_t gfpx
Float_t gfpy
Float_t gfpz
Float_t gfx
Float_t gfy
Float_t gfz
Float_t gembed
Float_t gprimary
Float_t nfromtruth
Float_t nwrong
Float_t ntrumaps
Float_t ntruintt
Float_t ntrutpc
Float_t ntrumms
Float_t ntrutpc1
Float_t ntrutpc11
Float_t ntrutpc2
Float_t ntrutpc3
Float_t layersfromtruth
Float_t nhittpcall
Float_t nhittpcin
Float_t nhittpcmid
Float_t nhittpcout
Float_t nclusall
Float_t nclustpc
Float_t nclusintt
Float_t nclusmaps
Float_t nclusmms
Float_t pu_event
Float_t pu_seed
Float_t pu_gntracks
Float_t pu_gtrackID
Float_t pu_gflavor
Float_t pu_gnhits
Float_t pu_gnmaps
Float_t pu_gnintt
Float_t pu_gnmms
Float_t pu_gnintt1
Float_t pu_gnintt2
Float_t pu_gnintt3
Float_t pu_gnintt4
Float_t pu_gnintt5
Float_t pu_gnintt6
Float_t pu_gnintt7
Float_t pu_gnintt8
Float_t pu_gntpc
Float_t pu_gnlmaps
Float_t pu_gnlintt
Float_t pu_gnltpc
Float_t pu_gnlmms
Float_t pu_gpx
Float_t pu_gpy
Float_t pu_gpz
Float_t pu_gpt
Float_t pu_geta
Float_t pu_gphi
Float_t pu_gvx
Float_t pu_gvy
Float_t pu_gvz
Float_t pu_gvt
Float_t pu_gfpx
Float_t pu_gfpy
Float_t pu_gfpz
Float_t pu_gfx
Float_t pu_gfy
Float_t pu_gfz
Float_t pu_gembed
Float_t pu_gprimary
Float_t pu_trackID
Float_t pu_px
Float_t pu_py
Float_t pu_pz
Float_t pu_pt
Float_t pu_eta
Float_t pu_phi
Float_t pu_deltapt
Float_t pu_deltaeta
Float_t pu_deltaphi
Float_t pu_charge
Float_t pu_quality
Float_t pu_chisq
Float_t pu_ndf
Float_t pu_nhits
Float_t pu_layers
Float_t pu_nmaps
Float_t pu_nintt
Float_t pu_ntpc
Float_t pu_nmms
Float_t pu_ntpc1
Float_t pu_ntpc11
Float_t pu_ntpc2
Float_t pu_ntpc3
Float_t pu_nlmaps
Float_t pu_nlintt
Float_t pu_nltpc
Float_t pu_nlmms
Float_t pu_vertexID
Float_t pu_vx
Float_t pu_vy
Float_t pu_vz
Float_t pu_dca2d
Float_t pu_dca2dsigma
Float_t pu_dca3dxy
Float_t pu_dca3dxysigma
Float_t pu_dca3dz
Float_t pu_dca3dzsigma
Float_t pu_pcax
Float_t pu_pcay
Float_t pu_pcaz
Float_t pu_nfromtruth
Float_t pu_nwrong
Float_t pu_ntrumaps
Float_t pu_ntruintt
Float_t pu_ntrutpc
Float_t pu_ntrumms
Float_t pu_ntrutpc1
Float_t pu_ntrutpc11
Float_t pu_ntrutpc2
Float_t pu_ntrutpc3
Float_t pu_layersfromtruth
Float_t pu_nhittpcall
Float_t pu_nhittpcin
Float_t pu_nhittpcmid
Float_t pu_nhittpcout
Float_t pu_nclusall
Float_t pu_nclustpc
Float_t pu_nclusintt
Float_t pu_nclusmaps
Float_t pu_nclusmms
Detailed Description
Definition at line 49 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 49 of file STrackCutStudy.h
Member Enumeration Documentation
enum STrackCutStudy::PHYSVAR
Enumerator:
PHI
ETA
PT
DELPHI
DELETA
DELPT
Definition at line 70 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 70 of file STrackCutStudy.h
enum STrackCutStudy::TRKVAR
Enumerator:
VX
VY
VZ
NMMS
NMAP
NINT
NTPC
QUAL
DCAXY
DCAZ
DELDCAXY
DELDCAZ
NCLUST
AVGCLUST
Definition at line 54 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 54 of file STrackCutStudy.h
enum STrackCutStudy::TYPE
Enumerator:
TRACK
TRUTH
WEIRD_ALL
WEIRD_SI
WEIRD_TPC
NORMAL
PILEUP
PRIMARY
NONPRIM
TRK_CUT
TRU_CUT
WEIRD_CUT
WEIRD_SI_CUT
WEIRD_TPC_CUT
NORM_CUT
PILE_CUT
PRIM_CUT
NONPRIM_CUT
Definition at line 78 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 78 of file STrackCutStudy.h
Constructor & Destructor Documentation
STrackCutStudy::STrackCutStudy ()
Definition at line 27 of file STrackCutStudy.cc.
View newest version in sPHENIX GitHub at line 27 of file STrackCutStudy.cc
References PT.
STrackCutStudy::~STrackCutStudy ()
Definition at line 243 of file STrackCutStudy.cc.
View newest version in sPHENIX GitHub at line 243 of file STrackCutStudy.cc
Member Function Documentation
void STrackCutStudy::Analyze ()
Definition at line 273 of file STrackCutStudy.cc.
View newest version in sPHENIX GitHub at line 273 of file STrackCutStudy.cc
References assert, deltaPhi(), eta, material_mapping_optimisation::flush, geta, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEntry(), gprimary, NPhysVar(), NTrkVar(), ActsTests::PropagationDatasets::phi, PT, physmon_track_finding_ttbar::pt, vx, vy, and vz.
Bool_t STrackCutStudy::ApplyCuts (const Bool_t isPrimary, const UInt_t trkNMVtx, const UInt_t trkNTpc, const Double_t trkVz, const Double_t trkDcaXY, const Double_t trkDcaZ, const Double_t trkQuality) private
Definition at line 20 of file STrackCutStudy.ana.h.
View newest version in sPHENIX GitHub at line 20 of file STrackCutStudy.ana.h
void STrackCutStudy::ConstructPlots (const Ssiz_t nToDraw, const Int_t typesToDraw[], const TString sDirToSaveTo, const TString sPlotLabel) private
Definition at line 110 of file STrackCutStudy.plot.h.
View newest version in sPHENIX GitHub at line 110 of file STrackCutStudy.plot.h
References AddEntry(), cd(), Close(), Data, Draw(), leg, NPanel(), NPhysVar(), NTrkVar(), NVtx, SetBorderMode(), SetBorderSize(), SetBottomMargin(), SetFillColor(), SetFillStyle(), SetFrameBorderMode(), SetLeftMargin(), SetLineColor(), SetLineStyle(), SetLogy(), SetRightMargin(), SetTextFont(), SetTopMargin(), and Write().
Bool_t STrackCutStudy::DoClusterCalculation () private
Definition at line 45 of file STrackCutStudy.ana.h.
View newest version in sPHENIX GitHub at line 45 of file STrackCutStudy.ana.h
void STrackCutStudy::End ()
Definition at line 545 of file STrackCutStudy.cc.
View newest version in sPHENIX GitHub at line 545 of file STrackCutStudy.cc
References cd(), and Close().
void STrackCutStudy::FillTrackHistograms (const Int_t type, const Double_t recoTrkVars[], const Double_t trueTrkVars[], const Double_t recoPhysVars[], const Double_t truePhysVars[]) private
Definition at line 702 of file STrackCutStudy.hist.h.
View newest version in sPHENIX GitHub at line 702 of file STrackCutStudy.hist.h
References assert, Fill(), NPhysVar(), NTrkVar(), PT, and parse_cmake_options::type.
void STrackCutStudy::FillTruthHistograms (const Int_t type, const Double_t recoTrkVars[], const Double_t trueTrkVars[], const Double_t recoPhysVars[], const Double_t truePhysVars[]) private
Definition at line 761 of file STrackCutStudy.hist.h.
View newest version in sPHENIX GitHub at line 761 of file STrackCutStudy.hist.h
References assert, Fill(), NPhysVar(), NTrkVar(), PT, and parse_cmake_options::type.
void STrackCutStudy::Init ()
Definition at line 259 of file STrackCutStudy.cc.
View newest version in sPHENIX GitHub at line 259 of file STrackCutStudy.cc
void STrackCutStudy::InitFiles () private
Definition at line 183 of file STrackCutStudy.io.h.
View newest version in sPHENIX GitHub at line 183 of file STrackCutStudy.io.h
References assert.
void STrackCutStudy::InitHists () private
Definition at line 20 of file STrackCutStudy.hist.h.
View newest version in sPHENIX GitHub at line 20 of file STrackCutStudy.hist.h
References Data, nEtaBins, NPhysVar(), NRange, NTrkVar(), and NType().
void STrackCutStudy::InitTuples () private
Definition at line 202 of file STrackCutStudy.io.h.
View newest version in sPHENIX GitHub at line 202 of file STrackCutStudy.io.h
References assert, charge(), eta, event, geta, gflavor, gprimary, gpx, gpy, gpz, gtrackID, gvt, nhittpcin, ActsTests::PropagationDatasets::phi, physmon_track_finding_ttbar::pt, seed, SetBranchAddress(), trackID, vx, vy, and vz.
void STrackCutStudy::MakeCutText () private
Definition at line 20 of file STrackCutStudy.plot.h.
View newest version in sPHENIX GitHub at line 20 of file STrackCutStudy.plot.h
References NVtx, SetFillColor(), SetFillStyle(), SetLineColor(), SetLineStyle(), and SetTextFont().
void STrackCutStudy::NormalizeHists () private
Definition at line 255 of file STrackCutStudy.hist.h.
View newest version in sPHENIX GitHub at line 255 of file STrackCutStudy.hist.h
References NPhysVar(), NTrkVar(), and NType().
void STrackCutStudy::SaveHists () private
Definition at line 440 of file STrackCutStudy.io.h.
View newest version in sPHENIX GitHub at line 440 of file STrackCutStudy.io.h
References cd(), Data, NPhysVar(), NTrkVar(), NType(), and Write().
void STrackCutStudy::SetBatchMode (const Bool_t doBatch = false)
Definition at line 20 of file STrackCutStudy.io.h.
View newest version in sPHENIX GitHub at line 20 of file STrackCutStudy.io.h
void STrackCutStudy::SetCutFlags (const Bool_t doPrimary, const Bool_t doTpc, const Bool_t doMVtx, const Bool_t doVz, const Bool_t doDcaXY, const Bool_t doDcaZ, const Bool_t doQuality)
Definition at line 119 of file STrackCutStudy.io.h.
View newest version in sPHENIX GitHub at line 119 of file STrackCutStudy.io.h
void STrackCutStudy::SetHistStyles () private
Definition at line 313 of file STrackCutStudy.hist.h.
View newest version in sPHENIX GitHub at line 313 of file STrackCutStudy.hist.h
References Data, FTxt(), GetXaxis(), GetYaxis(), GetZaxis(), NPhysVar(), NTrkVar(), NType(), SetFillColor(), SetFillStyle(), SetLineColor(), SetLineStyle(), SetMarkerColor(), SetMarkerStyle(), and SetTitle().
void STrackCutStudy::SetInputOutputFiles (const TString sEmbedOnlyInput, const TString sPileupInput, const TString sOutput)
Definition at line 34 of file STrackCutStudy.io.h.
View newest version in sPHENIX GitHub at line 34 of file STrackCutStudy.io.h
void STrackCutStudy::SetInputTuples (const TString sEmbedOnlyTuple, const TString sPileupTuple, const TString sEmbedOnlyClusterTuple = "")
Definition at line 50 of file STrackCutStudy.io.h.
View newest version in sPHENIX GitHub at line 50 of file STrackCutStudy.io.h
void STrackCutStudy::SetPlotText (const Ssiz_t nTxtE, const Ssiz_t nTxtP, const TString sTxtE[], const TString sTxtP[])
Definition at line 166 of file STrackCutStudy.io.h.
View newest version in sPHENIX GitHub at line 166 of file STrackCutStudy.io.h
void STrackCutStudy::SetStudyParameters (const Bool_t plots, const Bool_t pileup, const Bool_t intNorm, const Bool_t beforeCuts, const Bool_t avgClustCalc, const Double_t weirdFracMin, const Double_t weirdFracMax)
Definition at line 71 of file STrackCutStudy.io.h.
View newest version in sPHENIX GitHub at line 71 of file STrackCutStudy.io.h
void STrackCutStudy::SetTrackCuts (const pair< UInt_t, UInt_t > nMVtxRange, const pair< UInt_t, UInt_t > nTpcRange, const pair< Double_t, Double_t > vzRange, const pair< Double_t, Double_t > dcaXyRange, const pair< Double_t, Double_t > dcaZRange, const pair< Double_t, Double_t > qualityRange)
Definition at line 144 of file STrackCutStudy.io.h.
View newest version in sPHENIX GitHub at line 144 of file STrackCutStudy.io.h
Member Data Documentation
Float_t STrackCutStudy::charge private
Definition at line 212 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 212 of file STrackCutStudy.h
Float_t STrackCutStudy::chisq private
Definition at line 214 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 214 of file STrackCutStudy.h
Float_t STrackCutStudy::crossing private
Definition at line 202 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 202 of file STrackCutStudy.h
Float_t STrackCutStudy::dca2d private
Definition at line 234 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 234 of file STrackCutStudy.h
Float_t STrackCutStudy::dca2dsigma private
Definition at line 235 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 235 of file STrackCutStudy.h
Float_t STrackCutStudy::dca3dxy private
Definition at line 236 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 236 of file STrackCutStudy.h
Float_t STrackCutStudy::dca3dxysigma private
Definition at line 237 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 237 of file STrackCutStudy.h
Float_t STrackCutStudy::dca3dz private
Definition at line 238 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 238 of file STrackCutStudy.h
Float_t STrackCutStudy::dca3dzsigma private
Definition at line 239 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 239 of file STrackCutStudy.h
pair<Double_t, Double_t> STrackCutStudy::dcaXyCut private
Definition at line 194 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 194 of file STrackCutStudy.h
pair<Double_t, Double_t> STrackCutStudy::dcaZCut private
Definition at line 195 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 195 of file STrackCutStudy.h
Float_t STrackCutStudy::deltaeta private
Definition at line 210 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 210 of file STrackCutStudy.h
Float_t STrackCutStudy::deltaphi private
Definition at line 211 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 211 of file STrackCutStudy.h
Float_t STrackCutStudy::deltapt private
Definition at line 209 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 209 of file STrackCutStudy.h
Bool_t STrackCutStudy::doAvgClustCalc private
Definition at line 179 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 179 of file STrackCutStudy.h
Bool_t STrackCutStudy::doBeforeCuts private
Definition at line 178 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 178 of file STrackCutStudy.h
Bool_t STrackCutStudy::doDcaXyCut private
Definition at line 188 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 188 of file STrackCutStudy.h
Bool_t STrackCutStudy::doDcaZCut private
Definition at line 189 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 189 of file STrackCutStudy.h
Bool_t STrackCutStudy::doIntNorm private
Definition at line 177 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 177 of file STrackCutStudy.h
Bool_t STrackCutStudy::doMVtxCut private
Definition at line 185 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 185 of file STrackCutStudy.h
Bool_t STrackCutStudy::doPileup private
Definition at line 176 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 176 of file STrackCutStudy.h
Bool_t STrackCutStudy::doPrimaryCut private
Definition at line 184 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 184 of file STrackCutStudy.h
Bool_t STrackCutStudy::doQualityCut private
Definition at line 190 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 190 of file STrackCutStudy.h
Bool_t STrackCutStudy::doTpcCut private
Definition at line 186 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 186 of file STrackCutStudy.h
Bool_t STrackCutStudy::doVzCut private
Definition at line 187 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 187 of file STrackCutStudy.h
Float_t STrackCutStudy::eta private
Definition at line 207 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 207 of file STrackCutStudy.h
Float_t STrackCutStudy::event private
Definition at line 199 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 199 of file STrackCutStudy.h
TFile* STrackCutStudy::fInEO private
Definition at line 119 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 119 of file STrackCutStudy.h
TFile* STrackCutStudy::fInPU private
Definition at line 120 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 120 of file STrackCutStudy.h
TFile* STrackCutStudy::fOut private
Definition at line 118 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 118 of file STrackCutStudy.h
UInt_t STrackCutStudy::fTypeCol[NType] private
Definition at line 138 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 138 of file STrackCutStudy.h
UInt_t STrackCutStudy::fTypeMar[NType] private
Definition at line 139 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 139 of file STrackCutStudy.h
Float_t STrackCutStudy::gembed private
Definition at line 270 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 270 of file STrackCutStudy.h
Float_t STrackCutStudy::geta private
Definition at line 258 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 258 of file STrackCutStudy.h
Float_t STrackCutStudy::gflavor private
Definition at line 244 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 244 of file STrackCutStudy.h
Float_t STrackCutStudy::gfpx private
Definition at line 264 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 264 of file STrackCutStudy.h
Float_t STrackCutStudy::gfpy private
Definition at line 265 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 265 of file STrackCutStudy.h
Float_t STrackCutStudy::gfpz private
Definition at line 266 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 266 of file STrackCutStudy.h
Float_t STrackCutStudy::gfx private
Definition at line 267 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 267 of file STrackCutStudy.h
Float_t STrackCutStudy::gfy private
Definition at line 268 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 268 of file STrackCutStudy.h
Float_t STrackCutStudy::gfz private
Definition at line 269 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 269 of file STrackCutStudy.h
Float_t STrackCutStudy::gnhits private
Definition at line 245 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 245 of file STrackCutStudy.h
Float_t STrackCutStudy::gnintt private
Definition at line 247 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 247 of file STrackCutStudy.h
Float_t STrackCutStudy::gnlintt private
Definition at line 251 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 251 of file STrackCutStudy.h
Float_t STrackCutStudy::gnlmaps private
Definition at line 250 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 250 of file STrackCutStudy.h
Float_t STrackCutStudy::gnlmms private
Definition at line 253 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 253 of file STrackCutStudy.h
Float_t STrackCutStudy::gnltpc private
Definition at line 252 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 252 of file STrackCutStudy.h
Float_t STrackCutStudy::gnmaps private
Definition at line 246 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 246 of file STrackCutStudy.h
Float_t STrackCutStudy::gnmms private
Definition at line 249 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 249 of file STrackCutStudy.h
Float_t STrackCutStudy::gntpc private
Definition at line 248 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 248 of file STrackCutStudy.h
Float_t STrackCutStudy::gphi private
Definition at line 259 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 259 of file STrackCutStudy.h
Float_t STrackCutStudy::gprimary private
Definition at line 271 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 271 of file STrackCutStudy.h
Float_t STrackCutStudy::gpt private
Definition at line 257 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 257 of file STrackCutStudy.h
Float_t STrackCutStudy::gpx private
Definition at line 254 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 254 of file STrackCutStudy.h
Float_t STrackCutStudy::gpy private
Definition at line 255 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 255 of file STrackCutStudy.h
Float_t STrackCutStudy::gpz private
Definition at line 256 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 256 of file STrackCutStudy.h
Float_t STrackCutStudy::gtrackID private
Definition at line 243 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 243 of file STrackCutStudy.h
Float_t STrackCutStudy::gvt private
Definition at line 263 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 263 of file STrackCutStudy.h
Float_t STrackCutStudy::gvx private
Definition at line 260 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 260 of file STrackCutStudy.h
Float_t STrackCutStudy::gvy private
Definition at line 261 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 261 of file STrackCutStudy.h
Float_t STrackCutStudy::gvz private
Definition at line 262 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 262 of file STrackCutStudy.h
TH1D* STrackCutStudy::hPhysVar[NType][NPhysVar] private
Definition at line 157 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 157 of file STrackCutStudy.h
TH1D* STrackCutStudy::hPhysVarDiff[NType][NPhysVar] private
Definition at line 158 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 158 of file STrackCutStudy.h
TH1D* STrackCutStudy::hPhysVarFrac[NType][NPhysVar] private
Definition at line 159 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 159 of file STrackCutStudy.h
TH2D* STrackCutStudy::hPhysVarVsDcaXY[NType][NPhysVar] private
Definition at line 161 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 161 of file STrackCutStudy.h
TH2D* STrackCutStudy::hPhysVarVsDcaZ[NType][NPhysVar] private
Definition at line 162 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 162 of file STrackCutStudy.h
TH2D* STrackCutStudy::hPhysVarVsNTpc[NType][NPhysVar] private
Definition at line 160 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 160 of file STrackCutStudy.h
TH2D* STrackCutStudy::hPhysVarVsPtFrac[NType][NPhysVar] private
Definition at line 165 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 165 of file STrackCutStudy.h
TH2D* STrackCutStudy::hPhysVarVsPtReco[NType][NPhysVar] private
Definition at line 163 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 163 of file STrackCutStudy.h
TH2D* STrackCutStudy::hPhysVarVsPtTrue[NType][NPhysVar] private
Definition at line 164 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 164 of file STrackCutStudy.h
TH1D* STrackCutStudy::hTrkVar[NType][NTrkVar] private
Definition at line 146 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 146 of file STrackCutStudy.h
TH1D* STrackCutStudy::hTrkVarDiff[NType][NTrkVar] private
Definition at line 147 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 147 of file STrackCutStudy.h
TH1D* STrackCutStudy::hTrkVarFrac[NType][NTrkVar] private
Definition at line 148 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 148 of file STrackCutStudy.h
TH2D* STrackCutStudy::hTrkVarVsDcaXY[NType][NTrkVar] private
Definition at line 150 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 150 of file STrackCutStudy.h
TH2D* STrackCutStudy::hTrkVarVsDcaZ[NType][NTrkVar] private
Definition at line 151 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 151 of file STrackCutStudy.h
TH2D* STrackCutStudy::hTrkVarVsNTpc[NType][NTrkVar] private
Definition at line 149 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 149 of file STrackCutStudy.h
TH2D* STrackCutStudy::hTrkVarVsPtFrac[NType][NTrkVar] private
Definition at line 154 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 154 of file STrackCutStudy.h
TH2D* STrackCutStudy::hTrkVarVsPtReco[NType][NTrkVar] private
Definition at line 152 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 152 of file STrackCutStudy.h
TH2D* STrackCutStudy::hTrkVarVsPtTrue[NType][NTrkVar] private
Definition at line 153 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 153 of file STrackCutStudy.h
Bool_t STrackCutStudy::inBatchMode private
Definition at line 121 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 121 of file STrackCutStudy.h
Bool_t STrackCutStudy::isBeforeCuts[NType] private
Definition at line 135 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 135 of file STrackCutStudy.h
Bool_t STrackCutStudy::isPileup[NType] private
Definition at line 134 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 134 of file STrackCutStudy.h
Bool_t STrackCutStudy::isTruth[NType] private
Definition at line 133 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 133 of file STrackCutStudy.h
Float_t STrackCutStudy::layers private
Definition at line 229 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 229 of file STrackCutStudy.h
Float_t STrackCutStudy::layersfromtruth private
Definition at line 282 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 282 of file STrackCutStudy.h
Bool_t STrackCutStudy::makePlots private
Definition at line 175 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 175 of file STrackCutStudy.h
Float_t STrackCutStudy::nclusall private
Definition at line 287 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 287 of file STrackCutStudy.h
Float_t STrackCutStudy::nclusintt private
Definition at line 289 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 289 of file STrackCutStudy.h
Float_t STrackCutStudy::nclusmaps private
Definition at line 290 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 290 of file STrackCutStudy.h
Float_t STrackCutStudy::nclusmms private
Definition at line 291 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 291 of file STrackCutStudy.h
Float_t STrackCutStudy::nclustpc private
Definition at line 288 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 288 of file STrackCutStudy.h
Float_t STrackCutStudy::ndf private
Definition at line 215 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 215 of file STrackCutStudy.h
Float_t STrackCutStudy::nfromtruth private
Definition at line 272 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 272 of file STrackCutStudy.h
Float_t STrackCutStudy::nhits private
Definition at line 216 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 216 of file STrackCutStudy.h
Float_t STrackCutStudy::nhittpcall private
Definition at line 283 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 283 of file STrackCutStudy.h
Float_t STrackCutStudy::nhittpcin private
Definition at line 284 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 284 of file STrackCutStudy.h
Float_t STrackCutStudy::nhittpcmid private
Definition at line 285 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 285 of file STrackCutStudy.h
Float_t STrackCutStudy::nhittpcout private
Definition at line 286 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 286 of file STrackCutStudy.h
Float_t STrackCutStudy::nintt private
Definition at line 218 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 218 of file STrackCutStudy.h
Float_t STrackCutStudy::nlintt private
Definition at line 226 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 226 of file STrackCutStudy.h
Float_t STrackCutStudy::nlmaps private
Definition at line 225 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 225 of file STrackCutStudy.h
Float_t STrackCutStudy::nlmms private
Definition at line 228 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 228 of file STrackCutStudy.h
Float_t STrackCutStudy::nltpc private
Definition at line 227 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 227 of file STrackCutStudy.h
Float_t STrackCutStudy::nmaps private
Definition at line 217 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 217 of file STrackCutStudy.h
Float_t STrackCutStudy::nmms private
Definition at line 220 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 220 of file STrackCutStudy.h
pair<UInt_t, UInt_t> STrackCutStudy::nMVtxCut private
Definition at line 191 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 191 of file STrackCutStudy.h
Double_t STrackCutStudy::normalPtFracMax private
Definition at line 181 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 181 of file STrackCutStudy.h
Double_t STrackCutStudy::normalPtFracMin private
Definition at line 180 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 180 of file STrackCutStudy.h
TNtuple* STrackCutStudy::ntClustEO private
Definition at line 130 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 130 of file STrackCutStudy.h
Float_t STrackCutStudy::ntpc private
Definition at line 219 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 219 of file STrackCutStudy.h
Float_t STrackCutStudy::ntpc1 private
Definition at line 221 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 221 of file STrackCutStudy.h
Float_t STrackCutStudy::ntpc11 private
Definition at line 222 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 222 of file STrackCutStudy.h
Float_t STrackCutStudy::ntpc2 private
Definition at line 223 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 223 of file STrackCutStudy.h
Float_t STrackCutStudy::ntpc3 private
Definition at line 224 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 224 of file STrackCutStudy.h
pair<UInt_t, UInt_t> STrackCutStudy::nTpcCut private
Definition at line 192 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 192 of file STrackCutStudy.h
Float_t STrackCutStudy::ntruintt private
Definition at line 275 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 275 of file STrackCutStudy.h
Float_t STrackCutStudy::ntrumaps private
Definition at line 274 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 274 of file STrackCutStudy.h
Float_t STrackCutStudy::ntrumms private
Definition at line 277 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 277 of file STrackCutStudy.h
Float_t STrackCutStudy::ntrutpc private
Definition at line 276 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 276 of file STrackCutStudy.h
Float_t STrackCutStudy::ntrutpc1 private
Definition at line 278 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 278 of file STrackCutStudy.h
Float_t STrackCutStudy::ntrutpc11 private
Definition at line 279 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 279 of file STrackCutStudy.h
Float_t STrackCutStudy::ntrutpc2 private
Definition at line 280 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 280 of file STrackCutStudy.h
Float_t STrackCutStudy::ntrutpc3 private
Definition at line 281 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 281 of file STrackCutStudy.h
TNtuple* STrackCutStudy::ntTrkEO private
Definition at line 128 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 128 of file STrackCutStudy.h
TNtuple* STrackCutStudy::ntTrkPU private
Definition at line 129 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 129 of file STrackCutStudy.h
Ssiz_t STrackCutStudy::nTxtEO private
Definition at line 168 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 168 of file STrackCutStudy.h
Ssiz_t STrackCutStudy::nTxtPU private
Definition at line 169 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 169 of file STrackCutStudy.h
Float_t STrackCutStudy::nwrong private
Definition at line 273 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 273 of file STrackCutStudy.h
Float_t STrackCutStudy::pcax private
Definition at line 240 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 240 of file STrackCutStudy.h
Float_t STrackCutStudy::pcay private
Definition at line 241 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 241 of file STrackCutStudy.h
Float_t STrackCutStudy::pcaz private
Definition at line 242 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 242 of file STrackCutStudy.h
Float_t STrackCutStudy::phi private
Definition at line 208 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 208 of file STrackCutStudy.h
Bool_t STrackCutStudy::physVarHasTruVal[NPhysVar] private
Definition at line 137 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 137 of file STrackCutStudy.h
Float_t STrackCutStudy::pt private
Definition at line 206 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 206 of file STrackCutStudy.h
TPaveText* STrackCutStudy::ptCut private
Definition at line 170 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 170 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_charge private
Definition at line 344 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 344 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_chisq private
Definition at line 346 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 346 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_dca2d private
Definition at line 366 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 366 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_dca2dsigma private
Definition at line 367 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 367 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_dca3dxy private
Definition at line 368 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 368 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_dca3dxysigma private
Definition at line 369 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 369 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_dca3dz private
Definition at line 370 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 370 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_dca3dzsigma private
Definition at line 371 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 371 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_deltaeta private
Definition at line 342 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 342 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_deltaphi private
Definition at line 343 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 343 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_deltapt private
Definition at line 341 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 341 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_eta private
Definition at line 339 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 339 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_event private
Definition at line 294 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 294 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gembed private
Definition at line 332 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 332 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_geta private
Definition at line 320 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 320 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gflavor private
Definition at line 298 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 298 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gfpx private
Definition at line 326 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 326 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gfpy private
Definition at line 327 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 327 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gfpz private
Definition at line 328 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 328 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gfx private
Definition at line 329 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 329 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gfy private
Definition at line 330 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 330 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gfz private
Definition at line 331 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 331 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gnhits private
Definition at line 299 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 299 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gnintt private
Definition at line 301 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 301 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gnintt1 private
Definition at line 303 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 303 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gnintt2 private
Definition at line 304 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 304 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gnintt3 private
Definition at line 305 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 305 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gnintt4 private
Definition at line 306 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 306 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gnintt5 private
Definition at line 307 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 307 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gnintt6 private
Definition at line 308 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 308 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gnintt7 private
Definition at line 309 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 309 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gnintt8 private
Definition at line 310 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 310 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gnlintt private
Definition at line 313 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 313 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gnlmaps private
Definition at line 312 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 312 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gnlmms private
Definition at line 315 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 315 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gnltpc private
Definition at line 314 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 314 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gnmaps private
Definition at line 300 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 300 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gnmms private
Definition at line 302 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 302 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gntpc private
Definition at line 311 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 311 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gntracks private
Definition at line 296 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 296 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gphi private
Definition at line 321 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 321 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gprimary private
Definition at line 333 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 333 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gpt private
Definition at line 319 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 319 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gpx private
Definition at line 316 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 316 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gpy private
Definition at line 317 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 317 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gpz private
Definition at line 318 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 318 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gtrackID private
Definition at line 297 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 297 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gvt private
Definition at line 325 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 325 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gvx private
Definition at line 322 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 322 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gvy private
Definition at line 323 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 323 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_gvz private
Definition at line 324 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 324 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_layers private
Definition at line 349 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 349 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_layersfromtruth private
Definition at line 385 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 385 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nclusall private
Definition at line 390 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 390 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nclusintt private
Definition at line 392 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 392 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nclusmaps private
Definition at line 393 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 393 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nclusmms private
Definition at line 394 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 394 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nclustpc private
Definition at line 391 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 391 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_ndf private
Definition at line 347 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 347 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nfromtruth private
Definition at line 375 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 375 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nhits private
Definition at line 348 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 348 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nhittpcall private
Definition at line 386 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 386 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nhittpcin private
Definition at line 387 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 387 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nhittpcmid private
Definition at line 388 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 388 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nhittpcout private
Definition at line 389 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 389 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nintt private
Definition at line 351 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 351 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nlintt private
Definition at line 359 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 359 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nlmaps private
Definition at line 358 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 358 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nlmms private
Definition at line 361 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 361 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nltpc private
Definition at line 360 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 360 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nmaps private
Definition at line 350 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 350 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nmms private
Definition at line 353 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 353 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_ntpc private
Definition at line 352 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 352 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_ntpc1 private
Definition at line 354 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 354 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_ntpc11 private
Definition at line 355 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 355 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_ntpc2 private
Definition at line 356 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 356 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_ntpc3 private
Definition at line 357 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 357 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_ntruintt private
Definition at line 378 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 378 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_ntrumaps private
Definition at line 377 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 377 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_ntrumms private
Definition at line 380 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 380 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_ntrutpc private
Definition at line 379 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 379 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_ntrutpc1 private
Definition at line 381 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 381 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_ntrutpc11 private
Definition at line 382 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 382 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_ntrutpc2 private
Definition at line 383 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 383 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_ntrutpc3 private
Definition at line 384 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 384 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_nwrong private
Definition at line 376 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 376 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_pcax private
Definition at line 372 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 372 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_pcay private
Definition at line 373 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 373 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_pcaz private
Definition at line 374 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 374 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_phi private
Definition at line 340 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 340 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_pt private
Definition at line 338 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 338 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_px private
Definition at line 335 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 335 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_py private
Definition at line 336 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 336 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_pz private
Definition at line 337 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 337 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_quality private
Definition at line 345 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 345 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_seed private
Definition at line 295 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 295 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_trackID private
Definition at line 334 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 334 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_vertexID private
Definition at line 362 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 362 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_vx private
Definition at line 363 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 363 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_vy private
Definition at line 364 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 364 of file STrackCutStudy.h
Float_t STrackCutStudy::pu_vz private
Definition at line 365 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 365 of file STrackCutStudy.h
Float_t STrackCutStudy::px private
Definition at line 203 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 203 of file STrackCutStudy.h
Float_t STrackCutStudy::py private
Definition at line 204 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 204 of file STrackCutStudy.h
Float_t STrackCutStudy::pz private
Definition at line 205 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 205 of file STrackCutStudy.h
Float_t STrackCutStudy::quality private
Definition at line 213 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 213 of file STrackCutStudy.h
pair<Double_t, Double_t> STrackCutStudy::qualityCut private
Definition at line 196 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 196 of file STrackCutStudy.h
Float_t STrackCutStudy::seed private
Definition at line 200 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 200 of file STrackCutStudy.h
TString STrackCutStudy::sInClustEO private
Definition at line 126 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 126 of file STrackCutStudy.h
TString STrackCutStudy::sInFileEO private
Definition at line 122 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 122 of file STrackCutStudy.h
TString STrackCutStudy::sInFilePU private
Definition at line 123 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 123 of file STrackCutStudy.h
TString STrackCutStudy::sInTupleEO private
Definition at line 124 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 124 of file STrackCutStudy.h
TString STrackCutStudy::sInTuplePU private
Definition at line 125 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 125 of file STrackCutStudy.h
TString STrackCutStudy::sOutfile private
Definition at line 127 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 127 of file STrackCutStudy.h
TString STrackCutStudy::sPhysVars[NPhysVar] private
Definition at line 143 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 143 of file STrackCutStudy.h
TString STrackCutStudy::sTrkLabels[NType] private
Definition at line 141 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 141 of file STrackCutStudy.h
TString STrackCutStudy::sTrkNames[NType] private
Definition at line 140 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 140 of file STrackCutStudy.h
TString STrackCutStudy::sTrkVars[NTrkVar] private
Definition at line 142 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 142 of file STrackCutStudy.h
vector<TString> STrackCutStudy::sTxtEO private
Definition at line 171 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 171 of file STrackCutStudy.h
vector<TString> STrackCutStudy::sTxtPU private
Definition at line 172 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 172 of file STrackCutStudy.h
Float_t STrackCutStudy::trackID private
Definition at line 201 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 201 of file STrackCutStudy.h
Bool_t STrackCutStudy::trkVarHasTruVal[NTrkVar] private
Definition at line 136 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 136 of file STrackCutStudy.h
Float_t STrackCutStudy::vertexID private
Definition at line 230 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 230 of file STrackCutStudy.h
Float_t STrackCutStudy::vx private
Definition at line 231 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 231 of file STrackCutStudy.h
Float_t STrackCutStudy::vy private
Definition at line 232 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 232 of file STrackCutStudy.h
Float_t STrackCutStudy::vz private
Definition at line 233 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 233 of file STrackCutStudy.h
pair<Double_t, Double_t> STrackCutStudy::vzCut private
Definition at line 193 of file STrackCutStudy.h.
View newest version in sPHENIX GitHub at line 193 of file STrackCutStudy.h
The documentation for this class was generated from the following files:
analysis/blob/master/AndersonAnalysisModules/TrackStudies/STrackCutStudy/src/STrackCutStudy.h
analysis/blob/master/AndersonAnalysisModules/TrackStudies/STrackCutStudy/src/STrackCutStudy.ana.h
analysis/blob/master/AndersonAnalysisModules/TrackStudies/STrackCutStudy/src/STrackCutStudy.cc
analysis/blob/master/AndersonAnalysisModules/TrackStudies/STrackCutStudy/src/STrackCutStudy.hist.h
analysis/blob/master/AndersonAnalysisModules/TrackStudies/STrackCutStudy/src/STrackCutStudy.io.h
analysis/blob/master/AndersonAnalysisModules/TrackStudies/STrackCutStudy/src/STrackCutStudy.plot.h