Analysis Software: G4BEAMLINE Namespace Reference
G4BEAMLINE Namespace Reference
Functions
PHG4CylinderSubsystem * ForwardBeamLineEnclosure (nullptr)
PHG4CylinderSubsystem * BackwardBeamLineEnclosure (nullptr)
Variables
double starting_z = G4PIPE::max_z + 2*no_overlapp
double enclosure_z_max = 2050. + (800-starting_z)
double enclosure_r_max = 30.
double enclosure_center = 0.5 * (starting_z + enclosure_z_max)
double skin_thickness = 0.
int pipe_id_offset = 100
int roman_pot_pipe_id_offset = 200
Function Documentation
PHG4CylinderSubsystem* G4BEAMLINE::BackwardBeamLineEnclosure (nullptr)
Referenced by BeamLineDefineBeamPipe(), BeamLineDefineMagnets(), and ZDCSetup().
PHG4CylinderSubsystem* G4BEAMLINE::ForwardBeamLineEnclosure (nullptr)
Referenced by BeamLineDefineBeamPipe(), BeamLineDefineMagnets(), and ZDCSetup().
Variable Documentation
double G4BEAMLINE::enclosure_center = 0.5 * (starting_z + enclosure_z_max)
Definition at line 43 of file G4_BeamLine.C.
View newest version in sPHENIX GitHub at line 43 of file G4_BeamLine.C
Referenced by BeamLineDefineBeamPipe(), BeamLineDefineMagnets(), PHG4SpacalPrototype4Detector::Construct_AzimuthalSeg(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), and ZDCSetup().
double G4BEAMLINE::enclosure_r_max = 30.
Definition at line 42 of file G4_BeamLine.C.
View newest version in sPHENIX GitHub at line 42 of file G4_BeamLine.C
Referenced by BeamLineDefineMagnets(), and BeamLineInit().
double G4BEAMLINE::enclosure_z_max = 2050. + (800-starting_z)
Definition at line 41 of file G4_BeamLine.C.
View newest version in sPHENIX GitHub at line 41 of file G4_BeamLine.C
Referenced by BeamLineDefineMagnets(), and BeamLineInit().
int G4BEAMLINE::pipe_id_offset = 100
Definition at line 45 of file G4_BeamLine.C.
View newest version in sPHENIX GitHub at line 45 of file G4_BeamLine.C
Referenced by BeamLineDefineBeamPipe().
int G4BEAMLINE::roman_pot_pipe_id_offset = 200
Definition at line 46 of file G4_BeamLine.C.
View newest version in sPHENIX GitHub at line 46 of file G4_BeamLine.C
Referenced by BeamLineDefineBeamPipe().
double G4BEAMLINE::skin_thickness = 0.
Definition at line 44 of file G4_BeamLine.C.
View newest version in sPHENIX GitHub at line 44 of file G4_BeamLine.C
Referenced by BeamLineDefineMagnets(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_SinglePhotonGen_sPHENIX(), and Fun4All_SinglePi0Gen_sPHENIX().
double G4BEAMLINE::starting_z = G4PIPE::max_z + 2*no_overlapp
Definition at line 40 of file G4_BeamLine.C.
View newest version in sPHENIX GitHub at line 40 of file G4_BeamLine.C
Referenced by BeamLineDefineMagnets(), and PHG4TpcEndCapDetector::ConstructEndCapAssembly().