Analysis Software: TpcClusterZCrossingCorrection Class Reference
TpcClusterZCrossingCorrection Class Reference
#include <coresoftware/blob/master/offline/packages/tpc/TpcClusterZCrossingCorrection.h>
Public Member Functions
TpcClusterZCrossingCorrection ()
float correctZ (float zinit, unsigned int side, short int crossing) const
Static Public Attributes
static float _vdrift = 8.0e-03
Private Attributes
float _time_between_crossings = 106
Detailed Description
Definition at line 10 of file TpcClusterZCrossingCorrection.h.
View newest version in sPHENIX GitHub at line 10 of file TpcClusterZCrossingCorrection.h
Constructor & Destructor Documentation
TpcClusterZCrossingCorrection::TpcClusterZCrossingCorrection ()
Definition at line 15 of file TpcClusterZCrossingCorrection.cc.
View newest version in sPHENIX GitHub at line 15 of file TpcClusterZCrossingCorrection.cc
Member Function Documentation
float TpcClusterZCrossingCorrection::correctZ (float zinit, unsigned int side, short int crossing) const
Definition at line 18 of file TpcClusterZCrossingCorrection.cc.
View newest version in sPHENIX GitHub at line 18 of file TpcClusterZCrossingCorrection.cc
References _time_between_crossings, and _vdrift.
Referenced by TpcSpaceChargeReconstruction::get_global_position(), PHMicromegasTpcTrackMatching::getGlobalPosition(), PHTpcResiduals::getGlobalPosition(), PHGenFitTrkFitter::getGlobalPosition(), MakeSourceLinks::getSourceLinks(), ActsAlignmentStates::makeTpcGlobalCorrections(), and HelicalFitter::makeTpcGlobalCorrections().
Member Data Documentation
float TpcClusterZCrossingCorrection::_time_between_crossings = 106 private
Definition at line 22 of file TpcClusterZCrossingCorrection.h.
View newest version in sPHENIX GitHub at line 22 of file TpcClusterZCrossingCorrection.h
Referenced by correctZ().
float TpcClusterZCrossingCorrection::_vdrift = 8.0e-03 static
Definition at line 18 of file TpcClusterZCrossingCorrection.h.
View newest version in sPHENIX GitHub at line 18 of file TpcClusterZCrossingCorrection.h
Referenced by correctZ(), and TPCInit().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/tpc/TpcClusterZCrossingCorrection.h
coresoftware/blob/master/offline/packages/tpc/TpcClusterZCrossingCorrection.cc