Analysis Software: coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc File Reference
PHG4MvtxHitReco.cc File Reference
#include "PHG4MvtxHitReco.h"
#include <mvtx/CylinderGeom_Mvtx.h>
#include <mvtx/MvtxHitPruner.h>
#include <trackbase/MvtxDefs.h>
#include <trackbase/TrkrDefs.h>
#include <trackbase/TrkrHit.h>
#include <trackbase/TrkrHitSet.h>
#include <trackbase/TrkrHitSetContainer.h>
#include <trackbase/TrkrHitSetContainerv1.h>
#include <trackbase/TrkrHitTruthAssoc.h>
#include <trackbase/TrkrHitTruthAssocv1.h>
#include <trackbase/TrkrHitv2.h>
#include <g4tracking/TrkrTruthTrack.h>
#include <g4tracking/TrkrTruthTrackContainer.h>
#include <g4tracking/TrkrTruthTrackContainerv1.h>
#include <trackbase/ClusHitsVerbosev1.h>
#include <trackbase/TrkrClusterContainer.h>
#include <trackbase/TrkrClusterContainerv4.h>
#include <trackbase/TrkrClusterv4.h>
#include <g4detectors/PHG4CylinderGeom.h>
#include <g4detectors/PHG4CylinderGeomContainer.h>
#include <g4main/PHG4Hit.h>
#include <g4main/PHG4HitContainer.h>
#include <g4main/PHG4Utils.h>
#include <g4main/PHG4TruthInfoContainer.h>
#include <fun4all/Fun4AllReturnCodes.h>
#include <fun4all/SubsysReco.h>
#include <phool/PHCompositeNode.h>
#include <phool/PHIODataNode.h>
#include <phool/PHNode.h>
#include <phool/PHNodeIterator.h>
#include <phool/PHObject.h>
#include <phool/PHRandomSeed.h>
#include <phool/getClass.h>
#include <phool/phool.h>
#include <G4SystemOfUnits.hh>
#include <TVector3.h>
#include <cassert>
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <memory>
#include <vector>
#include <set>
Functions
m_rng reset (gsl_rng_alloc(gsl_rng_mt19937))
gsl_rng_set (m_rng.get(), seed)
InitializeParameters ()
Function Documentation
gsl_rng_set (m_rng. get(), seed)
Referenced by _embed_only(), Fun4AllDstPileupInputManager::Fun4AllDstPileupInputManager(), Fun4AllHepMCPileupInputManager::Fun4AllHepMCPileupInputManager(), Fun4AllSingleDstPileupInputManager::Fun4AllSingleDstPileupInputManager(), HijingShowerSize::HijingShowerSize(), ReactionPlaneAfterburner::Init(), HepMCNodeReader::Init(), FermimotionAfterburner::Init(), CaloWaveformSim::Init(), MbdVertexFastSimReco::InitRun(), GlobalVertexFastSimReco::InitRun(), JetProbeMaker::JetProbeMaker(), MbdDigitization::MbdDigitization(), PHEvtGenRandomEngine::PHEvtGenRandomEngine(), PHG4InttDigitizer::PHG4InttDigitizer(), PHG4MicromegasDigitizer::PHG4MicromegasDigitizer(), PHG4MicromegasHitReco::PHG4MicromegasHitReco(), PHG4MvtxDigitizer::PHG4MvtxDigitizer(), PHG4ParticleGeneratorBase::PHG4ParticleGeneratorBase(), PHG4TpcDigitizer::PHG4TpcDigitizer(), PHG4TpcPadPlaneReadout::PHG4TpcPadPlaneReadout(), PHG4ZDCSteppingAction::PHG4ZDCSteppingAction(), PHHepMCGenHelper::PHHepMCGenHelper(), PHTruthSiliconAssociation::PHTruthSiliconAssociation(), PHTruthTrackSeeding::PHTruthTrackSeeding(), RawTowerDigitizer::RawTowerDigitizer(), RawTowerDigitizer::set_seed(), PHG4ParticleGeneratorBase::set_seed(), PHG4TpcElectronDrift::set_seed(), SigmaTimingNtuple::SigmaTimingNtuple(), and simulateTimestamps().
InitializeParameters ()
m_rng reset (gsl_rng_alloc(gsl_rng_mt19937))
Referenced by G__ExampleAnalysisModule_Dict_578_0_2(), G__ExampleAnalysisModule_Dict_579_0_2(), and Fun4AllServer::ResetNodeTree().