Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Examples/Io/Root/SimhitReaderWriterTests.cpp File Reference
SimhitReaderWriterTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Tests/CommonHelpers/WhiteBoardUtilities.hpp"
#include "Acts/Utilities/Zip.hpp"
#include "ActsExamples/EventData/SimHit.hpp"
#include "ActsExamples/Io/Root/RootSimHitReader.hpp"
#include "ActsExamples/Io/Root/RootSimHitWriter.hpp"
#include <fstream>
#include <iostream>
#include <random>
Functions
std::mt19937 gen (23)
auto makeTestSimhits (std::size_t nSimHits)
BOOST_AUTO_TEST_CASE (RoundTripTest)
Function Documentation
BOOST_AUTO_TEST_CASE (RoundTripTest)
Definition at line 51 of file SimhitReaderWriterTests.cpp.
View newest version in sPHENIX GitHub at line 51 of file SimhitReaderWriterTests.cpp
References check_fpe_masks::check(), CHECK_CLOSE_ABS, Acts::UnitConstants::e, ActsExamples::RootSimHitWriter::Config::filePath, ActsExamples::RootSimHitReader::Config::filePath, ActsExamples::IReader::finalize(), ActsExamples::RootSimHitWriter::finalize(), ActsExamples::RootSimHitWriter::Config::inputSimHits, makeTestSimhits(), summary::reader, check_smearing_config::ref, ActsExamples::RootSimHitReader::Config::simHitCollection, train_ambiguity_solver::test, Acts::Logging::WARNING, writer, and Acts::zip().
std::mt19937 gen (23)
Referenced by Acts::Python::addGenerators(), Acts::Python::addPythia8(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), ConfigureInput(), ConstructGeometry(), EMRandom::EMRandom(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_Calos(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Geantino(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_MyDetector(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_G4_Write_Dst(), Fun4All_Generator_Display(), Fun4All_single_particle(), getRndDouble(), getRndInt(), Jin_BJet(), makeTestSimhits(), ReadEICFiles::process_event(), sampleFromMultivariate(), ActsExamples::Simulation::setupInput(), strf(), and Wrapper().
auto makeTestSimhits (std::size_t nSimHits)
Definition at line 27 of file SimhitReaderWriterTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file SimhitReaderWriterTests.cpp
References gen(), i, index, train_ambiguity_solver::pid, and Acts::Test::pos4().
Referenced by BOOST_AUTO_TEST_CASE().