Analysis Software: PHG4TpcPadBaselineShift Class Reference
PHG4TpcPadBaselineShift Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcPadBaselineShift.h>
Public Member Functions
PHG4TpcPadBaselineShift (const std::string &name="PHG4TpcPadBaselineShift")
virtual ~PHG4TpcPadBaselineShift ()
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void setScale (float CScale)
void setFileName (const std::string &filename)
void writeTree (int f_writeTree)
void set_drift_velocity (float vd)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
bool is_in_sector_boundary (int phibin, int sector, PHG4TpcCylinderGeom *layergeom)
Private Attributes
float _hit_z = NAN
float _hit_r = NAN
float _hit_phi = NAN
float _hit_e = NAN
int _hit_adc = INT_MIN
int _hit_adc_bls = INT_MIN
int _hit_layer = INT_MIN
int _hit_sector = INT_MIN
TrkrHitSetContainer * m_hits = nullptr
TrkrClusterContainer * m_clusterlist = nullptr
TrkrClusterHitAssoc * m_clusterhitassoc = nullptr
ActsSurfaceMaps * m_surfMaps = nullptr
ActsTrackingGeometry * m_tGeometry = nullptr
int _writeTree = 0
double SectorFiducialCut = 0.5
int NZBinsMax = 0
float _CScale = 1.
double AdcClockPeriod = 53.0
unsigned int MaxTBins = 498
float _drift_velocity = 8.0e-03
TFile * outfile = nullptr
std::string _filename = "./hitsBLS.root"
TTree * _rawHits = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 25 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 25 of file PHG4TpcPadBaselineShift.h
Constructor & Destructor Documentation
PHG4TpcPadBaselineShift::PHG4TpcPadBaselineShift (const std::string & name = "PHG4TpcPadBaselineShift")
Definition at line 84 of file PHG4TpcPadBaselineShift.cc.
View newest version in sPHENIX GitHub at line 84 of file PHG4TpcPadBaselineShift.cc
PHG4TpcPadBaselineShift::~PHG4TpcPadBaselineShift () virtual
Definition at line 115 of file PHG4TpcPadBaselineShift.cc.
View newest version in sPHENIX GitHub at line 115 of file PHG4TpcPadBaselineShift.cc
Member Function Documentation
int PHG4TpcPadBaselineShift::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 401 of file PHG4TpcPadBaselineShift.cc.
View newest version in sPHENIX GitHub at line 401 of file PHG4TpcPadBaselineShift.cc
References _writeTree, Fun4AllReturnCodes::EVENT_OK, and outfile.
int PHG4TpcPadBaselineShift::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 121 of file PHG4TpcPadBaselineShift.cc.
View newest version in sPHENIX GitHub at line 121 of file PHG4TpcPadBaselineShift.cc
References _filename, _hit_adc, _hit_adc_bls, _hit_e, _hit_layer, _hit_phi, _hit_r, _hit_sector, _hit_z, _rawHits, _writeTree, and outfile.
int PHG4TpcPadBaselineShift::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 151 of file PHG4TpcPadBaselineShift.cc.
View newest version in sPHENIX GitHub at line 151 of file PHG4TpcPadBaselineShift.cc
References Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and PHWHERE.
bool PHG4TpcPadBaselineShift::is_in_sector_boundary (int phibin, int sector, PHG4TpcCylinderGeom * layergeom) private
Definition at line 90 of file PHG4TpcPadBaselineShift.cc.
View newest version in sPHENIX GitHub at line 90 of file PHG4TpcPadBaselineShift.cc
References double(), PHG4TpcCylinderGeom::get_phibins(), PHG4TpcCylinderGeom::get_radius(), and SectorFiducialCut.
int PHG4TpcPadBaselineShift::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 168 of file PHG4TpcPadBaselineShift.cc.
View newest version in sPHENIX GitHub at line 168 of file PHG4TpcPadBaselineShift.cc
References _CScale, _drift_velocity, _hit_adc, _hit_adc_bls, _hit_e, _hit_layer, _hit_phi, _hit_r, _hit_sector, _hit_z, _rawHits, _writeTree, Fun4AllReturnCodes::ABORTRUN, AdcClockPeriod, Fun4AllReturnCodes::EVENT_OK, std::tr1::f1, PHNodeIterator::findFirst(), TpcDefs::genHitKey(), PHG4TpcCylinderGeom::get_phibins(), PHG4TpcCylinderGeom::get_phicenter(), PHG4TpcCylinderGeom::get_radius(), PHG4TpcCylinderGeom::get_zbins(), PHG4TpcCylinderGeom::get_zcenter(), TrkrHit::getEnergy(), TrkrHitSet::getHits(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4TpcCylinderGeomContainer::GetLayerCellGeom(), TpcDefs::getPad(), TpcDefs::getSectorId(), TpcDefs::getSide(), TpcDefs::getTBin(), layer, m_clusterhitassoc, m_clusterlist, m_hits, m_surfMaps, m_tGeometry, MaxTBins, NZBinsMax, MATSCAN::phibins, PHWHERE, pi, TrkrHit::setAdc(), TrkrClusterContainer::size(), TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
void PHG4TpcPadBaselineShift::set_drift_velocity (float vd) inline
Definition at line 47 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4TpcPadBaselineShift.h
References _drift_velocity.
void PHG4TpcPadBaselineShift::setFileName (const std::string & filename)
Definition at line 431 of file PHG4TpcPadBaselineShift.cc.
View newest version in sPHENIX GitHub at line 431 of file PHG4TpcPadBaselineShift.cc
References _filename, and filename.
void PHG4TpcPadBaselineShift::setScale (float CScale)
Definition at line 426 of file PHG4TpcPadBaselineShift.cc.
View newest version in sPHENIX GitHub at line 426 of file PHG4TpcPadBaselineShift.cc
References _CScale.
void PHG4TpcPadBaselineShift::writeTree (int f_writeTree)
Definition at line 436 of file PHG4TpcPadBaselineShift.cc.
View newest version in sPHENIX GitHub at line 436 of file PHG4TpcPadBaselineShift.cc
References _writeTree.
Member Data Documentation
float PHG4TpcPadBaselineShift::_CScale = 1. private
Definition at line 73 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4TpcPadBaselineShift.h
Referenced by process_event(), and setScale().
float PHG4TpcPadBaselineShift::_drift_velocity = 8.0e-03 private
Definition at line 77 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4TpcPadBaselineShift.h
Referenced by process_event(), and set_drift_velocity().
std::string PHG4TpcPadBaselineShift::_filename = "./hitsBLS.root" private
Definition at line 80 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 80 of file PHG4TpcPadBaselineShift.h
Referenced by Init(), and setFileName().
int PHG4TpcPadBaselineShift::_hit_adc = INT_MIN private
Definition at line 55 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4TpcPadBaselineShift.h
Referenced by Init(), and process_event().
int PHG4TpcPadBaselineShift::_hit_adc_bls = INT_MIN private
Definition at line 56 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4TpcPadBaselineShift.h
Referenced by Init(), and process_event().
float PHG4TpcPadBaselineShift::_hit_e = NAN private
Definition at line 54 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4TpcPadBaselineShift.h
Referenced by Init(), and process_event().
int PHG4TpcPadBaselineShift::_hit_layer = INT_MIN private
Definition at line 57 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4TpcPadBaselineShift.h
Referenced by Init(), and process_event().
float PHG4TpcPadBaselineShift::_hit_phi = NAN private
Definition at line 53 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4TpcPadBaselineShift.h
Referenced by Init(), and process_event().
float PHG4TpcPadBaselineShift::_hit_r = NAN private
Definition at line 52 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4TpcPadBaselineShift.h
Referenced by Init(), and process_event().
int PHG4TpcPadBaselineShift::_hit_sector = INT_MIN private
Definition at line 58 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4TpcPadBaselineShift.h
Referenced by Init(), and process_event().
float PHG4TpcPadBaselineShift::_hit_z = NAN private
Definition at line 51 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4TpcPadBaselineShift.h
Referenced by Init(), and process_event().
TTree* PHG4TpcPadBaselineShift::_rawHits = nullptr private
Definition at line 82 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 82 of file PHG4TpcPadBaselineShift.h
Referenced by Init(), and process_event().
int PHG4TpcPadBaselineShift::_writeTree = 0 private
Definition at line 68 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4TpcPadBaselineShift.h
Referenced by End(), Init(), process_event(), and writeTree().
double PHG4TpcPadBaselineShift::AdcClockPeriod = 53.0 private
Definition at line 75 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4TpcPadBaselineShift.h
Referenced by process_event().
TrkrClusterHitAssoc* PHG4TpcPadBaselineShift::m_clusterhitassoc = nullptr private
Definition at line 62 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4TpcPadBaselineShift.h
Referenced by process_event().
TrkrClusterContainer* PHG4TpcPadBaselineShift::m_clusterlist = nullptr private
Definition at line 61 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4TpcPadBaselineShift.h
Referenced by process_event().
TrkrHitSetContainer* PHG4TpcPadBaselineShift::m_hits = nullptr private
Definition at line 60 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4TpcPadBaselineShift.h
Referenced by process_event().
ActsSurfaceMaps* PHG4TpcPadBaselineShift::m_surfMaps = nullptr private
Definition at line 63 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4TpcPadBaselineShift.h
Referenced by process_event().
ActsTrackingGeometry* PHG4TpcPadBaselineShift::m_tGeometry = nullptr private
Definition at line 64 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4TpcPadBaselineShift.h
Referenced by process_event().
unsigned int PHG4TpcPadBaselineShift::MaxTBins = 498 private
Definition at line 76 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4TpcPadBaselineShift.h
Referenced by process_event().
int PHG4TpcPadBaselineShift::NZBinsMax = 0 private
Definition at line 72 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4TpcPadBaselineShift.h
Referenced by process_event().
TFile* PHG4TpcPadBaselineShift::outfile = nullptr private
Definition at line 79 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4TpcPadBaselineShift.h
Referenced by End(), and Init().
double PHG4TpcPadBaselineShift::SectorFiducialCut = 0.5 private
Definition at line 69 of file PHG4TpcPadBaselineShift.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4TpcPadBaselineShift.h
Referenced by is_in_sector_boundary().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcPadBaselineShift.h
coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcPadBaselineShift.cc