Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Plugins/DD4hep/DD4hepCylinderLayerStructureTests.cpp File Reference
DD4hepCylinderLayerStructureTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Plugins/DD4hep/DD4hepDetectorSurfaceFactory.hpp"
#include "Acts/Plugins/DD4hep/DD4hepLayerStructure.hpp"
#include "Acts/Surfaces/SurfaceBounds.hpp"
#include "Acts/Tests/CommonHelpers/CylindricalTrackingGeometry.hpp"
#include "Acts/Utilities/Logger.hpp"
#include <fstream>
#include <string>
#include <DD4hep/DetElement.h>
#include <DD4hep/DetFactoryHelper.h>
#include <DD4hep/Detector.h>
#include <XML/Utilities.h>
#include <XMLFragments.hpp>
#include "DD4hepTestsHelper.hpp"
Functions
BOOST_AUTO_TEST_CASE (DD4hepPluginBeampipeStructure)
BOOST_AUTO_TEST_CASE (DD4hepPluginCylinderLayerStructure)
Variables
Acts::GeometryContext tContext
Acts::Test::CylindricalTrackingGeometry cGeometry
const char * beampipe_head_xml
const char * cylinder_layer_head_xml
const char * tail_xml
const char * indent_12_xml = " "
Function Documentation
BOOST_AUTO_TEST_CASE (DD4hepPluginBeampipeStructure)
Definition at line 47 of file DD4hepCylinderLayerStructureTests.cpp.
View newest version in sPHENIX GitHub at line 47 of file DD4hepCylinderLayerStructureTests.cpp
References beampipe_head_xml, Acts::Logging::DEBUG, end_xml, Acts::getDefaultLogger(), head_xml, indent_12_xml, Acts::Experimental::DD4hepLayerStructure::Options::logLevel, testing::internal::move(), Acts::Experimental::DD4hepLayerStructure::Options::name, tail_xml, physmon_ckf_tracking::u, Acts::Logging::VERBOSE, and volumes.
BOOST_AUTO_TEST_CASE (DD4hepPluginCylinderLayerStructure)
Definition at line 119 of file DD4hepCylinderLayerStructureTests.cpp.
View newest version in sPHENIX GitHub at line 119 of file DD4hepCylinderLayerStructureTests.cpp
References cylinder_layer_head_xml, end_xml, ephi, Acts::getDefaultLogger(), head_xml, indent_12_xml, Acts::Experimental::DD4hepLayerStructure::Options::logLevel, testing::internal::move(), Acts::Experimental::DD4hepLayerStructure::Options::name, nphi, nz, physmon_simulation::s, segmentation_xml, Acts::Test::CylindricalTrackingGeometry::surfacesCylinder(), DD4hepTestsHelper::surfaceToXML(), tail_xml, to_string(), physmon_ckf_tracking::u, Acts::Logging::VERBOSE, and volumes.
Variable Documentation
const char* beampipe_head_xml
Initial value:
=
    R""""(
    <detectors>
        <detector id="0" name="BeamPipe" type="BarrelDetector">
            <type_flags type="DetType_TRACKER + DetType_BEAMPIPE"/>
            <layers>
                <layer name="BP" id="0">
)""""
Definition at line 33 of file DD4hepCylinderLayerStructureTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file DD4hepCylinderLayerStructureTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
Acts::Test::CylindricalTrackingGeometry cGeometry
Initial value:
=
    Acts::Test::CylindricalTrackingGeometry(tContext)
Definition at line 30 of file DD4hepCylinderLayerStructureTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file DD4hepCylinderLayerStructureTests.cpp
const char* cylinder_layer_head_xml
Initial value:
=
    R""""(
    <detectors>
        <detector id="1" name="BarrelLayer" type="BarrelDetector" readout="PixelReadout">
            <type_flags type="DetType_TRACKER + DetType_BARREL"/>
            <layers>
                <layer name="B0" id="0">
)""""
Definition at line 36 of file DD4hepCylinderLayerStructureTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file DD4hepCylinderLayerStructureTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
const char* indent_12_xml = " "
Definition at line 42 of file DD4hepCylinderLayerStructureTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file DD4hepCylinderLayerStructureTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
const char* tail_xml
Initial value:
=
    R""""(
                </layer>
            </layers>
        </detector>
    </detectors>
)""""
Definition at line 39 of file DD4hepCylinderLayerStructureTests.cpp.
View newest version in sPHENIX GitHub at line 39 of file DD4hepCylinderLayerStructureTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
Acts::GeometryContext tContext
Definition at line 29 of file DD4hepCylinderLayerStructureTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file DD4hepCylinderLayerStructureTests.cpp