Analysis Software: Acts::BinnedSPGroupIterator< external_spacepoint_t > Class Template Reference
Acts::BinnedSPGroupIterator< external_spacepoint_t > Class Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Seeding/BinnedSPGroup.hpp>
Public Member Functions
BinnedSPGroupIterator & operator++ ()
bool operator== (const BinnedSPGroupIterator &otherState)
bool operator!= (const BinnedSPGroupIterator &otherState)
Neighborhood
< external_spacepoint_t > middle ()
Neighborhood
< external_spacepoint_t > bottom ()
Neighborhood
< external_spacepoint_t > top ()
BinnedSPGroupIterator (const SpacePointGrid< external_spacepoint_t > *spgrid, BinFinder< external_spacepoint_t > *botBinFinder, BinFinder< external_spacepoint_t > *tBinFinder)
BinnedSPGroupIterator (const SpacePointGrid< external_spacepoint_t > *spgrid, BinFinder< external_spacepoint_t > *botBinFinder, BinFinder< external_spacepoint_t > *tBinFinder, size_t phiInd, size_t zInd)
if (phiIndex<=phiZbins[0]&&zIndex<=phiZbins[1])
Public Attributes
m_bottomBinFinder = botBinFinder
m_topBinFinder = tBinFinder
phiZbins = grid->numLocalBins()
phiIndex = 1
zIndex = 1
outputIndex = 0
bottomBinIndices = m_bottomBinFinder->findBins(phiIndex, zIndex, grid)
topBinIndices = m_topBinFinder->findBins(phiIndex, zIndex, grid)
grid = spgrid
Private Attributes
std::vector< size_t > currentBin
std::vector< size_t > bottomBinIndices
std::vector< size_t > topBinIndices
const SpacePointGrid
< external_spacepoint_t > * grid
size_t phiIndex = 1
size_t zIndex = 1
size_t outputIndex = 0
std::array< long unsigned int, 2ul > phiZbins
BinFinder
< external_spacepoint_t > * m_bottomBinFinder
BinFinder
< external_spacepoint_t > * m_topBinFinder
Detailed Description
template<typename external_spacepoint_t>
class Acts::BinnedSPGroupIterator< external_spacepoint_t >
iterate over all groups of bins a provided BinFinder can generate for each bin of a provided SPGrid
Definition at line 141 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 141 of file BinnedSPGroup.hpp
Constructor & Destructor Documentation
template<typename external_spacepoint_t > Acts::BinnedSPGroupIterator< external_spacepoint_t >::BinnedSPGroupIterator (const SpacePointGrid< external_spacepoint_t > * spgrid, BinFinder< external_spacepoint_t > * botBinFinder, BinFinder< external_spacepoint_t > * tBinFinder) inline
Definition at line 185 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 185 of file BinnedSPGroup.hpp
References Acts::detail::Grid< T, Axes >::globalBinFromLocalBins(), and Acts::BinnedSPGroupIterator< external_spacepoint_t >::grid.
template<typename external_spacepoint_t > Acts::BinnedSPGroupIterator< external_spacepoint_t >::BinnedSPGroupIterator (const SpacePointGrid< external_spacepoint_t > * spgrid, BinFinder< external_spacepoint_t > * botBinFinder, BinFinder< external_spacepoint_t > * tBinFinder, size_t phiInd, size_t zInd) inline
Definition at line 200 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 200 of file BinnedSPGroup.hpp
References Acts::detail::Grid< T, Axes >::globalBinFromLocalBins(), Acts::BinnedSPGroupIterator< external_spacepoint_t >::m_bottomBinFinder, and Acts::BinnedSPGroupIterator< external_spacepoint_t >::m_topBinFinder.
Member Function Documentation
template<typename external_spacepoint_t > Neighborhood<external_spacepoint_t> Acts::BinnedSPGroupIterator< external_spacepoint_t >::bottom () inline
Definition at line 177 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 177 of file BinnedSPGroup.hpp
References Acts::BinnedSPGroupIterator< external_spacepoint_t >::bottomBinIndices, and Acts::BinnedSPGroupIterator< external_spacepoint_t >::grid.
template<typename external_spacepoint_t > Acts::BinnedSPGroupIterator< external_spacepoint_t >::if (phiIndex<=phiZbins &&zIndex<= phiZbins[0][1]) inline
Definition at line 212 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 212 of file BinnedSPGroup.hpp
References Acts::BinnedSPGroupIterator< external_spacepoint_t >::bottomBinIndices, Acts::BinnedSPGroupIterator< external_spacepoint_t >::grid, Acts::BinnedSPGroupIterator< external_spacepoint_t >::m_bottomBinFinder, Acts::BinnedSPGroupIterator< external_spacepoint_t >::m_topBinFinder, Acts::BinnedSPGroupIterator< external_spacepoint_t >::phiIndex, Acts::BinnedSPGroupIterator< external_spacepoint_t >::topBinIndices, and Acts::BinnedSPGroupIterator< external_spacepoint_t >::zIndex.
template<typename external_spacepoint_t > Neighborhood<external_spacepoint_t> Acts::BinnedSPGroupIterator< external_spacepoint_t >::middle () inline
Definition at line 173 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 173 of file BinnedSPGroup.hpp
References Acts::BinnedSPGroupIterator< external_spacepoint_t >::currentBin, and Acts::BinnedSPGroupIterator< external_spacepoint_t >::grid.
template<typename external_spacepoint_t > bool Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator!= (const BinnedSPGroupIterator< external_spacepoint_t > & otherState) inline
Definition at line 169 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 169 of file BinnedSPGroup.hpp
References Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator==().
template<typename external_spacepoint_t > BinnedSPGroupIterator& Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator++ () inline
Definition at line 143 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 143 of file BinnedSPGroup.hpp
References Acts::BinnedSPGroupIterator< external_spacepoint_t >::bottomBinIndices, Acts::BinnedSPGroupIterator< external_spacepoint_t >::currentBin, Acts::BinnedSPGroupIterator< external_spacepoint_t >::grid, Acts::BinnedSPGroupIterator< external_spacepoint_t >::m_bottomBinFinder, Acts::BinnedSPGroupIterator< external_spacepoint_t >::m_topBinFinder, Acts::BinnedSPGroupIterator< external_spacepoint_t >::outputIndex, Acts::BinnedSPGroupIterator< external_spacepoint_t >::phiIndex, Acts::BinnedSPGroupIterator< external_spacepoint_t >::phiZbins, Acts::BinnedSPGroupIterator< external_spacepoint_t >::topBinIndices, and Acts::BinnedSPGroupIterator< external_spacepoint_t >::zIndex.
template<typename external_spacepoint_t > bool Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator== (const BinnedSPGroupIterator< external_spacepoint_t > & otherState) inline
Definition at line 165 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 165 of file BinnedSPGroup.hpp
References Acts::BinnedSPGroupIterator< external_spacepoint_t >::phiIndex, and Acts::BinnedSPGroupIterator< external_spacepoint_t >::zIndex.
Referenced by Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator!=().
template<typename external_spacepoint_t > Neighborhood<external_spacepoint_t> Acts::BinnedSPGroupIterator< external_spacepoint_t >::top () inline
Definition at line 181 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 181 of file BinnedSPGroup.hpp
References Acts::BinnedSPGroupIterator< external_spacepoint_t >::grid, and Acts::BinnedSPGroupIterator< external_spacepoint_t >::topBinIndices.
Referenced by pypdel(), pypdfu(), structm(), structmold(), structp(), and structpold().
Member Data Documentation
template<typename external_spacepoint_t > Acts::BinnedSPGroupIterator< external_spacepoint_t >::bottomBinIndices = m_bottomBinFinder->findBins(phiIndex, zIndex, grid)
Definition at line 196 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 196 of file BinnedSPGroup.hpp
Referenced by Acts::BinnedSPGroupIterator< external_spacepoint_t >::bottom(), Acts::BinnedSPGroupIterator< external_spacepoint_t >::if(), and Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator++().
template<typename external_spacepoint_t > std::vector<size_t> Acts::BinnedSPGroupIterator< external_spacepoint_t >::bottomBinIndices private
Definition at line 221 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 221 of file BinnedSPGroup.hpp
template<typename external_spacepoint_t > std::vector<size_t> Acts::BinnedSPGroupIterator< external_spacepoint_t >::currentBin private
Definition at line 220 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 220 of file BinnedSPGroup.hpp
Referenced by Acts::BinnedSPGroupIterator< external_spacepoint_t >::middle(), and Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator++().
template<typename external_spacepoint_t > Acts::BinnedSPGroupIterator< external_spacepoint_t >::grid = spgrid
Definition at line 207 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 207 of file BinnedSPGroup.hpp
Referenced by Acts::BinnedSPGroupIterator< external_spacepoint_t >::BinnedSPGroupIterator(), Acts::BinnedSPGroupIterator< external_spacepoint_t >::bottom(), Acts::BinnedSPGroupIterator< external_spacepoint_t >::if(), Acts::BinnedSPGroupIterator< external_spacepoint_t >::middle(), Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator++(), and Acts::BinnedSPGroupIterator< external_spacepoint_t >::top().
template<typename external_spacepoint_t > const SpacePointGrid<external_spacepoint_t>* Acts::BinnedSPGroupIterator< external_spacepoint_t >::grid private
Definition at line 223 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 223 of file BinnedSPGroup.hpp
template<typename external_spacepoint_t > Acts::BinnedSPGroupIterator< external_spacepoint_t >::m_bottomBinFinder = botBinFinder
Definition at line 190 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 190 of file BinnedSPGroup.hpp
Referenced by Acts::BinnedSPGroup< external_spacepoint_t >::begin(), Acts::BinnedSPGroupIterator< external_spacepoint_t >::BinnedSPGroupIterator(), Acts::BinnedSPGroup< external_spacepoint_t >::end(), Acts::BinnedSPGroupIterator< external_spacepoint_t >::if(), and Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator++().
template<typename external_spacepoint_t > BinFinder<external_spacepoint_t>* Acts::BinnedSPGroupIterator< external_spacepoint_t >::m_bottomBinFinder private
Definition at line 228 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 228 of file BinnedSPGroup.hpp
template<typename external_spacepoint_t > Acts::BinnedSPGroupIterator< external_spacepoint_t >::m_topBinFinder = tBinFinder
Definition at line 191 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 191 of file BinnedSPGroup.hpp
Referenced by Acts::BinnedSPGroup< external_spacepoint_t >::begin(), Acts::BinnedSPGroupIterator< external_spacepoint_t >::BinnedSPGroupIterator(), Acts::BinnedSPGroup< external_spacepoint_t >::end(), Acts::BinnedSPGroupIterator< external_spacepoint_t >::if(), and Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator++().
template<typename external_spacepoint_t > BinFinder<external_spacepoint_t>* Acts::BinnedSPGroupIterator< external_spacepoint_t >::m_topBinFinder private
Definition at line 229 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 229 of file BinnedSPGroup.hpp
template<typename external_spacepoint_t > Acts::BinnedSPGroupIterator< external_spacepoint_t >::outputIndex = 0
Definition at line 195 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 195 of file BinnedSPGroup.hpp
Referenced by Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator++().
template<typename external_spacepoint_t > size_t Acts::BinnedSPGroupIterator< external_spacepoint_t >::outputIndex = 0 private
Definition at line 226 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 226 of file BinnedSPGroup.hpp
template<typename external_spacepoint_t > Acts::BinnedSPGroupIterator< external_spacepoint_t >::phiIndex = 1
Definition at line 193 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 193 of file BinnedSPGroup.hpp
Referenced by Acts::BinnedSPGroupIterator< external_spacepoint_t >::if(), Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator++(), and Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator==().
template<typename external_spacepoint_t > size_t Acts::BinnedSPGroupIterator< external_spacepoint_t >::phiIndex = 1 private
Definition at line 224 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 224 of file BinnedSPGroup.hpp
template<typename external_spacepoint_t > Acts::BinnedSPGroupIterator< external_spacepoint_t >::phiZbins = grid->numLocalBins()
Definition at line 192 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 192 of file BinnedSPGroup.hpp
Referenced by Acts::BinnedSPGroup< external_spacepoint_t >::end(), and Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator++().
template<typename external_spacepoint_t > std::array<long unsigned int, 2ul> Acts::BinnedSPGroupIterator< external_spacepoint_t >::phiZbins private
Definition at line 227 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 227 of file BinnedSPGroup.hpp
template<typename external_spacepoint_t > Acts::BinnedSPGroupIterator< external_spacepoint_t >::topBinIndices = m_topBinFinder->findBins(phiIndex, zIndex, grid)
Definition at line 197 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 197 of file BinnedSPGroup.hpp
Referenced by Acts::BinnedSPGroupIterator< external_spacepoint_t >::if(), Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator++(), and Acts::BinnedSPGroupIterator< external_spacepoint_t >::top().
template<typename external_spacepoint_t > std::vector<size_t> Acts::BinnedSPGroupIterator< external_spacepoint_t >::topBinIndices private
Definition at line 222 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 222 of file BinnedSPGroup.hpp
template<typename external_spacepoint_t > Acts::BinnedSPGroupIterator< external_spacepoint_t >::zIndex = 1
Definition at line 194 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 194 of file BinnedSPGroup.hpp
Referenced by Acts::BinnedSPGroupIterator< external_spacepoint_t >::if(), Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator++(), and Acts::BinnedSPGroupIterator< external_spacepoint_t >::operator==().
template<typename external_spacepoint_t > size_t Acts::BinnedSPGroupIterator< external_spacepoint_t >::zIndex = 1 private
Definition at line 225 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 225 of file BinnedSPGroup.hpp
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Seeding/BinnedSPGroup.hpp