Analysis Software: analysis/blob/master/dNdEta_Run2023/analysis_INTT/plot/sPHENIXStyle/test_style.C File Reference
test_style.C File Reference
Functions
TH1F h1 ("h1","H1;Mass [GeV];Counts [/ GeV];", 20, 0, 20)
TH1F h2 ("h2","H2;Mass [GeV];Counts [/ GeV];", 20, 0, 20)
for (int i=0;i< 1000;i++)
h1 Draw ("e1")
h2 Draw ("same")
h2 SetFillColor (5)
h1 Draw ("e1same")
TLegend leg (.55,.70,.85,.93)
leg AddEntry ("","#it{#bf{sPHENIX}} Simulation","")
leg AddEntry ("","Au+Au #sqrt{s_{NN}}=200 GeV","")
leg Draw ()
c RedrawAxis ()
c Print ("test_style.pdf")
c Print ("test_style.png")
c2 SetRightMargin (.2)
TF2 f2 ("f2","exp(-x/5)*sin(y)",-5, 5,-5, 5)
f2 SetNpx (100)
f2 SetNpy (100)
f2 Draw ("surf2z")
f2 GetXaxis () -> SetTitle("X")
f2 GetYaxis () -> SetTitle("Y")
f2 GetZaxis () -> SetTitle("Z")
c2 Print ("test_style_f2.pdf")
c2 Print ("test_style_f2.png")
Variables
leg AddEntry & h1
leg AddEntry & h2
TCanvas c2
Function Documentation
leg AddEntry ("" , "#it{#bf{sPHENIX}} Simulation" , "")
Referenced by analyzeClusterEtIso(), CompareOldVsNewPlots(), STrackCutStudy::ConstructPlots(), DoPercentDifference(), draw_hists_3D(), drawCorr(), CemcMonDraw::DrawSecond(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), numericInverse(), and QuickDeltaPtExtractor().
leg AddEntry ("")
h1 Draw ("e1")
Referenced by analyzeClusterEtIso(), CalculateSigmaDca(), CompareOldVsNewPlots(), STrackCutStudy::ConstructPlots(), stack::displayEvent(), stack::displayStackSummary(), hcal::displaySummary(), DoPercentDifference(), INTTVtxZ::Draw_1DEffComp(), Draw_BDiJetImbalance(), draw_hists_3D(), drawCanvas_invMass(), drawCorr(), DrawCutLabel(), InttQA(), Jet_reso_Iso(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), MvtxQA(), numericInverse(), OutputVisualsTPC(), plot(), PlotLine(), QuickDeltaPtExtractor(), QuickTreePlotter(), QuickTuplePlotter(), sccalib(), sipmCalib(), spmcalib(), tileHelper::tilePattern(), TpcQA(), TpotQA(), TrackingQA(), and TrackProjection_Checks_Comparison().
fTCBfordave Draw ("same")
h1 Draw ("e1same")
tex Draw ()
f2 Draw ("surf2z")
TF2 f2 ("f2" , "exp(-x/5)*sin(y)" , - 5, 5 , - 5, 5)
Referenced by f2pyth(), pyofsh(), pyoper(), pyrnm3(), pyrnmq(), pytbdy(), pyxxga(), strf(), and vegas().
for ()
Definition at line 6 of file test_style.C.
View newest version in sPHENIX GitHub at line 6 of file test_style.C
References h1.
fTCBfordave GetXaxis () -> SetTitle("X")
Definition at line 102 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70.C.
View newest version in sPHENIX GitHub at line 102 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70.C
Referenced by analyzeClusterEtIso(), CalculateSigmaDca(), CompareOldVsNewPlots(), SDeltaPtCutStudy::CreateSigmaGraphs(), DoPercentDifference(), INTTVtxZ::Draw_1DEffComp(), plotUtil::Draw_1DhistsComp(), draw_hists_3D(), drawCorr(), STrackMatcherComparator::InitHists(), Jet_reso_Iso(), MakeNewMatcherPlots(), MakeNewMatcherTuplePlots(), MakeOldEvaluatorPlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), numericInverse(), MvtxMon::process_event(), QuickDeltaPtExtractor(), SetHistoStyle(), STrackCutStudy::SetHistStyles(), and SDeltaPtCutStudy::SetStyles().
fTCBfordave GetYaxis () -> SetTitle("Y")
Definition at line 339 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.rootDraw_HFJetTruth_InvMass_DrawCrossSection_PR.C.
View newest version in sPHENIX GitHub at line 339 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.rootDraw_HFJetTruth_InvMass_DrawCrossSection_PR.C
Referenced by analyzeClusterEtIso(), CalculateSigmaDca(), CompareOldVsNewPlots(), DoPercentDifference(), INTTVtxZ::Draw_1DEffComp(), plotUtil::Draw_1DhistsComp(), draw_hists_3D(), drawCorr(), CemcMonDraw::DrawSecond(), CemcMonDraw::DrawThird(), STrackMatcherComparator::InitHists(), MakeNewMatcherPlots(), MakeNewMatcherTuplePlots(), MakeOldEvaluatorPlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), numericInverse(), RawClusterPositionCorrection::process_event(), MvtxMon::process_event(), QuickDeltaPtExtractor(), SetHistoStyle(), STrackCutStudy::SetHistStyles(), and SDeltaPtCutStudy::SetStyles().
hhfit_15 GetZaxis () -> SetTitle("Z")
Referenced by CalculateSigmaDca(), CompareOldVsNewPlots(), draw_hists_3D(), CemcMonDraw::DrawFirst(), JetUnderlyingEvent::End(), STrackMatcherComparator::InitHists(), MakeNewMatcherPlots(), MakeNewMatcherTuplePlots(), MakeOldEvaluatorPlots(), STrackMatcherComparator::MakeRatiosAndPlots(), QuickDeltaPtExtractor(), STrackCutStudy::SetHistStyles(), and SDeltaPtCutStudy::SetStyles().
TH1F h1 ("h1" , "H1;Mass ;Counts ;" [GeV][/GeV], 20 , 0 , 20)
TH1F h2 ("h2" , "H2;Mass ;Counts ;" [GeV][/GeV], 20 , 0 , 20)
TLegend leg (. 55, . 70, . 85, . 93)
c Print ("test_style.pdf")
Referenced by compareForthBackJacNoise(), genfit::Exception::info(), PgPostBankBackupStorage::Print(), testing::gtest_printers_test::Print(), testing::gtest_printers_test::PrintByRef(), genfit::KalmanFitterRefTrack::processTrackPoint(), and genfit::KalmanFitterRefTrack::processTrackPointSqrt().
c Print ("test_style.png")
c2 Print ("test_style_f2.pdf")
c2 Print ("test_style_f2.png")
c RedrawAxis ()
h2 SetFillColor (5)
Referenced by CalculateSigmaDca(), CompareOldVsNewPlots(), STrackCutStudy::ConstructPlots(), DoPercentDifference(), CemcMonDraw::FindHotTower(), STrackCutStudy::MakeCutText(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), QuickDeltaPtExtractor(), STrackCutStudy::SetHistStyles(), and SDeltaPtCutStudy::SetStyles().
f2 SetNpx (100)
Referenced by sccalib().
f2 SetNpy (100)
c2 SetRightMargin (. 2)
Referenced by CalculateSigmaDca(), CompareOldVsNewPlots(), STrackCutStudy::ConstructPlots(), DoPercentDifference(), getPad(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), and QuickDeltaPtExtractor().
Variable Documentation
TCanvas c2
Definition at line 24 of file test_style.C.
View newest version in sPHENIX GitHub at line 24 of file test_style.C
Referenced by __example_6.f__(), __example_7.f__(), __example_8.f__(), airy1(), airy1d(), airy2(), airy2d(), analyzeClusterEtIso(), BOOST_AUTO_TEST_CASE(), InttVertexFinder::calculateZvertex(), calo_towers(), centrality_newplotbg_newsupp(), cherenkov_analysis(), cluster_efficiency(), CMDistortionAnalysis(), CMDistortionAnalysisCart(), CMDistortionAnalysisPhiR(), compare(), compareStreams(), Cone_Plots(), crossterms(), D0EffScan(), Conversion::dist(), draw_hists(), EdepPercentAnalyzerIH(), EdepPercentSmall(), eic_sphenix_test_smearing(), eicsmear_check_calorimeter(), eicsmear_check_tracking(), EMCDistribution_SUM(), EMCDistribution_SUM_RawADC(), evaluate_cluster_track_matching(), figmaker(), Conversion::firstLayer(), FitVerticalScan(), fjetResol(), GammaNeutronEnergy2DGraphMaker(), gauss1(), gauss2(), gauss3(), gauss4(), get_parametrization_F2(), genfit::GblFitterInfo::getCovariance(), KFParticleBase::GetDStoParticleBz(), KFParticleBaseSIMD::GetDStoParticleBz(), AnnularFieldSim::GetStepDistortion(), Conversion::hasSilicon(), hera_dis_countbins(), RecoConversionEval::hitCuts(), InttQA(), jet_reco(), look_purity(), main(), Langevin::Make(), makePlot_reco_check(), makePlot_reco_electron_id(), makePlot_reco_xQ2(), makePlot_track_eval(), MakePlots(), MakeTH1F(), MvtxQA(), newplotbg_newsupp(), newplotbg_newsupp_2021(), newplotbg_newsupp_2022(), newplotbg_newsupp_2022_60pct(), numericInverse(), plot(), plot_g1_projection(), plot_histos(), plot_jets(), plot_kshort(), plot_ratio(), plot_residuals(), plot_resolution(), plot_sidis_proj_uncertainty(), genfit::GFGbl::processTrackWithRep(), pyeig4(), pygau2(), pygaus(), pyhiscat(), pyrvch(), pyrvne(), pyscat(), pysghf(), eic_bnl_rich::read(), ReconstructTracks(), tails(), TpcQA(), TpotQA(), track_kinematics(), Conversion::trackDLayer(), TrackParamEtaDependence(), tracks(), true_kinematics(), VertexingQA(), and veto_analysis().
leg AddEntry& h1
Definition at line 17 of file test_style.C.
View newest version in sPHENIX GitHub at line 17 of file test_style.C
Referenced by compareDistributions(), compareHistograms(), DataAna(), DataAna2(), decode_idhammond(), display(), Draw_hotmap(), EdepPercentAnalyzerE(), EdepPercentAnalyzerIH(), EdepPercentAnalyzerOH(), EdepPercentE(), EdepPercentIH(), EdepPercentOH(), EdepPercentSmall(), EdepSmall(), EnergyGlance(), errorOf1DHistograms(), errorOf2DHistograms(), event_counts(), example_save_canvas(), Conversion::firstLayer(), FitProfile(), FitResolution(), fjetResol(), for(), KFParticle::GetDistanceFromVertexXY(), KFParticleSIMD::GetDistanceFromVertexXY(), BEmcRec::HitACompare(), G4TowerNtuple::Init(), G4CellNtuple::Init(), G4HitNtuple::Init(), G4SnglNtuple::Init(), EdepNtuple::Init(), TimingNtuple::Init(), SigmaTimingNtuple::Init(), KFParticleBase::Initialize(), KFParticleBaseSIMD::Initialize(), CDBHistos::LoadCalibrations(), makeLcD0(), makeLcD0_BUP2020(), makeLcD0_BUP2022(), makePlot_track_eval(), MergeRootfile(), Neutrals(), odeint(), plot_amatrix(), plot_compare_fun4all_eicroot(), plot_ntp_g4hit(), plot_track_deviations(), plot_track_multi(), pyhisigh(), pysigh(), CDBHistos::registerHisto(), ShSizeHist(), ShSizePrep(), Matter::sud_val_GG(), Matter::sud_val_QG(), epemGun::sud_val_QG_w_M(), Matter::sud_val_QG_w_M(), Matter::sud_val_QP(), Matter::sud_val_QQ(), Matter::sud_val_QQ_w_M_vac_only(), TestCDBHistos(), ThreeGraphs(), and Conversion::trackDLayer().
leg AddEntry& h2
Definition at line 18 of file test_style.C.
View newest version in sPHENIX GitHub at line 18 of file test_style.C
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), compareDistributions(), compareHistograms(), decode_idhammond(), display(), EdepPercentAnalyzerE(), EdepPercentAnalyzerIH(), EdepPercentAnalyzerOH(), EdepPercentSmall(), EMCDistribution_Fast(), EMCDistribution_PeakSample_Fast(), errorOf1DHistograms(), errorOf2DHistograms(), myAnalysis::finalize(), Conversion::firstLayer(), fjetResol(), BEmcRec::HitACompare(), SynRadAna::Init(), SoftLeptonTaggingTruth::Init_Spectrum(), KFParticleBase::Initialize(), KFParticleBaseSIMD::Initialize(), makeLcD0(), makeLcD0_BUP2020(), makeLcD0_BUP2022(), MakeShowerGraph(), MergeRootfile(), ParticleShowerSizeHistoMaker(), peaks(), plot_matscan(), plot_ntp_g4hit(), QAG4SimulationCalorimeterSum::process_event_Cluster(), pyhisigh(), pysigh(), spmcalib(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::step(), StupidGraphs(), Matter::sud_val_GG(), Matter::sud_val_QG(), epemGun::sud_val_QG_w_M(), Matter::sud_val_QG_w_M(), Matter::sud_val_QP(), Matter::sud_val_QQ(), Matter::sud_val_QQ_w_M_vac_only(), Surf3DHistoMaker(), TestCDBHistos(), Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testMultiTrajectoryExtraColumns(), ThreeGraphs(), Conversion::trackDLayer(), and GPUTPCTrackParam::TransportToX().