Analysis Software: analysis/blob/master/EICAnalysis/eventgen/Fun4All_MCEventGen.C File Reference
Fun4All_MCEventGen.C File Reference
Functions
int Fun4All_MCEventGen (const int nEvents=100, const char *outputFile="G4MCEventGen.root")
void G4Cmd (const char *cmd)
Function Documentation
int Fun4All_MCEventGen (const int nEvents = 100, const char * outputFile = "G4MCEventGen.root")
Definition at line 2 of file Fun4All_MCEventGen.C.
View newest version in sPHENIX GitHub at line 2 of file Fun4All_MCEventGen.C
References Fun4AllServer::End(), recoConsts::instance(), Fun4AllServer::instance(), nEvents, ReadEICFiles::OpenInputFile(), out, Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), Fun4AllServer::run(), PHSartre::set_config_file(), PHPythia6::set_config_file(), PHPythia8::set_config_file(), sHEPGen::set_datacard_file(), PHFlag::set_FloatFlag(), PHG4DSTReader::set_load_active_particle(), PHG4DSTReader::set_load_all_particle(), sHEPGen::set_momentum_electron(), sHEPGen::set_momentum_hadron(), PHG4DSTReader::set_save_particle(), PHG4DSTReader::set_save_vertex(), and Fun4AllBase::Verbosity().
void G4Cmd (const char * cmd)
Definition at line 200 of file Fun4All_MCEventGen.C.
View newest version in sPHENIX GitHub at line 200 of file Fun4All_MCEventGen.C
References PHG4Reco::ApplyCommand(), g4, Fun4AllServer::getSubsysReco(), and Fun4AllServer::instance().