Analysis Software: PHG4DetectorGroupSubsystem Class Reference
PHG4DetectorGroupSubsystem Class Reference abstract
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.h>
Public Types
enum FILE_TYPE { none = 0, xml = 1, root = 2 }
Public Member Functions
~PHG4DetectorGroupSubsystem () override
int Init (PHCompositeNode *) final
int InitRun (PHCompositeNode *) final
virtual int InitRunSubsystem (PHCompositeNode *)
virtual int InitSubsystem (PHCompositeNode *)
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
PHParametersContainer * GetParamsContainer () const
void set_double_param (const int detid, const std::string &name, const double dval)
double get_double_param (const int detid, const std::string &name) const
void set_int_param (const int detid, const std::string &name, const int ival)
int get_int_param (const int detid, const std::string &name) const
void set_string_param (const int detid, const std::string &name, const std::string &sval)
std::string get_string_param (const int detid, const std::string &name) const
void UseDB (const int i=1)
int ReadDB () const
FILE_TYPE get_filetype () const
void UseCalibFiles (const FILE_TYPE ftyp)
int SaveParamsToDB ()
int ReadParamsFromDB (const std::string &name, const int issuper)
int SaveParamsToFile (const FILE_TYPE ftyp)
int ReadParamsFromFile (const std::string &name, const FILE_TYPE ftyp, const int issuper)
void SetCalibrationFileDir (const std::string &calibdir)
void UpdateParametersWithMacro ()
void SetActive (const int detid, const int i)
void SetActive (const int i=1)
void SetAbsorberActive (const int detid, const int i)
void SetAbsorberActive (const int i=1)
void SetAbsorberTruth (const int detid, const int i)
void SetAbsorberTruth (const int i=1)
void SetSupportActive (const int detid, const int i=1)
void SetSupportActive (const int i=1)
void BlackHole (const int detid, const int i)
void BlackHole (const int i=1)
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int GetLayer () const
virtual void SetDefaultParameters ()=0
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
~PHG4Subsystem (void) override
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4Detector * GetDetector (void) const
return pointer to created detector object
virtual PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual PHG4SteppingAction * GetSteppingAction (void) const
return pointer to this subsystem stepping action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
virtual PHG4DisplayAction * GetDisplayAction () const
return pointer to this subsystem display setting
virtual PHG4StackingAction * GetStackingAction () const
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
void SetMotherSubsystem (PHG4Subsystem *subsys)
PHG4Subsystem * GetMotherSubsystem () const
void SetLogicalVolume (G4LogicalVolume *vol)
G4LogicalVolume * GetLogicalVolume () const
virtual bool CanBeMotherSubsystem () const
virtual void AddProcesses (G4ParticleDefinition *)
virtual void DefineMaterials ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int process_event (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
PHG4DetectorGroupSubsystem (const std::string &name="GenericSubsystem", const int lyr=0)
void InitializeParameters ()
void AddDetId (const int i)
std::pair< std::set< int >
::const_iterator, std::set
< int >::const_iterator > GetDetIds () const
void set_default_double_param (const int detid, const std::string &name, const double dval)
void set_default_int_param (const int detid, const std::string &name, const int ival)
void set_default_string_param (const int detid, const std::string &name, const std::string &sval)
int BeginRunExecuted () const
void PrintDefaultParams () const
void PrintMacroParams () const
Private Attributes
PHParametersContainer * m_ParamsContainer = nullptr
PHParametersContainer * m_ParamsContainerDefault = nullptr
PHCompositeNode * m_SaveTopNode = nullptr
bool m_OverlapCheckFlag = false
int m_Layer = 0
int m_UseDBFlag = 0
int m_BeginRunExecutedFlag = 0
FILE_TYPE m_FileType = PHG4DetectorGroupSubsystem::none
std::string m_SuperDetector = "NONE"
std::string m_CalibFileDir = "./"
std::set< int > m_LayerSet
std::map< int, std::map< const
std::string, double > > m_MacroDoubleParamsMap
std::map< int, std::map< const
std::string, int > > m_MacroIntegerParamsMap
std::map< int, std::map< const
std::string, std::string > > m_MacroStringParamsMap
std::map< int, std::map< const
std::string, double > > m_DefaultDoubleParamsMap
std::map< int, std::map< const
std::string, int > > m_DefaultIntegerParamsMap
std::map< int, std::map< const
std::string, std::string > > m_DefaultStringParamsMap
Detailed Description
Definition at line 16 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 16 of file PHG4DetectorGroupSubsystem.h
Member Enumeration Documentation
enum PHG4DetectorGroupSubsystem::FILE_TYPE
Enumerator:
none
xml
root
Definition at line 19 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4DetectorGroupSubsystem.h
Constructor & Destructor Documentation
PHG4DetectorGroupSubsystem::~PHG4DetectorGroupSubsystem () inline override
Definition at line 26 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 26 of file PHG4DetectorGroupSubsystem.h
PHG4DetectorGroupSubsystem::PHG4DetectorGroupSubsystem (const std::string & name = "GenericSubsystem", const int lyr = 0) protected
Definition at line 32 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 32 of file PHG4DetectorGroupSubsystem.cc
References Fun4AllBase::Name().
Member Function Documentation
void PHG4DetectorGroupSubsystem::AddDetId (const int i) inline protected
Definition at line 79 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4DetectorGroupSubsystem.h
References m_LayerSet.
Referenced by PHG4EICMvtxSubsystem::PHG4EICMvtxSubsystem(), PHG4InttSubsystem::PHG4InttSubsystem(), and PHG4MvtxSubsystem::PHG4MvtxSubsystem().
int PHG4DetectorGroupSubsystem::BeginRunExecuted () const inline protected
Definition at line 87 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 87 of file PHG4DetectorGroupSubsystem.h
References m_BeginRunExecutedFlag.
void PHG4DetectorGroupSubsystem::BlackHole (const int detid, const int i)
Definition at line 615 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 615 of file PHG4DetectorGroupSubsystem.cc
References set_int_param().
void PHG4DetectorGroupSubsystem::BlackHole (const int i = 1)
Definition at line 620 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 620 of file PHG4DetectorGroupSubsystem.cc
References m_LayerSet, and set_int_param().
bool PHG4DetectorGroupSubsystem::CheckOverlap () const inline
Definition at line 36 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4DetectorGroupSubsystem.h
References m_OverlapCheckFlag.
Referenced by PHG4EICMvtxSubsystem::InitRunSubsystem(), PHG4MvtxSubsystem::InitRunSubsystem(), PHG4InttSubsystem::InitRunSubsystem(), and PHG4PSTOFSubsystem::InitRunSubsystem().
double PHG4DetectorGroupSubsystem::get_double_param (const int detid, const std::string & name) const
Definition at line 166 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 166 of file PHG4DetectorGroupSubsystem.cc
References PHParameters::get_double_param(), PHParametersContainer::GetParameters(), m_ParamsContainer, and PHWHERE.
FILE_TYPE PHG4DetectorGroupSubsystem::get_filetype () const inline
Definition at line 48 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4DetectorGroupSubsystem.h
References m_FileType.
Referenced by InitRun().
int PHG4DetectorGroupSubsystem::get_int_param (const int detid, const std::string & name) const
Definition at line 181 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 181 of file PHG4DetectorGroupSubsystem.cc
References PHParameters::get_int_param(), PHParametersContainer::GetParameters(), m_ParamsContainer, and PHWHERE.
Referenced by PHG4PSTOFSubsystem::InitRunSubsystem().
std::string PHG4DetectorGroupSubsystem::get_string_param (const int detid, const std::string & name) const
Definition at line 197 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 197 of file PHG4DetectorGroupSubsystem.cc
References PHParameters::get_string_param(), PHParametersContainer::GetParameters(), m_ParamsContainer, and PHWHERE.
std::pair<std::set<int>::const_iterator, std::set<int>::const_iterator> PHG4DetectorGroupSubsystem::GetDetIds () const inline protected
Definition at line 80 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 80 of file PHG4DetectorGroupSubsystem.h
References m_LayerSet.
Referenced by PHG4EICMvtxSubsystem::InitRunSubsystem(), PHG4MvtxSubsystem::InitRunSubsystem(), PHG4InttSubsystem::InitRunSubsystem(), PHG4MvtxSubsystem::SetDefaultParameters(), PHG4EICMvtxSubsystem::SetDefaultParameters(), and PHG4InttSubsystem::SetDefaultParameters().
int PHG4DetectorGroupSubsystem::GetLayer () const inline
Definition at line 70 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4DetectorGroupSubsystem.h
References m_Layer.
PHParametersContainer* PHG4DetectorGroupSubsystem::GetParamsContainer () const inline
Definition at line 37 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4DetectorGroupSubsystem.h
References m_ParamsContainer.
Referenced by PHG4EICMvtxSubsystem::InitRunSubsystem(), PHG4MvtxSubsystem::InitRunSubsystem(), PHG4InttSubsystem::InitRunSubsystem(), PHG4PSTOFSubsystem::InitRunSubsystem(), PHG4InttSubsystem::Print(), PHG4PSTOFSubsystem::Print(), and UpdateParametersWithMacro().
int PHG4DetectorGroupSubsystem::Init (PHCompositeNode *) final virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 44 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 44 of file PHG4DetectorGroupSubsystem.cc
References InitSubsystem(), m_ParamsContainerDefault, m_SaveTopNode, Fun4AllBase::Name(), and PHParametersContainer::set_name().
void PHG4DetectorGroupSubsystem::InitializeParameters () protected
Definition at line 434 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 434 of file PHG4DetectorGroupSubsystem.cc
References PHParametersContainer::AddPHParameters(), material_mapping_optimisation::format, PHParametersContainer::GetParametersToModify(), m_DefaultDoubleParamsMap, m_DefaultIntegerParamsMap, m_DefaultStringParamsMap, m_LayerSet, m_ParamsContainerDefault, Fun4AllBase::Name(), set_default_int_param(), PHParameters::set_double_param(), PHParameters::set_int_param(), PHParameters::set_string_param(), and SetDefaultParameters().
Referenced by PHG4EICMvtxSubsystem::PHG4EICMvtxSubsystem(), PHG4InttSubsystem::PHG4InttSubsystem(), PHG4MvtxSubsystem::PHG4MvtxSubsystem(), and PHG4PSTOFSubsystem::PHG4PSTOFSubsystem().
int PHG4DetectorGroupSubsystem::InitRun (PHCompositeNode *) final virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 52 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 52 of file PHG4DetectorGroupSubsystem.cc
References PHCompositeNode::addNode(), PHParametersContainer::AddPHParameters(), PHParametersContainer::clear(), PHG4Subsystem::DefineMaterials(), PHParametersContainer::FillFrom(), PHNodeIterator::findFirst(), get_filetype(), PHParametersContainer::GetAllParameters(), InitRunSubsystem(), m_BeginRunExecutedFlag, m_ParamsContainer, m_ParamsContainerDefault, m_SuperDetector, Fun4AllBase::Name(), PHParametersContainer::Name(), none, PdbParameterMapContainer::print(), ReadDB(), ReadParamsFromDB(), ReadParamsFromFile(), PHParametersContainer::SaveToNodeTree(), SuperDetector(), PHParametersContainer::UpdateNodeTree(), UpdateParametersWithMacro(), and Fun4AllBase::Verbosity().
virtual int PHG4DetectorGroupSubsystem::InitRunSubsystem (PHCompositeNode *) inline virtual
Reimplemented in PHG4PSTOFSubsystem, PHG4InttSubsystem, PHG4EICMvtxSubsystem, and PHG4MvtxSubsystem.
Definition at line 30 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4DetectorGroupSubsystem.h
Referenced by InitRun().
virtual int PHG4DetectorGroupSubsystem::InitSubsystem (PHCompositeNode *) inline virtual
Definition at line 34 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4DetectorGroupSubsystem.h
Referenced by Init().
void PHG4DetectorGroupSubsystem::OverlapCheck (const bool chk = true) inline
Definition at line 35 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4DetectorGroupSubsystem.h
References m_OverlapCheckFlag.
Referenced by Intt(), and Mvtx().
void PHG4DetectorGroupSubsystem::PrintDefaultParams () const protected
Definition at line 641 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 641 of file PHG4DetectorGroupSubsystem.cc
References m_DefaultDoubleParamsMap, m_DefaultIntegerParamsMap, and m_DefaultStringParamsMap.
Referenced by PHG4InttSubsystem::Print(), and PHG4PSTOFSubsystem::Print().
void PHG4DetectorGroupSubsystem::PrintMacroParams () const protected
Definition at line 674 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 674 of file PHG4DetectorGroupSubsystem.cc
References m_MacroDoubleParamsMap, m_MacroIntegerParamsMap, and m_MacroStringParamsMap.
Referenced by PHG4InttSubsystem::Print(), and PHG4PSTOFSubsystem::Print().
int PHG4DetectorGroupSubsystem::ReadDB () const inline
Definition at line 47 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4DetectorGroupSubsystem.h
References m_UseDBFlag.
Referenced by InitRun().
int PHG4DetectorGroupSubsystem::ReadParamsFromDB (const std::string & name, const int issuper)
Definition at line 500 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 500 of file PHG4DetectorGroupSubsystem.cc
Referenced by InitRun().
int PHG4DetectorGroupSubsystem::ReadParamsFromFile (const std::string & name, const FILE_TYPE ftyp, const int issuper)
Definition at line 548 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 548 of file PHG4DetectorGroupSubsystem.cc
References extension, PHWHERE, root, and xml.
Referenced by InitRun().
int PHG4DetectorGroupSubsystem::SaveParamsToDB ()
Definition at line 488 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 488 of file PHG4DetectorGroupSubsystem.cc
References assert, m_ParamsContainer, and PHParametersContainer::WriteToDB().
int PHG4DetectorGroupSubsystem::SaveParamsToFile (const FILE_TYPE ftyp)
Definition at line 523 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 523 of file PHG4DetectorGroupSubsystem.cc
References assert, extension, m_CalibFileDir, m_ParamsContainer, PHWHERE, root, PHParametersContainer::WriteToFile(), and xml.
void PHG4DetectorGroupSubsystem::set_default_double_param (const int detid, const std::string & name, const double dval) protected
Definition at line 380 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 380 of file PHG4DetectorGroupSubsystem.cc
References m_DefaultDoubleParamsMap, perf_headwind::name, and PHWHERE.
Referenced by PHG4EICMvtxSubsystem::SetDefaultParameters(), PHG4MvtxSubsystem::SetDefaultParameters(), PHG4InttSubsystem::SetDefaultParameters(), and PHG4PSTOFSubsystem::SetDefaultParameters().
void PHG4DetectorGroupSubsystem::set_default_int_param (const int detid, const std::string & name, const int ival) protected
Definition at line 398 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 398 of file PHG4DetectorGroupSubsystem.cc
References m_DefaultIntegerParamsMap, perf_headwind::name, and PHWHERE.
Referenced by InitializeParameters(), PHG4MvtxSubsystem::SetDefaultParameters(), PHG4EICMvtxSubsystem::SetDefaultParameters(), PHG4InttSubsystem::SetDefaultParameters(), and PHG4PSTOFSubsystem::SetDefaultParameters().
void PHG4DetectorGroupSubsystem::set_default_string_param (const int detid, const std::string & name, const std::string & sval) protected
Definition at line 416 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 416 of file PHG4DetectorGroupSubsystem.cc
References m_DefaultStringParamsMap, perf_headwind::name, and PHWHERE.
Referenced by PHG4EICMvtxSubsystem::SetDefaultParameters(), and PHG4MvtxSubsystem::SetDefaultParameters().
void PHG4DetectorGroupSubsystem::set_double_param (const int detid, const std::string & name, const double dval)
Definition at line 212 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 212 of file PHG4DetectorGroupSubsystem.cc
References m_DefaultDoubleParamsMap, m_MacroDoubleParamsMap, and perf_headwind::name.
Referenced by Intt().
void PHG4DetectorGroupSubsystem::set_int_param (const int detid, const std::string & name, const int ival)
Definition at line 255 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 255 of file PHG4DetectorGroupSubsystem.cc
References m_DefaultIntegerParamsMap, m_MacroIntegerParamsMap, and perf_headwind::name.
Referenced by BlackHole(), Intt(), SetAbsorberActive(), SetAbsorberTruth(), SetActive(), and SetSupportActive().
void PHG4DetectorGroupSubsystem::set_string_param (const int detid, const std::string & name, const std::string & sval)
Definition at line 293 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 293 of file PHG4DetectorGroupSubsystem.cc
References m_DefaultStringParamsMap, m_MacroStringParamsMap, and perf_headwind::name.
Referenced by Mvtx().
void PHG4DetectorGroupSubsystem::SetAbsorberActive (const int detid, const int i)
Definition at line 589 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 589 of file PHG4DetectorGroupSubsystem.cc
References set_int_param().
Referenced by Intt().
void PHG4DetectorGroupSubsystem::SetAbsorberActive (const int i = 1)
Definition at line 594 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 594 of file PHG4DetectorGroupSubsystem.cc
References m_LayerSet, and set_int_param().
void PHG4DetectorGroupSubsystem::SetAbsorberTruth (const int detid, const int i)
Definition at line 628 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 628 of file PHG4DetectorGroupSubsystem.cc
References set_int_param().
void PHG4DetectorGroupSubsystem::SetAbsorberTruth (const int i = 1)
Definition at line 633 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 633 of file PHG4DetectorGroupSubsystem.cc
References m_LayerSet, and set_int_param().
void PHG4DetectorGroupSubsystem::SetActive (const int detid, const int i)
Definition at line 576 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 576 of file PHG4DetectorGroupSubsystem.cc
References set_int_param().
Referenced by Intt(), and Mvtx().
void PHG4DetectorGroupSubsystem::SetActive (const int i = 1)
Definition at line 581 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 581 of file PHG4DetectorGroupSubsystem.cc
References m_LayerSet, and set_int_param().
void PHG4DetectorGroupSubsystem::SetCalibrationFileDir (const std::string & calibdir) inline
Definition at line 54 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4DetectorGroupSubsystem.h
References m_CalibFileDir.
virtual void PHG4DetectorGroupSubsystem::SetDefaultParameters () pure virtual
Implemented in PHG4PSTOFSubsystem, PHG4InttSubsystem, PHG4EICMvtxSubsystem, and PHG4MvtxSubsystem.
Referenced by InitializeParameters().
void PHG4DetectorGroupSubsystem::SetSupportActive (const int detid, const int i = 1)
Definition at line 602 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 602 of file PHG4DetectorGroupSubsystem.cc
References set_int_param().
Referenced by Mvtx().
void PHG4DetectorGroupSubsystem::SetSupportActive (const int i = 1)
Definition at line 607 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 607 of file PHG4DetectorGroupSubsystem.cc
References m_LayerSet, and set_int_param().
void PHG4DetectorGroupSubsystem::SuperDetector (const std::string & name)
Definition at line 160 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 160 of file PHG4DetectorGroupSubsystem.cc
References m_SuperDetector, and perf_headwind::name.
Referenced by PSTOF().
const std::string PHG4DetectorGroupSubsystem::SuperDetector () const inline
Definition at line 69 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4DetectorGroupSubsystem.h
References m_SuperDetector.
Referenced by InitRun(), PHG4MvtxSubsystem::InitRunSubsystem(), PHG4EICMvtxSubsystem::InitRunSubsystem(), PHG4InttSubsystem::InitRunSubsystem(), PHG4PSTOFSubsystem::InitRunSubsystem(), PHG4EICMvtxSubsystem::PHG4EICMvtxSubsystem(), PHG4InttSubsystem::PHG4InttSubsystem(), PHG4MvtxSubsystem::PHG4MvtxSubsystem(), and PHG4PSTOFSubsystem::PHG4PSTOFSubsystem().
void PHG4DetectorGroupSubsystem::UpdateParametersWithMacro ()
Definition at line 337 of file PHG4DetectorGroupSubsystem.cc.
View newest version in sPHENIX GitHub at line 337 of file PHG4DetectorGroupSubsystem.cc
References PHParametersContainer::GetParametersToModify(), GetParamsContainer(), m_MacroDoubleParamsMap, m_MacroIntegerParamsMap, m_MacroStringParamsMap, PHParameters::set_double_param(), PHParameters::set_int_param(), and PHParameters::set_string_param().
Referenced by InitRun().
void PHG4DetectorGroupSubsystem::UseCalibFiles (const FILE_TYPE ftyp) inline
Definition at line 49 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4DetectorGroupSubsystem.h
References m_FileType.
void PHG4DetectorGroupSubsystem::UseDB (const int i = 1) inline
Definition at line 46 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4DetectorGroupSubsystem.h
References i, and m_UseDBFlag.
Member Data Documentation
int PHG4DetectorGroupSubsystem::m_BeginRunExecutedFlag = 0 private
Definition at line 98 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 98 of file PHG4DetectorGroupSubsystem.h
Referenced by BeginRunExecuted(), and InitRun().
std::string PHG4DetectorGroupSubsystem::m_CalibFileDir = "./" private
Definition at line 101 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 101 of file PHG4DetectorGroupSubsystem.h
Referenced by SaveParamsToFile(), and SetCalibrationFileDir().
std::map<int, std::map<const std::string, double> > PHG4DetectorGroupSubsystem::m_DefaultDoubleParamsMap private
Definition at line 109 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 109 of file PHG4DetectorGroupSubsystem.h
Referenced by InitializeParameters(), PrintDefaultParams(), set_default_double_param(), and set_double_param().
std::map<int, std::map<const std::string, int> > PHG4DetectorGroupSubsystem::m_DefaultIntegerParamsMap private
Definition at line 110 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 110 of file PHG4DetectorGroupSubsystem.h
Referenced by InitializeParameters(), PrintDefaultParams(), set_default_int_param(), and set_int_param().
std::map<int, std::map<const std::string, std::string> > PHG4DetectorGroupSubsystem::m_DefaultStringParamsMap private
Definition at line 111 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 111 of file PHG4DetectorGroupSubsystem.h
Referenced by InitializeParameters(), PrintDefaultParams(), set_default_string_param(), and set_string_param().
FILE_TYPE PHG4DetectorGroupSubsystem::m_FileType = PHG4DetectorGroupSubsystem::none private
Definition at line 99 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 99 of file PHG4DetectorGroupSubsystem.h
Referenced by get_filetype(), and UseCalibFiles().
int PHG4DetectorGroupSubsystem::m_Layer = 0 private
Definition at line 96 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 96 of file PHG4DetectorGroupSubsystem.h
Referenced by GetLayer().
std::set<int> PHG4DetectorGroupSubsystem::m_LayerSet private
Definition at line 103 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 103 of file PHG4DetectorGroupSubsystem.h
Referenced by AddDetId(), BlackHole(), GetDetIds(), InitializeParameters(), SetAbsorberActive(), SetAbsorberTruth(), SetActive(), and SetSupportActive().
std::map<int, std::map<const std::string, double> > PHG4DetectorGroupSubsystem::m_MacroDoubleParamsMap private
Definition at line 105 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 105 of file PHG4DetectorGroupSubsystem.h
Referenced by PrintMacroParams(), set_double_param(), and UpdateParametersWithMacro().
std::map<int, std::map<const std::string, int> > PHG4DetectorGroupSubsystem::m_MacroIntegerParamsMap private
Definition at line 106 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 106 of file PHG4DetectorGroupSubsystem.h
Referenced by PrintMacroParams(), set_int_param(), and UpdateParametersWithMacro().
std::map<int, std::map<const std::string, std::string> > PHG4DetectorGroupSubsystem::m_MacroStringParamsMap private
Definition at line 107 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 107 of file PHG4DetectorGroupSubsystem.h
Referenced by PrintMacroParams(), set_string_param(), and UpdateParametersWithMacro().
bool PHG4DetectorGroupSubsystem::m_OverlapCheckFlag = false private
Definition at line 95 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 95 of file PHG4DetectorGroupSubsystem.h
Referenced by CheckOverlap(), and OverlapCheck().
PHParametersContainer* PHG4DetectorGroupSubsystem::m_ParamsContainer = nullptr private
Definition at line 92 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 92 of file PHG4DetectorGroupSubsystem.h
Referenced by get_double_param(), get_int_param(), get_string_param(), GetParamsContainer(), InitRun(), SaveParamsToDB(), and SaveParamsToFile().
PHParametersContainer* PHG4DetectorGroupSubsystem::m_ParamsContainerDefault = nullptr private
Definition at line 93 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 93 of file PHG4DetectorGroupSubsystem.h
Referenced by Init(), InitializeParameters(), and InitRun().
PHCompositeNode* PHG4DetectorGroupSubsystem::m_SaveTopNode = nullptr private
Definition at line 94 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 94 of file PHG4DetectorGroupSubsystem.h
Referenced by Init().
std::string PHG4DetectorGroupSubsystem::m_SuperDetector = "NONE" private
Definition at line 100 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 100 of file PHG4DetectorGroupSubsystem.h
Referenced by InitRun(), and SuperDetector().
int PHG4DetectorGroupSubsystem::m_UseDBFlag = 0 private
Definition at line 97 of file PHG4DetectorGroupSubsystem.h.
View newest version in sPHENIX GitHub at line 97 of file PHG4DetectorGroupSubsystem.h
Referenced by ReadDB(), and UseDB().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.cc