Analysis Software: Acts::TrackSelector Class Reference
Acts::TrackSelector Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/TrackFinding/TrackSelector.hpp>
Classes
struct Config
struct EtaBinnedConfig
Public Member Functions
TrackSelector (const Config &config)
TrackSelector (const EtaBinnedConfig &config)
template<typename input_tracks_t , typename output_tracks_t >
void selectTracks (const input_tracks_t &inputTracks, output_tracks_t &outputTracks) const
template<typename track_proxy_t >
bool isValidTrack (const track_proxy_t &track) const
const EtaBinnedConfig & config () const
Private Attributes
EtaBinnedConfig m_cfg
bool m_isUnbinned
bool m_noEtaCuts
Static Private Attributes
static constexpr double inf = std::numeric_limits<double>::infinity()
Detailed Description
Class which performs filtering of tracks. It accepts an input and an output track container and uses the built-in copy facility to copy tracks into the output container.
Definition at line 22 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 22 of file TrackSelector.hpp
Constructor & Destructor Documentation
Acts::TrackSelector::TrackSelector (const Config & config) inline
Constructor from a single cut config object
Parameters
config is the configuration object
Definition at line 419 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 419 of file TrackSelector.hpp
Acts::TrackSelector::TrackSelector (const EtaBinnedConfig & config) inline
Constructor from a multi-eta
Parameters
config is the configuration object
Definition at line 387 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 387 of file TrackSelector.hpp
References Acts::TrackSelector::EtaBinnedConfig::absEtaEdges, Acts::TrackSelector::Config::absEtaMax, Acts::TrackSelector::Config::absEtaMin, cuts, Acts::TrackSelector::EtaBinnedConfig::cutSets, Acts::TrackSelector::Config::etaMax, Acts::TrackSelector::Config::etaMin, inf, m_cfg, m_isUnbinned, m_noEtaCuts, and Acts::TrackSelector::EtaBinnedConfig::nEtaBins().
Member Function Documentation
const EtaBinnedConfig& Acts::TrackSelector::config () const inline
Get readonly access to the config parameters
Returns
the config object
Definition at line 194 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 194 of file TrackSelector.hpp
References m_cfg.
template<typename track_proxy_t > bool Acts::TrackSelector::isValidTrack (const track_proxy_t & track) const
Helper function to check if a track is valid
Template Parameters
track_proxy_t is the type of the track proxy
Parameters
track is the track proxy
Returns
true if the track is valid
Definition at line 343 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 343 of file TrackSelector.hpp
References _eta, full_chain_itk::absEta, Acts::TrackSelector::EtaBinnedConfig::absEtaEdges, Acts::TrackSelector::Config::absEtaMax, Acts::TrackSelector::Config::absEtaMin, cuts, Acts::TrackSelector::EtaBinnedConfig::cutSets, Acts::TrackSelector::Config::etaMax, Acts::TrackSelector::Config::etaMin, Acts::TrackSelector::EtaBinnedConfig::getCuts(), Acts::TrackSelector::Config::loc0Max, Acts::TrackSelector::Config::loc0Min, Acts::TrackSelector::Config::loc1Max, Acts::TrackSelector::Config::loc1Min, m_cfg, m_isUnbinned, m_noEtaCuts, Acts::UnitConstants::min, Acts::TrackSelector::Config::minMeasurements, Acts::TrackSelector::Config::phiMax, Acts::TrackSelector::Config::phiMin, Acts::TrackSelector::Config::ptMax, Acts::TrackSelector::Config::ptMin, ActsTests::PropagationDatasets::theta, Acts::TrackSelector::Config::timeMax, Acts::TrackSelector::Config::timeMin, and ambiguity_solver_full_chain::x.
Referenced by selectTracks().
template<typename input_tracks_t , typename output_tracks_t > void Acts::TrackSelector::selectTracks (const input_tracks_t & inputTracks, output_tracks_t & outputTracks) const
Select tracks from an input container and copy them into an output container
Template Parameters
input_tracks_t is the type of the input track container
output_tracks_t is the type of the output track container
Parameters
inputTracks is the input track container
outputTracks is the output track container
Definition at line 330 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 330 of file TrackSelector.hpp
References isValidTrack().
Member Data Documentation
constexpr double Acts::TrackSelector::inf = std::numeric_limits<double>::infinity() static private
Definition at line 23 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 23 of file TrackSelector.hpp
Referenced by Acts::TrackSelector::Config::absEta(), Acts::TrackSelector::Config::eta(), and TrackSelector().
EtaBinnedConfig Acts::TrackSelector::m_cfg private
Definition at line 197 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 197 of file TrackSelector.hpp
Referenced by config(), isValidTrack(), and TrackSelector().
bool Acts::TrackSelector::m_isUnbinned private
Definition at line 198 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 198 of file TrackSelector.hpp
Referenced by isValidTrack(), and TrackSelector().
bool Acts::TrackSelector::m_noEtaCuts private
Definition at line 199 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 199 of file TrackSelector.hpp
Referenced by isValidTrack(), and TrackSelector().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/TrackFinding/TrackSelector.hpp