Analysis Software: SinglePrdfInput Class Reference
SinglePrdfInput Class Reference
#include <coresoftware/blob/master/offline/framework/fun4allraw/SinglePrdfInput.h>
Classes
struct PacketInfo
Public Member Functions
SinglePrdfInput (const std::string &name, Fun4AllPrdfInputPoolManager *inman)
~SinglePrdfInput () override
Eventiterator * GetEventIterator ()
virtual void FillPool (const unsigned int nevents)
int RunNumber () const
void RunNumber (const int irun)
int fileopen (const std::string &filename) override
int fileclose () override
int AllDone () const
void AllDone (const int i)
void EventNumberOffset (const int i)
int EventNumberOffset () const
Fun4AllPrdfInputPoolManager * InputMgr ()
void MakeReference (const bool b)
bool ReferenceFlag () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Print (const std::string &what="ALL") const
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from InputFileHandler
InputFileHandler ()=default
virtual ~InputFileHandler ()=default
int OpenNextFile ()
int AddListFile (const std::string &filename)
int AddFile (const std::string &filename)
void AddToFileOpened (const std::string &filename)
void Print (const std::string &what="ALL") const
int IsOpen () const
void IsOpen (const int i)
void SetVerbosity (const int i)
int GetVerbosity () const
void UpdateFileList ()
void FileName (const std::string &fn)
const std::string FileName () const
Private Member Functions
int majority_eventnumber ()
int majority_beamclock ()
void adjust_eventnumber_offset (const int decided_evtno)
Private Attributes
Eventiterator * m_EventIterator = nullptr
Fun4AllPrdfInputPoolManager * m_InputMgr = nullptr
Packet ** plist = nullptr
unsigned int m_NumSpecialEvents = 0
int m_EventNumberOffset = 1
int * m_PacketEventNumberOffset = nullptr
int m_RunNumber = 0
int m_EventsThisFile = 0
int m_AllDone = 0
bool m_MeReferenceFlag = false
std::map< int, std::vector
< Packet * > > m_PacketMap
std::set< int > m_EvtSet
std::vector< std::pair< int,
int > > m_Event
std::array< unsigned int, 100 > rollover
std::array< int, 100 > previous_eventnumber
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Detailed Description
Definition at line 19 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 19 of file SinglePrdfInput.h
Constructor & Destructor Documentation
SinglePrdfInput::SinglePrdfInput (const std::string & name, Fun4AllPrdfInputPoolManager * inman) explicit
Definition at line 16 of file SinglePrdfInput.cc.
View newest version in sPHENIX GitHub at line 16 of file SinglePrdfInput.cc
References m_PacketEventNumberOffset, Acts::UnitConstants::min, plist, previous_eventnumber, and rollover.
SinglePrdfInput::~SinglePrdfInput () override
Definition at line 27 of file SinglePrdfInput.cc.
View newest version in sPHENIX GitHub at line 27 of file SinglePrdfInput.cc
References m_EventIterator, m_PacketEventNumberOffset, and plist.
Member Function Documentation
void SinglePrdfInput::adjust_eventnumber_offset (const int decided_evtno) private
Definition at line 255 of file SinglePrdfInput.cc.
View newest version in sPHENIX GitHub at line 255 of file SinglePrdfInput.cc
References i, m_Event, m_PacketEventNumberOffset, and Fun4AllBase::Verbosity().
Referenced by FillPool().
int SinglePrdfInput::AllDone () const inline
Definition at line 30 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 30 of file SinglePrdfInput.h
References m_AllDone.
Referenced by SingleZdcInput::FillPool(), and FillPool().
void SinglePrdfInput::AllDone (const int i) inline
Definition at line 31 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 31 of file SinglePrdfInput.h
References i, and m_AllDone.
void SinglePrdfInput::EventNumberOffset (const int i) inline
Definition at line 32 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 32 of file SinglePrdfInput.h
References i, and m_EventNumberOffset.
int SinglePrdfInput::EventNumberOffset () const inline
Definition at line 33 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 33 of file SinglePrdfInput.h
References m_EventNumberOffset.
Referenced by SingleZdcInput::FillPool().
int SinglePrdfInput::fileclose () override virtual
Reimplemented from InputFileHandler.
Definition at line 349 of file SinglePrdfInput.cc.
View newest version in sPHENIX GitHub at line 349 of file SinglePrdfInput.cc
References InputFileHandler::IsOpen(), m_EventIterator, Fun4AllBase::Name(), and InputFileHandler::UpdateFileList().
Referenced by fileopen(), SingleZdcInput::FillPool(), and FillPool().
int SinglePrdfInput::fileopen (const std::string & filename) override virtual
Reimplemented from InputFileHandler.
Definition at line 317 of file SinglePrdfInput.cc.
View newest version in sPHENIX GitHub at line 317 of file SinglePrdfInput.cc
References InputFileHandler::AddToFileOpened(), fileclose(), InputFileHandler::FileName(), INTTVtxZ::fname, InputFileHandler::IsOpen(), FROG::location(), m_EventIterator, m_EventsThisFile, Fun4AllBase::Name(), PHWHERE, utils::status, and Fun4AllBase::Verbosity().
void SinglePrdfInput::FillPool (const unsigned int nevents) virtual
Reimplemented in SingleZdcInput.
Definition at line 34 of file SinglePrdfInput.cc.
View newest version in sPHENIX GitHub at line 34 of file SinglePrdfInput.cc
References Fun4AllPrdfInputPoolManager::AddBeamClock(), Fun4AllPrdfInputPoolManager::AddPacket(), adjust_eventnumber_offset(), AllDone(), Packet::convert(), DATAEVENT, fileclose(), Event::getEvtType(), Packet::getIdentifier(), Eventiterator::getNextEvent(), Event::getPacketList(), Event::getRunNumber(), i, Event::identify(), Packet::iValue(), m_Event, m_EventIterator, m_EventNumberOffset, m_EvtSet, m_InputMgr, m_MeReferenceFlag, m_NumSpecialEvents, m_PacketEventNumberOffset, m_PacketMap, m_RunNumber, majority_beamclock(), majority_eventnumber(), nevents(), InputFileHandler::OpenNextFile(), PHWHERE, plist, previous_eventnumber, rollover, Fun4AllPrdfInputPoolManager::SetReferenceClock(), Fun4AllPrdfInputPoolManager::UpdateDroppedPacket(), and Fun4AllBase::Verbosity().
Eventiterator* SinglePrdfInput::GetEventIterator () inline
Definition at line 24 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 24 of file SinglePrdfInput.h
References m_EventIterator.
Referenced by SingleZdcInput::FillPool().
Fun4AllPrdfInputPoolManager* SinglePrdfInput::InputMgr () inline
Definition at line 34 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 34 of file SinglePrdfInput.h
References m_InputMgr.
Referenced by SingleZdcInput::FillPool().
int SinglePrdfInput::majority_beamclock () private
Definition at line 292 of file SinglePrdfInput.cc.
View newest version in sPHENIX GitHub at line 292 of file SinglePrdfInput.cc
References m_Event, and Fun4AllBase::Verbosity().
Referenced by FillPool().
int SinglePrdfInput::majority_eventnumber () private
Definition at line 272 of file SinglePrdfInput.cc.
View newest version in sPHENIX GitHub at line 272 of file SinglePrdfInput.cc
References m_Event.
Referenced by FillPool().
void SinglePrdfInput::MakeReference (const bool b)
Definition at line 365 of file SinglePrdfInput.cc.
View newest version in sPHENIX GitHub at line 365 of file SinglePrdfInput.cc
References KFPMath::b, m_InputMgr, m_MeReferenceFlag, and Fun4AllPrdfInputPoolManager::SetReferenceInputMgr().
Referenced by Fun4All_Combiner().
bool SinglePrdfInput::ReferenceFlag () const inline
Definition at line 36 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 36 of file SinglePrdfInput.h
References m_MeReferenceFlag.
Referenced by SingleZdcInput::FillPool().
int SinglePrdfInput::RunNumber () const inline
Definition at line 26 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 26 of file SinglePrdfInput.h
References m_RunNumber.
Referenced by SingleZdcInput::FillPool().
void SinglePrdfInput::RunNumber (const int irun) inline
Definition at line 27 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 27 of file SinglePrdfInput.h
References m_RunNumber.
Member Data Documentation
int SinglePrdfInput::m_AllDone = 0 private
Definition at line 55 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 55 of file SinglePrdfInput.h
Referenced by AllDone().
std::vector<std::pair<int, int> > SinglePrdfInput::m_Event private
Definition at line 59 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 59 of file SinglePrdfInput.h
Referenced by adjust_eventnumber_offset(), FillPool(), majority_beamclock(), and majority_eventnumber().
Eventiterator* SinglePrdfInput::m_EventIterator = nullptr private
Definition at line 47 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 47 of file SinglePrdfInput.h
Referenced by fileclose(), fileopen(), FillPool(), GetEventIterator(), and ~SinglePrdfInput().
int SinglePrdfInput::m_EventNumberOffset = 1 private
Definition at line 51 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 51 of file SinglePrdfInput.h
Referenced by EventNumberOffset(), and FillPool().
int SinglePrdfInput::m_EventsThisFile = 0 private
Definition at line 54 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 54 of file SinglePrdfInput.h
Referenced by fileopen().
std::set<int> SinglePrdfInput::m_EvtSet private
Definition at line 58 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 58 of file SinglePrdfInput.h
Referenced by FillPool().
Fun4AllPrdfInputPoolManager* SinglePrdfInput::m_InputMgr = nullptr private
Definition at line 48 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 48 of file SinglePrdfInput.h
Referenced by FillPool(), InputMgr(), and MakeReference().
bool SinglePrdfInput::m_MeReferenceFlag = false private
Definition at line 56 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 56 of file SinglePrdfInput.h
Referenced by FillPool(), MakeReference(), and ReferenceFlag().
unsigned int SinglePrdfInput::m_NumSpecialEvents = 0 private
Definition at line 50 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 50 of file SinglePrdfInput.h
Referenced by FillPool().
int* SinglePrdfInput::m_PacketEventNumberOffset = nullptr private
Definition at line 52 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 52 of file SinglePrdfInput.h
Referenced by adjust_eventnumber_offset(), FillPool(), SinglePrdfInput(), and ~SinglePrdfInput().
std::map<int, std::vector<Packet *> > SinglePrdfInput::m_PacketMap private
Definition at line 57 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 57 of file SinglePrdfInput.h
Referenced by FillPool().
int SinglePrdfInput::m_RunNumber = 0 private
Definition at line 53 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 53 of file SinglePrdfInput.h
Referenced by FillPool(), and RunNumber().
Packet** SinglePrdfInput::plist = nullptr private
Definition at line 49 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 49 of file SinglePrdfInput.h
Referenced by FillPool(), SinglePrdfInput(), and ~SinglePrdfInput().
std::array<int,100> SinglePrdfInput::previous_eventnumber private
Definition at line 61 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 61 of file SinglePrdfInput.h
Referenced by FillPool(), and SinglePrdfInput().
std::array<unsigned int,100> SinglePrdfInput::rollover private
Definition at line 60 of file SinglePrdfInput.h.
View newest version in sPHENIX GitHub at line 60 of file SinglePrdfInput.h
Referenced by FillPool(), and SinglePrdfInput().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4allraw/SinglePrdfInput.h
coresoftware/blob/master/offline/framework/fun4allraw/SinglePrdfInput.cc