Analysis Software: MvtxCombinedRawDataDecoder Class Reference
MvtxCombinedRawDataDecoder Class Reference
mvtx raw data decoder
#include <coresoftware/blob/master/offline/packages/mvtx/MvtxCombinedRawDataDecoder.h>
Public Member Functions
MvtxCombinedRawDataDecoder (const std::string &name="MvtxCombinedRawDataDecoder")
constructor
int Init (PHCompositeNode *) override
global initialization
int InitRun (PHCompositeNode *) override
run initialization
int process_event (PHCompositeNode *) override
event processing
int End (PHCompositeNode *) override
end of processing
void useRawHitNodeName (const std::string &name)
void useRawEvtHeaderNodeName (const std::string &name)
void writeMvtxEventHeader (bool write)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void removeDuplicates (std::vector< std::pair< uint64_t, uint32_t >> &v)
Private Attributes
TrkrHitSetContainer * hit_set_container = nullptr
MvtxEventInfo * mvtx_event_header = nullptr
MvtxRawEvtHeader * mvtx_raw_event_header = nullptr
MvtxRawHitContainer * mvtx_hit_container = nullptr
MvtxRawHit * mvtx_hit = nullptr
std::string m_MvtxRawHitNodeName = "MVTXRAWHIT"
std::string m_MvtxRawEvtHeaderNodeName = "MVTXRAWEVTHEADER"
float m_strobeWidth = 89.
bool m_writeMvtxEventHeader = true
microseconds
std::vector< std::pair
< TrkrDefs::hitsetkey,
TrkrDefs::hitkey > > m_hotPixelMap
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
mvtx raw data decoder
Definition at line 27 of file MvtxCombinedRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 27 of file MvtxCombinedRawDataDecoder.h
Constructor & Destructor Documentation
MvtxCombinedRawDataDecoder::MvtxCombinedRawDataDecoder (const std::string & name = "MvtxCombinedRawDataDecoder")
constructor
Definition at line 32 of file MvtxCombinedRawDataDecoder.cc.
View newest version in sPHENIX GitHub at line 32 of file MvtxCombinedRawDataDecoder.cc
Member Function Documentation
int MvtxCombinedRawDataDecoder::End (PHCompositeNode *) override virtual
end of processing
Reimplemented from SubsysReco.
Definition at line 232 of file MvtxCombinedRawDataDecoder.cc.
View newest version in sPHENIX GitHub at line 232 of file MvtxCombinedRawDataDecoder.cc
References Fun4AllReturnCodes::EVENT_OK.
int MvtxCombinedRawDataDecoder::Init (PHCompositeNode *) override virtual
global initialization
Reimplemented from SubsysReco.
Definition at line 38 of file MvtxCombinedRawDataDecoder.cc.
View newest version in sPHENIX GitHub at line 38 of file MvtxCombinedRawDataDecoder.cc
References Fun4AllReturnCodes::EVENT_OK.
int MvtxCombinedRawDataDecoder::InitRun (PHCompositeNode * topNode) override virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 44 of file MvtxCombinedRawDataDecoder.cc.
View newest version in sPHENIX GitHub at line 44 of file MvtxCombinedRawDataDecoder.cc
References PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), MvtxDefs::genHitKey(), MvtxDefs::genHitSetKey(), CDBTTree::GetIntValue(), CDBTTree::GetSingleIntValue(), CDBInterface::getUrl(), hit_set_container, i, CDBInterface::instance(), m_hotPixelMap, m_MvtxRawEvtHeaderNodeName, m_writeMvtxEventHeader, mvtx_event_header, mvtx_raw_event_header, and PHWHERE.
int MvtxCombinedRawDataDecoder::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 123 of file MvtxCombinedRawDataDecoder.cc.
View newest version in sPHENIX GitHub at line 123 of file MvtxCombinedRawDataDecoder.cc
References Fun4AllReturnCodes::ABORTEVENT, assert, col, Fun4AllReturnCodes::EVENT_OK, TrkrHitSetContainer::findOrAddHitSet(), MvtxDefs::genHitKey(), MvtxDefs::genHitSetKey(), MvtxRawHit::get_bco(), MvtxRawHit::get_chip_id(), MvtxRawHit::get_col(), MvtxRawHit::get_layer_id(), MvtxRawHit::get_row(), MvtxRawHit::get_stave_id(), MvtxRawEvtHeader::getMvtxLvL1BCO(), hit_set_container, i, PHObject::identify(), MvtxEventInfo::identify(), index, layer, m_hotPixelMap, m_MvtxRawEvtHeaderNodeName, m_MvtxRawHitNodeName, m_strobeWidth, m_writeMvtxEventHeader, mvtx_event_header, mvtx_hit, mvtx_hit_container, mvtx_raw_event_header, PHWHERE, MvtxEventInfo::set_strobe_BCO(), MvtxEventInfo::set_strobe_BCO_L1_BCO(), Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_A_LOT, Fun4AllBase::VERBOSITY_EVEN_MORE, and Fun4AllBase::VERBOSITY_MORE.
void MvtxCombinedRawDataDecoder::removeDuplicates (std::vector< std::pair< uint64_t, uint32_t >> & v) private
Definition at line 237 of file MvtxCombinedRawDataDecoder.cc.
View newest version in sPHENIX GitHub at line 237 of file MvtxCombinedRawDataDecoder.cc
References end, it, and testSigmaEff::v.
void MvtxCombinedRawDataDecoder::useRawEvtHeaderNodeName (const std::string & name) inline
Definition at line 47 of file MvtxCombinedRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 47 of file MvtxCombinedRawDataDecoder.h
References m_MvtxRawEvtHeaderNodeName, and perf_headwind::name.
void MvtxCombinedRawDataDecoder::useRawHitNodeName (const std::string & name) inline
Definition at line 45 of file MvtxCombinedRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 45 of file MvtxCombinedRawDataDecoder.h
References m_MvtxRawHitNodeName, and perf_headwind::name.
void MvtxCombinedRawDataDecoder::writeMvtxEventHeader (bool write) inline
Definition at line 49 of file MvtxCombinedRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 49 of file MvtxCombinedRawDataDecoder.h
References m_writeMvtxEventHeader, and write().
Member Data Documentation
TrkrHitSetContainer* MvtxCombinedRawDataDecoder::hit_set_container = nullptr private
Definition at line 53 of file MvtxCombinedRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 53 of file MvtxCombinedRawDataDecoder.h
Referenced by InitRun(), and process_event().
std::vector<std::pair<TrkrDefs::hitsetkey, TrkrDefs::hitkey> > MvtxCombinedRawDataDecoder::m_hotPixelMap private
Definition at line 63 of file MvtxCombinedRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 63 of file MvtxCombinedRawDataDecoder.h
Referenced by InitRun(), and process_event().
std::string MvtxCombinedRawDataDecoder::m_MvtxRawEvtHeaderNodeName = "MVTXRAWEVTHEADER" private
Definition at line 60 of file MvtxCombinedRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 60 of file MvtxCombinedRawDataDecoder.h
Referenced by InitRun(), process_event(), and useRawEvtHeaderNodeName().
std::string MvtxCombinedRawDataDecoder::m_MvtxRawHitNodeName = "MVTXRAWHIT" private
Definition at line 59 of file MvtxCombinedRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 59 of file MvtxCombinedRawDataDecoder.h
Referenced by process_event(), and useRawHitNodeName().
float MvtxCombinedRawDataDecoder::m_strobeWidth = 89. private
Definition at line 61 of file MvtxCombinedRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 61 of file MvtxCombinedRawDataDecoder.h
Referenced by process_event().
bool MvtxCombinedRawDataDecoder::m_writeMvtxEventHeader = true private
microseconds
Definition at line 62 of file MvtxCombinedRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 62 of file MvtxCombinedRawDataDecoder.h
Referenced by InitRun(), process_event(), and writeMvtxEventHeader().
MvtxEventInfo* MvtxCombinedRawDataDecoder::mvtx_event_header = nullptr private
Definition at line 54 of file MvtxCombinedRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 54 of file MvtxCombinedRawDataDecoder.h
Referenced by InitRun(), and process_event().
MvtxRawHit* MvtxCombinedRawDataDecoder::mvtx_hit = nullptr private
Definition at line 57 of file MvtxCombinedRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 57 of file MvtxCombinedRawDataDecoder.h
Referenced by process_event().
MvtxRawHitContainer* MvtxCombinedRawDataDecoder::mvtx_hit_container = nullptr private
Definition at line 56 of file MvtxCombinedRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 56 of file MvtxCombinedRawDataDecoder.h
Referenced by process_event().
MvtxRawEvtHeader* MvtxCombinedRawDataDecoder::mvtx_raw_event_header = nullptr private
Definition at line 55 of file MvtxCombinedRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 55 of file MvtxCombinedRawDataDecoder.h
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mvtx/MvtxCombinedRawDataDecoder.h
coresoftware/blob/master/offline/packages/mvtx/MvtxCombinedRawDataDecoder.cc