Analysis Software: PHG4ParticleSvtxMap_v1 Class Reference
PHG4ParticleSvtxMap_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/PHG4ParticleSvtxMap_v1.h>
Public Member Functions
PHG4ParticleSvtxMap_v1 ()
PHG4ParticleSvtxMap_v1 (const PHG4ParticleSvtxMap_v1 &map)
PHG4ParticleSvtxMap_v1 & operator= (const PHG4ParticleSvtxMap_v1 &map)
~PHG4ParticleSvtxMap_v1 () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void Reset () override
Clear Event.
bool empty () const override
std::size_t size () const override
std::size_t count (const int key) const override
void clear () override
bool processed () const override
void setProcessed (const bool process) override
const WeightedRecoTrackMap & get (const int key) const override
WeightedRecoTrackMap & get (const int key) override
WeightedRecoTrackMap insert (const int key, const WeightedRecoTrackMap map) override
std::size_t erase (const int key) override
ConstIter begin () const override
ConstIter find (const int key) const override
ConstIter end () const override
Iter begin () override
Iter find (const int key) override
Iter end () override
Public Member Functions inherited from PHG4ParticleSvtxMap
~PHG4ParticleSvtxMap () override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (PHG4ParticleSvtxMap_v1, 1)
Private Attributes
PHG4ParticleSvtxMap::Map m_map
bool m_processed = false
Additional Inherited Members
Public Types inherited from PHG4ParticleSvtxMap
typedef std::map< float,
std::set< unsigned int > > WeightedRecoTrackMap
Truth->reco map with structure <g4part id, std::map< weight, std::set<reco track id>>>
typedef std::map< int,
WeightedRecoTrackMap > Map
typedef std::map< int,
WeightedRecoTrackMap >
::const_iterator ConstIter
typedef std::map< int,
WeightedRecoTrackMap >
::iterator Iter
Protected Member Functions inherited from PHG4ParticleSvtxMap
PHG4ParticleSvtxMap ()
Detailed Description
Definition at line 8 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 8 of file PHG4ParticleSvtxMap_v1.h
Constructor & Destructor Documentation
PHG4ParticleSvtxMap_v1::PHG4ParticleSvtxMap_v1 ()
Definition at line 3 of file PHG4ParticleSvtxMap_v1.cc.
View newest version in sPHENIX GitHub at line 3 of file PHG4ParticleSvtxMap_v1.cc
Referenced by CloneMe().
PHG4ParticleSvtxMap_v1::PHG4ParticleSvtxMap_v1 (const PHG4ParticleSvtxMap_v1 & map)
Definition at line 8 of file PHG4ParticleSvtxMap_v1.cc.
View newest version in sPHENIX GitHub at line 8 of file PHG4ParticleSvtxMap_v1.cc
References begin(), end(), and m_map.
PHG4ParticleSvtxMap_v1::~PHG4ParticleSvtxMap_v1 () override
Definition at line 30 of file PHG4ParticleSvtxMap_v1.cc.
View newest version in sPHENIX GitHub at line 30 of file PHG4ParticleSvtxMap_v1.cc
References Reset().
Member Function Documentation
ConstIter PHG4ParticleSvtxMap_v1::begin (void) const inline override virtual
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 40 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4ParticleSvtxMap_v1.h
References m_map.
Referenced by operator=(), and PHG4ParticleSvtxMap_v1().
Iter PHG4ParticleSvtxMap_v1::begin (void) inline override virtual
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 47 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4ParticleSvtxMap_v1.h
References m_map.
PHG4ParticleSvtxMap_v1::ClassDefOverride (PHG4ParticleSvtxMap_v1 , 1) private
void PHG4ParticleSvtxMap_v1::clear () inline override virtual
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 24 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 24 of file PHG4ParticleSvtxMap_v1.h
References m_map.
Referenced by Reset().
PHObject* PHG4ParticleSvtxMap_v1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 18 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 18 of file PHG4ParticleSvtxMap_v1.h
References PHG4ParticleSvtxMap_v1().
std::size_t PHG4ParticleSvtxMap_v1::count (const int key) const inline override virtual
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 23 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4ParticleSvtxMap_v1.h
References m_map.
bool PHG4ParticleSvtxMap_v1::empty () const inline override virtual
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 21 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4ParticleSvtxMap_v1.h
References m_map.
ConstIter PHG4ParticleSvtxMap_v1::end (void) const inline override virtual
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 45 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4ParticleSvtxMap_v1.h
References m_map.
Referenced by operator=(), and PHG4ParticleSvtxMap_v1().
Iter PHG4ParticleSvtxMap_v1::end (void) inline override virtual
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 49 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4ParticleSvtxMap_v1.h
References m_map.
std::size_t PHG4ParticleSvtxMap_v1::erase (const int key) inline override virtual
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 35 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4ParticleSvtxMap_v1.h
References m_map.
ConstIter PHG4ParticleSvtxMap_v1::find (const int key) const inline override virtual
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 41 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4ParticleSvtxMap_v1.h
References m_map.
Iter PHG4ParticleSvtxMap_v1::find (const int key) inline override virtual
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 48 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4ParticleSvtxMap_v1.h
References m_map.
const PHG4ParticleSvtxMap::WeightedRecoTrackMap & PHG4ParticleSvtxMap_v1::get (const int key) const override virtual
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 59 of file PHG4ParticleSvtxMap_v1.cc.
View newest version in sPHENIX GitHub at line 59 of file PHG4ParticleSvtxMap_v1.cc
References PHG4ParticleSvtxMap::get(), and m_map.
Referenced by HFTrackEfficiency::findTracks().
WeightedRecoTrackMap& PHG4ParticleSvtxMap_v1::get (const int key) inline override virtual
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 30 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4ParticleSvtxMap_v1.h
References m_map.
void PHG4ParticleSvtxMap_v1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 35 of file PHG4ParticleSvtxMap_v1.cc.
View newest version in sPHENIX GitHub at line 35 of file PHG4ParticleSvtxMap_v1.cc
References m_map.
PHG4ParticleSvtxMap::WeightedRecoTrackMap PHG4ParticleSvtxMap_v1::insert (const int key, const WeightedRecoTrackMap map) override virtual
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 53 of file PHG4ParticleSvtxMap_v1.cc.
View newest version in sPHENIX GitHub at line 53 of file PHG4ParticleSvtxMap_v1.cc
References m_map.
int PHG4ParticleSvtxMap_v1::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 17 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4ParticleSvtxMap_v1.h
PHG4ParticleSvtxMap_v1 & PHG4ParticleSvtxMap_v1::operator= (const PHG4ParticleSvtxMap_v1 & map)
Definition at line 18 of file PHG4ParticleSvtxMap_v1.cc.
View newest version in sPHENIX GitHub at line 18 of file PHG4ParticleSvtxMap_v1.cc
References begin(), end(), m_map, and Reset().
bool PHG4ParticleSvtxMap_v1::processed () const inline override virtual
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 26 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 26 of file PHG4ParticleSvtxMap_v1.h
References m_processed.
void PHG4ParticleSvtxMap_v1::Reset () inline override virtual
Clear Event.
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 20 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4ParticleSvtxMap_v1.h
References clear(), and m_processed.
Referenced by operator=(), and ~PHG4ParticleSvtxMap_v1().
void PHG4ParticleSvtxMap_v1::setProcessed (const bool process) inline override virtual
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 27 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4ParticleSvtxMap_v1.h
References m_processed, and tgeo-response2json::process().
std::size_t PHG4ParticleSvtxMap_v1::size (void) const inline override virtual
Reimplemented from PHG4ParticleSvtxMap.
Definition at line 22 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 22 of file PHG4ParticleSvtxMap_v1.h
References m_map.
Member Data Documentation
PHG4ParticleSvtxMap::Map PHG4ParticleSvtxMap_v1::m_map private
Definition at line 52 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4ParticleSvtxMap_v1.h
Referenced by begin(), clear(), count(), empty(), end(), erase(), find(), get(), identify(), insert(), operator=(), PHG4ParticleSvtxMap_v1(), and size().
bool PHG4ParticleSvtxMap_v1::m_processed = false private
Definition at line 53 of file PHG4ParticleSvtxMap_v1.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4ParticleSvtxMap_v1.h
Referenced by processed(), Reset(), and setProcessed().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/PHG4ParticleSvtxMap_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/PHG4ParticleSvtxMap_v1.cc