Analysis Software: Acts::ZScanVertexFinder< vfitter_t > Class Template Reference
Acts::ZScanVertexFinder< vfitter_t > Class Template Reference
Implements a vertex finder based on the mode of z0 values:
#include <acts/blob/sPHENIX/Core/include/Acts/Vertexing/ZScanVertexFinder.hpp>
Classes
struct Config
Configuration struct.
struct State
State struct for fulfilling interface.
Public Types
using InputTrack_t = typename vfitter_t::InputTrack_t
Public Member Functions
template<typename T = InputTrack_t, std::enable_if_t< std::is_same< T, BoundTrackParameters >::value, int > = 0>
ZScanVertexFinder (const Config &cfg, std::unique_ptr< const Logger > logger=getDefaultLogger("ZScanVertexFinder", Logging::INFO))
Constructor used if InputTrack_t type == BoundTrackParameters.
m_logger (std::move(logger))
ZScanVertexFinder (const Config &cfg, std::function< BoundTrackParameters(InputTrack_t)> func, std::unique_ptr< const Logger > logger=getDefaultLogger("ZScanVertexFinder", Logging::INFO))
Constructor for user-defined InputTrack_t type =! BoundTrackParameters.
Result< std::vector< Vertex
< InputTrack_t > > > find (const std::vector< const InputTrack_t * > &trackVector, const VertexingOptions< InputTrack_t > &vertexingOptions, State &state) const
Function that determines single vertex, based on z0 values of input tracks, using a Half Sample Mode algorithm.
Private Types
using Propagator_t = typename vfitter_t::Propagator_t
Private Member Functions
const Logger & logger () const
Private access to logging instance.
Private Attributes
Config m_cfg
std::function
< BoundTrackParameters(InputTrack_t)> m_extractParameters
Function to extract track parameters, InputTrack_t objects are BoundTrackParameters by default, function to be overwritten to return BoundTrackParameters for other InputTrack_t objects.
std::unique_ptr< const Logger > m_logger
Logging instance.
Detailed Description
template<typename vfitter_t>
class Acts::ZScanVertexFinder< vfitter_t >
Implements a vertex finder based on the mode of z0 values:
Determines the mode value of all input track z0 values
If no constraint is given, returns (0,0, z0_mode) as vertex position
If vertex constraint is given with x=x_constr and y=y_constr, the returned vertex position will be (x_constr, y_constr, z0_mode).
Definition at line 34 of file ZScanVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 34 of file ZScanVertexFinder.hpp
Member Typedef Documentation
template<typename vfitter_t > using Acts::ZScanVertexFinder< vfitter_t >::InputTrack_t = typename vfitter_t::InputTrack_t
Definition at line 40 of file ZScanVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 40 of file ZScanVertexFinder.hpp
template<typename vfitter_t > using Acts::ZScanVertexFinder< vfitter_t >::Propagator_t = typename vfitter_t::Propagator_t private
Definition at line 37 of file ZScanVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 37 of file ZScanVertexFinder.hpp
Constructor & Destructor Documentation
template<typename vfitter_t > template<typename T = InputTrack_t, std::enable_if_t< std::is_same< T, BoundTrackParameters >::value, int > = 0> Acts::ZScanVertexFinder< vfitter_t >::ZScanVertexFinder (const Config & cfg, std::unique_ptr< const Logger > logger = getDefaultLogger("ZScanVertexFinder< vfitter_t >", Logging::INFO)) inline
Constructor used if InputTrack_t type == BoundTrackParameters.
Parameters
cfg Configuration object
logger The logging instance
Definition at line 84 of file ZScanVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 84 of file ZScanVertexFinder.hpp
template<typename vfitter_t > Acts::ZScanVertexFinder< vfitter_t >::ZScanVertexFinder (const Config & cfg, std::function< BoundTrackParameters(InputTrack_t)> func, std::unique_ptr< const Logger > logger = getDefaultLogger("ZScanVertexFinder< vfitter_t >", Logging::INFO)) inline
Constructor for user-defined InputTrack_t type =! BoundTrackParameters.
Parameters
cfg Configuration object
func Function extracting BoundTrackParameters from InputTrack_t object
logger Logging instance
Definition at line 98 of file ZScanVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 98 of file ZScanVertexFinder.hpp
Member Function Documentation
template<typename vfitter_t > auto Acts::ZScanVertexFinder< vfitter_t >::find (const std::vector< const InputTrack_t * > & trackVector, const VertexingOptions< InputTrack_t > & vertexingOptions, State & state) const
Function that determines single vertex, based on z0 values of input tracks, using a Half Sample Mode algorithm.
Parameters
trackVector Input track collection
vertexingOptions Vertexing options
state State for fulfilling correct interface
Returns
Vector of vertices, filled with a single vertex (for consistent interfaces)
Definition at line 10 of file ZScanVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 10 of file ZScanVertexFinder.ipp
References ACTS_DEBUG, Acts::VertexingOptions< input_track_t >::constraint, Acts::ImpactParametersAndSigma::d0, Acts::eBoundQOverP, Acts::eBoundTheta, eZ, Acts::VertexingOptions< input_track_t >::geoContext, m_cfg(), Acts::VertexingOptions< input_track_t >::magFieldContext, check_smearing_config::output, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::parameters(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::position(), Pt(), Acts::ImpactParametersAndSigma::sigmaD0, Acts::VertexingOptions< input_track_t >::useConstraintInFit, and Acts::ImpactParametersAndSigma::z0.
template<typename vfitter_t > const Logger& Acts::ZScanVertexFinder< vfitter_t >::logger () const inline private
Private access to logging instance.
Definition at line 131 of file ZScanVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 131 of file ZScanVertexFinder.hpp
References Acts::ZScanVertexFinder< vfitter_t >::m_logger.
template<typename vfitter_t > Acts::ZScanVertexFinder< vfitter_t >::m_logger (std:: movelogger) inline
Definition at line 89 of file ZScanVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 89 of file ZScanVertexFinder.hpp
Member Data Documentation
template<typename vfitter_t > Config Acts::ZScanVertexFinder< vfitter_t >::m_cfg private
Definition at line 120 of file ZScanVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 120 of file ZScanVertexFinder.hpp
template<typename vfitter_t > std::function<BoundTrackParameters(InputTrack_t)> Acts::ZScanVertexFinder< vfitter_t >::m_extractParameters private
Function to extract track parameters, InputTrack_t objects are BoundTrackParameters by default, function to be overwritten to return BoundTrackParameters for other InputTrack_t objects.
Definition at line 125 of file ZScanVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 125 of file ZScanVertexFinder.hpp
template<typename vfitter_t > std::unique_ptr<const Logger> Acts::ZScanVertexFinder< vfitter_t >::m_logger private
Logging instance.
Definition at line 128 of file ZScanVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 128 of file ZScanVertexFinder.hpp
Referenced by Acts::ZScanVertexFinder< vfitter_t >::logger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Vertexing/ZScanVertexFinder.hpp
acts/blob/sPHENIX/Core/include/Acts/Vertexing/ZScanVertexFinder.ipp