Analysis Software: Acts::Intersection< DIM > Struct Template Reference
Acts::Intersection< DIM > Struct Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Utilities/Intersection.hpp>
Public Types
enum Status : int
Nested Status enum.
Public Member Functions
Intersection (const ActsVector< double, DIM > &sinter, double slength, Status sstatus)
Intersection ()=default
Default constructor.
operator bool () const
Bool() operator for validity checking.
bool operator< (const Intersection< DIM > &si) const
bool operator> (const Intersection< DIM > &si) const
Public Attributes
ActsVector< double, DIM > position = ActsVector<double, DIM>::Zero()
Position of the intersection.
double pathLength {std::numeric_limits<double>::infinity()}
Signed path length to the intersection (if valid)
Status status {Status::unreachable}
The Status of the intersection.
Detailed Description
template<unsigned int DIM>
struct Acts::Intersection< DIM >
Intersection struct used for position
Definition at line 24 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 24 of file Intersection.hpp
Member Enumeration Documentation
template<unsigned int DIM> enum Acts::Intersection::Status : int
Nested Status enum.
Definition at line 26 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 26 of file Intersection.hpp
Constructor & Destructor Documentation
template<unsigned int DIM> Acts::Intersection< DIM >::Intersection (const ActsVector< double, DIM > & sinter, double slength, Status sstatus) inline
Constructor with arguments
Parameters
sinter is the position of the intersection
slength is the path length to the intersection
svalid is a boolean indicating if intersection is valid
Definition at line 45 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 45 of file Intersection.hpp
template<unsigned int DIM> Acts::Intersection< DIM >::Intersection () default
Default constructor.
Member Function Documentation
template<unsigned int DIM> Acts::Intersection< DIM >::operator bool () const inline explicit
Bool() operator for validity checking.
Definition at line 53 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 53 of file Intersection.hpp
template<unsigned int DIM> bool Acts::Intersection< DIM >::operator< (const Intersection< DIM > & si) const inline
Smaller operator for sorting,
it respects the validity of the intersection
Parameters
si is the intersection for testing
Definition at line 58 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 58 of file Intersection.hpp
template<unsigned int DIM> bool Acts::Intersection< DIM >::operator> (const Intersection< DIM > & si) const inline
Greater operator for sorting,
it respects the validity of the intersection
Parameters
si is the intersection for testing
Definition at line 73 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 73 of file Intersection.hpp
Member Data Documentation
template<unsigned int DIM> double Acts::Intersection< DIM >::pathLength {std::numeric_limits<double>::infinity()}
Signed path length to the intersection (if valid)
Definition at line 36 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 36 of file Intersection.hpp
Referenced by Acts::TrackingVolume::compatibleBoundaries(), Acts::Layer::compatibleSurfaces(), Acts::SurfaceReached::operator()(), Acts::Intersection< 3 >::operator<(), Acts::Intersection< 3 >::operator>(), and Acts::Layer::surfaceOnApproach().
template<unsigned int DIM> ActsVector<double, DIM> Acts::Intersection< DIM >::position = ActsVector<double, DIM>::Zero()
Position of the intersection.
Definition at line 34 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 34 of file Intersection.hpp
template<unsigned int DIM> Status Acts::Intersection< DIM >::status {Status::unreachable}
The Status of the intersection.
Definition at line 38 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 38 of file Intersection.hpp
Referenced by Acts::Intersection< 3 >::operator bool(), Acts::Intersection< 3 >::operator<(), and Acts::Intersection< 3 >::operator>().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Utilities/Intersection.hpp