Analysis Software: RawTower Class Reference
RawTower Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTower.h>
Public Types
enum PROPERTY { prop_scint_gammas = 1, prop_cerenkov_gammas = 2, prop_MAX_NUMBER = UCHAR_MAX }
typedef unsigned long long CellKeyType
key type for cell map which should be consistent with CellKeyType
typedef std::map< CellKeyType,
float > CellMap
typedef CellMap::iterator CellIterator
typedef CellMap::const_iterator CellConstIterator
typedef std::pair
< CellIterator, CellIterator > CellRange
typedef std::pair
< CellConstIterator,
CellConstIterator > CellConstRange
typedef std::map< int, float > ShowerMap
typedef ShowerMap::iterator ShowerIterator
typedef ShowerMap::const_iterator ShowerConstIterator
typedef std::pair
< ShowerIterator,
ShowerIterator > ShowerRange
typedef std::pair
< ShowerConstIterator,
ShowerConstIterator > ShowerConstRange
Public Member Functions
~RawTower () override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &=std::cout) const override
virtual void set_id (RawTowerDefs::keytype)
virtual RawTowerDefs::keytype get_id () const
virtual void set_key (RawTowerDefs::keytype id)
virtual RawTowerDefs::keytype get_key () const
virtual int get_bineta () const
virtual int get_bintheta () const
virtual int get_binphi () const
virtual int get_binl () const
return layer ID assigned to tower
virtual int get_column () const
virtual int get_row () const
virtual double get_energy () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual void set_energy (const double)
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual double get_scint_gammas () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual void set_scint_gammas (const double)
scint_gammas assigned to the tower. Depending on stage of process and DST node name, it could be scint_gammas deposition, light yield or calibrated energies
virtual double get_cerenkov_gammas () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual void set_cerenkov_gammas (const double)
cerenkov_gammas assigned to the tower. Depending on stage of process and DST node name, it could be cerenkov_gammas deposition, light yield or calibrated energies
virtual float get_time () const
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
virtual void set_time (const float)
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
virtual bool empty_g4cells () const
virtual size_t size_g4cells () const
virtual CellConstRange get_g4cells () const
virtual CellIterator find_g4cell (CellKeyType id)
virtual CellConstIterator find_g4cell (CellKeyType id) const
virtual void add_ecell (const CellKeyType, const float)
virtual void clear_g4cells ()
virtual bool empty_g4showers () const
virtual size_t size_g4showers () const
virtual ShowerConstRange get_g4showers () const
virtual ShowerIterator find_g4shower (int)
virtual ShowerConstIterator find_g4shower (int) const
virtual void add_eshower (const int, const float)
virtual void clear_g4showers ()
virtual bool has_property (const PROPERTY) const
virtual double get_property (const PROPERTY) const
virtual void set_property (const PROPERTY, const double)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Static Public Member Functions
static const std::string get_property_info (PROPERTY prop_id)
Protected Member Functions
RawTower ()
virtual unsigned int get_property_nocheck (const PROPERTY) const
virtual void set_property_nocheck (const PROPERTY, const unsigned int)
Detailed Description
Definition at line 17 of file RawTower.h.
View newest version in sPHENIX GitHub at line 17 of file RawTower.h
Member Typedef Documentation
typedef CellMap::const_iterator RawTower::CellConstIterator
Definition at line 25 of file RawTower.h.
View newest version in sPHENIX GitHub at line 25 of file RawTower.h
typedef std::pair<CellConstIterator, CellConstIterator> RawTower::CellConstRange
Definition at line 27 of file RawTower.h.
View newest version in sPHENIX GitHub at line 27 of file RawTower.h
typedef CellMap::iterator RawTower::CellIterator
Definition at line 24 of file RawTower.h.
View newest version in sPHENIX GitHub at line 24 of file RawTower.h
typedef unsigned long long RawTower::CellKeyType
key type for cell map which should be consistent with CellKeyType
Definition at line 21 of file RawTower.h.
View newest version in sPHENIX GitHub at line 21 of file RawTower.h
typedef std::map<CellKeyType, float> RawTower::CellMap
Definition at line 23 of file RawTower.h.
View newest version in sPHENIX GitHub at line 23 of file RawTower.h
typedef std::pair<CellIterator, CellIterator> RawTower::CellRange
Definition at line 26 of file RawTower.h.
View newest version in sPHENIX GitHub at line 26 of file RawTower.h
typedef ShowerMap::const_iterator RawTower::ShowerConstIterator
Definition at line 31 of file RawTower.h.
View newest version in sPHENIX GitHub at line 31 of file RawTower.h
typedef std::pair<ShowerConstIterator, ShowerConstIterator> RawTower::ShowerConstRange
Definition at line 33 of file RawTower.h.
View newest version in sPHENIX GitHub at line 33 of file RawTower.h
typedef ShowerMap::iterator RawTower::ShowerIterator
Definition at line 30 of file RawTower.h.
View newest version in sPHENIX GitHub at line 30 of file RawTower.h
typedef std::map<int, float> RawTower::ShowerMap
Definition at line 29 of file RawTower.h.
View newest version in sPHENIX GitHub at line 29 of file RawTower.h
typedef std::pair<ShowerIterator, ShowerIterator> RawTower::ShowerRange
Definition at line 32 of file RawTower.h.
View newest version in sPHENIX GitHub at line 32 of file RawTower.h
Member Enumeration Documentation
enum RawTower::PROPERTY
Procedure to add a new PROPERTY tag: 1.add new tag below with unique value, 2.add a short name to RawTower::get_property_info
Enumerator:
prop_scint_gammas
Scintillation photon count or energy.
prop_cerenkov_gammas
Cherenkov photon count or energy.
prop_MAX_NUMBER
max limit in order to fit into 8 bit unsigned number
Definition at line 168 of file RawTower.h.
View newest version in sPHENIX GitHub at line 168 of file RawTower.h
Constructor & Destructor Documentation
RawTower::~RawTower () inline override
Definition at line 35 of file RawTower.h.
View newest version in sPHENIX GitHub at line 35 of file RawTower.h
RawTower::RawTower () inline protected
Definition at line 187 of file RawTower.h.
View newest version in sPHENIX GitHub at line 187 of file RawTower.h
Member Function Documentation
virtual void RawTower::add_ecell (const CellKeyType , const float) inline virtual
Reimplemented in RawTowerv1.
Definition at line 146 of file RawTower.h.
View newest version in sPHENIX GitHub at line 146 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerBuilder::process_event(), HcalRawTowerBuilder::process_event(), and RawTowerCombiner::process_event().
virtual void RawTower::add_eshower (const int , const float) inline virtual
Reimplemented in RawTowerv1.
Definition at line 158 of file RawTower.h.
View newest version in sPHENIX GitHub at line 158 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerBuilder::process_event(), HcalRawTowerBuilder::process_event(), and RawTowerCombiner::process_event().
virtual void RawTower::clear_g4cells () inline virtual
Reimplemented in RawTowerv1.
Definition at line 151 of file RawTower.h.
View newest version in sPHENIX GitHub at line 151 of file RawTower.h
Referenced by PHG4DstCompressReco::process_event().
virtual void RawTower::clear_g4showers () inline virtual
Reimplemented in RawTowerv1.
Definition at line 163 of file RawTower.h.
View newest version in sPHENIX GitHub at line 163 of file RawTower.h
virtual bool RawTower::empty_g4cells () const inline virtual
Reimplemented in RawTowerv1.
Definition at line 141 of file RawTower.h.
View newest version in sPHENIX GitHub at line 141 of file RawTower.h
virtual bool RawTower::empty_g4showers () const inline virtual
Reimplemented in RawTowerv1.
Definition at line 153 of file RawTower.h.
View newest version in sPHENIX GitHub at line 153 of file RawTower.h
RawTower::CellIterator RawTower::find_g4cell (CellKeyType id) virtual
Reimplemented in RawTowerv1.
Definition at line 10 of file RawTower.cc.
View newest version in sPHENIX GitHub at line 10 of file RawTower.cc
References DummyCellMap.
RawTower::CellConstIterator RawTower::find_g4cell (CellKeyType id) const virtual
Reimplemented in RawTowerv1.
Definition at line 15 of file RawTower.cc.
View newest version in sPHENIX GitHub at line 15 of file RawTower.cc
References DummyCellMap.
RawTower::ShowerIterator RawTower::find_g4shower (int) virtual
Reimplemented in RawTowerv1.
Definition at line 32 of file RawTower.cc.
View newest version in sPHENIX GitHub at line 32 of file RawTower.cc
References DummyShowerMap.
Referenced by CaloRawTowerEval::get_energy_contribution().
RawTower::ShowerConstIterator RawTower::find_g4shower (int) const virtual
Reimplemented in RawTowerv1.
Definition at line 37 of file RawTower.cc.
View newest version in sPHENIX GitHub at line 37 of file RawTower.cc
References DummyShowerMap.
virtual int RawTower::get_bineta () const inline virtual
Reimplemented in RawTower_Prototype3, RawTower_Prototype4, RawTowerv1, RawTower_Prototype2, and RawTower_Prototype4.
Definition at line 55 of file RawTower.h.
View newest version in sPHENIX GitHub at line 55 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
Referenced by cemcReco::calculateTSP(), CaloEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), get_bintheta(), STACalorimeterCharacterization::inspect_ordered_towers(), EventInfoSummary::process_event(), RawClusterDeadHotMask::process_event(), RawClusterPositionCorrection::process_event(), RawTowerCalibration::process_event(), HCalib::process_event(), Proto4ShowerCalib::process_event(), SubtractTowers::process_event(), SubtractTowersCS::process_event(), Proto3ShowerCalib::process_event(), Proto2ShowerCalib::process_event(), CaloCalibEmc_Pi0::process_event(), JetUnderlyingEvent::process_event(), Proto4TowerCalib::process_event(), ExampleAnalysisModule::process_event(), PhotonJet::process_event(), LiteCaloEval::process_event(), RawTowerCombiner::process_event(), DumpRawTowerContainer::process_Node(), and twrs::twrs().
virtual int RawTower::get_binl () const inline virtual
return layer ID assigned to tower
Reimplemented in RawTowerv1.
Definition at line 73 of file RawTower.h.
View newest version in sPHENIX GitHub at line 73 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerCalibration::process_event().
virtual int RawTower::get_binphi () const inline virtual
Reimplemented in RawTower_Prototype3, RawTower_Prototype4, RawTowerv1, RawTower_Prototype2, and RawTower_Prototype4.
Definition at line 66 of file RawTower.h.
View newest version in sPHENIX GitHub at line 66 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
Referenced by cemcReco::calculateTSP(), CaloEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), STACalorimeterCharacterization::inspect_ordered_towers(), EventInfoSummary::process_event(), RawClusterDeadHotMask::process_event(), RawClusterPositionCorrection::process_event(), RawTowerCalibration::process_event(), HCalib::process_event(), Proto4ShowerCalib::process_event(), SubtractTowersCS::process_event(), SubtractTowers::process_event(), Proto2ShowerCalib::process_event(), Proto3ShowerCalib::process_event(), Proto4TowerCalib::process_event(), CaloCalibEmc_Pi0::process_event(), ExampleAnalysisModule::process_event(), PhotonJet::process_event(), LiteCaloEval::process_event(), RawTowerCombiner::process_event(), DumpRawTowerContainer::process_Node(), and twrs::twrs().
virtual int RawTower::get_bintheta () const inline virtual
Definition at line 61 of file RawTower.h.
View newest version in sPHENIX GitHub at line 61 of file RawTower.h
References get_bineta().
virtual double RawTower::get_cerenkov_gammas () const inline virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented in RawTowerv2.
Definition at line 116 of file RawTower.h.
View newest version in sPHENIX GitHub at line 116 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
virtual int RawTower::get_column () const inline virtual
Reimplemented in RawTower_Prototype3, RawTower_Prototype4, RawTower_Prototype2, RawTower_Prototype4, RawTower_Temperature, RawTower_Temperature, RawTower_Temperature, and RawTower_Temperature.
Definition at line 78 of file RawTower.h.
View newest version in sPHENIX GitHub at line 78 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
Referenced by Proto4ShowerCalib::process_event(), and Proto2ShowerCalib::process_event().
virtual double RawTower::get_energy () const inline virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented in RawTower_Prototype3, RawTower_Prototype4, RawTower_Prototype2, RawTower_Prototype4, and RawTowerv1.
Definition at line 90 of file RawTower.h.
View newest version in sPHENIX GitHub at line 90 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
Referenced by DISKinematicsReco::AddGlobalCalorimeterInformation(), LeptoquarksReco::AddGlobalEventInformation(), LeptoquarksReco::AddJetStructureInformation(), cemcReco::calculateTSP(), RawTowerContainer::compress(), TreeMaker::CopyAndMakeJets(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), EpFinderEval::fill_tree(), Calib::fill_tree(), CaloEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), Proto4SampleFrac::find_max(), Proto4ShowerCalib::find_max(), Proto2ShowerCalib::find_max(), Proto3ShowerCalib::find_max(), Proto4TowerCalib::find_max(), ExampleAnalysisModule::find_max(), sPHAnalysis::Get_CAL_e3x3(), JetRecoEval::get_energy_contribution(), TowerJetInput::get_input(), STACalorimeterCharacterization::get_ordered_towers(), TrackProjectionTools::getE33Barrel(), TrackProjectionTools::getE33Forward(), IsolatedTrackAnalysis::getSimTowers(), IsolatedTrackAnalysis::getTowers(), STACalorimeterCharacterization::inspect_ordered_towers(), RawClusterBuilderTemplate::IsAcceptableTower(), RawClusterBuilderGraph::process_event(), EventInfoSummary::process_event(), RawClusterDeadHotMask::process_event(), RawTowerBuilder::process_event(), RawClusterBuilderTemplate::process_event(), RecoInfoExport::process_event(), RawClusterPositionCorrection::process_event(), HcalRawTowerBuilder::process_event(), RawTowerCalibration::process_event(), HCalib::process_event(), Proto4ShowerCalib::process_event(), SubtractTowersCS::process_event(), RawTowerDigitizer::process_event(), SubtractTowers::process_event(), CopyAndSubtractJets::process_event(), RetowerCEMC::process_event(), DetermineTowerBackground::process_event(), Proto3ShowerCalib::process_event(), Proto2ShowerCalib::process_event(), Proto4TowerCalib::process_event(), JetUnderlyingEvent::process_event(), TruthCaloTree::process_event(), ExampleAnalysisModule::process_event(), MyJetAnalysis::process_event(), LiteCaloEval::process_event(), RawTowerCombiner::process_event(), sPHAnalysis::process_event_notracking(), sPHAnalysis_calo::process_event_test(), QAG4SimulationCalorimeter::process_event_Tower(), EMCalAna::process_event_Tower(), EMCalCalib::process_event_Tower(), EMCalCalib_TestBeam::process_event_Tower(), DumpRawTowerContainer::process_Node(), RawTower_Prototype2::RawTower_Prototype2(), RawTower_Prototype4::RawTower_Prototype4(), RawTowerv1::RawTowerv1(), RawTowerDigitizer::simple_photon_digitization(), and RawTowerDigitizer::sipm_photon_digitization().
RawTower::CellConstRange RawTower::get_g4cells () const virtual
Reimplemented in RawTowerv1.
Definition at line 20 of file RawTower.cc.
View newest version in sPHENIX GitHub at line 20 of file RawTower.cc
References DummyCellMap, and PHOOL_VIRTUAL_WARN.
Referenced by CaloRawTowerEval::all_truth_hits(), RawTowerCombiner::process_event(), DumpRawTowerContainer::process_Node(), and RawTowerv1::RawTowerv1().
RawTower::ShowerConstRange RawTower::get_g4showers () const virtual
Reimplemented in RawTowerv1.
Definition at line 26 of file RawTower.cc.
View newest version in sPHENIX GitHub at line 26 of file RawTower.cc
References DummyShowerMap, and PHOOL_VIRTUAL_WARN.
Referenced by CaloRawTowerEval::all_truth_primary_showers(), CaloRawTowerEval::get_energy_contribution(), RawTowerCombiner::process_event(), DumpRawTowerContainer::process_Node(), and RawTowerv1::RawTowerv1().
virtual RawTowerDefs::keytype RawTower::get_id () const inline virtual
Reimplemented in RawTower_Temperature, RawTower_Temperature, RawTower_Temperature, RawTower_Prototype3, RawTower_Temperature, RawTower_Prototype4, RawTowerv1, RawTower_Prototype2, and RawTower_Prototype4.
Definition at line 46 of file RawTower.h.
View newest version in sPHENIX GitHub at line 46 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
Referenced by CaloEvaluator::fillOutputNtuples(), TowerJetInput::get_input(), get_key(), RawClusterBuilderGraph::process_event(), RawClusterBuilderTemplate::process_event(), RawTowerCalibration::process_event(), Proto4ShowerCalib::process_event(), Proto2ShowerCalib::process_event(), Proto3ShowerCalib::process_event(), ExampleAnalysisModule::process_event(), MyJetAnalysis::process_event(), LiteCaloEval::process_event(), RawTower_Prototype2::RawTower_Prototype2(), RawTower_Prototype4::RawTower_Prototype4(), and RawTowerv1::RawTowerv1().
virtual RawTowerDefs::keytype RawTower::get_key () const inline virtual
Definition at line 53 of file RawTower.h.
View newest version in sPHENIX GitHub at line 53 of file RawTower.h
References get_id().
Referenced by TreeMaker::CopyAndMakeJets(), sPHAnalysis::Get_CAL_e3x3(), TowerJetInput::get_input(), IsolatedTrackAnalysis::getSimTowers(), IsolatedTrackAnalysis::getTowers(), SubtractTowers::process_event(), SubtractTowersCS::process_event(), CopyAndSubtractJets::process_event(), RetowerCEMC::process_event(), DetermineTowerBackground::process_event(), JetUnderlyingEvent::process_event(), TruthCaloTree::process_event(), MyJetAnalysis::process_event(), sPHAnalysis::process_event_notracking(), and sPHAnalysis_calo::process_event_test().
virtual double RawTower::get_property (const PROPERTY) const inline virtual
Reimplemented in RawTowerv2.
Definition at line 182 of file RawTower.h.
View newest version in sPHENIX GitHub at line 182 of file RawTower.h
Referenced by RawTowerv2::RawTowerv2().
const std::string RawTower::get_property_info (RawTower::PROPERTY prop_id) static
Definition at line 42 of file RawTower.cc.
View newest version in sPHENIX GitHub at line 42 of file RawTower.cc
References prop_cerenkov_gammas, and prop_scint_gammas.
Referenced by RawTowerv2::identify().
virtual unsigned int RawTower::get_property_nocheck (const PROPERTY) const inline protected virtual
Definition at line 189 of file RawTower.h.
View newest version in sPHENIX GitHub at line 189 of file RawTower.h
virtual int RawTower::get_row () const inline virtual
Reimplemented in RawTower_Prototype3, RawTower_Prototype4, RawTower_Prototype2, RawTower_Prototype4, RawTower_Temperature, RawTower_Temperature, RawTower_Temperature, and RawTower_Temperature.
Definition at line 83 of file RawTower.h.
View newest version in sPHENIX GitHub at line 83 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
Referenced by Proto4ShowerCalib::process_event(), and Proto2ShowerCalib::process_event().
virtual double RawTower::get_scint_gammas () const inline virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented in RawTowerv2.
Definition at line 103 of file RawTower.h.
View newest version in sPHENIX GitHub at line 103 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
virtual float RawTower::get_time () const inline virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented in RawTower_Prototype3, RawTower_Prototype4, RawTower_Prototype2, RawTower_Prototype4, and RawTowerv1.
Definition at line 129 of file RawTower.h.
View newest version in sPHENIX GitHub at line 129 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerCombiner::process_event(), RawTower_Prototype2::RawTower_Prototype2(), RawTower_Prototype4::RawTower_Prototype4(), and RawTowerv1::RawTowerv1().
virtual bool RawTower::has_property (const PROPERTY) const inline virtual
Reimplemented in RawTowerv2.
Definition at line 181 of file RawTower.h.
View newest version in sPHENIX GitHub at line 181 of file RawTower.h
Referenced by RawTowerv2::RawTowerv2().
void RawTower::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in RawTower_Prototype3, RawTowerv1, RawTowerv2, RawTower_Prototype2, RawTower_Prototype4, RawTower_Temperature, RawTower_Temperature, and RawTower_Temperature.
Definition at line 43 of file RawTower.h.
View newest version in sPHENIX GitHub at line 43 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
Referenced by CaloEvaluator::fillOutputNtuples(), RawTowerBuilder::process_event(), RawTowerDigitizer::process_event(), LiteCaloEval::process_event(), RawTowerCombiner::process_event(), RawTowerDigitizer::simple_photon_digitization(), and RawTowerDigitizer::sipm_photon_digitization().
int RawTower::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in RawTower_Prototype3, RawTowerv1, RawTowerv2, RawTower_Prototype2, RawTower_Prototype4, RawTower_Temperature, RawTower_Temperature, and RawTower_Temperature.
Definition at line 38 of file RawTower.h.
View newest version in sPHENIX GitHub at line 38 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
void RawTower::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in RawTower_Prototype3, RawTowerv1, RawTowerv2, RawTower_Prototype2, RawTower_Prototype4, RawTower_Temperature, RawTower_Temperature, and RawTower_Temperature.
Definition at line 37 of file RawTower.h.
View newest version in sPHENIX GitHub at line 37 of file RawTower.h
References PHOOL_VIRTUAL_WARNING.
virtual void RawTower::set_cerenkov_gammas (const double) inline virtual
cerenkov_gammas assigned to the tower. Depending on stage of process and DST node name, it could be cerenkov_gammas deposition, light yield or calibrated energies
Reimplemented in RawTowerv2.
Definition at line 122 of file RawTower.h.
View newest version in sPHENIX GitHub at line 122 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTower::set_energy (const double) inline virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented in RawTower_Prototype3, RawTower_Prototype4, RawTower_Prototype2, RawTower_Prototype4, and RawTowerv1.
Definition at line 96 of file RawTower.h.
View newest version in sPHENIX GitHub at line 96 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerBuilder::process_event(), HcalRawTowerBuilder::process_event(), RawTowerCalibration::process_event(), SubtractTowers::process_event(), RawTowerDigitizer::process_event(), SubtractTowersCS::process_event(), RetowerCEMC::process_event(), RawTowerCombiner::process_event(), RawTowerDigitizer::simple_photon_digitization(), and RawTowerDigitizer::sipm_photon_digitization().
virtual void RawTower::set_id (RawTowerDefs::keytype) inline virtual
Reimplemented in RawTower_Temperature, RawTower_Temperature, RawTower_Temperature, RawTower_Prototype3, RawTower_Temperature, RawTower_Prototype4, RawTowerv1, RawTower_Prototype2, and RawTower_Prototype4.
Definition at line 45 of file RawTower.h.
View newest version in sPHENIX GitHub at line 45 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerContainer::AddTower(), and set_key().
virtual void RawTower::set_key (RawTowerDefs::keytype id) inline virtual
Definition at line 52 of file RawTower.h.
View newest version in sPHENIX GitHub at line 52 of file RawTower.h
References set_id().
virtual void RawTower::set_property (const PROPERTY , const double) inline virtual
Reimplemented in RawTowerv2.
Definition at line 183 of file RawTower.h.
View newest version in sPHENIX GitHub at line 183 of file RawTower.h
virtual void RawTower::set_property_nocheck (const PROPERTY , const unsigned int) inline protected virtual
Definition at line 190 of file RawTower.h.
View newest version in sPHENIX GitHub at line 190 of file RawTower.h
virtual void RawTower::set_scint_gammas (const double) inline virtual
scint_gammas assigned to the tower. Depending on stage of process and DST node name, it could be scint_gammas deposition, light yield or calibrated energies
Reimplemented in RawTowerv2.
Definition at line 109 of file RawTower.h.
View newest version in sPHENIX GitHub at line 109 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTower::set_time (const float) inline virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented in RawTower_Prototype3, RawTower_Prototype4, RawTower_Prototype2, RawTower_Prototype4, and RawTowerv1.
Definition at line 135 of file RawTower.h.
View newest version in sPHENIX GitHub at line 135 of file RawTower.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerCombiner::process_event().
virtual size_t RawTower::size_g4cells () const inline virtual
Reimplemented in RawTowerv1.
Definition at line 142 of file RawTower.h.
View newest version in sPHENIX GitHub at line 142 of file RawTower.h
virtual size_t RawTower::size_g4showers () const inline virtual
Reimplemented in RawTowerv1.
Definition at line 154 of file RawTower.h.
View newest version in sPHENIX GitHub at line 154 of file RawTower.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTower.h
coresoftware/blob/master/offline/packages/CaloBase/RawTower.cc