Analysis Software: AlignedDetector Struct Reference
AlignedDetector Struct Reference
#include <acts/blob/sPHENIX/Examples/Detectors/ContextualDetector/include/ActsExamples/ContextualDetector/AlignedDetector.hpp>
Public Types
using DetectorElement = ActsExamples::Contextual::AlignedDetectorElement
using DetectorElementPtr = std::shared_ptr< DetectorElement >
using Decorator = ActsExamples::Contextual::AlignmentDecorator
using DetectorStore = std::vector< std::vector< DetectorElementPtr >>
Public Types inherited from ActsExamples::IBaseDetector
using ContextDecorators = std::vector< std::shared_ptr< ActsExamples::IContextDecorator >>
using TrackingGeometryPtr = std::shared_ptr< const Acts::TrackingGeometry >
Public Member Functions
void addOptions (boost::program_options::options_description &opt) const override
std::pair
< ActsExamples::IBaseDetector::TrackingGeometryPtr,
ContextDecorators > finalize (const boost::program_options::variables_map &vm, std::shared_ptr< const Acts::IMaterialDecorator > mdecorator) override
Public Member Functions inherited from ActsExamples::IBaseDetector
virtual ~IBaseDetector ()=default
Public Attributes
DetectorStore detectorStore
The Store of the detector elements (lifetime: job)
Detailed Description
Definition at line 17 of file AlignedDetector.hpp.
View newest version in sPHENIX GitHub at line 17 of file AlignedDetector.hpp
Member Typedef Documentation
using AlignedDetector::Decorator = ActsExamples::Contextual::AlignmentDecorator
Definition at line 20 of file AlignedDetector.hpp.
View newest version in sPHENIX GitHub at line 20 of file AlignedDetector.hpp
using AlignedDetector::DetectorElement = ActsExamples::Contextual::AlignedDetectorElement
Definition at line 18 of file AlignedDetector.hpp.
View newest version in sPHENIX GitHub at line 18 of file AlignedDetector.hpp
using AlignedDetector::DetectorElementPtr = std::shared_ptr<DetectorElement>
Definition at line 19 of file AlignedDetector.hpp.
View newest version in sPHENIX GitHub at line 19 of file AlignedDetector.hpp
using AlignedDetector::DetectorStore = std::vector<std::vector<DetectorElementPtr>>
Definition at line 21 of file AlignedDetector.hpp.
View newest version in sPHENIX GitHub at line 21 of file AlignedDetector.hpp
Member Function Documentation
void AlignedDetector::addOptions (boost::program_options::options_description & opt) const override virtual
Implements ActsExamples::IBaseDetector.
Definition at line 25 of file AlignedDetector.cpp.
View newest version in sPHENIX GitHub at line 25 of file AlignedDetector.cpp
References ActsExamples::Options::addBFieldOptions(), and ActsExamples::Options::addGenericGeometryOptions().
auto AlignedDetector::finalize (const boost::program_options::variables_map & vm, std::shared_ptr< const Acts::IMaterialDecorator > mdecorator) override virtual
return the generic detector - with aligned context decorator
Implements ActsExamples::IBaseDetector.
Definition at line 62 of file AlignedDetector.cpp.
View newest version in sPHENIX GitHub at line 62 of file AlignedDetector.cpp
References ActsExamples::Contextual::AlignmentDecorator::Config::detectorStore, Acts::getDefaultLogger(), testing::internal::move(), ActsExamples::BField::BFieldScalor::Config::scalor, ActsExamples::RandomNumbers::Config::seed, and Acts::UnitConstants::um.
Member Data Documentation
DetectorStore AlignedDetector::detectorStore
The Store of the detector elements (lifetime: job)
Definition at line 24 of file AlignedDetector.hpp.
View newest version in sPHENIX GitHub at line 24 of file AlignedDetector.hpp
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Examples/Detectors/ContextualDetector/include/ActsExamples/ContextualDetector/AlignedDetector.hpp
acts/blob/sPHENIX/Examples/Detectors/ContextualDetector/src/AlignedDetector.cpp