Analysis Software: ActsTests::PropagationDatasets Namespace Reference
ActsTests::PropagationDatasets Namespace Reference
Variables
const auto phi = bdata::xrange(-180_degree, 181_degree, 45_degree)
const auto phiWithoutAmbiguity
const auto thetaCentral = bdata::make({45_degree, 90_degree, 135_degree})
const auto thetaForwardBackward
const auto thetaBeam = bdata::make({0_degree, 180_degree})
const auto thetaWithoutBeam = thetaCentral + thetaForwardBackward
const auto theta = thetaCentral + thetaForwardBackward + thetaBeam
const auto absMomentum = bdata::make({0.5_GeV, 1_GeV, 10_GeV, 100_GeV})
const auto chargeNonZero = bdata::make({1_e, -1_e})
const auto propagationFraction = bdata::make({0.125, 0.2, 0.4})
const auto pathLength = bdata::make({1_cm, 10_cm})
const auto magneticField = bdata::make({0.5_T, 2_T, 4_T})
Variable Documentation
const auto ActsTests::PropagationDatasets::absMomentum = bdata::make({0.5_GeV, 1_GeV, 10_GeV, 100_GeV})
Definition at line 38 of file PropagationDatasets.hpp.
View newest version in sPHENIX GitHub at line 38 of file PropagationDatasets.hpp
Referenced by ActsFatras::Particle::setAbsoluteMomentum().
const auto ActsTests::PropagationDatasets::chargeNonZero = bdata::make({1_e, -1_e})
Definition at line 39 of file PropagationDatasets.hpp.
View newest version in sPHENIX GitHub at line 39 of file PropagationDatasets.hpp
const auto ActsTests::PropagationDatasets::magneticField = bdata::make({0.5_T, 2_T, 4_T})
Definition at line 48 of file PropagationDatasets.hpp.
View newest version in sPHENIX GitHub at line 48 of file PropagationDatasets.hpp
Referenced by Acts::Python::addExampleAlgorithms(), Acts::Python::addExaTrkXTrackFinding(), Acts::Python::addTrackFinding(), Acts::Python::addTrackFitting(), main(), PYBIND11_MODULE(), runDetectorAlignment(), runDigitizationExample(), ActsExamples::runGeant4Simulation(), runHoughExample(), runMeasurementsToSP(), runRecCKFTracks(), runRecTruthTracks(), and runSeedingExample().
const auto ActsTests::PropagationDatasets::pathLength = bdata::make({1_cm, 10_cm})
Definition at line 45 of file PropagationDatasets.hpp.
View newest version in sPHENIX GitHub at line 45 of file PropagationDatasets.hpp
Referenced by Acts::CombinatorialKalmanFilter< propagator_t, traj_t >::Actor< source_link_accessor_t, parameters_t >::addNonSourcelinkState(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::CombinatorialKalmanFilter< propagator_t, traj_t >::Actor< source_link_accessor_t, parameters_t >::createSourceLinkTrackStates(), KshortReconstruction::fillNtp(), Acts::detail::kalmanHandleMeasurement(), Acts::detail::kalmanHandleNoMeasurement(), Acts::Experimental::Gx2Fitter< propagator_t, traj_t >::Actor< parameters_t >::operator()(), plot_kshort(), PHTpcResiduals::processTrack(), Acts::KalmanFitter< propagator_t, traj_t >::Actor< parameters_t >::reversedFilter(), runForwardBackwardTest(), runForwardComparisonTest(), runToSurfaceComparisonTest(), runToSurfaceTest(), PHG4HitEval::set_path_length(), test_combined_bound_state_function(), test_combined_curvilinear_state_function(), and transportFreely().
const auto ActsTests::PropagationDatasets::phi = bdata::xrange(-180_degree, 181_degree, 45_degree)
Definition at line 24 of file PropagationDatasets.hpp.
View newest version in sPHENIX GitHub at line 24 of file PropagationDatasets.hpp
Referenced by accessStepWise(), eic_bnl_rich::acq(), AddFlowToParent(), ActsExamples::HoughTransformSeeder::addMeasurements(), Acts::SingleSeedVertexFinder< spacepoint_t >::SortedSpacepoints::addSP(), ActsExamples::HoughTransformSeeder::addSpacePoints(), PHG4TpcDirectLaser::AimToPatternStep(), PHG4TpcDirectLaser::AimToPatternStep_File(), AnnularFieldSim::analyticFieldIntegral(), myAnalysis::analyze(), STrackCutStudy::Analyze(), AnalyzeResiduals(), AnnularFieldSim::AnnularFieldSim(), Acts::CylinderSurface::binningPosition(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), Acts::IntegrationTest::BOOST_DATA_TEST_CASE(), ActsFatras::BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_FIXTURE_TEST_CASE(), PHTruthSiliconAssociation::buildTrackSeed(), PHTruthTrackSeeding::buildTrackSeed(), BJetModule::calc3DDCA(), ActsTransformations::calculateDCA(), KshortReconstruction::calculateDca(), IsolatedTrackAnalysis::calculateDCA(), CalculateSigmaDca(), cemcReco::calculateTSP(), InttVertexFinder::calculateZvertex(), genfit::DAF::calcWeights(), ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::centralProtoLayers(), PHG4TpcPadPlaneReadout::check_phi(), Acts::LayerCreator::checkBinning(), CheckDeltaPtWithBoundaryMasks(), CMDistortionAnalysis(), CMDistortionAnalysisCart(), CMDistortionAnalysisPhiR(), CMDistortionReco(), CMDistortionRecoCart(), CMDistortionRecoPhiR(), PHG4EtaPhiParameterization::ComputeDimensions(), FieldMapsLaplace::ComputeE(), ConstructGeometry(), PHG4Prototype3InnerHcalDetector::ConstructInnerHcal(), PHG4Prototype2InnerHcalDetector::ConstructInnerHcal(), PHG4InnerHcalDetector::ConstructInnerHcal(), PHG4InttDetector::ConstructIntt(), PHG4PSTOFDetector::ConstructMe(), PHG4CEmcTestBeamDetector::ConstructMe(), PHG4HcalDetector::ConstructMe(), PHG4MvtxSupport::ConstructMvtxSupport(), PHG4Prototype2OuterHcalDetector::ConstructOuterHcal(), PHG4OuterHcalDetector::ConstructOuterHcal(), PHG4CEmcTestBeamDetector::ConstructTowerVolume(), ActsFatras::NuclearInteraction::convertParametersToParticles(), TreeMaker::CopyAndMakeClusters(), BEmcRecCEMC::CorrectShowerDepth(), create_pythia_dummy(), Acts::EventDataView3D::createEllipse(), Acts::SurfaceArrayCreator::createEquidistantAxis(), ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::createProtoLayers(), Acts::detail::VerticesHelper::createSegment(), Acts::SurfaceArrayCreator::createVariableAxis(), Acts::Experimental::detail::SupportHelper::cylindricalSupport(), PseudoJet::delta_phi_to(), PHActsTrackProjection::deltaPhi(), Acts::TGeoSurfaceConverter::discComponents(), Acts::Experimental::detail::SupportHelper::discSupport(), EMCalLikelihood::do_ganging(), ColoredHadronization::DoHadronization(), DrawEcal_BlockCalibration(), Acts::GeometryView3D::drawSurfaceArray(), dvcs_plot(), EMCalTowerRingStudy(), Acts::estimateTrackParamsFromSeed(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), PGun::Exec(), ActsExamples::VolumeAssociationTest::execute(), ActsExamples::ParticleSmearing::execute(), ActsExamples::ParticleSelector::execute(), ActsExamples::TruthSeedSelector::execute(), ActsExamples::PropagationAlgorithm::execute(), ExploreTTrees(), TpcSpaceChargeReconstructionHelper::extrapolate_phi2(), AnnularFieldSim::fieldIntegral(), ActsExamples::EffPlotTool::fill(), ActsExamples::DuplicationPlotTool::fill(), ActsExamples::FakeRatePlotTool::fill(), ActsExamples::ResPlotTool::fill(), ActsAlignmentStates::fillAlignmentStateMap(), TrackResiduals::fillHitTree(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), TrkrNtuplizer::fillOutputNtuples(), CaloEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), AnnularFieldSim::FilterPhiIndex(), AnnularFieldSim::FilterPhiPos(), CylinderGeomIntt::find_indices_from_segment_center(), CylinderGeomIntt::find_indices_from_world_location(), find_matching_jet(), PHG4TpcCylinderGeom::find_phibin(), PHG4CylinderGeomv4::find_segment_center(), PHG4CylinderGeomv4::find_strip_center(), CylinderGeomIntt::find_strip_center(), CylinderGeomMicromegas::find_tile_cylindrical(), ElectronID::findMCmatch(), LeptoquarksReco::FindMinDeltaRCandidate(), ICGlauber::findRPhi(), Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::fit(), fjetResol(), fullMaterial(), Acts::Test::SurfaceArrayCreatorFixture::fullPhiTestSurfacesBRL(), Acts::Test::SurfaceArrayCreatorFixture::fullPhiTestSurfacesEC(), Fun4All_G4_TPC(), Acts::Test::generateBoundParametersCovariance(), Acts::TrigFTF_GNN_EtaBin< external_spacepoint_t >::generatePhiIndexing(), GenHadron::GenHadron(), TpcDistortionCorrection::get_corrected_position(), TrackAnalysisUtils::get_dca(), SecondaryVertexFinder::get_dca(), HelicalFitter::get_dca(), FilterEvents::get_dca_SvtxEval(), TimingNtuple::get_dtotal(), SigmaTimingNtuple::get_dtotal(), PHG4Utils::get_etaphi(), TowerJetInput::get_input(), PHG4TpcCylinderGeom::get_pad_float(), TrackSeed_v1::get_phi(), PHG4TpcCylinderGeom::get_phi(), PHG4CylinderCellGeom::get_phibin(), PHG4TpcCylinderGeom::get_phibin(), PHG4TpcCylinderGeom::get_phibin_new(), SvtxTrackState_v1::get_rphi_error(), SvtxTrackState_v2::get_rphi_error(), CylinderGeom_Mvtx::get_sensor_indices_from_world_coords(), getBinPosition(), TrackProjectionTools::getCluster(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getDistanceAndMomentum(), PHG4MvtxSupport::GetEndWheelSideN(), PHG4MvtxSupport::GetEndWheelSideS(), PHField3DCylindrical::GetFieldCyl(), PHField2D::GetFieldValue(), PHField3DCylindrical::GetFieldValue(), PHG4HcalDetector::GetLength(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getLifetimeSignOfTrack(), Martini::getNewMomentumElas(), DVMPHelper::GetParticleReco(), DVMPHelper::GetParticleTruth(), quickHIJING::getPhi(), ABlob::GetPHI(), hijbkg_upc::getPhi(), cemcReco::getPhi(), BEmcRec::GetProb(), PHG4TpcCentralMembrane::getSearchResult(), Acts::SingleSeedVertexFinder< spacepoint_t >::SortedSpacepoints::getSP(), PHG4TpcCentralMembrane::getStripeID(), Martini::getThermalVec(), PHTruthClustering::getTpcSector(), HelicalFitter::getVertexResidual(), ActsFatras::NuclearInteraction::globalAngle(), Acts::CylinderSurface::globalToLocal(), HelicalFitter::globalvtxToLocalvtx(), HybridHadronization::gluon_decay(), Hit::Hit(), STrackCutStudy::InitTuples(), Acts::EllipseBounds::inside(), Acts::ConeVolumeBounds::inside(), Acts::CylinderVolumeBounds::inside(), Acts::CylinderBounds::inside3D(), Acts::detail::IntersectionHelper2D::intersectCircleSegment(), Conversion::InTwoPi(), Jet_reso(), Jet_reso_Iso(), LBT::jetInitialize(), RandomConeAna::jets_to_pseudojets(), PseudoJet::kt_distance(), likelihood(), AnnularFieldSim::load3dBfield(), AnnularFieldSim::load_and_resample_spacecharge(), Jetscape::PartonShower::load_edge_info_handler(), Acts::ConeSurface::localCartesianToBoundLocalDerivative(), Acts::CylinderSurface::localCartesianToBoundLocalDerivative(), Acts::ConeSurface::localToGlobal(), Acts::CylinderSurface::localToGlobal(), MakeMilleFiles::localToGlobalVertex(), HelicalFitter::localvtxToGlobalvtx(), CaloCalibEmc_Pi0::Loop(), CaloCalibEmc_Pi0::Loop_for_eta_slices(), PHActsTrkFitter::loopTracks(), main(), Acts::Test::SurfaceArrayCreatorFixture::makeBarrelStagger(), Acts::Test::makeParameters(), Acts::makePhiThetaFromDirection(), PHGenFitTrkFitter::MakeSvtxTrack(), PHG4TpcPadPlaneReadout::MapToPadPlane(), ActsExamples::Generic::modulePositionsRing(), NoiseSimulator(), Acts::ConeSurface::normal(), Acts::CylinderSurface::normal(), PHActsSiliconSeeding::normPhi2Pi(), Acts::ObjectSorterT< Vector3 >::operator()(), Fatras::Scattering< formula_t >::operator()(), ActsExamples::ParametricParticleGenerator::operator()(), ActsFatras::DiscRandom::operator()(), Acts::DistanceSorterT< T >::operator()(), ActsFatras::AnnulusRandom::operator()(), PHHepMCGenHelper::pair2Hep3Vector(), PHG4GDMLWriteParamvol::Para_dimensionsWrite(), PHG4GDMLWriteSolids::ParaWrite(), Acts::ConeSurface::pathCorrection(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::performNewtonOptimization(), PHField3DCylindrical::PHField3DCylindrical(), phi_in_range(), JetAnalyzer::phimod2pi(), PseudoJet::plain_distance(), plot_matscan(), plot_matscan_tdr(), PHG4TpcPadPlaneReadout::populate_zigzag_phibins(), TpcPrototypeGenFitTrkFitter::pos_cov_uvn_to_rz(), PHGenFitTrkFitter::pos_cov_XYZ_to_RZ(), TpcPrototypeGenFitTrkFitter::pos_cov_XYZ_to_RZ(), BEmcRec::PredictEnergyProb(), CaloEvaluator::printOutputInfo(), PHG4ParticleGenerator::process_event(), PHG4ParticleGeneratorD0::process_event(), JetProbeMaker::process_event(), TrackingPerformanceCheck::process_event(), SepdMon::process_event(), RecoInfoExport::process_event(), TpcMon::process_event(), TrackSeedTrackMapConverter::process_event(), EventPlaneReco::process_event(), RawTowerCalibration::process_event(), PHG4CylinderCellReco::process_event(), PHG4SimpleEventGenerator::process_event(), G4SnglNtuple::process_event(), G4CellNtuple::process_event(), G4SnglTree::process_event(), PHG4ParticleGeneratorVectorMeson::process_event(), G4TowerNtuple::process_event(), Quarkonia2LeptonsMC::process_event(), RawTowerDigitizer::process_event(), ShowerSize::process_event(), SubtractTowers::process_event(), SubtractTowersCS::process_event(), TpcCombinedRawDataUnpacker::process_event(), TowerTiming::process_event(), RetowerCEMC::process_event(), DetermineTowerBackground::process_event(), DirectPhotonPythia::process_event(), TPCRawDataTree::process_event(), TpcRawDataTree::process_event(), HijingShowerSize::process_event(), PJTranslator::process_event(), PHGenFitTrackProjection::process_event(), PHMicromegasTpcTrackMatching::process_event(), tpc_hits::process_event(), singlePhotonClusterAna::process_event(), pi0ClusterAna::process_event(), caloTreeGen::process_event(), TpcRawDataDecoder::process_event(), pythiaEMCalAna::process_event(), ElectronID::process_event(), fillSpaceChargeMaps::process_event(), AnaMvtxTelescopeHits::process_event(), PHTpcCentralMembraneClusterizer::process_event(), HelicalFitter::process_event(), MyJetAnalysis::process_event(), RawTowerCombiner::process_event(), sPHAnalysis::process_event_hepmc(), CaloWaveFormSim::process_g4hits(), TpcDirectLaserReconstruction::process_track(), PHSimpleKFProp::PropagateTrack(), pwithpF(), ActsFatras::PlanarSurfaceMask::radialMask(), RandomHit(), VtxRegressor::regress(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::JetInfo::Reset(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::FlowInfo::Reset(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ClustInfo::Reset(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::Reset(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::Reset(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::CstInfo::Rest(), EpFinder::Results(), PHFlowJetMaker::run_particle_flow(), trento::Deuteron::sample_nucleons_impl(), trento::DeformedWoodsSaxonNucleus::sample_nucleons_impl(), AnnularFieldSim::save_spacecharge(), ActsFatras::Channelizer::segments(), CaloTriggerInfov1::set_best2_EMCal_4x4_phi(), CaloTriggerInfov1::set_best_EMCal_2x2_phi(), CaloTriggerInfov1::set_best_EMCal_4x4_phi(), CaloTriggerInfov1::set_best_FullCalo_0p2x0p2_phi(), CaloTriggerInfov1::set_best_FullCalo_0p4x0p4_phi(), CaloTriggerInfov1::set_best_FullCalo_0p6x0p6_phi(), CaloTriggerInfov1::set_best_FullCalo_0p8x0p8_phi(), CaloTriggerInfov1::set_best_FullCalo_1p0x1p0_phi(), RawClusterv1::set_phi(), PHG4CylinderGeomv3::set_phi_slat_zero(), PHG4CylinderGeomv3::set_tiltangle(), PHG4TpcDirectLaser::SetArbitraryThetaPhi(), EcoMug::SetCylinderMaxPositionPhi(), EcoMug::SetCylinderMinPositionPhi(), Proto3ShowerCalib::Eval_Cluster::setfmods(), EcoMug::SetHSphereMaxPositionPhi(), EcoMug::SetHSphereMinPositionPhi(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::JetInfo::SetInfo(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::CstInfo::SetInfo(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::FlowInfo::SetInfo(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ClustInfo::SetInfo(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::SetInfo(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::SetInfo(), EcoMug::SetMaximumPhi(), EcoMug::SetMinimumPhi(), CMFlashDifferencev1::setRecoPhi(), CMFlashDifferencev1::setTruthPhi(), PHG4MicromegasDetector::setup_tiles(), Shifter::ShiftForward(), Acts::SingleSeedVertexFinder< spacepoint_t >::sortSpacepoints(), Acts::TGeoCylinderDiscSplitter::split(), AnnularFieldSim::sum_local_field_at(), Acts::SurfaceArrayCreator::surfaceArrayOnCylinder(), Acts::SurfaceArrayCreator::surfaceArrayOnDisc(), Acts::Test::CylindricalTrackingGeometry::surfacesRing(), TEST_CASE(), test_surface(), TPC_RawHit::TPC_RawHit(), TPCEventDisplay_Updated(), TPCEventDisplay_Updated_BCO(), track_calorimeter_matching(), TrackCaloDist(), Acts::detail::transformFreeToBoundParameters(), Acts::detail::transformFreeToCurvilinearParameters(), PHG4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteSolids::TrapWrite(), PHActsVertexFinder::updateTrackDCA(), TreeMaker::UseFastJet(), Acts::BinningData::value(), Acts::AnnulusBounds::vertices(), ActsEvaluator::visitTrackStates(), VtxRegressor::VtxRegressor(), ActsExamples::RootTrackParameterWriter::writeT(), ActsExamples::RootTrajectorySummaryWriter::writeT(), ActsExamples::RootTrajectoryStatesWriter::writeT(), ActsExamples::RootMaterialTrackWriter::writeT(), XYtoPhi(), XYtoPhi_02PI(), and ActsExamples::HoughTransformSeeder::yToX().
const auto ActsTests::PropagationDatasets::phiWithoutAmbiguity
Initial value:
=
    bdata::xrange(-135_degree, 136_degree, 45_degree)
Definition at line 26 of file PropagationDatasets.hpp.
View newest version in sPHENIX GitHub at line 26 of file PropagationDatasets.hpp
const auto ActsTests::PropagationDatasets::propagationFraction = bdata::make({0.125, 0.2, 0.4})
Definition at line 42 of file PropagationDatasets.hpp.
View newest version in sPHENIX GitHub at line 42 of file PropagationDatasets.hpp
const auto ActsTests::PropagationDatasets::theta = thetaCentral + thetaForwardBackward + thetaBeam
Definition at line 35 of file PropagationDatasets.hpp.
View newest version in sPHENIX GitHub at line 35 of file PropagationDatasets.hpp
Referenced by accessStepWise(), eic_bnl_rich::acq(), PHG4TpcDirectLaser::AimToPatternStep(), PHG4TpcDirectLaser::AimToPatternStep_File(), ana_starlight(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), ActsFatras::BetheHeitler::bremPhoton(), Acts::SpacePointBuilder< spacepoint_t >::buildSpacePoint(), PHTruthSiliconAssociation::buildTrackSeed(), PHTruthTrackSeeding::buildTrackSeed(), PHTpcCentralMembraneMatcher::CalculateCenters(), IsolatedTrackAnalysis::calculateProjectionEta(), PHG4TpcCentralMembrane::CalculateVertices(), FluidcellStatistic::compute_local_expansion_rate(), PHG4HcalPrototypeDetector::ConstructDetector(), ConstructGeometry(), PHG4InnerHcalDetector::ConstructHcalSingleScintillators(), PHG4OuterHcalDetector::ConstructHcalSingleScintillators(), PHG4PSTOFDetector::ConstructMe(), ActsFatras::NuclearInteraction::convertParametersToParticles(), Acts::EventDataView3D::decomposeCovariance(), Acts::EventDataView3D::drawCovarianceAngular(), Acts::EventDataView3D::drawCovarianceCartesian(), dvcs_plot(), Efficiency_ModuleDisplay(), eta2theta(), ActsExamples::TrackParameterSelector::execute(), ActsExamples::ParticleSmearing::execute(), ActsExamples::PropagationAlgorithm::execute(), ActsExamples::ResPlotTool::fill(), ActsAlignmentStates::fillAlignmentStateMap(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::fit(), fullMaterial(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_TPC(), Acts::Test::generateBoundParametersCovariance(), ActsFatras::PhotonConversion::generateChildDirection(), TimingNtuple::get_dtotal(), SigmaTimingNtuple::get_dtotal(), PHG4Utils::get_eta(), PHG4InputFilter::get_eta(), RawTowerGeomv1::get_eta(), RawTowerGeomv4::get_eta(), RawTowerGeomv2::get_eta(), RawTowerGeomv3::get_eta(), PHG4Utils::get_etaphi(), DVMPHelper::get_pt(), PHG4Utils::get_theta(), TrackSeed_v1::get_theta(), RawTowerGeomv1::get_theta(), RawTowerGeomv4::get_theta(), RawTowerGeomv3::get_theta(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getDistanceAndMomentum(), getEta(), PHG4Utils::GetLengthForRapidityCoverage(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getLifetimeSignOfTrack(), BEmcRec::GetProb(), ClusterIso::getTowerEta(), ActsFatras::NuclearInteraction::globalAngle(), HybridHadronization::gluon_decay(), DISKinematicsReco::InsertCandidateFromCluster(), Acts::TrackSelector::isValidTrack(), main(), PHActsTrackProjection::makeCaloSurfacePtrs(), Acts::Test::makeParameters(), Acts::makePhiThetaFromDirection(), momentumDistributions(), Noise_ModuleDisplay(), Acts::detail::normalizePhiTheta(), Fatras::GeneralMixture::operator()(), ActsFatras::detail::GeneralMixture::operator()(), ActsFatras::detail::ScatteringImpl< scattering_model_t >::operator()(), Fatras::Scattering< formula_t >::operator()(), ActsExamples::ParametricParticleGenerator::operator()(), PtResidualAccessor::operator()(), FluidcellStatistic::output_flowvelocity_vs_tau(), FluidcellStatistic::outputKnudersonNumberasTauvsX(), PHHepMCGenHelper::pair2Hep3Vector(), PHG4GDMLWriteParamvol::Para_dimensionsWrite(), PHG4GDMLWriteSolids::ParaWrite(), plot_matscan(), plot_matscan_tdr(), BEmcRec::PredictEnergyProb(), printHits(), PHSiliconTruthTrackSeeding::Process(), TpcMon::process_event(), G4SnglTree::process_event(), G4SnglNtuple::process_event(), PHG4SimpleEventGenerator::process_event(), ShowerSize::process_event(), HijingShowerSize::process_event(), BDiJetModule::process_event(), CaloWaveFormSim::process_g4hits(), KshortReconstruction::projectTrackToCylinder(), PseudoJet::pseudorapidity(), PHG4TpcDirectLaser::SetArbitraryThetaPhi(), EcoMug::SetHSphereMaxPositionTheta(), EcoMug::SetHSphereMinPositionTheta(), EcoMug::SetMaximumTheta(), EcoMug::SetMinimumTheta(), test_surface(), Acts::detail::transformFreeToBoundParameters(), Acts::detail::transformFreeToCurvilinearParameters(), PHG4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteSolids::TrapWrite(), Acts::SingleSeedVertexFinder< spacepoint_t >::tripletValidationAndUpdate(), ActsEvaluator::visitTrackStates(), ActsExamples::RootTrackParameterWriter::writeT(), ActsExamples::RootTrajectorySummaryWriter::writeT(), and ActsExamples::RootTrajectoryStatesWriter::writeT().
const auto ActsTests::PropagationDatasets::thetaBeam = bdata::make({0_degree, 180_degree})
Definition at line 33 of file PropagationDatasets.hpp.
View newest version in sPHENIX GitHub at line 33 of file PropagationDatasets.hpp
const auto ActsTests::PropagationDatasets::thetaCentral = bdata::make({45_degree, 90_degree, 135_degree})
Definition at line 29 of file PropagationDatasets.hpp.
View newest version in sPHENIX GitHub at line 29 of file PropagationDatasets.hpp
const auto ActsTests::PropagationDatasets::thetaForwardBackward
Initial value:
= bdata::make(
    {2_degree, 10_degree, 30_degree, 150_degree, 170_degree, 178_degree})
Definition at line 31 of file PropagationDatasets.hpp.
View newest version in sPHENIX GitHub at line 31 of file PropagationDatasets.hpp
const auto ActsTests::PropagationDatasets::thetaWithoutBeam = thetaCentral + thetaForwardBackward
Definition at line 34 of file PropagationDatasets.hpp.
View newest version in sPHENIX GitHub at line 34 of file PropagationDatasets.hpp