Analysis Software: Jetscape::JetScapeTaskSupport Class Reference
Jetscape::JetScapeTaskSupport Class Reference
#include <JETSCAPE/blob/main/src/framework/JetScapeTaskSupport.h>
Public Member Functions
int RegisterTask ()
shared_ptr< std::mt19937 > GetMt19937Generator (int TaskId)
Static Public Member Functions
static JetScapeTaskSupport * Instance ()
static void ReadSeedFromXML ()
Initialize random engine functionality from the XML file.
static unsigned int GetRandomSeed ()
Static Protected Attributes
static bool one_generator_per_task_ = false
Private Member Functions
JetScapeTaskSupport ()
Private Attributes
atomic_int CurrentTaskNumber
Static Private Attributes
static JetScapeTaskSupport * m_pInstance = nullptr
static unsigned int random_seed_ = 0
static bool initialized_ = false
static shared_ptr< std::mt19937 > one_for_all_ = nullptr
Detailed Description
Definition at line 52 of file JetScapeTaskSupport.h.
View newest version in sPHENIX GitHub at line 52 of file JetScapeTaskSupport.h
Constructor & Destructor Documentation
Jetscape::JetScapeTaskSupport::JetScapeTaskSupport () inline private
Definition at line 82 of file JetScapeTaskSupport.h.
View newest version in sPHENIX GitHub at line 82 of file JetScapeTaskSupport.h
Member Function Documentation
shared_ptr< std::mt19937 > Jetscape::JetScapeTaskSupport::GetMt19937Generator (int TaskId)
Return a handle to a mersenne twister Usually this should be just one shared by everybody but if reproducible seeds are requested, every task gets their own
Definition at line 90 of file JetScapeTaskSupport.cc.
View newest version in sPHENIX GitHub at line 90 of file JetScapeTaskSupport.cc
References JSDEBUG, and JSWARN.
Referenced by Jetscape::JetScapeModuleBase::GetMt19937Generator().
static unsigned int Jetscape::JetScapeTaskSupport::GetRandomSeed () inline static
Definition at line 76 of file JetScapeTaskSupport.h.
View newest version in sPHENIX GitHub at line 76 of file JetScapeTaskSupport.h
JetScapeTaskSupport * Jetscape::JetScapeTaskSupport::Instance () static
Definition at line 32 of file JetScapeTaskSupport.cc.
View newest version in sPHENIX GitHub at line 32 of file JetScapeTaskSupport.cc
References VERBOSE.
Referenced by Jetscape::JetScapeModuleBase::GetMt19937Generator().
void Jetscape::JetScapeTaskSupport::ReadSeedFromXML () static
Initialize random engine functionality from the XML file.
Definition at line 49 of file JetScapeTaskSupport.cc.
View newest version in sPHENIX GitHub at line 49 of file JetScapeTaskSupport.cc
References tinyxml2::XMLNode::FirstChildElement(), JSINFO, JSWARN, tinyxml2::XMLElement::QueryUnsignedText(), and VERBOSE.
Referenced by Jetscape::JetScape::ReadGeneralParametersFromXML().
int Jetscape::JetScapeTaskSupport::RegisterTask ()
Tasks should call this method at creation and remember the answer as their task id This could co a lot more, like keep a map of numbers to task.id (essentially the name of the task) But for now keep it simple
Definition at line 41 of file JetScapeTaskSupport.cc.
View newest version in sPHENIX GitHub at line 41 of file JetScapeTaskSupport.cc
References VERBOSE.
Member Data Documentation
atomic_int Jetscape::JetScapeTaskSupport::CurrentTaskNumber private
Definition at line 86 of file JetScapeTaskSupport.h.
View newest version in sPHENIX GitHub at line 86 of file JetScapeTaskSupport.h
bool Jetscape::JetScapeTaskSupport::initialized_ = false static private
Definition at line 88 of file JetScapeTaskSupport.h.
View newest version in sPHENIX GitHub at line 88 of file JetScapeTaskSupport.h
JetScapeTaskSupport * Jetscape::JetScapeTaskSupport::m_pInstance = nullptr static private
Definition at line 82 of file JetScapeTaskSupport.h.
View newest version in sPHENIX GitHub at line 82 of file JetScapeTaskSupport.h
shared_ptr< std::mt19937 > Jetscape::JetScapeTaskSupport::one_for_all_ = nullptr static private
Definition at line 90 of file JetScapeTaskSupport.h.
View newest version in sPHENIX GitHub at line 90 of file JetScapeTaskSupport.h
bool Jetscape::JetScapeTaskSupport::one_generator_per_task_ = false static protected
Definition at line 76 of file JetScapeTaskSupport.h.
View newest version in sPHENIX GitHub at line 76 of file JetScapeTaskSupport.h
unsigned int Jetscape::JetScapeTaskSupport::random_seed_ = 0 static private
Definition at line 87 of file JetScapeTaskSupport.h.
View newest version in sPHENIX GitHub at line 87 of file JetScapeTaskSupport.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/JetScapeTaskSupport.h
JETSCAPE/blob/main/src/framework/JetScapeTaskSupport.cc