Analysis Software: PHG4DstCompressReco Class Reference
PHG4DstCompressReco Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/PHG4DstCompressReco.h>
Public Member Functions
PHG4DstCompressReco (const std::string &name="PHG4DstCompressReco")
~PHG4DstCompressReco () override
int InitRun (PHCompositeNode *topNode) override
run initialization
int process_event (PHCompositeNode *topNode) override
event processing
void AddHitContainer (const std::string &name)
void AddCellContainer (const std::string &name)
void AddTowerContainer (const std::string &name)
void KeepRecoTrackMatchedParticles (bool b=true)
whether to compress tracker hits based on truth association table produced by PHG4DstCompressReco
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void SearchG4HitNodes (PHCompositeNode *topNode)
Private Attributes
bool m_keepRecoTrackMatchedParticles = false
PHG4TruthInfoContainer * _truth_info = nullptr
PHG4ParticleSvtxMap * _truthRecoMap = nullptr
SvtxPHG4ParticleMap * _recoTruthMap = nullptr
std::set< std::string > _compress_g4hit_names
std::set< std::string > _compress_g4cell_names
std::set< std::string > _compress_tower_names
std::set< PHG4CellContainer * > _g4cells
std::set< PHG4HitContainer * > _g4hits
std::set< PHG4HitContainer * > _keep_g4hits
std::set< RawTowerContainer * > _towers
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 19 of file PHG4DstCompressReco.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4DstCompressReco.h
Constructor & Destructor Documentation
PHG4DstCompressReco::PHG4DstCompressReco (const std::string & name = "PHG4DstCompressReco")
Definition at line 30 of file PHG4DstCompressReco.cc.
View newest version in sPHENIX GitHub at line 30 of file PHG4DstCompressReco.cc
PHG4DstCompressReco::~PHG4DstCompressReco () inline override
Definition at line 23 of file PHG4DstCompressReco.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4DstCompressReco.h
Member Function Documentation
void PHG4DstCompressReco::AddCellContainer (const std::string & name) inline
Definition at line 32 of file PHG4DstCompressReco.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4DstCompressReco.h
References _compress_g4cell_names.
Referenced by ShowerCompress().
void PHG4DstCompressReco::AddHitContainer (const std::string & name) inline
Definition at line 31 of file PHG4DstCompressReco.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4DstCompressReco.h
References _compress_g4hit_names.
Referenced by ShowerCompress().
void PHG4DstCompressReco::AddTowerContainer (const std::string & name) inline
Definition at line 33 of file PHG4DstCompressReco.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4DstCompressReco.h
References _compress_tower_names.
Referenced by ShowerCompress().
int PHG4DstCompressReco::InitRun (PHCompositeNode * topNode) override virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 35 of file PHG4DstCompressReco.cc.
View newest version in sPHENIX GitHub at line 35 of file PHG4DstCompressReco.cc
References _compress_g4cell_names, _compress_tower_names, _g4cells, _recoTruthMap, _towers, _truth_info, _truthRecoMap, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, m_keepRecoTrackMatchedParticles, perf_headwind::name, and SearchG4HitNodes().
void PHG4DstCompressReco::KeepRecoTrackMatchedParticles (bool b = true) inline
whether to compress tracker hits based on truth association table produced by PHG4DstCompressReco
Definition at line 35 of file PHG4DstCompressReco.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4DstCompressReco.h
References KFPMath::b, and m_keepRecoTrackMatchedParticles.
int PHG4DstCompressReco::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 88 of file PHG4DstCompressReco.cc.
View newest version in sPHENIX GitHub at line 88 of file PHG4DstCompressReco.cc
References _g4cells, _g4hits, _keep_g4hits, _recoTruthMap, _towers, _truth_info, _truthRecoMap, RawTower::clear_g4cells(), PHG4Shower::clear_g4hit_id(), PHG4Shower::clear_g4particle_id(), PHG4Shower::clear_g4vertex_id(), PHG4TruthInfoContainer::delete_particle(), PHG4TruthInfoContainer::delete_vtx(), Fun4AllReturnCodes::EVENT_OK, PHG4Hit::get_trkid(), PHG4Particle::get_vtx_id(), PHG4TruthInfoContainer::GetSecondaryParticleRange(), PHG4TruthInfoContainer::GetSecondaryVtxRange(), PHG4TruthInfoContainer::GetShowerRange(), and particle.
void PHG4DstCompressReco::SearchG4HitNodes (PHCompositeNode * topNode) private
Definition at line 218 of file PHG4DstCompressReco.cc.
View newest version in sPHENIX GitHub at line 218 of file PHG4DstCompressReco.cc
References _compress_g4hit_names, _g4hits, _keep_g4hits, PHDataNode< T >::getData(), and PHNodeIterator::ls().
Referenced by InitRun().
Member Data Documentation
std::set<std::string> PHG4DstCompressReco::_compress_g4cell_names private
Definition at line 48 of file PHG4DstCompressReco.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4DstCompressReco.h
Referenced by AddCellContainer(), and InitRun().
std::set<std::string> PHG4DstCompressReco::_compress_g4hit_names private
Definition at line 47 of file PHG4DstCompressReco.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4DstCompressReco.h
Referenced by AddHitContainer(), and SearchG4HitNodes().
std::set<std::string> PHG4DstCompressReco::_compress_tower_names private
Definition at line 49 of file PHG4DstCompressReco.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4DstCompressReco.h
Referenced by AddTowerContainer(), and InitRun().
std::set<PHG4CellContainer *> PHG4DstCompressReco::_g4cells private
Definition at line 51 of file PHG4DstCompressReco.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4DstCompressReco.h
Referenced by InitRun(), and process_event().
std::set<PHG4HitContainer *> PHG4DstCompressReco::_g4hits private
Definition at line 52 of file PHG4DstCompressReco.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4DstCompressReco.h
Referenced by process_event(), and SearchG4HitNodes().
std::set<PHG4HitContainer *> PHG4DstCompressReco::_keep_g4hits private
Definition at line 53 of file PHG4DstCompressReco.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4DstCompressReco.h
Referenced by process_event(), and SearchG4HitNodes().
SvtxPHG4ParticleMap* PHG4DstCompressReco::_recoTruthMap = nullptr private
Definition at line 46 of file PHG4DstCompressReco.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4DstCompressReco.h
Referenced by InitRun(), and process_event().
std::set<RawTowerContainer *> PHG4DstCompressReco::_towers private
Definition at line 55 of file PHG4DstCompressReco.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4DstCompressReco.h
Referenced by InitRun(), and process_event().
PHG4TruthInfoContainer* PHG4DstCompressReco::_truth_info = nullptr private
Definition at line 44 of file PHG4DstCompressReco.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4DstCompressReco.h
Referenced by InitRun(), and process_event().
PHG4ParticleSvtxMap* PHG4DstCompressReco::_truthRecoMap = nullptr private
Definition at line 45 of file PHG4DstCompressReco.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4DstCompressReco.h
Referenced by InitRun(), and process_event().
bool PHG4DstCompressReco::m_keepRecoTrackMatchedParticles = false private
whether to compress tracker hits based on truth association table produced by PHG4DstCompressReco default to false
Definition at line 42 of file PHG4DstCompressReco.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4DstCompressReco.h
Referenced by InitRun(), and KeepRecoTrackMatchedParticles().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/PHG4DstCompressReco.h
coresoftware/blob/master/simulation/g4simulation/g4eval/PHG4DstCompressReco.cc