Analysis Software: ActsExamples::JsonSurfacesReader Namespace Reference
ActsExamples::JsonSurfacesReader Namespace Reference
Classes
struct Options
Options specification for surface reading.
Functions
Acts::GeometryHierarchyMap
< std::shared_ptr
< Acts::Surface > > read (const Options &options)
Read the surfaces from the input file.
Function Documentation
Acts::GeometryHierarchyMap< std::shared_ptr< Acts::Surface > > ActsExamples::JsonSurfacesReader::read (const Options & options)
Read the surfaces from the input file.
Parameters
options specifies which file and what to read
Returns
a vector of surfaces
Definition at line 23 of file JsonSurfacesReader.cpp.
View newest version in sPHENIX GitHub at line 23 of file JsonSurfacesReader.cpp
References Acts::SurfaceJsonConverter::fromJson(), in, ActsExamples::JsonSurfacesReader::Options::inputFile, j, ActsExamples::JsonSurfacesReader::Options::jsonEntryPath, testing::internal::move(), and writeMapConfig::surface.
Referenced by Acts::Python::addJson(), BOOST_AUTO_TEST_CASE(), upload.MercurialVCS::GetBaseFile(), shower2::load_edge_info_handler(), Jetscape::PartonShower::load_edge_info_handler(), Jetscape::PartonShower::load_node_info_handler(), shower2::load_node_info_handler(), tinyxml2::XMLDocument::LoadFile(), main(), daq_device_file::put_data(), testing::internal::posix::Read(), oncsEventiterator::read_next_buffer(), fileEventiterator::read_next_buffer(), oamlBuffer::readn(), and readn().