Analysis Software: ActsAlignmentStates Class Reference
ActsAlignmentStates Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/ActsAlignmentStates.h>
Public Types
using Trajectory = ActsExamples::Trajectories
Public Member Functions
ActsAlignmentStates ()
~ActsAlignmentStates ()
void fillAlignmentStateMap (const ActsTrackFittingAlgorithm::TrackContainer &tracks, const std::vector< Acts::MultiTrajectoryTraits::IndexType > &tips, SvtxTrack *track, const ActsTrackFittingAlgorithm::MeasurementContainer &measurements)
void verbosity (const int verb)
void distortionContainers (TpcDistortionCorrectionContainer *stat, TpcDistortionCorrectionContainer *average, TpcDistortionCorrectionContainer *fluc)
void actsGeometry (ActsGeometry *geom)
void clusters (TrkrClusterContainer *clus)
void stateMap (SvtxAlignmentStateMap *map)
void fieldMap (std::string &fieldmap)
Private Member Functions
void makeTpcGlobalCorrections (TrkrDefs::cluskey cluster_key, short int crossing, Acts::Vector3 &global)
std::pair< Acts::Vector3,
Acts::Vector3 > get_projectionXY (const Acts::Surface &surface, const Acts::Vector3 &tangent)
SvtxAlignmentState::GlobalMatrix makeGlobalDerivatives (const Acts::Vector3 &OM, const std::pair< Acts::Vector3, Acts::Vector3 > &projxy)
Private Attributes
int m_verbosity = 0
float sensorAngles [3] = {0.1, 0.1, 0.2}
ClusterErrorPara m_clusErrPara
TpcDistortionCorrection m_distortionCorrection
TpcClusterZCrossingCorrection m_clusterCrossingCorrection
SvtxAlignmentStateMap * m_alignmentStateMap = nullptr
TrkrClusterContainer * m_clusterMap = nullptr
ActsGeometry * m_tGeometry = nullptr
TpcDistortionCorrectionContainer * m_dcc_static = nullptr
TpcDistortionCorrectionContainer * m_dcc_average = nullptr
TpcDistortionCorrectionContainer * m_dcc_fluctuation = nullptr
std::string m_fieldMap = ""
Detailed Description
Definition at line 30 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 30 of file ActsAlignmentStates.h
Member Typedef Documentation
using ActsAlignmentStates::Trajectory = ActsExamples::Trajectories
Definition at line 33 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 33 of file ActsAlignmentStates.h
Constructor & Destructor Documentation
ActsAlignmentStates::ActsAlignmentStates () inline
Definition at line 35 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 35 of file ActsAlignmentStates.h
ActsAlignmentStates::~ActsAlignmentStates () inline
Definition at line 36 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 36 of file ActsAlignmentStates.h
Member Function Documentation
void ActsAlignmentStates::actsGeometry (ActsGeometry * geom) inline
Definition at line 51 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 51 of file ActsAlignmentStates.h
References m_tGeometry.
Referenced by PHCosmicsTrkFitter::InitRun(), and PHActsTrkFitter::InitRun().
void ActsAlignmentStates::clusters (TrkrClusterContainer * clus) inline
Definition at line 52 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 52 of file ActsAlignmentStates.h
References m_clusterMap.
Referenced by PHCosmicsTrkFitter::InitRun(), and PHActsTrkFitter::InitRun().
void ActsAlignmentStates::distortionContainers (TpcDistortionCorrectionContainer * stat, TpcDistortionCorrectionContainer * average, TpcDistortionCorrectionContainer * fluc) inline
Definition at line 43 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 43 of file ActsAlignmentStates.h
References m_dcc_average, m_dcc_fluctuation, and m_dcc_static.
Referenced by PHCosmicsTrkFitter::InitRun(), and PHActsTrkFitter::InitRun().
void ActsAlignmentStates::fieldMap (std::string & fieldmap) inline
Definition at line 54 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 54 of file ActsAlignmentStates.h
References m_fieldMap.
Referenced by PHCosmicsTrkFitter::InitRun(), and PHActsTrkFitter::InitRun().
void ActsAlignmentStates::fillAlignmentStateMap (const ActsTrackFittingAlgorithm::TrackContainer & tracks, const std::vector< Acts::MultiTrajectoryTraits::IndexType > & tips, SvtxTrack * track, const ActsTrackFittingAlgorithm::MeasurementContainer & measurements)
make sure the track was fully fit through the mvtx
Collect only track states which were used in smoothing of KF and are measurements
get the local measurement that acts used
Local residual between measurement and smoothed Acts state
convert to acts units
The local bound parameters still have access to global phi/theta
opposite convention for coordinates in Acts
this is the derivative of the state wrt to Acts track parameters e.g. (d_0, z_0, phi, theta, q/p, t)
Definition at line 44 of file ActsAlignmentStates.cc.
View newest version in sPHENIX GitHub at line 44 of file ActsAlignmentStates.cc
References SvtxTrack::begin_states(), Acts::UnitConstants::cm, ActsPropagator::constField(), Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, Acts::eFreePos0, TrkrClusterContainer::findCluster(), ActsGeometry::geometry(), TrackSeed::get_crossing(), SvtxTrack::get_id(), get_projectionXY(), QAG4Util::get_r(), SvtxTrack::get_silicon_seed(), SvtxTrackState::get_x(), SvtxTrackState::get_y(), ActsTrackingGeometry::getGeoContext(), ActsGeometry::getGlobalPosition(), TrkrDefs::getTrkrId(), SvtxAlignmentStateMap::insertWithKey(), TrkrDefs::inttId, m_alignmentStateMap, m_clusterMap, m_fieldMap, m_tGeometry, m_verbosity, Acts::makeDirectionFromPhiTheta(), makeGlobalDerivatives(), makeTpcGlobalCorrections(), Acts::MeasurementFlag, TrkrDefs::mvtxId, next, OM(), ActsTests::PropagationDatasets::phi, ActsPropagator::setConstFieldValue(), filter::state, writeMapConfig::surface, ActsTests::PropagationDatasets::theta, TrkrDefs::tpcId, and Acts::detail::transformBoundToFreeParameters().
Referenced by PHCosmicsTrkFitter::getTrackFitResult(), and PHActsTrkFitter::getTrackFitResult().
std::pair< Acts::Vector3, Acts::Vector3 > ActsAlignmentStates::get_projectionXY (const Acts::Surface & surface, const Acts::Vector3 & tangent) private
Definition at line 250 of file ActsAlignmentStates.cc.
View newest version in sPHENIX GitHub at line 250 of file ActsAlignmentStates.cc
References Acts::Surface::center(), ActsGeometry::geometry(), ActsTrackingGeometry::getGeoContext(), m_tGeometry, m_verbosity, Acts::Surface::normal(), Acts::Surface::transform(), TauVsDIS_MachineLearning_Differentiation::X, TauVsDIS_MachineLearning_Differentiation::Y, and SVM_v1::Z.
Referenced by fillAlignmentStateMap().
SvtxAlignmentState::GlobalMatrix ActsAlignmentStates::makeGlobalDerivatives (const Acts::Vector3 & OM, const std::pair< Acts::Vector3, Acts::Vector3 > & projxy) private
x residual rotations
x residual translations
y residual rotations
y residual translations
Definition at line 223 of file ActsAlignmentStates.cc.
View newest version in sPHENIX GitHub at line 223 of file ActsAlignmentStates.cc
References Acts::VectorHelpers::cross().
Referenced by fillAlignmentStateMap().
void ActsAlignmentStates::makeTpcGlobalCorrections (TrkrDefs::cluskey cluster_key, short int crossing, Acts::Vector3 & global) private
Definition at line 278 of file ActsAlignmentStates.cc.
View newest version in sPHENIX GitHub at line 278 of file ActsAlignmentStates.cc
References TpcClusterZCrossingCorrection::correctZ(), TpcDistortionCorrection::get_corrected_position(), TpcDefs::getSide(), m_clusterCrossingCorrection, m_dcc_average, m_dcc_fluctuation, m_dcc_static, m_distortionCorrection, and physmon_track_finding_ttbar::z.
Referenced by fillAlignmentStateMap().
void ActsAlignmentStates::stateMap (SvtxAlignmentStateMap * map) inline
Definition at line 53 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 53 of file ActsAlignmentStates.h
References m_alignmentStateMap.
Referenced by PHCosmicsTrkFitter::InitRun(), and PHActsTrkFitter::InitRun().
void ActsAlignmentStates::verbosity (const int verb) inline
Definition at line 42 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 42 of file ActsAlignmentStates.h
References m_verbosity.
Referenced by PHCosmicsTrkFitter::InitRun(), and PHActsTrkFitter::InitRun().
Member Data Documentation
SvtxAlignmentStateMap* ActsAlignmentStates::m_alignmentStateMap = nullptr private
Definition at line 70 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 70 of file ActsAlignmentStates.h
Referenced by fillAlignmentStateMap(), and stateMap().
ClusterErrorPara ActsAlignmentStates::m_clusErrPara private
Definition at line 66 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 66 of file ActsAlignmentStates.h
TpcClusterZCrossingCorrection ActsAlignmentStates::m_clusterCrossingCorrection private
Definition at line 68 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 68 of file ActsAlignmentStates.h
Referenced by makeTpcGlobalCorrections().
TrkrClusterContainer* ActsAlignmentStates::m_clusterMap = nullptr private
Definition at line 71 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 71 of file ActsAlignmentStates.h
Referenced by clusters(), and fillAlignmentStateMap().
TpcDistortionCorrectionContainer* ActsAlignmentStates::m_dcc_average = nullptr private
Definition at line 74 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 74 of file ActsAlignmentStates.h
Referenced by distortionContainers(), and makeTpcGlobalCorrections().
TpcDistortionCorrectionContainer* ActsAlignmentStates::m_dcc_fluctuation = nullptr private
Definition at line 75 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 75 of file ActsAlignmentStates.h
Referenced by distortionContainers(), and makeTpcGlobalCorrections().
TpcDistortionCorrectionContainer* ActsAlignmentStates::m_dcc_static = nullptr private
Definition at line 73 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 73 of file ActsAlignmentStates.h
Referenced by distortionContainers(), and makeTpcGlobalCorrections().
TpcDistortionCorrection ActsAlignmentStates::m_distortionCorrection private
Definition at line 67 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 67 of file ActsAlignmentStates.h
Referenced by makeTpcGlobalCorrections().
std::string ActsAlignmentStates::m_fieldMap = "" private
Definition at line 76 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 76 of file ActsAlignmentStates.h
Referenced by fieldMap(), and fillAlignmentStateMap().
ActsGeometry* ActsAlignmentStates::m_tGeometry = nullptr private
Definition at line 72 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 72 of file ActsAlignmentStates.h
Referenced by actsGeometry(), fillAlignmentStateMap(), and get_projectionXY().
int ActsAlignmentStates::m_verbosity = 0 private
Definition at line 62 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 62 of file ActsAlignmentStates.h
Referenced by fillAlignmentStateMap(), get_projectionXY(), and verbosity().
float ActsAlignmentStates::sensorAngles[3] = {0.1, 0.1, 0.2} private
Definition at line 64 of file ActsAlignmentStates.h.
View newest version in sPHENIX GitHub at line 64 of file ActsAlignmentStates.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/ActsAlignmentStates.h
coresoftware/blob/master/offline/packages/trackreco/ActsAlignmentStates.cc