Analysis Software: PHG4StackingAction Class Reference
PHG4StackingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4StackingAction.h>
Public Member Functions
PHG4StackingAction (const std::string &name, const int i=0)
virtual ~PHG4StackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
stacking action. This gets called by the stacking action when a new track is generated
virtual void PrepareNewEvent ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual void SetInterfacePointers (PHCompositeNode *)
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
Private Attributes
int m_Verbosity = 0
std::string m_Name
Detailed Description
Definition at line 16 of file PHG4StackingAction.h.
View newest version in sPHENIX GitHub at line 16 of file PHG4StackingAction.h
Constructor & Destructor Documentation
PHG4StackingAction::PHG4StackingAction (const std::string & name, const int i = 0)
Definition at line 5 of file PHG4StackingAction.cc.
View newest version in sPHENIX GitHub at line 5 of file PHG4StackingAction.cc
virtual PHG4StackingAction::~PHG4StackingAction () inline virtual
Definition at line 20 of file PHG4StackingAction.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4StackingAction.h
Member Function Documentation
virtual G4ClassificationOfNewTrack PHG4StackingAction::ClassifyNewTrack (const G4Track *) inline virtual
stacking action. This gets called by the stacking action when a new track is generated
Definition at line 27 of file PHG4StackingAction.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4StackingAction.h
std::string PHG4StackingAction::GetName () const inline
Definition at line 35 of file PHG4StackingAction.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4StackingAction.h
References m_Name.
Referenced by cpp.ast.AstBuilder::_GetBases(), cpp.ast.AstBuilder::_GetClass(), cpp.ast.AstBuilder::_GetReturnTypeAndClassName(), cpp.ast.AstBuilder::_GetTemplatedTypes(), cpp.ast.AstBuilder::handle_namespace(), and cpp.ast.AstBuilder::handle_struct().
virtual int PHG4StackingAction::Init () inline virtual
Definition at line 31 of file PHG4StackingAction.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4StackingAction.h
virtual void PHG4StackingAction::PrepareNewEvent () inline virtual
Definition at line 28 of file PHG4StackingAction.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4StackingAction.h
virtual void PHG4StackingAction::Print (const std::string &) const inline virtual
Definition at line 34 of file PHG4StackingAction.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4StackingAction.h
virtual void PHG4StackingAction::SetInterfacePointers (PHCompositeNode *) inline virtual
Definition at line 33 of file PHG4StackingAction.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4StackingAction.h
void PHG4StackingAction::SetName (const std::string & name) inline
Definition at line 36 of file PHG4StackingAction.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4StackingAction.h
References m_Name, and perf_headwind::name.
virtual void PHG4StackingAction::Verbosity (const int i) inline virtual
Definition at line 29 of file PHG4StackingAction.h.
View newest version in sPHENIX GitHub at line 29 of file PHG4StackingAction.h
References i, and m_Verbosity.
virtual int PHG4StackingAction::Verbosity () const inline virtual
Definition at line 30 of file PHG4StackingAction.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4StackingAction.h
References m_Verbosity.
Member Data Documentation
std::string PHG4StackingAction::m_Name private
Definition at line 40 of file PHG4StackingAction.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4StackingAction.h
Referenced by GetName(), and SetName().
int PHG4StackingAction::m_Verbosity = 0 private
Definition at line 39 of file PHG4StackingAction.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4StackingAction.h
Referenced by Verbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4StackingAction.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4StackingAction.cc