Analysis Software: analysis/blob/master/EICAnalysis/macros/leptoquarks_fun4all/G4_CEmc_Spacal.C File Reference
G4_CEmc_Spacal.C File Reference
#include <iostream>
Enumerations
enum enu_Cemc_clusterizer { kCemcGraphClusterizer, kCemcTemplateClusterizer }
Functions
void CEmcInit (const int nslats=1)
graph clusterizer, RawClusterBuilderGraph
double CEmc (PHG4Reco *g4Reco, double radius, const int crossings, const int absorberactive=0)
EMCal main setup macro.
double CEmc_1DProjectiveSpacal (PHG4Reco *g4Reco, double radius, const int crossings, const int absorberactive=0)
EMCal setup macro - 1D azimuthal projective SPACAL.
double CEmc_2DProjectiveSpacal (PHG4Reco *g4Reco, double radius, const int crossings, const int absorberactive=0)
2D full projective SPACAL
void CEMC_Cells (int verbosity=0)
void CEMC_Towers (int verbosity=0)
void CEMC_Clusters (int verbosity=0)
void CEMC_Eval (std::string outputfile, int verbosity=0)
Variables
int Min_cemc_layer = 1
int Max_cemc_layer = 1
int Cemc_spacal_configuration = PHG4CylinderGeom_Spacalv1::k2DProjectiveSpacal
enu_Cemc_clusterizer Cemc_clusterizer = kCemcTemplateClusterizer
template clusterizer, RawClusterBuilderTemplate, as developed by Sasha Bazilevsky
Enumeration Type Documentation
enum enu_Cemc_clusterizer
Enumerator:
kCemcGraphClusterizer
kCemcTemplateClusterizer
Definition at line 11 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 11 of file G4_CEmc_Spacal.C
Function Documentation
double CEmc (PHG4Reco * g4Reco, double radius, const int crossings, const int absorberactive = 0)
EMCal main setup macro.
Definition at line 34 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 34 of file G4_CEmc_Spacal.C
References CEmc_1DProjectiveSpacal(), CEmc_2DProjectiveSpacal(), Cemc_spacal_configuration, PHG4CylinderGeom_Spacalv1::k1DProjectiveSpacal, and PHG4CylinderGeom_Spacalv1::k2DProjectiveSpacal.
Referenced by Fun4All_G4_Momentum_Projection_Calorimeters(), and G4Setup().
double CEmc_1DProjectiveSpacal (PHG4Reco * g4Reco, double radius, const int crossings, const int absorberactive = 0)
EMCal setup macro - 1D azimuthal projective SPACAL.
Definition at line 59 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 59 of file G4_CEmc_Spacal.C
References cemc, Max_cemc_layer, Min_cemc_layer, no_overlapp, overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), and PHG4DetectorSubsystem::SuperDetector().
Referenced by CEmc().
double CEmc_2DProjectiveSpacal (PHG4Reco * g4Reco, double radius, const int crossings, const int absorberactive = 0)
2D full projective SPACAL
Definition at line 140 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 140 of file G4_CEmc_Spacal.C
References assert, cemc, PHG4CylinderGeom_Spacalv1::kFullProjective_2DTaper_SameLengthFiberPerTower, Max_cemc_layer, no_overlapp, overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SetCalibrationFileDir(), PHG4DetectorSubsystem::SuperDetector(), PHG4DetectorSubsystem::UseCalibFiles(), Fun4AllBase::Verbosity(), and PHG4DetectorSubsystem::xml.
Referenced by CEmc().
void CEMC_Cells (int verbosity = 0)
Definition at line 256 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 256 of file G4_CEmc_Spacal.C
References PHG4CylinderCellReco::cellsize(), Cemc_spacal_configuration, PHG4CylinderCellReco::Detector(), PHG4FullProjSpacalCellReco::Detector(), PHG4FullProjSpacalCellReco::get_light_collection_model(), i, Fun4AllServer::instance(), PHG4CylinderGeom_Spacalv1::k1DProjectiveSpacal, PHG4CylinderGeom_Spacalv1::k2DProjectiveSpacal, LightCollectionModel::load_data_file(), Max_cemc_layer, Min_cemc_layer, Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_Calo(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_HCalJetPhiShift(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_single_particle(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Jin_BJet(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), spiNo2(), and Wrapper().
void CEMC_Clusters (int verbosity = 0)
Definition at line 378 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 378 of file G4_CEmc_Spacal.C
References Cemc_clusterizer, RawClusterBuilderGraph::Detector(), RawClusterBuilderTemplate::Detector(), Fun4AllServer::instance(), kCemcGraphClusterizer, kCemcTemplateClusterizer, Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_Calo(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_HCalJetPhiShift(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_single_particle(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Jin_BJet(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), spiNo2(), and Wrapper().
void CEMC_Eval (std::string outputfile, int verbosity = 0)
Definition at line 418 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 418 of file G4_CEmc_Spacal.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_single_particle(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Jin_BJet(), and Wrapper().
void CEMC_Towers (int verbosity = 0)
Definition at line 298 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 298 of file G4_CEmc_Spacal.C
References Cemc_spacal_configuration, RawTowerBuilder::Detector(), RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), Acts::UnitConstants::e, RawTowerCalibration::GetCalibrationParameters(), Fun4AllServer::instance(), PHG4CylinderGeom_Spacalv1::k1DProjectiveSpacal, PHG4CylinderGeom_Spacalv1::k2DProjectiveSpacal, RawTowerCalibration::kSimple_linear_calibration, RawTowerDigitizer::kSimple_photon_digitization, RawTowerCalibration::kTower_by_tower_calibration, PHParameters::ReadFromFile(), Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), RawTowerBuilder::set_sim_tower_node_prefix(), RawTowerDigitizer::set_zero_suppression_ADC(), verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_Calo(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_HCalJetPhiShift(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_single_particle(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Jin_BJet(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), spiNo2(), and Wrapper().
void CEmcInit (const int nslats = 1)
graph clusterizer, RawClusterBuilderGraph
Definition at line 26 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 26 of file G4_CEmc_Spacal.C
References Max_cemc_layer, and Min_cemc_layer.
Referenced by G4Init().
Variable Documentation
enu_Cemc_clusterizer Cemc_clusterizer = kCemcTemplateClusterizer
template clusterizer, RawClusterBuilderTemplate, as developed by Sasha Bazilevsky
Definition at line 19 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 19 of file G4_CEmc_Spacal.C
Referenced by CEMC_Clusters().
int Cemc_spacal_configuration = PHG4CylinderGeom_Spacalv1::k2DProjectiveSpacal
Definition at line 9 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 9 of file G4_CEmc_Spacal.C
Referenced by CEmc(), CEMC_Cells(), and CEMC_Towers().
int Max_cemc_layer = 1
Definition at line 3 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 3 of file G4_CEmc_Spacal.C
Referenced by CEmc_1DProjectiveSpacal(), CEmc_2DProjectiveSpacal(), CEMC_Cells(), CEmcInit(), Fun4All_G4_Clusters(), Fun4All_G4_W(), and Get_Max_cemc_layer().
int Min_cemc_layer = 1
Definition at line 2 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 2 of file G4_CEmc_Spacal.C
Referenced by CEmc_1DProjectiveSpacal(), CEMC_Cells(), CEmcInit(), Fun4All_G4_Clusters(), and Get_Min_cemc_layer().