Analysis Software: analysis/blob/master/CalorimeterJets/src/MyJetAnalysis.cc File Reference
MyJetAnalysis.cc File Reference
#include "MyJetAnalysis.h"
#include <vector>
#include <fun4all/Fun4AllReturnCodes.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/PHTFileServer.h>
#include <HepMC/GenVertex.h>
#include <HepMC/IteratorRange.h>
#include <HepMC/SimpleVector.h>
#include <phool/PHCompositeNode.h>
#include <phool/getClass.h>
#include <trackbase_historic/SvtxTrackMap.h>
#include <g4jets/FastJetAlgo.h>
#include <jetbackground/FastJetAlgoSub.h>
#include <g4jets/JetMap.h>
#include <g4jets/Jetv1.h>
#include <g4vertex/GlobalVertex.h>
#include <g4vertex/GlobalVertexMap.h>
#include <calobase/RawTowerContainer.h>
#include <calobase/RawTower.h>
#include <calobase/RawTowerGeomContainer.h>
#include <calobase/RawTowerGeom.h>
#include <calobase/TowerInfoContainer.h>
#include <calobase/TowerInfo.h>
#include <g4main/PHG4Particle.h>
#include <g4main/PHG4TruthInfoContainer.h>
#include <g4eval/CaloRawTowerEval.h>
#include <g4eval/CaloEvalStack.h>
#include <ffaobjects/EventHeader.h>
#include <ffaobjects/EventHeaderv1.h>
#include <centrality/CentralityInfo.h>
#include <fastjet/ClusterSequence.hh>
#include <fastjet/JetDefinition.hh>
#include <fastjet/PseudoJet.hh>
#include <jetbackground/TowerBackground.h>
#include <phhepmc/PHHepMCGenEvent.h>
#include <phhepmc/PHHepMCGenEventMap.h>
#include <TFile.h>
#include <TH1F.h>
#include <TH2F.h>
#include <TString.h>
#include <TTree.h>
#include <TVector3.h>
#include <TLorentzVector.h>
#include <TArrayF.h>
#include <fstream>
#include <algorithm>
#include <cassert>
#include <cmath>
#include <iostream>
#include <limits>
#include <stdexcept>
Functions
double DeltaPhi (double phi1, double phi2)
Function Documentation
double DeltaPhi (double phi1, double phi2)
Definition at line 68 of file MyJetAnalysis.cc.
View newest version in sPHENIX GitHub at line 68 of file MyJetAnalysis.cc
References TwoPi.
Referenced by ana_hijbkg(), PHTpcCentralMembraneClusterizer::process_event(), and MyJetAnalysis::process_event().