Analysis Software: Acts::Logger Class Reference
Acts::Logger Class Reference
class for printing debug output
#include <acts/blob/sPHENIX/Core/include/Acts/Utilities/Logger.hpp>
Public Member Functions
Logger (std::unique_ptr< Logging::OutputPrintPolicy > pPrint, std::unique_ptr< Logging::OutputFilterPolicy > pFilter)
construct from output print and filter policy
bool doPrint (const Logging::Level &lvl) const
decide whether a message with a given debug level has to be printed
void log (const Logging::Level &lvl, const std::string &input) const
log a debug message
const Logging::OutputPrintPolicy & printPolicy () const
const Logging::OutputFilterPolicy & filterPolicy () const
Logging::Level level () const
const std::string & name () const
std::unique_ptr< Logger > clone (const std::optional< std::string > &_name=std::nullopt, const std::optional< Logging::Level > &_level=std::nullopt) const
std::unique_ptr< Logger > clone (Logging::Level _level) const
std::unique_ptr< Logger > cloneWithSuffix (const std::string &suffix, std::optional< Logging::Level > _level=std::nullopt) const
const Logger & operator() () const
Private Attributes
std::unique_ptr
< Logging::OutputPrintPolicy > m_printPolicy
policy object for printing debug messages
std::unique_ptr
< Logging::OutputFilterPolicy > m_filterPolicy
policy object for filtering debug messages
Detailed Description
class for printing debug output
This class provides the user interface for printing debug messages with different levels of severity.
Definition at line 613 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 613 of file Logger.hpp
Constructor & Destructor Documentation
Acts::Logger::Logger (std::unique_ptr< Logging::OutputPrintPolicy > pPrint, std::unique_ptr< Logging::OutputFilterPolicy > pFilter) inline
construct from output print and filter policy
Parameters
[in] pPrint policy for printing debug messages
[in] pFilter policy for filtering debug messages
Definition at line 619 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 619 of file Logger.hpp
Member Function Documentation
std::unique_ptr<Logger> Acts::Logger::clone (const std::optional< std::string > & _name = std::nullopt, const std::optional< Logging::Level > & _level = std::nullopt) const inline
Make a copy of this logger, optionally changing the name or the level
Parameters
_name the optional new name
_level the optional new level
Definition at line 665 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 665 of file Logger.hpp
References level(), m_filterPolicy, m_printPolicy, and name().
Referenced by clone(), cloneWithSuffix(), ActsExamples::Geant4::Geant4Detector::constructTrackingGeometry(), Acts::cylinderVolumeHelper_dd4hep(), ActsExamples::TrackFindingFromPrototrackAlgorithm::execute(), and Acts::volumeBuilder_dd4hep().
std::unique_ptr<Logger> Acts::Logger::clone (Logging::Level _level) const inline
Make a copy of the logger, with a new level. Convenience function for if you only want to change the level but not the name.
Parameters
_level the new level
Returns
the new logger
Definition at line 677 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 677 of file Logger.hpp
References clone().
std::unique_ptr<Logger> Acts::Logger::cloneWithSuffix (const std::string & suffix, std::optional< Logging::Level > _level = std::nullopt) const inline
Make a copy of the logger, with a suffix added to the end of it's name. You can also optionally supply a new level
Parameters
suffix the suffix to add to the end of the name
_level the optional new level
Definition at line 685 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 685 of file Logger.hpp
References clone(), level(), and name().
Referenced by ActsExamples::IterativeVertexFinderAlgorithm::execute(), ActsExamples::VertexFitterAlgorithm::execute(), ActsTrackFittingAlgorithm::makeDirectedKalmanFitterFunction(), ActsExamples::makeGlobalChiSquareFitterFunction(), ActsExamples::makeGsfFitterFunction(), ActsGsfTrackFittingAlgorithm::makeGsfFitterFunction(), ActsExamples::makeKalmanFitterFunction(), ActsTrackFittingAlgorithm::makeKalmanFitterFunction(), and ActsExamples::TrackFindingAlgorithm::makeTrackFinderFunction().
bool Acts::Logger::doPrint (const Logging::Level & lvl) const inline
decide whether a message with a given debug level has to be printed
Parameters
[in] lvl debug level of debug message
Returns
true if debug message should be printed, otherwise false
Definition at line 628 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 628 of file Logger.hpp
References m_filterPolicy.
Referenced by log().
const Logging::OutputFilterPolicy& Acts::Logger::filterPolicy () const inline
Return the filter policy for this logger
Returns
the filter policy
Definition at line 650 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 650 of file Logger.hpp
References m_filterPolicy.
Logging::Level Acts::Logger::level () const inline
Return the level of the filter policy of this logger
Returns
the level
Definition at line 656 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 656 of file Logger.hpp
References m_filterPolicy.
Referenced by clone(), cloneWithSuffix(), ActsExamples::Geant4SimulationBase::Geant4SimulationBase(), and ActsExamples::Sequencer::run().
void Acts::Logger::log (const Logging::Level & lvl, const std::string & input) const inline
log a debug message
Parameters
[in] lvl debug level of debug message
[in] input text of debug message
Definition at line 636 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 636 of file Logger.hpp
References doPrint(), and m_printPolicy.
Referenced by __example_2.f__(), aiz(), alphas(), avscatcen(), biz(), deltas(), dofistatescat(), doinstatescat(), dokinematics(), genevent(), getdeltat(), getinspliti(), getinsudared(), getmass(), getpdfxint(), getscatterer(), getspliti(), gettemp(), getxsecint(), hijing(), insudaint(), intpgghigh(), intpgglow(), intpqghigh(), intpqglow(), intpqq(), lucell(), ludecy(), luptdi(), luradk(), lushow(), lustrf(), lutabu(), lux3jt(), lux4jt(), luxjet(), luxtot(), luzdis(), makeinsplit(), makesplitting(), mpolrad(), pdfint(), plu(), poissonian(), pyalem(), pyalps(), pyboei(), pycell(), pyct5l(), pyct5m(), pycteq(), pydecy(), pydisg(), pydocu(), pyevnt(), pyevnw(), pyfcmp(), pyfisb(), pyfscr(), pygaga(), pygano(), pygbeh(), pygdir(), pygfxx(), pyggam(), pygrvd(), pygrvl(), pygrvm(), pygrvs(), pygrvw(), pygvmd(), pyhii3au(), pyhiklim(), pyhikmap(), pyhimaxi(), pyhimult(), pyhirand(), pyhiremn(), pyhisigh(), pyhispen(), pyhisspa(), pyhistfu(), pyhithia(), pyhiw1au(), pyhiw2au(), pyhiwidt(), pyhixtot(), pyi3au(), pyinom(), pyinpr(), pyklim(), pykmap(), pymaxi(), pymign(), pymihk(), pymirm(), pymrun(), pymult(), pyofsh(), pyp(), pypcmp(), pypdel(), pypdfl(), pypdfu(), pypdga(), pypdpi(), pypdpo(), pyptdi(), pyptfs(), pyptis(), pyptmi(), pyradk(), pyrand(), pyreco(), pyremn(), pyresd(), pyrghm(), pysghg(), pysgqc(), pysgwz(), pyshow(), pysigh(), pyspen(), pysspa(), pystrf(), pysubh(), pytabu(), pytbbc(), pytbbn(), pywaux(), pywidt(), pyx3jt(), pyx4jt(), pyxjet(), pyxtee(), pyxtot(), pyxxga(), pyxxz6(), pyzdis(), r1990(), r1998(), rv2(), scatprimfunc(), splitfncint(), ulalps(), vacpol(), and xsecint().
const std::string& Acts::Logger::name () const inline
Return the name of the print policy of this logger
Returns
the name
Definition at line 660 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 660 of file Logger.hpp
References m_printPolicy.
Referenced by clone(), and cloneWithSuffix().
const Logger& Acts::Logger::operator() () const inline
Helper function so a logger reference can be used as is with the logging macros
Definition at line 693 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 693 of file Logger.hpp
const Logging::OutputPrintPolicy& Acts::Logger::printPolicy () const inline
Return the print policy for this logger
Returns
the print policy
Definition at line 644 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 644 of file Logger.hpp
References m_printPolicy.
Member Data Documentation
std::unique_ptr<Logging::OutputFilterPolicy> Acts::Logger::m_filterPolicy private
policy object for filtering debug messages
Definition at line 700 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 700 of file Logger.hpp
Referenced by clone(), doPrint(), filterPolicy(), and level().
std::unique_ptr<Logging::OutputPrintPolicy> Acts::Logger::m_printPolicy private
policy object for printing debug messages
Definition at line 697 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 697 of file Logger.hpp
Referenced by clone(), log(), name(), and printPolicy().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Utilities/Logger.hpp