Analysis Software: ACTSGEOM Namespace Reference
ACTSGEOM Namespace Reference
Functions
void ActsGeomInit ()
Variables
unsigned int mvtxMisalignment = 1
unsigned int inttMisalignment = 1
unsigned int tpcMisalignment = 1
unsigned int tpotMisalignment = 1
Function Documentation
void ACTSGEOM::ActsGeomInit ()
Definition at line 29 of file G4_ActsGeom.C.
View newest version in sPHENIX GitHub at line 29 of file G4_ActsGeom.C
References i, G4TRACKING::init_acts_magfield, Fun4AllServer::instance(), inttMisalignment, MakeActsGeometry::loadMagField(), G4MAGNET::magfield, G4MAGNET::magfield_rescale, Enable::MICROMEGAS, MakeActsGeometry::misalignmentFactor(), mvtxMisalignment, G4MICROMEGAS::n_micromegas_layer, MakeActsGeometry::set_drift_velocity(), MakeActsGeometry::setMagField(), MakeActsGeometry::setMagFieldRescale(), G4TPC::tpc_drift_velocity_reco, tpcMisalignment, tpotMisalignment, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by ClusteringInit(), Fun4All_TrkrClusteringSeeding(), Micromegas_Cells(), TPC_Clustering(), TPC_LaserClustering(), and TrackingInit().
Variable Documentation
unsigned int ACTSGEOM::inttMisalignment = 1
Definition at line 25 of file G4_ActsGeom.C.
View newest version in sPHENIX GitHub at line 25 of file G4_ActsGeom.C
Referenced by ActsGeomInit().
unsigned int ACTSGEOM::mvtxMisalignment = 1
Definition at line 24 of file G4_ActsGeom.C.
View newest version in sPHENIX GitHub at line 24 of file G4_ActsGeom.C
Referenced by ActsGeomInit().
unsigned int ACTSGEOM::tpcMisalignment = 1
Definition at line 26 of file G4_ActsGeom.C.
View newest version in sPHENIX GitHub at line 26 of file G4_ActsGeom.C
Referenced by ActsGeomInit().
unsigned int ACTSGEOM::tpotMisalignment = 1
Definition at line 27 of file G4_ActsGeom.C.
View newest version in sPHENIX GitHub at line 27 of file G4_ActsGeom.C
Referenced by ActsGeomInit().