Analysis Software: coresoftware/blob/master/offline/packages/PHGeometry/macros/PHGeom_DSTInspection.C File Reference
PHGeom_DSTInspection.C File Reference
Quick inspection of PHGeoTGeo object in RUN/GEOMETRY node inside a DST file.
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllNoSyncDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <phool/recoConsts.h>
#include <phgeom/PHGeomUtility.h>
#include <TEveManager.h>
#include <TGLViewer.h>
#include <TGLUtil.h>
#include <TGLClip.h>
#include <TGeoManager.h>
#include <TROOT.h>
#include <TEveGeoNode.h>
#include <cassert>
#include <string>
Functions
void PHGeom_DSTInspection (string DST_file_name="G4sPHENIX.root", bool do_clip=true)
Detailed Description
Quick inspection of PHGeoTGeo object in RUN/GEOMETRY node inside a DST file.
Author
Jin Huang jhuan.nosp@m.g@bn.nosp@m.l.gov
Version
Revision:
Date
Date:
Definition in file PHGeom_DSTInspection.C.
Function Documentation
void PHGeom_DSTInspection (string DST_file_name = "G4sPHENIX.root", bool do_clip = true)
Quick inspection of PHGeoTGeo object in RUN/GEOMETRY node inside a DST file Based on abhisek's display macro
Definition at line 45 of file PHGeom_DSTInspection.C.
View newest version in sPHENIX GitHub at line 45 of file PHGeom_DSTInspection.C
References assert, Fun4AllInputManager::fileopen(), PHGeomUtility::GetTGeoManager(), recoConsts::instance(), Fun4AllServer::instance(), Fun4AllServer::registerInputManager(), Fun4AllServer::run(), PHFlag::set_IntFlag(), Fun4AllServer::topNode(), testSigmaEff::v, and Fun4AllBase::Verbosity().