Analysis Software: PHSiliconHelicalPropagator Class Reference
PHSiliconHelicalPropagator Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHSiliconHelicalPropagator.h>
Public Member Functions
PHSiliconHelicalPropagator (const std::string &name="PHSiliconHelicalPropagator")
~PHSiliconHelicalPropagator ()
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_track_map_name (const std::string &name)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int createSeedContainer (TrackSeedContainer *&container, const std::string &container_name, PHCompositeNode *topNode)
Private Attributes
ActsGeometry * _tgeometry = nullptr
TrackSeedContainer * _si_seeds = nullptr
TrackSeedContainer * _tpc_seeds = nullptr
TrackSeedContainer * _svtx_seeds = nullptr
TrkrClusterContainer * _cluster_map = nullptr
TrkrClusterCrossingAssoc * _cluster_crossing_map = nullptr
std::string _track_map_name = "SvtxTrackSeedContainer"
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 8 of file PHSiliconHelicalPropagator.h.
View newest version in sPHENIX GitHub at line 8 of file PHSiliconHelicalPropagator.h
Constructor & Destructor Documentation
PHSiliconHelicalPropagator::PHSiliconHelicalPropagator (const std::string & name = "PHSiliconHelicalPropagator")
Definition at line 20 of file PHSiliconHelicalPropagator.cc.
View newest version in sPHENIX GitHub at line 20 of file PHSiliconHelicalPropagator.cc
PHSiliconHelicalPropagator::~PHSiliconHelicalPropagator ()
Definition at line 25 of file PHSiliconHelicalPropagator.cc.
View newest version in sPHENIX GitHub at line 25 of file PHSiliconHelicalPropagator.cc
Member Function Documentation
int PHSiliconHelicalPropagator::createSeedContainer (TrackSeedContainer *& container, const std::string & container_name, PHCompositeNode * topNode) private
Definition at line 78 of file PHSiliconHelicalPropagator.cc.
View newest version in sPHENIX GitHub at line 78 of file PHSiliconHelicalPropagator.cc
References PHCompositeNode::addNode(), container, Fun4AllReturnCodes::EVENT_OK, and PHNodeIterator::findFirst().
Referenced by InitRun().
int PHSiliconHelicalPropagator::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 217 of file PHSiliconHelicalPropagator.cc.
View newest version in sPHENIX GitHub at line 217 of file PHSiliconHelicalPropagator.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHSiliconHelicalPropagator::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 29 of file PHSiliconHelicalPropagator.cc.
View newest version in sPHENIX GitHub at line 29 of file PHSiliconHelicalPropagator.cc
References _cluster_crossing_map, _cluster_map, _si_seeds, _svtx_seeds, _tgeometry, _tpc_seeds, _track_map_name, Fun4AllReturnCodes::ABORTEVENT, createSeedContainer(), Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
int PHSiliconHelicalPropagator::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
There weren't enough clusters to fit
Check that the INTT clusters are in the same quadrant
Reimplemented from SubsysReco.
Definition at line 110 of file PHSiliconHelicalPropagator.cc.
View newest version in sPHENIX GitHub at line 110 of file PHSiliconHelicalPropagator.cc
References _cluster_crossing_map, _cluster_map, _si_seeds, _svtx_seeds, _tgeometry, _tpc_seeds, TrackFitUtils::addClusters(), TrackSeed::begin_cluster_keys(), TrackSeed::end_cluster_keys(), TrackSeedContainer::find(), TrkrClusterContainer::findCluster(), TrackFitUtils::fitClusters(), TrackSeedContainer::get(), TrkrClusterCrossingAssoc::getCrossings(), ActsGeometry::getGlobalPosition(), TrkrDefs::getLayer(), TrackFitUtils::getTrackletClusters(), TrkrDefs::getTrkrId(), TrackSeedContainer::insert(), TrackSeed_v1::insert_cluster_key(), TrkrDefs::inttId, TrkrDefs::mvtxId, SvtxTrackSeed_v1::set_silicon_seed_index(), SvtxTrackSeed_v1::set_tpc_seed_index(), TrackSeedContainer::size(), and Fun4AllBase::Verbosity().
void PHSiliconHelicalPropagator::set_track_map_name (const std::string & name) inline
Definition at line 18 of file PHSiliconHelicalPropagator.h.
View newest version in sPHENIX GitHub at line 18 of file PHSiliconHelicalPropagator.h
References _track_map_name, and perf_headwind::name.
Member Data Documentation
TrkrClusterCrossingAssoc* PHSiliconHelicalPropagator::_cluster_crossing_map = nullptr private
Definition at line 28 of file PHSiliconHelicalPropagator.h.
View newest version in sPHENIX GitHub at line 28 of file PHSiliconHelicalPropagator.h
Referenced by InitRun(), and process_event().
TrkrClusterContainer* PHSiliconHelicalPropagator::_cluster_map = nullptr private
Definition at line 27 of file PHSiliconHelicalPropagator.h.
View newest version in sPHENIX GitHub at line 27 of file PHSiliconHelicalPropagator.h
Referenced by InitRun(), and process_event().
TrackSeedContainer* PHSiliconHelicalPropagator::_si_seeds = nullptr private
Definition at line 24 of file PHSiliconHelicalPropagator.h.
View newest version in sPHENIX GitHub at line 24 of file PHSiliconHelicalPropagator.h
Referenced by InitRun(), and process_event().
TrackSeedContainer* PHSiliconHelicalPropagator::_svtx_seeds = nullptr private
Definition at line 26 of file PHSiliconHelicalPropagator.h.
View newest version in sPHENIX GitHub at line 26 of file PHSiliconHelicalPropagator.h
Referenced by InitRun(), and process_event().
ActsGeometry* PHSiliconHelicalPropagator::_tgeometry = nullptr private
Definition at line 23 of file PHSiliconHelicalPropagator.h.
View newest version in sPHENIX GitHub at line 23 of file PHSiliconHelicalPropagator.h
Referenced by InitRun(), and process_event().
TrackSeedContainer* PHSiliconHelicalPropagator::_tpc_seeds = nullptr private
Definition at line 25 of file PHSiliconHelicalPropagator.h.
View newest version in sPHENIX GitHub at line 25 of file PHSiliconHelicalPropagator.h
Referenced by InitRun(), and process_event().
std::string PHSiliconHelicalPropagator::_track_map_name = "SvtxTrackSeedContainer" private
Definition at line 30 of file PHSiliconHelicalPropagator.h.
View newest version in sPHENIX GitHub at line 30 of file PHSiliconHelicalPropagator.h
Referenced by InitRun(), and set_track_map_name().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHSiliconHelicalPropagator.h
coresoftware/blob/master/offline/packages/trackreco/PHSiliconHelicalPropagator.cc