Analysis Software: analysis/blob/master/JS-Jet/JetAnalysis/macro/Fun4All_JetVal.C File Reference
Fun4All_JetVal.C File Reference
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <phool/PHRandomSeed.h>
#include <phool/recoConsts.h>
#include <g4jets/FastJetAlgo.h>
#include <g4jets/JetReco.h>
#include <g4jets/TowerJetInput.h>
#include <g4jets/TruthJetInput.h>
#include <g4centrality/PHG4CentralityReco.h>
#include <jetbackground/CopyAndSubtractJets.h>
#include <jetbackground/DetermineTowerBackground.h>
#include <jetbackground/FastJetAlgoSub.h>
#include <jetbackground/RetowerCEMC.h>
#include <jetbackground/SubtractTowers.h>
#include <jetbackground/SubtractTowersCS.h>
#include </sphenix/u/damian0227/analysis/JS-Jet/JetAnalysis/src/JetKinematicCheck.h>
Namespaces
namespace Enable
namespace G4HIJETS
Functions
void Fun4All_JetVal (const char *filelistcalo="/sphenix/u/damian0227/analysis/JS-Jet/JetAnalysis/macro/dst_calo_cluster.list", const char *hits_mbd="/sphenix/u/damian0227/analysis/JS-Jet/JetAnalysis/macro/dst_bbc_g4hit.list", const char *outname="output.root")
Function Documentation
void Fun4All_JetVal (const char * filelistcalo = "/sphenix/u/damian0227/analysis/JS-Jet/JetAnalysis/macro/dst_calo_cluster.list", const char * hits_mbd = "/sphenix/u/damian0227/analysis/JS-Jet/JetAnalysis/macro/dst_bbc_g4hit.list", const char * outname = "output.root")
Definition at line 53 of file Fun4All_JetVal.C.
View newest version in sPHENIX GitHub at line 53 of file Fun4All_JetVal.C
References JetReco::add_algo(), JetReco::add_input(), Fun4AllInputManager::AddListFile(), Jet::ANTIKT, Jet::CEMC_TOWER_RETOWER, Jet::CEMC_TOWER_SUB1, G4HIJETS::do_flow, Fun4AllServer::End(), PHG4CentralityReco::GetCalibrationParameters(), Jet::HCALIN_TOWER, Jet::HCALIN_TOWER_SUB1, Jet::HCALOUT_TOWER, Jet::HCALOUT_TOWER_SUB1, recoConsts::instance(), Fun4AllServer::instance(), PHParameters::ReadFromFile(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), JetReco::set_algo_node(), JetReco::set_input_node(), DetermineTowerBackground::SetBackgroundOutputName(), JetKinematicCheck::setEtaRange(), DetermineTowerBackground::SetFlow(), SubtractTowers::SetFlowModulation(), CopyAndSubtractJets::SetFlowModulation(), JetKinematicCheck::setPtRange(), DetermineTowerBackground::SetSeedJetD(), DetermineTowerBackground::SetSeedJetPt(), DetermineTowerBackground::SetSeedType(), verbosity, and Fun4AllBase::Verbosity().