Analysis Software: ClusterErrorPara Class Reference
ClusterErrorPara Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase/ClusterErrorPara.h>
Public Types
using error_t = std::pair< double, double >
Public Member Functions
ClusterErrorPara ()
ClusterErrorPara (const ClusterErrorPara &)=delete
ClusterErrorPara & operator= (const ClusterErrorPara &)=delete
~ClusterErrorPara ()
error_t get_clusterv5_modified_error (TrkrCluster *cluster, double cluster_r, TrkrDefs::cluskey key)
error_t get_cluster_error (TrkrCluster *cluster, double cluster_r, TrkrDefs::cluskey key, float qOverR, float slope)
error_t get_cluster_error (TrkrCluster *cluster, TrkrDefs::cluskey key, double alpha, double beta)
error_t get_simple_cluster_error (TrkrCluster *cluster, double cluster_r, TrkrDefs::cluskey key)
error_t get_fix_tpc_cluster_error (TrkrCluster *cluster, TrkrDefs::cluskey key)
error_t get_si_cluster_error (const TrkrCluster *cluster, TrkrDefs::cluskey key)
double mm_phi_error (int layer, double alpha, TrkrCluster *cluster)
double mm_z_error (int layer, double beta, TrkrCluster *cluster)
double mvtx_phi_error (TrkrCluster *cluster)
double mvtx_phi_error (const TrkrCluster *cluster)
double mvtx_z_error (TrkrCluster *cluster)
double mvtx_z_error (const TrkrCluster *cluster)
double intt_phi_error (int layer, TrkrCluster *cluster)
double intt_z_error (TrkrCluster *cluster)
double intt_phi_error (int layer, const TrkrCluster *cluster)
double intt_z_error (const TrkrCluster *cluster)
double tpc_phi_error (int layer, double alpha, TrkrCluster *cluster)
double tpc_z_error (int layer, double beta, TrkrCluster *cluster)
Private Attributes
TF1 * f0 = nullptr
TF1 * f1 = nullptr
TF1 * f2 = nullptr
TF1 * f0fine = nullptr
TF1 * f1fine = nullptr
TF1 * f2fine = nullptr
TF1 * f2fine2 = nullptr
TF1 * fz0 = nullptr
TF1 * fz1 = nullptr
TF1 * fz2 = nullptr
TF1 * fz0fine = nullptr
TF1 * fz1fine = nullptr
TF1 * fz2fine = nullptr
TF1 * fmm_55_2 = nullptr
TF1 * fmm_56_2 = nullptr
TF1 * fmm_3 = nullptr
TF1 * fadcz0 = nullptr
TF1 * fadcz1 = nullptr
TF1 * fadcz2 = nullptr
TF1 * fadcz0fine = nullptr
TF1 * fadcz1fine = nullptr
TF1 * fadcz2fine = nullptr
TF1 * fadcphi0 = nullptr
TF1 * fadcphi0fine = nullptr
TF1 * fadcphi1 = nullptr
TF1 * fadcphi1fine = nullptr
TF1 * fadcphi2 = nullptr
TF1 * fadcphi2fine1 = nullptr
TF1 * fadcphi2fine2 = nullptr
double pitcherr_phi_mvtx
double pitcherr_z_mvtx
double pitcherr_phi_intt
double pitcherr_z_intt
double pitcherr_phi_mm1
double pitcherr_z_mm1
double pitcherr_phi_mm2
double pitcherr_z_mm2
double scale_mvtx = 1.2
double scale_mvtx_z = 0.9
double scale_intt_3 = 0.97
double scale_intt_4 = 0.964
double scale_intt_5 = 0.894
double scale_intt_6 = 0.893
double scale_mm_0 = 1.1
double scale_mm_1 = 1.5
double pull_fine_phi [60]
double pull_fine_z [60]
Detailed Description
Definition at line 15 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 15 of file ClusterErrorPara.h
Member Typedef Documentation
using ClusterErrorPara::error_t = std::pair<double, double>
Definition at line 56 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 56 of file ClusterErrorPara.h
Constructor & Destructor Documentation
ClusterErrorPara::ClusterErrorPara ()
Definition at line 18 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 18 of file ClusterErrorPara.cc
References Acts::UnitConstants::e, f0, f0fine, f1, f1fine, f2, f2fine, fadcphi0, fadcphi0fine, fadcphi1, fadcphi1fine, fadcphi2, fadcphi2fine1, fadcphi2fine2, fadcz0, fadcz0fine, fadcz1, fadcz1fine, fadcz2, fadcz2fine, fmm_3, fmm_55_2, fmm_56_2, fz0, fz0fine, fz1, fz1fine, fz2, fz2fine, pitcherr_phi_intt, pitcherr_phi_mm1, pitcherr_phi_mm2, pitcherr_phi_mvtx, pitcherr_z_intt, pitcherr_z_mm1, pitcherr_z_mm2, pitcherr_z_mvtx, pull_fine_phi, and pull_fine_z.
ClusterErrorPara::ClusterErrorPara (const ClusterErrorPara &) explicit delete
ClusterErrorPara::~ClusterErrorPara () inline
Definition at line 24 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 24 of file ClusterErrorPara.h
References f0, f0fine, f1, f1fine, f2, f2fine, f2fine2, fadcphi0, fadcphi0fine, fadcphi1, fadcphi1fine, fadcphi2, fadcphi2fine1, fadcphi2fine2, fadcz0, fadcz0fine, fadcz1, fadcz1fine, fadcz2, fadcz2fine, fmm_3, fmm_55_2, fmm_56_2, fz0, fz0fine, fz1, fz1fine, fz2, and fz2fine.
Member Function Documentation
ClusterErrorPara::error_t ClusterErrorPara::get_cluster_error (TrkrCluster * cluster, double cluster_r, TrkrDefs::cluskey key, float qOverR, float slope)
Definition at line 503 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 503 of file ClusterErrorPara.cc
References alpha, Acts::IntegrationTest::R, and physmon_track_finding_ttbar::r.
Referenced by TrackEvaluation::create_cluster().
ClusterErrorPara::error_t ClusterErrorPara::get_cluster_error (TrkrCluster * cluster, TrkrDefs::cluskey key, double alpha, double beta)
Definition at line 813 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 813 of file ClusterErrorPara.cc
References TrkrDefs::getLayer(), TrkrDefs::getTrkrId(), intt_phi_error(), intt_z_error(), TrkrDefs::inttId, layer, TrkrDefs::micromegasId, mm_phi_error(), mm_z_error(), mvtx_phi_error(), mvtx_z_error(), TrkrDefs::mvtxId, pull_fine_phi, pull_fine_z, square(), tpc_phi_error(), tpc_z_error(), and TrkrDefs::tpcId.
ClusterErrorPara::error_t ClusterErrorPara::get_clusterv5_modified_error (TrkrCluster * cluster, double cluster_r, TrkrDefs::cluskey key)
Definition at line 475 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 475 of file ClusterErrorPara.cc
References TrkrCluster::getEdge(), TrkrDefs::getLayer(), TrkrCluster::getOverlap(), TrkrCluster::getPhiSize(), TrkrCluster::getRPhiError(), TrkrDefs::getTrkrId(), TrkrCluster::getZError(), layer, square(), and TrkrDefs::tpcId.
Referenced by MakeMilleFiles::addTrackToMilleFile(), TrackEvaluation::create_cluster(), TrackResiduals::fillClusterBranches(), TrackResiduals::fillClusterTree(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHCosmicsTrkFitter::fillVectors(), ALICEKF::getClusterError(), HelicalFitter::getClusterError(), and MakeSourceLinks::getSourceLinks().
ClusterErrorPara::error_t ClusterErrorPara::get_fix_tpc_cluster_error (TrkrCluster * cluster, TrkrDefs::cluskey key)
Definition at line 917 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 917 of file ClusterErrorPara.cc
References TrkrDefs::getLayer(), layer, mvtx_phi_error(), mvtx_z_error(), pull_fine_phi, pull_fine_z, and square().
ClusterErrorPara::error_t ClusterErrorPara::get_si_cluster_error (const TrkrCluster * cluster, TrkrDefs::cluskey key)
Definition at line 940 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 940 of file ClusterErrorPara.cc
References TrkrDefs::getLayer(), TrkrDefs::getTrkrId(), intt_phi_error(), intt_z_error(), TrkrDefs::inttId, layer, mvtx_phi_error(), mvtx_z_error(), TrkrDefs::mvtxId, pull_fine_phi, pull_fine_z, and square().
ClusterErrorPara::error_t ClusterErrorPara::get_simple_cluster_error (TrkrCluster * cluster, double cluster_r, TrkrDefs::cluskey key)
Definition at line 866 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 866 of file ClusterErrorPara.cc
References alpha, TrkrDefs::getLayer(), TrkrDefs::getTrkrId(), intt_phi_error(), intt_z_error(), TrkrDefs::inttId, layer, TrkrDefs::micromegasId, mm_phi_error(), mm_z_error(), mvtx_phi_error(), mvtx_z_error(), TrkrDefs::mvtxId, pull_fine_phi, pull_fine_z, square(), tpc_phi_error(), tpc_z_error(), and TrkrDefs::tpcId.
double ClusterErrorPara::intt_phi_error (int layer, TrkrCluster * cluster)
Definition at line 769 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 769 of file ClusterErrorPara.cc
References TrkrCluster::getPhiSize(), pitcherr_phi_intt, scale_intt_3, scale_intt_4, scale_intt_5, and scale_intt_6.
Referenced by get_cluster_error(), get_si_cluster_error(), and get_simple_cluster_error().
double ClusterErrorPara::intt_phi_error (int layer, const TrkrCluster * cluster)
Definition at line 790 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 790 of file ClusterErrorPara.cc
References TrkrCluster::getPhiSize(), pitcherr_phi_intt, scale_intt_3, scale_intt_4, scale_intt_5, and scale_intt_6.
double ClusterErrorPara::intt_z_error (TrkrCluster * cluster)
Definition at line 785 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 785 of file ClusterErrorPara.cc
References TrkrCluster::getZSize(), and pitcherr_z_intt.
Referenced by get_cluster_error(), get_si_cluster_error(), and get_simple_cluster_error().
double ClusterErrorPara::intt_z_error (const TrkrCluster * cluster)
Definition at line 806 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 806 of file ClusterErrorPara.cc
References TrkrCluster::getZSize(), and pitcherr_z_intt.
double ClusterErrorPara::mm_phi_error (int layer, double alpha, TrkrCluster * cluster)
Definition at line 670 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 670 of file ClusterErrorPara.cc
References fmm_3, fmm_55_2, TrkrCluster::getPhiSize(), pitcherr_phi_mm1, pitcherr_phi_mm2, and scale_mm_0.
Referenced by get_cluster_error(), and get_simple_cluster_error().
double ClusterErrorPara::mm_z_error (int layer, double beta, TrkrCluster * cluster)
Definition at line 687 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 687 of file ClusterErrorPara.cc
References fmm_3, fmm_56_2, TrkrCluster::getZSize(), pitcherr_z_mm1, pitcherr_z_mm2, and scale_mm_1.
Referenced by get_cluster_error(), and get_simple_cluster_error().
double ClusterErrorPara::mvtx_phi_error (TrkrCluster * cluster)
Definition at line 704 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 704 of file ClusterErrorPara.cc
References TrkrCluster::getPhiSize(), TrkrCluster::getZSize(), pitcherr_phi_mvtx, and scale_mvtx.
Referenced by get_cluster_error(), get_fix_tpc_cluster_error(), get_si_cluster_error(), and get_simple_cluster_error().
double ClusterErrorPara::mvtx_phi_error (const TrkrCluster * cluster)
Definition at line 725 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 725 of file ClusterErrorPara.cc
References TrkrCluster::getPhiSize(), TrkrCluster::getZSize(), pitcherr_phi_mvtx, and scale_mvtx.
double ClusterErrorPara::mvtx_z_error (TrkrCluster * cluster)
Definition at line 746 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 746 of file ClusterErrorPara.cc
References TrkrCluster::getPhiSize(), TrkrCluster::getZSize(), pitcherr_z_mvtx, and scale_mvtx_z.
Referenced by get_cluster_error(), get_fix_tpc_cluster_error(), get_si_cluster_error(), and get_simple_cluster_error().
double ClusterErrorPara::mvtx_z_error (const TrkrCluster * cluster)
Definition at line 757 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 757 of file ClusterErrorPara.cc
References TrkrCluster::getPhiSize(), TrkrCluster::getZSize(), pitcherr_z_mvtx, and scale_mvtx_z.
ClusterErrorPara& ClusterErrorPara::operator= (const ClusterErrorPara &) delete
double ClusterErrorPara::tpc_phi_error (int layer, double alpha, TrkrCluster * cluster)
Definition at line 512 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 512 of file ClusterErrorPara.cc
References f0, f0fine, f1, f1fine, f2, f2fine, fadcphi0, fadcphi0fine, fadcphi1, fadcphi1fine, fadcphi2, fadcphi2fine1, TrkrCluster::getEdge(), TrkrCluster::getMaxAdc(), and TrkrCluster::getPhiSize().
Referenced by get_cluster_error(), and get_simple_cluster_error().
double ClusterErrorPara::tpc_z_error (int layer, double beta, TrkrCluster * cluster)
Definition at line 614 of file ClusterErrorPara.cc.
View newest version in sPHENIX GitHub at line 614 of file ClusterErrorPara.cc
References fadcz0, fadcz0fine, fadcz1, fadcz1fine, fadcz2, fadcz2fine, fz0, fz0fine, fz1, fz1fine, fz2, fz2fine, and TrkrCluster::getMaxAdc().
Referenced by get_cluster_error(), and get_simple_cluster_error().
Member Data Documentation
TF1* ClusterErrorPara::f0 = nullptr private
Definition at line 79 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 79 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_phi_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::f0fine = nullptr private
Definition at line 82 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 82 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_phi_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::f1 = nullptr private
Definition at line 80 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 80 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_phi_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::f1fine = nullptr private
Definition at line 83 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 83 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_phi_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::f2 = nullptr private
Definition at line 81 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 81 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_phi_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::f2fine = nullptr private
Definition at line 84 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 84 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_phi_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::f2fine2 = nullptr private
Definition at line 85 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 85 of file ClusterErrorPara.h
Referenced by ~ClusterErrorPara().
TF1* ClusterErrorPara::fadcphi0 = nullptr private
Definition at line 101 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 101 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_phi_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fadcphi0fine = nullptr private
Definition at line 102 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 102 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_phi_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fadcphi1 = nullptr private
Definition at line 103 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 103 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_phi_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fadcphi1fine = nullptr private
Definition at line 104 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 104 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_phi_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fadcphi2 = nullptr private
Definition at line 105 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 105 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_phi_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fadcphi2fine1 = nullptr private
Definition at line 106 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 106 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_phi_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fadcphi2fine2 = nullptr private
Definition at line 107 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 107 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fadcz0 = nullptr private
Definition at line 95 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 95 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_z_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fadcz0fine = nullptr private
Definition at line 98 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 98 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_z_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fadcz1 = nullptr private
Definition at line 96 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 96 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_z_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fadcz1fine = nullptr private
Definition at line 99 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 99 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_z_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fadcz2 = nullptr private
Definition at line 97 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 97 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_z_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fadcz2fine = nullptr private
Definition at line 100 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 100 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_z_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fmm_3 = nullptr private
Definition at line 94 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 94 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), mm_phi_error(), mm_z_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fmm_55_2 = nullptr private
Definition at line 92 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 92 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), mm_phi_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fmm_56_2 = nullptr private
Definition at line 93 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 93 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), mm_z_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fz0 = nullptr private
Definition at line 86 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 86 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_z_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fz0fine = nullptr private
Definition at line 89 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 89 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_z_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fz1 = nullptr private
Definition at line 87 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 87 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_z_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fz1fine = nullptr private
Definition at line 90 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 90 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_z_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fz2 = nullptr private
Definition at line 88 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 88 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_z_error(), and ~ClusterErrorPara().
TF1* ClusterErrorPara::fz2fine = nullptr private
Definition at line 91 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 91 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), tpc_z_error(), and ~ClusterErrorPara().
double ClusterErrorPara::pitcherr_phi_intt private
Definition at line 111 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 111 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), and intt_phi_error().
double ClusterErrorPara::pitcherr_phi_mm1 private
Definition at line 114 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 114 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), and mm_phi_error().
double ClusterErrorPara::pitcherr_phi_mm2 private
Definition at line 117 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 117 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), and mm_phi_error().
double ClusterErrorPara::pitcherr_phi_mvtx private
Definition at line 108 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 108 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), and mvtx_phi_error().
double ClusterErrorPara::pitcherr_z_intt private
Definition at line 112 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 112 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), and intt_z_error().
double ClusterErrorPara::pitcherr_z_mm1 private
Definition at line 115 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 115 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), and mm_z_error().
double ClusterErrorPara::pitcherr_z_mm2 private
Definition at line 118 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 118 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), and mm_z_error().
double ClusterErrorPara::pitcherr_z_mvtx private
Definition at line 109 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 109 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), and mvtx_z_error().
double ClusterErrorPara::pull_fine_phi[60] private
Definition at line 134 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 134 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), get_cluster_error(), get_fix_tpc_cluster_error(), get_si_cluster_error(), and get_simple_cluster_error().
double ClusterErrorPara::pull_fine_z[60] private
Definition at line 135 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 135 of file ClusterErrorPara.h
Referenced by ClusterErrorPara(), get_cluster_error(), get_fix_tpc_cluster_error(), get_si_cluster_error(), and get_simple_cluster_error().
double ClusterErrorPara::scale_intt_3 = 0.97 private
Definition at line 121 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 121 of file ClusterErrorPara.h
Referenced by intt_phi_error().
double ClusterErrorPara::scale_intt_4 = 0.964 private
Definition at line 122 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 122 of file ClusterErrorPara.h
Referenced by intt_phi_error().
double ClusterErrorPara::scale_intt_5 = 0.894 private
Definition at line 123 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 123 of file ClusterErrorPara.h
Referenced by intt_phi_error().
double ClusterErrorPara::scale_intt_6 = 0.893 private
Definition at line 124 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 124 of file ClusterErrorPara.h
Referenced by intt_phi_error().
double ClusterErrorPara::scale_mm_0 = 1.1 private
Definition at line 132 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 132 of file ClusterErrorPara.h
Referenced by mm_phi_error().
double ClusterErrorPara::scale_mm_1 = 1.5 private
Definition at line 133 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 133 of file ClusterErrorPara.h
Referenced by mm_z_error().
double ClusterErrorPara::scale_mvtx = 1.2 private
Definition at line 119 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 119 of file ClusterErrorPara.h
Referenced by mvtx_phi_error().
double ClusterErrorPara::scale_mvtx_z = 0.9 private
Definition at line 120 of file ClusterErrorPara.h.
View newest version in sPHENIX GitHub at line 120 of file ClusterErrorPara.h
Referenced by mvtx_z_error().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/ClusterErrorPara.h
coresoftware/blob/master/offline/packages/trackbase/ClusterErrorPara.cc