Analysis Software: check_include_guards Namespace Reference
check_include_guards Namespace Reference
Functions
def line_fmt
def code_print
def check_include_guards
def main
Function Documentation
def check_include_guards.check_include_guards (file)
Definition at line 32 of file check_include_guards.py.
View newest version in sPHENIX GitHub at line 32 of file check_include_guards.py
References code_print(), test_fpe.count, and Acts.open.
def check_include_guards.code_print (code, start, maxlines = 15)
Definition at line 17 of file check_include_guards.py.
View newest version in sPHENIX GitHub at line 17 of file check_include_guards.py
References Acts.enumerate(), join(), and line_fmt().
Referenced by check_include_guards().
def check_include_guards.line_fmt (line)
Definition at line 13 of file check_include_guards.py.
View newest version in sPHENIX GitHub at line 13 of file check_include_guards.py
References material_mapping_optimisation.format.
Referenced by code_print().
def check_include_guards.main (void)
Definition at line 76 of file check_include_guards.py.
View newest version in sPHENIX GitHub at line 76 of file check_include_guards.py
References material_mapping_optimisation.format, print(), and sum().