Analysis Software: ActsExamples::ResPlotTool Class Reference
ActsExamples::ResPlotTool Class Reference
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Validation/ResPlotTool.hpp>
Classes
struct Config
Nested configuration struct.
struct ResPlotCache
Nested Cache struct.
Public Member Functions
ResPlotTool (const Config &cfg, Acts::Logging::Level lvl)
void book (ResPlotCache &resPlotCache) const
book the histograms
void fill (ResPlotCache &resPlotCache, const Acts::GeometryContext &gctx, const ActsFatras::Particle &truthParticle, const Acts::BoundTrackParameters &fittedParamters) const
fill the histograms
void refinement (ResPlotCache &resPlotCache) const
extract the details of the residual/pull plots and fill details
void write (const ResPlotCache &resPlotCache) const
write the histograms to output file
void clear (ResPlotCache &resPlotCache) const
delete the histograms
Private Member Functions
const Acts::Logger & logger () const
The logger.
Private Attributes
Config m_cfg
The config class.
std::unique_ptr< const
Acts::Logger > m_logger
The logging instance.
Detailed Description
Definition at line 34 of file ResPlotTool.hpp.
View newest version in sPHENIX GitHub at line 34 of file ResPlotTool.hpp
Constructor & Destructor Documentation
ActsExamples::ResPlotTool::ResPlotTool (const Config & cfg, Acts::Logging::Level lvl)
Constructor
Parameters
cfg Configuration struct
level Message level declaration
Definition at line 26 of file ResPlotTool.cpp.
View newest version in sPHENIX GitHub at line 26 of file ResPlotTool.cpp
Member Function Documentation
void ActsExamples::ResPlotTool::book (ResPlotTool::ResPlotCache & resPlotCache) const
book the histograms
Parameters
resPlotCache the cache for residual/pull histograms
Definition at line 30 of file ResPlotTool.cpp.
View newest version in sPHENIX GitHub at line 30 of file ResPlotTool.cpp
References ACTS_DEBUG, ActsExamples::PlotHelpers::bookHisto(), Acts::eBoundSize, m_cfg(), ActsExamples::ResPlotTool::ResPlotCache::pull, ActsExamples::ResPlotTool::ResPlotCache::pull_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::pull_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::pullMean_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::pullMean_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::pullWidth_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::pullWidth_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::res, ActsExamples::ResPlotTool::ResPlotCache::res_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::res_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::resMean_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::resMean_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::resWidth_vs_eta, and ActsExamples::ResPlotTool::ResPlotCache::resWidth_vs_pT.
Referenced by ActsExamples::TrackFitterPerformanceWriter::TrackFitterPerformanceWriter().
void ActsExamples::ResPlotTool::clear (ResPlotCache & resPlotCache) const
delete the histograms
Parameters
resPlotCache the cache object for residual/pull histograms
Definition at line 104 of file ResPlotTool.cpp.
View newest version in sPHENIX GitHub at line 104 of file ResPlotTool.cpp
References ACTS_DEBUG, Acts::eBoundSize, m_cfg(), ActsExamples::ResPlotTool::ResPlotCache::pull, ActsExamples::ResPlotTool::ResPlotCache::pull_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::pull_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::pullMean_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::pullMean_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::pullWidth_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::pullWidth_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::res, ActsExamples::ResPlotTool::ResPlotCache::res_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::res_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::resMean_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::resMean_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::resWidth_vs_eta, and ActsExamples::ResPlotTool::ResPlotCache::resWidth_vs_pT.
void ActsExamples::ResPlotTool::fill (ResPlotTool::ResPlotCache & resPlotCache, const Acts::GeometryContext & gctx, const ActsFatras::Particle & truthParticle, const Acts::BoundTrackParameters & fittedParamters) const
fill the histograms
Parameters
resPlotCache the cache for residual/pull histograms
gctx the geometry context
truthParticle the truth particle
fittedParamters the fitted parameters at perigee surface
Definition at line 147 of file ResPlotTool.cpp.
View newest version in sPHENIX GitHub at line 147 of file ResPlotTool.cpp
References ActsFatras::Particle::absoluteMomentum(), ACTS_ERROR, ACTS_WARNING, ActsFatras::Particle::charge(), covariance(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::covariance(), ActsFatras::Particle::direction(), Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundSize, Acts::eBoundTheta, Acts::eBoundTime, eta, Acts::VectorHelpers::eta(), ActsExamples::PlotHelpers::fillHisto(), m_cfg(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::parameters(), Acts::VectorHelpers::perp(), ActsTests::PropagationDatasets::phi, Acts::VectorHelpers::phi(), ActsFatras::Particle::position(), pSurface, ActsExamples::ResPlotTool::ResPlotCache::pull, ActsExamples::ResPlotTool::ResPlotCache::pull_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::pull_vs_pT, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::referenceSurface(), ActsExamples::ResPlotTool::ResPlotCache::res, ActsExamples::ResPlotTool::ResPlotCache::res_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::res_vs_pT, ActsTests::PropagationDatasets::theta, Acts::VectorHelpers::theta(), ActsFatras::Particle::time(), and ActsFatras::Particle::transverseMomentum().
const Acts::Logger& ActsExamples::ResPlotTool::logger () const inline private
The logger.
Definition at line 127 of file ResPlotTool.hpp.
View newest version in sPHENIX GitHub at line 127 of file ResPlotTool.hpp
References m_logger.
void ActsExamples::ResPlotTool::refinement (ResPlotTool::ResPlotCache & resPlotCache) const
extract the details of the residual/pull plots and fill details
into separate histograms
Parameters
resPlotCache the cache object for residual/pull histograms
Definition at line 222 of file ResPlotTool.cpp.
View newest version in sPHENIX GitHub at line 222 of file ResPlotTool.cpp
References ActsExamples::PlotHelpers::anaHisto(), Acts::eBoundSize, j, m_cfg(), ActsExamples::PlotHelpers::Binning::nBins(), ActsExamples::ResPlotTool::ResPlotCache::pull_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::pull_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::pullMean_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::pullMean_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::pullWidth_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::pullWidth_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::res_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::res_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::resMean_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::resMean_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::resWidth_vs_eta, and ActsExamples::ResPlotTool::ResPlotCache::resWidth_vs_pT.
void ActsExamples::ResPlotTool::write (const ResPlotCache & resPlotCache) const
write the histograms to output file
Parameters
resPlotCache the cache object for residual/pull histograms
Definition at line 125 of file ResPlotTool.cpp.
View newest version in sPHENIX GitHub at line 125 of file ResPlotTool.cpp
References ACTS_DEBUG, Acts::eBoundSize, m_cfg(), ActsExamples::ResPlotTool::ResPlotCache::pull, ActsExamples::ResPlotTool::ResPlotCache::pull_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::pull_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::pullMean_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::pullMean_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::pullWidth_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::pullWidth_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::res, ActsExamples::ResPlotTool::ResPlotCache::res_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::res_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::resMean_vs_eta, ActsExamples::ResPlotTool::ResPlotCache::resMean_vs_pT, ActsExamples::ResPlotTool::ResPlotCache::resWidth_vs_eta, and ActsExamples::ResPlotTool::ResPlotCache::resWidth_vs_pT.
Member Data Documentation
Config ActsExamples::ResPlotTool::m_cfg private
The config class.
Definition at line 123 of file ResPlotTool.hpp.
View newest version in sPHENIX GitHub at line 123 of file ResPlotTool.hpp
std::unique_ptr<const Acts::Logger> ActsExamples::ResPlotTool::m_logger private
The logging instance.
Definition at line 124 of file ResPlotTool.hpp.
View newest version in sPHENIX GitHub at line 124 of file ResPlotTool.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Validation/ResPlotTool.hpp
acts/blob/sPHENIX/Examples/Framework/src/Validation/ResPlotTool.cpp