Analysis Software: analysis/blob/master/dNdEta_Run2023/analysis_INTT/src/BeamspotReco.cxx File Reference
BeamspotReco.cxx File Reference
#include "TFile.h"
#include "TTree.h"
#include "TH1F.h"
#include "TF1.h"
#include "TF2.h"
#include "TGraphErrors.h"
#include <Eigen/Dense>
#include "Hit.h"
#include "Beamspot.h"
Functions
Beamspot fit_PCAD0Phi0 (std::vector< std::pair< std::shared_ptr< Hit >, std::shared_ptr< Hit >>> tracklets, Beamspot BS_init, double d0_cut)
int main (int argc, char **argv)
Function Documentation
Beamspot fit_PCAD0Phi0 (std::vector< std::pair< std::shared_ptr< Hit >, std::shared_ptr< Hit >>> tracklets, Beamspot BS_init, double d0_cut)
Definition at line 13 of file BeamspotReco.cxx.
View newest version in sPHENIX GitHub at line 13 of file BeamspotReco.cxx
References Beamspot::d0phi0dist, Acts::UnitConstants::g, i, Beamspot::Ntracklets, Beamspot::pcadist, r1, r2, Beamspot::sigma_x, Beamspot::sigma_y, Beamspot::sigma_z, Beamspot::x, Beamspot::y, Beamspot::z, and Beamspot::z0dist.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 139 of file BeamspotReco.cxx.
View newest version in sPHENIX GitHub at line 139 of file BeamspotReco.cxx
References Beamspot::d0phi0dist, physmon_vertexing::events, fit_PCAD0Phi0(), i, Beamspot::identify(), inf, infile, j, Beamspot::Ntracklets, Acts::Test::origin(), add_histos::outfile, Beamspot::pcadist, Beamspot::sigma_x, Beamspot::sigma_y, Beamspot::sigma_z, t, Beamspot::x, Beamspot::xy_correlation, Beamspot::y, Beamspot::z, and Beamspot::z0dist.