Analysis Software: MvtxRawHit Class Reference
MvtxRawHit Class Reference
#include <coresoftware/blob/master/offline/framework/ffarawobjects/MvtxRawHit.h>
Public Member Functions
MvtxRawHit ()=default
virtual ~MvtxRawHit ()=default
virtual uint64_t get_bco () const
virtual void set_bco (const uint64_t)
virtual uint32_t get_strobe_bc () const
virtual void set_strobe_bc (const uint32_t)
virtual uint32_t get_chip_bc () const
virtual void set_chip_bc (const uint32_t)
virtual uint8_t get_layer_id () const
virtual void set_layer_id (uint8_t)
virtual uint8_t get_stave_id () const
virtual void set_stave_id (uint8_t)
virtual uint8_t get_chip_id () const
virtual void set_chip_id (uint8_t)
virtual uint16_t get_row () const
virtual void set_row (uint16_t)
virtual uint16_t get_col () const
virtual void set_col (uint16_t)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
Definition at line 9 of file MvtxRawHit.h.
View newest version in sPHENIX GitHub at line 9 of file MvtxRawHit.h
Constructor & Destructor Documentation
MvtxRawHit::MvtxRawHit () default
virtual MvtxRawHit::~MvtxRawHit () virtual default
Member Function Documentation
virtual uint64_t MvtxRawHit::get_bco () const inline virtual
Reimplemented in MvtxRawHitv1.
Definition at line 17 of file MvtxRawHit.h.
View newest version in sPHENIX GitHub at line 17 of file MvtxRawHit.h
Referenced by MvtxRawHitContainerv1::identify(), MvtxRawHitv1::MvtxRawHitv1(), MvtxCombinedRawDataDecoder::process_event(), and DumpMvtxRawHitContainer::process_Node().
virtual uint32_t MvtxRawHit::get_chip_bc () const inline virtual
Reimplemented in MvtxRawHitv1.
Definition at line 23 of file MvtxRawHit.h.
View newest version in sPHENIX GitHub at line 23 of file MvtxRawHit.h
Referenced by MvtxRawHitv1::MvtxRawHitv1(), and DumpMvtxRawHitContainer::process_Node().
virtual uint8_t MvtxRawHit::get_chip_id () const inline virtual
Reimplemented in MvtxRawHitv1.
Definition at line 32 of file MvtxRawHit.h.
View newest version in sPHENIX GitHub at line 32 of file MvtxRawHit.h
Referenced by MvtxRawHitv1::MvtxRawHitv1(), MvtxCombinedRawDataDecoder::process_event(), and DumpMvtxRawHitContainer::process_Node().
virtual uint16_t MvtxRawHit::get_col () const inline virtual
Reimplemented in MvtxRawHitv1.
Definition at line 38 of file MvtxRawHit.h.
View newest version in sPHENIX GitHub at line 38 of file MvtxRawHit.h
Referenced by MvtxRawHitv1::MvtxRawHitv1(), MvtxCombinedRawDataDecoder::process_event(), and DumpMvtxRawHitContainer::process_Node().
virtual uint8_t MvtxRawHit::get_layer_id () const inline virtual
Reimplemented in MvtxRawHitv1.
Definition at line 26 of file MvtxRawHit.h.
View newest version in sPHENIX GitHub at line 26 of file MvtxRawHit.h
Referenced by MvtxRawHitv1::MvtxRawHitv1(), MvtxCombinedRawDataDecoder::process_event(), and DumpMvtxRawHitContainer::process_Node().
virtual uint16_t MvtxRawHit::get_row () const inline virtual
Reimplemented in MvtxRawHitv1.
Definition at line 35 of file MvtxRawHit.h.
View newest version in sPHENIX GitHub at line 35 of file MvtxRawHit.h
Referenced by MvtxRawHitv1::MvtxRawHitv1(), MvtxCombinedRawDataDecoder::process_event(), and DumpMvtxRawHitContainer::process_Node().
virtual uint8_t MvtxRawHit::get_stave_id () const inline virtual
Reimplemented in MvtxRawHitv1.
Definition at line 29 of file MvtxRawHit.h.
View newest version in sPHENIX GitHub at line 29 of file MvtxRawHit.h
Referenced by MvtxRawHitv1::MvtxRawHitv1(), MvtxCombinedRawDataDecoder::process_event(), and DumpMvtxRawHitContainer::process_Node().
virtual uint32_t MvtxRawHit::get_strobe_bc () const inline virtual
Reimplemented in MvtxRawHitv1.
Definition at line 20 of file MvtxRawHit.h.
View newest version in sPHENIX GitHub at line 20 of file MvtxRawHit.h
Referenced by MvtxRawHitv1::MvtxRawHitv1(), and DumpMvtxRawHitContainer::process_Node().
virtual void MvtxRawHit::set_bco (const uint64_t) inline virtual
Reimplemented in MvtxRawHitv1.
Definition at line 18 of file MvtxRawHit.h.
View newest version in sPHENIX GitHub at line 18 of file MvtxRawHit.h
Referenced by SingleMvtxPoolInput::FillPool().
virtual void MvtxRawHit::set_chip_bc (const uint32_t) inline virtual
Reimplemented in MvtxRawHitv1.
Definition at line 24 of file MvtxRawHit.h.
View newest version in sPHENIX GitHub at line 24 of file MvtxRawHit.h
Referenced by SingleMvtxPoolInput::FillPool().
virtual void MvtxRawHit::set_chip_id (uint8_t) inline virtual
Reimplemented in MvtxRawHitv1.
Definition at line 33 of file MvtxRawHit.h.
View newest version in sPHENIX GitHub at line 33 of file MvtxRawHit.h
Referenced by SingleMvtxPoolInput::FillPool().
virtual void MvtxRawHit::set_col (uint16_t) inline virtual
Reimplemented in MvtxRawHitv1.
Definition at line 39 of file MvtxRawHit.h.
View newest version in sPHENIX GitHub at line 39 of file MvtxRawHit.h
Referenced by SingleMvtxPoolInput::FillPool().
virtual void MvtxRawHit::set_layer_id (uint8_t) inline virtual
Reimplemented in MvtxRawHitv1.
Definition at line 27 of file MvtxRawHit.h.
View newest version in sPHENIX GitHub at line 27 of file MvtxRawHit.h
Referenced by SingleMvtxPoolInput::FillPool().
virtual void MvtxRawHit::set_row (uint16_t) inline virtual
Reimplemented in MvtxRawHitv1.
Definition at line 36 of file MvtxRawHit.h.
View newest version in sPHENIX GitHub at line 36 of file MvtxRawHit.h
Referenced by SingleMvtxPoolInput::FillPool().
virtual void MvtxRawHit::set_stave_id (uint8_t) inline virtual
Reimplemented in MvtxRawHitv1.
Definition at line 30 of file MvtxRawHit.h.
View newest version in sPHENIX GitHub at line 30 of file MvtxRawHit.h
Referenced by SingleMvtxPoolInput::FillPool().
virtual void MvtxRawHit::set_strobe_bc (const uint32_t) inline virtual
Reimplemented in MvtxRawHitv1.
Definition at line 21 of file MvtxRawHit.h.
View newest version in sPHENIX GitHub at line 21 of file MvtxRawHit.h
Referenced by SingleMvtxPoolInput::FillPool().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/framework/ffarawobjects/MvtxRawHit.h