Analysis Software: Acts::Svg::LayerConverter Namespace Reference
Acts::Svg::LayerConverter Namespace Reference
Classes
struct Options
A nested options class for the layer conversion.
Enumerations
enum Sheets { eModuleInfo = 0, eGridInfo = 1, eCrossSectionXY = 2, eCrossSectionZR = 3 }
The enumeration for sheets.
Functions
std::vector< actsvg::svg::object > convert (const GeometryContext &gctx, const Layer &layer, const Options &cOptions)
Enumeration Type Documentation
enum Acts::Svg::LayerConverter::Sheets
The enumeration for sheets.
Enumerator:
eModuleInfo
eGridInfo
eCrossSectionXY
eCrossSectionZR
Definition at line 34 of file LayerSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 34 of file LayerSvgConverter.hpp
Function Documentation
std::vector< actsvg::svg::object > Acts::Svg::LayerConverter::convert (const GeometryContext & gctx, const Layer & layer, const Options & cOptions)
Write/create the layer sheets for a given layer
Parameters
gctx the geometry context
layer the layer to be displayed
cOptions the conversion objects
Returns
a vector of svg objects
Convert the surface array into proto surfaces and a grid structure
Definition at line 18 of file LayerSvgConverter.cpp.
View newest version in sPHENIX GitHub at line 18 of file LayerSvgConverter.cpp
References Acts::Svg::DetectorConverter::convert(), Acts::Surface::Disc, grid(), Acts::Svg::LayerConverter::Options::gridInfo, Acts::Svg::LayerConverter::Options::moduleInfo, Acts::Svg::LayerConverter::Options::name, Acts::Layer::surfaceArray(), Acts::Layer::surfaceRepresentation(), Acts::Svg::SurfaceArrayConverter::Options::surfaceStyles, and Acts::Svg::LayerConverter::Options::surfaceStyles.
Referenced by BOOST_AUTO_TEST_CASE().