Analysis Software: QAG4SimulationMvtx Class Reference
QAG4SimulationMvtx Class Reference
#include <coresoftware/blob/master/offline/QA/modules/QAG4SimulationMvtx.h>
Public Member Functions
QAG4SimulationMvtx (const std::string &name="QAG4SimulationMvtx")
constructor
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
using G4HitSet = std::set< PHG4Hit * >
Private Member Functions
std::string get_histo_prefix () const
common prefix for QA histograms
int load_nodes (PHCompositeNode *)
load nodes
void evaluate_clusters ()
evaluate clusters
G4HitSet find_g4hits (TrkrDefs::cluskey) const
Private Attributes
bool m_initialized = false
true if histograms are initialized
TrkrClusterContainer * m_cluster_map = nullptr
cluster map
TrkrClusterHitAssoc * m_cluster_hit_map = nullptr
clusters to hit association
TrkrHitTruthAssoc * m_hit_truth_map = nullptr
hit to g4hit association
ActsGeometry * m_tGeometry = nullptr
Acts tracking geometry for surface lookup.
PHG4HitContainer * m_g4hits_mvtx = nullptr
g4 hits
std::set< int > m_layers
list of relevant layers
ClusterErrorPara _ClusErrPara
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 21 of file QAG4SimulationMvtx.h.
View newest version in sPHENIX GitHub at line 21 of file QAG4SimulationMvtx.h
Member Typedef Documentation
using QAG4SimulationMvtx::G4HitSet = std::set<PHG4Hit*> private
Definition at line 41 of file QAG4SimulationMvtx.h.
View newest version in sPHENIX GitHub at line 41 of file QAG4SimulationMvtx.h
Constructor & Destructor Documentation
QAG4SimulationMvtx::QAG4SimulationMvtx (const std::string & name = "QAG4SimulationMvtx")
constructor
Definition at line 40 of file QAG4SimulationMvtx.cc.
View newest version in sPHENIX GitHub at line 40 of file QAG4SimulationMvtx.cc
Member Function Documentation
void QAG4SimulationMvtx::evaluate_clusters () private
evaluate clusters
Definition at line 204 of file QAG4SimulationMvtx.cc.
View newest version in sPHENIX GitHub at line 204 of file QAG4SimulationMvtx.cc
References assert, QAG4Util::delta_phi(), distance(), INTTVtxZ::dphi, dz, find_g4hits(), get_histo_prefix(), QAG4Util::get_r(), TrkrClusterContainer::getClusters(), MvtxDefs::getCol(), ActsGeometry::getGlobalPosition(), QAHistManagerDef::getHistoManager(), TrkrClusterHitAssoc::getHits(), TrkrClusterContainer::getHitSetKeys(), TrkrDefs::getLayer(), MvtxDefs::getRow(), h, layer, m_cluster_hit_map, m_cluster_map, m_layers, m_tGeometry, TrkrDefs::mvtxId, MATSCAN::phibins, and value.
Referenced by process_event().
QAG4SimulationMvtx::G4HitSet QAG4SimulationMvtx::find_g4hits (TrkrDefs::cluskey cluster_key) const private
Definition at line 315 of file QAG4SimulationMvtx.cc.
View newest version in sPHENIX GitHub at line 315 of file QAG4SimulationMvtx.cc
References PHG4HitContainer::findHit(), TrkrHitTruthAssoc::getG4Hits(), TrkrClusterHitAssoc::getHits(), TrkrDefs::getHitSetKeyFromClusKey(), TrkrDefs::getTrkrId(), m_cluster_hit_map, m_g4hits_mvtx, m_hit_truth_map, TrkrDefs::mvtxId, and out.
Referenced by evaluate_clusters().
std::string QAG4SimulationMvtx::get_histo_prefix () const private
common prefix for QA histograms
Definition at line 156 of file QAG4SimulationMvtx.cc.
View newest version in sPHENIX GitHub at line 156 of file QAG4SimulationMvtx.cc
References Fun4AllBase::Name().
Referenced by evaluate_clusters(), and InitRun().
int QAG4SimulationMvtx::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 46 of file QAG4SimulationMvtx.cc.
View newest version in sPHENIX GitHub at line 46 of file QAG4SimulationMvtx.cc
References Fun4AllReturnCodes::ABORTRUN, assert, Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, get_histo_prefix(), QAHistManagerDef::getHistoManager(), h, layer, m_initialized, m_layers, PHWHERE, and Fun4AllBase::Verbosity().
int QAG4SimulationMvtx::load_nodes (PHCompositeNode * topNode) private
load nodes
Definition at line 162 of file QAG4SimulationMvtx.cc.
View newest version in sPHENIX GitHub at line 162 of file QAG4SimulationMvtx.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_cluster_hit_map, m_cluster_map, m_g4hits_mvtx, m_hit_truth_map, m_tGeometry, and PHWHERE.
Referenced by process_event().
int QAG4SimulationMvtx::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 145 of file QAG4SimulationMvtx.cc.
View newest version in sPHENIX GitHub at line 145 of file QAG4SimulationMvtx.cc
References evaluate_clusters(), Fun4AllReturnCodes::EVENT_OK, and load_nodes().
Member Data Documentation
ClusterErrorPara QAG4SimulationMvtx::_ClusErrPara private
Definition at line 65 of file QAG4SimulationMvtx.h.
View newest version in sPHENIX GitHub at line 65 of file QAG4SimulationMvtx.h
TrkrClusterHitAssoc* QAG4SimulationMvtx::m_cluster_hit_map = nullptr private
clusters to hit association
Definition at line 51 of file QAG4SimulationMvtx.h.
View newest version in sPHENIX GitHub at line 51 of file QAG4SimulationMvtx.h
Referenced by evaluate_clusters(), find_g4hits(), and load_nodes().
TrkrClusterContainer* QAG4SimulationMvtx::m_cluster_map = nullptr private
cluster map
Definition at line 48 of file QAG4SimulationMvtx.h.
View newest version in sPHENIX GitHub at line 48 of file QAG4SimulationMvtx.h
Referenced by evaluate_clusters(), and load_nodes().
PHG4HitContainer* QAG4SimulationMvtx::m_g4hits_mvtx = nullptr private
g4 hits
Definition at line 60 of file QAG4SimulationMvtx.h.
View newest version in sPHENIX GitHub at line 60 of file QAG4SimulationMvtx.h
Referenced by find_g4hits(), and load_nodes().
TrkrHitTruthAssoc* QAG4SimulationMvtx::m_hit_truth_map = nullptr private
hit to g4hit association
Definition at line 54 of file QAG4SimulationMvtx.h.
View newest version in sPHENIX GitHub at line 54 of file QAG4SimulationMvtx.h
Referenced by find_g4hits(), and load_nodes().
bool QAG4SimulationMvtx::m_initialized = false private
true if histograms are initialized
Definition at line 45 of file QAG4SimulationMvtx.h.
View newest version in sPHENIX GitHub at line 45 of file QAG4SimulationMvtx.h
Referenced by InitRun().
std::set<int> QAG4SimulationMvtx::m_layers private
list of relevant layers
Definition at line 64 of file QAG4SimulationMvtx.h.
View newest version in sPHENIX GitHub at line 64 of file QAG4SimulationMvtx.h
Referenced by evaluate_clusters(), and InitRun().
ActsGeometry* QAG4SimulationMvtx::m_tGeometry = nullptr private
Acts tracking geometry for surface lookup.
Definition at line 57 of file QAG4SimulationMvtx.h.
View newest version in sPHENIX GitHub at line 57 of file QAG4SimulationMvtx.h
Referenced by evaluate_clusters(), and load_nodes().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/QA/modules/QAG4SimulationMvtx.h
coresoftware/blob/master/offline/QA/modules/QAG4SimulationMvtx.cc