Analysis Software: DynamicNearestNeighbours Class Reference
DynamicNearestNeighbours Class Reference abstract
Public Member Functions
virtual int NearestNeighbourIndex (const int ii) const =0
virtual double NearestNeighbourDistance (const int ii) const =0
virtual bool Valid (const int index) const =0
virtual void RemoveAndAddPoints (const std::vector< int > &indices_to_remove, const std::vector< EtaPhi > &points_to_add, std::vector< int > &indices_added, std::vector< int > &indices_of_updated_neighbours)=0
void RemovePoint (const int index, std::vector< int > &indices_of_updated_neighbours)
void RemoveCombinedAddCombination (const int index1, const int index2, const EtaPhi &newpoint, int &index3, std::vector< int > &indices_of_updated_neighbours)
virtual ~DynamicNearestNeighbours ()
Detailed Description
Definition at line 181 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 181 of file fjcore.cc
Constructor & Destructor Documentation
virtual DynamicNearestNeighbours::~DynamicNearestNeighbours () inline virtual
Definition at line 215 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 215 of file fjcore.cc
Member Function Documentation
virtual double DynamicNearestNeighbours::NearestNeighbourDistance (const int ii) const pure virtual
Referenced by ClusterSequence::_add_ktdistance_to_map().
virtual int DynamicNearestNeighbours::NearestNeighbourIndex (const int ii) const pure virtual
Referenced by ClusterSequence::_add_ktdistance_to_map().
virtual void DynamicNearestNeighbours::RemoveAndAddPoints (const std::vector< int > & indices_to_remove, const std::vector< EtaPhi > & points_to_add, std::vector< int > & indices_added, std::vector< int > & indices_of_updated_neighbours) pure virtual
Referenced by RemoveCombinedAddCombination(), and RemovePoint().
void DynamicNearestNeighbours::RemoveCombinedAddCombination (const int index1, const int index2, const EtaPhi & newpoint, int & index3, std::vector< int > & indices_of_updated_neighbours) inline
Definition at line 199 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 199 of file fjcore.cc
References Acts::index1, Acts::index2, and RemoveAndAddPoints().
Referenced by ClusterSequence::_delaunay_cluster().
void DynamicNearestNeighbours::RemovePoint (const int index, std::vector< int > & indices_of_updated_neighbours) inline
Definition at line 190 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 190 of file fjcore.cc
References index, and RemoveAndAddPoints().
Referenced by ClusterSequence::_delaunay_cluster().
virtual bool DynamicNearestNeighbours::Valid (const int index) const pure virtual
Referenced by ClusterSequence::_delaunay_cluster().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/fjcore.cc