Analysis Software: Fun4AllStreamingInputManager Class Reference
Fun4AllStreamingInputManager Class Reference
#include <coresoftware/blob/master/offline/framework/fun4allraw/Fun4AllStreamingInputManager.h>
Classes
struct Gl1RawHitInfo
struct InttRawHitInfo
struct MicromegasRawHitInfo
struct MvtxRawHitInfo
struct TpcRawHitInfo
Public Types
enum enu_subsystem {
MVTX = 1, INTT = 2, TPC = 3, MICROMEGAS = 4,
GL1 = 5
}
Public Member Functions
Fun4AllStreamingInputManager (const std::string &name="DUMMY", const std::string &dstnodename="DST", const std::string &topnodename="TOP")
~Fun4AllStreamingInputManager () override
int fileopen (const std::string &) override
int fileclose () override
int run (const int nevents=0) override
void Print (const std::string &what="ALL") const override
int ResetEvent () override
int PushBackEvents (const int i) override
int GetSyncObject (SyncObject **mastersync) override
int SyncIt (const SyncObject *mastersync) override
int HasSyncObject () const override
std::string GetString (const std::string &what) const override
void registerStreamingInput (SingleStreamingInput *evtin, enu_subsystem)
int FillGl1 ()
int FillIntt ()
int FillMicromegas ()
int FillMvtx ()
int FillTpc ()
void AddGl1RawHit (uint64_t bclk, Gl1RawHit *hit)
void AddInttRawHit (uint64_t bclk, InttRawHit *hit)
void AddMicromegasRawHit (uint64_t, MicromegasRawHit *)
void AddMvtxFeeId (uint64_t bclk, uint16_t feeid)
void AddMvtxL1TrgBco (uint64_t bclk, uint64_t lv1Bco)
void AddMvtxRawHit (uint64_t bclk, MvtxRawHit *hit)
void AddTpcRawHit (uint64_t bclk, TpcRawHit *hit)
void SetInttBcoRange (const unsigned int i)
void SetInttNegativeBco (const unsigned int value)
void SetMicromegasBcoRange (const unsigned int i)
void SetMicromegasNegativeBco (const unsigned int value)
void SetMvtxBcoRange (const unsigned int i)
void SetMvtxNegativeBco (const unsigned int value)
void SetTpcBcoRange (const unsigned int i)
void SetTpcNegativeBco (const unsigned int value)
int FillInttPool ()
int FillMicromegasPool ()
int FillMvtxPool ()
int FillTpcPool ()
Public Member Functions inherited from Fun4AllInputManager
~Fun4AllInputManager () override
virtual int ReadInRunNode (PHCompositeNode *)
std::string FileName () const
void FileName (const std::string &fn)
virtual int BranchSelect (const std::string &, const int)
virtual int setBranches ()
virtual int skip (const int nevt)
virtual int NoSyncPushBackEvents (const int)
int AddFile (const std::string &filename)
int AddListFile (const std::string &filename, const int do_it=0)
int registerSubsystem (SubsysReco *subsystem)
virtual int RejectEvent ()
void Repeat (const int i=-1)
virtual void setSyncManager (Fun4AllSyncManager *master)
virtual int ResetFileList ()
virtual void SetRunNumber (const int runno)
virtual int RunNumber () const
void AddToFileOpened (const std::string &filename)
std::pair< std::list
< std::string >
::const_iterator, std::list
< std::string >
::const_iterator > FileOpenListBeginEnd ()
std::string InputNode ()
void InputNode (const std::string &innode)
std::string TopNodeName () const
bool FileListEmpty () const
virtual int IsOpen () const
virtual int SkipForThisManager (const int)
const std::list< std::string > GetFileList () const
const std::list< std::string > GetFileOpenedList () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
int m_RunNumber = 0
bool m_gl1_registered_flag {false}
bool m_intt_registered_flag {false}
bool m_micromegas_registered_flag {false}
bool m_mvtx_registered_flag {false}
bool m_tpc_registered_flag {false}
unsigned int m_intt_bco_range {0}
unsigned int m_intt_negative_bco {0}
unsigned int m_micromegas_bco_range {0}
unsigned int m_micromegas_negative_bco {0}
unsigned int m_mvtx_bco_range {0}
unsigned int m_mvtx_negative_bco {0}
unsigned int m_tpc_bco_range {0}
unsigned int m_tpc_negative_bco {0}
uint64_t m_RefBCO {0}
std::vector
< SingleStreamingInput * > m_Gl1InputVector
std::vector
< SingleStreamingInput * > m_InttInputVector
std::vector
< SingleStreamingInput * > m_MicromegasInputVector
std::vector
< SingleStreamingInput * > m_MvtxInputVector
std::vector
< SingleStreamingInput * > m_TpcInputVector
SyncObject * m_SyncObject = nullptr
PHCompositeNode * m_topNode = nullptr
std::map< uint64_t, Gl1RawHitInfo > m_Gl1RawHitMap
std::map< uint64_t,
InttRawHitInfo > m_InttRawHitMap
std::map< uint64_t,
MicromegasRawHitInfo > m_MicromegasRawHitMap
std::map< uint64_t,
MvtxRawHitInfo > m_MvtxRawHitMap
std::map< uint64_t, TpcRawHitInfo > m_TpcRawHitMap
std::map< int, std::map< int,
uint64_t > > m_InttPacketFeeBcoMap
Additional Inherited Members
Protected Member Functions inherited from Fun4AllInputManager
Fun4AllInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
void UpdateFileList ()
int OpenNextFile ()
void IsOpen (const int i)
Fun4AllSyncManager * MySyncManager ()
Detailed Description
Definition at line 21 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 21 of file Fun4AllStreamingInputManager.h
Member Enumeration Documentation
enum Fun4AllStreamingInputManager::enu_subsystem
Enumerator:
MVTX
INTT
TPC
MICROMEGAS
GL1
Definition at line 27 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 27 of file Fun4AllStreamingInputManager.h
Constructor & Destructor Documentation
Fun4AllStreamingInputManager::Fun4AllStreamingInputManager (const std::string & name = "DUMMY", const std::string & dstnodename = "DST", const std::string & topnodename = "TOP")
Definition at line 38 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 38 of file Fun4AllStreamingInputManager.cc
References Fun4AllServer::instance(), m_topNode, Fun4AllServer::topNode(), and Fun4AllInputManager::TopNodeName().
Fun4AllStreamingInputManager::~Fun4AllStreamingInputManager () override
Definition at line 47 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 47 of file Fun4AllStreamingInputManager.cc
References fileclose(), Fun4AllInputManager::IsOpen(), m_Gl1InputVector, m_InttInputVector, m_InttRawHitMap, m_MicromegasInputVector, m_MvtxInputVector, m_MvtxRawHitMap, m_SyncObject, m_TpcInputVector, and m_TpcRawHitMap.
Member Function Documentation
void Fun4AllStreamingInputManager::AddGl1RawHit (uint64_t bclk, Gl1RawHit * hit)
Definition at line 396 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 396 of file Fun4AllStreamingInputManager.cc
References m_Gl1RawHitMap, and Fun4AllBase::Verbosity().
Referenced by SingleGl1PoolInput::FillPool().
void Fun4AllStreamingInputManager::AddInttRawHit (uint64_t bclk, InttRawHit * hit)
Definition at line 436 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 436 of file Fun4AllStreamingInputManager.cc
References InttRawHit::get_fee(), InttRawHit::get_packetid(), m_InttPacketFeeBcoMap, m_InttRawHitMap, and Fun4AllBase::Verbosity().
Referenced by SingleInttPoolInput::FillPool().
void Fun4AllStreamingInputManager::AddMicromegasRawHit (uint64_t bclk, MicromegasRawHit * hit)
Definition at line 447 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 447 of file Fun4AllStreamingInputManager.cc
References m_MicromegasRawHitMap, and Fun4AllBase::Verbosity().
Referenced by SingleMicromegasPoolInput::FillPool().
void Fun4AllStreamingInputManager::AddMvtxFeeId (uint64_t bclk, uint16_t feeid)
Definition at line 416 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 416 of file Fun4AllStreamingInputManager.cc
References m_MvtxRawHitMap, and Fun4AllBase::Verbosity().
Referenced by SingleMvtxPoolInput::FillPool().
void Fun4AllStreamingInputManager::AddMvtxL1TrgBco (uint64_t bclk, uint64_t lv1Bco)
Definition at line 426 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 426 of file Fun4AllStreamingInputManager.cc
References m_MvtxRawHitMap, and Fun4AllBase::Verbosity().
Referenced by SingleMvtxPoolInput::FillPool().
void Fun4AllStreamingInputManager::AddMvtxRawHit (uint64_t bclk, MvtxRawHit * hit)
Definition at line 406 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 406 of file Fun4AllStreamingInputManager.cc
References m_MvtxRawHitMap, and Fun4AllBase::Verbosity().
Referenced by SingleMvtxPoolInput::FillPool().
void Fun4AllStreamingInputManager::AddTpcRawHit (uint64_t bclk, TpcRawHit * hit)
Definition at line 457 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 457 of file Fun4AllStreamingInputManager.cc
References m_TpcRawHitMap, and Fun4AllBase::Verbosity().
Referenced by SingleTpcPoolInput::FillPool().
int Fun4AllStreamingInputManager::fileclose () override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 219 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 219 of file Fun4AllStreamingInputManager.cc
Referenced by ~Fun4AllStreamingInputManager().
int Fun4AllStreamingInputManager::fileopen (const std::string &) inline override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 36 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 36 of file Fun4AllStreamingInputManager.h
int Fun4AllStreamingInputManager::FillGl1 ()
Definition at line 467 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 467 of file Fun4AllStreamingInputManager.cc
References PHObject::identify(), m_Gl1InputVector, m_Gl1RawHitMap, m_RefBCO, m_RunNumber, m_topNode, Gl1RawHit::set_bco(), Fun4AllInputManager::SetRunNumber(), and Fun4AllBase::Verbosity().
Referenced by run().
int Fun4AllStreamingInputManager::FillIntt ()
Definition at line 509 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 509 of file Fun4AllStreamingInputManager.cc
References InttRawHitContainer::AddHit(), FillInttPool(), m_intt_bco_range, m_intt_negative_bco, m_InttInputVector, m_InttRawHitMap, m_RefBCO, m_topNode, and Fun4AllBase::Verbosity().
Referenced by run().
int Fun4AllStreamingInputManager::FillInttPool ()
Definition at line 862 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 862 of file Fun4AllStreamingInputManager.cc
References m_InttInputVector, m_InttRawHitMap, m_RunNumber, Fun4AllInputManager::SetRunNumber(), and Fun4AllBase::Verbosity().
Referenced by FillIntt().
int Fun4AllStreamingInputManager::FillMicromegas ()
Definition at line 684 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 684 of file Fun4AllStreamingInputManager.cc
References container, FillMicromegasPool(), m_micromegas_bco_range, m_micromegas_negative_bco, m_MicromegasInputVector, m_MicromegasRawHitMap, m_RefBCO, m_topNode, and Fun4AllBase::Verbosity().
Referenced by run().
int Fun4AllStreamingInputManager::FillMicromegasPool ()
Definition at line 902 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 902 of file Fun4AllStreamingInputManager.cc
References m_MicromegasInputVector, m_MicromegasRawHitMap, m_RunNumber, Fun4AllInputManager::SetRunNumber(), and Fun4AllBase::Verbosity().
Referenced by FillMicromegas().
int Fun4AllStreamingInputManager::FillMvtx ()
Definition at line 583 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 583 of file Fun4AllStreamingInputManager.cc
References MvtxRawEvtHeader::AddFeeId(), MvtxRawHitContainer::AddHit(), MvtxRawEvtHeader::AddL1Trg(), FillMvtxPool(), m_mvtx_bco_range, m_MvtxInputVector, m_MvtxRawHitMap, m_RefBCO, m_topNode, and Fun4AllBase::Verbosity().
Referenced by run().
int Fun4AllStreamingInputManager::FillMvtxPool ()
Definition at line 922 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 922 of file Fun4AllStreamingInputManager.cc
References m_MvtxInputVector, m_MvtxRawHitMap, m_RunNumber, Fun4AllInputManager::SetRunNumber(), and Fun4AllBase::Verbosity().
Referenced by FillMvtx().
int Fun4AllStreamingInputManager::FillTpc ()
Definition at line 754 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 754 of file Fun4AllStreamingInputManager.cc
References TpcRawHitContainer::AddHit(), FillTpcPool(), m_RefBCO, m_topNode, m_tpc_bco_range, m_tpc_negative_bco, m_TpcInputVector, m_TpcRawHitMap, and Fun4AllBase::Verbosity().
Referenced by run().
int Fun4AllStreamingInputManager::FillTpcPool ()
Definition at line 882 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 882 of file Fun4AllStreamingInputManager.cc
References m_RunNumber, m_TpcInputVector, m_TpcRawHitMap, Fun4AllInputManager::SetRunNumber(), and Fun4AllBase::Verbosity().
Referenced by FillTpc().
std::string Fun4AllStreamingInputManager::GetString (const std::string & what) const override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 349 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 349 of file Fun4AllStreamingInputManager.cc
References PHWHERE.
int Fun4AllStreamingInputManager::GetSyncObject (SyncObject ** mastersync) override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 307 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 307 of file Fun4AllStreamingInputManager.cc
References assert, SyncObject::CloneMe(), m_SyncObject, and Fun4AllReturnCodes::SYNC_OK.
int Fun4AllStreamingInputManager::HasSyncObject () const inline override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 46 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 46 of file Fun4AllStreamingInputManager.h
void Fun4AllStreamingInputManager::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllInputManager.
Definition at line 224 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 224 of file Fun4AllStreamingInputManager.cc
References m_TpcRawHitMap, and Fun4AllInputManager::Print().
int Fun4AllStreamingInputManager::PushBackEvents (const int i) override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 252 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 252 of file Fun4AllStreamingInputManager.cc
void Fun4AllStreamingInputManager::registerStreamingInput (SingleStreamingInput * evtin, enu_subsystem system)
Definition at line 355 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 355 of file Fun4AllStreamingInputManager.cc
References SingleStreamingInput::ConfigureStreamingInputManager(), SingleStreamingInput::CreateDSTNode(), GL1, INTT, m_gl1_registered_flag, m_Gl1InputVector, m_intt_registered_flag, m_InttInputVector, m_micromegas_registered_flag, m_MicromegasInputVector, m_mvtx_registered_flag, m_MvtxInputVector, m_topNode, m_tpc_registered_flag, m_TpcInputVector, MICROMEGAS, MVTX, Fun4AllBase::Name(), SingleStreamingInput::StreamingInputManager(), TPC, and Fun4AllBase::Verbosity().
Referenced by Fun4All_Intt_Combiner(), Fun4All_Mvtx_Combiner(), Fun4All_Stream_Combiner(), and Fun4All_Tpc_Combiner().
int Fun4AllStreamingInputManager::ResetEvent () override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 242 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 242 of file Fun4AllStreamingInputManager.cc
int Fun4AllStreamingInputManager::run (const int nevents = 0) override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 113 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 113 of file Fun4AllStreamingInputManager.cc
References FillGl1(), FillIntt(), FillMicromegas(), FillMvtx(), FillTpc(), m_gl1_registered_flag, m_intt_registered_flag, m_micromegas_registered_flag, m_mvtx_registered_flag, and m_tpc_registered_flag.
void Fun4AllStreamingInputManager::SetInttBcoRange (const unsigned int i)
Definition at line 822 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 822 of file Fun4AllStreamingInputManager.cc
References m_intt_bco_range.
Referenced by SingleInttPoolInput::ConfigureStreamingInputManager().
void Fun4AllStreamingInputManager::SetInttNegativeBco (const unsigned int value)
Definition at line 827 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 827 of file Fun4AllStreamingInputManager.cc
References m_intt_negative_bco.
Referenced by SingleInttPoolInput::ConfigureStreamingInputManager().
void Fun4AllStreamingInputManager::SetMicromegasBcoRange (const unsigned int i)
Definition at line 832 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 832 of file Fun4AllStreamingInputManager.cc
References m_micromegas_bco_range.
Referenced by SingleMicromegasPoolInput::ConfigureStreamingInputManager().
void Fun4AllStreamingInputManager::SetMicromegasNegativeBco (const unsigned int value)
Definition at line 837 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 837 of file Fun4AllStreamingInputManager.cc
References m_micromegas_negative_bco.
Referenced by SingleMicromegasPoolInput::ConfigureStreamingInputManager().
void Fun4AllStreamingInputManager::SetMvtxBcoRange (const unsigned int i)
Definition at line 857 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 857 of file Fun4AllStreamingInputManager.cc
References m_mvtx_bco_range.
Referenced by SingleMvtxPoolInput::ConfigureStreamingInputManager().
void Fun4AllStreamingInputManager::SetMvtxNegativeBco (const unsigned int value)
Definition at line 842 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 842 of file Fun4AllStreamingInputManager.cc
References m_mvtx_negative_bco.
Referenced by SingleMvtxPoolInput::ConfigureStreamingInputManager().
void Fun4AllStreamingInputManager::SetTpcBcoRange (const unsigned int i)
Definition at line 847 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 847 of file Fun4AllStreamingInputManager.cc
References m_tpc_bco_range.
Referenced by SingleTpcPoolInput::ConfigureStreamingInputManager().
void Fun4AllStreamingInputManager::SetTpcNegativeBco (const unsigned int value)
Definition at line 852 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 852 of file Fun4AllStreamingInputManager.cc
References m_tpc_negative_bco.
Referenced by SingleTpcPoolInput::ConfigureStreamingInputManager().
int Fun4AllStreamingInputManager::SyncIt (const SyncObject * mastersync) override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 328 of file Fun4AllStreamingInputManager.cc.
View newest version in sPHENIX GitHub at line 328 of file Fun4AllStreamingInputManager.cc
References SyncObject::Different(), m_SyncObject, Fun4AllBase::Name(), PHWHERE, Fun4AllReturnCodes::SYNC_FAIL, and Fun4AllReturnCodes::SYNC_OK.
Member Data Documentation
bool Fun4AllStreamingInputManager::m_gl1_registered_flag {false} private
Definition at line 108 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 108 of file Fun4AllStreamingInputManager.h
Referenced by registerStreamingInput(), and run().
std::vector<SingleStreamingInput *> Fun4AllStreamingInputManager::m_Gl1InputVector private
Definition at line 123 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 123 of file Fun4AllStreamingInputManager.h
Referenced by FillGl1(), registerStreamingInput(), and ~Fun4AllStreamingInputManager().
std::map<uint64_t, Gl1RawHitInfo> Fun4AllStreamingInputManager::m_Gl1RawHitMap private
Definition at line 130 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 130 of file Fun4AllStreamingInputManager.h
Referenced by AddGl1RawHit(), and FillGl1().
unsigned int Fun4AllStreamingInputManager::m_intt_bco_range {0} private
Definition at line 113 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 113 of file Fun4AllStreamingInputManager.h
Referenced by FillIntt(), and SetInttBcoRange().
unsigned int Fun4AllStreamingInputManager::m_intt_negative_bco {0} private
Definition at line 114 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 114 of file Fun4AllStreamingInputManager.h
Referenced by FillIntt(), and SetInttNegativeBco().
bool Fun4AllStreamingInputManager::m_intt_registered_flag {false} private
Definition at line 109 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 109 of file Fun4AllStreamingInputManager.h
Referenced by registerStreamingInput(), and run().
std::vector<SingleStreamingInput *> Fun4AllStreamingInputManager::m_InttInputVector private
Definition at line 124 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 124 of file Fun4AllStreamingInputManager.h
Referenced by FillIntt(), FillInttPool(), registerStreamingInput(), and ~Fun4AllStreamingInputManager().
std::map<int, std::map<int, uint64_t> > Fun4AllStreamingInputManager::m_InttPacketFeeBcoMap private
Definition at line 135 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 135 of file Fun4AllStreamingInputManager.h
Referenced by AddInttRawHit().
std::map<uint64_t, InttRawHitInfo> Fun4AllStreamingInputManager::m_InttRawHitMap private
Definition at line 131 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 131 of file Fun4AllStreamingInputManager.h
Referenced by AddInttRawHit(), FillIntt(), FillInttPool(), and ~Fun4AllStreamingInputManager().
unsigned int Fun4AllStreamingInputManager::m_micromegas_bco_range {0} private
Definition at line 115 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 115 of file Fun4AllStreamingInputManager.h
Referenced by FillMicromegas(), and SetMicromegasBcoRange().
unsigned int Fun4AllStreamingInputManager::m_micromegas_negative_bco {0} private
Definition at line 116 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 116 of file Fun4AllStreamingInputManager.h
Referenced by FillMicromegas(), and SetMicromegasNegativeBco().
bool Fun4AllStreamingInputManager::m_micromegas_registered_flag {false} private
Definition at line 110 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 110 of file Fun4AllStreamingInputManager.h
Referenced by registerStreamingInput(), and run().
std::vector<SingleStreamingInput *> Fun4AllStreamingInputManager::m_MicromegasInputVector private
Definition at line 125 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 125 of file Fun4AllStreamingInputManager.h
Referenced by FillMicromegas(), FillMicromegasPool(), registerStreamingInput(), and ~Fun4AllStreamingInputManager().
std::map<uint64_t, MicromegasRawHitInfo> Fun4AllStreamingInputManager::m_MicromegasRawHitMap private
Definition at line 132 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 132 of file Fun4AllStreamingInputManager.h
Referenced by AddMicromegasRawHit(), FillMicromegas(), and FillMicromegasPool().
unsigned int Fun4AllStreamingInputManager::m_mvtx_bco_range {0} private
Definition at line 117 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 117 of file Fun4AllStreamingInputManager.h
Referenced by FillMvtx(), and SetMvtxBcoRange().
unsigned int Fun4AllStreamingInputManager::m_mvtx_negative_bco {0} private
Definition at line 118 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 118 of file Fun4AllStreamingInputManager.h
Referenced by SetMvtxNegativeBco().
bool Fun4AllStreamingInputManager::m_mvtx_registered_flag {false} private
Definition at line 111 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 111 of file Fun4AllStreamingInputManager.h
Referenced by registerStreamingInput(), and run().
std::vector<SingleStreamingInput *> Fun4AllStreamingInputManager::m_MvtxInputVector private
Definition at line 126 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 126 of file Fun4AllStreamingInputManager.h
Referenced by FillMvtx(), FillMvtxPool(), registerStreamingInput(), and ~Fun4AllStreamingInputManager().
std::map<uint64_t, MvtxRawHitInfo> Fun4AllStreamingInputManager::m_MvtxRawHitMap private
Definition at line 133 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 133 of file Fun4AllStreamingInputManager.h
Referenced by AddMvtxFeeId(), AddMvtxL1TrgBco(), AddMvtxRawHit(), FillMvtx(), FillMvtxPool(), and ~Fun4AllStreamingInputManager().
uint64_t Fun4AllStreamingInputManager::m_RefBCO {0} private
Definition at line 121 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 121 of file Fun4AllStreamingInputManager.h
Referenced by FillGl1(), FillIntt(), FillMicromegas(), FillMvtx(), and FillTpc().
int Fun4AllStreamingInputManager::m_RunNumber = 0 private
Definition at line 107 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 107 of file Fun4AllStreamingInputManager.h
Referenced by FillGl1(), FillInttPool(), FillMicromegasPool(), FillMvtxPool(), and FillTpcPool().
SyncObject* Fun4AllStreamingInputManager::m_SyncObject = nullptr private
Definition at line 128 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 128 of file Fun4AllStreamingInputManager.h
Referenced by GetSyncObject(), SyncIt(), and ~Fun4AllStreamingInputManager().
PHCompositeNode* Fun4AllStreamingInputManager::m_topNode = nullptr private
Definition at line 129 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 129 of file Fun4AllStreamingInputManager.h
Referenced by FillGl1(), FillIntt(), FillMicromegas(), FillMvtx(), FillTpc(), Fun4AllStreamingInputManager(), and registerStreamingInput().
unsigned int Fun4AllStreamingInputManager::m_tpc_bco_range {0} private
Definition at line 119 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 119 of file Fun4AllStreamingInputManager.h
Referenced by FillTpc(), and SetTpcBcoRange().
unsigned int Fun4AllStreamingInputManager::m_tpc_negative_bco {0} private
Definition at line 120 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 120 of file Fun4AllStreamingInputManager.h
Referenced by FillTpc(), and SetTpcNegativeBco().
bool Fun4AllStreamingInputManager::m_tpc_registered_flag {false} private
Definition at line 112 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 112 of file Fun4AllStreamingInputManager.h
Referenced by registerStreamingInput(), and run().
std::vector<SingleStreamingInput *> Fun4AllStreamingInputManager::m_TpcInputVector private
Definition at line 127 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 127 of file Fun4AllStreamingInputManager.h
Referenced by FillTpc(), FillTpcPool(), registerStreamingInput(), and ~Fun4AllStreamingInputManager().
std::map<uint64_t, TpcRawHitInfo> Fun4AllStreamingInputManager::m_TpcRawHitMap private
Definition at line 134 of file Fun4AllStreamingInputManager.h.
View newest version in sPHENIX GitHub at line 134 of file Fun4AllStreamingInputManager.h
Referenced by AddTpcRawHit(), FillTpc(), FillTpcPool(), Print(), and ~Fun4AllStreamingInputManager().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4allraw/Fun4AllStreamingInputManager.h
coresoftware/blob/master/offline/framework/fun4allraw/Fun4AllStreamingInputManager.cc