Analysis Software: Acts::ObjectMultiIntersection< object_t, representation_t > Class Template Reference
Acts::ObjectMultiIntersection< object_t, representation_t > Class Template Reference
class extensions to return also the object and a representation
#include <acts/blob/sPHENIX/Core/include/Acts/Utilities/Intersection.hpp>
Public Types
using SplitIntersections = boost::container::static_vector< ObjectIntersection< object_t, representation_t >, s_maximumNumberOfIntersections >
Public Member Functions
template<typename T = representation_t, std::enable_if_t< std::is_same< T, object_t >::value, int > = 0>
constexpr ObjectMultiIntersection (const MultiIntersection3D &intersections, const object_t *object)
constexpr ObjectMultiIntersection (const MultiIntersection3D &intersections, const object_t *object, const representation_t *representation)
constexpr ObjectIntersection
< object_t, representation_t > operator[] (std::uint8_t index) const
constexpr std::size_t size () const
constexpr const object_t * object () const
constexpr const representation_t * representation () const
constexpr SplitIntersections split () const
constexpr ObjectIntersection
< object_t, representation_t > closest () const
Private Attributes
MultiIntersection3D m_intersections
The intersections.
const object_t * m_object = nullptr
The object that was (tried to be) intersected.
const representation_t * m_representation = nullptr
The representation of this object.
Detailed Description
template<typename object_t, typename representation_t = object_t>
class Acts::ObjectMultiIntersection< object_t, representation_t >
class extensions to return also the object and a representation
Definition at line 211 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 211 of file Intersection.hpp
Member Typedef Documentation
template<typename object_t , typename representation_t = object_t> using Acts::ObjectMultiIntersection< object_t, representation_t >::SplitIntersections = boost::container::static_vector< ObjectIntersection<object_t, representation_t>, s_maximumNumberOfIntersections>
Definition at line 215 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 215 of file Intersection.hpp
Constructor & Destructor Documentation
template<typename object_t , typename representation_t = object_t> template<typename T = representation_t, std::enable_if_t< std::is_same< T, object_t >::value, int > = 0> constexpr Acts::ObjectMultiIntersection< object_t, representation_t >::ObjectMultiIntersection (const MultiIntersection3D & intersections, const object_t * object) inline
Object intersection - symmetric setup
Parameters
intersections are the intersections
object is the object to be instersected
Definition at line 223 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 223 of file Intersection.hpp
template<typename object_t , typename representation_t = object_t> constexpr Acts::ObjectMultiIntersection< object_t, representation_t >::ObjectMultiIntersection (const MultiIntersection3D & intersections, const object_t * object, const representation_t * representation) inline
Object intersection
Parameters
intersections are the intersections
object is the object to be instersected
representation is the object representation
Definition at line 234 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 234 of file Intersection.hpp
Member Function Documentation
template<typename object_t , typename representation_t = object_t> constexpr ObjectIntersection<object_t, representation_t> Acts::ObjectMultiIntersection< object_t, representation_t >::closest () const inline
Definition at line 262 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 262 of file Intersection.hpp
References Acts::ObjectMultiIntersection< object_t, representation_t >::split().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Layer::compatibleSurfaces(), Acts::CombinatorialKalmanFilter< propagator_t, traj_t >::Actor< source_link_accessor_t, parameters_t >::finalize(), Acts::detail::CorrectedFreeToBoundTransformer::operator()(), and ActsExamples::RootMaterialTrackWriter::writeT().
template<typename object_t , typename representation_t = object_t> constexpr const object_t* Acts::ObjectMultiIntersection< object_t, representation_t >::object () const inline
Definition at line 248 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 248 of file Intersection.hpp
References Acts::ObjectMultiIntersection< object_t, representation_t >::m_object.
template<typename object_t , typename representation_t = object_t> constexpr ObjectIntersection<object_t, representation_t> Acts::ObjectMultiIntersection< object_t, representation_t >::operator[] (std::uint8_t index) const inline
Definition at line 241 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 241 of file Intersection.hpp
References index, Acts::ObjectMultiIntersection< object_t, representation_t >::m_intersections, Acts::ObjectMultiIntersection< object_t, representation_t >::m_object, and Acts::ObjectMultiIntersection< object_t, representation_t >::m_representation.
template<typename object_t , typename representation_t = object_t> constexpr const representation_t* Acts::ObjectMultiIntersection< object_t, representation_t >::representation () const inline
Definition at line 250 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 250 of file Intersection.hpp
References Acts::ObjectMultiIntersection< object_t, representation_t >::m_representation.
template<typename object_t , typename representation_t = object_t> constexpr std::size_t Acts::ObjectMultiIntersection< object_t, representation_t >::size () const inline
Definition at line 246 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 246 of file Intersection.hpp
References Acts::ObjectMultiIntersection< object_t, representation_t >::m_intersections.
Referenced by Acts::ObjectMultiIntersection< object_t, representation_t >::split().
template<typename object_t , typename representation_t = object_t> constexpr SplitIntersections Acts::ObjectMultiIntersection< object_t, representation_t >::split () const inline
Definition at line 254 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 254 of file Intersection.hpp
References i, and Acts::ObjectMultiIntersection< object_t, representation_t >::size().
Referenced by Acts::ObjectMultiIntersection< object_t, representation_t >::closest(), Acts::TrackingVolume::compatibleBoundaries(), and Acts::Layer::compatibleSurfaces().
Member Data Documentation
template<typename object_t , typename representation_t = object_t> MultiIntersection3D Acts::ObjectMultiIntersection< object_t, representation_t >::m_intersections private
The intersections.
Definition at line 271 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 271 of file Intersection.hpp
Referenced by Acts::ObjectMultiIntersection< object_t, representation_t >::operator[](), and Acts::ObjectMultiIntersection< object_t, representation_t >::size().
template<typename object_t , typename representation_t = object_t> const object_t* Acts::ObjectMultiIntersection< object_t, representation_t >::m_object = nullptr private
The object that was (tried to be) intersected.
Definition at line 273 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 273 of file Intersection.hpp
Referenced by Acts::ObjectMultiIntersection< object_t, representation_t >::object(), and Acts::ObjectMultiIntersection< object_t, representation_t >::operator[]().
template<typename object_t , typename representation_t = object_t> const representation_t* Acts::ObjectMultiIntersection< object_t, representation_t >::m_representation = nullptr private
The representation of this object.
Definition at line 275 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 275 of file Intersection.hpp
Referenced by Acts::ObjectMultiIntersection< object_t, representation_t >::operator[](), and Acts::ObjectMultiIntersection< object_t, representation_t >::representation().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Utilities/Intersection.hpp