Analysis Software: TowerInfoContainerv1 Class Reference
TowerInfoContainerv1 Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/TowerInfoContainerv1.h>
Public Member Functions
TowerInfoContainerv1 (DETECTOR detec)
TowerInfoContainerv1 ()
PHObject * CloneMe () const override
Virtual copy constructor.
TowerInfoContainerv1 (const TowerInfoContainerv1 &)
~TowerInfoContainerv1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
TowerInfov1 * get_tower_at_channel (int pos) override
TowerInfov1 * get_tower_at_key (int pos) override
unsigned int encode_key (unsigned int towerIndex) override
unsigned int decode_key (unsigned int tower_key) override
size_t size () const override
DETECTOR get_detectorid () const override
Public Member Functions inherited from TowerInfoContainer
TowerInfoContainer ()=default
~TowerInfoContainer () override=default
virtual unsigned int encode_epd (unsigned int)
virtual unsigned int encode_hcal (unsigned int)
virtual unsigned int encode_emcal (unsigned int)
virtual unsigned int encode_mbd (unsigned int)
virtual unsigned int encode_zdc (unsigned int)
virtual unsigned int decode_epd (unsigned int)
virtual unsigned int decode_hcal (unsigned int)
virtual unsigned int decode_emcal (unsigned int)
virtual unsigned int decode_mbd (unsigned int)
virtual unsigned int decode_zdc (unsigned int)
virtual unsigned int getTowerPhiBin (unsigned int)
virtual unsigned int getTowerEtaBin (unsigned int)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
TClonesArray * _clones = nullptr
DETECTOR _detector = DETECTOR_INVALID
Private Member Functions
ClassDefOverride (TowerInfoContainerv1, 1)
Additional Inherited Members
Public Types inherited from TowerInfoContainer
enum DETECTOR {
EMCAL = 0, HCAL = 1, SEPD = 2, MBD = 3,
ZDC = 4, DETECTOR_INVALID = 9999
}
typedef std::map< unsigned int,
TowerInfo * > TowerMap
typedef TowerMap::const_iterator ConstIter
typedef TowerMap::iterator Iter
Detailed Description
Definition at line 11 of file TowerInfoContainerv1.h.
View newest version in sPHENIX GitHub at line 11 of file TowerInfoContainerv1.h
Constructor & Destructor Documentation
TowerInfoContainerv1::TowerInfoContainerv1 (DETECTOR detec)
Definition at line 12 of file TowerInfoContainerv1.cc.
View newest version in sPHENIX GitHub at line 12 of file TowerInfoContainerv1.cc
References _clones, _detector, i, Enable::MBD, CaloTowerDefs::SEPD, and RawTowerDefs::ZDC.
TowerInfoContainerv1::TowerInfoContainerv1 () inline
Definition at line 17 of file TowerInfoContainerv1.h.
View newest version in sPHENIX GitHub at line 17 of file TowerInfoContainerv1.h
Referenced by CloneMe().
TowerInfoContainerv1::TowerInfoContainerv1 (const TowerInfoContainerv1 & source)
Definition at line 52 of file TowerInfoContainerv1.cc.
View newest version in sPHENIX GitHub at line 52 of file TowerInfoContainerv1.cc
References _clones, _detector, get_detectorid(), i, and size().
TowerInfoContainerv1::~TowerInfoContainerv1 () override
Definition at line 47 of file TowerInfoContainerv1.cc.
View newest version in sPHENIX GitHub at line 47 of file TowerInfoContainerv1.cc
References _clones.
Member Function Documentation
TowerInfoContainerv1::ClassDefOverride (TowerInfoContainerv1 , 1) private
PHObject* TowerInfoContainerv1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 18 of file TowerInfoContainerv1.h.
View newest version in sPHENIX GitHub at line 18 of file TowerInfoContainerv1.h
References TowerInfoContainerv1().
unsigned int TowerInfoContainerv1::decode_key (unsigned int tower_key) override virtual
Reimplemented from TowerInfoContainer.
Definition at line 134 of file TowerInfoContainerv1.cc.
View newest version in sPHENIX GitHub at line 134 of file TowerInfoContainerv1.cc
References _detector, TowerInfoContainer::decode_emcal(), TowerInfoContainer::decode_epd(), TowerInfoContainer::decode_hcal(), TowerInfoContainer::decode_mbd(), TowerInfoContainer::decode_zdc(), index, Enable::MBD, CaloTowerDefs::SEPD, and RawTowerDefs::ZDC.
Referenced by get_tower_at_key().
unsigned int TowerInfoContainerv1::encode_key (unsigned int towerIndex) override virtual
Reimplemented from TowerInfoContainer.
Definition at line 108 of file TowerInfoContainerv1.cc.
View newest version in sPHENIX GitHub at line 108 of file TowerInfoContainerv1.cc
References _detector, TowerInfoContainer::encode_emcal(), TowerInfoContainer::encode_epd(), TowerInfoContainer::encode_hcal(), TowerInfoContainer::encode_mbd(), TowerInfoContainer::encode_zdc(), Enable::MBD, CaloTowerDefs::SEPD, and RawTowerDefs::ZDC.
Referenced by RawTowerCalibration::process_event().
DETECTOR TowerInfoContainerv1::get_detectorid () const inline override virtual
Reimplemented from TowerInfoContainer.
Definition at line 33 of file TowerInfoContainerv1.h.
View newest version in sPHENIX GitHub at line 33 of file TowerInfoContainerv1.h
References _detector.
Referenced by TowerInfoContainerv1().
TowerInfov1 * TowerInfoContainerv1::get_tower_at_channel (int pos) override virtual
Reimplemented from TowerInfoContainer.
Definition at line 97 of file TowerInfoContainerv1.cc.
View newest version in sPHENIX GitHub at line 97 of file TowerInfoContainerv1.cc
References _clones.
Referenced by RawTowerCalibration::process_event().
TowerInfov1 * TowerInfoContainerv1::get_tower_at_key (int pos) override virtual
Reimplemented from TowerInfoContainer.
Definition at line 102 of file TowerInfoContainerv1.cc.
View newest version in sPHENIX GitHub at line 102 of file TowerInfoContainerv1.cc
References _clones, decode_key(), and index.
void TowerInfoContainerv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from TowerInfoContainer.
Definition at line 66 of file TowerInfoContainerv1.cc.
View newest version in sPHENIX GitHub at line 66 of file TowerInfoContainerv1.cc
References size().
void TowerInfoContainerv1::Reset () override virtual
Clear Event.
Reimplemented from TowerInfoContainer.
Definition at line 71 of file TowerInfoContainerv1.cc.
View newest version in sPHENIX GitHub at line 71 of file TowerInfoContainerv1.cc
References _clones, assert, and i.
size_t TowerInfoContainerv1::size (void) const inline override virtual
Reimplemented from TowerInfoContainer.
Definition at line 32 of file TowerInfoContainerv1.h.
View newest version in sPHENIX GitHub at line 32 of file TowerInfoContainerv1.h
References _clones.
Referenced by identify(), RawTowerCalibration::process_event(), and TowerInfoContainerv1().
Member Data Documentation
TClonesArray* TowerInfoContainerv1::_clones = nullptr protected
Definition at line 36 of file TowerInfoContainerv1.h.
View newest version in sPHENIX GitHub at line 36 of file TowerInfoContainerv1.h
Referenced by get_tower_at_channel(), get_tower_at_key(), Reset(), size(), TowerInfoContainerv1(), and ~TowerInfoContainerv1().
DETECTOR TowerInfoContainerv1::_detector = DETECTOR_INVALID protected
Definition at line 37 of file TowerInfoContainerv1.h.
View newest version in sPHENIX GitHub at line 37 of file TowerInfoContainerv1.h
Referenced by decode_key(), encode_key(), get_detectorid(), and TowerInfoContainerv1().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/TowerInfoContainerv1.h
coresoftware/blob/master/offline/packages/CaloBase/TowerInfoContainerv1.cc