var namespacecl =
[
    [ "detail", "da/d3e/namespacecl_1_1detail.html", "da/d3e/namespacecl_1_1detail" ],
    [ "sycl", "d4/df1/namespacecl_1_1sycl.html", null ],
    [ "string", "d7/daa/classcl_1_1string.html", "d7/daa/classcl_1_1string" ],
    [ "vector", "d6/d2c/classcl_1_1vector.html", "d6/d2c/classcl_1_1vector" ],
    [ "size_t", "d2/d1b/structcl_1_1size__t.html", null ],
    [ "ImageFormat", "d1/d40/structcl_1_1ImageFormat.html", "d1/d40/structcl_1_1ImageFormat" ],
    [ "Device", "d5/ddd/classcl_1_1Device.html", "d5/ddd/classcl_1_1Device" ],
    [ "Platform", "d8/d7f/classcl_1_1Platform.html", "d8/d7f/classcl_1_1Platform" ],
    [ "Context", "d1/d80/classcl_1_1Context.html", "d1/d80/classcl_1_1Context" ],
    [ "Event", "de/d39/classcl_1_1Event.html", "de/d39/classcl_1_1Event" ],
    [ "Memory", "dc/de6/classcl_1_1Memory.html", "dc/de6/classcl_1_1Memory" ],
    [ "Buffer", "dd/de2/classcl_1_1Buffer.html", "dd/de2/classcl_1_1Buffer" ],
    [ "BufferGL", "d8/d40/classcl_1_1BufferGL.html", "d8/d40/classcl_1_1BufferGL" ],
    [ "BufferRenderGL", "db/d04/classcl_1_1BufferRenderGL.html", "db/d04/classcl_1_1BufferRenderGL" ],
    [ "Image", "de/daf/classcl_1_1Image.html", "de/daf/classcl_1_1Image" ],
    [ "Image2D", "d4/d26/classcl_1_1Image2D.html", "d4/d26/classcl_1_1Image2D" ],
    [ "Image2DGL", "d1/d23/classcl_1_1Image2DGL.html", "d1/d23/classcl_1_1Image2DGL" ],
    [ "Image3D", "dc/d1b/classcl_1_1Image3D.html", "dc/d1b/classcl_1_1Image3D" ],
    [ "Image3DGL", "d4/daf/classcl_1_1Image3DGL.html", "d4/daf/classcl_1_1Image3DGL" ],
    [ "Sampler", "d0/dca/classcl_1_1Sampler.html", "d0/dca/classcl_1_1Sampler" ],
    [ "NDRange", "dc/d37/classcl_1_1NDRange.html", "dc/d37/classcl_1_1NDRange" ],
    [ "LocalSpaceArg", "d2/d00/structcl_1_1LocalSpaceArg.html", "d2/d00/structcl_1_1LocalSpaceArg" ],
    [ "Kernel", "d4/db4/classcl_1_1Kernel.html", "d4/db4/classcl_1_1Kernel" ],
    [ "Program", "dd/d5e/classcl_1_1Program.html", "dd/d5e/classcl_1_1Program" ],
    [ "CommandQueue", "db/df8/classcl_1_1CommandQueue.html", "db/df8/classcl_1_1CommandQueue" ],
    [ "KernelFunctor", "d1/df8/classcl_1_1KernelFunctor.html", "d1/df8/classcl_1_1KernelFunctor" ]
];