Analysis Software: StreamingCheck Class Reference
StreamingCheck Class Reference
#include <coresoftware/blob/master/offline/framework/ffarawmodules/StreamingCheck.h>
Public Member Functions
StreamingCheck (const std::string &name="StreamingCheck")
~StreamingCheck () override
int Init (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
void SetTpcBcoRange (const unsigned int i)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
unsigned int tpc_bcorange {0}
std::set< uint64_t > bclk_seen
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 14 of file StreamingCheck.h.
View newest version in sPHENIX GitHub at line 14 of file StreamingCheck.h
Constructor & Destructor Documentation
StreamingCheck::StreamingCheck (const std::string & name = "StreamingCheck")
Definition at line 31 of file StreamingCheck.cc.
View newest version in sPHENIX GitHub at line 31 of file StreamingCheck.cc
StreamingCheck::~StreamingCheck () inline override
Definition at line 19 of file StreamingCheck.h.
View newest version in sPHENIX GitHub at line 19 of file StreamingCheck.h
Member Function Documentation
int StreamingCheck::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 37 of file StreamingCheck.cc.
View newest version in sPHENIX GitHub at line 37 of file StreamingCheck.cc
References Fun4AllReturnCodes::EVENT_OK.
int StreamingCheck::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 43 of file StreamingCheck.cc.
View newest version in sPHENIX GitHub at line 43 of file StreamingCheck.cc
References Fun4AllReturnCodes::EVENT_OK, InttRawHit::get_bco(), Gl1RawHit::get_bco(), TpcRawHit::get_gtm_bco(), InttRawHitContainer::get_hit(), TpcRawHitContainer::get_hit(), InttRawHitContainer::get_nhits(), TpcRawHitContainer::get_nhits(), i, PHObject::identify(), tpc_bcorange, and Fun4AllBase::Verbosity().
void StreamingCheck::SetTpcBcoRange (const unsigned int i) inline
Definition at line 27 of file StreamingCheck.h.
View newest version in sPHENIX GitHub at line 27 of file StreamingCheck.h
References i, and tpc_bcorange.
Member Data Documentation
std::set<uint64_t> StreamingCheck::bclk_seen private
Definition at line 30 of file StreamingCheck.h.
View newest version in sPHENIX GitHub at line 30 of file StreamingCheck.h
unsigned int StreamingCheck::tpc_bcorange {0} private
Definition at line 29 of file StreamingCheck.h.
View newest version in sPHENIX GitHub at line 29 of file StreamingCheck.h
Referenced by process_event(), and SetTpcBcoRange().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/ffarawmodules/StreamingCheck.h
coresoftware/blob/master/offline/framework/ffarawmodules/StreamingCheck.cc