Analysis Software: ActsExamples::TrkrClusterFittingAlgorithm Class Reference
ActsExamples::TrkrClusterFittingAlgorithm Class Reference
#include <acts/blob/sPHENIX/Examples/Algorithms/Fitting/include/ActsExamples/Fitting/TrkrClusterFittingAlgorithm.hpp>
Classes
struct Config
Public Types
using FitterResult = Acts::Result< Acts::KalmanFitterResult< ActsExamples::TrkrClusterSourceLink >>
Construct some aliases to be used for the fitting results.
using FitterFunction = std::function< FitterResult(const std::vector< ActsExamples::TrkrClusterSourceLink > &, const TrackParameters &, const Acts::KalmanFitterOptions< Acts::VoidOutlierFinder > &)>
using DirectedFitterFunction = std::function< FitterResult(const std::vector< ActsExamples::TrkrClusterSourceLink > &, const TrackParameters &, const Acts::KalmanFitterOptions< Acts::VoidOutlierFinder > &, const std::vector< const Acts::Surface * > &)>
Public Member Functions
TrkrClusterFittingAlgorithm (Config cfg, Acts::Logging::Level lvl)
Constructor.
Public Member Functions inherited from ActsExamples::BareAlgorithm
BareAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const finaloverride
The algorithm name.
virtual ProcessCode execute (const AlgorithmContext &context) const override=0
Static Public Member Functions
static FitterFunction makeFitterFunction (std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, Options::BFieldVariant magneticField)
Create fitter function.
static DirectedFitterFunction makeFitterFunction (Options::BFieldVariant magneticField)
Private Attributes
Config m_cfg
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::BareAlgorithm
const Acts::Logger & logger () const
Detailed Description
This class contains the information required to run the Kalman fitter with the TrkrClusterSourceLinks. Based on ActsExamples::FittingAlgorithm
Definition at line 36 of file TrkrClusterFittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 36 of file TrkrClusterFittingAlgorithm.hpp
Member Typedef Documentation
using ActsExamples::TrkrClusterFittingAlgorithm::DirectedFitterFunction = std::function<FitterResult(const std::vector<ActsExamples::TrkrClusterSourceLink>&, const TrackParameters&, const Acts::KalmanFitterOptions<Acts::VoidOutlierFinder>&, const std::vector<const Acts::Surface*>&)>
Definition at line 53 of file TrkrClusterFittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 53 of file TrkrClusterFittingAlgorithm.hpp
using ActsExamples::TrkrClusterFittingAlgorithm::FitterFunction = std::function<FitterResult(const std::vector<ActsExamples::TrkrClusterSourceLink>&, const TrackParameters&, const Acts::KalmanFitterOptions<Acts::VoidOutlierFinder>&)>
Definition at line 46 of file TrkrClusterFittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 46 of file TrkrClusterFittingAlgorithm.hpp
using ActsExamples::TrkrClusterFittingAlgorithm::FitterResult = Acts::Result<Acts::KalmanFitterResult<ActsExamples::TrkrClusterSourceLink>>
Construct some aliases to be used for the fitting results.
Definition at line 41 of file TrkrClusterFittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 41 of file TrkrClusterFittingAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::TrkrClusterFittingAlgorithm::TrkrClusterFittingAlgorithm (Config cfg, Acts::Logging::Level lvl)
Constructor.
Member Function Documentation
ActsExamples::TrkrClusterFittingAlgorithm::FitterFunction ActsExamples::TrkrClusterFittingAlgorithm::makeFitterFunction (std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, Options::BFieldVariant magneticField) static
Create fitter function.
Function that actually makes the fitting function to be used
Return a new instance of the fitter
Construct some aliases for the components below
Make the components for the fitter
Build the fitter function
Definition at line 68 of file TrkrClusterFittingAlgorithmFitterFunction.cpp.
View newest version in sPHENIX GitHub at line 68 of file TrkrClusterFittingAlgorithmFitterFunction.cpp
References testing::internal::move(), Acts::Test::navigator, and propagation_timing::stepper.
Referenced by PHActsTrkFitter::InitRun().
ActsExamples::TrkrClusterFittingAlgorithm::DirectedFitterFunction ActsExamples::TrkrClusterFittingAlgorithm::makeFitterFunction (Options::BFieldVariant magneticField) static
Return a new instance of the fitter
Construct some aliases for the components below
Make the components for the fitter
Build the fitter function
Definition at line 104 of file TrkrClusterFittingAlgorithmFitterFunction.cpp.
View newest version in sPHENIX GitHub at line 104 of file TrkrClusterFittingAlgorithmFitterFunction.cpp
References testing::internal::move(), Acts::Test::navigator, and propagation_timing::stepper.
Member Data Documentation
Config ActsExamples::TrkrClusterFittingAlgorithm::m_cfg private
Definition at line 75 of file TrkrClusterFittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 75 of file TrkrClusterFittingAlgorithm.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Fitting/include/ActsExamples/Fitting/TrkrClusterFittingAlgorithm.hpp
acts/blob/sPHENIX/Examples/Algorithms/Fitting/src/TrkrClusterFittingAlgorithmFitterFunction.cpp