Analysis Software: acts/blob/sPHENIX/Core/src/Surfaces/EllipseBounds.cpp File Reference
EllipseBounds.cpp File Reference
#include "Acts/Surfaces/EllipseBounds.hpp"
#include "Acts/Definitions/TrackParametrization.hpp"
#include "Acts/Surfaces/detail/VerticesHelper.hpp"
#include "Acts/Utilities/VectorHelpers.hpp"
#include <iomanip>
#include <iostream>
Functions
static double square (double x)
Function Documentation
static double square (double x) inline static
Definition at line 25 of file EllipseBounds.cpp.
View newest version in sPHENIX GitHub at line 25 of file EllipseBounds.cpp
References ambiguity_solver_full_chain::x.
Referenced by TrackFitUtils::addClustersOnLine(), ALICEKF::ALICEKalmanFilter(), PHTruthSiliconAssociation::buildTrackSeed(), PHTruthTrackSeeding::buildTrackSeed(), TrackFitUtils::circle_circle_intersection(), TrackFitUtils::circle_fit_by_taubin(), TpcSpaceChargeReconstructionHelper::extrapolate_phi2(), TpcSpaceChargeReconstructionHelper::extrapolate_z(), TrackResiduals::fillClusterTree(), PHActsKDTreeSeeding::findInttMatches(), PHActsSiliconSeeding::findInttMatches(), TrackSeed_v1::findRoot(), ClusterErrorPara::get_cluster_error(), ClusterErrorPara::get_clusterv5_modified_error(), TpcDistortionCorrection::get_corrected_position(), ClusterErrorPara::get_fix_tpc_cluster_error(), SvtxTrackState_v1::get_phi_error(), SvtxTrackState_v2::get_phi_error(), SvtxTrackState_v1::get_rphi_error(), SvtxTrackState_v2::get_rphi_error(), ClusterErrorPara::get_si_cluster_error(), ClusterErrorPara::get_simple_cluster_error(), PHCosmicsTrkFitter::getCharge(), ALICEKF::GetCircleClusterResiduals(), TrackFitUtils::getCircleClusterResiduals(), TrackSeedTrackMapConverter::getCosmicCharge(), ALICEKF::GetLineClusterResiduals(), TrackFitUtils::getLineClusterResiduals(), TpcPrototypeCluster::getPhiError(), TrkrClusterv1::getPhiError(), TrkrClusterv2::getPhiError(), Acts::EllipseBounds::inside(), TrackFitUtils::line_fit(), TrackSeed_v1::lineFit(), PHGenFitTrkFitter::MakeSvtxTrack(), PHActsKDTreeSeeding::matchInttClusters(), PHActsSiliconSeeding::matchInttClusters(), PHG4TpcPadPlaneReadout::populate_zigzag_phibins(), PHSiliconTruthTrackSeeding::Process(), MicromegasClusterizer::process_event(), TrackResiduals::process_event(), PHG4TpcElectronDrift::process_event(), PHTpcDeltaZCorrection::process_track(), TpcDirectLaserReconstruction::process_track(), TpcSpaceChargeReconstruction::process_track(), PHTpcResiduals::processTrack(), PHSimpleKFProp::PropagateTrack(), PHCosmicSeeder::recalculateSeedLineParameters(), PHGenFitTrkFitter::ReFitTrack(), PHCosmicTrackMerger::removeOutliers(), ActsTransformations::rotateActsCovToSvtxTrack(), and ActsTransformations::rotateSvtxTrackCovToActs().