Analysis Software: Jetscape::PartonShower Class Reference
Jetscape::PartonShower Class Reference
#include <JETSCAPE/blob/main/src/framework/PartonShower.h>
Public Member Functions
PartonShower ()
virtual ~PartonShower ()
node new_vertex (shared_ptr< Vertex > v)
int new_parton (node s, node t, shared_ptr< Parton > p)
shared_ptr< Vertex > GetVertex (node n)
shared_ptr< Parton > GetParton (edge e)
shared_ptr< Parton > GetPartonAt (int n)
shared_ptr< Vertex > GetVertexAt (int n)
node GetNodeAt (int n)
edge GetEdgeAt (int n)
int GetNumberOfParents (int n)
int GetNumberOfChilds (int n)
vector< shared_ptr< Parton > > GetFinalPartons ()
vector< fjcore::PseudoJet > GetFinalPartonsForFastJet ()
int GetNumberOfPartons () const
int GetNumberOfVertices () const
void save_node_info_handler (ostream *o, node n) const
void save_edge_info_handler (ostream *o, edge n) const
void load_edge_info_handler (edge e, GML_pair *read)
void load_node_info_handler (node n, GML_pair *read)
void pre_clear_handler ()
void PrintVertices ()
void PrintPartons ()
void PrintNodes (bool verbose=true)
void PrintEdges (bool verbose=true)
void SaveAsGML (string fName)
void SaveAsGV (string fName)
void SaveAsGraphML (string fName)
Public Member Functions inherited from graph
graph ()
graph (const graph &G)
graph (const graph &G, const list< node > &nodes)
graph (const graph &G, list< node >::const_iterator it, list< node >::const_iterator end)
virtual ~graph ()
void make_directed ()
void make_undirected ()
bool is_directed () const
bool is_undirected () const
bool is_bidirected (edge_map< edge > &rev) const
bool is_connected () const
bool is_acyclic () const
int number_of_nodes () const
int number_of_edges () const
node center () const
virtual node new_node ()
virtual edge new_edge (node s, node t)
virtual edge new_edge (const list< node > &sources, const list< node > &targets)
void del_node (node n)
void del_all_nodes ()
void del_edge (edge e)
void del_all_edges ()
void clear ()
node_iterator nodes_begin () const
node_iterator nodes_end () const
edge_iterator edges_begin () const
edge_iterator edges_end () const
list< node > all_nodes () const
list< edge > all_edges () const
node choose_node () const
void hide_edge (edge e)
void restore_edge (edge e)
list< edge > hide_node (node n)
void restore_node (node n)
void induced_subgraph (list< node > &subgraph_nodes)
void restore_graph ()
list< edge > insert_reverse_edges ()
GML_error load (const string &filename, bool preserve_ids=false)
GML_error load (const char *filename, bool preserve_ids=false)
int save (const char *filename) const
void save (ostream *file=&cout) const
virtual void pre_new_node_handler ()
virtual void post_new_node_handler (node n)
virtual void pre_del_node_handler (node n)
virtual void post_del_node_handler ()
virtual void pre_hide_node_handler (node n)
virtual void post_hide_node_handler (node n)
virtual void pre_restore_node_handler (node n)
virtual void post_restore_node_handler (node n)
virtual void pre_new_edge_handler (node s, node t)
virtual void post_new_edge_handler (edge e)
virtual void pre_del_edge_handler (edge e)
virtual void post_del_edge_handler (node, node)
virtual void pre_hide_edge_handler (edge e)
virtual void post_hide_edge_handler (edge e)
virtual void pre_restore_edge_handler (edge e)
virtual void post_restore_edge_handler (edge e)
virtual void post_clear_handler ()
virtual void pre_make_directed_handler ()
virtual void post_make_directed_handler ()
virtual void pre_make_undirected_handler ()
virtual void post_make_undirected_handler ()
virtual void pre_graph_save_handler (ostream *os) const
virtual void save_graph_info_handler (ostream *) const
virtual void after_graph_save_handler (ostream *) const
virtual void top_level_key_handler (GML_pair *list)
virtual void load_graph_info_handler (GML_pair *list)
int number_of_ids (node) const
int number_of_ids (edge) const
Private Attributes
node_map< shared_ptr< Vertex > > vMap
edge_map< shared_ptr< Parton > > pMap
vector< shared_ptr< Parton > > pFinal
Additional Inherited Members
Public Types inherited from graph
typedef list< node >
::const_iterator node_iterator
typedef list< edge >
::const_iterator edge_iterator
Detailed Description
Definition at line 37 of file PartonShower.h.
View newest version in sPHENIX GitHub at line 37 of file PartonShower.h
Constructor & Destructor Documentation
Jetscape::PartonShower::PartonShower ()
Definition at line 30 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 30 of file PartonShower.cc
References VERBOSESHOWER.
Jetscape::PartonShower::~PartonShower () virtual
Definition at line 186 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 186 of file PartonShower.cc
References pFinal, and VERBOSESHOWER.
Member Function Documentation
edge Jetscape::PartonShower::GetEdgeAt (int n)
Definition at line 158 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 158 of file PartonShower.cc
References graph::edges_begin().
Referenced by GetNumberOfChilds(), and GetNumberOfParents().
vector< shared_ptr< Parton > > Jetscape::PartonShower::GetFinalPartons ()
Definition at line 119 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 119 of file PartonShower.cc
References graph::edges_begin(), graph::edges_end(), pFinal, and pMap.
Referenced by GetFinalPartonsForFastJet(), and Jetscape::JetScapeWriterFinalStateStream< T >::Write().
vector< fjcore::PseudoJet > Jetscape::PartonShower::GetFinalPartonsForFastJet ()
Definition at line 138 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 138 of file PartonShower.cc
References GetFinalPartons(), and i.
node Jetscape::PartonShower::GetNodeAt (int n)
Definition at line 165 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 165 of file PartonShower.cc
References graph::nodes_begin().
int Jetscape::PartonShower::GetNumberOfChilds (int n)
Definition at line 154 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 154 of file PartonShower.cc
References GetEdgeAt(), node::outdeg(), and edge::target().
int Jetscape::PartonShower::GetNumberOfParents (int n)
Definition at line 150 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 150 of file PartonShower.cc
References GetEdgeAt(), node::indeg(), and edge::source().
int Jetscape::PartonShower::GetNumberOfPartons () const inline
Definition at line 65 of file PartonShower.h.
View newest version in sPHENIX GitHub at line 65 of file PartonShower.h
References graph::number_of_edges().
int Jetscape::PartonShower::GetNumberOfVertices () const inline
Definition at line 66 of file PartonShower.h.
View newest version in sPHENIX GitHub at line 66 of file PartonShower.h
References graph::number_of_nodes().
shared_ptr<Parton> Jetscape::PartonShower::GetParton (edge e) inline
Definition at line 47 of file PartonShower.h.
View newest version in sPHENIX GitHub at line 47 of file PartonShower.h
References Acts::UnitConstants::e, and pMap.
Referenced by GetPartonAt().
shared_ptr< Parton > Jetscape::PartonShower::GetPartonAt (int n)
Definition at line 172 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 172 of file PartonShower.cc
References graph::edges_begin(), and GetParton().
shared_ptr<Vertex> Jetscape::PartonShower::GetVertex (node n) inline
Definition at line 46 of file PartonShower.h.
View newest version in sPHENIX GitHub at line 46 of file PartonShower.h
References n, and vMap.
Referenced by GetVertexAt().
shared_ptr< Vertex > Jetscape::PartonShower::GetVertexAt (int n)
Definition at line 179 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 179 of file PartonShower.cc
References GetVertex(), and graph::nodes_begin().
void Jetscape::PartonShower::load_edge_info_handler (edge e, GML_pair * list) virtual
Called after an edge is created. The whole list of key-value-pairs belonging to this edge is passed to this handler together with the edge itself.
Parameters
<code>e</code> edge parsed
<code>list</code> pointer to the list of key-value-pairs of this edge.
See Also
graph::load
Reimplemented from graph.
Definition at line 266 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 266 of file PartonShower.cc
References E, Acts::UnitConstants::e, eta, GML_pair_val::floating, if(), GML_pair_val::integer, GML_pair::key, GML_pair::next, ActsTests::PropagationDatasets::phi, train_ambiguity_solver::pid, pMap, graph_fancy::pT, ActsExamples::JsonSurfacesReader::read(), Acts::Test::tmp(), GML_pair::value, and VERBOSESHOWER.
void Jetscape::PartonShower::load_node_info_handler (node n, GML_pair * list) virtual
Called after a node is created. The whole list of key-value-pairs belonging to this node is passed to this handler together with the node itself.
Parameters
<code>n</code> node parsed
<code>list</code> pointer to the list of key-value-pairs of this node.
See Also
graph::load
Reimplemented from graph.
Definition at line 296 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 296 of file PartonShower.cc
References GML_pair_val::floating, if(), GML_pair::key, n, GML_pair::next, ActsExamples::JsonSurfacesReader::read(), t, Acts::Test::tmp(), GML_pair::value, VERBOSESHOWER, vMap, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
int Jetscape::PartonShower::new_parton (node s, node t, shared_ptr< Parton > p)
Definition at line 38 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 38 of file PartonShower.cc
References Acts::UnitConstants::e, edge::id(), graph::new_edge(), merge_hashes::p, and pMap.
node Jetscape::PartonShower::new_vertex (shared_ptr< Vertex > v)
Definition at line 32 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 32 of file PartonShower.cc
References n, graph::new_node(), testSigmaEff::v, and vMap.
void Jetscape::PartonShower::pre_clear_handler () virtual
Virtual function called before performing clear; can be redefined in a derived class for customization. Please note: Although nodes and edges are deleted during graph::clear this is not achieved by calling graph::del_node and graph::del_edge, which is why the correspondig handler will not be called.
See Also
graph::clear
Reimplemented from graph.
Definition at line 213 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 213 of file PartonShower.cc
References graph::edges_begin(), graph::edges_end(), graph::nodes_begin(), graph::nodes_end(), pMap, VERBOSESHOWER, and vMap.
void Jetscape::PartonShower::PrintEdges (bool verbose = true)
Definition at line 243 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 243 of file PartonShower.cc
References graph::edges_begin(), graph::edges_end(), Jetscape::JetScapeLogger::Instance(), os, pMap, physmon_track_finding_ttbar::pt, and VERBOSESHOWER.
Referenced by PrintPartons().
void Jetscape::PartonShower::PrintNodes (bool verbose = true)
Definition at line 226 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 226 of file PartonShower.cc
References Jetscape::JetScapeLogger::Instance(), graph::nodes_begin(), graph::nodes_end(), os, VERBOSESHOWER, and vMap.
Referenced by PrintVertices().
void Jetscape::PartonShower::PrintPartons () inline
Definition at line 76 of file PartonShower.h.
View newest version in sPHENIX GitHub at line 76 of file PartonShower.h
References PrintEdges().
void Jetscape::PartonShower::PrintVertices () inline
Definition at line 75 of file PartonShower.h.
View newest version in sPHENIX GitHub at line 75 of file PartonShower.h
References PrintNodes().
void Jetscape::PartonShower::save_edge_info_handler (ostream * , edge) const virtual
Called before the closing bracket of the list belonging to the key of edge e is written. This can be used to write information belonging to the edge e and thus should appear within the list associated with this edge.
Parameters
<code>os</code> output stream.
See Also
graph::save
Reimplemented from graph.
Definition at line 201 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 201 of file PartonShower.cc
References Acts::UnitConstants::e, and pMap.
void Jetscape::PartonShower::save_node_info_handler (ostream * , node) const virtual
Called before the closing bracket of the list belonging to the key of node n is written. This can be used to write information belonging to the node n and thus should appear within the list associated with this node.
Parameters
<code>os</code> output stream.
See Also
graph::save
Reimplemented from graph.
Definition at line 191 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 191 of file PartonShower.cc
References node::id(), n, and vMap.
void Jetscape::PartonShower::SaveAsGML (string fName) inline
Definition at line 80 of file PartonShower.h.
View newest version in sPHENIX GitHub at line 80 of file PartonShower.h
References graph::save().
void Jetscape::PartonShower::SaveAsGraphML (string fName)
Definition at line 401 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 401 of file PartonShower.cc
References graph::edges_begin(), graph::edges_end(), Acts::UnitConstants::g, n, graph::nodes_begin(), graph::nodes_end(), pMap, physmon_track_finding_ttbar::pt, to_string(), and vMap.
void Jetscape::PartonShower::SaveAsGV (string fName)
Definition at line 325 of file PartonShower.cc.
View newest version in sPHENIX GitHub at line 325 of file PartonShower.cc
References graph::edges_begin(), graph::edges_end(), CKF_timing_vs_mu::label, n, graph::nodes_begin(), graph::nodes_end(), train_ambiguity_solver::pid, pMap, physmon_track_finding_ttbar::pt, t, to_string(), and vMap.
Member Data Documentation
vector<shared_ptr<Parton> > Jetscape::PartonShower::pFinal private
Definition at line 88 of file PartonShower.h.
View newest version in sPHENIX GitHub at line 88 of file PartonShower.h
Referenced by GetFinalPartons(), and ~PartonShower().
edge_map<shared_ptr<Parton> > Jetscape::PartonShower::pMap private
Definition at line 86 of file PartonShower.h.
View newest version in sPHENIX GitHub at line 86 of file PartonShower.h
Referenced by GetFinalPartons(), GetParton(), load_edge_info_handler(), new_parton(), pre_clear_handler(), PrintEdges(), save_edge_info_handler(), SaveAsGraphML(), and SaveAsGV().
node_map<shared_ptr<Vertex> > Jetscape::PartonShower::vMap private
Definition at line 85 of file PartonShower.h.
View newest version in sPHENIX GitHub at line 85 of file PartonShower.h
Referenced by GetVertex(), load_node_info_handler(), new_vertex(), pre_clear_handler(), PrintNodes(), save_node_info_handler(), SaveAsGraphML(), and SaveAsGV().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/PartonShower.h
JETSCAPE/blob/main/src/framework/PartonShower.cc