Analysis Software: Acts::SeedFinder< external_spacepoint_t, Acts::Cuda > Class Template Reference
Acts::SeedFinder< external_spacepoint_t, Acts::Cuda > Class Template Reference
#include <acts/blob/sPHENIX/Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/SeedFinder.hpp>
Public Member Functions
SeedFinder (const Acts::SeedFinderConfig< external_spacepoint_t > &config, const Acts::SeedFinderOptions &options)
~SeedFinder ()=default
template<typename sp_range_t >
std::vector< Seed
< external_spacepoint_t > > createSeedsForGroup (Acts::SpacePointData &spacePointData, Acts::SpacePointGrid< external_spacepoint_t > &grid, const sp_range_t &bottomSPs, const std::size_t middleSPs, const sp_range_t &topSPs) const
Disallow default instantiation, copy, assignment
SeedFinder ()=delete
SeedFinder (const SeedFinder< external_spacepoint_t, Acts::Cuda > &)=delete
SeedFinder
< external_spacepoint_t,
Acts::Cuda > & operator= (const SeedFinder< external_spacepoint_t, Acts::Cuda > &)=delete
Private Attributes
Acts::SeedFinderConfig
< external_spacepoint_t > m_config
Acts::SeedFinderOptions m_options
Detailed Description
template<typename external_spacepoint_t>
class Acts::SeedFinder< external_spacepoint_t, Acts::Cuda >
Definition at line 32 of file SeedFinder.hpp.
View newest version in sPHENIX GitHub at line 32 of file SeedFinder.hpp
Constructor & Destructor Documentation
template<typename external_spacepoint_t > Acts::SeedFinder< external_spacepoint_t, Acts::Cuda >::SeedFinder (const Acts::SeedFinderConfig< external_spacepoint_t > & config, const Acts::SeedFinderOptions & options)
Definition at line 19 of file SeedFinder.ipp.
View newest version in sPHENIX GitHub at line 19 of file SeedFinder.ipp
References Acts::SeedFinderConfig< SpacePoint >::deltaRMaxBottomSP, Acts::SeedFinderConfig< SpacePoint >::deltaRMaxTopSP, Acts::SeedFinderConfig< SpacePoint >::deltaRMinBottomSP, Acts::SeedFinderConfig< SpacePoint >::deltaRMinTopSP, Acts::SeedFinderConfig< SpacePoint >::isInInternalUnits, and Acts::SeedFinder< external_spacepoint_t, platform_t >::m_config.
template<typename external_spacepoint_t > Acts::SeedFinder< external_spacepoint_t, Acts::Cuda >::~SeedFinder () default
template<typename external_spacepoint_t > Acts::SeedFinder< external_spacepoint_t, Acts::Cuda >::SeedFinder () delete
template<typename external_spacepoint_t > Acts::SeedFinder< external_spacepoint_t, Acts::Cuda >::SeedFinder (const SeedFinder< external_spacepoint_t, Acts::Cuda > &) delete
Member Function Documentation
template<typename external_spacepoint_t > template<typename sp_range_t > std::vector< Seed< external_spacepoint_t > > Acts::SeedFinder< external_spacepoint_t, Acts::Cuda >::createSeedsForGroup (Acts::SpacePointData & spacePointData, Acts::SpacePointGrid< external_spacepoint_t > & grid, const sp_range_t & bottomSPs, const std::size_t middleSPs, const sp_range_t & topSPs) const
Create all seeds from the space points in the three iterators. Can be used to parallelize the seed creation
Parameters
bottomSPs group of space points to be used as innermost SP in a seed.
middleSPs group of space points to be used as middle SP in a seed.
topSPs group of space points to be used as outermost SP in a seed. Ranges must return pointers. Ranges must be separate objects for each parallel call.
Returns
vector in which all found seeds for this group are stored.
Definition at line 49 of file SeedFinder.ipp.
View newest version in sPHENIX GitHub at line 49 of file SeedFinder.ipp
References Acts::detail::Grid< T, Axes >::at(), Acts::SeedFinderConfig< SpacePoint >::collisionRegionMax, Acts::SeedFinderConfig< SpacePoint >::collisionRegionMin, Acts::SeedFinderConfig< SpacePoint >::cotThetaMax, Acts::SeedFinderConfig< SpacePoint >::deltaRMax, Acts::SeedFinderConfig< SpacePoint >::deltaRMin, Acts::CpuScalar< var_t >::get(), Acts::CpuVector< var_t >::get(), i, train_ambiguity_solver::id, ambiguity_solver_full_chain::idx, Acts::SeedFinderConfig< SpacePoint >::impactMax, Acts::SeedFinder< external_spacepoint_t, platform_t >::m_config, Acts::SeedFinderConfig< SpacePoint >::maxBlockSize, Acts::SeedFinderConfig< SpacePoint >::maxScatteringAngle2, Acts::SeedFinderConfig< SpacePoint >::nAvgTrplPerSpBLimit, Acts::SeedFinderConfig< SpacePoint >::nTrplPerSpBLimit, Acts::SeedFinderConfig< SpacePoint >::seedFilter, Acts::SeedFinderConfig< SpacePoint >::sigmaScattering, Acts::Experimental::detail::BlueprintHelper::sort(), and Acts::CpuVector< var_t >::zeros().
template<typename external_spacepoint_t > SeedFinder<external_spacepoint_t, Acts::Cuda>& Acts::SeedFinder< external_spacepoint_t, Acts::Cuda >::operator= (const SeedFinder< external_spacepoint_t, Acts::Cuda > &) delete
Member Data Documentation
template<typename external_spacepoint_t > Acts::SeedFinderConfig<external_spacepoint_t> Acts::SeedFinder< external_spacepoint_t, Acts::Cuda >::m_config private
Definition at line 66 of file SeedFinder.hpp.
View newest version in sPHENIX GitHub at line 66 of file SeedFinder.hpp
template<typename external_spacepoint_t > Acts::SeedFinderOptions Acts::SeedFinder< external_spacepoint_t, Acts::Cuda >::m_options private
Definition at line 67 of file SeedFinder.hpp.
View newest version in sPHENIX GitHub at line 67 of file SeedFinder.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/SeedFinder.hpp
acts/blob/sPHENIX/Plugins/Cuda/include/Acts/Plugins/Cuda/Seeding/SeedFinder.ipp