Analysis Software: ActsExamples::ObjTrackingGeometryWriter::Config Class Reference
ActsExamples::ObjTrackingGeometryWriter::Config Class Reference
#include <acts/blob/sPHENIX/Examples/Io/Obj/include/ActsExamples/Plugins/Obj/ObjTrackingGeometryWriter.hpp>
Public Attributes
double outputScalor = 1.0
scale output values
size_t outputPrecision = 6
floating point precision
std::string outputDir = "."
Acts::ViewConfig containerView = Acts::ViewConfig({220, 220, 220})
Acts::ViewConfig volumeView = Acts::ViewConfig({220, 220, 0})
Acts::ViewConfig sensitiveView = Acts::ViewConfig({0, 180, 240})
Acts::ViewConfig passiveView = Acts::ViewConfig({240, 280, 0})
Acts::ViewConfig gridView = Acts::ViewConfig({220, 0, 0})
Detailed Description
Definition at line 40 of file ObjTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 40 of file ObjTrackingGeometryWriter.hpp
Member Data Documentation
Acts::ViewConfig ActsExamples::ObjTrackingGeometryWriter::Config::containerView = Acts::ViewConfig({220, 220, 220})
Definition at line 46 of file ObjTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 46 of file ObjTrackingGeometryWriter.hpp
Referenced by ActsExamples::Options::readObjTrackingGeometryWriterConfig().
Acts::ViewConfig ActsExamples::ObjTrackingGeometryWriter::Config::gridView = Acts::ViewConfig({220, 0, 0})
Definition at line 50 of file ObjTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 50 of file ObjTrackingGeometryWriter.hpp
Referenced by ActsExamples::Options::readObjTrackingGeometryWriterConfig().
std::string ActsExamples::ObjTrackingGeometryWriter::Config::outputDir = "."
Definition at line 44 of file ObjTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 44 of file ObjTrackingGeometryWriter.hpp
size_t ActsExamples::ObjTrackingGeometryWriter::Config::outputPrecision = 6
floating point precision
Definition at line 43 of file ObjTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 43 of file ObjTrackingGeometryWriter.hpp
Referenced by ActsExamples::Options::readObjTrackingGeometryWriterConfig().
double ActsExamples::ObjTrackingGeometryWriter::Config::outputScalor = 1.0
scale output values
Definition at line 42 of file ObjTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 42 of file ObjTrackingGeometryWriter.hpp
Referenced by ActsExamples::Options::readObjTrackingGeometryWriterConfig().
Acts::ViewConfig ActsExamples::ObjTrackingGeometryWriter::Config::passiveView = Acts::ViewConfig({240, 280, 0})
Definition at line 49 of file ObjTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 49 of file ObjTrackingGeometryWriter.hpp
Referenced by ActsExamples::Options::readObjTrackingGeometryWriterConfig().
Acts::ViewConfig ActsExamples::ObjTrackingGeometryWriter::Config::sensitiveView = Acts::ViewConfig({0, 180, 240})
Definition at line 48 of file ObjTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 48 of file ObjTrackingGeometryWriter.hpp
Referenced by ActsExamples::Options::readObjTrackingGeometryWriterConfig().
Acts::ViewConfig ActsExamples::ObjTrackingGeometryWriter::Config::volumeView = Acts::ViewConfig({220, 220, 0})
Definition at line 47 of file ObjTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 47 of file ObjTrackingGeometryWriter.hpp
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Examples/Io/Obj/include/ActsExamples/Plugins/Obj/ObjTrackingGeometryWriter.hpp