Analysis Software: pathfinder Class Reference
pathfinder Class Reference
#include <JETSCAPE/blob/main/external_packages/gtl/include/GTL/st_number.h>
Classes
class const_iterator
Public Member Functions
pathfinder (const graph &G, edge st, node s)
bool is_valid ()
const_iterator path (node n)
const_iterator end ()
Private Types
typedef pair< list< edge >
::iterator, list< edge >
::iterator > pos_pair
Private Member Functions
void dfs_sub (node &, node &)
Private Attributes
node_map< int > dfs_num
node_map< int > low_num
node_map< list< edge > > tree
node_map< list< edge > > back
node_map< list< edge > > forward
node_map< list< edge >::iterator > to_low
node_map< list< edge >::iterator > to_father
edge_map< pos_pair > pos
node_map< int > used
int act_dfs_num
int new_nodes
bool is_biconn
Friends
class const_iterator
Detailed Description
Definition at line 26 of file st_number.h.
View newest version in sPHENIX GitHub at line 26 of file st_number.h
Member Typedef Documentation
typedef pair<list<edge>::iterator, list<edge>::iterator> pathfinder::pos_pair private
Definition at line 181 of file st_number.h.
View newest version in sPHENIX GitHub at line 181 of file st_number.h
Constructor & Destructor Documentation
__GTL_BEGIN_NAMESPACE pathfinder::pathfinder (const graph & G, edge st, node s)
Definition at line 26 of file st_number.cpp.
View newest version in sPHENIX GitHub at line 26 of file st_number.cpp
References act_dfs_num, back, dfs_num, dfs_sub(), forward, ne_map< Key, Value, Graph, Alloc >::init(), is_biconn, low_num, new_nodes, graph::number_of_nodes(), node::opposite(), pos, physmon_simulation::s, t, to_father, to_low, tree, and used.
Referenced by st_number::check().
Member Function Documentation
void pathfinder::dfs_sub (node & curr, node & father) private
Definition at line 71 of file st_number.cpp.
View newest version in sPHENIX GitHub at line 71 of file st_number.cpp
References act_dfs_num, node::adj_edges_begin(), node::adj_edges_end(), node::adj_edges_iterator(), back, dfs_num, end(), forward, is_biconn, it, low_num, new_nodes, node::opposite(), pos, Acts::Test::tmp(), to_father, to_low, and tree.
Referenced by pathfinder().
const_iterator pathfinder::end (void) inline
Definition at line 128 of file st_number.h.
View newest version in sPHENIX GitHub at line 128 of file st_number.h
Referenced by dfs_sub(), and st_number::run().
bool pathfinder::is_valid () inline
Definition at line 39 of file st_number.h.
View newest version in sPHENIX GitHub at line 39 of file st_number.h
const_iterator pathfinder::path (node n) inline
Definition at line 120 of file st_number.h.
View newest version in sPHENIX GitHub at line 120 of file st_number.h
Referenced by item.Item::__eq__(), and item.Item::__hash__().
Friends And Related Function Documentation
friend class const_iterator friend
Definition at line 212 of file st_number.h.
View newest version in sPHENIX GitHub at line 212 of file st_number.h
Member Data Documentation
int pathfinder::act_dfs_num private
Definition at line 196 of file st_number.h.
View newest version in sPHENIX GitHub at line 196 of file st_number.h
Referenced by dfs_sub(), and pathfinder().
node_map<list<edge> > pathfinder::back private
Definition at line 161 of file st_number.h.
View newest version in sPHENIX GitHub at line 161 of file st_number.h
Referenced by pathfinder::const_iterator::const_iterator(), dfs_sub(), and pathfinder().
node_map<int> pathfinder::dfs_num private
Definition at line 146 of file st_number.h.
View newest version in sPHENIX GitHub at line 146 of file st_number.h
Referenced by dfs_sub(), and pathfinder().
node_map<list<edge> > pathfinder::forward private
Definition at line 166 of file st_number.h.
View newest version in sPHENIX GitHub at line 166 of file st_number.h
Referenced by pathfinder::const_iterator::const_iterator(), dfs_sub(), and pathfinder().
bool pathfinder::is_biconn private
Definition at line 206 of file st_number.h.
View newest version in sPHENIX GitHub at line 206 of file st_number.h
Referenced by dfs_sub(), and pathfinder().
node_map<int> pathfinder::low_num private
Definition at line 151 of file st_number.h.
View newest version in sPHENIX GitHub at line 151 of file st_number.h
Referenced by dfs_sub(), and pathfinder().
int pathfinder::new_nodes private
Definition at line 201 of file st_number.h.
View newest version in sPHENIX GitHub at line 201 of file st_number.h
Referenced by dfs_sub(), and pathfinder().
edge_map<pos_pair > pathfinder::pos private
Definition at line 186 of file st_number.h.
View newest version in sPHENIX GitHub at line 186 of file st_number.h
Referenced by pathfinder::const_iterator::const_iterator(), dfs_sub(), pathfinder(), and st_number::run().
node_map<list<edge>::iterator> pathfinder::to_father private
Definition at line 176 of file st_number.h.
View newest version in sPHENIX GitHub at line 176 of file st_number.h
Referenced by dfs_sub(), and pathfinder().
node_map<list<edge>::iterator> pathfinder::to_low private
Definition at line 171 of file st_number.h.
View newest version in sPHENIX GitHub at line 171 of file st_number.h
Referenced by dfs_sub(), and pathfinder().
node_map<list<edge> > pathfinder::tree private
Definition at line 156 of file st_number.h.
View newest version in sPHENIX GitHub at line 156 of file st_number.h
Referenced by pathfinder::const_iterator::const_iterator(), dfs_sub(), and pathfinder().
node_map<int> pathfinder::used private
Definition at line 191 of file st_number.h.
View newest version in sPHENIX GitHub at line 191 of file st_number.h
Referenced by pathfinder::const_iterator::const_iterator(), and pathfinder().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/gtl/include/GTL/st_number.h
JETSCAPE/blob/main/external_packages/gtl/src/st_number.cpp