Analysis Software: ActsFatras::Particle Class Reference
ActsFatras::Particle Class Reference
#include <acts/blob/sPHENIX/Fatras/include/ActsFatras/EventData/Particle.hpp>
Public Types
using Scalar = Acts::ActsScalar
using Vector3 = Acts::ActsVector< 3 >
using Vector4 = Acts::ActsVector< 4 >
Public Member Functions
Particle ()=default
Construct a default particle with invalid identity.
Particle (Barcode particleId, Acts::PdgParticle pdg, Scalar charge, Scalar mass)
Particle (Barcode particleId, Acts::PdgParticle pdg)
Particle (const Particle &)=default
Particle (Particle &&)=default
Particle & operator= (const Particle &)=default
Particle & operator= (Particle &&)=default
Particle withParticleId (Barcode particleId) const
Particle & setProcess (ProcessType proc)
Set the process type that generated this particle.
Particle setPdg (Acts::PdgParticle pdg)
Set the pdg.
Particle setCharge (Scalar charge)
Set the charge.
Particle setMass (Scalar mass)
Set the mass.
Particle & setParticleId (Barcode barcode)
Set the particle ID.
Particle & setPosition4 (const Vector4 &pos4)
Set the space-time position four-vector.
Particle & setPosition4 (const Vector3 &position, Scalar time)
Set the space-time position four-vector from three-position and time.
Particle & setPosition4 (Scalar x, Scalar y, Scalar z, Scalar time)
Set the space-time position four-vector from scalar components.
Particle & setDirection (const Vector3 &direction)
Set the direction three-vector.
Particle & setDirection (Scalar dx, Scalar dy, Scalar dz)
Set the direction three-vector from scalar components.
Particle & setAbsoluteMomentum (Scalar absMomentum)
Set the absolute momentum.
Particle & correctEnergy (Scalar delta)
constexpr Barcode particleId () const
Particle identifier within an event.
constexpr ProcessType process () const
Which type of process generated this particle.
constexpr Acts::PdgParticle pdg () const
PDG particle number that identifies the type.
constexpr Acts::PdgParticle absolutePdg () const
Absolute PDG particle number that identifies the type.
constexpr Scalar charge () const
Particle charge.
constexpr Scalar absoluteCharge () const
Particle absolute charge.
constexpr Scalar mass () const
Particle mass.
constexpr Acts::ParticleHypothesis hypothesis () const
Particle hypothesis.
constexpr Scalar qOverP () const
Particl qOverP.
constexpr const Vector4 & fourPosition () const
Space-time position four-vector.
auto position () const
Three-position, i.e. spatial coordinates without the time.
Scalar time () const
Time coordinate.
Vector4 fourMomentum () const
Energy-momentum four-vector.
const Vector3 & direction () const
Unit three-direction, i.e. the normalized momentum three-vector.
Scalar theta () const
Polar angle.
Scalar phi () const
Azimuthal angle.
Scalar transverseMomentum () const
Absolute momentum in the x-y plane.
constexpr Scalar absoluteMomentum () const
Absolute momentum.
Vector3 momentum () const
Absolute momentum.
Scalar energy () const
Total energy, i.e. norm of the four-momentum.
constexpr bool isAlive () const
Check if the particle is alive, i.e. is not at rest.
constexpr bool isSecondary () const
constexpr Particle & setProperTime (Scalar properTime)
constexpr Scalar properTime () const
Proper time in the particle rest frame.
constexpr Particle & setMaterialPassed (Scalar pathInX0, Scalar pathInL0)
constexpr Scalar pathInX0 () const
Accumulated path within material measured in radiation lengths.
constexpr Scalar pathInL0 () const
Accumulated path within material measured in interaction lengths.
Particle & setReferenceSurface (const Acts::Surface *surface)
const Acts::Surface * referenceSurface () const
Reference surface.
bool hasReferenceSurface () const
Check if the particle has a reference surface.
Acts::Result
< Acts::BoundTrackParameters > boundParameters (const Acts::GeometryContext &gctx) const
Bound track parameters.
Acts::CurvilinearTrackParameters curvilinearParameters () const
Private Attributes
Barcode m_particleId
Particle identifier within the event.
ProcessType m_process = ProcessType::eUndefined
Process type specifier.
Acts::PdgParticle m_pdg = Acts::PdgParticle::eInvalid
PDG particle number.
Scalar m_charge = Scalar(0)
Scalar m_mass = Scalar(0)
Vector3 m_direction = Vector3::UnitZ()
Scalar m_absMomentum = Scalar(0)
Vector4 m_position4 = Vector4::Zero()
Scalar m_properTime = Scalar(0)
Scalar m_pathInX0 = Scalar(0)
Scalar m_pathInL0 = Scalar(0)
const Acts::Surface * m_referenceSurface {nullptr}
Detailed Description
Particle identity information and kinematic state.
Also stores some simulation-specific properties.
Definition at line 35 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 35 of file Particle.hpp
Member Typedef Documentation
using ActsFatras::Particle::Scalar = Acts::ActsScalar
Definition at line 37 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 37 of file Particle.hpp
using ActsFatras::Particle::Vector3 = Acts::ActsVector<3>
Definition at line 38 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 38 of file Particle.hpp
using ActsFatras::Particle::Vector4 = Acts::ActsVector<4>
Definition at line 39 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 39 of file Particle.hpp
Constructor & Destructor Documentation
ActsFatras::Particle::Particle () default
Construct a default particle with invalid identity.
ActsFatras::Particle::Particle (Barcode particleId, Acts::PdgParticle pdg, Scalar charge, Scalar mass) inline
Construct a particle at rest with explicit mass and charge.
Parameters
particleId Particle identifier within an event
pdg PDG id
charge Particle charge in native units
mass Particle mass in native units
Warning
It is the users responsibility that charge and mass match the PDG particle number.
Definition at line 52 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 52 of file Particle.hpp
ActsFatras::Particle::Particle (Barcode particleId, Acts::PdgParticle pdg)
Construct a particle at rest from a PDG particle number.
Parameters
particleId Particle identifier within an event
pdg PDG particle number
Charge and mass are retrieved from the particle data table.
Definition at line 16 of file Particle.cpp.
View newest version in sPHENIX GitHub at line 16 of file Particle.cpp
ActsFatras::Particle::Particle (const Particle &) default
ActsFatras::Particle::Particle (Particle &&) default
Member Function Documentation
constexpr Scalar ActsFatras::Particle::absoluteCharge () const inline
Particle absolute charge.
Definition at line 170 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 170 of file Particle.hpp
References m_charge.
Referenced by hypothesis(), ActsFatras::detail::Highland::operator()(), ActsFatras::detail::GeneralMixture::operator()(), ActsFatras::detail::GaussianMixture::operator()(), and ActsFatras::BetheBloch::operator()().
constexpr Scalar ActsFatras::Particle::absoluteMomentum () const inline
Absolute momentum.
Definition at line 210 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 210 of file Particle.hpp
References m_absMomentum.
Referenced by BOOST_DATA_TEST_CASE(), ActsExamples::ResPlotTool::fill(), ActsFatras::PhotonConversion::generatePathLimits(), ActsFatras::NuclearInteraction::generatePathLimits(), momentum(), ActsFatras::detail::GaussianMixture::operator()(), ActsFatras::detail::GeneralMixture::operator()(), ActsFatras::Casts::Pt::operator()(), ActsFatras::BetheHeitler::operator()(), ActsFatras::Casts::P::operator()(), ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::operator()(), ActsFatras::operator<<(), ActsExamples::detail::NuclearInteractionParametrisation::prepareMomenta(), ActsExamples::Geant4::HepMC3::PrimaryGeneratorAction::prepareParticleGun(), qOverP(), ActsFatras::PhotonConversion::run(), and ActsFatras::NuclearInteraction::run().
constexpr Acts::PdgParticle ActsFatras::Particle::absolutePdg () const inline
Absolute PDG particle number that identifies the type.
Definition at line 164 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 164 of file Particle.hpp
References Acts::makeAbsolutePdgParticle(), and pdg().
Referenced by hypothesis(), ActsFatras::detail::Highland::operator()(), ActsFatras::detail::GeneralMixture::operator()(), and ActsFatras::detail::GaussianMixture::operator()().
Acts::Result<Acts::BoundTrackParameters> ActsFatras::Particle::boundParameters (const Acts::GeometryContext & gctx) const inline
Bound track parameters.
Definition at line 265 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 265 of file Particle.hpp
References direction(), Acts::Surface::globalToLocal(), hasReferenceSurface(), hypothesis(), m_referenceSurface, phi(), position(), qOverP(), referenceSurface(), theta(), and time().
Referenced by ActsFatras::SingleParticleSimulation< propagator_t, interactions_t, hit_surface_selector_t, decay_t >::simulate().
constexpr Scalar ActsFatras::Particle::charge () const inline
Particle charge.
Definition at line 168 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 168 of file Particle.hpp
References m_charge.
Referenced by ActsExamples::ResPlotTool::fill(), ActsFatras::NeutralSelector::operator()(), ActsFatras::ChargedSelector::operator()(), ActsFatras::PositiveSelector::operator()(), ActsFatras::NegativeSelector::operator()(), ActsFatras::operator<<(), qOverP(), ActsFatras::Simulation< charged_selector_t, charged_simulator_t, neutral_selector_t, neutral_simulator_t >::selectParticle(), setCharge(), and ActsExamples::EDM4hepUtil::writeParticle().
Particle& ActsFatras::Particle::correctEnergy (Scalar delta) inline
Change the energy by the given amount.
Energy loss corresponds to a negative change. If the updated energy would result in an unphysical value, the particle is put to rest, i.e. its absolute momentum is set to zero.
Definition at line 147 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 147 of file Particle.hpp
References physmon_vertexing::delta, m_absMomentum, and m_mass.
Referenced by ActsFatras::BetheBloch::operator()(), and ActsFatras::BetheHeitler::operator()().
Acts::CurvilinearTrackParameters ActsFatras::Particle::curvilinearParameters () const inline
Definition at line 282 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 282 of file Particle.hpp
References direction(), fourPosition(), hypothesis(), and qOverP().
Referenced by ActsFatras::SingleParticleSimulation< propagator_t, interactions_t, hit_surface_selector_t, decay_t >::simulate().
const Vector3& ActsFatras::Particle::direction () const inline
Unit three-direction, i.e. the normalized momentum three-vector.
Definition at line 200 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 200 of file Particle.hpp
References m_direction.
Referenced by boundParameters(), ActsFatras::BetheHeitler::bremPhoton(), ActsFatras::NuclearInteraction::convertParametersToParticles(), curvilinearParameters(), ActsExamples::EffPlotTool::fill(), ActsExamples::DuplicationPlotTool::fill(), ActsExamples::FakeRatePlotTool::fill(), ActsExamples::ResPlotTool::fill(), ActsFatras::PhotonConversion::generateChildDirection(), momentum(), ActsFatras::Casts::Eta::operator()(), ActsFatras::detail::ScatteringImpl< scattering_model_t >::operator()(), ActsFatras::Casts::AbsEta::operator()(), ActsFatras::Casts::Pt::operator()(), ActsFatras::BetheHeitler::operator()(), ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::operator()(), phi(), ActsExamples::Geant4::HepMC3::PrimaryGeneratorAction::prepareParticleGun(), setDirection(), and theta().
Scalar ActsFatras::Particle::energy () const inline
Total energy, i.e. norm of the four-momentum.
Definition at line 214 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 214 of file Particle.hpp
References m_absMomentum, and m_mass.
Referenced by BOOST_DATA_TEST_CASE(), ActsFatras::BetheHeitler::bremPhoton(), fourMomentum(), ActsFatras::PhotonConversion::generateChildDirection(), ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::makeParticle(), ActsFatras::BetheHeitler::operator()(), and ActsFatras::Casts::E::operator()().
Vector4 ActsFatras::Particle::fourMomentum () const inline
Energy-momentum four-vector.
Definition at line 190 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 190 of file Particle.hpp
References Acts::eEnergy, Acts::eMom0, Acts::eMom1, Acts::eMom2, energy(), Acts::ePos0, Acts::ePos1, Acts::ePos2, m_absMomentum, and m_direction.
Referenced by BOOST_DATA_TEST_CASE(), ActsFatras::Geant4Decay::decayParticle(), ActsFatras::PhotonConversion::generateChildren(), ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::operator()(), ActsExamples::detail::NuclearInteractionParametrisation::prepareInvariantMasses(), and ActsExamples::EDM4hepUtil::writeParticle().
constexpr const Vector4& ActsFatras::Particle::fourPosition () const inline
Space-time position four-vector.
Definition at line 184 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 184 of file Particle.hpp
References m_position4.
Referenced by ActsFatras::BetheHeitler::bremPhoton(), ActsFatras::NuclearInteraction::convertParametersToParticles(), curvilinearParameters(), ActsFatras::Geant4Decay::decayParticle(), ActsFatras::PhotonConversion::generateChildren(), and ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::operator()().
bool ActsFatras::Particle::hasReferenceSurface () const inline
Check if the particle has a reference surface.
Definition at line 262 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 262 of file Particle.hpp
References m_referenceSurface.
Referenced by boundParameters(), and ActsFatras::SingleParticleSimulation< propagator_t, interactions_t, hit_surface_selector_t, decay_t >::simulate().
constexpr Acts::ParticleHypothesis ActsFatras::Particle::hypothesis () const inline
Particle hypothesis.
Definition at line 175 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 175 of file Particle.hpp
References absoluteCharge(), absolutePdg(), and mass().
Referenced by boundParameters(), curvilinearParameters(), and qOverP().
constexpr bool ActsFatras::Particle::isAlive () const inline
Check if the particle is alive, i.e. is not at rest.
Definition at line 217 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 217 of file Particle.hpp
References m_absMomentum.
constexpr bool ActsFatras::Particle::isSecondary () const inline
Definition at line 219 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 219 of file Particle.hpp
References ActsFatras::Barcode::generation(), particleId(), ActsFatras::Barcode::subParticle(), and ActsFatras::Barcode::vertexSecondary().
constexpr Scalar ActsFatras::Particle::mass () const inline
Particle mass.
Definition at line 172 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 172 of file Particle.hpp
References m_mass.
Referenced by ActsFatras::BetheHeitler::bremPhoton(), hypothesis(), ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::makeParticle(), ActsFatras::detail::Highland::operator()(), ActsFatras::detail::GeneralMixture::operator()(), ActsFatras::detail::GaussianMixture::operator()(), ActsFatras::BetheBloch::operator()(), ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::operator()(), ActsFatras::operator<<(), setMass(), and ActsExamples::EDM4hepUtil::writeParticle().
Vector3 ActsFatras::Particle::momentum () const inline
Absolute momentum.
Definition at line 212 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 212 of file Particle.hpp
References absoluteMomentum(), and direction().
Particle& ActsFatras::Particle::operator= (const Particle &) default
Particle& ActsFatras::Particle::operator= (Particle &&) default
constexpr Barcode ActsFatras::Particle::particleId () const inline
Particle identifier within an event.
Definition at line 158 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 158 of file Particle.hpp
References m_particleId.
Referenced by ActsFatras::BetheHeitler::bremPhoton(), ActsFatras::NuclearInteraction::convertParametersToParticles(), ActsFatras::Geant4Decay::decayParticle(), ActsFatras::PhotonConversion::generateChildren(), isSecondary(), ActsExamples::detail::CompareParticleId::operator()(), ActsExamples::detail::PrimaryVertexIdGetter::operator()(), ActsExamples::detail::SecondaryVertexIdGetter::operator()(), ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::operator()(), ActsFatras::operator<<(), and withParticleId().
constexpr Scalar ActsFatras::Particle::pathInL0 () const inline
Accumulated path within material measured in interaction lengths.
Definition at line 248 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 248 of file Particle.hpp
References m_pathInL0.
Referenced by ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::interact(), and setMaterialPassed().
constexpr Scalar ActsFatras::Particle::pathInX0 () const inline
Accumulated path within material measured in radiation lengths.
Definition at line 246 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 246 of file Particle.hpp
References m_pathInX0.
Referenced by ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::interact(), and setMaterialPassed().
constexpr Acts::PdgParticle ActsFatras::Particle::pdg () const inline
PDG particle number that identifies the type.
Definition at line 162 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 162 of file Particle.hpp
References m_pdg.
Referenced by absolutePdg(), ActsFatras::Geant4Decay::decayParticle(), ActsFatras::PhotonConversion::generatePathLimits(), ActsFatras::NuclearInteraction::generatePathLimits(), ActsFatras::Geant4Decay::generateProperTimeLimit(), ActsFatras::PdgSelector< Pdg >::operator()(), ActsFatras::AbsPdgSelector< Pdg >::operator()(), ActsFatras::PdgExcluder< Pdg >::operator()(), ActsFatras::AbsPdgExcluder< Pdg >::operator()(), ActsFatras::operator<<(), ActsExamples::Geant4::HepMC3::PrimaryGeneratorAction::prepareParticleGun(), ActsFatras::PhotonConversion::run(), ActsFatras::NuclearInteraction::run(), setPdg(), and ActsExamples::EDM4hepUtil::writeParticle().
Scalar ActsFatras::Particle::phi () const inline
Azimuthal angle.
Definition at line 204 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 204 of file Particle.hpp
References direction(), and Acts::VectorHelpers::phi().
Referenced by boundParameters().
auto ActsFatras::Particle::position () const inline
Three-position, i.e. spatial coordinates without the time.
Definition at line 186 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 186 of file Particle.hpp
References Acts::ePos0, and m_position4.
Referenced by boundParameters(), ActsExamples::ResPlotTool::fill(), ActsFatras::Casts::Vrho::operator()(), ActsFatras::Casts::Vz::operator()(), ActsFatras::Casts::AbsVz::operator()(), ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::operator()(), ActsExamples::Geant4::HepMC3::PrimaryGeneratorAction::prepareParticleGun(), and ActsExamples::EDM4hepUtil::writeParticle().
constexpr ProcessType ActsFatras::Particle::process () const inline
Which type of process generated this particle.
Definition at line 160 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 160 of file Particle.hpp
References m_process.
constexpr Scalar ActsFatras::Particle::properTime () const inline
Proper time in the particle rest frame.
Definition at line 234 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 234 of file Particle.hpp
References m_properTime.
Referenced by ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::makeParticle(), ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::operator()(), and setProperTime().
constexpr Scalar ActsFatras::Particle::qOverP () const inline
Particl qOverP.
Definition at line 179 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 179 of file Particle.hpp
References absoluteMomentum(), charge(), and hypothesis().
Referenced by boundParameters(), curvilinearParameters(), ActsFatras::detail::Highland::operator()(), ActsFatras::detail::GaussianMixture::operator()(), ActsFatras::BetheBloch::operator()(), ActsFatras::detail::GeneralMixture::operator()(), and ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::operator()().
const Acts::Surface* ActsFatras::Particle::referenceSurface () const inline
Reference surface.
Definition at line 259 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 259 of file Particle.hpp
References m_referenceSurface.
Referenced by boundParameters(), ActsFatras::BetheHeitler::bremPhoton(), ActsFatras::NuclearInteraction::convertParametersToParticles(), and ActsFatras::PhotonConversion::generateChildren().
Particle& ActsFatras::Particle::setAbsoluteMomentum (Scalar absMomentum) inline
Set the absolute momentum.
Definition at line 137 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 137 of file Particle.hpp
References ActsTests::PropagationDatasets::absMomentum, and m_absMomentum.
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), ActsFatras::BetheHeitler::bremPhoton(), ActsExamples::ParticleTrackingAction::convert(), ActsFatras::PhotonConversion::generateChildren(), Dataset::makeParticle(), ActsExamples::Pythia8Generator::operator()(), ActsExamples::ParametricParticleGenerator::operator()(), ActsExamples::HepMC3Particle::particle(), ActsExamples::CsvParticleReader::read(), ActsExamples::RootParticleReader::read(), ActsExamples::EDM4hepUtil::readParticle(), and ActsFatras::NuclearInteraction::run().
Particle ActsFatras::Particle::setCharge (Scalar charge) inline
Set the charge.
Definition at line 89 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 89 of file Particle.hpp
References charge(), and m_charge.
Referenced by ActsExamples::RootParticleReader::read().
Particle& ActsFatras::Particle::setDirection (const Vector3 & direction) inline
Set the direction three-vector.
Definition at line 123 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 123 of file Particle.hpp
References direction(), and m_direction.
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), ActsExamples::ParticleTrackingAction::convert(), ActsFatras::NuclearInteraction::convertParametersToParticles(), Dataset::makeParticle(), ActsFatras::detail::ScatteringImpl< scattering_model_t >::operator()(), ActsExamples::Pythia8Generator::operator()(), ActsFatras::BetheHeitler::operator()(), ActsExamples::ParametricParticleGenerator::operator()(), ActsExamples::HepMC3Particle::particle(), ActsExamples::CsvParticleReader::read(), ActsExamples::RootParticleReader::read(), ActsExamples::RootTrajectorySummaryReader::read(), and ActsExamples::EDM4hepUtil::readParticle().
Particle& ActsFatras::Particle::setDirection (Scalar dx, Scalar dy, Scalar dz) inline
Set the direction three-vector from scalar components.
Definition at line 129 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 129 of file Particle.hpp
References dy, dz, Acts::ePos0, Acts::ePos1, Acts::ePos2, and m_direction.
Particle ActsFatras::Particle::setMass (Scalar mass) inline
Set the mass.
Definition at line 94 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 94 of file Particle.hpp
References m_mass, and mass().
Referenced by ActsExamples::RootParticleReader::read().
constexpr Particle& ActsFatras::Particle::setMaterialPassed (Scalar pathInX0, Scalar pathInL0) inline
Set the accumulated material measured in radiation/interaction lengths.
Parameters
pathInX0 accumulated material measured in radiation lengths
pathInL0 accumulated material measured in interaction lengths
Definition at line 240 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 240 of file Particle.hpp
References m_pathInL0, m_pathInX0, pathInL0(), and pathInX0().
Referenced by ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::interact().
Particle& ActsFatras::Particle::setParticleId (Barcode barcode) inline
Set the particle ID.
Definition at line 99 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 99 of file Particle.hpp
References m_particleId.
Referenced by ActsExamples::RootParticleReader::read(), and ActsExamples::RootTrajectorySummaryReader::read().
Particle ActsFatras::Particle::setPdg (Acts::PdgParticle pdg) inline
Set the pdg.
Definition at line 84 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 84 of file Particle.hpp
References m_pdg, and pdg().
Referenced by ActsExamples::RootParticleReader::read().
Particle& ActsFatras::Particle::setPosition4 (const Vector4 & pos4) inline
Set the space-time position four-vector.
Definition at line 104 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 104 of file Particle.hpp
References m_position4, and Acts::Test::pos4().
Referenced by ActsFatras::BetheHeitler::bremPhoton(), ActsExamples::ParticleTrackingAction::convert(), ActsFatras::NuclearInteraction::convertParametersToParticles(), ActsFatras::Geant4Decay::decayParticle(), Dataset::makeParticle(), ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::makeParticle(), ActsExamples::Pythia8Generator::operator()(), ActsExamples::CsvParticleReader::read(), ActsExamples::RootParticleReader::read(), ActsExamples::RootTrajectorySummaryReader::read(), and ActsExamples::EDM4hepUtil::readParticle().
Particle& ActsFatras::Particle::setPosition4 (const Vector3 & position, Scalar time) inline
Set the space-time position four-vector from three-position and time.
Definition at line 109 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 109 of file Particle.hpp
References Acts::ePos0, Acts::eTime, m_position4, and time().
Particle& ActsFatras::Particle::setPosition4 (Scalar x, Scalar y, Scalar z, Scalar time) inline
Set the space-time position four-vector from scalar components.
Definition at line 115 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 115 of file Particle.hpp
References Acts::ePos0, Acts::ePos1, Acts::ePos2, Acts::eTime, m_position4, time(), ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Particle& ActsFatras::Particle::setProcess (ProcessType proc) inline
Set the process type that generated this particle.
Definition at line 79 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 79 of file Particle.hpp
References m_process.
Referenced by ActsFatras::BetheHeitler::bremPhoton(), ActsFatras::NuclearInteraction::convertParametersToParticles(), ActsFatras::Geant4Decay::decayParticle(), ActsFatras::PhotonConversion::generateChildren(), ActsExamples::CsvParticleReader::read(), and ActsExamples::RootParticleReader::read().
constexpr Particle& ActsFatras::Particle::setProperTime (Scalar properTime) inline
Set the proper time in the particle rest frame.
Parameters
properTime passed proper time in the rest frame
Definition at line 229 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 229 of file Particle.hpp
References m_properTime, and properTime().
Particle& ActsFatras::Particle::setReferenceSurface (const Acts::Surface * surface) inline
Set the reference surface.
Parameters
surface reference surface
Definition at line 253 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 253 of file Particle.hpp
References m_referenceSurface, and writeMapConfig::surface.
Referenced by ActsFatras::BetheHeitler::bremPhoton(), ActsFatras::NuclearInteraction::convertParametersToParticles(), ActsFatras::PhotonConversion::generateChildren(), and ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::makeParticle().
Scalar ActsFatras::Particle::theta () const inline
Polar angle.
Definition at line 202 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 202 of file Particle.hpp
References direction(), and Acts::VectorHelpers::theta().
Referenced by boundParameters().
Scalar ActsFatras::Particle::time () const inline
Time coordinate.
Definition at line 188 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 188 of file Particle.hpp
References Acts::eTime, and m_position4.
Referenced by boundParameters(), ActsExamples::ResPlotTool::fill(), ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::makeParticle(), ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::operator()(), and setPosition4().
Scalar ActsFatras::Particle::transverseMomentum () const inline
Absolute momentum in the x-y plane.
Definition at line 206 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 206 of file Particle.hpp
References Acts::eMom0, m_absMomentum, m_direction, and norm.
Referenced by ActsExamples::EffPlotTool::fill(), ActsExamples::DuplicationPlotTool::fill(), ActsExamples::FakeRatePlotTool::fill(), and ActsExamples::ResPlotTool::fill().
Particle ActsFatras::Particle::withParticleId (Barcode particleId) const inline
Construct a new particle with a new identifier but same kinematics.
Note
This is intentionally not a regular setter. The particle id is used to identify the whole particle. Setting it on an existing particle is usually a mistake.
Definition at line 72 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 72 of file Particle.hpp
References m_particleId, merge_hashes::p, and particleId().
Member Data Documentation
Scalar ActsFatras::Particle::m_absMomentum = Scalar(0) private
Definition at line 300 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 300 of file Particle.hpp
Referenced by absoluteMomentum(), correctEnergy(), energy(), fourMomentum(), isAlive(), setAbsoluteMomentum(), and transverseMomentum().
Scalar ActsFatras::Particle::m_charge = Scalar(0) private
Definition at line 296 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 296 of file Particle.hpp
Referenced by absoluteCharge(), charge(), and setCharge().
Vector3 ActsFatras::Particle::m_direction = Vector3::UnitZ() private
Definition at line 299 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 299 of file Particle.hpp
Referenced by direction(), fourMomentum(), setDirection(), and transverseMomentum().
Scalar ActsFatras::Particle::m_mass = Scalar(0) private
Definition at line 297 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 297 of file Particle.hpp
Referenced by correctEnergy(), energy(), mass(), and setMass().
Barcode ActsFatras::Particle::m_particleId private
Particle identifier within the event.
Definition at line 290 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 290 of file Particle.hpp
Referenced by particleId(), setParticleId(), and withParticleId().
Scalar ActsFatras::Particle::m_pathInL0 = Scalar(0) private
Definition at line 306 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 306 of file Particle.hpp
Referenced by pathInL0(), and setMaterialPassed().
Scalar ActsFatras::Particle::m_pathInX0 = Scalar(0) private
Definition at line 305 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 305 of file Particle.hpp
Referenced by pathInX0(), and setMaterialPassed().
Acts::PdgParticle ActsFatras::Particle::m_pdg = Acts::PdgParticle::eInvalid private
PDG particle number.
Definition at line 294 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 294 of file Particle.hpp
Referenced by pdg(), and setPdg().
Vector4 ActsFatras::Particle::m_position4 = Vector4::Zero() private
Definition at line 301 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 301 of file Particle.hpp
Referenced by fourPosition(), position(), setPosition4(), and time().
ProcessType ActsFatras::Particle::m_process = ProcessType::eUndefined private
Process type specifier.
Definition at line 292 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 292 of file Particle.hpp
Referenced by process(), and setProcess().
Scalar ActsFatras::Particle::m_properTime = Scalar(0) private
Definition at line 303 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 303 of file Particle.hpp
Referenced by properTime(), and setProperTime().
const Acts::Surface* ActsFatras::Particle::m_referenceSurface {nullptr} private
Definition at line 308 of file Particle.hpp.
View newest version in sPHENIX GitHub at line 308 of file Particle.hpp
Referenced by boundParameters(), hasReferenceSurface(), referenceSurface(), and setReferenceSurface().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Fatras/include/ActsFatras/EventData/Particle.hpp
acts/blob/sPHENIX/Fatras/src/EventData/Particle.cpp