Analysis Software: macros/blob/master/calibrations/calo/calib_nov23/pimacs/runCCPi0Loop.C File Reference
runCCPi0Loop.C File Reference
#include <calib_emc_pi0/CaloCalibEmc_Pi0.h>
#include <fstream>
#include <string>
#include "TChain.h"
#include "TTree.h"
#include "TString.h"
Functions
void runCCPi0Loop (int nevents=-1, const char *ifile="", const char *ofile="")
TTree * GetTChainMacro (TString ifile="")
Function Documentation
TTree * GetTChainMacro (TString ifile = "")
Definition at line 24 of file runCCPi0Loop.C.
View newest version in sPHENIX GitHub at line 24 of file runCCPi0Loop.C
References in, test_fpe::lines, and printf().
Referenced by runCCPi0Loop().
void runCCPi0Loop (int nevents = -1, const char * ifile = "", const char * ofile = "")
Definition at line 11 of file runCCPi0Loop.C.
View newest version in sPHENIX GitHub at line 11 of file runCCPi0Loop.C
References CaloCalibEmc_Pi0::End(), GetTChainMacro(), CaloCalibEmc_Pi0::InitRun(), CaloCalibEmc_Pi0::Loop(), nevents(), and ofile.