Analysis Software: Fun4AllRolloverFileOutStream Class Reference
Fun4AllRolloverFileOutStream Class Reference
#include <coresoftware/blob/master/offline/framework/fun4allraw/Fun4AllRolloverFileOutStream.h>
Public Member Functions
Fun4AllRolloverFileOutStream (const std::string &frule="OUTDATA-%010d-%04d.PRDFF", const unsigned int nEvents=0, const unsigned int sizeInMB=0, const int offset=0, const int increment=1, const std::string &name="Fun4AllRolloverFileOutStream")
virtual ~Fun4AllRolloverFileOutStream ()=default
int WriteEventOut (Event *evt) override
void identify (std::ostream &os=std::cout) const
Public Member Functions inherited from Fun4AllFileOutStream
Fun4AllFileOutStream (const std::string &frule="OUTDATA-%010d-%04d.PRDFF", const std::string &name="FILEOUTSTREAM")
virtual ~Fun4AllFileOutStream ()
int CloseOutStream () override
void identify (std::ostream &os=std::cout) const
oBuffer * GetoBuffer ()
void SetoBuffer (oBuffer *bf)
uint64_t MaxSize () const
void DeleteoBuffer ()
std::string FileRule () const
int iSeq () const
void iSeq (const int i)
uint64_t BytesWritten () const
void BytesWritten (const uint64_t i)
int OutFileDescriptor () const
void OutFileDescriptor (const int i)
PHDWORD * xb ()
void SetNEvents (unsigned int i)
unsigned int GetNEvents () const
Public Member Functions inherited from Fun4AllEventOutStream
virtual ~Fun4AllEventOutStream ()
virtual int StreamStatus ()
virtual int WriteEvent (Event *evt)
int AddPacket (const int ipkt)
int DropPacket (const int ipkt)
int AddPacketRange (const int minpacket, const int maxpacket)
int DropPacketRange (const int minpacket, const int maxpacket)
void SetManager (Fun4AllEventOutputManager *myman)
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Print (const std::string &what="ALL") const
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void open_new_file ()
Private Attributes
uint64_t m_MaxFileFize {0}
unsigned int m_MaxNEvents {0}
int m_CurrentSequence {0}
int m_Offset {0}
int m_Increment {1}
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Static Public Attributes inherited from Fun4AllFileOutStream
static const unsigned int LENGTH = (4 * 1024 * 1024)
Protected Member Functions inherited from Fun4AllEventOutStream
Fun4AllEventOutStream (const std::string &name="OUTSTREAM")
int resize_evtbuf (const unsigned int newsize)
Fun4AllEventOutputManager * MyManager ()
Detailed Description
Definition at line 13 of file Fun4AllRolloverFileOutStream.h.
View newest version in sPHENIX GitHub at line 13 of file Fun4AllRolloverFileOutStream.h
Constructor & Destructor Documentation
Fun4AllRolloverFileOutStream::Fun4AllRolloverFileOutStream (const std::string & frule = "OUTDATA-%010d-%04d.PRDFF", const unsigned int nEvents = 0, const unsigned int sizeInMB = 0, const int offset = 0, const int increment = 1, const std::string & name = "Fun4AllRolloverFileOutStream")
Definition at line 18 of file Fun4AllRolloverFileOutStream.cc.
View newest version in sPHENIX GitHub at line 18 of file Fun4AllRolloverFileOutStream.cc
References m_CurrentSequence, m_Increment, m_MaxFileFize, m_MaxNEvents, m_Offset, Fun4AllFileOutStream::MaxSize(), nEvents, and offset.
virtual Fun4AllRolloverFileOutStream::~Fun4AllRolloverFileOutStream () virtual default
Member Function Documentation
void Fun4AllRolloverFileOutStream::identify (std::ostream & os = std::cout) const
Definition at line 103 of file Fun4AllRolloverFileOutStream.cc.
View newest version in sPHENIX GitHub at line 103 of file Fun4AllRolloverFileOutStream.cc
References Fun4AllFileOutStream::FileRule(), and m_CurrentSequence.
void Fun4AllRolloverFileOutStream::open_new_file () private
Definition at line 110 of file Fun4AllRolloverFileOutStream.cc.
View newest version in sPHENIX GitHub at line 110 of file Fun4AllRolloverFileOutStream.cc
References Fun4AllFileOutStream::BytesWritten(), Fun4AllFileOutStream::DeleteoBuffer(), Fun4AllEventOutStream::MyManager(), Fun4AllFileOutStream::OutFileDescriptor(), Fun4AllOutputManager::RunAfterClosing(), Fun4AllOutputManager::SetClosingScriptArgs(), and Fun4AllFileOutStream::SetNEvents().
Referenced by WriteEventOut().
int Fun4AllRolloverFileOutStream::WriteEventOut (Event * evt) override virtual
Reimplemented from Fun4AllFileOutStream.
Definition at line 48 of file Fun4AllRolloverFileOutStream.cc.
View newest version in sPHENIX GitHub at line 48 of file Fun4AllRolloverFileOutStream.cc
References oBuffer::addEvent(), Fun4AllFileOutStream::BytesWritten(), Fun4AllFileOutStream::FileRule(), Event::getEvtSequence(), Fun4AllFileOutStream::GetNEvents(), Fun4AllFileOutStream::GetoBuffer(), Event::getRunNumber(), Fun4AllFileOutStream::iSeq(), Fun4AllFileOutStream::LENGTH, m_CurrentSequence, m_Increment, m_MaxFileFize, m_MaxNEvents, Fun4AllEventOutStream::MyManager(), Fun4AllBase::Name(), Acts::open, open_new_file(), Fun4AllFileOutStream::OutFileDescriptor(), PHWHERE, Fun4AllFileOutStream::SetNEvents(), Fun4AllFileOutStream::SetoBuffer(), Fun4AllEventOutputManager::SetOutfileName(), utils::status, Fun4AllBase::Verbosity(), and Fun4AllFileOutStream::xb().
Member Data Documentation
int Fun4AllRolloverFileOutStream::m_CurrentSequence {0} private
Definition at line 31 of file Fun4AllRolloverFileOutStream.h.
View newest version in sPHENIX GitHub at line 31 of file Fun4AllRolloverFileOutStream.h
Referenced by Fun4AllRolloverFileOutStream(), identify(), and WriteEventOut().
int Fun4AllRolloverFileOutStream::m_Increment {1} private
Definition at line 33 of file Fun4AllRolloverFileOutStream.h.
View newest version in sPHENIX GitHub at line 33 of file Fun4AllRolloverFileOutStream.h
Referenced by Fun4AllRolloverFileOutStream(), and WriteEventOut().
uint64_t Fun4AllRolloverFileOutStream::m_MaxFileFize {0} private
Definition at line 29 of file Fun4AllRolloverFileOutStream.h.
View newest version in sPHENIX GitHub at line 29 of file Fun4AllRolloverFileOutStream.h
Referenced by Fun4AllRolloverFileOutStream(), and WriteEventOut().
unsigned int Fun4AllRolloverFileOutStream::m_MaxNEvents {0} private
Definition at line 30 of file Fun4AllRolloverFileOutStream.h.
View newest version in sPHENIX GitHub at line 30 of file Fun4AllRolloverFileOutStream.h
Referenced by Fun4AllRolloverFileOutStream(), and WriteEventOut().
int Fun4AllRolloverFileOutStream::m_Offset {0} private
Definition at line 32 of file Fun4AllRolloverFileOutStream.h.
View newest version in sPHENIX GitHub at line 32 of file Fun4AllRolloverFileOutStream.h
Referenced by Fun4AllRolloverFileOutStream().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4allraw/Fun4AllRolloverFileOutStream.h
coresoftware/blob/master/offline/framework/fun4allraw/Fun4AllRolloverFileOutStream.cc