Analysis Software: PHTpcTracker Class Reference
PHTpcTracker Class Reference
#include <coresoftware/blob/master/offline/packages/PHTpcTracker/PHTpcTracker.h>
Public Member Functions
PHTpcTracker (const std::string &name="PHTpcTracker")
~PHTpcTracker () override
void set_seed_finder_options (double maxdistance1=3.0, double tripletangle1=M_PI/8, size_t minhits1=10, double maxdistance2=6.0, double tripletangle2=M_PI/8, size_t minhits2=5, size_t nthreads=1)
void set_seed_finder_optimization_remove_loopers (bool opt=false, double minr=10.0, double maxr=70.0)
void set_track_follower_optimization_helix (bool opt=false)
void set_track_follower_optimization_precise_fit (bool opt=true)
PHTpcSeedFinder * get_seed_finder ()
PHTpcTrackFollower * get_track_follower ()
PHTpcVertexFinder * get_vertex_finder ()
PHTpcEventExporter * get_event_exporter ()
void enable_vertexing (bool opt=false)
void enable_json_export (bool opt=false)
Public Member Functions inherited from PHTrackSeeding
PHTrackSeeding (const std::string &name="PHTrackSeeding")
~PHTrackSeeding () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_track_map_name (const std::string &map_name)
void SetUseTruthClusters (bool setit)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int Setup (PHCompositeNode *topNode) override
int Process (PHCompositeNode *topNode) override
int End () override
Called in SubsysReco::End.
PHField * getMagField (PHCompositeNode *topNode, double &B)
Private Attributes
PHTpcSeedFinder * mSeedFinder
PHTpcTrackFollower * mTrackFollower
PHTpcVertexFinder * mVertexFinder
PHTpcEventExporter * mEventExporter
PHTpcLookup * mLookup
PHGenFit2::Fitter * mFitter
TGeoManager * mTGeoManager
PHField * mField
double mB
bool mEnableVertexing
bool mEnableJsonExport
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Attributes inherited from PHTrackSeeding
TrkrClusterContainer * _cluster_map = nullptr
TrkrClusterHitAssoc * _cluster_hit_map = nullptr
SvtxVertexMap * _vertex_map = nullptr
SvtxTrackMap * _track_map = nullptr
AssocInfoContainer * _assoc_container = nullptr
TrkrHitSetContainer * _hitsets = nullptr
std::string _track_map_name = "SvtxTrackMap"
bool _use_truth_clusters = false
Detailed Description
Definition at line 36 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 36 of file PHTpcTracker.h
Constructor & Destructor Documentation
PHTpcTracker::PHTpcTracker (const std::string & name = "PHTpcTracker")
Definition at line 59 of file PHTpcTracker.cc.
View newest version in sPHENIX GitHub at line 59 of file PHTpcTracker.cc
References mEventExporter, mLookup, mSeedFinder, mTrackFollower, and mVertexFinder.
PHTpcTracker::~PHTpcTracker () override
Definition at line 88 of file PHTpcTracker.cc.
View newest version in sPHENIX GitHub at line 88 of file PHTpcTracker.cc
References mEventExporter, mField, mFitter, mLookup, mSeedFinder, mTrackFollower, and mVertexFinder.
Member Function Documentation
void PHTpcTracker::enable_json_export (bool opt = false) inline
Definition at line 54 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 54 of file PHTpcTracker.h
References mEnableJsonExport.
Referenced by Tracking_Reco().
void PHTpcTracker::enable_vertexing (bool opt = false) inline
Definition at line 53 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 53 of file PHTpcTracker.h
References mEnableVertexing.
Referenced by Tracking_Reco().
int PHTpcTracker::End () inline override protected virtual
Called in SubsysReco::End.
Implements PHTrackSeeding.
Definition at line 61 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 61 of file PHTpcTracker.h
PHTpcEventExporter* PHTpcTracker::get_event_exporter () inline
Definition at line 51 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 51 of file PHTpcTracker.h
References mEventExporter.
PHTpcSeedFinder* PHTpcTracker::get_seed_finder () inline
Definition at line 48 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 48 of file PHTpcTracker.h
References mSeedFinder.
PHTpcTrackFollower* PHTpcTracker::get_track_follower () inline
Definition at line 49 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 49 of file PHTpcTracker.h
References mTrackFollower.
PHTpcVertexFinder* PHTpcTracker::get_vertex_finder () inline
Definition at line 50 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 50 of file PHTpcTracker.h
References mVertexFinder.
PHField * PHTpcTracker::getMagField (PHCompositeNode * topNode, double & B) protected
Definition at line 213 of file PHTpcTracker.cc.
View newest version in sPHENIX GitHub at line 213 of file PHTpcTracker.cc
References writeMapConfig::bconfig, PHFieldUtility::BuildFieldMap(), Acts::IntegrationTest::Bz, PHFieldUtility::GetFieldMapNode(), PHField::GetFieldValue(), LOG_DEBUG, LOG_WARN, and PHFieldConfigv2::set_field_mag_z().
Referenced by Process().
int PHTpcTracker::Process (PHCompositeNode * topNode) override protected virtual
process event interface for trackers, called in process_event. implemented in derived classes
Implements PHTrackSeeding.
Definition at line 107 of file PHTpcTracker.cc.
View newest version in sPHENIX GitHub at line 107 of file PHTpcTracker.cc
References PHTrackSeeding::_cluster_map, PHTrackSeeding::_hitsets, PHTrackSeeding::_track_map, charge, PHTpcLookup::clear(), Acts::Test::cov, Fun4AllReturnCodes::EVENT_OK, PHTpcSeedFinder::findSeeds(), PHTpcTrackFollower::followTracks(), getMagField(), PHGeomUtility::GetTGeoManager(), i, PHTpcLookup::init(), SvtxTrackMap::insert(), it, j, k, LOG_ERROR_IF, LOG_INFO, mB, mField, mFitter, mLookup, mSeedFinder, mTGeoManager, mTrackFollower, PHWHERE, Acts::Test::pos, and Fun4AllBase::Verbosity().
void PHTpcTracker::set_seed_finder_optimization_remove_loopers (bool opt = false, double minr = 10.0, double maxr = 70.0)
Definition at line 252 of file PHTpcTracker.cc.
View newest version in sPHENIX GitHub at line 252 of file PHTpcTracker.cc
References mSeedFinder, and PHTpcSeedFinder::set_optimization_remove_loopers().
Referenced by Tracking_Reco().
void PHTpcTracker::set_seed_finder_options (double maxdistance1 = 3.0, double tripletangle1 = M_PI / 8, size_t minhits1 = 10, double maxdistance2 = 6.0, double tripletangle2 = M_PI / 8, size_t minhits2 = 5, size_t nthreads = 1)
Definition at line 245 of file PHTpcTracker.cc.
View newest version in sPHENIX GitHub at line 245 of file PHTpcTracker.cc
References mSeedFinder, and PHTpcSeedFinder::set_options().
Referenced by Tracking_Reco().
void PHTpcTracker::set_track_follower_optimization_helix (bool opt = false)
Definition at line 257 of file PHTpcTracker.cc.
View newest version in sPHENIX GitHub at line 257 of file PHTpcTracker.cc
References mTrackFollower, and PHTpcTrackFollower::set_optimization_helix().
Referenced by Tracking_Reco().
void PHTpcTracker::set_track_follower_optimization_precise_fit (bool opt = true)
Definition at line 262 of file PHTpcTracker.cc.
View newest version in sPHENIX GitHub at line 262 of file PHTpcTracker.cc
References mTrackFollower, and PHTpcTrackFollower::set_optimization_precise_fit().
Referenced by Tracking_Reco().
int PHTpcTracker::Setup (PHCompositeNode * topNode) override protected virtual
setup interface for trackers, called in InitRun, setup things like pointers to nodes. overrided in derived classes
Reimplemented from PHTrackSeeding.
Definition at line 99 of file PHTpcTracker.cc.
View newest version in sPHENIX GitHub at line 99 of file PHTpcTracker.cc
References Fun4AllReturnCodes::EVENT_OK, and PHTrackSeeding::Setup().
Member Data Documentation
double PHTpcTracker::mB private
Definition at line 75 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 75 of file PHTpcTracker.h
Referenced by Process().
bool PHTpcTracker::mEnableJsonExport private
Definition at line 78 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 78 of file PHTpcTracker.h
Referenced by enable_json_export().
bool PHTpcTracker::mEnableVertexing private
Definition at line 77 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 77 of file PHTpcTracker.h
Referenced by enable_vertexing().
PHTpcEventExporter* PHTpcTracker::mEventExporter private
Definition at line 69 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 69 of file PHTpcTracker.h
Referenced by get_event_exporter(), PHTpcTracker(), and ~PHTpcTracker().
PHField* PHTpcTracker::mField private
Definition at line 74 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 74 of file PHTpcTracker.h
Referenced by Process(), and ~PHTpcTracker().
PHGenFit2::Fitter* PHTpcTracker::mFitter private
Definition at line 72 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 72 of file PHTpcTracker.h
Referenced by Process(), and ~PHTpcTracker().
PHTpcLookup* PHTpcTracker::mLookup private
Definition at line 70 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 70 of file PHTpcTracker.h
Referenced by PHTpcTracker(), Process(), and ~PHTpcTracker().
PHTpcSeedFinder* PHTpcTracker::mSeedFinder private
Definition at line 66 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 66 of file PHTpcTracker.h
Referenced by get_seed_finder(), PHTpcTracker(), Process(), set_seed_finder_optimization_remove_loopers(), set_seed_finder_options(), and ~PHTpcTracker().
TGeoManager* PHTpcTracker::mTGeoManager private
Definition at line 73 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 73 of file PHTpcTracker.h
Referenced by Process().
PHTpcTrackFollower* PHTpcTracker::mTrackFollower private
Definition at line 67 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 67 of file PHTpcTracker.h
Referenced by get_track_follower(), PHTpcTracker(), Process(), set_track_follower_optimization_helix(), set_track_follower_optimization_precise_fit(), and ~PHTpcTracker().
PHTpcVertexFinder* PHTpcTracker::mVertexFinder private
Definition at line 68 of file PHTpcTracker.h.
View newest version in sPHENIX GitHub at line 68 of file PHTpcTracker.h
Referenced by get_vertex_finder(), PHTpcTracker(), and ~PHTpcTracker().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/PHTpcTracker/PHTpcTracker.h
coresoftware/blob/master/offline/packages/PHTpcTracker/PHTpcTracker.cc