Analysis Software: BbcVertexv2 Class Reference
BbcVertexv2 Class Reference
#include <coresoftware/blob/master/offline/packages/mbd/BbcVertexv2.h>
Public Member Functions
BbcVertexv2 ()
~BbcVertexv2 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
unsigned int get_id () const override
void set_id (unsigned int id) override
float get_t () const override
void set_t (float t) override
float get_t_err () const override
void set_t_err (float t_err) override
float get_z () const override
void set_z (float z) override
float get_z_err () const override
void set_z_err (float z_err) override
void set_bbc_ns (int iarm, int bbc_npmt, float bbc_q, float bbc_t) override
int get_bbc_npmt (int iarm) const override
float get_bbc_q (int iarm) const override
float get_bbc_t (int iarm) const override
Public Member Functions inherited from BbcVertex
~BbcVertex () override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (BbcVertexv2, 1)
Private Attributes
unsigned int _id
float _t
float _t_err
float _z
float _z_err
int _bbc_ns_npmt [2] {}
float _bbc_ns_q [2] {}
float _bbc_ns_t [2] {}
Additional Inherited Members
Protected Member Functions inherited from BbcVertex
BbcVertex ()
Detailed Description
Definition at line 8 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 8 of file BbcVertexv2.h
Constructor & Destructor Documentation
BbcVertexv2::BbcVertexv2 ()
Definition at line 7 of file BbcVertexv2.cc.
View newest version in sPHENIX GitHub at line 7 of file BbcVertexv2.cc
References _bbc_ns_npmt, _bbc_ns_q, _bbc_ns_t, and i.
Referenced by CloneMe(), and Reset().
BbcVertexv2::~BbcVertexv2 () override default
Member Function Documentation
BbcVertexv2::ClassDefOverride (BbcVertexv2 , 1) private
PHObject* BbcVertexv2::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from BbcVertex.
Definition at line 19 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 19 of file BbcVertexv2.h
References BbcVertexv2().
int BbcVertexv2::get_bbc_npmt (int iarm) const inline override virtual
Reimplemented from BbcVertex.
Definition at line 45 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 45 of file BbcVertexv2.h
References _bbc_ns_npmt.
float BbcVertexv2::get_bbc_q (int iarm) const inline override virtual
Reimplemented from BbcVertex.
Definition at line 46 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 46 of file BbcVertexv2.h
References _bbc_ns_q.
float BbcVertexv2::get_bbc_t (int iarm) const inline override virtual
Reimplemented from BbcVertex.
Definition at line 47 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 47 of file BbcVertexv2.h
References _bbc_ns_t.
unsigned int BbcVertexv2::get_id () const inline override virtual
Reimplemented from BbcVertex.
Definition at line 23 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 23 of file BbcVertexv2.h
References _id.
Referenced by identify().
float BbcVertexv2::get_t () const inline override virtual
Reimplemented from BbcVertex.
Definition at line 26 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 26 of file BbcVertexv2.h
References _t.
Referenced by identify().
float BbcVertexv2::get_t_err () const inline override virtual
Reimplemented from BbcVertex.
Definition at line 29 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 29 of file BbcVertexv2.h
References _t_err.
Referenced by identify().
float BbcVertexv2::get_z () const inline override virtual
Reimplemented from BbcVertex.
Definition at line 32 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 32 of file BbcVertexv2.h
References _z.
Referenced by identify().
float BbcVertexv2::get_z_err () const inline override virtual
Reimplemented from BbcVertex.
Definition at line 35 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 35 of file BbcVertexv2.h
References _z_err.
Referenced by identify().
void BbcVertexv2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from BbcVertex.
Definition at line 24 of file BbcVertexv2.cc.
View newest version in sPHENIX GitHub at line 24 of file BbcVertexv2.cc
References get_id(), get_t(), get_t_err(), get_z(), and get_z_err().
int BbcVertexv2::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from BbcVertex.
Definition at line 35 of file BbcVertexv2.cc.
View newest version in sPHENIX GitHub at line 35 of file BbcVertexv2.cc
References _id, _t, _t_err, _z, and _z_err.
void BbcVertexv2::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 17 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 17 of file BbcVertexv2.h
References BbcVertexv2().
void BbcVertexv2::set_bbc_ns (int iarm, int bbc_npmt, float bbc_q, float bbc_t) inline override virtual
Reimplemented from BbcVertex.
Definition at line 38 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 38 of file BbcVertexv2.h
References _bbc_ns_npmt, _bbc_ns_q, and _bbc_ns_t.
void BbcVertexv2::set_id (unsigned int id) inline override virtual
Reimplemented from BbcVertex.
Definition at line 24 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 24 of file BbcVertexv2.h
References _id, and train_ambiguity_solver::id.
void BbcVertexv2::set_t (float t) inline override virtual
Reimplemented from BbcVertex.
Definition at line 27 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 27 of file BbcVertexv2.h
References _t, and t.
void BbcVertexv2::set_t_err (float t_err) inline override virtual
Reimplemented from BbcVertex.
Definition at line 30 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 30 of file BbcVertexv2.h
References _t_err.
void BbcVertexv2::set_z (float z) inline override virtual
Reimplemented from BbcVertex.
Definition at line 33 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 33 of file BbcVertexv2.h
References _z, and physmon_track_finding_ttbar::z.
void BbcVertexv2::set_z_err (float z_err) inline override virtual
Reimplemented from BbcVertex.
Definition at line 36 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 36 of file BbcVertexv2.h
References _z_err.
Member Data Documentation
int BbcVertexv2::_bbc_ns_npmt[2] {} private
Definition at line 55 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 55 of file BbcVertexv2.h
Referenced by BbcVertexv2(), get_bbc_npmt(), and set_bbc_ns().
float BbcVertexv2::_bbc_ns_q[2] {} private
Definition at line 56 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 56 of file BbcVertexv2.h
Referenced by BbcVertexv2(), get_bbc_q(), and set_bbc_ns().
float BbcVertexv2::_bbc_ns_t[2] {} private
Definition at line 57 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 57 of file BbcVertexv2.h
Referenced by BbcVertexv2(), get_bbc_t(), and set_bbc_ns().
unsigned int BbcVertexv2::_id private
Definition at line 50 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 50 of file BbcVertexv2.h
Referenced by get_id(), isValid(), and set_id().
float BbcVertexv2::_t private
Definition at line 51 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 51 of file BbcVertexv2.h
Referenced by get_t(), isValid(), and set_t().
float BbcVertexv2::_t_err private
Definition at line 52 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 52 of file BbcVertexv2.h
Referenced by get_t_err(), isValid(), and set_t_err().
float BbcVertexv2::_z private
Definition at line 53 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 53 of file BbcVertexv2.h
Referenced by get_z(), isValid(), and set_z().
float BbcVertexv2::_z_err private
Definition at line 54 of file BbcVertexv2.h.
View newest version in sPHENIX GitHub at line 54 of file BbcVertexv2.h
Referenced by get_z_err(), isValid(), and set_z_err().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mbd/BbcVertexv2.h
coresoftware/blob/master/offline/packages/mbd/BbcVertexv2.cc