Analysis Software: CDBUtils Class Reference
CDBUtils Class Reference
#include <coresoftware/blob/master/offline/database/sphenixnpc/CDBUtils.h>
Public Member Functions
CDBUtils ()
CDBUtils (const std::string &globaltag)
CDBUtils (const CDBUtils &)=delete
CDBUtils & operator= (const CDBUtils &)=delete
virtual ~CDBUtils ()=default
int createGlobalTag (const std::string &tagname)
int setGlobalTag (const std::string &tagname)
int lockGlobalTag (const std::string &tagname)
int unlockGlobalTag (const std::string &tagname)
int createPayloadType (const std::string &domain)
std::string getUrl (const std::string &type, uint64_t iov)
int insertPayload (const std::string &pl_type, const std::string &file_url, uint64_t iov_start)
int insertPayload (const std::string &pl_type, const std::string &file_url, uint64_t iov_start, uint64_t iov_end)
int cloneGlobalTag (const std::string &source, const std::string &target)
int deleteGlobalTag (const std::string &)
void listGlobalTags ()
void listPayloadTypes ()
void listPayloadIOVs (uint64_t iov)
void clearCache ()
bool isGlobalTagSet ()
void Verbosity (int i)
int Verbosity () const
int deletePayloadIOV (const std::string &pl_type, uint64_t iov_start)
int deletePayloadIOV (const std::string &pl_type, uint64_t iov_start, uint64_t iov_end)
Private Attributes
int m_Verbosity = 0
SphenixClient * cdbclient = nullptr
std::string m_CachedGlobalTag
std::set< std::string > m_PayloadTypeCache
Detailed Description
Definition at line 10 of file CDBUtils.h.
View newest version in sPHENIX GitHub at line 10 of file CDBUtils.h
Constructor & Destructor Documentation
CDBUtils::CDBUtils ()
Definition at line 10 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 10 of file CDBUtils.cc
CDBUtils::CDBUtils (const std::string & globaltag) explicit
Definition at line 15 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 15 of file CDBUtils.cc
CDBUtils::CDBUtils (const CDBUtils &) explicit delete
virtual CDBUtils::~CDBUtils () virtual default
Member Function Documentation
void CDBUtils::clearCache ()
Definition at line 56 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 56 of file CDBUtils.cc
References cdbclient.
Referenced by clearCache().
int CDBUtils::cloneGlobalTag (const std::string & source, const std::string & target)
Definition at line 93 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 93 of file CDBUtils.cc
References cdbclient, and it.
Referenced by cloneGlobalTag().
int CDBUtils::createGlobalTag (const std::string & tagname)
Definition at line 20 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 20 of file CDBUtils.cc
References cdbclient.
Referenced by createGlobalTag(), and TPCPedestalCalibration::NewCDBGlobalTag().
int CDBUtils::createPayloadType (const std::string & domain)
Definition at line 69 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 69 of file CDBUtils.cc
References cdbclient, and SphenixClient::createDomain().
Referenced by TPCPedestalCalibration::CDBInsert(), createPayloadType(), and TestCDBInsert().
int CDBUtils::deleteGlobalTag (const std::string & tagname)
Definition at line 29 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 29 of file CDBUtils.cc
References cdbclient.
Referenced by deleteGlobalTag().
int CDBUtils::deletePayloadIOV (const std::string & pl_type, uint64_t iov_start)
Definition at line 205 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 205 of file CDBUtils.cc
References cdbclient, and SphenixClient::deletePayloadIOV().
Referenced by deletePayloadIOV().
int CDBUtils::deletePayloadIOV (const std::string & pl_type, uint64_t iov_start, uint64_t iov_end)
Definition at line 222 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 222 of file CDBUtils.cc
References cdbclient, and SphenixClient::deletePayloadIOV().
std::string CDBUtils::getUrl (const std::string & type, uint64_t iov)
Definition at line 63 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 63 of file CDBUtils.cc
References cdbclient, and SphenixClient::getUrl().
Referenced by getCalibration().
int CDBUtils::insertPayload (const std::string & pl_type, const std::string & file_url, uint64_t iov_start)
Definition at line 143 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 143 of file CDBUtils.cc
References cdbclient, SphenixClient::insertPayload(), and isGlobalTagSet().
Referenced by TPCPedestalCalibration::CDBInsert(), insertPayload(), and TestCDBInsert().
int CDBUtils::insertPayload (const std::string & pl_type, const std::string & file_url, uint64_t iov_start, uint64_t iov_end)
Definition at line 163 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 163 of file CDBUtils.cc
References cdbclient, SphenixClient::insertPayload(), and isGlobalTagSet().
bool CDBUtils::isGlobalTagSet ()
Definition at line 191 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 191 of file CDBUtils.cc
References cdbclient, and SphenixClient::isGlobalTagSet().
Referenced by insertPayload(), and insertPayload().
void CDBUtils::listGlobalTags ()
Definition at line 119 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 119 of file CDBUtils.cc
References cdbclient, and it.
Referenced by listGlobalTags().
void CDBUtils::listPayloadIOVs (uint64_t iov)
Definition at line 74 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 74 of file CDBUtils.cc
References cdbclient, SphenixClient::getPayloadIOVs(), and physmon_track_finding_ttbar::pt.
Referenced by listPayloadIOVs().
void CDBUtils::listPayloadTypes ()
Definition at line 131 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 131 of file CDBUtils.cc
References cdbclient, and it.
Referenced by listPayloadTypes().
int CDBUtils::lockGlobalTag (const std::string & tagname)
Definition at line 38 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 38 of file CDBUtils.cc
References cdbclient, and SphenixClient::lockGlobalTag().
Referenced by lockGlobalTag().
CDBUtils& CDBUtils::operator= (const CDBUtils &) delete
int CDBUtils::setGlobalTag (const std::string & tagname)
Definition at line 183 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 183 of file CDBUtils.cc
References cdbclient, and SphenixClient::setGlobalTag().
Referenced by setGlobalTag().
int CDBUtils::unlockGlobalTag (const std::string & tagname)
Definition at line 47 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 47 of file CDBUtils.cc
References cdbclient, and SphenixClient::unlockGlobalTag().
Referenced by unlockGlobalTag().
void CDBUtils::Verbosity (int i)
Definition at line 196 of file CDBUtils.cc.
View newest version in sPHENIX GitHub at line 196 of file CDBUtils.cc
References cdbclient, i, m_Verbosity, and SphenixClient::Verbosity().
Referenced by Verbosity().
int CDBUtils::Verbosity () const inline
Definition at line 38 of file CDBUtils.h.
View newest version in sPHENIX GitHub at line 38 of file CDBUtils.h
References m_Verbosity.
Member Data Documentation
SphenixClient* CDBUtils::cdbclient = nullptr private
Definition at line 44 of file CDBUtils.h.
View newest version in sPHENIX GitHub at line 44 of file CDBUtils.h
Referenced by clearCache(), cloneGlobalTag(), createGlobalTag(), createPayloadType(), deleteGlobalTag(), deletePayloadIOV(), getUrl(), insertPayload(), isGlobalTagSet(), listGlobalTags(), listPayloadIOVs(), listPayloadTypes(), lockGlobalTag(), setGlobalTag(), unlockGlobalTag(), and Verbosity().
std::string CDBUtils::m_CachedGlobalTag private
Definition at line 45 of file CDBUtils.h.
View newest version in sPHENIX GitHub at line 45 of file CDBUtils.h
std::set<std::string> CDBUtils::m_PayloadTypeCache private
Definition at line 46 of file CDBUtils.h.
View newest version in sPHENIX GitHub at line 46 of file CDBUtils.h
int CDBUtils::m_Verbosity = 0 private
Definition at line 43 of file CDBUtils.h.
View newest version in sPHENIX GitHub at line 43 of file CDBUtils.h
Referenced by Verbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/sphenixnpc/CDBUtils.h
coresoftware/blob/master/offline/database/sphenixnpc/CDBUtils.cc