Analysis Software: CMFlashClusterContainer Class Reference
CMFlashClusterContainer Class Reference abstract
Cluster container object.
#include <coresoftware/blob/master/offline/packages/trackbase/CMFlashClusterContainer.h>
Public Types
convenient shortuts
using Map = std::map< unsigned int, CMFlashCluster * >
using Iterator = Map::iterator
using ConstIterator = Map::const_iterator
using Range = std::pair< Iterator, Iterator >
using ConstRange = std::pair< ConstIterator, ConstIterator >
Public Member Functions
void Reset () override
reset method
void identify (std::ostream &=std::cout) const override
identify object
virtual void addClusterSpecifyKey (const unsigned int, CMFlashCluster *)=0
add a cluster with specific key
virtual void removeCluster (unsigned int)
remove cluster
virtual ConstRange getClusters () const =0
return all clusters
virtual CMFlashCluster * findCluster (unsigned int) const
find cluster matching given key
virtual unsigned int size () const
total number of clusters
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
CMFlashClusterContainer ()=default
constructor
Detailed Description
Cluster container object.
Definition at line 22 of file CMFlashClusterContainer.h.
View newest version in sPHENIX GitHub at line 22 of file CMFlashClusterContainer.h
Member Typedef Documentation
using CMFlashClusterContainer::ConstIterator = Map::const_iterator
Definition at line 30 of file CMFlashClusterContainer.h.
View newest version in sPHENIX GitHub at line 30 of file CMFlashClusterContainer.h
using CMFlashClusterContainer::ConstRange = std::pair<ConstIterator, ConstIterator>
Definition at line 32 of file CMFlashClusterContainer.h.
View newest version in sPHENIX GitHub at line 32 of file CMFlashClusterContainer.h
using CMFlashClusterContainer::Iterator = Map::iterator
Definition at line 29 of file CMFlashClusterContainer.h.
View newest version in sPHENIX GitHub at line 29 of file CMFlashClusterContainer.h
using CMFlashClusterContainer::Map = std::map<unsigned int, CMFlashCluster *>
Definition at line 28 of file CMFlashClusterContainer.h.
View newest version in sPHENIX GitHub at line 28 of file CMFlashClusterContainer.h
using CMFlashClusterContainer::Range = std::pair<Iterator, Iterator>
Definition at line 31 of file CMFlashClusterContainer.h.
View newest version in sPHENIX GitHub at line 31 of file CMFlashClusterContainer.h
Constructor & Destructor Documentation
CMFlashClusterContainer::CMFlashClusterContainer () protected default
constructor
Member Function Documentation
virtual void CMFlashClusterContainer::addClusterSpecifyKey (const unsigned int, CMFlashCluster *) pure virtual
add a cluster with specific key
Implemented in CMFlashClusterContainerv1.
Referenced by PHTpcCentralMembraneClusterizer::process_event().
virtual CMFlashCluster* CMFlashClusterContainer::findCluster (unsigned int) const inline virtual
find cluster matching given key
Reimplemented in CMFlashClusterContainerv1.
Definition at line 51 of file CMFlashClusterContainer.h.
View newest version in sPHENIX GitHub at line 51 of file CMFlashClusterContainer.h
virtual ConstRange CMFlashClusterContainer::getClusters () const pure virtual
return all clusters
Implemented in CMFlashClusterContainerv1.
Referenced by PHTpcCentralMembraneClusterizer::process_event(), and PHTpcCentralMembraneMatcher::process_event().
void CMFlashClusterContainer::identify (std::ostream & = std::cout) const inline override virtual
identify object
Reimplemented from PHObject.
Reimplemented in CMFlashClusterContainerv1.
Definition at line 39 of file CMFlashClusterContainer.h.
View newest version in sPHENIX GitHub at line 39 of file CMFlashClusterContainer.h
virtual void CMFlashClusterContainer::removeCluster (unsigned int) inline virtual
remove cluster
Reimplemented in CMFlashClusterContainerv1.
Definition at line 45 of file CMFlashClusterContainer.h.
View newest version in sPHENIX GitHub at line 45 of file CMFlashClusterContainer.h
void CMFlashClusterContainer::Reset () inline override virtual
reset method
Reimplemented from PHObject.
Reimplemented in CMFlashClusterContainerv1.
Definition at line 36 of file CMFlashClusterContainer.h.
View newest version in sPHENIX GitHub at line 36 of file CMFlashClusterContainer.h
virtual unsigned int CMFlashClusterContainer::size (void) const inline virtual
total number of clusters
Reimplemented in CMFlashClusterContainerv1.
Definition at line 54 of file CMFlashClusterContainer.h.
View newest version in sPHENIX GitHub at line 54 of file CMFlashClusterContainer.h
Referenced by PHTpcCentralMembraneMatcher::process_event().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase/CMFlashClusterContainer.h