Analysis Software: Fun4AllDummyInputManager Class Reference
Fun4AllDummyInputManager Class Reference
#include <coresoftware/blob/master/offline/framework/fun4all/Fun4AllDummyInputManager.h>
Public Member Functions
Fun4AllDummyInputManager (const std::string &name="DUMMY", const std::string &nodename="DST")
~Fun4AllDummyInputManager () override
int fileopen (const std::string &) override
int fileclose () override
int IsOpen () const override
int run (const int) override
int GetSyncObject (SyncObject **) override
int SyncIt (const SyncObject *) override
void setSyncManager (Fun4AllSyncManager *master) override
int PushBackEvents (const int nevt) override
int NoSyncPushBackEvents (const int nevt) override
int ResetFileList () override
Public Member Functions inherited from Fun4AllInputManager
~Fun4AllInputManager () override
virtual int ReadInRunNode (PHCompositeNode *)
std::string FileName () const
void FileName (const std::string &fn)
virtual int BranchSelect (const std::string &, const int)
virtual int setBranches ()
void Print (const std::string &what="ALL") const override
virtual int skip (const int nevt)
int AddFile (const std::string &filename)
int AddListFile (const std::string &filename, const int do_it=0)
int registerSubsystem (SubsysReco *subsystem)
virtual int RejectEvent ()
void Repeat (const int i=-1)
virtual int ResetEvent ()
virtual void SetRunNumber (const int runno)
virtual int RunNumber () const
void AddToFileOpened (const std::string &filename)
std::pair< std::list
< std::string >
::const_iterator, std::list
< std::string >
::const_iterator > FileOpenListBeginEnd ()
std::string InputNode ()
void InputNode (const std::string &innode)
std::string TopNodeName () const
bool FileListEmpty () const
virtual int SkipForThisManager (const int)
virtual int HasSyncObject () const
virtual std::string GetString (const std::string &) const
const std::list< std::string > GetFileList () const
const std::list< std::string > GetFileOpenedList () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
int m_NumEvents = 0
int m_SumEvents = 0
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from Fun4AllInputManager
Fun4AllInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
void UpdateFileList ()
int OpenNextFile ()
void IsOpen (const int i)
Fun4AllSyncManager * MySyncManager ()
Detailed Description
Definition at line 15 of file Fun4AllDummyInputManager.h.
View newest version in sPHENIX GitHub at line 15 of file Fun4AllDummyInputManager.h
Constructor & Destructor Documentation
Fun4AllDummyInputManager::Fun4AllDummyInputManager (const std::string & name = "DUMMY", const std::string & nodename = "DST")
Definition at line 9 of file Fun4AllDummyInputManager.cc.
View newest version in sPHENIX GitHub at line 9 of file Fun4AllDummyInputManager.cc
References Fun4AllInputManager::FileName().
Fun4AllDummyInputManager::~Fun4AllDummyInputManager () inline override
Definition at line 19 of file Fun4AllDummyInputManager.h.
View newest version in sPHENIX GitHub at line 19 of file Fun4AllDummyInputManager.h
Member Function Documentation
int Fun4AllDummyInputManager::fileclose () inline override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 21 of file Fun4AllDummyInputManager.h.
View newest version in sPHENIX GitHub at line 21 of file Fun4AllDummyInputManager.h
int Fun4AllDummyInputManager::fileopen (const std::string &) inline override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 20 of file Fun4AllDummyInputManager.h.
View newest version in sPHENIX GitHub at line 20 of file Fun4AllDummyInputManager.h
int Fun4AllDummyInputManager::GetSyncObject (SyncObject **) inline override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 24 of file Fun4AllDummyInputManager.h.
View newest version in sPHENIX GitHub at line 24 of file Fun4AllDummyInputManager.h
References Fun4AllReturnCodes::SYNC_NOOBJECT.
int Fun4AllDummyInputManager::IsOpen () const inline override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 22 of file Fun4AllDummyInputManager.h.
View newest version in sPHENIX GitHub at line 22 of file Fun4AllDummyInputManager.h
int Fun4AllDummyInputManager::NoSyncPushBackEvents (const int nevt) inline override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 28 of file Fun4AllDummyInputManager.h.
View newest version in sPHENIX GitHub at line 28 of file Fun4AllDummyInputManager.h
References PushBackEvents().
int Fun4AllDummyInputManager::PushBackEvents (const int nevt) override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 22 of file Fun4AllDummyInputManager.cc.
View newest version in sPHENIX GitHub at line 22 of file Fun4AllDummyInputManager.cc
References m_NumEvents, and m_SumEvents.
Referenced by NoSyncPushBackEvents().
int Fun4AllDummyInputManager::ResetFileList () override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 16 of file Fun4AllDummyInputManager.cc.
View newest version in sPHENIX GitHub at line 16 of file Fun4AllDummyInputManager.cc
References m_NumEvents.
int Fun4AllDummyInputManager::run (const int nevents) override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 44 of file Fun4AllDummyInputManager.cc.
View newest version in sPHENIX GitHub at line 44 of file Fun4AllDummyInputManager.cc
References Fun4AllSyncManager::CurrentEvent(), Fun4AllReturnCodes::EVENT_OK, m_NumEvents, m_SumEvents, Fun4AllInputManager::MySyncManager(), nevents(), and Fun4AllBase::Verbosity().
void Fun4AllDummyInputManager::setSyncManager (Fun4AllSyncManager * master) override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 29 of file Fun4AllDummyInputManager.cc.
View newest version in sPHENIX GitHub at line 29 of file Fun4AllDummyInputManager.cc
References Fun4AllSyncManager::CurrentRun(), PHFlag::get_IntFlag(), recoConsts::instance(), Fun4AllInputManager::MySyncManager(), runnumber, and Fun4AllInputManager::setSyncManager().
int Fun4AllDummyInputManager::SyncIt (const SyncObject *) inline override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 25 of file Fun4AllDummyInputManager.h.
View newest version in sPHENIX GitHub at line 25 of file Fun4AllDummyInputManager.h
References Fun4AllReturnCodes::SYNC_OK.
Member Data Documentation
int Fun4AllDummyInputManager::m_NumEvents = 0 private
Definition at line 32 of file Fun4AllDummyInputManager.h.
View newest version in sPHENIX GitHub at line 32 of file Fun4AllDummyInputManager.h
Referenced by PushBackEvents(), ResetFileList(), and run().
int Fun4AllDummyInputManager::m_SumEvents = 0 private
Definition at line 33 of file Fun4AllDummyInputManager.h.
View newest version in sPHENIX GitHub at line 33 of file Fun4AllDummyInputManager.h
Referenced by PushBackEvents(), and run().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4all/Fun4AllDummyInputManager.h
coresoftware/blob/master/offline/framework/fun4all/Fun4AllDummyInputManager.cc