Analysis Software: ActsExamples::Generic::LayerBuilderT< detector_element_t > Class Template Reference
ActsExamples::Generic::LayerBuilderT< detector_element_t > Class Template Reference
#include <acts/blob/sPHENIX/Examples/Detectors/GenericDetector/include/ActsExamples/GenericDetector/LayerBuilderT.hpp>
Classes
struct Config
Public Member Functions
LayerBuilderT (const Config &cfg, std::unique_ptr< const Acts::Logger > logger=Acts::getDefaultLogger("LayerBuilderT", Acts::Logging::INFO))
const Acts::LayerVector negativeLayers (const Acts::GeometryContext &gctx) const override
LayerBuilder interface method - returning the layers at negative side.
const Acts::LayerVector centralLayers (const Acts::GeometryContext &gctx) const override
LayerBuilder interface method - returning the central layers.
const Acts::LayerVector positiveLayers (const Acts::GeometryContext &gctx) const override
LayerBuilder interface method - returning the layers at positive side.
const std::string & identification () const override
ILayerBuilder method.
Public Member Functions inherited from Acts::ILayerBuilder
virtual ~ILayerBuilder ()=default
Virtual destructor.
Private Member Functions
const Acts::LayerVector constructEndcapLayers (const Acts::GeometryContext &gctx, int side) const
const Acts::Logger & logger () const
Private access to the logging instance.
Private Attributes
Config m_cfg
Configuration member.
std::unique_ptr< const
Acts::Logger > m_logger
the logging instance
Detailed Description
template<typename detector_element_t>
class ActsExamples::Generic::LayerBuilderT< detector_element_t >
The LayerBuilderT is able to build cylinder & disc layers from hard-coded input. This is meant for the simple detector examples.
Definition at line 44 of file LayerBuilderT.hpp.
View newest version in sPHENIX GitHub at line 44 of file LayerBuilderT.hpp
Constructor & Destructor Documentation
template<typename detector_element_t > ActsExamples::Generic::LayerBuilderT< detector_element_t >::LayerBuilderT (const Config & cfg, std::unique_ptr< const Acts::Logger > logger = Acts::getDefaultLogger("LayerBuilderT< detector_element_t >", Acts::Logging::INFO))
Constructor
Parameters
glbConfig is the configuration class
Definition at line 183 of file LayerBuilderT.hpp.
View newest version in sPHENIX GitHub at line 183 of file LayerBuilderT.hpp
Member Function Documentation
template<typename detector_element_t > const Acts::LayerVector ActsExamples::Generic::LayerBuilderT< detector_element_t >::centralLayers (const Acts::GeometryContext & gctx) const override virtual
LayerBuilder interface method - returning the central layers.
Implements Acts::ILayerBuilder.
Definition at line 123 of file LayerBuilderT.hpp.
View newest version in sPHENIX GitHub at line 123 of file LayerBuilderT.hpp
References ACTS_VERBOSE, Acts::Surface::assignSurfaceMaterial(), and m_cfg().
template<typename detector_element_t > const Acts::LayerVector ActsExamples::Generic::LayerBuilderT< detector_element_t >::constructEndcapLayers (const Acts::GeometryContext & gctx, int side) const private
the layer is created
Definition at line 190 of file LayerBuilderT.hpp.
View newest version in sPHENIX GitHub at line 190 of file LayerBuilderT.hpp
References ACTS_VERBOSE, Acts::Surface::assignSurfaceMaterial(), and m_cfg().
template<typename detector_element_t > const std::string& ActsExamples::Generic::LayerBuilderT< detector_element_t >::identification () const inline override virtual
ILayerBuilder method.
Implements Acts::ILayerBuilder.
Definition at line 104 of file LayerBuilderT.hpp.
View newest version in sPHENIX GitHub at line 104 of file LayerBuilderT.hpp
References ActsExamples::Generic::LayerBuilderT< detector_element_t >::Config::layerIdentification, and ActsExamples::Generic::LayerBuilderT< detector_element_t >::m_cfg.
template<typename detector_element_t > const Acts::Logger& ActsExamples::Generic::LayerBuilderT< detector_element_t >::logger () const inline private
Private access to the logging instance.
Definition at line 116 of file LayerBuilderT.hpp.
View newest version in sPHENIX GitHub at line 116 of file LayerBuilderT.hpp
References ActsExamples::Generic::LayerBuilderT< detector_element_t >::m_logger.
template<typename detector_element_t > const Acts::LayerVector ActsExamples::Generic::LayerBuilderT< detector_element_t >::negativeLayers (const Acts::GeometryContext & gctx) const override virtual
LayerBuilder interface method - returning the layers at negative side.
Implements Acts::ILayerBuilder.
Definition at line 171 of file LayerBuilderT.hpp.
View newest version in sPHENIX GitHub at line 171 of file LayerBuilderT.hpp
template<typename detector_element_t > const Acts::LayerVector ActsExamples::Generic::LayerBuilderT< detector_element_t >::positiveLayers (const Acts::GeometryContext & gctx) const override virtual
LayerBuilder interface method - returning the layers at positive side.
Implements Acts::ILayerBuilder.
Definition at line 177 of file LayerBuilderT.hpp.
View newest version in sPHENIX GitHub at line 177 of file LayerBuilderT.hpp
Member Data Documentation
template<typename detector_element_t > Config ActsExamples::Generic::LayerBuilderT< detector_element_t >::m_cfg private
Configuration member.
Definition at line 113 of file LayerBuilderT.hpp.
View newest version in sPHENIX GitHub at line 113 of file LayerBuilderT.hpp
Referenced by ActsExamples::Generic::LayerBuilderT< detector_element_t >::identification().
template<typename detector_element_t > std::unique_ptr<const Acts::Logger> ActsExamples::Generic::LayerBuilderT< detector_element_t >::m_logger private
the logging instance
Definition at line 119 of file LayerBuilderT.hpp.
View newest version in sPHENIX GitHub at line 119 of file LayerBuilderT.hpp
Referenced by ActsExamples::Generic::LayerBuilderT< detector_element_t >::logger().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Examples/Detectors/GenericDetector/include/ActsExamples/GenericDetector/LayerBuilderT.hpp