Analysis Software: PHG4TpcEndCapDisplayAction Class Reference
PHG4TpcEndCapDisplayAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcEndCapDisplayAction.h>
Public Member Functions
PHG4TpcEndCapDisplayAction (const std::string &name)
~PHG4TpcEndCapDisplayAction () override
void ApplyDisplayAction (G4VPhysicalVolume *physvol) override
ApplyDisplayAction method.
void AddVolume (G4LogicalVolume *logvol, const std::string &mat)
Public Member Functions inherited from PHG4DisplayAction
PHG4DisplayAction ()=delete
constructor
PHG4DisplayAction (const std::string &name)
virtual ~PHG4DisplayAction ()
destructor
virtual void SetName (const std::string &name)
virtual std::string GetName () const
virtual void Print (const std::string &="ALL")
Private Attributes
std::map< G4LogicalVolume
*, std::string > m_LogicalVolumeMap
std::vector< G4VisAttributes * > m_VisAttVec
Additional Inherited Members
Public Types inherited from PHG4DisplayAction
enum CheckReturnCodes { ABORT = -1, FAILED = 0, ACCEPT = 1 }
Protected Member Functions inherited from PHG4DisplayAction
int FindVolumes (G4VPhysicalVolume *physvol)
find FindVolume method
virtual int CheckVolume (G4VPhysicalVolume *)
find CheckVolume method
virtual void ApplyVisAttributes (G4VPhysicalVolume *)
ApplyVisAttributes method.
Detailed Description
Definition at line 16 of file PHG4TpcEndCapDisplayAction.h.
View newest version in sPHENIX GitHub at line 16 of file PHG4TpcEndCapDisplayAction.h
Constructor & Destructor Documentation
PHG4TpcEndCapDisplayAction::PHG4TpcEndCapDisplayAction (const std::string & name) explicit
Definition at line 14 of file PHG4TpcEndCapDisplayAction.cc.
View newest version in sPHENIX GitHub at line 14 of file PHG4TpcEndCapDisplayAction.cc
PHG4TpcEndCapDisplayAction::~PHG4TpcEndCapDisplayAction () override
Definition at line 19 of file PHG4TpcEndCapDisplayAction.cc.
View newest version in sPHENIX GitHub at line 19 of file PHG4TpcEndCapDisplayAction.cc
References it, and m_VisAttVec.
Member Function Documentation
void PHG4TpcEndCapDisplayAction::AddVolume (G4LogicalVolume * logvol, const std::string & mat) inline
Definition at line 24 of file PHG4TpcEndCapDisplayAction.h.
View newest version in sPHENIX GitHub at line 24 of file PHG4TpcEndCapDisplayAction.h
References m_LogicalVolumeMap.
Referenced by PHG4TpcEndCapDetector::AddLayer(), PHG4TpcEndCapDetector::ConstructElectronics(), and PHG4TpcEndCapDetector::ConstructWagonWheel().
void PHG4TpcEndCapDisplayAction::ApplyDisplayAction (G4VPhysicalVolume * physvol) override virtual
ApplyDisplayAction method.
pure virtual - has to be implemented by derived class creates and set VisAttributes for volumes
Parameters
[in] physvol starting volume in hierarchy (typically world volume)
Implements PHG4DisplayAction.
Definition at line 28 of file PHG4TpcEndCapDisplayAction.cc.
View newest version in sPHENIX GitHub at line 28 of file PHG4TpcEndCapDisplayAction.cc
References it, m_LogicalVolumeMap, m_VisAttVec, and PHG4Utils::SetColour().
Member Data Documentation
std::map<G4LogicalVolume *, std::string> PHG4TpcEndCapDisplayAction::m_LogicalVolumeMap private
Definition at line 27 of file PHG4TpcEndCapDisplayAction.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4TpcEndCapDisplayAction.h
Referenced by AddVolume(), and ApplyDisplayAction().
std::vector<G4VisAttributes *> PHG4TpcEndCapDisplayAction::m_VisAttVec private
Definition at line 28 of file PHG4TpcEndCapDisplayAction.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4TpcEndCapDisplayAction.h
Referenced by ApplyDisplayAction(), and ~PHG4TpcEndCapDisplayAction().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcEndCapDisplayAction.h
coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcEndCapDisplayAction.cc