Analysis Software: Acts::Transform3JsonConverter Namespace Reference
Acts::Transform3JsonConverter Namespace Reference
Classes
struct Options
The options for the transform converter.
Functions
nlohmann::json toJson (const Transform3 &t, const Options &options={})
The Transform converter to json.
Transform3 fromJson (const nlohmann::json &jTransform)
The Transform converter from json.
Function Documentation
Acts::Transform3 Acts::Transform3JsonConverter::fromJson (const nlohmann::json & jVolumeBounds)
The Transform converter from json.
Parameters
jTransform the transform json transformation
Returns
a transform object
Conversion to surfaceBounds from json
The type is given as a template argument in order to be able to construct the correct fitting types for surfaces.
Parameters
j the read-in json object
Returns
a shared_ptr to a surface object for type polymorphism
Conversion to volume bounds from json
The type is given as a template argument in order to be able to construct the correct fitting types for surfaces.
Parameters
jVolumeBounds the read-in json object
Returns
a unique_ptr to a volume bounds object for type polymorphism
Conversion to volume bounds from json
Parameters
jVolumeBounds the read-in json object
Returns
a unique_ptr to a volume bounds object for type polymorphism
Definition at line 78 of file AlgebraJsonConverter.cpp.
View newest version in sPHENIX GitHub at line 78 of file AlgebraJsonConverter.cpp
References Acts::from_json(), and t.
Referenced by BOOST_AUTO_TEST_CASE(), Acts::from_json(), Acts::DetectorJsonConverter::fromJson(), Acts::DetectorVolumeJsonConverter::fromJson(), Acts::PortalJsonConverter::fromJson(), Acts::SurfaceJsonConverter::fromJson(), Acts::IndexedSurfacesJsonConverter::fromJson(), and Acts::surfaceFromJsonT().
nlohmann::json Acts::Transform3JsonConverter::toJson (const Transform3 & t, const Options & options = {})
The Transform converter to json.
Parameters
t the transform to be converted
options transformation options
Returns
a json object representing the transform
Definition at line 51 of file AlgebraJsonConverter.cpp.
View newest version in sPHENIX GitHub at line 51 of file AlgebraJsonConverter.cpp
References translation(), Acts::Transform3JsonConverter::Options::transpose, and Acts::Transform3JsonConverter::Options::writeIdentity.
Referenced by BOOST_AUTO_TEST_CASE(), Acts::IndexedSurfacesJsonConverter::convertImpl(), Acts::to_json(), Acts::DetectorJsonConverter::toJson(), Acts::PortalJsonConverter::toJson(), Acts::DetectorVolumeJsonConverter::toJson(), Acts::SurfaceJsonConverter::toJson(), Acts::DetectorVolumeJsonConverter::toJsonDetray(), and Acts::SurfaceJsonConverter::toJsonDetray().