Analysis Software: TSQLResultSet Class Reference
TSQLResultSet Class Reference abstract
#include <RDBC/blob/master/include/RDBC/TSQLResultSet.h>
Public Member Functions
virtual ~TSQLResultSet ()
virtual Bool_t WasNull ()=0
virtual TString GetString (Int_t columnIndex)=0
virtual Bool_t GetBoolean (Int_t columnIndex)=0
virtual Char_t GetByte (Int_t columnIndex)=0
virtual Short_t GetShort (Int_t columnIndex)=0
virtual Int_t GetInt (Int_t columnIndex)=0
virtual Long_t GetLong (Int_t columnIndex)=0
virtual Float_t GetFloat (Int_t columnIndex)=0
virtual Double_t GetDouble (Int_t columnIndex)=0
virtual TArrayC GetBytes (Int_t columnIndex)=0
virtual TSQLDate GetDate (Int_t columnIndex)=0
virtual TSQLTime GetTime (Int_t columnIndex)=0
virtual TSQLTimestamp GetTimestamp (Int_t columnIndex)=0
virtual TBuffer * GetAsciiStream (Int_t columnIndex)=0
virtual TBuffer * GetBinaryStream (Int_t columnIndex)=0
virtual TObject * GetObject (Int_t columnIndex)=0
virtual TString GetString (const TString &columnName)=0
virtual Bool_t GetBoolean (const TString &columnName)=0
virtual Char_t GetByte (const TString &columnName)=0
virtual Short_t GetShort (const TString &columnName)=0
virtual Int_t GetInt (const TString &columnName)=0
virtual Long_t GetLong (const TString &columnName)=0
virtual Float_t GetFloat (const TString &columnName)=0
virtual Double_t GetDouble (const TString &columnName)=0
virtual TArrayC GetBytes (const TString &columnName)=0
virtual TSQLDate GetDate (const TString &columnName)=0
virtual TSQLTime GetTime (const TString &columnName)=0
virtual TSQLTimestamp GetTimestamp (const TString &columnName)=0
virtual TBuffer * GetAsciiStream (const TString &columnName)=0
virtual TBuffer * GetBinaryStream (const TString &columnName)=0
virtual TObject * GetObject (const TString &columnName)=0
virtual TString GetCursorName ()=0
virtual Int_t FindColumn (const TString &columnName)=0
virtual Bool_t IsBeforeFirst ()=0
virtual Bool_t IsAfterLast ()=0
virtual Bool_t IsFirst ()=0
virtual Bool_t IsLast ()=0
virtual void BeforeFirst ()=0
virtual void AfterLast ()=0
virtual void SetFetchDirection (Int_t direction)=0
virtual Int_t GetFetchDirection ()=0
virtual Int_t GetRow ()=0
virtual void SetFetchSize (Int_t rows)=0
virtual Int_t GetFetchSize ()=0
virtual Int_t GetType ()=0
virtual Int_t GetConcurrency ()=0
virtual void UpdateNull (Int_t columnIndex)=0
virtual void UpdateBoolean (Int_t columnIndex, Bool_t x)=0
virtual void UpdateByte (Int_t columnIndex, Char_t x)=0
virtual void UpdateShort (Int_t columnIndex, Short_t x)=0
virtual void UpdateInt (Int_t columnIndex, Int_t x)=0
virtual void UpdateLong (Int_t columnIndex, Long_t x)=0
virtual void UpdateFloat (Int_t columnIndex, Float_t x)=0
virtual void UpdateDouble (Int_t columnIndex, Double_t x)=0
virtual void UpdateString (Int_t columnIndex, const TString &x)=0
virtual void UpdateBytes (Int_t columnIndex, const TArrayC &x)=0
virtual void UpdateDate (Int_t columnIndex, const TSQLDate &x)=0
virtual void UpdateTime (Int_t columnIndex, const TSQLTime &x)=0
virtual void UpdateTimestamp (Int_t columnIndex, const TSQLTimestamp &x)=0
virtual void UpdateAsciiStream (Int_t columnIndex, TBuffer *x, Int_t length)=0
virtual void UpdateBinaryStream (Int_t columnIndex, TBuffer *x, Int_t length)=0
virtual void UpdateObject (Int_t columnIndex, TObject *x)=0
virtual void UpdateNull (const TString &columnName)=0
virtual void UpdateBoolean (const TString &columnName, Bool_t x)=0
virtual void UpdateByte (const TString &columnName, Char_t x)=0
virtual void UpdateShort (const TString &columnName, Short_t x)=0
virtual void UpdateInt (const TString &columnName, Int_t x)=0
virtual void UpdateLong (const TString &columnName, Long_t x)=0
virtual void UpdateFloat (const TString &columnName, Float_t x)=0
virtual void UpdateDouble (const TString &columnName, Double_t x)=0
virtual void UpdateString (const TString &columnName, const TString &x)=0
virtual void UpdateBytes (const TString &columnName, const TArrayC &x)=0
virtual void UpdateDate (const TString &columnName, const TSQLDate &x)=0
virtual void UpdateTime (const TString &columnName, const TSQLTime &x)=0
virtual void UpdateTimestamp (const TString &columnName, const TSQLTimestamp &x)=0
virtual void UpdateAsciiStream (const TString &columnName, TBuffer *x, Int_t length)=0
virtual void UpdateBinaryStream (const TString &columnName, TBuffer *x, Int_t length)=0
virtual void UpdateObject (const TString &columnName, TObject *x)=0
virtual Bool_t RowUpdated ()=0
virtual Bool_t RowInserted ()=0
virtual Bool_t RowDeleted ()=0
virtual void InsertRow ()=0
virtual void UpdateRow ()=0
virtual void DeleteRow ()=0
virtual void RefreshRow ()=0
virtual void CancelRowUpdates ()=0
virtual void MoveToInsertRow ()=0
virtual void MoveToCurrentRow ()=0
virtual void Close (const Option_t *option="")=0
virtual TSQLRow * Next ()=0
virtual TSQLRow * Previous ()=0
virtual TSQLRow * First ()=0
virtual TSQLRow * Last ()=0
virtual TSQLRow * Absolute (Int_t row)=0
virtual TSQLRow * Relative (Int_t rows)=0
virtual TSQLResultSetMetaData * GetMetaData ()=0
virtual TSQLStatement * GetStatement () const
virtual Int_t GetFieldCount ()
virtual const char * GetFieldName (Int_t field)
virtual void Print (Option_t *option="") const
virtual TTree * Tree (Int_t begin=0, Int_t end=0)
Public Member Functions inherited from TSQL
TSQL (void *imp=0)
virtual ~TSQL ()
virtual void Throw (TSQLException *e)
TList * GetWarnings () const
void ClearWarnings ()
virtual Bool_t IsValid () const
Protected Member Functions
TSQLResultSet (TSQLStatement *stmt=0, void *imp=0)
Protected Attributes
RDBCRow * fRow
TSQLStatement * fStatement
TSQLResultSetMetaData * fMetaData
Protected Attributes inherited from TSQL
TList * fWarnings
void * fImp
Friends
class TSQLStatement
Additional Inherited Members
Static Public Member Functions inherited from TSQL
static Bool_t SetHandler (const TString &handler)
static Bool_t UnsetHandler (const TString &handler="")
Detailed Description
Definition at line 40 of file TSQLResultSet.h.
View newest version in sPHENIX GitHub at line 40 of file TSQLResultSet.h
Constructor & Destructor Documentation
TSQLResultSet::TSQLResultSet (TSQLStatement * stmt = 0, void * imp = 0) protected
Definition at line 223 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 223 of file MySQLResultSet.cxx
References TSQL::fImp, fMetaData, MySQLResultSetPrivate::fMYSQL_RES, fRow, and fStatement.
TSQLResultSet::~TSQLResultSet () virtual
Definition at line 234 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 234 of file MySQLResultSet.cxx
References TSQL::fImp, fMetaData, and fRow.
Member Function Documentation
TSQLRow * TSQLResultSet::Absolute (Int_t row) pure virtual
Implemented in ODBCResultSet.
Definition at line 2168 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 2168 of file MySQLResultSet.cxx
Referenced by Print(), and Tree().
void TSQLResultSet::AfterLast () pure virtual
Implemented in ODBCResultSet.
Definition at line 1182 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1182 of file MySQLResultSet.cxx
References MySQLResultSetPrivate::fDoingUpdates, TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, MySQLResultSetPrivate::fOnInsertRow, and Jetscape::null.
Referenced by Compare().
void TSQLResultSet::BeforeFirst () pure virtual
Implemented in ODBCResultSet.
Definition at line 1159 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1159 of file MySQLResultSet.cxx
References MySQLResultSetPrivate::fCurrentRow, MySQLResultSetPrivate::fDoingUpdates, TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, MySQLResultSetPrivate::fOnInsertRow, and Jetscape::null.
void TSQLResultSet::CancelRowUpdates () pure virtual
Implemented in ODBCResultSet.
Definition at line 2039 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 2039 of file MySQLResultSet.cxx
void TSQLResultSet::Close (const Option_t * option = "") pure virtual
Definition at line 2331 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 2331 of file MySQLResultSet.cxx
References TSQL::fImp, fMetaData, and fRow.
Referenced by TSQLStatement::Execute(), and TSQLStatement::ExecuteQuery().
void TSQLResultSet::DeleteRow () pure virtual
Implemented in ODBCResultSet.
Definition at line 2002 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 2002 of file MySQLResultSet.cxx
Int_t TSQLResultSet::FindColumn (const TString & columnName) pure virtual
Implemented in ODBCResultSet.
Definition at line 1067 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1067 of file MySQLResultSet.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and i.
Referenced by GetAsciiStream(), GetBinaryStream(), GetBoolean(), GetByte(), GetBytes(), GetDate(), GetDouble(), GetFloat(), GetInt(), GetLong(), GetObject(), GetShort(), GetString(), GetTime(), GetTimestamp(), UpdateAsciiStream(), UpdateBinaryStream(), UpdateBoolean(), UpdateByte(), UpdateBytes(), UpdateDate(), UpdateDouble(), UpdateFloat(), UpdateInt(), UpdateLong(), UpdateNull(), UpdateObject(), UpdateShort(), UpdateString(), UpdateTime(), and UpdateTimestamp().
TSQLRow * TSQLResultSet::First () pure virtual
Implemented in ODBCResultSet.
Definition at line 2135 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 2135 of file MySQLResultSet.cxx
References con, TSQLStatement::fConnection, MySQLResultSetPrivate::fCurrentRow, MySQLResultSetPrivate::fDoingUpdates, TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, MySQLResultSetPrivate::fOnInsertRow, fRow, fStatement, kTYPE_FORWARD_ONLY, Acts::IntegrationTest::L, and TSQL::Throw().
Referenced by Compare(), and DbForm::First().
TBuffer * TSQLResultSet::GetAsciiStream (Int_t columnIndex) pure virtual
Implemented in ODBCResultSet.
Definition at line 645 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 645 of file MySQLResultSet.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Referenced by GetAsciiStream().
TBuffer * TSQLResultSet::GetAsciiStream (const TString & columnName) pure virtual
Implemented in ODBCResultSet.
Definition at line 957 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 957 of file MySQLResultSet.cxx
References FindColumn(), and GetAsciiStream().
TBuffer * TSQLResultSet::GetBinaryStream (Int_t columnIndex) pure virtual
Implemented in ODBCResultSet.
Definition at line 687 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 687 of file MySQLResultSet.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Referenced by GetBinaryStream(), and GetObject().
TBuffer * TSQLResultSet::GetBinaryStream (const TString & columnName) pure virtual
Implemented in ODBCResultSet.
Definition at line 984 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 984 of file MySQLResultSet.cxx
References FindColumn(), and GetBinaryStream().
Bool_t TSQLResultSet::GetBoolean (Int_t columnIndex) pure virtual
Implemented in ODBCResultSet.
Definition at line 294 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 294 of file MySQLResultSet.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, str, and TSQL::Throw().
Referenced by GetBoolean().
Bool_t TSQLResultSet::GetBoolean (const TString & columnName) pure virtual
Implemented in ODBCResultSet.
Definition at line 776 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 776 of file MySQLResultSet.cxx
References FindColumn(), and GetBoolean().
Char_t TSQLResultSet::GetByte (Int_t columnIndex) pure virtual
Implemented in ODBCResultSet.
Definition at line 327 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 327 of file MySQLResultSet.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, str, and TSQL::Throw().
Referenced by GetByte().
Char_t TSQLResultSet::GetByte (const TString & columnName) pure virtual
Implemented in ODBCResultSet.
Definition at line 792 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 792 of file MySQLResultSet.cxx
References FindColumn(), and GetByte().
TArrayC TSQLResultSet::GetBytes (Int_t columnIndex) pure virtual
Implemented in ODBCResultSet.
Definition at line 521 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 521 of file MySQLResultSet.cxx
References TauVsDIS_MachineLearning_Differentiation::array, TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Referenced by GetBytes().
TArrayC TSQLResultSet::GetBytes (const TString & columnName) pure virtual
Implemented in ODBCResultSet.
Definition at line 888 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 888 of file MySQLResultSet.cxx
References FindColumn(), and GetBytes().
Int_t TSQLResultSet::GetConcurrency () pure virtual
Implemented in ODBCResultSet.
Definition at line 1306 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1306 of file MySQLResultSet.cxx
TString TSQLResultSet::GetCursorName () pure virtual
Implemented in ODBCResultSet.
Definition at line 1027 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1027 of file MySQLResultSet.cxx
TSQLDate TSQLResultSet::GetDate (Int_t columnIndex) pure virtual
Implemented in ODBCResultSet.
Definition at line 552 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 552 of file MySQLResultSet.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Referenced by GetDate().
TSQLDate TSQLResultSet::GetDate (const TString & columnName) pure virtual
Implemented in ODBCResultSet.
Definition at line 906 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 906 of file MySQLResultSet.cxx
References FindColumn(), and GetDate().
Double_t TSQLResultSet::GetDouble (Int_t columnIndex) pure virtual
Implemented in ODBCResultSet.
Definition at line 493 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 493 of file MySQLResultSet.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Referenced by GetDouble(), and Tree().
Double_t TSQLResultSet::GetDouble (const TString & columnName) pure virtual
Implemented in ODBCResultSet.
Definition at line 872 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 872 of file MySQLResultSet.cxx
References FindColumn(), and GetDouble().
virtual Int_t TSQLResultSet::GetFetchDirection () pure virtual
Implemented in ODBCResultSet.
Int_t TSQLResultSet::GetFetchSize () pure virtual
Implemented in ODBCResultSet.
Definition at line 1275 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1275 of file MySQLResultSet.cxx
Int_t TSQLResultSet::GetFieldCount () virtual
Definition at line 2307 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 2307 of file MySQLResultSet.cxx
References TSQL::fImp, and MySQLResultSetPrivate::fMYSQL_RES.
const char * TSQLResultSet::GetFieldName (Int_t field) virtual
Definition at line 2316 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 2316 of file MySQLResultSet.cxx
References TSQL::fImp, and MySQLResultSetPrivate::fMYSQL_RES.
Float_t TSQLResultSet::GetFloat (Int_t columnIndex) pure virtual
Implemented in ODBCResultSet.
Definition at line 465 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 465 of file MySQLResultSet.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Referenced by GetFloat(), RDBCemp(), RDBCTestInt(), and Tree().
Float_t TSQLResultSet::GetFloat (const TString & columnName) pure virtual
Implemented in ODBCResultSet.
Definition at line 856 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 856 of file MySQLResultSet.cxx
References FindColumn(), and GetFloat().
Int_t TSQLResultSet::GetInt (Int_t columnIndex) pure virtual
Implemented in ODBCResultSet.
Definition at line 400 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 400 of file MySQLResultSet.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Referenced by PgPostBankBackupManager::CleanTable(), Compare(), RDBCBench::DoOne(), PgPostBankBackupManager::dumpTable(), PgPostBankBackupManager::fetchAllBank2TFile(), PgPostBankManager::fetchBank(), GetInt(), PgPostBankBackupManager::getListOfRId(), PgPostBankBackupManager::getTotalRowCount(), PgPostCalBankIterator::next(), RDBCemp(), RDBCfirst(), RDBCTestInt(), PgPostBankBackupManager::SQLResultSet2BackupStorage(), and Tree().
Int_t TSQLResultSet::GetInt (const TString & columnName) pure virtual
Implemented in ODBCResultSet.
Definition at line 824 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 824 of file MySQLResultSet.cxx
References FindColumn(), and GetInt().
Long_t TSQLResultSet::GetLong (Int_t columnIndex) pure virtual
Implemented in ODBCResultSet.
Definition at line 428 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 428 of file MySQLResultSet.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, Acts::IntegrationTest::L, G4PLUGDOOR::length, TSQL::Throw(), and value.
Referenced by PgPostBankBackupManager::dumpTable(), PgPostBankManager::fetchBank(), GetLong(), PgPostCalBankIterator::next(), RDBCfirst(), and PgPostBankBackupManager::SQLResultSet2BackupStorage().
Long_t TSQLResultSet::GetLong (const TString & columnName) pure virtual
Implemented in ODBCResultSet.
Definition at line 840 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 840 of file MySQLResultSet.cxx
References FindColumn(), and GetLong().
TSQLResultSetMetaData * TSQLResultSet::GetMetaData () pure virtual
Implemented in ODBCResultSet.
Definition at line 1053 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1053 of file MySQLResultSet.cxx
References TSQL::fImp, and fMetaData.
Referenced by ClassImpQ(), DbForm::HandleExecuteQuery(), RDBCTestMetaData(), and SaveAsCSV().
TObject * TSQLResultSet::GetObject (Int_t columnIndex) pure virtual
Implemented in ODBCResultSet.
Definition at line 727 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 727 of file MySQLResultSet.cxx
References KFPMath::b, TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, GetBinaryStream(), and TSQL::Throw().
Referenced by PgPostBankBackupManager::dumpTable(), PgPostBankManager::fetchBank(), GetObject(), PgPostCalBankIterator::next(), RDBCconsumer(), and PgPostBankBackupManager::SQLResultSet2BackupStorage().
TObject * TSQLResultSet::GetObject (const TString & columnName) pure virtual
Implemented in ODBCResultSet.
Definition at line 1012 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1012 of file MySQLResultSet.cxx
References FindColumn(), and GetObject().
Int_t TSQLResultSet::GetRow () pure virtual
Implemented in ODBCResultSet.
Definition at line 1204 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1204 of file MySQLResultSet.cxx
References MySQLResultSetPrivate::fCurrentRow, TSQL::fImp, and MySQLResultSetPrivate::fMYSQL_RES.
Referenced by Compare(), DbForm::DisplayResults(), PgPostBankBackupManager::fetchAllBank2TFile(), DbForm::HandleExecuteQuery(), Print(), RDBCemp(), PgPostBankBackupManager::SQLResultSet2BackupStorage(), and Tree().
Short_t TSQLResultSet::GetShort (Int_t columnIndex) pure virtual
Implemented in ODBCResultSet.
Definition at line 372 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 372 of file MySQLResultSet.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Referenced by GetShort(), and Tree().
Short_t TSQLResultSet::GetShort (const TString & columnName) pure virtual
Implemented in ODBCResultSet.
Definition at line 808 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 808 of file MySQLResultSet.cxx
References FindColumn(), and GetShort().
TSQLStatement * TSQLResultSet::GetStatement () const inline virtual
Definition at line 150 of file TSQLResultSet.h.
View newest version in sPHENIX GitHub at line 150 of file TSQLResultSet.h
References fStatement.
TString TSQLResultSet::GetString (Int_t columnIndex) pure virtual
Implemented in ODBCResultSet.
Definition at line 266 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 266 of file MySQLResultSet.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Referenced by ClassImpQ(), Compare(), DbForm::DisplayResults(), PgPostBankBackupManager::dumpTable(), PgPostBankManager::fetchBank(), Fill(), GetString(), TSQLDatabaseMetaData::GetUserName(), TSQLImporter::LoadCatalog(), PgPostCalBankIterator::next(), Print(), RDBCconsumer(), RDBCemp(), RDBCfirst(), RDBCTestInt(), RDBCTestMetaData(), SaveAsCSV(), TRDBCServer::ServerInfo(), PgPostBankBackupManager::SQLResultSet2BackupStorage(), and Tree().
TString TSQLResultSet::GetString (const TString & columnName) pure virtual
Implemented in ODBCResultSet.
Definition at line 760 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 760 of file MySQLResultSet.cxx
References FindColumn(), and GetString().
TSQLTime TSQLResultSet::GetTime (Int_t columnIndex) pure virtual
Implemented in ODBCResultSet.
Definition at line 583 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 583 of file MySQLResultSet.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Referenced by GetTime().
TSQLTime TSQLResultSet::GetTime (const TString & columnName) pure virtual
Implemented in ODBCResultSet.
Definition at line 923 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 923 of file MySQLResultSet.cxx
References FindColumn(), and GetTime().
TSQLTimestamp TSQLResultSet::GetTimestamp (Int_t columnIndex) pure virtual
Implemented in ODBCResultSet.
Definition at line 614 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 614 of file MySQLResultSet.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Referenced by GetTimestamp().
TSQLTimestamp TSQLResultSet::GetTimestamp (const TString & columnName) pure virtual
Implemented in ODBCResultSet.
Definition at line 940 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 940 of file MySQLResultSet.cxx
References FindColumn(), and GetTimestamp().
Int_t TSQLResultSet::GetType () pure virtual
Implemented in ODBCResultSet.
Definition at line 1290 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1290 of file MySQLResultSet.cxx
References kTYPE_SCROLL_INSENSITIVE.
void TSQLResultSet::InsertRow () pure virtual
Implemented in ODBCResultSet.
Definition at line 1974 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1974 of file MySQLResultSet.cxx
Bool_t TSQLResultSet::IsAfterLast () pure virtual
Implemented in ODBCResultSet.
Definition at line 1105 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1105 of file MySQLResultSet.cxx
References TSQL::fImp, and MySQLResultSetPrivate::fMYSQL_RES.
Referenced by Compare(), DbForm::DisplayResults(), and DbForm::UpdateColumn().
Bool_t TSQLResultSet::IsBeforeFirst () pure virtual
Implemented in ODBCResultSet.
Definition at line 1088 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1088 of file MySQLResultSet.cxx
References TSQL::fImp, and MySQLResultSetPrivate::fMYSQL_RES.
Referenced by Compare(), DbForm::DisplayResults(), and DbForm::UpdateColumn().
Bool_t TSQLResultSet::IsFirst () pure virtual
Implemented in ODBCResultSet.
Definition at line 1122 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1122 of file MySQLResultSet.cxx
References TSQL::fImp, and MySQLResultSetPrivate::fMYSQL_RES.
Referenced by Compare().
Bool_t TSQLResultSet::IsLast () pure virtual
Implemented in ODBCResultSet.
Definition at line 1138 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1138 of file MySQLResultSet.cxx
References TSQL::fImp, and MySQLResultSetPrivate::fMYSQL_RES.
Referenced by Compare().
TSQLRow * TSQLResultSet::Last () pure virtual
Implemented in ODBCResultSet.
Definition at line 2290 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 2290 of file MySQLResultSet.cxx
References fRow.
Referenced by Compare(), and DbForm::Last().
void TSQLResultSet::MoveToCurrentRow () pure virtual
Implemented in ODBCResultSet.
Definition at line 2076 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 2076 of file MySQLResultSet.cxx
void TSQLResultSet::MoveToInsertRow () pure virtual
Implemented in ODBCResultSet.
Definition at line 2054 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 2054 of file MySQLResultSet.cxx
TSQLRow * TSQLResultSet::Next () pure virtual
Implemented in ODBCResultSet.
Definition at line 2106 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 2106 of file MySQLResultSet.cxx
References MySQLResultSetPrivate::fDoingUpdates, TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, MySQLResultSetPrivate::fOnInsertRow, and fRow.
Referenced by PgPostBankBackupManager::CleanTable(), RDBCBench::DoOne(), PgPostBankBackupManager::dumpTable(), PgPostBankBackupManager::fetchAllBank2TFile(), PgPostBankManager::fetchBank(), PgPostBankBackupManager::fetchBank(), Fill(), PgPostBankBackupManager::getListOfRId(), PgPostBankBackupManager::getTotalRowCount(), TSQLDatabaseMetaData::GetUserName(), PgPostBankBackupManager::isRIdExist(), TSQLImporter::LoadCatalog(), PgPostCalBankIterator::next(), DbForm::Next(), Print(), RDBCconsumer(), RDBCemp(), RDBCfirst(), RDBCTestInt(), RDBCTestMetaData(), SaveAsCSV(), TRDBCServer::ServerInfo(), and Tree().
TSQLRow * TSQLResultSet::Previous () pure virtual
Implemented in ODBCResultSet.
Definition at line 2269 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 2269 of file MySQLResultSet.cxx
References fRow.
Referenced by Compare(), and DbForm::Prev().
void TSQLResultSet::Print (Option_t * option = "") const virtual
Definition at line 2377 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 2377 of file MySQLResultSet.cxx
References Absolute(), TSQL::fImp, fMetaData, fStatement, TSQLResultSetMetaData::GetColumnCount(), TSQLResultSetMetaData::GetColumnDisplaySize(), TSQLResultSetMetaData::GetColumnName(), TSQLStatement::GetResultSetType(), GetRow(), GetString(), GetValueFromOption(), i, kTYPE_FORWARD_ONLY, Next(), str, and TSQL::Throw().
void TSQLResultSet::RefreshRow () pure virtual
Implemented in ODBCResultSet.
Definition at line 2014 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 2014 of file MySQLResultSet.cxx
TSQLRow * TSQLResultSet::Relative (Int_t rows) pure virtual
Implemented in ODBCResultSet.
Definition at line 2244 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 2244 of file MySQLResultSet.cxx
Bool_t TSQLResultSet::RowDeleted () pure virtual
Implemented in ODBCResultSet.
Definition at line 1364 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1364 of file MySQLResultSet.cxx
Bool_t TSQLResultSet::RowInserted () pure virtual
Implemented in ODBCResultSet.
Definition at line 1344 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1344 of file MySQLResultSet.cxx
Bool_t TSQLResultSet::RowUpdated () pure virtual
Implemented in ODBCResultSet.
Definition at line 1324 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1324 of file MySQLResultSet.cxx
virtual void TSQLResultSet::SetFetchDirection (Int_t direction) pure virtual
Implemented in ODBCResultSet.
void TSQLResultSet::SetFetchSize (Int_t rows) pure virtual
Implemented in ODBCResultSet.
Definition at line 1251 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1251 of file MySQLResultSet.cxx
References parse_cmake_options::rows.
TTree * TSQLResultSet::Tree (Int_t begin = 0, Int_t end = 0) virtual
Definition at line 2507 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 2507 of file MySQLResultSet.cxx
References Absolute(), fMetaData, fStatement, TSQLResultSetMetaData::GetColumnCount(), TSQLResultSetMetaData::GetColumnName(), TSQLResultSetMetaData::GetColumnType(), GetDouble(), GetFloat(), GetInt(), TSQLResultSetMetaData::GetPrecision(), TSQLStatement::GetResultSetType(), GetRow(), GetShort(), GetString(), TSQLResultSetMetaData::GetTableName(), i, kBIGINT, kBIT, kCHAR, kDATE, kDECIMAL, kDOUBLE, kFLOAT, kINTEGER, kLONGVARBINARY, kLONGVARCHAR, kNUMERIC, kREAL, kSMALLINT, kTIME, kTIMESTAMP, kTINYINT, kTYPE_FORWARD_ONLY, kVARBINARY, kVARCHAR, Acts::UnitConstants::mm, Next(), offset, str, t, Acts::Test::tmp(), tree, and parse_cmake_options::type.
void TSQLResultSet::UpdateAsciiStream (Int_t columnIndex, TBuffer * x, Int_t length) pure virtual
Implemented in ODBCResultSet.
Definition at line 1611 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1611 of file MySQLResultSet.cxx
Referenced by UpdateAsciiStream().
void TSQLResultSet::UpdateAsciiStream (const TString & columnName, TBuffer * x, Int_t length) pure virtual
Implemented in ODBCResultSet.
Definition at line 1913 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1913 of file MySQLResultSet.cxx
References FindColumn(), and UpdateAsciiStream().
void TSQLResultSet::UpdateBinaryStream (Int_t columnIndex, TBuffer * x, Int_t length) pure virtual
Implemented in ODBCResultSet.
Definition at line 1631 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1631 of file MySQLResultSet.cxx
Referenced by UpdateBinaryStream(), and UpdateObject().
void TSQLResultSet::UpdateBinaryStream (const TString & columnName, TBuffer * x, Int_t length) pure virtual
Implemented in ODBCResultSet.
Definition at line 1934 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1934 of file MySQLResultSet.cxx
References FindColumn(), and UpdateBinaryStream().
void TSQLResultSet::UpdateBoolean (Int_t columnIndex, Bool_t x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1401 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1401 of file MySQLResultSet.cxx
Referenced by UpdateBoolean().
void TSQLResultSet::UpdateBoolean (const TString & columnName, Bool_t x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1692 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1692 of file MySQLResultSet.cxx
References FindColumn(), and UpdateBoolean().
void TSQLResultSet::UpdateByte (Int_t columnIndex, Char_t x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1418 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1418 of file MySQLResultSet.cxx
Referenced by UpdateByte().
void TSQLResultSet::UpdateByte (const TString & columnName, Char_t x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1710 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1710 of file MySQLResultSet.cxx
References FindColumn(), and UpdateByte().
void TSQLResultSet::UpdateBytes (Int_t columnIndex, const TArrayC & x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1539 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1539 of file MySQLResultSet.cxx
Referenced by UpdateBytes().
void TSQLResultSet::UpdateBytes (const TString & columnName, const TArrayC & x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1837 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1837 of file MySQLResultSet.cxx
References FindColumn(), and UpdateBytes().
void TSQLResultSet::UpdateDate (Int_t columnIndex, const TSQLDate & x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1557 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1557 of file MySQLResultSet.cxx
Referenced by UpdateDate().
void TSQLResultSet::UpdateDate (const TString & columnName, const TSQLDate & x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1856 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1856 of file MySQLResultSet.cxx
References FindColumn(), and UpdateDate().
void TSQLResultSet::UpdateDouble (Int_t columnIndex, Double_t x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1503 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1503 of file MySQLResultSet.cxx
Referenced by UpdateDouble().
void TSQLResultSet::UpdateDouble (const TString & columnName, Double_t x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1800 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1800 of file MySQLResultSet.cxx
References FindColumn(), and UpdateDouble().
void TSQLResultSet::UpdateFloat (Int_t columnIndex, Float_t x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1486 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1486 of file MySQLResultSet.cxx
Referenced by UpdateFloat().
void TSQLResultSet::UpdateFloat (const TString & columnName, Float_t x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1782 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1782 of file MySQLResultSet.cxx
References FindColumn(), and UpdateFloat().
void TSQLResultSet::UpdateInt (Int_t columnIndex, Int_t x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1452 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1452 of file MySQLResultSet.cxx
Referenced by UpdateInt().
void TSQLResultSet::UpdateInt (const TString & columnName, Int_t x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1746 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1746 of file MySQLResultSet.cxx
References FindColumn(), and UpdateInt().
void TSQLResultSet::UpdateLong (Int_t columnIndex, Long_t x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1469 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1469 of file MySQLResultSet.cxx
Referenced by UpdateLong().
void TSQLResultSet::UpdateLong (const TString & columnName, Long_t x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1764 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1764 of file MySQLResultSet.cxx
References FindColumn(), and UpdateLong().
void TSQLResultSet::UpdateNull (Int_t columnIndex) pure virtual
Implemented in ODBCResultSet.
Definition at line 1385 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1385 of file MySQLResultSet.cxx
Referenced by UpdateNull().
void TSQLResultSet::UpdateNull (const TString & columnName) pure virtual
Implemented in ODBCResultSet.
Definition at line 1674 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1674 of file MySQLResultSet.cxx
References FindColumn(), and UpdateNull().
void TSQLResultSet::UpdateObject (Int_t columnIndex, TObject * x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1651 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1651 of file MySQLResultSet.cxx
References KFPMath::b, and UpdateBinaryStream().
Referenced by Fill(), and UpdateObject().
void TSQLResultSet::UpdateObject (const TString & columnName, TObject * x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1955 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1955 of file MySQLResultSet.cxx
References FindColumn(), and UpdateObject().
void TSQLResultSet::UpdateRow () pure virtual
Implemented in ODBCResultSet.
Definition at line 1990 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1990 of file MySQLResultSet.cxx
Referenced by Fill().
void TSQLResultSet::UpdateShort (Int_t columnIndex, Short_t x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1435 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1435 of file MySQLResultSet.cxx
Referenced by UpdateShort().
void TSQLResultSet::UpdateShort (const TString & columnName, Short_t x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1728 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1728 of file MySQLResultSet.cxx
References FindColumn(), and UpdateShort().
void TSQLResultSet::UpdateString (Int_t columnIndex, const TString & x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1521 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1521 of file MySQLResultSet.cxx
Referenced by DbForm::UpdateColumn(), and UpdateString().
void TSQLResultSet::UpdateString (const TString & columnName, const TString & x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1818 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1818 of file MySQLResultSet.cxx
References FindColumn(), and UpdateString().
void TSQLResultSet::UpdateTime (Int_t columnIndex, const TSQLTime & x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1575 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1575 of file MySQLResultSet.cxx
Referenced by UpdateTime().
void TSQLResultSet::UpdateTime (const TString & columnName, const TSQLTime & x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1875 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1875 of file MySQLResultSet.cxx
References FindColumn(), and UpdateTime().
void TSQLResultSet::UpdateTimestamp (Int_t columnIndex, const TSQLTimestamp & x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1593 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1593 of file MySQLResultSet.cxx
Referenced by UpdateTimestamp().
void TSQLResultSet::UpdateTimestamp (const TString & columnName, const TSQLTimestamp & x) pure virtual
Implemented in ODBCResultSet.
Definition at line 1894 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 1894 of file MySQLResultSet.cxx
References FindColumn(), and UpdateTimestamp().
Bool_t TSQLResultSet::WasNull () pure virtual
Implemented in ODBCResultSet.
Definition at line 248 of file MySQLResultSet.cxx.
View newest version in sPHENIX GitHub at line 248 of file MySQLResultSet.cxx
References TSQL::fImp, and MySQLResultSetPrivate::fWasNull.
Friends And Related Function Documentation
friend class TSQLStatement friend
Definition at line 42 of file TSQLResultSet.h.
View newest version in sPHENIX GitHub at line 42 of file TSQLResultSet.h
Member Data Documentation
TSQLResultSetMetaData* TSQLResultSet::fMetaData protected
Definition at line 47 of file TSQLResultSet.h.
View newest version in sPHENIX GitHub at line 47 of file TSQLResultSet.h
Referenced by ClassImpQ(), ODBCResultSet::Close(), Close(), ODBCResultSet::GetMetaData(), GetMetaData(), ODBCResultSet::ODBCResultSet(), Print(), Tree(), TSQLResultSet(), ODBCResultSet::~ODBCResultSet(), and ~TSQLResultSet().
RDBCRow* TSQLResultSet::fRow protected
Definition at line 45 of file TSQLResultSet.h.
View newest version in sPHENIX GitHub at line 45 of file TSQLResultSet.h
Referenced by ODBCResultSet::Absolute(), ODBCResultSet::Close(), Close(), ODBCResultSet::First(), First(), ODBCResultSet::Last(), Last(), ODBCResultSet::Next(), Next(), ODBCResultSet::ODBCResultSet(), ODBCResultSet::Previous(), Previous(), ODBCResultSet::Relative(), TSQLResultSet(), ODBCResultSet::~ODBCResultSet(), and ~TSQLResultSet().
TSQLStatement* TSQLResultSet::fStatement protected
Definition at line 46 of file TSQLResultSet.h.
View newest version in sPHENIX GitHub at line 46 of file TSQLResultSet.h
Referenced by First(), GetStatement(), ODBCResultSet::ODBCResultSet(), Print(), Tree(), TSQLResultSet(), and ODBCResultSet::~ODBCResultSet().
The documentation for this class was generated from the following files:
RDBC/blob/master/include/RDBC/TSQLResultSet.h
RDBC/blob/master/mysql/MySQLResultSet.cxx
RDBC/blob/master/rdbc/TSQLResultSet.cxx