Analysis Software: Jetscape::EvolutionHistory Class Reference
Jetscape::EvolutionHistory Class Reference
#include <JETSCAPE/blob/main/src/framework/FluidEvolutionHistory.h>
Public Member Functions
EvolutionHistory ()=default
void FromVector (const std::vector< float > &data_, const std::vector< std::string > &data_info_, float tau_min, float dtau, float x_min, float dx, int nx, float y_min, float dy, int ny, float eta_min, float deta, int neta, bool tau_eta_is_tz)
~EvolutionHistory ()
void clear_up_evolution_data ()
int get_data_size () const
bool is_boost_invariant () const
bool is_Cartesian () const
Jetscape::real Tau0 () const
Jetscape::real XMin () const
Jetscape::real YMin () const
Jetscape::real EtaMin () const
Jetscape::real TauMax () const
Jetscape::real XMax () const
Jetscape::real YMax () const
Jetscape::real EtaMax () const
int CheckInRange (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real eta) const
int GetIdTau (Jetscape::real tau) const
int GetIdX (Jetscape::real x) const
int GetIdY (Jetscape::real y) const
int GetIdEta (Jetscape::real eta) const
Jetscape::real TauCoord (int id_tau) const
Jetscape::real XCoord (int id_x) const
Jetscape::real YCoord (int id_y) const
Jetscape::real EtaCoord (int id_eta) const
int CellIndex (int id_tau, int id_x, int id_y, int id_eta) const
FluidCellInfo GetFluidCell (int id_tau, int id_x, int id_y, int id_eta) const
FluidCellInfo GetAtTimeStep (int id_tau, Jetscape::real x, Jetscape::real y, Jetscape::real etas) const
FluidCellInfo get (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real etas) const
FluidCellInfo get_tz (Jetscape::real t, Jetscape::real x, Jetscape::real y, Jetscape::real z) const
Public Attributes
Jetscape::real tau_min
Jetscape::real dtau
Jetscape::real x_min
Jetscape::real dx
Jetscape::real y_min
Jetscape::real dy
Jetscape::real eta_min
Jetscape::real deta
int ntau
int nx
int ny
int neta
bool tau_eta_is_tz
bool boost_invariant
std::vector< FluidCellInfo > data
std::vector< float > data_vector
std::vector< std::string > data_info
Detailed Description
Definition at line 75 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 75 of file FluidEvolutionHistory.h
Constructor & Destructor Documentation
Jetscape::EvolutionHistory::EvolutionHistory () default
Default constructor.
Jetscape::EvolutionHistory::~EvolutionHistory () inline
Default destructor.
Definition at line 126 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 126 of file FluidEvolutionHistory.h
References data, data_info, and data_vector.
Member Function Documentation
int Jetscape::EvolutionHistory::CellIndex (int id_tau, int id_x, int id_y, int id_eta) const inline
Returns
FluidCellInfo index in the data.
Parameters
id_tau Fluid cell number along tau-grid.
id_x Fluid cell number along x-grid.
id_y Fluid cell number along y-grid.
id_eta Fluid cell number along eta-grid.
Definition at line 228 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 228 of file FluidEvolutionHistory.h
References Acts::UnitConstants::min, neta, ntau, nx, and ny.
Referenced by GetFluidCell().
int Jetscape::EvolutionHistory::CheckInRange (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real eta) const
It checks whether a space-time point (tau, x, y, eta) is inside evolution history or outside.
Parameters
tau Light-cone coordinate.
x Space coordinate.
y Space coordinate.
eta Light-cone coordinate.
Definition at line 62 of file FluidEvolutionHistory.cc.
View newest version in sPHENIX GitHub at line 62 of file FluidEvolutionHistory.cc
References boost_invariant, eta_min, EtaMax(), utils::status, tau_min, TauMax(), to_string(), x_min, XMax(), y_min, and YMax().
Referenced by get(), Jetscape::FluidDynamics::GetHydroInfo(), and test_not_in_range().
void Jetscape::EvolutionHistory::clear_up_evolution_data () inline
Definition at line 132 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 132 of file FluidEvolutionHistory.h
References data.
Referenced by Jetscape::FluidDynamics::clear_up_evolution_data().
Jetscape::real Jetscape::EvolutionHistory::EtaCoord (int id_eta) const inline
Parameters
id_eta Fluid cell number along eta-grid.
Returns
The eta coordinate for fluid cell number.
Definition at line 217 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 217 of file FluidEvolutionHistory.h
References deta, and eta_min.
Referenced by GetAtTimeStep().
Jetscape::real Jetscape::EvolutionHistory::EtaMax () const inline
Maximum value of eta.
Definition at line 153 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 153 of file FluidEvolutionHistory.h
References deta, eta_min, and neta.
Referenced by CheckInRange().
Jetscape::real Jetscape::EvolutionHistory::EtaMin () const inline
Definition at line 141 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 141 of file FluidEvolutionHistory.h
References eta_min.
Referenced by Jetscape::SurfaceFinder::Find_full_hypersurface_4D().
void Jetscape::EvolutionHistory::FromVector (const std::vector< float > & data_, const std::vector< std::string > & data_info_, float tau_min_, float dtau_, float x_min_, float dx_, int nx_, float y_min_, float dy_, int ny_, float eta_min_, float deta_, int neta_, bool tau_eta_is_tz_)
Auxiliary function that helps to read hydro evolution history from external fluid dynamic module. The history from 3rd party hydro should be stored in a std::vector<float> container. The size of the vector should equal ntau * nx * ny * neta * data_info_.size(); For each piece with length data_info_.size(), the vector should store the corresponding float number whose name is written in std::vector<string> data_info_. E.g., data_info_ can be a vector of ['
Construct evolution history given the bulk_data and the data_info
Definition at line 103 of file FluidEvolutionHistory.cc.
View newest version in sPHENIX GitHub at line 103 of file FluidEvolutionHistory.cc
References data_info, data_vector, deta, dtau, dx, dy, eta_min, neta, ntau, nx, ny, tau_eta_is_tz, tau_min, x_min, and y_min.
FluidCellInfo Jetscape::EvolutionHistory::get (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real etas) const
Returns
FluidCellInfo at a point (tau, x, y, eta).
Parameters
tau Light-cone coordinate.
x Space coordinate.
y Space coordinate.
eta Light-cone coordinate.
Definition at line 270 of file FluidEvolutionHistory.cc.
View newest version in sPHENIX GitHub at line 270 of file FluidEvolutionHistory.cc
References CheckInRange(), GetAtTimeStep(), GetIdTau(), Jetscape::LinearInt(), utils::status, tau0, and TauCoord().
Referenced by Jetscape::SurfaceFinder::check_intersect_3D(), Jetscape::SurfaceFinder::check_intersect_4D(), Jetscape::SurfaceFinder::Find_full_hypersurface_3D(), and Jetscape::SurfaceFinder::Find_full_hypersurface_4D().
int Jetscape::EvolutionHistory::get_data_size () const inline
Definition at line 134 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 134 of file FluidEvolutionHistory.h
References data.
Referenced by Jetscape::SurfaceFinder::SurfaceFinder().
FluidCellInfo Jetscape::EvolutionHistory::get_tz (Jetscape::real t, Jetscape::real x, Jetscape::real y, Jetscape::real z) const
Definition at line 286 of file FluidEvolutionHistory.cc.
View newest version in sPHENIX GitHub at line 286 of file FluidEvolutionHistory.cc
References eta, tau, VERBOSE, and physmon_track_finding_ttbar::z.
FluidCellInfo Jetscape::EvolutionHistory::GetAtTimeStep (int id_tau, Jetscape::real x, Jetscape::real y, Jetscape::real eta) const
Returns
FluidCellInfo at a point (x,y,eta) and time-step id_tau.
Parameters
id_tau tau-step number.
x Space coordinate.
y Space coordinate.
eta Light-cone coordinate.
For one given time step id_tau, get FluidCellInfo at spatial point (x, y, eta)
Definition at line 238 of file FluidEvolutionHistory.cc.
View newest version in sPHENIX GitHub at line 238 of file FluidEvolutionHistory.cc
References boost_invariant, EtaCoord(), GetFluidCell(), GetIdEta(), GetIdX(), GetIdY(), Jetscape::TrilinearInt(), x0, XCoord(), and YCoord().
Referenced by get().
FluidCellInfo Jetscape::EvolutionHistory::GetFluidCell (int id_tau, int id_x, int id_y, int id_eta) const
Definition at line 128 of file FluidEvolutionHistory.cc.
View newest version in sPHENIX GitHub at line 128 of file FluidEvolutionHistory.cc
References CellIndex(), data, data_info, data_vector, Jetscape::ENTRY_BULK_PI, Jetscape::ENTRY_ENERGY_DENSITY, Jetscape::ENTRY_ENTROPY_DENSITY, Jetscape::ENTRY_MU_B, Jetscape::ENTRY_MU_C, Jetscape::ENTRY_MU_S, Jetscape::ENTRY_PI00, Jetscape::ENTRY_PI01, Jetscape::ENTRY_PI02, Jetscape::ENTRY_PI03, Jetscape::ENTRY_PI11, Jetscape::ENTRY_PI12, Jetscape::ENTRY_PI13, Jetscape::ENTRY_PI22, Jetscape::ENTRY_PI23, Jetscape::ENTRY_PI33, Jetscape::ENTRY_PRESSURE, Jetscape::ENTRY_QGP_FRACTION, Jetscape::ENTRY_TEMPERATURE, Jetscape::ENTRY_VX, Jetscape::ENTRY_VY, Jetscape::ENTRY_VZ, i, JSWARN, neta, and Jetscape::ResolveEntryName().
Referenced by GetAtTimeStep().
int Jetscape::EvolutionHistory::GetIdEta (Jetscape::real eta) const inline
Returns
Fluid cell number along the eta-grid.
Parameters
eta Light-cone coordinate.
Definition at line 192 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 192 of file FluidEvolutionHistory.h
References deta, and eta_min.
Referenced by GetAtTimeStep().
int Jetscape::EvolutionHistory::GetIdTau (Jetscape::real tau) const inline
Returns
Fluid cell number along the tau-grid.
Parameters
tau Light-cone coordinate.
Definition at line 168 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 168 of file FluidEvolutionHistory.h
References dtau, and tau_min.
Referenced by get().
int Jetscape::EvolutionHistory::GetIdX (Jetscape::real x) const inline
Returns
Fluid cell number along the x-grid.
Parameters
x Space coordinate.
Definition at line 176 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 176 of file FluidEvolutionHistory.h
References dx, and x_min.
Referenced by GetAtTimeStep().
int Jetscape::EvolutionHistory::GetIdY (Jetscape::real y) const inline
Returns
Fluid cell number along the y-grid.
Parameters
y Space coordinate.
Definition at line 184 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 184 of file FluidEvolutionHistory.h
References dy, and y_min.
Referenced by GetAtTimeStep().
bool Jetscape::EvolutionHistory::is_boost_invariant () const inline
Definition at line 135 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 135 of file FluidEvolutionHistory.h
References boost_invariant.
Referenced by HybridHadronization::DoHadronization(), and Jetscape::SurfaceFinder::SurfaceFinder().
bool Jetscape::EvolutionHistory::is_Cartesian () const inline
Definition at line 136 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 136 of file FluidEvolutionHistory.h
References tau_eta_is_tz.
Referenced by HybridHadronization::DoHadronization().
Jetscape::real Jetscape::EvolutionHistory::Tau0 () const inline
Definition at line 138 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 138 of file FluidEvolutionHistory.h
References tau_min.
Referenced by Jetscape::SurfaceFinder::Find_full_hypersurface_3D(), and Jetscape::SurfaceFinder::Find_full_hypersurface_4D().
Jetscape::real Jetscape::EvolutionHistory::TauCoord (int id_tau) const inline
Parameters
id_tau Fluid cell number along tau-grid.
Returns
The tau coordinate for fluid cell number.
Definition at line 200 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 200 of file FluidEvolutionHistory.h
References dtau, and tau_min.
Referenced by get().
Jetscape::real Jetscape::EvolutionHistory::TauMax () const inline
Maximum value of tau.
Definition at line 144 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 144 of file FluidEvolutionHistory.h
References dtau, ntau, and tau_min.
Referenced by CheckInRange(), Jetscape::SurfaceFinder::Find_full_hypersurface_3D(), and Jetscape::SurfaceFinder::Find_full_hypersurface_4D().
Jetscape::real Jetscape::EvolutionHistory::XCoord (int id_x) const inline
Parameters
id_x Fluid cell number along x-grid.
Returns
The x coordinate for fluid cell number.
Definition at line 207 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 207 of file FluidEvolutionHistory.h
References dx, and x_min.
Referenced by GetAtTimeStep().
Jetscape::real Jetscape::EvolutionHistory::XMax () const inline
Maximum value of x.
Definition at line 147 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 147 of file FluidEvolutionHistory.h
References dx, nx, and x_min.
Referenced by CheckInRange().
Jetscape::real Jetscape::EvolutionHistory::XMin () const inline
Definition at line 139 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 139 of file FluidEvolutionHistory.h
References x_min.
Referenced by Jetscape::SurfaceFinder::Find_full_hypersurface_3D(), and Jetscape::SurfaceFinder::Find_full_hypersurface_4D().
Jetscape::real Jetscape::EvolutionHistory::YCoord (int id_y) const inline
Parameters
id_y Fluid cell number along y-grid.
Returns
The y coordinate for fluid cell number.
Definition at line 212 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 212 of file FluidEvolutionHistory.h
References dy, and y_min.
Referenced by GetAtTimeStep().
Jetscape::real Jetscape::EvolutionHistory::YMax () const inline
Maximum value of y.
Definition at line 150 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 150 of file FluidEvolutionHistory.h
References dy, ny, and y_min.
Referenced by CheckInRange().
Jetscape::real Jetscape::EvolutionHistory::YMin () const inline
Definition at line 140 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 140 of file FluidEvolutionHistory.h
References y_min.
Referenced by Jetscape::SurfaceFinder::Find_full_hypersurface_3D(), and Jetscape::SurfaceFinder::Find_full_hypersurface_4D().
Member Data Documentation
bool Jetscape::EvolutionHistory::boost_invariant
Definition at line 93 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 93 of file FluidEvolutionHistory.h
Referenced by CheckInRange(), GetAtTimeStep(), and is_boost_invariant().
std::vector<FluidCellInfo> Jetscape::EvolutionHistory::data
The bulk information of hydro dynamics, in the form of vector of FluidCellInfo objects.
Definition at line 97 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 97 of file FluidEvolutionHistory.h
Referenced by clear_up_evolution_data(), get_data_size(), GetFluidCell(), Jetscape::FluidDynamics::GetHydroInfo(), Jetscape::FluidDynamics::StoreHydroEvolutionHistory(), and ~EvolutionHistory().
std::vector<std::string> Jetscape::EvolutionHistory::data_info
Store the entry names of one record in the data array
Definition at line 107 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 107 of file FluidEvolutionHistory.h
Referenced by FromVector(), GetFluidCell(), and ~EvolutionHistory().
std::vector<float> Jetscape::EvolutionHistory::data_vector
The bulk information of hydro dynamics, in the form of 1D float vector. It is easy to pass vector of float from 3rd party hydro module to Jetscape Fluid Evolution History, where bulk info should be stored in orders of ed0, sd0, temp0, ..., ed1, sd1, temp1, ..., edn, sdn, tempn. The content and order of data entres are given by data_info
Definition at line 104 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 104 of file FluidEvolutionHistory.h
Referenced by FromVector(), GetFluidCell(), and ~EvolutionHistory().
Jetscape::real Jetscape::EvolutionHistory::deta
Parameters
deta Step-size for eta.
Definition at line 84 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 84 of file FluidEvolutionHistory.h
Referenced by EtaCoord(), EtaMax(), FromVector(), and GetIdEta().
Jetscape::real Jetscape::EvolutionHistory::dtau
Parameters
dtau Step-size for tau.
Definition at line 78 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 78 of file FluidEvolutionHistory.h
Referenced by FromVector(), GetIdTau(), TauCoord(), and TauMax().
Jetscape::real Jetscape::EvolutionHistory::dx
Parameters
dx Step-size for x.
Definition at line 80 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 80 of file FluidEvolutionHistory.h
Referenced by FromVector(), GetIdX(), XCoord(), and XMax().
Jetscape::real Jetscape::EvolutionHistory::dy
Parameters
dy Step-size for y.
Definition at line 82 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 82 of file FluidEvolutionHistory.h
Referenced by FromVector(), GetIdY(), YCoord(), and YMax().
Jetscape::real Jetscape::EvolutionHistory::eta_min
Parameters
eta_min Minimum value of eta.
Definition at line 84 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 84 of file FluidEvolutionHistory.h
Referenced by CheckInRange(), EtaCoord(), EtaMax(), EtaMin(), FromVector(), and GetIdEta().
int Jetscape::EvolutionHistory::neta
Parameters
neta Number of grid points in eta-axis.
Definition at line 88 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 88 of file FluidEvolutionHistory.h
Referenced by CellIndex(), EtaMax(), FromVector(), and GetFluidCell().
int Jetscape::EvolutionHistory::ntau
Parameters
ntau Number of grid points in tau-axis.
Definition at line 85 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 85 of file FluidEvolutionHistory.h
Referenced by CellIndex(), FromVector(), and TauMax().
int Jetscape::EvolutionHistory::nx
Parameters
nx Number of grid points in x-axis.
Definition at line 86 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 86 of file FluidEvolutionHistory.h
Referenced by CellIndex(), FromVector(), and XMax().
int Jetscape::EvolutionHistory::ny
Parameters
ny Number of grid points in y-axis.
Definition at line 87 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 87 of file FluidEvolutionHistory.h
Referenced by CellIndex(), FromVector(), and YMax().
bool Jetscape::EvolutionHistory::tau_eta_is_tz
Default is set to false. Set flag tau_eta_is_tz to true if hydro dynamics is setup in (t,x,y,z) coordinate.
Definition at line 91 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 91 of file FluidEvolutionHistory.h
Referenced by FromVector(), Jetscape::FluidDynamics::GetHydroInfo(), and is_Cartesian().
Jetscape::real Jetscape::EvolutionHistory::tau_min
Parameters
tau_min Minimum value of tau.
Definition at line 78 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 78 of file FluidEvolutionHistory.h
Referenced by CheckInRange(), FromVector(), GetIdTau(), Tau0(), TauCoord(), and TauMax().
Jetscape::real Jetscape::EvolutionHistory::x_min
Parameters
x_min Minimum value of x.
Definition at line 80 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 80 of file FluidEvolutionHistory.h
Referenced by CheckInRange(), FromVector(), GetIdX(), XCoord(), XMax(), and XMin().
Jetscape::real Jetscape::EvolutionHistory::y_min
Parameters
y_min Minimum value of y.
Definition at line 82 of file FluidEvolutionHistory.h.
View newest version in sPHENIX GitHub at line 82 of file FluidEvolutionHistory.h
Referenced by CheckInRange(), FromVector(), GetIdY(), YCoord(), YMax(), and YMin().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/FluidEvolutionHistory.h
JETSCAPE/blob/main/src/framework/FluidEvolutionHistory.cc