Analysis Software: Fun4AllDstPileupMerger Exception Reference
Fun4AllDstPileupMerger Exception Reference final
#include <coresoftware/blob/master/simulation/g4simulation/g4main/Fun4AllDstPileupMerger.h>
Public Member Functions
Fun4AllDstPileupMerger ()=default
constructor
~Fun4AllDstPileupMerger ()=default
destructor
void load_nodes (PHCompositeNode *)
load destination nodes from composite
void copy_background_event (PHCompositeNode *, double delta_t) const
time-shift and copy content of source nodes to destination
void copyDetectorActiveCrossings (const std::map< std::string, std::pair< double, double >> &dmap)
Private Attributes
PHHepMCGenEventMap * m_geneventmap = nullptr
hepmc
std::map< std::string,
PHG4HitContainer * > m_g4hitscontainers
maps g4hit containers to node names
PHG4TruthInfoContainer * m_g4truthinfo = nullptr
truth information
std::map< std::string,
std::pair< double,double > > m_DetectorTiming
Detailed Description
utility class that can merge the relevant nodes together, once time shifted in order to generate full pileup events from raw events it is used internally by Fun4AllDstPileupInputManager and Fun4AllSingleDstPileupInputManager
Definition at line 24 of file Fun4AllDstPileupMerger.h.
View newest version in sPHENIX GitHub at line 24 of file Fun4AllDstPileupMerger.h
Constructor & Destructor Documentation
Fun4AllDstPileupMerger::Fun4AllDstPileupMerger () default
constructor
Fun4AllDstPileupMerger::~Fun4AllDstPileupMerger () default
destructor
Member Function Documentation
void Fun4AllDstPileupMerger::copy_background_event (PHCompositeNode * dstNode, double delta_t) const
time-shift and copy content of source nodes to destination
Definition at line 111 of file Fun4AllDstPileupMerger.cc.
View newest version in sPHENIX GitHub at line 111 of file Fun4AllDstPileupMerger.cc
References PHG4TruthInfoContainer::AddEmbededTrkId(), PHG4TruthInfoContainer::AddEmbededVtxId(), PHG4TruthInfoContainer::AddParticle(), PHG4TruthInfoContainer::AddVertex(), upload::dest, genevent(), PHHepMCGenEvent::getEvent(), PHHepMCGenEventMap::insert_background_event(), m_DetectorTiming, m_g4hitscontainers, m_g4truthinfo, m_geneventmap, PHG4TruthInfoContainer::maxtrkindex(), PHG4TruthInfoContainer::maxvtxindex(), PHG4TruthInfoContainer::mintrkindex(), PHG4TruthInfoContainer::minvtxindex(), and parse_cmake_options::source.
Referenced by Fun4AllDstPileupInputManager::run(), and Fun4AllSingleDstPileupInputManager::run().
void Fun4AllDstPileupMerger::copyDetectorActiveCrossings (const std::map< std::string, std::pair< double, double >> & dmap) inline
Definition at line 41 of file Fun4AllDstPileupMerger.h.
View newest version in sPHENIX GitHub at line 41 of file Fun4AllDstPileupMerger.h
References m_DetectorTiming.
Referenced by Fun4AllDstPileupInputManager::run().
void Fun4AllDstPileupMerger::load_nodes (PHCompositeNode * dstNode)
load destination nodes from composite
Definition at line 84 of file Fun4AllDstPileupMerger.cc.
View newest version in sPHENIX GitHub at line 84 of file Fun4AllDstPileupMerger.cc
References PHNodeIterator::forEach(), m_g4hitscontainers, m_g4truthinfo, and m_geneventmap.
Referenced by Fun4AllDstPileupInputManager::run(), and Fun4AllSingleDstPileupInputManager::run().
Member Data Documentation
std::map<std::string,std::pair<double ,double> > Fun4AllDstPileupMerger::m_DetectorTiming private
Definition at line 54 of file Fun4AllDstPileupMerger.h.
View newest version in sPHENIX GitHub at line 54 of file Fun4AllDstPileupMerger.h
Referenced by copy_background_event(), and copyDetectorActiveCrossings().
std::map<std::string, PHG4HitContainer *> Fun4AllDstPileupMerger::m_g4hitscontainers private
maps g4hit containers to node names
Definition at line 49 of file Fun4AllDstPileupMerger.h.
View newest version in sPHENIX GitHub at line 49 of file Fun4AllDstPileupMerger.h
Referenced by copy_background_event(), and load_nodes().
PHG4TruthInfoContainer* Fun4AllDstPileupMerger::m_g4truthinfo = nullptr private
truth information
Definition at line 52 of file Fun4AllDstPileupMerger.h.
View newest version in sPHENIX GitHub at line 52 of file Fun4AllDstPileupMerger.h
Referenced by copy_background_event(), and load_nodes().
PHHepMCGenEventMap* Fun4AllDstPileupMerger::m_geneventmap = nullptr private
hepmc
Definition at line 46 of file Fun4AllDstPileupMerger.h.
View newest version in sPHENIX GitHub at line 46 of file Fun4AllDstPileupMerger.h
Referenced by copy_background_event(), and load_nodes().
The documentation for this exception was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/Fun4AllDstPileupMerger.h
coresoftware/blob/master/simulation/g4simulation/g4main/Fun4AllDstPileupMerger.cc