Analysis Software: BbcVertexv1 Class Reference
BbcVertexv1 Class Reference
#include <coresoftware/blob/master/offline/packages/mbd/BbcVertexv1.h>
Public Member Functions
BbcVertexv1 ()
~BbcVertexv1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
unsigned int get_id () const override
void set_id (unsigned int id) override
float get_t () const override
void set_t (float t) override
float get_t_err () const override
void set_t_err (float t_err) override
float get_z () const override
void set_z (float z) override
float get_z_err () const override
void set_z_err (float z_err) override
Public Member Functions inherited from BbcVertex
~BbcVertex () override
virtual void set_bbc_ns (int, int, float, float)
virtual int get_bbc_npmt (int) const
virtual float get_bbc_q (int) const
virtual float get_bbc_t (int) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (BbcVertexv1, 1)
Private Attributes
unsigned int _id
float _t
float _t_err
float _z
float _z_err
Additional Inherited Members
Protected Member Functions inherited from BbcVertex
BbcVertex ()
Detailed Description
Definition at line 8 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 8 of file BbcVertexv1.h
Constructor & Destructor Documentation
BbcVertexv1::BbcVertexv1 ()
Definition at line 7 of file BbcVertexv1.cc.
View newest version in sPHENIX GitHub at line 7 of file BbcVertexv1.cc
Referenced by CloneMe(), and Reset().
BbcVertexv1::~BbcVertexv1 () override default
Member Function Documentation
BbcVertexv1::ClassDefOverride (BbcVertexv1 , 1) private
PHObject* BbcVertexv1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from BbcVertex.
Definition at line 19 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 19 of file BbcVertexv1.h
References BbcVertexv1().
unsigned int BbcVertexv1::get_id () const inline override virtual
Reimplemented from BbcVertex.
Definition at line 23 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 23 of file BbcVertexv1.h
References _id.
Referenced by identify().
float BbcVertexv1::get_t () const inline override virtual
Reimplemented from BbcVertex.
Definition at line 26 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 26 of file BbcVertexv1.h
References _t.
Referenced by identify().
float BbcVertexv1::get_t_err () const inline override virtual
Reimplemented from BbcVertex.
Definition at line 29 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 29 of file BbcVertexv1.h
References _t_err.
Referenced by identify().
float BbcVertexv1::get_z () const inline override virtual
Reimplemented from BbcVertex.
Definition at line 32 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 32 of file BbcVertexv1.h
References _z.
Referenced by identify().
float BbcVertexv1::get_z_err () const inline override virtual
Reimplemented from BbcVertex.
Definition at line 35 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 35 of file BbcVertexv1.h
References _z_err.
Referenced by identify().
void BbcVertexv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from BbcVertex.
Definition at line 18 of file BbcVertexv1.cc.
View newest version in sPHENIX GitHub at line 18 of file BbcVertexv1.cc
References get_id(), get_t(), get_t_err(), get_z(), and get_z_err().
int BbcVertexv1::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from BbcVertex.
Definition at line 29 of file BbcVertexv1.cc.
View newest version in sPHENIX GitHub at line 29 of file BbcVertexv1.cc
References _id, _t, _t_err, _z, and _z_err.
void BbcVertexv1::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 17 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 17 of file BbcVertexv1.h
References BbcVertexv1().
void BbcVertexv1::set_id (unsigned int id) inline override virtual
Reimplemented from BbcVertex.
Definition at line 24 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 24 of file BbcVertexv1.h
References _id, and train_ambiguity_solver::id.
void BbcVertexv1::set_t (float t) inline override virtual
Reimplemented from BbcVertex.
Definition at line 27 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 27 of file BbcVertexv1.h
References _t, and t.
void BbcVertexv1::set_t_err (float t_err) inline override virtual
Reimplemented from BbcVertex.
Definition at line 30 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 30 of file BbcVertexv1.h
References _t_err.
void BbcVertexv1::set_z (float z) inline override virtual
Reimplemented from BbcVertex.
Definition at line 33 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 33 of file BbcVertexv1.h
References _z, and physmon_track_finding_ttbar::z.
void BbcVertexv1::set_z_err (float z_err) inline override virtual
Reimplemented from BbcVertex.
Definition at line 36 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 36 of file BbcVertexv1.h
References _z_err.
Member Data Documentation
unsigned int BbcVertexv1::_id private
Definition at line 39 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 39 of file BbcVertexv1.h
Referenced by get_id(), isValid(), and set_id().
float BbcVertexv1::_t private
Definition at line 40 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 40 of file BbcVertexv1.h
Referenced by get_t(), isValid(), and set_t().
float BbcVertexv1::_t_err private
Definition at line 41 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 41 of file BbcVertexv1.h
Referenced by get_t_err(), isValid(), and set_t_err().
float BbcVertexv1::_z private
Definition at line 42 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 42 of file BbcVertexv1.h
Referenced by get_z(), isValid(), and set_z().
float BbcVertexv1::_z_err private
Definition at line 43 of file BbcVertexv1.h.
View newest version in sPHENIX GitHub at line 43 of file BbcVertexv1.h
Referenced by get_z_err(), isValid(), and set_z_err().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mbd/BbcVertexv1.h
coresoftware/blob/master/offline/packages/mbd/BbcVertexv1.cc