Analysis Software: analysis/blob/master/EMCal-QA/macro/QA.C File Reference
QA.C File Reference
#include <string>
#include <vector>
#include <iostream>
#include <TH2F.h>
#include <TFile.h>
#include <TTree.h>
Namespaces
namespace myAnalysis
Functions
void myAnalysis::init (const string &inputFile="data/LEDTowerBuilder.root")
void myAnalysis::analyze (UInt_t nevents=0)
void myAnalysis::finalize (const string &outputFile="output/test.root")
void QA (const string &inputFile, const string &outputFile="test.root", UInt_t nevents=0)
int main (int argc, char *argv[])
Variables
TTree * myAnalysis::data
TH1F * myAnalysis::hclusterEta
TH1F * myAnalysis::hclusterPhi
TH1F * myAnalysis::hclusterE
TH1F * myAnalysis::hclusterE_2
TH1F * myAnalysis::hclusterPt
TH1F * myAnalysis::hclusterChisq
TH1F * myAnalysis::hclusterChisq_2
TH1F * myAnalysis::hclusterChisq_3
TH2F * myAnalysis::h2clusterPhiVsEta
TH2F * myAnalysis::h2clusterPhiVsEta_2
TH2F * myAnalysis::h2clusterPhiVsEta_3
TH2F * myAnalysis::h2clusterChisqVsE
TH2F * myAnalysis::h2clusterChisqVsE_2
TH2F * myAnalysis::h2clusterE_CalibVsE
UInt_t myAnalysis::e_bins = 500
Float_t myAnalysis::e_min = 0
Float_t myAnalysis::e_max = 5e4
UInt_t myAnalysis::pt_bins = 500
Float_t myAnalysis::pt_min = 0
Float_t myAnalysis::pt_max = 5e4
UInt_t myAnalysis::chi2_bins = 500
Float_t myAnalysis::chi2_min = 0
Float_t myAnalysis::chi2_max = 5e5
vector< Float_t > * myAnalysis::clusterPhi = 0
vector< Float_t > * myAnalysis::clusterEta = 0
vector< Float_t > * myAnalysis::clusterE = 0
vector< Float_t > * myAnalysis::clusterPt = 0
vector< Float_t > * myAnalysis::clusterChisq = 0
Function Documentation
int main (int argc, char * argv[])
Definition at line 220 of file QA.C.
View newest version in sPHENIX GitHub at line 220 of file QA.C
References physmon_vertexing::events, digitization_config::input, check_smearing_config::output, and QA().
void QA (const string & inputFile, const string & outputFile = "test.root", UInt_t nevents = 0)
Definition at line 210 of file QA.C.
View newest version in sPHENIX GitHub at line 210 of file QA.C
References myAnalysis::analyze(), myAnalysis::finalize(), and myAnalysis::init().
Referenced by main().