Analysis Software: SvtxTrackCaloClusterMap_v1 Class Reference
SvtxTrackCaloClusterMap_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackCaloClusterMap_v1.h>
Public Member Functions
SvtxTrackCaloClusterMap_v1 ()
SvtxTrackCaloClusterMap_v1 (const SvtxTrackCaloClusterMap_v1 &map)
SvtxTrackCaloClusterMap_v1 & operator= (const SvtxTrackCaloClusterMap_v1 &map)
~SvtxTrackCaloClusterMap_v1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
bool empty () const override
size_t size () const override
void clear () override
const std::vector< RawCluster * > get (SvtxTrack *track) const override
std::vector< RawCluster * > get (SvtxTrack *track) override
std::vector< RawCluster * > insert (SvtxTrack *track, std::vector< RawCluster * > clusters) override
std::vector< RawCluster * > insert (SvtxTrack *track, RawCluster *clus) override
size_t erase (SvtxTrack *track) override
ConstIter begin () const override
ConstIter find (SvtxTrack *track) const override
ConstIter end () const override
Iter begin () override
Iter find (SvtxTrack *track) override
Iter end () override
Public Member Functions inherited from SvtxTrackCaloClusterMap
~SvtxTrackCaloClusterMap () override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (SvtxTrackCaloClusterMap_v1, 1)
Private Attributes
Map _map
Additional Inherited Members
Public Types inherited from SvtxTrackCaloClusterMap
typedef std::map< SvtxTrack
*, std::vector< RawCluster * > > Map
typedef std::map< SvtxTrack
*, std::vector< RawCluster * >
>::const_iterator ConstIter
typedef std::map< SvtxTrack
*, std::vector< RawCluster * >
>::iterator Iter
Protected Member Functions inherited from SvtxTrackCaloClusterMap
SvtxTrackCaloClusterMap ()
Detailed Description
Definition at line 11 of file SvtxTrackCaloClusterMap_v1.h.
View newest version in sPHENIX GitHub at line 11 of file SvtxTrackCaloClusterMap_v1.h
Constructor & Destructor Documentation
SvtxTrackCaloClusterMap_v1::SvtxTrackCaloClusterMap_v1 ()
Definition at line 14 of file SvtxTrackCaloClusterMap_v1.cc.
View newest version in sPHENIX GitHub at line 14 of file SvtxTrackCaloClusterMap_v1.cc
Referenced by CloneMe().
SvtxTrackCaloClusterMap_v1::SvtxTrackCaloClusterMap_v1 (const SvtxTrackCaloClusterMap_v1 & map)
Definition at line 19 of file SvtxTrackCaloClusterMap_v1.cc.
View newest version in sPHENIX GitHub at line 19 of file SvtxTrackCaloClusterMap_v1.cc
References _map, begin(), and end().
SvtxTrackCaloClusterMap_v1::~SvtxTrackCaloClusterMap_v1 () override
Definition at line 44 of file SvtxTrackCaloClusterMap_v1.cc.
View newest version in sPHENIX GitHub at line 44 of file SvtxTrackCaloClusterMap_v1.cc
References Reset().
Member Function Documentation
ConstIter SvtxTrackCaloClusterMap_v1::begin (void) const inline override virtual
Reimplemented from SvtxTrackCaloClusterMap.
Definition at line 35 of file SvtxTrackCaloClusterMap_v1.h.
View newest version in sPHENIX GitHub at line 35 of file SvtxTrackCaloClusterMap_v1.h
References _map.
Referenced by operator=(), and SvtxTrackCaloClusterMap_v1().
Iter SvtxTrackCaloClusterMap_v1::begin (void) inline override virtual
Reimplemented from SvtxTrackCaloClusterMap.
Definition at line 39 of file SvtxTrackCaloClusterMap_v1.h.
View newest version in sPHENIX GitHub at line 39 of file SvtxTrackCaloClusterMap_v1.h
References _map.
SvtxTrackCaloClusterMap_v1::ClassDefOverride (SvtxTrackCaloClusterMap_v1 , 1) private
void SvtxTrackCaloClusterMap_v1::clear () inline override virtual
Reimplemented from SvtxTrackCaloClusterMap.
Definition at line 27 of file SvtxTrackCaloClusterMap_v1.h.
View newest version in sPHENIX GitHub at line 27 of file SvtxTrackCaloClusterMap_v1.h
References Reset().
PHObject* SvtxTrackCaloClusterMap_v1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from SvtxTrackCaloClusterMap.
Definition at line 23 of file SvtxTrackCaloClusterMap_v1.h.
View newest version in sPHENIX GitHub at line 23 of file SvtxTrackCaloClusterMap_v1.h
References SvtxTrackCaloClusterMap_v1().
bool SvtxTrackCaloClusterMap_v1::empty () const inline override virtual
Reimplemented from SvtxTrackCaloClusterMap.
Definition at line 25 of file SvtxTrackCaloClusterMap_v1.h.
View newest version in sPHENIX GitHub at line 25 of file SvtxTrackCaloClusterMap_v1.h
References _map.
ConstIter SvtxTrackCaloClusterMap_v1::end (void) const inline override virtual
Reimplemented from SvtxTrackCaloClusterMap.
Definition at line 37 of file SvtxTrackCaloClusterMap_v1.h.
View newest version in sPHENIX GitHub at line 37 of file SvtxTrackCaloClusterMap_v1.h
References _map.
Referenced by operator=(), and SvtxTrackCaloClusterMap_v1().
Iter SvtxTrackCaloClusterMap_v1::end (void) inline override virtual
Reimplemented from SvtxTrackCaloClusterMap.
Definition at line 41 of file SvtxTrackCaloClusterMap_v1.h.
View newest version in sPHENIX GitHub at line 41 of file SvtxTrackCaloClusterMap_v1.h
References _map.
size_t SvtxTrackCaloClusterMap_v1::erase (SvtxTrack * track) override virtual
Reimplemented from SvtxTrackCaloClusterMap.
Definition at line 116 of file SvtxTrackCaloClusterMap_v1.cc.
View newest version in sPHENIX GitHub at line 116 of file SvtxTrackCaloClusterMap_v1.cc
References _map.
ConstIter SvtxTrackCaloClusterMap_v1::find (SvtxTrack * track) const inline override virtual
Reimplemented from SvtxTrackCaloClusterMap.
Definition at line 36 of file SvtxTrackCaloClusterMap_v1.h.
View newest version in sPHENIX GitHub at line 36 of file SvtxTrackCaloClusterMap_v1.h
References _map.
Iter SvtxTrackCaloClusterMap_v1::find (SvtxTrack * track) inline override virtual
Reimplemented from SvtxTrackCaloClusterMap.
Definition at line 40 of file SvtxTrackCaloClusterMap_v1.h.
View newest version in sPHENIX GitHub at line 40 of file SvtxTrackCaloClusterMap_v1.h
References _map.
const std::vector< RawCluster * > SvtxTrackCaloClusterMap_v1::get (SvtxTrack * track) const override virtual
Reimplemented from SvtxTrackCaloClusterMap.
Definition at line 62 of file SvtxTrackCaloClusterMap_v1.cc.
View newest version in sPHENIX GitHub at line 62 of file SvtxTrackCaloClusterMap_v1.cc
References _map, and dummy.
std::vector< RawCluster * > SvtxTrackCaloClusterMap_v1::get (SvtxTrack * track) override virtual
Reimplemented from SvtxTrackCaloClusterMap.
Definition at line 73 of file SvtxTrackCaloClusterMap_v1.cc.
View newest version in sPHENIX GitHub at line 73 of file SvtxTrackCaloClusterMap_v1.cc
References _map, and dummy.
void SvtxTrackCaloClusterMap_v1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxTrackCaloClusterMap.
Definition at line 56 of file SvtxTrackCaloClusterMap_v1.cc.
View newest version in sPHENIX GitHub at line 56 of file SvtxTrackCaloClusterMap_v1.cc
References _map.
std::vector< RawCluster * > SvtxTrackCaloClusterMap_v1::insert (SvtxTrack * track, std::vector< RawCluster * > clusters) override virtual
Reimplemented from SvtxTrackCaloClusterMap.
Definition at line 84 of file SvtxTrackCaloClusterMap_v1.cc.
View newest version in sPHENIX GitHub at line 84 of file SvtxTrackCaloClusterMap_v1.cc
References _map, and clusters.
std::vector< RawCluster * > SvtxTrackCaloClusterMap_v1::insert (SvtxTrack * track, RawCluster * clus) override virtual
Reimplemented from SvtxTrackCaloClusterMap.
Definition at line 99 of file SvtxTrackCaloClusterMap_v1.cc.
View newest version in sPHENIX GitHub at line 99 of file SvtxTrackCaloClusterMap_v1.cc
References _map, and dummy.
int SvtxTrackCaloClusterMap_v1::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxTrackCaloClusterMap.
Definition at line 22 of file SvtxTrackCaloClusterMap_v1.h.
View newest version in sPHENIX GitHub at line 22 of file SvtxTrackCaloClusterMap_v1.h
SvtxTrackCaloClusterMap_v1 & SvtxTrackCaloClusterMap_v1::operator= (const SvtxTrackCaloClusterMap_v1 & map)
Definition at line 31 of file SvtxTrackCaloClusterMap_v1.cc.
View newest version in sPHENIX GitHub at line 31 of file SvtxTrackCaloClusterMap_v1.cc
References _map, begin(), end(), and Reset().
void SvtxTrackCaloClusterMap_v1::Reset () override virtual
Clear Event.
Pointers to SvtxTrack and RawCluster will be deleted by their respective containers already
Reimplemented from PHObject.
Definition at line 49 of file SvtxTrackCaloClusterMap_v1.cc.
View newest version in sPHENIX GitHub at line 49 of file SvtxTrackCaloClusterMap_v1.cc
References _map.
Referenced by clear(), operator=(), and ~SvtxTrackCaloClusterMap_v1().
size_t SvtxTrackCaloClusterMap_v1::size (void) const inline override virtual
Reimplemented from SvtxTrackCaloClusterMap.
Definition at line 26 of file SvtxTrackCaloClusterMap_v1.h.
View newest version in sPHENIX GitHub at line 26 of file SvtxTrackCaloClusterMap_v1.h
References _map.
Member Data Documentation
Map SvtxTrackCaloClusterMap_v1::_map private
Definition at line 44 of file SvtxTrackCaloClusterMap_v1.h.
View newest version in sPHENIX GitHub at line 44 of file SvtxTrackCaloClusterMap_v1.h
Referenced by begin(), empty(), end(), erase(), find(), get(), identify(), insert(), operator=(), Reset(), size(), and SvtxTrackCaloClusterMap_v1().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackCaloClusterMap_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackCaloClusterMap_v1.cc