Analysis Software: acts/blob/sPHENIX/Plugins/ExaTrkX/src/buildEdges.cpp File Reference
buildEdges.cpp File Reference
#include "Acts/Plugins/ExaTrkX/detail/buildEdges.hpp"
#include "Acts/Plugins/ExaTrkX/detail/TensorVectorConversion.hpp"
#include "Acts/Utilities/Helpers.hpp"
#include "Acts/Utilities/KDTree.hpp"
#include <iostream>
#include <mutex>
#include <vector>
#include <torch/script.h>
#include <torch/torch.h>
#include <cuda.h>
#include <cuda_runtime_api.h>
#include <grid/counting_sort.h>
#include <grid/find_nbrs.h>
#include <grid/grid.h>
#include <grid/insert_points.h>
#include <grid/prefix_sum.h>
Classes
struct Span< T, S >
struct BuildEdgesKDTree< Dim >
Functions
template<std::size_t Dim>
float dist (const Span< float, Dim > &a, const Span< float, Dim > &b)
Function Documentation
template<std::size_t Dim> float dist (const Span< float, Dim > & a, const Span< float, Dim > & b)
Definition at line 198 of file buildEdges.cpp.
View newest version in sPHENIX GitHub at line 198 of file buildEdges.cpp
References i, and physmon_simulation::s.
Referenced by LazyTiling9Alt::_add_untagged_neighbours_to_tile_union_using_max_info(), LazyTiling9::_add_untagged_neighbours_to_tile_union_using_max_info(), LazyTiling25::_add_untagged_neighbours_to_tile_union_using_max_info(), ClusterSequence::_bj_dist(), ClusterSequence::_bj_set_NN_crosscheck(), ClusterSequence::_bj_set_NN_nocross(), ClusterSequence::_faster_tiled_N2_cluster(), ClusterSequence::_minheap_faster_tiled_N2_cluster(), LazyTiling9Alt::_set_NN(), LazyTiling9::_set_NN(), LazyTiling25::_set_NN(), ClusterSequence::_simple_N2_cluster(), ClusterSequence::_tiled_N2_cluster(), LazyTiling9Alt::_update_jetX_jetI_NN(), LazyTiling9::_update_jetX_jetI_NN(), LazyTiling25::_update_jetX_jetI_NN(), nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::addPoint(), BOOST_DATA_TEST_CASE(), Acts::BoundaryCheck::computeEuclideanClosestPointOnRectangle(), PHActsInitialVertexFinder::createCentroidMap(), DrawGraph(), Acts::Polyhedron::extent(), BEmcRec::fTowerDist(), sPHAnalysis::Get_CAL_e3x3(), PHG4TpcCentralMembrane::getStripeID(), BuildEdgesKDTree< Dim >::invoke(), PHCosmicSeeder::makeSeeds(), FilterEventsUpsilon::MatchClusterCEMC(), FilterEvents::MatchClusterCEMC(), sPHAnalysis::MatchClusterCEMC(), NNH< BJ, I >::merge_jets(), ActsExamples::Digitization::GaussTrunc::operator()(), ActsExamples::Digitization::GaussClipped::operator()(), ActsExamples::Digitization::Uniform::operator()(), FilterEventsUpsilon::process_event(), FilterEvents::process_event(), SigmaTimingNtuple::process_event(), pyhimult(), pymult(), LazyTiling9Alt::run(), LazyTiling9::run(), LazyTiling25::run(), Jetscape::InitialState::SampleABinaryCollisionPoint(), ActsFatras::NuclearInteraction::sampleInvariantMasses(), ActsFatras::NuclearInteraction::sampleMomenta(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::searchLevel(), NNH< BJ, I >::set_NN_crosscheck(), NNH< BJ, I >::set_NN_nocross(), TEST_CASE(), and Acts::SingleSeedVertexFinder< spacepoint_t >::tripletValidationAndUpdate().