Analysis Software: HybridHadronization::HHparton Class Reference
HybridHadronization::HHparton Class Reference
Public Member Functions
HHparton ()
double x ()
double y ()
double z ()
double x_t ()
double px ()
double py ()
double pz ()
double e ()
bool is_shower ()
bool is_thermal ()
bool is_used ()
bool is_decayedglu ()
bool is_remnant ()
bool used_reco ()
bool used_str ()
bool is_strendpt ()
bool used_junction ()
bool is_fakeparton ()
int id ()
int orig ()
int par ()
int string_id () const
int pos_str () const
int endpt_id ()
int sibling ()
int PY_par1 ()
int PY_par2 ()
int PY_dau1 ()
int PY_dau2 ()
int PY_stat ()
int PY_origid ()
int PY_tag1 ()
int PY_tag2 ()
int PY_tag3 ()
double mass ()
FourVector pos ()
FourVector P ()
int status ()
int col ()
int acol ()
void x (double val)
void y (double val)
void z (double val)
void x_t (double val)
void pos (FourVector val)
void px (double val)
void py (double val)
void pz (double val)
void e (double val)
void P (FourVector val)
void is_shower (bool val)
void is_thermal (bool val)
void is_used (bool val)
void is_decayedglu (bool val)
void is_remnant (bool val)
void used_reco (bool val)
void used_str (bool val)
void is_strendpt (bool val)
void used_junction (bool val)
void is_fakeparton (bool val)
void id (int val)
void orig (int val)
void par (int val)
void string_id (int val)
void pos_str (int val)
void endpt_id (int val)
void sibling (int val)
void PY_par1 (int val)
void PY_par2 (int val)
void PY_dau1 (int val)
void PY_dau2 (int val)
void PY_stat (int val)
void PY_origid (int val)
void PY_tag1 (int val)
void PY_tag2 (int val)
void PY_tag3 (int val)
void mass (double val)
void status (int val)
void col (int val)
void acol (int val)
FourVector boost_P (FourVector B)
FourVector boost_P (double vx, double vy, double vz)
FourVector boost_pos (FourVector B)
FourVector boost_pos (double vx, double vy, double vz)
double pDif2 (HHparton comp)
double posDif2 (HHparton comp)
Public Member Functions inherited from Jetscape::Parton
virtual void set_mean_form_time ()
virtual void set_form_time (double form_time)
virtual double form_time ()
virtual const double mean_form_time ()
virtual void reset_p (double px, double py, double pz)
virtual void set_color (unsigned int col)
sets the color of the parton
virtual void set_anti_color (unsigned int acol)
sets anti-color of the parton
virtual void set_max_color (unsigned int col)
sets the color of the parton
virtual void set_min_color (unsigned int col)
sets the color of the parton
virtual void set_min_anti_color (unsigned int acol)
sets anti-color of the parton
bool isPhoton (int pid)
Parton (int label, int id, int stat, const FourVector &p, const FourVector &x)
Parton (int label, int id, int stat, double pt, double eta, double phi, double e, double *x=0)
Parton (const Parton &srp)
Parton & operator= (Parton &c)
Parton & operator= (const Parton &c)
const double t ()
void set_t (double t)
virtuality of particle, : rescales the spatial component
unsigned int color ()
returns the color of the parton
unsigned int anti_color ()
returns the anti-color of the parton
unsigned int max_color ()
unsigned int min_color ()
unsigned int min_anti_color ()
const int edgeid () const
void set_edgeid (const int id)
void set_shower (const shared_ptr< PartonShower > pShower)
void set_shower (const weak_ptr< PartonShower > pShower)
const weak_ptr< PartonShower > shower () const
std::vector< Parton > parents ()
Public Member Functions inherited from Jetscape::JetScapeParticleBase
void reset_momentum (const double px, const double py, const double pz, const double e)
void reset_momentum (const FourVector &p)
fjcore::PseudoJet GetPseudoJet () const
No implicit cast to PseudoJet is allowed, provide a conversion.
JetScapeParticleBase ()
JetScapeParticleBase (int label, int id, int stat, const FourVector &p, const FourVector &x)
JetScapeParticleBase (int label, int id, int stat, double pt, double eta, double phi, double e, double *x=0)
JetScapeParticleBase (int label, int id, int stat, const FourVector &p, const FourVector &x, double mass)
JetScapeParticleBase (const JetScapeParticleBase &srp)
virtual ~JetScapeParticleBase ()
void clear ()
void set_label (int label)
void set_id (int id)
void set_stat (int stat)
void set_x (double x[4])
void init_jet_v ()
void set_jet_v (double v[4])
void set_jet_v (FourVector j)
bool SetController (string controller="")
void UnsetController ()
const int pid () const
const int pstat () const
const int plabel () const
const double time () const
std::vector< JetScapeParticleBase > parents ()
const FourVector p_in () const
const FourVector & x_in () const
const FourVector & jet_v () const
const double restmass ()
const double p (int i)
double pl ()
const double nu ()
const double t_max ()
virtual JetScapeParticleBase & operator= (JetScapeParticleBase &c)
virtual JetScapeParticleBase & operator= (const JetScapeParticleBase &c)
string GetController () const
bool GetControlled () const
Protected Attributes
bool is_shower_
bool is_thermal_
bool is_used_
bool is_decayedglu_
bool is_remnant_
bool used_reco_
bool used_str_
bool is_strendpt_
bool used_junction_
bool is_fakep_
int alt_id_
int orig_
int par_
int string_id_
int pos_str_
int endpt_id_
int sibling_
int PY_par1_
int PY_par2_
int PY_dau1_
int PY_dau2_
int PY_stat_
int PY_origid_
int PY_tag1_
int PY_tag2_
int PY_tag3_
double alt_mass_
Protected Attributes inherited from Jetscape::Parton
double mean_form_time_
Mean formation time.
double form_time_
event by event formation time
unsigned int Color_
Large Nc color of parton.
unsigned int antiColor_
Large Nc anti-color of parton.
unsigned int MaxColor_
the running maximum color
unsigned int MinColor_
color of the parent
unsigned int MinAntiColor_
anti-color of the parent
weak_ptr< PartonShower > pShower_
shower that this parton belongs to
int edgeid_
Position in the shower graph.
Protected Attributes inherited from Jetscape::JetScapeParticleBase
int pid_
particle id
int pstat_
status of particle
int plabel_
the line number in the event record
double mass_
rest mass of the particle
FourVector x_in_
position of particle
FourVector jet_v_
jet four vector, without gamma factor (so not really a four vector)
bool controlled_ = false
check whether a module claimed responsibility of this particle
string controller_ = ""
Additional Inherited Members
Static Public Attributes inherited from Jetscape::JetScapeParticleBase
static Pythia8::Pythia InternalHelperPythia
Protected Member Functions inherited from Jetscape::Parton
void initialize_form_time ()
void CheckAcceptability (int id)
restrict to a few pids only.
Detailed Description
Definition at line 116 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 116 of file HybridHadronization.h
Constructor & Destructor Documentation
HybridHadronization::HHparton::HHparton () inline
Definition at line 128 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 128 of file HybridHadronization.h
Member Function Documentation
int HybridHadronization::HHparton::acol () inline
Definition at line 148 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 148 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), HybridHadronization::gluon_decay(), HybridHadronization::recomb(), and HybridHadronization::stringprep().
void HybridHadronization::HHparton::acol (int val) inline
Definition at line 171 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 171 of file HybridHadronization.h
FourVector HybridHadronization::HHparton::boost_P (FourVector B) inline
Definition at line 174 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 174 of file HybridHadronization.h
FourVector HybridHadronization::HHparton::boost_P (double vx, double vy, double vz) inline
Definition at line 175 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 175 of file HybridHadronization.h
FourVector HybridHadronization::HHparton::boost_pos (FourVector B) inline
Definition at line 176 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 176 of file HybridHadronization.h
FourVector HybridHadronization::HHparton::boost_pos (double vx, double vy, double vz) inline
Definition at line 177 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 177 of file HybridHadronization.h
int HybridHadronization::HHparton::col () inline
Definition at line 148 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 148 of file HybridHadronization.h
Referenced by item.Item::__eq__(), item.Item::__hash__(), HybridHadronization::DoHadronization(), HybridHadronization::gluon_decay(), HybridHadronization::recomb(), and HybridHadronization::stringprep().
void HybridHadronization::HHparton::col (int val) inline
Definition at line 171 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 171 of file HybridHadronization.h
Referenced by item.Item::__eq__(), and item.Item::__hash__().
double HybridHadronization::HHparton::e () inline
Definition at line 137 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 137 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), HybridHadronization::recomb(), HybridHadronization::set_initial_parton_masses(), and HybridHadronization::stringprep().
void HybridHadronization::HHparton::e (double val) inline
Definition at line 159 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 159 of file HybridHadronization.h
int HybridHadronization::HHparton::endpt_id () inline
Definition at line 142 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 142 of file HybridHadronization.h
void HybridHadronization::HHparton::endpt_id (int val) inline
Definition at line 166 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 166 of file HybridHadronization.h
int HybridHadronization::HHparton::id () inline
Definition at line 141 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 141 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), HybridHadronization::findcloserepl(), HybridHadronization::findcloserepl_glu(), HybridHadronization::gluon_decay(), HybridHadronization::recomb(), HybridHadronization::set_initial_parton_masses(), and HybridHadronization::stringprep().
void HybridHadronization::HHparton::id (int val) inline
Definition at line 165 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 165 of file HybridHadronization.h
bool HybridHadronization::HHparton::is_decayedglu () inline
Definition at line 138 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 138 of file HybridHadronization.h
void HybridHadronization::HHparton::is_decayedglu (bool val) inline
Definition at line 162 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 162 of file HybridHadronization.h
bool HybridHadronization::HHparton::is_fakeparton () inline
Definition at line 140 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 140 of file HybridHadronization.h
Referenced by HybridHadronization::recomb(), and HybridHadronization::stringprep().
void HybridHadronization::HHparton::is_fakeparton (bool val) inline
Definition at line 164 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 164 of file HybridHadronization.h
bool HybridHadronization::HHparton::is_remnant () inline
Definition at line 139 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 139 of file HybridHadronization.h
Referenced by HybridHadronization::recomb(), and HybridHadronization::stringprep().
void HybridHadronization::HHparton::is_remnant (bool val) inline
Definition at line 163 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 163 of file HybridHadronization.h
bool HybridHadronization::HHparton::is_shower () inline
Definition at line 138 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 138 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization().
void HybridHadronization::HHparton::is_shower (bool val) inline
Definition at line 162 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 162 of file HybridHadronization.h
bool HybridHadronization::HHparton::is_strendpt () inline
Definition at line 139 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 139 of file HybridHadronization.h
void HybridHadronization::HHparton::is_strendpt (bool val) inline
Definition at line 163 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 163 of file HybridHadronization.h
bool HybridHadronization::HHparton::is_thermal () inline
Definition at line 138 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 138 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), and HybridHadronization::findcloserepl_glu().
void HybridHadronization::HHparton::is_thermal (bool val) inline
Definition at line 162 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 162 of file HybridHadronization.h
bool HybridHadronization::HHparton::is_used () inline
Definition at line 138 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 138 of file HybridHadronization.h
void HybridHadronization::HHparton::is_used (bool val) inline
Definition at line 162 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 162 of file HybridHadronization.h
double HybridHadronization::HHparton::mass () inline
Definition at line 145 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 145 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), HybridHadronization::gluon_decay(), HybridHadronization::recomb(), HybridHadronization::set_initial_parton_masses(), and HybridHadronization::stringprep().
void HybridHadronization::HHparton::mass (double val) inline
Definition at line 170 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 170 of file HybridHadronization.h
int HybridHadronization::HHparton::orig () inline
Definition at line 141 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 141 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), HybridHadronization::recomb(), and HybridHadronization::stringprep().
void HybridHadronization::HHparton::orig (int val) inline
Definition at line 165 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 165 of file HybridHadronization.h
FourVector HybridHadronization::HHparton::P () inline
Definition at line 147 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 147 of file HybridHadronization.h
Referenced by HybridHadronization::gluon_decay().
void HybridHadronization::HHparton::P (FourVector val) inline
Definition at line 160 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 160 of file HybridHadronization.h
int HybridHadronization::HHparton::par () inline
Definition at line 141 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 141 of file HybridHadronization.h
void HybridHadronization::HHparton::par (int val) inline
Definition at line 165 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 165 of file HybridHadronization.h
double HybridHadronization::HHparton::pDif2 (HHparton comp) inline
Definition at line 179 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 179 of file HybridHadronization.h
References Jetscape::JetScapeParticleBase::p_in().
FourVector HybridHadronization::HHparton::pos () inline
Definition at line 146 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 146 of file HybridHadronization.h
Referenced by HybridHadronization::gluon_decay().
void HybridHadronization::HHparton::pos (FourVector val) inline
Definition at line 155 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 155 of file HybridHadronization.h
References Jetscape::FourVector::t(), Jetscape::FourVector::x(), Jetscape::FourVector::y(), and Jetscape::FourVector::z().
int HybridHadronization::HHparton::pos_str () const inline
Definition at line 141 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 141 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), and HybridHadronization::stringform().
void HybridHadronization::HHparton::pos_str (int val) inline
Definition at line 166 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 166 of file HybridHadronization.h
double HybridHadronization::HHparton::posDif2 (HHparton comp) inline
Definition at line 180 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 180 of file HybridHadronization.h
References Jetscape::JetScapeParticleBase::x_in().
Referenced by HybridHadronization::findcloserepl(), and HybridHadronization::findcloserepl_glu().
double HybridHadronization::HHparton::px () inline
Definition at line 137 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 137 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), HybridHadronization::gluon_decay(), HybridHadronization::recomb(), HybridHadronization::set_initial_parton_masses(), and HybridHadronization::stringprep().
void HybridHadronization::HHparton::px (double val) inline
Definition at line 156 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 156 of file HybridHadronization.h
References Acts::UnitConstants::e.
double HybridHadronization::HHparton::py () inline
Definition at line 137 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 137 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), HybridHadronization::gluon_decay(), HybridHadronization::recomb(), HybridHadronization::set_initial_parton_masses(), and HybridHadronization::stringprep().
void HybridHadronization::HHparton::py (double val) inline
Definition at line 157 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 157 of file HybridHadronization.h
References Acts::UnitConstants::e.
int HybridHadronization::HHparton::PY_dau1 () inline
Definition at line 143 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 143 of file HybridHadronization.h
void HybridHadronization::HHparton::PY_dau1 (int val) inline
Definition at line 167 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 167 of file HybridHadronization.h
int HybridHadronization::HHparton::PY_dau2 () inline
Definition at line 143 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 143 of file HybridHadronization.h
void HybridHadronization::HHparton::PY_dau2 (int val) inline
Definition at line 167 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 167 of file HybridHadronization.h
int HybridHadronization::HHparton::PY_origid () inline
Definition at line 143 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 143 of file HybridHadronization.h
void HybridHadronization::HHparton::PY_origid (int val) inline
Definition at line 168 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 168 of file HybridHadronization.h
int HybridHadronization::HHparton::PY_par1 () inline
Definition at line 142 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 142 of file HybridHadronization.h
void HybridHadronization::HHparton::PY_par1 (int val) inline
Definition at line 167 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 167 of file HybridHadronization.h
int HybridHadronization::HHparton::PY_par2 () inline
Definition at line 142 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 142 of file HybridHadronization.h
void HybridHadronization::HHparton::PY_par2 (int val) inline
Definition at line 167 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 167 of file HybridHadronization.h
int HybridHadronization::HHparton::PY_stat () inline
Definition at line 143 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 143 of file HybridHadronization.h
Referenced by HybridHadronization::stringprep().
void HybridHadronization::HHparton::PY_stat (int val) inline
Definition at line 168 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 168 of file HybridHadronization.h
int HybridHadronization::HHparton::PY_tag1 () inline
Definition at line 144 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 144 of file HybridHadronization.h
Referenced by HybridHadronization::stringprep().
void HybridHadronization::HHparton::PY_tag1 (int val) inline
Definition at line 169 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 169 of file HybridHadronization.h
int HybridHadronization::HHparton::PY_tag2 () inline
Definition at line 144 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 144 of file HybridHadronization.h
Referenced by HybridHadronization::stringprep().
void HybridHadronization::HHparton::PY_tag2 (int val) inline
Definition at line 169 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 169 of file HybridHadronization.h
int HybridHadronization::HHparton::PY_tag3 () inline
Definition at line 144 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 144 of file HybridHadronization.h
Referenced by HybridHadronization::stringprep().
void HybridHadronization::HHparton::PY_tag3 (int val) inline
Definition at line 169 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 169 of file HybridHadronization.h
double HybridHadronization::HHparton::pz () inline
Definition at line 137 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 137 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), HybridHadronization::gluon_decay(), HybridHadronization::recomb(), HybridHadronization::set_initial_parton_masses(), and HybridHadronization::stringprep().
void HybridHadronization::HHparton::pz (double val) inline
Definition at line 158 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 158 of file HybridHadronization.h
References Acts::UnitConstants::e.
int HybridHadronization::HHparton::sibling () inline
Definition at line 142 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 142 of file HybridHadronization.h
Referenced by HybridHadronization::findcloserepl().
void HybridHadronization::HHparton::sibling (int val) inline
Definition at line 166 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 166 of file HybridHadronization.h
int HybridHadronization::HHparton::status () inline
Definition at line 148 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 148 of file HybridHadronization.h
void HybridHadronization::HHparton::status (int val) inline
Definition at line 171 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 171 of file HybridHadronization.h
int HybridHadronization::HHparton::string_id () const inline
Definition at line 141 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 141 of file HybridHadronization.h
Referenced by HybridHadronization::stringform().
void HybridHadronization::HHparton::string_id (int val) inline
Definition at line 166 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 166 of file HybridHadronization.h
bool HybridHadronization::HHparton::used_junction () inline
Definition at line 140 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 140 of file HybridHadronization.h
void HybridHadronization::HHparton::used_junction (bool val) inline
Definition at line 164 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 164 of file HybridHadronization.h
bool HybridHadronization::HHparton::used_reco () inline
Definition at line 139 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 139 of file HybridHadronization.h
void HybridHadronization::HHparton::used_reco (bool val) inline
Definition at line 163 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 163 of file HybridHadronization.h
bool HybridHadronization::HHparton::used_str () inline
Definition at line 139 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 139 of file HybridHadronization.h
void HybridHadronization::HHparton::used_str (bool val) inline
Definition at line 163 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 163 of file HybridHadronization.h
double HybridHadronization::HHparton::x () inline
Definition at line 136 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 136 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), and HybridHadronization::gluon_decay().
void HybridHadronization::HHparton::x (double val) inline
Definition at line 151 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 151 of file HybridHadronization.h
References t, y, and physmon_track_finding_ttbar::z.
double HybridHadronization::HHparton::x_t () inline
Definition at line 136 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 136 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), HybridHadronization::findcloserepl(), HybridHadronization::findcloserepl_glu(), and HybridHadronization::gluon_decay().
void HybridHadronization::HHparton::x_t (double val) inline
Definition at line 154 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 154 of file HybridHadronization.h
References ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
double HybridHadronization::HHparton::y () inline
Definition at line 136 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 136 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), and HybridHadronization::gluon_decay().
void HybridHadronization::HHparton::y (double val) inline
Definition at line 152 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 152 of file HybridHadronization.h
References t, ambiguity_solver_full_chain::x, and physmon_track_finding_ttbar::z.
double HybridHadronization::HHparton::z () inline
Definition at line 136 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 136 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), and HybridHadronization::gluon_decay().
void HybridHadronization::HHparton::z (double val) inline
Definition at line 153 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 153 of file HybridHadronization.h
References t, ambiguity_solver_full_chain::x, and y.
Member Data Documentation
int HybridHadronization::HHparton::alt_id_ protected
Definition at line 122 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 122 of file HybridHadronization.h
double HybridHadronization::HHparton::alt_mass_ protected
Definition at line 124 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 124 of file HybridHadronization.h
int HybridHadronization::HHparton::endpt_id_ protected
Definition at line 122 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 122 of file HybridHadronization.h
bool HybridHadronization::HHparton::is_decayedglu_ protected
Definition at line 119 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 119 of file HybridHadronization.h
bool HybridHadronization::HHparton::is_fakep_ protected
Definition at line 119 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 119 of file HybridHadronization.h
bool HybridHadronization::HHparton::is_remnant_ protected
Definition at line 119 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 119 of file HybridHadronization.h
bool HybridHadronization::HHparton::is_shower_ protected
Definition at line 119 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 119 of file HybridHadronization.h
bool HybridHadronization::HHparton::is_strendpt_ protected
Definition at line 119 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 119 of file HybridHadronization.h
bool HybridHadronization::HHparton::is_thermal_ protected
Definition at line 119 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 119 of file HybridHadronization.h
bool HybridHadronization::HHparton::is_used_ protected
Definition at line 119 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 119 of file HybridHadronization.h
int HybridHadronization::HHparton::orig_ protected
Definition at line 122 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 122 of file HybridHadronization.h
int HybridHadronization::HHparton::par_ protected
Definition at line 122 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 122 of file HybridHadronization.h
int HybridHadronization::HHparton::pos_str_ protected
Definition at line 122 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 122 of file HybridHadronization.h
int HybridHadronization::HHparton::PY_dau1_ protected
Definition at line 122 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 122 of file HybridHadronization.h
int HybridHadronization::HHparton::PY_dau2_ protected
Definition at line 122 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 122 of file HybridHadronization.h
int HybridHadronization::HHparton::PY_origid_ protected
Definition at line 122 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 122 of file HybridHadronization.h
int HybridHadronization::HHparton::PY_par1_ protected
Definition at line 122 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 122 of file HybridHadronization.h
int HybridHadronization::HHparton::PY_par2_ protected
Definition at line 122 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 122 of file HybridHadronization.h
int HybridHadronization::HHparton::PY_stat_ protected
Definition at line 122 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 122 of file HybridHadronization.h
int HybridHadronization::HHparton::PY_tag1_ protected
Definition at line 122 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 122 of file HybridHadronization.h
int HybridHadronization::HHparton::PY_tag2_ protected
Definition at line 122 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 122 of file HybridHadronization.h
int HybridHadronization::HHparton::PY_tag3_ protected
Definition at line 122 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 122 of file HybridHadronization.h
int HybridHadronization::HHparton::sibling_ protected
Definition at line 122 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 122 of file HybridHadronization.h
int HybridHadronization::HHparton::string_id_ protected
Definition at line 122 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 122 of file HybridHadronization.h
bool HybridHadronization::HHparton::used_junction_ protected
Definition at line 119 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 119 of file HybridHadronization.h
bool HybridHadronization::HHparton::used_reco_ protected
Definition at line 119 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 119 of file HybridHadronization.h
bool HybridHadronization::HHparton::used_str_ protected
Definition at line 119 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 119 of file HybridHadronization.h
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/src/hadronization/HybridHadronization.h