Analysis Software: CMFlashDifference Class Reference
CMFlashDifference Class Reference
Base class for Central Membrane flassh combined difference object.
#include <coresoftware/blob/master/offline/packages/trackbase/CMFlashDifference.h>
Public Member Functions
~CMFlashDifference () override
dtor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
virtual void CopyFrom (const CMFlashDifference &)
copy content from base class
virtual void CopyFrom (CMFlashDifference *)
copy content from base class
virtual float getTruthPhi () const
virtual void setTruthPhi (float)
virtual float getRecoPhi () const
virtual void setRecoPhi (float)
virtual float getTruthR () const
virtual void setTruthR (float)
virtual float getRecoR () const
virtual void setRecoR (float)
virtual float getTruthZ () const
virtual void setTruthZ (float)
virtual float getRecoZ () const
virtual void setRecoZ (float)
virtual unsigned int getNclusters () const
virtual void setNclusters (unsigned int)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
CMFlashDifference ()=default
Detailed Description
Base class for Central Membrane flassh combined difference object.
Virtual base class for TPC CM flash difference object
Definition at line 23 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 23 of file CMFlashDifference.h
Constructor & Destructor Documentation
CMFlashDifference::~CMFlashDifference () inline override
dtor
Definition at line 27 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 27 of file CMFlashDifference.h
CMFlashDifference::CMFlashDifference () protected default
Member Function Documentation
virtual void CMFlashDifference::CopyFrom (const CMFlashDifference &) inline virtual
copy content from base class
Reimplemented in CMFlashDifferencev1.
Definition at line 41 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 41 of file CMFlashDifference.h
Referenced by CMFlashDifferencev1::CopyFrom().
virtual void CMFlashDifference::CopyFrom (CMFlashDifference *) inline virtual
copy content from base class
Reimplemented in CMFlashDifferencev1.
Definition at line 44 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 44 of file CMFlashDifference.h
virtual unsigned int CMFlashDifference::getNclusters () const inline virtual
Reimplemented in CMFlashDifferencev1.
Definition at line 67 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 67 of file CMFlashDifference.h
Referenced by CMFlashDifferencev1::CopyFrom().
virtual float CMFlashDifference::getRecoPhi () const inline virtual
Reimplemented in CMFlashDifferencev1.
Definition at line 52 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 52 of file CMFlashDifference.h
Referenced by CMFlashDifferencev1::CopyFrom().
virtual float CMFlashDifference::getRecoR () const inline virtual
Reimplemented in CMFlashDifferencev1.
Definition at line 58 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 58 of file CMFlashDifference.h
Referenced by CMFlashDifferencev1::CopyFrom().
virtual float CMFlashDifference::getRecoZ () const inline virtual
Reimplemented in CMFlashDifferencev1.
Definition at line 64 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 64 of file CMFlashDifference.h
Referenced by CMFlashDifferencev1::CopyFrom().
virtual float CMFlashDifference::getTruthPhi () const inline virtual
Reimplemented in CMFlashDifferencev1.
Definition at line 49 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 49 of file CMFlashDifference.h
Referenced by CMFlashDifferencev1::CopyFrom().
virtual float CMFlashDifference::getTruthR () const inline virtual
Reimplemented in CMFlashDifferencev1.
Definition at line 55 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 55 of file CMFlashDifference.h
Referenced by CMFlashDifferencev1::CopyFrom().
virtual float CMFlashDifference::getTruthZ () const inline virtual
Reimplemented in CMFlashDifferencev1.
Definition at line 61 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 61 of file CMFlashDifference.h
Referenced by CMFlashDifferencev1::CopyFrom().
void CMFlashDifference::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in CMFlashDifferencev1.
Definition at line 29 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 29 of file CMFlashDifference.h
References os.
int CMFlashDifference::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in CMFlashDifferencev1.
Definition at line 34 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 34 of file CMFlashDifference.h
void CMFlashDifference::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in CMFlashDifferencev1.
Definition at line 33 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 33 of file CMFlashDifference.h
virtual void CMFlashDifference::setNclusters (unsigned int) inline virtual
Reimplemented in CMFlashDifferencev1.
Definition at line 68 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 68 of file CMFlashDifference.h
virtual void CMFlashDifference::setRecoPhi (float) inline virtual
Reimplemented in CMFlashDifferencev1.
Definition at line 53 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 53 of file CMFlashDifference.h
virtual void CMFlashDifference::setRecoR (float) inline virtual
Reimplemented in CMFlashDifferencev1.
Definition at line 59 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 59 of file CMFlashDifference.h
virtual void CMFlashDifference::setRecoZ (float) inline virtual
Reimplemented in CMFlashDifferencev1.
Definition at line 65 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 65 of file CMFlashDifference.h
virtual void CMFlashDifference::setTruthPhi (float) inline virtual
Reimplemented in CMFlashDifferencev1.
Definition at line 50 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 50 of file CMFlashDifference.h
virtual void CMFlashDifference::setTruthR (float) inline virtual
Reimplemented in CMFlashDifferencev1.
Definition at line 56 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 56 of file CMFlashDifference.h
virtual void CMFlashDifference::setTruthZ (float) inline virtual
Reimplemented in CMFlashDifferencev1.
Definition at line 62 of file CMFlashDifference.h.
View newest version in sPHENIX GitHub at line 62 of file CMFlashDifference.h
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase/CMFlashDifference.h