Analysis Software: PHG4MvtxSteppingAction Class Reference
PHG4MvtxSteppingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4MvtxSteppingAction.h>
Public Member Functions
PHG4MvtxSteppingAction (PHG4MvtxDetector *detector, PHParametersContainer *paramscont)
constructor
~PHG4MvtxSteppingAction () override
destroctor
bool UserSteppingAction (const G4Step *, bool) override
stepping action
void SetInterfacePointers (PHCompositeNode *) override
reimplemented from base class
void SetHitNodeName (const std::string &type, const std::string &name) override
Set the G4HIT node names from Subsystem rather than constructing your own.
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual int InitWithNode (PHCompositeNode *)
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
Private Attributes
PHG4MvtxDetector * m_Detector {nullptr}
pointer to the detector
PHG4HitContainer * m_HitContainer {nullptr}
pointer to hit container
PHG4HitContainer * m_SupportHitContainer {nullptr}
PHG4HitContainer * m_SaveHitContainer {nullptr}
PHG4Hit * m_Hit {nullptr}
PHG4Shower * m_SaveShower {nullptr}
int m_SupportActiveFlag {0}
int m_BlackHoleFlag {0}
std::string m_HitNodeName
std::string m_SupportNodeName
Detailed Description
Definition at line 16 of file PHG4MvtxSteppingAction.h.
View newest version in sPHENIX GitHub at line 16 of file PHG4MvtxSteppingAction.h
Constructor & Destructor Documentation
PHG4MvtxSteppingAction::PHG4MvtxSteppingAction (PHG4MvtxDetector * detector, PHParametersContainer * paramscont)
constructor
Definition at line 58 of file PHG4MvtxSteppingAction.cc.
View newest version in sPHENIX GitHub at line 58 of file PHG4MvtxSteppingAction.cc
References PHParameters::get_int_param(), PHParametersContainer::GetAllParameters(), PHParametersContainer::GetParameters(), m_BlackHoleFlag, and m_SupportActiveFlag.
PHG4MvtxSteppingAction::~PHG4MvtxSteppingAction () override
destroctor
Definition at line 82 of file PHG4MvtxSteppingAction.cc.
View newest version in sPHENIX GitHub at line 82 of file PHG4MvtxSteppingAction.cc
References m_Hit.
Member Function Documentation
void PHG4MvtxSteppingAction::SetHitNodeName (const std::string & , const std::string &) override virtual
Set the G4HIT node names from Subsystem rather than constructing your own.
Reimplemented from PHG4SteppingAction.
Definition at line 516 of file PHG4MvtxSteppingAction.cc.
View newest version in sPHENIX GitHub at line 516 of file PHG4MvtxSteppingAction.cc
References m_HitNodeName, m_SupportNodeName, and perf_headwind::name.
void PHG4MvtxSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) override virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 493 of file PHG4MvtxSteppingAction.cc.
View newest version in sPHENIX GitHub at line 493 of file PHG4MvtxSteppingAction.cc
References m_BlackHoleFlag, m_HitContainer, m_HitNodeName, m_SupportHitContainer, m_SupportNodeName, and PHG4SteppingAction::Verbosity().
bool PHG4MvtxSteppingAction::UserSteppingAction (const G4Step * aStep, bool) override virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 92 of file PHG4MvtxSteppingAction.cc.
View newest version in sPHENIX GitHub at line 92 of file PHG4MvtxSteppingAction.cc
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, PHG4Hit::get_edep(), PHG4Hit::get_hit_id(), PHG4HitContainer::GetID(), Acts::UnitConstants::GeV, PHG4MvtxDetector::IsActive(), PHG4MvtxDetector::IsBlackHole(), PHG4MvtxDetector::IsInMvtx(), PHG4MvtxDetector::IsSensor(), m_Detector, m_Hit, m_HitContainer, m_SaveHitContainer, m_SaveShower, m_SupportActiveFlag, m_SupportHitContainer, merge_hashes::p, PHWHERE, PHG4Hit::print(), PHG4Hit::prop_chip_index, PHG4Hit::prop_half_stave_index, PHG4Hit::prop_module_index, PHG4Hit::prop_stave_index, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_layer(), PHG4Hit::set_property(), PHG4Hit::set_px(), PHG4Hit::set_py(), PHG4Hit::set_pz(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), PHG4SteppingAction::StoreLocalCoordinate(), v1, v2, v3, and PHG4SteppingAction::Verbosity().
Member Data Documentation
int PHG4MvtxSteppingAction::m_BlackHoleFlag {0} private
Definition at line 45 of file PHG4MvtxSteppingAction.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4MvtxSteppingAction.h
Referenced by PHG4MvtxSteppingAction(), and SetInterfacePointers().
PHG4MvtxDetector* PHG4MvtxSteppingAction::m_Detector {nullptr} private
pointer to the detector
Definition at line 35 of file PHG4MvtxSteppingAction.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4MvtxSteppingAction.h
Referenced by UserSteppingAction().
PHG4Hit* PHG4MvtxSteppingAction::m_Hit {nullptr} private
Definition at line 41 of file PHG4MvtxSteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4MvtxSteppingAction.h
Referenced by UserSteppingAction(), and ~PHG4MvtxSteppingAction().
PHG4HitContainer* PHG4MvtxSteppingAction::m_HitContainer {nullptr} private
pointer to hit container
Definition at line 38 of file PHG4MvtxSteppingAction.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4MvtxSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::string PHG4MvtxSteppingAction::m_HitNodeName private
Definition at line 47 of file PHG4MvtxSteppingAction.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4MvtxSteppingAction.h
Referenced by SetHitNodeName(), and SetInterfacePointers().
PHG4HitContainer* PHG4MvtxSteppingAction::m_SaveHitContainer {nullptr} private
Definition at line 40 of file PHG4MvtxSteppingAction.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4MvtxSteppingAction.h
Referenced by UserSteppingAction().
PHG4Shower* PHG4MvtxSteppingAction::m_SaveShower {nullptr} private
Definition at line 42 of file PHG4MvtxSteppingAction.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4MvtxSteppingAction.h
Referenced by UserSteppingAction().
int PHG4MvtxSteppingAction::m_SupportActiveFlag {0} private
Definition at line 44 of file PHG4MvtxSteppingAction.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4MvtxSteppingAction.h
Referenced by PHG4MvtxSteppingAction(), and UserSteppingAction().
PHG4HitContainer* PHG4MvtxSteppingAction::m_SupportHitContainer {nullptr} private
Definition at line 39 of file PHG4MvtxSteppingAction.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4MvtxSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::string PHG4MvtxSteppingAction::m_SupportNodeName private
Definition at line 48 of file PHG4MvtxSteppingAction.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4MvtxSteppingAction.h
Referenced by SetHitNodeName(), and SetInterfacePointers().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4MvtxSteppingAction.h
coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4MvtxSteppingAction.cc