Analysis Software: DaqMon Class Reference
DaqMon Class Reference
#include <OnlMon/blob/main/subsystems/daq/DaqMon.h>
Public Member Functions
DaqMon (const std::string &name="DAQMON")
virtual ~DaqMon ()
int process_event (Event *evt)
int Init ()
int BeginRun (const int runno)
int Reset ()
Public Member Functions inherited from OnlMon
OnlMon (const std::string &name="NONE")
~OnlMon () override
virtual int process_event_common (Event *evt)
virtual int InitCommon (OnlMonServer *se)
virtual void identify (std::ostream &out=std::cout) const
virtual int BeginRunCommon (const int runno, OnlMonServer *se)
virtual int EndRun (const int)
virtual void SetStatus (const int newstatus)
virtual int ResetEvent ()
virtual void SetMonitorServerId (unsigned int i)
virtual unsigned int MonitorServerId () const
Public Member Functions inherited from OnlMonBase
OnlMonBase (const std::string &name="NONE")
virtual ~OnlMonBase ()
const std::string Name () const
void Name (const std::string &name)
virtual void Verbosity (const int i)
virtual int Verbosity () const
Protected Attributes
int evtcnt = 0
int idummy = 0
TH1 * daqhist1 = nullptr
TH2 * daqhist2 = nullptr
Protected Attributes inherited from OnlMon
int status
unsigned int m_MonitorServerId = 0
TH1 * m_LocalFrameWorkVars = nullptr
Protected Attributes inherited from OnlMonBase
std::string ThisName
int verbosity = 0
Additional Inherited Members
Public Types inherited from OnlMon
enum { ACTIVE = -1, OK = 0, WARNING = 1, ERROR = 2 }
Detailed Description
Definition at line 10 of file DaqMon.h.
View newest version in sPHENIX GitHub at line 10 of file DaqMon.h
Constructor & Destructor Documentation
DaqMon::DaqMon (const std::string & name = "DAQMON")
Definition at line 31 of file DaqMon.cc.
View newest version in sPHENIX GitHub at line 31 of file DaqMon.cc
DaqMon::~DaqMon () virtual
Definition at line 39 of file DaqMon.cc.
View newest version in sPHENIX GitHub at line 39 of file DaqMon.cc
Member Function Documentation
int DaqMon::BeginRun (const int runno) virtual
Reimplemented from OnlMon.
Definition at line 71 of file DaqMon.cc.
View newest version in sPHENIX GitHub at line 71 of file DaqMon.cc
int DaqMon::Init () virtual
Reimplemented from OnlMon.
Definition at line 45 of file DaqMon.cc.
View newest version in sPHENIX GitHub at line 45 of file DaqMon.cc
References daqhist1, daqhist2, OnlMonServer::instance(), printf(), OnlMonServer::registerHisto(), and Reset().
int DaqMon::process_event (Event * evt) virtual
Reimplemented from OnlMon.
Definition at line 78 of file DaqMon.cc.
View newest version in sPHENIX GitHub at line 78 of file DaqMon.cc
References daqhist1, daqhist2, and evtcnt.
int DaqMon::Reset () virtual
Reimplemented from OnlMon.
Definition at line 91 of file DaqMon.cc.
View newest version in sPHENIX GitHub at line 91 of file DaqMon.cc
References evtcnt, and idummy.
Referenced by Init().
Member Data Documentation
TH1* DaqMon::daqhist1 = nullptr protected
Definition at line 24 of file DaqMon.h.
View newest version in sPHENIX GitHub at line 24 of file DaqMon.h
Referenced by Init(), and process_event().
TH2* DaqMon::daqhist2 = nullptr protected
Definition at line 25 of file DaqMon.h.
View newest version in sPHENIX GitHub at line 25 of file DaqMon.h
Referenced by Init(), and process_event().
int DaqMon::evtcnt = 0 protected
Definition at line 22 of file DaqMon.h.
View newest version in sPHENIX GitHub at line 22 of file DaqMon.h
Referenced by process_event(), and Reset().
int DaqMon::idummy = 0 protected
Definition at line 23 of file DaqMon.h.
View newest version in sPHENIX GitHub at line 23 of file DaqMon.h
Referenced by Reset().
The documentation for this class was generated from the following files:
OnlMon/blob/main/subsystems/daq/DaqMon.h
OnlMon/blob/main/subsystems/daq/DaqMon.cc