Analysis Software: SingleTpcPoolInput Class Reference
SingleTpcPoolInput Class Reference
#include <coresoftware/blob/master/offline/framework/fun4allraw/SingleTpcPoolInput.h>
Public Member Functions
SingleTpcPoolInput (const std::string &name)
~SingleTpcPoolInput () override
void FillPool (const unsigned int) override
void CleanupUsedPackets (const uint64_t bclk) override
bool CheckPoolDepth (const uint64_t bclk) override
void ClearCurrentEvent () override
bool GetSomeMoreEvents ()
void Print (const std::string &what="ALL") const override
void CreateDSTNode (PHCompositeNode *topNode) override
void SetBcoRange (const unsigned int i)
void ConfigureStreamingInputManager () override
void SetNegativeBco (const unsigned int value)
Public Member Functions inherited from SingleStreamingInput
SingleStreamingInput (const std::string &name, Fun4AllEvtInputPoolManager *inman)
SingleStreamingInput (const std::string &name)
~SingleStreamingInput () override
virtual Eventiterator * GetEventIterator ()
virtual void FillPool (const uint64_t)
virtual void RunNumber (const int runno)
virtual int RunNumber () const
virtual int fileopen (const std::string &filename) override
virtual int fileclose () override
virtual int AllDone () const
virtual void AllDone (const int i)
virtual void EventNumberOffset (const int i)
virtual Eventiterator * GetEventiterator () const
virtual
Fun4AllEvtInputPoolManager * InputManager ()
virtual void InputManager (Fun4AllEvtInputPoolManager *in)
virtual
Fun4AllStreamingInputManager * StreamingInputManager ()
virtual void StreamingInputManager (Fun4AllStreamingInputManager *in)
virtual void SubsystemEnum (const int id)
virtual int SubsystemEnum () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from InputFileHandler
InputFileHandler ()=default
virtual ~InputFileHandler ()=default
int OpenNextFile ()
int AddListFile (const std::string &filename)
int AddFile (const std::string &filename)
void AddToFileOpened (const std::string &filename)
void Print (const std::string &what="ALL") const
int IsOpen () const
void IsOpen (const int i)
void SetVerbosity (const int i)
int GetVerbosity () const
void UpdateFileList ()
void FileName (const std::string &fn)
const std::string FileName () const
Private Attributes
Packet ** plist {nullptr}
unsigned int m_NumSpecialEvents {0}
unsigned int m_BcoRange {0}
unsigned int m_NegativeBco {0}
std::map< unsigned int, uint64_t > m_packet_bco
map bco to packet
std::map< uint64_t, std::set
< int > > m_BeamClockFEE
std::map< uint64_t,
std::vector< TpcRawHit * > > m_TpcRawHitMap
std::map< int, uint64_t > m_FEEBclkMap
std::set< uint64_t > m_BclkStack
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Detailed Description
Definition at line 16 of file SingleTpcPoolInput.h.
View newest version in sPHENIX GitHub at line 16 of file SingleTpcPoolInput.h
Constructor & Destructor Documentation
SingleTpcPoolInput::SingleTpcPoolInput (const std::string & name) explicit
Definition at line 25 of file SingleTpcPoolInput.cc.
View newest version in sPHENIX GitHub at line 25 of file SingleTpcPoolInput.cc
References NPACKETS, plist, SingleStreamingInput::SubsystemEnum(), and Fun4AllStreamingInputManager::TPC.
SingleTpcPoolInput::~SingleTpcPoolInput () override
Definition at line 32 of file SingleTpcPoolInput.cc.
View newest version in sPHENIX GitHub at line 32 of file SingleTpcPoolInput.cc
References plist.
Member Function Documentation
bool SingleTpcPoolInput::CheckPoolDepth (const uint64_t bclk) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 246 of file SingleTpcPoolInput.cc.
View newest version in sPHENIX GitHub at line 246 of file SingleTpcPoolInput.cc
References m_FEEBclkMap, and Fun4AllBase::Verbosity().
void SingleTpcPoolInput::CleanupUsedPackets (const uint64_t bclk) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 215 of file SingleTpcPoolInput.cc.
View newest version in sPHENIX GitHub at line 215 of file SingleTpcPoolInput.cc
References m_BclkStack, m_BeamClockFEE, and m_TpcRawHitMap.
Referenced by ClearCurrentEvent().
void SingleTpcPoolInput::ClearCurrentEvent () override virtual
Reimplemented from SingleStreamingInput.
Definition at line 273 of file SingleTpcPoolInput.cc.
View newest version in sPHENIX GitHub at line 273 of file SingleTpcPoolInput.cc
References CleanupUsedPackets(), and m_BclkStack.
void SingleTpcPoolInput::ConfigureStreamingInputManager () override virtual
Reimplemented from SingleStreamingInput.
Definition at line 343 of file SingleTpcPoolInput.cc.
View newest version in sPHENIX GitHub at line 343 of file SingleTpcPoolInput.cc
References m_BcoRange, m_NegativeBco, Fun4AllStreamingInputManager::SetTpcBcoRange(), Fun4AllStreamingInputManager::SetTpcNegativeBco(), and SingleStreamingInput::StreamingInputManager().
void SingleTpcPoolInput::CreateDSTNode (PHCompositeNode * topNode) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 318 of file SingleTpcPoolInput.cc.
View newest version in sPHENIX GitHub at line 318 of file SingleTpcPoolInput.cc
References PHCompositeNode::addNode(), and PHNodeIterator::findFirst().
void SingleTpcPoolInput::FillPool (const unsigned int) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 37 of file SingleTpcPoolInput.cc.
View newest version in sPHENIX GitHub at line 37 of file SingleTpcPoolInput.cc
References Fun4AllStreamingInputManager::AddTpcRawHit(), SingleStreamingInput::AllDone(), DATAEVENT, SingleStreamingInput::fileclose(), SingleStreamingInput::GetEventiterator(), Event::getEvtSequence(), Event::getEvtType(), Packet::getIdentifier(), Event::getPacketList(), Event::getRunNumber(), GetSomeMoreEvents(), InputFileHandler::GetVerbosity(), i, Event::identify(), m_BclkStack, m_BeamClockFEE, m_FEEBclkMap, m_NumSpecialEvents, m_packet_bco, m_TpcRawHitMap, NPACKETS, InputFileHandler::OpenNextFile(), plist, SingleStreamingInput::RunNumber(), TpcRawHit::set_adc(), TpcRawHit::set_bco(), TpcRawHit::set_channel(), TpcRawHit::set_fee(), TpcRawHit::set_gtm_bco(), TpcRawHit::set_packetid(), TpcRawHit::set_sampaaddress(), TpcRawHit::set_sampachannel(), TpcRawHit::set_samples(), SingleStreamingInput::StreamingInputManager(), t, and Fun4AllBase::Verbosity().
bool SingleTpcPoolInput::GetSomeMoreEvents ()
Definition at line 284 of file SingleTpcPoolInput.cc.
View newest version in sPHENIX GitHub at line 284 of file SingleTpcPoolInput.cc
References SingleStreamingInput::AllDone(), m_BcoRange, m_FEEBclkMap, and m_TpcRawHitMap.
Referenced by FillPool().
void SingleTpcPoolInput::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from SingleStreamingInput.
Definition at line 173 of file SingleTpcPoolInput.cc.
View newest version in sPHENIX GitHub at line 173 of file SingleTpcPoolInput.cc
References m_BclkStack, m_BeamClockFEE, m_FEEBclkMap, and m_TpcRawHitMap.
void SingleTpcPoolInput::SetBcoRange (const unsigned int i) inline
Definition at line 28 of file SingleTpcPoolInput.h.
View newest version in sPHENIX GitHub at line 28 of file SingleTpcPoolInput.h
References i, and m_BcoRange.
Referenced by Fun4All_Stream_Combiner(), and Fun4All_Tpc_Combiner().
void SingleTpcPoolInput::SetNegativeBco (const unsigned int value) inline
Definition at line 30 of file SingleTpcPoolInput.h.
View newest version in sPHENIX GitHub at line 30 of file SingleTpcPoolInput.h
References m_NegativeBco, and value.
Member Data Documentation
std::set<uint64_t> SingleTpcPoolInput::m_BclkStack private
Definition at line 44 of file SingleTpcPoolInput.h.
View newest version in sPHENIX GitHub at line 44 of file SingleTpcPoolInput.h
Referenced by CleanupUsedPackets(), ClearCurrentEvent(), FillPool(), and Print().
unsigned int SingleTpcPoolInput::m_BcoRange {0} private
Definition at line 35 of file SingleTpcPoolInput.h.
View newest version in sPHENIX GitHub at line 35 of file SingleTpcPoolInput.h
Referenced by ConfigureStreamingInputManager(), GetSomeMoreEvents(), and SetBcoRange().
std::map<uint64_t, std::set<int> > SingleTpcPoolInput::m_BeamClockFEE private
Definition at line 41 of file SingleTpcPoolInput.h.
View newest version in sPHENIX GitHub at line 41 of file SingleTpcPoolInput.h
Referenced by CleanupUsedPackets(), FillPool(), and Print().
std::map<int, uint64_t> SingleTpcPoolInput::m_FEEBclkMap private
Definition at line 43 of file SingleTpcPoolInput.h.
View newest version in sPHENIX GitHub at line 43 of file SingleTpcPoolInput.h
Referenced by CheckPoolDepth(), FillPool(), GetSomeMoreEvents(), and Print().
unsigned int SingleTpcPoolInput::m_NegativeBco {0} private
Definition at line 36 of file SingleTpcPoolInput.h.
View newest version in sPHENIX GitHub at line 36 of file SingleTpcPoolInput.h
Referenced by ConfigureStreamingInputManager(), and SetNegativeBco().
unsigned int SingleTpcPoolInput::m_NumSpecialEvents {0} private
Definition at line 34 of file SingleTpcPoolInput.h.
View newest version in sPHENIX GitHub at line 34 of file SingleTpcPoolInput.h
Referenced by FillPool().
std::map<unsigned int, uint64_t> SingleTpcPoolInput::m_packet_bco private
map bco to packet
Definition at line 39 of file SingleTpcPoolInput.h.
View newest version in sPHENIX GitHub at line 39 of file SingleTpcPoolInput.h
Referenced by FillPool().
std::map<uint64_t, std::vector<TpcRawHit *> > SingleTpcPoolInput::m_TpcRawHitMap private
Definition at line 42 of file SingleTpcPoolInput.h.
View newest version in sPHENIX GitHub at line 42 of file SingleTpcPoolInput.h
Referenced by CleanupUsedPackets(), FillPool(), GetSomeMoreEvents(), and Print().
Packet** SingleTpcPoolInput::plist {nullptr} private
Definition at line 33 of file SingleTpcPoolInput.h.
View newest version in sPHENIX GitHub at line 33 of file SingleTpcPoolInput.h
Referenced by FillPool(), SingleTpcPoolInput(), and ~SingleTpcPoolInput().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4allraw/SingleTpcPoolInput.h
coresoftware/blob/master/offline/framework/fun4allraw/SingleTpcPoolInput.cc