Analysis Software: Acts::InternalSpacePoint< SpacePoint > Class Template Reference
Acts::InternalSpacePoint< SpacePoint > Class Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Seeding/InternalSpacePoint.hpp>
Public Member Functions
InternalSpacePoint ()=delete
InternalSpacePoint (std::size_t index, const SpacePoint &sp, const Acts::Vector3 &globalPos, const Acts::Vector2 &offsetXY, const Acts::Vector2 &variance)
InternalSpacePoint (const InternalSpacePoint< SpacePoint > &sp)
~InternalSpacePoint ()=default
InternalSpacePoint< SpacePoint > & operator= (const InternalSpacePoint< SpacePoint > &)=delete
std::size_t index () const
float x () const
float y () const
float z () const
float radius () const
float phi () const
float varianceR () const
float varianceZ () const
const SpacePoint & sp () const
Protected Attributes
std::size_t m_index
float m_x
float m_y
float m_z
float m_r
float m_phi
float m_varianceR
float m_varianceZ
std::reference_wrapper< const
SpacePoint > m_sp
Detailed Description
template<typename SpacePoint>
class Acts::InternalSpacePoint< SpacePoint >
Definition at line 20 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 20 of file InternalSpacePoint.hpp
Constructor & Destructor Documentation
template<typename SpacePoint> Acts::InternalSpacePoint< SpacePoint >::InternalSpacePoint () delete
template<typename SpacePoint> Acts::InternalSpacePoint< SpacePoint >::InternalSpacePoint (std::size_t index, const SpacePoint & sp, const Acts::Vector3 & globalPos, const Acts::Vector2 & offsetXY, const Acts::Vector2 & variance) inline
Definition at line 65 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 65 of file InternalSpacePoint.hpp
template<typename SpacePoint> Acts::InternalSpacePoint< SpacePoint >::InternalSpacePoint (const InternalSpacePoint< SpacePoint > & sp) inline default
template<typename SpacePoint> Acts::InternalSpacePoint< SpacePoint >::~InternalSpacePoint () default
Member Function Documentation
template<typename SpacePoint> std::size_t Acts::InternalSpacePoint< SpacePoint >::index () const inline
Definition at line 38 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 38 of file InternalSpacePoint.hpp
Referenced by Acts::SeedFilter< external_spacepoint_t >::filterSeeds_2SpFixed(), and Acts::xyzCoordinateCheck().
template<typename SpacePoint> InternalSpacePoint<SpacePoint>& Acts::InternalSpacePoint< SpacePoint >::operator= (const InternalSpacePoint< SpacePoint > &) delete
template<typename SpacePoint> float Acts::InternalSpacePoint< SpacePoint >::phi () const inline
Definition at line 43 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 43 of file InternalSpacePoint.hpp
Referenced by Acts::SeedFinderOrthogonal< external_spacepoint_t >::createSeeds().
template<typename SpacePoint> float Acts::InternalSpacePoint< SpacePoint >::radius () const inline
Definition at line 42 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 42 of file InternalSpacePoint.hpp
Referenced by Acts::SeedFinderOrthogonal< external_spacepoint_t >::createSeeds(), Acts::SeedFinder< external_spacepoint_t, platform_t >::filterCandidates(), Acts::SeedFinderOrthogonal< external_spacepoint_t >::filterCandidates(), Acts::SeedFilter< external_spacepoint_t >::filterSeeds_2SpFixed(), Acts::SeedFinder< external_spacepoint_t, platform_t >::getCompatibleDoublets(), Acts::SeedFinderOrthogonal< external_spacepoint_t >::processFromMiddleSP(), Acts::ATLASCuts< SpacePoint >::seedWeight(), TestHostCuts::seedWeight(), Acts::ATLASCuts< SpacePoint >::singleSeedCut(), TestHostCuts::singleSeedCut(), and Acts::SeedFinderOrthogonal< external_spacepoint_t >::validTuple().
template<typename SpacePoint> const SpacePoint& Acts::InternalSpacePoint< SpacePoint >::sp () const inline
Definition at line 46 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 46 of file InternalSpacePoint.hpp
Referenced by f2allm(), lujmas(), lusphe(), pyhimult(), pyjmas(), pymign(), pymult(), pysphe(), and pyxued().
template<typename SpacePoint> float Acts::InternalSpacePoint< SpacePoint >::varianceR () const inline
Definition at line 44 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 44 of file InternalSpacePoint.hpp
Referenced by Acts::SeedFinder< external_spacepoint_t, platform_t >::filterCandidates(), Acts::SeedFinderOrthogonal< external_spacepoint_t >::filterCandidates(), and Acts::SeedFinder< external_spacepoint_t, platform_t >::getCompatibleDoublets().
template<typename SpacePoint> float Acts::InternalSpacePoint< SpacePoint >::varianceZ () const inline
Definition at line 45 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 45 of file InternalSpacePoint.hpp
Referenced by Acts::SeedFinder< external_spacepoint_t, platform_t >::filterCandidates(), Acts::SeedFinderOrthogonal< external_spacepoint_t >::filterCandidates(), and Acts::SeedFinder< external_spacepoint_t, platform_t >::getCompatibleDoublets().
template<typename SpacePoint> float Acts::InternalSpacePoint< SpacePoint >::x () const inline
Definition at line 39 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 39 of file InternalSpacePoint.hpp
Referenced by Acts::SeedFinder< external_spacepoint_t, platform_t >::filterCandidates(), Acts::SeedFinder< external_spacepoint_t, platform_t >::getCompatibleDoublets(), and Acts::SeedFinderOrthogonal< external_spacepoint_t >::validTuple().
template<typename SpacePoint> float Acts::InternalSpacePoint< SpacePoint >::y () const inline
Definition at line 40 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 40 of file InternalSpacePoint.hpp
Referenced by Acts::SeedFinder< external_spacepoint_t, platform_t >::filterCandidates(), Acts::SeedFinder< external_spacepoint_t, platform_t >::getCompatibleDoublets(), and Acts::SeedFinderOrthogonal< external_spacepoint_t >::validTuple().
template<typename SpacePoint> float Acts::InternalSpacePoint< SpacePoint >::z () const inline
Definition at line 41 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 41 of file InternalSpacePoint.hpp
Referenced by Acts::SeedFinderOrthogonal< external_spacepoint_t >::createSeeds(), Acts::SeedFinder< external_spacepoint_t, platform_t >::filterCandidates(), Acts::SeedFinderOrthogonal< external_spacepoint_t >::filterCandidates(), Acts::SeedFilter< external_spacepoint_t >::filterSeeds_2SpFixed(), Acts::SeedFinder< external_spacepoint_t, platform_t >::getCompatibleDoublets(), Acts::SeedFinderOrthogonal< external_spacepoint_t >::processFromMiddleSP(), and Acts::SeedFinderOrthogonal< external_spacepoint_t >::validTuple().
Member Data Documentation
template<typename SpacePoint> std::size_t Acts::InternalSpacePoint< SpacePoint >::m_index protected
Definition at line 49 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 49 of file InternalSpacePoint.hpp
Referenced by Acts::InternalSpacePoint< external_spacepoint_t >::index().
template<typename SpacePoint> float Acts::InternalSpacePoint< SpacePoint >::m_phi protected
Definition at line 54 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 54 of file InternalSpacePoint.hpp
Referenced by Acts::InternalSpacePoint< external_spacepoint_t >::phi().
template<typename SpacePoint> float Acts::InternalSpacePoint< SpacePoint >::m_r protected
Definition at line 53 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 53 of file InternalSpacePoint.hpp
Referenced by Acts::InternalSpacePoint< external_spacepoint_t >::radius().
template<typename SpacePoint> std::reference_wrapper<const SpacePoint> Acts::InternalSpacePoint< SpacePoint >::m_sp protected
Definition at line 57 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 57 of file InternalSpacePoint.hpp
Referenced by Acts::InternalSpacePoint< external_spacepoint_t >::sp().
template<typename SpacePoint> float Acts::InternalSpacePoint< SpacePoint >::m_varianceR protected
Definition at line 55 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 55 of file InternalSpacePoint.hpp
Referenced by Acts::InternalSpacePoint< external_spacepoint_t >::varianceR().
template<typename SpacePoint> float Acts::InternalSpacePoint< SpacePoint >::m_varianceZ protected
Definition at line 56 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 56 of file InternalSpacePoint.hpp
Referenced by Acts::InternalSpacePoint< external_spacepoint_t >::varianceZ().
template<typename SpacePoint> float Acts::InternalSpacePoint< SpacePoint >::m_x protected
Definition at line 50 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 50 of file InternalSpacePoint.hpp
Referenced by Acts::InternalSpacePoint< external_spacepoint_t >::x().
template<typename SpacePoint> float Acts::InternalSpacePoint< SpacePoint >::m_y protected
Definition at line 51 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 51 of file InternalSpacePoint.hpp
Referenced by Acts::InternalSpacePoint< external_spacepoint_t >::y().
template<typename SpacePoint> float Acts::InternalSpacePoint< SpacePoint >::m_z protected
Definition at line 52 of file InternalSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 52 of file InternalSpacePoint.hpp
Referenced by Acts::InternalSpacePoint< external_spacepoint_t >::z().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Seeding/InternalSpacePoint.hpp