Analysis Software: JetUnderlyingEvent Class Reference
JetUnderlyingEvent Class Reference
#include <analysis/blob/master/JS-Jet/JetUnderlyingEvent/src/JetUnderlyingEvent.h>
Public Member Functions
JetUnderlyingEvent (const std::string &name="JetUnderlyingEvent", const std::string &outputfilename="myjetanalysis.root")
~JetUnderlyingEvent () override
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int ResetEvent (PHCompositeNode *topNode) override
Clean up internals after each event.
int EndRun (const int runnumber) override
Called at the end of each run.
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
int Reset (PHCompositeNode *) override
Reset.
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from SubsysReco
~SubsysReco () override
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
std::string m_outputFileName
TH3 * hsubtractedE
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 15 of file JetUnderlyingEvent.h.
View newest version in sPHENIX GitHub at line 15 of file JetUnderlyingEvent.h
Constructor & Destructor Documentation
JetUnderlyingEvent::JetUnderlyingEvent (const std::string & name = "JetUnderlyingEvent", const std::string & outputfilename = "myjetanalysis.root")
Definition at line 98 of file JetUnderlyingEvent.cc.
View newest version in sPHENIX GitHub at line 98 of file JetUnderlyingEvent.cc
JetUnderlyingEvent::~JetUnderlyingEvent () override
Definition at line 106 of file JetUnderlyingEvent.cc.
View newest version in sPHENIX GitHub at line 106 of file JetUnderlyingEvent.cc
Member Function Documentation
int JetUnderlyingEvent::End (PHCompositeNode * topNode) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 301 of file JetUnderlyingEvent.cc.
View newest version in sPHENIX GitHub at line 301 of file JetUnderlyingEvent.cc
References PHTFileServer::cd(), Centrality(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), GetZaxis(), hsubtractedE, i, m_outputFileName, and Write().
int JetUnderlyingEvent::EndRun (const int runnumber) override virtual
Called at the end of each run.
Reimplemented from SubsysReco.
Definition at line 294 of file JetUnderlyingEvent.cc.
View newest version in sPHENIX GitHub at line 294 of file JetUnderlyingEvent.cc
References Fun4AllReturnCodes::EVENT_OK.
int JetUnderlyingEvent::Init (PHCompositeNode * topNode) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 112 of file JetUnderlyingEvent.cc.
View newest version in sPHENIX GitHub at line 112 of file JetUnderlyingEvent.cc
References Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), hsubtractedE, m_outputFileName, and PHTFileServer::open().
int JetUnderlyingEvent::InitRun (PHCompositeNode * topNode) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.
Reimplemented from SubsysReco.
Definition at line 128 of file JetUnderlyingEvent.cc.
View newest version in sPHENIX GitHub at line 128 of file JetUnderlyingEvent.cc
References Fun4AllReturnCodes::EVENT_OK.
void JetUnderlyingEvent::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 325 of file JetUnderlyingEvent.cc.
View newest version in sPHENIX GitHub at line 325 of file JetUnderlyingEvent.cc
int JetUnderlyingEvent::process_event (PHCompositeNode * topNode) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 135 of file JetUnderlyingEvent.cc.
View newest version in sPHENIX GitHub at line 135 of file JetUnderlyingEvent.cc
References assert, JetMap::begin(), Jet::begin_comp(), mvtx_utils::comp(), JetMap::end(), Jet::end_comp(), Fun4AllReturnCodes::EVENT_OK, RawTower::get_bineta(), CentralityInfo::get_centile(), RawTower::get_energy(), RawTower::get_key(), TowerBackground::get_Psi2(), Jet::get_pt(), TowerBackground::get_UE(), TowerBackground::get_v2(), RawTowerContainer::getTower(), hsubtractedE, physmon_track_finding_ttbar::pt, Jet::set_e(), Jet::set_px(), Jet::set_py(), and Jet::set_pz().
int JetUnderlyingEvent::Reset (PHCompositeNode * topNode) override virtual
Reset.
Reimplemented from SubsysReco.
Definition at line 318 of file JetUnderlyingEvent.cc.
View newest version in sPHENIX GitHub at line 318 of file JetUnderlyingEvent.cc
References Fun4AllReturnCodes::EVENT_OK.
int JetUnderlyingEvent::ResetEvent (PHCompositeNode * topNode) override virtual
Clean up internals after each event.
Reimplemented from SubsysReco.
Definition at line 288 of file JetUnderlyingEvent.cc.
View newest version in sPHENIX GitHub at line 288 of file JetUnderlyingEvent.cc
References Fun4AllReturnCodes::EVENT_OK.
Member Data Documentation
TH3* JetUnderlyingEvent::hsubtractedE private
Definition at line 58 of file JetUnderlyingEvent.h.
View newest version in sPHENIX GitHub at line 58 of file JetUnderlyingEvent.h
Referenced by End(), Init(), and process_event().
std::string JetUnderlyingEvent::m_outputFileName private
Definition at line 57 of file JetUnderlyingEvent.h.
View newest version in sPHENIX GitHub at line 57 of file JetUnderlyingEvent.h
Referenced by End(), and Init().
The documentation for this class was generated from the following files:
analysis/blob/master/JS-Jet/JetUnderlyingEvent/src/JetUnderlyingEvent.h
analysis/blob/master/JS-Jet/JetUnderlyingEvent/src/JetUnderlyingEvent.cc