Analysis Software: LEDTowerBuilder Class Reference
LEDTowerBuilder Class Reference
#include <analysis/blob/master/EMCal-LEDs/src/LEDTowerBuilder.h>
Public Types
enum DetectorSystem { CEMC = 0, HCALIN = 1, HCALOUT = 2, EPD = 3 }
Public Member Functions
LEDTowerBuilder (const std::string &name="LEDTowerBuilder")
~LEDTowerBuilder () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_detector_type (LEDTowerBuilder::DetectorSystem dettype)
void set_nsamples (int _nsamples)
void set_dataflag (bool flag)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
CaloWaveformProcessing * WaveformProcessing = new CaloWaveformProcessing()
LEDTowerBuilder::DetectorSystem m_dettype
std::string m_detector
int m_packet_low
int m_packet_high
int m_nsamples
int m_nchannels
bool m_isdata
int m_event
TTree * tOut
std::vector< float > m_adc
std::vector< float > m_ped
std::vector< float > m_time
std::vector< int > m_chan
std::vector< std::vector< float > > m_waveforms
std::string m_outputFilename
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 22 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 22 of file LEDTowerBuilder.h
Member Enumeration Documentation
enum LEDTowerBuilder::DetectorSystem
Enumerator:
CEMC
HCALIN
HCALOUT
EPD
Definition at line 32 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 32 of file LEDTowerBuilder.h
Constructor & Destructor Documentation
LEDTowerBuilder::LEDTowerBuilder (const std::string & name = "LEDTowerBuilder")
Definition at line 3 of file LEDTowerBuilder.cc.
View newest version in sPHENIX GitHub at line 3 of file LEDTowerBuilder.cc
References Branch(), m_adc, m_chan, m_ped, m_time, m_waveforms, and tOut.
LEDTowerBuilder::~LEDTowerBuilder () override
Definition at line 31 of file LEDTowerBuilder.cc.
View newest version in sPHENIX GitHub at line 31 of file LEDTowerBuilder.cc
Member Function Documentation
int LEDTowerBuilder::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 145 of file LEDTowerBuilder.cc.
View newest version in sPHENIX GitHub at line 145 of file LEDTowerBuilder.cc
References Fun4AllReturnCodes::EVENT_OK, m_outputFilename, check_smearing_config::output, tOut, and Write().
int LEDTowerBuilder::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 36 of file LEDTowerBuilder.cc.
View newest version in sPHENIX GitHub at line 36 of file LEDTowerBuilder.cc
References CEMC, EPD, Fun4AllReturnCodes::EVENT_OK, CaloWaveformProcessing::FAST, HCALIN, HCALOUT, CaloWaveformProcessing::initialize_processing(), m_detector, m_dettype, m_nchannels, m_packet_high, m_packet_low, PHCompositeNode::print(), CaloWaveformProcessing::set_processing_type(), CaloWaveformProcessing::set_template_file(), and WaveformProcessing.
int LEDTowerBuilder::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 74 of file LEDTowerBuilder.cc.
View newest version in sPHENIX GitHub at line 74 of file LEDTowerBuilder.cc
References channel(), Fun4AllReturnCodes::DISCARDEVENT, Fun4AllReturnCodes::EVENT_OK, Fill(), Event::getEvtType(), Event::getPacket(), i, Packet::iValue(), m_adc, m_chan, m_event, m_isdata, m_nchannels, m_nsamples, m_packet_high, m_packet_low, m_ped, m_time, m_waveforms, train_ambiguity_solver::pid, CaloWaveformProcessing::process_waveform(), tOut, and WaveformProcessing.
void LEDTowerBuilder::set_dataflag (bool flag) inline
Definition at line 48 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 48 of file LEDTowerBuilder.h
References m_isdata.
void LEDTowerBuilder::set_detector_type (LEDTowerBuilder::DetectorSystem dettype) inline
Definition at line 39 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 39 of file LEDTowerBuilder.h
References m_dettype.
Referenced by Fun4All_LEDTowerBuilder().
void LEDTowerBuilder::set_nsamples (int _nsamples) inline
Definition at line 44 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 44 of file LEDTowerBuilder.h
References m_nsamples.
Member Data Documentation
std::vector<float> LEDTowerBuilder::m_adc private
Definition at line 66 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 66 of file LEDTowerBuilder.h
Referenced by LEDTowerBuilder(), and process_event().
std::vector<int> LEDTowerBuilder::m_chan private
Definition at line 69 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 69 of file LEDTowerBuilder.h
Referenced by LEDTowerBuilder(), and process_event().
std::string LEDTowerBuilder::m_detector private
Definition at line 57 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 57 of file LEDTowerBuilder.h
Referenced by InitRun().
LEDTowerBuilder::DetectorSystem LEDTowerBuilder::m_dettype private
Definition at line 56 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 56 of file LEDTowerBuilder.h
Referenced by InitRun(), and set_detector_type().
int LEDTowerBuilder::m_event private
Definition at line 63 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 63 of file LEDTowerBuilder.h
Referenced by process_event().
bool LEDTowerBuilder::m_isdata private
Definition at line 62 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 62 of file LEDTowerBuilder.h
Referenced by process_event(), and set_dataflag().
int LEDTowerBuilder::m_nchannels private
Definition at line 61 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 61 of file LEDTowerBuilder.h
Referenced by InitRun(), and process_event().
int LEDTowerBuilder::m_nsamples private
Definition at line 60 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 60 of file LEDTowerBuilder.h
Referenced by process_event(), and set_nsamples().
std::string LEDTowerBuilder::m_outputFilename private
Definition at line 71 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 71 of file LEDTowerBuilder.h
Referenced by End().
int LEDTowerBuilder::m_packet_high private
Definition at line 59 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 59 of file LEDTowerBuilder.h
Referenced by InitRun(), and process_event().
int LEDTowerBuilder::m_packet_low private
Definition at line 58 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 58 of file LEDTowerBuilder.h
Referenced by InitRun(), and process_event().
std::vector<float> LEDTowerBuilder::m_ped private
Definition at line 67 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 67 of file LEDTowerBuilder.h
Referenced by LEDTowerBuilder(), and process_event().
std::vector<float> LEDTowerBuilder::m_time private
Definition at line 68 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 68 of file LEDTowerBuilder.h
Referenced by LEDTowerBuilder(), and process_event().
std::vector<std::vector<float> > LEDTowerBuilder::m_waveforms private
Definition at line 70 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 70 of file LEDTowerBuilder.h
Referenced by LEDTowerBuilder(), and process_event().
TTree* LEDTowerBuilder::tOut private
Definition at line 65 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 65 of file LEDTowerBuilder.h
Referenced by End(), LEDTowerBuilder(), and process_event().
CaloWaveformProcessing* LEDTowerBuilder::WaveformProcessing = new CaloWaveformProcessing() private
Definition at line 55 of file LEDTowerBuilder.h.
View newest version in sPHENIX GitHub at line 55 of file LEDTowerBuilder.h
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/EMCal-LEDs/src/LEDTowerBuilder.h
analysis/blob/master/EMCal-LEDs/src/LEDTowerBuilder.cc