Analysis Software: PHGenIntegral Class Reference
PHGenIntegral Class Reference
PHGenIntegral.
#include <coresoftware/blob/master/generators/phhepmc/PHGenIntegral.h>
Public Member Functions
PHGenIntegral ()
~PHGenIntegral () override
virtual Double_t get_Integrated_Lumi () const
Integrated luminosity in pb^-1.
virtual void set_Integrated_Lumi (Double_t)
Integrated luminosity in pb^-1.
virtual ULong64_t get_N_Generator_Accepted_Event () const
Number of accepted events in the event generator. This can be higher than fNProcessedEvent depending on trigger on the event generator.
virtual void set_N_Generator_Accepted_Event (ULong64_t)
Number of accepted events in the event generator. This can be higher than fNProcessedEvent depending on trigger on the event generator.
virtual ULong64_t get_N_Processed_Event () const
Number of processed events in the Fun4All cycles.
virtual void set_N_Processed_Event (ULong64_t)
Number of processed events in the Fun4All cycles.
virtual Double_t get_Sum_Of_Weight () const
virtual void set_Sum_Of_Weight (Double_t)
virtual Double_t get_CrossSection_Processed_Event () const
cross sections for the processed events in pb
virtual Double_t get_CrossSection_Generator_Accepted_Event () const
cross sections for the events accepted by the event generator in pb
virtual const std::string & get_Description () const
description on the source
virtual void set_Description (const std::string &)
description on the source
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
PHGenIntegral.
Definition at line 21 of file PHGenIntegral.h.
View newest version in sPHENIX GitHub at line 21 of file PHGenIntegral.h
Constructor & Destructor Documentation
PHGenIntegral::PHGenIntegral () inline
Definition at line 24 of file PHGenIntegral.h.
View newest version in sPHENIX GitHub at line 24 of file PHGenIntegral.h
PHGenIntegral::~PHGenIntegral () inline override
Definition at line 25 of file PHGenIntegral.h.
View newest version in sPHENIX GitHub at line 25 of file PHGenIntegral.h
Member Function Documentation
Double_t PHGenIntegral::get_CrossSection_Generator_Accepted_Event () const virtual
cross sections for the events accepted by the event generator in pb
Definition at line 22 of file PHGenIntegral.cc.
View newest version in sPHENIX GitHub at line 22 of file PHGenIntegral.cc
References get_Integrated_Lumi(), and get_N_Generator_Accepted_Event().
Referenced by TruthPhotonJet::End(), BuildResonanceJetTaggingTree::End(), PHGenIntegralv1::identify(), and DumpPHGenIntegral::process_Node().
Double_t PHGenIntegral::get_CrossSection_Processed_Event () const virtual
cross sections for the processed events in pb
Definition at line 16 of file PHGenIntegral.cc.
View newest version in sPHENIX GitHub at line 16 of file PHGenIntegral.cc
References get_Integrated_Lumi(), and get_N_Processed_Event().
Referenced by TruthPhotonJet::End(), BuildResonanceJetTaggingTree::End(), PHGenIntegralv1::identify(), and DumpPHGenIntegral::process_Node().
const std::string & PHGenIntegral::get_Description () const virtual
description on the source
Reimplemented in PHGenIntegralv1.
Definition at line 28 of file PHGenIntegral.cc.
View newest version in sPHENIX GitHub at line 28 of file PHGenIntegral.cc
Referenced by PHGenIntegralv1::CopyFrom(), PHGenIntegralv1::Integrate(), and DumpPHGenIntegral::process_Node().
virtual Double_t PHGenIntegral::get_Integrated_Lumi () const inline virtual
Integrated luminosity in pb^-1.
Reimplemented in PHGenIntegralv1.
Definition at line 28 of file PHGenIntegral.h.
View newest version in sPHENIX GitHub at line 28 of file PHGenIntegral.h
Referenced by PHGenIntegralv1::CopyFrom(), HFMLTriggerHepMCTrigger::End(), HFFastSim::End(), TruthPhotonJet::End(), BuildResonanceJetTaggingTree::End(), get_CrossSection_Generator_Accepted_Event(), get_CrossSection_Processed_Event(), PHGenIntegralv1::Integrate(), and DumpPHGenIntegral::process_Node().
virtual ULong64_t PHGenIntegral::get_N_Generator_Accepted_Event () const inline virtual
Number of accepted events in the event generator. This can be higher than fNProcessedEvent depending on trigger on the event generator.
Reimplemented in PHGenIntegralv1.
Definition at line 39 of file PHGenIntegral.h.
View newest version in sPHENIX GitHub at line 39 of file PHGenIntegral.h
Referenced by PHGenIntegralv1::CopyFrom(), TruthPhotonJet::End(), BuildResonanceJetTaggingTree::End(), get_CrossSection_Generator_Accepted_Event(), PHGenIntegralv1::Integrate(), and DumpPHGenIntegral::process_Node().
virtual ULong64_t PHGenIntegral::get_N_Processed_Event () const inline virtual
Number of processed events in the Fun4All cycles.
Reimplemented in PHGenIntegralv1.
Definition at line 50 of file PHGenIntegral.h.
View newest version in sPHENIX GitHub at line 50 of file PHGenIntegral.h
Referenced by PHGenIntegralv1::CopyFrom(), TruthPhotonJet::End(), BuildResonanceJetTaggingTree::End(), get_CrossSection_Processed_Event(), PHGenIntegralv1::Integrate(), and DumpPHGenIntegral::process_Node().
virtual Double_t PHGenIntegral::get_Sum_Of_Weight () const inline virtual
Sum of weight assigned to the events by the generators. Event weight is normally 1 and thus equal to number of the generated event and is uninteresting. However, there are several cases where one may have nontrivial event weights, e.g. using user hooks in Pythia8 generators to reweight the phase space
Reimplemented in PHGenIntegralv1.
Definition at line 63 of file PHGenIntegral.h.
View newest version in sPHENIX GitHub at line 63 of file PHGenIntegral.h
Referenced by PHGenIntegralv1::CopyFrom(), PHGenIntegralv1::Integrate(), and DumpPHGenIntegral::process_Node().
virtual void PHGenIntegral::set_Description (const std::string &) inline virtual
description on the source
Reimplemented in PHGenIntegralv1.
Definition at line 85 of file PHGenIntegral.h.
View newest version in sPHENIX GitHub at line 85 of file PHGenIntegral.h
virtual void PHGenIntegral::set_Integrated_Lumi (Double_t) inline virtual
Integrated luminosity in pb^-1.
Reimplemented in PHGenIntegralv1.
Definition at line 34 of file PHGenIntegral.h.
View newest version in sPHENIX GitHub at line 34 of file PHGenIntegral.h
Referenced by PHPythia8::process_event().
virtual void PHGenIntegral::set_N_Generator_Accepted_Event (ULong64_t) inline virtual
Number of accepted events in the event generator. This can be higher than fNProcessedEvent depending on trigger on the event generator.
Reimplemented in PHGenIntegralv1.
Definition at line 45 of file PHGenIntegral.h.
View newest version in sPHENIX GitHub at line 45 of file PHGenIntegral.h
Referenced by PHPythia8::process_event().
virtual void PHGenIntegral::set_N_Processed_Event (ULong64_t) inline virtual
Number of processed events in the Fun4All cycles.
Reimplemented in PHGenIntegralv1.
Definition at line 56 of file PHGenIntegral.h.
View newest version in sPHENIX GitHub at line 56 of file PHGenIntegral.h
Referenced by PHPythia8::process_event().
virtual void PHGenIntegral::set_Sum_Of_Weight (Double_t) inline virtual
Sum of weight assigned to the events by the generators. Event weight is normally 1 and thus equal to number of the generated event and is uninteresting. However, there are several cases where one may have nontrivial event weights, e.g. using user hooks in Pythia8 generators to reweight the phase space
Reimplemented in PHGenIntegralv1.
Definition at line 71 of file PHGenIntegral.h.
View newest version in sPHENIX GitHub at line 71 of file PHGenIntegral.h
Referenced by PHPythia8::process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/generators/phhepmc/PHGenIntegral.h
coresoftware/blob/master/generators/phhepmc/PHGenIntegral.cc