Analysis Software: Jetscape::InitialState Class Reference
Jetscape::InitialState Class Reference
#include <JETSCAPE/blob/main/src/framework/InitialState.h>
Public Member Functions
InitialState ()
~InitialState ()
virtual void Init ()
virtual void Exec ()
virtual void Clear ()
virtual void Write (weak_ptr< JetScapeWriter > w)
virtual void CollectHeader (weak_ptr< JetScapeWriter > w)
virtual double GetNpart ()
virtual double GetNcoll ()
virtual double GetTotalEntropy ()
void SetRanges (double xmax, double ymax, double zmax)
void SetSteps (double dx, double dy, double dz)
std::vector< double > GetEntropyDensityDistribution ()
std::vector< double > GetNumOfBinaryCollisions ()
int GetEventId () const
void SetEventId (int event_id_in)
set the event id
std::tuple< double, double,
double > CoordFromIdx (int idx)
virtual void SampleABinaryCollisionPoint (double &x, double &y)
double GetXMax ()
double GetXStep ()
double GetYMax ()
double GetYStep ()
double GetZMax ()
double GetZStep ()
int GetXSize ()
int GetYSize ()
int GetZSize ()
Public Member Functions inherited from Jetscape::JetScapeModuleBase
JetScapeModuleBase ()
JetScapeModuleBase (string m_name)
virtual ~JetScapeModuleBase ()
void SetXMLMainFileName (string m_name)
string GetXMLMainFileName ()
void SetXMLUserFileName (string m_name)
string GetXMLUserFileName ()
shared_ptr< std::mt19937 > GetMt19937Generator ()
tinyxml2::XMLElement * GetXMLElement (std::initializer_list< const char * > path, bool isRequired=true)
std::string GetXMLElementText (std::initializer_list< const char * > path, bool isRequired=true)
int GetXMLElementInt (std::initializer_list< const char * > path, bool isRequired=true)
double GetXMLElementDouble (std::initializer_list< const char * > path, bool isRequired=true)
Public Member Functions inherited from Jetscape::JetScapeTask
JetScapeTask ()
virtual ~JetScapeTask ()
virtual void Finish ()
virtual void ExecuteTasks ()
virtual void ExecuteTask ()
virtual void InitTask ()
virtual void InitTasks ()
virtual void ClearTasks ()
virtual void ClearTask ()
virtual void FinishTask ()
virtual void FinishTasks ()
virtual void WriteTasks (weak_ptr< JetScapeWriter > w)
virtual void WriteTask (weak_ptr< JetScapeWriter > w)
virtual void CollectHeaders (weak_ptr< JetScapeWriter > w)
virtual void Add (shared_ptr< JetScapeTask > m_tasks)
virtual const int GetMyTaskNumber () const
const vector< shared_ptr
< JetScapeTask > > GetTaskList () const
shared_ptr< JetScapeTask > GetTaskAt (int i)
void EraseTaskLast ()
void EraseTaskAt (int i)
void ResizeTaskList (int i)
void ClearTaskList ()
int GetNumberOfTasks ()
const bool GetActive () const
void SetActive (bool m_active_exec)
void SetId (string m_id)
const string GetId () const
const shared_ptr
< JetScapeModuleMutex > GetMutex () const
void SetMutex (shared_ptr< JetScapeModuleMutex > m_mutex)
Public Member Functions inherited from sigslot::has_slots< sigslot::multi_threaded_local >
has_slots ()
has_slots (const has_slots &hs)
void signal_connect (_signal_base< sigslot::multi_threaded_local > *sender)
void signal_disconnect (_signal_base< sigslot::multi_threaded_local > *sender)
virtual ~has_slots ()
void disconnect_all ()
Protected Attributes
std::vector< double > entropy_density_distribution_
std::vector< double > num_of_binary_collisions_
int event_id_
double grid_max_x_
double grid_max_y_
double grid_max_z_
double grid_step_x_
double grid_step_y_
double grid_step_z_
Additional Inherited Members
Static Public Member Functions inherited from Jetscape::JetScapeModuleBase
static int GetCurrentEvent ()
static void IncrementCurrentEvent ()
Detailed Description
Definition at line 28 of file InitialState.h.
View newest version in sPHENIX GitHub at line 28 of file InitialState.h
Constructor & Destructor Documentation
Jetscape::InitialState::InitialState () inline
Default constructor to create a Initial State Physics task. Sets the task ID as "InitialState".
Definition at line 32 of file InitialState.h.
View newest version in sPHENIX GitHub at line 32 of file InitialState.h
References Jetscape::JetScapeTask::SetId().
Jetscape::InitialState::~InitialState ()
Destructor for the Initial State Physics task.
Definition at line 22 of file InitialState.cc.
View newest version in sPHENIX GitHub at line 22 of file InitialState.cc
Member Function Documentation
void Jetscape::InitialState::Clear (void) virtual
Default Clear() function. It can be overridden by other tasks.
Reimplemented from Jetscape::JetScapeModuleBase.
Reimplemented in Jetscape::TrentoInitial, InitialFromFile, IPGlasmaWrapper, and NcollListFromFile.
Definition at line 47 of file InitialState.cc.
View newest version in sPHENIX GitHub at line 47 of file InitialState.cc
void Jetscape::InitialState::CollectHeader (weak_ptr< JetScapeWriter > w) virtual
Collect header information for writer modules
Parameters
w is a pointer of type JetScapeWrite class.
Reimplemented from Jetscape::JetScapeTask.
Definition at line 55 of file InitialState.cc.
View newest version in sPHENIX GitHub at line 55 of file InitialState.cc
References f, GetNcoll(), GetNpart(), and GetTotalEntropy().
std::tuple< double, double, double > Jetscape::InitialState::CoordFromIdx (int idx)
compute 3d coordinates (x, y, z) given the 1D index in vector
Returns
Grid point (x,y,z or eta).
Parameters
idx is an integer which maps to an unique unit cell in the coordinate space (x,y,z or eta).
Definition at line 65 of file InitialState.cc.
View newest version in sPHENIX GitHub at line 65 of file InitialState.cc
References col, GetXSize(), GetYSize(), GetZSize(), grid_max_x_, grid_max_y_, grid_max_z_, grid_step_x_, grid_step_y_, grid_step_z_, std::tr1::make_tuple(), nx, ny, and nz.
Referenced by SampleABinaryCollisionPoint().
void Jetscape::InitialState::Exec () virtual
Default Exec() function. It can be overridden by other tasks. After this is run, GetNumBinaryCollisions and GetEntropyDensityDistribution should return sensible values.
Reimplemented from Jetscape::JetScapeModuleBase.
Reimplemented in Jetscape::TrentoInitial, InitialFromFile, IPGlasmaWrapper, and NcollListFromFile.
Definition at line 43 of file InitialState.cc.
View newest version in sPHENIX GitHub at line 43 of file InitialState.cc
std::vector<double> Jetscape::InitialState::GetEntropyDensityDistribution () inline
Returns
The initial state entropy density distribution.
See Also
Function CoordFromIdx(int idx) for mapping of the index of the vector entropy_density_distribution_ to the fluid cell at location (x, y, z or eta).
Definition at line 104 of file InitialState.h.
View newest version in sPHENIX GitHub at line 104 of file InitialState.h
References entropy_density_distribution_.
int Jetscape::InitialState::GetEventId () const inline
Returns
the event id
Definition at line 118 of file InitialState.h.
View newest version in sPHENIX GitHub at line 118 of file InitialState.h
References event_id_.
virtual double Jetscape::InitialState::GetNcoll () inline virtual
Generated number of binary collisions. To be overwritten by implementations that have such information.
Reimplemented in InitialFromFile, IPGlasmaWrapper, and NcollListFromFile.
Definition at line 70 of file InitialState.h.
View newest version in sPHENIX GitHub at line 70 of file InitialState.h
Referenced by CollectHeader().
virtual double Jetscape::InitialState::GetNpart () inline virtual
Generated number of collision participants. To be overwritten by implementations that have such information.
Reimplemented in InitialFromFile.
Definition at line 65 of file InitialState.h.
View newest version in sPHENIX GitHub at line 65 of file InitialState.h
Referenced by CollectHeader().
std::vector<double> Jetscape::InitialState::GetNumOfBinaryCollisions () inline
one can sample jet production position from Ta * Tb where Ta * Tb is the distribution of num_of_binary_collisions
Returns
The un-normalized probability density of binary collisions.
See Also
Function CoordFromIdx(int idx) for mapping of the index of the vector num_of_binary_collisions_ to the fluid cell at location (x, y, z or eta).
Definition at line 113 of file InitialState.h.
View newest version in sPHENIX GitHub at line 113 of file InitialState.h
References num_of_binary_collisions_.
virtual double Jetscape::InitialState::GetTotalEntropy () inline virtual
Generated total entropy To be overwritten by implementations that have such information.
Reimplemented in InitialFromFile.
Definition at line 75 of file InitialState.h.
View newest version in sPHENIX GitHub at line 75 of file InitialState.h
Referenced by CollectHeader().
double Jetscape::InitialState::GetXMax () inline
Returns
The maximum value of coordinate "x" in the nuclear profile of a nucleus.
Definition at line 132 of file InitialState.h.
View newest version in sPHENIX GitHub at line 132 of file InitialState.h
References grid_max_x_.
Referenced by Jetscape::TrentoInitial::Exec(), and Jetscape::TrentoInitial::InitTask().
int Jetscape::InitialState::GetXSize () inline
Returns
The number of grid points in x-direction in the nuclear profile of a nucleus.
Definition at line 152 of file InitialState.h.
View newest version in sPHENIX GitHub at line 152 of file InitialState.h
References grid_max_x_, and grid_step_x_.
Referenced by CoordFromIdx().
double Jetscape::InitialState::GetXStep () inline
Returns
The step-size "dx" used to discretize the nuclear profile of a nucleus in x-direction.
Definition at line 135 of file InitialState.h.
View newest version in sPHENIX GitHub at line 135 of file InitialState.h
References grid_step_x_.
Referenced by Jetscape::TrentoInitial::InitTask().
double Jetscape::InitialState::GetYMax () inline
Returns
The maximum value of coordinate "y" in the nuclear profile of a nucleus.
Definition at line 138 of file InitialState.h.
View newest version in sPHENIX GitHub at line 138 of file InitialState.h
References grid_max_y_.
Referenced by Jetscape::TrentoInitial::Exec().
int Jetscape::InitialState::GetYSize () inline
Returns
The number of grid points in y-direction in the nuclear profile of a nucleus.
Definition at line 159 of file InitialState.h.
View newest version in sPHENIX GitHub at line 159 of file InitialState.h
References grid_max_y_, and grid_step_y_.
Referenced by CoordFromIdx().
double Jetscape::InitialState::GetYStep () inline
Returns
The step-size "dy" used to discretize the nuclear profile of a nucleus in y-direction.
Definition at line 141 of file InitialState.h.
View newest version in sPHENIX GitHub at line 141 of file InitialState.h
References grid_step_y_.
double Jetscape::InitialState::GetZMax () inline
Returns
The maximum value of coordinate "z or eta" in the nuclear profile of a nucleus.
Definition at line 144 of file InitialState.h.
View newest version in sPHENIX GitHub at line 144 of file InitialState.h
References grid_max_z_.
Referenced by Jetscape::TrentoInitial::InitTask().
int Jetscape::InitialState::GetZSize () inline
Returns
The number of grid points in z or eta direction in the nuclear profile of a nucleus.
Definition at line 166 of file InitialState.h.
View newest version in sPHENIX GitHub at line 166 of file InitialState.h
References grid_max_z_, grid_step_z_, and nz.
Referenced by CoordFromIdx().
double Jetscape::InitialState::GetZStep () inline
Returns
The step-size "dz" used to discretize the nuclear profile of a nucleus in z or eta direction.
Definition at line 147 of file InitialState.h.
View newest version in sPHENIX GitHub at line 147 of file InitialState.h
References grid_step_z_.
Referenced by Jetscape::TrentoInitial::InitTask().
void Jetscape::InitialState::Init () virtual
Reads the input parameters from the XML file under the tag <IS>. Calls InitTask(); This explicit call of InitTask() can be used for actual initialization of modules such as Trento if attached as a polymorphic class. It also initializes the tasks within the current module.
See Also
Read about polymorphism in C++.
Reimplemented from Jetscape::JetScapeModuleBase.
Definition at line 24 of file InitialState.cc.
View newest version in sPHENIX GitHub at line 24 of file InitialState.cc
References Jetscape::JetScapeTask::GetId(), Jetscape::JetScapeModuleBase::GetXMLElementDouble(), grid_max_x_, grid_max_y_, grid_max_z_, grid_step_x_, grid_step_y_, grid_step_z_, Jetscape::JetScapeModuleBase::Init(), Jetscape::JetScapeTask::InitTask(), Jetscape::JetScapeTask::InitTasks(), and JSINFO.
void Jetscape::InitialState::SampleABinaryCollisionPoint (double & x, double & y) virtual
Reimplemented in IPGlasmaWrapper, and NcollListFromFile.
Definition at line 80 of file InitialState.cc.
View newest version in sPHENIX GitHub at line 80 of file InitialState.cc
References parse_cmake_options::begin, CoordFromIdx(), dist(), end, Jetscape::JetScapeModuleBase::GetMt19937Generator(), ambiguity_solver_full_chain::idx, JSWARN, and num_of_binary_collisions_.
void Jetscape::InitialState::SetEventId (int event_id_in) inline
set the event id
Definition at line 121 of file InitialState.h.
View newest version in sPHENIX GitHub at line 121 of file InitialState.h
References event_id_.
void Jetscape::InitialState::SetRanges (double xmax, double ymax, double zmax) inline
Sets the range of the coordinates (xmax, ymax, zmax).
Parameters
xmax Maximum value of the coordinate x in the nuclear density profile.
ymax Maximum value of the coordinate y in the nuclear density profile.
zmax Maxium value of the spatial rapidity (if (tau,x,y,eta) system), or maximum value of the coordinate z (if in (t,x,y,z) system) in the nuclear density profile.
Definition at line 83 of file InitialState.h.
View newest version in sPHENIX GitHub at line 83 of file InitialState.h
References grid_max_x_, grid_max_y_, grid_max_z_, xmax, and ymax.
Referenced by IPGlasmaWrapper::InitTask(), Jetscape::TrentoInitial::InitTask(), and InitialFromFile::ReadConfigs().
void Jetscape::InitialState::SetSteps (double dx, double dy, double dz) inline
It sets the step-size (dx, dy, dz).
Parameters
dx Step-size for x.
dy Step-size for y.
dz Step-size for z or eta.
Definition at line 95 of file InitialState.h.
View newest version in sPHENIX GitHub at line 95 of file InitialState.h
References dy, dz, grid_step_x_, grid_step_y_, and grid_step_z_.
Referenced by IPGlasmaWrapper::InitTask(), Jetscape::TrentoInitial::InitTask(), and InitialFromFile::ReadConfigs().
void Jetscape::InitialState::Write (weak_ptr< JetScapeWriter > w) virtual
Default Write() function. It can be overridden by other tasks.
Parameters
w A pointer to the JetScapeWriter class.
Reimplemented in InitialFromFile, and IPGlasmaWrapper.
Definition at line 49 of file InitialState.cc.
View newest version in sPHENIX GitHub at line 49 of file InitialState.cc
Member Data Documentation
std::vector<double> Jetscape::InitialState::entropy_density_distribution_ protected
It stores the initial state entropy density distribution. The index of the vector is associated to a cell with coordinate (x, y, z or eta).
See Also
Function CoordFromIdx(int idx) for the mapping.
Definition at line 183 of file InitialState.h.
View newest version in sPHENIX GitHub at line 183 of file InitialState.h
Referenced by InitialFromFile::Clear(), Jetscape::TrentoInitial::Clear(), Jetscape::TrentoInitial::Exec(), GetEntropyDensityDistribution(), and InitialFromFile::ReadEntropyDist().
int Jetscape::InitialState::event_id_ protected
Returns
The initial state entropy density distribution.
See Also
Function CoordFromIdx(int idx) for mapping of the index of the vector entropy_density_distribution_ to the fluid cell at location (x, y, z or eta).
Returns
The un-normalized probability density of binary collisions.
See Also
Function CoordFromIdx(int idx) for mapping of the index of the vector num_of_binary_collisions_ to the fluid cell at location (x, y, z or eta).
Returns
Grid point (x,y,z or eta).
Parameters
idx is an integer which maps to an unique unit cell in the coordinate space (x,y,z or eta).
Definition at line 212 of file InitialState.h.
View newest version in sPHENIX GitHub at line 212 of file InitialState.h
Referenced by NcollListFromFile::Exec(), IPGlasmaWrapper::Exec(), InitialFromFile::Exec(), GetEventId(), InitialFromFile::InitialFromFile(), IPGlasmaWrapper::IPGlasmaWrapper(), NcollListFromFile::NcollListFromFile(), and SetEventId().
double Jetscape::InitialState::grid_max_x_ protected
Definition at line 219 of file InitialState.h.
View newest version in sPHENIX GitHub at line 219 of file InitialState.h
Referenced by CoordFromIdx(), GetXMax(), GetXSize(), Init(), and SetRanges().
double Jetscape::InitialState::grid_max_y_ protected
Definition at line 220 of file InitialState.h.
View newest version in sPHENIX GitHub at line 220 of file InitialState.h
Referenced by CoordFromIdx(), GetYMax(), GetYSize(), Init(), and SetRanges().
double Jetscape::InitialState::grid_max_z_ protected
Definition at line 221 of file InitialState.h.
View newest version in sPHENIX GitHub at line 221 of file InitialState.h
Referenced by CoordFromIdx(), GetZMax(), GetZSize(), Init(), and SetRanges().
double Jetscape::InitialState::grid_step_x_ protected
Definition at line 225 of file InitialState.h.
View newest version in sPHENIX GitHub at line 225 of file InitialState.h
Referenced by CoordFromIdx(), GetXSize(), GetXStep(), Init(), and SetSteps().
double Jetscape::InitialState::grid_step_y_ protected
Definition at line 226 of file InitialState.h.
View newest version in sPHENIX GitHub at line 226 of file InitialState.h
Referenced by CoordFromIdx(), GetYSize(), GetYStep(), Init(), and SetSteps().
double Jetscape::InitialState::grid_step_z_ protected
Definition at line 227 of file InitialState.h.
View newest version in sPHENIX GitHub at line 227 of file InitialState.h
Referenced by CoordFromIdx(), GetZSize(), GetZStep(), Init(), and SetSteps().
std::vector<double> Jetscape::InitialState::num_of_binary_collisions_ protected
It represents the un-normalized probability density of binary collisions. The index of the vector is associated to a cell with coordinate (x, y, z or eta).
See Also
Function CoordFromIdx(int idx) for the mapping.
Definition at line 191 of file InitialState.h.
View newest version in sPHENIX GitHub at line 191 of file InitialState.h
Referenced by InitialFromFile::Clear(), Jetscape::TrentoInitial::Clear(), Jetscape::TrentoInitial::Exec(), GetNumOfBinaryCollisions(), InitialFromFile::ReadNbcDist(), and SampleABinaryCollisionPoint().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/InitialState.h
JETSCAPE/blob/main/src/framework/InitialState.cc