Analysis Software: ActsExamples::TrkrClusterSourceLink Class Reference
ActsExamples::TrkrClusterSourceLink Class Reference
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/EventData/TrkrClusterSourceLink.hpp>
Public Member Functions
TrkrClusterSourceLink (uint64_t cluskey, std::shared_ptr< const Acts::Surface > surface, Acts::BoundVector loc, Acts::BoundMatrix cov)
TrkrClusterSourceLink ()=default
Must be default constructible to satisfy SourceLinkConcept.
TrkrClusterSourceLink (TrkrClusterSourceLink &&)=default
TrkrClusterSourceLink (const TrkrClusterSourceLink &)=default
TrkrClusterSourceLink & operator= (TrkrClusterSourceLink &&)=default
Needs equality operators defined to satisfy SourceLinkConcept.
TrkrClusterSourceLink & operator= (const TrkrClusterSourceLink &)=default
const Acts::BoundVector location () const
const Acts::BoundMatrix covariance () const
const Acts::GeometryIdentifier geoId () const
const Acts::Surface & referenceSurface () const
Needs referenceSurface function to satisfy SourceLinkConcept.
Acts::FittableMeasurement
< TrkrClusterSourceLink > operator* () const
Create Acts::FittableMeasurement from information in SourceLink.
uint64_t cluskey () const
Private Attributes
uint64_t m_cluskey
std::shared_ptr< const
Acts::Surface > m_surface
Acts::GeometryIdentifier m_geoId
Acts::BoundVector m_loc
Local x and y position for cluster.
Acts::BoundMatrix m_cov
Cluster covariance matrix.
Friends
constexpr bool operator== (const TrkrClusterSourceLink &lhs, const TrkrClusterSourceLink &rhs)
Detailed Description
This class creates an Acts::SourceLink that relates TrkrClusters to the surface they were measured on. The source link is needed for the fitting
Definition at line 19 of file TrkrClusterSourceLink.hpp.
View newest version in sPHENIX GitHub at line 19 of file TrkrClusterSourceLink.hpp
Constructor & Destructor Documentation
ActsExamples::TrkrClusterSourceLink::TrkrClusterSourceLink (uint64_t cluskey, std::shared_ptr< const Acts::Surface > surface, Acts::BoundVector loc, Acts::BoundMatrix cov) inline
Instantiate with a hitid, associated surface, and values that actually make the measurement. Acts requires the surface be available in this class
Definition at line 25 of file TrkrClusterSourceLink.hpp.
View newest version in sPHENIX GitHub at line 25 of file TrkrClusterSourceLink.hpp
ActsExamples::TrkrClusterSourceLink::TrkrClusterSourceLink () default
Must be default constructible to satisfy SourceLinkConcept.
Referenced by operator*().
ActsExamples::TrkrClusterSourceLink::TrkrClusterSourceLink (TrkrClusterSourceLink &&) default
ActsExamples::TrkrClusterSourceLink::TrkrClusterSourceLink (const TrkrClusterSourceLink &) default
Member Function Documentation
uint64_t ActsExamples::TrkrClusterSourceLink::cluskey () const inline
Definition at line 82 of file TrkrClusterSourceLink.hpp.
View newest version in sPHENIX GitHub at line 82 of file TrkrClusterSourceLink.hpp
References m_cluskey.
Referenced by PHActsTrkFitter::getSourceLinks().
const Acts::BoundMatrix ActsExamples::TrkrClusterSourceLink::covariance () const inline
Definition at line 50 of file TrkrClusterSourceLink.hpp.
View newest version in sPHENIX GitHub at line 50 of file TrkrClusterSourceLink.hpp
References m_cov.
Referenced by PHActsTrkFitter::getSourceLinks(), and PHActsSiliconSeeding::makeSpacePoint().
const Acts::GeometryIdentifier ActsExamples::TrkrClusterSourceLink::geoId () const inline
Definition at line 55 of file TrkrClusterSourceLink.hpp.
View newest version in sPHENIX GitHub at line 55 of file TrkrClusterSourceLink.hpp
References m_geoId.
Referenced by PHActsTrkFitter::getSourceLinks().
const Acts::BoundVector ActsExamples::TrkrClusterSourceLink::location () const inline
Definition at line 46 of file TrkrClusterSourceLink.hpp.
View newest version in sPHENIX GitHub at line 46 of file TrkrClusterSourceLink.hpp
References m_loc.
Referenced by PHActsTrkFitter::getSourceLinks(), and PHActsSiliconSeeding::makeSpacePoint().
Acts::FittableMeasurement<TrkrClusterSourceLink> ActsExamples::TrkrClusterSourceLink::operator* () const inline
Create Acts::FittableMeasurement from information in SourceLink.
Definition at line 67 of file TrkrClusterSourceLink.hpp.
View newest version in sPHENIX GitHub at line 67 of file TrkrClusterSourceLink.hpp
References Acts::eBoundLoc0, Acts::eBoundLoc1, m_cov, m_loc, m_surface, and TrkrClusterSourceLink().
TrkrClusterSourceLink& ActsExamples::TrkrClusterSourceLink::operator= (TrkrClusterSourceLink &&) default
Needs equality operators defined to satisfy SourceLinkConcept.
TrkrClusterSourceLink& ActsExamples::TrkrClusterSourceLink::operator= (const TrkrClusterSourceLink &) default
const Acts::Surface& ActsExamples::TrkrClusterSourceLink::referenceSurface () const inline
Needs referenceSurface function to satisfy SourceLinkConcept.
Definition at line 61 of file TrkrClusterSourceLink.hpp.
View newest version in sPHENIX GitHub at line 61 of file TrkrClusterSourceLink.hpp
References m_surface.
Referenced by PHActsTrkFitter::getSourceLinks(), PHActsSiliconSeeding::makeSpacePoint(), and PHTpcResiduals::propagateTrackState().
Friends And Related Function Documentation
constexpr bool operator== (const TrkrClusterSourceLink & lhs, const TrkrClusterSourceLink & rhs) friend
Needs equality operator defined to satisfy SourceLinkConcept Equate the cluster keys
Definition at line 104 of file TrkrClusterSourceLink.hpp.
View newest version in sPHENIX GitHub at line 104 of file TrkrClusterSourceLink.hpp
Member Data Documentation
uint64_t ActsExamples::TrkrClusterSourceLink::m_cluskey private
Hitindex corresponding to hitID and the corresponding surface to which it belongs to
Definition at line 92 of file TrkrClusterSourceLink.hpp.
View newest version in sPHENIX GitHub at line 92 of file TrkrClusterSourceLink.hpp
Referenced by cluskey().
Acts::BoundMatrix ActsExamples::TrkrClusterSourceLink::m_cov private
Cluster covariance matrix.
Definition at line 99 of file TrkrClusterSourceLink.hpp.
View newest version in sPHENIX GitHub at line 99 of file TrkrClusterSourceLink.hpp
Referenced by covariance(), and operator*().
Acts::GeometryIdentifier ActsExamples::TrkrClusterSourceLink::m_geoId private
Definition at line 94 of file TrkrClusterSourceLink.hpp.
View newest version in sPHENIX GitHub at line 94 of file TrkrClusterSourceLink.hpp
Referenced by geoId().
Acts::BoundVector ActsExamples::TrkrClusterSourceLink::m_loc private
Local x and y position for cluster.
Definition at line 97 of file TrkrClusterSourceLink.hpp.
View newest version in sPHENIX GitHub at line 97 of file TrkrClusterSourceLink.hpp
Referenced by location(), and operator*().
std::shared_ptr<const Acts::Surface> ActsExamples::TrkrClusterSourceLink::m_surface private
Definition at line 93 of file TrkrClusterSourceLink.hpp.
View newest version in sPHENIX GitHub at line 93 of file TrkrClusterSourceLink.hpp
Referenced by operator*(), and referenceSurface().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/EventData/TrkrClusterSourceLink.hpp