Analysis Software: TrkrClusterv4 Class Reference
TrkrClusterv4 Class Reference
Version 4 of TrkrCluster.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv4.h>
Public Member Functions
TrkrClusterv4 ()
ctor
~TrkrClusterv4 () override=default
dtor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void CopyFrom (const TrkrCluster &) override
copy content from base class
void CopyFrom (TrkrCluster *source) override
copy content from base class
float getPosition (int coor) const override
void setPosition (int coor, float xi) override
float getLocalX () const override
void setLocalX (float loc0) override
float getLocalY () const override
void setLocalY (float loc1) override
TrkrDefs::subsurfkey getSubSurfKey () const override
void setSubSurfKey (TrkrDefs::subsurfkey id) override
unsigned int getAdc () const override
void setAdc (unsigned int adc) override
unsigned int getMaxAdc () const override
void setMaxAdc (uint16_t maxadc) override
float getRPhiError () const override
float getZError () const override
float getX () const override
deprecated global funtions with a warning
float getY () const override
float getZ () const override
void setX (float) override
void setY (float) override
void setZ (float) override
float getSize (unsigned int, unsigned int) const override
void setSize (unsigned int, unsigned int, float) override
float getError (unsigned int, unsigned int) const override
void setError (unsigned int, unsigned int, float) override
char getSize () const override
float getPhiSize () const override
void setPhiSize (char phisize)
float getZSize () const override
void setZSize (char zsize)
char getOverlap () const override
void setOverlap (char overlap) override
char getEdge () const override
void setEdge (char edge) override
Public Member Functions inherited from TrkrCluster
~TrkrCluster () override=default
dtor
virtual void setTime (const float)
virtual float getTime () const
virtual float getPhiError () const
virtual void setActsLocalError (unsigned int, unsigned int, float)
Acts functions, for Acts modules use only.
virtual float getActsLocalError (unsigned int, unsigned int) const
virtual void setGlobal ()
virtual void setLocal ()
virtual bool isGlobal () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
float m_local [2]
TrkrDefs::subsurfkey m_subsurfkey
unsigned short int m_adc
char m_phisize
char m_zsize
char m_overlap
char m_edge
Additional Inherited Members
Protected Member Functions inherited from TrkrCluster
TrkrCluster ()=default
Detailed Description
Version 4 of TrkrCluster.
This version of TrkrCluster is reduced to a minimal number of data members
Definition at line 22 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 22 of file TrkrClusterv4.h
Constructor & Destructor Documentation
TrkrClusterv4::TrkrClusterv4 ()
ctor
Definition at line 19 of file TrkrClusterv4.cc.
View newest version in sPHENIX GitHub at line 19 of file TrkrClusterv4.cc
References i, and m_local.
Referenced by CloneMe().
TrkrClusterv4::~TrkrClusterv4 () override default
dtor
Member Function Documentation
PHObject* TrkrClusterv4::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 37 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 37 of file TrkrClusterv4.h
References TrkrClusterv4().
void TrkrClusterv4::CopyFrom (const TrkrCluster & source) override virtual
copy content from base class
Reimplemented from TrkrCluster.
Definition at line 59 of file TrkrClusterv4.cc.
View newest version in sPHENIX GitHub at line 59 of file TrkrClusterv4.cc
References TrkrCluster::CopyFrom(), TrkrCluster::getAdc(), TrkrCluster::getEdge(), TrkrCluster::getLocalX(), TrkrCluster::getLocalY(), TrkrCluster::getOverlap(), TrkrCluster::getPhiSize(), TrkrCluster::getSubSurfKey(), TrkrCluster::getZSize(), setAdc(), setEdge(), setLocalX(), setLocalY(), setOverlap(), setPhiSize(), setSubSurfKey(), and setZSize().
void TrkrClusterv4::CopyFrom (TrkrCluster * source) inline override virtual
copy content from base class
Reimplemented from TrkrCluster.
Definition at line 46 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 46 of file TrkrClusterv4.h
References CopyFrom().
Referenced by CopyFrom().
unsigned int TrkrClusterv4::getAdc () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 65 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 65 of file TrkrClusterv4.h
References m_adc, and Acts::Test::tmp().
char TrkrClusterv4::getEdge () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 135 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 135 of file TrkrClusterv4.h
References m_edge.
float TrkrClusterv4::getError (unsigned int , unsigned int) const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 118 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 118 of file TrkrClusterv4.h
float TrkrClusterv4::getLocalX () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 54 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 54 of file TrkrClusterv4.h
References m_local.
Referenced by identify().
float TrkrClusterv4::getLocalY () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 56 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 56 of file TrkrClusterv4.h
References m_local.
Referenced by identify().
unsigned int TrkrClusterv4::getMaxAdc () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 80 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 80 of file TrkrClusterv4.h
References m_adc, out, and Acts::Test::tmp().
char TrkrClusterv4::getOverlap () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 132 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 132 of file TrkrClusterv4.h
References m_overlap.
float TrkrClusterv4::getPhiSize () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 126 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 126 of file TrkrClusterv4.h
References m_phisize.
float TrkrClusterv4::getPosition (int coor) const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 52 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 52 of file TrkrClusterv4.h
References m_local.
Referenced by isValid().
float TrkrClusterv4::getRPhiError () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 96 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 96 of file TrkrClusterv4.h
float TrkrClusterv4::getSize (unsigned int , unsigned int) const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 114 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 114 of file TrkrClusterv4.h
char TrkrClusterv4::getSize () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 123 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 123 of file TrkrClusterv4.h
References m_phisize, and m_zsize.
TrkrDefs::subsurfkey TrkrClusterv4::getSubSurfKey () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 59 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 59 of file TrkrClusterv4.h
References m_subsurfkey.
float TrkrClusterv4::getX () const inline override virtual
deprecated global funtions with a warning
Reimplemented from TrkrCluster.
Definition at line 102 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 102 of file TrkrClusterv4.h
float TrkrClusterv4::getY () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 104 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 104 of file TrkrClusterv4.h
float TrkrClusterv4::getZ () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 106 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 106 of file TrkrClusterv4.h
float TrkrClusterv4::getZError () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 98 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 98 of file TrkrClusterv4.h
float TrkrClusterv4::getZSize () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 129 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 129 of file TrkrClusterv4.h
References m_zsize.
void TrkrClusterv4::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from TrkrCluster.
Definition at line 33 of file TrkrClusterv4.cc.
View newest version in sPHENIX GitHub at line 33 of file TrkrClusterv4.cc
References getLocalX(), getLocalY(), and isValid().
int TrkrClusterv4::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from TrkrCluster.
Definition at line 48 of file TrkrClusterv4.cc.
View newest version in sPHENIX GitHub at line 48 of file TrkrClusterv4.cc
References getPosition(), i, and m_adc.
Referenced by identify().
void TrkrClusterv4::Reset () inline override virtual
Clear Event.
Reimplemented from TrkrCluster.
Definition at line 35 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 35 of file TrkrClusterv4.h
void TrkrClusterv4::setAdc (unsigned int adc) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 71 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 71 of file TrkrClusterv4.h
References m_adc, and Acts::Test::tmp().
Referenced by TpcClusterBuilder::cluster_hits(), and CopyFrom().
void TrkrClusterv4::setEdge (char edge) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 136 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 136 of file TrkrClusterv4.h
References m_edge.
Referenced by CopyFrom().
void TrkrClusterv4::setError (unsigned int , unsigned int , float) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 120 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 120 of file TrkrClusterv4.h
void TrkrClusterv4::setLocalX (float loc0) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 55 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 55 of file TrkrClusterv4.h
References physmon_track_finding_ttbar::loc0, and m_local.
Referenced by CopyFrom().
void TrkrClusterv4::setLocalY (float loc1) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 57 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 57 of file TrkrClusterv4.h
References m_local.
Referenced by CopyFrom().
void TrkrClusterv4::setMaxAdc (uint16_t maxadc) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 87 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 87 of file TrkrClusterv4.h
References m_adc, and Acts::Test::tmp().
void TrkrClusterv4::setOverlap (char overlap) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 133 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 133 of file TrkrClusterv4.h
References m_overlap.
Referenced by CopyFrom().
void TrkrClusterv4::setPhiSize (char phisize) inline
Definition at line 127 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 127 of file TrkrClusterv4.h
References m_phisize, and phisize.
Referenced by CopyFrom().
void TrkrClusterv4::setPosition (int coor, float xi) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 53 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 53 of file TrkrClusterv4.h
References m_local.
void TrkrClusterv4::setSize (unsigned int , unsigned int , float) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 116 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 116 of file TrkrClusterv4.h
void TrkrClusterv4::setSubSurfKey (TrkrDefs::subsurfkey id) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 60 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 60 of file TrkrClusterv4.h
References train_ambiguity_solver::id, and m_subsurfkey.
Referenced by CopyFrom().
void TrkrClusterv4::setX (float) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 108 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 108 of file TrkrClusterv4.h
void TrkrClusterv4::setY (float) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 110 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 110 of file TrkrClusterv4.h
void TrkrClusterv4::setZ (float) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 112 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 112 of file TrkrClusterv4.h
void TrkrClusterv4::setZSize (char zsize) inline
Definition at line 130 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 130 of file TrkrClusterv4.h
References m_zsize, and zsize.
Referenced by CopyFrom().
Member Data Documentation
unsigned short int TrkrClusterv4::m_adc protected
Definition at line 149 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 149 of file TrkrClusterv4.h
Referenced by getAdc(), getMaxAdc(), isValid(), setAdc(), and setMaxAdc().
char TrkrClusterv4::m_edge protected
Definition at line 153 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 153 of file TrkrClusterv4.h
Referenced by getEdge(), and setEdge().
float TrkrClusterv4::m_local[2] protected
Definition at line 147 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 147 of file TrkrClusterv4.h
Referenced by getLocalX(), getLocalY(), getPosition(), setLocalX(), setLocalY(), setPosition(), and TrkrClusterv4().
char TrkrClusterv4::m_overlap protected
Definition at line 152 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 152 of file TrkrClusterv4.h
Referenced by getOverlap(), and setOverlap().
char TrkrClusterv4::m_phisize protected
Definition at line 150 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 150 of file TrkrClusterv4.h
Referenced by getPhiSize(), getSize(), and setPhiSize().
TrkrDefs::subsurfkey TrkrClusterv4::m_subsurfkey protected
Definition at line 148 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 148 of file TrkrClusterv4.h
Referenced by getSubSurfKey(), and setSubSurfKey().
char TrkrClusterv4::m_zsize protected
Definition at line 151 of file TrkrClusterv4.h.
View newest version in sPHENIX GitHub at line 151 of file TrkrClusterv4.h
Referenced by getSize(), getZSize(), and setZSize().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv4.h
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv4.cc