Analysis Software: rcdaq/blob/master/daqBuffer.cc File Reference
daqBuffer.cc File Reference
#include <daqBuffer.h>
#include <daqONCSEvent.h>
#include <daqPRDFEvent.h>
#include <signal.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <string.h>
#include <lzo/lzo1x.h>
Macros
#define ACKVALUE 101
Functions
int readn (int fd, char *ptr, const int nbytes)
int writen (int fd, char *ptr, const int nbytes)
Macro Definition Documentation
#define ACKVALUE 101
Definition at line 190 of file daqBuffer.cc.
View newest version in sPHENIX GitHub at line 190 of file daqBuffer.cc
Function Documentation
int readn (int fd, char * ptr, const int nbytes)
Definition at line 657 of file sfs.cc.
View newest version in sPHENIX GitHub at line 657 of file sfs.cc
References i, and ActsExamples::JsonSurfacesReader::read().
Referenced by handle_this_child(), rcdaqEventiterator::read_next_buffer(), sendMonitorData(), daqBuffer::sendout(), server_send_beginrun_sequence(), server_send_endrun_sequence(), and server_send_rollover_sequence().
int writen (int fd, char * ptr, const int nbytes)
Definition at line 692 of file sfs.cc.
View newest version in sPHENIX GitHub at line 692 of file sfs.cc
References write().
Referenced by handle_this_child(), rcdaqEventiterator::read_next_buffer(), daqBuffer::sendData(), daqBuffer::sendout(), server_send_beginrun_sequence(), server_send_close_sequence(), server_send_endrun_sequence(), server_send_rollover_sequence(), prdfoStream::writeout(), and daqBuffer::writeout().