Analysis Software: LimitedWarning Class Reference
LimitedWarning Class Reference
#include <JETSCAPE/blob/main/external_packages/fjcore.hh>
Public Member Functions
LimitedWarning ()
LimitedWarning (int max_warn_in)
void warn (const char *warning)
void warn (const std::string &warning)
void warn (const char *warning, std::ostream *ostr)
void warn (const std::string &warning, std::ostream *ostr)
int max_warn () const
int n_warn_so_far () const
Static Public Member Functions
static void set_default_stream (std::ostream *ostr)
static void set_default_max_warn (int max_warn)
static std::string summary ()
Private Types
typedef std::pair< std::string,
unsigned int > Summary
Private Attributes
int _max_warn
int _n_warn_so_far
Summary * _this_warning_summary
Static Private Attributes
static int _max_warn_default = 5
static std::ostream * _default_ostr = &cerr
static std::list< Summary > _global_warnings_summary
Detailed Description
Definition at line 414 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 414 of file fjcore.hh
Member Typedef Documentation
typedef std::pair<std::string, unsigned int> LimitedWarning::Summary private
Definition at line 435 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 435 of file fjcore.hh
Constructor & Destructor Documentation
LimitedWarning::LimitedWarning () inline
Definition at line 416 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 416 of file fjcore.hh
LimitedWarning::LimitedWarning (int max_warn_in) inline
Definition at line 417 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 417 of file fjcore.hh
Member Function Documentation
int LimitedWarning::max_warn () const inline
Definition at line 428 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 428 of file fjcore.hh
References _max_warn.
Referenced by set_default_max_warn().
int LimitedWarning::n_warn_so_far () const inline
Definition at line 429 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 429 of file fjcore.hh
References _n_warn_so_far.
static void LimitedWarning::set_default_max_warn (int max_warn) inline static
Definition at line 425 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 425 of file fjcore.hh
References _max_warn_default, and max_warn().
static void LimitedWarning::set_default_stream (std::ostream * ostr) inline static
Definition at line 422 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 422 of file fjcore.hh
References _default_ostr.
string LimitedWarning::summary () static
Definition at line 3672 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3672 of file fjcore.cc
References it, and str.
void LimitedWarning::warn (const char * warning) inline
Definition at line 418 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 418 of file fjcore.hh
References _default_ostr, and warn().
Referenced by warn().
void LimitedWarning::warn (const std::string & warning) inline
Definition at line 419 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 419 of file fjcore.hh
References _default_ostr, and warn().
Referenced by warn().
void LimitedWarning::warn (const char * warning, std::ostream * ostr)
Definition at line 3651 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3651 of file fjcore.cc
References Summary().
void LimitedWarning::warn (const std::string & warning, std::ostream * ostr) inline
Definition at line 421 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 421 of file fjcore.hh
References warn().
Referenced by warn().
Member Data Documentation
FJCORE_BEGIN_NAMESPACE ostream * LimitedWarning::_default_ostr = &cerr static private
Definition at line 434 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 434 of file fjcore.hh
Referenced by set_default_stream(), and warn().
std::list< LimitedWarning::Summary > LimitedWarning::_global_warnings_summary static private
Definition at line 436 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 436 of file fjcore.hh
int LimitedWarning::_max_warn private
Definition at line 432 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 432 of file fjcore.hh
Referenced by max_warn().
int LimitedWarning::_max_warn_default = 5 static private
Definition at line 433 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 433 of file fjcore.hh
Referenced by set_default_max_warn().
int LimitedWarning::_n_warn_so_far private
Definition at line 432 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 432 of file fjcore.hh
Referenced by n_warn_so_far().
Summary* LimitedWarning::_this_warning_summary private
Definition at line 437 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 437 of file fjcore.hh
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/fjcore.hh
JETSCAPE/blob/main/external_packages/fjcore.cc