Analysis Software: clvisc::CompileOption Class Reference
clvisc::CompileOption Class Reference
#include <JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/opencl_backend.h>
Public Member Functions
CompileOption ()
CompileOption (bool use_single_precision, bool optimize)
std::string str ()
void Define (std::string name)
void SetDoubleConst (std::string name, double value)
void SetFloatConst (std::string name, float value)
void SetIntConst (std::string name, int value)
void KernelIncludePath (std::string abs_path)
Public Attributes
std::stringstream opt
Detailed Description
Definition at line 46 of file opencl_backend.h.
View newest version in sPHENIX GitHub at line 46 of file opencl_backend.h
Constructor & Destructor Documentation
clvisc::CompileOption::CompileOption ()
Definition at line 28 of file opencl_backend.cc.
View newest version in sPHENIX GitHub at line 28 of file opencl_backend.cc
References Define().
clvisc::CompileOption::CompileOption (bool use_single_precision, bool optimize)
if you see strange behaviour in opencl, please set compilation option optimize=false
Definition at line 32 of file opencl_backend.cc.
View newest version in sPHENIX GitHub at line 32 of file opencl_backend.cc
References Define().
Member Function Documentation
void clvisc::CompileOption::Define (std::string name)
Definition at line 41 of file opencl_backend.cc.
View newest version in sPHENIX GitHub at line 41 of file opencl_backend.cc
References opt.
Referenced by clvisc::CLIdeal::CLIdeal(), and CompileOption().
void clvisc::CompileOption::KernelIncludePath (std::string abs_path)
Definition at line 45 of file opencl_backend.cc.
View newest version in sPHENIX GitHub at line 45 of file opencl_backend.cc
References opt.
Referenced by clvisc::CLIdeal::CLIdeal().
void clvisc::CompileOption::SetDoubleConst (std::string name, double value)
Definition at line 59 of file opencl_backend.cc.
View newest version in sPHENIX GitHub at line 59 of file opencl_backend.cc
References opt.
void clvisc::CompileOption::SetFloatConst (std::string name, float value)
Definition at line 54 of file opencl_backend.cc.
View newest version in sPHENIX GitHub at line 54 of file opencl_backend.cc
References opt.
Referenced by clvisc::CLIdeal::CLIdeal(), and clvisc::CLIdeal::read_eos_table_().
void clvisc::CompileOption::SetIntConst (std::string name, int value)
Definition at line 49 of file opencl_backend.cc.
View newest version in sPHENIX GitHub at line 49 of file opencl_backend.cc
References opt.
Referenced by clvisc::CLIdeal::CLIdeal(), and clvisc::CLIdeal::read_eos_table_().
std::string clvisc::CompileOption::str ()
return the string in the CompileOption
Definition at line 63 of file opencl_backend.cc.
View newest version in sPHENIX GitHub at line 63 of file opencl_backend.cc
References opt.
Referenced by clvisc::CLIdeal::CLIdeal().
Member Data Documentation
std::stringstream clvisc::CompileOption::opt
Definition at line 48 of file opencl_backend.h.
View newest version in sPHENIX GitHub at line 48 of file opencl_backend.h
Referenced by Define(), KernelIncludePath(), SetDoubleConst(), SetFloatConst(), SetIntConst(), and str().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/opencl_backend.h
JETSCAPE/blob/main/external_packages/clvisc_wrapper/opencl_backend.cc