Analysis Software: TSQLResultSetMetaData Class Reference
TSQLResultSetMetaData Class Reference abstract
#include <RDBC/blob/master/include/RDBC/TSQLResultSetMetaData.h>
Public Member Functions
virtual Int_t GetColumnCount ()=0
virtual Bool_t IsAutoIncrement (Int_t column)=0
virtual Bool_t IsCaseSensitive (Int_t column)=0
virtual Bool_t IsSearchable (Int_t column)=0
virtual Bool_t IsCurrency (Int_t column)=0
virtual Bool_t IsNullable (Int_t column)=0
virtual Bool_t IsSigned (Int_t column)=0
virtual Int_t GetColumnDisplaySize (Int_t column)=0
virtual TString GetColumnLabel (Int_t column)=0
virtual TString GetColumnName (Int_t column)=0
virtual TString GetSchemaName (Int_t column)=0
virtual Int_t GetPrecision (Int_t column)=0
virtual Int_t GetScale (Int_t column)=0
virtual TString GetTableName (Int_t column)=0
virtual TString GetCatalogName (Int_t column)=0
virtual Int_t GetColumnType (Int_t column)=0
virtual TString GetColumnTypeName (Int_t column)=0
virtual Bool_t IsReadOnly (Int_t column)=0
virtual Bool_t IsWritable (Int_t column)=0
virtual Bool_t IsDefinitelyWritable (Int_t column)=0
Public Member Functions inherited from TSQL
TSQL (void *imp=0)
virtual ~TSQL ()
virtual void Throw (TSQLException *e)
TList * GetWarnings () const
void ClearWarnings ()
virtual Bool_t IsValid () const
Protected Member Functions
TSQLResultSetMetaData (TSQLResultSet *rs, void *imp=0)
virtual ~TSQLResultSetMetaData ()
Protected Attributes
TSQLResultSet * fResultSet
Protected Attributes inherited from TSQL
TList * fWarnings
void * fImp
Friends
class TSQLResultSet
Additional Inherited Members
Static Public Member Functions inherited from TSQL
static Bool_t SetHandler (const TString &handler)
static Bool_t UnsetHandler (const TString &handler="")
Detailed Description
Definition at line 16 of file TSQLResultSetMetaData.h.
View newest version in sPHENIX GitHub at line 16 of file TSQLResultSetMetaData.h
Constructor & Destructor Documentation
TSQLResultSetMetaData::TSQLResultSetMetaData (TSQLResultSet * rs, void * imp = 0) protected
TSQLResultSetMetaData::~TSQLResultSetMetaData () protected virtual
Definition at line 154 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 154 of file MySQLResultSetMetaData.cxx
References TSQL::fImp, and fResultSet.
Member Function Documentation
TString TSQLResultSetMetaData::GetCatalogName (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 475 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 475 of file MySQLResultSetMetaData.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Int_t TSQLResultSetMetaData::GetColumnCount () pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 163 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 163 of file MySQLResultSetMetaData.cxx
References TSQL::fImp, and MySQLResultSetPrivate::fMYSQL_RES.
Referenced by DbForm::ClearCanvas(), DbForm::DisplayResults(), DbForm::HandleExecuteQuery(), TSQLResultSet::Print(), RDBCTestMetaData(), SaveAsCSV(), and TSQLResultSet::Tree().
Int_t TSQLResultSetMetaData::GetColumnDisplaySize (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 319 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 319 of file MySQLResultSetMetaData.cxx
References MySQLResultSetPrivate::fColumnPrecisions, TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Referenced by ClassImpQ(), and TSQLResultSet::Print().
TString TSQLResultSetMetaData::GetColumnLabel (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 342 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 342 of file MySQLResultSetMetaData.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
TString TSQLResultSetMetaData::GetColumnName (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 365 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 365 of file MySQLResultSetMetaData.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Referenced by DbForm::HandleExecuteQuery(), TSQLResultSet::Print(), RDBCTestMetaData(), SaveAsCSV(), and TSQLResultSet::Tree().
Int_t TSQLResultSetMetaData::GetColumnType (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 497 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 497 of file MySQLResultSetMetaData.cxx
References MySQLResultSetPrivate::fColumnTypes, TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Referenced by DbForm::HandleExecuteQuery(), SaveAsCSV(), and TSQLResultSet::Tree().
TString TSQLResultSetMetaData::GetColumnTypeName (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 546 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 546 of file MySQLResultSetMetaData.cxx
References MySQLResultSetPrivate::fColumnTypeNames, TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Referenced by RDBCTestMetaData().
Int_t TSQLResultSetMetaData::GetPrecision (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 409 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 409 of file MySQLResultSetMetaData.cxx
References MySQLResultSetPrivate::fColumnPrecisions, TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Referenced by TSQLResultSet::Tree().
Int_t TSQLResultSetMetaData::GetScale (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 431 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 431 of file MySQLResultSetMetaData.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
TString TSQLResultSetMetaData::GetSchemaName (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 387 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 387 of file MySQLResultSetMetaData.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
TString TSQLResultSetMetaData::GetTableName (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 453 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 453 of file MySQLResultSetMetaData.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Referenced by TSQLResultSet::Tree().
Bool_t TSQLResultSetMetaData::IsAutoIncrement (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 179 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 179 of file MySQLResultSetMetaData.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Bool_t TSQLResultSetMetaData::IsCaseSensitive (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 206 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 206 of file MySQLResultSetMetaData.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Bool_t TSQLResultSetMetaData::IsCurrency (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 251 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 251 of file MySQLResultSetMetaData.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Bool_t TSQLResultSetMetaData::IsDefinitelyWritable (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 616 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 616 of file MySQLResultSetMetaData.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Bool_t TSQLResultSetMetaData::IsNullable (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 273 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 273 of file MySQLResultSetMetaData.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Bool_t TSQLResultSetMetaData::IsReadOnly (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 571 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 571 of file MySQLResultSetMetaData.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Bool_t TSQLResultSetMetaData::IsSearchable (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 229 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 229 of file MySQLResultSetMetaData.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Bool_t TSQLResultSetMetaData::IsSigned (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 297 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 297 of file MySQLResultSetMetaData.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Bool_t TSQLResultSetMetaData::IsWritable (Int_t column) pure virtual
Implemented in ODBCResultSetMetaData.
Definition at line 593 of file MySQLResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 593 of file MySQLResultSetMetaData.cxx
References TSQL::fImp, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
Friends And Related Function Documentation
friend class TSQLResultSet friend
Definition at line 18 of file TSQLResultSetMetaData.h.
View newest version in sPHENIX GitHub at line 18 of file TSQLResultSetMetaData.h
Referenced by TSQLStatement::Execute(), and TSQLStatement::ExecuteQuery().
Member Data Documentation
TSQLResultSet* TSQLResultSetMetaData::fResultSet protected
Definition at line 21 of file TSQLResultSetMetaData.h.
View newest version in sPHENIX GitHub at line 21 of file TSQLResultSetMetaData.h
Referenced by ~TSQLResultSetMetaData().
The documentation for this class was generated from the following files:
RDBC/blob/master/include/RDBC/TSQLResultSetMetaData.h
RDBC/blob/master/mysql/MySQLResultSetMetaData.cxx
RDBC/blob/master/rdbc/TSQLResultSetMetaData.cxx