Analysis Software: Acts::CylinderVolumeBounds Class Reference
Acts::CylinderVolumeBounds Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Geometry/CylinderVolumeBounds.hpp>
Public Types
enum BoundValues : unsigned int {
eMinR = 0, eMaxR = 1, eHalfLengthZ = 2, eHalfPhiSector = 3,
eAveragePhi = 4, eBevelMinZ = 5, eBevelMaxZ = 6, eSize
}
for streaming and access
Public Types inherited from Acts::VolumeBounds
enum BoundsType : int {
eCone = 0, eCuboid = 1, eCutoutCylinder = 2, eCylinder = 3,
eGenericCuboid = 4, eTrapezoid = 5, eOther = 6
}
Public Member Functions
CylinderVolumeBounds ()=delete
CylinderVolumeBounds (double rmin, double rmax, double halfz, double halfphi=M_PI, double avgphi=0., double bevelMinZ=0., double bevelMaxZ=0.) noexcept(false)
buildSurfaceBounds ()
CylinderVolumeBounds (const std::array< double, eSize > &values) noexcept(false)
CylinderVolumeBounds (const CylinderBounds &cBounds, double thickness) noexcept(false)
CylinderVolumeBounds (const RadialBounds &rBounds, double thickness) noexcept(false)
CylinderVolumeBounds (const CylinderVolumeBounds &cylbo)=default
~CylinderVolumeBounds () override=default
CylinderVolumeBounds & operator= (const CylinderVolumeBounds &cylbo)=default
VolumeBounds::BoundsType type () const final
std::vector< double > values () const final
bool inside (const Vector3 &pos, double tol=0.) const override
OrientedSurfaces orientedSurfaces (const Transform3 &transform=Transform3::Identity()) const override
Volume::BoundingBox boundingBox (const Transform3 *trf=nullptr, const Vector3 &envelope={0, 0, 0}, const Volume *entity=nullptr) const final
Vector3 binningOffset (BinningValue bValue) const override
double binningBorder (BinningValue bValue) const override
std::ostream & toStream (std::ostream &sl) const override
Output Method for std::ostream.
double get (BoundValues bValue) const
Public Member Functions inherited from Acts::VolumeBounds
VolumeBounds ()=default
virtual ~VolumeBounds ()=default
Private Member Functions
void checkConsistency () noexcept(false)
void buildSurfaceBounds ()
Helper method to create the surface bounds.
template<class stream_t >
stream_t & dumpT (stream_t &dt) const
Private Attributes
std::array< double, eSize > m_values {}
The internal version of the bounds can be float/double.
std::shared_ptr< const
CylinderBounds > m_innerCylinderBounds {nullptr}
Bounds of the inner CylinderBounds.
std::shared_ptr< const
CylinderBounds > m_outerCylinderBounds {nullptr}
Bounds of the inner CylinderBounds.
std::shared_ptr< const
RadialBounds > m_discBounds {nullptr}
Bounds of the bottom/top Radial.
std::shared_ptr< const
PlanarBounds > m_sectorPlaneBounds {nullptr}
Bounds of the sector planes.
Detailed Description
[0] and [1] at positive
Bounds for a cylindrical Volume, the orientedSurfaces(..) method creates a vector of up to 6 surfaces:
case A) 3 Surfaces (full cylindrical tube): BoundarySurfaceFace [index]:
negativeFaceXY [0] : Acts::DiscSurface with , parallel to plane at negative
positiveFaceXY [1] : Acts::DiscSurface with , parallel to plane at positive
cylinderCover [2] : Acts::CylinderSurface confining the Acts::Volume
case B) 4 Surfaces (tube with inner and outer radius): BoundarySurfaceFace [index]:
negativeFaceXY [0] : Acts::DiscSurface with , parallel to plane at negative
positiveFaceXY [1] : Acts::DiscSurface with , parallel to plane at positive
tubeOuterCover [2] : Acts::CylinderSurface with
tubeInnerCover [3] : Acts::CylinderSurface with
case C) 6 Surfaces (sectoral tube with inner and outer radius): BoundarySurfaceFace [index]:
negativeFaceXY [0] : Acts::DiscSurface with and , parallel to plane at negative
positiveFaceXY [1] : Acts::DiscSurface with and , parallel to plane at positive
tubeSectorOuterCover [2] : Acts::CylinderSurface with
tubeSectorInnerCover [3] : Acts::CylinderSurface with
tubeSectorNegativePhi [4] : Rectangular Acts::PlaneSurface attached to [0] and [1] at negative
tubeSectorNegativePhi [5] :
Definition at line 72 of file CylinderVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 72 of file CylinderVolumeBounds.hpp
Member Enumeration Documentation
enum Acts::CylinderVolumeBounds::BoundValues : unsigned int
for streaming and access
Enumerator:
eMinR
eMaxR
eHalfLengthZ
eHalfPhiSector
eAveragePhi
eBevelMinZ
eBevelMaxZ
eSize
Definition at line 75 of file CylinderVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 75 of file CylinderVolumeBounds.hpp
Constructor & Destructor Documentation
Acts::CylinderVolumeBounds::CylinderVolumeBounds () delete
Acts::CylinderVolumeBounds::CylinderVolumeBounds (double rmin, double rmax, double halfz, double halfphi = M_PI, double avgphi = 0., double bevelMinZ = 0., double bevelMaxZ = 0.) inline noexcept
Constructor
Parameters
rmin The inner radius of the cylinder
rmax The outer radius of the cylinder
halfz The half length in z
halfphi The half lopening angle
avgphi The average phi value
bevelMinZ The bevel angle, in radians, for the negative side
bevelMaxZ The bevel angle, in radians, for the positive side
Definition at line 97 of file CylinderVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 97 of file CylinderVolumeBounds.hpp
Acts::CylinderVolumeBounds::CylinderVolumeBounds (const std::array< double, eSize > & values) inline noexcept
Constructor - from a fixed size array
Parameters
values The bound values
Definition at line 109 of file CylinderVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 109 of file CylinderVolumeBounds.hpp
References buildSurfaceBounds(), and checkConsistency().
Acts::CylinderVolumeBounds::CylinderVolumeBounds (const CylinderBounds & cBounds, double thickness) noexcept
Constructor - extruded from cylinder bounds and thickness
Parameters
cBounds the cylinder bounds
thickness of the extrusion
Definition at line 26 of file CylinderVolumeBounds.cpp.
View newest version in sPHENIX GitHub at line 26 of file CylinderVolumeBounds.cpp
References buildSurfaceBounds(), eR, and thickness.
Acts::CylinderVolumeBounds::CylinderVolumeBounds (const RadialBounds & rBounds, double thickness) noexcept
Constructor - extruded from radial bounds and thickness
Parameters
rBounds the Radial bounds
thickness
Definition at line 44 of file CylinderVolumeBounds.cpp.
View newest version in sPHENIX GitHub at line 44 of file CylinderVolumeBounds.cpp
References buildSurfaceBounds(), double(), rBounds, and thickness.
Acts::CylinderVolumeBounds::CylinderVolumeBounds (const CylinderVolumeBounds & cylbo) default
Copy Constructor
Parameters
cylbo is the source cylinder volume bounds for the copy
Acts::CylinderVolumeBounds::~CylinderVolumeBounds () override default
Member Function Documentation
double Acts::CylinderVolumeBounds::binningBorder (BinningValue bValue) const inline override virtual
Binning borders in double
Parameters
bValue is the type used for the binning
Reimplemented from Acts::VolumeBounds.
Definition at line 239 of file CylinderVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 239 of file CylinderVolumeBounds.hpp
References Acts::VolumeBounds::binningBorder(), Acts::binR, Acts::binZ, eHalfLengthZ, eMaxR, and eMinR.
Vector3 Acts::CylinderVolumeBounds::binningOffset (BinningValue bValue) const inline override virtual
Binning offset - overloaded for some R-binning types
Parameters
bValue is the type used for the binning
Reimplemented from Acts::VolumeBounds.
Definition at line 231 of file CylinderVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 231 of file CylinderVolumeBounds.hpp
References Acts::VolumeBounds::binningOffset(), Acts::binR, Acts::binRPhi, eMaxR, and eMinR.
Acts::Volume::BoundingBox Acts::CylinderVolumeBounds::boundingBox (const Transform3 * trf = nullptr, const Vector3 & envelope = {0, 0, 0}, const Volume * entity = nullptr) const final virtual
Construct bounding box for this shape
Parameters
trf Optional transform
envelope Optional envelope to add / subtract from min/max
entity Entity to associate this bounding box with
Returns
Constructed bounding box
Implements Acts::VolumeBounds.
Definition at line 161 of file CylinderVolumeBounds.cpp.
View newest version in sPHENIX GitHub at line 161 of file CylinderVolumeBounds.cpp
References xmax, xmin, ymax, and ymin.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
void Acts::CylinderVolumeBounds::buildSurfaceBounds ()
Definition at line 139 of file CylinderVolumeBounds.cpp.
View newest version in sPHENIX GitHub at line 139 of file CylinderVolumeBounds.cpp
References Acts::s_epsilon.
Referenced by CylinderVolumeBounds().
void Acts::CylinderVolumeBounds::buildSurfaceBounds () private
Helper method to create the surface bounds.
void Acts::CylinderVolumeBounds::checkConsistency () inline private noexcept
Check the input values for consistency, will throw a logic_exception if consistency is not given
Definition at line 267 of file CylinderVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 267 of file CylinderVolumeBounds.hpp
References eAveragePhi, eBevelMaxZ, eBevelMinZ, eHalfLengthZ, eHalfPhiSector, eMaxR, eMinR, and Acts::detail::radian_sym().
Referenced by CylinderVolumeBounds().
template<class stream_t > stream_t & Acts::CylinderVolumeBounds::dumpT (stream_t & dt) const private
Templated dumpT method
Template Parameters
stream_t The type for the dump stream
Parameters
dt The dump stream object
Definition at line 250 of file CylinderVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 250 of file CylinderVolumeBounds.hpp
References eAveragePhi, eBevelMaxZ, eBevelMinZ, eHalfLengthZ, eHalfPhiSector, eMaxR, and eMinR.
double Acts::CylinderVolumeBounds::get (BoundValues bValue) const inline
Access to the bound values
Parameters
bValue the class nested enum for the array access
Definition at line 190 of file CylinderVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 190 of file CylinderVolumeBounds.hpp
References m_values.
Referenced by Acts::adjustBinUtility(), Acts::CylinderVolumeBuilder::analyzeContent(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), Acts::CylinderVolumeHelper::createContainerTrackingVolume(), Acts::CylinderVolumeHelper::estimateAndCheckDimension(), Acts::CylinderVolumeHelper::glueTrackingVolumes(), and Acts::CylinderVolumeBuilder::trackingVolume().
bool Acts::CylinderVolumeBounds::inside (const Vector3 & pos, double tol = 0.) const inline override virtual
This method checks if position in the 3D volume frame is inside the cylinder
Parameters
pos is a global position to be checked
tol is the tolerance for the check
Implements Acts::VolumeBounds.
Definition at line 218 of file CylinderVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 218 of file CylinderVolumeBounds.hpp
References eHalfLengthZ, eHalfPhiSector, eMaxR, eMinR, Acts::VectorHelpers::perp(), ActsTests::PropagationDatasets::phi, and Acts::VectorHelpers::phi().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
CylinderVolumeBounds& Acts::CylinderVolumeBounds::operator= (const CylinderVolumeBounds & cylbo) default
Acts::OrientedSurfaces Acts::CylinderVolumeBounds::orientedSurfaces (const Transform3 & transform = Transform3::Identity()) const override virtual
Oriented surfaces, i.e. the decomposed boundary surfaces and the according navigation direction into the volume given the normal vector on the surface
Parameters
transform is the 3D transform to be applied to the boundary surfaces to position them in 3D space
It will throw an exception if the orientation prescription is not adequate
Returns
a vector of surfaces bounding this volume
Implements Acts::VolumeBounds.
Definition at line 61 of file CylinderVolumeBounds.cpp.
View newest version in sPHENIX GitHub at line 61 of file CylinderVolumeBounds.cpp
References Acts::Test::cSurface, eAveragePhi, eBevelMaxZ, eBevelMinZ, eHalfLengthZ, eHalfPhiSector, eMaxR, eMinR, m_discBounds, m_innerCylinderBounds, m_outerCylinderBounds, m_sectorPlaneBounds, testing::internal::move(), Acts::Direction::Negative, Acts::Direction::Positive, pSurface, and Acts::Test::transform.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), and Acts::GeometryView3D::drawSurfaceArray().
std::ostream & Acts::CylinderVolumeBounds::toStream (std::ostream & sl) const override virtual
Output Method for std::ostream.
Implements Acts::VolumeBounds.
Definition at line 157 of file CylinderVolumeBounds.cpp.
View newest version in sPHENIX GitHub at line 157 of file CylinderVolumeBounds.cpp
VolumeBounds::BoundsType Acts::CylinderVolumeBounds::type () const inline final virtual
Return the bounds type - for persistency optimization
Returns
is a BoundsType enum
Implements Acts::VolumeBounds.
Definition at line 137 of file CylinderVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 137 of file CylinderVolumeBounds.hpp
References Acts::VolumeBounds::eCylinder.
std::vector< double > Acts::CylinderVolumeBounds::values () const inline final virtual
Return the bound values as dynamically sized vector
Returns
this returns a copy of the internal values
Implements Acts::VolumeBounds.
Definition at line 261 of file CylinderVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 261 of file CylinderVolumeBounds.hpp
References m_values.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Member Data Documentation
std::shared_ptr<const RadialBounds> Acts::CylinderVolumeBounds::m_discBounds {nullptr} private
Bounds of the bottom/top Radial.
Definition at line 200 of file CylinderVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 200 of file CylinderVolumeBounds.hpp
Referenced by orientedSurfaces().
std::shared_ptr<const CylinderBounds> Acts::CylinderVolumeBounds::m_innerCylinderBounds {nullptr} private
Bounds of the inner CylinderBounds.
Definition at line 196 of file CylinderVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 196 of file CylinderVolumeBounds.hpp
Referenced by orientedSurfaces().
std::shared_ptr<const CylinderBounds> Acts::CylinderVolumeBounds::m_outerCylinderBounds {nullptr} private
Bounds of the inner CylinderBounds.
Definition at line 198 of file CylinderVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 198 of file CylinderVolumeBounds.hpp
Referenced by orientedSurfaces().
std::shared_ptr<const PlanarBounds> Acts::CylinderVolumeBounds::m_sectorPlaneBounds {nullptr} private
Bounds of the sector planes.
Definition at line 202 of file CylinderVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 202 of file CylinderVolumeBounds.hpp
Referenced by orientedSurfaces().
std::array<double, eSize> Acts::CylinderVolumeBounds::m_values {} private
The internal version of the bounds can be float/double.
Definition at line 194 of file CylinderVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 194 of file CylinderVolumeBounds.hpp
Referenced by get(), and values().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Geometry/CylinderVolumeBounds.hpp
acts/blob/sPHENIX/Core/src/Geometry/CylinderVolumeBounds.cpp