Analysis Software: Acts::NumericalTrackLinearizer< propagator_t, propagator_options_t >::Config Struct Reference
Acts::NumericalTrackLinearizer< propagator_t, propagator_options_t >::Config Struct Reference
Configuration struct.
#include <acts/blob/sPHENIX/Core/include/Acts/Vertexing/NumericalTrackLinearizer.hpp>
Public Member Functions
Config (std::shared_ptr< const MagneticFieldProvider > bIn, std::shared_ptr< const Propagator_t > prop)
Config (std::shared_ptr< const Propagator_t > prop)
Config constructor without B field -> uses NullBField.
propagator (std::move(prop))
Public Attributes
std::shared_ptr< const
MagneticFieldProvider > bField
std::shared_ptr< const
Propagator_t > propagator
ActsScalar targetTolerance = 1e-12
ActsScalar delta = 1e-8
Detailed Description
template<typename propagator_t, typename propagator_options_t = PropagatorOptions<>>
struct Acts::NumericalTrackLinearizer< propagator_t, propagator_options_t >::Config
Configuration struct.
Definition at line 78 of file NumericalTrackLinearizer.hpp.
View newest version in sPHENIX GitHub at line 78 of file NumericalTrackLinearizer.hpp
Constructor & Destructor Documentation
template<typename propagator_t , typename propagator_options_t = PropagatorOptions<>> Acts::NumericalTrackLinearizer< propagator_t, propagator_options_t >::Config::Config (std::shared_ptr< const MagneticFieldProvider > bIn, std::shared_ptr< const Propagator_t > prop) inline
@ Config constructor if magnetic field is present
Parameters
bIn The magnetic field
prop The propagator
Definition at line 83 of file NumericalTrackLinearizer.hpp.
View newest version in sPHENIX GitHub at line 83 of file NumericalTrackLinearizer.hpp
Referenced by acts.examples.Sequencer::__init__().
template<typename propagator_t , typename propagator_options_t = PropagatorOptions<>> Acts::NumericalTrackLinearizer< propagator_t, propagator_options_t >::Config::Config (std::shared_ptr< const Propagator_t > prop) inline
Config constructor without B field -> uses NullBField.
Parameters
prop Propagator
Definition at line 90 of file NumericalTrackLinearizer.hpp.
View newest version in sPHENIX GitHub at line 90 of file NumericalTrackLinearizer.hpp
Referenced by acts.examples.Sequencer::__init__().
Member Function Documentation
template<typename propagator_t , typename propagator_options_t = PropagatorOptions<>> Acts::NumericalTrackLinearizer< propagator_t, propagator_options_t >::Config::propagator (std:: moveprop) inline
Definition at line 91 of file NumericalTrackLinearizer.hpp.
View newest version in sPHENIX GitHub at line 91 of file NumericalTrackLinearizer.hpp
References testing::internal::move(), and Acts::NumericalTrackLinearizer< propagator_t, propagator_options_t >::Config::propagator().
Referenced by Acts::NumericalTrackLinearizer< propagator_t, propagator_options_t >::Config::propagator().
Member Data Documentation
template<typename propagator_t , typename propagator_options_t = PropagatorOptions<>> std::shared_ptr<const MagneticFieldProvider> Acts::NumericalTrackLinearizer< propagator_t, propagator_options_t >::Config::bField
Definition at line 93 of file NumericalTrackLinearizer.hpp.
View newest version in sPHENIX GitHub at line 93 of file NumericalTrackLinearizer.hpp
template<typename propagator_t , typename propagator_options_t = PropagatorOptions<>> ActsScalar Acts::NumericalTrackLinearizer< propagator_t, propagator_options_t >::Config::delta = 1e-8
Setting size of the perturbation delta for calculation of numerical derivatives (i.e., f'(x) ~ (f(x+delta) - f(x)) / delta)
Definition at line 103 of file NumericalTrackLinearizer.hpp.
View newest version in sPHENIX GitHub at line 103 of file NumericalTrackLinearizer.hpp
template<typename propagator_t , typename propagator_options_t = PropagatorOptions<>> std::shared_ptr<const Propagator_t> Acts::NumericalTrackLinearizer< propagator_t, propagator_options_t >::Config::propagator
Definition at line 95 of file NumericalTrackLinearizer.hpp.
View newest version in sPHENIX GitHub at line 95 of file NumericalTrackLinearizer.hpp
template<typename propagator_t , typename propagator_options_t = PropagatorOptions<>> ActsScalar Acts::NumericalTrackLinearizer< propagator_t, propagator_options_t >::Config::targetTolerance = 1e-12
Tolerance determining how close we need to get to a surface to reach it during propagation
Definition at line 99 of file NumericalTrackLinearizer.hpp.
View newest version in sPHENIX GitHub at line 99 of file NumericalTrackLinearizer.hpp
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Vertexing/NumericalTrackLinearizer.hpp