Analysis Software: ActsSurfaceMaps Struct Reference
ActsSurfaceMaps Struct Reference
#include <coresoftware/blob/master/offline/packages/trackbase/ActsSurfaceMaps.h>
Public Member Functions
ActsSurfaceMaps ()=default
bool isTpcSurface (const Acts::Surface *surface) const
true if given surface corresponds to TPC
bool isMicromegasSurface (const Acts::Surface *surface) const
true if given surface corresponds to Micromegas
Surface getSurface (TrkrDefs::cluskey, TrkrCluster *cluster) const
Surface getSiliconSurface (TrkrDefs::hitsetkey hitsetkey) const
Surface getTpcSurface (TrkrDefs::hitsetkey hitsetkey, TrkrDefs::subsurfkey surfkey) const
Surface getMMSurface (TrkrDefs::hitsetkey hitsetkey) const
Public Attributes
std::map< TrkrDefs::hitsetkey,
Surface > m_siliconSurfaceMap
map hitset to Surface for the silicon detectors (MVTX and INTT)
std::map< unsigned int,
SurfaceVec > m_tpcSurfaceMap
map hitset to surface vector for the TPC
std::map< TrkrDefs::hitsetkey,
Surface > m_mmSurfaceMap
map hitset to surface vector for the micromegas
std::map< TrkrDefs::hitsetkey,
TGeoNode * > m_tGeoNodeMap
map TGeoNode to hitset
std::set< int > m_tpcVolumeIds
stores all acts volume ids relevant to the TPC
std::set< int > m_micromegasVolumeIds
stores all acts volume ids relevant to the micromegas
Detailed Description
Definition at line 29 of file ActsSurfaceMaps.h.
View newest version in sPHENIX GitHub at line 29 of file ActsSurfaceMaps.h
Constructor & Destructor Documentation
ActsSurfaceMaps::ActsSurfaceMaps () default
Member Function Documentation
Surface ActsSurfaceMaps::getMMSurface (TrkrDefs::hitsetkey hitsetkey) const
Definition at line 109 of file ActsSurfaceMaps.cc.
View newest version in sPHENIX GitHub at line 109 of file ActsSurfaceMaps.cc
References m_mmSurfaceMap.
Referenced by AlignmentTransformation::createMap(), CylinderGeomMicromegas::find_strip_from_local_coords(), CylinderGeomMicromegas::get_local_coordinates(), CylinderGeomMicromegas::get_local_from_world_coords(), CylinderGeomMicromegas::get_local_from_world_vect(), CylinderGeomMicromegas::get_strip_count(), CylinderGeomMicromegas::get_strip_length(), CylinderGeomMicromegas::get_world_from_local_coords(), CylinderGeomMicromegas::get_world_from_local_vect(), and getSurface().
Surface ActsSurfaceMaps::getSiliconSurface (TrkrDefs::hitsetkey hitsetkey) const
If it can't be found, return nullptr
Definition at line 62 of file ActsSurfaceMaps.cc.
View newest version in sPHENIX GitHub at line 62 of file ActsSurfaceMaps.cc
References TrkrDefs::getTrkrId(), TrkrDefs::inttId, m_siliconSurfaceMap, TrkrDefs::mvtxId, InttDefs::resetCrossingHitSetKey(), and MvtxDefs::resetStrobeHitSetKey().
Referenced by AlignmentTransformation::createMap(), TrackResiduals::fillHitTree(), PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), PHActsKDTreeSeeding::getMvtxSpacePoints(), PHActsSiliconSeeding::getSiliconSpacePoints(), getSurface(), PHActsKDTreeSeeding::matchInttClusters(), PHActsSiliconSeeding::matchInttClusters(), PHG4MvtxHitReco::process_event(), and PHGenFitTrkFitter::ReFitTrack().
Surface ActsSurfaceMaps::getSurface (TrkrDefs::cluskey key, TrkrCluster * cluster) const
Definition at line 32 of file ActsSurfaceMaps.cc.
View newest version in sPHENIX GitHub at line 32 of file ActsSurfaceMaps.cc
References TrkrDefs::getHitSetKeyFromClusKey(), getMMSurface(), getSiliconSurface(), TrkrCluster::getSubSurfKey(), getTpcSurface(), TrkrDefs::getTrkrId(), TrkrDefs::inttId, TrkrDefs::micromegasId, TrkrDefs::mvtxId, and TrkrDefs::tpcId.
Referenced by MakeMilleFiles::addTrackToMilleFile(), TrackResiduals::fillStatesWithLineFit(), PHCosmicsTrkFitter::getCharge(), ActsGeometry::getGlobalPosition(), ActsGeometry::getGlobalPositionTpc(), MakeMilleFiles::getLocalVtxDerivativesXY(), MakeSourceLinks::getSourceLinks(), ActsEvaluator::getSurface(), HelicalFitter::getTrackletClusterList(), HelicalFitter::process_event(), and PHTpcResiduals::processTrack().
Surface ActsSurfaceMaps::getTpcSurface (TrkrDefs::hitsetkey hitsetkey, TrkrDefs::subsurfkey surfkey) const
If it can't be found, return nullptr to skip this cluster
Definition at line 92 of file ActsSurfaceMaps.cc.
View newest version in sPHENIX GitHub at line 92 of file ActsSurfaceMaps.cc
References TrkrDefs::getLayer(), layer, and m_tpcSurfaceMap.
Referenced by AlignmentTransformation::createMap(), and getSurface().
bool ActsSurfaceMaps::isMicromegasSurface (const Acts::Surface * surface) const
true if given surface corresponds to Micromegas
Definition at line 29 of file ActsSurfaceMaps.cc.
View newest version in sPHENIX GitHub at line 29 of file ActsSurfaceMaps.cc
References Acts::GeometryObject::geometryId(), m_micromegasVolumeIds, and Acts::GeometryIdentifier::volume().
Referenced by PHActsTrkFitter::getSurfaceVector(), and PHActsTrkFitter::loopTracks().
bool ActsSurfaceMaps::isTpcSurface (const Acts::Surface * surface) const
true if given surface corresponds to TPC
Definition at line 26 of file ActsSurfaceMaps.cc.
View newest version in sPHENIX GitHub at line 26 of file ActsSurfaceMaps.cc
References Acts::GeometryObject::geometryId(), m_tpcVolumeIds, and Acts::GeometryIdentifier::volume().
Referenced by PHActsTrkFitter::getSurfaceVector().
Member Data Documentation
std::set<int> ActsSurfaceMaps::m_micromegasVolumeIds
stores all acts volume ids relevant to the micromegas
it is used to quickly tell if a given Acts Surface belongs to micromegas
Definition at line 67 of file ActsSurfaceMaps.h.
View newest version in sPHENIX GitHub at line 67 of file ActsSurfaceMaps.h
Referenced by MakeActsGeometry::InitRun(), and isMicromegasSurface().
std::map<TrkrDefs::hitsetkey, Surface> ActsSurfaceMaps::m_mmSurfaceMap
map hitset to surface vector for the micromegas
Definition at line 56 of file ActsSurfaceMaps.h.
View newest version in sPHENIX GitHub at line 56 of file ActsSurfaceMaps.h
Referenced by getMMSurface(), and MakeActsGeometry::InitRun().
std::map<TrkrDefs::hitsetkey, Surface> ActsSurfaceMaps::m_siliconSurfaceMap
map hitset to Surface for the silicon detectors (MVTX and INTT)
Definition at line 50 of file ActsSurfaceMaps.h.
View newest version in sPHENIX GitHub at line 50 of file ActsSurfaceMaps.h
Referenced by getSiliconSurface(), and MakeActsGeometry::InitRun().
std::map<TrkrDefs::hitsetkey, TGeoNode*> ActsSurfaceMaps::m_tGeoNodeMap
map TGeoNode to hitset
Definition at line 59 of file ActsSurfaceMaps.h.
View newest version in sPHENIX GitHub at line 59 of file ActsSurfaceMaps.h
Referenced by MakeActsGeometry::InitRun().
std::map<unsigned int, SurfaceVec> ActsSurfaceMaps::m_tpcSurfaceMap
map hitset to surface vector for the TPC
Definition at line 53 of file ActsSurfaceMaps.h.
View newest version in sPHENIX GitHub at line 53 of file ActsSurfaceMaps.h
Referenced by DSTEmulator::evaluate_tracks(), ActsGeometry::get_tpc_surface_from_coords(), getTpcSurface(), and MakeActsGeometry::InitRun().
std::set<int> ActsSurfaceMaps::m_tpcVolumeIds
stores all acts volume ids relevant to the TPC
it is used to quickly tell if a given Acts Surface belongs to the TPC
Definition at line 63 of file ActsSurfaceMaps.h.
View newest version in sPHENIX GitHub at line 63 of file ActsSurfaceMaps.h
Referenced by MakeActsGeometry::InitRun(), and isTpcSurface().
The documentation for this struct was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/ActsSurfaceMaps.h
coresoftware/blob/master/offline/packages/trackbase/ActsSurfaceMaps.cc