Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Propagator/MultiStepperTests.cpp File Reference
MultiStepperTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Definitions/Direction.hpp"
#include "Acts/Definitions/TrackParametrization.hpp"
#include "Acts/EventData/Charge.hpp"
#include "Acts/EventData/GenericBoundTrackParameters.hpp"
#include "Acts/EventData/MultiComponentTrackParameters.hpp"
#include "Acts/EventData/TrackParameters.hpp"
#include "Acts/EventData/detail/CorrectedTransformationFreeToBound.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/MagneticField/ConstantBField.hpp"
#include "Acts/MagneticField/MagneticFieldContext.hpp"
#include "Acts/MagneticField/NullBField.hpp"
#include "Acts/Propagator/DefaultExtension.hpp"
#include "Acts/Propagator/EigenStepper.hpp"
#include "Acts/Propagator/MultiEigenStepperLoop.hpp"
#include "Acts/Propagator/Navigator.hpp"
#include "Acts/Propagator/Propagator.hpp"
#include "Acts/Propagator/StepperExtensionList.hpp"
#include "Acts/Surfaces/PlaneSurface.hpp"
#include "Acts/Surfaces/Surface.hpp"
#include "Acts/Utilities/Helpers.hpp"
#include "Acts/Utilities/Intersection.hpp"
#include "Acts/Utilities/Logger.hpp"
#include "Acts/Utilities/Result.hpp"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <memory>
#include <optional>
#include <stdexcept>
#include <tuple>
#include <type_traits>
#include <utility>
#include <vector>
Classes
struct Options
struct MockNavigator
struct Navigation
struct DummyPropState< stepper_state_t >
Namespaces
namespace Acts
Acts includes to create all necessary definitions.
Typedefs
using MultiStepperLoop = MultiEigenStepperLoop< StepperExtensionList< DefaultExtension >>
using SingleStepper = EigenStepper< StepperExtensionList< DefaultExtension >>
template<typename T >
using components_t = typename T::components
Functions
auto makeDefaultBoundPars (bool cov=true, std::size_t n=4, std::optional< BoundVector > ext_pars=std::nullopt)
template<typename multi_stepper_t , bool Cov>
void test_multi_stepper_state ()
BOOST_AUTO_TEST_CASE (multi_stepper_state_no_cov)
template<typename multi_stepper_t >
void test_multi_stepper_state_invalid ()
BOOST_AUTO_TEST_CASE (multi_eigen_stepper_state_invalid)
template<typename multi_stepper_t >
void test_multi_stepper_vs_eigen_stepper ()
BOOST_AUTO_TEST_CASE (multi_eigen_vs_single_eigen)
template<typename multi_stepper_t >
void test_components_modifying_accessors ()
BOOST_AUTO_TEST_CASE (multi_eigen_component_iterable_with_modification)
template<typename multi_stepper_t >
void test_multi_stepper_surface_status_update ()
BOOST_AUTO_TEST_CASE (test_surface_status_and_cmpwise_bound_state)
template<typename multi_stepper_t >
void test_component_bound_state ()
BOOST_AUTO_TEST_CASE (test_component_wise_bound_state)
template<typename multi_stepper_t >
void test_combined_bound_state_function ()
BOOST_AUTO_TEST_CASE (test_combined_bound_state)
template<typename multi_stepper_t >
void test_combined_curvilinear_state_function ()
BOOST_AUTO_TEST_CASE (test_curvilinear_state)
template<typename multi_stepper_t >
void test_single_component_interface_function ()
BOOST_AUTO_TEST_CASE (test_single_component_interface)
template<typename multi_stepper_t >
void remove_add_components_function ()
BOOST_AUTO_TEST_CASE (remove_add_components_test)
template<typename multi_stepper_t >
void propagator_instatiation_test_function ()
BOOST_AUTO_TEST_CASE (propagator_instatiation_test)
Variables
const MagneticFieldContext magCtx
const GeometryContext geoCtx
const double defaultStepSize = 123.
const auto defaultNDir = Direction::Backward
const auto defaultBField
const auto defaultNullBField = std::make_shared<NullBField>()
const auto particleHypothesis = ParticleHypothesis::pion()
static constexpr MockNavigator mockNavigator
Typedef Documentation
template<typename T > using components_t = typename T::components
Definition at line 105 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 105 of file MultiStepperTests.cpp
using MultiStepperLoop = MultiEigenStepperLoop<StepperExtensionList<DefaultExtension>>
Definition at line 62 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 62 of file MultiStepperTests.cpp
using SingleStepper = EigenStepper<StepperExtensionList<DefaultExtension>>
Definition at line 63 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 63 of file MultiStepperTests.cpp
Function Documentation
BOOST_AUTO_TEST_CASE (multi_stepper_state_no_cov)
Definition at line 177 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 177 of file MultiStepperTests.cpp
BOOST_AUTO_TEST_CASE (multi_eigen_stepper_state_invalid)
Definition at line 193 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 193 of file MultiStepperTests.cpp
BOOST_AUTO_TEST_CASE (multi_eigen_vs_single_eigen)
Definition at line 259 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 259 of file MultiStepperTests.cpp
BOOST_AUTO_TEST_CASE (multi_eigen_component_iterable_with_modification)
Definition at line 349 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 349 of file MultiStepperTests.cpp
BOOST_AUTO_TEST_CASE (test_surface_status_and_cmpwise_bound_state)
Definition at line 449 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 449 of file MultiStepperTests.cpp
BOOST_AUTO_TEST_CASE (test_component_wise_bound_state)
Definition at line 528 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 528 of file MultiStepperTests.cpp
BOOST_AUTO_TEST_CASE (test_combined_bound_state)
Definition at line 570 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 570 of file MultiStepperTests.cpp
BOOST_AUTO_TEST_CASE (test_curvilinear_state)
Definition at line 615 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 615 of file MultiStepperTests.cpp
BOOST_AUTO_TEST_CASE (test_single_component_interface)
Definition at line 670 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 670 of file MultiStepperTests.cpp
BOOST_AUTO_TEST_CASE (remove_add_components_test)
Definition at line 705 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 705 of file MultiStepperTests.cpp
BOOST_AUTO_TEST_CASE (propagator_instatiation_test)
Definition at line 742 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 742 of file MultiStepperTests.cpp
auto makeDefaultBoundPars (bool cov = true, std::size_t n = 4, std::optional< BoundVector > ext_pars = std::nullopt)
Definition at line 110 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 110 of file MultiStepperTests.cpp
References Acts::PhysicalConstants::c, Acts::Test::cov, i, n, particleHypothesis, and writeMapConfig::surface.
Referenced by remove_add_components_function(), test_components_modifying_accessors(), test_multi_stepper_state(), and test_multi_stepper_state_invalid().
template<typename multi_stepper_t > void propagator_instatiation_test_function ()
Definition at line 714 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 714 of file MultiStepperTests.cpp
References Acts::IntegrationTest::bField, geoCtx, magCtx, testing::internal::move(), ckf::options, pars, particleHypothesis, and writeMapConfig::surface.
template<typename multi_stepper_t > void remove_add_components_function ()
Definition at line 679 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 679 of file MultiStepperTests.cpp
References defaultBField, defaultStepSize, geoCtx, magCtx, makeDefaultBoundPars(), pars, and particleHypothesis.
template<typename multi_stepper_t > void test_combined_bound_state_function ()
Definition at line 533 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 533 of file MultiStepperTests.cpp
References Acts::PhysicalConstants::c, Acts::Test::cov, defaultBField, defaultStepSize, Acts::UnitConstants::e, geoCtx, magCtx, pars, particleHypothesis, ActsTests::PropagationDatasets::pathLength, and writeMapConfig::surface.
template<typename multi_stepper_t > void test_combined_curvilinear_state_function ()
Definition at line 578 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 578 of file MultiStepperTests.cpp
References Acts::PhysicalConstants::c, Acts::Test::cov, defaultBField, defaultStepSize, geoCtx, magCtx, pars, particleHypothesis, ActsTests::PropagationDatasets::pathLength, and writeMapConfig::surface.
template<typename multi_stepper_t > void test_component_bound_state ()
Definition at line 457 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 457 of file MultiStepperTests.cpp
References Acts::detail::boundState(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::boundState(), defaultNullBField, defaultStepSize, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::Direction::Forward, geoCtx, magCtx, mockNavigator, particleHypothesis, Acts::EigenStepper< extensionlist_t, auctioneer_t >::step(), and Acts::EigenStepper< extensionlist_t, auctioneer_t >::updateSurfaceStatus().
template<typename multi_stepper_t > void test_components_modifying_accessors ()
Definition at line 274 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 274 of file MultiStepperTests.cpp
References check_fpe_masks::check(), root_event_diff_np::cmp(), defaultBField, defaultStepSize, Acts::UnitConstants::e, geoCtx, magCtx, std::tr1::make_tuple(), makeDefaultBoundPars(), modify(), and Acts::type.
template<typename multi_stepper_t , bool Cov> void test_multi_stepper_state ()
Test the construction of the MultiStepper::State
Definition at line 137 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 137 of file MultiStepperTests.cpp
References root_event_diff_np::cmp(), defaultBField, defaultStepSize, geoCtx, magCtx, makeDefaultBoundPars(), Acts::UnitConstants::ms, N, and filter::state.
template<typename multi_stepper_t > void test_multi_stepper_state_invalid ()
Definition at line 182 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 182 of file MultiStepperTests.cpp
References defaultBField, defaultStepSize, geoCtx, magCtx, and makeDefaultBoundPars().
template<typename multi_stepper_t > void test_multi_stepper_surface_status_update ()
Definition at line 357 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 357 of file MultiStepperTests.cpp
References defaultNullBField, defaultStepSize, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::Direction::Forward, geoCtx, magCtx, mockNavigator, particleHypothesis, utils::status, and Acts::EigenStepper< extensionlist_t, auctioneer_t >::step().
template<typename multi_stepper_t > void test_multi_stepper_vs_eigen_stepper ()
Definition at line 201 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 201 of file MultiStepperTests.cpp
References root_event_diff_np::cmp(), Acts::Test::cov, defaultBField, defaultNDir, defaultStepSize, geoCtx, i, magCtx, mockNavigator, pars, particleHypothesis, Acts::EigenStepper< extensionlist_t, auctioneer_t >::step(), writeMapConfig::surface, and Acts::EigenStepper< extensionlist_t, auctioneer_t >::transportCovarianceToCurvilinear().
template<typename multi_stepper_t > void test_single_component_interface_function ()
Definition at line 624 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 624 of file MultiStepperTests.cpp
References check_fpe_masks::check(), root_event_diff_np::cmp(), defaultBField, defaultNDir, defaultStepSize, Acts::eFreeDir0, Acts::eFreePos0, Acts::eFreeQOverP, Acts::eFreeTime, geoCtx, i, magCtx, particleHypothesis, and writeMapConfig::surface.
Variable Documentation
const auto defaultBField
Initial value:
=
    std::make_shared<ConstantBField>(Vector3(1., 2.5, 33.33))
Definition at line 68 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 68 of file MultiStepperTests.cpp
Referenced by remove_add_components_function(), test_combined_bound_state_function(), test_combined_curvilinear_state_function(), test_components_modifying_accessors(), test_multi_stepper_state(), test_multi_stepper_state_invalid(), test_multi_stepper_vs_eigen_stepper(), and test_single_component_interface_function().
const auto defaultNDir = Direction::Backward
Definition at line 66 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file MultiStepperTests.cpp
Referenced by test_multi_stepper_vs_eigen_stepper(), and test_single_component_interface_function().
const auto defaultNullBField = std::make_shared<NullBField>()
Definition at line 70 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file MultiStepperTests.cpp
Referenced by test_component_bound_state(), and test_multi_stepper_surface_status_update().
const double defaultStepSize = 123.
Definition at line 65 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 65 of file MultiStepperTests.cpp
Referenced by remove_add_components_function(), test_combined_bound_state_function(), test_combined_curvilinear_state_function(), test_component_bound_state(), test_components_modifying_accessors(), test_multi_stepper_state(), test_multi_stepper_state_invalid(), test_multi_stepper_surface_status_update(), test_multi_stepper_vs_eigen_stepper(), and test_single_component_interface_function().
const GeometryContext geoCtx
Definition at line 59 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 59 of file MultiStepperTests.cpp
const MagneticFieldContext magCtx
Definition at line 58 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 58 of file MultiStepperTests.cpp
constexpr MockNavigator mockNavigator static
Definition at line 84 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 84 of file MultiStepperTests.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), test_component_bound_state(), test_multi_stepper_surface_status_update(), and test_multi_stepper_vs_eigen_stepper().
const auto particleHypothesis = ParticleHypothesis::pion()
Definition at line 72 of file MultiStepperTests.cpp.
View newest version in sPHENIX GitHub at line 72 of file MultiStepperTests.cpp
Referenced by Acts::Python::addEventData(), Acts::Python::addPropagation(), Acts::Python::addTrackFinding(), Acts::Python::addTruthTracking(), Acts::detail::GenericDenseEnvironmentExtension< scalar_t >::bid(), BOOST_DATA_TEST_CASE(), Acts::detail::boundState(), Acts::EventDataView3D::drawMultiTrajectory(), ActsExamples::ParticleSmearing::execute(), Acts::detail::GenericDenseEnvironmentExtension< scalar_t >::finalize(), Acts::detail::GenericDenseEnvironmentExtension< scalar_t >::initializeEnergyLoss(), Acts::detail::GenericDenseEnvironmentExtension< scalar_t >::k(), makeDefaultBoundPars(), makeParametersCurvilinear(), makeParametersCurvilinearWithCovariance(), propagator_instatiation_test_function(), remove_add_components_function(), Acts::VectorTrackContainer::setParticleHypothesis_impl(), test_combined_bound_state_function(), test_combined_curvilinear_state_function(), test_component_bound_state(), test_multi_stepper_surface_status_update(), test_multi_stepper_vs_eigen_stepper(), test_single_component_interface_function(), and Acts::detail::GenericDenseEnvironmentExtension< scalar_t >::transportMatrix().