Analysis Software: OnlMonDB Class Reference
OnlMonDB Class Reference
#include <OnlMon/blob/main/onlmondatabase/OnlMonDB.h>
Public Member Functions
OnlMonDB (const std::string &thisname="DUMMY")
virtual ~OnlMonDB ()
int registerVar (const std::string &varname)
int SetVar (const std::string &varname, const float var, const float varerr, const float varqual)
int SetVar (const std::string &varname, const float var[3])
int DBcommit ()
int DBcommitTest ()
int DBInit ()
void Print () const
int GetVar (const time_t begin, const time_t end, const std::string &varname, std::vector< time_t > &timestp, std::vector< int > &runnumber, std::vector< float > &var, std::vector< float > &varerr)
void Reset ()
Public Member Functions inherited from OnlMonBase
OnlMonBase (const std::string &name="NONE")
virtual ~OnlMonBase ()
const std::string Name () const
void Name (const std::string &name)
virtual void Verbosity (const int i)
virtual int Verbosity () const
Protected Attributes
std::map< const std::string,
OnlMonDBVar * > varmap
OnlMonDBodbc * db = nullptr
Protected Attributes inherited from OnlMonBase
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 14 of file OnlMonDB.h.
View newest version in sPHENIX GitHub at line 14 of file OnlMonDB.h
Constructor & Destructor Documentation
OnlMonDB::OnlMonDB (const std::string & thisname = "DUMMY")
Definition at line 15 of file OnlMonDB.cc.
View newest version in sPHENIX GitHub at line 15 of file OnlMonDB.cc
OnlMonDB::~OnlMonDB () virtual
Definition at line 21 of file OnlMonDB.cc.
View newest version in sPHENIX GitHub at line 21 of file OnlMonDB.cc
References db, and varmap.
Member Function Documentation
int OnlMonDB::DBcommit ()
Definition at line 90 of file OnlMonDB.cc.
View newest version in sPHENIX GitHub at line 90 of file OnlMonDB.cc
References OnlMonDBodbc::AddRow(), OnlMonServer::CurrentTicks(), db, OnlMonServer::instance(), printf(), OnlMonServer::RunNumber(), and varmap.
Referenced by MyMon::process_event().
int OnlMonDB::DBcommitTest ()
Definition at line 116 of file OnlMonDB.cc.
View newest version in sPHENIX GitHub at line 116 of file OnlMonDB.cc
References OnlMonDBodbc::AddRow(), db, runnumber, Acts::Test::time, and varmap.
int OnlMonDB::DBInit ()
Definition at line 79 of file OnlMonDB.cc.
View newest version in sPHENIX GitHub at line 79 of file OnlMonDB.cc
References OnlMonDBodbc::CheckAndCreateTable(), db, OnlMonBase::ThisName, varmap, and OnlMonBase::Verbosity().
Referenced by MyMon::DBVarInit(), and InttMon::DBVarInit().
int OnlMonDB::GetVar (const time_t begin, const time_t end, const std::string & varname, std::vector< time_t > & timestp, std::vector< int > & runnumber, std::vector< float > & var, std::vector< float > & varerr)
Definition at line 154 of file OnlMonDB.cc.
View newest version in sPHENIX GitHub at line 154 of file OnlMonDB.cc
References db, OnlMonDBodbc::GetVar(), and OnlMonBase::ThisName.
Referenced by MyMonDraw::DrawHistory(), DaqMonDraw::DrawHistory(), and MvtxMonDraw::DrawHistory().
void OnlMonDB::Print () const
Definition at line 31 of file OnlMonDB.cc.
View newest version in sPHENIX GitHub at line 31 of file OnlMonDB.cc
References OnlMonBase::ThisName, and varmap.
Referenced by MyMon::DBVarInit().
int OnlMonDB::registerVar (const std::string & varname)
Definition at line 42 of file OnlMonDB.cc.
View newest version in sPHENIX GitHub at line 42 of file OnlMonDB.cc
References Acts::Test::transform, and varmap.
Referenced by MyMon::DBVarInit(), and InttMon::DBVarInit().
void OnlMonDB::Reset ()
Definition at line 164 of file OnlMonDB.cc.
View newest version in sPHENIX GitHub at line 164 of file OnlMonDB.cc
References varmap.
int OnlMonDB::SetVar (const std::string & varname, const float var, const float varerr, const float varqual)
Definition at line 56 of file OnlMonDB.cc.
View newest version in sPHENIX GitHub at line 56 of file OnlMonDB.cc
Referenced by InttMon::DBVarUpdate(), and MyMon::process_event().
int OnlMonDB::SetVar (const std::string & varname, const float var[3])
Definition at line 65 of file OnlMonDB.cc.
View newest version in sPHENIX GitHub at line 65 of file OnlMonDB.cc
References Acts::Test::transform, and varmap.
Member Data Documentation
OnlMonDBodbc* OnlMonDB::db = nullptr protected
Definition at line 32 of file OnlMonDB.h.
View newest version in sPHENIX GitHub at line 32 of file OnlMonDB.h
Referenced by DBcommit(), DBcommitTest(), DBInit(), GetVar(), and ~OnlMonDB().
std::map<const std::string, OnlMonDBVar *> OnlMonDB::varmap protected
Definition at line 31 of file OnlMonDB.h.
View newest version in sPHENIX GitHub at line 31 of file OnlMonDB.h
Referenced by DBcommit(), DBcommitTest(), DBInit(), Print(), registerVar(), Reset(), SetVar(), and ~OnlMonDB().
The documentation for this class was generated from the following files:
OnlMon/blob/main/onlmondatabase/OnlMonDB.h
OnlMon/blob/main/onlmondatabase/OnlMonDB.cc