Analysis Software: analysis/blob/master/HF-Particle/D0/makeV1_BUP2020.C File Reference
makeV1_BUP2020.C File Reference
#include <fstream>
#include <iostream>
#include "stdio.h"
#include <TChain.h>
#include <TFile.h>
#include <TGraphAsymmErrors.h>
#include <TGraphErrors.h>
#include <TLatex.h>
#include <TLegend.h>
#include <TLine.h>
#include <TROOT.h>
#include <TMath.h>
#include <TString.h>
#include <TTree.h>
#include <TVectorD.h>
#include <TVirtualFitter.h>
#include <cassert>
#include <cmath>
#include <vector>
#include "SaveCanvas.C"
#include "sPhenixStyle.C"
Functions
Double_t v1_err (Double_t sig, Double_t v1, Double_t Res)
TGraphErrors * GraphShiftScaling (TGraphErrors *gr_src, const double x_shift, const double err_scaling)
void makeV1_BUP2020 (const Bool_t sPHENIX=1)
Function Documentation
TGraphErrors* GraphShiftScaling (TGraphErrors * gr_src, const double x_shift, const double err_scaling)
Definition at line 33 of file makeV1_BUP2020.C.
View newest version in sPHENIX GitHub at line 33 of file makeV1_BUP2020.C
References assert, gr, i, vx, vy, and ambiguity_solver_full_chain::x.
void makeV1_BUP2020 (const Bool_t sPHENIX = 1)
Definition at line 70 of file makeV1_BUP2020.C.
View newest version in sPHENIX GitHub at line 70 of file makeV1_BUP2020.C
References AuAu_Ncoll_60_70, AuAu_Ncoll_70_80, AuAu_Ncoll_C0_10, AuAu_Ncoll_C0_100, AuAu_Ncoll_C0_20, AuAu_rec_3year, AuAu_rec_5year, eta, GraphShiftScaling(), i, ambiguity_solver_full_chain::idx, leg, offset, merge_hashes::p, pAu_Ncoll_C0_100, refAuAuMB, refAuAuXSec, SaveCanvas(), SetsPhenixStyle(), v1_err(), ambiguity_solver_full_chain::x, y, and yn.
Double_t v1_err (Double_t sig, Double_t v1, Double_t Res)
Definition at line 27 of file makeV1_BUP2020.C.
View newest version in sPHENIX GitHub at line 27 of file makeV1_BUP2020.C
Referenced by makeV1_BUP2020().