Analysis Software: analysis/blob/master/dNdEta_Run2023/analysis_INTT/src/Utilities.h File Reference
Utilities.h File Reference
#include <vector>
#include <TMath.h>
#include <TFile.h>
#include <TTree.h>
Functions
template<class T >
void CleanVec (std::vector< T > &v)
float deltaPhi (float phi1, float phi2)
float deltaR (float eta1, float phi1, float eta2, float phi2)
template<typename T >
std::string number_to_string (T param_)
vector< tuple< float, float,
float, float > > MVTXStavePositionXY ()
Function Documentation
template<class T > void CleanVec (std::vector< T > & v)
Definition at line 10 of file Utilities.h.
View newest version in sPHENIX GitHub at line 10 of file Utilities.h
References swap().
Referenced by main(), ResetVec(), and dNdEtaINTT::ResetVectors().
float deltaPhi (float phi1, float phi2)
Definition at line 16 of file Utilities.h.
View newest version in sPHENIX GitHub at line 16 of file Utilities.h
Referenced by STrackCutStudy::Analyze(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), CMDistortionAnalysis(), CMDistortionAnalysisCart(), CMDistortionAnalysisPhiR(), CMDistortionReco(), CMDistortionRecoCart(), CMDistortionRecoPhiR(), Acts::SpacePointGridCreator::createGrid(), deltaR(), PHTrackClusterAssociator::getCluster(), main(), Fatras::Scattering< formula_t >::operator()(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::performNewtonOptimization(), QAG4SimulationDistortions::process_event(), PHTpcResiduals::processTrack(), ProtoTracklets(), Acts::SeedFinderFTF< external_spacepoint_t >::runGNN_TrackFinder(), Tracklet::SetHits(), and Tracklet::Tracklet().
float deltaR (float eta1, float phi1, float eta2, float phi2)
Definition at line 26 of file Utilities.h.
View newest version in sPHENIX GitHub at line 26 of file Utilities.h
References deltaPhi().
vector<tuple<float, float, float, float> > MVTXStavePositionXY ()
Definition at line 55 of file Utilities.h.
View newest version in sPHENIX GitHub at line 55 of file Utilities.h
References f, i, std::tr1::make_tuple(), t, and testSigmaEff::v.
template<typename T > std::string number_to_string (T param_)
Definition at line 34 of file Utilities.h.
View newest version in sPHENIX GitHub at line 34 of file Utilities.h
References str, and to_string().