Analysis Software: Calibrator Class Reference
Calibrator Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase/Calibrator.h>
Public Types
using Measurement = ::Acts::BoundVariantMeasurement
using MeasurementContainer = std::vector< Measurement >
Public Member Functions
void calibrate (const MeasurementContainer &measurements, const Acts::GeometryContext &gctx, const Acts::CalibrationContext &, const Acts::SourceLink &sourceLink, Acts::VectorMultiTrajectory::TrackStateProxy &trackState) const
virtual ~Calibrator ()=default
Detailed Description
Definition at line 16 of file Calibrator.h.
View newest version in sPHENIX GitHub at line 16 of file Calibrator.h
Member Typedef Documentation
using Calibrator::Measurement = ::Acts::BoundVariantMeasurement
Definition at line 19 of file Calibrator.h.
View newest version in sPHENIX GitHub at line 19 of file Calibrator.h
using Calibrator::MeasurementContainer = std::vector<Measurement>
Container of measurements.
In contrast to the source links, the measurements themself must not be orderable. The source links stored in the measurements are treated as opaque here and no ordering is enforced on the stored measurements.
Definition at line 25 of file Calibrator.h.
View newest version in sPHENIX GitHub at line 25 of file Calibrator.h
Constructor & Destructor Documentation
virtual Calibrator::~Calibrator () virtual default
Member Function Documentation
void Calibrator::calibrate (const MeasurementContainer & measurements, const Acts::GeometryContext & gctx, const Acts::CalibrationContext & , const Acts::SourceLink & sourceLink, Acts::VectorMultiTrajectory::TrackStateProxy & trackState) const
Definition at line 3 of file Calibrator.cc.
View newest version in sPHENIX GitHub at line 3 of file Calibrator.cc
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::allocateCalibrated(), ActsSourceLink::cluskey(), Acts::Test::cov, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::SourceLink::get(), TrkrDefs::getLayer(), i, ActsSourceLink::index(), index, j, layer, loc, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setCalibrated(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setUncalibratedSourceLink(), and Acts::Measurement< indices_t, kSize >::size().
Referenced by CalibratorAdapter::calibrate().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/Calibrator.h
coresoftware/blob/master/offline/packages/trackbase/Calibrator.cc