Analysis Software: PktSizeMonDraw Class Reference
PktSizeMonDraw Class Reference
#include <OnlMon/blob/main/subsystems/pktsize/PktSizeMonDraw.h>
Public Member Functions
PktSizeMonDraw (const std::string &name="PKTSIZEMON")
virtual ~PktSizeMonDraw ()
int Init ()
int Draw (const std::string &what="ALL")
int MakeHtml (const std::string &what="ALL")
int SavePlot (const std::string &what="ALL", const std::string &type="png")
int loadpreviousruns (const int nruns=5)
int AddKnownBig (const unsigned int packetid, const float maxsize)
void Print (const std::string &what="ALL") const
int CleanOldRuns (const unsigned int maxrun)
int RemoveRun (const int runno)
Public Member Functions inherited from OnlMonDraw
OnlMonDraw (const std::string &name="NONE")
virtual ~OnlMonDraw ()
virtual int MakePS (const std::string &what="ALL")
const std::string Name () const
void Verbosity (const int i)
int Verbosity () const
Protected Member Functions
int MakeCanvas (const char *name)
int DrawFirst (const std::string &what="ALL")
int DrawOldFirst (const std::string &what="ALL")
int DrawHistory (const std::string &what="ALL")
int FillPacketMap (const TH1 *histo)
int FillRunPacketList (std::map< unsigned int, float > &pkts, const int runnumber)
int ExtractActivePackets (const std::map< unsigned int, float > &packetsize)
int MakeNoisyCandidates ()
int IsKnownBig (const unsigned int packetid, const float size)
int PlotNoisy (TGraph &gr, TMarker &tr, TText &tx, const unsigned int ipkt, const unsigned int icnt)
int ReplaceRunFromDB (const int runno)
Protected Member Functions inherited from OnlMonDraw
virtual int DrawDeadServer (TPad *transparent)
Protected Attributes
TCanvas * TC [2] {}
TPad * transparent [2] {}
TPad * Pad [2] {}
TH2 * Frames [12] {}
PktSizeDBodbc * db = nullptr
RunDBodbc * rd = nullptr
TMarker * tm = nullptr
int lastrun
std::map< int, std::map
< unsigned int, float > > packetmap
std::map< std::string,
std::pair< unsigned int,
unsigned int > > granulepacketlimits
std::map< unsigned int, float > knownbig
std::set< unsigned int > activepackets
std::set< unsigned int > noisypackets
std::set< int > runlist
Protected Attributes inherited from OnlMonDraw
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 18 of file PktSizeMonDraw.h.
View newest version in sPHENIX GitHub at line 18 of file PktSizeMonDraw.h
Constructor & Destructor Documentation
PktSizeMonDraw::PktSizeMonDraw (const std::string & name = "PKTSIZEMON")
Definition at line 37 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 37 of file PktSizeMonDraw.cc
References lastrun, Pad, TC, tm, and transparent.
PktSizeMonDraw::~PktSizeMonDraw () virtual
Definition at line 50 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 50 of file PktSizeMonDraw.cc
References activepackets, db, Frames, knownbig, packetmap, and rd.
Member Function Documentation
int PktSizeMonDraw::AddKnownBig (const unsigned int packetid, const float maxsize)
Definition at line 688 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 688 of file PktSizeMonDraw.cc
References knownbig, and packetid.
Referenced by MakeHtml().
int PktSizeMonDraw::CleanOldRuns (const unsigned int maxrun)
Definition at line 725 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 725 of file PktSizeMonDraw.cc
References packetmap, runlist, and OnlMonDraw::verbosity.
Referenced by DrawHistory().
int PktSizeMonDraw::Draw (const std::string & what = "ALL") virtual
Reimplemented from OnlMonDraw.
Definition at line 104 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 104 of file PktSizeMonDraw.cc
References DrawFirst(), DrawHistory(), and PHWHERE.
Referenced by MakeHtml(), and SavePlot().
int PktSizeMonDraw::DrawFirst (const std::string & what = "ALL") protected
Definition at line 126 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 126 of file PktSizeMonDraw.cc
References KFPMath::a, KFPMath::b, cd(), OnlMonDraw::DrawDeadServer(), Frames, OnlMonClient::getHisto(), i, OnlMonClient::instance(), MakeCanvas(), n, TC, tm, transparent, and ambiguity_solver_full_chain::x.
Referenced by Draw().
int PktSizeMonDraw::DrawHistory (const std::string & what = "ALL") protected
Definition at line 586 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 586 of file PktSizeMonDraw.cc
References bytelimit, CleanOldRuns(), OnlMonDraw::DrawDeadServer(), OnlMonClient::EventTime(), OnlMonClient::getHisto(), gr, htmp, OnlMonClient::instance(), lastrun, loadpreviousruns(), MakeCanvas(), MakeNoisyCandidates(), MAXSIZEDISP, noisypackets, Pad, PlotNoisy(), rd, RemoveRun(), ReplaceRunFromDB(), runlist, OnlMonClient::RunNumber(), runnumber, RunDBodbc::RunType(), TC, AlignmentDefs::tl, and transparent.
Referenced by Draw().
int PktSizeMonDraw::DrawOldFirst (const std::string & what = "ALL") protected
Definition at line 306 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 306 of file PktSizeMonDraw.cc
References bytelimit, OnlMonDraw::DrawDeadServer(), OnlMonClient::EventTime(), FillPacketMap(), OnlMonClient::getHisto(), GRANTXTOFFSET, granulepacketlimits, htmp, OnlMonClient::instance(), IsKnownBig(), MakeCanvas(), MAXPKTDISP, MAXSIZEDISP, packetmap, Pad, OnlMonClient::RunNumber(), runnumber, TC, AlignmentDefs::tl, transparent, and xpos.
int PktSizeMonDraw::ExtractActivePackets (const std::map< unsigned int, float > & packetsize) protected
Definition at line 789 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 789 of file PktSizeMonDraw.cc
References activepackets.
Referenced by FillPacketMap().
int PktSizeMonDraw::FillPacketMap (const TH1 * histo) protected
Definition at line 485 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 485 of file PktSizeMonDraw.cc
References ExtractActivePackets(), i, OnlMonClient::instance(), packetid, packetmap, OnlMonClient::RunNumber(), and runnumber.
Referenced by DrawOldFirst().
int PktSizeMonDraw::FillRunPacketList (std::map< unsigned int, float > & pkts, const int runnumber) protected
Definition at line 715 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 715 of file PktSizeMonDraw.cc
References db, PktSizeDBodbc::GetPacketContent(), and granulepacketlimits.
Referenced by loadpreviousruns(), and ReplaceRunFromDB().
int PktSizeMonDraw::Init () virtual
Reimplemented from OnlMonDraw.
Definition at line 64 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 64 of file PktSizeMonDraw.cc
References db, PktSizeCommon::fillgranules(), granulepacketlimits, rd, and OnlMonDraw::ThisName.
int PktSizeMonDraw::IsKnownBig (const unsigned int packetid, const float size) protected
Definition at line 694 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 694 of file PktSizeMonDraw.cc
References knownbig.
Referenced by DrawOldFirst(), and MakeNoisyCandidates().
int PktSizeMonDraw::loadpreviousruns (const int nruns = 5)
Definition at line 674 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 674 of file PktSizeMonDraw.cc
References FillRunPacketList(), RunDBodbc::GetRunNumbers(), lastrun, packetmap, rd, and runlist.
Referenced by DrawHistory().
int PktSizeMonDraw::MakeCanvas (const char * name) protected
Definition at line 72 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 72 of file PktSizeMonDraw.cc
References OnlMonClient::GetDisplaySizeX(), OnlMonClient::GetDisplaySizeY(), OnlMonClient::instance(), Pad, TC, and transparent.
Referenced by DrawFirst(), DrawHistory(), and DrawOldFirst().
int PktSizeMonDraw::MakeHtml (const std::string & what = "ALL") virtual
Reimplemented from OnlMonDraw.
Definition at line 533 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 533 of file PktSizeMonDraw.cc
References AddKnownBig(), OnlMonClient::CanvasToPng(), Draw(), OnlMonClient::htmlRegisterPage(), i, OnlMonClient::instance(), OnlMonClient::SaveLogFile(), and TC.
int PktSizeMonDraw::MakeNoisyCandidates () protected
Definition at line 799 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 799 of file PktSizeMonDraw.cc
References activepackets, bytelimit, OnlMonClient::instance(), IsKnownBig(), noisypackets, packetmap, OnlMonClient::RunNumber(), runnumber, size, and OnlMonDraw::verbosity.
Referenced by DrawHistory().
int PktSizeMonDraw::PlotNoisy (TGraph & gr, TMarker & tr, TText & tx, const unsigned int ipkt, const unsigned int icnt) protected
Definition at line 861 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 861 of file PktSizeMonDraw.cc
References i, lastrun, MAXSIZEDISP, packetmap, ambiguity_solver_full_chain::x, and y.
Referenced by DrawHistory().
void PktSizeMonDraw::Print (const std::string & what = "ALL") const
Definition at line 760 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 760 of file PktSizeMonDraw.cc
References packetmap, and runlist.
int PktSizeMonDraw::RemoveRun (const int runno)
Definition at line 744 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 744 of file PktSizeMonDraw.cc
References packetmap, and runlist.
Referenced by DrawHistory().
int PktSizeMonDraw::ReplaceRunFromDB (const int runno) protected
Definition at line 707 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 707 of file PktSizeMonDraw.cc
References FillRunPacketList(), and packetmap.
Referenced by DrawHistory().
int PktSizeMonDraw::SavePlot (const std::string & what = "ALL", const std::string & type = "png") virtual
Reimplemented from OnlMonDraw.
Definition at line 510 of file PktSizeMonDraw.cc.
View newest version in sPHENIX GitHub at line 510 of file PktSizeMonDraw.cc
References OnlMonClient::CanvasToPng(), Draw(), filename, OnlMonClient::instance(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and to_string().
Member Data Documentation
std::set<unsigned int> PktSizeMonDraw::activepackets protected
Definition at line 58 of file PktSizeMonDraw.h.
View newest version in sPHENIX GitHub at line 58 of file PktSizeMonDraw.h
Referenced by ExtractActivePackets(), MakeNoisyCandidates(), and ~PktSizeMonDraw().
PktSizeDBodbc* PktSizeMonDraw::db = nullptr protected
Definition at line 51 of file PktSizeMonDraw.h.
View newest version in sPHENIX GitHub at line 51 of file PktSizeMonDraw.h
Referenced by FillRunPacketList(), Init(), and ~PktSizeMonDraw().
TH2* PktSizeMonDraw::Frames[12] {} protected
Definition at line 50 of file PktSizeMonDraw.h.
View newest version in sPHENIX GitHub at line 50 of file PktSizeMonDraw.h
Referenced by DrawFirst(), and ~PktSizeMonDraw().
std::map<std::string, std::pair<unsigned int, unsigned int> > PktSizeMonDraw::granulepacketlimits protected
Definition at line 56 of file PktSizeMonDraw.h.
View newest version in sPHENIX GitHub at line 56 of file PktSizeMonDraw.h
Referenced by DrawOldFirst(), FillRunPacketList(), and Init().
std::map<unsigned int, float> PktSizeMonDraw::knownbig protected
Definition at line 57 of file PktSizeMonDraw.h.
View newest version in sPHENIX GitHub at line 57 of file PktSizeMonDraw.h
Referenced by AddKnownBig(), IsKnownBig(), and ~PktSizeMonDraw().
int PktSizeMonDraw::lastrun protected
Definition at line 54 of file PktSizeMonDraw.h.
View newest version in sPHENIX GitHub at line 54 of file PktSizeMonDraw.h
Referenced by DrawHistory(), loadpreviousruns(), PktSizeMonDraw(), and PlotNoisy().
std::set<unsigned int> PktSizeMonDraw::noisypackets protected
Definition at line 59 of file PktSizeMonDraw.h.
View newest version in sPHENIX GitHub at line 59 of file PktSizeMonDraw.h
Referenced by DrawHistory(), and MakeNoisyCandidates().
std::map<int, std::map<unsigned int, float> > PktSizeMonDraw::packetmap protected
Definition at line 55 of file PktSizeMonDraw.h.
View newest version in sPHENIX GitHub at line 55 of file PktSizeMonDraw.h
Referenced by CleanOldRuns(), DrawOldFirst(), FillPacketMap(), loadpreviousruns(), MakeNoisyCandidates(), PlotNoisy(), Print(), RemoveRun(), ReplaceRunFromDB(), and ~PktSizeMonDraw().
TPad* PktSizeMonDraw::Pad[2] {} protected
Definition at line 49 of file PktSizeMonDraw.h.
View newest version in sPHENIX GitHub at line 49 of file PktSizeMonDraw.h
Referenced by DrawHistory(), DrawOldFirst(), MakeCanvas(), and PktSizeMonDraw().
RunDBodbc* PktSizeMonDraw::rd = nullptr protected
Definition at line 52 of file PktSizeMonDraw.h.
View newest version in sPHENIX GitHub at line 52 of file PktSizeMonDraw.h
Referenced by DrawHistory(), Init(), loadpreviousruns(), and ~PktSizeMonDraw().
std::set<int> PktSizeMonDraw::runlist protected
Definition at line 60 of file PktSizeMonDraw.h.
View newest version in sPHENIX GitHub at line 60 of file PktSizeMonDraw.h
Referenced by CleanOldRuns(), DrawHistory(), loadpreviousruns(), Print(), and RemoveRun().
TCanvas* PktSizeMonDraw::TC[2] {} protected
Definition at line 47 of file PktSizeMonDraw.h.
View newest version in sPHENIX GitHub at line 47 of file PktSizeMonDraw.h
Referenced by DrawFirst(), DrawHistory(), DrawOldFirst(), MakeCanvas(), MakeHtml(), PktSizeMonDraw(), and SavePlot().
TMarker* PktSizeMonDraw::tm = nullptr protected
Definition at line 53 of file PktSizeMonDraw.h.
View newest version in sPHENIX GitHub at line 53 of file PktSizeMonDraw.h
Referenced by DrawFirst(), and PktSizeMonDraw().
TPad* PktSizeMonDraw::transparent[2] {} protected
Definition at line 48 of file PktSizeMonDraw.h.
View newest version in sPHENIX GitHub at line 48 of file PktSizeMonDraw.h
Referenced by DrawFirst(), DrawHistory(), DrawOldFirst(), MakeCanvas(), and PktSizeMonDraw().
The documentation for this class was generated from the following files:
OnlMon/blob/main/subsystems/pktsize/PktSizeMonDraw.h
OnlMon/blob/main/subsystems/pktsize/PktSizeMonDraw.cc