Analysis Software: Jetscape::JetScapeWriterAsciiGZ Class Reference
Jetscape::JetScapeWriterAsciiGZ Class Reference
#include <JETSCAPE/blob/main/jail/JetScapeWriterAsciiGZ.h>
Public Member Functions
JetScapeWriterAsciiGZ ()
JetScapeWriterAsciiGZ (string m_file_name_out)
virtual ~JetScapeWriterAsciiGZ ()
void Init ()
void Exec ()
bool GetStatus ()
void Close ()
void Write (weak_ptr< PartonShower > ps)
void Write (weak_ptr< Parton > p)
void Write (weak_ptr< Vertex > v)
void Write (weak_ptr< Hadron > h)
void WriteHeaderToFile ()
Gets called first, before all tasks write themselves.
void Write (string s)
void WriteComment (string s)
void WriteWhiteSpace (string s)
void WriteEvent ()
Gets called last, after all tasks have written themselves.
Public Member Functions inherited from Jetscape::JetScapeWriter
JetScapeWriter ()
JetScapeWriter (string m_file_name_out)
virtual ~JetScapeWriter ()
void SetOutputFileName (string m_file_name_out)
string GetOutputFileName ()
virtual void Open ()
virtual void WriteInitFileXML ()
virtual void Write (weak_ptr< Jet > j)
virtual void Write (ostream *o)
virtual JetScapeEventHeader & GetHeader ()
Public Member Functions inherited from Jetscape::JetScapeModuleBase
JetScapeModuleBase ()
JetScapeModuleBase (string m_name)
virtual ~JetScapeModuleBase ()
virtual void Clear ()
void SetXMLMainFileName (string m_name)
string GetXMLMainFileName ()
void SetXMLUserFileName (string m_name)
string GetXMLUserFileName ()
shared_ptr< std::mt19937 > GetMt19937Generator ()
tinyxml2::XMLElement * GetXMLElement (std::initializer_list< const char * > path, bool isRequired=true)
std::string GetXMLElementText (std::initializer_list< const char * > path, bool isRequired=true)
int GetXMLElementInt (std::initializer_list< const char * > path, bool isRequired=true)
double GetXMLElementDouble (std::initializer_list< const char * > path, bool isRequired=true)
Public Member Functions inherited from Jetscape::JetScapeTask
JetScapeTask ()
virtual ~JetScapeTask ()
virtual void Finish ()
virtual void ExecuteTasks ()
virtual void ExecuteTask ()
virtual void InitTask ()
virtual void InitTasks ()
virtual void ClearTasks ()
virtual void ClearTask ()
virtual void FinishTask ()
virtual void FinishTasks ()
virtual void WriteTasks (weak_ptr< JetScapeWriter > w)
virtual void WriteTask (weak_ptr< JetScapeWriter > w)
virtual void CollectHeader (weak_ptr< JetScapeWriter > w)
virtual void CollectHeaders (weak_ptr< JetScapeWriter > w)
virtual void Add (shared_ptr< JetScapeTask > m_tasks)
virtual const int GetMyTaskNumber () const
const vector< shared_ptr
< JetScapeTask > > GetTaskList () const
shared_ptr< JetScapeTask > GetTaskAt (int i)
void EraseTaskLast ()
void EraseTaskAt (int i)
void ResizeTaskList (int i)
void ClearTaskList ()
int GetNumberOfTasks ()
const bool GetActive () const
void SetActive (bool m_active_exec)
void SetId (string m_id)
const string GetId () const
const shared_ptr
< JetScapeModuleMutex > GetMutex () const
void SetMutex (shared_ptr< JetScapeModuleMutex > m_mutex)
Public Member Functions inherited from sigslot::has_slots< sigslot::multi_threaded_local >
has_slots ()
has_slots (const has_slots &hs)
void signal_connect (_signal_base< sigslot::multi_threaded_local > *sender)
void signal_disconnect (_signal_base< sigslot::multi_threaded_local > *sender)
virtual ~has_slots ()
void disconnect_all ()
Private Attributes
ogzstream output_file
Output file.
Additional Inherited Members
Static Public Member Functions inherited from Jetscape::JetScapeModuleBase
static int GetCurrentEvent ()
static void IncrementCurrentEvent ()
Protected Attributes inherited from Jetscape::JetScapeWriter
string file_name_out
JetScapeEventHeader header
Detailed Description
Definition at line 25 of file JetScapeWriterAsciiGZ.h.
View newest version in sPHENIX GitHub at line 25 of file JetScapeWriterAsciiGZ.h
Constructor & Destructor Documentation
Jetscape::JetScapeWriterAsciiGZ::JetScapeWriterAsciiGZ () inline
Definition at line 30 of file JetScapeWriterAsciiGZ.h.
View newest version in sPHENIX GitHub at line 30 of file JetScapeWriterAsciiGZ.h
Jetscape::JetScapeWriterAsciiGZ::JetScapeWriterAsciiGZ (string m_file_name_out)
Definition at line 16 of file JetScapeWriterAsciiGZ.cc.
View newest version in sPHENIX GitHub at line 16 of file JetScapeWriterAsciiGZ.cc
References Jetscape::JetScapeWriter::SetOutputFileName().
Jetscape::JetScapeWriterAsciiGZ::~JetScapeWriterAsciiGZ () virtual
Definition at line 21 of file JetScapeWriterAsciiGZ.cc.
View newest version in sPHENIX GitHub at line 21 of file JetScapeWriterAsciiGZ.cc
References Close(), and Jetscape::JetScapeTask::GetActive().
Member Function Documentation
void Jetscape::JetScapeWriterAsciiGZ::Close () inline virtual
Reimplemented from Jetscape::JetScapeWriter.
Definition at line 38 of file JetScapeWriterAsciiGZ.h.
View newest version in sPHENIX GitHub at line 38 of file JetScapeWriterAsciiGZ.h
References gzstreambase::close(), and output_file.
Referenced by ~JetScapeWriterAsciiGZ().
void Jetscape::JetScapeWriterAsciiGZ::Exec () virtual
A virtual function to define a default Exec() function for a JetScapeModuleBase. It can be overridden by different modules/tasks.
Reimplemented from Jetscape::JetScapeModuleBase.
Definition at line 103 of file JetScapeWriterAsciiGZ.cc.
View newest version in sPHENIX GitHub at line 103 of file JetScapeWriterAsciiGZ.cc
bool Jetscape::JetScapeWriterAsciiGZ::GetStatus () inline virtual
Implements Jetscape::JetScapeWriter.
Definition at line 37 of file JetScapeWriterAsciiGZ.h.
View newest version in sPHENIX GitHub at line 37 of file JetScapeWriterAsciiGZ.h
References output_file.
void Jetscape::JetScapeWriterAsciiGZ::Init () virtual
A virtual function for a default initialization of a JetScapeModuleBase. It also checks whether a XML file is loaded or not.
Reimplemented from Jetscape::JetScapeModuleBase.
Definition at line 94 of file JetScapeWriterAsciiGZ.cc.
View newest version in sPHENIX GitHub at line 94 of file JetScapeWriterAsciiGZ.cc
References Jetscape::JetScapeTask::GetActive(), Jetscape::JetScapeWriter::GetOutputFileName(), Acts::Logging::INFO, ogzstream::open(), and output_file.
void Jetscape::JetScapeWriterAsciiGZ::Write (weak_ptr< PartonShower > ps) virtual
Reimplemented from Jetscape::JetScapeWriter.
Definition at line 63 of file JetScapeWriterAsciiGZ.cc.
View newest version in sPHENIX GitHub at line 63 of file JetScapeWriterAsciiGZ.cc
References to_string(), WriteComment(), and WriteWhiteSpace().
Referenced by WriteHeaderToFile().
void Jetscape::JetScapeWriterAsciiGZ::Write (weak_ptr< Parton > p) virtual
Reimplemented from Jetscape::JetScapeWriter.
Definition at line 47 of file JetScapeWriterAsciiGZ.cc.
View newest version in sPHENIX GitHub at line 47 of file JetScapeWriterAsciiGZ.cc
References output_file.
void Jetscape::JetScapeWriterAsciiGZ::Write (weak_ptr< Vertex > v) virtual
Reimplemented from Jetscape::JetScapeWriter.
Definition at line 55 of file JetScapeWriterAsciiGZ.cc.
View newest version in sPHENIX GitHub at line 55 of file JetScapeWriterAsciiGZ.cc
References output_file.
void Jetscape::JetScapeWriterAsciiGZ::Write (weak_ptr< Hadron > h) virtual
Reimplemented from Jetscape::JetScapeWriter.
Definition at line 86 of file JetScapeWriterAsciiGZ.cc.
View newest version in sPHENIX GitHub at line 86 of file JetScapeWriterAsciiGZ.cc
References output_file.
void Jetscape::JetScapeWriterAsciiGZ::Write (string s) inline virtual
Reimplemented from Jetscape::JetScapeWriter.
Definition at line 46 of file JetScapeWriterAsciiGZ.h.
View newest version in sPHENIX GitHub at line 46 of file JetScapeWriterAsciiGZ.h
References output_file.
void Jetscape::JetScapeWriterAsciiGZ::WriteComment (string s) inline virtual
Reimplemented from Jetscape::JetScapeWriter.
Definition at line 47 of file JetScapeWriterAsciiGZ.h.
View newest version in sPHENIX GitHub at line 47 of file JetScapeWriterAsciiGZ.h
References output_file.
Referenced by Write(), and WriteHeaderToFile().
void Jetscape::JetScapeWriterAsciiGZ::WriteEvent () virtual
Gets called last, after all tasks have written themselves.
Reimplemented from Jetscape::JetScapeWriter.
Definition at line 41 of file JetScapeWriterAsciiGZ.cc.
View newest version in sPHENIX GitHub at line 41 of file JetScapeWriterAsciiGZ.cc
void Jetscape::JetScapeWriterAsciiGZ::WriteHeaderToFile () virtual
Gets called first, before all tasks write themselves.
Reimplemented from Jetscape::JetScapeWriter.
Definition at line 27 of file JetScapeWriterAsciiGZ.cc.
View newest version in sPHENIX GitHub at line 27 of file JetScapeWriterAsciiGZ.cc
References Jetscape::JetScapeModuleBase::GetCurrentEvent(), Jetscape::JetScapeEventHeader::GetEventWeight(), Jetscape::JetScapeWriter::GetHeader(), Jetscape::JetScapeTask::GetId(), Jetscape::JetScapeEventHeader::GetSigmaErr(), Jetscape::JetScapeEventHeader::GetSigmaGen(), Acts::Logging::INFO, to_string(), Write(), and WriteComment().
void Jetscape::JetScapeWriterAsciiGZ::WriteWhiteSpace (string s) inline virtual
Reimplemented from Jetscape::JetScapeWriter.
Definition at line 48 of file JetScapeWriterAsciiGZ.h.
View newest version in sPHENIX GitHub at line 48 of file JetScapeWriterAsciiGZ.h
References output_file.
Referenced by Write().
Member Data Documentation
ogzstream Jetscape::JetScapeWriterAsciiGZ::output_file private
Output file.
Definition at line 53 of file JetScapeWriterAsciiGZ.h.
View newest version in sPHENIX GitHub at line 53 of file JetScapeWriterAsciiGZ.h
Referenced by Close(), GetStatus(), Init(), Write(), WriteComment(), and WriteWhiteSpace().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/jail/JetScapeWriterAsciiGZ.h
JETSCAPE/blob/main/jail/JetScapeWriterAsciiGZ.cc