Analysis Software: PHSiliconTruthTrackSeeding Class Reference
PHSiliconTruthTrackSeeding Class Reference
Vertexing using truth info.
#include <coresoftware/blob/master/offline/packages/trackreco/PHSiliconTruthTrackSeeding.h>
Public Member Functions
PHSiliconTruthTrackSeeding (const std::string &name="PHSiliconTruthTrackSeeding")
unsigned int get_min_clusters_per_track () const
void set_min_clusters_per_track (unsigned int minClustersPerTrack)
void set_min_layer (unsigned int minLayer)
void set_max_layer (unsigned int maxLayer)
double get_min_momentum () const
minimal truth momentum cut
void set_min_momentum (double m)
minimal truth momentum cut
Public Member Functions inherited from PHTrackSeeding
PHTrackSeeding (const std::string &name="PHTrackSeeding")
~PHTrackSeeding () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_track_map_name (const std::string &map_name)
void set_do_hit_association (bool do_assoc)
void SetUseTruthClusters (bool setit)
void SetIteration (int iter)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int Setup (PHCompositeNode *topNode) override
int Process (PHCompositeNode *topNode) override
int End () override
Called in SubsysReco::End.
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
fetch node pointers
Private Attributes
PHG4TruthInfoContainer * _g4truth_container = nullptr
PHG4HitContainer * phg4hits_tpc = nullptr
PHG4HitContainer * phg4hits_intt = nullptr
PHG4HitContainer * phg4hits_mvtx = nullptr
PHG4HitContainer * phg4hits_micromegas = nullptr
TrkrHitTruthAssoc * hittruthassoc = nullptr
TrkrClusterHitAssoc * clusterhitassoc = nullptr
unsigned int _min_clusters_per_track = 2
unsigned int _min_layer = 0
unsigned int _max_layer = 6
double _min_momentum = 50e-3
minimal truth momentum cut (GeV)
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Attributes inherited from PHTrackSeeding
TrkrClusterContainer * _cluster_map = nullptr
TrkrClusterHitAssoc * _cluster_hit_map = nullptr
TrkrClusterIterationMapv1 * _iteration_map
int _n_iteration
bool do_hit_assoc = true
SvtxVertexMap * _vertex_map = nullptr
TrackSeedContainer * _track_map = nullptr
TrkrHitSetContainer * _hitsets = nullptr
std::string _track_map_name = "TpcTrackSeedContainer"
bool _use_truth_clusters = false
Detailed Description
Vertexing using truth info.
Definition at line 27 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 27 of file PHSiliconTruthTrackSeeding.h
Constructor & Destructor Documentation
PHSiliconTruthTrackSeeding::PHSiliconTruthTrackSeeding (const std::string & name = "PHSiliconTruthTrackSeeding")
Definition at line 52 of file PHSiliconTruthTrackSeeding.cc.
View newest version in sPHENIX GitHub at line 52 of file PHSiliconTruthTrackSeeding.cc
Member Function Documentation
int PHSiliconTruthTrackSeeding::End () override protected virtual
Called in SubsysReco::End.
Implements PHTrackSeeding.
Definition at line 425 of file PHSiliconTruthTrackSeeding.cc.
View newest version in sPHENIX GitHub at line 425 of file PHSiliconTruthTrackSeeding.cc
unsigned int PHSiliconTruthTrackSeeding::get_min_clusters_per_track () const inline
Definition at line 32 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 32 of file PHSiliconTruthTrackSeeding.h
References _min_clusters_per_track.
double PHSiliconTruthTrackSeeding::get_min_momentum () const inline
minimal truth momentum cut
Definition at line 53 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 53 of file PHSiliconTruthTrackSeeding.h
References _min_momentum.
int PHSiliconTruthTrackSeeding::GetNodes (PHCompositeNode * topNode) private
fetch node pointers
Definition at line 371 of file PHSiliconTruthTrackSeeding.cc.
View newest version in sPHENIX GitHub at line 371 of file PHSiliconTruthTrackSeeding.cc
References _g4truth_container, Fun4AllReturnCodes::ABORTEVENT, clusterhitassoc, Fun4AllReturnCodes::EVENT_OK, hittruthassoc, phg4hits_intt, phg4hits_micromegas, phg4hits_mvtx, phg4hits_tpc, and PHWHERE.
int PHSiliconTruthTrackSeeding::Process (PHCompositeNode * topNode) override protected virtual
process event interface for trackers, called in process_event. implemented in derived classes
Implements PHTrackSeeding.
Definition at line 78 of file PHSiliconTruthTrackSeeding.cc.
View newest version in sPHENIX GitHub at line 78 of file PHSiliconTruthTrackSeeding.cc
References PHTrackSeeding::_cluster_map, _g4truth_container, _min_clusters_per_track, _min_momentum, PHTrackSeeding::_track_map, PHTrackSeeding::_vertex_map, TrackSeedContainer::begin(), charge(), clusterhitassoc, TrackSeedContainer::end(), eta, Fun4AllReturnCodes::EVENT_OK, TrkrClusterContainer::findCluster(), PHG4HitContainer::findHit(), SvtxVertexMap::get(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4Hit::get_trkid(), PHG4Particle::get_vtx_id(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), TrkrClusterContainer::getClusters(), TrkrHitTruthAssoc::getG4Hits(), TrkrClusterHitAssoc::getHits(), TrkrDefs::getHitSetKeyFromClusKey(), TrkrClusterContainer::getHitSetKeys(), TrkrDefs::getLayer(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetPrimaryVtxRange(), TrkrDefs::getTrkrId(), TrkrCluster::getX(), TrkrCluster::getY(), hittruthassoc, PHG4Particle::identify(), SvtxVertexMap::identify(), TrackSeedContainer::identify(), TrackSeedContainer::insert(), TrkrDefs::inttId, PHG4TruthInfoContainer::isEmbeded(), PHG4TruthInfoContainer::isEmbededVtx(), it, layer, TrkrDefs::mvtxId, particle, phg4hits_intt, phg4hits_mvtx, PHWHERE, physmon_track_finding_ttbar::pt, TrackSeedContainer::size(), square(), ActsTests::PropagationDatasets::theta, and Fun4AllBase::Verbosity().
void PHSiliconTruthTrackSeeding::set_max_layer (unsigned int maxLayer) inline
Definition at line 47 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 47 of file PHSiliconTruthTrackSeeding.h
References _max_layer.
void PHSiliconTruthTrackSeeding::set_min_clusters_per_track (unsigned int minClustersPerTrack) inline
Definition at line 37 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 37 of file PHSiliconTruthTrackSeeding.h
References _min_clusters_per_track.
void PHSiliconTruthTrackSeeding::set_min_layer (unsigned int minLayer) inline
Definition at line 42 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 42 of file PHSiliconTruthTrackSeeding.h
References _min_layer.
void PHSiliconTruthTrackSeeding::set_min_momentum (double m) inline
minimal truth momentum cut
Definition at line 59 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 59 of file PHSiliconTruthTrackSeeding.h
References _min_momentum, and Acts::UnitConstants::m.
int PHSiliconTruthTrackSeeding::Setup (PHCompositeNode * topNode) override protected virtual
setup interface for trackers, called in InitRun, setup things like pointers to nodes. overrided in derived classes
Reimplemented from PHTrackSeeding.
Definition at line 60 of file PHSiliconTruthTrackSeeding.cc.
View newest version in sPHENIX GitHub at line 60 of file PHSiliconTruthTrackSeeding.cc
References Fun4AllReturnCodes::EVENT_OK, PHTrackSeeding::set_track_map_name(), PHTrackSeeding::Setup(), and Fun4AllBase::Verbosity().
Member Data Documentation
PHG4TruthInfoContainer* PHSiliconTruthTrackSeeding::_g4truth_container = nullptr private
Definition at line 75 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 75 of file PHSiliconTruthTrackSeeding.h
Referenced by GetNodes(), and Process().
unsigned int PHSiliconTruthTrackSeeding::_max_layer = 6 private
Definition at line 87 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 87 of file PHSiliconTruthTrackSeeding.h
Referenced by set_max_layer().
unsigned int PHSiliconTruthTrackSeeding::_min_clusters_per_track = 2 private
Definition at line 85 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 85 of file PHSiliconTruthTrackSeeding.h
Referenced by get_min_clusters_per_track(), Process(), and set_min_clusters_per_track().
unsigned int PHSiliconTruthTrackSeeding::_min_layer = 0 private
Definition at line 86 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 86 of file PHSiliconTruthTrackSeeding.h
Referenced by set_min_layer().
double PHSiliconTruthTrackSeeding::_min_momentum = 50e-3 private
minimal truth momentum cut (GeV)
Definition at line 90 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 90 of file PHSiliconTruthTrackSeeding.h
Referenced by get_min_momentum(), Process(), and set_min_momentum().
TrkrClusterHitAssoc* PHSiliconTruthTrackSeeding::clusterhitassoc = nullptr private
Definition at line 83 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 83 of file PHSiliconTruthTrackSeeding.h
Referenced by GetNodes(), and Process().
TrkrHitTruthAssoc* PHSiliconTruthTrackSeeding::hittruthassoc = nullptr private
Definition at line 82 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 82 of file PHSiliconTruthTrackSeeding.h
Referenced by GetNodes(), and Process().
PHG4HitContainer* PHSiliconTruthTrackSeeding::phg4hits_intt = nullptr private
Definition at line 78 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 78 of file PHSiliconTruthTrackSeeding.h
Referenced by GetNodes(), and Process().
PHG4HitContainer* PHSiliconTruthTrackSeeding::phg4hits_micromegas = nullptr private
Definition at line 80 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 80 of file PHSiliconTruthTrackSeeding.h
Referenced by GetNodes().
PHG4HitContainer* PHSiliconTruthTrackSeeding::phg4hits_mvtx = nullptr private
Definition at line 79 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 79 of file PHSiliconTruthTrackSeeding.h
Referenced by GetNodes(), and Process().
PHG4HitContainer* PHSiliconTruthTrackSeeding::phg4hits_tpc = nullptr private
Definition at line 77 of file PHSiliconTruthTrackSeeding.h.
View newest version in sPHENIX GitHub at line 77 of file PHSiliconTruthTrackSeeding.h
Referenced by GetNodes().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHSiliconTruthTrackSeeding.h
coresoftware/blob/master/offline/packages/trackreco/PHSiliconTruthTrackSeeding.cc