Analysis Software: Hydro Class Reference
Hydro Class Reference
#include <JETSCAPE/blob/main/jail/vhlle/src/hdo.h>
Public Member Functions
Hydro (Fluid *_f, EoS *_eos, TransportCoeff *_trcoeff, double _t0, double _dt)
~Hydro ()
void setDtau (double deltaTau)
void hlle_flux (Cell *left, Cell *right, int direction, int mode)
void visc_flux (Cell *left, Cell *right, int direction)
void visc_source_step (int ix, int iy, int iz)
void source (double tau, double x, double y, double z, double e, double p, double nb, double nq, double ns, double vx, double vy, double vz, double S[7])
void source_step (int ix, int iy, int iz, int mode)
void NSquant (int ix, int iy, int iz, double pi[][4], double &Pi, double dmu[4][4], double &du)
void setNSvalues ()
void ISformal ()
void performStep (void)
double getTau ()
Private Attributes
Fluid * f
EoS * eos
TransportCoeff * trcoeff
double dt
double tau
double tau_z
Detailed Description
Definition at line 9 of file hdo.h.
View newest version in sPHENIX GitHub at line 9 of file hdo.h
Constructor & Destructor Documentation
Hydro::Hydro (Fluid * _f, EoS * _eos, TransportCoeff * _trcoeff, double _t0, double _dt)
Definition at line 52 of file hdo.cpp.
View newest version in sPHENIX GitHub at line 52 of file hdo.cpp
References eos, f, tau, and trcoeff.
Hydro::~Hydro ()
Definition at line 61 of file hdo.cpp.
View newest version in sPHENIX GitHub at line 61 of file hdo.cpp
Member Function Documentation
double Hydro::getTau () inline
Definition at line 52 of file hdo.h.
View newest version in sPHENIX GitHub at line 52 of file hdo.h
References tau.
Referenced by getenergyhlle_(), getvalueshlle_(), initoutputhlle_(), main(), and makestephlle_().
void Hydro::hlle_flux (Cell * left, Cell * right, int direction, int mode)
Definition at line 73 of file hdo.cpp.
View newest version in sPHENIX GitHub at line 73 of file hdo.cpp
References Cell::addFlux(), EoS::cs(), EoS::cs2(), debugRiemann, Cell::Dump(), eos, f, Fluid::getDx(), Fluid::getDy(), Fluid::getDz(), Cell::getM(), Cell::getPrimVarHLeft(), Cell::getPrimVarHRight(), Cell::getPrimVarLeft(), Cell::getPrimVarRight(), Acts::UnitConstants::min, NB_, NQ_, NS_, PREDICT, T_, tau, X_, Y_, and Z_.
void Hydro::ISformal ()
Definition at line 608 of file hdo.cpp.
View newest version in sPHENIX GitHub at line 608 of file hdo.cpp
References Cell::addFlux(), Cell::addpi0(), Cell::addPi0(), Cell::addpiH0(), Cell::addPiH0(), Acts::PhysicalConstants::c, Acts::UnitConstants::e, eos, EoS::eos(), f, Fluid::getCell(), Fluid::getDx(), Fluid::getDy(), Fluid::getDz(), Fluid::getNX(), Fluid::getNY(), Fluid::getNZ(), Cell::getpi(), Cell::getPi(), Cell::getpi0(), Cell::getPi0(), Cell::getpiH0(), Cell::getPiH0(), Cell::getPrimVarHCenter(), TransportCoeff::getTau(), i, j, k, Acts::UnitConstants::ns, merge_hashes::p, pi, Cell::setpi(), Cell::setPi(), Cell::setpi0(), Cell::setPi0(), Cell::setpiH(), Cell::setPiH(), Cell::setpiH0(), Cell::setPiH0(), Cell::setViscCorrCutFlag(), sign(), Acts::UnitConstants::T, tau, trcoeff, physmon_ckf_tracking::u, vx, vy, and vz.
void Hydro::NSquant (int ix, int iy, int iz, double pi[][4], double & Pi, double dmu[4][4], double & du)
Definition at line 374 of file hdo.cpp.
View newest version in sPHENIX GitHub at line 374 of file hdo.cpp
References Acts::PhysicalConstants::c, dy, dz, Acts::UnitConstants::e, eos, EoS::eos(), etaS, f, Fluid::getCell(), Fluid::getDx(), Fluid::getDy(), Fluid::getDz(), TransportCoeff::getEta(), Cell::getMaxM(), Cell::getNext(), Cell::getPrev(), Cell::getPrimVar(), Cell::getPrimVarHCenter(), Cell::getPrimVarPrev(), i, j, k, CKF_timing_vs_mu::mu, Acts::UnitConstants::ns, merge_hashes::p, rho, physmon_simulation::s, EoS::s(), Acts::UnitConstants::T, tau, trcoeff, X_, Y_, SVM_v1::Z, and zetaS.
void Hydro::performStep (void)
Definition at line 891 of file hdo.cpp.
View newest version in sPHENIX GitHub at line 891 of file hdo.cpp
References Acts::PhysicalConstants::c, Cell::clearFlux(), CORRECT, Fluid::correctImagCells(), Fluid::correctImagCellsFull(), debugRiemann, f, Fluid::getCell(), Fluid::getNX(), Fluid::getNY(), Fluid::getNZ(), TransportCoeff::isViscous(), PREDICT, Cell::saveQprev(), tau, trcoeff, Cell::updateByFlux(), Fluid::updateM(), Cell::updateQtoQhByFlux(), X_, Y_, and Z_.
Referenced by main(), and makestephlle_().
void Hydro::setDtau (double deltaTau)
Definition at line 63 of file hdo.cpp.
View newest version in sPHENIX GitHub at line 63 of file hdo.cpp
References f, Fluid::getDx(), Fluid::getDy(), Fluid::getDz(), and tau.
Referenced by dtauhlle_(), and main().
void Hydro::setNSvalues ()
Definition at line 579 of file hdo.cpp.
View newest version in sPHENIX GitHub at line 579 of file hdo.cpp
References Acts::PhysicalConstants::c, Acts::UnitConstants::e, eos, EoS::eos(), etaS, f, Fluid::getCell(), TransportCoeff::getEta(), Fluid::getNX(), Fluid::getNY(), Fluid::getNZ(), Cell::getPrimVar(), i, j, Acts::UnitConstants::ns, merge_hashes::p, physmon_simulation::s, EoS::s(), Cell::setpi(), Cell::setPi(), Acts::UnitConstants::T, tau, trcoeff, vx, vy, vz, and zetaS.
Referenced by inithydrohlle_(), and main().
void Hydro::source (double tau, double x, double y, double z, double e, double p, double nb, double nq, double ns, double vx, double vy, double vz, double S[7])
Definition at line 300 of file hdo.cpp.
View newest version in sPHENIX GitHub at line 300 of file hdo.cpp
References NB_, NQ_, NS_, Q(), T_, transformCV(), vz, X_, Y_, and Z_.
void Hydro::source_step (int ix, int iy, int iz, int mode)
Definition at line 314 of file hdo.cpp.
View newest version in sPHENIX GitHub at line 314 of file hdo.cpp
References Cell::addFlux(), Acts::PhysicalConstants::c, Acts::UnitConstants::e, eos, f, Fluid::getCell(), Cell::getPrimVar(), Cell::getPrimVarHCenter(), Fluid::getX(), Fluid::getY(), Fluid::getZ(), i, k, NB_, NQ_, Acts::UnitConstants::ns, NS_, merge_hashes::p, PREDICT, parse_cmake_options::source, T_, tau, vx, vy, vz, ambiguity_solver_full_chain::x, X_, y, Y_, physmon_track_finding_ttbar::z, and Z_.
void Hydro::visc_flux (Cell * left, Cell * right, int direction)
Definition at line 841 of file hdo.cpp.
View newest version in sPHENIX GitHub at line 841 of file hdo.cpp
References Cell::addFlux(), Acts::UnitConstants::e, eos, f, Fluid::getDx(), Fluid::getDy(), Fluid::getDz(), Cell::getM(), Cell::getpiH(), Cell::getPiH(), Cell::getPrimVarHCenter(), i, Acts::UnitConstants::ns, merge_hashes::p, T_, tau, testSigmaEff::v, X_, Y_, and Z_.
void Hydro::visc_source_step (int ix, int iy, int iz)
Definition at line 346 of file hdo.cpp.
View newest version in sPHENIX GitHub at line 346 of file hdo.cpp
References Cell::addFlux(), Acts::PhysicalConstants::c, Acts::UnitConstants::e, eos, f, Fluid::getCell(), Cell::getpiH(), Cell::getPiH(), Cell::getPrimVarHCenter(), i, k, Acts::UnitConstants::ns, merge_hashes::p, T_, tau, vx, vy, vz, X_, Y_, and Z_.
Member Data Documentation
double Hydro::dt private
Definition at line 14 of file hdo.h.
View newest version in sPHENIX GitHub at line 14 of file hdo.h
EoS* Hydro::eos private
Definition at line 12 of file hdo.h.
View newest version in sPHENIX GitHub at line 12 of file hdo.h
Fluid* Hydro::f private
Definition at line 11 of file hdo.h.
View newest version in sPHENIX GitHub at line 11 of file hdo.h
Referenced by KFParticleBaseSIMD::SetNoDecayLength().
double Hydro::tau private
Definition at line 14 of file hdo.h.
View newest version in sPHENIX GitHub at line 14 of file hdo.h
Referenced by getTau().
double Hydro::tau_z private
Definition at line 15 of file hdo.h.
View newest version in sPHENIX GitHub at line 15 of file hdo.h
TransportCoeff* Hydro::trcoeff private
Definition at line 13 of file hdo.h.
View newest version in sPHENIX GitHub at line 13 of file hdo.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/jail/vhlle/src/hdo.h
JETSCAPE/blob/main/jail/vhlle/src/hdo.cpp