Analysis Software: HelixHoughSpace_v1 Class Reference
HelixHoughSpace_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/HelixHoughSpace_v1.h>
Public Member Functions
HelixHoughSpace_v1 ()
HelixHoughSpace_v1 (const HelixHoughSpace_v1 &hough_space)
~HelixHoughSpace_v1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void add_one_zoom (std::vector< unsigned int > &one_zoom) override
unsigned int get_max_zoom () override
void print_zoom_profile () override
void print_para_range () override
void set_kappa_min (float kappa_min) override
float get_kappa_min () const override
void set_kappa_max (float kappa_max) override
float get_kappa_max () const override
void set_phi_min (float phi_min) override
float get_phi_min () const override
void set_phi_max (float phi_max) override
float get_phi_max () const override
void set_d_min (float d_min) override
float get_d_min () const override
void set_d_max (float d_max) override
float get_d_max () const override
void set_dzdl_min (float dzdl_min) override
float get_dzdl_min () const override
void set_dzdl_max (float dzdl_max) override
float get_dzdl_max () const override
void set_z0_min (float z0_min) override
float get_z0_min () const override
void set_z0_max (float z0_max) override
float get_z0_max () const override
unsigned int get_n_kappa_bins (unsigned int zoomlevel) const override
unsigned int get_n_phi_bins (unsigned int zoomlevel) const override
unsigned int get_n_d_bins (unsigned int zoomlevel) const override
unsigned int get_n_dzdl_bins (unsigned int zoomlevel) const override
unsigned int get_n_z0_bins (unsigned int zoomlevel) const override
float get_kappa_bin_size (unsigned int zoomlevel) const override
float get_phi_bin_size (unsigned int zoomlevel) const override
float get_d_bin_size (unsigned int zoomlevel) const override
float get_dzdl_bin_size (unsigned int zoomlevel) const override
float get_z0_bin_size (unsigned int zoomlevel) const override
unsigned int get_kappa_bin (unsigned int zoomlevel, float kappa) const override
unsigned int get_phi_bin (unsigned int zoomlevel, float phi) const override
unsigned int get_d_bin (unsigned int zoomlevel, float d) const override
unsigned int get_dzdl_bin (unsigned int zoomlevel, float dzdl) const override
unsigned int get_z0_bin (unsigned int zoomlevel, float z0) const override
unsigned int get_bin (unsigned int zoomlevel, unsigned int *bins) const override
Public Member Functions inherited from HelixHoughSpace
~HelixHoughSpace () override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
float _para_min [5]
float _para_max [5]
unsigned int _zoom_profile [ZOOMLEVEL_MAX][5]
unsigned int _max_zoom
Additional Inherited Members
Protected Member Functions inherited from HelixHoughSpace
HelixHoughSpace ()=default
ClassDefOverride (HelixHoughSpace, 1)
Detailed Description
Definition at line 11 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 11 of file HelixHoughSpace_v1.h
Constructor & Destructor Documentation
HelixHoughSpace_v1::HelixHoughSpace_v1 ()
Definition at line 5 of file HelixHoughSpace_v1.cc.
View newest version in sPHENIX GitHub at line 5 of file HelixHoughSpace_v1.cc
References _max_zoom, _para_max, _para_min, _zoom_profile, i, j, and ZOOMLEVEL_MAX.
Referenced by CloneMe().
HelixHoughSpace_v1::HelixHoughSpace_v1 (const HelixHoughSpace_v1 & hough_space)
Definition at line 24 of file HelixHoughSpace_v1.cc.
View newest version in sPHENIX GitHub at line 24 of file HelixHoughSpace_v1.cc
HelixHoughSpace_v1::~HelixHoughSpace_v1 () inline override
Definition at line 17 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 17 of file HelixHoughSpace_v1.h
Member Function Documentation
void HelixHoughSpace_v1::add_one_zoom (std::vector< unsigned int > & one_zoom) override virtual
Reimplemented from HelixHoughSpace.
Definition at line 29 of file HelixHoughSpace_v1.cc.
View newest version in sPHENIX GitHub at line 29 of file HelixHoughSpace_v1.cc
References _max_zoom, and _zoom_profile.
PHObject* HelixHoughSpace_v1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from HelixHoughSpace.
Definition at line 24 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 24 of file HelixHoughSpace_v1.h
References HelixHoughSpace_v1().
unsigned int HelixHoughSpace_v1::get_bin (unsigned int zoomlevel, unsigned int * bins) const override virtual
Reimplemented from HelixHoughSpace.
Definition at line 230 of file HelixHoughSpace_v1.cc.
View newest version in sPHENIX GitHub at line 230 of file HelixHoughSpace_v1.cc
References _zoom_profile, get_n_d_bins(), get_n_dzdl_bins(), get_n_kappa_bins(), get_n_phi_bins(), and get_n_z0_bins().
unsigned int HelixHoughSpace_v1::get_d_bin (unsigned int zoomlevel, float d) const override virtual
Reimplemented from HelixHoughSpace.
Definition at line 191 of file HelixHoughSpace_v1.cc.
View newest version in sPHENIX GitHub at line 191 of file HelixHoughSpace_v1.cc
References get_d_bin_size(), get_d_min(), and i.
float HelixHoughSpace_v1::get_d_bin_size (unsigned int zoomlevel) const override virtual
Reimplemented from HelixHoughSpace.
Definition at line 94 of file HelixHoughSpace_v1.cc.
View newest version in sPHENIX GitHub at line 94 of file HelixHoughSpace_v1.cc
References _para_max, _para_min, and _zoom_profile.
Referenced by get_d_bin().
float HelixHoughSpace_v1::get_d_max () const inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 42 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 42 of file HelixHoughSpace_v1.h
References _para_max.
float HelixHoughSpace_v1::get_d_min () const inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 40 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 40 of file HelixHoughSpace_v1.h
References _para_min.
Referenced by get_d_bin().
unsigned int HelixHoughSpace_v1::get_dzdl_bin (unsigned int zoomlevel, float dzdl) const override virtual
Reimplemented from HelixHoughSpace.
Definition at line 201 of file HelixHoughSpace_v1.cc.
View newest version in sPHENIX GitHub at line 201 of file HelixHoughSpace_v1.cc
References get_dzdl_bin_size(), get_dzdl_min(), get_n_dzdl_bins(), and i.
float HelixHoughSpace_v1::get_dzdl_bin_size (unsigned int zoomlevel) const override virtual
Reimplemented from HelixHoughSpace.
Definition at line 103 of file HelixHoughSpace_v1.cc.
View newest version in sPHENIX GitHub at line 103 of file HelixHoughSpace_v1.cc
References _para_max, _para_min, and _zoom_profile.
Referenced by get_dzdl_bin().
float HelixHoughSpace_v1::get_dzdl_max () const inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 46 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 46 of file HelixHoughSpace_v1.h
References _para_max.
float HelixHoughSpace_v1::get_dzdl_min () const inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 44 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 44 of file HelixHoughSpace_v1.h
References _para_min.
Referenced by get_dzdl_bin().
unsigned int HelixHoughSpace_v1::get_kappa_bin (unsigned int zoomlevel, float kappa) const override virtual
Reimplemented from HelixHoughSpace.
Definition at line 166 of file HelixHoughSpace_v1.cc.
View newest version in sPHENIX GitHub at line 166 of file HelixHoughSpace_v1.cc
References get_kappa_bin_size(), get_kappa_min(), and i.
float HelixHoughSpace_v1::get_kappa_bin_size (unsigned int zoomlevel) const override virtual
Reimplemented from HelixHoughSpace.
Definition at line 76 of file HelixHoughSpace_v1.cc.
View newest version in sPHENIX GitHub at line 76 of file HelixHoughSpace_v1.cc
References _para_max, _para_min, and _zoom_profile.
Referenced by get_kappa_bin().
float HelixHoughSpace_v1::get_kappa_max () const inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 34 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 34 of file HelixHoughSpace_v1.h
References _para_max.
float HelixHoughSpace_v1::get_kappa_min () const inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 32 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 32 of file HelixHoughSpace_v1.h
References _para_min.
Referenced by get_kappa_bin().
unsigned int HelixHoughSpace_v1::get_max_zoom () override virtual
Reimplemented from HelixHoughSpace.
Definition at line 42 of file HelixHoughSpace_v1.cc.
View newest version in sPHENIX GitHub at line 42 of file HelixHoughSpace_v1.cc
References _max_zoom.
unsigned int HelixHoughSpace_v1::get_n_d_bins (unsigned int zoomlevel) const inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 54 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 54 of file HelixHoughSpace_v1.h
References _zoom_profile.
Referenced by get_bin().
unsigned int HelixHoughSpace_v1::get_n_dzdl_bins (unsigned int zoomlevel) const inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 55 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 55 of file HelixHoughSpace_v1.h
References _zoom_profile.
Referenced by get_bin(), and get_dzdl_bin().
unsigned int HelixHoughSpace_v1::get_n_kappa_bins (unsigned int zoomlevel) const inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 52 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 52 of file HelixHoughSpace_v1.h
References _zoom_profile.
Referenced by get_bin().
unsigned int HelixHoughSpace_v1::get_n_phi_bins (unsigned int zoomlevel) const inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 53 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 53 of file HelixHoughSpace_v1.h
References _zoom_profile.
Referenced by get_bin().
unsigned int HelixHoughSpace_v1::get_n_z0_bins (unsigned int zoomlevel) const inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 56 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 56 of file HelixHoughSpace_v1.h
References _zoom_profile.
Referenced by get_bin().
unsigned int HelixHoughSpace_v1::get_phi_bin (unsigned int zoomlevel, float phi) const override virtual
Reimplemented from HelixHoughSpace.
Definition at line 176 of file HelixHoughSpace_v1.cc.
View newest version in sPHENIX GitHub at line 176 of file HelixHoughSpace_v1.cc
References get_phi_bin_size(), get_phi_min(), and i.
float HelixHoughSpace_v1::get_phi_bin_size (unsigned int zoomlevel) const override virtual
Reimplemented from HelixHoughSpace.
Definition at line 85 of file HelixHoughSpace_v1.cc.
View newest version in sPHENIX GitHub at line 85 of file HelixHoughSpace_v1.cc
References _para_max, _para_min, and _zoom_profile.
Referenced by get_phi_bin().
float HelixHoughSpace_v1::get_phi_max () const inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 38 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 38 of file HelixHoughSpace_v1.h
References _para_max.
float HelixHoughSpace_v1::get_phi_min () const inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 36 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 36 of file HelixHoughSpace_v1.h
References _para_min.
Referenced by get_phi_bin().
unsigned int HelixHoughSpace_v1::get_z0_bin (unsigned int zoomlevel, float z0) const override virtual
Reimplemented from HelixHoughSpace.
Definition at line 221 of file HelixHoughSpace_v1.cc.
View newest version in sPHENIX GitHub at line 221 of file HelixHoughSpace_v1.cc
References get_z0_bin_size(), and i.
float HelixHoughSpace_v1::get_z0_bin_size (unsigned int zoomlevel) const override virtual
Reimplemented from HelixHoughSpace.
Definition at line 112 of file HelixHoughSpace_v1.cc.
View newest version in sPHENIX GitHub at line 112 of file HelixHoughSpace_v1.cc
References _para_max, _para_min, and _zoom_profile.
Referenced by get_z0_bin().
float HelixHoughSpace_v1::get_z0_max () const inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 50 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 50 of file HelixHoughSpace_v1.h
References _para_max.
float HelixHoughSpace_v1::get_z0_min () const inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 48 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 48 of file HelixHoughSpace_v1.h
References _para_min.
void HelixHoughSpace_v1::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from HelixHoughSpace.
Definition at line 21 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 21 of file HelixHoughSpace_v1.h
int HelixHoughSpace_v1::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from HelixHoughSpace.
Definition at line 23 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 23 of file HelixHoughSpace_v1.h
void HelixHoughSpace_v1::print_para_range () override virtual
Reimplemented from HelixHoughSpace.
Definition at line 59 of file HelixHoughSpace_v1.cc.
View newest version in sPHENIX GitHub at line 59 of file HelixHoughSpace_v1.cc
References _para_max, and _para_min.
void HelixHoughSpace_v1::print_zoom_profile () override virtual
Reimplemented from HelixHoughSpace.
Definition at line 48 of file HelixHoughSpace_v1.cc.
View newest version in sPHENIX GitHub at line 48 of file HelixHoughSpace_v1.cc
References _max_zoom, _zoom_profile, i, and j.
void HelixHoughSpace_v1::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 22 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 22 of file HelixHoughSpace_v1.h
void HelixHoughSpace_v1::set_d_max (float d_max) inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 41 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 41 of file HelixHoughSpace_v1.h
References _para_max.
void HelixHoughSpace_v1::set_d_min (float d_min) inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 39 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 39 of file HelixHoughSpace_v1.h
References _para_min.
void HelixHoughSpace_v1::set_dzdl_max (float dzdl_max) inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 45 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 45 of file HelixHoughSpace_v1.h
References _para_max.
void HelixHoughSpace_v1::set_dzdl_min (float dzdl_min) inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 43 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 43 of file HelixHoughSpace_v1.h
References _para_min.
void HelixHoughSpace_v1::set_kappa_max (float kappa_max) inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 33 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 33 of file HelixHoughSpace_v1.h
References _para_max.
void HelixHoughSpace_v1::set_kappa_min (float kappa_min) inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 31 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 31 of file HelixHoughSpace_v1.h
References _para_min.
void HelixHoughSpace_v1::set_phi_max (float phi_max) inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 37 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 37 of file HelixHoughSpace_v1.h
References _para_max.
void HelixHoughSpace_v1::set_phi_min (float phi_min) inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 35 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 35 of file HelixHoughSpace_v1.h
References _para_min.
void HelixHoughSpace_v1::set_z0_max (float z0_max) inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 49 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 49 of file HelixHoughSpace_v1.h
References _para_max.
void HelixHoughSpace_v1::set_z0_min (float z0_min) inline override virtual
Reimplemented from HelixHoughSpace.
Definition at line 47 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 47 of file HelixHoughSpace_v1.h
References _para_min.
Member Data Documentation
unsigned int HelixHoughSpace_v1::_max_zoom private
Definition at line 84 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 84 of file HelixHoughSpace_v1.h
Referenced by add_one_zoom(), get_max_zoom(), HelixHoughSpace_v1(), and print_zoom_profile().
float HelixHoughSpace_v1::_para_max[5] private
Definition at line 81 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 81 of file HelixHoughSpace_v1.h
Referenced by get_d_bin_size(), get_d_max(), get_dzdl_bin_size(), get_dzdl_max(), get_kappa_bin_size(), get_kappa_max(), get_phi_bin_size(), get_phi_max(), get_z0_bin_size(), get_z0_max(), HelixHoughSpace_v1(), print_para_range(), set_d_max(), set_dzdl_max(), set_kappa_max(), set_phi_max(), and set_z0_max().
float HelixHoughSpace_v1::_para_min[5] private
Definition at line 80 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 80 of file HelixHoughSpace_v1.h
Referenced by get_d_bin_size(), get_d_min(), get_dzdl_bin_size(), get_dzdl_min(), get_kappa_bin_size(), get_kappa_min(), get_phi_bin_size(), get_phi_min(), get_z0_bin_size(), get_z0_min(), HelixHoughSpace_v1(), print_para_range(), set_d_min(), set_dzdl_min(), set_kappa_min(), set_phi_min(), and set_z0_min().
unsigned int HelixHoughSpace_v1::_zoom_profile[ZOOMLEVEL_MAX][5] private
Definition at line 83 of file HelixHoughSpace_v1.h.
View newest version in sPHENIX GitHub at line 83 of file HelixHoughSpace_v1.h
Referenced by add_one_zoom(), get_bin(), get_d_bin_size(), get_dzdl_bin_size(), get_kappa_bin_size(), get_n_d_bins(), get_n_dzdl_bins(), get_n_kappa_bins(), get_n_phi_bins(), get_n_z0_bins(), get_phi_bin_size(), get_z0_bin_size(), HelixHoughSpace_v1(), and print_zoom_profile().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/HelixHoughSpace_v1.h
coresoftware/blob/master/offline/packages/trackreco/HelixHoughSpace_v1.cc