Analysis Software: JETSCAPE/blob/main/examples/unittests/causal_liquifier.cc File Reference
causal_liquifier.cc File Reference
#include "CausalLiquefier.h"
#include "LiquefierBase.h"
#include "gtest/gtest.h"
#include <iostream>
Functions
TEST (CausalLiquifierTest, TEST_COORDINATES)
TEST (CausalLiquifierTest, TEST_CAUSALITY)
TEST (CausalLiquifierTest, TEST_CONSERVATION)
TEST (CausalLiquifierTest, TEST_GRID_CARTESIAN_CONSERVATION)
TEST (CausalLiquifierTest, TEST_GRID_TAU_ETA_CONSERVATION)
Function Documentation
TEST (CausalLiquifierTest , TEST_COORDINATES)
Definition at line 24 of file causal_liquifier.cc.
View newest version in sPHENIX GitHub at line 24 of file causal_liquifier.cc
References eta, EXPECT_DOUBLE_EQ, Jetscape::CausalLiquefier::get_peta(), Jetscape::CausalLiquefier::get_ptau(), Jetscape::CausalLiquefier::get_t(), Jetscape::CausalLiquefier::get_z(), t, tau, and physmon_track_finding_ttbar::z.
TEST (CausalLiquifierTest , TEST_CAUSALITY)
Definition at line 52 of file causal_liquifier.cc.
View newest version in sPHENIX GitHub at line 52 of file causal_liquifier.cc
References Jetscape::CausalLiquefier::c_diff, Jetscape::CausalLiquefier::dtau, EXPECT_DOUBLE_EQ, Jetscape::CausalLiquefier::kernel_rho(), Jetscape::CausalLiquefier::rho_delta(), Jetscape::CausalLiquefier::rho_smooth(), Jetscape::CausalLiquefier::smearing_kernel(), Jetscape::CausalLiquefier::tau_delay, and Acts::Test::time.
TEST (CausalLiquifierTest , TEST_CONSERVATION)
Definition at line 84 of file causal_liquifier.cc.
View newest version in sPHENIX GitHub at line 84 of file causal_liquifier.cc
References EXPECT_NEAR, Jetscape::CausalLiquefier::kernel_rho(), physmon_track_finding_ttbar::r, and t.
TEST (CausalLiquifierTest , TEST_GRID_CARTESIAN_CONSERVATION)
Definition at line 104 of file causal_liquifier.cc.
View newest version in sPHENIX GitHub at line 104 of file causal_liquifier.cc
References double(), dy, dz, EXPECT_NEAR, i, Jetscape::CausalLiquefier::kernel_rho(), physmon_track_finding_ttbar::r, t, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
TEST (CausalLiquifierTest , TEST_GRID_TAU_ETA_CONSERVATION)
Definition at line 152 of file causal_liquifier.cc.
View newest version in sPHENIX GitHub at line 152 of file causal_liquifier.cc
References double(), dtau, dy, EXPECT_NEAR, n_eta, Jetscape::CausalLiquefier::set_t_delay(), Jetscape::CausalLiquefier::smearing_kernel(), and t.