Analysis Software: Acts::HomogeneousVolumeMaterial Class Reference
Acts::HomogeneousVolumeMaterial Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Material/HomogeneousVolumeMaterial.hpp>
Public Member Functions
HomogeneousVolumeMaterial (const Material &material)
HomogeneousVolumeMaterial (const HomogeneousVolumeMaterial &hvm)=default
HomogeneousVolumeMaterial (HomogeneousVolumeMaterial &&hvm)=default
~HomogeneousVolumeMaterial () override=default
Destructor.
HomogeneousVolumeMaterial & operator= (const HomogeneousVolumeMaterial &hvm)=default
bool operator== (const HomogeneousVolumeMaterial &hvm) const
const Material material (const Vector3 &position) const final
std::ostream & toStream (std::ostream &sl) const final
Public Member Functions inherited from Acts::IVolumeMaterial
virtual ~IVolumeMaterial ()=default
Virtual Destructor.
Private Attributes
Material m_material = Material()
Detailed Description
It extends the IVolumeMaterial base class to describe a simple homogeneous material in a volume
Definition at line 23 of file HomogeneousVolumeMaterial.hpp.
View newest version in sPHENIX GitHub at line 23 of file HomogeneousVolumeMaterial.hpp
Constructor & Destructor Documentation
Acts::HomogeneousVolumeMaterial::HomogeneousVolumeMaterial (const Material & material)
Explicit constructor
Parameters
material is the material held by this
Definition at line 15 of file HomogeneousVolumeMaterial.cpp.
View newest version in sPHENIX GitHub at line 15 of file HomogeneousVolumeMaterial.cpp
Acts::HomogeneousVolumeMaterial::HomogeneousVolumeMaterial (const HomogeneousVolumeMaterial & hvm) default
Copy Constructor
Parameters
hvm is the source material
Acts::HomogeneousVolumeMaterial::HomogeneousVolumeMaterial (HomogeneousVolumeMaterial && hvm) default
Copy Move Constructor
Parameters
hvm is the source material
Acts::HomogeneousVolumeMaterial::~HomogeneousVolumeMaterial () override default
Destructor.
Member Function Documentation
const Material Acts::HomogeneousVolumeMaterial::material (const Vector3 & position) const inline final virtual
Access to actual material
Parameters
position is the request position for the material call
Note
position is ignored
Implements Acts::IVolumeMaterial.
Definition at line 70 of file HomogeneousVolumeMaterial.hpp.
View newest version in sPHENIX GitHub at line 70 of file HomogeneousVolumeMaterial.hpp
References m_material.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
HomogeneousVolumeMaterial& Acts::HomogeneousVolumeMaterial::operator= (const HomogeneousVolumeMaterial & hvm) default
Assignment operator
Parameters
hvm is the source material
bool Acts::HomogeneousVolumeMaterial::operator== (const HomogeneousVolumeMaterial & hvm) const inline
Equality operator
Parameters
hvm is the source material
Definition at line 75 of file HomogeneousVolumeMaterial.hpp.
View newest version in sPHENIX GitHub at line 75 of file HomogeneousVolumeMaterial.hpp
References m_material.
std::ostream & Acts::HomogeneousVolumeMaterial::toStream (std::ostream & sl) const final virtual
Output Method for std::ostream
Parameters
sl The outoput stream
Implements Acts::IVolumeMaterial.
Definition at line 19 of file HomogeneousVolumeMaterial.cpp.
View newest version in sPHENIX GitHub at line 19 of file HomogeneousVolumeMaterial.cpp
Member Data Documentation
Material Acts::HomogeneousVolumeMaterial::m_material = Material() private
Definition at line 67 of file HomogeneousVolumeMaterial.hpp.
View newest version in sPHENIX GitHub at line 67 of file HomogeneousVolumeMaterial.hpp
Referenced by material(), and operator==().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Material/HomogeneousVolumeMaterial.hpp
acts/blob/sPHENIX/Core/src/Material/HomogeneousVolumeMaterial.cpp