Analysis Software: TrkrClusterHitAssocv3 Class Reference
TrkrClusterHitAssocv3 Class Reference
Class for associating clusters to the hits that went into them.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrClusterHitAssocv3.h>
Public Member Functions
TrkrClusterHitAssocv3 ()=default
void Reset () override
Clear Event.
void identify (std::ostream &os=std::cout) const override
void addAssoc (TrkrDefs::cluskey, unsigned int) override
Add association between cluster and hit.
Map * getClusterMap (TrkrDefs::hitsetkey) override
get pointer to cluster-to-hit map corresponding to a given hitset id
ConstRange getHits (TrkrDefs::cluskey) override
Get all the hits associated with a cluster by key.
unsigned int size (void) const override
Private Member Functions
ClassDefOverride (TrkrClusterHitAssocv3, 1)
Private Attributes
std::map< TrkrDefs::hitsetkey,
Map > m_map
Additional Inherited Members
Public Types inherited from TrkrClusterHitAssoc
using Map = std::multimap< TrkrDefs::cluskey, TrkrDefs::hitkey >
using ConstIterator = Map::const_iterator
using ConstRange = std::pair< Map::const_iterator, Map::const_iterator >
Protected Member Functions inherited from TrkrClusterHitAssoc
TrkrClusterHitAssoc ()=default
Detailed Description
Class for associating clusters to the hits that went into them.
Store the associations between clusters and the hits that went into them.
Definition at line 25 of file TrkrClusterHitAssocv3.h.
View newest version in sPHENIX GitHub at line 25 of file TrkrClusterHitAssocv3.h
Constructor & Destructor Documentation
TrkrClusterHitAssocv3::TrkrClusterHitAssocv3 () default
Member Function Documentation
void TrkrClusterHitAssocv3::addAssoc (TrkrDefs::cluskey ckey, unsigned hidx) override virtual
Add association between cluster and hit.
Parameters
[in] ckey Cluster key
[in] hidx Index of the hit in TrkrHitSet
Implements TrkrClusterHitAssoc.
Definition at line 45 of file TrkrClusterHitAssocv3.cc.
View newest version in sPHENIX GitHub at line 45 of file TrkrClusterHitAssocv3.cc
References TrkrDefs::getHitSetKeyFromClusKey(), and m_map.
TrkrClusterHitAssocv3::ClassDefOverride (TrkrClusterHitAssocv3 , 1) private
TrkrClusterHitAssocv3::Map * TrkrClusterHitAssocv3::getClusterMap (TrkrDefs::hitsetkey) override virtual
get pointer to cluster-to-hit map corresponding to a given hitset id
Reimplemented from TrkrClusterHitAssoc.
Definition at line 58 of file TrkrClusterHitAssocv3.cc.
View newest version in sPHENIX GitHub at line 58 of file TrkrClusterHitAssocv3.cc
References m_map.
TrkrClusterHitAssocv3::ConstRange TrkrClusterHitAssocv3::getHits (TrkrDefs::cluskey) override virtual
Get all the hits associated with a cluster by key.
Parameters
[in] ckey Cluster key
[out] Range over hits associated with ckey
Implements TrkrClusterHitAssoc.
Definition at line 65 of file TrkrClusterHitAssocv3.cc.
View newest version in sPHENIX GitHub at line 65 of file TrkrClusterHitAssocv3.cc
References TrkrDefs::getHitSetKeyFromClusKey(), and m_map.
void TrkrClusterHitAssocv3::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 25 of file TrkrClusterHitAssocv3.cc.
View newest version in sPHENIX GitHub at line 25 of file TrkrClusterHitAssocv3.cc
References TrkrDefs::getLayer(), m_map, and size().
void TrkrClusterHitAssocv3::Reset () override virtual
Clear Event.
Reimplemented from TrkrClusterHitAssoc.
Definition at line 19 of file TrkrClusterHitAssocv3.cc.
View newest version in sPHENIX GitHub at line 19 of file TrkrClusterHitAssocv3.cc
References m_map.
unsigned int TrkrClusterHitAssocv3::size (void) const override virtual
Reimplemented from TrkrClusterHitAssoc.
Definition at line 83 of file TrkrClusterHitAssocv3.cc.
View newest version in sPHENIX GitHub at line 83 of file TrkrClusterHitAssocv3.cc
References m_map.
Referenced by identify().
Member Data Documentation
std::map<TrkrDefs::hitsetkey, Map> TrkrClusterHitAssocv3::m_map private
Definition at line 43 of file TrkrClusterHitAssocv3.h.
View newest version in sPHENIX GitHub at line 43 of file TrkrClusterHitAssocv3.h
Referenced by addAssoc(), getClusterMap(), getHits(), identify(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterHitAssocv3.h
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterHitAssocv3.cc