Analysis Software: Acts::EDM4hepUtil::detail Namespace Reference
Acts::EDM4hepUtil::detail Namespace Reference
Classes
struct Parameters
Functions
ActsSquareMatrix< 6 > jacobianToEdm4hep (double theta, double qOverP, double Bz)
ActsSquareMatrix< 6 > jacobianFromEdm4hep (double tanLambda, double omega, double Bz)
void unpackCovariance (const float *from, ActsSquareMatrix< 6 > &to)
void packCovariance (const ActsSquareMatrix< 6 > &from, float *to)
Parameters convertTrackParametersToEdm4hep (const Acts::GeometryContext &gctx, double Bz, const BoundTrackParameters &params)
BoundTrackParameters convertTrackParametersFromEdm4hep (double Bz, const Parameters &params)
Function Documentation
BoundTrackParameters Acts::EDM4hepUtil::detail::convertTrackParametersFromEdm4hep (double Bz, const Parameters & params)
Definition at line 181 of file EDM4hepUtil.cpp.
View newest version in sPHENIX GitHub at line 181 of file EDM4hepUtil.cpp
References Acts::IntegrationTest::Bz, Acts::Test::cov, Acts::EDM4hepUtil::detail::Parameters::covariance, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, Acts::UnitConstants::J, jacobianFromEdm4hep(), Acts::EDM4hepUtil::detail::Parameters::particleHypothesis, Acts::EDM4hepUtil::detail::Parameters::surface, and Acts::EDM4hepUtil::detail::Parameters::values.
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::EDM4hepUtil::readTrack().
Parameters Acts::EDM4hepUtil::detail::convertTrackParametersToEdm4hep (const Acts::GeometryContext & gctx, double Bz, const BoundTrackParameters & params)
Definition at line 110 of file EDM4hepUtil.cpp.
View newest version in sPHENIX GitHub at line 110 of file EDM4hepUtil.cpp
References Acts::IntegrationTest::Bz, Acts::EDM4hepUtil::detail::Parameters::covariance, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::covariance(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::direction(), Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, gctx, Acts::Surface::getSharedPtr(), Acts::UnitConstants::J, jacobianToEdm4hep(), Acts::Surface::localToGlobal(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::parameters(), Acts::EDM4hepUtil::detail::Parameters::particleHypothesis, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::particleHypothesis(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::referenceSurface(), Acts::EDM4hepUtil::detail::Parameters::surface, Acts::detail::transformBoundToFreeParameters(), Acts::detail::transformFreeToBoundParameters(), Acts::transportCovarianceToBound(), value, and Acts::EDM4hepUtil::detail::Parameters::values.
Referenced by BOOST_AUTO_TEST_CASE(), Acts::EDM4hepUtil::writeTrack(), and ActsExamples::EDM4hepUtil::writeTrajectory().
ActsSquareMatrix< 6 > Acts::EDM4hepUtil::detail::jacobianFromEdm4hep (double tanLambda, double omega, double Bz)
Definition at line 57 of file EDM4hepUtil.cpp.
View newest version in sPHENIX GitHub at line 57 of file EDM4hepUtil.cpp
References Acts::UnitConstants::J.
Referenced by convertTrackParametersFromEdm4hep().
ActsSquareMatrix< 6 > Acts::EDM4hepUtil::detail::jacobianToEdm4hep (double theta, double qOverP, double Bz)
Definition at line 21 of file EDM4hepUtil.cpp.
View newest version in sPHENIX GitHub at line 21 of file EDM4hepUtil.cpp
References Acts::UnitConstants::J.
Referenced by convertTrackParametersToEdm4hep().
void Acts::EDM4hepUtil::detail::packCovariance (const ActsSquareMatrix< 6 > & from, float * to)
Definition at line 92 of file EDM4hepUtil.cpp.
View newest version in sPHENIX GitHub at line 92 of file EDM4hepUtil.cpp
References i, j, and k.
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::EDM4hepUtil::writeTrack().
void Acts::EDM4hepUtil::detail::unpackCovariance (const float * from, ActsSquareMatrix< 6 > & to)
Definition at line 101 of file EDM4hepUtil.cpp.
View newest version in sPHENIX GitHub at line 101 of file EDM4hepUtil.cpp
References i, j, and k.
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::EDM4hepUtil::readTrack().