Analysis Software: MinimumBiasClassifier Class Reference
MinimumBiasClassifier Class Reference
#include <coresoftware/blob/master/offline/packages/trigger/MinimumBiasClassifier.h>
Public Member Functions
MinimumBiasClassifier (const std::string &name="MinimumBiasClassifier")
constructor
~MinimumBiasClassifier () override=default
destructor
int InitRun (PHCompositeNode *) override
void CreateNodes (PHCompositeNode *)
int GetNodes (PHCompositeNode *)
int process_event (PHCompositeNode *) override
event processing method
int ResetEvent (PHCompositeNode *) override
end of run method
int FillMinimumBiasInfo ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
const float _z_vtx_cut {60.}
const float _mbd_north_cut {10.}
const float _mbd_south_cut {150}
const int _mbd_tube_cut {2}
const float _zdc_cut {40.}
MinimumBiasInfo * _mb_info {nullptr}
MbdOut * _mbd_out {nullptr}
GlobalVertexMap * _global_vertex_map {nullptr}
TowerInfoContainer * _towers_zdc {nullptr}
TowerInfo * _tmp_tower {nullptr}
std::array< float, 2 > _zdc_energy_sum {}
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 18 of file MinimumBiasClassifier.h.
View newest version in sPHENIX GitHub at line 18 of file MinimumBiasClassifier.h
Constructor & Destructor Documentation
MinimumBiasClassifier::MinimumBiasClassifier (const std::string & name = "MinimumBiasClassifier") explicit
constructor
Definition at line 30 of file MinimumBiasClassifier.cc.
View newest version in sPHENIX GitHub at line 30 of file MinimumBiasClassifier.cc
MinimumBiasClassifier::~MinimumBiasClassifier () override default
destructor
Member Function Documentation
void MinimumBiasClassifier::CreateNodes (PHCompositeNode * topNode)
Definition at line 218 of file MinimumBiasClassifier.cc.
View newest version in sPHENIX GitHub at line 218 of file MinimumBiasClassifier.cc
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), PHWHERE, and Fun4AllBase::Verbosity().
Referenced by InitRun().
int MinimumBiasClassifier::FillMinimumBiasInfo ()
Definition at line 57 of file MinimumBiasClassifier.cc.
View newest version in sPHENIX GitHub at line 57 of file MinimumBiasClassifier.cc
References _global_vertex_map, _mb_info, _mbd_north_cut, _mbd_out, _mbd_south_cut, _mbd_tube_cut, _tmp_tower, _towers_zdc, _z_vtx_cut, _zdc_cut, _zdc_energy_sum, GlobalVertexMap::begin(), GlobalVertexMap::empty(), energy, Fun4AllReturnCodes::EVENT_OK, TowerInfo::get_energy(), MbdOut::get_npmt(), MbdOut::get_q(), TowerInfoContainer::get_tower_at_channel(), GlobalVertex::get_z(), i, GlobalVertex::isValid(), j, MinimumBiasInfo::setIsAuAuMinimumBias(), TowerInfoContainer::size(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int MinimumBiasClassifier::GetNodes (PHCompositeNode * topNode)
Definition at line 177 of file MinimumBiasClassifier.cc.
View newest version in sPHENIX GitHub at line 177 of file MinimumBiasClassifier.cc
References _global_vertex_map, _mb_info, _mbd_out, _towers_zdc, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
Referenced by process_event().
int MinimumBiasClassifier::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 36 of file MinimumBiasClassifier.cc.
View newest version in sPHENIX GitHub at line 36 of file MinimumBiasClassifier.cc
References CreateNodes(), Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
int MinimumBiasClassifier::process_event (PHCompositeNode * topNode) override virtual
event processing method
Reimplemented from SubsysReco.
Definition at line 156 of file MinimumBiasClassifier.cc.
View newest version in sPHENIX GitHub at line 156 of file MinimumBiasClassifier.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, FillMinimumBiasInfo(), GetNodes(), and Fun4AllBase::Verbosity().
int MinimumBiasClassifier::ResetEvent (PHCompositeNode *) override virtual
end of run method
Reimplemented from SubsysReco.
Definition at line 48 of file MinimumBiasClassifier.cc.
View newest version in sPHENIX GitHub at line 48 of file MinimumBiasClassifier.cc
References _zdc_energy_sum, and Fun4AllReturnCodes::EVENT_OK.
Member Data Documentation
GlobalVertexMap* MinimumBiasClassifier::_global_vertex_map {nullptr} private
Definition at line 50 of file MinimumBiasClassifier.h.
View newest version in sPHENIX GitHub at line 50 of file MinimumBiasClassifier.h
Referenced by FillMinimumBiasInfo(), and GetNodes().
MinimumBiasInfo* MinimumBiasClassifier::_mb_info {nullptr} private
Definition at line 48 of file MinimumBiasClassifier.h.
View newest version in sPHENIX GitHub at line 48 of file MinimumBiasClassifier.h
Referenced by FillMinimumBiasInfo(), and GetNodes().
const float MinimumBiasClassifier::_mbd_north_cut {10.} private
Definition at line 43 of file MinimumBiasClassifier.h.
View newest version in sPHENIX GitHub at line 43 of file MinimumBiasClassifier.h
Referenced by FillMinimumBiasInfo().
MbdOut* MinimumBiasClassifier::_mbd_out {nullptr} private
Definition at line 49 of file MinimumBiasClassifier.h.
View newest version in sPHENIX GitHub at line 49 of file MinimumBiasClassifier.h
Referenced by FillMinimumBiasInfo(), and GetNodes().
const float MinimumBiasClassifier::_mbd_south_cut {150} private
Definition at line 44 of file MinimumBiasClassifier.h.
View newest version in sPHENIX GitHub at line 44 of file MinimumBiasClassifier.h
Referenced by FillMinimumBiasInfo().
const int MinimumBiasClassifier::_mbd_tube_cut {2} private
Definition at line 45 of file MinimumBiasClassifier.h.
View newest version in sPHENIX GitHub at line 45 of file MinimumBiasClassifier.h
Referenced by FillMinimumBiasInfo().
TowerInfo* MinimumBiasClassifier::_tmp_tower {nullptr} private
Definition at line 52 of file MinimumBiasClassifier.h.
View newest version in sPHENIX GitHub at line 52 of file MinimumBiasClassifier.h
Referenced by FillMinimumBiasInfo().
TowerInfoContainer* MinimumBiasClassifier::_towers_zdc {nullptr} private
Definition at line 51 of file MinimumBiasClassifier.h.
View newest version in sPHENIX GitHub at line 51 of file MinimumBiasClassifier.h
Referenced by FillMinimumBiasInfo(), and GetNodes().
const float MinimumBiasClassifier::_z_vtx_cut {60.} private
Definition at line 42 of file MinimumBiasClassifier.h.
View newest version in sPHENIX GitHub at line 42 of file MinimumBiasClassifier.h
Referenced by FillMinimumBiasInfo().
const float MinimumBiasClassifier::_zdc_cut {40.} private
Definition at line 46 of file MinimumBiasClassifier.h.
View newest version in sPHENIX GitHub at line 46 of file MinimumBiasClassifier.h
Referenced by FillMinimumBiasInfo().
std::array<float, 2> MinimumBiasClassifier::_zdc_energy_sum {} private
Definition at line 54 of file MinimumBiasClassifier.h.
View newest version in sPHENIX GitHub at line 54 of file MinimumBiasClassifier.h
Referenced by FillMinimumBiasInfo(), and ResetEvent().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trigger/MinimumBiasClassifier.h
coresoftware/blob/master/offline/packages/trigger/MinimumBiasClassifier.cc