Analysis Software: Acts::VectorTrackContainer Exception Reference
Acts::VectorTrackContainer Exception Reference final
#include <acts/blob/sPHENIX/Core/include/Acts/EventData/VectorTrackContainer.hpp>
Public Member Functions
VectorTrackContainer ()
VectorTrackContainer (VectorTrackContainer &&)=default
VectorTrackContainer (const ConstVectorTrackContainer &other)
std::any component_impl (HashedString key, IndexType itrack)
std::any component_impl (HashedString key, IndexType itrack) const
IndexType addTrack_impl ()
void removeTrack_impl (IndexType itrack)
template<typename T >
constexpr void addColumn_impl (const std::string &key)
Parameters parameters (IndexType itrack)
ConstParameters parameters (IndexType itrack) const
Covariance covariance (IndexType itrack)
ConstCovariance covariance (IndexType itrack) const
void copyDynamicFrom_impl (IndexType dstIdx, const VectorTrackContainerBase &src, IndexType srcIdx)
void ensureDynamicColumns_impl (const detail_vtc::VectorTrackContainerBase &other)
void reserve (IndexType size)
void clear ()
void setReferenceSurface_impl (IndexType itrack, std::shared_ptr< const Surface > surface)
void setParticleHypothesis_impl (IndexType itrack, const ParticleHypothesis &particleHypothesis)
Public Member Functions inherited from Acts::detail_vtc::VectorTrackContainerBase
constexpr bool hasColumn_impl (HashedString key) const
const Surface * referenceSurface_impl (IndexType itrack) const
std::size_t size_impl () const
Additional Inherited Members
Public Types inherited from Acts::detail_vtc::VectorTrackContainerBase
using IndexType = MultiTrajectoryTraits::IndexType
using Parameters = typename detail_lt::Types< eBoundSize, false >::CoefficientsMap
using Covariance = typename detail_lt::Types< eBoundSize, false >::CovarianceMap
using ConstParameters = typename detail_lt::Types< eBoundSize, true >::CoefficientsMap
using ConstCovariance = typename detail_lt::Types< eBoundSize, true >::CovarianceMap
Public Attributes inherited from Acts::detail_vtc::VectorTrackContainerBase
std::vector< IndexType > m_tipIndex
std::vector< IndexType > m_stemIndex
std::vector< ParticleHypothesis > m_particleHypothesis
std::vector< typename
detail_lt::Types< eBoundSize >
::Coefficients > m_params
std::vector< typename
detail_lt::Types< eBoundSize >
::Covariance > m_cov
std::vector< std::shared_ptr
< const Surface > > m_referenceSurfaces
std::vector< unsigned int > m_nMeasurements
std::vector< unsigned int > m_nHoles
std::vector< float > m_chi2
std::vector< unsigned int > m_ndf
std::vector< unsigned int > m_nOutliers
std::vector< unsigned int > m_nSharedHits
std::unordered_map
< HashedString,
std::unique_ptr
< detail::DynamicColumnBase > > m_dynamic
Static Public Attributes inherited from Acts::detail_vtc::VectorTrackContainerBase
static constexpr auto kInvalid = MultiTrajectoryTraits::kInvalid
static constexpr auto MeasurementSizeMax
Protected Member Functions inherited from Acts::detail_vtc::VectorTrackContainerBase
VectorTrackContainerBase ()=default
VectorTrackContainerBase (const VectorTrackContainerBase &other)
VectorTrackContainerBase (VectorTrackContainerBase &&other)=default
bool checkConsistency () const
Static Protected Member Functions inherited from Acts::detail_vtc::VectorTrackContainerBase
template<bool EnsureConst, typename T >
static std::any component_impl (T &instance, HashedString key, IndexType itrack)
Detailed Description
Definition at line 193 of file VectorTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 193 of file VectorTrackContainer.hpp
Constructor & Destructor Documentation
Acts::VectorTrackContainer::VectorTrackContainer () inline
Definition at line 195 of file VectorTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 195 of file VectorTrackContainer.hpp
Acts::VectorTrackContainer::VectorTrackContainer (VectorTrackContainer &&) default
Acts::VectorTrackContainer::VectorTrackContainer (const ConstVectorTrackContainer & other) inline
Definition at line 309 of file VectorTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 309 of file VectorTrackContainer.hpp
Member Function Documentation
template<typename T > constexpr void Acts::VectorTrackContainer::addColumn_impl (const std::string & key) inline
Definition at line 219 of file VectorTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 219 of file VectorTrackContainer.hpp
References Acts::hashString(), and Acts::detail_vtc::VectorTrackContainerBase::m_dynamic.
VectorTrackContainer::IndexType Acts::VectorTrackContainer::addTrack_impl ()
Definition at line 40 of file VectorTrackContainer.cpp.
View newest version in sPHENIX GitHub at line 40 of file VectorTrackContainer.cpp
References assert, Acts::detail_vtc::VectorTrackContainerBase::checkConsistency(), Acts::detail_vtc::VectorTrackContainerBase::kInvalid, Acts::detail_vtc::VectorTrackContainerBase::m_chi2, Acts::detail_vtc::VectorTrackContainerBase::m_cov, Acts::detail_vtc::VectorTrackContainerBase::m_dynamic, Acts::detail_vtc::VectorTrackContainerBase::m_ndf, Acts::detail_vtc::VectorTrackContainerBase::m_nHoles, Acts::detail_vtc::VectorTrackContainerBase::m_nMeasurements, Acts::detail_vtc::VectorTrackContainerBase::m_nOutliers, Acts::detail_vtc::VectorTrackContainerBase::m_nSharedHits, Acts::detail_vtc::VectorTrackContainerBase::m_params, Acts::detail_vtc::VectorTrackContainerBase::m_particleHypothesis, Acts::detail_vtc::VectorTrackContainerBase::m_referenceSurfaces, Acts::detail_vtc::VectorTrackContainerBase::m_stemIndex, Acts::detail_vtc::VectorTrackContainerBase::m_tipIndex, Acts::ParticleHypothesis::pion(), and vec.
void Acts::VectorTrackContainer::clear ()
Definition at line 144 of file VectorTrackContainer.cpp.
View newest version in sPHENIX GitHub at line 144 of file VectorTrackContainer.cpp
References Acts::detail_vtc::VectorTrackContainerBase::m_chi2, Acts::detail_vtc::VectorTrackContainerBase::m_cov, Acts::detail_vtc::VectorTrackContainerBase::m_dynamic, Acts::detail_vtc::VectorTrackContainerBase::m_ndf, Acts::detail_vtc::VectorTrackContainerBase::m_nHoles, Acts::detail_vtc::VectorTrackContainerBase::m_nMeasurements, Acts::detail_vtc::VectorTrackContainerBase::m_nOutliers, Acts::detail_vtc::VectorTrackContainerBase::m_nSharedHits, Acts::detail_vtc::VectorTrackContainerBase::m_params, Acts::detail_vtc::VectorTrackContainerBase::m_particleHypothesis, Acts::detail_vtc::VectorTrackContainerBase::m_referenceSurfaces, Acts::detail_vtc::VectorTrackContainerBase::m_stemIndex, Acts::detail_vtc::VectorTrackContainerBase::m_tipIndex, and vec.
std::any Acts::VectorTrackContainer::component_impl (HashedString key, IndexType itrack) inline
Definition at line 204 of file VectorTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 204 of file VectorTrackContainer.hpp
std::any Acts::VectorTrackContainer::component_impl (HashedString key, IndexType itrack) const inline
Definition at line 209 of file VectorTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 209 of file VectorTrackContainer.hpp
void Acts::VectorTrackContainer::copyDynamicFrom_impl (IndexType dstIdx, const VectorTrackContainerBase & src, IndexType srcIdx)
Definition at line 99 of file VectorTrackContainer.cpp.
View newest version in sPHENIX GitHub at line 99 of file VectorTrackContainer.cpp
References it, Acts::detail_vtc::VectorTrackContainerBase::m_dynamic, and value.
Covariance Acts::VectorTrackContainer::covariance (IndexType itrack) inline
Definition at line 232 of file VectorTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 232 of file VectorTrackContainer.hpp
References Acts::detail_vtc::VectorTrackContainerBase::m_cov.
ConstCovariance Acts::VectorTrackContainer::covariance (IndexType itrack) const inline
Definition at line 236 of file VectorTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 236 of file VectorTrackContainer.hpp
References Acts::detail_vtc::VectorTrackContainerBase::m_cov.
void Acts::VectorTrackContainer::ensureDynamicColumns_impl (const detail_vtc::VectorTrackContainerBase & other)
Definition at line 112 of file VectorTrackContainer.cpp.
View newest version in sPHENIX GitHub at line 112 of file VectorTrackContainer.cpp
References Acts::detail_vtc::VectorTrackContainerBase::m_dynamic, and value.
Parameters Acts::VectorTrackContainer::parameters (IndexType itrack) inline
Definition at line 224 of file VectorTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 224 of file VectorTrackContainer.hpp
References Acts::detail_vtc::VectorTrackContainerBase::m_params.
ConstParameters Acts::VectorTrackContainer::parameters (IndexType itrack) const inline
Definition at line 228 of file VectorTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 228 of file VectorTrackContainer.hpp
References Acts::detail_vtc::VectorTrackContainerBase::m_params.
void Acts::VectorTrackContainer::removeTrack_impl (IndexType itrack)
Definition at line 70 of file VectorTrackContainer.cpp.
View newest version in sPHENIX GitHub at line 70 of file VectorTrackContainer.cpp
References assert, it, Acts::detail_vtc::VectorTrackContainerBase::m_chi2, Acts::detail_vtc::VectorTrackContainerBase::m_cov, Acts::detail_vtc::VectorTrackContainerBase::m_dynamic, Acts::detail_vtc::VectorTrackContainerBase::m_ndf, Acts::detail_vtc::VectorTrackContainerBase::m_nHoles, Acts::detail_vtc::VectorTrackContainerBase::m_nMeasurements, Acts::detail_vtc::VectorTrackContainerBase::m_nOutliers, Acts::detail_vtc::VectorTrackContainerBase::m_nSharedHits, Acts::detail_vtc::VectorTrackContainerBase::m_params, Acts::detail_vtc::VectorTrackContainerBase::m_referenceSurfaces, Acts::detail_vtc::VectorTrackContainerBase::m_stemIndex, Acts::detail_vtc::VectorTrackContainerBase::m_tipIndex, and vec.
void Acts::VectorTrackContainer::reserve (IndexType size)
Definition at line 121 of file VectorTrackContainer.cpp.
View newest version in sPHENIX GitHub at line 121 of file VectorTrackContainer.cpp
References Acts::detail_vtc::VectorTrackContainerBase::m_chi2, Acts::detail_vtc::VectorTrackContainerBase::m_cov, Acts::detail_vtc::VectorTrackContainerBase::m_dynamic, Acts::detail_vtc::VectorTrackContainerBase::m_ndf, Acts::detail_vtc::VectorTrackContainerBase::m_nHoles, Acts::detail_vtc::VectorTrackContainerBase::m_nMeasurements, Acts::detail_vtc::VectorTrackContainerBase::m_nOutliers, Acts::detail_vtc::VectorTrackContainerBase::m_nSharedHits, Acts::detail_vtc::VectorTrackContainerBase::m_params, Acts::detail_vtc::VectorTrackContainerBase::m_particleHypothesis, Acts::detail_vtc::VectorTrackContainerBase::m_referenceSurfaces, Acts::detail_vtc::VectorTrackContainerBase::m_stemIndex, Acts::detail_vtc::VectorTrackContainerBase::m_tipIndex, and vec.
void Acts::VectorTrackContainer::setParticleHypothesis_impl (IndexType itrack, const ParticleHypothesis & particleHypothesis) inline
Definition at line 255 of file VectorTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 255 of file VectorTrackContainer.hpp
References Acts::detail_vtc::VectorTrackContainerBase::m_particleHypothesis, and particleHypothesis.
void Acts::VectorTrackContainer::setReferenceSurface_impl (IndexType itrack, std::shared_ptr< const Surface > surface) inline
Definition at line 250 of file VectorTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 250 of file VectorTrackContainer.hpp
References Acts::detail_vtc::VectorTrackContainerBase::m_referenceSurfaces, and testing::internal::move().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/EventData/VectorTrackContainer.hpp
acts/blob/sPHENIX/Core/src/EventData/VectorTrackContainer.cpp