Analysis Software: analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorQAMaker/macros/CalculateSigmaDca.cxx File Reference
CalculateSigmaDca.cxx File Reference
#include <string>
#include <vector>
#include <utility>
#include <iostream>
#include <TH1.h>
#include <TH2.h>
#include <TF1.h>
#include <TFile.h>
#include <TMath.h>
#include <TError.h>
#include <TNtuple.h>
#include <TString.h>
#include <TCanvas.h>
#include <TObjArray.h>
#include <TPaveText.h>
#include <TGraphErrors.h>
Functions
static const size_t NDca (2)
static const size_t NPar (4)
static const size_t NObj (2)
static const size_t NVtx (4)
void CalculateSigmaDca ()
Function Documentation
void CalculateSigmaDca ()
Definition at line 39 of file CalculateSigmaDca.cxx.
View newest version in sPHENIX GitHub at line 39 of file CalculateSigmaDca.cxx
References cd(), Close(), configureMap::data, Draw(), energy, eta, Fill(), material_mapping_optimisation::flush, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEntry(), GetParameter(), GetXaxis(), GetYaxis(), GetZaxis(), NDca(), NPar(), ActsTests::PropagationDatasets::phi, physmon_track_finding_ttbar::pt, SetBorderMode(), SetBorderSize(), SetBottomMargin(), SetBranchAddress(), SetFillColor(), SetFillStyle(), SetLeftMargin(), SetLineColor(), SetLineStyle(), SetLineWidth(), SetMarkerColor(), SetMarkerStyle(), SetName(), SetParameter(), SetRightMargin(), SetTextFont(), SetTitle(), SetTopMargin(), start, text(), and Write().
static const size_t NDca (2) static
Referenced by CalculateSigmaDca().
static const size_t NObj (2) static
static const size_t NPar (4) static
Referenced by CalculateSigmaDca().
static const size_t NVtx (4) static