Analysis Software: PGun Class Reference
PGun Class Reference
#include <JETSCAPE/blob/main/src/initialstate/PGun.h>
Public Member Functions
PGun ()
~PGun ()
void InitTask ()
void Exec ()
Public Member Functions inherited from Jetscape::HardProcess
HardProcess ()
virtual ~HardProcess ()
virtual void Init ()
virtual void Clear ()
virtual void WriteTask (weak_ptr< JetScapeWriter > w)
virtual void CollectHeader (weak_ptr< JetScapeWriter > w)
int GetNHardPartons ()
shared_ptr< Parton > GetPartonAt (int i)
vector< shared_ptr< Parton > > & GetPartonList ()
void AddParton (shared_ptr< Parton > p)
void GetHardPartonList (vector< shared_ptr< Parton >> &plist)
virtual double GetSigmaGen ()
virtual double GetSigmaErr ()
virtual double GetPtHat ()
virtual double GetEventWeight ()
void AddHadron (shared_ptr< Hadron > h)
void GetHadronList (vector< shared_ptr< Hadron >> &hlist)
vector< shared_ptr< Hadron > > & GetHadronList ()
int GetNHadrons ()
Public Member Functions inherited from Jetscape::JetScapeModuleBase
JetScapeModuleBase ()
JetScapeModuleBase (string m_name)
virtual ~JetScapeModuleBase ()
void SetXMLMainFileName (string m_name)
string GetXMLMainFileName ()
void SetXMLUserFileName (string m_name)
string GetXMLUserFileName ()
shared_ptr< std::mt19937 > GetMt19937Generator ()
tinyxml2::XMLElement * GetXMLElement (std::initializer_list< const char * > path, bool isRequired=true)
std::string GetXMLElementText (std::initializer_list< const char * > path, bool isRequired=true)
int GetXMLElementInt (std::initializer_list< const char * > path, bool isRequired=true)
double GetXMLElementDouble (std::initializer_list< const char * > path, bool isRequired=true)
Public Member Functions inherited from Jetscape::JetScapeTask
JetScapeTask ()
virtual ~JetScapeTask ()
virtual void Finish ()
virtual void ExecuteTasks ()
virtual void ExecuteTask ()
virtual void InitTasks ()
virtual void ClearTasks ()
virtual void ClearTask ()
virtual void FinishTask ()
virtual void FinishTasks ()
virtual void WriteTasks (weak_ptr< JetScapeWriter > w)
virtual void CollectHeaders (weak_ptr< JetScapeWriter > w)
virtual void Add (shared_ptr< JetScapeTask > m_tasks)
virtual const int GetMyTaskNumber () const
const vector< shared_ptr
< JetScapeTask > > GetTaskList () const
shared_ptr< JetScapeTask > GetTaskAt (int i)
void EraseTaskLast ()
void EraseTaskAt (int i)
void ResizeTaskList (int i)
void ClearTaskList ()
int GetNumberOfTasks ()
const bool GetActive () const
void SetActive (bool m_active_exec)
void SetId (string m_id)
const string GetId () const
const shared_ptr
< JetScapeModuleMutex > GetMutex () const
void SetMutex (shared_ptr< JetScapeModuleMutex > m_mutex)
Public Member Functions inherited from sigslot::has_slots< sigslot::multi_threaded_local >
has_slots ()
has_slots (const has_slots &hs)
void signal_connect (_signal_base< sigslot::multi_threaded_local > *sender)
void signal_disconnect (_signal_base< sigslot::multi_threaded_local > *sender)
virtual ~has_slots ()
void disconnect_all ()
Private Attributes
double fixed_pT
double parID
Static Private Attributes
static Pythia8::Pythia InternalHelperPythia
static RegisterJetScapeModule
< PGun > reg
Additional Inherited Members
Static Public Member Functions inherited from Jetscape::JetScapeModuleBase
static int GetCurrentEvent ()
static void IncrementCurrentEvent ()
Public Attributes inherited from Jetscape::HardProcess
std::shared_ptr< InitialState > ini
std::string printer
Detailed Description
Definition at line 26 of file PGun.h.
View newest version in sPHENIX GitHub at line 26 of file PGun.h
Constructor & Destructor Documentation
PGun::PGun ()
Definition at line 28 of file PGun.cc.
View newest version in sPHENIX GitHub at line 28 of file PGun.cc
References fixed_pT, parID, Jetscape::JetScapeTask::SetId(), and VERBOSE.
PGun::~PGun ()
Definition at line 35 of file PGun.cc.
View newest version in sPHENIX GitHub at line 35 of file PGun.cc
References VERBOSE.
Member Function Documentation
void PGun::Exec () virtual
Calls JetScapeTask::ExecuteTasks() for recursive execution of tasks attached to HardProcess module. It can be overridden by the attached module.
Reimplemented from Jetscape::HardProcess.
Definition at line 52 of file PGun.cc.
View newest version in sPHENIX GitHub at line 52 of file PGun.cc
References Jetscape::HardProcess::AddParton(), fixed_pT, Jetscape::JetScapeTask::GetId(), Jetscape::HardProcess::GetNHardPartons(), i, Jetscape::HardProcess::ini, InternalHelperPythia, JSWARN, mass, Jetscape::maxN, merge_hashes::p, parID, ActsTests::PropagationDatasets::phi, graph_fancy::pT, Jetscape::rounding_error, VERBOSE, ambiguity_solver_full_chain::x, and y.
void PGun::InitTask () virtual
A virtual function to define a default InitTask() function for a JetScapeTask. It can be overridden by different modules/tasks.
Reimplemented from Jetscape::JetScapeTask.
Definition at line 37 of file PGun.cc.
View newest version in sPHENIX GitHub at line 37 of file PGun.cc
References fixed_pT, Jetscape::JetScapeModuleBase::GetXMLElementDouble(), Jetscape::JetScapeModuleBase::GetXMLElementText(), JSDEBUG, JSINFO, parID, physmon_simulation::s, and VERBOSE.
Member Data Documentation
double PGun::fixed_pT private
Definition at line 31 of file PGun.h.
View newest version in sPHENIX GitHub at line 31 of file PGun.h
Referenced by Exec(), InitTask(), and PGun().
Pythia8::Pythia PGun::InternalHelperPythia static private
Definition at line 28 of file PGun.h.
View newest version in sPHENIX GitHub at line 28 of file PGun.h
Referenced by Exec().
double PGun::parID private
Definition at line 32 of file PGun.h.
View newest version in sPHENIX GitHub at line 32 of file PGun.h
Referenced by Exec(), InitTask(), and PGun().
RegisterJetScapeModule< PGun > PGun::reg static private
Definition at line 35 of file PGun.h.
View newest version in sPHENIX GitHub at line 35 of file PGun.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/initialstate/PGun.h
JETSCAPE/blob/main/src/initialstate/PGun.cc