Analysis Software: Acts::InfiniteBounds Class Reference
Acts::InfiniteBounds Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Surfaces/InfiniteBounds.hpp>
Public Member Functions
InfiniteBounds ()=default
~InfiniteBounds () override=default
SurfaceBounds::BoundsType type () const final
std::vector< double > values () const final
bool inside (const Vector2 &, const BoundaryCheck &) const final
std::ostream & toStream (std::ostream &os) const final
Output Method for std::ostream.
Public Member Functions inherited from Acts::SurfaceBounds
virtual ~SurfaceBounds ()=default
Additional Inherited Members
Public Types inherited from Acts::SurfaceBounds
enum BoundsType : int {
eCone = 0, eCylinder = 1, eDiamond = 2, eDisc = 3,
eEllipse = 4, eLine = 5, eRectangle = 6, eTrapezoid = 7,
eTriangle = 8, eDiscTrapezoid = 9, eConvexPolygon = 10, eAnnulus = 11,
eBoundless = 12, eOther = 13
}
Detailed Description
templated boundless extension to forward the interface Returns all inside checks to true and can templated for all bounds
Definition at line 20 of file InfiniteBounds.hpp.
View newest version in sPHENIX GitHub at line 20 of file InfiniteBounds.hpp
Constructor & Destructor Documentation
Acts::InfiniteBounds::InfiniteBounds () default
Acts::InfiniteBounds::~InfiniteBounds () override default
Member Function Documentation
bool Acts::InfiniteBounds::inside (const Vector2 & , const BoundaryCheck &) const inline final virtual
Method inside() returns true for any case
ignores input parameters
Returns
always true
Implements Acts::SurfaceBounds.
Definition at line 37 of file InfiniteBounds.hpp.
View newest version in sPHENIX GitHub at line 37 of file InfiniteBounds.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
std::ostream& Acts::InfiniteBounds::toStream (std::ostream & os) const inline final virtual
Output Method for std::ostream.
Implements Acts::SurfaceBounds.
Definition at line 43 of file InfiniteBounds.hpp.
View newest version in sPHENIX GitHub at line 43 of file InfiniteBounds.hpp
References os.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
SurfaceBounds::BoundsType Acts::InfiniteBounds::type () const inline final virtual
Return the bounds type - for persistency optimization
Returns
is a BoundsType enum
Implements Acts::SurfaceBounds.
Definition at line 26 of file InfiniteBounds.hpp.
View newest version in sPHENIX GitHub at line 26 of file InfiniteBounds.hpp
References Acts::SurfaceBounds::eBoundless.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
std::vector<double> Acts::InfiniteBounds::values () const inline final virtual
Access method for bound values, this is a dynamically sized vector containing the parameters needed to describe these bounds
Returns
of the stored values for this SurfaceBounds object
Implements Acts::SurfaceBounds.
Definition at line 30 of file InfiniteBounds.hpp.
View newest version in sPHENIX GitHub at line 30 of file InfiniteBounds.hpp
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Surfaces/InfiniteBounds.hpp