Analysis Software: ActsExamples::Simulation Namespace Reference
ActsExamples::Simulation Namespace Reference
Functions
void addInputOptions (ActsExamples::Options::Description &desc)
void setupInput (const ActsExamples::Options::Variables &vars, ActsExamples::Sequencer &sequencer, std::shared_ptr< const ActsExamples::RandomNumbers > randomNumbers)
void setupOutput (const ActsExamples::Options::Variables &vars, ActsExamples::Sequencer &sequencer)
Variables
static constexpr const char * kParticlesInput = "particles_input"
Collection names.
static constexpr const char * kParticlesSelection = "particles_selection"
static constexpr const char * kParticlesInitial = "particles_initial"
static constexpr const char * kParticlesFinal = "particles_final"
static constexpr const char * kSimHits = "simhits"
static constexpr const char * kMaterialTracks = "material_tracks"
Function Documentation
void ActsExamples::Simulation::addInputOptions (ActsExamples::Options::Description & desc)
Add input options
Parameters
desc is the boost options descr format
Definition at line 28 of file CommonSimulation.cpp.
View newest version in sPHENIX GitHub at line 28 of file CommonSimulation.cpp
References ActsExamples::Options::addParticleGunOptions(), ActsExamples::Options::addParticleSelectorOptions(), and value.
Referenced by main(), and runFatras().
void ActsExamples::Simulation::setupInput (const ActsExamples::Options::Variables & vars, ActsExamples::Sequencer & sequencer, std::shared_ptr< const ActsExamples::RandomNumbers > randomNumbers)
Setup the input from the provided options
Parameters
vars the parsed variables from the boost options
sequencer the non-const sequencer
randomNumbers the randomNumbers shared pointer
Definition at line 41 of file CommonSimulation.cpp.
View newest version in sPHENIX GitHub at line 41 of file CommonSimulation.cpp
References ActsExamples::Sequencer::addAlgorithm(), ActsExamples::Sequencer::addReader(), gen(), ActsExamples::CsvParticleReader::Config::inputDir, ActsExamples::CsvParticleReader::Config::inputStem, kParticlesInput, kParticlesSelection, telescope_simulation::logLevel, testing::internal::move(), ActsExamples::CsvParticleReader::Config::outputParticles, ActsExamples::Options::readLogLevel(), ActsExamples::Options::readParticleGunOptions(), and ActsExamples::Options::readParticleSelectorConfig().
Referenced by runFatras(), and ActsExamples::runGeant4Simulation().
void ActsExamples::Simulation::setupOutput (const ActsExamples::Options::Variables & vars, ActsExamples::Sequencer & sequencer)
Setup the output from the provided options
Parameters
vars the parsed variables from the boost options
sequencer the non-const sequencer
Definition at line 75 of file CommonSimulation.cpp.
View newest version in sPHENIX GitHub at line 75 of file CommonSimulation.cpp
References ActsExamples::Sequencer::addWriter(), ActsExamples::ensureWritableDirectory(), ActsExamples::RootSimHitWriter::Config::filePath, ActsExamples::RootParticleWriter::Config::filePath, ActsExamples::RootParticleWriter::Config::inputParticles, ActsExamples::CsvParticleWriter::Config::inputParticles, ActsExamples::RootSimHitWriter::Config::inputSimHits, ActsExamples::CsvSimHitWriter::Config::inputSimHits, ActsExamples::joinPaths(), kParticlesFinal, kParticlesInitial, kSimHits, telescope_simulation::logLevel, outputDir, ActsExamples::CsvSimHitWriter::Config::outputDir, ActsExamples::CsvParticleWriter::Config::outputDir, ActsExamples::CsvSimHitWriter::Config::outputStem, ActsExamples::CsvParticleWriter::Config::outputStem, and ActsExamples::Options::readLogLevel().
Referenced by runFatras(), and ActsExamples::runGeant4Simulation().
Variable Documentation
constexpr const char* ActsExamples::Simulation::kMaterialTracks = "material_tracks" static
Definition at line 24 of file CommonSimulation.hpp.
View newest version in sPHENIX GitHub at line 24 of file CommonSimulation.hpp
Referenced by runMaterialMapping(), ActsExamples::runMaterialRecording(), and ActsExamples::setupMaterialRecording().
constexpr const char* ActsExamples::Simulation::kParticlesFinal = "particles_final" static
Definition at line 22 of file CommonSimulation.hpp.
View newest version in sPHENIX GitHub at line 22 of file CommonSimulation.hpp
Referenced by ActsExamples::setupGeant4Simulation(), and setupOutput().
constexpr const char* ActsExamples::Simulation::kParticlesInitial = "particles_initial" static
Definition at line 21 of file CommonSimulation.hpp.
View newest version in sPHENIX GitHub at line 21 of file CommonSimulation.hpp
Referenced by ActsExamples::runMaterialRecording(), ActsExamples::setupGeant4Simulation(), ActsExamples::setupMaterialRecording(), and setupOutput().
constexpr const char* ActsExamples::Simulation::kParticlesInput = "particles_input" static
Collection names.
Definition at line 19 of file CommonSimulation.hpp.
View newest version in sPHENIX GitHub at line 19 of file CommonSimulation.hpp
Referenced by setupInput().
constexpr const char* ActsExamples::Simulation::kParticlesSelection = "particles_selection" static
Definition at line 20 of file CommonSimulation.hpp.
View newest version in sPHENIX GitHub at line 20 of file CommonSimulation.hpp
Referenced by ActsExamples::setupGeant4Simulation(), and setupInput().
constexpr const char* ActsExamples::Simulation::kSimHits = "simhits" static
Definition at line 23 of file CommonSimulation.hpp.
View newest version in sPHENIX GitHub at line 23 of file CommonSimulation.hpp
Referenced by ActsExamples::setupGeant4Simulation(), and setupOutput().