Analysis Software: Acts::DetrayJsonHelper Namespace Reference
Acts::DetrayJsonHelper Namespace Reference
Functions
static std::tuple< unsigned
int, std::vector< ActsScalar > > maskFromBounds (const Acts::SurfaceBounds &sBounds, bool portal=false)
Helper function to switch keys from ACTS to detray.
static void addVolumeLink (nlohmann::json &jSurface, int vLink)
add volume link
Function Documentation
static void Acts::DetrayJsonHelper::addVolumeLink (nlohmann::json & jSurface, int vLink) inline static
add volume link
Parameters
jSurface [in,out] is the json object to be patched
vLink is the volume link to be added
Definition at line 89 of file DetrayJsonHelper.hpp.
View newest version in sPHENIX GitHub at line 89 of file DetrayJsonHelper.hpp
Referenced by Acts::DetectorVolumeJsonConverter::toJsonDetray(), and Acts::PortalJsonConverter::toJsonDetray().
static std::tuple<unsigned int, std::vector<ActsScalar> > Acts::DetrayJsonHelper::maskFromBounds (const Acts::SurfaceBounds & sBounds, bool portal = false) inline static
Helper function to switch keys from ACTS to detray.
DETRAY types
Parameters
sBounds is the surface bounds type
portal is the flag for conversion into detray portal format
Returns
type and value array in detray format
Definition at line 42 of file DetrayJsonHelper.hpp.
View newest version in sPHENIX GitHub at line 42 of file DetrayJsonHelper.hpp
References Acts::SurfaceBounds::type(), Acts::type, physmon_ckf_tracking::u, and Acts::SurfaceBounds::values().
Referenced by Acts::SurfaceBoundsJsonConverter::toJsonDetray().