Analysis Software: plotUtil Namespace Reference
plotUtil Namespace Reference
Functions
def colorset
def Draw_1Dhist
def Draw_1DhistsComp
def Draw_2Dhist
def plot_Stack
def GetHistogram
def str_pttop
Variables
float TickSize 0.03
float AxisTitleSize 0.05
float AxisLabelSize 0.04
float LeftMargin 0.15
float RightMargin 0.08
float TopMargin 0.08
float BottomMargin 0.13
string black_hex '#1B1A17'
string red_hex '#9A031E'
string blue_hex '#0B60B0'
string green_hex '#186F65'
string orange_hex '#e99960'
string purple_hex '#7F167F'
string pink_hex '#FFC0CB'
string yellow_hex '#ffcc66'
string cyan_hex '#7FE9DE'
Function Documentation
def plotUtil.colorset (i)
Definition at line 21 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 21 of file plotUtil.py
Referenced by plot_DataSimComp.Draw_1Dhist_datasimcomp().
def plotUtil.Draw_1Dhist (hist, IsData, norm1, logy, ymaxscale, XaxisName, Ytitle_unit, outname)
Definition at line 37 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 37 of file plotUtil.py
References material_mapping_optimisation.format, if(), and SetTitle().
def plotUtil.Draw_1DhistsComp (lhist, norm1, logx, logy, ymaxscale, XaxisName, Ytitle_unit, outname)
Definition at line 103 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 103 of file plotUtil.py
References Acts.enumerate(), material_mapping_optimisation.format, GetXaxis(), GetYaxis(), if(), and SetTitle().
def plotUtil.Draw_2Dhist (hist, IsData, logz, norm1, rmargin, XaxisName, YaxisName, drawopt, outname)
Definition at line 207 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 207 of file plotUtil.py
References if(), and SetTitle().
Referenced by RecoPV_optimization.main().
def plotUtil.GetHistogram (filename, histname)
Definition at line 311 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 311 of file plotUtil.py
def plotUtil.plot_Stack (totalhist, list_hist, color, list_legtext, logy, ymaxscale, XaxisName, Ytitle_unit, plotname)
Definition at line 251 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 251 of file plotUtil.py
References Acts.enumerate(), material_mapping_optimisation.format, if(), and SetTitle().
def plotUtil.str_pttop (s)
Definition at line 319 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 319 of file plotUtil.py
References str.
Variable Documentation
float plotUtil.AxisLabelSize 0.04
Definition at line 5 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 5 of file plotUtil.py
float plotUtil.AxisTitleSize 0.05
Definition at line 4 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 4 of file plotUtil.py
string plotUtil.black_hex '#1B1A17'
Definition at line 11 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 11 of file plotUtil.py
string plotUtil.blue_hex '#0B60B0'
Definition at line 13 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 13 of file plotUtil.py
float plotUtil.BottomMargin 0.13
Definition at line 9 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 9 of file plotUtil.py
string plotUtil.cyan_hex '#7FE9DE'
Definition at line 19 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 19 of file plotUtil.py
string plotUtil.green_hex '#186F65'
Definition at line 14 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 14 of file plotUtil.py
float plotUtil.LeftMargin 0.15
Definition at line 6 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 6 of file plotUtil.py
string plotUtil.orange_hex '#e99960'
Definition at line 15 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 15 of file plotUtil.py
string plotUtil.pink_hex '#FFC0CB'
Definition at line 17 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 17 of file plotUtil.py
string plotUtil.purple_hex '#7F167F'
Definition at line 16 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 16 of file plotUtil.py
string plotUtil.red_hex '#9A031E'
Definition at line 12 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 12 of file plotUtil.py
float plotUtil.RightMargin 0.08
Definition at line 7 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 7 of file plotUtil.py
float plotUtil.TickSize 0.03
Definition at line 3 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 3 of file plotUtil.py
float plotUtil.TopMargin 0.08
Definition at line 8 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 8 of file plotUtil.py
string plotUtil.yellow_hex '#ffcc66'
Definition at line 18 of file plotUtil.py.
View newest version in sPHENIX GitHub at line 18 of file plotUtil.py