Analysis Software: BDTNode Class Reference
BDTNode Class Reference
Public Member Functions
BDTNode (BDTNode *left, BDTNode *right, int selector, double cutValue, bool cutType, int nodeType, double purity, double response)
virtual ~BDTNode ()
virtual bool GoesRight (const std::vector< double > &inputValues) const
BDTNode * GetRight (void)
virtual bool GoesLeft (const std::vector< double > &inputValues) const
BDTNode * GetLeft (void)
double GetPurity (void) const
int GetNodeType (void) const
double GetResponse (void) const
BDTNode (BDTNode *left, BDTNode *right, int selector, double cutValue, bool cutType, int nodeType, double purity, double response)
virtual ~BDTNode ()
virtual bool GoesRight (const std::vector< double > &inputValues) const
BDTNode * GetRight (void)
virtual bool GoesLeft (const std::vector< double > &inputValues) const
BDTNode * GetLeft (void)
double GetPurity (void) const
int GetNodeType (void) const
double GetResponse (void) const
BDTNode (BDTNode *left, BDTNode *right, int selector, double cutValue, bool cutType, int nodeType, double purity, double response)
virtual ~BDTNode ()
virtual bool GoesRight (const std::vector< double > &inputValues) const
BDTNode * GetRight (void)
virtual bool GoesLeft (const std::vector< double > &inputValues) const
BDTNode * GetLeft (void)
double GetPurity (void) const
int GetNodeType (void) const
double GetResponse (void) const
Private Attributes
BDTNode * fLeft
BDTNode * fRight
int fSelector
double fCutValue
bool fCutType
int fNodeType
double fPurity
double fResponse
Detailed Description
Definition at line 98 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 98 of file TMVAClassification_BDT.class.C
Constructor & Destructor Documentation
BDTNode::BDTNode (BDTNode * left, BDTNode * right, int selector, double cutValue, bool cutType, int nodeType, double purity, double response) inline
Definition at line 103 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 103 of file TMVAClassification_BDT.class.C
BDTNode::~BDTNode () virtual
Definition at line 146 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 146 of file TMVAClassification_BDT.class.C
References fLeft, and fRight.
BDTNode::BDTNode (BDTNode * left, BDTNode * right, int selector, double cutValue, bool cutType, int nodeType, double purity, double response) inline
Definition at line 103 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 103 of file TMVAClassification_BDT.class.C
virtual BDTNode::~BDTNode () virtual
BDTNode::BDTNode (BDTNode * left, BDTNode * right, int selector, double cutValue, bool cutType, int nodeType, double purity, double response) inline
Definition at line 102 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 102 of file TMVAClassification_BDT.class.C
virtual BDTNode::~BDTNode () virtual
Member Function Documentation
BDTNode* BDTNode::GetLeft (void) inline
Definition at line 123 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 123 of file TMVAClassification_BDT.class.C
References fLeft.
BDTNode* BDTNode::GetLeft (void) inline
Definition at line 124 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 124 of file TMVAClassification_BDT.class.C
References fLeft.
Referenced by ReadBDT::GetMvaValue__().
BDTNode* BDTNode::GetLeft (void) inline
Definition at line 124 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 124 of file TMVAClassification_BDT.class.C
References fLeft.
int BDTNode::GetNodeType (void) const inline
Definition at line 129 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 129 of file TMVAClassification_BDT.class.C
References fNodeType.
int BDTNode::GetNodeType (void) const inline
Definition at line 130 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 130 of file TMVAClassification_BDT.class.C
References fNodeType.
Referenced by ReadBDT::GetMvaValue__().
int BDTNode::GetNodeType (void) const inline
Definition at line 130 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 130 of file TMVAClassification_BDT.class.C
References fNodeType.
double BDTNode::GetPurity (void) const inline
Definition at line 127 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 127 of file TMVAClassification_BDT.class.C
References fPurity.
double BDTNode::GetPurity (void) const inline
Definition at line 128 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 128 of file TMVAClassification_BDT.class.C
References fPurity.
double BDTNode::GetPurity (void) const inline
Definition at line 128 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 128 of file TMVAClassification_BDT.class.C
References fPurity.
double BDTNode::GetResponse (void) const inline
Definition at line 130 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 130 of file TMVAClassification_BDT.class.C
References fResponse.
double BDTNode::GetResponse (void) const inline
Definition at line 131 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 131 of file TMVAClassification_BDT.class.C
References fResponse.
double BDTNode::GetResponse (void) const inline
Definition at line 131 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 131 of file TMVAClassification_BDT.class.C
References fResponse.
BDTNode* BDTNode::GetRight (void) inline
Definition at line 119 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 119 of file TMVAClassification_BDT.class.C
References fRight.
BDTNode* BDTNode::GetRight (void) inline
Definition at line 120 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 120 of file TMVAClassification_BDT.class.C
References fRight.
BDTNode* BDTNode::GetRight (void) inline
Definition at line 120 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 120 of file TMVAClassification_BDT.class.C
References fRight.
Referenced by ReadBDT::GetMvaValue__().
virtual bool BDTNode::GoesLeft (const std::vector< double > & inputValues) const virtual
virtual bool BDTNode::GoesLeft (const std::vector< double > & inputValues) const virtual
bool BDTNode::GoesLeft (const std::vector< double > & inputValues) const virtual
Definition at line 163 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 163 of file TMVAClassification_BDT.class.C
References GoesRight().
virtual bool BDTNode::GoesRight (const std::vector< double > & inputValues) const virtual
virtual bool BDTNode::GoesRight (const std::vector< double > & inputValues) const virtual
bool BDTNode::GoesRight (const std::vector< double > & inputValues) const virtual
Definition at line 153 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 153 of file TMVAClassification_BDT.class.C
References fCutType, fCutValue, and fSelector.
Referenced by ReadBDT::GetMvaValue__(), and GoesLeft().
Member Data Documentation
bool BDTNode::fCutType private
Definition at line 139 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 139 of file TMVAClassification_BDT.class.C
Referenced by GoesRight().
double BDTNode::fCutValue private
Definition at line 138 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 138 of file TMVAClassification_BDT.class.C
Referenced by GoesRight().
BDTNode * BDTNode::fLeft private
Definition at line 135 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 135 of file TMVAClassification_BDT.class.C
Referenced by GetLeft(), and ~BDTNode().
int BDTNode::fNodeType private
Definition at line 140 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 140 of file TMVAClassification_BDT.class.C
Referenced by GetNodeType().
double BDTNode::fPurity private
Definition at line 141 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 141 of file TMVAClassification_BDT.class.C
Referenced by GetPurity().
double BDTNode::fResponse private
Definition at line 142 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 142 of file TMVAClassification_BDT.class.C
Referenced by GetResponse().
BDTNode * BDTNode::fRight private
Definition at line 136 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 136 of file TMVAClassification_BDT.class.C
Referenced by GetRight(), and ~BDTNode().
int BDTNode::fSelector private
Definition at line 137 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 137 of file TMVAClassification_BDT.class.C
Referenced by GoesRight().
The documentation for this class was generated from the following files:
analysis/blob/master/ElectronID/src/dataset/Weights_negative/TMVAClassification_BDT.class.C
analysis/blob/master/ElectronID/src/dataset/Weights_positive/TMVAClassification_BDT.class.C
analysis/blob/master/HF-Particle/HFTrigger/weights/woutCaloAndMinTrack/TMVAClassification_BDT.class.C