Analysis Software: cl::Kernel Class Reference
cl::Kernel Class Reference
Kernel interface that implements cl_kernel.
#include <JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp>
Public Member Functions
Kernel (const Program &program, const char *name, cl_int *err=NULL)
Kernel ()
Kernel (const Kernel &kernel)
Kernel & operator= (const Kernel &rhs)
template<typename T >
cl_int getInfo (cl_kernel_info name, T *param) const
template<cl_int name>
detail::param_traits
< detail::cl_kernel_info, name >
::param_type getInfo (cl_int *err=NULL) const
template<typename T >
cl_int getWorkGroupInfo (const Device &device, cl_kernel_work_group_info name, T *param) const
template<cl_int name>
detail::param_traits
< detail::cl_kernel_work_group_info,
name >::param_type getWorkGroupInfo (const Device &device, cl_int *err=NULL) const
template<typename T >
cl_int setArg (cl_uint index, T value)
cl_int setArg (cl_uint index,::size_t size, void *argPtr)
KernelFunctor bind (const CommandQueue &queue, const NDRange &offset, const NDRange &global, const NDRange &local)
KernelFunctor bind (const CommandQueue &queue, const NDRange &global, const NDRange &local)
Public Member Functions inherited from cl::detail::Wrapper< cl_kernel >
Wrapper ()
Wrapper (const Wrapper< cl_type > &rhs)
~Wrapper ()
Wrapper< cl_type > & operator= (const Wrapper< cl_type > &rhs)
cl_type operator() () const
cl_type & operator() ()
Additional Inherited Members
Public Types inherited from cl::detail::Wrapper< cl_kernel >
typedef cl_kernel cl_type
Protected Member Functions inherited from cl::detail::Wrapper< cl_kernel >
cl_int retain () const
cl_int release () const
Protected Attributes inherited from cl::detail::Wrapper< cl_kernel >
cl_type object_
Detailed Description
Kernel interface that implements cl_kernel.
Definition at line 2289 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2289 of file cl.hpp
Constructor & Destructor Documentation
cl::Kernel::Kernel (const Program & program, const char * name, cl_int * err = NULL) inline
Definition at line 2543 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2543 of file cl.hpp
References cl::detail::errHandler(), and acts::error.
cl::Kernel::Kernel () inline
Definition at line 2294 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2294 of file cl.hpp
cl::Kernel::Kernel (const Kernel & kernel) inline
Definition at line 2296 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2296 of file cl.hpp
Member Function Documentation
KernelFunctor cl::Kernel::bind (const CommandQueue & queue, const NDRange & offset, const NDRange & global, const NDRange & local) inline
Definition at line 3355 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3355 of file cl.hpp
KernelFunctor cl::Kernel::bind (const CommandQueue & queue, const NDRange & global, const NDRange & local) inline
Definition at line 3364 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3364 of file cl.hpp
References cl::NullRange.
template<typename T > cl_int cl::Kernel::getInfo (cl_kernel_info name, T * param) const inline
Definition at line 2307 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2307 of file cl.hpp
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_kernel >::object_.
Referenced by getInfo().
template<cl_int name> detail::param_traits<detail::cl_kernel_info, name>::param_type cl::Kernel::getInfo (cl_int * err = NULL) const inline
Definition at line 2316 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2316 of file cl.hpp
References getInfo().
template<typename T > cl_int cl::Kernel::getWorkGroupInfo (const Device & device, cl_kernel_work_group_info name, T * param) const inline
Definition at line 2328 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2328 of file cl.hpp
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_kernel >::object_.
Referenced by getWorkGroupInfo().
template<cl_int name> detail::param_traits<detail::cl_kernel_work_group_info, name>::param_type cl::Kernel::getWorkGroupInfo (const Device & device, cl_int * err = NULL) const inline
Definition at line 2339 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2339 of file cl.hpp
References getWorkGroupInfo().
Kernel& cl::Kernel::operator= (const Kernel & rhs) inline
Definition at line 2298 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2298 of file cl.hpp
References cl::detail::Wrapper< T >::operator=().
template<typename T > cl_int cl::Kernel::setArg (cl_uint index, T value) inline
Definition at line 2351 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2351 of file cl.hpp
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_kernel >::object_.
Referenced by clvisc::BulkInfo::add_data(), clvisc::CLIdeal::half_step_(), clvisc::CLVisc::half_step_israel_stewart_(), clvisc::CLVisc::half_step_visc_(), clvisc::CLVisc::israel_stewart_initialize_(), clvisc::CLIdeal::max_energy_density(), cl::KernelFunctor::operator()(), and clvisc::CLVisc::update_udiff_().
cl_int cl::Kernel::setArg (cl_uint index, ::size_t size, void * argPtr) inline
Definition at line 2362 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2362 of file cl.hpp
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_kernel >::object_.
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp