Analysis Software: DeadHotMapLoader Class Reference
DeadHotMapLoader Class Reference
DeadHotMapLoader loads dead map at inti run.
#include <coresoftware/blob/master/offline/packages/CaloReco/DeadHotMapLoader.h>
Public Member Functions
DeadHotMapLoader (const std::string &detector)
~DeadHotMapLoader () override
int InitRun (PHCompositeNode *topNode) override
const std::string & detector () const
void detector (const std::string &detector)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int process_event (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
std::string m_detector
CDBTTree * m_CDBTTree = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
DeadHotMapLoader loads dead map at inti run.
Definition at line 24 of file DeadHotMapLoader.h.
View newest version in sPHENIX GitHub at line 24 of file DeadHotMapLoader.h
Constructor & Destructor Documentation
DeadHotMapLoader::DeadHotMapLoader (const std::string & detector) explicit
Definition at line 38 of file DeadHotMapLoader.cc.
View newest version in sPHENIX GitHub at line 38 of file DeadHotMapLoader.cc
DeadHotMapLoader::~DeadHotMapLoader () inline override
Definition at line 29 of file DeadHotMapLoader.h.
View newest version in sPHENIX GitHub at line 29 of file DeadHotMapLoader.h
Member Function Documentation
const std::string& DeadHotMapLoader::detector () const inline
Definition at line 33 of file DeadHotMapLoader.h.
View newest version in sPHENIX GitHub at line 33 of file DeadHotMapLoader.h
References m_detector.
Referenced by detector(), Fun4All_Calo(), and Fun4All_Year1().
void DeadHotMapLoader::detector (const std::string & detector) inline
Definition at line 38 of file DeadHotMapLoader.h.
View newest version in sPHENIX GitHub at line 38 of file DeadHotMapLoader.h
References detector(), and m_detector.
int DeadHotMapLoader::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 44 of file DeadHotMapLoader.cc.
View newest version in sPHENIX GitHub at line 44 of file DeadHotMapLoader.cc
References Fun4AllReturnCodes::ABORTRUN, RawTowerDeadMap::addDeadTower(), PHCompositeNode::addNode(), RawTowerDefs::convert_name_to_caloid(), TowerInfoDefs::encode_emcal(), TowerInfoDefs::encode_hcal(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), TowerInfoDefs::getCaloTowerEtaBin(), TowerInfoDefs::getCaloTowerPhiBin(), CDBTTree::GetIntValue(), CDBInterface::getUrl(), i, RawTowerDeadMap::identify(), CDBInterface::instance(), m_CDBTTree, m_detector, Fun4AllBase::Name(), MATSCAN::phibins, PHWHERE, summary::url, and Fun4AllBase::Verbosity().
Member Data Documentation
CDBTTree* DeadHotMapLoader::m_CDBTTree = nullptr private
Definition at line 45 of file DeadHotMapLoader.h.
View newest version in sPHENIX GitHub at line 45 of file DeadHotMapLoader.h
Referenced by InitRun().
std::string DeadHotMapLoader::m_detector private
Definition at line 44 of file DeadHotMapLoader.h.
View newest version in sPHENIX GitHub at line 44 of file DeadHotMapLoader.h
Referenced by detector(), and InitRun().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/DeadHotMapLoader.h
coresoftware/blob/master/offline/packages/CaloReco/DeadHotMapLoader.cc