Analysis Software: KFParticle_truthAndDetTools Class Reference
KFParticle_truthAndDetTools Class Reference
#include <coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.h>
Public Member Functions
KFParticle_truthAndDetTools ()
virtual ~KFParticle_truthAndDetTools ()
SvtxTrack * getTrack (unsigned int track_id, SvtxTrackMap *trackmap)
GlobalVertex * getVertex (unsigned int vertex_id, GlobalVertexMap *vertexmap)
PHG4Particle * getTruthTrack (SvtxTrack *thisTrack, PHCompositeNode *topNode)
void initializeTruthBranches (TTree *m_tree, int daughter_id, const std::string &daughter_number, bool m_constrain_to_vertex_truthMatch)
void fillTruthBranch (PHCompositeNode *topNode, TTree *m_tree, const KFParticle &daughter, int daughter_id, const KFParticle &vertex, bool m_constrain_to_vertex_truthMatch)
void fillGeant4Branch (PHG4Particle *particle, int daughter_id)
void fillHepMCBranch (HepMC::GenParticle *particle, int daughter_id)
int getHepMCInfo (PHCompositeNode *topNode, TTree *m_tree, const KFParticle &daughter, int daughter_id)
void initializeCaloBranches (TTree *m_tree, int daughter_id, const std::string &daughter_number)
void fillCaloBranch (PHCompositeNode *topNode, TTree *m_tree, const KFParticle &daughter, int daughter_id)
void initializeDetectorBranches (TTree *m_tree, int daughter_id, const std::string &daughter_number)
void initializeSubDetectorBranches (TTree *m_tree, const std::string &detectorName, int daughter_id, const std::string &daughter_number)
void fillDetectorBranch (PHCompositeNode *topNode, TTree *m_tree, const KFParticle &daughter, int daughter_id)
void allPVInfo (PHCompositeNode *topNode, TTree *m_tree, const KFParticle &motherParticle, std::vector< KFParticle > daughters, std::vector< KFParticle > intermediates)
void clearVectors ()
Protected Attributes
std::string m_trk_map_node_name_nTuple = "SvtxTrackMap"
std::string m_vtx_map_node_name_nTuple = "SvtxVertexMap"
SvtxEvalStack * m_svtx_evalstack = nullptr
SvtxClusterEval * clustereval = nullptr
SvtxHitEval * hiteval = nullptr
SvtxTrackEval * trackeval = nullptr
SvtxTruthEval * trutheval = nullptr
SvtxVertexEval * vertexeval = nullptr
SvtxTrackMap * dst_trackmap = nullptr
SvtxTrack * track = nullptr
PHG4Particle * g4particle = nullptr
PHG4VtxPoint * g4vertex_point = nullptr
SvtxVertexMap * dst_vertexmap = nullptr
SvtxVertex * vertex = nullptr
TrkrClusterContainer * dst_clustermap = nullptr
int m_num_tracks_nTuple = 0
int m_num_intermediate_states_nTuple = 0
float m_true_daughter_vertex_x [max_tracks] = {0}
float m_true_daughter_vertex_y [max_tracks] = {0}
float m_true_daughter_vertex_z [max_tracks] = {0}
float m_true_daughter_ip [max_tracks] = {0}
float m_true_daughter_ip_xy [max_tracks] = {0}
float m_true_daughter_px [max_tracks] = {0}
float m_true_daughter_py [max_tracks] = {0}
float m_true_daughter_pz [max_tracks] = {0}
float m_true_daughter_p [max_tracks] = {0}
float m_true_daughter_pt [max_tracks] = {0}
int m_true_daughter_id [max_tracks] = {0}
float m_true_daughter_pv_x [max_tracks] = {0}
float m_true_daughter_pv_y [max_tracks] = {0}
float m_true_daughter_pv_z [max_tracks] = {0}
std::vector< int > m_true_daughter_track_history_PDG_ID [max_tracks]
std::vector< float > m_true_daughter_track_history_PDG_mass [max_tracks]
std::vector< float > m_true_daughter_track_history_px [max_tracks]
std::vector< float > m_true_daughter_track_history_py [max_tracks]
std::vector< float > m_true_daughter_track_history_pz [max_tracks]
std::vector< float > m_true_daughter_track_history_pE [max_tracks]
std::vector< float > m_true_daughter_track_history_pT [max_tracks]
float detector_emcal_deltaphi [max_tracks] = {0}
float detector_emcal_deltaeta [max_tracks] = {0}
float detector_emcal_energy_3x3 [max_tracks] = {0}
float detector_emcal_energy_5x5 [max_tracks] = {0}
float detector_emcal_cluster_energy [max_tracks] = {0}
float detector_ihcal_deltaphi [max_tracks] = {0}
float detector_ihcal_deltaeta [max_tracks] = {0}
float detector_ihcal_energy_3x3 [max_tracks] = {0}
float detector_ihcal_energy_5x5 [max_tracks] = {0}
float detector_ihcal_cluster_energy [max_tracks] = {0}
float detector_ohcal_deltaphi [max_tracks] = {0}
float detector_ohcal_deltaeta [max_tracks] = {0}
float detector_ohcal_energy_3x3 [max_tracks] = {0}
float detector_ohcal_energy_5x5 [max_tracks] = {0}
float detector_ohcal_cluster_energy [max_tracks] = {0}
std::vector< float > detector_local_x [max_tracks]
std::vector< float > detector_local_y [max_tracks]
std::vector< float > detector_local_z [max_tracks]
std::vector< int > detector_layer [max_tracks]
std::vector< int > mvtx_staveID [max_tracks]
std::vector< int > mvtx_chipID [max_tracks]
std::vector< int > intt_ladderZID [max_tracks]
std::vector< int > intt_ladderPhiID [max_tracks]
std::vector< int > tpc_sectorID [max_tracks]
std::vector< int > tpc_side [max_tracks]
std::vector< float > allPV_x
std::vector< float > allPV_y
std::vector< float > allPV_z
std::vector< float > allPV_mother_IP
std::vector< float > allPV_mother_IPchi2
std::vector< float > allPV_daughter_IP [max_tracks]
std::vector< float > allPV_daughter_IPchi2 [max_tracks]
std::vector< float > allPV_intermediates_IP [max_tracks]
std::vector< float > allPV_intermediates_IPchi2 [max_tracks]
PHG4TruthInfoContainer * m_truthinfo = nullptr
PHHepMCGenEventMap * m_geneventmap = nullptr
PHHepMCGenEvent * m_genevt = nullptr
Static Protected Attributes
static const int max_tracks = 20
Detailed Description
Definition at line 34 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 34 of file KFParticle_truthAndDetTools.h
Constructor & Destructor Documentation
KFParticle_truthAndDetTools::KFParticle_truthAndDetTools ()
Definition at line 69 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 69 of file KFParticle_truthAndDetTools.cc
KFParticle_truthAndDetTools::~KFParticle_truthAndDetTools () virtual default
Member Function Documentation
void KFParticle_truthAndDetTools::allPVInfo (PHCompositeNode * topNode, TTree * m_tree, const KFParticle & motherParticle, std::vector< KFParticle > daughters, std::vector< KFParticle > intermediates)
Definition at line 610 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 610 of file KFParticle_truthAndDetTools.cc
References allPV_daughter_IP, allPV_daughter_IPchi2, allPV_intermediates_IP, allPV_intermediates_IPchi2, allPV_mother_IP, allPV_mother_IPchi2, allPV_x, allPV_y, allPV_z, KFParticleBase::GetDeviationFromVertex(), GetDeviationFromVertex(), KFParticleBase::GetDistanceFromVertex(), GetDistanceFromVertex(), j, kfpTupleTools, m_vtx_map_node_name_nTuple, and KFParticle_Tools::makeAllPrimaryVertices().
Referenced by KFParticle_nTuple::fillBranch().
void KFParticle_truthAndDetTools::clearVectors ()
Definition at line 642 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 642 of file KFParticle_truthAndDetTools.cc
References allPV_daughter_IP, allPV_daughter_IPchi2, allPV_intermediates_IP, allPV_intermediates_IPchi2, allPV_mother_IP, allPV_mother_IPchi2, allPV_x, allPV_y, allPV_z, detector_layer, detector_local_x, detector_local_y, detector_local_z, i, intt_ladderPhiID, intt_ladderZID, m_num_intermediate_states_nTuple, m_num_tracks_nTuple, m_true_daughter_track_history_PDG_ID, m_true_daughter_track_history_PDG_mass, m_true_daughter_track_history_pE, m_true_daughter_track_history_pT, m_true_daughter_track_history_px, m_true_daughter_track_history_py, m_true_daughter_track_history_pz, mvtx_chipID, mvtx_staveID, tpc_sectorID, and tpc_side.
Referenced by KFParticle_nTuple::fillBranch().
void KFParticle_truthAndDetTools::fillCaloBranch (PHCompositeNode * topNode, TTree * m_tree, const KFParticle & daughter, int daughter_id)
Definition at line 473 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 473 of file KFParticle_truthAndDetTools.cc
References detector_emcal_cluster_energy, detector_emcal_deltaeta, detector_emcal_deltaphi, detector_emcal_energy_3x3, detector_emcal_energy_5x5, detector_ihcal_cluster_energy, detector_ihcal_deltaeta, detector_ihcal_deltaphi, detector_ihcal_energy_3x3, detector_ihcal_energy_5x5, detector_ohcal_cluster_energy, detector_ohcal_deltaeta, detector_ohcal_deltaphi, detector_ohcal_energy_3x3, detector_ohcal_energy_5x5, dst_trackmap, PHNodeIterator::findFirst(), SvtxTrack::get_cal_cluster_e(), SvtxTrack::get_cal_deta(), SvtxTrack::get_cal_dphi(), SvtxTrack::get_cal_energy_3x3(), SvtxTrack::get_cal_energy_5x5(), getTrack(), KFParticleBase::Id(), m_trk_map_node_name_nTuple, and track.
Referenced by KFParticle_nTuple::fillBranch().
void KFParticle_truthAndDetTools::fillDetectorBranch (PHCompositeNode * topNode, TTree * m_tree, const KFParticle & daughter, int daughter_id)
Definition at line 543 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 543 of file KFParticle_truthAndDetTools.cc
References SvtxTrack::begin_cluster_keys(), detector_layer, detector_local_x, detector_local_y, detector_local_z, dst_clustermap, dst_trackmap, SvtxTrack::end_cluster_keys(), TrkrClusterContainer::findCluster(), PHNodeIterator::findFirst(), MvtxDefs::getChipId(), InttDefs::getLadderPhiId(), InttDefs::getLadderZId(), TrkrDefs::getLayer(), TpcDefs::getSectorId(), TpcDefs::getSide(), MvtxDefs::getStaveId(), getTrack(), TrkrDefs::getTrkrId(), TrkrCluster::getX(), TrkrCluster::getY(), TrkrCluster::getZ(), KFParticleBase::Id(), intt_ladderPhiID, intt_ladderZID, TrkrDefs::inttId, m_trk_map_node_name_nTuple, mvtx_chipID, mvtx_staveID, TrkrDefs::mvtxId, tpc_sectorID, tpc_side, TrkrDefs::tpcId, and track.
Referenced by KFParticle_nTuple::fillBranch().
void KFParticle_truthAndDetTools::fillGeant4Branch (PHG4Particle * particle, int daughter_id)
Definition at line 319 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 319 of file KFParticle_truthAndDetTools.cc
References PHG4Particle::get_e(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), m_true_daughter_track_history_PDG_ID, m_true_daughter_track_history_PDG_mass, m_true_daughter_track_history_pE, m_true_daughter_track_history_pT, m_true_daughter_track_history_px, m_true_daughter_track_history_py, m_true_daughter_track_history_pz, and graph_fancy::pT.
Referenced by getHepMCInfo().
void KFParticle_truthAndDetTools::fillHepMCBranch (HepMC::GenParticle * particle, int daughter_id)
Definition at line 332 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 332 of file KFParticle_truthAndDetTools.cc
References m_true_daughter_track_history_PDG_ID, m_true_daughter_track_history_PDG_mass, m_true_daughter_track_history_pE, m_true_daughter_track_history_pT, m_true_daughter_track_history_px, m_true_daughter_track_history_py, and m_true_daughter_track_history_pz.
Referenced by getHepMCInfo().
void KFParticle_truthAndDetTools::fillTruthBranch (PHCompositeNode * topNode, TTree * m_tree, const KFParticle & daughter, int daughter_id, const KFParticle & vertex, bool m_constrain_to_vertex_truthMatch)
Definition at line 181 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 181 of file KFParticle_truthAndDetTools.cc
References KFParticle::Create(), dst_trackmap, dst_vertexmap, GlobalVertex::end_vertexes(), SvtxVertexMap::find(), GlobalVertex::find_vertexes(), PHNodeIterator::findFirst(), g4particle, g4vertex_point, SvtxEvalStack::get_track_eval(), SvtxEvalStack::get_truth_eval(), SvtxTruthEval::get_vertex(), SvtxEvalStack::get_vertex_eval(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_x(), GlobalVertex::get_x(), PHG4VtxPoint::get_y(), GlobalVertex::get_y(), PHG4VtxPoint::get_z(), GlobalVertex::get_z(), KFParticleBase::GetDistanceFromVertex(), KFParticle::GetDistanceFromVertexXY(), PHG4TruthInfoContainer::GetPrimaryParticle(), getTrack(), getTruthTrack(), getVertex(), PHG4TruthInfoContainer::GetVtx(), KFParticleBase::Id(), m_svtx_evalstack, m_trk_map_node_name_nTuple, m_true_daughter_id, m_true_daughter_ip, m_true_daughter_ip_xy, m_true_daughter_p, m_true_daughter_pt, m_true_daughter_pv_x, m_true_daughter_pv_y, m_true_daughter_pv_z, m_true_daughter_px, m_true_daughter_py, m_true_daughter_pz, m_true_daughter_vertex_x, m_true_daughter_vertex_y, m_true_daughter_vertex_z, m_truthinfo, m_vtx_map_node_name_nTuple, SvtxVertexEval::max_truth_point_by_ntracks(), GlobalVertex::SVTX, track, trackeval, trutheval, and vertexeval.
Referenced by KFParticle_nTuple::fillBranch().
int KFParticle_truthAndDetTools::getHepMCInfo (PHCompositeNode * topNode, TTree * m_tree, const KFParticle & daughter, int daughter_id)
Definition at line 345 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 345 of file KFParticle_truthAndDetTools.cc
References parse_cmake_options::begin, dst_trackmap, end, fillGeant4Branch(), fillHepMCBranch(), PHNodeIterator::findFirst(), g4particle, PHHepMCGenEventMap::get(), PHHepMCGenEvent::getEvent(), PHG4TruthInfoContainer::GetParticle(), getTrack(), getTruthTrack(), KFParticleBase::Id(), m_geneventmap, m_genevt, m_trk_map_node_name_nTuple, m_truthinfo, merge_hashes::p, and track.
Referenced by KFParticle_nTuple::fillBranch().
SvtxTrack * KFParticle_truthAndDetTools::getTrack (unsigned int track_id, SvtxTrackMap * trackmap)
Definition at line 76 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 76 of file KFParticle_truthAndDetTools.cc
Referenced by fillCaloBranch(), fillDetectorBranch(), KFParticle_DST::fillParticleNode_Track(), fillTruthBranch(), and getHepMCInfo().
PHG4Particle * KFParticle_truthAndDetTools::getTruthTrack (SvtxTrack * thisTrack, PHCompositeNode * topNode)
Definition at line 98 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 98 of file KFParticle_truthAndDetTools.cc
References PHNodeIterator::findFirst(), SvtxPHG4ParticleMap_v1::get(), SvtxTrack::get_id(), SvtxEvalStack::get_track_eval(), SvtxEvalStack::get_truth_eval(), SvtxEvalStack::get_vertex_eval(), PHG4TruthInfoContainer::GetParticle(), m_svtx_evalstack, m_truthinfo, SvtxTrackEval::max_truth_particle_by_nclusters(), SvtxEvalStack::next_event(), particle, trackeval, trutheval, and vertexeval.
Referenced by fillTruthBranch(), and getHepMCInfo().
GlobalVertex * KFParticle_truthAndDetTools::getVertex (unsigned int vertex_id, GlobalVertexMap * vertexmap)
Definition at line 91 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 91 of file KFParticle_truthAndDetTools.cc
References GlobalVertexMap::get().
Referenced by fillTruthBranch().
void KFParticle_truthAndDetTools::initializeCaloBranches (TTree * m_tree, int daughter_id, const std::string & daughter_number)
Definition at line 454 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 454 of file KFParticle_truthAndDetTools.cc
References detector_emcal_cluster_energy, detector_emcal_deltaeta, detector_emcal_deltaphi, detector_emcal_energy_3x3, detector_emcal_energy_5x5, detector_ihcal_cluster_energy, detector_ihcal_deltaeta, detector_ihcal_deltaphi, detector_ihcal_energy_3x3, detector_ihcal_energy_5x5, detector_ohcal_cluster_energy, detector_ohcal_deltaeta, detector_ohcal_deltaphi, detector_ohcal_energy_3x3, and detector_ohcal_energy_5x5.
Referenced by KFParticle_nTuple::initializeBranches().
void KFParticle_truthAndDetTools::initializeDetectorBranches (TTree * m_tree, int daughter_id, const std::string & daughter_number)
Definition at line 508 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 508 of file KFParticle_truthAndDetTools.cc
References detector_layer, detector_local_x, detector_local_y, detector_local_z, and initializeSubDetectorBranches().
Referenced by KFParticle_nTuple::initializeBranches().
void KFParticle_truthAndDetTools::initializeSubDetectorBranches (TTree * m_tree, const std::string & detectorName, int daughter_id, const std::string & daughter_number)
Definition at line 524 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 524 of file KFParticle_truthAndDetTools.cc
References intt_ladderPhiID, intt_ladderZID, mvtx_chipID, mvtx_staveID, tpc_sectorID, and tpc_side.
Referenced by initializeDetectorBranches().
void KFParticle_truthAndDetTools::initializeTruthBranches (TTree * m_tree, int daughter_id, const std::string & daughter_number, bool m_constrain_to_vertex_truthMatch)
Definition at line 150 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 150 of file KFParticle_truthAndDetTools.cc
References m_true_daughter_id, m_true_daughter_ip, m_true_daughter_ip_xy, m_true_daughter_p, m_true_daughter_pt, m_true_daughter_pv_x, m_true_daughter_pv_y, m_true_daughter_pv_z, m_true_daughter_px, m_true_daughter_py, m_true_daughter_pz, m_true_daughter_track_history_PDG_ID, m_true_daughter_track_history_PDG_mass, m_true_daughter_track_history_pE, m_true_daughter_track_history_pT, m_true_daughter_track_history_px, m_true_daughter_track_history_py, m_true_daughter_track_history_pz, m_true_daughter_vertex_x, m_true_daughter_vertex_y, and m_true_daughter_vertex_z.
Referenced by KFParticle_nTuple::initializeBranches().
Member Data Documentation
std::vector<float> KFParticle_truthAndDetTools::allPV_daughter_IP[max_tracks] protected
Definition at line 148 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 148 of file KFParticle_truthAndDetTools.h
Referenced by allPVInfo(), clearVectors(), and KFParticle_nTuple::initializeBranches().
std::vector<float> KFParticle_truthAndDetTools::allPV_daughter_IPchi2[max_tracks] protected
Definition at line 149 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 149 of file KFParticle_truthAndDetTools.h
Referenced by allPVInfo(), clearVectors(), and KFParticle_nTuple::initializeBranches().
std::vector<float> KFParticle_truthAndDetTools::allPV_intermediates_IP[max_tracks] protected
Definition at line 150 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 150 of file KFParticle_truthAndDetTools.h
Referenced by allPVInfo(), clearVectors(), and KFParticle_nTuple::initializeBranches().
std::vector<float> KFParticle_truthAndDetTools::allPV_intermediates_IPchi2[max_tracks] protected
Definition at line 151 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 151 of file KFParticle_truthAndDetTools.h
Referenced by allPVInfo(), clearVectors(), and KFParticle_nTuple::initializeBranches().
std::vector<float> KFParticle_truthAndDetTools::allPV_mother_IP protected
Definition at line 146 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 146 of file KFParticle_truthAndDetTools.h
Referenced by allPVInfo(), clearVectors(), and KFParticle_nTuple::initializeBranches().
std::vector<float> KFParticle_truthAndDetTools::allPV_mother_IPchi2 protected
Definition at line 147 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 147 of file KFParticle_truthAndDetTools.h
Referenced by allPVInfo(), clearVectors(), and KFParticle_nTuple::initializeBranches().
std::vector<float> KFParticle_truthAndDetTools::allPV_x protected
Definition at line 143 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 143 of file KFParticle_truthAndDetTools.h
Referenced by allPVInfo(), clearVectors(), and KFParticle_nTuple::initializeBranches().
std::vector<float> KFParticle_truthAndDetTools::allPV_y protected
Definition at line 144 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 144 of file KFParticle_truthAndDetTools.h
Referenced by allPVInfo(), clearVectors(), and KFParticle_nTuple::initializeBranches().
std::vector<float> KFParticle_truthAndDetTools::allPV_z protected
Definition at line 145 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 145 of file KFParticle_truthAndDetTools.h
Referenced by allPVInfo(), clearVectors(), and KFParticle_nTuple::initializeBranches().
SvtxClusterEval* KFParticle_truthAndDetTools::clustereval = nullptr protected
Definition at line 71 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 71 of file KFParticle_truthAndDetTools.h
float KFParticle_truthAndDetTools::detector_emcal_cluster_energy[max_tracks] = {0} protected
Definition at line 120 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 120 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), and initializeCaloBranches().
float KFParticle_truthAndDetTools::detector_emcal_deltaeta[max_tracks] = {0} protected
Definition at line 117 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 117 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), and initializeCaloBranches().
float KFParticle_truthAndDetTools::detector_emcal_deltaphi[max_tracks] = {0} protected
Definition at line 116 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 116 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), and initializeCaloBranches().
float KFParticle_truthAndDetTools::detector_emcal_energy_3x3[max_tracks] = {0} protected
Definition at line 118 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 118 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), and initializeCaloBranches().
float KFParticle_truthAndDetTools::detector_emcal_energy_5x5[max_tracks] = {0} protected
Definition at line 119 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 119 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), and initializeCaloBranches().
float KFParticle_truthAndDetTools::detector_ihcal_cluster_energy[max_tracks] = {0} protected
Definition at line 125 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 125 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), and initializeCaloBranches().
float KFParticle_truthAndDetTools::detector_ihcal_deltaeta[max_tracks] = {0} protected
Definition at line 122 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 122 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), and initializeCaloBranches().
float KFParticle_truthAndDetTools::detector_ihcal_deltaphi[max_tracks] = {0} protected
Definition at line 121 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 121 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), and initializeCaloBranches().
float KFParticle_truthAndDetTools::detector_ihcal_energy_3x3[max_tracks] = {0} protected
Definition at line 123 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 123 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), and initializeCaloBranches().
float KFParticle_truthAndDetTools::detector_ihcal_energy_5x5[max_tracks] = {0} protected
Definition at line 124 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 124 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), and initializeCaloBranches().
std::vector<int> KFParticle_truthAndDetTools::detector_layer[max_tracks] protected
Definition at line 135 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 135 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), fillDetectorBranch(), and initializeDetectorBranches().
std::vector<float> KFParticle_truthAndDetTools::detector_local_x[max_tracks] protected
Definition at line 132 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 132 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), fillDetectorBranch(), and initializeDetectorBranches().
std::vector<float> KFParticle_truthAndDetTools::detector_local_y[max_tracks] protected
Definition at line 133 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 133 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), fillDetectorBranch(), and initializeDetectorBranches().
std::vector<float> KFParticle_truthAndDetTools::detector_local_z[max_tracks] protected
Definition at line 134 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 134 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), fillDetectorBranch(), and initializeDetectorBranches().
float KFParticle_truthAndDetTools::detector_ohcal_cluster_energy[max_tracks] = {0} protected
Definition at line 130 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 130 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), and initializeCaloBranches().
float KFParticle_truthAndDetTools::detector_ohcal_deltaeta[max_tracks] = {0} protected
Definition at line 127 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 127 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), and initializeCaloBranches().
float KFParticle_truthAndDetTools::detector_ohcal_deltaphi[max_tracks] = {0} protected
Definition at line 126 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 126 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), and initializeCaloBranches().
float KFParticle_truthAndDetTools::detector_ohcal_energy_3x3[max_tracks] = {0} protected
Definition at line 128 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 128 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), and initializeCaloBranches().
float KFParticle_truthAndDetTools::detector_ohcal_energy_5x5[max_tracks] = {0} protected
Definition at line 129 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 129 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), and initializeCaloBranches().
TrkrClusterContainer* KFParticle_truthAndDetTools::dst_clustermap = nullptr protected
Definition at line 86 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 86 of file KFParticle_truthAndDetTools.h
Referenced by fillDetectorBranch().
SvtxTrackMap* KFParticle_truthAndDetTools::dst_trackmap = nullptr protected
Definition at line 77 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 77 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), fillDetectorBranch(), fillTruthBranch(), and getHepMCInfo().
SvtxVertexMap* KFParticle_truthAndDetTools::dst_vertexmap = nullptr protected
Definition at line 83 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 83 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch().
PHG4Particle* KFParticle_truthAndDetTools::g4particle = nullptr protected
Definition at line 80 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 80 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and getHepMCInfo().
PHG4VtxPoint* KFParticle_truthAndDetTools::g4vertex_point = nullptr protected
Definition at line 81 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 81 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch().
SvtxHitEval* KFParticle_truthAndDetTools::hiteval = nullptr protected
Definition at line 72 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 72 of file KFParticle_truthAndDetTools.h
std::vector<int> KFParticle_truthAndDetTools::intt_ladderPhiID[max_tracks] protected
Definition at line 139 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 139 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), fillDetectorBranch(), and initializeSubDetectorBranches().
std::vector<int> KFParticle_truthAndDetTools::intt_ladderZID[max_tracks] protected
Definition at line 138 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 138 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), fillDetectorBranch(), and initializeSubDetectorBranches().
PHHepMCGenEventMap* KFParticle_truthAndDetTools::m_geneventmap = nullptr protected
Definition at line 154 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 154 of file KFParticle_truthAndDetTools.h
Referenced by getHepMCInfo().
PHHepMCGenEvent* KFParticle_truthAndDetTools::m_genevt = nullptr protected
Definition at line 155 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 155 of file KFParticle_truthAndDetTools.h
Referenced by getHepMCInfo().
int KFParticle_truthAndDetTools::m_num_intermediate_states_nTuple = 0 protected
Definition at line 89 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 89 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), KFParticle_nTuple::fillBranch(), KFParticle_nTuple::initializeBranches(), and KFParticle_sPHENIX::setNumberOfIntermediateStates().
int KFParticle_truthAndDetTools::m_num_tracks_nTuple = 0 protected
Definition at line 88 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 88 of file KFParticle_truthAndDetTools.h
Referenced by KFParticle_nTuple::calc_secondary_vertex_mass_noPID(), clearVectors(), KFParticle_nTuple::fillBranch(), KFParticle_nTuple::initializeBranches(), and KFParticle_sPHENIX::setNumberOfTracks().
SvtxEvalStack* KFParticle_truthAndDetTools::m_svtx_evalstack = nullptr protected
Definition at line 70 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 70 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and getTruthTrack().
std::string KFParticle_truthAndDetTools::m_trk_map_node_name_nTuple = "SvtxTrackMap" protected
Definition at line 67 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 67 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), fillDetectorBranch(), fillTruthBranch(), getHepMCInfo(), and KFParticle_sPHENIX::setTrackMapNodeName().
int KFParticle_truthAndDetTools::m_true_daughter_id[max_tracks] = {0} protected
Definition at line 103 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 103 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_ip[max_tracks] = {0} protected
Definition at line 96 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 96 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_ip_xy[max_tracks] = {0} protected
Definition at line 97 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 97 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_p[max_tracks] = {0} protected
Definition at line 101 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 101 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_pt[max_tracks] = {0} protected
Definition at line 102 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 102 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_pv_x[max_tracks] = {0} protected
Definition at line 104 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 104 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_pv_y[max_tracks] = {0} protected
Definition at line 105 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 105 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_pv_z[max_tracks] = {0} protected
Definition at line 106 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 106 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_px[max_tracks] = {0} protected
Definition at line 98 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 98 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_py[max_tracks] = {0} protected
Definition at line 99 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 99 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_pz[max_tracks] = {0} protected
Definition at line 100 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 100 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
std::vector<int> KFParticle_truthAndDetTools::m_true_daughter_track_history_PDG_ID[max_tracks] protected
Definition at line 108 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 108 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), fillGeant4Branch(), fillHepMCBranch(), and initializeTruthBranches().
std::vector<float> KFParticle_truthAndDetTools::m_true_daughter_track_history_PDG_mass[max_tracks] protected
Definition at line 109 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 109 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), fillGeant4Branch(), fillHepMCBranch(), and initializeTruthBranches().
std::vector<float> KFParticle_truthAndDetTools::m_true_daughter_track_history_pE[max_tracks] protected
Definition at line 113 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 113 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), fillGeant4Branch(), fillHepMCBranch(), and initializeTruthBranches().
std::vector<float> KFParticle_truthAndDetTools::m_true_daughter_track_history_pT[max_tracks] protected
Definition at line 114 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 114 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), fillGeant4Branch(), fillHepMCBranch(), and initializeTruthBranches().
std::vector<float> KFParticle_truthAndDetTools::m_true_daughter_track_history_px[max_tracks] protected
Definition at line 110 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 110 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), fillGeant4Branch(), fillHepMCBranch(), and initializeTruthBranches().
std::vector<float> KFParticle_truthAndDetTools::m_true_daughter_track_history_py[max_tracks] protected
Definition at line 111 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 111 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), fillGeant4Branch(), fillHepMCBranch(), and initializeTruthBranches().
std::vector<float> KFParticle_truthAndDetTools::m_true_daughter_track_history_pz[max_tracks] protected
Definition at line 112 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 112 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), fillGeant4Branch(), fillHepMCBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_vertex_x[max_tracks] = {0} protected
Definition at line 93 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 93 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_vertex_y[max_tracks] = {0} protected
Definition at line 94 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 94 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_vertex_z[max_tracks] = {0} protected
Definition at line 95 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 95 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
PHG4TruthInfoContainer* KFParticle_truthAndDetTools::m_truthinfo = nullptr protected
Definition at line 153 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 153 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), getHepMCInfo(), and getTruthTrack().
std::string KFParticle_truthAndDetTools::m_vtx_map_node_name_nTuple = "SvtxVertexMap" protected
Definition at line 68 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 68 of file KFParticle_truthAndDetTools.h
Referenced by allPVInfo(), KFParticle_nTuple::fillBranch(), fillTruthBranch(), and KFParticle_sPHENIX::setVertexMapNodeName().
const int KFParticle_truthAndDetTools::max_tracks = 20 static protected
Definition at line 91 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 91 of file KFParticle_truthAndDetTools.h
std::vector<int> KFParticle_truthAndDetTools::mvtx_chipID[max_tracks] protected
Definition at line 137 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 137 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), fillDetectorBranch(), and initializeSubDetectorBranches().
std::vector<int> KFParticle_truthAndDetTools::mvtx_staveID[max_tracks] protected
Definition at line 136 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 136 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), fillDetectorBranch(), and initializeSubDetectorBranches().
std::vector<int> KFParticle_truthAndDetTools::tpc_sectorID[max_tracks] protected
Definition at line 140 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 140 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), fillDetectorBranch(), and initializeSubDetectorBranches().
std::vector<int> KFParticle_truthAndDetTools::tpc_side[max_tracks] protected
Definition at line 141 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 141 of file KFParticle_truthAndDetTools.h
Referenced by clearVectors(), fillDetectorBranch(), and initializeSubDetectorBranches().
SvtxTrack* KFParticle_truthAndDetTools::track = nullptr protected
Definition at line 78 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 78 of file KFParticle_truthAndDetTools.h
Referenced by fillCaloBranch(), fillDetectorBranch(), fillTruthBranch(), and getHepMCInfo().
SvtxTrackEval* KFParticle_truthAndDetTools::trackeval = nullptr protected
Definition at line 73 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 73 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and getTruthTrack().
SvtxTruthEval* KFParticle_truthAndDetTools::trutheval = nullptr protected
Definition at line 74 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 74 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and getTruthTrack().
SvtxVertex* KFParticle_truthAndDetTools::vertex = nullptr protected
Definition at line 84 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 84 of file KFParticle_truthAndDetTools.h
Referenced by KFParticle_sPHENIX::process_event().
SvtxVertexEval* KFParticle_truthAndDetTools::vertexeval = nullptr protected
Definition at line 75 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 75 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and getTruthTrack().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.h
coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc