Analysis Software: Acts::VolumeConfig Struct Reference
Acts::VolumeConfig Struct Reference
VolumeConfig struct to understand the layer config.
#include <acts/blob/sPHENIX/Core/include/Acts/Geometry/CylinderVolumeBuilder.hpp>
Public Member Functions
VolumeConfig ()
Default constructor.
void adaptZ (const VolumeConfig &lConfig)
void adaptR (const VolumeConfig &lConfig)
void adapt (const VolumeConfig &lConfig)
void midPointAttachZ (VolumeConfig &lConfig)
void attachZ (const VolumeConfig &lConfig)
bool overlapsInR (const VolumeConfig &vConfig) const
bool overlapsInZ (const VolumeConfig &vConfig) const
bool wraps (const VolumeConfig &vConfig) const
bool contains (const VolumeConfig &vConfig) const
bool containsInR (const VolumeConfig &vConfig) const
bool containsInZ (const VolumeConfig &vConfig) const
std::string toString () const
Method for output formatting.
operator bool () const
Conversion operator to bool.
Public Attributes
bool present {false}
layers are present
bool wrapping {false}
in what way they are binned
double rMin
min parameter r
double rMax
max parameter r
double zMin
min parameter z
double zMax
max parameter z
LayerVector layers
the layers you have
MutableTrackingVolumeVector volumes
the confined volumes you have
Detailed Description
VolumeConfig struct to understand the layer config.
Definition at line 47 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 47 of file CylinderVolumeBuilder.hpp
Constructor & Destructor Documentation
Acts::VolumeConfig::VolumeConfig () inline
Default constructor.
Definition at line 58 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 58 of file CylinderVolumeBuilder.hpp
Member Function Documentation
void Acts::VolumeConfig::adapt (const VolumeConfig & lConfig) inline
Adapt to the dimensions of another config it will take the maximum/minimum values and just overwrite them
Parameters
[in] lConfig is the config to which it should be adapded
Definition at line 91 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 91 of file CylinderVolumeBuilder.hpp
References adaptR(), and adaptZ().
Referenced by Acts::WrappingConfig::configureContainerVolume().
void Acts::VolumeConfig::adaptR (const VolumeConfig & lConfig) inline
Adapt to the dimensions of another config in R it will take the maximum/minimum values and just overwrite them
Parameters
[in] lConfig is the config to which it should be adapded
Definition at line 80 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 80 of file CylinderVolumeBuilder.hpp
References Acts::UnitConstants::min, rMax, and rMin.
Referenced by adapt(), Acts::WrappingConfig::configureContainerVolume(), and Acts::WrappingConfig::wrapInsertAttach().
void Acts::VolumeConfig::adaptZ (const VolumeConfig & lConfig) inline
Adapt to the dimensions of another config in Z it will take the maximum/minimum values and just overwrite them
Parameters
[in] lConfig is the config to which it should be adapded
Definition at line 69 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 69 of file CylinderVolumeBuilder.hpp
References Acts::UnitConstants::min, zMax, and zMin.
Referenced by adapt(), and Acts::WrappingConfig::wrapInsertAttach().
void Acts::VolumeConfig::attachZ (const VolumeConfig & lConfig) inline
Attach method - const it attaches the one volume config to the other one
Parameters
[in] lConfig is the confit to which it should be attached
Definition at line 118 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 118 of file CylinderVolumeBuilder.hpp
References zMax, and zMin.
Referenced by Acts::WrappingConfig::wrapInsertAttach().
bool Acts::VolumeConfig::contains (const VolumeConfig & vConfig) const inline
Check if contained full set
Parameters
[in] vConfig is the config against which is checked
Definition at line 162 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 162 of file CylinderVolumeBuilder.hpp
References containsInR(), and containsInZ().
Referenced by Acts::Test::BOOST_DATA_TEST_CASE().
bool Acts::VolumeConfig::containsInR (const VolumeConfig & vConfig) const inline
Check if contained radially
Parameters
[in] vConfig is the config against which is checked
Definition at line 169 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 169 of file CylinderVolumeBuilder.hpp
References rMax, and rMin.
Referenced by Acts::Test::BOOST_DATA_TEST_CASE(), contains(), and wraps().
bool Acts::VolumeConfig::containsInZ (const VolumeConfig & vConfig) const inline
Check if contained longitudinally
Parameters
[in] vConfig is the config against which is checked
Definition at line 176 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 176 of file CylinderVolumeBuilder.hpp
References zMax, and zMin.
Referenced by Acts::Test::BOOST_DATA_TEST_CASE(), and contains().
void Acts::VolumeConfig::midPointAttachZ (VolumeConfig & lConfig) inline
Attach method - non-const it attaches the one volume config to the other one in Z this is the non-cost method, i.e. the mid point is used
Parameters
[in] lConfig is the config to which it should be attached
Note
lConfig will be changed
Definition at line 102 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 102 of file CylinderVolumeBuilder.hpp
References zMax, and zMin.
Referenced by Acts::WrappingConfig::configureContainerVolume().
Acts::VolumeConfig::operator bool () const inline
Conversion operator to bool.
Definition at line 189 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 189 of file CylinderVolumeBuilder.hpp
References present.
bool Acts::VolumeConfig::overlapsInR (const VolumeConfig & vConfig) const inline
Overlap check radially
Parameters
[in] vConfig is the config against which is checked
Returns
boolean if the overlap in r exists
Definition at line 130 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 130 of file CylinderVolumeBuilder.hpp
References Acts::UnitConstants::min, present, rMax, and rMin.
Referenced by Acts::Test::BOOST_DATA_TEST_CASE().
bool Acts::VolumeConfig::overlapsInZ (const VolumeConfig & vConfig) const inline
Overlap check longitudinally
Parameters
[in] vConfig is the config against which is checked
Returns
boolean if the overlap in z exists
Definition at line 141 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 141 of file CylinderVolumeBuilder.hpp
References Acts::UnitConstants::min, present, zMax, and zMin.
Referenced by Acts::Test::BOOST_DATA_TEST_CASE().
std::string Acts::VolumeConfig::toString () const inline
Method for output formatting.
for screen output
Definition at line 181 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 181 of file CylinderVolumeBuilder.hpp
References rMax, rMin, zMax, and zMin.
Referenced by Acts::WrappingConfig::toString(), and Acts::CylinderVolumeBuilder::trackingVolume().
bool Acts::VolumeConfig::wraps (const VolumeConfig & vConfig) const inline
Compatibility check full set
Parameters
[in] vConfig is the config against which is checked
Returns
boolean if the current volume wraps the vConfig fully
Definition at line 152 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 152 of file CylinderVolumeBuilder.hpp
References containsInR(), zMax, and zMin.
Referenced by Acts::Test::BOOST_DATA_TEST_CASE(), and Acts::WrappingConfig::wrapInsertAttach().
Member Data Documentation
LayerVector Acts::VolumeConfig::layers
the layers you have
Definition at line 54 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 54 of file CylinderVolumeBuilder.hpp
Referenced by Acts::CylinderVolumeBuilder::analyzeContent(), and Acts::CylinderVolumeBuilder::trackingVolume().
bool Acts::VolumeConfig::present {false}
layers are present
Definition at line 48 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 48 of file CylinderVolumeBuilder.hpp
Referenced by Acts::CylinderVolumeBuilder::analyzeContent(), Acts::Test::BOOST_DATA_TEST_CASE(), Acts::WrappingConfig::configureContainerVolume(), operator bool(), overlapsInR(), overlapsInZ(), Acts::CylinderVolumeBuilder::trackingVolume(), and Acts::WrappingConfig::wrapInsertAttach().
double Acts::VolumeConfig::rMax
max parameter r
Definition at line 51 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 51 of file CylinderVolumeBuilder.hpp
Referenced by adaptR(), Acts::CylinderVolumeBuilder::analyzeContent(), Acts::Test::BOOST_DATA_TEST_CASE(), containsInR(), overlapsInR(), toString(), Acts::CylinderVolumeBuilder::trackingVolume(), and Acts::WrappingConfig::wrapInsertAttach().
double Acts::VolumeConfig::rMin
min parameter r
Definition at line 50 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 50 of file CylinderVolumeBuilder.hpp
Referenced by adaptR(), Acts::CylinderVolumeBuilder::analyzeContent(), Acts::Test::BOOST_DATA_TEST_CASE(), containsInR(), overlapsInR(), toString(), Acts::CylinderVolumeBuilder::trackingVolume(), and Acts::WrappingConfig::wrapInsertAttach().
MutableTrackingVolumeVector Acts::VolumeConfig::volumes
the confined volumes you have
Definition at line 55 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 55 of file CylinderVolumeBuilder.hpp
Referenced by Acts::CylinderVolumeBuilder::analyzeContent(), and Acts::CylinderVolumeBuilder::trackingVolume().
bool Acts::VolumeConfig::wrapping {false}
in what way they are binned
Definition at line 49 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 49 of file CylinderVolumeBuilder.hpp
double Acts::VolumeConfig::zMax
max parameter z
Definition at line 53 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 53 of file CylinderVolumeBuilder.hpp
Referenced by adaptZ(), Acts::CylinderVolumeBuilder::analyzeContent(), attachZ(), Acts::Test::BOOST_DATA_TEST_CASE(), containsInZ(), midPointAttachZ(), overlapsInZ(), toString(), Acts::CylinderVolumeBuilder::trackingVolume(), Acts::WrappingConfig::wrapInsertAttach(), and wraps().
double Acts::VolumeConfig::zMin
min parameter z
Definition at line 52 of file CylinderVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 52 of file CylinderVolumeBuilder.hpp
Referenced by adaptZ(), Acts::CylinderVolumeBuilder::analyzeContent(), attachZ(), Acts::Test::BOOST_DATA_TEST_CASE(), containsInZ(), midPointAttachZ(), overlapsInZ(), toString(), Acts::CylinderVolumeBuilder::trackingVolume(), Acts::WrappingConfig::wrapInsertAttach(), and wraps().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Geometry/CylinderVolumeBuilder.hpp