Analysis Software: ActsExamples::RootMaterialWriter Class Reference
ActsExamples::RootMaterialWriter Class Reference
Material decorator from Root format.
#include <acts/blob/sPHENIX/Examples/Io/Root/include/ActsExamples/Io/Root/RootMaterialWriter.hpp>
Classes
class Config
Public Member Functions
RootMaterialWriter (const Config &config, Acts::Logging::Level level)
~RootMaterialWriter () override
Virtual destructor.
void writeMaterial (const Acts::DetectorMaterialMaps &detMaterial) override
void write (const Acts::TrackingGeometry &tGeometry)
const Config & config () const
Get readonly access to the config parameters.
Public Member Functions inherited from ActsExamples::IMaterialWriter
virtual ~IMaterialWriter ()=default
Virtual Destructor.
Private Member Functions
void collectMaterial (const Acts::TrackingVolume &tVolume, Acts::DetectorMaterialMaps &detMatMap)
void collectMaterial (const Acts::Layer &tLayer, Acts::DetectorMaterialMaps &detMatMap)
const Acts::Logger & logger () const
Private access to the logging instance.
Private Attributes
Config m_cfg
The config class.
std::unique_ptr< const
Acts::Logger > m_logger
The logger instance.
TFile * m_outputFile {nullptr}
Detailed Description
Material decorator from Root format.
This reads in material maps for surfaces and volumes from a root file
Definition at line 51 of file RootMaterialWriter.hpp.
View newest version in sPHENIX GitHub at line 51 of file RootMaterialWriter.hpp
Constructor & Destructor Documentation
ActsExamples::RootMaterialWriter::RootMaterialWriter (const Config & config, Acts::Logging::Level level)
Constructor
Parameters
config The configuration struct
level The log level
Definition at line 41 of file RootMaterialWriter.cpp.
View newest version in sPHENIX GitHub at line 41 of file RootMaterialWriter.cpp
References Acts::getDefaultLogger().
ActsExamples::RootMaterialWriter::~RootMaterialWriter () override
Virtual destructor.
Definition at line 318 of file RootMaterialWriter.cpp.
View newest version in sPHENIX GitHub at line 318 of file RootMaterialWriter.cpp
Member Function Documentation
void ActsExamples::RootMaterialWriter::collectMaterial (const Acts::TrackingVolume & tVolume, Acts::DetectorMaterialMaps & detMatMap) private
Collect the material from the tracking geometry
Parameters
tVolume The TrackingVolume for the material to be collected
[in,out] detMatMap the map to be filled
Definition at line 336 of file RootMaterialWriter.cpp.
View newest version in sPHENIX GitHub at line 336 of file RootMaterialWriter.cpp
References Acts::BinnedArray< T >::arrayObjects(), Acts::TrackingVolume::boundarySurfaces(), Acts::TrackingVolume::confinedLayers(), Acts::TrackingVolume::confinedVolumes(), Acts::GeometryObject::geometryId(), m_cfg(), and Acts::TrackingVolume::volumeMaterialSharedPtr().
void ActsExamples::RootMaterialWriter::collectMaterial (const Acts::Layer & tLayer, Acts::DetectorMaterialMaps & detMatMap) private
Collect the material from the tracking geometry
Parameters
tLayer The TrackingVolume for the material to be collected
[in,out] detMatMap the map to be filled
Definition at line 370 of file RootMaterialWriter.cpp.
View newest version in sPHENIX GitHub at line 370 of file RootMaterialWriter.cpp
References Acts::Layer::approachDescriptor(), Acts::ApproachDescriptor::containedSurfaces(), m_cfg(), Acts::Layer::surfaceArray(), Acts::Surface::surfaceMaterialSharedPtr(), Acts::Layer::surfaceRepresentation(), and Acts::SurfaceArray::surfaces().
const Config& ActsExamples::RootMaterialWriter::config () const inline
Get readonly access to the config parameters.
Definition at line 134 of file RootMaterialWriter.hpp.
View newest version in sPHENIX GitHub at line 134 of file RootMaterialWriter.hpp
References m_cfg.
const Acts::Logger& ActsExamples::RootMaterialWriter::logger () const inline private
Private access to the logging instance.
Definition at line 158 of file RootMaterialWriter.hpp.
View newest version in sPHENIX GitHub at line 158 of file RootMaterialWriter.hpp
References m_logger.
void ActsExamples::RootMaterialWriter::write (const Acts::TrackingGeometry & tGeometry)
Write out the material map from Geometry
Parameters
tGeometry is the TrackingGeometry
Definition at line 324 of file RootMaterialWriter.cpp.
View newest version in sPHENIX GitHub at line 324 of file RootMaterialWriter.cpp
References Acts::TrackingGeometry::highestTrackingVolume(), and Acts::Test::hVolume.
Referenced by processGeometry().
void ActsExamples::RootMaterialWriter::writeMaterial (const Acts::DetectorMaterialMaps & detMaterial) override virtual
Write out the material map
Parameters
detMaterial is the SurfaceMaterial and VolumeMaterial maps
Implements ActsExamples::IMaterialWriter.
Definition at line 62 of file RootMaterialWriter.cpp.
View newest version in sPHENIX GitHub at line 62 of file RootMaterialWriter.cpp
References A, ACTS_VERBOSE, Acts::GeometryIdentifier::approach(), Acts::detail::Grid< T, Axes >::at(), KFPMath::b, b1, Acts::BinUtility::binningData(), bins, Acts::BinUtility::bins(), Acts::BinnedSurfaceMaterial::binUtility(), Acts::GeometryIdentifier::boundary(), Acts::MaterialMapper< G >::getGrid(), grid(), Acts::GeometryIdentifier::layer(), m_cfg(), Acts::IVolumeMaterial::material(), Acts::ISurfaceMaterial::materialSlab(), Acts::UnitConstants::min, n, rho, Acts::GeometryIdentifier::sensitive(), Acts::detail::Grid< T, Axes >::size(), t, to_string(), testSigmaEff::v, value, Acts::GeometryIdentifier::volume(), x0, and SVM_v1::Z.
Member Data Documentation
Config ActsExamples::RootMaterialWriter::m_cfg private
The config class.
Definition at line 152 of file RootMaterialWriter.hpp.
View newest version in sPHENIX GitHub at line 152 of file RootMaterialWriter.hpp
Referenced by config().
std::unique_ptr<const Acts::Logger> ActsExamples::RootMaterialWriter::m_logger private
The logger instance.
Definition at line 155 of file RootMaterialWriter.hpp.
View newest version in sPHENIX GitHub at line 155 of file RootMaterialWriter.hpp
Referenced by logger().
TFile* ActsExamples::RootMaterialWriter::m_outputFile {nullptr} private
Definition at line 160 of file RootMaterialWriter.hpp.
View newest version in sPHENIX GitHub at line 160 of file RootMaterialWriter.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Io/Root/include/ActsExamples/Io/Root/RootMaterialWriter.hpp
acts/blob/sPHENIX/Examples/Io/Root/src/RootMaterialWriter.cpp