Analysis Software: Fun4AllServer Class Reference
Fun4AllServer Class Reference
#include <coresoftware/blob/master/offline/framework/fun4all/Fun4AllServer.h>
Public Member Functions
~Fun4AllServer () override
virtual bool registerHisto (const std::string &hname, TNamed *h1d, const int replace=0)
virtual bool registerHisto (TNamed *h1d, const int replace=0)
template<typename T >
T * makeHisto (T *t)
virtual int isHistoRegistered (const std::string &name) const
int registerSubsystem (SubsysReco *subsystem, const std::string &topnodename="TOP")
void addNewSubsystem (SubsysReco *subsystem, const std::string &topnodename="TOP")
int unregisterSubsystem (SubsysReco *subsystem)
SubsysReco * getSubsysReco (const std::string &name)
int registerOutputManager (Fun4AllOutputManager *manager)
Fun4AllOutputManager * getOutputManager (const std::string &name)
int registerHistoManager (Fun4AllHistoManager *manager)
Fun4AllHistoManager * getHistoManager (const std::string &name)
TNamed * getHisto (const std::string &hname) const
TNamed * getHisto (const unsigned int ihisto) const
std::string getHistoName (const unsigned int ihisto) const
void Print (const std::string &what="ALL") const override
void InitAll ()
int BeginRunTimeStamp (PHTimeStamp &TimeStp)
int dumpHistos (const std::string &filename, const std::string &openmode="RECREATE")
int Reset ()
virtual int BeginRun (const int runno)
int BeginRunSubsystem (const std::pair< SubsysReco *, PHCompositeNode * > &subsys)
virtual int EndRun (const int runno=0)
virtual int End ()
PHCompositeNode * topNode () const
PHCompositeNode * topNode (const std::string &name)
int outfileclose ()
virtual int process_event ()
PHCompositeNode * getNode (const std::string &name, const std::string &topnodename="TOP")
int AddTopNode (const std::string &name)
int MakeNodesTransient (PHCompositeNode *startNode)
int MakeNodesPersistent (PHCompositeNode *startNode)
int AddComplaint (const std::string &complaint, const std::string &remedy)
int registerInputManager (Fun4AllInputManager *InManager)
Fun4AllInputManager * getInputManager (const std::string &name)
int PrdfEvents () const
int DstEvents () const
int run (const int nevnts=0, const bool require_nevents=false)
run n events (0 means up to end of file)
int skip (const int nevnts=0)
skip n events (0 means up to the end of file). Skip means read, don't process.
int fileopen (const std::string &managername, const std::string &filename)
int fileclose (const std::string &managername)
int SegmentNumber ()
int ResetNodeTree ()
int BranchSelect (const std::string &managername, const std::string &branch, int iflag)
int BranchSelect (const std::string &branch, int iflag)
int setBranches (const std::string &managername)
int setBranches ()
virtual void identify (std::ostream &out=std::cout) const
unsigned GetTopNodes (std::vector< std::string > &names) const
void GetInputFullFileList (std::vector< std::string > &fnames) const
void GetOutputManagerList (std::vector< std::string > &names) const
void GetModuleList (std::vector< std::string > &names) const
Fun4AllSyncManager * getSyncManager (const std::string &name="DefaultSyncManager")
int registerSyncManager (Fun4AllSyncManager *newmaster)
int retcodestats (const int iret)
void EventNumber (const int evtno)
int EventNumber () const
void NodeIdentify (const std::string &name)
void KeepDBConnection (const int i=1)
void PrintTimer (const std::string &name="")
void PrintMemoryTracker (const std::string &name="") const
int RunNumber () const
int EventCounter () const
std::map< const std::string,
PHTimer >::const_iterator timer_begin ()
std::map< const std::string,
PHTimer >::const_iterator timer_end ()
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Static Public Member Functions
static Fun4AllServer * instance ()
Protected Member Functions
Fun4AllServer (const std::string &name="Fun4AllServer")
int InitNodeTree (PHCompositeNode *topNode)
int CountOutNodes (PHCompositeNode *startNode)
int CountOutNodesRecursive (PHCompositeNode *startNode, const int icount)
int UpdateEventSelector (Fun4AllOutputManager *manager)
int unregisterSubsystemsNow ()
int setRun (const int runnumber)
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
TH1 * FrameWorkVars = nullptr
Fun4AllMemoryTracker * ffamemtracker = nullptr
Fun4AllHistoManager * ServerHistoManager = nullptr
PHTimeStamp * beginruntimestamp = nullptr
PHCompositeNode * TopNode = nullptr
Fun4AllSyncManager * defaultSyncManager = nullptr
int OutNodeCount = 0
int bortime_override = 0
int ScreamEveryEvent = 0
int unregistersubsystem = 0
int runnumber = 0
int eventnumber = 0
int eventcounter = 0
int keep_db_connected = 0
std::vector< std::string > ComplaintList
std::vector< std::pair
< SubsysReco
*, PHCompositeNode * > > Subsystems
std::vector< std::pair
< SubsysReco
*, PHCompositeNode * > > DeleteSubsystems
std::deque< std::pair
< SubsysReco *, std::string > > NewSubsystems
std::vector< int > RetCodes
std::vector
< Fun4AllOutputManager * > OutputManager
std::vector< TDirectory * > TDirCollection
std::vector
< Fun4AllHistoManager * > HistoManager
std::map< std::string,
PHCompositeNode * > topnodemap
std::string default_Tdirectory = "Rint:/"
std::vector< Fun4AllSyncManager * > SyncManagers
std::map< int, int > retcodesmap
std::map< const std::string,
PHTimer > timer_map
Static Protected Attributes
static Fun4AllServer * __instance = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Detailed Description
Definition at line 30 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 30 of file Fun4AllServer.h
Constructor & Destructor Documentation
Fun4AllServer::~Fun4AllServer () override
Definition at line 63 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 63 of file Fun4AllServer.cc
References __instance, beginruntimestamp, ffamemtracker, HistoManager, recoConsts::instance(), OutputManager, Reset(), Subsystems, SyncManagers, TDirCollection, topnodemap, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MORE.
Fun4AllServer::Fun4AllServer (const std::string & name = "Fun4AllServer") protected
Definition at line 53 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 53 of file Fun4AllServer.cc
References InitAll().
Referenced by instance().
Member Function Documentation
int Fun4AllServer::AddComplaint (const std::string & complaint, const std::string & remedy)
Definition at line 346 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 346 of file Fun4AllServer.cc
References ComplaintList, and ScreamEveryEvent.
void Fun4AllServer::addNewSubsystem (SubsysReco * subsystem, const std::string & topnodename = "TOP") inline
Definition at line 47 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 47 of file Fun4AllServer.h
References NewSubsystems.
Referenced by CDBInterface::CDBInterface().
int Fun4AllServer::AddTopNode (const std::string & name)
Definition at line 1284 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1284 of file Fun4AllServer.cc
References perf_headwind::name, and topnodemap.
Referenced by topNode().
int Fun4AllServer::BeginRun (const int runno) virtual
Reimplemented in OnCalServer.
Definition at line 797 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 797 of file Fun4AllServer.cc
References BeginRunSubsystem(), beginruntimestamp, bortime_override, default_Tdirectory, eventcounter, ffamemtracker, NewSubsystems, PHTimeStamp::print(), Print(), registerSubsystem(), Fun4AllMemoryTracker::Snapshot(), Subsystems, topNode(), unregistersubsystem, unregisterSubsystemsNow(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by run().
int Fun4AllServer::BeginRunSubsystem (const std::pair< SubsysReco *, PHCompositeNode * > & subsys)
Definition at line 859 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 859 of file Fun4AllServer.cc
References Fun4AllReturnCodes::ABORTRUN, Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, ffamemtracker, PHWHERE, Fun4AllMemoryTracker::Start(), Fun4AllMemoryTracker::Stop(), Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_EVEN_MORE, and Fun4AllBase::VERBOSITY_SOME.
Referenced by BeginRun().
int Fun4AllServer::BeginRunTimeStamp (PHTimeStamp & TimeStp)
Definition at line 787 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 787 of file Fun4AllServer.cc
References beginruntimestamp, bortime_override, and PHTimeStamp::print().
Referenced by OnCalServer::SetBorTime().
int Fun4AllServer::BranchSelect (const std::string & managername, const std::string & branch, int iflag)
Definition at line 1522 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1522 of file Fun4AllServer.cc
References SyncManagers.
int Fun4AllServer::BranchSelect (const std::string & branch, int iflag)
Definition at line 1533 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1533 of file Fun4AllServer.cc
References SyncManagers.
int Fun4AllServer::CountOutNodes (PHCompositeNode * startNode) protected
Definition at line 919 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 919 of file Fun4AllServer.cc
References CountOutNodesRecursive().
Referenced by process_event().
int Fun4AllServer::CountOutNodesRecursive (PHCompositeNode * startNode, const int icount) protected
Definition at line 927 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 927 of file Fun4AllServer.cc
References PHNodeIterator::ls(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_EVEN_MORE.
Referenced by CountOutNodes().
int Fun4AllServer::DstEvents () const
Definition at line 1335 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1335 of file Fun4AllServer.cc
References defaultSyncManager, and Fun4AllSyncManager::TotalEvents().
int Fun4AllServer::dumpHistos (const std::string & filename, const std::string & openmode = "RECREATE")
Definition at line 145 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 145 of file Fun4AllServer.cc
References HistoManager, ServerHistoManager, and Fun4AllHistoManager::setOutfileName().
Referenced by Fun(), RunBoth(), and Wrapper().
int Fun4AllServer::End () virtual
Reimplemented in OnCalServer.
Definition at line 1041 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1041 of file Fun4AllServer.cc
References ComplaintList, default_Tdirectory, Acts::UnitConstants::e, EndRun(), PHNodeIterator::findFirst(), PHFlag::get_IntFlag(), i, recoConsts::instance(), MakeNodesTransient(), outfileclose(), OutputManager, PHWHERE, ScreamEveryEvent, Subsystems, TopNode, Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_EVEN_MORE, and Fun4AllBase::VERBOSITY_SOME.
Referenced by AnalyzeTree(), clus_dst_simple_superfastcalib(), dst_simple_towerslope_runmacro(), Fun(), Fun4All(), Fun4All_Ana(), Fun4All_Analysis(), Fun4All_AnaTutorial_DSTReadBack(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_Calo(), Fun4All_CaloAna(), Fun4All_CaloProduction(), Fun4All_CaloProduction_PreQM23(), Fun4All_CaloTreeGen(), Fun4All_CaloWaveFormSim(), Fun4All_CentralityValidation(), Fun4All_Combiner(), Fun4All_Condor(), Fun4All_EICAnalysis_DIS(), Fun4All_EICAnalysis_DISReco(), Fun4All_EICAnalysis_DVCS(), Fun4All_EICAnalysis_Exclusive(), Fun4All_EICAnalysis_Leptoquarks(), Fun4All_EICAnalysis_Quarkonia(), Fun4All_EICAnalysis_TrackEval(), Fun4All_EMCal(), Fun4All_EMCal_Hist(), Fun4All_EMCal_sp(), Fun4All_EMCalBadTowerID(), Fun4All_EMCalLikelihood(), Fun4All_EMJetVal(), Fun4All_ExportGeom(), Fun4All_FillChargesMap_300evts_MDC2(), Fun4All_FillDCMap(), Fun4All_G4_block(), Fun4All_G4_Calo(), Fun4All_G4_Calos(), Fun4All_G4_Clusters(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_analysis(), Fun4All_G4_EICDetector_LQ_analysis_nf(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_EICIR(), Fun4All_G4_Example01(), Fun4All_G4_Example02(), Fun4All_G4_Example03(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Geantino(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_MyDetector(), Fun4All_G4_Pi0_Tbt(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_SlopeCal(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_G4_Write_Dst(), Fun4All_GeoExtract(), Fun4All_HCALAnalysis(), Fun4All_HCalCalib(), Fun4All_HCalCalib_sim(), Fun4All_HCalJetPhiShift(), Fun4All_hijbkg(), Fun4All_ImportGeom(), Fun4All_Intt_Combiner(), Fun4All_IsolatedTrackAnalysis(), Fun4All_JetAna(), Fun4All_JetAna_MDC(), Fun4All_JetBkgd(), Fun4All_JetBkgd_Embed(), Fun4All_JetNconst(), Fun4All_JetRhoMedian(), Fun4All_JetSeedCount(), Fun4All_JetSub(), Fun4All_JetVal(), Fun4All_LEDTowerBuilder(), Fun4All_MBDTreeGen(), Fun4All_MCEventGen(), Fun4All_MDCTreeMaker(), Fun4All_Mvtx_Combiner(), Fun4All_MySimpleReco(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_PRDF(), Fun4All_Pythia6(), Fun4All_pythiaEMCalAna(), Fun4All_quickHijing_Prod(), Fun4All_Read_Dst(), Fun4All_ReadDST_TPCML(), Fun4All_RhoFluct(), Fun4All_RICHReco(), Fun4All_RTrack(), Fun4All_RunEMCReco(), Fun4All_RunNewTruthMatcher(), Fun4All_RunPi0ClusterAna(), Fun4All_RunPi0Efficiency(), Fun4All_RunSinglePhotonClusterAna(), Fun4All_single_particle(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4All_Stream_Combiner(), Fun4All_Templates(), Fun4All_TestBeam(), Fun4All_TestBeam_Ana(), Fun4All_TestBeam_ExampleAnalysisModule(), Fun4All_TestBeam_HCAL_SampleFrac(), Fun4All_TestBeam_HCAL_ShowerCalib(), Fun4All_TestBeam_HCAL_TowerCalib(), Fun4All_TestBeam_ShowerCalib(), Fun4All_TestBeam_TPC(), Fun4All_testingGround(), Fun4All_Tpc_Combiner(), Fun4All_TPC_EventDisplayPrep(), Fun4All_TPC_UnpackPRDF(), Fun4All_TPC_UnpackPRDF_Batch(), Fun4All_UE_v2_Psi2(), Fun4All_Year1(), G4_HIJetReco(), G4TTree(), generate_hepmc_bjet(), hcal_toweridmacro(), Jin_BJet(), MakeEdepNtuple(), MakeHijingCountNtuple(), MakeHijingShowerSize(), MakeHitCountNtuple(), MakeShowerSize(), MakeSigmaTimingNtuple(), MakeTimingNtuple(), MakeTowerTiming(), MakeTree(), MyHitTTree(), run(), Run_BbcCheck(), Run_BBCStudy(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), run_dump(), run_macro(), run_macro_2(), runall(), runanae(), runanajpsi(), runanaK(), runanapi(), runanapythiaupsilon(), RunBDiJetModule(), RunBJetModule(), RunBoth(), rundata(), rundst_spiNo(), RunGenFitTrackProp(), runmb(), runpairs(), spiNo2(), srundst_mdc2_clustest(), TestCDBSubsysReco(), toweridmacro(), towerslope_dst_runner(), tsdst_plus_tsfit(), wholeIter_Pi0EtaByEta(), and Wrapper().
int Fun4AllServer::EndRun (const int runno = 0) virtual
Reimplemented in OnCalServer.
Definition at line 991 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 991 of file Fun4AllServer.cc
References default_Tdirectory, Acts::UnitConstants::e, PHWHERE, Subsystems, Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_EVEN_MORE, and Fun4AllBase::VERBOSITY_MORE.
Referenced by End(), and run().
int Fun4AllServer::EventCounter () const inline
Definition at line 116 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 116 of file Fun4AllServer.h
References eventcounter.
Referenced by SyncReco::process_event().
void Fun4AllServer::EventNumber (const int evtno) inline
Definition at line 109 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 109 of file Fun4AllServer.h
References eventnumber.
Referenced by Fun4AllSyncManager::CurrentEvent(), SyncReco::process_event(), HeadReco::process_event(), and EventNumberCheck::process_event().
int Fun4AllServer::EventNumber () const inline
Definition at line 110 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 110 of file Fun4AllServer.h
References eventnumber.
int Fun4AllServer::fileclose (const std::string & managername)
Definition at line 1566 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1566 of file Fun4AllServer.cc
References SyncManagers.
int Fun4AllServer::fileopen (const std::string & managername, const std::string & filename)
Definition at line 1511 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1511 of file Fun4AllServer.cc
References SyncManagers.
Referenced by AnalyzeTree(), Fun4All_Ana(), Fun4All_EICAnalysis_DIS(), Fun4All_EICAnalysis_DISReco(), Fun4All_EICAnalysis_DVCS(), Fun4All_EICAnalysis_Exclusive(), Fun4All_EICAnalysis_Leptoquarks(), Fun4All_EICAnalysis_Quarkonia(), Fun4All_EICAnalysis_TrackEval(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_Generator_Display(), Fun4All_HCALAnalysis(), Fun4All_single_particle(), Jin_BJet(), Run_BBCStudy(), and run_dump().
TNamed * Fun4AllServer::getHisto (const std::string & hname) const
Definition at line 496 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 496 of file Fun4AllServer.cc
References Fun4AllHistoManager::getHisto(), and ServerHistoManager.
Referenced by OnCalServer::dumpHistos(), PHG4OuterHcalSteppingAction::FieldChecker(), and PHG4OHCalSteppingAction::FieldChecker().
TNamed * Fun4AllServer::getHisto (const unsigned int ihisto) const
Definition at line 485 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 485 of file Fun4AllServer.cc
References Fun4AllHistoManager::getHisto(), and ServerHistoManager.
Fun4AllHistoManager * Fun4AllServer::getHistoManager (const std::string & name)
Definition at line 444 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 444 of file Fun4AllServer.cc
References HistoManager, perf_headwind::name, Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_EVEN_MORE, and Fun4AllBase::VERBOSITY_MORE.
Referenced by PHAna::create_histos(), PHAna::End(), PHAna::fill_histos(), EMCalLikelihood::get_HistoManager(), Proto4SampleFrac::get_HistoManager(), analysis::get_HistoManager(), jetrtrack::get_HistoManager(), EMCalAna::get_HistoManager(), EMCalCalib::get_HistoManager(), EMCalCalib_TestBeam::get_HistoManager(), Proto4ShowerCalib::get_HistoManager(), Proto2ShowerCalib::get_HistoManager(), Proto3ShowerCalib::get_HistoManager(), Proto4TowerCalib::get_HistoManager(), ExampleAnalysisModule::get_HistoManager(), QAHistManagerDef::getHistoManager(), TPCIntegratedCharge::getHistoManager(), TPCDataStreamEmulator::getHistoManager(), PHG4ScoringManager::getHistoManager(), JetHepMCLoader::getHistoManager(), TPCMLDataInterface::getHistoManager(), SynRadAna::getHistoManager(), SoftLeptonTaggingTruth::getHistoManager(), TPCFEETestRecov1::getHistoManager(), and TpcPrototypeUnpacker::getHistoManager().
std::string Fun4AllServer::getHistoName (const unsigned int ihisto) const
Definition at line 491 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 491 of file Fun4AllServer.cc
References Fun4AllHistoManager::getHistoName(), and ServerHistoManager.
void Fun4AllServer::GetInputFullFileList (std::vector< std::string > & fnames) const
Definition at line 1583 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1583 of file Fun4AllServer.cc
References defaultSyncManager, and Fun4AllSyncManager::GetInputFullFileList().
Fun4AllInputManager * Fun4AllServer::getInputManager (const std::string & name)
Definition at line 1316 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1316 of file Fun4AllServer.cc
References SyncManagers.
void Fun4AllServer::GetModuleList (std::vector< std::string > & names) const
Definition at line 1611 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1611 of file Fun4AllServer.cc
References Subsystems.
PHCompositeNode * Fun4AllServer::getNode (const std::string & name, const std::string & topnodename = "TOP")
Definition at line 1297 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1297 of file Fun4AllServer.cc
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), and topNode().
Referenced by Fun4AllDstInputManager::fileopen(), Fun4AllRunNodeInputManager::fileopen(), Fun4AllHepMCInputManager::Fun4AllHepMCInputManager(), and Fun4AllOscarInputManager::Fun4AllOscarInputManager().
Fun4AllOutputManager * Fun4AllServer::getOutputManager (const std::string & name)
Definition at line 425 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 425 of file Fun4AllServer.cc
References OutputManager, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_EVEN_MORE.
void Fun4AllServer::GetOutputManagerList (std::vector< std::string > & names) const
Definition at line 1600 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1600 of file Fun4AllServer.cc
References OutputManager.
SubsysReco * Fun4AllServer::getSubsysReco (const std::string & name)
Definition at line 328 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 328 of file Fun4AllServer.cc
References perf_headwind::name, Subsystems, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_EVEN_MORE.
Referenced by DisplayOn(), Fun4All_G4_EICIR(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), G4Cmd(), get_gen(), get_gun(), getgun(), matscan(), and QTGui().
Fun4AllSyncManager * Fun4AllServer::getSyncManager (const std::string & name = "DefaultSyncManager")
Definition at line 1642 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1642 of file Fun4AllServer.cc
References defaultSyncManager, perf_headwind::name, and SyncManagers.
Referenced by Fun4All_JetBkgd_Embed().
unsigned Fun4AllServer::GetTopNodes (std::vector< std::string > & names) const
Definition at line 1590 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1590 of file Fun4AllServer.cc
References topnodemap.
void Fun4AllServer::identify (std::ostream & out = std::cout) const virtual
Definition at line 1225 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1225 of file Fun4AllServer.cc
References Fun4AllBase::Name().
void Fun4AllServer::InitAll ()
Definition at line 121 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 121 of file Fun4AllServer.cc
References defaultSyncManager, FrameWorkVars, i, InitNodeTree(), Fun4AllMonitoring::instance(), Fun4AllBase::Name(), NFRAMEWORKBINS, registerHisto(), registerHistoManager(), ServerHistoManager, Fun4AllMonitoring::Snapshot(), SyncManagers, TopNode, and topnodemap.
Referenced by Fun4AllServer().
int Fun4AllServer::InitNodeTree (PHCompositeNode * topNode) protected
Definition at line 1247 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1247 of file Fun4AllServer.cc
References PHCompositeNode::addNode().
Referenced by InitAll(), and topNode().
Fun4AllServer * Fun4AllServer::instance () static
Definition at line 43 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 43 of file Fun4AllServer.cc
References __instance, and Fun4AllServer().
Referenced by ACTSGEOM::ActsGeomInit(), alignment(), AnalyzeTree(), Bbc_Reco(), build_truthreco_tables(), CaloTrigger_Sim(), CDBInterface::CDBInterface(), CEMC_Cells(), CEMC_Clusters(), CEMC_Eval(), CEMC_QA(), CEMC_Towers(), Centrality(), clus_dst_simple_superfastcalib(), ConfigureInput(), ConstructGeometry(), convert_seeds(), PHAna::create_histos(), caloTowerEmbed::CreateNodeTree(), Fun4AllSyncManager::CurrentEvent(), DisplayOn(), Distortions_QA(), doFitAndCalibUpdate(), dst_simple_towerslope_runmacro(), PHG4GDMLUtility::Dump_GDML(), EEMC_Cells(), EEMC_Clusters(), EEMC_Eval(), EEMC_Towers(), EGEM_FastSim_Reco(), PHAna::End(), EPD_Tiles(), FastSim_Reco_EIC(), FEMC_Cells(), FEMC_Clusters(), FEMC_Eval(), FEMC_Towers(), FEMCSetup(), FGEM_FastSim_Eval(), FGEM_FastSim_Reco(), FHCAL_Cells(), FHCAL_Clusters(), FHCAL_Eval(), FHCAL_Towers(), FHCALSetup(), PHG4OuterHcalSteppingAction::FieldChecker(), PHG4OHCalSteppingAction::FieldChecker(), Fun4AllDstInputManager::fileopen(), Fun4AllRunNodeInputManager::fileopen(), Fun4AllDstPileupInputManager::fileopen(), Fun4AllSingleDstPileupInputManager::fileopen(), PHAna::fill_histos(), Filter_Conversion_Electrons(), Fun(), Fun4All(), Fun4All_Ana(), Fun4All_Analysis(), Fun4All_AnaTutorial_DSTReadBack(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_Calo(), Fun4All_CaloAna(), Fun4All_CaloProduction(), Fun4All_CaloProduction_PreQM23(), Fun4All_CaloTreeGen(), Fun4All_CaloWaveFormSim(), Fun4All_CentralityValidation(), Fun4All_Combiner(), Fun4All_Condor(), Fun4All_EICAnalysis_DIS(), Fun4All_EICAnalysis_DISReco(), Fun4All_EICAnalysis_DVCS(), Fun4All_EICAnalysis_Exclusive(), Fun4All_EICAnalysis_Leptoquarks(), Fun4All_EICAnalysis_Quarkonia(), Fun4All_EICAnalysis_TrackEval(), Fun4All_EMCal(), Fun4All_EMCal_Hist(), Fun4All_EMCal_sp(), Fun4All_EMCalBadTowerID(), Fun4All_EMCalLikelihood(), Fun4All_EMJetVal(), Fun4All_ExportGeom(), Fun4All_FillChargesMap_300evts_MDC2(), Fun4All_FillDCMap(), Fun4All_G4_block(), Fun4All_G4_Calo(), Fun4All_G4_Calos(), Fun4All_G4_Clusters(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_analysis(), Fun4All_G4_EICDetector_LQ_analysis_nf(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_EICIR(), Fun4All_G4_Example01(), Fun4All_G4_Example02(), Fun4All_G4_Example03(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Geantino(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_MyDetector(), Fun4All_G4_Pi0_Tbt(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_SlopeCal(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_jobC(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_G4_Write_Dst(), Fun4All_Generator_Display(), Fun4All_GeoExtract(), Fun4All_HCALAnalysis(), Fun4All_HCalCalib(), Fun4All_HCalCalib_sim(), Fun4All_HCalJetPhiShift(), Fun4All_hijbkg(), Fun4All_ImportGeom(), Fun4All_Intt_Combiner(), Fun4All_IsolatedTrackAnalysis(), Fun4All_JetAna(), Fun4All_JetAna_MDC(), Fun4All_JetBkgd(), Fun4All_JetBkgd_Embed(), Fun4All_JetNconst(), Fun4All_JetRhoMedian(), Fun4All_JetSeedCount(), Fun4All_JetSub(), Fun4All_JetVal(), Fun4All_LEDTowerBuilder(), Fun4All_MBDTreeGen(), Fun4All_MCEventGen(), Fun4All_MDCTreeMaker(), Fun4All_Mvtx_Combiner(), Fun4All_MySimpleReco(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_PRDF(), Fun4All_Pythia6(), Fun4All_pythiaEMCalAna(), Fun4All_quickHijing_Prod(), Fun4All_Read_Dst(), Fun4All_ReadDST_TPCML(), Fun4All_RhoFluct(), Fun4All_RICHReco(), Fun4All_RTrack(), Fun4All_RunCorrelatorJetTree(), Fun4All_RunCorrelatorQAModules(), Fun4All_RunEMCReco(), Fun4All_RunLambdaJetHunter(), Fun4All_RunNewTruthMatcher(), Fun4All_RunPi0ClusterAna(), Fun4All_RunPi0Efficiency(), Fun4All_RunSinglePhotonClusterAna(), Fun4All_single_particle(), Fun4All_SingleMvtx(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4All_Stream_Combiner(), Fun4All_Templates(), Fun4All_TestBeam(), Fun4All_TestBeam_Ana(), Fun4All_TestBeam_ExampleAnalysisModule(), Fun4All_TestBeam_HCAL_SampleFrac(), Fun4All_TestBeam_HCAL_ShowerCalib(), Fun4All_TestBeam_HCAL_TowerCalib(), Fun4All_TestBeam_ShowerCalib(), Fun4All_TestBeam_TPC(), Fun4All_testEtIso_Hijing(), Fun4All_testEtIso_Pythia(), Fun4All_testingGround(), Fun4All_Tpc_Combiner(), Fun4All_TPC_EventDisplayPrep(), Fun4All_TPC_UnpackPRDF(), Fun4All_TPC_UnpackPRDF_Batch(), Fun4All_TrkrClusteringSeeding(), Fun4All_TrkrHitSet_Unpacker(), Fun4All_UE_v2_Psi2(), Fun4All_Year1(), Fun4AllHepMCInputManager::Fun4AllHepMCInputManager(), Fun4AllOscarInputManager::Fun4AllOscarInputManager(), Fun4AllPrdfInputManager::Fun4AllPrdfInputManager(), Fun4AllPrdfInputPoolManager::Fun4AllPrdfInputPoolManager(), Fun4AllPythia(), Fun4AllStreamingInputManager::Fun4AllStreamingInputManager(), G4_HIJetReco(), G4_Lepto(), G4Cmd(), G4DSTreader(), G4DSTreader_EICDetector(), G4DSTreader_EICIR(), G4DSTreader_fsPHENIX(), G4KshortReconstruction(), G4Setup(), G4TTree(), generate_hepmc_bjet(), LightCollectionModel::get_fiber_transmission(), get_gen(), get_gun(), EMCalLikelihood::get_HistoManager(), Proto4SampleFrac::get_HistoManager(), analysis::get_HistoManager(), jetrtrack::get_HistoManager(), EMCalAna::get_HistoManager(), EMCalCalib::get_HistoManager(), EMCalCalib_TestBeam::get_HistoManager(), Proto4ShowerCalib::get_HistoManager(), Proto2ShowerCalib::get_HistoManager(), Proto3ShowerCalib::get_HistoManager(), Proto4TowerCalib::get_HistoManager(), ExampleAnalysisModule::get_HistoManager(), LightCollectionModel::get_light_guide_efficiency(), PHFieldUtility::GetFieldConfigNode(), PHFieldUtility::GetFieldMapNode(), getgun(), QAHistManagerDef::getHistoManager(), TPCIntegratedCharge::getHistoManager(), TPCDataStreamEmulator::getHistoManager(), PHG4ScoringManager::getHistoManager(), JetHepMCLoader::getHistoManager(), TPCMLDataInterface::getHistoManager(), SynRadAna::getHistoManager(), SoftLeptonTaggingTruth::getHistoManager(), TPCFEETestRecov1::getHistoManager(), TpcPrototypeUnpacker::getHistoManager(), MakeActsGeometry::getNodes(), Global_FastSim(), Global_Reco(), hcal_toweridmacro(), HCALInner_Cells(), HCALInner_Clusters(), HCALInner_Eval(), HCALInner_QA(), HCALInner_Towers(), HCALOuter_Cells(), HCALOuter_Clusters(), HCALOuter_Eval(), HCALOuter_QA(), HCALOuter_Towers(), HIJetReco(), AnalyzeSimpleTree::Init(), SvtxSimPerformanceCheckReco::Init(), TrackingPerformanceCheck::Init(), HCalCalibTree::Init(), STACalorimeterCharacterization::Init(), SimpleTrackingAnalysis::Init(), singlePhotonClusterAna::Init(), pi0ClusterAna::Init(), caloTreeGen::Init(), pi0Efficiency::Init(), cemcReco::Init(), PHAJMaker::Init(), Prototype2RawTowerBuilder::InitRun(), PHG4Prototype2HcalCellReco::InitRun(), caloTowerEmbed::InitRun(), PHG4TpcElectronDrift::InitRun(), InputInit(), InputManagers(), InputRegister(), Intt_Cells(), Intt_Clustering(), Intt_QA(), Jet_Eval(), Jet_FwdEval(), Jet_FwdReco(), Jet_QA(), Jet_Reco(), Jin_BJet(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), KFParticle_QA(), HFjets::KFParticle_Set_Reco(), KFParticle_Upsilon_Reco(), MakeEdepNtuple(), MakeHijingCountNtuple(), MakeHijingShowerSize(), MakeHitCountNtuple(), MakeShowerSize(), MakeSigmaTimingNtuple(), MakeTimingNtuple(), MakeTowerTiming(), MakeTree(), matscan(), Mbd_Reco(), Micromegas_Cells(), Micromegas_Clustering(), Micromegas_QA(), Mvtx_Cells(), Mvtx_Clustering(), Mvtx_QA(), myDemoReco(), myHeavyFlavorReco(), MyHitTTree(), ParticleFlow(), PHGeom_DSTInspection(), SyncReco::process_event(), TimerStats::process_event(), HeadReco::process_event(), EventNumberCheck::process_event(), QA_G4CaloTracking(), QA_Output(), QTGui(), ReadFieldMap(), Prototype2RawTowerBuilder::ReadParamsFromNodeTree(), HcalRawTowerBuilder::ReadParamsFromNodeTree(), Fun4AllInputManager::registerSubsystem(), registerSubsystem(), Fun4AllInputManager::RejectEvent(), run(), Fun4AllDstPileupInputManager::run(), Run_BbcCheck(), Run_BBCStudy(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), run_dump(), run_macro(), run_macro_2(), runall(), runanae(), runanajpsi(), runanaK(), runanapi(), runanapythiaupsilon(), RunBDiJetModule(), RunBJetModule(), RunBoth(), rundata(), rundst_spiNo(), RunGenFitTrackProp(), runmb(), runpairs(), seedResiduals(), ShowerCompress(), spiNo2(), srundst_mdc2_clustest(), Svtx_Cells(), Svtx_Clustering(), Svtx_Eval(), Svtx_Reco(), Svtx_Tracking(), TestCDBSubsysReco(), TopoClusterReco(), toweridmacro(), towerslope_dst_runner(), TPC_Cells(), TPC_Clustering(), TPC_LaserClustering(), TPC_QA(), Track_Matching(), Tracking_Eval(), Tracking_QA(), Tracking_Reco_CommissioningTrackSeed(), Tracking_Reco_TrackFit(), Tracking_Reco_TrackSeed(), Tracking_Reco_TrackSeed_pass1(), TrackingInit(), tsdst_plus_tsfit(), UserAnalysisInit(), vertexing(), wholeIter_Pi0EtaByEta(), Wrapper(), Fun4AllEventOutputManager::Write(), Fun4AllDstOutputManager::Write(), Fun4AllFileOutStream::WriteEventOut(), Fun4AllDstOutputManager::WriteNode(), ZDC_Eval(), ZDC_Towers(), and ZDCSetup().
int Fun4AllServer::isHistoRegistered (const std::string & name) const virtual
Definition at line 171 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 171 of file Fun4AllServer.cc
References Fun4AllHistoManager::isHistoRegistered(), and ServerHistoManager.
Referenced by PHG4OuterHcalSteppingAction::FieldChecker(), and PHG4OHCalSteppingAction::FieldChecker().
void Fun4AllServer::KeepDBConnection (const int i = 1) inline
Definition at line 112 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 112 of file Fun4AllServer.h
References i, and keep_db_connected.
template<typename T > T* Fun4AllServer::makeHisto (T * t) inline
Definition at line 40 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 40 of file Fun4AllServer.h
References Fun4AllHistoManager::makeHisto(), and ServerHistoManager.
int Fun4AllServer::MakeNodesPersistent (PHCompositeNode * startNode)
Definition at line 972 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 972 of file Fun4AllServer.cc
References PHNodeIterator::ls().
Referenced by Fun4AllDstOutputManager::Write(), and Fun4AllDstOutputManager::WriteNode().
int Fun4AllServer::MakeNodesTransient (PHCompositeNode * startNode)
Definition at line 952 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 952 of file Fun4AllServer.cc
References PHNodeIterator::ls().
Referenced by End(), process_event(), Fun4AllDstOutputManager::Write(), and Fun4AllDstOutputManager::WriteNode().
void Fun4AllServer::NodeIdentify (const std::string & name)
Definition at line 1676 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1676 of file Fun4AllServer.cc
References PHObject::identify(), perf_headwind::name, and TopNode.
int Fun4AllServer::outfileclose ()
Definition at line 1231 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1231 of file Fun4AllServer.cc
References Fun4AllBase::Name(), OutputManager, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MORE.
Referenced by End().
int Fun4AllServer::PrdfEvents () const
Definition at line 1330 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1330 of file Fun4AllServer.cc
References defaultSyncManager, and Fun4AllSyncManager::PrdfEvents().
void Fun4AllServer::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 1132 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1132 of file Fun4AllServer.cc
References HistoManager, OutputManager, Acts::Test::pos, PHNodeIterator::print(), Subsystems, SyncManagers, and topnodemap.
Referenced by BeginRun(), Prototype2RawTowerBuilder::InitRun(), PHG4Prototype2HcalCellReco::InitRun(), OnCalServer::Print(), Prototype2RawTowerBuilder::ReadParamsFromNodeTree(), HcalRawTowerBuilder::ReadParamsFromNodeTree(), and TestCDBSubsysReco().
void Fun4AllServer::PrintMemoryTracker (const std::string & name = "") const
Definition at line 1722 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1722 of file Fun4AllServer.cc
References ffamemtracker, and Fun4AllMemoryTracker::PrintMemoryTracker().
void Fun4AllServer::PrintTimer (const std::string & name = "")
Definition at line 1691 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1691 of file Fun4AllServer.cc
References PHTimer::PRINT(), and timer_map.
Referenced by clus_dst_simple_superfastcalib(), dst_simple_towerslope_runmacro(), Fun4All_CaloProduction(), Fun4All_CaloProduction_PreQM23(), Fun4All_CaloTreeGen(), Fun4All_EMCal(), Fun4All_EMCal_Hist(), Fun4All_EMCal_sp(), Fun4All_EMCalBadTowerID(), Fun4All_HCalCalib(), Fun4All_HCalCalib_sim(), Fun4All_LEDTowerBuilder(), Fun4All_MBDTreeGen(), Fun4All_Templates(), Fun4All_UE_v2_Psi2(), Fun4All_Year1(), hcal_toweridmacro(), srundst_mdc2_clustest(), toweridmacro(), towerslope_dst_runner(), tsdst_plus_tsfit(), and wholeIter_Pi0EtaByEta().
int Fun4AllServer::process_event () virtual
Reimplemented in OnCalServer.
Definition at line 501 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 501 of file Fun4AllServer.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::ABORTRUN, ComplaintList, CountOutNodes(), default_Tdirectory, Fun4AllReturnCodes::DISCARDEVENT, Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, eventcounter, ffamemtracker, PHNodeIterator::findFirst(), Fun4AllMonitoring::instance(), MakeNodesTransient(), OutNodeCount, OutputManager, PHWHERE, PHNodeIterator::print(), ResetNodeTree(), RetCodes, retcodesmap, ScreamEveryEvent, Fun4AllMonitoring::Snapshot(), Fun4AllMemoryTracker::Snapshot(), Fun4AllMemoryTracker::Start(), Fun4AllMemoryTracker::Stop(), Subsystems, SyncManagers, timer_map, TopNode, unregistersubsystem, unregisterSubsystemsNow(), Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_EVEN_MORE, and Fun4AllBase::VERBOSITY_MORE.
Referenced by OnCalServer::process_event(), and run().
bool Fun4AllServer::registerHisto (const std::string & hname, TNamed * h1d, const int replace = 0) virtual
Definition at line 166 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 166 of file Fun4AllServer.cc
References Fun4AllHistoManager::registerHisto(), and ServerHistoManager.
Referenced by PHG4OuterHcalSteppingAction::FieldChecker(), PHG4OHCalSteppingAction::FieldChecker(), LightCollectionModel::get_fiber_transmission(), LightCollectionModel::get_light_guide_efficiency(), SvtxSimPerformanceCheckReco::Init(), TrackingPerformanceCheck::Init(), STACalorimeterCharacterization::Init(), SimpleTrackingAnalysis::Init(), InitAll(), OnCalServer::OnCalServer(), and OnCalServer::registerHisto().
bool Fun4AllServer::registerHisto (TNamed * h1d, const int replace = 0) virtual
Definition at line 161 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 161 of file Fun4AllServer.cc
References Fun4AllHistoManager::registerHisto(), and ServerHistoManager.
int Fun4AllServer::registerHistoManager (Fun4AllHistoManager * manager)
Definition at line 465 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 465 of file Fun4AllServer.cc
References HistoManager, Fun4AllBase::Name(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by PHAna::create_histos(), EMCalLikelihood::get_HistoManager(), Proto4SampleFrac::get_HistoManager(), jetrtrack::get_HistoManager(), analysis::get_HistoManager(), EMCalAna::get_HistoManager(), EMCalCalib::get_HistoManager(), EMCalCalib_TestBeam::get_HistoManager(), Proto4ShowerCalib::get_HistoManager(), Proto2ShowerCalib::get_HistoManager(), Proto3ShowerCalib::get_HistoManager(), Proto4TowerCalib::get_HistoManager(), ExampleAnalysisModule::get_HistoManager(), QAHistManagerDef::getHistoManager(), TPCIntegratedCharge::getHistoManager(), TPCDataStreamEmulator::getHistoManager(), PHG4ScoringManager::getHistoManager(), JetHepMCLoader::getHistoManager(), TPCMLDataInterface::getHistoManager(), SynRadAna::getHistoManager(), SoftLeptonTaggingTruth::getHistoManager(), TPCFEETestRecov1::getHistoManager(), TpcPrototypeUnpacker::getHistoManager(), AnalyzeSimpleTree::Init(), PHAJMaker::Init(), and InitAll().
int Fun4AllServer::registerInputManager (Fun4AllInputManager * InManager)
Definition at line 1309 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1309 of file Fun4AllServer.cc
References defaultSyncManager, and Fun4AllSyncManager::registerInputManager().
Referenced by AnalyzeTree(), clus_dst_simple_superfastcalib(), ConfigureInput(), ConstructGeometry(), dst_simple_towerslope_runmacro(), Fun4All(), Fun4All_Ana(), Fun4All_Analysis(), Fun4All_AnaTutorial_DSTReadBack(), Fun4All_Calo(), Fun4All_CaloAna(), Fun4All_CaloProduction(), Fun4All_CaloProduction_PreQM23(), Fun4All_CaloTreeGen(), Fun4All_CaloWaveFormSim(), Fun4All_CentralityValidation(), Fun4All_Combiner(), Fun4All_Condor(), Fun4All_EICAnalysis_DIS(), Fun4All_EICAnalysis_DISReco(), Fun4All_EICAnalysis_DVCS(), Fun4All_EICAnalysis_Exclusive(), Fun4All_EICAnalysis_Leptoquarks(), Fun4All_EICAnalysis_Quarkonia(), Fun4All_EICAnalysis_TrackEval(), Fun4All_EMCal(), Fun4All_EMCal_Hist(), Fun4All_EMCal_sp(), Fun4All_EMCalBadTowerID(), Fun4All_EMCalLikelihood(), Fun4All_EMJetVal(), Fun4All_ExportGeom(), Fun4All_FillChargesMap_300evts_MDC2(), Fun4All_FillDCMap(), Fun4All_G4_block(), Fun4All_G4_Calos(), Fun4All_G4_Clusters(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_analysis(), Fun4All_G4_EICDetector_LQ_analysis_nf(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_EICIR(), Fun4All_G4_Example01(), Fun4All_G4_Example02(), Fun4All_G4_Example03(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Geantino(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_MyDetector(), Fun4All_G4_Pi0_Tbt(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_SlopeCal(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_G4_Write_Dst(), Fun4All_Generator_Display(), Fun4All_GeoExtract(), Fun4All_HCALAnalysis(), Fun4All_HCalCalib(), Fun4All_HCalCalib_sim(), Fun4All_hijbkg(), Fun4All_ImportGeom(), Fun4All_Intt_Combiner(), Fun4All_IsolatedTrackAnalysis(), Fun4All_JetAna(), Fun4All_JetAna_MDC(), Fun4All_JetBkgd(), Fun4All_JetBkgd_Embed(), Fun4All_JetNconst(), Fun4All_JetRhoMedian(), Fun4All_JetSeedCount(), Fun4All_JetSub(), Fun4All_JetVal(), Fun4All_LEDTowerBuilder(), Fun4All_MBDTreeGen(), Fun4All_MDCTreeMaker(), Fun4All_Mvtx_Combiner(), Fun4All_MySimpleReco(), Fun4All_PRDF(), Fun4All_pythiaEMCalAna(), Fun4All_quickHijing_Prod(), Fun4All_Read_Dst(), Fun4All_RhoFluct(), Fun4All_RICHReco(), Fun4All_RTrack(), Fun4All_RunEMCReco(), Fun4All_RunPi0ClusterAna(), Fun4All_RunPi0Efficiency(), Fun4All_RunSinglePhotonClusterAna(), Fun4All_single_particle(), Fun4All_Stream_Combiner(), Fun4All_Templates(), Fun4All_TestBeam(), Fun4All_TestBeam_Ana(), Fun4All_TestBeam_ExampleAnalysisModule(), Fun4All_TestBeam_HCAL_SampleFrac(), Fun4All_TestBeam_HCAL_ShowerCalib(), Fun4All_TestBeam_HCAL_TowerCalib(), Fun4All_TestBeam_ShowerCalib(), Fun4All_TestBeam_TPC(), Fun4All_testEtIso_Hijing(), Fun4All_testEtIso_Pythia(), Fun4All_testingGround(), Fun4All_Tpc_Combiner(), Fun4All_TPC_EventDisplayPrep(), Fun4All_TPC_UnpackPRDF(), Fun4All_TPC_UnpackPRDF_Batch(), Fun4All_UE_v2_Psi2(), Fun4All_Year1(), G4_HIJetReco(), G4TTree(), generate_hepmc_bjet(), hcal_toweridmacro(), InputManagers(), Jin_BJet(), MakeEdepNtuple(), MakeHijingCountNtuple(), MakeHijingShowerSize(), MakeHitCountNtuple(), MakeShowerSize(), MakeSigmaTimingNtuple(), MakeTimingNtuple(), MakeTowerTiming(), MakeTree(), MyHitTTree(), PHGeom_DSTInspection(), ReadFieldMap(), run(), Run_BbcCheck(), Run_BBCStudy(), run_dump(), run_macro(), run_macro_2(), runall(), runanae(), runanajpsi(), runanaK(), runanapi(), runanapythiaupsilon(), RunBDiJetModule(), RunBJetModule(), RunBoth(), rundata(), RunGenFitTrackProp(), runmb(), runpairs(), srundst_mdc2_clustest(), TestCDBSubsysReco(), toweridmacro(), towerslope_dst_runner(), tsdst_plus_tsfit(), wholeIter_Pi0EtaByEta(), and Wrapper().
int Fun4AllServer::registerOutputManager (Fun4AllOutputManager * manager)
Definition at line 363 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 363 of file Fun4AllServer.cc
References Fun4AllBase::Name(), OutputManager, UpdateEventSelector(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_CaloProduction(), Fun4All_CaloProduction_PreQM23(), Fun4All_Combiner(), Fun4All_Condor(), Fun4All_EMCalLikelihood(), Fun4All_G4_block(), Fun4All_G4_Calo(), Fun4All_G4_Calos(), Fun4All_G4_Clusters(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_EICIR(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_IonGun(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_Write_Dst(), Fun4All_GeoExtract(), Fun4All_HCalJetPhiShift(), Fun4All_ImportGeom(), Fun4All_Intt_Combiner(), Fun4All_MCEventGen(), Fun4All_Mvtx_Combiner(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_PRDF(), Fun4All_Pythia6(), Fun4All_RTrack(), Fun4All_RunNewTruthMatcher(), Fun4All_single_particle(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4All_Stream_Combiner(), Fun4All_TestBeam(), Fun4All_TestBeam_TPC(), Fun4All_Year1(), G4TTree(), generate_hepmc_bjet(), Jin_BJet(), MakeTree(), MyHitTTree(), run(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), runall(), rundst_spiNo(), runmb(), and spiNo2().
int Fun4AllServer::registerSubsystem (SubsysReco * subsystem, const std::string & topnodename = "TOP")
Definition at line 177 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 177 of file Fun4AllServer.cc
References default_Tdirectory, Fun4AllReturnCodes::DONOTREGISTERSUBSYSTEM, Acts::UnitConstants::e, ffamemtracker, SubsysReco::Init(), instance(), Fun4AllBase::Name(), PHWHERE, RetCodes, Fun4AllMemoryTracker::Start(), Fun4AllMemoryTracker::Stop(), Subsystems, TDirCollection, timer_map, topNode(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by alignment(), AnalyzeTree(), Bbc_Reco(), BeginRun(), build_truthreco_tables(), CaloTrigger_Sim(), CEMC_Cells(), CEMC_Clusters(), CEMC_Eval(), CEMC_QA(), CEMC_Towers(), Centrality(), clus_dst_simple_superfastcalib(), ConfigureInput(), ConstructGeometry(), convert_seeds(), Distortions_QA(), dst_simple_towerslope_runmacro(), EEMC_Cells(), EEMC_Clusters(), EEMC_Eval(), EEMC_Towers(), EGEM_FastSim_Reco(), EPD_Tiles(), FastSim_Reco_EIC(), FEMC_Cells(), FEMC_Clusters(), FEMC_Eval(), FEMC_Towers(), FGEM_FastSim_Eval(), FGEM_FastSim_Reco(), FHCAL_Cells(), FHCAL_Clusters(), FHCAL_Eval(), FHCAL_Towers(), Filter_Conversion_Electrons(), Fun(), Fun4All(), Fun4All_Ana(), Fun4All_Analysis(), Fun4All_AnaTutorial_DSTReadBack(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_Calo(), Fun4All_CaloAna(), Fun4All_CaloProduction(), Fun4All_CaloProduction_PreQM23(), Fun4All_CaloTreeGen(), Fun4All_CaloWaveFormSim(), Fun4All_CentralityValidation(), Fun4All_Condor(), Fun4All_EICAnalysis_DIS(), Fun4All_EICAnalysis_DISReco(), Fun4All_EICAnalysis_DVCS(), Fun4All_EICAnalysis_Exclusive(), Fun4All_EICAnalysis_Leptoquarks(), Fun4All_EICAnalysis_Quarkonia(), Fun4All_EICAnalysis_TrackEval(), Fun4All_EMCal(), Fun4All_EMCal_Hist(), Fun4All_EMCal_sp(), Fun4All_EMCalBadTowerID(), Fun4All_EMCalLikelihood(), Fun4All_EMJetVal(), Fun4All_FillChargesMap_300evts_MDC2(), Fun4All_FillDCMap(), Fun4All_G4_block(), Fun4All_G4_Calo(), Fun4All_G4_Calos(), Fun4All_G4_Clusters(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_analysis_nf(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_EICIR(), Fun4All_G4_Example01(), Fun4All_G4_Example02(), Fun4All_G4_Example03(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Geantino(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_MyDetector(), Fun4All_G4_Pi0_Tbt(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_SlopeCal(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_G4_Write_Dst(), Fun4All_Generator_Display(), Fun4All_HCALAnalysis(), Fun4All_HCalCalib(), Fun4All_HCalCalib_sim(), Fun4All_HCalJetPhiShift(), Fun4All_ImportGeom(), Fun4All_IsolatedTrackAnalysis(), Fun4All_JetAna(), Fun4All_JetAna_MDC(), Fun4All_JetBkgd(), Fun4All_JetBkgd_Embed(), Fun4All_JetNconst(), Fun4All_JetRhoMedian(), Fun4All_JetSeedCount(), Fun4All_JetSub(), Fun4All_JetVal(), Fun4All_LEDTowerBuilder(), Fun4All_MBDTreeGen(), Fun4All_MCEventGen(), Fun4All_MDCTreeMaker(), Fun4All_MySimpleReco(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_PRDF(), Fun4All_Pythia6(), Fun4All_Read_Dst(), Fun4All_ReadDST_TPCML(), Fun4All_RhoFluct(), Fun4All_RICHReco(), Fun4All_RTrack(), Fun4All_RunEMCReco(), Fun4All_RunNewTruthMatcher(), Fun4All_RunPi0ClusterAna(), Fun4All_RunPi0Efficiency(), Fun4All_RunSinglePhotonClusterAna(), Fun4All_single_particle(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4All_Templates(), Fun4All_TestBeam(), Fun4All_TestBeam_Ana(), Fun4All_TestBeam_ExampleAnalysisModule(), Fun4All_TestBeam_HCAL_SampleFrac(), Fun4All_TestBeam_HCAL_ShowerCalib(), Fun4All_TestBeam_HCAL_TowerCalib(), Fun4All_TestBeam_ShowerCalib(), Fun4All_TestBeam_TPC(), Fun4All_testEtIso_Hijing(), Fun4All_testEtIso_Pythia(), Fun4All_testingGround(), Fun4All_TPC_EventDisplayPrep(), Fun4All_TPC_UnpackPRDF(), Fun4All_TPC_UnpackPRDF_Batch(), Fun4All_UE_v2_Psi2(), Fun4All_Year1(), G4_HIJetReco(), G4_Lepto(), G4DSTreader(), G4DSTreader_EICDetector(), G4DSTreader_EICIR(), G4DSTreader_fsPHENIX(), G4KshortReconstruction(), G4Setup(), G4TTree(), generate_hepmc_bjet(), Global_FastSim(), Global_Reco(), hcal_toweridmacro(), HCALInner_Cells(), HCALInner_Clusters(), HCALInner_Eval(), HCALInner_QA(), HCALInner_Towers(), HCALOuter_Cells(), HCALOuter_Clusters(), HCALOuter_Eval(), HCALOuter_QA(), HCALOuter_Towers(), HIJetReco(), InputRegister(), Intt_Cells(), Intt_Clustering(), Intt_QA(), Jet_Eval(), Jet_FwdEval(), Jet_FwdReco(), Jet_QA(), Jet_Reco(), Jin_BJet(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), KFParticle_QA(), HFjets::KFParticle_Set_Reco(), KFParticle_Upsilon_Reco(), MakeEdepNtuple(), MakeHijingCountNtuple(), MakeHijingShowerSize(), MakeHitCountNtuple(), MakeShowerSize(), MakeSigmaTimingNtuple(), MakeTimingNtuple(), MakeTowerTiming(), MakeTree(), Mbd_Reco(), Mvtx_Cells(), Mvtx_Clustering(), Mvtx_QA(), myDemoReco(), myHeavyFlavorReco(), MyHitTTree(), ParticleFlow(), QA_G4CaloTracking(), ReadFieldMap(), run(), Run_BbcCheck(), Run_BBCStudy(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), run_dump(), run_macro(), run_macro_2(), runall(), runanae(), runanajpsi(), runanaK(), runanapi(), runanapythiaupsilon(), RunBDiJetModule(), RunBJetModule(), RunBoth(), rundata(), rundst_spiNo(), RunGenFitTrackProp(), runmb(), runpairs(), seedResiduals(), ShowerCompress(), spiNo2(), srundst_mdc2_clustest(), Svtx_Cells(), Svtx_Clustering(), Svtx_Eval(), Svtx_Reco(), Svtx_Tracking(), TopoClusterReco(), toweridmacro(), towerslope_dst_runner(), TPC_Clustering(), TPC_LaserClustering(), TPC_QA(), Track_Matching(), Tracking_Eval(), Tracking_QA(), Tracking_Reco_TrackSeed_pass1(), tsdst_plus_tsfit(), vertexing(), wholeIter_Pi0EtaByEta(), Wrapper(), ZDC_Eval(), and ZDC_Towers().
int Fun4AllServer::registerSyncManager (Fun4AllSyncManager * newmaster)
Definition at line 1622 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1622 of file Fun4AllServer.cc
References Fun4AllBase::Name(), SyncManagers, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
int Fun4AllServer::Reset ()
Definition at line 767 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 767 of file Fun4AllServer.cc
References HistoManager, i, Subsystems, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_EVEN_MORE.
Referenced by ~Fun4AllServer().
int Fun4AllServer::ResetNodeTree ()
Definition at line 745 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 745 of file Fun4AllServer.cc
References PHNodeIterator::cd(), PHNodeIterator::forEach(), reset(), topnodemap, PHNodeOperation::Verbosity(), and Fun4AllBase::Verbosity().
Referenced by process_event(), and run().
int Fun4AllServer::retcodestats (const int iret) inline
Definition at line 108 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 108 of file Fun4AllServer.h
References retcodesmap.
int Fun4AllServer::run (const int nevnts = 0, const bool require_nevents = false)
run n events (0 means up to end of file)
Definition at line 1341 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1341 of file Fun4AllServer.cc
References Fun4AllReturnCodes::ABORTEVENT, BeginRun(), EndRun(), PHFlag::FlagExist(), PHFlag::get_IntFlag(), recoConsts::instance(), process_event(), Fun4AllReturnCodes::RESET_NODE_TREE, ResetNodeTree(), RetCodes, runnumber, setRun(), SyncManagers, Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_MORE, and Fun4AllBase::VERBOSITY_QUIET.
Referenced by AnalyzeTree(), clus_dst_simple_superfastcalib(), ConstructGeometry(), dst_simple_towerslope_runmacro(), Fun(), Fun4All(), Fun4All_Ana(), Fun4All_Analysis(), Fun4All_AnaTutorial_DSTReadBack(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_Calo(), Fun4All_CaloAna(), Fun4All_CaloProduction(), Fun4All_CaloProduction_PreQM23(), Fun4All_CaloTreeGen(), Fun4All_CaloWaveFormSim(), Fun4All_CentralityValidation(), Fun4All_Combiner(), Fun4All_Condor(), Fun4All_EICAnalysis_DIS(), Fun4All_EICAnalysis_DISReco(), Fun4All_EICAnalysis_DVCS(), Fun4All_EICAnalysis_Exclusive(), Fun4All_EICAnalysis_Leptoquarks(), Fun4All_EICAnalysis_Quarkonia(), Fun4All_EICAnalysis_TrackEval(), Fun4All_EMCal(), Fun4All_EMCal_Hist(), Fun4All_EMCal_sp(), Fun4All_EMCalBadTowerID(), Fun4All_EMCalLikelihood(), Fun4All_EMJetVal(), Fun4All_ExportGeom(), Fun4All_FillChargesMap_300evts_MDC2(), Fun4All_FillDCMap(), Fun4All_G4_block(), Fun4All_G4_Calo(), Fun4All_G4_Calos(), Fun4All_G4_Clusters(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_analysis(), Fun4All_G4_EICDetector_LQ_analysis_nf(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_EICIR(), Fun4All_G4_Example01(), Fun4All_G4_Example02(), Fun4All_G4_Example03(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Geantino(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_MyDetector(), Fun4All_G4_Pi0_Tbt(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_SlopeCal(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_G4_Write_Dst(), Fun4All_Generator_Display(), Fun4All_GeoExtract(), Fun4All_HCALAnalysis(), Fun4All_HCalCalib(), Fun4All_HCalCalib_sim(), Fun4All_HCalJetPhiShift(), Fun4All_hijbkg(), Fun4All_ImportGeom(), Fun4All_Intt_Combiner(), Fun4All_IsolatedTrackAnalysis(), Fun4All_JetAna(), Fun4All_JetAna_MDC(), Fun4All_JetBkgd(), Fun4All_JetBkgd_Embed(), Fun4All_JetNconst(), Fun4All_JetRhoMedian(), Fun4All_JetSeedCount(), Fun4All_JetSub(), Fun4All_JetVal(), Fun4All_LEDTowerBuilder(), Fun4All_MBDTreeGen(), Fun4All_MCEventGen(), Fun4All_MDCTreeMaker(), Fun4All_Mvtx_Combiner(), Fun4All_MySimpleReco(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_PRDF(), Fun4All_Pythia6(), Fun4All_pythiaEMCalAna(), Fun4All_quickHijing_Prod(), Fun4All_Read_Dst(), Fun4All_ReadDST_TPCML(), Fun4All_RhoFluct(), Fun4All_RICHReco(), Fun4All_RTrack(), Fun4All_RunEMCReco(), Fun4All_RunNewTruthMatcher(), Fun4All_RunPi0ClusterAna(), Fun4All_RunPi0Efficiency(), Fun4All_RunSinglePhotonClusterAna(), Fun4All_single_particle(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4All_Stream_Combiner(), Fun4All_Templates(), Fun4All_TestBeam(), Fun4All_TestBeam_Ana(), Fun4All_TestBeam_ExampleAnalysisModule(), Fun4All_TestBeam_HCAL_SampleFrac(), Fun4All_TestBeam_HCAL_ShowerCalib(), Fun4All_TestBeam_HCAL_TowerCalib(), Fun4All_TestBeam_ShowerCalib(), Fun4All_TestBeam_TPC(), Fun4All_testingGround(), Fun4All_Tpc_Combiner(), Fun4All_TPC_EventDisplayPrep(), Fun4All_TPC_UnpackPRDF(), Fun4All_TPC_UnpackPRDF_Batch(), Fun4All_UE_v2_Psi2(), Fun4All_Year1(), G4_HIJetReco(), G4TTree(), generate_hepmc_bjet(), hcal_toweridmacro(), Jin_BJet(), MakeEdepNtuple(), MakeHijingCountNtuple(), MakeHijingShowerSize(), MakeHitCountNtuple(), MakeShowerSize(), MakeSigmaTimingNtuple(), MakeTimingNtuple(), MakeTowerTiming(), MakeTree(), MyHitTTree(), PHGeom_DSTInspection(), ReadFieldMap(), run(), Run_BbcCheck(), Run_BBCStudy(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), run_dump(), run_macro(), run_macro_2(), runall(), runanae(), runanajpsi(), runanaK(), runanapi(), runanapythiaupsilon(), RunBDiJetModule(), RunBJetModule(), RunBoth(), rundata(), rundst_spiNo(), RunGenFitTrackProp(), runmb(), runpairs(), Fun4AllMessenger::SetNewValue(), spiNo2(), srundst_mdc2_clustest(), OnCalServer::SyncCalibTimeStampsToOnCal(), OnCalServer::SyncOncalTimeStampsToRunDB(), TestCDBSubsysReco(), toweridmacro(), towerslope_dst_runner(), tsdst_plus_tsfit(), wholeIter_Pi0EtaByEta(), and Wrapper().
int Fun4AllServer::RunNumber () const inline
Definition at line 115 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 115 of file Fun4AllServer.h
References runnumber.
Referenced by SyncReco::process_event(), and HeadReco::process_event().
int Fun4AllServer::SegmentNumber ()
Definition at line 1577 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1577 of file Fun4AllServer.cc
References defaultSyncManager, and Fun4AllSyncManager::SegmentNumber().
Referenced by SyncReco::process_event(), and Fun4AllFileOutStream::WriteEventOut().
int Fun4AllServer::setBranches (const std::string & managername)
Definition at line 1544 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1544 of file Fun4AllServer.cc
References SyncManagers.
int Fun4AllServer::setBranches ()
Definition at line 1555 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1555 of file Fun4AllServer.cc
References SyncManagers.
int Fun4AllServer::setRun (const int runnumber) protected
Definition at line 1661 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1661 of file Fun4AllServer.cc
References PHFlag::FlagExist(), FrameWorkVars, PHFlag::get_uint64Flag(), recoConsts::instance(), RUNNUMBERBIN, PHFlag::set_IntFlag(), and PHFlag::set_uint64Flag().
Referenced by run().
int Fun4AllServer::skip (const int nevnts = 0)
skip n events (0 means up to the end of file). Skip means read, don't process.
Definition at line 1495 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1495 of file Fun4AllServer.cc
References eventcounter, and SyncManagers.
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_CaloProduction(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_JetSeedCount(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4All_Templates(), Fun4All_TestBeam_TPC(), Fun4All_TPC_UnpackPRDF(), and G4_HIJetReco().
std::map<const std::string, PHTimer>::const_iterator Fun4AllServer::timer_begin () inline
Definition at line 117 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 117 of file Fun4AllServer.h
References timer_map.
Referenced by TimerStats::process_event().
std::map<const std::string, PHTimer>::const_iterator Fun4AllServer::timer_end () inline
Definition at line 118 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 118 of file Fun4AllServer.h
References timer_map.
Referenced by TimerStats::process_event().
PHCompositeNode* Fun4AllServer::topNode () const inline
Definition at line 67 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 67 of file Fun4AllServer.h
References TopNode.
Referenced by BeginRun(), ConstructGeometry(), caloTowerEmbed::CreateNodeTree(), DisplayOn(), PHG4GDMLUtility::Dump_GDML(), Fun4All_ExportGeom(), Fun4All_Generator_Display(), Fun4All_ImportGeom(), Fun4AllHepMCInputManager::Fun4AllHepMCInputManager(), Fun4AllOscarInputManager::Fun4AllOscarInputManager(), Fun4AllPrdfInputManager::Fun4AllPrdfInputManager(), Fun4AllPrdfInputPoolManager::Fun4AllPrdfInputPoolManager(), Fun4AllStreamingInputManager::Fun4AllStreamingInputManager(), PHFieldUtility::GetFieldConfigNode(), PHFieldUtility::GetFieldMapNode(), getNode(), caloTowerEmbed::InitRun(), matscan(), PHGeom_DSTInspection(), QTGui(), Fun4AllInputManager::registerSubsystem(), registerSubsystem(), Fun4AllInputManager::RejectEvent(), and Fun4AllEventOutputManager::Write().
PHCompositeNode * Fun4AllServer::topNode (const std::string & name)
Definition at line 1260 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 1260 of file Fun4AllServer.cc
References AddTopNode(), InitNodeTree(), PHWHERE, and topnodemap.
int Fun4AllServer::unregisterSubsystem (SubsysReco * subsystem)
Definition at line 273 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 273 of file Fun4AllServer.cc
References DeleteSubsystems, and unregistersubsystem.
Referenced by OnCalServer::BeginRun().
int Fun4AllServer::unregisterSubsystemsNow () protected
Definition at line 281 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 281 of file Fun4AllServer.cc
References DeleteSubsystems, index, OutputManager, RetCodes, Subsystems, unregistersubsystem, UpdateEventSelector(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MORE.
Referenced by OnCalServer::BeginRun(), BeginRun(), and process_event().
int Fun4AllServer::UpdateEventSelector (Fun4AllOutputManager * manager) protected
Definition at line 383 of file Fun4AllServer.cc.
View newest version in sPHENIX GitHub at line 383 of file Fun4AllServer.cc
References Fun4AllOutputManager::EventSelector(), index, PHWHERE, Fun4AllOutputManager::RecoModuleIndex(), Subsystems, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_EVEN_MORE.
Referenced by registerOutputManager(), and unregisterSubsystemsNow().
Member Data Documentation
Fun4AllServer * Fun4AllServer::__instance = nullptr static protected
Definition at line 128 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 128 of file Fun4AllServer.h
Referenced by instance(), and ~Fun4AllServer().
PHTimeStamp* Fun4AllServer::beginruntimestamp = nullptr protected
Definition at line 132 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 132 of file Fun4AllServer.h
Referenced by BeginRun(), BeginRunTimeStamp(), and ~Fun4AllServer().
int Fun4AllServer::bortime_override = 0 protected
Definition at line 137 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 137 of file Fun4AllServer.h
Referenced by BeginRun(), and BeginRunTimeStamp().
std::vector<std::string> Fun4AllServer::ComplaintList protected
Definition at line 145 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 145 of file Fun4AllServer.h
Referenced by AddComplaint(), End(), and process_event().
std::string Fun4AllServer::default_Tdirectory = "Rint:/" protected
Definition at line 154 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 154 of file Fun4AllServer.h
Referenced by OnCalServer::BeginRun(), BeginRun(), OnCalServer::End(), End(), EndRun(), process_event(), and registerSubsystem().
Fun4AllSyncManager* Fun4AllServer::defaultSyncManager = nullptr protected
Definition at line 134 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 134 of file Fun4AllServer.h
Referenced by DstEvents(), GetInputFullFileList(), getSyncManager(), InitAll(), PrdfEvents(), registerInputManager(), and SegmentNumber().
std::vector<std::pair<SubsysReco *, PHCompositeNode *> > Fun4AllServer::DeleteSubsystems protected
Definition at line 147 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 147 of file Fun4AllServer.h
Referenced by unregisterSubsystem(), and unregisterSubsystemsNow().
int Fun4AllServer::eventcounter = 0 protected
Definition at line 142 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 142 of file Fun4AllServer.h
Referenced by BeginRun(), EventCounter(), process_event(), and skip().
int Fun4AllServer::eventnumber = 0 protected
Definition at line 141 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 141 of file Fun4AllServer.h
Referenced by EventNumber().
Fun4AllMemoryTracker* Fun4AllServer::ffamemtracker = nullptr protected
Definition at line 130 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 130 of file Fun4AllServer.h
Referenced by BeginRun(), BeginRunSubsystem(), PrintMemoryTracker(), process_event(), registerSubsystem(), and ~Fun4AllServer().
TH1* Fun4AllServer::FrameWorkVars = nullptr protected
Definition at line 129 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 129 of file Fun4AllServer.h
Referenced by InitAll(), and setRun().
std::vector<Fun4AllHistoManager *> Fun4AllServer::HistoManager protected
Definition at line 152 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 152 of file Fun4AllServer.h
Referenced by dumpHistos(), getHistoManager(), Print(), registerHistoManager(), Reset(), and ~Fun4AllServer().
int Fun4AllServer::keep_db_connected = 0 protected
Definition at line 143 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 143 of file Fun4AllServer.h
Referenced by KeepDBConnection().
std::deque<std::pair<SubsysReco *, std::string> > Fun4AllServer::NewSubsystems protected
Definition at line 148 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 148 of file Fun4AllServer.h
Referenced by addNewSubsystem(), and BeginRun().
int Fun4AllServer::OutNodeCount = 0 protected
Definition at line 136 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 136 of file Fun4AllServer.h
Referenced by process_event().
std::vector<Fun4AllOutputManager *> Fun4AllServer::OutputManager protected
Definition at line 150 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 150 of file Fun4AllServer.h
Referenced by End(), getOutputManager(), GetOutputManagerList(), outfileclose(), Print(), process_event(), registerOutputManager(), unregisterSubsystemsNow(), and ~Fun4AllServer().
std::vector<int> Fun4AllServer::RetCodes protected
Definition at line 149 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 149 of file Fun4AllServer.h
Referenced by process_event(), registerSubsystem(), run(), and unregisterSubsystemsNow().
std::map<int, int> Fun4AllServer::retcodesmap protected
Definition at line 156 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 156 of file Fun4AllServer.h
Referenced by process_event(), and retcodestats().
int Fun4AllServer::runnumber = 0 protected
Definition at line 140 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 140 of file Fun4AllServer.h
Referenced by OnCalServer::CreateCalibration(), run(), and RunNumber().
int Fun4AllServer::ScreamEveryEvent = 0 protected
Definition at line 138 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 138 of file Fun4AllServer.h
Referenced by AddComplaint(), End(), and process_event().
Fun4AllHistoManager* Fun4AllServer::ServerHistoManager = nullptr protected
Definition at line 131 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 131 of file Fun4AllServer.h
Referenced by dumpHistos(), getHisto(), getHistoName(), InitAll(), isHistoRegistered(), makeHisto(), and registerHisto().
std::vector<std::pair<SubsysReco *, PHCompositeNode *> > Fun4AllServer::Subsystems protected
Definition at line 146 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 146 of file Fun4AllServer.h
Referenced by OnCalServer::BeginRun(), BeginRun(), OnCalServer::End(), End(), EndRun(), GetModuleList(), getSubsysReco(), OnCalServer::Print(), Print(), OnCalServer::process_event(), process_event(), registerSubsystem(), Reset(), unregisterSubsystemsNow(), UpdateEventSelector(), and ~Fun4AllServer().
std::vector<Fun4AllSyncManager *> Fun4AllServer::SyncManagers protected
Definition at line 155 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 155 of file Fun4AllServer.h
Referenced by BranchSelect(), OnCalServer::End(), fileclose(), fileopen(), OnCalServer::FillRunListFromFileList(), getInputManager(), getSyncManager(), InitAll(), OnCalServer::Print(), Print(), process_event(), registerSyncManager(), run(), setBranches(), skip(), and ~Fun4AllServer().
std::vector<TDirectory *> Fun4AllServer::TDirCollection protected
Definition at line 151 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 151 of file Fun4AllServer.h
Referenced by registerSubsystem(), and ~Fun4AllServer().
std::map<const std::string, PHTimer> Fun4AllServer::timer_map protected
Definition at line 157 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 157 of file Fun4AllServer.h
Referenced by PrintTimer(), process_event(), registerSubsystem(), timer_begin(), and timer_end().
PHCompositeNode* Fun4AllServer::TopNode = nullptr protected
Definition at line 133 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 133 of file Fun4AllServer.h
Referenced by OnCalServer::BeginRun(), End(), InitAll(), NodeIdentify(), process_event(), and topNode().
std::map<std::string, PHCompositeNode *> Fun4AllServer::topnodemap protected
Definition at line 153 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 153 of file Fun4AllServer.h
Referenced by AddTopNode(), GetTopNodes(), InitAll(), Print(), ResetNodeTree(), topNode(), and ~Fun4AllServer().
int Fun4AllServer::unregistersubsystem = 0 protected
Definition at line 139 of file Fun4AllServer.h.
View newest version in sPHENIX GitHub at line 139 of file Fun4AllServer.h
Referenced by BeginRun(), process_event(), unregisterSubsystem(), and unregisterSubsystemsNow().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4all/Fun4AllServer.h
coresoftware/blob/master/offline/framework/fun4all/Fun4AllServer.cc