Analysis Software: kdfinder::CircleFit< T > Class Template Reference
kdfinder::CircleFit< T > Class Template Reference
#include <coresoftware/blob/master/offline/packages/PHTpcTracker/externals/kdfinder.hpp>
Public Member Functions
CircleFit ()
Static Public Member Functions
static Circle< T > * RegularFit (const std::vector< std::vector< T >> &hits, size_t fit=0)
static Circle< T > * RobustFit (const std::vector< std::vector< T >> &hits, Circle< T > *circle=0, T lambda=0.01)
Static Private Member Functions
static T Sigma (Data< T > &data, Circle< T > *circle)
static T ChiSqr (Data< T > &data, Circle< T > *circle)
static Circle< T > * CircleFitByHyper (const std::vector< std::vector< T >> &hits)
static Circle< T > * CircleFitByTaubin (const std::vector< std::vector< T >> &hits)
static Circle< T > * CircleFitByPratt (const std::vector< std::vector< T >> &hits)
static T pythag (T a, T b)
static T OptimalRadius (Data< T > &data, Circle< T > &circle)
static void eigen2x2 (T a, T b, T c, T &d1, T &d2, T &Vx, T &Vy)
static T SigmaWithLargeCircleOption (Data< T > &data, Circle< T > &circle)
static void GradientHessian (Data< T > &data, Circle< T > &circle, T &F1, T &F2, T &A11, T &A22, T &A12)
static int CircleFitByChernovHoussam (const std::vector< std::vector< T >> &hits, Circle< T > *circleIni=0, T LambdaIni=0.01)
Detailed Description
template<class T>
class kdfinder::CircleFit< T >
Definition at line 1354 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1354 of file kdfinder.hpp
Constructor & Destructor Documentation
template<class T > kdfinder::CircleFit< T >::CircleFit () inline
Definition at line 1357 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1357 of file kdfinder.hpp
Member Function Documentation
template<class T > static T kdfinder::CircleFit< T >::ChiSqr (Data< T > & data, Circle< T > * circle) inline static private
Definition at line 1395 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1395 of file kdfinder.hpp
References kdfinder::Circle< T >::a, kdfinder::Circle< T >::b, dx, dy, kdfinder::Data< T >::hits, kdfinder::Data< T >::hits_size, i, kdfinder::Circle< T >::r, sum(), and Acts::UnitConstants::T.
Referenced by kdfinder::CircleFit< T >::CircleFitByChernovHoussam(), kdfinder::CircleFit< T >::CircleFitByHyper(), kdfinder::CircleFit< T >::CircleFitByPratt(), and kdfinder::CircleFit< T >::CircleFitByTaubin().
template<class T > static int kdfinder::CircleFit< T >::CircleFitByChernovHoussam (const std::vector< std::vector< T >> & hits, Circle< T > * circleIni = 0, T LambdaIni = 0.01) inline static private
Definition at line 1856 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1856 of file kdfinder.hpp
References kdfinder::Circle< T >::a, kdfinder::abs(), kdfinder::Circle< T >::b, kdfinder::CircleFit< T >::ChiSqr(), configureMap::data, dx, Acts::Test::dX, dy, Acts::Test::dY, kdfinder::CircleFit< T >::eigen2x2(), F1, F2, kdfinder::Circle< T >::g, kdfinder::CircleFit< T >::GradientHessian(), kdfinder::Circle< T >::Gx, kdfinder::Circle< T >::Gy, kdfinder::Data< T >::hits, kdfinder::Data< T >::hits_size, i, kdfinder::Circle< T >::i, kdfinder::Circle< T >::initFromCircle(), kdfinder::Circle< T >::j, max, kdfinder::Data< T >::means(), kdfinder::Data< T >::meanX, kdfinder::Data< T >::meanY, n, Old, kdfinder::CircleFit< T >::OptimalRadius(), Acts::IntegrationTest::R, kdfinder::Circle< T >::r, kdfinder::CircleFit< T >::RegularFit(), kdfinder::Circle< T >::s, kdfinder::CircleFit< T >::SigmaWithLargeCircleOption(), and Acts::UnitConstants::T.
Referenced by kdfinder::CircleFit< T >::RobustFit().
template<class T > static Circle<T>* kdfinder::CircleFit< T >::CircleFitByHyper (const std::vector< std::vector< T >> & hits) inline static private
Definition at line 1407 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1407 of file kdfinder.hpp
References kdfinder::Circle< T >::a, kdfinder::abs(), kdfinder::Circle< T >::b, kdfinder::Circle< T >::chi2, kdfinder::CircleFit< T >::ChiSqr(), configureMap::data, Dy, kdfinder::Data< T >::hits, kdfinder::Data< T >::hits_size, i, kdfinder::Circle< T >::j, kdfinder::Data< T >::means(), kdfinder::Data< T >::meanX, kdfinder::Data< T >::meanY, kdfinder::Circle< T >::r, kdfinder::Circle< T >::s, kdfinder::CircleFit< T >::Sigma(), Acts::UnitConstants::T, x, and y.
Referenced by kdfinder::CircleFit< T >::RegularFit().
template<class T > static Circle<T>* kdfinder::CircleFit< T >::CircleFitByPratt (const std::vector< std::vector< T >> & hits) inline static private
Definition at line 1568 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1568 of file kdfinder.hpp
References kdfinder::Circle< T >::a, kdfinder::abs(), kdfinder::Circle< T >::b, kdfinder::Circle< T >::chi2, kdfinder::CircleFit< T >::ChiSqr(), configureMap::data, Dy, i, kdfinder::Circle< T >::j, kdfinder::Circle< T >::r, kdfinder::Circle< T >::s, kdfinder::CircleFit< T >::Sigma(), Acts::UnitConstants::T, x, and y.
Referenced by kdfinder::CircleFit< T >::RegularFit().
template<class T > static Circle<T>* kdfinder::CircleFit< T >::CircleFitByTaubin (const std::vector< std::vector< T >> & hits) inline static private
Definition at line 1489 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1489 of file kdfinder.hpp
References kdfinder::Circle< T >::a, kdfinder::abs(), kdfinder::Circle< T >::b, kdfinder::Circle< T >::chi2, kdfinder::CircleFit< T >::ChiSqr(), configureMap::data, Dy, i, kdfinder::Circle< T >::j, kdfinder::Circle< T >::r, kdfinder::Circle< T >::s, kdfinder::CircleFit< T >::Sigma(), Acts::UnitConstants::T, x, and y.
Referenced by kdfinder::CircleFit< T >::RegularFit().
template<class T > static void kdfinder::CircleFit< T >::eigen2x2 (T a, T b, T c, T & d1, T & d2, T & Vx, T & Vy) inline static private
Definition at line 1668 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1668 of file kdfinder.hpp
References KFPMath::a, kdfinder::abs(), KFPMath::b, c, kdfinder::CircleFit< T >::pythag(), and Acts::UnitConstants::T.
Referenced by kdfinder::CircleFit< T >::CircleFitByChernovHoussam().
template<class T > static void kdfinder::CircleFit< T >::GradientHessian (Data< T > & data, Circle< T > & circle, T & F1, T & F2, T & A11, T & A22, T & A12) inline static private
Definition at line 1751 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1751 of file kdfinder.hpp
References KFPMath::a, kdfinder::Circle< T >::a, kdfinder::abs(), KFPMath::b, kdfinder::Circle< T >::b, c, dx, dy, Acts::UnitConstants::g, kdfinder::Data< T >::hits, kdfinder::Data< T >::hits_size, i, kdfinder::Data< T >::meanX, kdfinder::Data< T >::meanY, n, p, Acts::IntegrationTest::R, r, Acts::UnitConstants::s, t, Acts::UnitConstants::T, Acts::UnitConstants::u, v, x, TauVsDIS_MachineLearning_Differentiation::X, y, TauVsDIS_MachineLearning_Differentiation::Y, and z.
Referenced by kdfinder::CircleFit< T >::CircleFitByChernovHoussam().
template<class T > static T kdfinder::CircleFit< T >::OptimalRadius (Data< T > & data, Circle< T > & circle) inline static private
Definition at line 1656 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1656 of file kdfinder.hpp
References kdfinder::Circle< T >::a, kdfinder::Circle< T >::b, dx, dy, kdfinder::Data< T >::hits, kdfinder::Data< T >::hits_size, i, and Acts::UnitConstants::T.
Referenced by kdfinder::CircleFit< T >::CircleFitByChernovHoussam().
template<class T > static T kdfinder::CircleFit< T >::pythag (T a, T b) inline static private
Definition at line 1646 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1646 of file kdfinder.hpp
References kdfinder::abs(), and Acts::UnitConstants::T.
Referenced by kdfinder::CircleFit< T >::eigen2x2().
template<class T > static Circle<T>* kdfinder::CircleFit< T >::RegularFit (const std::vector< std::vector< T >> & hits, size_t fit = 0) inline static
Definition at line 1359 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1359 of file kdfinder.hpp
References kdfinder::CircleFit< T >::CircleFitByHyper(), kdfinder::CircleFit< T >::CircleFitByPratt(), kdfinder::CircleFit< T >::CircleFitByTaubin(), and fit().
Referenced by kdfinder::CircleFit< T >::CircleFitByChernovHoussam(), and kdfinder::TrackCandidate< T >::radiusFit().
template<class T > static Circle<T>* kdfinder::CircleFit< T >::RobustFit (const std::vector< std::vector< T >> & hits, Circle< T > * circle = 0, T lambda = 0.01) inline static
Definition at line 1376 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1376 of file kdfinder.hpp
References kdfinder::CircleFit< T >::CircleFitByChernovHoussam().
Referenced by kdfinder::TrackCandidate< T >::radiusFit().
template<class T > static T kdfinder::CircleFit< T >::Sigma (Data< T > & data, Circle< T > * circle) inline static private
Definition at line 1383 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1383 of file kdfinder.hpp
References kdfinder::Circle< T >::a, kdfinder::Circle< T >::b, dx, dy, kdfinder::Data< T >::hits, kdfinder::Data< T >::hits_size, i, kdfinder::Circle< T >::r, sum(), and Acts::UnitConstants::T.
Referenced by kdfinder::CircleFit< T >::CircleFitByHyper(), kdfinder::CircleFit< T >::CircleFitByPratt(), and kdfinder::CircleFit< T >::CircleFitByTaubin().
template<class T > static T kdfinder::CircleFit< T >::SigmaWithLargeCircleOption (Data< T > & data, Circle< T > & circle) inline static private
Definition at line 1705 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1705 of file kdfinder.hpp
References kdfinder::Circle< T >::a, kdfinder::abs(), kdfinder::Circle< T >::b, c, dx, dy, Acts::UnitConstants::g, kdfinder::Data< T >::hits, kdfinder::Data< T >::hits_size, i, kdfinder::Data< T >::meanX, kdfinder::Data< T >::meanY, n, p, r, Acts::UnitConstants::s, sum(), t, Acts::UnitConstants::T, x, y, z, and SVM_v1::Z.
Referenced by kdfinder::CircleFit< T >::CircleFitByChernovHoussam().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/PHTpcTracker/externals/kdfinder.hpp