Analysis Software: analysis/blob/master/FrawleyTrackEvalMacros/CBfitter_jpsi_1state.C File Reference
CBfitter_jpsi_1state.C File Reference
#include <TF1.h>
#include <TMath.h>
#include <TFile.h>
#include <TCanvas.h>
#include <TH1.h>
#include <TH2.h>
#include <TGraph.h>
#include <TGraphErrors.h>
#include <TLegend.h>
#include <TStyle.h>
#include <TROOT.h>
#include <TLatex.h>
Functions
Double_t CBcalc (Double_t *xx, Double_t *par)
Double_t CBcalc_exp (Double_t *xx, Double_t *par)
Double_t CBcalc_LL (Double_t *xx, Double_t *par)
Double_t Upscalc (Double_t *xx, Double_t *par)
void CBfitter_jpsi_1state ()
Variables
TH1D * recomass
TH1D * recomassFG
TH1D * recomassBG
Function Documentation
Double_t CBcalc (Double_t * xx, Double_t * par)
Definition at line 18 of file CBfitter_jpsi_1state.C.
View newest version in sPHENIX GitHub at line 18 of file CBfitter_jpsi_1state.C
References A, alpha, f, n, N, sigma, and ambiguity_solver_full_chain::x.
Double_t CBcalc_exp (Double_t * xx, Double_t * par)
Definition at line 50 of file CBfitter_jpsi_1state.C.
View newest version in sPHENIX GitHub at line 50 of file CBfitter_jpsi_1state.C
References A, alpha, f, n, N, sigma, and ambiguity_solver_full_chain::x.
Referenced by CBfitter_jpsi_LL_single().
Double_t CBcalc_LL (Double_t * xx, Double_t * par)
Definition at line 87 of file CBfitter_jpsi_1state.C.
View newest version in sPHENIX GitHub at line 87 of file CBfitter_jpsi_1state.C
References A, alpha, f, configureMap::ibin, n, N, recomassBG, sigma, and ambiguity_solver_full_chain::x.
Referenced by CBfitter_jpsi_LL_single().
void CBfitter_jpsi_1state ()
Definition at line 192 of file CBfitter_jpsi_1state.C.
View newest version in sPHENIX GitHub at line 192 of file CBfitter_jpsi_1state.C
References CBcalc(), INTTVtxZ::fname, mean(), recomass, and sigma.
Double_t Upscalc (Double_t * xx, Double_t * par)
Definition at line 142 of file CBfitter_jpsi_1state.C.
View newest version in sPHENIX GitHub at line 142 of file CBfitter_jpsi_1state.C
References CBcalc(), std::tr1::f1, std::tr1::f2, std::tr1::f3, mass, and ambiguity_solver_full_chain::x.
Variable Documentation
TH1D* recomass
Definition at line 14 of file CBfitter_jpsi_1state.C.
View newest version in sPHENIX GitHub at line 14 of file CBfitter_jpsi_1state.C
Referenced by CBfitter(), CBfitter_1state(), CBfitter_jpsi_1state(), project_quarkonium_mass(), and quarkonia_reconstruction_embedded().
TH1D* recomassBG
Definition at line 16 of file CBfitter_jpsi_1state.C.
View newest version in sPHENIX GitHub at line 16 of file CBfitter_jpsi_1state.C
Referenced by CBcalc_LL(), and CBfitter_jpsi_LL_single().
TH1D* recomassFG
Definition at line 15 of file CBfitter_jpsi_1state.C.
View newest version in sPHENIX GitHub at line 15 of file CBfitter_jpsi_1state.C
Referenced by CBfitter_jpsi_LL_single().