Analysis Software: LazyTiling25 Class Reference
LazyTiling25 Class Reference
Public Member Functions
LazyTiling25 (ClusterSequence &cs)
void run ()
Protected Member Functions
void _initialise_tiles ()
int _tile_index (int ieta, int iphi) const
void _bj_remove_from_tiles (TiledJet *const jet)
int _tile_index (const double eta, const double phi) const
void _tj_set_jetinfo (TiledJet *const jet, const int _jets_index)
void _print_tiles (TiledJet *briefjets) const
void _add_neighbours_to_tile_union (const int tile_index, std::vector< int > &tile_union, int &n_near_tiles) const
void _add_untagged_neighbours_to_tile_union (const int tile_index, std::vector< int > &tile_union, int &n_near_tiles)
void _add_untagged_neighbours_to_tile_union_using_max_info (const TiledJet *const jet, std::vector< int > &tile_union, int &n_near_tiles)
double _distance_to_tile (const TiledJet *bj, const Tile25 *) const
void _update_jetX_jetI_NN (TiledJet *jetX, TiledJet *jetI, std::vector< TiledJet * > &jets_for_minheap)
void _set_NN (TiledJet *jetI, std::vector< TiledJet * > &jets_for_minheap)
template<class J >
double _bj_diJ (const J *const jet) const
template<class J >
void _bj_set_jetinfo (J *const jetA, const int _jets_index) const
template<class J >
double _bj_dist (const J *const jetA, const J *const jetB) const
template<class J >
double _bj_dist_not_periodic (const J *const jetA, const J *const jetB) const
Protected Attributes
ClusterSequence & _cs
const std::vector< PseudoJet > & _jets
std::vector< Tile25 > _tiles
double _Rparam
double _R2
double _invR2
double _tiles_eta_min
double _tiles_eta_max
double _tile_size_eta
double _tile_size_phi
double _tile_half_size_eta
double _tile_half_size_phi
int _n_tiles_phi
int _tiles_ieta_min
int _tiles_ieta_max
std::vector< TiledJet * > _jets_for_minheap
Detailed Description
Definition at line 1060 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1060 of file fjcore.cc
Constructor & Destructor Documentation
FJCORE_BEGIN_NAMESPACE LazyTiling25::LazyTiling25 (ClusterSequence & cs)
Definition at line 4944 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4944 of file fjcore.cc
References _initialise_tiles(), _invR2, _R2, and _Rparam.
Member Function Documentation
void LazyTiling25::_add_neighbours_to_tile_union (const int tile_index, std::vector< int > & tile_union, int & n_near_tiles) const protected
Definition at line 5110 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5110 of file fjcore.cc
References _tiles.
void LazyTiling25::_add_untagged_neighbours_to_tile_union (const int tile_index, std::vector< int > & tile_union, int & n_near_tiles) inline protected
Definition at line 5118 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5118 of file fjcore.cc
References _tiles.
void LazyTiling25::_add_untagged_neighbours_to_tile_union_using_max_info (const TiledJet *const jet, std::vector< int > & tile_union, int & n_near_tiles) inline protected
Definition at line 5130 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5130 of file fjcore.cc
References _distance_to_tile(), _tiles, dist(), tile(), tile_edge_security_margin, and TiledJet::tile_index.
Referenced by run().
template<class J > double LazyTiling25::_bj_diJ (const J *const jet) const inline protected
Definition at line 1101 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1101 of file fjcore.cc
Referenced by run().
template<class J > double LazyTiling25::_bj_dist (const J *const jetA, const J *const jetB) const inline protected
Definition at line 1115 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1115 of file fjcore.cc
References INTTVtxZ::dphi, pi, and twopi.
Referenced by _set_NN(), _update_jetX_jetI_NN(), and run().
template<class J > double LazyTiling25::_bj_dist_not_periodic (const J *const jetA, const J *const jetB) const inline protected
Definition at line 1128 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1128 of file fjcore.cc
References INTTVtxZ::dphi.
Referenced by run().
void LazyTiling25::_bj_remove_from_tiles (TiledJet *const jet) protected
Definition at line 5084 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5084 of file fjcore.cc
References _tiles, TiledJet::next, TiledJet::previous, tile(), and TiledJet::tile_index.
Referenced by run().
template<class J > void LazyTiling25::_bj_set_jetinfo (J *const jetA, const int _jets_index) const inline protected
Definition at line 1106 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1106 of file fjcore.cc
References LazyTiling9::_cs, LazyTiling9::_jets, and LazyTiling9::_R2.
double LazyTiling25::_distance_to_tile (const TiledJet * bj, const Tile25 * tile) const inline protected
Definition at line 5143 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5143 of file fjcore.cc
References INTTVtxZ::dphi, TiledJet::eta, TiledJet::phi, pi, TiledJet::tile_index, and twopi.
Referenced by _add_untagged_neighbours_to_tile_union_using_max_info(), _set_NN(), and run().
void LazyTiling25::_initialise_tiles () protected
Definition at line 4956 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4956 of file fjcore.cc
References _cs, _jets, _n_tiles_phi, _Rparam, _tile_half_size_eta, _tile_half_size_phi, _tile_index(), _tile_size_eta, _tile_size_phi, _tiles, _tiles_eta_max, _tiles_eta_min, _tiles_ieta_max, _tiles_ieta_min, eta, i, TilingExtent::maxrap(), TilingExtent::minrap(), tile(), and twopi.
Referenced by LazyTiling25().
void LazyTiling25::_print_tiles (TiledJet * briefjets) const protected
Definition at line 5095 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5095 of file fjcore.cc
References _tiles, i, Acts::Experimental::detail::BlueprintHelper::sort(), and tile().
void LazyTiling25::_set_NN (TiledJet * jetI, std::vector< TiledJet * > & jets_for_minheap) inline protected
Definition at line 5177 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5177 of file fjcore.cc
References _bj_dist(), _distance_to_tile(), _R2, _tiles, dist(), TiledJet::label_minheap_update_needed(), TiledJet::minheap_update_needed(), TiledJet::next, TiledJet::NN, TiledJet::NN_dist, and TiledJet::tile_index.
Referenced by run().
int LazyTiling25::_tile_index (int ieta, int iphi) const inline protected
Definition at line 1079 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1079 of file fjcore.cc
References LazyTiling9::_n_tiles_phi, and LazyTiling9::_tiles_ieta_min.
Referenced by _initialise_tiles(), and _tj_set_jetinfo().
int LazyTiling25::_tile_index (const double eta, const double phi) const protected
Definition at line 5062 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5062 of file fjcore.cc
References _n_tiles_phi, _tile_size_eta, _tile_size_phi, _tiles_eta_max, _tiles_eta_min, _tiles_ieta_max, _tiles_ieta_min, and twopi.
void LazyTiling25::_tj_set_jetinfo (TiledJet *const jet, const int _jets_index) inline protected
Definition at line 5074 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5074 of file fjcore.cc
References _tile_index(), _tiles, and tile().
Referenced by run().
void LazyTiling25::_update_jetX_jetI_NN (TiledJet * jetX, TiledJet * jetI, std::vector< TiledJet * > & jets_for_minheap) inline protected
Definition at line 5159 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5159 of file fjcore.cc
References _bj_dist(), dist(), TiledJet::label_minheap_update_needed(), TiledJet::minheap_update_needed(), TiledJet::NN, and TiledJet::NN_dist.
Referenced by run().
void LazyTiling25::run ()
Definition at line 5197 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5197 of file fjcore.cc
References _add_untagged_neighbours_to_tile_union_using_max_info(), _bj_diJ(), _bj_dist(), _bj_dist_not_periodic(), _bj_remove_from_tiles(), _cs, _distance_to_tile(), _invR2, _jets, TiledJet::_jets_index, _set_NN(), _tiles, _tj_set_jetinfo(), _update_jetX_jetI_NN(), dist(), i, TiledJet::label_minheap_update_done(), MinHeap::minloc(), MinHeap::minval(), n, TiledJet::next, TiledJet::NN, TiledJet::NN_dist, MinHeap::remove(), swap(), tile(), TiledJet::tile_index, and MinHeap::update().
Referenced by ClusterSequence::_initialise_and_run_no_decant().
Member Data Documentation
ClusterSequence& LazyTiling25::_cs protected
Definition at line 1065 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1065 of file fjcore.cc
Referenced by _initialise_tiles(), and run().
double LazyTiling25::_invR2 protected
Definition at line 1072 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1072 of file fjcore.cc
Referenced by LazyTiling25(), and run().
const std::vector<PseudoJet>& LazyTiling25::_jets protected
Definition at line 1066 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1066 of file fjcore.cc
Referenced by _initialise_tiles(), and run().
std::vector<TiledJet *> LazyTiling25::_jets_for_minheap protected
Definition at line 1077 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1077 of file fjcore.cc
int LazyTiling25::_n_tiles_phi protected
Definition at line 1076 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1076 of file fjcore.cc
Referenced by _initialise_tiles(), and _tile_index().
double LazyTiling25::_R2 protected
Definition at line 1072 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1072 of file fjcore.cc
Referenced by _set_NN(), and LazyTiling25().
double LazyTiling25::_Rparam protected
Definition at line 1072 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1072 of file fjcore.cc
Referenced by _initialise_tiles(), and LazyTiling25().
double LazyTiling25::_tile_half_size_eta protected
Definition at line 1075 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1075 of file fjcore.cc
Referenced by _initialise_tiles().
double LazyTiling25::_tile_half_size_phi protected
Definition at line 1075 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1075 of file fjcore.cc
Referenced by _initialise_tiles().
double LazyTiling25::_tile_size_eta protected
Definition at line 1074 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1074 of file fjcore.cc
Referenced by _initialise_tiles(), and _tile_index().
double LazyTiling25::_tile_size_phi protected
Definition at line 1074 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1074 of file fjcore.cc
Referenced by _initialise_tiles(), and _tile_index().
std::vector<Tile25> LazyTiling25::_tiles protected
Definition at line 1067 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1067 of file fjcore.cc
Referenced by _add_neighbours_to_tile_union(), _add_untagged_neighbours_to_tile_union(), _add_untagged_neighbours_to_tile_union_using_max_info(), _bj_remove_from_tiles(), _initialise_tiles(), _print_tiles(), _set_NN(), _tj_set_jetinfo(), and run().
double LazyTiling25::_tiles_eta_max protected
Definition at line 1073 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1073 of file fjcore.cc
Referenced by _initialise_tiles(), and _tile_index().
double LazyTiling25::_tiles_eta_min protected
Definition at line 1073 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1073 of file fjcore.cc
Referenced by _initialise_tiles(), and _tile_index().
int LazyTiling25::_tiles_ieta_max protected
Definition at line 1076 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1076 of file fjcore.cc
Referenced by _initialise_tiles(), and _tile_index().
int LazyTiling25::_tiles_ieta_min protected
Definition at line 1076 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1076 of file fjcore.cc
Referenced by _initialise_tiles(), and _tile_index().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/fjcore.cc