Analysis Software: Jetscape::Hadron Class Reference
Jetscape::Hadron Class Reference
#include <JETSCAPE/blob/main/src/framework/JetScapeParticles.h>
Public Member Functions
Hadron (int label, int id, int stat, const FourVector &p, const FourVector &x)
Hadron (int label, int id, int stat, double pt, double eta, double phi, double e, double *x=0)
Hadron (int label, int id, int stat, const FourVector &p, const FourVector &x, double mass)
Hadron (const Hadron &srh)
Hadron & operator= (Hadron &c)
Hadron & operator= (const Hadron &c)
void set_decay_width (double width)
double decay_width ()
bool CheckOrForceHadron (const int id, const double mass=0)
bool has_no_position ()
Returns true when all x entries of the hadrons are (close to) 0.
Public Member Functions inherited from Jetscape::JetScapeParticleBase
void reset_momentum (const double px, const double py, const double pz, const double e)
void reset_momentum (const FourVector &p)
fjcore::PseudoJet GetPseudoJet () const
No implicit cast to PseudoJet is allowed, provide a conversion.
JetScapeParticleBase ()
JetScapeParticleBase (int label, int id, int stat, const FourVector &p, const FourVector &x)
JetScapeParticleBase (int label, int id, int stat, double pt, double eta, double phi, double e, double *x=0)
JetScapeParticleBase (int label, int id, int stat, const FourVector &p, const FourVector &x, double mass)
JetScapeParticleBase (const JetScapeParticleBase &srp)
virtual ~JetScapeParticleBase ()
void clear ()
void set_label (int label)
void set_id (int id)
void set_stat (int stat)
void set_x (double x[4])
void init_jet_v ()
void set_jet_v (double v[4])
void set_jet_v (FourVector j)
bool SetController (string controller="")
void UnsetController ()
const int pid () const
const int pstat () const
const int plabel () const
const double time () const
std::vector< JetScapeParticleBase > parents ()
const FourVector p_in () const
const FourVector & x_in () const
const FourVector & jet_v () const
const double restmass ()
const double p (int i)
double pl ()
const double nu ()
const double t_max ()
virtual JetScapeParticleBase & operator= (JetScapeParticleBase &c)
virtual JetScapeParticleBase & operator= (const JetScapeParticleBase &c)
string GetController () const
bool GetControlled () const
Protected Attributes
double width_
Protected Attributes inherited from Jetscape::JetScapeParticleBase
int pid_
particle id
int pstat_
status of particle
int plabel_
the line number in the event record
double mass_
rest mass of the particle
FourVector x_in_
position of particle
FourVector jet_v_
jet four vector, without gamma factor (so not really a four vector)
bool controlled_ = false
check whether a module claimed responsibility of this particle
string controller_ = ""
Additional Inherited Members
Static Public Attributes inherited from Jetscape::JetScapeParticleBase
static Pythia8::Pythia InternalHelperPythia
Protected Member Functions inherited from Jetscape::JetScapeParticleBase
void set_restmass (double mass_input)
shouldn't be called from the outside, needs to be consistent with PID
Detailed Description
Definition at line 375 of file JetScapeParticles.h.
View newest version in sPHENIX GitHub at line 375 of file JetScapeParticles.h
Constructor & Destructor Documentation
Jetscape::Hadron::Hadron (int label, int id, int stat, const FourVector & p, const FourVector & x)
Definition at line 457 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 457 of file JetScapeParticles.cc
References assert, CheckOrForceHadron(), and set_decay_width().
Jetscape::Hadron::Hadron (int label, int id, int stat, double pt, double eta, double phi, double e, double * x = 0)
Definition at line 465 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 465 of file JetScapeParticles.cc
References assert, CheckOrForceHadron(), and set_decay_width().
Jetscape::Hadron::Hadron (int label, int id, int stat, const FourVector & p, const FourVector & x, double mass)
Definition at line 475 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 475 of file JetScapeParticles.cc
References assert, CheckOrForceHadron(), and Jetscape::JetScapeParticleBase::set_restmass().
Jetscape::Hadron::Hadron (const Hadron & srh)
Definition at line 452 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 452 of file JetScapeParticles.cc
References width_.
Member Function Documentation
bool Jetscape::Hadron::CheckOrForceHadron (const int id, const double mass = 0)
Hadron may be used to handle electrons, gammas, ... as well In addition, not all generated ids may be in the database Currently, we add these manually. Could also reject outright.
Definition at line 482 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 482 of file JetScapeParticles.cc
References Jetscape::JetScapeParticleBase::InternalHelperPythia, JSWARN, and utils::status.
Referenced by Hadron().
double Jetscape::Hadron::decay_width () inline
Definition at line 389 of file JetScapeParticles.h.
View newest version in sPHENIX GitHub at line 389 of file JetScapeParticles.h
References width_.
bool Jetscape::Hadron::has_no_position ()
Returns true when all x entries of the hadrons are (close to) 0.
Definition at line 503 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 503 of file JetScapeParticles.cc
References Acts::UnitConstants::e, Jetscape::FourVector::t(), Jetscape::FourVector::x(), Jetscape::JetScapeParticleBase::x_in_, Jetscape::FourVector::y(), and Jetscape::FourVector::z().
Hadron & Jetscape::Hadron::operator= (Hadron & c)
Definition at line 510 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 510 of file JetScapeParticles.cc
References Jetscape::JetScapeParticleBase::operator=(), and width_.
Hadron & Jetscape::Hadron::operator= (const Hadron & c)
Definition at line 516 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 516 of file JetScapeParticles.cc
References Jetscape::JetScapeParticleBase::operator=(), and width_.
void Jetscape::Hadron::set_decay_width (double width) inline
Definition at line 387 of file JetScapeParticles.h.
View newest version in sPHENIX GitHub at line 387 of file JetScapeParticles.h
References width, and width_.
Referenced by Hadron().
Member Data Documentation
double Jetscape::Hadron::width_ protected
Definition at line 400 of file JetScapeParticles.h.
View newest version in sPHENIX GitHub at line 400 of file JetScapeParticles.h
Referenced by decay_width(), Hadron(), operator=(), and set_decay_width().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/JetScapeParticles.h
JETSCAPE/blob/main/src/framework/JetScapeParticles.cc