Analysis Software: acts/blob/sPHENIX/Examples/Algorithms/TrackFinding/src/HoughTransformSeeder.cpp File Reference
HoughTransformSeeder.cpp File Reference
#include "ActsExamples/TrackFinding/HoughTransformSeeder.hpp"
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Definitions/Common.hpp"
#include "Acts/Definitions/TrackParametrization.hpp"
#include "Acts/EventData/SourceLink.hpp"
#include "Acts/Geometry/TrackingGeometry.hpp"
#include "Acts/Surfaces/Surface.hpp"
#include "Acts/Utilities/Enumerate.hpp"
#include "ActsExamples/EventData/GeometryContainers.hpp"
#include "ActsExamples/EventData/Index.hpp"
#include "ActsExamples/EventData/IndexSourceLink.hpp"
#include "ActsExamples/EventData/Measurement.hpp"
#include "ActsExamples/EventData/ProtoTrack.hpp"
#include "ActsExamples/Framework/AlgorithmContext.hpp"
#include "ActsExamples/TrackFinding/DefaultHoughFunctions.hpp"
#include "ActsExamples/Utilities/GroupBy.hpp"
#include "ActsExamples/Utilities/Range.hpp"
#include <algorithm>
#include <cmath>
#include <iterator>
#include <ostream>
#include <stdexcept>
#include <variant>
Functions
static int quant (double min, double max, unsigned nSteps, double val)
static double unquant (double min, double max, unsigned nSteps, int step)
template<typename T >
static std::string to_string (std::vector< T > v)
Function Documentation
static int quant (double min, double max, unsigned nSteps, double val) inline static
Definition at line 328 of file HoughTransformSeeder.cpp.
View newest version in sPHENIX GitHub at line 328 of file HoughTransformSeeder.cpp
References Acts::UnitConstants::min.
Referenced by ActsExamples::HoughTransformSeeder::yToXBins().
template<typename T > static std::string to_string (std::vector< T > v) inline static
Definition at line 339 of file HoughTransformSeeder.cpp.
View newest version in sPHENIX GitHub at line 339 of file HoughTransformSeeder.cpp
Referenced by _digit(), addCylinderLayer(), Fun4AllPrdfInputPoolManager::AddPrdfInputFile(), Fun4AllPrdfInputPoolManager::AddPrdfInputList(), PHTpcResiduals::addTrackState(), ALICEKF::ALICEKalmanFilter(), BeamLineDefineBeamPipe(), Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), ActsFatras::BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_FIXTURE_TEST_CASE(), boundParamResolution(), MakeActsGeometry::buildActsSurfaces(), PHG4MvtxSupport::buildLayerCables(), Acts::TGeoLayerBuilder::buildLayers(), ActsExamples::MockupSectorBuilder::buildSector(), cemcDraw(), cemcDrawInit(), Acts::DD4hepLayerBuilder::centralLayers(), Jetscape::EvolutionHistory::CheckInRange(), ActsExamples::Telescope::TelescopeG4DetectorConstruction::Construct(), Acts::Experimental::VolumeStructureBuilder::construct(), PHG4SpacalPrototype4Detector::Construct_AzimuthalSeg(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4EPDDetector::construct_block(), PHG4MicromegasDetector::construct_fee_board(), PHG4MicromegasDetector::construct_micromegas(), PHG4MicromegasDetector::construct_micromegas_tile(), PHG4EPDDetector::ConstructMe(), PHG4ZDCDetector::ConstructMe(), Acts::Svg::SurfaceArrayConverter::convert(), Acts::Svg::DetectorVolumeConverter::convert(), Acts::Svg::TrackingGeometryConverter::convert(), Acts::convertBinning(), Acts::Svg::IndexedSurfacesConverter::convertImpl(), create_disc_layer(), PHPythia8::create_node_tree(), CreateHostList(), ActsExamples::createMeasurement(), D0EffScan(), D0TruthSeparator(), daq_set_name(), Jetscape::JetScapeLogger::Debug(), Jetscape::JetScapeLogger::DebugThread(), Acts::decodeBinning(), ActsExamples::RootMeasurementWriter::DigitizationTree::DigitizationTree(), display(), draw_corr(), MvtxMonDraw::DrawGeneral(), Acts::GeometryView3D::drawTrackingVolume(), Acts::DD4hepLayerBuilder::endcapLayers(), Acts::extractSeries(), Acts::Experimental::detail::BlueprintHelper::fillGaps(), SingleInttPoolInput::FillPool(), ActsExamples::RootNuclearInteractionParametersWriter::finalize(), CaloCalibEmc_Pi0::Fit_Histos(), CaloCalibEmc_Pi0::Fit_Histos_Eta_Phi_Add32(), CaloCalibEmc_Pi0::Fit_Histos_Eta_Phi_Add96(), CaloCalibEmc_Pi0::Fit_Histos_Etas96(), ActsExamples::Sequencer::fpeMaskCount(), ActsExamples::Sequencer::fpeReport(), Acts::SurfaceJsonConverter::fromJson(), Fun4All_FillChargesMap_300evts_MDC2(), Fun4All_FillDCMap(), Fun4All_HCalJetPhiShift(), Fun4All_Intt_Combiner(), Fun4All_JetBkgd(), Fun4All_Mvtx_Combiner(), Fun4All_RunCorrelatorJetTree(), Fun4All_RunCorrelatorQAModules(), Fun4All_RunLambdaJetHunter(), Fun4All_SingleMvtx(), Fun4All_Stream_Combiner(), Fun4All_Tpc_Combiner(), RawClusterv1::get_et_iso(), CaloCalibEmc_Pi0::Get_Histos(), LiteCaloEval::Get_Histos(), PHG4MvtxSupport::GetConeVolume(), PHG4MvtxSupport::GetEndWheelSideN(), PHG4MvtxSupport::GetEndWheelSideS(), ParticleReader::getParticles(), TpcMonDraw::getTime(), Acts::ProtoVolume::harmonize(), ActsExamples::HoughTransformSeeder::HoughTransformSeeder(), Jetscape::JetScapeLogger::Info(), myAnalysis::init(), HCalCalibTree::Init(), ColoredHadronization::Init(), ColorlessHadronization::Init(), HybridHadronization::Init(), QAG4SimulationTruthDecay::Init(), truthDecayTester::Init(), JetBkgdSub::Init(), KFParticle_nTuple::initializeBranches(), truthDecayTester::initializeBranches(), QAG4SimulationTruthDecay::initializeBranches(), HFTrackEfficiency::initializeBranches(), CaloCalibEmc_Pi0::InitRun(), PHG4HcalSubsystem::InitRun(), LiteCaloEval::InitRun(), Jetscape::TrentoInitial::InitTask(), PHG4OHCalSteppingAction::InitWithNode(), InputInit(), InputManagers(), main(), LL1MonDraw::MakeHtml(), MyMonDraw::MakeHtml(), TpcMonDraw::MakeHtml(), CemcMonDraw::MakeHtml(), SepdMonDraw::MakeHtml(), HcalMonDraw::MakeHtml(), MvtxMonDraw::MakeHtml(), BbcMonDraw::MakeHtml(), TrackerEventDisplay::makeJsonFile(), Mat_map(), materialComposition(), MaterialHistograms::MaterialHistograms(), MbdEvent::MbdEvent(), Acts::Svg::measure(), mvtxDrawInit(), number_to_string(), Acts::Experimental::detail::outputIndices(), PHG4DetectorSubsystem::PHG4DetectorSubsystem(), PHG4HcalSubsystem::PHG4HcalSubsystem(), plot(), plot_ratio(), Acts::Svg::EventDataConverter::point(), Fun4AllMonitoring::PrintsMaps(), RawTowerCalibration::process_event(), HCalib::process_event(), RawTowerDigitizer::process_event(), processGeometry(), ActsExamples::prototrackToSeed(), Fun4AllHepMCInputManager::PushBackEvents(), Fun4AllHepMCPileupInputManager::PushBackEvents(), rcdaq_init(), ActsExamples::SensitiveSurfaceMapper::remapSensitiveNames(), removeFirstBin(), ActsExamples::Sequencer::run(), PROTOTYPE4_FEM::SampleFit_PowerLawDoubleExp(), TPCDaqDefs::FEEv1::SampleFit_PowerLawDoubleExp(), TpcPrototypeDefs::FEEv2::SampleFit_PowerLawDoubleExp(), PROTOTYPE4_FEM::SampleFit_PowerLawExp(), save_correc_value(), Jetscape::PartonShower::SaveAsGraphML(), Jetscape::PartonShower::SaveAsGV(), MyMonDraw::SavePlot(), LL1MonDraw::SavePlot(), ZdcMonDraw::SavePlot(), DaqMonDraw::SavePlot(), TpcMonDraw::SavePlot(), CemcMonDraw::SavePlot(), HcalMonDraw::SavePlot(), SepdMonDraw::SavePlot(), PktSizeMonDraw::SavePlot(), MvtxMonDraw::SavePlot(), TpotMonDraw::SavePlot(), BbcMonDraw::SavePlot(), ActsExamples::SeedingAlgorithm::SeedingAlgorithm(), ActsExamples::SeedingFTFAlgorithm::SeedingFTFAlgorithm(), ActsExamples::SeedingOrthogonalAlgorithm::SeedingOrthogonalAlgorithm(), RawClusterv1::set_et_iso(), OnlMon::SetMonitorServerId(), ActsExamples::TGeoITkModuleSplitter::splitBarrelModule(), ActsExamples::TGeoITkModuleSplitter::splitDiscModule(), TEST_CASE(), TestCDBTTree(), Acts::Test::testPlyString(), TPC_Channel_QA_Backup(), TPCEventDisplay(), TPCEventDisplay_Clusters(), TPCEventDisplay_Hits(), TPCEventDisplay_Updated(), TPCEventDisplay_Updated_BCO(), Acts::CylinderVolumeBuilder::trackingVolume(), ActsExamples::Trajectories::trackParameters(), ActsExamples::Contextual::InternallyAlignedDetectorElement::transform(), ActsExamples::TruthSeedingAlgorithm::TruthSeedingAlgorithm(), ActsExamples::Geant4::HepMC3::SteppingAction::UserSteppingAction(), Jetscape::JetScapeLogger::Verbose(), Jetscape::JetScapeLogger::VerboseParton(), Jetscape::JetScapeLogger::VerboseShower(), Jetscape::JetScapeLogger::VerboseVertex(), wholeIter_Pi0EtaByEta(), Jetscape::JetScapeWriterAsciiGZ::Write(), Jetscape::JetScapeWriterStream< T >::Write(), Jetscape::JetScapeWriterFinalStateStream< T >::WriteEvent(), Jetscape::JetScapeWriterAsciiGZ::WriteHeaderToFile(), Jetscape::JetScapeWriterStream< T >::WriteHeaderToFile(), OnlMonServer::WriteHistoFile(), ActsExamples::RootMaterialWriter::writeMaterial(), Jetscape::Hadronization::WriteTask(), iSpectraSamplerWrapper::WriteTask(), SmashWrapper::WriteTask(), and Acts::Svg::View::xy().
static double unquant (double min, double max, unsigned nSteps, int step) inline static
Definition at line 333 of file HoughTransformSeeder.cpp.
View newest version in sPHENIX GitHub at line 333 of file HoughTransformSeeder.cpp
References Acts::UnitConstants::min.
Referenced by ActsExamples::HoughTransformSeeder::HoughTransformSeeder().