Analysis Software: pythia6/blob/master/pythia6-lhapdf/pythia-6.4.28.f File Reference
pythia-6.4.28.f File Reference
Functions/Subroutines
subroutine pyckbd
subroutine pytest (MTEST)
subroutine pyhepc (MCONV)
subroutine pyinit (FRAME, BEAM, TARGET, WIN)
subroutine pyevnt
subroutine pyevnw
subroutine pystat (MSTAT)
subroutine pyupev
subroutine pyupin
subroutine pylhef
subroutine pyinre
subroutine pyinbm (CHFRAM, CHBEAM, CHTARG, WIN)
subroutine pyinki (MODKI)
subroutine pyinpr
subroutine pyxtot
subroutine pymaxi
subroutine pypile (MPILE)
subroutine pysave (ISAVE, IGA)
subroutine pygaga (IGAGA, WTGAGA)
subroutine pyrand
subroutine pyscat
subroutine pyevol (MODE, PT2MAX, PT2MIN)
subroutine pysspa (IPU1, IPU2)
subroutine pyptis (MODE, PT2NOW, PT2CUT, PT2, IFAIL)
subroutine pymemx (MECOR, WTFF, WTGF, WTFG, WTGG)
subroutine pymewt (MECOR, IFLCB, Q2, Z, PHIBR, WTME)
subroutine pyptmi (MODE, PT2NOW, PT2CUT, PT2, IFAIL)
double precision function pyfcmp (XC, XS, NPOW)
double precision function pypcmp (XS, NPOW)
subroutine pyupre
subroutine pyadsh (NFIN)
subroutine pyveto (IVETO)
subroutine pyresd (IRES)
subroutine pymult (MMUL)
subroutine pyremn (IPU1, IPU2)
subroutine pymign (MMUL)
subroutine pymihk
subroutine pycttr (I, KCS, IEND)
subroutine pymihg (JCP1, JCG1, JCP2, JCG2)
subroutine pymirm
subroutine pyfscr (IP)
subroutine pydiff
subroutine pydisg
subroutine pydocu
subroutine pyfram (IFRAME)
subroutine pywidt (KFLR, SH, WDTP, WDTE)
subroutine pyofsh (MOFSH, KFMO, KFD1, KFD2, PMMO, RET1, RET2)
subroutine pyreco (IW1, IW2, NSD1, NAFT1)
subroutine pyklim (ILIM)
subroutine pykmap (IVAR, MVAR, VVAR)
subroutine pysigh (NCHN, SIGS)
subroutine pysgqc (NCHN, SIGS)
subroutine pysghf (NCHN, SIGS)
subroutine pysgwz (NCHN, SIGS)
subroutine pysghg (NCHN, SIGS)
subroutine pysgsu (NCHN, SIGS)
subroutine pysgtc (NCHN, SIGS)
subroutine pysgex (NCHN, SIGS)
subroutine pypdfu (KF, X, Q2, XPQ)
subroutine pypdfl (KF, X, Q2, XPQ)
subroutine pypdel (KFA, X, Q2, XPEL)
subroutine pypdga (X, Q2, XPGA)
subroutine pyggam (ISET, X, Q2, P2, IP2, F2GM, XPDFGM)
subroutine pygvmd (ISET, KF, X, Q2, P2, ALAM, XPGA, VXPGA)
subroutine pygano (KF, X, Q2, P2, ALAM, XPGA, VXPGA)
subroutine pygbeh (KF, X, Q2, P2, PM2, XPBH)
subroutine pygdir (X, Q2, P2, Q02, XPGA)
subroutine pypdpi (X, Q2, XPPI)
subroutine pypdpr (X, Q2, XPPR)
function pycteq (ISET, IPRT, X, Q)
subroutine pygrvl (X, Q2, UV, DV, DEL, UDB, SB, CHM, BOT, GL)
subroutine pygrvm (X, Q2, UV, DV, DEL, UDB, SB, CHM, BOT, GL)
subroutine pygrvd (X, Q2, UV, DV, DEL, UDB, SB, CHM, BOT, GL)
function pygrvv (X, N, AK, BK, A, B, C, D)
function pygrvw (X, S, AL, BE, AK, BK, A, B, C, D, E, ES)
function pygrvs (X, S, STH, AL, BE, AK, AG, B, D, E, ES)
function pyct5l (IFL, X, Q)
function pyct5m (IFL, X, Q)
subroutine pypdpo (X, Q2, XPPR)
function pyhfth (SH, SQM, FRATT)
subroutine pyspli (KF, KFLIN, KFLCH, KFLSP)
function pygamm (X)
subroutine pywaux (IAUX, EPS, WRE, WIM)
subroutine pyi3au (EPS, RAT, Y3RE, Y3IM)
function pyspen (XREIN, XIMIN, IREIM)
subroutine pyqqbh (WTQQBH)
subroutine pystbh (WTTBH)
subroutine pytbhb (MT, MB, MHP, BR, GAMT)
subroutine pytbhg (Q1, Q2, P1, P2, P3, MT, MB, RMB, MHP, AMP2)
subroutine pytbhq (Q1, Q2, P1, P2, P3, MT, MB, RMB, MHP, AMP2)
DOUBLE PRECISION function pytbhs (A, B)
subroutine pymsin
subroutine pyslha (MUPDA, KFORIG, IRETRN)
subroutine pyapps
subroutine pysugi
subroutine pyfeyn (IERR)
function pyrnmq (ID, DTERM)
subroutine pythrg
subroutine pyinom
function pyrnm3 (RGUT)
subroutine pyeig4 (A, W, Z)
subroutine pyhggm (ALPHA)
subroutine pysubh (XMA, TANB, XMQ, XMUR, XMTOP, AU, AD, XMU, XMH, XHM, XMHCH, SA, CA, TANBA)
subroutine pypole (IHIGGS, XMC, XMA, TANB, XMQ, XMUR, XMDR, XMT, AT, AB, XMU, XMH, XMHP, HM, HMP, AMP, SA, CA, STOP1, STOP2, SBOT1, SBOT2, TANBA, XMG, DT, DB)
subroutine pyrghm (MCHI, MA, TANB, MQ, MUR, MD, MTOP, AU, AD, MU, MHP, HMP, MCH, SA, CA, SAB, CAB, TANBA, MGLU, DELTAMT, DELTAMB)
subroutine pygfxx (MA, TANB, MQ, MUR, MD, MTOP, AT, AB, XMU, XMGL, VH, STOP1, STOP2, SBOT1, SBOT2, DELTAMT, DELTAMB)
function pyfint (A, B, C)
function pyfisb (X)
subroutine pysfdc (KFIN, XLAM, IDLAM, IKNT)
subroutine pyglui (KFIN, XLAM, IDLAM, IKNT)
subroutine pytbbn (I, NN, E, XMGLU, GAM)
subroutine pytbbc (I, NN, XMGLU, GAM)
subroutine pynjdc (KFIN, XLAM, IDLAM, IKNT)
subroutine pycjdc (KFIN, XLAM, IDLAM, IKNT)
double precision function pyxxz6 (X)
double precision function pyxxga (C0, XM1, XM2, XMTR, XMTL)
double precision function pyx2xg (C1, XM1, XM2, XM3, GX2, GLR)
double precision function pyx2xh (C1, XM1, XM2, XM3, GX2, GLR)
subroutine pyhext (KFIN, XLAM, IDLAM, IKNT)
double precision function pyh2xx (C1, XM1, XM2, XM3, GX2, GLR)
function pygaus (F, A, B, EPS)
function pygau2 (F, A, B, EPS)
function pysimp (Y, X0, X1, N)
double precision function pylamf (X, Y, Z)
subroutine pytbdy (IDIN)
subroutine pytecm (SMIN, SMOU, WIDO, IOPT)
subroutine pyxdin
subroutine pyuedc
subroutine pyxued (NCHN, SIGS)
subroutine pygram (IN)
DOUBLE PRECISION function pygraw (YIN)
DOUBLE PRECISION function pywdkk (X)
subroutine pyeicg (NM, N, AR, AI, WR, WI, MATZ, ZR, ZI, FV1, FV2, FV3, IERR)
subroutine pycmqr (NM, N, LOW, IGH, HR, HI, WR, WI, IERR)
subroutine pycmq2 (NM, N, LOW, IGH, ORTR, ORTI, HR, HI, WR, WI, ZR, ZI, IERR)
subroutine pycdiv (AR, AI, BR, BI, CR, CI)
subroutine pycsrt (XR, XI, YR, YI)
DOUBLE PRECISION function pythag (A, B)
subroutine pycbal (NM, N, AR, AI, LOW, IGH, SCALE)
subroutine pycba2 (NM, N, LOW, IGH, SCALE, M, ZR, ZI)
subroutine pycrth (NM, N, LOW, IGH, AR, AI, ORTR, ORTI)
subroutine pyldcm (A, N, NP, INDX, D)
subroutine pybksb (A, N, NP, INDX, B)
subroutine pywidx (KFLR, SH, WDTP, WDTE)
subroutine pyrvsf (KFIN, XLAM, IDLAM, LKNT)
subroutine pyrvne (KFIN, XLAM, IDLAM, LKNT)
subroutine pyrvch (KFIN, XLAM, IDLAM, LKNT)
subroutine pyrvgl (KFIN, XLAM, IDLAM, LKNT)
function pyrvsb (KFIN, ID1, ID2, RM2, MODE)
subroutine pyrvgw (KFIN, ID1, ID2, ID3, XLAM)
double precision function pyrvi1 (ID1, ID2, ID3)
double precision function pyrvi2 (ID1, ID2, ID3)
double precision function pyrvi3 (ID1, ID2, ID3)
double precision function pyrvg1 (X)
double precision function pyrvg2 (X)
double precision function pyrvg3 (X)
double precision function pyrvg4 (Y)
double precision function pyrvr (Mab2, RM, RW)
double precision function pyrvs (X, Y, M1, W1, M2, W2)
subroutine py1ent (IP, KF, PE, THE, PHI)
subroutine py2ent (IP, KF1, KF2, PECM)
subroutine py3ent (IP, KF1, KF2, KF3, PECM, X1, X3)
subroutine py4ent (IP, KF1, KF2, KF3, KF4, PECM, X1, X2, X4, X12, X14)
subroutine py2frm (IRAD, ITAU, ICOM)
subroutine py4frm (ATOTSQ, A1SQ, A2SQ, ISTRAT, IRAD, ITAU, ICOM)
subroutine py6frm (P12, P13, P21, P23, P31, P32, PTOP, IRAD, ITAU, ICOM)
subroutine py4jet (PMAX, IRAD, ICOM)
function py4jtw (IA1, IA2, IA3, IA4)
subroutine py4jts (IA1, IA2, IA3, IA4, IA5, QMAX)
subroutine pyjoin (NJOIN, IJOIN)
subroutine pygive (CHIN)
subroutine pyonof (CHIN)
subroutine pytune (MYTUNE)
subroutine pyexec
subroutine pyprep (IP)
subroutine pystrf (IP)
subroutine pyjurf (PJU, VJU)
subroutine pyindf (IP)
subroutine pydecy (IP)
subroutine pydcyk (KFL1, KFL2, KFL3, KF)
subroutine pykfdi (KFL1, KFL2, KFL3, KF)
subroutine pynmes (KFDIQ)
subroutine pykfin
subroutine pyptdi (KFL, PX, PY)
subroutine pyzdis (KFL1, KFL2, PR, Z)
subroutine pyshow (IP1, IP2, QMAX)
subroutine pyptfs (MODE, PTMAX, PTMIN, PTGEN)
function pymael (NI, X1, X2, R1, R2, ALPHA)
subroutine pyboei (NSAV)
subroutine pybesq (I1, I2, NI, Q2OLD, Q2NEW)
function pymass (KF)
function pymrun (KF, Q2)
subroutine pyname (KF, CHAU)
integer function pychge (KF)
integer function pycomp (KF)
subroutine pyerrm (MERR, CHMESS)
function pyalem (Q2)
function pyalps (Q2)
function pyangl (X, Y)
function pyr (IDUMMY)
subroutine pyrget (LFN, MOVE)
subroutine pyrset (LFN, MOVE)
subroutine pyrobo (IMI, IMA, THE, PHI, BEX, BEY, BEZ)
subroutine pyedit (MEDIT)
subroutine pylist (MLIST)
subroutine pylogo
subroutine pyupda (MUPDA, LFN)
integer function pyk (I, J)
function pyp (I, J)
subroutine pysphe (SPH, APL)
subroutine pythru (THR, OBL)
subroutine pyclus (NJET)
subroutine pycell (NJET)
subroutine pyjmas (PMH, PML)
subroutine pyfowo (H10, H20, H30, H40)
subroutine pytabu (MTABU)
subroutine pyeevt (KFL, ECM)
subroutine pyxtee (KFL, ECM, XTOT)
subroutine pyradk (ECM, MK, PAK, THEK, PHIK, ALPK)
subroutine pyxkfl (KFL, ECM, ECMC, KFLC)
subroutine pyxjet (ECM, NJET, CUT)
subroutine pyx3jt (NJET, CUT, KFL, ECM, X1, X2)
subroutine pyx4jt (NJET, CUT, KFL, ECM, KFLN, X1, X2, X4, X12, X14)
subroutine pyxdif (NC, NJET, KFL, ECM, CHI, THE, PHI)
subroutine pyonia (KFL, ECM)
subroutine pybook (ID, TITLE, NX, XL, XU)
subroutine pyfill (ID, X, W)
subroutine pyfact (ID, F)
subroutine pyoper (ID1, OPER, ID2, ID3, F1, F2)
subroutine pyhist
subroutine pyplot (ID)
subroutine pynull (ID)
subroutine pydump (MDUMP, LFN, NHI, IHI)
subroutine pystop (MCOD)
subroutine pykcut (MCUT)
subroutine pyevwt (WTXS)
subroutine upinit
subroutine upevnt
subroutine upveto (IVETO)
subroutine pdfsetold (PARM, VALUE)
subroutine structmold (XX, QQ, UPV, DNV, USEA, DSEA, STR, CHM, BOT, TOP, GLU)
subroutine structpold (XX, QQ2, P2, IP2, UPV, DNV, USEA, DSEA, STR, CHM, BOT, TOP, GLU)
subroutine sugra (MZERO, MHLF, AZERO, TANB, SGNMU, MTOP, IMODL)
character *40 function visaje ()
subroutine ssmssm (RDUM1, RDUM2, RDUM3, RDUM4, RDUM5, RDUM6, RDUM7, RDUM8, RDUM9, RDUM10, RDUM11, RDUM12, RDUM13, RDUM14, RDUM15, RDUM16, RDUM17, RDUM18, RDUM19, RDUM20, RDUM21, RDUM22, RDUM23, RDUM24, RDUM25, IDUM1, IDUM2)
subroutine fhsetflags (IERR, IMSP, IFR, ITBR, IHMX, IP2A, ILP, ITR, IBR)
subroutine fhsetpara (IER, SCF, DMT, DMB, DMW, DMZ, DTANB, DMA, DMH, DM3L, DM3E, DM3Q, DM3U, DM3D, DM2L, DM2E, DM2Q, DM2U, DM2D, DM1L, DM1E, DM1Q, DM1U, DM1D, DMU, AE33, AU33, AD33, AE22, AU22, AD22, AE11, AU11, AD11, DM1, DM2, DM3, RLT, RLB, QTAU, QT, QB)
subroutine fhhiggscorr (IERR, RMHIGG, SAEFF, UHIGGS)
subroutine pytaud (ITAU, IORIG, KFORIG, NDECAY)
subroutine pytime (IDATI)
Function/Subroutine Documentation
subroutine fhhiggscorr (IERR, double precision, dimension(4) RMHIGG, double complex SAEFF, double complex, dimension(3,3) UHIGGS)
Definition at line 81594 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 81594 of file pythia-6.4.28.f
References pydat1, pystop(), and x.
subroutine fhsetflags (IERR, IMSP, IFR, ITBR, IHMX, IP2A, ILP, ITR, IBR)
Definition at line 81530 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 81530 of file pythia-6.4.28.f
References pydat1, pystop(), and x.
subroutine fhsetpara (IER, SCF, DMT, DMB, DMW, DMZ, DTANB, DMA, DMH, DM3L, DM3E, DM3Q, DM3U, DM3D, DM2L, DM2E, DM2Q, DM2U, DM2D, DM1L, DM1E, DM1Q, DM1U, DM1D, double complex DMU, double complex AE33, double complex AU33, double complex AD33, double complex AE22, double complex AU22, double complex AD22, double complex AE11, double complex AU11, double complex AD11, double complex DM1, double complex DM2, double complex DM3, RLT, RLB, QTAU, QT, QB)
Definition at line 81562 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 81562 of file pythia-6.4.28.f
References pydat1, pystop(), and x.
subroutine pdfsetold (character*20, dimension(20) PARM, double precision, dimension(20) VALUE)
Definition at line 81336 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 81336 of file pythia-6.4.28.f
References pydat1, pystop(), value, and x.
subroutine py1ent (IP, KF, PE, THE, PHI)
Definition at line 59301 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 59301 of file pythia-6.4.28.f
References j, k, Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, phi, pycomp, pydat1, pydat2, pyerrm(), pyexec(), pyjets, pylist(), pymass(), and v.
subroutine py2ent (IP, KF1, KF2, PECM)
Definition at line 59356 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 59356 of file pythia-6.4.28.f
References i, j, k, Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, pycomp, pydat1, pydat2, pyerrm(), pyexec(), pyjets, pylist(), pymass(), and v.
subroutine py2frm (IRAD, ITAU, ICOM)
Definition at line 59737 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 59737 of file pythia-6.4.28.f
References i, ValueGen1::i1(), ValueGen1::i2(), k, Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, pydat1, pyerrm(), pyexec(), pyhepc(), pyjets, pyjoin(), pyshow(), and v.
subroutine py3ent (IP, KF1, KF2, KF3, PECM, X1, X3)
Definition at line 59448 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 59448 of file pythia-6.4.28.f
References i, j, k, Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, pycomp, pydat1, pydat2, pyerrm(), pyexec(), pyjets, pylist(), pymass(), and v.
subroutine py4ent (IP, KF1, KF2, KF3, KF4, PECM, X1, X2, X4, X12, X14)
Definition at line 59570 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 59570 of file pythia-6.4.28.f
References i, j, k, Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, pycomp, pydat1, pydat2, pyerrm(), pyexec(), pyjets, pylist(), pymass(), pyr(), and v.
subroutine py4frm (ATOTSQ, A1SQ, A2SQ, ISTRAT, IRAD, ITAU, ICOM)
Definition at line 59846 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 59846 of file pythia-6.4.28.f
References i, ValueGen1::i1(), ValueGen1::i2(), ValueGen1::i3(), ValueGen1::i4(), j, k, Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, p, pari, parp, pychge(), pydat1, pyerrm(), pyexec(), pyhepc(), pyint1, pyjets, pyjoin(), pypars, pyr(), pyreco(), pyshow(), v, and vint.
subroutine py4jet (PMAX, IRAD, ICOM)
Definition at line 60438 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 60438 of file pythia-6.4.28.f
References Fatras::Test::Particle::beta(), i, ValueGen1::i1(), ValueGen1::i2(), ValueGen1::i3(), ValueGen1::i4(), j, k, Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, phi, py4jts(), py4jtw(), pyangl(), pydat1, pyerrm(), pyexec(), pyhepc(), pyjets, pyjoin(), pyr(), pyrobo(), pyshow(), and v.
subroutine py4jts (IA1, IA2, IA3, IA4, IA5, QMAX)
Definition at line 60714 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 60714 of file pythia-6.4.28.f
References i, j, k, Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, pyjets, and v.
function py4jtw (IA1, IA2, IA3, IA4)
Definition at line 60646 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 60646 of file pythia-6.4.28.f
References j, k, Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, py4jtw(), pyjets, and v.
subroutine py6frm (P12, P13, P21, P23, P31, P32, PTOP, IRAD, ITAU, ICOM)
Definition at line 60074 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 60074 of file pythia-6.4.28.f
References Fatras::Test::Particle::beta(), i, ValueGen1::i1(), ValueGen1::i2(), ValueGen1::i3(), ValueGen1::i4(), ValueGen1::i5(), it, j, k, Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, pychge(), pydat1, pyerrm(), pyexec(), pyhepc(), pyjets, pyjoin(), pyr(), pyrobo(), pyshow(), and v.
subroutine pyadsh (NFIN)
Definition at line 16829 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 16829 of file pythia-6.4.28.f
References Fatras::Test::Particle::beta(), i, ValueGen1::i3(), j, k, Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, npart(), p, pari, parp, pydat1, pyerrm(), pyint1, pyjets, pypars, pyptfs(), pyrobo(), pyshow(), v, and vint.
function pyalem (Q2)
Definition at line 75169 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 75169 of file pythia-6.4.28.f
References Acts::Logger::log(), pyalem(), and pydat1.
function pyalps (Q2)
Definition at line 75215 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 75215 of file pythia-6.4.28.f
References b1, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), pyalps(), pydat1, and pydat2.
function pyangl (X, Y)
Definition at line 75295 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 75295 of file pythia-6.4.28.f
References pyangl(), pydat1, r, sign(), x, and y.
subroutine pyapps ()
Definition at line 47660 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 47660 of file pythia-6.4.28.f
References Fatras::Test::Particle::beta(), i, pycomp, pydat1, pydat2, pymrun(), pymssm, pyrnmq(), pystop(), and sign().
subroutine pybesq (I1, I2, NI, Q2OLD, Q2NEW)
Definition at line 74794 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 74794 of file pythia-6.4.28.f
References ValueGen1::i1(), ValueGen1::i2(), j, k, Acts::detail::PhiBoundParameterLimits::max(), n, ni, npad, p, phi, pyangl(), pydat1, pyjets, pyrobo(), PseudoJet::pz(), s, and v.
subroutine pybksb (complex*16, dimension(np,np) A, integer N, integer NP, integer, dimension(n) INDX, complex*16, dimension(n) B)
Definition at line 57370 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 57370 of file pythia-6.4.28.f
References i, j, n, and sum().
subroutine pyboei (NSAV)
Definition at line 74289 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 74289 of file pythia-6.4.28.f
References alpha, i, ValueGen1::i1(), ValueGen1::i2(), ValueGen1::i3(), ValueGen1::i4(), j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, n, nbin, npad, p, pybesq(), pydat1, pydat2, pyerrm(), pyint1, pyjets, pymass(), pyp(), pyr(), pyrobo(), v, vint, and sHelix::w().
subroutine pybook (ID, character, dimension(*) TITLE, NX, XL, XU)
Definition at line 80317 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 80317 of file pythia-6.4.28.f
References Acts::BinUtility::bin(), id, it, nx, pybins, pyerrm(), pynull(), and title.
subroutine pycba2 (integer NM, integer N, integer LOW, integer IGH, double precision, dimension(5) SCALE, integer M, double precision, dimension(5,5) ZR, double precision, dimension(5,5) ZI)
Definition at line 57115 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 57115 of file pythia-6.4.28.f
References i, j, k, ActsExamples::PlotHelpers::Binning::low(), n, and s.
subroutine pycbal (integer NM, integer N, double precision, dimension(5,5) AR, double precision, dimension(5,5) AI, integer LOW, integer IGH, double precision, dimension(5) SCALE)
Definition at line 56944 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 56944 of file pythia-6.4.28.f
References c, f, false, g, i, j, k, ActsExamples::PlotHelpers::Binning::low(), n, r, s, and true.
subroutine pycdiv (double precision AR, double precision AI, double precision BR, double precision BI, double precision CR, double precision CI)
Definition at line 56821 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 56821 of file pythia-6.4.28.f
References ci, and s.
subroutine pycell (NJET)
Definition at line 77731 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 77731 of file pythia-6.4.28.f
References eta, i, j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), n, HiMain1::np(), npad, p, phi, pt, pyangl(), pychge(), pycomp, pydat1, pydat2, pyerrm(), pyjets, pyr(), sign(), and v.
integer function pychge (KF)
Definition at line 75002 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 75002 of file pythia-6.4.28.f
References pychge(), pycomp, and pydat2.
subroutine pycjdc (integer KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, integer IKNT)
Definition at line 53133 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 53133 of file pythia-6.4.28.f
References Fatras::Test::Particle::beta(), ei(), i, j, pi, pyalem(), pyalps(), pycomp, pydat1, pydat2, pygaus(), pylamf(), pymssm, pyrvch(), pyssmt, pyx2xg(), pyx2xh(), pyxxz6(), and sign().
subroutine pyckbd ()
Definition at line 2220 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 2220 of file pythia-6.4.28.f
References k, msti, mstp, n, npad, p, pari, parp, pydat1, pydat2, pydat3, pyjets, pypars, pystop(), pysubs, and v.
subroutine pyclus (NJET)
Definition at line 77353 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 77353 of file pythia-6.4.28.f
References i, ValueGen1::i1(), ValueGen1::i2(), j, k, Acts::detail::PhiBoundParameterLimits::max(), n, HiMain1::np(), npad, p, ps(), pychge(), pycomp, pydat1, pydat2, pyerrm(), pyjets, r2, and v.
subroutine pycmq2 (integer NM, integer N, integer LOW, integer IGH, double precision, dimension(5) ORTR, double precision, dimension(5) ORTI, double precision, dimension(5,5) HR, double precision, dimension(5,5) HI, double precision, dimension(5) WR, double precision, dimension(5) WI, double precision, dimension(5,5) ZR, double precision, dimension(5,5) ZI, integer IERR)
Definition at line 56474 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 56474 of file pythia-6.4.28.f
References i, j, k, ActsExamples::PlotHelpers::Binning::low(), n, norm, pycdiv(), pycsrt(), pythag(), and x.
subroutine pycmqr (integer NM, integer N, integer LOW, integer IGH, double precision, dimension(5,5) HR, double precision, dimension(5,5) HI, double precision, dimension(5) WR, double precision, dimension(5) WI, integer IERR)
Definition at line 56230 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 56230 of file pythia-6.4.28.f
References i, j, ActsExamples::PlotHelpers::Binning::low(), n, norm, pycdiv(), pycsrt(), pythag(), and x.
integer function pycomp (KF)
Definition at line 75026 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 75026 of file pythia-6.4.28.f
References i, ValueGen1::i1(), pycomp, pydat1, and pydat2.
subroutine pycrth (integer NM, integer N, integer LOW, integer IGH, double precision, dimension(5,5) AR, double precision, dimension(5,5) AI, double precision, dimension(5) ORTR, double precision, dimension(5) ORTI)
Definition at line 57207 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 57207 of file pythia-6.4.28.f
References f, g, h, i, j, ActsExamples::PlotHelpers::Binning::low(), n, and pythag().
subroutine pycsrt (double precision XR, double precision XI, double precision YR, double precision YI)
Definition at line 56846 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 56846 of file pythia-6.4.28.f
References pythag(), and s.
function pyct5l (IFL, X, Q)
Definition at line 41880 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 41880 of file pythia-6.4.28.f
References e, i, k, Acts::Logger::log(), pyct5l(), Fatras::Test::Particle::q(), x, and y.
function pyct5m (IFL, X, Q)
Definition at line 42135 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 42135 of file pythia-6.4.28.f
References e, i, k, Acts::Logger::log(), pyct5m(), Fatras::Test::Particle::q(), x, and y.
function pycteq (ISET, IPRT, X, Q)
Definition at line 41145 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 41145 of file pythia-6.4.28.f
References i, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), pycteq(), Fatras::Test::Particle::q(), and x.
subroutine pycttr (I, KCS, IEND)
Definition at line 23016 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 23016 of file pythia-6.4.28.f
References i, k, mint, n, npad, p, pycomp, pydat1, pydat2, pyerrm(), pyint1, pyjets, pylist(), v, and vint.
subroutine pydcyk (KFL1, KFL2, KFL3, KF)
Definition at line 69476 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 69476 of file pythia-6.4.28.f
References g, pycomp, pydat1, pydat2, pykfdi(), pymass(), pyptdi(), pyr(), pyzdis(), x, and z.
subroutine pydecy (IP)
Definition at line 68654 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 68654 of file pythia-6.4.28.f
References c, i, j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), n, HiMain1::np(), npad, ntry, p, phi, ps(), pyangl(), pycomp, pydat1, pydat2, pydat3, pydcyk(), pyerrm(), pyjets, pykfdi(), pymass(), pyr(), pyrobo(), pytaud(), and v.
subroutine pydiff ()
Definition at line 24307 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 24307 of file pythia-6.4.28.f
References i, j, k, Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, ntry, p, pari, parp, phi, pyangl(), pydat1, pydecy(), pyint1, pyjets, pykfdi(), pymass(), pypars, pyr(), pyrobo(), pyspli(), PseudoJet::pz(), v, and vint.
subroutine pydisg ()
Definition at line 24533 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 24533 of file pythia-6.4.28.f
References i, ValueGen1::i1(), ValueGen1::i2(), j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, ntry, p, pari, parp, phi, pt, pycomp, pydat1, pydat2, pyint1, pyjets, pymass(), pypars, pyptdi(), pyr(), pyrobo(), pyshow(), pyspli(), pysubs, pyzdis(), v, and vint.
subroutine pydocu ()
Definition at line 24840 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 24840 of file pythia-6.4.28.f
References i, j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, ngen, ngenpd, npad, p, pari, parp, pt, pyangl(), pydat1, pyint1, pyint2, pyint5, pyjets, pypars, pysave(), pysubs, sign(), v, vint, and xsec.
subroutine pydump (MDUMP, LFN, NHI, dimension(*) IHI)
Definition at line 80734 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 80734 of file pythia-6.4.28.f
References Acts::BinUtility::bin(), end, ValueGen1::i5(), id, it, nx, p, pybins, pybook(), pyerrm(), title, and x.
subroutine pyedit (MEDIT)
Definition at line 75597 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 75597 of file pythia-6.4.28.f
References i, ValueGen1::i1(), id, j, k, Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, pyangl(), pychge(), pycomp, pydat1, pydat2, pyerrm(), pyjets, pyrobo(), sign(), and v.
subroutine pyeevt (KFL, ECM)
Definition at line 78976 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 78976 of file pythia-6.4.28.f
References k, Acts::detail::PhiBoundParameterLimits::max(), n, npad, ntry, p, phi, py1ent, py2ent(), py3ent(), py4ent(), pydat1, pydat2, pyerrm(), pyexec(), pyjets, pylist(), pyprep(), pyradk(), pyrobo(), pyshow(), pyx3jt(), pyx4jt(), pyxdif(), pyxjet(), pyxkfl(), pyxtee(), and v.
subroutine pyeicg (integer NM, integer N, double precision, dimension(5,5) AR, double precision, dimension(5,5) AI, double precision, dimension(5) WR, double precision, dimension(5) WI, integer MATZ, double precision, dimension(5,5) ZR, double precision, dimension(5,5) ZI, double precision, dimension(5) FV1, double precision, dimension(5) FV2, double precision, dimension(5) FV3, integer IERR)
Definition at line 56148 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 56148 of file pythia-6.4.28.f
References n, pycba2(), pycbal(), pycmq2(), pycmqr(), pycrth(), and x.
subroutine pyeig4 (dimension(4,4) A, dimension(4) W, dimension(4,4) Z)
Definition at line 49265 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 49265 of file pythia-6.4.28.f
References b1, c2, e, i, ValueGen1::i1(), ValueGen1::i2(), ValueGen1::i3(), j, pyr(), TrigInDetTriplet< space_point_t >::s1(), TrigInDetTriplet< space_point_t >::s2(), sHelix::w(), x, and z.
subroutine pyerrm (MERR, character, dimension(*) CHMESS)
Definition at line 75111 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 75111 of file pythia-6.4.28.f
References ValueGen1::i2(), k, n, npad, p, pydat1, pyjets, pylist(), pystop(), v, and x.
subroutine pyevnt ()
Definition at line 3178 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 3178 of file pythia-6.4.28.f
References i, ValueGen1::i1(), j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, ngen, ngenpd, npad, npart(), p, pari, parp, pyadsh(), pycomp, pydat1, pydat2, pydat3, pydiff(), pydisg(), pydocu(), pyedit(), pyerrm(), pyevnw(), pyexec(), pyfram(), pyfscr(), pygaga(), pyinki(), pyint1, pyint2, pyint4, pyint5, pyjets, pymign(), pymihk(), pymirm(), pymult(), pypars, pypile(), pyprep(), pyptfs(), pyr(), pyrand(), pyremn(), pyresd(), pysave(), pyscat(), pyshow(), pysspa(), pystop(), pyveto(), pyxtot(), v, vint, x, and xsec.
subroutine pyevnw ()
Definition at line 3552 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 3552 of file pythia-6.4.28.f
References i, ValueGen1::i1(), j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, ngen, ngenpd, npad, npart(), p, pari, parp, pyadsh(), pycomp, pycttr(), pydat1, pydat2, pydat3, pydiff(), pydisg(), pydocu(), pyedit(), pyerrm(), pyevol(), pyexec(), pyfram(), pyfscr(), pygaga(), pyinki(), pyint1, pyint2, pyint4, pyint5, pyjets, pymihk(), pymirm(), pypars, pypile(), pyprep(), pyptfs(), pyr(), pyrand(), pyremn(), pyresd(), pysave(), pyscat(), pystop(), pyveto(), pyxtot(), v, vint, x, and xsec.
subroutine pyevol (MODE, PT2MAX, PT2MIN)
Definition at line 13593 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 13593 of file pythia-6.4.28.f
References i, j, k, Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, npart(), p, pari, parp, pyalps(), pydat1, pydat2, pyerrm(), pyint1, pyint2, pyint3, pyjets, pypars, pyptis(), pyptmi(), v, and vint.
subroutine pyevwt (WTXS)
Definition at line 80992 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 80992 of file pythia-6.4.28.f
References mint, PseudoJet::pt2(), pydat1, pyint1, pyint2, pystop(), tau, vint, and x.
subroutine pyexec ()
Definition at line 64935 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 64935 of file pythia-6.4.28.f
References i, j, k, Acts::detail::PhiBoundParameterLimits::max(), mint, n, npad, p, ps(), pyboei(), pychge(), pycomp, pydat1, pydat2, pydat3, pydecy(), pyerrm(), pyindf(), pyint1, pyint4, pyjets, pylist(), pyprep(), pyresd(), pyshow(), pystrf(), v, and vint.
subroutine pyfact (ID, F)
Definition at line 80400 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 80400 of file pythia-6.4.28.f
References Acts::BinUtility::bin(), f, id, pybins, and pyerrm().
double precision function pyfcmp (double precision XC, double precision XS, integer NPOW)
Definition at line 16644 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 16644 of file pythia-6.4.28.f
References Acts::Logger::log(), pyfcmp(), and y.
subroutine pyfeyn (IERR)
Definition at line 48319 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 48319 of file pythia-6.4.28.f
References alpha, fhhiggscorr(), fhsetflags(), fhsetpara(), pydat1, pydat2, pyerrm(), pymssm, Fatras::Test::Particle::q(), and r.
subroutine pyfill (ID, X, W)
Definition at line 80363 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 80363 of file pythia-6.4.28.f
References Acts::BinUtility::bin(), id, Acts::detail::PhiBoundParameterLimits::max(), pybins, pyerrm(), sHelix::w(), and x.
function pyfint (A, B, C)
Definition at line 50711 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 50711 of file pythia-6.4.28.f
References c, pyfint(), pyfisb(), pygaus(), pyints, xhi, and xlo.
function pyfisb (X)
Definition at line 50740 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 50740 of file pythia-6.4.28.f
References Acts::Logger::log(), pyfisb(), pyints, and x.
subroutine pyfowo (H10, H20, H30, H40)
Definition at line 78130 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 78130 of file pythia-6.4.28.f
References i, ValueGen1::i1(), ValueGen1::i2(), j, k, n, HiMain1::np(), npad, p, pychge(), pycomp, pydat1, pydat2, pyerrm(), pyjets, and v.
subroutine pyfram (IFRAME)
Definition at line 25028 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 25028 of file pythia-6.4.28.f
References ValueGen1::i5(), mint, msti, mstp, pari, parp, pydat1, pyint1, pypars, pyrobo(), vint, and x.
subroutine pyfscr (IP)
Definition at line 23855 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 23855 of file pythia-6.4.28.f
References i, ValueGen1::i1(), ValueGen1::i2(), it, j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, p, pari, parp, pycomp, pycttr(), pydat1, pydat2, pyerrm(), pyint1, pyjets, pypars, pyr(), pystop(), pythru(), v, and vint.
subroutine pygaga (IGAGA, WTGAGA)
Definition at line 8776 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 8776 of file pythia-6.4.28.f
References Fatras::Test::Particle::beta(), eps, i, j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, ngen, ngenpd, npad, p, pari, parp, phi, pt, pyangl(), pycomp, pydat1, pydat2, pyint1, pyint5, pyjets, pypars, pyr(), pyrobo(), pysubs, pyxtot(), sign(), v, vint, x, xmax, xmin, xsec, y, ymax, and ymin.
function pygamm (X)
Definition at line 43130 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 43130 of file pythia-6.4.28.f
References i, nx, pygamm(), and x.
subroutine pygano (KF, X, Q2, P2, ALAM, dimension(-6:6) XPGA, dimension(-6:6) VXPGA)
Definition at line 40555 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 40555 of file pythia-6.4.28.f
References Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), HiStrng::nfp(), s, and x.
function pygau2 (double precision, external F, A, B, EPS)
Definition at line 54623 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 54623 of file pythia-6.4.28.f
References c2, eps, f, h, i, pyerrm(), pygau2(), sHelix::w(), and x.
function pygaus (double precision, external F, A, B, EPS)
Definition at line 54555 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 54555 of file pythia-6.4.28.f
References c2, eps, f, h, i, pyerrm(), pygaus(), sHelix::w(), and x.
subroutine pygbeh (KF, X, Q2, P2, PM2, XPBH)
Definition at line 40718 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 40718 of file pythia-6.4.28.f
References Fatras::Test::Particle::beta(), Acts::Logger::log(), and x.
subroutine pygdir (X, Q2, P2, Q02, dimension(-6:6) XPGA)
Definition at line 40785 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 40785 of file pythia-6.4.28.f
References Acts::Logger::log(), and x.
subroutine pygfxx (MA, TANB, MQ, MUR, MD, MTOP, AT, AB, XMU, XMGL, dimension(2,2) VH, STOP1, STOP2, SBOT1, SBOT2, DELTAMT, DELTAMB)
Definition at line 50389 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 50389 of file pythia-6.4.28.f
References g, h1b, h2b, i, j, Acts::Logger::log(), pi, pydat1, pydat2, pymrun(), t, t1(), v, x, y, and z.
subroutine pyggam (ISET, X, Q2, P2, IP2, F2GM, dimension(-6:6) XPDFGM)
Definition at line 40135 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 40135 of file pythia-6.4.28.f
References Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), pygano(), pygbeh(), pygdir(), pygvmd(), pyint8, pyint9, and x.
subroutine pygive (character, dimension(*) CHIN)
Definition at line 60918 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 60918 of file pythia-6.4.28.f
References i, ValueGen1::i1(), ValueGen1::i2(), ValueGen1::i3(), j, k, mint, msti, mstp, n, ngen, ngenpd, npad, p, pari, parp, pycomp, pydat1, pydat2, pydat3, pydat4, pydatr, pyerrm(), pyint1, pyint2, pyint3, pyint4, pyint5, pyint6, pyint7, pyint8, pyjets, pylist(), pymssm, pyonof(), pypars, pysubs, v, vint, x, and xsec.
subroutine pyglui (KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, integer IKNT)
Definition at line 51414 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 51414 of file pythia-6.4.28.f
References ei(), i, pi, pyalem(), pyalps(), pycomp, pydat1, pydat2, pygaus(), pylamf(), pymssm, pyrvgl(), pyssmt, pytbbc(), pytbbn(), pyxxz6(), and sign().
subroutine pygram (IN)
Definition at line 55882 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 55882 of file pythia-6.4.28.f
References i, in, pi, pydat1, pydat2, pygaus(), pygraw(), pyr(), pystop(), x, y, and ymax.
DOUBLE PRECISION function pygraw (YIN)
Definition at line 56017 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 56017 of file pythia-6.4.28.f
References i, n, pi, pydat1, pygamm(), pygraw(), pywdkk(), ymax, and ymin.
subroutine pygrvd (X, Q2, UV, DV, DEL, UDB, SB, CHM, BOT, GL)
Definition at line 41651 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 41651 of file pythia-6.4.28.f
References ac(), cd(), Acts::Logger::log(), Jetscape::JetScapeParticleBase::nu(), pygrvs(), pygrvv(), pygrvw(), s, TrigInDetTriplet< space_point_t >::s2(), TrigInDetTriplet< space_point_t >::s3(), and x.
subroutine pygrvl (X, Q2, UV, DV, DEL, UDB, SB, CHM, BOT, GL)
Definition at line 41418 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 41418 of file pythia-6.4.28.f
References ac(), cd(), Acts::Logger::log(), Jetscape::JetScapeParticleBase::nu(), pygrvs(), pygrvv(), pygrvw(), s, TrigInDetTriplet< space_point_t >::s2(), TrigInDetTriplet< space_point_t >::s3(), and x.
subroutine pygrvm (X, Q2, UV, DV, DEL, UDB, SB, CHM, BOT, GL)
Definition at line 41535 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 41535 of file pythia-6.4.28.f
References ac(), cd(), Acts::Logger::log(), Jetscape::JetScapeParticleBase::nu(), pygrvs(), pygrvv(), pygrvw(), s, TrigInDetTriplet< space_point_t >::s2(), TrigInDetTriplet< space_point_t >::s3(), and x.
function pygrvs (X, S, STH, AL, BE, AK, AG, B, D, E, ES)
Definition at line 41807 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 41807 of file pythia-6.4.28.f
References e, Acts::Logger::log(), pygrvs(), s, and x.
function pygrvv (X, N, AK, BK, A, B, C, D)
Definition at line 41767 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 41767 of file pythia-6.4.28.f
References bk(), c, n, pygrvv(), and x.
function pygrvw (X, S, AL, BE, AK, BK, A, B, C, D, E, ES)
Definition at line 41787 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 41787 of file pythia-6.4.28.f
References bk(), c, e, Acts::Logger::log(), pygrvw(), s, and x.
subroutine pygvmd (ISET, KF, X, Q2, P2, ALAM, dimension(-6:6) XPGA, dimension(-6:6) VXPGA)
Definition at line 40336 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 40336 of file pythia-6.4.28.f
References Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), HiStrng::nfp(), s, TrigInDetTriplet< space_point_t >::s2(), TrigInDetTriplet< space_point_t >::s3(), ValueGen1::s4(), and x.
double precision function pyh2xx (double precision C1, double precision XM1, double precision XM2, double precision XM3, GX2, GLR)
Definition at line 54521 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 54521 of file pythia-6.4.28.f
References pydat1, pyh2xx(), and pylamf().
subroutine pyhepc (MCONV)
Definition at line 2683 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 2683 of file pythia-6.4.28.f
References i, ValueGen1::i1(), ValueGen1::i2(), j, k, n, npad, p, pycomp, pydat1, pydat2, pyerrm(), pyjets, and v.
subroutine pyhext (integer KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, integer IKNT)
Definition at line 54056 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 54056 of file pythia-6.4.28.f
References Fatras::Test::Particle::beta(), ei(), gr, i, j, msti, mstp, pari, parp, pyalem(), pycomp, pydat1, pydat2, pyh2xx(), pylamf(), pymssm, pypars, and pyssmt.
function pyhfth (SH, SQM, FRATT)
Definition at line 42890 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 42890 of file pythia-6.4.28.f
References Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, pari, parp, pyalps(), pydat1, pyhfth(), pyint1, pypars, and vint.
subroutine pyhggm (double precision ALPHA)
Definition at line 49423 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 49423 of file pythia-6.4.28.f
References alpha, msti, mstp, pari, parp, pycomp, pydat1, pydat2, pyerrm(), pymssm, pypars, pypole(), and pysubh().
subroutine pyhist ()
Definition at line 80527 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 80527 of file pythia-6.4.28.f
References Acts::BinUtility::bin(), id, pybins, pynull(), and pyplot().
subroutine pyi3au (EPS, RAT, Y3RE, Y3IM)
Definition at line 43206 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 43206 of file pythia-6.4.28.f
References eps, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), phi, pydat1, pyspen(), and r.
subroutine pyinbm (character CHFRAM, character CHBEAM, character CHTARG, WIN)
Definition at line 5532 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 5532 of file pythia-6.4.28.f
References i, j, k, Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, p, pari, parp, pydat1, pydat2, pyint1, pyjets, pymass(), pyname(), pypars, pystop(), pysubs, s, sign(), v, vint, and x.
subroutine pyindf (IP)
Definition at line 68182 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 68182 of file pythia-6.4.28.f
References i, ValueGen1::i1(), j, k, Acts::detail::PhiBoundParameterLimits::max(), n, npad, ntry, p, phi, pyangl(), pycomp, pydat1, pydat2, pyerrm(), pyjets, pykfdi(), pymass(), pyptdi(), pyr(), pyrobo(), pyzdis(), v, sHelix::w(), and z.
subroutine pyinit (character*(*) FRAME, character*(*) BEAM, character*(*) TARGET, WIN)
Definition at line 2854 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 2854 of file pythia-6.4.28.f
References i, ValueGen1::i3(), ValueGen1::i4(), j, mint, msti, mstp, ngen, ngenpd, pari, parp, pdfset(), pyckbd(), pydat1, pydat2, pydat3, pydat4, pygaga(), pyinbm(), pyinki(), pyinpr(), pyinre(), pyint1, pyint2, pyint5, pykfin(), pylist(), pymaxi(), pymign(), pymsin(), pymult(), pypars, pypile(), pysave(), pystop(), pysubs, pytune, pyxdin(), pyxtot(), upinit(), value, vint, x, and xsec.
subroutine pyinki (MODKI)
Definition at line 5811 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 5811 of file pythia-6.4.28.f
References i, j, k, Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, p, pari, parp, pyangl(), pydat1, pydat2, pyerrm(), pyint1, pyjets, pypars, pyrobo(), pysubs, s, sign(), v, and vint.
subroutine pyinom ()
Definition at line 48775 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 48775 of file pythia-6.4.28.f
References Fatras::Test::Particle::beta(), i, index, j, k, Acts::Logger::log(), pyalem(), pyalps(), pycomp, pydat1, pydat2, pyeicg(), pyerrm(), pymssm, pyrnm3(), pyssmt, pystop(), s, sign(), and x0.
subroutine pyinpr ()
Definition at line 6009 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 6009 of file pythia-6.4.28.f
References i, j, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, pari, parp, pycomp, pydat1, pydat2, pydat3, pyerrm(), pyint1, pyint2, pyint6, pypars, pysubs, and vint.
subroutine pyinre ()
Definition at line 5217 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 5217 of file pythia-6.4.28.f
References i, ValueGen1::i1(), j, mint, msti, mstp, pari, parp, pycomp, pydat1, pydat2, pydat3, pydat4, pyint1, pyint2, pyint4, pyint6, pymssm, pypars, pystop(), pysubs, pywidt(), vint, and x.
subroutine pyjmas (PMH, PML)
Definition at line 77949 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 77949 of file pythia-6.4.28.f
References i, j, k, Acts::detail::PhiBoundParameterLimits::max(), n, HiMain1::np(), npad, p, ps(), pychge(), pycomp, pydat1, pydat2, pyerrm(), pyjets, Acts::InternalSpacePoint< SpacePoint >::sp(), and v.
subroutine pyjoin (NJOIN, dimension(*) IJOIN)
Definition at line 60858 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 60858 of file pythia-6.4.28.f
References i, in, k, n, npad, p, pycomp, pydat1, pydat2, pyerrm(), pyjets, pyr(), and v.
subroutine pyjurf (dimension(3,5) PJU, dimension(5) VJU)
Definition at line 67974 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 67974 of file pythia-6.4.28.f
References i, ValueGen1::i1(), Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, Input, Result >::iter(), j, k, Acts::detail::PhiBoundParameterLimits::max(), and twopi.
integer function pyk (I, J)
Definition at line 76785 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 76785 of file pythia-6.4.28.f
References i, ValueGen1::i1(), ValueGen1::i2(), ValueGen1::i3(), j, k, Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, pychge(), pycomp, pydat1, pydat2, pyjets, pyk(), and v.
subroutine pykcut (MCUT)
Definition at line 80914 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 80914 of file pythia-6.4.28.f
References Acts::detail::PhiBoundParameterLimits::max(), mint, PseudoJet::pt2(), pydat1, pyint1, pyint2, pystop(), tau, vint, and x.
subroutine pykfdi (KFL1, KFL2, KFL3, KF)
Definition at line 69614 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 69614 of file pythia-6.4.28.f
References Acts::detail::PhiBoundParameterLimits::max(), pycomp, pydat1, pydat2, pyerrm(), pykfin(), pynmes(), and pyr().
subroutine pykfin ()
Definition at line 70108 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 70108 of file pythia-6.4.28.f
References i, id, Acts::detail::PhiBoundParameterLimits::max(), pycomp, pydat1, pydat2, pyerrm(), and pymass().
subroutine pyklim (ILIM)
Definition at line 29064 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 29064 of file pythia-6.4.28.f
References k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, p, pari, parp, pydat1, pydat2, pydat3, pyint1, pyint2, pyjets, pypars, pysubs, sign(), tau, v, and vint.
subroutine pykmap (IVAR, MVAR, VVAR)
Definition at line 29480 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 29480 of file pythia-6.4.28.f
References eps, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, pari, parp, pydat1, pydat2, pyint1, pyint2, pypars, pyr(), pysubs, rpt, tau, and vint.
double precision function pylamf (double precision X, double precision Y, double precision Z)
Definition at line 54715 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 54715 of file pythia-6.4.28.f
References pylamf(), x, y, and z.
subroutine pyldcm (complex*16, dimension(np,np) A, integer N, integer NP, integer, dimension(n) INDX, real*8 D)
Definition at line 57303 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 57303 of file pythia-6.4.28.f
References i, j, k, n, pyerrm(), and sum().
subroutine pylhef ()
Definition at line 5097 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 5097 of file pythia-6.4.28.f
References end, i, msti, mstp, pari, parp, pypars, and mvtx::PayLoadCont::rewind().
subroutine pylist (MLIST)
Definition at line 75896 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 75896 of file pythia-6.4.28.f
References i, ValueGen1::i1(), ValueGen1::i2(), ValueGen1::i3(), ValueGen1::i4(), ValueGen1::i5(), j, k, Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, ps(), pycomp, pydat1, pydat2, pydat3, pyjets, pylogo(), pyname(), pyp(), v, and x.
subroutine pylogo ()
Definition at line 76250 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 76250 of file pythia-6.4.28.f
References j, line, Acts::detail::PhiBoundParameterLimits::max(), msti, mstp, pari, parp, pydat1, pypars, pystop(), and pytime().
function pymael (NI, X1, X2, R1, R2, ALPHA)
Definition at line 73631 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 73631 of file pythia-6.4.28.f
References alpha, Acts::detail::PhiBoundParameterLimits::max(), ni, ps(), pyerrm(), pymael(), r1, and r2.
function pymass (KF)
Definition at line 74871 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 74871 of file pythia-6.4.28.f
References Acts::detail::PhiBoundParameterLimits::max(), pycomp, pydat1, pydat2, pymass(), and pyr().
subroutine pymaxi ()
Definition at line 7315 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 7315 of file pythia-6.4.28.f
References e, false, i, ValueGen1::i3(), ValueGen1::i4(), j, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, nbin, ngen, ngenpd, ntry, p, pari, parp, pyalem(), pycomp, pydat1, pydat2, pydat3, pyerrm(), pyevwt(), pygaga(), pyint1, pyint2, pyint3, pyint4, pyint5, pyint6, pyint7, pyklim(), pykmap(), pyofsh(), pypars, pysigh(), pystop(), pysubs, pytecm(), TrigInDetTriplet< space_point_t >::s1(), tau, true, vint, x, and xsec.
subroutine pymemx (MECOR, WTFF, WTGF, WTFG, WTGG)
Definition at line 15953 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 15953 of file pythia-6.4.28.f
References k, mint, msti, mstp, n, npad, p, pari, parp, pydat1, pyint1, pyint2, pyjets, pypars, v, and vint.
subroutine pymewt (MECOR, IFLCB, Q2, Z, PHIBR, WTME)
Definition at line 16000 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 16000 of file pythia-6.4.28.f
References k, mint, msti, mstp, n, npad, p, pari, parp, pydat1, pyint1, pyint2, pyjets, pypars, v, vint, and z.
subroutine pymign (MMUL)
Definition at line 20921 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 20921 of file pythia-6.4.28.f
References i, ValueGen1::i1(), ValueGen1::i2(), j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, ngen, ngenpd, npad, p, pari, parp, phi, pt, pyalps(), pydat1, pydat2, pydat3, pyerrm(), pyint1, pyint2, pyint3, pyint5, pyint7, pyjets, pyklim(), pykmap(), pymass(), pypars, pypdfu(), pyr(), pyrobo(), pysigh(), pysspa(), pysubs, pywidt(), Acts::InternalSpacePoint< SpacePoint >::sp(), tau, v, vint, x, and xsec.
subroutine pymihg (JCP1, JCG1, JCP2, JCG2)
Definition at line 23138 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 23138 of file pythia-6.4.28.f
References i, k, Acts::detail::PhiBoundParameterLimits::max(), mint, n, npad, p, pyerrm(), pyint1, pyjets, v, and vint.
subroutine pymihk ()
Definition at line 21903 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 21903 of file pythia-6.4.28.f
References Fatras::Test::Particle::beta(), i, ValueGen1::i1(), ValueGen1::i2(), j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, ntry, p, pari, parp, pycomp, pycttr(), pydat1, pydat2, pyedit(), pyerrm(), pyint1, pyjets, pykfdi(), pylist(), pymass(), pymihg(), pypars, pyr(), pyrobo(), pyspli(), v, and vint.
subroutine pymirm ()
Definition at line 23282 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 23282 of file pythia-6.4.28.f
References c, corr, eps, i, ValueGen1::i1(), ValueGen1::i2(), in, j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, ntry, p, pari, parp, phi, pt, PseudoJet::pt2(), pyangl(), pydat1, pyerrm(), pygive(), pyint1, pyjets, pypars, pyr(), pyrobo(), pyzdis(), Fatras::Test::Particle::q(), r1, r2, sigma, t1(), v, vint, sHelix::w(), and x.
function pymrun (KF, Q2)
Definition at line 74936 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 74936 of file pythia-6.4.28.f
References Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), msti, mstp, pari, parp, pyalps(), pydat1, pydat2, pymass(), pymrun(), and pypars.
subroutine pymsin ()
Definition at line 45473 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 45473 of file pythia-6.4.28.f
References Fatras::Test::Particle::beta(), dy, i, ValueGen1::i1(), init(), j, Acts::StepperExtensionList< extensions >::k1(), msti, mstp, pari, parp, pyapps(), pycjdc(), pycomp, pydat1, pydat2, pydat3, pydat4, pyglui(), pyhext(), pyhggm(), pyinom(), pyint4, pymssm, pynjdc(), pypars, pysfdc(), pyslha(), pyssmt, pystop(), pysugi(), pythrg(), pywidt(), r, and sign().
subroutine pymult (MMUL)
Definition at line 19572 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 19572 of file pythia-6.4.28.f
References dist(), i, ValueGen1::i1(), ValueGen1::i2(), j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, ngen, ngenpd, npad, p, pari, parp, phi, pt, pycomp, pydat1, pydat2, pyerrm(), pyint1, pyint2, pyint3, pyint5, pyint7, pyjets, pyklim(), pykmap(), pypars, pyr(), pyshow(), pysigh(), pysubs, Acts::InternalSpacePoint< SpacePoint >::sp(), tau, v, vint, x, and xsec.
subroutine pyname (KF, character CHAU)
Definition at line 74973 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 74973 of file pythia-6.4.28.f
References pycomp, pydat1, pydat2, and pydat4.
subroutine pynjdc (integer KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, integer IKNT)
Definition at line 52234 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 52234 of file pythia-6.4.28.f
References Fatras::Test::Particle::beta(), ei(), fid, i, j, pi, pyalem(), pyalps(), pycomp, pydat1, pydat2, pygaus(), pylamf(), pymssm, pyrvne(), pyssmt, pyx2xg(), pyx2xh(), pyxxga(), pyxxz6(), and sign().
subroutine pynmes (KFDIQ)
Definition at line 70046 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 70046 of file pythia-6.4.28.f
References pydat1, pydat2, pyerrm(), and pyr().
subroutine pynull (ID)
Definition at line 80709 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 80709 of file pythia-6.4.28.f
References Acts::BinUtility::bin(), id, and pybins.
subroutine pyofsh (MOFSH, KFMO, KFD1, KFD2, PMMO, RET1, RET2)
Definition at line 28109 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 28109 of file pythia-6.4.28.f
References f2(), i, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, ngen, ngenpd, pari, parp, pycomp, pydat1, pydat2, pydat3, pyerrm(), pyint1, pyint2, pyint5, pypars, pyr(), pysubs, vint, and xsec.
subroutine pyonia (KFL, ECM)
Definition at line 80158 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 80158 of file pythia-6.4.28.f
References k, Acts::detail::PhiBoundParameterLimits::max(), n, npad, ntry, p, phi, py1ent, py2ent(), py3ent(), pyalps(), pydat1, pydat2, pyerrm(), pyexec(), pyjets, pylist(), pyprep(), pyr(), pyrobo(), pyshow(), and v.
subroutine pyonof (character, dimension(*) CHIN)
Definition at line 61416 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 61416 of file pythia-6.4.28.f
References pycomp, pydat1, pydat3, and pyerrm().
subroutine pyoper (ID1, character, dimension(*) OPER, ID2, ID3, F1, F2)
Definition at line 80427 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 80427 of file pythia-6.4.28.f
References Acts::BinUtility::bin(), f2(), Acts::detail::PhiBoundParameterLimits::max(), nx, pybins, and pyerrm().
function pyp (I, J)
Definition at line 76924 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 76924 of file pythia-6.4.28.f
References i, ValueGen1::i1(), j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, pyangl(), pychge(), pydat1, pydat2, pyjets, pymass(), pyp(), sign(), and v.
double precision function pypcmp (double precision XS, integer NPOW)
Definition at line 16680 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 16680 of file pythia-6.4.28.f
References Acts::Logger::log(), and pypcmp().
subroutine pypdel (KFA, X, Q2, dimension(-25:25) XPEL)
Definition at line 39832 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 39832 of file pythia-6.4.28.f
References Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, Input, Result >::iter(), Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, pari, parp, pdfset(), pyalem(), pydat1, pydat2, pygamm(), pyggam(), pyint1, pypars, pypdga(), str, structm(), bin_heap< T, Pred >::top(), value, vint, x, xmax, and xmin.
subroutine pypdfl (KF, X, Q2, dimension(-25:25) XPQ)
Definition at line 39589 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 39589 of file pythia-6.4.28.f
References Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, p, pari, parp, pydat1, pydat2, pyint1, pypars, pypdfu(), vint, and x.
subroutine pypdfu (KF, X, Q2, dimension(-25:25) XPQ)
Definition at line 38911 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 38911 of file pythia-6.4.28.f
References ValueGen1::i1(), ValueGen1::i5(), k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, p, pari, parp, pdfset(), pydat1, pydat2, pyerrm(), pyfcmp(), pygano(), pyggam(), pygvmd(), pyint1, pyint8, pyint9, pyjets, pypars, pypcmp(), pypdel(), pypdga(), pypdpi(), pypdpr(), pyr(), str, structm(), structp(), bin_heap< T, Pred >::top(), v, value, vint, x, xmax, xmin, and y.
subroutine pypdga (X, Q2, dimension(-6:6) XPGA)
Definition at line 40015 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 40015 of file pythia-6.4.28.f
References Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, pari, parp, pydat1, pyint1, pypars, t, vint, and x.
subroutine pypdpi (X, Q2, dimension(-6:6) XPPI)
Definition at line 40823 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 40823 of file pythia-6.4.28.f
References Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, pari, parp, pydat1, pygamm(), pyint1, pypars, ValueGen1::ts(), vint, x, and y.
subroutine pypdpo (X, Q2, dimension(-6:6) XPPR)
Definition at line 42391 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 42391 of file pythia-6.4.28.f
References it, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, nx, pari, parp, pydat1, pydat2, pygamm(), pyint1, pypars, t, ValueGen1::ts(), vint, vx, x, and y.
subroutine pypdpr (X, Q2, dimension(-6:6) XPPR)
Definition at line 40995 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 40995 of file pythia-6.4.28.f
References i, Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, pari, parp, pyct5l(), pyct5m(), pycteq(), pydat1, pydat2, pygrvd(), pygrvl(), pygrvm(), pyint1, pypars, pypdpo(), vint, and x.
subroutine pypile (MPILE)
Definition at line 8519 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 8519 of file pythia-6.4.28.f
References i, Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, p, pari, parp, pydat1, pyint1, pyint7, pypars, pyr(), vint, and x.
subroutine pyplot (ID)
Definition at line 80553 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 80553 of file pythia-6.4.28.f
References Acts::BinUtility::bin(), dy, ValueGen1::i2(), ValueGen1::i4(), ValueGen1::i5(), id, it, j, Acts::detail::PhiBoundParameterLimits::max(), nx, out, p, pybins, pydat1, pytime(), sign(), title, x, ymax, and ymin.
subroutine pypole (IHIGGS, XMC, XMA, TANB, XMQ, XMUR, XMDR, XMT, AT, AB, XMU, XMH, XMHP, HM, HMP, AMP, SA, CA, STOP1, STOP2, SBOT1, SBOT2, TANBA, XMG, DT, DB)
Definition at line 49805 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 49805 of file pythia-6.4.28.f
References deriv(), ValueGen1::dt(), eps, i, ValueGen1::i3(), Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, Input, Result >::iter(), j, pi, prun(), pydat1, pyfint(), pymrun(), pyrghm(), pystop(), t, and v.
subroutine pyprep (IP)
Definition at line 65109 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 65109 of file pythia-6.4.28.f
References alpha, Fatras::Test::Particle::beta(), i, ValueGen1::i1(), ValueGen1::i2(), ValueGen1::i3(), ValueGen1::i4(), it, Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, Input, Result >::iter(), j, k, Acts::StepperExtensionList< extensions >::k1(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, HiMain1::np(), npad, ntry, p, pari, parp, phi, genfit::EventDisplay::prev(), PseudoJet::pt2(), pyangl(), pycomp, pycttr(), pydat1, pydat2, pydat3, pydcyk(), pyerrm(), pyint1, pyjets, pyjurf(), pykfdi(), pylist(), pymass(), pypars, pyr(), pyrobo(), t, v, and vint.
subroutine pyptdi (KFL, PX, PY)
Definition at line 70426 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 70426 of file pythia-6.4.28.f
References Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), phi, pt, PseudoJet::px(), PseudoJet::py(), pydat1, and pyr().
subroutine pyptfs (MODE, PTMAX, PTMIN, PTGEN)
Definition at line 72147 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 72147 of file pythia-6.4.28.f
References alpha, ei(), i, ValueGen1::i1(), ValueGen1::i2(), j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, ngen, npad, npart(), p, pari, parp, phi, PseudoJet::pt2(), pyangl(), pycomp, pycttr(), pydat1, pydat2, pyerrm(), pygive(), pyint1, pyjets, pyk(), pymael(), pypars, pyr(), pyrobo(), sign(), v, vint, and z.
subroutine pyptis (MODE, PT2NOW, PT2CUT, PT2, IFAIL)
Definition at line 14831 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 14831 of file pythia-6.4.28.f
References i, ValueGen1::i1(), it, j, k, PseudoJet::kt2(), Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, npart(), ntry, p, pari, parp, phi, print(), PseudoJet::pt2(), pyangl(), pycomp, pycttr(), pydat1, pydat2, pyerrm(), pyfcmp(), pyint1, pyint2, pyjets, pymass(), pymemx(), pymewt(), pypars, pypdfu(), pyptmi(), pyr(), pyrobo(), TpcMon::side(), v, vint, Fun4AllFileOutStream::xb(), y, and z.
subroutine pyptmi (MODE, PT2NOW, PT2CUT, PT2, IFAIL)
Definition at line 16068 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 16068 of file pythia-6.4.28.f
References i, ValueGen1::i1(), ValueGen1::i2(), j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, ngen, ngenpd, npad, npart(), ntry, p, pari, parp, phi, PseudoJet::pt2(), pycomp, pycttr(), pydat1, pydat2, pydat3, pyerrm(), pyint1, pyint2, pyint3, pyint5, pyint7, pyjets, pyklim(), pykmap(), pymass(), pypars, pypdfu(), pyr(), pyrobo(), pysigh(), pywidt(), tau, v, vint, x, and xsec.
subroutine pyqqbh (WTQQBH)
Definition at line 43412 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 43412 of file pythia-6.4.28.f
References i, j, Acts::StepperExtensionList< extensions >::k1(), Acts::SolenoidBField::k2(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, pari, parp, HiStrng::pp(), pt, pycomp, pydat1, pydat2, pyint1, pyint2, pypars, and vint.
function pyr (IDUMMY)
Definition at line 75328 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 75328 of file pythia-6.4.28.f
References i, j, k, pydatr, pyr(), s, and t.
subroutine pyradk (ECM, MK, PAK, THEK, PHIK, ALPK)
Definition at line 79296 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 79296 of file pythia-6.4.28.f
References Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), pyangl(), pydat1, pymass(), and pyr().
subroutine pyrand ()
Definition at line 9195 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 9195 of file pythia-6.4.28.f
References e, eps, i, ValueGen1::i1(), ValueGen1::i2(), ValueGen1::i3(), Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, ngen, ngenpd, p, pari, parp, ps(), pycomp, pydat1, pydat2, pydat3, pyerrm(), pyevwt(), pygaga(), pyint1, pyint2, pyint3, pyint4, pyint5, pyint7, pykcut(), pyklim(), pykmap(), pylist(), pymass(), pymign(), pymssm, pymult(), pyofsh(), pypars, pypdfl(), pypdfu(), pyr(), pysave(), pysigh(), pyspli(), pystop(), pysubs, pyupre(), sign(), upevnt(), vint, x, and xsec.
subroutine pyreco (IW1, IW2, NSD1, NAFT1)
Definition at line 28527 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 28527 of file pythia-6.4.28.f
References Poisson::fact(), i, ValueGen1::i1(), ValueGen1::i2(), iap, j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, p, pari, parp, phi, pi, pydat1, pydat2, pyint1, pyjets, pyjoin(), pypars, pyprep(), pyr(), pyrobo(), pyshow(), Fatras::Test::Particle::q(), r, sum(), t, tc, v, v1, v2, vint, x, Fun4AllFileOutStream::xb(), y, and z.
subroutine pyremn (IPU1, IPU2)
Definition at line 20242 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 20242 of file pythia-6.4.28.f
References i, ValueGen1::i1(), ValueGen1::i2(), Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, Input, Result >::iter(), j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, ntry, p, pari, parp, phi, pt, pyangl(), pycomp, pydat1, pydat2, pyint1, pyjets, pymass(), pypars, pyptdi(), pyr(), pyrobo(), pyspli(), pyzdis(), sign(), v, and vint.
subroutine pyresd (IRES)
Definition at line 17236 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 17236 of file pythia-6.4.28.f
References c, ValueGen1::dt(), e, ei(), eta, hgz, i, ValueGen1::i1(), ValueGen1::i2(), ValueGen1::i3(), ValueGen1::i4(), ValueGen1::i5(), id, j, k, Acts::Logger::log(), mass, Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, HiMain1::n0(), HiMain1::np(), npad, npart(), p, pari, parp, phi, ps(), py2ent(), py3ent(), py4ent(), pyangl(), pycomp, pydat1, pydat2, pydat3, pyerrm(), pygram(), pyint1, pyint2, pyint4, pyjets, pymass(), pyofsh(), pypars, pyptfs(), pyr(), pyreco(), pyrobo(), pyshow(), pysubs, pytbdy(), pywidt(), pyx3jt(), pyx4jt(), pyxdif(), pyxjet(), TpcMon::side(), sign(), sngl, v, and vint.
subroutine pyrget (LFN, MOVE)
Definition at line 75408 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 75408 of file pythia-6.4.28.f
References ValueGen1::i1(), ValueGen1::i2(), pydatr, and pyerrm().
subroutine pyrghm (MCHI, MA, TANB, MQ, MUR, MD, MTOP, AU, AD, MU, MHP, HMP, MCH, SA, CA, SAB, CAB, TANBA, MGLU, DELTAMT, DELTAMB)
Definition at line 50170 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 50170 of file pythia-6.4.28.f
References alpha, i, j, Acts::Logger::log(), pi, pydat1, pygfxx(), pymrun(), and v.
function pyrnm3 (RGUT)
Definition at line 49196 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 49196 of file pythia-6.4.28.f
References c, f2(), Acts::detail::PhiBoundParameterLimits::max(), pyalps(), pyrnm3(), r, x0, and xmin.
function pyrnmq (ID, DTERM)
Definition at line 48429 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 48429 of file pythia-6.4.28.f
References c, ci, f2(), id, Acts::detail::PhiBoundParameterLimits::max(), pi, pyalps(), pymssm, pyrnmq(), r, x0, and xmin.
subroutine pyrobo (IMI, IMA, THE, PHI, BEX, BEY, BEZ)
Definition at line 75492 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 75492 of file pythia-6.4.28.f
References i, j, k, n, npad, p, phi, pydat1, pyerrm(), pyjets, and v.
subroutine pyrset (LFN, MOVE)
Definition at line 75449 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 75449 of file pythia-6.4.28.f
References ValueGen1::i1(), ValueGen1::i2(), Acts::detail::PhiBoundParameterLimits::max(), pydatr, and pyerrm().
subroutine pyrvch (KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, LKNT)
Definition at line 58117 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 58117 of file pythia-6.4.28.f
References c2, false, i, j, pycomp, pydat1, pydat2, pymrun(), pymssm, pyrvgw(), pyssmt, rms(), and true.
double precision function pyrvg1 (double precision X)
Definition at line 59144 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 59144 of file pythia-6.4.28.f
References Acts::detail::PhiBoundParameterLimits::max(), pyrvg1(), pyrvr(), and x.
double precision function pyrvg2 (double precision X)
Definition at line 59177 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 59177 of file pythia-6.4.28.f
References Acts::detail::PhiBoundParameterLimits::max(), pyrvg2(), pyrvs(), and x.
double precision function pyrvg3 (double precision X)
Definition at line 59210 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 59210 of file pythia-6.4.28.f
References Acts::detail::PhiBoundParameterLimits::max(), pygau2(), pyrvg3(), pyrvg4(), x, ymax, and ymin.
double precision function pyrvg4 (double precision Y)
Definition at line 59248 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 59248 of file pythia-6.4.28.f
References pyrvg4(), pyrvs(), x, and y.
subroutine pyrvgl (KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, LKNT)
Definition at line 58594 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 58594 of file pythia-6.4.28.f
References false, i, pyalps(), pycomp, pydat1, pydat2, pymssm, pyrvgw(), pyssmt, rms(), and true.
subroutine pyrvgw (KFIN, ID1, ID2, ID3, XLAM)
Definition at line 58864 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 58864 of file pythia-6.4.28.f
References eps, false, i, j, n, pycomp, pydat2, pymrun(), pyrvi1(), pyrvi2(), pyrvi3(), pyssmt, rms(), true, and xlim.
double precision function pyrvi1 (integer ID1, integer ID2, integer ID3)
Definition at line 59028 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 59028 of file pythia-6.4.28.f
References pygaus(), pyrvg1(), pyrvi1(), and rms().
double precision function pyrvi2 (integer ID1, integer ID2, integer ID3)
Definition at line 59064 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 59064 of file pythia-6.4.28.f
References pygaus(), pyrvg2(), pyrvi2(), and rms().
double precision function pyrvi3 (integer ID1, integer ID2, integer ID3)
Definition at line 59104 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 59104 of file pythia-6.4.28.f
References pygaus(), pyrvg3(), pyrvi3(), and rms().
subroutine pyrvne (KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, LKNT)
Definition at line 57850 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 57850 of file pythia-6.4.28.f
References c2, false, i, j, pycomp, pydat1, pydat2, pymrun(), pymssm, pyrvgw(), pyssmt, rms(), and true.
double precision function pyrvr (double precision Mab2, double precision RM, double precision RW)
Definition at line 59274 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 59274 of file pythia-6.4.28.f
References pyrvr().
double precision function pyrvs (double precision X, double precision Y, double precision M1, double precision W1, double precision M2, double precision W2)
Definition at line 59287 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 59287 of file pythia-6.4.28.f
References pyrvr(), pyrvs(), x, and y.
function pyrvsb (KFIN, ID1, ID2, RM2, MODE)
Definition at line 58823 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 58823 of file pythia-6.4.28.f
References i, Acts::detail::PhiBoundParameterLimits::max(), n, pycomp, pydat1, pydat2, and pyrvsb().
subroutine pyrvsf (KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, LKNT)
Definition at line 57546 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 57546 of file pythia-6.4.28.f
References i, j, k, pycomp, pydat2, pymssm, pyrvsb(), and pyssmt.
subroutine pysave (ISAVE, IGA)
Definition at line 8608 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 8608 of file pythia-6.4.28.f
References i, ValueGen1::i1(), ValueGen1::i2(), j, mint, msti, mstp, ngen, ngenpd, pari, parp, pyint1, pyint2, pyint5, pyint7, pypars, pyr(), pysubs, vint, and xsec.
subroutine pyscat ()
Definition at line 10572 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 10572 of file pythia-6.4.28.f
References c2, i, ValueGen1::i1(), ValueGen1::i2(), ValueGen1::i3(), ValueGen1::i4(), in, j, k, Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, ngen, ngenpd, npad, npart(), p, pari, parp, phi, pt, PseudoJet::px(), PseudoJet::py(), pyangl(), pychge(), pycomp, pydat1, pydat2, pydat3, pyerrm(), pyint1, pyint2, pyint3, pyint4, pyint5, pyjets, pymass(), pypars, pyr(), pyrobo(), pyssmt, pystop(), pysubs, pywidt(), PseudoJet::pz(), sign(), v, vint, xsec, and z.
subroutine pysfdc (integer KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, integer IKNT)
Definition at line 50761 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 50761 of file pythia-6.4.28.f
References Fatras::Test::Particle::beta(), ei(), i, j, pi, pyalem(), pyalps(), pycomp, pydat1, pydat2, pylamf(), pymrun(), pymssm, pyrvsf(), pyssmt, and sign().
subroutine pysgex (NCHN, SIGS)
Definition at line 38017 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 38017 of file pythia-6.4.28.f
References ei(), Poisson::fact(), i, j, mint, msti, mstp, pari, parp, pycomp, pydat1, pydat2, pydat3, pyint1, pyint2, pyint3, pyint4, pypars, pyr(), pywidt(), sign(), vint, and x.
subroutine pysghf (NCHN, SIGS)
Definition at line 31578 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 31578 of file pythia-6.4.28.f
References c2, i, j, mint, msti, mstp, pari, parp, pycomp, pydat1, pydat2, pyhfth(), pyint1, pyint2, pyint3, pyint4, pypars, vint, and x.
subroutine pysghg (NCHN, SIGS)
Definition at line 34049 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 34049 of file pythia-6.4.28.f
References ei(), i, j, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, pari, parp, pydat1, pydat2, pydat3, pyerrm(), pyi3au(), pyint1, pyint2, pyint3, pyint4, pymrun(), pymssm, pypars, pyqqbh(), pystbh(), pystop(), pysubs, pywaux(), pywidt(), sign(), vint, and x.
subroutine pysgqc (NCHN, SIGS)
Definition at line 30662 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 30662 of file pythia-6.4.28.f
References ei(), i, j, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, pari, parp, pyalps(), pycomp, pydat1, pydat2, pydat3, pyi3au(), pyint1, pyint2, pyint3, pyint4, pyint7, pypars, pywaux(), pywidt(), sign(), vint, and x.
subroutine pysgsu (NCHN, SIGS)
Definition at line 35426 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 35426 of file pythia-6.4.28.f
References ei(), i, j, mint, msti, mstp, pari, parp, pycomp, pydat1, pydat2, pyint1, pyint2, pyint3, pyint4, pymssm, pypars, pyssmt, pywidt(), sign(), vint, and x.
subroutine pysgtc (NCHN, SIGS)
Definition at line 36699 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 36699 of file pythia-6.4.28.f
References ei(), i, j, Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, pari, parp, pyalps(), pybksb(), pycomp, pydat1, pydat2, pydat3, pyhfth(), pyint1, pyint2, pyint3, pyint4, pyldcm(), pypars, pywidt(), sign(), vint, and x.
subroutine pysgwz (NCHN, SIGS)
Definition at line 33239 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 33239 of file pythia-6.4.28.f
References ei(), hgz, i, j, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, pari, parp, pyalps(), pydat1, pydat2, pydat3, pyint1, pyint2, pyint3, pyint4, pypars, pysubs, pywidt(), sign(), vint, and x.
subroutine pyshow (IP1, IP2, QMAX)
Definition at line 70578 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 70578 of file pythia-6.4.28.f
References alpha, ei(), i, ValueGen1::i1(), ValueGen1::i2(), j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, npart(), p, pari, parp, phi, ps(), pt, pyangl(), pycomp, pydat1, pydat2, pyerrm(), pyint1, pyjets, pymael(), pymass(), pypars, pyptfs(), pyr(), pyrobo(), sign(), v, vint, and z.
subroutine pysigh (NCHN, SIGS)
Definition at line 29863 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 29863 of file pythia-6.4.28.f
References h1, h2, i, j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, ngen, ngenpd, npad, p, pari, parp, pyalem(), pyalps(), pycomp, pydat1, pydat2, pydat3, pyint1, pyint2, pyint3, pyint4, pyint5, pyint7, pyjets, pymass(), pymssm, pypars, pypdfl(), pypdfu(), pysgex(), pysghf(), pysghg(), pysgqc(), pysgsu(), pysgtc(), pysgwz(), pyssmt, pysubs, pyxued(), Acts::MultiComponentBoundTrackParameters::reduce(), tau, v, vint, x, and xsec.
function pysimp (double precision, dimension(0:n) Y, double precision X0, double precision X1, N)
Definition at line 54689 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 54689 of file pythia-6.4.28.f
References h, i, n, pysimp(), s, x0, and y.
subroutine pyslha (MUPDA, KFORIG, IRETRN)
Definition at line 46191 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 46191 of file pythia-6.4.28.f
References end, i, ValueGen1::i1(), ValueGen1::i2(), ValueGen1::i3(), ValueGen1::i4(), it, j, k, Acts::detail::PhiBoundParameterLimits::max(), msti, mstp, p, pari, parp, pychge(), pycomp, pydat1, pydat2, pydat3, pydat4, pyerrm(), pyfeyn(), pyint4, pymssm, pypars, pyssmt, pystop(), Fatras::Test::Particle::q(), mvtx::PayLoadCont::rewind(), sign(), visaje(), width, and x.
function pyspen (XREIN, XIMIN, IREIM)
Definition at line 43315 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 43315 of file pythia-6.4.28.f
References i, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), pydat1, pyspen(), and sign().
subroutine pysphe (SPH, APL)
Definition at line 77007 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 77007 of file pythia-6.4.28.f
References i, j, k, Acts::detail::PhiBoundParameterLimits::max(), n, HiMain1::np(), npad, p, ps(), pychge(), pycomp, pydat1, pydat2, pyerrm(), pyjets, pyr(), Acts::InternalSpacePoint< SpacePoint >::sp(), and v.
subroutine pyspli (KF, KFLIN, KFLCH, KFLSP)
Definition at line 42931 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 42931 of file pythia-6.4.28.f
References j, mint, msti, mstp, ntry, pari, parp, pydat1, pyerrm(), pyint1, pykfdi(), pypars, pyr(), and vint.
subroutine pysspa (IPU1, IPU2)
Definition at line 13914 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 13914 of file pythia-6.4.28.f
References i, it, j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, npart(), ntry, p, pari, parp, ps(), pyalps(), pyangl(), pycomp, pydat1, pydat2, pyerrm(), pyint1, pyint2, pyint3, pyjets, pymass(), pymemx(), pymewt(), pypars, pypdfl(), pypdfu(), pyr(), pyrobo(), pyshow(), pysubs, v, vint, Fun4AllFileOutStream::xb(), and z.
subroutine pystat (MSTAT)
Definition at line 4029 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 4029 of file pythia-6.4.28.f
References eps, i, ValueGen1::i1(), ValueGen1::i2(), ValueGen1::i3(), ValueGen1::i4(), ValueGen1::i5(), j, Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, ngen, ngenpd, p, pari, parp, pycomp, pydat1, pydat2, pydat3, pyint1, pyint2, pyint4, pyint5, pyint6, pymssm, pyname(), pypars, pysave(), pysubs, pywidt(), vint, x, and xsec.
subroutine pystbh (WTTBH)
Definition at line 43820 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 43820 of file pythia-6.4.28.f
References alpha, alphas(), i, Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, pari, parp, HiStrng::pp(), pt, pydat1, pydat2, pyint1, pyint2, pyint3, pyint4, pymrun(), pymssm, pypars, pysubs, pytbhg(), pytbhq(), v, vint, and x.
subroutine pystop (MCOD)
Definition at line 80884 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 80884 of file pythia-6.4.28.f
References ValueGen1::i4(), pydat1, Acts::ExaTrkXTimer::stop(), and x.
subroutine pystrf (IP)
Definition at line 66569 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 66569 of file pythia-6.4.28.f
References fd, i, ValueGen1::i1(), Acts::Ray< value_t, DIM >::idir(), in, it, j, k, line, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), n, HiMain1::np(), npad, ntry, p, HijJet4::pdr(), genfit::EventDisplay::prev(), PseudoJet::px(), PseudoJet::py(), pycomp, pydat1, pydat2, pyerrm(), pyjets, pyjurf(), pykfdi(), pymass(), pyp(), pyptdi(), pyr(), pyrobo(), pyzdis(), Acts::MultiComponentBoundTrackParameters::reduce(), sign(), v, and z.
subroutine pysubh (double precision XMA, double precision TANB, double precision XMQ, double precision XMUR, double precision XMTOP, double precision AU, double precision AD, double precision XMU, double precision XMH, double precision XHM, double precision XMHCH, double precision SA, double precision CA, double precision TANBA)
Definition at line 49570 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 49570 of file pythia-6.4.28.f
References Acts::Logger::log(), pi, pyalem(), pyalps(), pydat1, pydat2, pymrun(), t, and v.
subroutine pysugi ()
Definition at line 47792 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 47792 of file pythia-6.4.28.f
References i, in, j, Acts::StepperExtensionList< extensions >::k1(), Acts::SolenoidBField::k2(), Acts::detail::PhiBoundParameterLimits::max(), msti, mstp, PseudoJet::mt(), p, pari, parp, pycomp, pydat1, pydat2, pyerrm(), pyfeyn(), pymssm, pypars, pyssmt, pystop(), ssmssm(), sugra(), v, visaje(), and x.
subroutine pytabu (MTABU)
Definition at line 78222 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 78222 of file pythia-6.4.28.f
References i, ValueGen1::i1(), ValueGen1::i2(), j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), n, HiMain1::np(), npad, p, phi, pyangl(), pychge(), pycomp, pydat1, pydat2, pydat3, pyerrm(), pyjets, pymass(), pyname(), sign(), v, and x.
subroutine pytaud (ITAU, IORIG, KFORIG, NDECAY)
Definition at line 81641 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 81641 of file pythia-6.4.28.f
References k, n, npad, p, pydat1, pyjets, pystop(), v, and x.
subroutine pytbbc (integer I, integer NN, double precision XMGLU, double precision GAM)
Definition at line 51995 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 51995 of file pythia-6.4.28.f
References alphas(), false, i, j, Acts::Logger::log(), pyalem(), pyalps(), pycomp, pydat1, pydat2, pylamf(), pymrun(), pymssm, pysimp(), pyssmt, true, and sHelix::w().
subroutine pytbbn (I, integer NN, double precision E, double precision XMGLU, double precision GAM)
Definition at line 51773 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 51773 of file pythia-6.4.28.f
References alphas(), b1, e, false, g, i, j, Acts::Logger::log(), pyalem(), pyalps(), pycomp, pydat1, pydat2, pylamf(), pymrun(), pymssm, pysimp(), pyssmt, true, and sHelix::w().
subroutine pytbdy (IDIN)
Definition at line 54736 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 54736 of file pythia-6.4.28.f
References c, ValueGen1::d1(), ei(), eps, f2(), i, ValueGen1::i1(), id, k, Acts::detail::PhiBoundParameterLimits::max(), msti, mstp, n, npad, p, pari, parp, print(), pycomp, pydat1, pydat2, pyjets, pypars, pyr(), pyssmt, r, sign(), v, x0, and xmin.
subroutine pytbhb (double precision MT, double precision MB, double precision MHP, BR, GAMT)
Definition at line 43906 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 43906 of file pythia-6.4.28.f
References alpha, alphas(), PseudoJet::mt(), v, and Fun4AllFileOutStream::xb().
subroutine pytbhg (dimension(4) Q1, dimension(4) Q2, dimension(4) P1, dimension(4) P2, dimension(4) P3, double precision MT, double precision MB, RMB, double precision MHP, AMP2)
Definition at line 43954 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 43954 of file pythia-6.4.28.f
References alpha, alphas(), Poisson::fact(), PseudoJet::mt(), pi, ps(), pydat1, pydat2, pymssm, pytbhb(), pytbhs(), s, and v.
subroutine pytbhq (dimension(4) Q1, dimension(4) Q2, dimension(4) P1, dimension(4) P2, dimension(4) P3, double precision MT, double precision MB, RMB, double precision MHP, AMP2)
Definition at line 45289 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 45289 of file pythia-6.4.28.f
References alpha, alphas(), Poisson::fact(), PseudoJet::mt(), pi, ps(), pydat1, pydat2, pymssm, pytbhb(), pytbhs(), s, and v.
DOUBLE PRECISION function pytbhs (dimension(4) A, dimension(4) B)
Definition at line 45453 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 45453 of file pythia-6.4.28.f
References id, and pytbhs().
subroutine pytecm (SMIN, SMOU, WIDO, IOPT)
Definition at line 55143 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 55143 of file pythia-6.4.28.f
References i, j, msti, mstp, pari, parp, pyalem(), pycomp, pydat1, pydat2, pyeicg(), pypars, pywidt(), r1, r2, TrigInDetTriplet< space_point_t >::s1(), and TrigInDetTriplet< space_point_t >::s2().
subroutine pytest (MTEST)
Definition at line 2254 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 2254 of file pythia-6.4.28.f
References i, ValueGen1::i2(), ValueGen1::i4(), j, k, Acts::detail::PhiBoundParameterLimits::max(), msti, mstp, n, npad, p, pari, parp, phi, py1ent, py2ent(), py3ent(), py4ent(), pycomp, pydat1, pydat2, pydat3, pyeevt(), pyevnt(), pyexec(), pyinit(), pyjets, pylist(), pymass(), pyonia(), pyp(), pypars, pyr(), pystat(), pystop(), pysubs, pytabu(), sign(), v, and x.
DOUBLE PRECISION function pythag (double precision A, double precision B)
Definition at line 56862 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 56862 of file pythia-6.4.28.f
References p, pythag(), r, s, and t.
subroutine pythrg ()
Definition at line 48516 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 48516 of file pythia-6.4.28.f
References Fatras::Test::Particle::beta(), i, if(), it, j, Acts::detail::PhiBoundParameterLimits::max(), pycomp, pydat1, pydat2, pyerrm(), pymrun(), pymssm, pyssmt, pystop(), sign(), small, and true.
subroutine pythru (THR, OBL)
Definition at line 77161 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 77161 of file pythia-6.4.28.f
References i, j, k, n, HiMain1::np(), npad, p, phi, ps(), pyangl(), pychge(), pycomp, pydat1, pydat2, pyerrm(), pyjets, pyr(), pyrobo(), sign(), and v.
subroutine pytime (integer, dimension(6) IDATI)
Definition at line 81675 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 81675 of file pythia-6.4.28.f
References j.
subroutine pytune (MYTUNE)
Definition at line 61592 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 61592 of file pythia-6.4.28.f
References e, i, ValueGen1::i2(), ValueGen1::i3(), ValueGen1::i4(), msti, mstp, pari, parp, pydat1, pyerrm(), pypars, and x.
subroutine pyuedc ()
Definition at line 55358 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 55358 of file pythia-6.4.28.f
References c, i, msti, mstp, pari, parp, pi, pyalps(), pydat1, pydat2, pydat3, pyint4, pypars, pystop(), pywidt(), and zeta3.
subroutine pyupda (MUPDA, LFN)
Definition at line 76426 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 76426 of file pythia-6.4.28.f
References end, i, ValueGen1::i3(), ValueGen1::i5(), j, Acts::detail::PhiBoundParameterLimits::max(), p, pychge(), pycomp, pydat1, pydat2, pydat3, pydat4, pyerrm(), pyint4, pylist(), and x.
subroutine pyupev ()
Definition at line 4742 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 4742 of file pythia-6.4.28.f
References i, ValueGen1::i5(), j, k, mint, msti, mstp, n, npad, p, pari, parp, pycomp, pydat1, pydat2, pydat3, pydiff(), pydisg(), pydocu(), pyfram(), pygaga(), pyinki(), pyint1, pyint2, pyint4, pyjets, pypars, pyrand(), pyresd(), pyrobo(), pysave(), pyscat(), pyveto(), pyxtot(), Acts::ExaTrkXTimer::stop(), v, vint, and x.
subroutine pyupin ()
Definition at line 5026 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 5026 of file pythia-6.4.28.f
References k, Acts::detail::PhiBoundParameterLimits::max(), msti, mstp, n, ngen, ngenpd, npad, p, pari, parp, pyint5, pyjets, pypars, pysubs, v, and xsec.
subroutine pyupre ()
Definition at line 16718 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 16718 of file pythia-6.4.28.f
References i, j, and pyerrm().
subroutine pyveto (IVETO)
Definition at line 17073 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 17073 of file pythia-6.4.28.f
References Fatras::Test::Particle::gamma(), i, k, Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, npad, p, pari, parp, pydat1, pyint1, pyjets, pypars, upveto(), v, and vint.
subroutine pywaux (IAUX, EPS, WRE, WIM)
Definition at line 43168 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 43168 of file pythia-6.4.28.f
References eps, Acts::Logger::log(), pydat1, and x.
DOUBLE PRECISION function pywdkk (X)
Definition at line 56073 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 56073 of file pythia-6.4.28.f
References i, n, pi, pydat1, pydat2, pywdkk(), and x.
subroutine pywidt (KFLR, SH, dimension(0:400) WDTP, dimension(0:400,0:5) WDTE)
Definition at line 25088 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 25088 of file pythia-6.4.28.f
References Fatras::Test::Particle::beta(), ei(), eps, i, j, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, pari, parp, pyalem(), pyalps(), pycomp, pydat1, pydat2, pydat3, pyhfth(), pyint1, pyint4, pymrun(), pymssm, pyofsh(), pypars, pyssmt, pysubs, pywidx(), sign(), t1(), vint, x, and y.
subroutine pywidx (KFLR, SH, dimension(0:400) WDTP, dimension(0:400,0:5) WDTE)
Definition at line 57407 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 57407 of file pythia-6.4.28.f
References i, Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, pari, parp, pyalem(), pyalps(), pycomp, pydat1, pydat2, pydat3, pyhfth(), pyint1, pyint4, pymssm, pypars, pysubs, sign(), and vint.
double precision function pyx2xg (double precision C1, double precision XM1, double precision XM2, double precision XM3, double precision GX2, double precision GLR)
Definition at line 53994 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 53994 of file pythia-6.4.28.f
References pylamf(), and pyx2xg().
double precision function pyx2xh (double precision C1, double precision XM1, double precision XM2, double precision XM3, GX2, GLR)
Definition at line 54023 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 54023 of file pythia-6.4.28.f
References pylamf(), and pyx2xh().
subroutine pyx3jt (NJET, CUT, KFL, ECM, X1, X2)
Definition at line 79627 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 79627 of file pythia-6.4.28.f
References Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), pydat1, pymass(), pyr(), sign(), and x.
subroutine pyx4jt (NJET, CUT, KFL, ECM, KFLN, X1, X2, X4, X12, X14)
Definition at line 79794 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 79794 of file pythia-6.4.28.f
References id, it, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), pydat1, pymass(), and pyr().
subroutine pyxdif (NC, NJET, KFL, ECM, CHI, THE, PHI)
Definition at line 80018 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 80018 of file pythia-6.4.28.f
References k, Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, phi, pydat1, pydat2, pyjets, pymass(), pyr(), sign(), and v.
subroutine pyxdin ()
Definition at line 55270 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 55270 of file pythia-6.4.28.f
References pydat1, pydat3, pygive(), pygram(), pysubs, and pyuedc().
subroutine pyxjet (ECM, NJET, CUT)
Definition at line 79447 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 79447 of file pythia-6.4.28.f
References Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), pyalps(), pydat1, pyerrm(), and pyr().
subroutine pyxkfl (KFL, ECM, ECMC, KFLC)
Definition at line 79373 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 79373 of file pythia-6.4.28.f
References Acts::detail::PhiBoundParameterLimits::max(), ntry, pydat1, pydat2, pyerrm(), pymass(), pyr(), and sign().
subroutine pyxtee (KFL, ECM, XTOT)
Definition at line 79133 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 79133 of file pythia-6.4.28.f
References Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), pyalps(), pydat1, pydat2, pymass(), and sign().
subroutine pyxtot ()
Definition at line 6930 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 6930 of file pythia-6.4.28.f
References eps, eta, i, ValueGen1::i1(), ValueGen1::i2(), j, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, ngen, ngenpd, pari, parp, pydat1, pydat2, pyerrm(), pyint1, pyint5, pyint7, pypars, s, vint, and xsec.
subroutine pyxued (integer NCHN, double precision SIGS)
Definition at line 55603 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 55603 of file pythia-6.4.28.f
References alphas(), i, j, mint, msti, mstp, pari, parp, pi, pyalps(), pydat2, pyint1, pyint3, pypars, pyr(), Acts::InternalSpacePoint< SpacePoint >::sp(), vint, and x.
double precision function pyxxga (double precision C0, double precision XM1, double precision XM2, double precision XMTR, double precision XMTL)
Definition at line 53970 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 53970 of file pythia-6.4.28.f
References f2(), Acts::Logger::log(), and pyxxga().
double precision function pyxxz6 (double precision X)
Definition at line 53831 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 53831 of file pythia-6.4.28.f
References c, i, Acts::Logger::log(), pydat1, pyxxz6(), s, x, and y.
subroutine pyzdis (KFL1, KFL2, PR, Z)
Definition at line 70454 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 70454 of file pythia-6.4.28.f
References fc, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), pydat1, pydat2, pyr(), and z.
subroutine ssmssm (real RDUM1, real RDUM2, real RDUM3, real RDUM4, real RDUM5, real RDUM6, real RDUM7, real RDUM8, real RDUM9, real RDUM10, real RDUM11, real RDUM12, real RDUM13, real RDUM14, real RDUM15, real RDUM16, real RDUM17, real RDUM18, real RDUM19, real RDUM20, real RDUM21, real RDUM22, real RDUM23, real RDUM24, real RDUM25, IDUM1, IDUM2)
Definition at line 81501 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 81501 of file pythia-6.4.28.f
References pydat1, pystop(), and x.
subroutine structmold (double precision XX, double precision QQ, double precision UPV, double precision DNV, double precision USEA, double precision DSEA, double precision STR, double precision CHM, double precision BOT, double precision TOP, double precision GLU)
Definition at line 81368 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 81368 of file pythia-6.4.28.f
References pydat1, pystop(), str, bin_heap< T, Pred >::top(), and x.
subroutine structpold (double precision XX, double precision QQ2, double precision P2, IP2, double precision UPV, double precision DNV, double precision USEA, double precision DSEA, double precision STR, double precision CHM, double precision BOT, double precision TOP, double precision GLU)
Definition at line 81406 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 81406 of file pythia-6.4.28.f
References pydat1, pystop(), str, bin_heap< T, Pred >::top(), and x.
subroutine sugra (real MZERO, real MHLF, real AZERO, real TANB, real SGNMU, real MTOP, integer IMODL)
Definition at line 81446 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 81446 of file pythia-6.4.28.f
References pydat1, pystop(), and x.
subroutine upevnt ()
Definition at line 81172 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 81172 of file pythia-6.4.28.f
References end, i, j, msti, mstp, pari, parp, and pypars.
subroutine upinit ()
Definition at line 81052 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 81052 of file pythia-6.4.28.f
References end, msti, mstp, pari, parp, pypars, and pystop().
subroutine upveto (IVETO)
Definition at line 81303 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 81303 of file pythia-6.4.28.f
References pylist().
character*40 function visaje ()
Definition at line 81472 of file pythia-6.4.28.f.
View newest version in sPHENIX GitHub at line 81472 of file pythia-6.4.28.f
References pydat1, pystop(), visaje(), and x.