Analysis Software: Acts::Intersection< DIM > Struct Template Reference
Acts::Intersection< DIM > Struct Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Utilities/Intersection.hpp>
Public Types
using Position = ActsVector< DIM >
Position type.
using Status = IntersectionStatus
Status enum.
Public Member Functions
constexpr Intersection (const Position &position, double pathLength, Status status)
constexpr operator bool () const
Returns whether the intersection was successful or not.
constexpr const Position & position () const
constexpr ActsScalar pathLength () const
constexpr Status status () const
Static Public Member Functions
static constexpr Intersection invalid ()
static constexpr bool forwardOrder (const Intersection &aIntersection, const Intersection &bIntersection)
static constexpr bool closestOrder (const Intersection &aIntersection, const Intersection &bIntersection)
Private Member Functions
constexpr Intersection ()=default
Private Attributes
Position m_position = Position::Zero()
Position of the intersection.
ActsScalar m_pathLength = std::numeric_limits<double>::infinity()
Signed path length to the intersection (if valid)
Status m_status = Status::unreachable
The Status of the intersection.
Detailed Description
template<unsigned int DIM>
struct Acts::Intersection< DIM >
Intersection struct used for position
Definition at line 45 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 45 of file Intersection.hpp
Member Typedef Documentation
template<unsigned int DIM> using Acts::Intersection< DIM >::Position = ActsVector<DIM>
Position type.
Definition at line 48 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 48 of file Intersection.hpp
template<unsigned int DIM> using Acts::Intersection< DIM >::Status = IntersectionStatus
Status enum.
Definition at line 50 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 50 of file Intersection.hpp
Constructor & Destructor Documentation
template<unsigned int DIM> constexpr Acts::Intersection< DIM >::Intersection (const Position & position, double pathLength, Status status) inline
Constructor with arguments
Parameters
position is the position of the intersection
pathLength is the path length to the intersection
status is an enum indicating the status of the intersection
Definition at line 57 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 57 of file Intersection.hpp
template<unsigned int DIM> constexpr Acts::Intersection< DIM >::Intersection () private default
Referenced by Acts::Intersection< 3 >::invalid().
Member Function Documentation
template<unsigned int DIM> static constexpr bool Acts::Intersection< DIM >::closestOrder (const Intersection< DIM > & aIntersection, const Intersection< DIM > & bIntersection) inline static
Comparison function for closest order i.e. intersection closest to 0 will be first.
Definition at line 85 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 85 of file Intersection.hpp
template<unsigned int DIM> static constexpr bool Acts::Intersection< DIM >::forwardOrder (const Intersection< DIM > & aIntersection, const Intersection< DIM > & bIntersection) inline static
Comparison function for forward order i.e. intersection closest to -inf will be first.
Definition at line 76 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 76 of file Intersection.hpp
template<unsigned int DIM> static constexpr Intersection Acts::Intersection< DIM >::invalid () inline static
Definition at line 72 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 72 of file Intersection.hpp
Referenced by Acts::detail::IntersectionHelper2D::intersectCircleSegment(), Acts::detail::IntersectionHelper2D::intersectEllipse(), and Acts::detail::IntersectionHelper2D::intersectSegment().
template<unsigned int DIM> constexpr Acts::Intersection< DIM >::operator bool () const inline explicit
Returns whether the intersection was successful or not.
Definition at line 62 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 62 of file Intersection.hpp
template<unsigned int DIM> constexpr ActsScalar Acts::Intersection< DIM >::pathLength () const inline
Definition at line 68 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 68 of file Intersection.hpp
Referenced by ActsFatras::PlanarSurfaceMask::annulusMask(), Acts::Intersection< 3 >::closestOrder(), Acts::Intersection< 3 >::forwardOrder(), Acts::ConeSurface::intersect(), Acts::CylinderSurface::intersect(), and Acts::ObjectIntersection< Surface >::pathLength().
template<unsigned int DIM> constexpr const Position& Acts::Intersection< DIM >::position () const inline
Definition at line 66 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 66 of file Intersection.hpp
Referenced by ActsFatras::PlanarSurfaceMask::annulusMask(), Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::boundState(), and Acts::ObjectIntersection< Surface >::position().
template<unsigned int DIM> constexpr Status Acts::Intersection< DIM >::status () const inline
Definition at line 70 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 70 of file Intersection.hpp
Referenced by ActsFatras::PlanarSurfaceMask::annulusMask(), Acts::Intersection< 3 >::closestOrder(), and Acts::ObjectIntersection< Surface >::status().
Member Data Documentation
template<unsigned int DIM> ActsScalar Acts::Intersection< DIM >::m_pathLength = std::numeric_limits<double>::infinity() private
Signed path length to the intersection (if valid)
Definition at line 105 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 105 of file Intersection.hpp
Referenced by Acts::Intersection< 3 >::pathLength().
template<unsigned int DIM> Position Acts::Intersection< DIM >::m_position = Position::Zero() private
Position of the intersection.
Definition at line 103 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 103 of file Intersection.hpp
Referenced by Acts::Intersection< 3 >::position().
template<unsigned int DIM> Status Acts::Intersection< DIM >::m_status = Status::unreachable private
The Status of the intersection.
Definition at line 107 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 107 of file Intersection.hpp
Referenced by Acts::Intersection< 3 >::operator bool(), and Acts::Intersection< 3 >::status().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Utilities/Intersection.hpp