Analysis Software: ClientThread Class Reference
ClientThread Class Reference
Public Member Functions
ClientThread (int number_of_txns, RDBCBench *p)
~ClientThread ()
void Run ()
void Start ()
TTimer * GetThread () const
Private Attributes
Int_t fNtrans
RDBCBench * fParent
TTimer * fThread
Detailed Description
Definition at line 89 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 89 of file RDBCbench.C
Constructor & Destructor Documentation
ClientThread::ClientThread (int number_of_txns, RDBCBench * p)
Definition at line 106 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 106 of file RDBCbench.C
References fNtrans, fParent, fThread, and merge_hashes::p.
ClientThread::~ClientThread () inline
Definition at line 98 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 98 of file RDBCbench.C
Member Function Documentation
TTimer* ClientThread::GetThread () const inline
Definition at line 102 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 102 of file RDBCbench.C
References fThread.
Referenced by RDBCBench::RDBCBench().
void ClientThread::Run ()
Definition at line 117 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 117 of file RDBCbench.C
References physmon_vertexing::delta, RDBCBench::DoOne(), fNtrans, fParent, RDBCBench::GetRandomID(), RDBCBench::GetRandomInt(), kACCOUNT, kBRANCH, kTELLER, RDBCBench::ReportDone(), and transaction_count.
void ClientThread::Start () inline
Definition at line 101 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 101 of file RDBCbench.C
References fThread.
Referenced by RDBCBench::RDBCBench().
Member Data Documentation
Int_t ClientThread::fNtrans private
Definition at line 92 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 92 of file RDBCbench.C
Referenced by ClientThread(), and Run().
RDBCBench* ClientThread::fParent private
Definition at line 93 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 93 of file RDBCbench.C
Referenced by ClientThread(), and Run().
TTimer* ClientThread::fThread private
Definition at line 94 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 94 of file RDBCbench.C
Referenced by ClientThread(), GetThread(), and Start().
The documentation for this class was generated from the following file:
RDBC/blob/master/macros/RDBCbench.C