Analysis Software: Acts::ObjVisualization3D< T > Class Template Reference
Acts::ObjVisualization3D< T > Class Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Visualization/ObjVisualization3D.hpp>
Public Types
using ValueType = T
Stored value type, should be double or float.
using VertexType = ActsVector< ValueType, 3 >
Type of a vertex based on the value type.
using LineType = std::pair< size_t, size_t >
Type of a line.
Public Types inherited from Acts::IVisualization3D
using FaceType = std::vector< size_t >
Public Member Functions
ObjVisualization3D (unsigned int prec=4, double scale=1.)
void vertex (const Vector3D &vtx, ColorRGB color={0, 0, 0}) final
void line (const Vector3D &a, const Vector3D &b, ColorRGB color={0, 0, 0}) final
void face (const std::vector< Vector3D > &vtxs, ColorRGB color={0, 0, 0}) final
void faces (const std::vector< Vector3D > &vtxs, const std::vector< FaceType > &faces, ColorRGB color={0, 0, 0}) final
void write (const std::string &path) const final
void write (std::ostream &os) const final
void write (std::ostream &os, std::ostream &mos) const
void clear () final
Public Member Functions inherited from Acts::IVisualization3D
void vertex (const Vector3F &vtx, ColorRGB color={120, 120, 120})
void face (const std::vector< Vector3F > &vtxs, ColorRGB color={120, 120, 120})
void line (const Vector3F &a, const Vector3F &b, ColorRGB color={120, 120, 120})
(const Vector3F&, const Vector3F&,
Private Attributes
unsigned int m_outputPrecision = 4
The output parameters.
double m_outputScalor = 1.
std::vector< VertexType > m_vertices
The object data to be written.
std::vector< FaceType > m_faces
std::vector< LineType > m_lines
std::map< size_t, ColorRGB > m_lineColors
Map of colors to be written at given index position.
std::map< size_t, ColorRGB > m_vertexColors
std::map< size_t, ColorRGB > m_faceColors
Additional Inherited Members
Protected Member Functions inherited from Acts::IVisualization3D
bool hasExtension (const std::string &path) const
void replaceExtension (std::string &path, const std::string &suffix) const
Detailed Description
template<typename T = double>
class Acts::ObjVisualization3D< T >
This helper produces output in the OBJ format. Note that colors are not supported in this implementation.
Definition at line 29 of file ObjVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 29 of file ObjVisualization3D.hpp
Member Typedef Documentation
template<typename T = double> using Acts::ObjVisualization3D< T >::LineType = std::pair<size_t, size_t>
Type of a line.
Definition at line 41 of file ObjVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 41 of file ObjVisualization3D.hpp
template<typename T = double> using Acts::ObjVisualization3D< T >::ValueType = T
Stored value type, should be double or float.
Definition at line 35 of file ObjVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 35 of file ObjVisualization3D.hpp
template<typename T = double> using Acts::ObjVisualization3D< T >::VertexType = ActsVector<ValueType, 3>
Type of a vertex based on the value type.
Definition at line 38 of file ObjVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 38 of file ObjVisualization3D.hpp
Constructor & Destructor Documentation
template<typename T = double> Acts::ObjVisualization3D< T >::ObjVisualization3D (unsigned int prec = 4, double scale = 1.) inline
Constructor that allows to set scalor and precision
Parameters
prec The output precission with std::setprecision
scale An (optional) scaling for the writing out
Definition at line 46 of file ObjVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 46 of file ObjVisualization3D.hpp
Member Function Documentation
template<typename T > void Acts::ObjVisualization3D< T >::clear () final virtual
Remove all contents of this helper
Implements Acts::IVisualization3D.
Definition at line 169 of file ObjVisualization3D.ipp.
View newest version in sPHENIX GitHub at line 169 of file ObjVisualization3D.ipp
References Acts::ObjVisualization3D< T >::clear().
Referenced by Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::ObjVisualization3D< T >::clear().
template<typename T > void Acts::ObjVisualization3D< T >::face (const std::vector< Vector3D > & vtxs, ColorRGB color = {0, 0, 0}) final virtual
Draw a face that connects a list of vertices.
Note
Depending on the helper implementation, out of plane vertices might be handled differently.
Parameters
vtxs The vertices that make up the face
color The color of the face
Implements Acts::IVisualization3D.
Definition at line 28 of file ObjVisualization3D.ipp.
View newest version in sPHENIX GitHub at line 28 of file ObjVisualization3D.ipp
References color, and testing::internal::move().
template<typename T > void Acts::ObjVisualization3D< T >::faces (const std::vector< Vector3D > & vtxs, const std::vector< FaceType > & faces, ColorRGB color = {0, 0, 0}) final virtual
Draw a faces that connects a list of vertices - expert only
Note
Depending on the helper implementation, out of plane vertices might be handled differently.
Parameters
vtxs The vertices that make up the faceS
faces The face presectiotions (i.e. connecting vertices)
color The color of the face
Implements Acts::IVisualization3D.
Definition at line 43 of file ObjVisualization3D.ipp.
View newest version in sPHENIX GitHub at line 43 of file ObjVisualization3D.ipp
References color, and Acts::Test::transform.
template<typename T > void Acts::ObjVisualization3D< T >::line (const Vector3D & a, const Vector3D & b, ColorRGB color = {0, 0, 0}) final virtual
Draw a line from a vertex to another
Parameters
a The start vertex
b The end vertex
color The color of the line
Implements Acts::IVisualization3D.
Definition at line 16 of file ObjVisualization3D.ipp.
View newest version in sPHENIX GitHub at line 16 of file ObjVisualization3D.ipp
References color.
template<typename T > void Acts::ObjVisualization3D< T >::vertex (const Vector3D & vtx, ColorRGB color = {0, 0, 0}) final virtual
Draw a vertex at a given location and a color.
Parameters
vtx The vertex position
color The color
Implements Acts::IVisualization3D.
Definition at line 10 of file ObjVisualization3D.ipp.
View newest version in sPHENIX GitHub at line 10 of file ObjVisualization3D.ipp
References color.
template<typename T > void Acts::ObjVisualization3D< T >::write (const std::string & path) const final virtual
Write the content of the helper to an outstream.
Parameters
os The output stream for file
Implements Acts::IVisualization3D.
Definition at line 73 of file ObjVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 73 of file ObjVisualization3D.hpp
Referenced by Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::Test::BOOST_FIXTURE_TEST_CASE().
template<typename T > void Acts::ObjVisualization3D< T >::write (std::ostream & os) const final virtual
Write the content of the helper to an outstream.
Parameters
os The output stream for file
Implements Acts::IVisualization3D.
Definition at line 91 of file ObjVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 91 of file ObjVisualization3D.hpp
template<typename T > void Acts::ObjVisualization3D< T >::write (std::ostream & os, std::ostream & mos) const
Write the object and the material file
Parameters
os the output stream for the object
mos the output stream for the auxiliary material file
Definition at line 97 of file ObjVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 97 of file ObjVisualization3D.hpp
Member Data Documentation
template<typename T = double> std::map<size_t, ColorRGB> Acts::ObjVisualization3D< T >::m_faceColors private
Definition at line 90 of file ObjVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 90 of file ObjVisualization3D.hpp
template<typename T = double> std::vector<FaceType> Acts::ObjVisualization3D< T >::m_faces private
Definition at line 85 of file ObjVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 85 of file ObjVisualization3D.hpp
template<typename T = double> std::map<size_t, ColorRGB> Acts::ObjVisualization3D< T >::m_lineColors private
Map of colors to be written at given index position.
Definition at line 88 of file ObjVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 88 of file ObjVisualization3D.hpp
template<typename T = double> std::vector<LineType> Acts::ObjVisualization3D< T >::m_lines private
Definition at line 86 of file ObjVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 86 of file ObjVisualization3D.hpp
template<typename T = double> unsigned int Acts::ObjVisualization3D< T >::m_outputPrecision = 4 private
The output parameters.
Definition at line 81 of file ObjVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 81 of file ObjVisualization3D.hpp
template<typename T = double> double Acts::ObjVisualization3D< T >::m_outputScalor = 1. private
Definition at line 82 of file ObjVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 82 of file ObjVisualization3D.hpp
template<typename T = double> std::map<size_t, ColorRGB> Acts::ObjVisualization3D< T >::m_vertexColors private
Definition at line 89 of file ObjVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 89 of file ObjVisualization3D.hpp
template<typename T = double> std::vector<VertexType> Acts::ObjVisualization3D< T >::m_vertices private
The object data to be written.
Definition at line 84 of file ObjVisualization3D.hpp.
View newest version in sPHENIX GitHub at line 84 of file ObjVisualization3D.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Visualization/ObjVisualization3D.hpp
acts/blob/sPHENIX/Core/include/Acts/Visualization/detail/ObjVisualization3D.ipp