Analysis Software: oncsSub_idgl1v0 Class Reference
oncsSub_idgl1v0 Class Reference
#include <online_distribution/blob/master/newbasic/oncsSub_idgl1v0.h>
Public Member Functions
oncsSub_idgl1v0 (subevtdata_ptr)
int iValue (const int dummy)
iValue returns the value of a given channel as an int.
long long lValue (const int hit, const char *what)
long long lValue (const int channel, const int iy)
void dump (OSTREAM &os=COUT)
Public Member Functions inherited from oncsSubevent_w4
oncsSubevent_w4 (subevtdata_ptr)
virtual void gdump (const int how=EVT_HEXADECIMAL, OSTREAM &os=COUT) const
Public Member Functions inherited from oncsSubevent
oncsSubevent (subevtdata_ptr data)
virtual ~oncsSubevent ()
virtual int getLength () const
virtual int getIdentifier () const
get the packet identifier
virtual int getHitFormat () const
get the hit format; in case of unformatted get the encoding scheme.
virtual int getPadding () const
get the number of padding units in the packet data.
virtual int getDataLength () const
get what the name says...
virtual int getStructure () const
get the structure of the packet data; unformatted, hitlist, etc.
virtual int getDebugLength () const
get the length of the debug block
virtual int getErrorLength () const
virtual void identify (OSTREAM &=COUT) const
virtual int setIdentifier (const int newid)
set a new packet identifier
int iValue (const int)
iValue returns the value of a given channel as an int.
int iValue (const int, const char *)
int iValue (const int, const int)
int iValue (const int, const int, const char *)
int iValue (const int channel, const int iy, const int iz)
int iValue (const int channel, const int iy, const int iz, const char *what)
virtual float rValue (const int)
virtual float rValue (const int, const char *)
virtual float rValue (const int, const int)
virtual int getArraylength (const char *)
virtual int fillIntArray (int[], const int, int *, const char *what="")
virtual int fillFloatArray (float[], const int, int *, const char *what="")
fillFloatArray fills an array of floats
virtual int * getIntArray (int *, const char *what="")
virtual float * getFloatArray (int *, const char *what="")
getFloatArray creates and returns an array of floats
virtual int is_pointer_type () const
find out what type (pointer- or data based) packet object we have
virtual int convert ()
convert from pointer- to data based object, if it is already data-based, do nothing.
virtual int copyMe (int[], const int maxlength) const
int setInternalParameter (const int p1=0, const int p2=0, const char *what="")
Public Member Functions inherited from Packet
virtual ~Packet ()
the virtual destructor
virtual double dValue (const int channel)
virtual double dValue (const int channel, const char *what)
virtual double dValue (const int channel, const int iy)
virtual long long lValue (const int channel)
virtual long long lValue (const int channel, const int iy, const char *what)
virtual void * pValue (const int)
virtual void * pValue (const int, const char *)
virtual void * pValue (const int, const int)
virtual void identify (std::ostream &os=std::cout) const =0
see below for comments
virtual void fullIdentify (std::ostream &os=std::cout) const
write an indepth identification message to the supplied OSTREAM.
virtual void dump (std::ostream &os=std::cout)=0
virtual void gdump (const int how=EVT_HEXADECIMAL, std::ostream &os=std::cout) const =0
virtual int getCheckSumStatus () const
Protected Member Functions
int decode ()
Protected Member Functions inherited from oncsSubevent_w4
virtual int * decode (int *)
Protected Attributes
int is_decoded
unsigned long long BCO
unsigned long long BunchNumber
unsigned long long TriggerInput
unsigned long long TriggerVector
unsigned int packet_nr
unsigned long long scalers [3 *64]
Detailed Description
Definition at line 7 of file oncsSub_idgl1v0.h.
View newest version in sPHENIX GitHub at line 7 of file oncsSub_idgl1v0.h
Constructor & Destructor Documentation
oncsSub_idgl1v0::oncsSub_idgl1v0 (subevtdata_ptr data)
Definition at line 7 of file oncsSub_idgl1v0.cc.
View newest version in sPHENIX GitHub at line 7 of file oncsSub_idgl1v0.cc
References BCO, is_decoded, packet_nr, and scalers.
Member Function Documentation
int oncsSub_idgl1v0::decode () protected
Definition at line 19 of file oncsSub_idgl1v0.cc.
View newest version in sPHENIX GitHub at line 19 of file oncsSub_idgl1v0.cc
References BCO, BunchNumber, subevt_data::data, i, index, is_decoded, j, packet_nr, physmon_simulation::s, scalers, oncsSubevent::SubeventHdr, TriggerInput, and TriggerVector.
Referenced by iValue(), and lValue().
void oncsSub_idgl1v0::dump (OSTREAM & os = COUT) virtual
Reimplemented from oncsSubevent_w4.
Definition at line 196 of file oncsSub_idgl1v0.cc.
View newest version in sPHENIX GitHub at line 196 of file oncsSub_idgl1v0.cc
References i, oncsSubevent::identify(), iValue(), and lValue().
int oncsSub_idgl1v0::iValue (const int) virtual
iValue returns the value of a given channel as an int.
Implements Packet.
Definition at line 137 of file oncsSub_idgl1v0.cc.
View newest version in sPHENIX GitHub at line 137 of file oncsSub_idgl1v0.cc
References decode(), and packet_nr.
Referenced by dump().
long long oncsSub_idgl1v0::lValue (const int hit, const char * what) virtual
Reimplemented from Packet.
Definition at line 150 of file oncsSub_idgl1v0.cc.
View newest version in sPHENIX GitHub at line 150 of file oncsSub_idgl1v0.cc
References BCO, BunchNumber, decode(), TriggerInput, and TriggerVector.
Referenced by dump().
long long oncsSub_idgl1v0::lValue (const int channel, const int iy) virtual
Reimplemented from Packet.
Definition at line 143 of file oncsSub_idgl1v0.cc.
View newest version in sPHENIX GitHub at line 143 of file oncsSub_idgl1v0.cc
References decode(), k, and scalers.
Member Data Documentation
unsigned long long oncsSub_idgl1v0::BCO protected
Definition at line 30 of file oncsSub_idgl1v0.h.
View newest version in sPHENIX GitHub at line 30 of file oncsSub_idgl1v0.h
Referenced by decode(), lValue(), and oncsSub_idgl1v0().
unsigned long long oncsSub_idgl1v0::BunchNumber protected
Definition at line 31 of file oncsSub_idgl1v0.h.
View newest version in sPHENIX GitHub at line 31 of file oncsSub_idgl1v0.h
Referenced by decode(), and lValue().
int oncsSub_idgl1v0::is_decoded protected
Definition at line 28 of file oncsSub_idgl1v0.h.
View newest version in sPHENIX GitHub at line 28 of file oncsSub_idgl1v0.h
Referenced by decode(), and oncsSub_idgl1v0().
unsigned int oncsSub_idgl1v0::packet_nr protected
Definition at line 35 of file oncsSub_idgl1v0.h.
View newest version in sPHENIX GitHub at line 35 of file oncsSub_idgl1v0.h
Referenced by decode(), iValue(), and oncsSub_idgl1v0().
unsigned long long oncsSub_idgl1v0::scalers[3 *64] protected
Definition at line 37 of file oncsSub_idgl1v0.h.
View newest version in sPHENIX GitHub at line 37 of file oncsSub_idgl1v0.h
Referenced by decode(), lValue(), and oncsSub_idgl1v0().
unsigned long long oncsSub_idgl1v0::TriggerInput protected
Definition at line 32 of file oncsSub_idgl1v0.h.
View newest version in sPHENIX GitHub at line 32 of file oncsSub_idgl1v0.h
Referenced by decode(), and lValue().
unsigned long long oncsSub_idgl1v0::TriggerVector protected
Definition at line 33 of file oncsSub_idgl1v0.h.
View newest version in sPHENIX GitHub at line 33 of file oncsSub_idgl1v0.h
Referenced by decode(), and lValue().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/oncsSub_idgl1v0.h
online_distribution/blob/master/newbasic/oncsSub_idgl1v0.cc