Analysis Software: ActsExamples::Geant4::HepMC3::SteppingAction Class Reference
ActsExamples::Geant4::HepMC3::SteppingAction Class Reference
Collects the particles history.
#include <acts/blob/sPHENIX/Examples/Algorithms/Geant4HepMC/src/SteppingAction.hpp>
Public Member Functions
SteppingAction (std::vector< std::string > eventRejectionProcess)
~SteppingAction () override
void UserSteppingAction (const G4Step *step) override
Interface Method doing the step and records the data.
void clear ()
Interface reset method.
bool eventAborted ()
Return the abort status.
Static Public Member Functions
static SteppingAction * instance ()
Static access method to the instance.
Private Attributes
std::shared_ptr
<::HepMC3::GenVertex > m_previousVertex = nullptr
The end vertex of the previous step.
std::vector< std::string > m_eventRejectionProcess
List to veto events with certain processes.
bool m_eventAborted = false
States whether an event was aborted.
Static Private Attributes
static SteppingAction * s_instance = nullptr
Instance of the SteppingAction.
Detailed Description
Collects the particles history.
Definition at line 21 of file SteppingAction.hpp.
View newest version in sPHENIX GitHub at line 21 of file SteppingAction.hpp
Constructor & Destructor Documentation
ActsExamples::Geant4::HepMC3::SteppingAction::SteppingAction (std::vector< std::string > eventRejectionProcess)
Definition at line 30 of file SteppingAction.cpp.
View newest version in sPHENIX GitHub at line 30 of file SteppingAction.cpp
References s_instance.
ActsExamples::Geant4::HepMC3::SteppingAction::~SteppingAction () override
Definition at line 40 of file SteppingAction.cpp.
View newest version in sPHENIX GitHub at line 40 of file SteppingAction.cpp
References s_instance.
Member Function Documentation
void ActsExamples::Geant4::HepMC3::SteppingAction::clear ()
Interface reset method.
Definition at line 170 of file SteppingAction.cpp.
View newest version in sPHENIX GitHub at line 170 of file SteppingAction.cpp
References m_eventAborted, and m_previousVertex.
Referenced by ActsExamples::Geant4::HepMC3::EventAction::BeginOfEventAction(), and ActsExamples::Geant4::HepMC3::EventAction::clear().
bool ActsExamples::Geant4::HepMC3::SteppingAction::eventAborted () inline
Return the abort status.
Definition at line 37 of file SteppingAction.hpp.
View newest version in sPHENIX GitHub at line 37 of file SteppingAction.hpp
References m_eventAborted.
SteppingAction * ActsExamples::Geant4::HepMC3::SteppingAction::instance () static
Static access method to the instance.
Definition at line 25 of file SteppingAction.cpp.
View newest version in sPHENIX GitHub at line 25 of file SteppingAction.cpp
References s_instance.
Referenced by ActsExamples::Geant4::HepMC3::EventAction::BeginOfEventAction(), ActsExamples::Geant4::HepMC3::EventAction::clear(), and ActsExamples::EventRecording::execute().
void ActsExamples::Geant4::HepMC3::SteppingAction::UserSteppingAction (const G4Step * step) override
Interface Method doing the step and records the data.
Parameters
step is the Geant4 step of the particle
Store the step such that a vertex knows the position and upcoming process for a particle. The particle properties are stored as ingoing before and as outgoing after the step with the process was performed. Therefore the vertex defines the starting point of a process while the next vertex describes the state after the process, including all particles produced along the step. In total the entire event is represented by vertices which describe each step in Geant4.
Definition at line 44 of file SteppingAction.cpp.
View newest version in sPHENIX GitHub at line 44 of file SteppingAction.cpp
References event, ActsExamples::Geant4::HepMC3::EventAction::event(), Acts::UnitConstants::GeV, ActsExamples::Geant4::HepMC3::EventAction::instance(), m_eventAborted, m_eventRejectionProcess, m_previousVertex, Acts::UnitConstants::mm, tgeo-response2json::process(), physmon_simulation::s, to_string(), and X0.
Member Data Documentation
bool ActsExamples::Geant4::HepMC3::SteppingAction::m_eventAborted = false private
States whether an event was aborted.
Definition at line 47 of file SteppingAction.hpp.
View newest version in sPHENIX GitHub at line 47 of file SteppingAction.hpp
Referenced by clear(), eventAborted(), and UserSteppingAction().
std::vector<std::string> ActsExamples::Geant4::HepMC3::SteppingAction::m_eventRejectionProcess private
List to veto events with certain processes.
Definition at line 45 of file SteppingAction.hpp.
View newest version in sPHENIX GitHub at line 45 of file SteppingAction.hpp
Referenced by UserSteppingAction().
std::shared_ptr<::HepMC3::GenVertex> ActsExamples::Geant4::HepMC3::SteppingAction::m_previousVertex = nullptr private
The end vertex of the previous step.
Definition at line 43 of file SteppingAction.hpp.
View newest version in sPHENIX GitHub at line 43 of file SteppingAction.hpp
Referenced by clear(), and UserSteppingAction().
SteppingAction * ActsExamples::Geant4::HepMC3::SteppingAction::s_instance = nullptr static private
Instance of the SteppingAction.
Definition at line 41 of file SteppingAction.hpp.
View newest version in sPHENIX GitHub at line 41 of file SteppingAction.hpp
Referenced by instance(), SteppingAction(), and ~SteppingAction().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Geant4HepMC/src/SteppingAction.hpp
acts/blob/sPHENIX/Examples/Algorithms/Geant4HepMC/src/SteppingAction.cpp