Analysis Software: ActsExamples::VertexFitterAlgorithm Exception Reference
ActsExamples::VertexFitterAlgorithm Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/Vertexing/include/ActsExamples/Vertexing/VertexFitterAlgorithm.hpp>
Classes
struct Config
Public Types
using Propagator = Acts::Propagator< Acts::EigenStepper<>>
using PropagatorOptions = Acts::PropagatorOptions<>
using Linearizer = Acts::HelicalTrackLinearizer< Propagator >
using VertexFitter = Acts::FullBilloirVertexFitter< Acts::BoundTrackParameters, Linearizer >
using VertexFitterOptions = Acts::VertexingOptions< Acts::BoundTrackParameters >
using VertexCollection = std::vector< Acts::Vertex< Acts::BoundTrackParameters >>
Public Member Functions
VertexFitterAlgorithm (const Config &cfg, Acts::Logging::Level lvl)
ProcessCode execute (const AlgorithmContext &ctx) const final
const Config & config () const
Get readonly access to the config parameters.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
ReadDataHandle< std::vector
< Acts::BoundTrackParameters > > m_inputTrackParameters {this, "InputTrackParameters"}
ReadDataHandle
< TrajectoriesContainer > m_inputTrajectories
ReadDataHandle
< ProtoVertexContainer > m_inputProtoVertices
WriteDataHandle< VertexCollection > m_outputVertices {this, "OutputVertices"}
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Definition at line 46 of file VertexFitterAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 46 of file VertexFitterAlgorithm.hpp
Member Typedef Documentation
using ActsExamples::VertexFitterAlgorithm::Linearizer = Acts::HelicalTrackLinearizer<Propagator>
Definition at line 50 of file VertexFitterAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 50 of file VertexFitterAlgorithm.hpp
using ActsExamples::VertexFitterAlgorithm::Propagator = Acts::Propagator<Acts::EigenStepper<>>
Definition at line 48 of file VertexFitterAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 48 of file VertexFitterAlgorithm.hpp
using ActsExamples::VertexFitterAlgorithm::PropagatorOptions = Acts::PropagatorOptions<>
Definition at line 49 of file VertexFitterAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 49 of file VertexFitterAlgorithm.hpp
using ActsExamples::VertexFitterAlgorithm::VertexCollection = std::vector<Acts::Vertex<Acts::BoundTrackParameters>>
Definition at line 57 of file VertexFitterAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 57 of file VertexFitterAlgorithm.hpp
using ActsExamples::VertexFitterAlgorithm::VertexFitter = Acts::FullBilloirVertexFitter<Acts::BoundTrackParameters, Linearizer>
Definition at line 52 of file VertexFitterAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 52 of file VertexFitterAlgorithm.hpp
using ActsExamples::VertexFitterAlgorithm::VertexFitterOptions = Acts::VertexingOptions<Acts::BoundTrackParameters>
Definition at line 54 of file VertexFitterAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 54 of file VertexFitterAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::VertexFitterAlgorithm::VertexFitterAlgorithm (const Config & cfg, Acts::Logging::Level lvl)
Definition at line 26 of file VertexFitterAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 26 of file VertexFitterAlgorithm.cpp
References ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::VertexFitterAlgorithm::Config::inputProtoVertices, ActsExamples::VertexFitterAlgorithm::Config::inputTrackParameters, ActsExamples::VertexFitterAlgorithm::Config::inputTrajectories, m_cfg, m_inputProtoVertices, m_inputTrackParameters, m_inputTrajectories, m_outputVertices, ActsExamples::DataHandleBase::maybeInitialize(), and ActsExamples::VertexFitterAlgorithm::Config::outputVertices.
Member Function Documentation
const Config& ActsExamples::VertexFitterAlgorithm::config () const inline
Get readonly access to the config parameters.
Definition at line 92 of file VertexFitterAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 92 of file VertexFitterAlgorithm.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::VertexFitterAlgorithm::execute (const AlgorithmContext & ctx) const final virtual
Fit the input vertices.
Parameters
ctx is the algorithm context with event information
Returns
a process code indication success or failure
Implements ActsExamples::IAlgorithm.
Definition at line 44 of file VertexFitterAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 44 of file VertexFitterAlgorithm.cpp
References ACTS_DEBUG, ACTS_ERROR, ACTS_INFO, ACTS_VERBOSE, Acts::Logger::cloneWithSuffix(), Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::fit(), ActsExamples::AlgorithmContext::geoContext, logger(), m_cfg(), ActsExamples::AlgorithmContext::magFieldContext, ActsExamples::makeParameterContainers(), testing::internal::move(), Acts::Vertex< input_track_t >::setFullCovariance(), Acts::Vertex< input_track_t >::setFullPosition(), filter::state, propagation_timing::stepper, and SUCCESS.
Member Data Documentation
Config ActsExamples::VertexFitterAlgorithm::m_cfg private
Definition at line 95 of file VertexFitterAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 95 of file VertexFitterAlgorithm.hpp
Referenced by config(), and VertexFitterAlgorithm().
ReadDataHandle<ProtoVertexContainer> ActsExamples::VertexFitterAlgorithm::m_inputProtoVertices private
Initial value:
{
      this, "InputProtoVertices"}
Definition at line 103 of file VertexFitterAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 103 of file VertexFitterAlgorithm.hpp
Referenced by VertexFitterAlgorithm().
ReadDataHandle<std::vector<Acts::BoundTrackParameters> > ActsExamples::VertexFitterAlgorithm::m_inputTrackParameters {this, "InputTrackParameters"} private
Definition at line 98 of file VertexFitterAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 98 of file VertexFitterAlgorithm.hpp
Referenced by VertexFitterAlgorithm().
ReadDataHandle<TrajectoriesContainer> ActsExamples::VertexFitterAlgorithm::m_inputTrajectories private
Initial value:
{
      this, "InputTrajectories"}
Definition at line 100 of file VertexFitterAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 100 of file VertexFitterAlgorithm.hpp
Referenced by VertexFitterAlgorithm().
WriteDataHandle<VertexCollection> ActsExamples::VertexFitterAlgorithm::m_outputVertices {this, "OutputVertices"} private
Definition at line 106 of file VertexFitterAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 106 of file VertexFitterAlgorithm.hpp
Referenced by VertexFitterAlgorithm().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Vertexing/include/ActsExamples/Vertexing/VertexFitterAlgorithm.hpp
acts/blob/sPHENIX/Examples/Algorithms/Vertexing/src/VertexFitterAlgorithm.cpp