Analysis Software: Acts::TGeoCylinderDiscSplitter Class Reference
Acts::TGeoCylinderDiscSplitter Class Reference
TGeoCylinderDiscSplitter.
#include <acts/blob/sPHENIX/Plugins/TGeo/include/Acts/Plugins/TGeo/TGeoCylinderDiscSplitter.hpp>
Classes
struct Config
Nested configuration struct.
Public Member Functions
TGeoCylinderDiscSplitter (const Config &cfg, std::unique_ptr< const Acts::Logger > logger=Acts::getDefaultLogger("TGeoCylinderDiscSplitter", Acts::Logging::INFO))
~TGeoCylinderDiscSplitter () override=default
std::vector< std::shared_ptr
< const
Acts::TGeoDetectorElement > > split (const GeometryContext &gctx, std::shared_ptr< const Acts::TGeoDetectorElement > tgde) const override
Public Member Functions inherited from Acts::ITGeoDetectorElementSplitter
virtual ~ITGeoDetectorElementSplitter ()=default
Private Member Functions
const Acts::Logger & logger () const
Private access to the logger.
Private Attributes
Config m_cfg
std::unique_ptr< const
Acts::Logger > m_logger
Logging instance.
Detailed Description
TGeoCylinderDiscSplitter.
Split Cylinder and disks into submodules
Definition at line 27 of file TGeoCylinderDiscSplitter.hpp.
View newest version in sPHENIX GitHub at line 27 of file TGeoCylinderDiscSplitter.hpp
Constructor & Destructor Documentation
Acts::TGeoCylinderDiscSplitter::TGeoCylinderDiscSplitter (const Config & cfg, std::unique_ptr< const Acts::Logger > logger = Acts::getDefaultLogger("TGeoCylinderDiscSplitter", Acts::Logging::INFO))
Constructor
Parameters
cfg the configuration struct
logger the logging object
Definition at line 24 of file TGeoCylinderDiscSplitter.cpp.
View newest version in sPHENIX GitHub at line 24 of file TGeoCylinderDiscSplitter.cpp
Acts::TGeoCylinderDiscSplitter::~TGeoCylinderDiscSplitter () override default
Member Function Documentation
const Acts::Logger& Acts::TGeoCylinderDiscSplitter::logger () const inline private
Private access to the logger.
Definition at line 69 of file TGeoCylinderDiscSplitter.hpp.
View newest version in sPHENIX GitHub at line 69 of file TGeoCylinderDiscSplitter.hpp
References m_logger.
std::vector< std::shared_ptr< const Acts::TGeoDetectorElement > > Acts::TGeoCylinderDiscSplitter::split (const GeometryContext & gctx, std::shared_ptr< const Acts::TGeoDetectorElement > tgde) const override virtual
Take a geometry context and TGeoElement and split it into sub elements
Parameters
gctx is a geometry context object
tgde is a TGeoDetectorElement that is eventually split
Note
If no split is performed the unsplit detector element is returned
Returns
a vector of TGeoDetectorElement objects
Implements Acts::ITGeoDetectorElementSplitter.
Definition at line 30 of file TGeoCylinderDiscSplitter.cpp.
View newest version in sPHENIX GitHub at line 30 of file TGeoCylinderDiscSplitter.cpp
References ACTS_DEBUG, Acts::Surface::bounds(), Acts::Surface::center(), Acts::Surface::Cylinder, Acts::Surface::Disc, Acts::SurfaceBounds::eCylinder, Acts::SurfaceBounds::eDisc, Acts::CylinderBounds::eHalfLengthZ, Acts::RadialBounds::eMaxR, Acts::RadialBounds::eMinR, Acts::CylinderBounds::eR, m_cfg(), maxR, maxZ, minR, ActsTests::PropagationDatasets::phi, Acts::SurfaceBounds::type(), Acts::Surface::type(), and Acts::SurfaceBounds::values().
Member Data Documentation
Config Acts::TGeoCylinderDiscSplitter::m_cfg private
Definition at line 66 of file TGeoCylinderDiscSplitter.hpp.
View newest version in sPHENIX GitHub at line 66 of file TGeoCylinderDiscSplitter.hpp
std::unique_ptr<const Acts::Logger> Acts::TGeoCylinderDiscSplitter::m_logger private
Logging instance.
Definition at line 72 of file TGeoCylinderDiscSplitter.hpp.
View newest version in sPHENIX GitHub at line 72 of file TGeoCylinderDiscSplitter.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Plugins/TGeo/include/Acts/Plugins/TGeo/TGeoCylinderDiscSplitter.hpp
acts/blob/sPHENIX/Plugins/TGeo/src/TGeoCylinderDiscSplitter.cpp