Analysis Software: ActsExamples::TGeoDetector Struct Reference
ActsExamples::TGeoDetector Struct Reference
#include <acts/blob/sPHENIX/Examples/Detectors/TGeoDetector/include/ActsExamples/TGeoDetector/TGeoDetector.hpp>
Classes
struct Config
Public Types
using DetectorElementPtr = std::shared_ptr< const Acts::TGeoDetectorElement >
using DetectorStore = std::vector< DetectorElementPtr >
using ContextDecorators = std::vector< std::shared_ptr< ActsExamples::IContextDecorator >>
using TrackingGeometryPtr = std::shared_ptr< const Acts::TrackingGeometry >
Public Member Functions
std::pair< TrackingGeometryPtr,
ContextDecorators > finalize (const Config &cfg, std::shared_ptr< const Acts::IMaterialDecorator > mdecorator)
Static Public Member Functions
static void readTGeoLayerBuilderConfigsFile (const std::string &path, Config &config)
Read the TGeo layer builder configurations from the user configuration.
Public Attributes
DetectorStore detectorStore
The Store of the detector elements (lifetime: job)
Detailed Description
Definition at line 37 of file TGeoDetector.hpp.
View newest version in sPHENIX GitHub at line 37 of file TGeoDetector.hpp
Member Typedef Documentation
using ActsExamples::TGeoDetector::ContextDecorators = std::vector<std::shared_ptr<ActsExamples::IContextDecorator>>
Definition at line 42 of file TGeoDetector.hpp.
View newest version in sPHENIX GitHub at line 42 of file TGeoDetector.hpp
using ActsExamples::TGeoDetector::DetectorElementPtr = std::shared_ptr<const Acts::TGeoDetectorElement>
Definition at line 38 of file TGeoDetector.hpp.
View newest version in sPHENIX GitHub at line 38 of file TGeoDetector.hpp
using ActsExamples::TGeoDetector::DetectorStore = std::vector<DetectorElementPtr>
Definition at line 39 of file TGeoDetector.hpp.
View newest version in sPHENIX GitHub at line 39 of file TGeoDetector.hpp
using ActsExamples::TGeoDetector::TrackingGeometryPtr = std::shared_ptr<const Acts::TrackingGeometry>
Definition at line 43 of file TGeoDetector.hpp.
View newest version in sPHENIX GitHub at line 43 of file TGeoDetector.hpp
Member Function Documentation
auto ActsExamples::TGeoDetector::finalize (const Config & cfg, std::shared_ptr< const Acts::IMaterialDecorator > mdecorator)
Definition at line 368 of file TGeoDetector.cpp.
View newest version in sPHENIX GitHub at line 368 of file TGeoDetector.cpp
References cfg, Acts::getDefaultLogger(), Acts::Logging::INFO, and testing::internal::move().
Referenced by Acts::Python::addDetector(), and MakeActsGeometry::build().
void ActsExamples::TGeoDetector::readTGeoLayerBuilderConfigsFile (const std::string & path, Config & config) static
Read the TGeo layer builder configurations from the user configuration.
Definition at line 341 of file TGeoDetector.cpp.
View newest version in sPHENIX GitHub at line 341 of file TGeoDetector.cpp
References ActsExamples::TGeoDetector::Config::beamPipeHalflengthZ, ActsExamples::TGeoDetector::Config::beamPipeLayerThickness, ActsExamples::TGeoDetector::Config::beamPipeRadius, ActsExamples::TGeoDetector::Config::buildBeamPipe, in, infile, ActsExamples::TGeoDetector::Config::unitScalor, and ActsExamples::TGeoDetector::Config::volumes.
Member Data Documentation
DetectorStore ActsExamples::TGeoDetector::detectorStore
The Store of the detector elements (lifetime: job)
Definition at line 46 of file TGeoDetector.hpp.
View newest version in sPHENIX GitHub at line 46 of file TGeoDetector.hpp
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Examples/Detectors/TGeoDetector/include/ActsExamples/TGeoDetector/TGeoDetector.hpp
acts/blob/sPHENIX/Examples/Detectors/TGeoDetector/src/TGeoDetector.cpp