Analysis Software: ActsExamples::IReader Class Reference
ActsExamples::IReader Class Reference abstract
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Framework/IReader.hpp>
Public Member Functions
virtual std::pair< size_t, size_t > availableEvents () const =0
virtual ProcessCode read (const AlgorithmContext &context)=0
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Fulfill the algorithm interface.
ProcessCode finalize () override
Fulfill the algorithm interface.
Public Member Functions inherited from ActsExamples::SequenceElement
virtual ~SequenceElement ()=default
virtual std::string name () const =0
The algorithm name.
const std::vector< const
DataHandleBase * > & writeHandles () const
const std::vector< const
DataHandleBase * > & readHandles () const
Detailed Description
Event data reader interface.
Read data from disk and add it to the event store. The reader can have internal state and implementations are responsible to handle concurrent calls.
Definition at line 25 of file IReader.hpp.
View newest version in sPHENIX GitHub at line 25 of file IReader.hpp
Member Function Documentation
virtual std::pair<size_t, size_t> ActsExamples::IReader::availableEvents () const pure virtual
Provide range of available events or [0, SIZE_MAX) if undefined.
The upper limit is exclusive, i.e. [0,3) means events 0, 1, and 2.
Implemented in ActsExamples::RootAthenaNTupleReader, ActsExamples::EventGenerator, ActsExamples::CsvMeasurementReader, ActsExamples::CsvPlanarClusterReader, ActsExamples::RootMaterialTrackReader, ActsExamples::RootTrajectorySummaryReader, ActsExamples::CsvSpacePointReader, ActsExamples::RootParticleReader, ActsExamples::RootSimHitReader, ActsExamples::EDM4hepSimHitReader, ActsExamples::CsvTrackParameterReader, ActsExamples::EDM4hepMeasurementReader, ActsExamples::CsvSimHitReader, ActsExamples::CsvParticleReader, ActsExamples::HepMC3AsciiReader, ActsExamples::EDM4hepTrackReader, and ActsExamples::EDM4hepParticleReader.
ProcessCode ActsExamples::IReader::finalize () inline override virtual
Fulfill the algorithm interface.
Implements ActsExamples::SequenceElement.
Definition at line 49 of file IReader.hpp.
View newest version in sPHENIX GitHub at line 49 of file IReader.hpp
References SUCCESS.
Referenced by BOOST_AUTO_TEST_CASE().
ProcessCode ActsExamples::IReader::initialize () inline override virtual
Fulfill the algorithm interface.
Implements ActsExamples::SequenceElement.
Definition at line 46 of file IReader.hpp.
View newest version in sPHENIX GitHub at line 46 of file IReader.hpp
References SUCCESS.
ProcessCode ActsExamples::IReader::internalExecute (const AlgorithmContext & context) inline final virtual
Internal execute method forwards to the read method as mutable
Parameters
context The algorithm context
Implements ActsExamples::SequenceElement.
Definition at line 41 of file IReader.hpp.
View newest version in sPHENIX GitHub at line 41 of file IReader.hpp
References read().
virtual ProcessCode ActsExamples::IReader::read (const AlgorithmContext & context) pure virtual
Read data for the requested event and write it into the event store.
As a result of the parallelization and/or skipping events, this method will most likely not be called in order. Implementations must use the event number provided to select the proper data to be read.
Implemented in ActsExamples::RootAthenaNTupleReader, ActsExamples::EventGenerator, ActsExamples::CsvMeasurementReader, ActsExamples::CsvPlanarClusterReader, ActsExamples::RootMaterialTrackReader, ActsExamples::RootTrajectorySummaryReader, ActsExamples::RootParticleReader, ActsExamples::RootSimHitReader, ActsExamples::CsvSpacePointReader, ActsExamples::EDM4hepSimHitReader, ActsExamples::CsvTrackParameterReader, ActsExamples::EDM4hepMeasurementReader, ActsExamples::CsvSimHitReader, ActsExamples::CsvParticleReader, ActsExamples::HepMC3AsciiReader, ActsExamples::EDM4hepTrackReader, and ActsExamples::EDM4hepParticleReader.
Referenced by internalExecute().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Framework/IReader.hpp