Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Navigation/DetectorNavigatorTests.cpp File Reference
DetectorNavigatorTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Definitions/Direction.hpp"
#include "Acts/Definitions/Units.hpp"
#include "Acts/Detector/Detector.hpp"
#include "Acts/Detector/DetectorVolume.hpp"
#include "Acts/Detector/PortalGenerators.hpp"
#include "Acts/EventData/TrackParameters.hpp"
#include "Acts/Geometry/CuboidVolumeBounds.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/MagneticField/ConstantBField.hpp"
#include "Acts/MagneticField/MagneticFieldContext.hpp"
#include "Acts/Navigation/DetectorNavigator.hpp"
#include "Acts/Navigation/DetectorVolumeFinders.hpp"
#include "Acts/Navigation/SurfaceCandidatesUpdators.hpp"
#include "Acts/Propagator/AbortList.hpp"
#include "Acts/Propagator/ActionList.hpp"
#include "Acts/Propagator/EigenStepper.hpp"
#include "Acts/Propagator/Propagator.hpp"
#include "Acts/Utilities/Logger.hpp"
#include <algorithm>
#include <array>
#include <memory>
#include <tuple>
#include <utility>
#include <vector>
Namespaces
namespace Acts
Acts includes to create all necessary definitions.
Functions
BOOST_AUTO_TEST_CASE (DetectorNavigator)
Variables
Acts::GeometryContext tgContext
Acts::MagneticFieldContext mfContext
Function Documentation
BOOST_AUTO_TEST_CASE (DetectorNavigator)
Definition at line 49 of file DetectorNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 49 of file DetectorNavigatorTests.cpp
References Acts::IntegrationTest::bField, Acts::Experimental::DetectorVolumeFactory::construct(), Acts::Experimental::defaultPortalAndSubPortalGenerator(), Acts::Experimental::DetectorNavigator::Config::detector, Acts::getDefaultLogger(), Acts::Experimental::Detector::makeShared(), Acts::IntegrationTest::mfContext, Acts::Test::navigator, ckf::options, Acts::ParticleHypothesis::pion(), Acts::Test::pos, start, propagation_timing::stepper, Acts::UnitConstants::T, Acts::tgContext, Acts::Experimental::tryAllPortalsAndSurfaces(), Acts::Experimental::tryAllSubVolumes(), Acts::Experimental::tryRootVolumes(), and VERBOSE.
Variable Documentation
Acts::MagneticFieldContext mfContext
Definition at line 45 of file DetectorNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 45 of file DetectorNavigatorTests.cpp
Acts::GeometryContext tgContext
Definition at line 44 of file DetectorNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 44 of file DetectorNavigatorTests.cpp