Analysis Software: tinyxml2 Namespace Reference
tinyxml2 Namespace Reference
Classes
struct Entity
struct LongFitsIntoSizeTMinusOne
struct LongFitsIntoSizeTMinusOne< false >
class StrPair
class DynArray
class MemPool
class MemPoolT
class XMLVisitor
class XMLUtil
class XMLNode
class XMLText
class XMLComment
class XMLDeclaration
class XMLUnknown
class XMLAttribute
class XMLElement
class XMLDocument
class XMLHandle
class XMLConstHandle
class XMLPrinter
Enumerations
enum XMLError {
XML_SUCCESS = 0, XML_NO_ATTRIBUTE, XML_WRONG_ATTRIBUTE_TYPE, XML_ERROR_FILE_NOT_FOUND,
XML_ERROR_FILE_COULD_NOT_BE_OPENED, XML_ERROR_FILE_READ_ERROR, XML_ERROR_ELEMENT_MISMATCH, XML_ERROR_PARSING_ELEMENT,
XML_ERROR_PARSING_ATTRIBUTE, XML_ERROR_IDENTIFYING_TAG, XML_ERROR_PARSING_TEXT, XML_ERROR_PARSING_CDATA,
XML_ERROR_PARSING_COMMENT, XML_ERROR_PARSING_DECLARATION, XML_ERROR_PARSING_UNKNOWN, XML_ERROR_EMPTY_DOCUMENT,
XML_ERROR_MISMATCHED_ELEMENT, XML_ERROR_PARSING, XML_CAN_NOT_CONVERT_TEXT, XML_NO_TEXT_NODE,
XML_ERROR_COUNT
}
enum Whitespace { PRESERVE_WHITESPACE, COLLAPSE_WHITESPACE }
Functions
static FILE * callfopen (const char *filepath, const char *mode)
Variables
static const int NUM_ENTITIES = 5
static const Entity entities [NUM_ENTITIES]
Enumeration Type Documentation
enum tinyxml2::Whitespace
Enumerator:
PRESERVE_WHITESPACE
COLLAPSE_WHITESPACE
Definition at line 1577 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1577 of file tinyxml2.h
enum tinyxml2::XMLError
Enumerator:
XML_SUCCESS
XML_NO_ATTRIBUTE
XML_WRONG_ATTRIBUTE_TYPE
XML_ERROR_FILE_NOT_FOUND
XML_ERROR_FILE_COULD_NOT_BE_OPENED
XML_ERROR_FILE_READ_ERROR
XML_ERROR_ELEMENT_MISMATCH
XML_ERROR_PARSING_ELEMENT
XML_ERROR_PARSING_ATTRIBUTE
XML_ERROR_IDENTIFYING_TAG
XML_ERROR_PARSING_TEXT
XML_ERROR_PARSING_CDATA
XML_ERROR_PARSING_COMMENT
XML_ERROR_PARSING_DECLARATION
XML_ERROR_PARSING_UNKNOWN
XML_ERROR_EMPTY_DOCUMENT
XML_ERROR_MISMATCHED_ELEMENT
XML_ERROR_PARSING
XML_CAN_NOT_CONVERT_TEXT
XML_NO_TEXT_NODE
XML_ERROR_COUNT
Definition at line 501 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 501 of file tinyxml2.h
Function Documentation
static FILE* tinyxml2::callfopen (const char * filepath, const char * mode) static
Definition at line 2035 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 2035 of file tinyxml2.cc
References check_license::err(), and TIXMLASSERT.
Referenced by tinyxml2::XMLDocument::LoadFile(), and tinyxml2::XMLDocument::SaveFile().
Variable Documentation
const Entity tinyxml2::entities[NUM_ENTITIES] static
Initial value:
= {
    { "quot", 4,        DOUBLE_QUOTE },
    { "amp", 3,         '&'  },
    { "apos", 4,        SINGLE_QUOTE },
    { "lt",     2,              '<'      },
    { "gt",     2,              '>'      }
}
Definition at line 129 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 129 of file tinyxml2.cc
Referenced by tinyxml2::StrPair::GetStr(), tinyxml2::XMLPrinter::PrintString(), and tinyxml2::XMLPrinter::XMLPrinter().
const int tinyxml2::NUM_ENTITIES = 5 static
Definition at line 128 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 128 of file tinyxml2.cc
Referenced by tinyxml2::StrPair::GetStr(), tinyxml2::XMLPrinter::PrintString(), and tinyxml2::XMLPrinter::XMLPrinter().