Analysis Software: Fluid Class Reference
Fluid Class Reference
#include <JETSCAPE/blob/main/jail/vhlle/src/fld.h>
Public Member Functions
Fluid (EoS *_eos, EoS *_eosH, TransportCoeff *_trcoeff, int _nx, int _ny, int _nz, double _minx, double _maxx, double _miny, double _maxy, double _minz, double _maxz, double dt, double eCrit)
~Fluid ()
void initOutput (char *dir, int maxstep, double tau0, int cmpr2dOut)
int getNX ()
int getNY ()
int getNZ ()
double getDx ()
double getDy ()
double getDz ()
double getX (int ix)
double getY (int iy)
double getZ (int iz)
void getCMFvariables (Cell *c, double tau, double &e, double &nb, double &nq, double &ns, double &vx, double &vy, double &Y)
Cell * getCell (int ix, int iy, int iz)
void correctImagCells (void)
void correctImagCellsFull (void)
void updateM (double tau, double dt)
void outputGnuplot (double tau)
void calcTotals (double tau)
Public Attributes
int output_xy_spacing
int output_eta_points
int output_tau_spacing
int output_eta_spacing
int output_nt
int output_nx
int output_ny
Private Attributes
EoS * eos
EoS * eosH
TransportCoeff * trcoeff
Cornelius * cornelius
Cell * cell
Cell * cell0
int nx
int ny
int nz
double minx
double maxx
double miny
double maxy
double minz
double maxz
double dx
double dy
double dz
double dt
std::ofstream foutkw
std::ofstream foutkw_dim
std::ofstream foutxvisc
std::ofstream foutyvisc
std::ofstream foutdiagvisc
std::ofstream foutx
std::ofstream fouty
std::ofstream foutdiag
std::ofstream foutz
std::ofstream fout_aniz
std::ofstream fout2d
std::ofstream ffreeze
int compress2dOut
Detailed Description
Definition at line 11 of file fld.h.
View newest version in sPHENIX GitHub at line 11 of file fld.h
Constructor & Destructor Documentation
Fluid::Fluid (EoS * _eos, EoS * _eosH, TransportCoeff * _trcoeff, int _nx, int _ny, int _nz, double _minx, double _maxx, double _miny, double _maxy, double _minz, double _maxz, double dt, double eCrit)
Definition at line 49 of file fld.cpp.
View newest version in sPHENIX GitHub at line 49 of file fld.cpp
References dy, dz, eos, nx, ny, nz, trcoeff, X_, Y_, and Z_.
Fluid::~Fluid ()
Definition at line 93 of file fld.cpp.
View newest version in sPHENIX GitHub at line 93 of file fld.cpp
Member Function Documentation
void Fluid::calcTotals (double tau)
Definition at line 463 of file fld.cpp.
View newest version in sPHENIX GitHub at line 463 of file fld.cpp
References Acts::PhysicalConstants::c, deltas(), dy, dz, E, Acts::UnitConstants::e, eos, EoS::eos(), eta, Cell::getpi(), Cell::getQ(), i, TransportCoeff::isViscous(), j, NB_, Acts::UnitConstants::ns, nx, ny, nz, merge_hashes::p, Px(), Q(), physmon_simulation::s, EoS::s(), S(), t, trcoeff, vx, vy, and vz.
Referenced by main().
void Fluid::correctImagCells (void)
Definition at line 155 of file fld.cpp.
View newest version in sPHENIX GitHub at line 155 of file fld.cpp
References nx, ny, nz, and Q().
Referenced by Hydro::performStep().
void Fluid::correctImagCellsFull (void)
Definition at line 195 of file fld.cpp.
View newest version in sPHENIX GitHub at line 195 of file fld.cpp
References i, j, nx, ny, nz, and Q().
Referenced by Hydro::performStep().
Cell* Fluid::getCell (int ix, int iy, int iz) inline
Definition at line 53 of file fld.h.
View newest version in sPHENIX GitHub at line 53 of file fld.h
References cell, nx, ny, and nz.
Referenced by getenergyhlle_(), getvalueshlle_(), getvflaghlle_(), getvischlle_(), icsethlle_(), Hydro::ISformal(), Hydro::NSquant(), Hydro::performStep(), ICGubser::setIC(), IC::setIC(), ICGlauber::setIC(), Hydro::setNSvalues(), Hydro::source_step(), and Hydro::visc_source_step().
void Fluid::getCMFvariables (Cell * c, double tau, double & e, double & nb, double & nq, double & ns, double & vx, double & vy, double & Y)
Definition at line 37 of file fld.cpp.
View newest version in sPHENIX GitHub at line 37 of file fld.cpp
References eos, eta, Cell::getPrimVar(), Cell::getZ(), merge_hashes::p, and vz.
double Fluid::getDx () inline
Definition at line 43 of file fld.h.
View newest version in sPHENIX GitHub at line 43 of file fld.h
References dx.
Referenced by Hydro::hlle_flux(), Hydro::ISformal(), Hydro::NSquant(), Hydro::setDtau(), ICGubser::setIC(), IC::setIC(), ICGlauber::setIC(), and Hydro::visc_flux().
double Fluid::getDy () inline
Definition at line 44 of file fld.h.
View newest version in sPHENIX GitHub at line 44 of file fld.h
References dy.
Referenced by Hydro::hlle_flux(), Hydro::ISformal(), Hydro::NSquant(), Hydro::setDtau(), ICGubser::setIC(), IC::setIC(), ICGlauber::setIC(), and Hydro::visc_flux().
double Fluid::getDz () inline
Definition at line 45 of file fld.h.
View newest version in sPHENIX GitHub at line 45 of file fld.h
References dz.
Referenced by Hydro::hlle_flux(), Hydro::ISformal(), Hydro::NSquant(), Hydro::setDtau(), ICGubser::setIC(), IC::setIC(), ICGlauber::setIC(), and Hydro::visc_flux().
int Fluid::getNX () inline
Definition at line 40 of file fld.h.
View newest version in sPHENIX GitHub at line 40 of file fld.h
References nx.
Referenced by getenergyhlle_(), Hydro::ISformal(), Hydro::performStep(), IC::setIC(), ICGubser::setIC(), ICGlauber::setIC(), and Hydro::setNSvalues().
int Fluid::getNY () inline
Definition at line 41 of file fld.h.
View newest version in sPHENIX GitHub at line 41 of file fld.h
References ny.
Referenced by getenergyhlle_(), Hydro::ISformal(), Hydro::performStep(), IC::setIC(), ICGubser::setIC(), ICGlauber::setIC(), and Hydro::setNSvalues().
int Fluid::getNZ () inline
Definition at line 42 of file fld.h.
View newest version in sPHENIX GitHub at line 42 of file fld.h
References nz.
Referenced by getenergyhlle_(), Hydro::ISformal(), Hydro::performStep(), IC::setIC(), ICGubser::setIC(), ICGlauber::setIC(), and Hydro::setNSvalues().
double Fluid::getX (int ix) inline
Definition at line 46 of file fld.h.
View newest version in sPHENIX GitHub at line 46 of file fld.h
References dx, and minx.
Referenced by getxhlle_(), ICGubser::setIC(), IC::setIC(), ICGlauber::setIC(), and Hydro::source_step().
double Fluid::getY (int iy) inline
Definition at line 47 of file fld.h.
View newest version in sPHENIX GitHub at line 47 of file fld.h
References dy, and miny.
Referenced by getyhlle_(), ICGubser::setIC(), IC::setIC(), ICGlauber::setIC(), and Hydro::source_step().
double Fluid::getZ (int iz) inline
Definition at line 48 of file fld.h.
View newest version in sPHENIX GitHub at line 48 of file fld.h
References dz, and minz.
Referenced by getenergyhlle_(), getzhlle_(), IC::setIC(), ICGubser::setIC(), ICGlauber::setIC(), and Hydro::source_step().
void Fluid::initOutput (char * dir, int maxstep, double tau0, int cmpr2dOut)
Definition at line 98 of file fld.cpp.
View newest version in sPHENIX GitHub at line 98 of file fld.cpp
Referenced by initoutputhlle_(), and main().
void Fluid::outputGnuplot (double tau)
Definition at line 346 of file fld.cpp.
View newest version in sPHENIX GitHub at line 346 of file fld.cpp
References Acts::PhysicalConstants::c, Acts::UnitConstants::e, eos, EoS::eos(), Cell::getpi(), Cell::getPi(), Cell::getViscCorrCutFlag(), Acts::UnitConstants::ns, nx, ny, nz, merge_hashes::p, t, vx, vy, vz, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by main().
void Fluid::updateM (double tau, double dt)
Definition at line 304 of file fld.cpp.
View newest version in sPHENIX GitHub at line 304 of file fld.cpp
References Cell::addM(), Acts::PhysicalConstants::c, dy, dz, Cell::getDM(), Cell::setDM(), X_, Y_, and Z_.
Referenced by Hydro::performStep().
Member Data Documentation
Cell* Fluid::cell private
Definition at line 16 of file fld.h.
View newest version in sPHENIX GitHub at line 16 of file fld.h
Referenced by getCell().
Cell* Fluid::cell0 private
Definition at line 17 of file fld.h.
View newest version in sPHENIX GitHub at line 17 of file fld.h
int Fluid::compress2dOut private
Definition at line 25 of file fld.h.
View newest version in sPHENIX GitHub at line 25 of file fld.h
Cornelius* Fluid::cornelius private
Definition at line 15 of file fld.h.
View newest version in sPHENIX GitHub at line 15 of file fld.h
double Fluid::dt private
Definition at line 21 of file fld.h.
View newest version in sPHENIX GitHub at line 21 of file fld.h
double Fluid::dx private
Definition at line 21 of file fld.h.
View newest version in sPHENIX GitHub at line 21 of file fld.h
Referenced by getDx(), and getX().
double Fluid::dy private
Definition at line 21 of file fld.h.
View newest version in sPHENIX GitHub at line 21 of file fld.h
Referenced by getDy(), and getY().
double Fluid::dz private
Definition at line 21 of file fld.h.
View newest version in sPHENIX GitHub at line 21 of file fld.h
Referenced by getDz(), and getZ().
EoS* Fluid::eos private
Definition at line 13 of file fld.h.
View newest version in sPHENIX GitHub at line 13 of file fld.h
EoS * Fluid::eosH private
Definition at line 13 of file fld.h.
View newest version in sPHENIX GitHub at line 13 of file fld.h
std::ofstream Fluid::ffreeze private
Definition at line 23 of file fld.h.
View newest version in sPHENIX GitHub at line 23 of file fld.h
std::ofstream Fluid::fout2d private
Definition at line 23 of file fld.h.
View newest version in sPHENIX GitHub at line 23 of file fld.h
std::ofstream Fluid::fout_aniz private
Definition at line 23 of file fld.h.
View newest version in sPHENIX GitHub at line 23 of file fld.h
std::ofstream Fluid::foutdiag private
Definition at line 23 of file fld.h.
View newest version in sPHENIX GitHub at line 23 of file fld.h
std::ofstream Fluid::foutdiagvisc private
Definition at line 23 of file fld.h.
View newest version in sPHENIX GitHub at line 23 of file fld.h
std::ofstream Fluid::foutkw private
Definition at line 23 of file fld.h.
View newest version in sPHENIX GitHub at line 23 of file fld.h
std::ofstream Fluid::foutkw_dim private
Definition at line 23 of file fld.h.
View newest version in sPHENIX GitHub at line 23 of file fld.h
std::ofstream Fluid::foutx private
Definition at line 23 of file fld.h.
View newest version in sPHENIX GitHub at line 23 of file fld.h
std::ofstream Fluid::foutxvisc private
Definition at line 23 of file fld.h.
View newest version in sPHENIX GitHub at line 23 of file fld.h
std::ofstream Fluid::fouty private
Definition at line 23 of file fld.h.
View newest version in sPHENIX GitHub at line 23 of file fld.h
std::ofstream Fluid::foutyvisc private
Definition at line 23 of file fld.h.
View newest version in sPHENIX GitHub at line 23 of file fld.h
std::ofstream Fluid::foutz private
Definition at line 23 of file fld.h.
View newest version in sPHENIX GitHub at line 23 of file fld.h
double Fluid::maxx private
Definition at line 20 of file fld.h.
View newest version in sPHENIX GitHub at line 20 of file fld.h
double Fluid::maxy private
Definition at line 20 of file fld.h.
View newest version in sPHENIX GitHub at line 20 of file fld.h
double Fluid::maxz private
Definition at line 20 of file fld.h.
View newest version in sPHENIX GitHub at line 20 of file fld.h
double Fluid::minx private
Definition at line 20 of file fld.h.
View newest version in sPHENIX GitHub at line 20 of file fld.h
Referenced by getX().
double Fluid::miny private
Definition at line 20 of file fld.h.
View newest version in sPHENIX GitHub at line 20 of file fld.h
Referenced by getY().
double Fluid::minz private
Definition at line 20 of file fld.h.
View newest version in sPHENIX GitHub at line 20 of file fld.h
Referenced by getZ().
int Fluid::nx private
Definition at line 18 of file fld.h.
View newest version in sPHENIX GitHub at line 18 of file fld.h
Referenced by getCell(), and getNX().
int Fluid::ny private
Definition at line 18 of file fld.h.
View newest version in sPHENIX GitHub at line 18 of file fld.h
Referenced by getCell(), and getNY().
int Fluid::nz private
Definition at line 18 of file fld.h.
View newest version in sPHENIX GitHub at line 18 of file fld.h
Referenced by getCell(), and getNZ().
int Fluid::output_eta_points
Definition at line 34 of file fld.h.
View newest version in sPHENIX GitHub at line 34 of file fld.h
int Fluid::output_eta_spacing
Definition at line 36 of file fld.h.
View newest version in sPHENIX GitHub at line 36 of file fld.h
int Fluid::output_nt
Definition at line 38 of file fld.h.
View newest version in sPHENIX GitHub at line 38 of file fld.h
int Fluid::output_nx
Definition at line 38 of file fld.h.
View newest version in sPHENIX GitHub at line 38 of file fld.h
int Fluid::output_ny
Definition at line 38 of file fld.h.
View newest version in sPHENIX GitHub at line 38 of file fld.h
int Fluid::output_tau_spacing
Definition at line 35 of file fld.h.
View newest version in sPHENIX GitHub at line 35 of file fld.h
int Fluid::output_xy_spacing
Definition at line 33 of file fld.h.
View newest version in sPHENIX GitHub at line 33 of file fld.h
TransportCoeff* Fluid::trcoeff private
Definition at line 14 of file fld.h.
View newest version in sPHENIX GitHub at line 14 of file fld.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/jail/vhlle/src/fld.h
JETSCAPE/blob/main/jail/vhlle/src/fld.cpp