Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/TrackFitting/FitterTestsCommon.hpp File Reference
FitterTestsCommon.hpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Units.hpp"
#include "Acts/EventData/MultiTrajectory.hpp"
#include "Acts/EventData/SourceLink.hpp"
#include "Acts/EventData/VectorMultiTrajectory.hpp"
#include "Acts/EventData/VectorTrackContainer.hpp"
#include "Acts/Geometry/TrackingGeometry.hpp"
#include "Acts/MagneticField/ConstantBField.hpp"
#include "Acts/MagneticField/MagneticFieldContext.hpp"
#include "Acts/Propagator/Navigator.hpp"
#include "Acts/Propagator/StraightLineStepper.hpp"
#include "Acts/Tests/CommonHelpers/CubicTrackingGeometry.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Tests/CommonHelpers/MeasurementsCreator.hpp"
#include "Acts/Tests/CommonHelpers/TestSourceLink.hpp"
#include "Acts/TrackFitting/detail/KalmanGlobalCovariance.hpp"
#include "Acts/Utilities/CalibrationContext.hpp"
#include <iterator>
Classes
struct TestOutlierFinder
struct TestReverseFilteringLogic
struct FitterTester
Functions
auto makeStraightPropagator (std::shared_ptr< const Acts::TrackingGeometry > geo)
template<typename stepper_t >
auto makeConstantFieldPropagator (std::shared_ptr< const Acts::TrackingGeometry > geo, double bz)
Function Documentation
template<typename stepper_t > auto makeConstantFieldPropagator (std::shared_ptr< const Acts::TrackingGeometry > geo, double bz)
Definition at line 97 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 97 of file FitterTestsCommon.hpp
References cfg, ckf::field, testing::internal::move(), Acts::Test::navigator, and propagation_timing::stepper.
Referenced by BOOST_AUTO_TEST_CASE().
auto makeStraightPropagator (std::shared_ptr< const Acts::TrackingGeometry > geo)
Definition at line 84 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 84 of file FitterTestsCommon.hpp
References cfg, testing::internal::move(), Acts::Test::navigator, and propagation_timing::stepper.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().