Analysis Software: TSQLPreparedStatement Class Reference
TSQLPreparedStatement Class Reference abstract
#include <RDBC/blob/master/include/RDBC/TSQLPreparedStatement.h>
Public Member Functions
virtual ~TSQLPreparedStatement ()
virtual void SetNull (Int_t parameterIndex, Int_t sqlType)=0
virtual void SetBoolean (Int_t parameterIndex, Bool_t x)=0
virtual void SetByte (Int_t parameterIndex, Char_t x)=0
virtual void SetShort (Int_t parameterIndex, Short_t x)=0
virtual void SetInt (Int_t parameterIndex, Int_t x)=0
virtual void SetLong (Int_t parameterIndex, Long_t x)=0
virtual void SetFloat (Int_t parameterIndex, Float_t x)=0
virtual void SetDouble (Int_t parameterIndex, Double_t x)=0
virtual void SetString (Int_t parameterIndex, const TString &x)=0
virtual void SetBytes (Int_t parameterIndex, const TArrayC &x)=0
virtual void SetDate (Int_t parameterIndex, const TSQLDate &x)=0
virtual void SetTime (Int_t parameterIndex, const TSQLTime &x)=0
virtual void SetTimestamp (Int_t parameterIndex, const TSQLTimestamp &x)=0
virtual void SetAsciiStream (Int_t parameterIndex, TBuffer *x, Int_t length)=0
virtual void SetBinaryStream (Int_t parameterIndex, TBuffer *x, Int_t length)=0
virtual void SetObject (Int_t parameterIndex, TObject *x)=0
virtual void ClearParameters ()=0
Public Member Functions inherited from TSQLStatement
virtual void Execute (const char *, const char *, int *)
virtual void Execute (TMethod *, TObjArray *, int *)
virtual ~TSQLStatement ()
virtual TSQLResultSet * ExecuteQuery (const TString &sql="")=0
virtual Int_t ExecuteUpdate (const TString &sql="")=0
virtual Bool_t Execute (const TString &sql="")=0
virtual TSQLResultSet * GetResultSet ()=0
virtual Bool_t GetMoreResults ()=0
virtual void Close ()=0
virtual void Cancel ()=0
virtual Int_t GetMaxFieldSize ()=0
virtual void SetMaxFieldSize (Int_t max)=0
virtual Int_t GetMaxRows ()=0
virtual void SetMaxRows (Int_t max)=0
virtual Bool_t GetEscapeProcessing ()=0
virtual void SetEscapeProcessing (Bool_t enable=kTRUE)=0
virtual Int_t GetQueryTimeout ()=0
virtual void SetQueryTimeout (Int_t seconds)=0
virtual Int_t GetUpdateCount ()=0
virtual void SetCursorName (const TString &name)=0
virtual void AddBatch (const TString &sql)=0
virtual void ClearBatch ()=0
virtual Int_t * ExecuteBatch ()=0
virtual Int_t GetFetchDirection ()=0
virtual void SetFetchDirection (Int_t direction)=0
virtual Int_t GetFetchSize ()=0
virtual void SetFetchSize (Int_t rows)=0
virtual Int_t GetResultSetConcurrency ()=0
virtual Int_t GetResultSetType ()=0
TSQLConnection * GetConnection () const
Public Member Functions inherited from TSQL
TSQL (void *imp=0)
virtual ~TSQL ()
virtual void Throw (TSQLException *e)
TList * GetWarnings () const
void ClearWarnings ()
virtual Bool_t IsValid () const
Protected Member Functions
TSQLPreparedStatement (TSQLConnection *con, void *imp=0)
Protected Member Functions inherited from TSQLStatement
TSQLStatement (TSQLConnection *con, void *imp=0)
Additional Inherited Members
Static Public Member Functions inherited from TSQL
static Bool_t SetHandler (const TString &handler)
static Bool_t UnsetHandler (const TString &handler="")
Protected Attributes inherited from TSQLStatement
TList * fBatches
TSQLResultSet * fCurrentResult
TSQLConnection * fConnection
Detailed Description
Definition at line 21 of file TSQLPreparedStatement.h.
View newest version in sPHENIX GitHub at line 21 of file TSQLPreparedStatement.h
Constructor & Destructor Documentation
TSQLPreparedStatement::TSQLPreparedStatement (TSQLConnection * con, void * imp = 0) inline protected
Definition at line 24 of file TSQLPreparedStatement.h.
View newest version in sPHENIX GitHub at line 24 of file TSQLPreparedStatement.h
virtual TSQLPreparedStatement::~TSQLPreparedStatement () inline virtual
Definition at line 27 of file TSQLPreparedStatement.h.
View newest version in sPHENIX GitHub at line 27 of file TSQLPreparedStatement.h
Member Function Documentation
void TSQLPreparedStatement::ClearParameters () pure virtual
Implemented in ODBCCallableStatement, and ODBCPreparedStatement.
Definition at line 342 of file MySQLPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 342 of file MySQLPreparedStatement.cxx
void TSQLPreparedStatement::SetAsciiStream (Int_t parameterIndex, TBuffer * x, Int_t length) pure virtual
Implemented in ODBCCallableStatement, and ODBCPreparedStatement.
Definition at line 274 of file MySQLPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 274 of file MySQLPreparedStatement.cxx
void TSQLPreparedStatement::SetBinaryStream (Int_t parameterIndex, TBuffer * x, Int_t length) pure virtual
Implemented in ODBCCallableStatement, and ODBCPreparedStatement.
Definition at line 299 of file MySQLPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 299 of file MySQLPreparedStatement.cxx
Referenced by SetObject(), and ODBCCallableStatement::SetObject().
void TSQLPreparedStatement::SetBoolean (Int_t parameterIndex, Bool_t x) pure virtual
Implemented in ODBCCallableStatement, and ODBCPreparedStatement.
Definition at line 75 of file MySQLPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 75 of file MySQLPreparedStatement.cxx
void TSQLPreparedStatement::SetByte (Int_t parameterIndex, Char_t x) pure virtual
Implemented in ODBCCallableStatement, and ODBCPreparedStatement.
Definition at line 91 of file MySQLPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 91 of file MySQLPreparedStatement.cxx
void TSQLPreparedStatement::SetBytes (Int_t parameterIndex, const TArrayC & x) pure virtual
Implemented in ODBCCallableStatement, and ODBCPreparedStatement.
Definition at line 205 of file MySQLPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 205 of file MySQLPreparedStatement.cxx
void TSQLPreparedStatement::SetDate (Int_t parameterIndex, const TSQLDate & x) pure virtual
Implemented in ODBCCallableStatement, and ODBCPreparedStatement.
Definition at line 223 of file MySQLPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 223 of file MySQLPreparedStatement.cxx
void TSQLPreparedStatement::SetDouble (Int_t parameterIndex, Double_t x) pure virtual
Implemented in ODBCCallableStatement, and ODBCPreparedStatement.
Definition at line 171 of file MySQLPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 171 of file MySQLPreparedStatement.cxx
void TSQLPreparedStatement::SetFloat (Int_t parameterIndex, Float_t x) pure virtual
Implemented in ODBCCallableStatement, and ODBCPreparedStatement.
Definition at line 155 of file MySQLPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 155 of file MySQLPreparedStatement.cxx
Referenced by RDBCTestInt().
void TSQLPreparedStatement::SetInt (Int_t parameterIndex, Int_t x) pure virtual
Implemented in ODBCCallableStatement, and ODBCPreparedStatement.
Definition at line 123 of file MySQLPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 123 of file MySQLPreparedStatement.cxx
Referenced by PgPostBankBackupManager::CleanTable(), PgPostBankWrapper::commit(), PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), PgPostBankBackupLog::Log(), Populate(), and RDBCTestInt().
void TSQLPreparedStatement::SetLong (Int_t parameterIndex, Long_t x) pure virtual
Implemented in ODBCCallableStatement, and ODBCPreparedStatement.
Definition at line 139 of file MySQLPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 139 of file MySQLPreparedStatement.cxx
Referenced by PgPostBankWrapper::commit(), PgPostBankBackupManager::commit(), and PgPostBankBackupManager::commitAllBankfromTFile().
void TSQLPreparedStatement::SetNull (Int_t parameterIndex, Int_t sqlType) pure virtual
Implemented in ODBCCallableStatement, and ODBCPreparedStatement.
Definition at line 58 of file MySQLPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 58 of file MySQLPreparedStatement.cxx
void TSQLPreparedStatement::SetObject (Int_t parameterIndex, TObject * x) pure virtual
Implemented in ODBCCallableStatement, and ODBCPreparedStatement.
Definition at line 323 of file MySQLPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 323 of file MySQLPreparedStatement.cxx
References KFPMath::b, and SetBinaryStream().
Referenced by PgPostBankWrapper::commit(), PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), and CreateStuff().
void TSQLPreparedStatement::SetShort (Int_t parameterIndex, Short_t x) pure virtual
Implemented in ODBCCallableStatement, and ODBCPreparedStatement.
Definition at line 107 of file MySQLPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 107 of file MySQLPreparedStatement.cxx
void TSQLPreparedStatement::SetString (Int_t parameterIndex, const TString & x) pure virtual
Implemented in ODBCCallableStatement, and ODBCPreparedStatement.
Definition at line 187 of file MySQLPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 187 of file MySQLPreparedStatement.cxx
Referenced by PgPostBankWrapper::commit(), PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), CreateStuff(), Populate(), and RDBCTestInt().
void TSQLPreparedStatement::SetTime (Int_t parameterIndex, const TSQLTime & x) pure virtual
Implemented in ODBCCallableStatement, and ODBCPreparedStatement.
Definition at line 240 of file MySQLPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 240 of file MySQLPreparedStatement.cxx
void TSQLPreparedStatement::SetTimestamp (Int_t parameterIndex, const TSQLTimestamp & x) pure virtual
Implemented in ODBCCallableStatement, and ODBCPreparedStatement.
Definition at line 257 of file MySQLPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 257 of file MySQLPreparedStatement.cxx
The documentation for this class was generated from the following files:
RDBC/blob/master/include/RDBC/TSQLPreparedStatement.h
RDBC/blob/master/mysql/MySQLPreparedStatement.cxx