Analysis Software: macros/blob/master/common/G4_HcalOut_ref.C File Reference
G4_HcalOut_ref.C File Reference
#include <GlobalVariables.C>
#include <QA.C>
#include <g4calo/HcalRawTowerBuilder.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4ohcal/PHG4OHCalSubsystem.h>
#include <g4detectors/PHG4HcalCellReco.h>
#include <g4detectors/PHG4OuterHcalSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <caloreco/RawClusterBuilderGraph.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <qa_modules/QAG4SimulationCalorimeter.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4HCALOUT
Macros
#define MACRO_G4HCALOUTREF_C
Enumerations
enum G4HCALOUT::enu_HCalOut_clusterizer { G4HCALOUT::kHCalOutGraphClusterizer, G4HCALOUT::kHCalOutTemplateClusterizer, G4HCALOUT::kHCalOutGraphClusterizer, G4HCALOUT::kHCalOutTemplateClusterizer }
Functions
void HCalOuterInit ()
double HCalOuter (PHG4Reco *g4Reco, double radius, const int crossings)
void HCALOuter_Cells ()
void HCALOuter_Towers ()
void HCALOuter_Clusters ()
void HCALOuter_Eval (const std::string &outputfile, int start_event=0)
void HCALOuter_QA ()
Variables
bool Enable::HCALOUT_OLD = false
bool Enable::HCALOUT_G4Hit = true
double G4HCALOUT::phistart = NAN
double G4HCALOUT::tower_emin = NAN
int G4HCALOUT::light_scint_model = -1
int G4HCALOUT::tower_energy_source = -1
Macro Definition Documentation
#define MACRO_G4HCALOUTREF_C
Definition at line 2 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 2 of file G4_HcalOut_ref.C
Function Documentation
double HCalOuter (PHG4Reco * g4Reco, double radius, const int crossings)
Definition at line 87 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 87 of file G4_HcalOut_ref.C
References Enable::ABSORBER, PHG4DetectorSubsystem::get_double_param(), Enable::HCALOUT_ABSORBER, Enable::HCALOUT_G4Hit, Enable::HCALOUT_OLD, Enable::HCALOUT_OVERLAPCHECK, Enable::HCALOUT_VERBOSITY, i, inch, G4HCALOUT::light_scint_model, G4MAGNET::magfield_OHCAL_steel, G4MAGNET::magfield_rescale, no_overlapp, PHG4DetectorSubsystem::OverlapCheck(), Enable::OVERLAPCHECK, G4HCALOUT::phistart, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4Subsystem::SetMotherSubsystem(), PHG4DetectorSubsystem::SuperDetector(), G4HCALIN::support_ring_outer_radius, G4HCALIN::support_ring_z, verbosity, and Enable::VERBOSITY.
void HCALOuter_Cells ()
Definition at line 243 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 243 of file G4_HcalOut_ref.C
References PHG4HcalCellReco::Detector(), Enable::HCALOUT_G4Hit, Enable::HCALOUT_VERBOSITY, Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void HCALOuter_Clusters ()
Definition at line 345 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 345 of file G4_HcalOut_ref.C
References RawClusterBuilderGraph::Detector(), RawClusterBuilderTemplate::Detector(), G4HCALOUT::HCalOut_clusterizer, Enable::HCALOUT_G4Hit, Enable::HCALOUT_VERBOSITY, Fun4AllServer::instance(), G4HCALOUT::kHCalOutGraphClusterizer, G4HCALOUT::kHCalOutTemplateClusterizer, Fun4AllServer::registerSubsystem(), RawClusterBuilderTemplate::set_UseTowerInfo(), RawClusterBuilderTemplate::SetCylindricalGeometry(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void HCALOuter_Eval (const std::string & outputfile, int start_event = 0)
Definition at line 377 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 377 of file G4_HcalOut_ref.C
References Enable::HCALOUT_VERBOSITY, Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), CaloEvaluator::set_event(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void HCALOuter_QA ()
Definition at line 391 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 391 of file G4_HcalOut_ref.C
References Enable::HCALOUT_VERBOSITY, Fun4AllServer::instance(), Enable::QA_VERBOSITY, Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
void HCALOuter_Towers ()
Definition at line 268 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 268 of file G4_HcalOut_ref.C
References HcalRawTowerBuilder::Detector(), RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), Acts::UnitConstants::e, Enable::HCALOUT_G4Hit, Enable::HCALOUT_OLD, Enable::HCALOUT_VERBOSITY, Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, G4HCALOUT::phistart, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), PHParameterInterface::set_double_param(), PHParameterInterface::set_int_param(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), HcalRawTowerBuilder::set_sim_tower_node_prefix(), RawTowerCalibration::set_towerinfo(), RawTowerDigitizer::set_towerinfo(), RawTowerDigitizer::set_zero_suppression_ADC(), G4HCALOUT::tower_emin, G4HCALOUT::tower_energy_source, G4HCALOUT::TowerDigi, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void HCalOuterInit ()
Definition at line 80 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 80 of file G4_HcalOut_ref.C
References BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, Acts::UnitConstants::min, BlackHoleGeometry::min_z, G4HCALOUT::outer_radius, and G4HCALOUT::size_z.