Analysis Software: TSQL Class Reference
TSQL Class Reference
#include <RDBC/blob/master/include/RDBC/TSQL.h>
Public Member Functions
TSQL (void *imp=0)
virtual ~TSQL ()
virtual void Throw (TSQLException *e)
TList * GetWarnings () const
void ClearWarnings ()
virtual Bool_t IsValid () const
Static Public Member Functions
static Bool_t SetHandler (const TString &handler)
static Bool_t UnsetHandler (const TString &handler="")
Protected Attributes
TList * fWarnings
void * fImp
Detailed Description
Definition at line 50 of file TSQL.h.
View newest version in sPHENIX GitHub at line 50 of file TSQL.h
Constructor & Destructor Documentation
TSQL::TSQL (void * imp = 0)
Definition at line 96 of file TSQL.cxx.
View newest version in sPHENIX GitHub at line 96 of file TSQL.cxx
References fImp, and fWarnings.
TSQL::~TSQL () virtual
Definition at line 105 of file TSQL.cxx.
View newest version in sPHENIX GitHub at line 105 of file TSQL.cxx
References ClearWarnings(), and fWarnings.
Member Function Documentation
void TSQL::ClearWarnings ()
Definition at line 131 of file TSQL.cxx.
View newest version in sPHENIX GitHub at line 131 of file TSQL.cxx
References fWarnings.
Referenced by RDBCBench::CreateDatabase(), ODBCConnection::CreateStatement(), RDBCBench::DoOne(), ODBCStatement::Execute(), TSQLStatement::Execute(), ODBCPreparedStatement::Execute(), ODBCCallableStatement::Execute(), ODBCStatement::ExecuteQuery(), TSQLStatement::ExecuteQuery(), ODBCPreparedStatement::ExecuteQuery(), ODBCCallableStatement::ExecuteQuery(), ODBCStatement::ExecuteUpdate(), ODBCPreparedStatement::ExecuteUpdate(), ODBCCallableStatement::ExecuteUpdate(), ODBCConnection::NativeSQL(), ODBCConnection::PrepareCall(), ODBCConnection::PrepareStatement(), and ~TSQL().
TList* TSQL::GetWarnings () const inline
Definition at line 62 of file TSQL.h.
View newest version in sPHENIX GitHub at line 62 of file TSQL.h
References fWarnings.
Referenced by TSQLDriverManager::GetConnection().
virtual Bool_t TSQL::IsValid () const inline virtual
Definition at line 64 of file TSQL.h.
View newest version in sPHENIX GitHub at line 64 of file TSQL.h
References fImp.
Referenced by ClassImpQ().
Bool_t TSQL::SetHandler (const TString & handler) static
Definition at line 139 of file TSQL.cxx.
View newest version in sPHENIX GitHub at line 139 of file TSQL.cxx
References UnsetHandler().
Referenced by bench(), DbForm::DbForm(), RDBCBench::DoOne(), RDBCBench::DropDatabase(), oproducer(), RDBCconsumer(), RDBCemp(), RDBCfirst(), and RDBCscroll().
void TSQL::Throw (TSQLException * e) virtual
Definition at line 114 of file TSQL.cxx.
View newest version in sPHENIX GitHub at line 114 of file TSQL.cxx
References fWarnings, TSQLException::Print(), and printf().
Referenced by ODBCResultSet::Absolute(), ODBCResultSet::AfterLast(), ODBCResultSet::BeforeFirst(), ODBCStatement::Cancel(), ODBCPreparedStatement::Cancel(), ODBCCallableStatement::Cancel(), ODBCResultSet::CancelRowUpdates(), ClassImpQ(), ODBCPreparedStatement::ClearParameters(), ODBCCallableStatement::ClearParameters(), ODBCStatement::Close(), ODBCConnection::Close(), ODBCPreparedStatement::Close(), ODBCCallableStatement::Close(), TSQLConnection::Close(), ODBCResultSet::Close(), ODBCConnection::Commit(), TSQLConnection::Commit(), ODBCConnection::CreateStatement(), ODBCResultSet::DeleteRow(), ODBCStatement::Execute(), TSQLStatement::Execute(), ODBCPreparedStatement::Execute(), ODBCCallableStatement::Execute(), ODBCStatement::ExecuteQuery(), TSQLStatement::ExecuteQuery(), ODBCPreparedStatement::ExecuteQuery(), ODBCCallableStatement::ExecuteQuery(), ODBCStatement::ExecuteUpdate(), ODBCPreparedStatement::ExecuteUpdate(), ODBCCallableStatement::ExecuteUpdate(), ODBCResultSet::FindColumn(), ODBCResultSet::First(), TSQLResultSet::First(), ODBCResultSet::GetAsciiStream(), TSQLResultSet::GetAsciiStream(), ODBCConnection::GetAutoCommit(), ODBCResultSet::GetBinaryStream(), TSQLResultSet::GetBinaryStream(), ODBCCallableStatement::GetBoolean(), ODBCResultSet::GetBoolean(), TSQLResultSet::GetBoolean(), ODBCCallableStatement::GetByte(), ODBCResultSet::GetByte(), TSQLResultSet::GetByte(), ODBCCallableStatement::GetBytes(), ODBCResultSet::GetBytes(), TSQLResultSet::GetBytes(), ODBCConnection::GetCatalog(), TSQLConnection::GetCatalog(), ODBCResultSetMetaData::GetCatalogName(), TSQLResultSetMetaData::GetCatalogName(), TSQLDatabaseMetaData::GetCatalogs(), ODBCResultSetMetaData::GetColumnCount(), ODBCResultSetMetaData::GetColumnDisplaySize(), TSQLResultSetMetaData::GetColumnDisplaySize(), ODBCResultSetMetaData::GetColumnLabel(), TSQLResultSetMetaData::GetColumnLabel(), ODBCResultSetMetaData::GetColumnName(), TSQLResultSetMetaData::GetColumnName(), TSQLDatabaseMetaData::GetColumnPrivileges(), ODBCResultSetMetaData::GetColumnType(), TSQLResultSetMetaData::GetColumnType(), ODBCResultSetMetaData::GetColumnTypeName(), TSQLResultSetMetaData::GetColumnTypeName(), ODBCResultSet::GetConcurrency(), TSQLDriverManager::GetConnection(), ODBCResultSet::GetCursorName(), TSQLDriverManager::GetDataSources(), ODBCCallableStatement::GetDate(), ODBCResultSet::GetDate(), TSQLResultSet::GetDate(), ODBCCallableStatement::GetDouble(), ODBCResultSet::GetDouble(), TSQLResultSet::GetDouble(), TSQLDriverManager::GetDrivers(), ODBCStatement::GetEscapeProcessing(), ODBCPreparedStatement::GetEscapeProcessing(), ODBCCallableStatement::GetEscapeProcessing(), ODBCStatement::GetFetchSize(), ODBCPreparedStatement::GetFetchSize(), ODBCResultSet::GetFetchSize(), ODBCCallableStatement::GetFetchSize(), ODBCCallableStatement::GetFloat(), ODBCResultSet::GetFloat(), TSQLResultSet::GetFloat(), ODBCCallableStatement::GetInt(), ODBCResultSet::GetInt(), TSQLResultSet::GetInt(), ODBCCallableStatement::GetLong(), ODBCResultSet::GetLong(), TSQLResultSet::GetLong(), ODBCStatement::GetMaxFieldSize(), ODBCPreparedStatement::GetMaxFieldSize(), ODBCCallableStatement::GetMaxFieldSize(), ODBCStatement::GetMaxRows(), ODBCPreparedStatement::GetMaxRows(), ODBCCallableStatement::GetMaxRows(), ODBCConnection::GetMetaData(), ODBCStatement::GetMoreResults(), ODBCPreparedStatement::GetMoreResults(), ODBCCallableStatement::GetMoreResults(), TSQLResultSet::GetObject(), ODBCResultSetMetaData::GetPrecision(), TSQLResultSetMetaData::GetPrecision(), TSQLDatabaseMetaData::GetProcedureColumns(), TSQLDatabaseMetaData::GetProcedures(), ODBCStatement::GetQueryTimeout(), ODBCPreparedStatement::GetQueryTimeout(), ODBCCallableStatement::GetQueryTimeout(), ODBCStatement::GetResultSet(), ODBCPreparedStatement::GetResultSet(), ODBCCallableStatement::GetResultSet(), ODBCStatement::GetResultSetConcurrency(), ODBCPreparedStatement::GetResultSetConcurrency(), ODBCCallableStatement::GetResultSetConcurrency(), ODBCStatement::GetResultSetType(), ODBCPreparedStatement::GetResultSetType(), ODBCCallableStatement::GetResultSetType(), ODBCResultSet::GetRow(), ODBCResultSetMetaData::GetScale(), TSQLResultSetMetaData::GetScale(), ODBCResultSetMetaData::GetSchemaName(), TSQLResultSetMetaData::GetSchemaName(), ODBCCallableStatement::GetShort(), ODBCResultSet::GetShort(), TSQLResultSet::GetShort(), ODBCCallableStatement::GetString(), ODBCResultSet::GetString(), TSQLResultSet::GetString(), ODBCResultSetMetaData::GetTableName(), TSQLResultSetMetaData::GetTableName(), TSQLDatabaseMetaData::GetTablePrivileges(), TSQLDatabaseMetaData::GetTables(), ODBCCallableStatement::GetTime(), ODBCResultSet::GetTime(), TSQLResultSet::GetTime(), ODBCCallableStatement::GetTimestamp(), ODBCResultSet::GetTimestamp(), TSQLResultSet::GetTimestamp(), ODBCConnection::GetTrace(), TSQLConnection::GetTrace(), ODBCConnection::GetTraceFile(), TSQLConnection::GetTraceFile(), ODBCConnection::GetTransactionIsolation(), ODBCResultSet::GetType(), ODBCStatement::GetUpdateCount(), ODBCPreparedStatement::GetUpdateCount(), ODBCCallableStatement::GetUpdateCount(), TSQLDatabaseMetaData::GetVersionColumns(), ODBCResultSet::InsertRow(), ODBCResultSet::IsAfterLast(), ODBCResultSetMetaData::IsAutoIncrement(), TSQLResultSetMetaData::IsAutoIncrement(), ODBCResultSet::IsBeforeFirst(), ODBCResultSetMetaData::IsCaseSensitive(), TSQLResultSetMetaData::IsCaseSensitive(), ODBCResultSetMetaData::IsCurrency(), TSQLResultSetMetaData::IsCurrency(), ODBCResultSetMetaData::IsDefinitelyWritable(), TSQLResultSetMetaData::IsDefinitelyWritable(), ODBCResultSet::IsFirst(), ODBCResultSet::IsLast(), ODBCResultSetMetaData::IsNullable(), TSQLResultSetMetaData::IsNullable(), ODBCConnection::IsReadOnly(), ODBCResultSetMetaData::IsReadOnly(), TSQLResultSetMetaData::IsReadOnly(), ODBCResultSetMetaData::IsSearchable(), TSQLResultSetMetaData::IsSearchable(), ODBCResultSetMetaData::IsSigned(), TSQLResultSetMetaData::IsSigned(), ODBCResultSetMetaData::IsWritable(), TSQLResultSetMetaData::IsWritable(), ODBCResultSet::Last(), ODBCResultSet::MoveToCurrentRow(), ODBCResultSet::MoveToInsertRow(), ODBCConnection::NativeSQL(), ODBCResultSet::Next(), ODBCConnection::ODBCConnection(), ODBCResultSet::ODBCResultSet(), ODBCConnection::PrepareCall(), TSQLConnection::PrepareCall(), ODBCConnection::PrepareStatement(), ODBCResultSet::Previous(), TSQLResultSet::Print(), ODBCConnection::RefreshDataSources(), ODBCConnection::RefreshDrivers(), ODBCResultSet::RefreshRow(), ODBCCallableStatement::RegisterOutParameter(), ODBCResultSet::Relative(), ODBCConnection::Rollback(), TSQLConnection::Rollback(), ODBCResultSet::RowDeleted(), ODBCResultSet::RowInserted(), ODBCResultSet::RowUpdated(), ODBCPreparedStatement::SetAsciiStream(), ODBCCallableStatement::SetAsciiStream(), ODBCConnection::SetAutoCommit(), TSQLConnection::SetAutoCommit(), ODBCPreparedStatement::SetBinaryStream(), ODBCCallableStatement::SetBinaryStream(), ODBCPreparedStatement::SetBoolean(), ODBCCallableStatement::SetBoolean(), ODBCPreparedStatement::SetByte(), ODBCCallableStatement::SetByte(), ODBCPreparedStatement::SetBytes(), ODBCCallableStatement::SetBytes(), ODBCConnection::SetCatalog(), TSQLConnection::SetCatalog(), ODBCStatement::SetCursorName(), ODBCPreparedStatement::SetCursorName(), ODBCCallableStatement::SetCursorName(), ODBCPreparedStatement::SetDate(), ODBCCallableStatement::SetDate(), ODBCPreparedStatement::SetDouble(), ODBCCallableStatement::SetDouble(), ODBCStatement::SetEscapeProcessing(), ODBCPreparedStatement::SetEscapeProcessing(), ODBCCallableStatement::SetEscapeProcessing(), ODBCResultSet::SetFetchSize(), ODBCPreparedStatement::SetFloat(), ODBCCallableStatement::SetFloat(), ODBCPreparedStatement::SetInt(), ODBCCallableStatement::SetInt(), ODBCPreparedStatement::SetLong(), ODBCCallableStatement::SetLong(), ODBCStatement::SetMaxFieldSize(), ODBCPreparedStatement::SetMaxFieldSize(), ODBCCallableStatement::SetMaxFieldSize(), ODBCStatement::SetMaxRows(), ODBCPreparedStatement::SetMaxRows(), ODBCCallableStatement::SetMaxRows(), ODBCPreparedStatement::SetNull(), ODBCCallableStatement::SetNull(), ODBCStatement::SetQueryTimeout(), ODBCPreparedStatement::SetQueryTimeout(), ODBCCallableStatement::SetQueryTimeout(), ODBCConnection::SetReadOnly(), TSQLConnection::SetReadOnly(), ODBCPreparedStatement::SetShort(), ODBCCallableStatement::SetShort(), ODBCPreparedStatement::SetString(), ODBCCallableStatement::SetString(), ODBCPreparedStatement::SetTime(), ODBCCallableStatement::SetTime(), ODBCPreparedStatement::SetTimestamp(), ODBCCallableStatement::SetTimestamp(), ODBCConnection::SetTrace(), TSQLConnection::SetTrace(), ODBCConnection::SetTraceFile(), TSQLConnection::SetTraceFile(), ODBCConnection::SetTransactionIsolation(), TSQLConnection::SetTransactionIsolation(), ODBCConnection::Shutdown(), TSQLConnection::TSQLConnection(), ODBCResultSet::UpdateAsciiStream(), ODBCResultSet::UpdateBinaryStream(), ODBCResultSet::UpdateBoolean(), ODBCResultSet::UpdateByte(), ODBCResultSet::UpdateBytes(), ODBCResultSet::UpdateDate(), ODBCResultSet::UpdateDouble(), ODBCResultSet::UpdateFloat(), ODBCResultSet::UpdateInt(), ODBCResultSet::UpdateLong(), ODBCResultSet::UpdateNull(), ODBCResultSet::UpdateRow(), ODBCResultSet::UpdateShort(), ODBCResultSet::UpdateString(), ODBCResultSet::UpdateTime(), ODBCResultSet::UpdateTimestamp(), ODBCCallableStatement::WasNull(), ODBCResultSet::WasNull(), ODBCCallableStatement::~ODBCCallableStatement(), ODBCConnection::~ODBCConnection(), ODBCPreparedStatement::~ODBCPreparedStatement(), ODBCResultSet::~ODBCResultSet(), ODBCResultSetMetaData::~ODBCResultSetMetaData(), and ODBCStatement::~ODBCStatement().
Bool_t TSQL::UnsetHandler (const TString & handler = "") static
Definition at line 170 of file TSQL.cxx.
View newest version in sPHENIX GitHub at line 170 of file TSQL.cxx
Referenced by RDBCBench::DropDatabase(), oproducer(), and SetHandler().
Member Data Documentation
void* TSQL::fImp protected
Definition at line 54 of file TSQL.h.
View newest version in sPHENIX GitHub at line 54 of file TSQL.h
Referenced by ODBCResultSet::Absolute(), ODBCResultSet::AfterLast(), TSQLResultSet::AfterLast(), ODBCResultSet::BeforeFirst(), TSQLResultSet::BeforeFirst(), ODBCStatement::Cancel(), ODBCPreparedStatement::Cancel(), ODBCCallableStatement::Cancel(), ODBCResultSet::CancelRowUpdates(), ClassImpQ(), ODBCPreparedStatement::ClearParameters(), ODBCCallableStatement::ClearParameters(), ODBCConnection::Close(), ODBCStatement::Close(), TSQLStatement::Close(), ODBCPreparedStatement::Close(), ODBCCallableStatement::Close(), TSQLConnection::Close(), ODBCResultSet::Close(), TSQLResultSet::Close(), ODBCConnection::Commit(), ODBCConnection::CreateStatement(), ODBCResultSet::DeleteRow(), ODBCStatement::Execute(), TSQLStatement::Execute(), ODBCPreparedStatement::Execute(), ODBCCallableStatement::Execute(), ODBCStatement::ExecuteQuery(), TSQLStatement::ExecuteQuery(), ODBCPreparedStatement::ExecuteQuery(), ODBCCallableStatement::ExecuteQuery(), ODBCStatement::ExecuteUpdate(), ODBCPreparedStatement::ExecuteUpdate(), ODBCCallableStatement::ExecuteUpdate(), ODBCResultSet::FindColumn(), TSQLResultSet::FindColumn(), ODBCResultSet::First(), TSQLResultSet::First(), ODBCResultSet::GetAsciiStream(), TSQLResultSet::GetAsciiStream(), ODBCConnection::GetAutoCommit(), TSQLDatabaseMetaData::GetBestRowIdentifier(), ODBCResultSet::GetBinaryStream(), TSQLResultSet::GetBinaryStream(), ODBCCallableStatement::GetBoolean(), ODBCResultSet::GetBoolean(), TSQLResultSet::GetBoolean(), ODBCCallableStatement::GetByte(), ODBCResultSet::GetByte(), TSQLResultSet::GetByte(), ODBCCallableStatement::GetBytes(), ODBCResultSet::GetBytes(), TSQLResultSet::GetBytes(), ODBCConnection::GetCatalog(), TSQLConnection::GetCatalog(), ODBCResultSetMetaData::GetCatalogName(), TSQLResultSetMetaData::GetCatalogName(), TSQLDatabaseMetaData::GetCatalogs(), ODBCResultSetMetaData::GetColumnCount(), TSQLResultSetMetaData::GetColumnCount(), ODBCResultSetMetaData::GetColumnDisplaySize(), TSQLResultSetMetaData::GetColumnDisplaySize(), ODBCResultSetMetaData::GetColumnLabel(), TSQLResultSetMetaData::GetColumnLabel(), ODBCResultSetMetaData::GetColumnName(), TSQLResultSetMetaData::GetColumnName(), TSQLDatabaseMetaData::GetColumnPrivileges(), TSQLDatabaseMetaData::GetColumns(), ODBCResultSetMetaData::GetColumnType(), TSQLResultSetMetaData::GetColumnType(), ODBCResultSetMetaData::GetColumnTypeName(), TSQLResultSetMetaData::GetColumnTypeName(), ODBCResultSet::GetConcurrency(), TSQLDriverManager::GetConnection(), TSQLDatabaseMetaData::GetCrossReference(), ODBCResultSet::GetCursorName(), TSQLDatabaseMetaData::GetDatabaseProductVersion(), ODBCCallableStatement::GetDate(), ODBCResultSet::GetDate(), TSQLResultSet::GetDate(), ODBCCallableStatement::GetDouble(), ODBCResultSet::GetDouble(), TSQLResultSet::GetDouble(), ODBCStatement::GetEscapeProcessing(), TSQLStatement::GetEscapeProcessing(), ODBCPreparedStatement::GetEscapeProcessing(), ODBCCallableStatement::GetEscapeProcessing(), TSQLDatabaseMetaData::GetExportedKeys(), ODBCStatement::GetFetchSize(), ODBCPreparedStatement::GetFetchSize(), ODBCResultSet::GetFetchSize(), ODBCCallableStatement::GetFetchSize(), TSQLResultSet::GetFieldCount(), TSQLResultSet::GetFieldName(), ODBCCallableStatement::GetFloat(), ODBCResultSet::GetFloat(), TSQLResultSet::GetFloat(), TSQLDatabaseMetaData::GetIndexInfo(), ODBCCallableStatement::GetInt(), ODBCResultSet::GetInt(), TSQLResultSet::GetInt(), ODBCCallableStatement::GetLong(), ODBCResultSet::GetLong(), TSQLResultSet::GetLong(), ODBCStatement::GetMaxFieldSize(), TSQLStatement::GetMaxFieldSize(), ODBCPreparedStatement::GetMaxFieldSize(), ODBCCallableStatement::GetMaxFieldSize(), ODBCStatement::GetMaxRows(), TSQLStatement::GetMaxRows(), ODBCPreparedStatement::GetMaxRows(), ODBCCallableStatement::GetMaxRows(), ODBCConnection::GetMetaData(), TSQLResultSet::GetMetaData(), ODBCStatement::GetMoreResults(), ODBCPreparedStatement::GetMoreResults(), ODBCCallableStatement::GetMoreResults(), TSQLResultSet::GetObject(), ODBCResultSetMetaData::GetPrecision(), TSQLResultSetMetaData::GetPrecision(), TSQLDatabaseMetaData::GetPrimaryKeys(), ODBCStatement::GetQueryTimeout(), TSQLStatement::GetQueryTimeout(), ODBCPreparedStatement::GetQueryTimeout(), ODBCCallableStatement::GetQueryTimeout(), ODBCStatement::GetResultSet(), ODBCPreparedStatement::GetResultSet(), ODBCCallableStatement::GetResultSet(), ODBCStatement::GetResultSetConcurrency(), ODBCPreparedStatement::GetResultSetConcurrency(), ODBCCallableStatement::GetResultSetConcurrency(), ODBCStatement::GetResultSetType(), TSQLStatement::GetResultSetType(), ODBCPreparedStatement::GetResultSetType(), ODBCCallableStatement::GetResultSetType(), ODBCResultSet::GetRow(), TSQLResultSet::GetRow(), ODBCResultSetMetaData::GetScale(), TSQLResultSetMetaData::GetScale(), ODBCResultSetMetaData::GetSchemaName(), TSQLResultSetMetaData::GetSchemaName(), TSQLDatabaseMetaData::GetSchemas(), ODBCCallableStatement::GetShort(), ODBCResultSet::GetShort(), TSQLResultSet::GetShort(), ODBCCallableStatement::GetString(), ODBCResultSet::GetString(), TSQLResultSet::GetString(), ODBCResultSetMetaData::GetTableName(), TSQLResultSetMetaData::GetTableName(), TSQLDatabaseMetaData::GetTablePrivileges(), TSQLDatabaseMetaData::GetTables(), TSQLDatabaseMetaData::GetTableTypes(), ODBCCallableStatement::GetTime(), ODBCResultSet::GetTime(), TSQLResultSet::GetTime(), ODBCCallableStatement::GetTimestamp(), ODBCResultSet::GetTimestamp(), TSQLResultSet::GetTimestamp(), ODBCConnection::GetTrace(), ODBCConnection::GetTraceFile(), ODBCConnection::GetTransactionIsolation(), ODBCResultSet::GetType(), TSQLDatabaseMetaData::GetTypeInfo(), ODBCStatement::GetUpdateCount(), ODBCPreparedStatement::GetUpdateCount(), ODBCCallableStatement::GetUpdateCount(), TSQLDatabaseMetaData::GetVersionColumns(), ODBCResultSet::InsertRow(), ODBCResultSet::IsAfterLast(), TSQLResultSet::IsAfterLast(), ODBCResultSetMetaData::IsAutoIncrement(), TSQLResultSetMetaData::IsAutoIncrement(), ODBCResultSet::IsBeforeFirst(), TSQLResultSet::IsBeforeFirst(), ODBCResultSetMetaData::IsCaseSensitive(), TSQLResultSetMetaData::IsCaseSensitive(), TSQLConnection::IsClosed(), ODBCResultSetMetaData::IsCurrency(), TSQLResultSetMetaData::IsCurrency(), ODBCResultSetMetaData::IsDefinitelyWritable(), TSQLResultSetMetaData::IsDefinitelyWritable(), ODBCResultSet::IsFirst(), TSQLResultSet::IsFirst(), ODBCResultSet::IsLast(), TSQLResultSet::IsLast(), ODBCResultSetMetaData::IsNullable(), TSQLResultSetMetaData::IsNullable(), ODBCConnection::IsReadOnly(), ODBCResultSetMetaData::IsReadOnly(), TSQLResultSetMetaData::IsReadOnly(), TSQLConnection::IsReadOnly(), ODBCResultSetMetaData::IsSearchable(), TSQLResultSetMetaData::IsSearchable(), ODBCResultSetMetaData::IsSigned(), TSQLResultSetMetaData::IsSigned(), IsValid(), ODBCResultSetMetaData::IsWritable(), TSQLResultSetMetaData::IsWritable(), ODBCResultSet::Last(), ODBCResultSet::MoveToCurrentRow(), ODBCResultSet::MoveToInsertRow(), ODBCConnection::NativeSQL(), ODBCResultSet::Next(), TSQLResultSet::Next(), ODBCConnection::ODBCConnection(), ODBCResultSet::ODBCResultSet(), ODBCConnection::PrepareCall(), ODBCConnection::PrepareStatement(), ODBCResultSet::Previous(), TSQLResultSet::Print(), ODBCResultSet::RefreshRow(), ODBCCallableStatement::RegisterOutParameter(), ODBCResultSet::Relative(), ODBCConnection::Rollback(), ODBCResultSet::RowDeleted(), ODBCResultSet::RowInserted(), ODBCResultSet::RowUpdated(), TSQLDatabaseMetaData::Set(), ODBCPreparedStatement::SetAsciiStream(), ODBCCallableStatement::SetAsciiStream(), ODBCConnection::SetAutoCommit(), ODBCPreparedStatement::SetBinaryStream(), ODBCCallableStatement::SetBinaryStream(), ODBCPreparedStatement::SetBoolean(), ODBCCallableStatement::SetBoolean(), ODBCPreparedStatement::SetByte(), ODBCCallableStatement::SetByte(), ODBCPreparedStatement::SetBytes(), ODBCCallableStatement::SetBytes(), ODBCConnection::SetCatalog(), TSQLConnection::SetCatalog(), ODBCStatement::SetCursorName(), ODBCPreparedStatement::SetCursorName(), ODBCCallableStatement::SetCursorName(), ODBCPreparedStatement::SetDate(), ODBCCallableStatement::SetDate(), ODBCPreparedStatement::SetDouble(), ODBCCallableStatement::SetDouble(), ODBCStatement::SetEscapeProcessing(), TSQLStatement::SetEscapeProcessing(), ODBCPreparedStatement::SetEscapeProcessing(), ODBCCallableStatement::SetEscapeProcessing(), ODBCStatement::SetFetchDirection(), ODBCPreparedStatement::SetFetchDirection(), ODBCCallableStatement::SetFetchDirection(), ODBCStatement::SetFetchSize(), ODBCResultSet::SetFetchSize(), ODBCPreparedStatement::SetFetchSize(), ODBCCallableStatement::SetFetchSize(), ODBCPreparedStatement::SetFloat(), ODBCCallableStatement::SetFloat(), ODBCPreparedStatement::SetInt(), ODBCCallableStatement::SetInt(), ODBCPreparedStatement::SetLong(), ODBCCallableStatement::SetLong(), ODBCStatement::SetMaxFieldSize(), TSQLStatement::SetMaxFieldSize(), ODBCPreparedStatement::SetMaxFieldSize(), ODBCCallableStatement::SetMaxFieldSize(), ODBCStatement::SetMaxRows(), TSQLStatement::SetMaxRows(), ODBCPreparedStatement::SetMaxRows(), ODBCCallableStatement::SetMaxRows(), ODBCPreparedStatement::SetNull(), ODBCCallableStatement::SetNull(), ODBCStatement::SetQueryTimeout(), TSQLStatement::SetQueryTimeout(), ODBCPreparedStatement::SetQueryTimeout(), ODBCCallableStatement::SetQueryTimeout(), ODBCConnection::SetReadOnly(), TSQLConnection::SetReadOnly(), ODBCPreparedStatement::SetShort(), ODBCCallableStatement::SetShort(), ODBCPreparedStatement::SetString(), ODBCCallableStatement::SetString(), ODBCPreparedStatement::SetTime(), ODBCCallableStatement::SetTime(), ODBCPreparedStatement::SetTimestamp(), ODBCCallableStatement::SetTimestamp(), ODBCConnection::SetTrace(), ODBCConnection::SetTraceFile(), TSQLConnection::SetURL(), TSQL(), TSQLConnection::TSQLConnection(), TSQLResultSet::TSQLResultSet(), ODBCResultSet::UpdateAsciiStream(), ODBCResultSet::UpdateBinaryStream(), ODBCResultSet::UpdateBoolean(), ODBCResultSet::UpdateByte(), ODBCResultSet::UpdateBytes(), ODBCResultSet::UpdateDate(), ODBCResultSet::UpdateDouble(), ODBCResultSet::UpdateFloat(), ODBCResultSet::UpdateInt(), ODBCResultSet::UpdateLong(), ODBCResultSet::UpdateNull(), ODBCResultSet::UpdateRow(), ODBCResultSet::UpdateShort(), ODBCResultSet::UpdateString(), ODBCResultSet::UpdateTime(), ODBCResultSet::UpdateTimestamp(), ODBCCallableStatement::WasNull(), ODBCResultSet::WasNull(), TSQLResultSet::WasNull(), ODBCCallableStatement::~ODBCCallableStatement(), ODBCConnection::~ODBCConnection(), ODBCPreparedStatement::~ODBCPreparedStatement(), ODBCResultSet::~ODBCResultSet(), ODBCResultSetMetaData::~ODBCResultSetMetaData(), ODBCStatement::~ODBCStatement(), TSQLDatabaseMetaData::~TSQLDatabaseMetaData(), TSQLResultSet::~TSQLResultSet(), TSQLResultSetMetaData::~TSQLResultSetMetaData(), and TSQLStatement::~TSQLStatement().
TList* TSQL::fWarnings protected
Definition at line 53 of file TSQL.h.
View newest version in sPHENIX GitHub at line 53 of file TSQL.h
Referenced by ClearWarnings(), GetWarnings(), Throw(), TSQL(), and ~TSQL().
The documentation for this class was generated from the following files:
RDBC/blob/master/include/RDBC/TSQL.h
RDBC/blob/master/rdbc/TSQL.cxx