Analysis Software: TrkrClusterContainerv1 Class Reference
TrkrClusterContainerv1 Class Reference
Cluster container object.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainerv1.h>
Public Types
typedef std::map
< TrkrDefs::cluskey,
TrkrCluster * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Types inherited from TrkrClusterContainer
using Map = std::map< TrkrDefs::cluskey, TrkrCluster * >
using Iterator = Map::iterator
using ConstIterator = Map::const_iterator
using Range = std::pair< Iterator, Iterator >
using ConstRange = std::pair< ConstIterator, ConstIterator >
using HitSetKeyList = std::vector< TrkrDefs::hitsetkey >
Public Member Functions
TrkrClusterContainerv1 ()=default
void Reset () override
reset method
void identify (std::ostream &os=std::cout) const override
identify object
void addClusterSpecifyKey (const TrkrDefs::cluskey key, TrkrCluster *newClus) override
add a cluster with specific key
void removeCluster (TrkrDefs::cluskey) override
remove cluster
ConstRange getClusters () const override
return all clusters
TrkrCluster * findCluster (TrkrDefs::cluskey key) const override
find cluster matching given key
unsigned int size () const override
total number of clusters
Public Member Functions inherited from TrkrClusterContainer
virtual ConstRange getClusters (TrkrDefs::hitsetkey)
get all clusters matching hitset
virtual HitSetKeyList getHitSetKeys () const
get hitset key list
virtual HitSetKeyList getHitSetKeys (const TrkrDefs::TrkrId) const
get hitset key list for a given detector
virtual HitSetKeyList getHitSetKeys (const TrkrDefs::TrkrId, const uint8_t) const
get hitset key list for a given detector and layer
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
Map m_clusmap
Additional Inherited Members
Protected Member Functions inherited from TrkrClusterContainer
TrkrClusterContainer ()=default
constructor
Detailed Description
Cluster container object.
Container for TrkrCluster objects
Definition at line 26 of file TrkrClusterContainerv1.h.
View newest version in sPHENIX GitHub at line 26 of file TrkrClusterContainerv1.h
Member Typedef Documentation
typedef Map::const_iterator TrkrClusterContainerv1::ConstIterator
Definition at line 31 of file TrkrClusterContainerv1.h.
View newest version in sPHENIX GitHub at line 31 of file TrkrClusterContainerv1.h
typedef std::pair<ConstIterator, ConstIterator> TrkrClusterContainerv1::ConstRange
Definition at line 33 of file TrkrClusterContainerv1.h.
View newest version in sPHENIX GitHub at line 33 of file TrkrClusterContainerv1.h
typedef Map::iterator TrkrClusterContainerv1::Iterator
Definition at line 30 of file TrkrClusterContainerv1.h.
View newest version in sPHENIX GitHub at line 30 of file TrkrClusterContainerv1.h
typedef std::map<TrkrDefs::cluskey, TrkrCluster *> TrkrClusterContainerv1::Map
Definition at line 29 of file TrkrClusterContainerv1.h.
View newest version in sPHENIX GitHub at line 29 of file TrkrClusterContainerv1.h
typedef std::pair<Iterator, Iterator> TrkrClusterContainerv1::Range
Definition at line 32 of file TrkrClusterContainerv1.h.
View newest version in sPHENIX GitHub at line 32 of file TrkrClusterContainerv1.h
Constructor & Destructor Documentation
TrkrClusterContainerv1::TrkrClusterContainerv1 () default
Member Function Documentation
void TrkrClusterContainerv1::addClusterSpecifyKey (const TrkrDefs::cluskey , TrkrCluster *) override virtual
add a cluster with specific key
Reimplemented from TrkrClusterContainer.
Definition at line 37 of file TrkrClusterContainerv1.cc.
View newest version in sPHENIX GitHub at line 37 of file TrkrClusterContainerv1.cc
References m_clusmap.
TrkrCluster * TrkrClusterContainerv1::findCluster (TrkrDefs::cluskey) const override virtual
find cluster matching given key
Reimplemented from TrkrClusterContainer.
Definition at line 59 of file TrkrClusterContainerv1.cc.
View newest version in sPHENIX GitHub at line 59 of file TrkrClusterContainerv1.cc
References it, and m_clusmap.
TrkrClusterContainer::ConstRange TrkrClusterContainerv1::getClusters (void) const override virtual
return all clusters
Reimplemented from TrkrClusterContainer.
Definition at line 53 of file TrkrClusterContainerv1.cc.
View newest version in sPHENIX GitHub at line 53 of file TrkrClusterContainerv1.cc
References m_clusmap.
Referenced by AnaMvtxTestBeam2019::process_event().
void TrkrClusterContainerv1::identify (std::ostream & = std::cout) const override virtual
identify object
Reimplemented from TrkrClusterContainer.
Definition at line 22 of file TrkrClusterContainerv1.cc.
View newest version in sPHENIX GitHub at line 22 of file TrkrClusterContainerv1.cc
References TrkrDefs::getLayer(), layer, m_clusmap, and size().
void TrkrClusterContainerv1::removeCluster (TrkrDefs::cluskey) override virtual
remove cluster
Reimplemented from TrkrClusterContainer.
Definition at line 47 of file TrkrClusterContainerv1.cc.
View newest version in sPHENIX GitHub at line 47 of file TrkrClusterContainerv1.cc
References m_clusmap.
void TrkrClusterContainerv1::Reset () override virtual
reset method
Reimplemented from TrkrClusterContainer.
Definition at line 12 of file TrkrClusterContainerv1.cc.
View newest version in sPHENIX GitHub at line 12 of file TrkrClusterContainerv1.cc
References m_clusmap.
unsigned int TrkrClusterContainerv1::size (void) const override virtual
total number of clusters
Reimplemented from TrkrClusterContainer.
Definition at line 65 of file TrkrClusterContainerv1.cc.
View newest version in sPHENIX GitHub at line 65 of file TrkrClusterContainerv1.cc
References m_clusmap.
Referenced by identify(), and AnaMvtxTestBeam2019::process_event().
Member Data Documentation
Map TrkrClusterContainerv1::m_clusmap private
Definition at line 52 of file TrkrClusterContainerv1.h.
View newest version in sPHENIX GitHub at line 52 of file TrkrClusterContainerv1.h
Referenced by addClusterSpecifyKey(), findCluster(), getClusters(), identify(), removeCluster(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainerv1.h
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainerv1.cc