Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Detector/SupportHelperTests.cpp File Reference
SupportHelperTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Detector/detail/SupportHelper.hpp"
#include "Acts/Geometry/Extent.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Surfaces/Surface.hpp"
#include "Acts/Surfaces/SurfaceBounds.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Utilities/BinningType.hpp"
#include <array>
#include <cmath>
#include <cstddef>
#include <memory>
#include <optional>
#include <stdexcept>
#include <vector>
Functions
BOOST_AUTO_TEST_CASE (CylindricalSupport)
BOOST_AUTO_TEST_CASE (DiscSupport)
BOOST_AUTO_TEST_CASE (addCylinderSupport)
BOOST_AUTO_TEST_CASE (addDiscSupport)
BOOST_AUTO_TEST_CASE (addMisconfiguredSupport)
Variables
Acts::GeometryContext tContext
Function Documentation
BOOST_AUTO_TEST_CASE (CylindricalSupport)
Definition at line 32 of file SupportHelperTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file SupportHelperTests.cpp
References Acts::Experimental::detail::SupportHelper::cylindricalSupport(), parse_cmake_options::type, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (DiscSupport)
Definition at line 61 of file SupportHelperTests.cpp.
View newest version in sPHENIX GitHub at line 61 of file SupportHelperTests.cpp
References Acts::Experimental::detail::SupportHelper::discSupport(), parse_cmake_options::type, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (addCylinderSupport)
Definition at line 86 of file SupportHelperTests.cpp.
View newest version in sPHENIX GitHub at line 86 of file SupportHelperTests.cpp
References Acts::Experimental::detail::SupportHelper::addSupport(), Acts::binR, Acts::binZ, bounds, CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::Extent::set(), physmon_ckf_tracking::u, and Acts::Test::values.
BOOST_AUTO_TEST_CASE (addDiscSupport)
Definition at line 122 of file SupportHelperTests.cpp.
View newest version in sPHENIX GitHub at line 122 of file SupportHelperTests.cpp
References Acts::Experimental::detail::SupportHelper::addSupport(), Acts::binR, Acts::binZ, CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::Extent::set(), Acts::Test::transform, translation(), physmon_ckf_tracking::u, and physmon_track_finding_ttbar::z.
BOOST_AUTO_TEST_CASE (addMisconfiguredSupport)
Definition at line 159 of file SupportHelperTests.cpp.
View newest version in sPHENIX GitHub at line 159 of file SupportHelperTests.cpp
References Acts::Experimental::detail::SupportHelper::addSupport(), Acts::binR, Acts::binZ, Acts::Extent::set(), and physmon_ckf_tracking::u.
Variable Documentation
Acts::GeometryContext tContext
Definition at line 28 of file SupportHelperTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file SupportHelperTests.cpp