Analysis Software: SvtxTrack_FastSim_v2 Exception Reference
SvtxTrack_FastSim_v2 Exception Reference final
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack_FastSim_v2.h>
Public Member Functions
SvtxTrack_FastSim_v2 ()=default
SvtxTrack_FastSim_v2 (const SvtxTrack &)
~SvtxTrack_FastSim_v2 () override=default
void CopyFrom (const SvtxTrack &) override
copy content from base class
void CopyFrom (SvtxTrack *source) override
copy content from base class
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
accessors
unsigned int get_truth_track_id () const override
unsigned int get_num_measurements () const override
const HitIdMap & g4hit_ids () const override
bool empty_g4hit_id () const override
size_t size_g4hit_id () const override
SvtxTrack::HitIdConstIter begin_g4hit_id () const override
SvtxTrack::HitIdConstIter end_g4hit_id () const override
SvtxTrack::HitIdConstIter find_g4hit_id (int volume) const override
modifiers
void set_truth_track_id (unsigned int truthTrackId) override
void set_num_measurements (int nmeas) override
void add_g4hit_id (int volume, PHG4HitDefs::keytype id) override
size_t remove_g4hit_id (int volume, PHG4HitDefs::keytype id) override
size_t remove_g4hit_volume (int volume) override
SvtxTrack::HitIdIter begin_g4hit_id () override
SvtxTrack::HitIdIter end_g4hit_id () override
SvtxTrack::HitIdIter find_g4hit_id (int volume) override
void clear_g4hit_id () override
Public Member Functions inherited from SvtxTrack_v2
SvtxTrack_v2 ()
SvtxTrack_v2 (const SvtxTrack &)
SvtxTrack_v2 (const SvtxTrack_v2 &)
SvtxTrack_v2 & operator= (const SvtxTrack_v2 &track)
~SvtxTrack_v2 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void CopyFrom (const SvtxTrack &) override
copy content from base class
void CopyFrom (SvtxTrack *source) override
copy content from base class
unsigned int get_id () const override
void set_id (unsigned int id) override
unsigned int get_vertex_id () const override
void set_vertex_id (unsigned int id) override
bool get_positive_charge () const override
void set_positive_charge (bool ispos) override
int get_charge () const override
void set_charge (int charge) override
float get_chisq () const override
void set_chisq (float chisq) override
unsigned int get_ndf () const override
void set_ndf (int ndf) override
float get_quality () const override
float get_dca () const override
void set_dca (float dca) override
float get_dca_error () const override
void set_dca_error (float dca_error) override
float get_dca2d () const override
void set_dca2d (float dca2d) override
float get_dca2d_error () const override
void set_dca2d_error (float error) override
float get_dca3d_xy () const override
void set_dca3d_xy (float dcaxy) override
float get_dca3d_xy_error () const override
void set_dca3d_xy_error (float error) override
float get_dca3d_z () const override
void set_dca3d_z (float dcaz) override
float get_dca3d_z_error () const override
void set_dca3d_z_error (float error) override
float get_x () const override
void set_x (float x) override
float get_y () const override
void set_y (float y) override
float get_z () const override
void set_z (float z) override
float get_pos (unsigned int i) const override
float get_px () const override
void set_px (float px) override
float get_py () const override
void set_py (float py) override
float get_pz () const override
void set_pz (float pz) override
float get_mom (unsigned int i) const override
float get_p () const override
float get_pt () const override
float get_eta () const override
float get_phi () const override
float get_error (int i, int j) const override
void set_error (int i, int j, float value) override
bool empty_states () const override
size_t size_states () const override
size_t count_states (float pathlength) const override
void clear_states () override
const SvtxTrackState * get_state (float pathlength) const override
SvtxTrackState * get_state (float pathlength) override
SvtxTrackState * insert_state (const SvtxTrackState *state) override
size_t erase_state (float pathlength) override
ConstStateIter begin_states () const override
ConstStateIter find_state (float pathlength) const override
ConstStateIter end_states () const override
StateIter begin_states () override
StateIter find_state (float pathlength) override
StateIter end_states () override
void clear_clusters () override
bool empty_clusters () const override
size_t size_clusters () const override
void insert_cluster (unsigned int clusterid) override
size_t erase_cluster (unsigned int clusterid) override
ConstClusterIter begin_clusters () const override
ConstClusterIter find_cluster (unsigned int clusterid) const override
ConstClusterIter end_clusters () const override
ClusterIter find_cluster (unsigned int clusterid) override
ClusterIter begin_clusters () override
ClusterIter end_clusters () override
void clear_cluster_keys () override
bool empty_cluster_keys () const override
size_t size_cluster_keys () const override
void insert_cluster_key (TrkrDefs::cluskey clusterid) override
size_t erase_cluster_key (TrkrDefs::cluskey clusterid) override
ConstClusterKeyIter find_cluster_key (TrkrDefs::cluskey clusterid) const override
ConstClusterKeyIter begin_cluster_keys () const override
ConstClusterKeyIter end_cluster_keys () const override
ClusterKeyIter find_cluster_keys (unsigned int clusterid) override
ClusterKeyIter begin_cluster_keys () override
ClusterKeyIter end_cluster_keys () override
float get_cal_dphi (CAL_LAYER layer) const override
void set_cal_dphi (CAL_LAYER layer, float dphi) override
float get_cal_deta (CAL_LAYER layer) const override
void set_cal_deta (CAL_LAYER layer, float deta) override
float get_cal_energy_3x3 (CAL_LAYER layer) const override
void set_cal_energy_3x3 (CAL_LAYER layer, float energy_3x3) override
float get_cal_energy_5x5 (CAL_LAYER layer) const override
void set_cal_energy_5x5 (CAL_LAYER layer, float energy_5x5) override
unsigned int get_cal_cluster_id (CAL_LAYER layer) const override
void set_cal_cluster_id (CAL_LAYER layer, unsigned int id) override
TrkrDefs::cluskey get_cal_cluster_key (CAL_LAYER layer) const override
void set_cal_cluster_key (CAL_LAYER layer, TrkrDefs::cluskey id) override
float get_cal_cluster_e (CAL_LAYER layer) const override
void set_cal_cluster_e (CAL_LAYER layer, float e) override
float get_acts_covariance (unsigned int i, unsigned int j) const override
void set_acts_covariance (unsigned int i, unsigned int j, float value) override
Public Member Functions inherited from SvtxTrack
~SvtxTrack () override=default
virtual TrackSeed * get_tpc_seed () const
virtual void set_tpc_seed (TrackSeed *)
virtual TrackSeed * get_silicon_seed () const
virtual void set_silicon_seed (TrackSeed *)
virtual short int get_crossing () const
virtual void set_crossing (short int)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
unsigned int _truth_track_id = UINT_MAX
unsigned int _nmeas = 0
HitIdMap _g4hit_ids
Additional Inherited Members
Public Types inherited from SvtxTrack
enum CAL_LAYER {
PRES = 0, CEMC = 1, HCALIN = 2, HCALOUT = 3,
OUTER_CEMC = 4, OUTER_HCALIN = 5, OUTER_HCALOUT = 6
}
typedef std::map< float,
SvtxTrackState * > StateMap
typedef StateMap::const_iterator ConstStateIter
typedef StateMap::iterator StateIter
typedef std::set< unsigned int > ClusterSet
typedef ClusterSet::const_iterator ConstClusterIter
typedef ClusterSet::iterator ClusterIter
typedef std::set
< TrkrDefs::cluskey > ClusterKeySet
typedef
ClusterKeySet::const_iterator ConstClusterKeyIter
typedef ClusterKeySet::iterator ClusterKeyIter
typedef std::map< int,
std::set< PHG4HitDefs::keytype > > HitIdMap
typedef HitIdMap::iterator HitIdIter
typedef HitIdMap::const_iterator HitIdConstIter
Protected Member Functions inherited from SvtxTrack
SvtxTrack ()
ClassDefOverride (SvtxTrack, 1)
Detailed Description
Definition at line 11 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 11 of file SvtxTrack_FastSim_v2.h
Constructor & Destructor Documentation
SvtxTrack_FastSim_v2::SvtxTrack_FastSim_v2 () default
Referenced by CloneMe(), and Reset().
SvtxTrack_FastSim_v2::SvtxTrack_FastSim_v2 (const SvtxTrack & source)
Definition at line 15 of file SvtxTrack_FastSim_v2.cc.
View newest version in sPHENIX GitHub at line 15 of file SvtxTrack_FastSim_v2.cc
References CopyFrom().
SvtxTrack_FastSim_v2::~SvtxTrack_FastSim_v2 () override default
Member Function Documentation
void SvtxTrack_FastSim_v2::add_g4hit_id (int volume, PHG4HitDefs::keytype id) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 76 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 76 of file SvtxTrack_FastSim_v2.h
References _g4hit_ids.
SvtxTrack::HitIdConstIter SvtxTrack_FastSim_v2::begin_g4hit_id () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 55 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 55 of file SvtxTrack_FastSim_v2.h
References _g4hit_ids.
SvtxTrack::HitIdIter SvtxTrack_FastSim_v2::begin_g4hit_id () inline override virtual
Reimplemented from SvtxTrack.
Definition at line 85 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 85 of file SvtxTrack_FastSim_v2.h
References _g4hit_ids.
void SvtxTrack_FastSim_v2::clear_g4hit_id () inline override virtual
Reimplemented from SvtxTrack.
Definition at line 94 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 94 of file SvtxTrack_FastSim_v2.h
References _g4hit_ids.
PHObject* SvtxTrack_FastSim_v2::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from SvtxTrack.
Definition at line 34 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 34 of file SvtxTrack_FastSim_v2.h
References SvtxTrack_FastSim_v2().
void SvtxTrack_FastSim_v2::CopyFrom (const SvtxTrack &) override virtual
copy content from base class
Reimplemented from SvtxTrack.
Definition at line 18 of file SvtxTrack_FastSim_v2.cc.
View newest version in sPHENIX GitHub at line 18 of file SvtxTrack_FastSim_v2.cc
References _g4hit_ids, _nmeas, _truth_track_id, SvtxTrack_v2::CopyFrom(), SvtxTrack::g4hit_ids(), SvtxTrack::get_num_measurements(), and SvtxTrack::get_truth_track_id().
Referenced by SvtxTrack_FastSim_v2().
void SvtxTrack_FastSim_v2::CopyFrom (SvtxTrack *) inline override virtual
copy content from base class
Reimplemented from SvtxTrack.
Definition at line 26 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 26 of file SvtxTrack_FastSim_v2.h
References CopyFrom().
Referenced by CopyFrom().
bool SvtxTrack_FastSim_v2::empty_g4hit_id () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 49 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 49 of file SvtxTrack_FastSim_v2.h
References _g4hit_ids.
SvtxTrack::HitIdConstIter SvtxTrack_FastSim_v2::end_g4hit_id () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 58 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 58 of file SvtxTrack_FastSim_v2.h
References _g4hit_ids.
SvtxTrack::HitIdIter SvtxTrack_FastSim_v2::end_g4hit_id () inline override virtual
Reimplemented from SvtxTrack.
Definition at line 88 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 88 of file SvtxTrack_FastSim_v2.h
References _g4hit_ids.
SvtxTrack::HitIdConstIter SvtxTrack_FastSim_v2::find_g4hit_id (int volume) const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 61 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 61 of file SvtxTrack_FastSim_v2.h
References _g4hit_ids.
SvtxTrack::HitIdIter SvtxTrack_FastSim_v2::find_g4hit_id (int volume) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 91 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 91 of file SvtxTrack_FastSim_v2.h
References _g4hit_ids.
const HitIdMap& SvtxTrack_FastSim_v2::g4hit_ids () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 46 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 46 of file SvtxTrack_FastSim_v2.h
References _g4hit_ids.
unsigned int SvtxTrack_FastSim_v2::get_num_measurements () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 43 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 43 of file SvtxTrack_FastSim_v2.h
References _nmeas.
unsigned int SvtxTrack_FastSim_v2::get_truth_track_id () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 40 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 40 of file SvtxTrack_FastSim_v2.h
References _truth_track_id.
void SvtxTrack_FastSim_v2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxTrack.
Definition at line 32 of file SvtxTrack_FastSim_v2.cc.
View newest version in sPHENIX GitHub at line 32 of file SvtxTrack_FastSim_v2.cc
References _g4hit_ids, _nmeas, _truth_track_id, and SvtxTrack_v2::identify().
int SvtxTrack_FastSim_v2::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxTrack.
Definition at line 51 of file SvtxTrack_FastSim_v2.cc.
View newest version in sPHENIX GitHub at line 51 of file SvtxTrack_FastSim_v2.cc
size_t SvtxTrack_FastSim_v2::remove_g4hit_id (int volume, PHG4HitDefs::keytype id) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 79 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 79 of file SvtxTrack_FastSim_v2.h
References _g4hit_ids.
size_t SvtxTrack_FastSim_v2::remove_g4hit_volume (int volume) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 82 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 82 of file SvtxTrack_FastSim_v2.h
References _g4hit_ids.
void SvtxTrack_FastSim_v2::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 31 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 31 of file SvtxTrack_FastSim_v2.h
References SvtxTrack_FastSim_v2().
void SvtxTrack_FastSim_v2::set_num_measurements (int nmeas) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 73 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 73 of file SvtxTrack_FastSim_v2.h
References _nmeas.
void SvtxTrack_FastSim_v2::set_truth_track_id (unsigned int truthTrackId) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 70 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 70 of file SvtxTrack_FastSim_v2.h
References _truth_track_id.
size_t SvtxTrack_FastSim_v2::size_g4hit_id () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 52 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 52 of file SvtxTrack_FastSim_v2.h
References _g4hit_ids.
Member Data Documentation
HitIdMap SvtxTrack_FastSim_v2::_g4hit_ids private
Definition at line 104 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 104 of file SvtxTrack_FastSim_v2.h
Referenced by add_g4hit_id(), begin_g4hit_id(), clear_g4hit_id(), CopyFrom(), empty_g4hit_id(), end_g4hit_id(), find_g4hit_id(), g4hit_ids(), identify(), remove_g4hit_id(), remove_g4hit_volume(), and size_g4hit_id().
unsigned int SvtxTrack_FastSim_v2::_nmeas = 0 private
Definition at line 102 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 102 of file SvtxTrack_FastSim_v2.h
Referenced by CopyFrom(), get_num_measurements(), identify(), and set_num_measurements().
unsigned int SvtxTrack_FastSim_v2::_truth_track_id = UINT_MAX private
Definition at line 101 of file SvtxTrack_FastSim_v2.h.
View newest version in sPHENIX GitHub at line 101 of file SvtxTrack_FastSim_v2.h
Referenced by CopyFrom(), get_truth_track_id(), identify(), and set_truth_track_id().
The documentation for this exception was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack_FastSim_v2.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack_FastSim_v2.cc