Analysis Software: PHG4VtxPoint Class Reference
PHG4VtxPoint Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4VtxPoint.h>
Public Member Functions
~PHG4VtxPoint () override
void identify (std::ostream &os=std::cout) const override
virtual void set_x (const double)
virtual void set_y (const double)
virtual void set_z (const double)
virtual void set_t (const double)
virtual void set_id (const int)
virtual double get_x () const
virtual double get_y () const
virtual double get_z () const
virtual double get_t () const
virtual int get_id () const
bool operator== (const PHG4VtxPoint &) const
comparison of vertex value only, not on the id, per algorithm requirement in PHG4TruthInfoContainer::AddPrimaryVertex
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
PHG4VtxPoint ()
Detailed Description
Definition at line 12 of file PHG4VtxPoint.h.
View newest version in sPHENIX GitHub at line 12 of file PHG4VtxPoint.h
Constructor & Destructor Documentation
PHG4VtxPoint::~PHG4VtxPoint () inline override
Definition at line 15 of file PHG4VtxPoint.h.
View newest version in sPHENIX GitHub at line 15 of file PHG4VtxPoint.h
PHG4VtxPoint::PHG4VtxPoint () inline protected
Definition at line 37 of file PHG4VtxPoint.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4VtxPoint.h
Member Function Documentation
virtual int PHG4VtxPoint::get_id () const inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 29 of file PHG4VtxPoint.h.
View newest version in sPHENIX GitHub at line 29 of file PHG4VtxPoint.h
Referenced by PHG4TruthTrackingAction::AddParticle(), BaseTruthEval::are_same_vertex(), SvtxEvaluator::fillOutputNtuples(), IsolatedTrackAnalysis::getAddTruth(), PHG4TruthInfoContainer::is_primary_vtx(), QAG4SimulationVertex::process_event(), PHG4DSTReader::process_event(), TruthCaloTree::process_event(), and TruthConversionEval::process_event().
virtual double PHG4VtxPoint::get_t () const inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 28 of file PHG4VtxPoint.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4VtxPoint.h
Referenced by pythiaEMCalAna::addPrimaryFromGeant(), PHG4InEvent::AddVtxCommon(), PHG4TrackFastSimEval::fill_track_tree(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), operator==(), Conversion::PHG4VtxPointToSvtxVertex(), QAG4SimulationVertex::process_event(), MbdVertexFastSimReco::process_event(), GlobalVertexFastSimReco::process_event(), Proto4SampleFrac::process_event(), MBDStudy::process_event(), MbdDigitization::process_event(), PHG4DSTReader::process_event(), BBCStudy::process_event(), singlePhotonClusterAna::process_event(), QAG4SimulationCalorimeter::process_event_G4Hit(), TrackClusterEvaluator::processRecoTracks(), and TrackClusterEvaluator::processTruthTracks().
virtual double PHG4VtxPoint::get_x () const inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 25 of file PHG4VtxPoint.h.
View newest version in sPHENIX GitHub at line 25 of file PHG4VtxPoint.h
Referenced by pythiaEMCalAna::addPrimaryFromGeant(), LeptoquarksReco::AddTrackInformation(), PHG4InEvent::AddVtxCommon(), DecayFinder::checkIfCorrectGeant4Particle(), Conversion::dist(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), PHAna::fill_histos(), PHG4TrackFastSimEval::fill_track_tree(), AnaSvtxTracksForGenFit::fill_tree(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), CaloEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), KFParticle_truthAndDetTools::fillTruthBranch(), HCalJetPhiShift::FillTTree(), HFTrackEfficiency::findTracks(), SetupDualRICHAnalyzer::get_emission_momentum(), IsolatedTrackAnalysis::getAddTruth(), dNdEtaINTT::GetTruthPVInfo(), PHGenFitTrkFitter::MakeSvtxTrack(), VtxTest::numUnique(), operator==(), Conversion::PHG4VtxPointToSvtxVertex(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), CaloEvaluator::printOutputInfo(), SvtxEvaluator::printOutputInfo(), SvtxSimPerformanceCheckReco::process_event(), MomentumEvaluator::process_event(), G4VtxNtuple::process_event(), TracksInJets::process_event(), SimpleTrackingAnalysis::process_event(), QAG4SimulationVertex::process_event(), GlobalVertexFastSimReco::process_event(), BJetModule::process_event(), RICHEvaluator::process_event(), QAG4Decayer::process_event(), MBDStudy::process_event(), Proto4SampleFrac::process_event(), MbdDigitization::process_event(), BBCStudy::process_event(), PHG4DSTReader::process_event(), QAG4SimulationTruthDecay::process_event(), truthDecayTester::process_event(), singlePhotonClusterAna::process_event(), TruthCaloTree::process_event(), pythiaEMCalAna::process_event(), VtxTest::process_event(), TruthConversionEval::process_event(), QAG4SimulationCalorimeter::process_event_G4Hit(), SoftLeptonTaggingTruth::process_Spectrum(), TrackClusterEvaluator::processRecoTracks(), TrackClusterEvaluator::processTruthTracks(), TruthConversionEval::recordConversion(), PHG4ParticleGeneratorBase::ReuseExistingVertex(), VtxTest::vtoR(), and TruthConversionEval::vtoR().
virtual double PHG4VtxPoint::get_y () const inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 26 of file PHG4VtxPoint.h.
View newest version in sPHENIX GitHub at line 26 of file PHG4VtxPoint.h
Referenced by pythiaEMCalAna::addPrimaryFromGeant(), LeptoquarksReco::AddTrackInformation(), PHG4InEvent::AddVtxCommon(), DecayFinder::checkIfCorrectGeant4Particle(), Conversion::dist(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), PHAna::fill_histos(), PHG4TrackFastSimEval::fill_track_tree(), AnaSvtxTracksForGenFit::fill_tree(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), CaloEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), KFParticle_truthAndDetTools::fillTruthBranch(), HCalJetPhiShift::FillTTree(), HFTrackEfficiency::findTracks(), SetupDualRICHAnalyzer::get_emission_momentum(), IsolatedTrackAnalysis::getAddTruth(), dNdEtaINTT::GetTruthPVInfo(), PHGenFitTrkFitter::MakeSvtxTrack(), VtxTest::numUnique(), operator==(), Conversion::PHG4VtxPointToSvtxVertex(), CaloEvaluator::printOutputInfo(), SvtxSimPerformanceCheckReco::process_event(), G4VtxNtuple::process_event(), SimpleTrackingAnalysis::process_event(), QAG4SimulationVertex::process_event(), Proto4ShowerCalib::process_event(), GlobalVertexFastSimReco::process_event(), BJetModule::process_event(), RICHEvaluator::process_event(), Proto2ShowerCalib::process_event(), Proto3ShowerCalib::process_event(), QAG4Decayer::process_event(), MBDStudy::process_event(), Proto4SampleFrac::process_event(), MbdDigitization::process_event(), BBCStudy::process_event(), truthDecayTester::process_event(), QAG4SimulationTruthDecay::process_event(), PHG4DSTReader::process_event(), singlePhotonClusterAna::process_event(), TruthCaloTree::process_event(), ExampleAnalysisModule::process_event(), pythiaEMCalAna::process_event(), VtxTest::process_event(), TruthConversionEval::process_event(), QAG4SimulationCalorimeter::process_event_G4Hit(), SoftLeptonTaggingTruth::process_Spectrum(), TrackClusterEvaluator::processRecoTracks(), TrackClusterEvaluator::processTruthTracks(), TruthConversionEval::recordConversion(), PHG4ParticleGeneratorBase::ReuseExistingVertex(), VtxTest::vtoR(), and TruthConversionEval::vtoR().
virtual double PHG4VtxPoint::get_z () const inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 27 of file PHG4VtxPoint.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4VtxPoint.h
Referenced by pythiaEMCalAna::addPrimaryFromGeant(), LeptoquarksReco::AddTrackInformation(), PHG4InEvent::AddVtxCommon(), DecayFinder::checkIfCorrectGeant4Particle(), Conversion::dist(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), PHAna::fill_histos(), PHG4TrackFastSimEval::fill_track_tree(), AnaSvtxTracksForGenFit::fill_tree(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), CaloEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), KFParticle_truthAndDetTools::fillTruthBranch(), HCalJetPhiShift::FillTTree(), HFTrackEfficiency::findTracks(), SetupDualRICHAnalyzer::get_emission_momentum(), IsolatedTrackAnalysis::getAddTruth(), dNdEtaINTT::GetTruthPVInfo(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), PHGenFitTrkFitter::MakeSvtxTrack(), VtxTest::numUnique(), operator==(), Conversion::PHG4VtxPointToSvtxVertex(), CaloEvaluator::printOutputInfo(), SvtxSimPerformanceCheckReco::process_event(), G4VtxNtuple::process_event(), SimpleTrackingAnalysis::process_event(), QAG4SimulationVertex::process_event(), MbdVertexFastSimReco::process_event(), Proto4ShowerCalib::process_event(), GlobalVertexFastSimReco::process_event(), BJetModule::process_event(), RICHEvaluator::process_event(), Proto3ShowerCalib::process_event(), Proto2ShowerCalib::process_event(), HFMLTriggerOccupancy::process_event(), SynRadAna::process_event(), QAG4Decayer::process_event(), MBDStudy::process_event(), Proto4SampleFrac::process_event(), MbdDigitization::process_event(), truthDecayTester::process_event(), BBCStudy::process_event(), PHG4DSTReader::process_event(), QAG4SimulationTruthDecay::process_event(), singlePhotonClusterAna::process_event(), TruthCaloTree::process_event(), ExampleAnalysisModule::process_event(), pythiaEMCalAna::process_event(), VtxTest::process_event(), QAG4SimulationCalorimeter::process_event_G4Hit(), SoftLeptonTaggingTruth::process_Spectrum(), TrackClusterEvaluator::processRecoTracks(), TrackClusterEvaluator::processTruthTracks(), TruthConversionEval::recordConversion(), and PHG4ParticleGeneratorBase::ReuseExistingVertex().
void PHG4VtxPoint::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHG4VtxPointv1.
Definition at line 6 of file PHG4VtxPoint.cc.
View newest version in sPHENIX GitHub at line 6 of file PHG4VtxPoint.cc
Referenced by Conversion::printReco(), Proto4SampleFrac::process_event(), QAG4SimulationCalorimeter::process_event_G4Hit(), and PHG4ParticleGeneratorBase::ReuseExistingVertex().
bool PHG4VtxPoint::operator== (const PHG4VtxPoint & p) const
comparison of vertex value only, not on the id, per algorithm requirement in PHG4TruthInfoContainer::AddPrimaryVertex
Definition at line 13 of file PHG4VtxPoint.cc.
View newest version in sPHENIX GitHub at line 13 of file PHG4VtxPoint.cc
References get_t(), get_x(), get_y(), and get_z().
virtual void PHG4VtxPoint::set_id (const int) inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 23 of file PHG4VtxPoint.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4VtxPoint.h
Referenced by PHG4TruthInfoContainer::AddVertex().
virtual void PHG4VtxPoint::set_t (const double) inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 22 of file PHG4VtxPoint.h.
View newest version in sPHENIX GitHub at line 22 of file PHG4VtxPoint.h
virtual void PHG4VtxPoint::set_x (const double) inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 19 of file PHG4VtxPoint.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4VtxPoint.h
virtual void PHG4VtxPoint::set_y (const double) inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 20 of file PHG4VtxPoint.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4VtxPoint.h
virtual void PHG4VtxPoint::set_z (const double) inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 21 of file PHG4VtxPoint.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4VtxPoint.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4VtxPoint.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4VtxPoint.cc