Analysis Software: Acts::detail::SymmetricKLDistanceMatrix Class Reference
Acts::detail::SymmetricKLDistanceMatrix Class Reference
Class representing a symmetric distance matrix.
#include <acts/blob/sPHENIX/Core/include/Acts/TrackFitting/detail/SymmetricKlDistanceMatrix.hpp>
Public Member Functions
template<typename component_t , typename projector_t >
SymmetricKLDistanceMatrix (const std::vector< component_t > &cmps, const projector_t &proj)
auto at (std::size_t i, std::size_t j) const
template<typename component_t , typename projector_t >
void recomputeAssociatedDistances (std::size_t n, const std::vector< component_t > &cmps, const projector_t &proj)
void maskAssociatedDistances (std::size_t n)
auto minDistancePair () const
Private Types
using Array = Eigen::Array< Acts::ActsScalar, Eigen::Dynamic, 1 >
using Mask = Eigen::Array< bool, Eigen::Dynamic, 1 >
Private Member Functions
template<typename array_t , typename setter_t >
void setAssociated (std::size_t n, array_t &array, setter_t &&setter)
Private Attributes
Array m_distances
Mask m_mask
std::vector< std::pair
< std::size_t, std::size_t > > m_mapToPair
std::size_t m_numberComponents
Friends
std::ostream & operator<< (std::ostream &os, const SymmetricKLDistanceMatrix &m)
Detailed Description
Class representing a symmetric distance matrix.
Definition at line 68 of file SymmetricKlDistanceMatrix.hpp.
View newest version in sPHENIX GitHub at line 68 of file SymmetricKlDistanceMatrix.hpp
Member Typedef Documentation
using Acts::detail::SymmetricKLDistanceMatrix::Array = Eigen::Array<Acts::ActsScalar, Eigen::Dynamic, 1> private
Definition at line 69 of file SymmetricKlDistanceMatrix.hpp.
View newest version in sPHENIX GitHub at line 69 of file SymmetricKlDistanceMatrix.hpp
using Acts::detail::SymmetricKLDistanceMatrix::Mask = Eigen::Array<bool, Eigen::Dynamic, 1> private
Definition at line 70 of file SymmetricKlDistanceMatrix.hpp.
View newest version in sPHENIX GitHub at line 70 of file SymmetricKlDistanceMatrix.hpp
Constructor & Destructor Documentation
template<typename component_t , typename projector_t > Acts::detail::SymmetricKLDistanceMatrix::SymmetricKLDistanceMatrix (const std::vector< component_t > & cmps, const projector_t & proj) inline
Definition at line 94 of file SymmetricKlDistanceMatrix.hpp.
View newest version in sPHENIX GitHub at line 94 of file SymmetricKlDistanceMatrix.hpp
References Acts::detail::computeSymmetricKlDivergence(), i, j, m_distances, m_mapToPair, and m_numberComponents.
Member Function Documentation
auto Acts::detail::SymmetricKLDistanceMatrix::at (std::size_t i, std::size_t j) const inline
Definition at line 110 of file SymmetricKlDistanceMatrix.hpp.
View newest version in sPHENIX GitHub at line 110 of file SymmetricKlDistanceMatrix.hpp
References m_distances.
void Acts::detail::SymmetricKLDistanceMatrix::maskAssociatedDistances (std::size_t n) inline
Definition at line 125 of file SymmetricKlDistanceMatrix.hpp.
View newest version in sPHENIX GitHub at line 125 of file SymmetricKlDistanceMatrix.hpp
References m_mask, and setAssociated().
Referenced by reduceWithKLDistanceImpl().
auto Acts::detail::SymmetricKLDistanceMatrix::minDistancePair () const inline
Definition at line 129 of file SymmetricKlDistanceMatrix.hpp.
View newest version in sPHENIX GitHub at line 129 of file SymmetricKlDistanceMatrix.hpp
References i, ambiguity_solver_full_chain::idx, m_distances, m_mapToPair, m_mask, and Acts::UnitConstants::min.
Referenced by reduceWithKLDistanceImpl().
template<typename component_t , typename projector_t > void Acts::detail::SymmetricKLDistanceMatrix::recomputeAssociatedDistances (std::size_t n, const std::vector< component_t > & cmps, const projector_t & proj) inline
Definition at line 115 of file SymmetricKlDistanceMatrix.hpp.
View newest version in sPHENIX GitHub at line 115 of file SymmetricKlDistanceMatrix.hpp
References assert, Acts::detail::computeSymmetricKlDivergence(), i, j, m_distances, m_numberComponents, and setAssociated().
Referenced by reduceWithKLDistanceImpl().
template<typename array_t , typename setter_t > void Acts::detail::SymmetricKLDistanceMatrix::setAssociated (std::size_t n, array_t & array, setter_t && setter) inline private
Definition at line 78 of file SymmetricKlDistanceMatrix.hpp.
View newest version in sPHENIX GitHub at line 78 of file SymmetricKlDistanceMatrix.hpp
References i, m_numberComponents, and n.
Referenced by maskAssociatedDistances(), and recomputeAssociatedDistances().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const SymmetricKLDistanceMatrix & m) friend
Definition at line 144 of file SymmetricKlDistanceMatrix.hpp.
View newest version in sPHENIX GitHub at line 144 of file SymmetricKlDistanceMatrix.hpp
Member Data Documentation
Array Acts::detail::SymmetricKLDistanceMatrix::m_distances private
Definition at line 72 of file SymmetricKlDistanceMatrix.hpp.
View newest version in sPHENIX GitHub at line 72 of file SymmetricKlDistanceMatrix.hpp
Referenced by at(), minDistancePair(), recomputeAssociatedDistances(), and SymmetricKLDistanceMatrix().
std::vector<std::pair<std::size_t, std::size_t> > Acts::detail::SymmetricKLDistanceMatrix::m_mapToPair private
Definition at line 74 of file SymmetricKlDistanceMatrix.hpp.
View newest version in sPHENIX GitHub at line 74 of file SymmetricKlDistanceMatrix.hpp
Referenced by minDistancePair(), and SymmetricKLDistanceMatrix().
Mask Acts::detail::SymmetricKLDistanceMatrix::m_mask private
Definition at line 73 of file SymmetricKlDistanceMatrix.hpp.
View newest version in sPHENIX GitHub at line 73 of file SymmetricKlDistanceMatrix.hpp
Referenced by maskAssociatedDistances(), and minDistancePair().
std::size_t Acts::detail::SymmetricKLDistanceMatrix::m_numberComponents private
Definition at line 75 of file SymmetricKlDistanceMatrix.hpp.
View newest version in sPHENIX GitHub at line 75 of file SymmetricKlDistanceMatrix.hpp
Referenced by recomputeAssociatedDistances(), setAssociated(), and SymmetricKLDistanceMatrix().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/TrackFitting/detail/SymmetricKlDistanceMatrix.hpp