Analysis Software: ValueGen1 Class Reference
ValueGen1 Class Reference
Public Member Functions
ValueGen1 (Int_t max)
~ValueGen1 ()
Bool_t Next ()
Int_t cnt () const
signed char i1 () const
short i2 () const
int i3 () const
int i4 () const
Long_t i5 () const
float f1 () const
float f2 () const
double f3 () const
Long_t d1 () const
TString s1 () const
TString s3 () const
TString s2 () const
TString s4 () const
Date dt ()
Time t ()
Timestamp ts ()
Private Attributes
Int_t fCnt
Int_t fMax
Detailed Description
Definition at line 37 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 37 of file RDBCmysql.C
Constructor & Destructor Documentation
ValueGen1::ValueGen1 (Int_t max) inline
Definition at line 44 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 44 of file RDBCmysql.C
ValueGen1::~ValueGen1 () inline
Definition at line 45 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 45 of file RDBCmysql.C
Member Function Documentation
Int_t ValueGen1::cnt () const inline
Definition at line 48 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 48 of file RDBCmysql.C
References fCnt.
Referenced by checkTables().
Long_t ValueGen1::d1 () const inline
Definition at line 58 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 58 of file RDBCmysql.C
References fCnt, and fMax.
Referenced by checkTables(), hijsft(), populateTables(), and pytbdy().
Date ValueGen1::dt () inline
Definition at line 66 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 66 of file RDBCmysql.C
References fCnt.
Referenced by checkTables(), doinstatescat(), getqvec(), populateTables(), pyhiresd(), pypole(), pyresd(), and vegas().
float ValueGen1::f1 () const inline
Definition at line 55 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 55 of file RDBCmysql.C
References fCnt.
Referenced by checkTables(), and populateTables().
float ValueGen1::f2 () const inline
Definition at line 56 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 56 of file RDBCmysql.C
References fCnt.
Referenced by checkTables(), and populateTables().
double ValueGen1::f3 () const inline
Definition at line 57 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 57 of file RDBCmysql.C
References fCnt.
Referenced by checkTables(), and populateTables().
signed char ValueGen1::i1 () const inline
Definition at line 50 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 50 of file RDBCmysql.C
References fCnt.
Referenced by checkTables(), klu(), luboei(), luclus(), luedit(), lufowo(), lugive(), luhepc(), luindf(), lulist(), luprep(), lushow(), lustrf(), lutabu(), plu(), podinl(), populateTables(), py2frm(), py4frm(), py4jet(), py6frm(), pybesq(), pyboei(), pyclus(), pycomp(), pydisg(), pyedit(), pyeig4(), pyevnt(), pyevnw(), pyfowo(), pyfscr(), pygive(), pyhepc(), pyhiinit(), pyhimult(), pyhirand(), pyhiremn(), pyhiresd(), pyhiscat(), pyhistfe(), pyindf(), pyinre(), pyjurf(), pyk(), pylist(), pymign(), pymihk(), pymirm(), pymsin(), pymult(), pyp(), pypdfu(), pyprep(), pyptfs(), pyptis(), pyptmi(), pyrand(), pyreco(), pyremn(), pyresd(), pyrget(), pyrset(), pysave(), pyscat(), pyshow(), pyslha(), pystat(), pystrf(), pytabu(), pytbdy(), pytune(), pyxtot(), rluget(), rluset(), and tails().
short ValueGen1::i2 () const inline
Definition at line 51 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 51 of file RDBCmysql.C
References fCnt.
Referenced by checkTables(), converttohepmc(), klu(), luboei(), luclus(), luerrm(), lufowo(), luhepc(), lulist(), lushow(), lutabu(), podinl(), populateTables(), printtime(), py2frm(), py4frm(), py4jet(), py6frm(), pybesq(), pyboei(), pyclus(), pydisg(), pyeig4(), pyerrm(), pyfowo(), pyfscr(), pygive(), pyhepc(), pyhiinit(), pyhimult(), pyhirand(), pyhiremn(), pyhiresd(), pyhiscat(), pyhistfe(), pyhitest(), pyk(), pylist(), pymign(), pymihk(), pymirm(), pymult(), pyplot(), pyprep(), pyptfs(), pyptmi(), pyrand(), pyreco(), pyremn(), pyresd(), pyrget(), pyrset(), pysave(), pyscat(), pyshow(), pyslha(), pystat(), pytabu(), pytest(), pytune(), pyxtot(), quench(), rluget(), rluset(), tails(), and vegas().
int ValueGen1::i3 () const inline
Definition at line 52 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 52 of file RDBCmysql.C
References fCnt.
Referenced by checkTables(), converttohepmc(), hijset(), klu(), lulist(), lutest(), luupda(), populateTables(), py4frm(), py4jet(), py6frm(), pyadsh(), pyboei(), pyeig4(), pygive(), pyhiinit(), pyhimaxi(), pyhirand(), pyhiresd(), pyhistat(), pyhistfe(), pyinit(), pyk(), pylist(), pymaxi(), pypole(), pyprep(), pyrand(), pyresd(), pyscat(), pyslha(), pystat(), pytune(), pyupda(), and vegas().
int ValueGen1::i4 () const inline
Definition at line 53 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 53 of file RDBCmysql.C
References fCnt.
Referenced by __example_1.f__(), checkTables(), lulist(), lutest(), luupda(), populateTables(), printtime(), py4frm(), py4jet(), py6frm(), pyboei(), pyhiinit(), pyhimaxi(), pyhiresd(), pyhitest(), pyinit(), pylist(), pymaxi(), pyplot(), pyprep(), pyresd(), pyscat(), pyslha(), pystat(), pystop(), pytest(), pytune(), and vegas().
Long_t ValueGen1::i5 () const inline
Definition at line 54 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 54 of file RDBCmysql.C
References fCnt, and Acts::IntegrationTest::L.
Referenced by checkTables(), lulist(), luupda(), populateTables(), py6frm(), pydump(), pyfram(), pyhifram(), pyhiresd(), pyhisspa(), pyhistfu(), pylist(), pypdfu(), pyplot(), pyresd(), pystat(), pyupda(), pyupev(), and vegas().
Bool_t ValueGen1::Next () inline
Definition at line 47 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 47 of file RDBCmysql.C
References fCnt, and fMax.
Referenced by checkTables(), and populateTables().
TString ValueGen1::s1 () const inline
Definition at line 59 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 59 of file RDBCmysql.C
References fCnt, and testchars.
Referenced by checkTables(), populateTables(), and s3().
TString ValueGen1::s2 () const inline
Definition at line 61 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 61 of file RDBCmysql.C
References fCnt.
Referenced by checkTables(), populateTables(), and s4().
TString ValueGen1::s3 () const inline
Definition at line 60 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 60 of file RDBCmysql.C
References s1().
Referenced by checkTables(), and populateTables().
TString ValueGen1::s4 () const inline
Definition at line 64 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 64 of file RDBCmysql.C
References s2().
Referenced by checkTables(), populateTables(), and pygvmd().
Time ValueGen1::t () inline
Definition at line 70 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 70 of file RDBCmysql.C
References fCnt.
Referenced by checkTables(), and populateTables().
Timestamp ValueGen1::ts () inline
Definition at line 74 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 74 of file RDBCmysql.C
References fCnt.
Referenced by checkTables(), getdeltat(), populateTables(), pyhistfu(), pypdpi(), and pypdpo().
Member Data Documentation
Int_t ValueGen1::fCnt private
Definition at line 40 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 40 of file RDBCmysql.C
Referenced by cnt(), d1(), dt(), f1(), f2(), f3(), i1(), i2(), i3(), i4(), i5(), Next(), s1(), s2(), t(), and ts().
Int_t ValueGen1::fMax private
Definition at line 41 of file RDBCmysql.C.
View newest version in sPHENIX GitHub at line 41 of file RDBCmysql.C
Referenced by d1(), and Next().
The documentation for this class was generated from the following file:
RDBC/blob/master/macros/RDBCmysql.C