Analysis Software: ActsExamples::ModuleClusters Class Reference
ActsExamples::ModuleClusters Class Reference
#include <acts/blob/sPHENIX/Examples/Algorithms/Digitization/include/ActsExamples/Digitization/ModuleClusters.hpp>
Public Types
using simhit_t = SimHitContainer::size_type
Public Member Functions
ModuleClusters (Acts::BinUtility segmentation, std::vector< Acts::BoundIndices > geoIndices, bool merge, double nsigma, bool commonCorner)
void add (DigitizedParameters params, simhit_t simhit)
std::vector< std::pair
< DigitizedParameters,
std::set< simhit_t > > > digitizedParameters ()
Private Member Functions
std::vector< ModuleValue > createCellCollection ()
void merge ()
ModuleValue squash (std::vector< ModuleValue > &values)
std::vector< size_t > nonGeoEntries (std::vector< Acts::BoundIndices > &indices)
std::vector< std::vector
< ModuleValue > > mergeParameters (std::vector< ModuleValue > values)
Private Attributes
Acts::BinUtility m_segmentation
std::vector< Acts::BoundIndices > m_geoIndices
std::vector< ModuleValue > m_moduleValues
bool m_merge
double m_nsigma
bool m_commonCorner
Detailed Description
Definition at line 39 of file ModuleClusters.hpp.
View newest version in sPHENIX GitHub at line 39 of file ModuleClusters.hpp
Member Typedef Documentation
using ActsExamples::ModuleClusters::simhit_t = SimHitContainer::size_type
Definition at line 41 of file ModuleClusters.hpp.
View newest version in sPHENIX GitHub at line 41 of file ModuleClusters.hpp
Constructor & Destructor Documentation
ActsExamples::ModuleClusters::ModuleClusters (Acts::BinUtility segmentation, std::vector< Acts::BoundIndices > geoIndices, bool merge, double nsigma, bool commonCorner) inline
Definition at line 43 of file ModuleClusters.hpp.
View newest version in sPHENIX GitHub at line 43 of file ModuleClusters.hpp
Member Function Documentation
void ActsExamples::ModuleClusters::add (DigitizedParameters params, simhit_t simhit)
Definition at line 25 of file ModuleClusters.cpp.
View newest version in sPHENIX GitHub at line 25 of file ModuleClusters.cpp
References ActsExamples::Cluster::channels, ActsExamples::DigitizedParameters::cluster, ActsExamples::DigitizedParameters::indices, m_merge, m_moduleValues, testing::internal::move(), ActsExamples::ModuleValue::paramIndices, ActsExamples::ModuleValue::paramValues, ActsExamples::ModuleValue::paramVariances, ActsExamples::ModuleValue::sources, ActsExamples::ModuleValue::value, ActsExamples::DigitizedParameters::values, and ActsExamples::DigitizedParameters::variances.
Referenced by ActsExamples::DigitizationAlgorithm::execute().
std::vector< ModuleValue > ActsExamples::ModuleClusters::createCellCollection () private
Definition at line 92 of file ModuleClusters.cpp.
View newest version in sPHENIX GitHub at line 92 of file ModuleClusters.cpp
References m_moduleValues.
Referenced by merge().
std::vector< std::pair< DigitizedParameters, std::set< ModuleClusters::simhit_t > > > ActsExamples::ModuleClusters::digitizedParameters ()
Definition at line 47 of file ModuleClusters.cpp.
View newest version in sPHENIX GitHub at line 47 of file ModuleClusters.cpp
References ActsExamples::DigitizedParameters::cluster, ActsExamples::DigitizedParameters::indices, m_merge, m_moduleValues, merge(), testing::internal::move(), ActsExamples::DigitizedParameters::values, and ActsExamples::DigitizedParameters::variances.
Referenced by ActsExamples::DigitizationAlgorithm::execute().
void ActsExamples::ModuleClusters::merge () private
Definition at line 102 of file ModuleClusters.cpp.
View newest version in sPHENIX GitHub at line 102 of file ModuleClusters.cpp
References createCellCollection(), m_commonCorner, m_moduleValues, ambiguity_solver_perf::merged, mergeParameters(), testing::internal::move(), and squash().
Referenced by digitizedParameters().
std::vector< std::vector< ModuleValue > > ActsExamples::ModuleClusters::mergeParameters (std::vector< ModuleValue > values) private
Definition at line 150 of file ModuleClusters.cpp.
View newest version in sPHENIX GitHub at line 150 of file ModuleClusters.cpp
References i, j, k, left(), m_nsigma, testing::internal::move(), and nonGeoEntries().
Referenced by merge().
std::vector< size_t > ActsExamples::ModuleClusters::nonGeoEntries (std::vector< Acts::BoundIndices > & indices) private
Definition at line 136 of file ModuleClusters.cpp.
View newest version in sPHENIX GitHub at line 136 of file ModuleClusters.cpp
References i, ambiguity_solver_full_chain::idx, and m_geoIndices.
Referenced by mergeParameters().
ModuleValue ActsExamples::ModuleClusters::squash (std::vector< ModuleValue > & values) private
Definition at line 225 of file ModuleClusters.cpp.
View newest version in sPHENIX GitHub at line 225 of file ModuleClusters.cpp
References b1, ActsFatras::Channelizer::ChannelSegment::bin, Acts::BinUtility::binningData(), ActsExamples::Cluster::channels, f, std::tr1::f2, i, ambiguity_solver_full_chain::idx, j, m_geoIndices, m_segmentation, Acts::UnitConstants::min, testing::internal::move(), ActsExamples::ModuleValue::paramIndices, ActsExamples::ModuleValue::paramValues, ActsExamples::ModuleValue::paramVariances, Acts::Test::pos, ActsExamples::Cluster::sizeLoc0, ActsExamples::Cluster::sizeLoc1, ActsExamples::ModuleValue::sources, and ActsExamples::ModuleValue::value.
Referenced by merge().
Member Data Documentation
bool ActsExamples::ModuleClusters::m_commonCorner private
Definition at line 62 of file ModuleClusters.hpp.
View newest version in sPHENIX GitHub at line 62 of file ModuleClusters.hpp
Referenced by merge().
std::vector<Acts::BoundIndices> ActsExamples::ModuleClusters::m_geoIndices private
Definition at line 58 of file ModuleClusters.hpp.
View newest version in sPHENIX GitHub at line 58 of file ModuleClusters.hpp
Referenced by nonGeoEntries(), and squash().
bool ActsExamples::ModuleClusters::m_merge private
Definition at line 60 of file ModuleClusters.hpp.
View newest version in sPHENIX GitHub at line 60 of file ModuleClusters.hpp
Referenced by add(), and digitizedParameters().
std::vector<ModuleValue> ActsExamples::ModuleClusters::m_moduleValues private
Definition at line 59 of file ModuleClusters.hpp.
View newest version in sPHENIX GitHub at line 59 of file ModuleClusters.hpp
Referenced by add(), createCellCollection(), digitizedParameters(), and merge().
double ActsExamples::ModuleClusters::m_nsigma private
Definition at line 61 of file ModuleClusters.hpp.
View newest version in sPHENIX GitHub at line 61 of file ModuleClusters.hpp
Referenced by mergeParameters().
Acts::BinUtility ActsExamples::ModuleClusters::m_segmentation private
Definition at line 57 of file ModuleClusters.hpp.
View newest version in sPHENIX GitHub at line 57 of file ModuleClusters.hpp
Referenced by squash().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Digitization/include/ActsExamples/Digitization/ModuleClusters.hpp
acts/blob/sPHENIX/Examples/Algorithms/Digitization/src/ModuleClusters.cpp