Analysis Software: Acts::Experimental::BoundVolumesGrid1Impl Struct Reference
Acts::Experimental::BoundVolumesGrid1Impl Struct Reference
This is used for volumes that are indexed in a bound 1-dimensional grid, e.g. a z-spaced array, or an r-spaced array of volumes.
#include <acts/blob/sPHENIX/Core/include/Acts/Navigation/DetectorVolumeUpdators.hpp>
Public Types
using IndexedUpdator = IndexedUpdatorImpl< VariableBoundIndexGrid1, DetectorVolumesCollection, DetectorVolumeFiller >
Public Member Functions
BoundVolumesGrid1Impl (const std::vector< ActsScalar > &gBoundaries, BinningValue bValue, const std::vector< const DetectorVolume * > &cVolumes, const Transform3 &bTransform=Transform3::Identity()) noexcept(false)
if (gBoundaries.size()!=cVolumes.size()+1u)
for (std::size_t ib=1u;ib< gBoundaries.size();++ib)
BoundVolumesGrid1Impl ()=delete
void update (const GeometryContext &gctx, NavigationState &nState) const
This updator relies on an 1D single index grid.
Public Member Functions inherited from Acts::Experimental::INavigationDelegate
virtual ~INavigationDelegate ()=default
Public Attributes
IndexedUpdator indexedUpdator
bTransform
Detailed Description
This is used for volumes that are indexed in a bound 1-dimensional grid, e.g. a z-spaced array, or an r-spaced array of volumes.
Definition at line 101 of file DetectorVolumeUpdators.hpp.
View newest version in sPHENIX GitHub at line 101 of file DetectorVolumeUpdators.hpp
Member Typedef Documentation
using Acts::Experimental::BoundVolumesGrid1Impl::IndexedUpdator = IndexedUpdatorImpl<VariableBoundIndexGrid1, DetectorVolumesCollection, DetectorVolumeFiller>
Definition at line 104 of file DetectorVolumeUpdators.hpp.
View newest version in sPHENIX GitHub at line 104 of file DetectorVolumeUpdators.hpp
Constructor & Destructor Documentation
Acts::Experimental::BoundVolumesGrid1Impl::BoundVolumesGrid1Impl (const std::vector< ActsScalar > & gBoundaries, BinningValue bValue, const std::vector< const DetectorVolume * > & cVolumes, const Transform3 & bTransform = Transform3::Identity()) inline noexcept
Allowed constructor with explicit arguments
Parameters
gBoundaries the grid boundaries
bValue the binning value
cVolumes the contained volumes
bTransform is the optional transform
Definition at line 114 of file DetectorVolumeUpdators.hpp.
View newest version in sPHENIX GitHub at line 114 of file DetectorVolumeUpdators.hpp
Acts::Experimental::BoundVolumesGrid1Impl::BoundVolumesGrid1Impl () delete
Member Function Documentation
Acts::Experimental::BoundVolumesGrid1Impl::for () inline
Definition at line 128 of file DetectorVolumeUpdators.hpp.
View newest version in sPHENIX GitHub at line 128 of file DetectorVolumeUpdators.hpp
References Acts::detail::Grid< T, Axes >::at(), Acts::Experimental::IndexedUpdatorImpl< grid_t, extractor_type, filler_type >::grid, add_histos_bX::ib, and indexedUpdator.
Acts::Experimental::BoundVolumesGrid1Impl::if (gBoundaries.size()! = cVolumes.size() + 1u) inline
Definition at line 123 of file DetectorVolumeUpdators.hpp.
View newest version in sPHENIX GitHub at line 123 of file DetectorVolumeUpdators.hpp
void Acts::Experimental::BoundVolumesGrid1Impl::update (const GeometryContext & gctx, NavigationState & nState) const inline
This updator relies on an 1D single index grid.
Parameters
gctx the geometry context
nState [in,out] the navigation state to be updated
Definition at line 139 of file DetectorVolumeUpdators.hpp.
View newest version in sPHENIX GitHub at line 139 of file DetectorVolumeUpdators.hpp
References indexedUpdator, and Acts::Experimental::IndexedUpdatorImpl< grid_t, extractor_type, filler_type >::update().
Referenced by BOOST_AUTO_TEST_CASE().
Member Data Documentation
Acts::Experimental::BoundVolumesGrid1Impl::bTransform
Initial value:
{
    indexedUpdator.extractor.dVolumes = cVolumes
Definition at line 120 of file DetectorVolumeUpdators.hpp.
View newest version in sPHENIX GitHub at line 120 of file DetectorVolumeUpdators.hpp
IndexedUpdator Acts::Experimental::BoundVolumesGrid1Impl::indexedUpdator
Definition at line 106 of file DetectorVolumeUpdators.hpp.
View newest version in sPHENIX GitHub at line 106 of file DetectorVolumeUpdators.hpp
Referenced by for(), Acts::PortalJsonConverter::toJsonDetray(), and update().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Navigation/DetectorVolumeUpdators.hpp