Analysis Software: PHG4TruthInfoContainer Class Reference
PHG4TruthInfoContainer Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4TruthInfoContainer.h>
Public Types
typedef std::map< int,
PHG4Particle * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
typedef std::map< int,
PHG4VtxPoint * > VtxMap
typedef VtxMap::iterator VtxIterator
typedef VtxMap::const_iterator ConstVtxIterator
typedef std::pair< VtxIterator,
VtxIterator > VtxRange
typedef std::pair
< ConstVtxIterator,
ConstVtxIterator > ConstVtxRange
typedef std::map< int,
PHG4Shower * > ShowerMap
typedef ShowerMap::iterator ShowerIterator
typedef ShowerMap::const_iterator ConstShowerIterator
typedef std::pair
< ShowerIterator,
ShowerIterator > ShowerRange
typedef std::pair
< ConstShowerIterator,
ConstShowerIterator > ConstShowerRange
Public Member Functions
PHG4TruthInfoContainer ()
~PHG4TruthInfoContainer () override
void Reset () override
Clear Event.
void identify (std::ostream &os=std::cout) const override
ConstIterator AddParticle (const int particleid, PHG4Particle *newparticle)
Add a particle that the user has created.
void delete_particle (Iterator piter)
void delete_particle (int trackid)
PHG4Particle * GetParticle (const int trackid)
PHG4Particle * GetPrimaryParticle (const int trackid)
bool is_primary (const PHG4Particle *p) const
Range GetParticleRange ()
Get a range of iterators covering the entire container.
ConstRange GetParticleRange () const
Range GetPrimaryParticleRange ()
ConstRange GetPrimaryParticleRange () const
Range GetSecondaryParticleRange ()
ConstRange GetSecondaryParticleRange () const
unsigned int size (void) const
track -> particle map size
int GetNumPrimaryVertexParticles ()
const Map & GetMap () const
Get the Particle Map storage.
int maxtrkindex () const
int mintrkindex () const
std::pair< std::map< int, int >
::const_iterator, std::map
< int, int >::const_iterator > GetEmbeddedTrkIds () const
void AddEmbededTrkId (const int id, const int flag)
int isEmbeded (const int trackid) const
ConstVtxIterator AddVertex (const int vtxid, PHG4VtxPoint *vertex)
Add a vertex and return an iterator to the user.
void delete_vtx (VtxIterator viter)
void delete_vtx (int vtxid)
PHG4VtxPoint * GetVtx (const int vtxid)
PHG4VtxPoint * GetPrimaryVtx (const int vtxid)
bool is_primary_vtx (const PHG4VtxPoint *v) const
VtxRange GetVtxRange ()
Get a range of iterators covering the entire vertex container.
ConstVtxRange GetVtxRange () const
VtxRange GetPrimaryVtxRange ()
ConstVtxRange GetPrimaryVtxRange () const
VtxRange GetSecondaryVtxRange ()
ConstVtxRange GetSecondaryVtxRange () const
unsigned int GetNumVertices () const
Get the number of vertices stored.
const VtxMap & GetVtxMap () const
Get the Vertex Map storage.
int maxvtxindex () const
int minvtxindex () const
int GetPrimaryVertexIndex () const
std::pair< std::map< int, int >
::const_iterator, std::map
< int, int >::const_iterator > GetEmbeddedVtxIds () const
void AddEmbededVtxId (const int id, const int flag)
int isEmbededVtx (const int vtxid) const
ConstShowerIterator AddShower (const int showerid, PHG4Shower *newshower)
Add a shower that the user has created.
void delete_shower (ShowerIterator piter)
PHG4Shower * GetShower (const int showerid)
PHG4Shower * GetPrimaryShower (const int showerid)
ShowerRange GetShowerRange ()
Get a range of iterators covering the entire container.
ConstShowerRange GetShowerRange () const
ShowerRange GetPrimaryShowerRange ()
ConstShowerRange GetPrimaryShowerRange () const
ShowerRange GetSecondaryShowerRange ()
ConstShowerRange GetSecondaryShowerRange () const
unsigned int shower_size (void) const
shower size
const ShowerMap & GetShowerMap () const
Get the Shower Map storage.
int maxshowerindex () const
int minshowerindex () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
Map particlemap
VtxMap vtxmap
ShowerMap showermap
std::map< int, int > particle_embed_flags
std::map< int, int > vertex_embed_flags
Detailed Description
Definition at line 17 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4TruthInfoContainer.h
Member Typedef Documentation
typedef Map::const_iterator PHG4TruthInfoContainer::ConstIterator
Definition at line 22 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 22 of file PHG4TruthInfoContainer.h
typedef std::pair<ConstIterator, ConstIterator> PHG4TruthInfoContainer::ConstRange
Definition at line 24 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 24 of file PHG4TruthInfoContainer.h
typedef ShowerMap::const_iterator PHG4TruthInfoContainer::ConstShowerIterator
Definition at line 34 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4TruthInfoContainer.h
typedef std::pair<ConstShowerIterator, ConstShowerIterator> PHG4TruthInfoContainer::ConstShowerRange
Definition at line 36 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4TruthInfoContainer.h
typedef VtxMap::const_iterator PHG4TruthInfoContainer::ConstVtxIterator
Definition at line 28 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4TruthInfoContainer.h
typedef std::pair<ConstVtxIterator, ConstVtxIterator> PHG4TruthInfoContainer::ConstVtxRange
Definition at line 30 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4TruthInfoContainer.h
typedef Map::iterator PHG4TruthInfoContainer::Iterator
Definition at line 21 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4TruthInfoContainer.h
typedef std::map<int, PHG4Particle*> PHG4TruthInfoContainer::Map
Definition at line 20 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4TruthInfoContainer.h
typedef std::pair<Iterator, Iterator> PHG4TruthInfoContainer::Range
Definition at line 23 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4TruthInfoContainer.h
typedef ShowerMap::iterator PHG4TruthInfoContainer::ShowerIterator
Definition at line 33 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4TruthInfoContainer.h
typedef std::map<int, PHG4Shower*> PHG4TruthInfoContainer::ShowerMap
Definition at line 32 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4TruthInfoContainer.h
typedef std::pair<ShowerIterator, ShowerIterator> PHG4TruthInfoContainer::ShowerRange
Definition at line 35 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4TruthInfoContainer.h
typedef VtxMap::iterator PHG4TruthInfoContainer::VtxIterator
Definition at line 27 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4TruthInfoContainer.h
typedef std::map<int, PHG4VtxPoint*> PHG4TruthInfoContainer::VtxMap
Definition at line 26 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 26 of file PHG4TruthInfoContainer.h
typedef std::pair<VtxIterator, VtxIterator> PHG4TruthInfoContainer::VtxRange
Definition at line 29 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 29 of file PHG4TruthInfoContainer.h
Constructor & Destructor Documentation
PHG4TruthInfoContainer::PHG4TruthInfoContainer ()
Definition at line 14 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 14 of file PHG4TruthInfoContainer.cc
PHG4TruthInfoContainer::~PHG4TruthInfoContainer () override
Definition at line 22 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 22 of file PHG4TruthInfoContainer.cc
References Reset().
Member Function Documentation
void PHG4TruthInfoContainer::AddEmbededTrkId (const int id, const int flag) inline
Set the embedding ID for the HepMC subevent or track to be analyzed. positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 96 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 96 of file PHG4TruthInfoContainer.h
References particle_embed_flags.
Referenced by Fun4AllDstPileupMerger::copy_background_event(), and PHG4TruthEventAction::EndOfEventAction().
void PHG4TruthInfoContainer::AddEmbededVtxId (const int id, const int flag) inline
Set the embedding ID for the HepMC subevent or track to be analyzed. positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 157 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 157 of file PHG4TruthInfoContainer.h
References vertex_embed_flags.
Referenced by Fun4AllDstPileupMerger::copy_background_event(), and PHG4TruthEventAction::EndOfEventAction().
PHG4TruthInfoContainer::ConstIterator PHG4TruthInfoContainer::AddParticle (const int particleid, PHG4Particle * newparticle)
Add a particle that the user has created.
Definition at line 94 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 94 of file PHG4TruthInfoContainer.cc
References PHG4Particle::get_name(), PHG4Particle::get_parent_id(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4Particle::get_track_id(), it, and particlemap.
Referenced by PHG4TruthTrackingAction::AddParticle(), PHG4TpcDirectLaser::AppendLaserTrack(), and Fun4AllDstPileupMerger::copy_background_event().
PHG4TruthInfoContainer::ConstShowerIterator PHG4TruthInfoContainer::AddShower (const int showerid, PHG4Shower * newshower)
Add a shower that the user has created.
Definition at line 220 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 220 of file PHG4TruthInfoContainer.cc
References train_ambiguity_solver::id, identify(), it, PHG4Shower::set_id(), and showermap.
Referenced by PHG4TruthTrackingAction::PreUserTrackingAction().
PHG4TruthInfoContainer::ConstVtxIterator PHG4TruthInfoContainer::AddVertex (const int vtxid, PHG4VtxPoint * vertex)
Add a vertex and return an iterator to the user.
Definition at line 193 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 193 of file PHG4TruthInfoContainer.cc
References train_ambiguity_solver::id, identify(), it, PHG4VtxPoint::set_id(), and vtxmap.
Referenced by PHG4TruthTrackingAction::AddVertex(), PHG4TpcDirectLaser::AppendLaserTrack(), and Fun4AllDstPileupMerger::copy_background_event().
void PHG4TruthInfoContainer::delete_particle (Iterator piter)
Definition at line 330 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 330 of file PHG4TruthInfoContainer.cc
References particlemap.
Referenced by delete_particle(), PHG4TruthEventAction::EndOfEventAction(), PHG4TruthSubsystem::process_after_geant(), PHG4DstCompressReco::process_event(), PHG4TruthTrackingAction::ResetEvent(), and PHG4TruthTrackingAction::UpdateG4ParticleStack().
void PHG4TruthInfoContainer::delete_particle (int trackid)
Definition at line 337 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 337 of file PHG4TruthInfoContainer.cc
References delete_particle(), it, and particlemap.
void PHG4TruthInfoContainer::delete_shower (ShowerIterator piter)
Definition at line 362 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 362 of file PHG4TruthInfoContainer.cc
References showermap.
Referenced by PHG4TruthEventAction::PruneShowers().
void PHG4TruthInfoContainer::delete_vtx (VtxIterator viter)
Definition at line 346 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 346 of file PHG4TruthInfoContainer.cc
References vtxmap.
Referenced by delete_vtx(), PHG4TruthEventAction::EndOfEventAction(), PHG4TruthSubsystem::process_after_geant(), and PHG4DstCompressReco::process_event().
void PHG4TruthInfoContainer::delete_vtx (int vtxid)
Definition at line 353 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 353 of file PHG4TruthInfoContainer.cc
References delete_vtx(), it, and vtxmap.
std::pair<std::map<int, int>::const_iterator, std::map<int, int>::const_iterator> PHG4TruthInfoContainer::GetEmbeddedTrkIds () const inline
Retrieve the embedding ID for the HepMC subevent or track to be analyzed. positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 87 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 87 of file PHG4TruthInfoContainer.h
References particle_embed_flags.
Referenced by PHG4ConsistencyCheck::process_event(), TrackingPerformanceCheck::process_event(), and DumpPHG4TruthInfoContainer::process_Node().
std::pair<std::map<int, int>::const_iterator, std::map<int, int>::const_iterator> PHG4TruthInfoContainer::GetEmbeddedVtxIds () const inline
Retrieve the embedding ID for the HepMC subevent or track to be analyzed. positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 148 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 148 of file PHG4TruthInfoContainer.h
References vertex_embed_flags.
Referenced by DumpPHG4TruthInfoContainer::process_Node().
const Map& PHG4TruthInfoContainer::GetMap () const inline
Get the Particle Map storage.
Definition at line 76 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4TruthInfoContainer.h
References particlemap.
Referenced by PHG4TruthEventAction::BeginOfEventAction(), QAG4SimulationCalorimeterSum::get_truth_particle(), operator==(), MomentumEvaluator::process_event(), Proto4SampleFrac::process_event(), PHG4DSTReader::process_event(), QAG4SimulationCalorimeter::process_event_Cluster(), QAG4SimulationCalorimeter::process_event_G4Hit(), and EMCalAna::process_event_UpslisonTrig().
int PHG4TruthInfoContainer::GetNumPrimaryVertexParticles () inline
Definition at line 70 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4TruthInfoContainer.h
References distance(), and particlemap.
Referenced by SvtxEvaluator::fillOutputNtuples(), QAG4SimulationVertex::process_event(), SynRadAna::process_event(), ElectronID::process_event(), and TrackClusterEvaluator::processTruthTracks().
unsigned int PHG4TruthInfoContainer::GetNumVertices () const inline
Get the number of vertices stored.
Definition at line 130 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 130 of file PHG4TruthInfoContainer.h
References vtxmap.
Referenced by SynRadAna::process_event(), MBDStudy::process_event(), BBCStudy::process_event(), and DumpPHG4TruthInfoContainer::process_Node().
PHG4Particle * PHG4TruthInfoContainer::GetParticle (const int trackid)
Definition at line 117 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 117 of file PHG4TruthInfoContainer.cc
References it, and particlemap.
Referenced by SvtxHitEval::all_hits_from(), SvtxTrackEval::all_truth_particles(), JetTruthEval::all_truth_particles(), RICHEvaluator::calculate_true_emission_angle(), PHG4TruthEventAction::EndOfEventAction(), DSTEmulator::evaluate_tracks(), TrackEvaluation::evaluate_tracks(), PHG4TrackFastSimEval::fill_vertex_tree(), EventEvaluator::fillOutputNtuples(), BuildResonanceJetTaggingTree::findMatchedTruthD0(), ResonanceJetTagging::findMCTaggedJets(), HFTrackEfficiency::findTracks(), SetupDualRICHAnalyzer::get_emission_momentum(), BaseTruthEval::get_particle(), BaseTruthEval::get_primary_particle(), SetupDualRICHAnalyzer::get_true_momentum(), JetTruthEval::get_truth_jet(), IsolatedTrackAnalysis::getAddTruth(), dNdEtaINTT::GetG4PAncestor(), PHTruthSiliconAssociation::getG4PrimaryParticle(), IsolatedTrackAnalysis::getG4Truth(), KFParticle_truthAndDetTools::getHepMCInfo(), TrkrTruthTrackContainerv1::getTruthTrack(), KFParticle_truthAndDetTools::getTruthTrack(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), SvtxTrackEval::max_truth_particle_by_nclusters(), PHSiliconTruthTrackSeeding::Process(), PHG4ConsistencyCheck::process_event(), FastPid_RICH::process_event(), RICHEvaluator::process_event(), RICHParticleID::process_event(), SynRadAna::process_event(), QAG4Decayer::process_event(), MBDStudy::process_event(), Proto4SampleFrac::process_event(), MbdDigitization::process_event(), isoCluster::process_event(), BBCStudy::process_event(), truthDecayTester::process_event(), PHG4DSTReader::process_event(), QAG4SimulationTruthDecay::process_event(), TruthCaloTree::process_event(), VtxTest::process_event(), jetrtrack::process_event(), TruthConversionEval::process_event(), QAG4SimulationCalorimeter::process_event_G4Hit(), PHG4TruthEventAction::ProcessShowers(), PHG4TruthEventAction::PruneShowers(), DecayFinder::searchGeant4Record(), Conversion::setPrimaryPhoton(), and TruthJetTagging::TruthPhotonTagging().
Range PHG4TruthInfoContainer::GetParticleRange () inline
Get a range of iterators covering the entire container.
Definition at line 59 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4TruthInfoContainer.h
References particlemap.
Referenced by PHG4TruthEventAction::EndOfEventAction(), SvtxEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), SvtxClusterEval::FillRecoClusterFromG4HitCache(), SvtxTruthEval::FillTruthHitsFromParticleCache(), SvtxTruthRecoTableEval::fillTruthMap(), VtxTest::findChildren(), DecayFinder::findDecay(), ResonanceJetTagging::findMCTaggedJets(), HFTrackEfficiency::findTracks(), CaloEvaluator::printInputInfo(), PHG4TruthSubsystem::process_after_geant(), PHG4ConsistencyCheck::process_event(), TrackingPerformanceCheck::process_event(), QAG4Decayer::process_event(), truthDecayTester::process_event(), QAG4SimulationTruthDecay::process_event(), PHTruthClustering::process_event(), VtxTest::process_event(), TruthConversionEval::process_event(), DumpPHG4TruthInfoContainer::process_Node(), TrackClusterEvaluator::processTruthTracks(), and DecayFinder::searchGeant4Record().
ConstRange PHG4TruthInfoContainer::GetParticleRange () const inline
Definition at line 60 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4TruthInfoContainer.h
References particlemap.
PHG4Particle * PHG4TruthInfoContainer::GetPrimaryParticle (const int trackid)
Definition at line 128 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 128 of file PHG4TruthInfoContainer.cc
References it, and particlemap.
Referenced by KFParticle_truthAndDetTools::fillTruthBranch(), BaseTruthEval::get_primary_particle(), PHTruthClustering::process_event(), and FullJetFinder::process_event().
Range PHG4TruthInfoContainer::GetPrimaryParticleRange () inline
Definition at line 62 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4TruthInfoContainer.h
References particlemap.
Referenced by QAG4SimulationMicromegas::evaluate_clusters(), QAG4SimulationTpc::evaluate_clusters(), PHGenFitTrkFitter::fill_eval_tree(), PHG4TrackFastSimEval::fill_track_tree(), AnaSvtxTracksForGenFit::fill_tree(), EpFinderEval::fill_tree(), FastTrackingEval::fill_tree(), PHAna::fill_truth_ntuple(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), SvtxTruthRecoTableEval::fillTruthMap(), HCalJetPhiShift::FillTTree(), ElectronID::findMCmatch(), TruthJetInput::get_input(), pythiaEMCalAna::getG4EndVtx(), IsolatedTrackAnalysis::getG4Truth(), AnaTutorial::getPHG4Truth(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), CaloEvaluator::printOutputInfo(), SvtxEvaluator::printOutputInfo(), PHTruthTrackSeeding::Process(), SvtxSimPerformanceCheckReco::process_event(), RecoInfoExport::process_event(), QAG4SimulationUpsilon::process_event(), STACalorimeterCharacterization::process_event(), SimpleTrackingAnalysis::process_event(), QAG4SimulationVertex::process_event(), G4SnglNtuple::process_event(), Proto4ShowerCalib::process_event(), G4SnglTree::process_event(), HijingCountNtuple::process_event(), TowerTiming::process_event(), ShowerSize::process_event(), BJetModule::process_event(), TimingNtuple::process_event(), Forward_pi0s::process_event(), DetermineTowerBackground::process_event(), QAG4SimulationTracking::process_event(), Photons::process_event(), Proto2ShowerCalib::process_event(), HFMLTriggerOccupancy::process_event(), Proto3ShowerCalib::process_event(), HFMLTriggerInterface::process_event(), TPCDataStreamEmulator::process_event(), SynRadAna::process_event(), SigmaTimingNtuple::process_event(), TruthPhotonJet::process_event(), Proto4SampleFrac::process_event(), Proto4TowerCalib::process_event(), isoCluster::process_event(), PHG4DSTReader::process_event(), TPCMLDataInterface::process_event(), singlePhotonClusterAna::process_event(), TruthCaloTree::process_event(), pi0ClusterAna::process_event(), ExampleAnalysisModule::process_event(), pythiaEMCalAna::process_event(), ElectronID::process_event(), pi0Efficiency::process_event(), jetrtrack::process_event(), cemcReco::process_event(), PHG4TrackFastSim::process_event(), FillTruthRecoMatchTree::process_event(), QAG4SimulationCalorimeter::process_event_G4Hit(), EMCalCalib::process_event_MCPhoton(), EMCalAna::process_event_Trk(), EMCalAna::process_event_UpslisonTrig(), CaloWaveFormSim::process_g4hits(), SoftLeptonTaggingTruth::process_Spectrum(), and TrackClusterEvaluator::processTruthTracks().
ConstRange PHG4TruthInfoContainer::GetPrimaryParticleRange () const inline
Definition at line 63 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4TruthInfoContainer.h
References particlemap.
PHG4Shower * PHG4TruthInfoContainer::GetPrimaryShower (const int showerid)
Definition at line 178 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 178 of file PHG4TruthInfoContainer.cc
References it, and showermap.
ShowerRange PHG4TruthInfoContainer::GetPrimaryShowerRange () inline
Definition at line 181 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 181 of file PHG4TruthInfoContainer.h
References showermap.
Referenced by BaseTruthEval::get_primary_shower().
ConstShowerRange PHG4TruthInfoContainer::GetPrimaryShowerRange () const inline
Definition at line 182 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 182 of file PHG4TruthInfoContainer.h
References showermap.
int PHG4TruthInfoContainer::GetPrimaryVertexIndex () const
Return ID of the truth primary vertex with highest embedding ID. For vertex with identical embedding ID, return first one simulated in Geant4.
Definition at line 401 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 401 of file PHG4TruthInfoContainer.cc
References GetPrimaryVtxRange(), isEmbededVtx(), and Acts::UnitConstants::min.
Referenced by PHAna::fill_histos(), CaloEvaluator::fillOutputNtuples(), HCalJetPhiShift::FillTTree(), identify(), PHGenFitTrkFitter::MakeSvtxTrack(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), CaloEvaluator::printOutputInfo(), SvtxEvaluator::printOutputInfo(), MomentumEvaluator::process_event(), G4VtxNtuple::process_event(), TracksInJets::process_event(), MbdVertexFastSimReco::process_event(), GlobalVertexFastSimReco::process_event(), BJetModule::process_event(), HFMLTriggerOccupancy::process_event(), MBDStudy::process_event(), MbdDigitization::process_event(), and BBCStudy::process_event().
PHG4VtxPoint * PHG4TruthInfoContainer::GetPrimaryVtx (const int vtxid)
Definition at line 153 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 153 of file PHG4TruthInfoContainer.cc
References it, and vtxmap.
Referenced by PHAna::fill_histos(), CaloEvaluator::fillOutputNtuples(), HCalJetPhiShift::FillTTree(), PHGenFitTrkFitter::MakeSvtxTrack(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), CaloEvaluator::printOutputInfo(), SvtxEvaluator::printOutputInfo(), MomentumEvaluator::process_event(), G4VtxNtuple::process_event(), TracksInJets::process_event(), MbdVertexFastSimReco::process_event(), GlobalVertexFastSimReco::process_event(), BJetModule::process_event(), HFMLTriggerOccupancy::process_event(), Proto4SampleFrac::process_event(), MBDStudy::process_event(), MbdDigitization::process_event(), BBCStudy::process_event(), QAG4SimulationCalorimeter::process_event_Cluster(), QAG4SimulationCalorimeter::process_event_G4Hit(), SoftLeptonTaggingTruth::process_Spectrum(), and PHG4ParticleGeneratorBase::ReuseExistingVertex().
VtxRange PHG4TruthInfoContainer::GetPrimaryVtxRange () inline
Definition at line 123 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 123 of file PHG4TruthInfoContainer.h
References vtxmap.
Referenced by PHGenFitTrkFitter::fill_eval_tree(), SvtxEvaluator::fillOutputNtuples(), GetPrimaryVertexIndex(), dNdEtaINTT::GetTruthPVInfo(), PHTruthVertexing::Process(), PHSiliconTruthTrackSeeding::Process(), QAG4SimulationVertex::process_event(), and pythiaEMCalAna::process_event().
ConstVtxRange PHG4TruthInfoContainer::GetPrimaryVtxRange () const inline
Definition at line 124 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 124 of file PHG4TruthInfoContainer.h
References vtxmap.
Range PHG4TruthInfoContainer::GetSecondaryParticleRange () inline
Definition at line 65 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4TruthInfoContainer.h
References particlemap.
Referenced by IsolatedTrackAnalysis::getAddTruth(), pythiaEMCalAna::getG4EndVtx(), IsolatedTrackAnalysis::getG4Truth(), PHG4DstCompressReco::process_event(), Forward_pi0s::process_event(), SigmaTimingNtuple::process_event(), pi0ClusterAna::process_event(), singlePhotonClusterAna::process_event(), TruthCaloTree::process_event(), pi0Efficiency::process_event(), and cemcReco::process_event().
ConstRange PHG4TruthInfoContainer::GetSecondaryParticleRange () const inline
Definition at line 66 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4TruthInfoContainer.h
References particlemap.
ShowerRange PHG4TruthInfoContainer::GetSecondaryShowerRange () inline
Definition at line 184 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 184 of file PHG4TruthInfoContainer.h
References showermap.
Referenced by BaseTruthEval::all_secondary_showers().
ConstShowerRange PHG4TruthInfoContainer::GetSecondaryShowerRange () const inline
Definition at line 185 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 185 of file PHG4TruthInfoContainer.h
References showermap.
VtxRange PHG4TruthInfoContainer::GetSecondaryVtxRange () inline
Definition at line 126 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 126 of file PHG4TruthInfoContainer.h
References vtxmap.
Referenced by PHG4DstCompressReco::process_event().
ConstVtxRange PHG4TruthInfoContainer::GetSecondaryVtxRange () const inline
Definition at line 127 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 127 of file PHG4TruthInfoContainer.h
References vtxmap.
PHG4Shower * PHG4TruthInfoContainer::GetShower (const int showerid)
Definition at line 167 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 167 of file PHG4TruthInfoContainer.cc
References it, and showermap.
Referenced by CaloRawTowerEval::all_truth_primary_showers(), and BaseTruthEval::get_primary_shower().
const ShowerMap& PHG4TruthInfoContainer::GetShowerMap () const inline
Get the Shower Map storage.
Definition at line 191 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 191 of file PHG4TruthInfoContainer.h
References showermap.
Referenced by operator==().
ShowerRange PHG4TruthInfoContainer::GetShowerRange () inline
Get a range of iterators covering the entire container.
Definition at line 178 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 178 of file PHG4TruthInfoContainer.h
References showermap.
Referenced by PHG4DstCompressReco::process_event(), DumpPHG4TruthInfoContainer::process_Node(), PHG4TruthEventAction::ProcessShowers(), and PHG4TruthEventAction::PruneShowers().
ConstShowerRange PHG4TruthInfoContainer::GetShowerRange () const inline
Definition at line 179 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 179 of file PHG4TruthInfoContainer.h
References showermap.
PHG4VtxPoint * PHG4TruthInfoContainer::GetVtx (const int vtxid)
Definition at line 142 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 142 of file PHG4TruthInfoContainer.cc
References it, and vtxmap.
Referenced by PHTruthSiliconAssociation::buildTrackSeed(), PHTruthTrackSeeding::buildTrackSeed(), DecayFinder::checkIfCorrectGeant4Particle(), PHG4TrackFastSimEval::fill_track_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), EventEvaluator::fillOutputNtuples(), KFParticle_truthAndDetTools::fillTruthBranch(), HFTrackEfficiency::findTracks(), SetupDualRICHAnalyzer::get_emission_momentum(), BaseTruthEval::get_vertex(), pythiaEMCalAna::getG4EndVtx(), TrkrTruthTrackContainerv1::getTruthTrack(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), SvtxEvaluator::printOutputInfo(), MomentumEvaluator::process_event(), Proto4ShowerCalib::process_event(), BJetModule::process_event(), RICHEvaluator::process_event(), Proto3ShowerCalib::process_event(), Proto2ShowerCalib::process_event(), SynRadAna::process_event(), QAG4Decayer::process_event(), Proto4TowerCalib::process_event(), PHG4DSTReader::process_event(), QAG4SimulationTruthDecay::process_event(), truthDecayTester::process_event(), singlePhotonClusterAna::process_event(), ExampleAnalysisModule::process_event(), VtxTest::process_event(), TruthConversionEval::process_event(), and PHG4TruthEventAction::ProcessShowers().
const VtxMap& PHG4TruthInfoContainer::GetVtxMap () const inline
Get the Vertex Map storage.
Definition at line 133 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 133 of file PHG4TruthInfoContainer.h
References vtxmap.
Referenced by PHG4TruthTrackingAction::AddVertex(), and operator==().
VtxRange PHG4TruthInfoContainer::GetVtxRange () inline
Get a range of iterators covering the entire vertex container.
Definition at line 120 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 120 of file PHG4TruthInfoContainer.h
References vtxmap.
Referenced by PHG4TruthEventAction::EndOfEventAction(), IsolatedTrackAnalysis::getAddTruth(), PHG4TruthSubsystem::process_after_geant(), MBDStudy::process_event(), BBCStudy::process_event(), TruthCaloTree::process_event(), and DumpPHG4TruthInfoContainer::process_Node().
ConstVtxRange PHG4TruthInfoContainer::GetVtxRange () const inline
Definition at line 121 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 121 of file PHG4TruthInfoContainer.h
References vtxmap.
void PHG4TruthInfoContainer::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 50 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 50 of file PHG4TruthInfoContainer.cc
References GetPrimaryVertexIndex(), particle_embed_flags, particlemap, showermap, vertex_embed_flags, and vtxmap.
Referenced by AddShower(), AddVertex(), and PHG4ParticleGeneratorBase::ReuseExistingVertex().
bool PHG4TruthInfoContainer::is_primary (const PHG4Particle * p) const
Definition at line 396 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 396 of file PHG4TruthInfoContainer.cc
References PHG4Particle::get_track_id().
Referenced by IsolatedTrackAnalysis::getG4Truth(), PhotonJet::GetRecoHadronsAndJets(), AnaTutorial::getTracks(), IsolatedTrackAnalysis::getTracks(), BJetModule::process_event(), and TruthCaloTree::process_event().
bool PHG4TruthInfoContainer::is_primary_vtx (const PHG4VtxPoint * v) const
Definition at line 391 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 391 of file PHG4TruthInfoContainer.cc
References PHG4VtxPoint::get_id().
int PHG4TruthInfoContainer::isEmbeded (const int trackid) const
Retrieve the embedding ID for the HepMC subevent or track to be analyzed. positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 369 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 369 of file PHG4TruthInfoContainer.cc
References particle_embed_flags.
Referenced by BaseTruthEval::get_embed(), VtxTest::get_embed(), DSTEmulator::get_embed(), TruthConversionEval::get_embed(), TrackEvaluation::get_embed(), TruthJetInput::get_input(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluator::printOutputInfo(), PHSiliconTruthTrackSeeding::Process(), PHG4TruthSubsystem::process_after_geant(), PHG4ConsistencyCheck::process_event(), BJetModule::process_event(), DetermineTowerBackground::process_event(), Photons::process_event(), PHG4TpcElectronDrift::process_event(), PHTruthClustering::process_event(), pythiaEMCalAna::process_event(), MyJetAnalysis::process_event(), PHG4InttHitReco::truthcheck_g4hit(), and PHG4MvtxHitReco::truthcheck_g4hit().
int PHG4TruthInfoContainer::isEmbededVtx (const int vtxid) const
Retrieve the embedding ID for the HepMC subevent or track to be analyzed. positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 380 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 380 of file PHG4TruthInfoContainer.cc
References vertex_embed_flags.
Referenced by SvtxEvaluator::fillOutputNtuples(), GetPrimaryVertexIndex(), dNdEtaINTT::GetTruthPVInfo(), PHTruthVertexing::Process(), PHSiliconTruthTrackSeeding::Process(), and QAG4SimulationVertex::process_event().
int PHG4TruthInfoContainer::maxshowerindex () const
Definition at line 302 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 302 of file PHG4TruthInfoContainer.cc
References showermap.
Referenced by DumpPHG4TruthInfoContainer::process_Node().
int PHG4TruthInfoContainer::maxtrkindex () const
Definition at line 246 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 246 of file PHG4TruthInfoContainer.cc
References particlemap.
Referenced by PHG4TruthTrackingAction::AddParticle(), PHG4TpcDirectLaser::AppendLaserTrack(), Fun4AllDstPileupMerger::copy_background_event(), and DumpPHG4TruthInfoContainer::process_Node().
int PHG4TruthInfoContainer::maxvtxindex () const
Definition at line 274 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 274 of file PHG4TruthInfoContainer.cc
References vtxmap.
Referenced by PHG4TruthTrackingAction::AddVertex(), PHG4TpcDirectLaser::AppendLaserTrack(), Fun4AllDstPileupMerger::copy_background_event(), and DumpPHG4TruthInfoContainer::process_Node().
int PHG4TruthInfoContainer::minshowerindex () const
Definition at line 316 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 316 of file PHG4TruthInfoContainer.cc
References showermap.
Referenced by DumpPHG4TruthInfoContainer::process_Node().
int PHG4TruthInfoContainer::mintrkindex () const
Definition at line 260 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 260 of file PHG4TruthInfoContainer.cc
References particlemap.
Referenced by PHG4TruthTrackingAction::AddParticle(), Fun4AllDstPileupMerger::copy_background_event(), and DumpPHG4TruthInfoContainer::process_Node().
int PHG4TruthInfoContainer::minvtxindex () const
Definition at line 288 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 288 of file PHG4TruthInfoContainer.cc
References vtxmap.
Referenced by PHG4TruthTrackingAction::AddVertex(), Fun4AllDstPileupMerger::copy_background_event(), and DumpPHG4TruthInfoContainer::process_Node().
void PHG4TruthInfoContainer::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 24 of file PHG4TruthInfoContainer.cc.
View newest version in sPHENIX GitHub at line 24 of file PHG4TruthInfoContainer.cc
References particle_embed_flags, particlemap, showermap, vertex_embed_flags, and vtxmap.
Referenced by ~PHG4TruthInfoContainer().
unsigned int PHG4TruthInfoContainer::shower_size (void) const inline
shower size
Definition at line 188 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 188 of file PHG4TruthInfoContainer.h
References showermap.
Referenced by DumpPHG4TruthInfoContainer::process_Node().
unsigned int PHG4TruthInfoContainer::size (void) const inline
track -> particle map size
Definition at line 69 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4TruthInfoContainer.h
References particlemap.
Referenced by SigmaTimingNtuple::process_event(), SynRadAna::process_event(), ElectronID::process_event(), and DumpPHG4TruthInfoContainer::process_Node().
Member Data Documentation
std::map<int, int> PHG4TruthInfoContainer::particle_embed_flags private
Definition at line 230 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 230 of file PHG4TruthInfoContainer.h
Referenced by AddEmbededTrkId(), GetEmbeddedTrkIds(), identify(), isEmbeded(), and Reset().
Map PHG4TruthInfoContainer::particlemap private
particle storage map format description: primary particles are appended in the positive direction secondary particles are appended in the negative direction +N primary particle id => particle* +N-1 ... +1 primary particle id => particle* 0 no entry -1 secondary particle id => particle* ... -M+1 -M secondary particle id => particle*
Definition at line 209 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 209 of file PHG4TruthInfoContainer.h
Referenced by AddParticle(), delete_particle(), GetMap(), GetNumPrimaryVertexParticles(), GetParticle(), GetParticleRange(), GetPrimaryParticle(), GetPrimaryParticleRange(), GetSecondaryParticleRange(), identify(), maxtrkindex(), mintrkindex(), Reset(), and size().
ShowerMap PHG4TruthInfoContainer::showermap private
shower map showers encapsulate the secondaries and hits from a primary particle
Definition at line 227 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 227 of file PHG4TruthInfoContainer.h
Referenced by AddShower(), delete_shower(), GetPrimaryShower(), GetPrimaryShowerRange(), GetSecondaryShowerRange(), GetShower(), GetShowerMap(), GetShowerRange(), identify(), maxshowerindex(), minshowerindex(), Reset(), and shower_size().
std::map<int, int> PHG4TruthInfoContainer::vertex_embed_flags private
Definition at line 231 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 231 of file PHG4TruthInfoContainer.h
Referenced by AddEmbededVtxId(), GetEmbeddedVtxIds(), identify(), isEmbededVtx(), and Reset().
VtxMap PHG4TruthInfoContainer::vtxmap private
vertex storage map format description: primary vertexes are appended in the positive direction secondary vertexes are appended in the negative direction +N primary vertex id => vertex* +N-1 ... +1 primary vertex id => vertex* 0 no entry -1 secondary vertex id => vertex* ... -M+1 -M secondary vertex id => vertex*
Definition at line 223 of file PHG4TruthInfoContainer.h.
View newest version in sPHENIX GitHub at line 223 of file PHG4TruthInfoContainer.h
Referenced by AddVertex(), delete_vtx(), GetNumVertices(), GetPrimaryVtx(), GetPrimaryVtxRange(), GetSecondaryVtxRange(), GetVtx(), GetVtxMap(), GetVtxRange(), identify(), maxvtxindex(), minvtxindex(), and Reset().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4TruthInfoContainer.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4TruthInfoContainer.cc