Analysis Software: MbdOut Class Reference
MbdOut Class Reference
#include <coresoftware/blob/master/offline/packages/mbd/MbdOut.h>
Public Member Functions
~MbdOut () override
void identify (std::ostream &os=std::cout) const override
virtual void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
virtual Float_t get_zvtx () const
get ZVertex determined by Mbd
virtual Float_t get_zvtxerr () const
get Error on ZVertex determined by Mbd
virtual Float_t get_t0 () const
get T0 determined by Mbd
virtual Float_t get_t0err () const
get Error on T0 determined by Mbd
virtual void set_t0zvtx (const Float_t t0, const Float_t t0err, const Float_t vtx, const Float_t vtxerr)
virtual void set_t0 (const Float_t t0, const Float_t t0err=0)
virtual void set_zvtx (const Float_t vtx, const Float_t vtxerr)
set vertex
virtual void set_zvtxerr (const Float_t vtxerr)
virtual void set_arm (const int iarm, const Short_t npmt, const Float_t ncharge, const Float_t timing)
virtual void set_clocks (const Int_t ievt, const UShort_t iclk, const UShort_t ifemclk)
virtual Short_t get_npmt (const int iarm) const
virtual Float_t get_q (const int iarm) const
virtual Float_t get_time (const int iarm) const
virtual Int_t get_evt () const
virtual UShort_t get_clock () const
virtual UShort_t get_femclock () const
virtual void FillFromClass (const MbdOut &old)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
void virtual_warning (const std::string &funcname) const
Detailed Description
Definition at line 11 of file MbdOut.h.
View newest version in sPHENIX GitHub at line 11 of file MbdOut.h
Constructor & Destructor Documentation
MbdOut::~MbdOut () inline override
Definition at line 15 of file MbdOut.h.
View newest version in sPHENIX GitHub at line 15 of file MbdOut.h
Member Function Documentation
void MbdOut::FillFromClass (const MbdOut & old) virtual
Definition at line 126 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 126 of file MbdOut.cc
References get_npmt(), get_q(), get_t0(), get_t0err(), get_time(), get_zvtx(), get_zvtxerr(), set_arm(), and set_t0zvtx().
UShort_t MbdOut::get_clock () const virtual
get XMIT Clock Counter
Reimplemented in MbdOutV2.
Definition at line 108 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 108 of file MbdOut.cc
References virtual_warning().
Int_t MbdOut::get_evt () const virtual
get Event Number
Reimplemented in MbdOutV2.
Definition at line 102 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 102 of file MbdOut.cc
References virtual_warning().
UShort_t MbdOut::get_femclock () const virtual
get FEM Clock Counter
Reimplemented in MbdOutV2.
Definition at line 114 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 114 of file MbdOut.cc
References virtual_warning().
Short_t MbdOut::get_npmt (const int iarm) const virtual
get Number of PMT's fired in North/South Mbd
Parameters
iarm Arm, use Mbd::North and Mbd::South
Reimplemented in MbdOutV2, and MbdOutV1.
Definition at line 84 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 84 of file MbdOut.cc
References MbdReturnCodes::MBD_INVALID_SHORT, and virtual_warning().
Referenced by FillFromClass(), MinimumBiasClassifier::FillMinimumBiasInfo(), and DumpMbdOut::process_Node().
Float_t MbdOut::get_q (const int iarm) const virtual
get Number of Charged Particles into North/South Mbd
Parameters
iarm Arm, use Mbd::North and Mbd::South
Reimplemented in MbdOutV2, and MbdOutV1.
Definition at line 90 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 90 of file MbdOut.cc
References virtual_warning().
Referenced by BbcCheck::CheckDST(), MBDStudy::CheckDST(), BBCStudy::CheckDST(), FillFromClass(), MinimumBiasClassifier::FillMinimumBiasInfo(), CentralityReco::FillVars(), JetBkgdSub::GetCentInfo(), and DumpMbdOut::process_Node().
Float_t MbdOut::get_t0 () const virtual
get T0 determined by Mbd
Reimplemented in MbdOutV1, and MbdOutV2.
Definition at line 37 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 37 of file MbdOut.cc
References virtual_warning().
Referenced by FillFromClass(), and DumpMbdOut::process_Node().
Float_t MbdOut::get_t0err () const virtual
get Error on T0 determined by Mbd
Reimplemented in MbdOutV1, and MbdOutV2.
Definition at line 44 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 44 of file MbdOut.cc
References virtual_warning().
Referenced by FillFromClass(), and DumpMbdOut::process_Node().
Float_t MbdOut::get_time (const int iarm) const virtual
get Timing of North/South Mbd
Parameters
iarm Arm, use Mbd::North and Mbd::South
Reimplemented in MbdOutV2, and MbdOutV1.
Definition at line 96 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 96 of file MbdOut.cc
References virtual_warning().
Referenced by FillFromClass(), and DumpMbdOut::process_Node().
Float_t MbdOut::get_zvtx () const virtual
get ZVertex determined by Mbd
Reimplemented in MbdOutV1, and MbdOutV2.
Definition at line 25 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 25 of file MbdOut.cc
References virtual_warning().
Referenced by BbcCheck::CheckDST(), MBDStudy::CheckDST(), BBCStudy::CheckDST(), FillFromClass(), and DumpMbdOut::process_Node().
Float_t MbdOut::get_zvtxerr () const virtual
get Error on ZVertex determined by Mbd
Reimplemented in MbdOutV1, and MbdOutV2.
Definition at line 31 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 31 of file MbdOut.cc
References virtual_warning().
Referenced by FillFromClass(), and DumpMbdOut::process_Node().
void MbdOut::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in MbdOutV1, and MbdOutV2.
Definition at line 7 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 7 of file MbdOut.cc
int MbdOut::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in MbdOutV1, and MbdOutV2.
Definition at line 19 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 19 of file MbdOut.cc
References virtual_warning().
Referenced by DumpMbdOut::process_Node().
void MbdOut::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in MbdOutV1, and MbdOutV2.
Definition at line 13 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 13 of file MbdOut.cc
Referenced by MbdEvent::Calculate().
void MbdOut::set_arm (const int iarm, const Short_t npmt, const Float_t ncharge, const Float_t timing) virtual
Add Mbd North/South data containing Number of pmt's, Energy and Timing
Parameters
npmt Number of PMT's fired
ncharge Number of Charged Particles into North/South
timing Timing of North/South
iarm Arm, use Mbd::North and Mbd::South
Reimplemented in MbdOutV1, and MbdOutV2.
Definition at line 72 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 72 of file MbdOut.cc
References virtual_warning().
Referenced by MbdEvent::Calculate(), and FillFromClass().
void MbdOut::set_clocks (const Int_t ievt, const UShort_t iclk, const UShort_t ifemclk) virtual
Add Mbd data containing evt, clk, and femclk
Parameters
ievt Event number
iclk XMIT clock
ifemclk FEM clock
Reimplemented in MbdOutV2.
Definition at line 78 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 78 of file MbdOut.cc
References virtual_warning().
Referenced by MbdEvent::Calculate().
void MbdOut::set_t0 (const Float_t t0, const Float_t t0err = 0) virtual
set T0 for Mbd
Parameters
t0 Mbd T0
t0err Mbd T0 error
Reimplemented in MbdOutV1, and MbdOutV2.
Definition at line 51 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 51 of file MbdOut.cc
References virtual_warning().
Referenced by MbdEvent::Calculate(), and set_t0zvtx().
virtual void MbdOut::set_t0zvtx (const Float_t t0, const Float_t t0err, const Float_t vtx, const Float_t vtxerr) inline virtual
set T0, Error on T0, ZVertex and Error on ZVertex
Parameters
t0 Mbd T0
t0err Mbd Error on T0
vtx Mbd ZVertex
vtxerr Mbd Error on ZVertex
Definition at line 46 of file MbdOut.h.
View newest version in sPHENIX GitHub at line 46 of file MbdOut.h
References set_t0(), and set_zvtx().
Referenced by FillFromClass().
void MbdOut::set_zvtx (const Float_t vtx, const Float_t vtxerr) virtual
set vertex
Reimplemented in MbdOutV1, and MbdOutV2.
Definition at line 58 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 58 of file MbdOut.cc
References virtual_warning().
Referenced by MbdEvent::Calculate(), and set_t0zvtx().
void MbdOut::set_zvtxerr (const Float_t vtxerr) virtual
set Vtx Error for Mbd
Parameters
vtxerr Mbd Vtx Error
Reimplemented in MbdOutV1, and MbdOutV2.
Definition at line 65 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 65 of file MbdOut.cc
References virtual_warning().
void MbdOut::virtual_warning (const std::string & funcname) const private
Definition at line 120 of file MbdOut.cc.
View newest version in sPHENIX GitHub at line 120 of file MbdOut.cc
Referenced by get_clock(), get_evt(), get_femclock(), get_npmt(), get_q(), get_t0(), get_t0err(), get_time(), get_zvtx(), get_zvtxerr(), isValid(), set_arm(), set_clocks(), set_t0(), set_zvtx(), and set_zvtxerr().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mbd/MbdOut.h
coresoftware/blob/master/offline/packages/mbd/MbdOut.cc