Analysis Software: FullJetFinder Class Reference
FullJetFinder Class Reference
#include <analysis/blob/master/JS-Jet/FullJetFinder/src/FullJetFinder.h>
Classes
struct chConstituent
class Container
class CutSelection
struct neConstituent
class PrimaryVertex
class RecoJets
reconstructed jets
class TruthJets
truth jets
Public Member Functions
FullJetFinder (const std::string &outputfilename="myjetanalysis.root")
HEPMC truth includes.
~FullJetFinder () override
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int ResetEvent (PHCompositeNode *topNode) override
Clean up internals after each event.
int EndRun (const int runnumber) override
Called at the end of each run.
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
int Reset (PHCompositeNode *) override
Reset.
void Print (const std::string &what="ALL") const override
void GetDistanceFromVertexXY (SvtxTrack *m_dst_track, GlobalVertex *m_dst_vertex, float &val, float &err)
void add_input (const std::string &recojetname="AntiKt_Tower_r04", const std::string &truthjetname="AntiKt_Truth_r04", const std::string &outputtreename="AntiKt_r04")
void doFiducialAcceptance (bool doF)
void setPtRangeReco (double low, double high)
void setPtRangeTruth (double low, double high)
void doTruth (int flag)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
int m_inputs = 0
std::vector< std::string > m_TreeNameCollection
std::vector< std::string > m_recoJetName
std::vector< std::string > m_truthJetName
std::string m_outputFileName
std::pair< double, double > m_etaRange
std::pair< double, double > m_ptRangeReco
std::pair< double, double > m_ptRangeTruth
int m_doTruthJets
bool doFiducial = false
TTree * m_T [10]
Output Tree variables.
std::vector< float > jetR
TH1I * m_stat
Container * m_container [10]
main branch
TH1D * m_chi2ndf [10]
TH1I * m_mvtxcl [10]
TH1I * m_inttcl [10]
TH1I * m_mtpccl [10]
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 36 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 36 of file FullJetFinder.h
Constructor & Destructor Documentation
FullJetFinder::FullJetFinder (const std::string & outputfilename = "myjetanalysis.root")
HEPMC truth includes.
Definition at line 65 of file FullJetFinder.cc.
View newest version in sPHENIX GitHub at line 65 of file FullJetFinder.cc
FullJetFinder::~FullJetFinder () override
Definition at line 79 of file FullJetFinder.cc.
View newest version in sPHENIX GitHub at line 79 of file FullJetFinder.cc
Member Function Documentation
void FullJetFinder::add_input (const std::string & recojetname = "AntiKt_Tower_r04", const std::string & truthjetname = "AntiKt_Truth_r04", const std::string & outputtreename = "AntiKt_r04") inline
Definition at line 79 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 79 of file FullJetFinder.h
References jetR, m_inputs, m_recoJetName, m_TreeNameCollection, and m_truthJetName.
void FullJetFinder::doFiducialAcceptance (bool doF) inline
Definition at line 88 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 88 of file FullJetFinder.h
References doFiducial.
void FullJetFinder::doTruth (int flag) inline
Definition at line 92 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 92 of file FullJetFinder.h
References m_doTruthJets.
int FullJetFinder::End (PHCompositeNode * topNode) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 510 of file FullJetFinder.cc.
View newest version in sPHENIX GitHub at line 510 of file FullJetFinder.cc
References cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), i, m_inputs, m_outputFileName, m_stat, m_T, and m_TreeNameCollection.
int FullJetFinder::EndRun (const int runnumber) override virtual
Called at the end of each run.
Reimplemented from SubsysReco.
Definition at line 503 of file FullJetFinder.cc.
View newest version in sPHENIX GitHub at line 503 of file FullJetFinder.cc
References Fun4AllReturnCodes::EVENT_OK.
void FullJetFinder::GetDistanceFromVertexXY (SvtxTrack * m_dst_track, GlobalVertex * m_dst_vertex, float & val, float & err)
Definition at line 550 of file FullJetFinder.cc.
View newest version in sPHENIX GitHub at line 550 of file FullJetFinder.cc
References KFParticle::Chi2(), KFParticle::Create(), SvtxTrack::get_charge(), GlobalVertex::get_chisq(), SvtxTrack::get_chisq(), GlobalVertex::get_error(), SvtxTrack::get_error(), SvtxTrack::get_id(), SvtxTrack::get_ndf(), GlobalVertex::get_ndof(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), GlobalVertex::get_x(), SvtxTrack::get_x(), GlobalVertex::get_y(), SvtxTrack::get_y(), GlobalVertex::get_z(), SvtxTrack::get_z(), KFParticle::GetDistanceFromVertexXY(), i, j, KFParticle::NDF(), and KFParticleBase::SetId().
Referenced by process_event().
int FullJetFinder::Init (PHCompositeNode * topNode) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 97 of file FullJetFinder.cc.
View newest version in sPHENIX GitHub at line 97 of file FullJetFinder.cc
References Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), i, m_chi2ndf, m_container, m_inputs, m_inttcl, m_mtpccl, m_mvtxcl, m_outputFileName, m_stat, m_T, m_TreeNameCollection, PHTFileServer::open(), and Acts::Test::tmp().
int FullJetFinder::InitRun (PHCompositeNode * topNode) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.
Reimplemented from SubsysReco.
Definition at line 133 of file FullJetFinder.cc.
View newest version in sPHENIX GitHub at line 133 of file FullJetFinder.cc
References Fun4AllReturnCodes::EVENT_OK.
void FullJetFinder::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 545 of file FullJetFinder.cc.
View newest version in sPHENIX GitHub at line 545 of file FullJetFinder.cc
int FullJetFinder::process_event (PHCompositeNode * topNode) override virtual
Called for each event. This is where you do the real work.
If the node was not properly put on the tree, return
Reimplemented from SubsysReco.
Definition at line 140 of file FullJetFinder.cc.
View newest version in sPHENIX GitHub at line 140 of file FullJetFinder.cc
References Fun4AllReturnCodes::ABORTEVENT, FullJetFinder::RecoJets::area, FullJetFinder::TruthJets::area, assert, parse_cmake_options::begin, FullJetFinder::Container::centrality, FullJetFinder::RecoJets::chConstituents, FullJetFinder::chConstituent::chisq, FullJetFinder::PrimaryVertex::chisq, mvtx_utils::comp(), FullJetFinder::TruthJets::constituents_PDG_ID, FullJetFinder::chConstituent::DCA_xy, FullJetFinder::chConstituent::DCA_xy_unc, doFiducial, FullJetFinder::neConstituent::e, FullJetFinder::chConstituent::e, FullJetFinder::RecoJets::e, FullJetFinder::TruthJets::e, Acts::UnitConstants::e, GlobalVertexMap::empty(), end, FullJetFinder::neConstituent::eta, FullJetFinder::chConstituent::eta, FullJetFinder::RecoJets::eta, FullJetFinder::TruthJets::eta, Fun4AllReturnCodes::EVENT_OK, PHHepMCGenEventMap::get(), PHG4Particle::get_barcode(), CentralityInfo::get_centile(), SvtxTrack::get_chisq(), TrackAnalysisUtils::get_cluster_keys(), ParticleFlowElement::get_e(), ParticleFlowElement::get_eta(), SvtxTrack::get_ndf(), ParticleFlowElement::get_phi(), ParticleFlowElement::get_pt(), CentralityInfo::get_quantity(), ParticleFlowElement::get_track(), ParticleFlowElement::get_type(), SvtxTrack::get_vertex_id(), GlobalVertex::get_x(), SvtxTrack::get_x(), GlobalVertex::get_y(), SvtxTrack::get_y(), GetDistanceFromVertexXY(), PHHepMCGenEvent::getEvent(), ParticleFlowElementContainer::getParticleFlowElement(), PHG4TruthInfoContainer::GetPrimaryParticle(), TrkrDefs::getTrkrId(), FullJetFinder::RecoJets::id, FullJetFinder::TruthJets::id, FullJetFinder::PrimaryVertex::id, train_ambiguity_solver::id, FullJetFinder::Container::impactparam, digitization_config::input, TrkrDefs::inttId, jetR, FullJetFinder::RecoJets::m, FullJetFinder::TruthJets::m, m_container, m_doTruthJets, m_inputs, m_ptRangeReco, m_ptRangeTruth, m_recoJetName, m_stat, m_T, m_truthJetName, Enable::MBD, TrkrDefs::mvtxId, FullJetFinder::chConstituent::n_intt, FullJetFinder::chConstituent::n_mvtx, FullJetFinder::chConstituent::n_tpc, FullJetFinder::chConstituent::ndf, FullJetFinder::PrimaryVertex::ndf, FullJetFinder::RecoJets::neConstituents, FullJetFinder::RecoJets::num_ChConstituents, FullJetFinder::TruthJets::num_ChConstituents, FullJetFinder::RecoJets::num_Constituents, FullJetFinder::TruthJets::num_Constituents, FullJetFinder::neConstituent::pflowtype, FullJetFinder::chConstituent::pflowtype, FullJetFinder::neConstituent::phi, FullJetFinder::chConstituent::phi, FullJetFinder::RecoJets::phi, FullJetFinder::TruthJets::phi, PHWHERE, FullJetFinder::Container::primaryVertex, JetContainer::property_index(), FullJetFinder::chConstituent::pt, FullJetFinder::RecoJets::pt, FullJetFinder::TruthJets::pt, FullJetFinder::RecoJets::px, FullJetFinder::TruthJets::px, FullJetFinder::RecoJets::py, FullJetFinder::TruthJets::py, FullJetFinder::RecoJets::pz, FullJetFinder::TruthJets::pz, FullJetFinder::Container::reco_jet_n, FullJetFinder::Container::recojets, FullJetFinder::Container::Reset(), FullJetFinder::chConstituent::sDCA_xy, sign(), parse_cmake_options::source, TrkrDefs::tpcId, FullJetFinder::Container::truth_jet_n, FullJetFinder::Container::truthjets, FullJetFinder::chConstituent::vtx_id, FullJetFinder::PrimaryVertex::vtxtype, FullJetFinder::PrimaryVertex::x, FullJetFinder::PrimaryVertex::x_unc, FullJetFinder::PrimaryVertex::y, FullJetFinder::PrimaryVertex::y_unc, FullJetFinder::PrimaryVertex::z, and FullJetFinder::PrimaryVertex::z_unc.
int FullJetFinder::Reset (PHCompositeNode * topNode) override virtual
Reset.
Reimplemented from SubsysReco.
Definition at line 538 of file FullJetFinder.cc.
View newest version in sPHENIX GitHub at line 538 of file FullJetFinder.cc
References Fun4AllReturnCodes::EVENT_OK.
int FullJetFinder::ResetEvent (PHCompositeNode * topNode) override virtual
Clean up internals after each event.
Reimplemented from SubsysReco.
Definition at line 496 of file FullJetFinder.cc.
View newest version in sPHENIX GitHub at line 496 of file FullJetFinder.cc
References Fun4AllReturnCodes::EVENT_OK.
void FullJetFinder::setPtRangeReco (double low, double high) inline
Definition at line 90 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 90 of file FullJetFinder.h
References m_ptRangeReco.
void FullJetFinder::setPtRangeTruth (double low, double high) inline
Definition at line 91 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 91 of file FullJetFinder.h
References m_ptRangeTruth.
Member Data Documentation
bool FullJetFinder::doFiducial = false private
Definition at line 206 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 206 of file FullJetFinder.h
Referenced by doFiducialAcceptance(), and process_event().
std::vector<float> FullJetFinder::jetR private
Definition at line 210 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 210 of file FullJetFinder.h
Referenced by add_input(), and process_event().
TH1D* FullJetFinder::m_chi2ndf[10] private
Definition at line 216 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 216 of file FullJetFinder.h
Referenced by Init().
Container* FullJetFinder::m_container[10] private
main branch
Definition at line 214 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 214 of file FullJetFinder.h
Referenced by Init(), and process_event().
int FullJetFinder::m_doTruthJets private
Definition at line 204 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 204 of file FullJetFinder.h
Referenced by doTruth(), and process_event().
std::pair<double, double> FullJetFinder::m_etaRange private
Definition at line 201 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 201 of file FullJetFinder.h
int FullJetFinder::m_inputs = 0 private
Definition at line 196 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 196 of file FullJetFinder.h
Referenced by add_input(), End(), Init(), and process_event().
TH1I* FullJetFinder::m_inttcl[10] private
Definition at line 218 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 218 of file FullJetFinder.h
Referenced by Init().
TH1I* FullJetFinder::m_mtpccl[10] private
Definition at line 219 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 219 of file FullJetFinder.h
Referenced by Init().
TH1I* FullJetFinder::m_mvtxcl[10] private
Definition at line 217 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 217 of file FullJetFinder.h
Referenced by Init().
std::string FullJetFinder::m_outputFileName private
Definition at line 200 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 200 of file FullJetFinder.h
Referenced by End(), and Init().
std::pair<double, double> FullJetFinder::m_ptRangeReco private
Definition at line 202 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 202 of file FullJetFinder.h
Referenced by process_event(), and setPtRangeReco().
std::pair<double, double> FullJetFinder::m_ptRangeTruth private
Definition at line 203 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 203 of file FullJetFinder.h
Referenced by process_event(), and setPtRangeTruth().
std::vector<std::string> FullJetFinder::m_recoJetName private
Definition at line 198 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 198 of file FullJetFinder.h
Referenced by add_input(), and process_event().
TH1I* FullJetFinder::m_stat private
Definition at line 211 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 211 of file FullJetFinder.h
Referenced by End(), Init(), and process_event().
TTree* FullJetFinder::m_T[10] private
Output Tree variables.
Definition at line 209 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 209 of file FullJetFinder.h
Referenced by End(), Init(), and process_event().
std::vector<std::string> FullJetFinder::m_TreeNameCollection private
Definition at line 197 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 197 of file FullJetFinder.h
Referenced by add_input(), End(), and Init().
std::vector<std::string> FullJetFinder::m_truthJetName private
Definition at line 199 of file FullJetFinder.h.
View newest version in sPHENIX GitHub at line 199 of file FullJetFinder.h
Referenced by add_input(), and process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/JS-Jet/FullJetFinder/src/FullJetFinder.h
analysis/blob/master/JS-Jet/FullJetFinder/src/FullJetFinder.cc