Analysis Software: gtest_xml_output_unittest.GTestXMLOutputUnitTest Class Reference
gtest_xml_output_unittest.GTestXMLOutputUnitTest Class Reference
Public Member Functions
def testNonEmptyXmlOutput
def testEmptyXmlOutput
def testTimestampValue
def testDefaultOutputFile
def testSuppressedXmlOutput
def testFilteredTestXmlOutput
Public Member Functions inherited from gtest_xml_test_utils.GTestXMLTestCase
def AssertEquivalentNodes
def NormalizeXml
Private Member Functions
def _GetXmlOutput
def _TestXmlOutput
Additional Inherited Members
Static Public Attributes inherited from gtest_xml_test_utils.GTestXMLTestCase
dictionary identifying_attribute
Detailed Description
Unit test for Google Test's XML output functionality.
Definition at line 152 of file gtest_xml_output_unittest.py.
View newest version in sPHENIX GitHub at line 152 of file gtest_xml_output_unittest.py
Member Function Documentation
def gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput (self, gtest_prog_name, extra_args, expected_exit_code) private
Returns the xml output generated by running the program gtest_prog_name.
Furthermore, the program's exit code must be expected_exit_code.
Definition at line 263 of file gtest_xml_output_unittest.py.
View newest version in sPHENIX GitHub at line 263 of file gtest_xml_output_unittest.py
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput(), gtest_test_utils.GetTempDir(), and gtest_test_utils.GetTestExecutablePath().
Referenced by gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testTimestampValue().
def gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput (self, gtest_prog_name, expected_xml, expected_exit_code, extra_args = None) private
Asserts that the XML document generated by running the program
gtest_prog_name matches expected_xml, a string containing another
XML document.  Furthermore, the program's exit code must be
expected_exit_code.
Definition at line 288 of file gtest_xml_output_unittest.py.
View newest version in sPHENIX GitHub at line 288 of file gtest_xml_output_unittest.py
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput(), gtest_xml_test_utils.GTestXMLTestCase.AssertEquivalentNodes(), gtest_test_utils.Main(), and gtest_xml_test_utils.GTestXMLTestCase.NormalizeXml().
Referenced by gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput(), gtest_xml_output_unittest.GTestXMLOutputUnitTest.testEmptyXmlOutput(), gtest_xml_output_unittest.GTestXMLOutputUnitTest.testFilteredTestXmlOutput(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testNonEmptyXmlOutput().
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testDefaultOutputFile (self)
Confirms that Google Test produces an XML output file with the expected
default name if no name is explicitly specified.
Definition at line 201 of file gtest_xml_output_unittest.py.
View newest version in sPHENIX GitHub at line 201 of file gtest_xml_output_unittest.py
References gtest_test_utils.GetTempDir(), and gtest_test_utils.GetTestExecutablePath().
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testEmptyXmlOutput (self)
Verifies XML output for a Google Test binary without actual tests.
Runs a test program that generates an empty XML output, and
tests that the XML output is expected.
Definition at line 167 of file gtest_xml_output_unittest.py.
View newest version in sPHENIX GitHub at line 167 of file gtest_xml_output_unittest.py
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput().
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testFilteredTestXmlOutput (self)
Verifies XML output when a filter is applied.
Runs a test program that executes only some tests and verifies that
non-selected tests do not show up in the XML output.
Definition at line 253 of file gtest_xml_output_unittest.py.
View newest version in sPHENIX GitHub at line 253 of file gtest_xml_output_unittest.py
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput().
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testNonEmptyXmlOutput (self)
Runs a test program that generates a non-empty XML output, and
tests that the XML output is expected.
Definition at line 160 of file gtest_xml_output_unittest.py.
View newest version in sPHENIX GitHub at line 160 of file gtest_xml_output_unittest.py
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput().
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testSuppressedXmlOutput (self)
Tests that no XML file is generated if the default XML listener is
shut down before RUN_ALL_TESTS is invoked.
Definition at line 224 of file gtest_xml_output_unittest.py.
View newest version in sPHENIX GitHub at line 224 of file gtest_xml_output_unittest.py
References gtest_test_utils.GetTempDir().
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testTimestampValue (self)
Checks whether the timestamp attribute in the XML output is valid.
Runs a test program that generates an empty XML output, and checks if
the timestamp attribute in the testsuites tag is valid.
Definition at line 176 of file gtest_xml_output_unittest.py.
View newest version in sPHENIX GitHub at line 176 of file gtest_xml_output_unittest.py
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/googletest/googletest/test/gtest_xml_output_unittest.py