Analysis Software: analysis/blob/master/AndersonAnalysisModules/TrackStudies/STrackCutStudy/macros/Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn.C File Reference
Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn.C File Reference
#include <GlobalVariables.C>
#include <DisplayOn.C>
#include <G4Setup_sPHENIX.C>
#include <G4_Bbc.C>
#include <G4_CaloTrigger.C>
#include <G4_Centrality.C>
#include <G4_DSTReader.C>
#include <G4_Global.C>
#include <G4_HIJetReco.C>
#include <G4_Input.C>
#include <G4_Jets.C>
#include <G4_KFParticle.C>
#include <G4_ParticleFlow.C>
#include <G4_Production.C>
#include <G4_TopoClusterReco.C>
#include <Trkr_RecoInit.C>
#include <Trkr_Clustering.C>
#include <Trkr_LaserClustering.C>
#include <Trkr_Reco.C>
#include <Trkr_Eval.C>
#include <Trkr_QA.C>
#include <Trkr_Diagnostics.C>
#include <G4_User.C>
#include <QA.C>
#include <ffamodules/FlagHandler.h>
#include <ffamodules/HeadReco.h>
#include <ffamodules/SyncReco.h>
#include <ffamodules/CDBInterface.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <phool/PHRandomSeed.h>
#include <phool/recoConsts.h>
Macros
#define MACRO_FUN4ALLG4SPHENIX_C
Functions
int Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn (const int nEvents=1, const string &inputFile="https://www.phenix.bnl.gov/WWW/publish/phnxbld/sPHENIX/files/sPHENIX_G4Hits_sHijing_9-11fm_00000_00010.root", const string &outputFile="G4sPHENIX.root", const string &embed_input_file="https://www.phenix.bnl.gov/WWW/publish/phnxbld/sPHENIX/files/sPHENIX_G4Hits_sHijing_9-11fm_00000_00010.root", const int skip=0, const string &outdir=".")
Macro Definition Documentation
#define MACRO_FUN4ALLG4SPHENIX_C
Definition at line 2 of file Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn.C.
View newest version in sPHENIX GitHub at line 2 of file Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn.C
Function Documentation
int Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn (const int nEvents = 1, const string & inputFile = "https://www.phenix.bnl.gov/WWW/publish/phnxbld/sPHENIX/files/sPHENIX_G4Hits_sHijing_9-11fm_00000_00010.root", const string & outputFile = "G4sPHENIX.root", const string & embed_input_file = "https://www.phenix.bnl.gov/WWW/publish/phnxbld/sPHENIX/files/sPHENIX_G4Hits_sHijing_9-11fm_00000_00010.root", const int skip = 0, const string & outdir = ".")
Nominal collision geometry is selected by Input::BEAM_CONFIGURATION
Nominal collision geometry is selected by Input::BEAM_CONFIGURATION
Nominal collision geometry is selected by Input::BEAM_CONFIGURATION
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Nominal collision geometry is selected by Input::BEAM_CONFIGURATION
forward flux return plug door. Out of acceptance and off by default.
Definition at line 50 of file Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn.C.
View newest version in sPHENIX GitHub at line 50 of file Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn.C
References Input::ApplysPHENIXBeamParameter(), Bbc_Reco(), Enable::BEAMLINE, Enable::BLACKHOLE, Enable::CALOTRIGGER, CaloTrigger_Sim(), Enable::CDB, Enable::CEMC, Enable::CEMC_ABSORBER, Enable::CEMC_CELL, CEMC_Cells(), Enable::CEMC_CLUSTER, CEMC_Clusters(), Enable::CEMC_EVAL, CEMC_Eval(), Enable::CEMC_QA, Enable::CEMC_TOWER, CEMC_Towers(), Enable::CENTRALITY, Centrality(), PHHepMCGenHelper::CopyHelperSettings(), Enable::DISPLAY, DisplayOn(), DstCompress(), Enable::DSTOUT, Enable::DSTOUT_COMPRESS, Enable::DSTREADER, Input::DZERO, Input::EMBED, G4TPC::ENABLE_CENTRAL_MEMBRANE_HITS, G4TPC::ENABLE_DIRECT_LASER_HITS, Fun4AllServer::End(), Enable::EPD, Enable::EPD_TILE, EPD_Tiles(), INPUTHEPMC::filename, INPUTREADHITS::filename, INPUTEMBED::filename, G4TRACKING::filter_conversion_electrons, Filter_Conversion_Electrons(), G4DSTreader(), G4TRACKING::g4eval_use_initial_vertex, G4Init(), G4KshortReconstruction(), G4Setup(), PHG4SimpleEventGenerator::Gaus, Enable::GLOBAL_FASTSIM, Global_FastSim(), Global_Reco(), Enable::GLOBAL_RECO, CDB::global_tag, Input::GUN, INPUTGENERATOR::Gun, Enable::HCALIN, Enable::HCALIN_ABSORBER, Enable::HCALIN_CELL, Enable::HCALIN_CLUSTER, Enable::HCALIN_EVAL, Enable::HCALIN_QA, Enable::HCALIN_TOWER, HCALInner_Cells(), HCALInner_Clusters(), HCALInner_Eval(), HCALInner_QA(), HCALInner_Towers(), Enable::HCALOUT, Enable::HCALOUT_ABSORBER, Enable::HCALOUT_CELL, Enable::HCALOUT_CLUSTER, Enable::HCALOUT_EVAL, Enable::HCALOUT_QA, Enable::HCALOUT_TOWER, HCALOuter_Cells(), HCALOuter_Clusters(), HCALOuter_Eval(), HCALOuter_QA(), HCALOuter_Towers(), Input::HEPMC, INPUTMANAGER::HepMCInputManager, INPUTMANAGER::HepMCPileupInputManager, HIJetReco(), Enable::HIJETS, InputInit(), InputManagers(), InputRegister(), recoConsts::instance(), Fun4AllServer::instance(), Enable::INTT, Enable::INTT_CELL, Intt_Cells(), Enable::INTT_CLUSTER, Intt_Clustering(), Enable::INTT_QA, Intt_QA(), Jet_Eval(), Jet_QA(), Jet_Reco(), Enable::JETS, Enable::JETS_EVAL, Enable::JETS_QA, Enable::KFPARTICLE, KFParticle_D0_Reco(), KFParticle_Upsilon_Reco(), Enable::MAGNET, Enable::MAGNET_ABSORBER, Enable::MICROMEGAS, Enable::MICROMEGAS_CELL, Micromegas_Cells(), Enable::MICROMEGAS_CLUSTER, Micromegas_Clustering(), Enable::MICROMEGAS_QA, Micromegas_QA(), Enable::MVTX, Enable::MVTX_CELL, Mvtx_Cells(), Enable::MVTX_CLUSTER, Mvtx_Clustering(), Enable::MVTX_QA, Mvtx_QA(), G4TPC::n_gas_layer, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, G4MICROMEGAS::n_micromegas_layer, out, DstOut::OutputDir, DstOut::OutputFile, Enable::PARTICLEFLOW, ParticleFlow(), Input::PILEUPRATE, Enable::PIPE, Enable::PIPE_ABSORBER, Enable::PLUGDOOR_ABSORBER, Acts::Test::pos, TRACKING::pp_mode, Enable::PRODUCTION, Production_CreateOutputDir(), Production_MoveOutput(), Input::PYTHIA6, INPUTGENERATOR::Pythia6, Input::PYTHIA8, INPUTGENERATOR::Pythia8, Enable::QA, QA_G4CaloTracking(), QA_Output(), Input::READHITS, Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), INPUTEMBED::REPEAT, Fun4AllServer::run(), seedResiduals(), PHFlag::set_IntFlag(), PHFlag::set_StringFlag(), PHFlag::set_uint64Flag(), ShowerCompress(), Input::SIMPLE, INPUTGENERATOR::SimpleEventGenerator, Fun4AllServer::skip(), CDB::timestamp, Enable::TOPOCLUSTER, TopoClusterReco(), Enable::TPC, Enable::TPC_ABSORBER, Enable::TPC_CELL, TPC_Cells(), Enable::TPC_CLUSTER, TPC_Clustering(), TPC_LaserClustering(), Enable::TPC_QA, TPC_QA(), Enable::TRACKING_DIAGNOSTICS, Enable::TRACKING_EVAL, Enable::TRACKING_QA, Tracking_QA(), Tracking_Reco(), Enable::TRACKING_TRACK, TrackingInit(), Input::UPSILON, Enable::USER, UserAnalysisInit(), INPUTGENERATOR::VectorMesonGenerator, PHRandomSeed::Verbosity(), Fun4AllBase::Verbosity(), Input::VERBOSITY, Verbosity(), Enable::ZDC, Enable::ZDC_EVAL, and Enable::ZDC_TOWER.