Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Plugins/Json/DetectorVolumeJsonConverterTests.cpp File Reference
DetectorVolumeJsonConverterTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Detector/DetectorVolume.hpp"
#include "Acts/Detector/DetectorVolumeBuilder.hpp"
#include "Acts/Detector/LayerStructureBuilder.hpp"
#include "Acts/Detector/PortalGenerators.hpp"
#include "Acts/Detector/VolumeStructureBuilder.hpp"
#include "Acts/Geometry/CylinderVolumeBounds.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Navigation/DetectorVolumeFinders.hpp"
#include "Acts/Navigation/SurfaceCandidatesUpdators.hpp"
#include "Acts/Plugins/Json/DetectorVolumeJsonConverter.hpp"
#include "Acts/Surfaces/CylinderBounds.hpp"
#include "Acts/Surfaces/CylinderSurface.hpp"
#include "Acts/Tests/CommonHelpers/CylindricalTrackingGeometry.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include <fstream>
#include <memory>
#include <vector>
#include <nlohmann/json.hpp>
Functions
BOOST_AUTO_TEST_CASE (SingleEmptyVolume)
BOOST_AUTO_TEST_CASE (SingleSurfaceVolume)
BOOST_AUTO_TEST_CASE (EndcapVolumeWithSurfaces)
BOOST_AUTO_TEST_CASE (BarrelVolumeWithSurfaces)
Variables
Acts::GeometryContext tContext
auto cGeometry = Acts::Test::CylindricalTrackingGeometry(tContext)
auto portalGenerator = Acts::Experimental::defaultPortalGenerator()
Function Documentation
BOOST_AUTO_TEST_CASE (SingleEmptyVolume)
Definition at line 57 of file DetectorVolumeJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 57 of file DetectorVolumeJsonConverterTests.cpp
References bounds, Acts::Experimental::DetectorVolumeFactory::construct(), Acts::DetectorVolumeJsonConverter::fromJson(), in, testing::internal::move(), nominal, out, portalGenerator, Acts::DetectorVolumeJsonConverter::toJson(), Acts::DetectorVolumeJsonConverter::toJsonDetray(), Acts::DetectorVolumeJsonConverter::Options::transformOptions, Acts::Experimental::tryAllPortals(), and Acts::Transform3JsonConverter::Options::writeIdentity.
BOOST_AUTO_TEST_CASE (SingleSurfaceVolume)
Definition at line 108 of file DetectorVolumeJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 108 of file DetectorVolumeJsonConverterTests.cpp
References Acts::Experimental::DetectorVolumeFactory::construct(), Acts::DetectorVolumeJsonConverter::fromJson(), in, testing::internal::move(), nominal, out, portalGenerator, Acts::DetectorVolumeJsonConverter::toJson(), Acts::Experimental::tryAllPortalsAndSurfaces(), and Acts::Experimental::tryRootVolumes().
BOOST_AUTO_TEST_CASE (EndcapVolumeWithSurfaces)
Definition at line 151 of file DetectorVolumeJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 151 of file DetectorVolumeJsonConverterTests.cpp
References Acts::Experimental::DetectorVolumeBuilder::Config::auxiliary, Acts::Experimental::LayerStructureBuilder::Config::auxiliary, Acts::binPhi, Acts::Experimental::VolumeStructureBuilder::Config::boundValues, cGeometry, Acts::DetectorVolumeJsonConverter::fromJson(), Acts::getDefaultLogger(), in, out, Acts::DetectorVolumeJsonConverter::toJson(), physmon_ckf_tracking::u, Acts::Logging::VERBOSE, and volumes.
BOOST_AUTO_TEST_CASE (BarrelVolumeWithSurfaces)
Definition at line 229 of file DetectorVolumeJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 229 of file DetectorVolumeJsonConverterTests.cpp
References Acts::Experimental::DetectorVolumeBuilder::Config::auxiliary, Acts::Experimental::LayerStructureBuilder::Config::auxiliary, Acts::binPhi, Acts::binZ, Acts::Experimental::VolumeStructureBuilder::Config::boundValues, cGeometry, Acts::DetectorVolumeJsonConverter::fromJson(), Acts::getDefaultLogger(), in, out, Acts::DetectorVolumeJsonConverter::toJson(), physmon_ckf_tracking::u, Acts::Logging::VERBOSE, and volumes.
Variable Documentation
auto cGeometry = Acts::Test::CylindricalTrackingGeometry(tContext)
Definition at line 51 of file DetectorVolumeJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 51 of file DetectorVolumeJsonConverterTests.cpp
auto portalGenerator = Acts::Experimental::defaultPortalGenerator()
Definition at line 53 of file DetectorVolumeJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 53 of file DetectorVolumeJsonConverterTests.cpp
Acts::GeometryContext tContext
Definition at line 50 of file DetectorVolumeJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file DetectorVolumeJsonConverterTests.cpp