Analysis Software: CentralityReco Class Reference
CentralityReco Class Reference
#include <coresoftware/blob/master/offline/packages/centrality/CentralityReco.h>
Public Member Functions
CentralityReco (const std::string &name="CentralityReco")
constructor
~CentralityReco () override=default
destructor
int InitRun (PHCompositeNode *) override
full initialization
void CreateNodes (PHCompositeNode *)
int FillCentralityInfo ()
int FillVars ()
int GetNodes (PHCompositeNode *)
int process_event (PHCompositeNode *) override
event processing method
int ResetEvent (PHCompositeNode *) override
Clean up after each event.
int Download_centralityDivisions (const std::string &dbfile)
int Download_centralityScale (const std::string &dbfile)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
std::string _dbfilename
const int NDIVS {100}
MbdOut * _mbd_out {nullptr}
CentralityInfo * _central {nullptr}
unsigned int _key {std::numeric_limits<unsigned int>::max()}
float _mbd_charge_sum {std::numeric_limits<float>::quiet_NaN()}
float _mbd_charge_sum_n {std::numeric_limits<float>::quiet_NaN()}
float _mbd_charge_sum_s {std::numeric_limits<float>::quiet_NaN()}
double _centrality_scale {std::numeric_limits<double>::quiet_NaN()}
std::array< float, 100 > _centrality_map {}
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 14 of file CentralityReco.h.
View newest version in sPHENIX GitHub at line 14 of file CentralityReco.h
Constructor & Destructor Documentation
CentralityReco::CentralityReco (const std::string & name = "CentralityReco") explicit
constructor
Definition at line 25 of file CentralityReco.cc.
View newest version in sPHENIX GitHub at line 25 of file CentralityReco.cc
CentralityReco::~CentralityReco () override default
destructor
Member Function Documentation
void CentralityReco::CreateNodes (PHCompositeNode * topNode)
Definition at line 233 of file CentralityReco.cc.
View newest version in sPHENIX GitHub at line 233 of file CentralityReco.cc
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), PHWHERE, and Fun4AllBase::Verbosity().
Referenced by InitRun().
int CentralityReco::Download_centralityDivisions (const std::string & dbfile)
Definition at line 78 of file CentralityReco.cc.
View newest version in sPHENIX GitHub at line 78 of file CentralityReco.cc
References _centrality_map, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, CDBTTree::GetFloatValue(), CDBTTree::LoadCalibrations(), NDIVS, path, PHWHERE, CDBTTree::Print(), and Fun4AllBase::Verbosity().
Referenced by InitRun().
int CentralityReco::Download_centralityScale (const std::string & dbfile)
Definition at line 53 of file CentralityReco.cc.
View newest version in sPHENIX GitHub at line 53 of file CentralityReco.cc
References _centrality_scale, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, CDBTTree::GetDoubleValue(), CDBTTree::LoadCalibrations(), path, PHWHERE, and Fun4AllBase::Verbosity().
Referenced by InitRun().
int CentralityReco::FillCentralityInfo ()
Definition at line 147 of file CentralityReco.cc.
View newest version in sPHENIX GitHub at line 147 of file CentralityReco.cc
References _central, _centrality_map, _mbd_charge_sum, Fun4AllReturnCodes::EVENT_OK, i, NDIVS, CentralityInfo::set_centile(), CentralityInfo::set_centrality_bin(), value, and Fun4AllBase::Verbosity().
Referenced by process_event().
int CentralityReco::FillVars ()
Definition at line 124 of file CentralityReco.cc.
View newest version in sPHENIX GitHub at line 124 of file CentralityReco.cc
References _centrality_scale, _mbd_charge_sum, _mbd_charge_sum_n, _mbd_charge_sum_s, _mbd_out, Fun4AllReturnCodes::EVENT_OK, MbdOut::get_q(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int CentralityReco::GetNodes (PHCompositeNode * topNode)
Definition at line 208 of file CentralityReco.cc.
View newest version in sPHENIX GitHub at line 208 of file CentralityReco.cc
References _central, _mbd_out, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
Referenced by process_event().
int CentralityReco::InitRun (PHCompositeNode * topNode) override virtual
full initialization
Reimplemented from SubsysReco.
Definition at line 31 of file CentralityReco.cc.
View newest version in sPHENIX GitHub at line 31 of file CentralityReco.cc
References Fun4AllReturnCodes::ABORTRUN, CreateNodes(), Download_centralityDivisions(), Download_centralityScale(), Fun4AllReturnCodes::EVENT_OK, CDBInterface::getUrl(), and CDBInterface::instance().
int CentralityReco::process_event (PHCompositeNode * topNode) override virtual
event processing method
Reimplemented from SubsysReco.
Definition at line 177 of file CentralityReco.cc.
View newest version in sPHENIX GitHub at line 177 of file CentralityReco.cc
References _central, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, FillCentralityInfo(), FillVars(), GetNodes(), CentralityInfo::identify(), and Fun4AllBase::Verbosity().
int CentralityReco::ResetEvent (PHCompositeNode *) override virtual
Clean up after each event.
Reimplemented from SubsysReco.
Definition at line 111 of file CentralityReco.cc.
View newest version in sPHENIX GitHub at line 111 of file CentralityReco.cc
References _mbd_charge_sum, _mbd_charge_sum_n, _mbd_charge_sum_s, Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
Member Data Documentation
CentralityInfo* CentralityReco::_central {nullptr} private
Definition at line 45 of file CentralityReco.h.
View newest version in sPHENIX GitHub at line 45 of file CentralityReco.h
Referenced by FillCentralityInfo(), GetNodes(), and process_event().
std::array<float, 100> CentralityReco::_centrality_map {} private
Definition at line 54 of file CentralityReco.h.
View newest version in sPHENIX GitHub at line 54 of file CentralityReco.h
Referenced by Download_centralityDivisions(), and FillCentralityInfo().
double CentralityReco::_centrality_scale {std::numeric_limits<double>::quiet_NaN()} private
Definition at line 53 of file CentralityReco.h.
View newest version in sPHENIX GitHub at line 53 of file CentralityReco.h
Referenced by Download_centralityScale(), and FillVars().
std::string CentralityReco::_dbfilename private
Definition at line 39 of file CentralityReco.h.
View newest version in sPHENIX GitHub at line 39 of file CentralityReco.h
unsigned int CentralityReco::_key {std::numeric_limits<unsigned int>::max()} private
Definition at line 47 of file CentralityReco.h.
View newest version in sPHENIX GitHub at line 47 of file CentralityReco.h
float CentralityReco::_mbd_charge_sum {std::numeric_limits<float>::quiet_NaN()} private
Definition at line 49 of file CentralityReco.h.
View newest version in sPHENIX GitHub at line 49 of file CentralityReco.h
Referenced by FillCentralityInfo(), FillVars(), and ResetEvent().
float CentralityReco::_mbd_charge_sum_n {std::numeric_limits<float>::quiet_NaN()} private
Definition at line 50 of file CentralityReco.h.
View newest version in sPHENIX GitHub at line 50 of file CentralityReco.h
Referenced by FillVars(), and ResetEvent().
float CentralityReco::_mbd_charge_sum_s {std::numeric_limits<float>::quiet_NaN()} private
Definition at line 51 of file CentralityReco.h.
View newest version in sPHENIX GitHub at line 51 of file CentralityReco.h
Referenced by FillVars(), and ResetEvent().
MbdOut* CentralityReco::_mbd_out {nullptr} private
Definition at line 43 of file CentralityReco.h.
View newest version in sPHENIX GitHub at line 43 of file CentralityReco.h
Referenced by FillVars(), and GetNodes().
const int CentralityReco::NDIVS {100} private
Definition at line 41 of file CentralityReco.h.
View newest version in sPHENIX GitHub at line 41 of file CentralityReco.h
Referenced by Download_centralityDivisions(), and FillCentralityInfo().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/centrality/CentralityReco.h
coresoftware/blob/master/offline/packages/centrality/CentralityReco.cc