Analysis Software: MicromegasClusterizer Class Reference
MicromegasClusterizer Class Reference
micromegas clusterizer
#include <coresoftware/blob/master/offline/packages/micromegas/MicromegasClusterizer.h>
Public Member Functions
MicromegasClusterizer (const std::string &name="MicromegasClusterizer")
constructor
int Init (PHCompositeNode *) override
global initialization
int InitRun (PHCompositeNode *) override
run initialization
int process_event (PHCompositeNode *) override
event processing
void set_default_pedestal (double value)
set default pedestal
void set_use_default_pedestal (bool value)
set whether default pedestal is used or not
void set_calibration_file (const std::string &value)
calibration file
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
calibration filename
bool m_use_default_pedestal = true
if true, use default pedestal to get hit charge. Relies on calibration data otherwise
double m_default_pedestal = 74.6
default pedestal
std::string m_calibration_filename
calibration filename
MicromegasCalibrationData m_calibration_data
calibration data
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
micromegas clusterizer
Definition at line 18 of file MicromegasClusterizer.h.
View newest version in sPHENIX GitHub at line 18 of file MicromegasClusterizer.h
Constructor & Destructor Documentation
MicromegasClusterizer::MicromegasClusterizer (const std::string & name = "MicromegasClusterizer")
constructor
Definition at line 85 of file MicromegasClusterizer.cc.
View newest version in sPHENIX GitHub at line 85 of file MicromegasClusterizer.cc
Member Function Documentation
int MicromegasClusterizer::Init (PHCompositeNode *) override virtual
global initialization
Reimplemented from SubsysReco.
Definition at line 90 of file MicromegasClusterizer.cc.
View newest version in sPHENIX GitHub at line 90 of file MicromegasClusterizer.cc
References Fun4AllReturnCodes::EVENT_OK, m_calibration_data, m_calibration_filename, m_default_pedestal, m_use_default_pedestal, and MicromegasCalibrationData::read().
int MicromegasClusterizer::InitRun (PHCompositeNode * topNode) override virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 109 of file MicromegasClusterizer.cc.
View newest version in sPHENIX GitHub at line 109 of file MicromegasClusterizer.cc
References assert, Fun4AllReturnCodes::EVENT_OK, and PHNodeIterator::findFirst().
int MicromegasClusterizer::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 154 of file MicromegasClusterizer.cc.
View newest version in sPHENIX GitHub at line 154 of file MicromegasClusterizer.cc
References assert, parse_cmake_options::begin, double(), Fun4AllReturnCodes::EVENT_OK, TrkrDefs::genClusKey(), MicromegasCalibrationData::get_pedestal_mapped(), TrkrHitSet::getHits(), TrkrDefs::getLayer(), PHG4CylinderGeomContainer::GetLayerGeom(), MicromegasDefs::getStrip(), MicromegasDefs::getTileId(), layer, m_calibration_data, m_default_pedestal, m_use_default_pedestal, TrkrDefs::micromegasId, pedestal(), PHG4InttDefs::SEGMENTATION_PHI, PHG4InttDefs::SEGMENTATION_Z, and square().
void MicromegasClusterizer::set_calibration_file (const std::string & value) inline
calibration file
Definition at line 43 of file MicromegasClusterizer.h.
View newest version in sPHENIX GitHub at line 43 of file MicromegasClusterizer.h
References m_calibration_filename, and value.
void MicromegasClusterizer::set_default_pedestal (double value) inline
set default pedestal
Definition at line 35 of file MicromegasClusterizer.h.
View newest version in sPHENIX GitHub at line 35 of file MicromegasClusterizer.h
References m_default_pedestal, and value.
void MicromegasClusterizer::set_use_default_pedestal (bool value) inline
set whether default pedestal is used or not
Definition at line 39 of file MicromegasClusterizer.h.
View newest version in sPHENIX GitHub at line 39 of file MicromegasClusterizer.h
References m_use_default_pedestal, and value.
Member Data Documentation
MicromegasCalibrationData MicromegasClusterizer::m_calibration_data private
calibration data
Definition at line 61 of file MicromegasClusterizer.h.
View newest version in sPHENIX GitHub at line 61 of file MicromegasClusterizer.h
Referenced by Init(), and process_event().
std::string MicromegasClusterizer::m_calibration_filename private
calibration filename
Definition at line 58 of file MicromegasClusterizer.h.
View newest version in sPHENIX GitHub at line 58 of file MicromegasClusterizer.h
Referenced by Init(), and set_calibration_file().
double MicromegasClusterizer::m_default_pedestal = 74.6 private
default pedestal
Definition at line 55 of file MicromegasClusterizer.h.
View newest version in sPHENIX GitHub at line 55 of file MicromegasClusterizer.h
Referenced by Init(), process_event(), and set_default_pedestal().
bool MicromegasClusterizer::m_use_default_pedestal = true private
if true, use default pedestal to get hit charge. Relies on calibration data otherwise
Definition at line 52 of file MicromegasClusterizer.h.
View newest version in sPHENIX GitHub at line 52 of file MicromegasClusterizer.h
Referenced by Init(), process_event(), and set_use_default_pedestal().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/micromegas/MicromegasClusterizer.h
coresoftware/blob/master/offline/packages/micromegas/MicromegasClusterizer.cc