Analysis Software: PHG4ZDCSubsystem Class Reference
PHG4ZDCSubsystem Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ZDCSubsystem.h>
Public Member Functions
PHG4ZDCSubsystem (const std::string &name, const int layer)
~PHG4ZDCSubsystem () override
int InitRunSubsystem (PHCompositeNode *) override
int process_event (PHCompositeNode *) override
PHG4Detector * GetDetector () const override
PHG4SteppingAction * GetSteppingAction () const override
return pointer to this subsystem stepping action
PHG4DisplayAction * GetDisplayAction () const override
return pointer to this subsystem display setting
Public Member Functions inherited from PHG4DetectorSubsystem
~PHG4DetectorSubsystem () override
int Init (PHCompositeNode *) final
int InitRun (PHCompositeNode *) final
virtual int InitSubsystem (PHCompositeNode *)
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
PHParameters * GetParams () const
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UseDB (const int i=1)
int ReadDB () const
void UseCDB (const std::string &domain)
FILE_TYPE get_filetype () const
void UseCalibFiles (const FILE_TYPE ftyp)
int ReadParamsFromCDB (const std::string &domain)
int SaveParamsToDB ()
int ReadParamsFromDB (const std::string &name, const int issuper)
int SaveParamsToFile (const FILE_TYPE ftyp)
int ReadParamsFromFile (const std::string &name, const FILE_TYPE ftyp, const int issuper)
void SetCalibrationFileDir (const std::string &calibdir)
void UpdateParametersWithMacro ()
void SetActive (const int i=1)
void SetAbsorberActive (const int i=1)
void SetAbsorberTruth (const int i=1)
void BlackHole (const int i=1)
void SetSupportActive (const int i=1)
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int GetLayer () const
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
~PHG4Subsystem (void) override
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
virtual PHG4StackingAction * GetStackingAction () const
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
void SetMotherSubsystem (PHG4Subsystem *subsys)
PHG4Subsystem * GetMotherSubsystem () const
void SetLogicalVolume (G4LogicalVolume *vol)
G4LogicalVolume * GetLogicalVolume () const
virtual bool CanBeMotherSubsystem () const
virtual void AddProcesses (G4ParticleDefinition *)
virtual void DefineMaterials ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void SetDefaultParameters () override
Private Attributes
PHG4ZDCDetector * m_Detector = nullptr
PHG4SteppingAction * m_SteppingAction = nullptr
PHG4DisplayAction * m_DisplayAction = nullptr
display attribute setting
std::string m_HitNodeName
std::string m_AbsorberNodeName
std::string m_SupportNodeName
Additional Inherited Members
Public Types inherited from PHG4DetectorSubsystem
enum FILE_TYPE { none = 0, xml = 1, root = 2 }
Protected Member Functions inherited from PHG4DetectorSubsystem
PHG4DetectorSubsystem (const std::string &name="GenericSubsystem", const int lyr=0)
void InitializeParameters ()
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
int BeginRunExecuted () const
Detailed Description
Definition at line 16 of file PHG4ZDCSubsystem.h.
View newest version in sPHENIX GitHub at line 16 of file PHG4ZDCSubsystem.h
Constructor & Destructor Documentation
PHG4ZDCSubsystem::PHG4ZDCSubsystem (const std::string & name, const int layer) explicit
Constructor
Definition at line 27 of file PHG4ZDCSubsystem.cc.
View newest version in sPHENIX GitHub at line 27 of file PHG4ZDCSubsystem.cc
References PHG4DetectorSubsystem::InitializeParameters().
PHG4ZDCSubsystem::~PHG4ZDCSubsystem () override
Destructor
Definition at line 34 of file PHG4ZDCSubsystem.cc.
View newest version in sPHENIX GitHub at line 34 of file PHG4ZDCSubsystem.cc
References m_DisplayAction.
Member Function Documentation
PHG4Detector * PHG4ZDCSubsystem::GetDetector (void) const override virtual
Accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 125 of file PHG4ZDCSubsystem.cc.
View newest version in sPHENIX GitHub at line 125 of file PHG4ZDCSubsystem.cc
References m_Detector.
PHG4DisplayAction* PHG4ZDCSubsystem::GetDisplayAction () const inline override virtual
return pointer to this subsystem display setting
Reimplemented from PHG4Subsystem.
Definition at line 41 of file PHG4ZDCSubsystem.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4ZDCSubsystem.h
References m_DisplayAction.
PHG4SteppingAction* PHG4ZDCSubsystem::GetSteppingAction (void) const inline override virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 39 of file PHG4ZDCSubsystem.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4ZDCSubsystem.h
References m_SteppingAction.
int PHG4ZDCSubsystem::InitRunSubsystem (PHCompositeNode * topNode) override virtual
Creates relevant hit nodes that will be populated by the stepping action and stored in the output DST
Reimplemented from PHG4DetectorSubsystem.
Definition at line 40 of file PHG4ZDCSubsystem.cc.
View newest version in sPHENIX GitHub at line 40 of file PHG4ZDCSubsystem.cc
References PHCompositeNode::addNode(), PHG4DetectorSubsystem::CheckOverlap(), PHNodeIterator::findFirst(), PHG4DetectorSubsystem::get_int_param(), PHG4DetectorSubsystem::GetLayer(), PHG4DetectorSubsystem::GetParams(), m_AbsorberNodeName, m_Detector, m_DisplayAction, m_HitNodeName, m_SteppingAction, m_SupportNodeName, Fun4AllBase::Name(), PHG4Detector::OverlapCheck(), PHG4SteppingAction::SetHitNodeName(), PHG4ZDCDetector::SuperDetector(), PHG4DetectorSubsystem::SuperDetector(), PHG4Detector::topNode(), PHG4Detector::Verbosity(), and Fun4AllBase::Verbosity().
int PHG4ZDCSubsystem::process_event (PHCompositeNode * topNode) override virtual
Event processing
Reimplemented from SubsysReco.
Definition at line 113 of file PHG4ZDCSubsystem.cc.
View newest version in sPHENIX GitHub at line 113 of file PHG4ZDCSubsystem.cc
References m_SteppingAction, and PHG4SteppingAction::SetInterfacePointers().
void PHG4ZDCSubsystem::SetDefaultParameters () override private virtual
Implements PHG4DetectorSubsystem.
Definition at line 130 of file PHG4ZDCSubsystem.cc.
View newest version in sPHENIX GitHub at line 130 of file PHG4ZDCSubsystem.cc
References PHG4DetectorSubsystem::set_default_double_param().
Member Data Documentation
std::string PHG4ZDCSubsystem::m_AbsorberNodeName private
Definition at line 59 of file PHG4ZDCSubsystem.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4ZDCSubsystem.h
Referenced by InitRunSubsystem().
PHG4ZDCDetector* PHG4ZDCSubsystem::m_Detector = nullptr private
Pointer to the Geant4 implementation of the detector
Definition at line 48 of file PHG4ZDCSubsystem.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4ZDCSubsystem.h
Referenced by GetDetector(), and InitRunSubsystem().
PHG4DisplayAction* PHG4ZDCSubsystem::m_DisplayAction = nullptr private
display attribute setting
derives from PHG4DisplayAction
Definition at line 56 of file PHG4ZDCSubsystem.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4ZDCSubsystem.h
Referenced by GetDisplayAction(), InitRunSubsystem(), and ~PHG4ZDCSubsystem().
std::string PHG4ZDCSubsystem::m_HitNodeName private
Definition at line 58 of file PHG4ZDCSubsystem.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4ZDCSubsystem.h
Referenced by InitRunSubsystem().
PHG4SteppingAction* PHG4ZDCSubsystem::m_SteppingAction = nullptr private
Stepping action
Definition at line 52 of file PHG4ZDCSubsystem.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4ZDCSubsystem.h
Referenced by GetSteppingAction(), InitRunSubsystem(), and process_event().
std::string PHG4ZDCSubsystem::m_SupportNodeName private
Definition at line 60 of file PHG4ZDCSubsystem.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4ZDCSubsystem.h
Referenced by InitRunSubsystem().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ZDCSubsystem.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ZDCSubsystem.cc