Analysis Software: ParticleFlowElementv1 Class Reference
ParticleFlowElementv1 Class Reference
#include <coresoftware/blob/master/offline/packages/particleflow/ParticleFlowElementv1.h>
Public Member Functions
ParticleFlowElementv1 ()
~ParticleFlowElementv1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
ParticleFlowElement::PFLOWTYPE get_type () const override
void set_type (ParticleFlowElement::PFLOWTYPE type) override
unsigned int get_id () const override
void set_id (unsigned int id) override
float get_px () const override
void set_px (float px) override
float get_py () const override
void set_py (float py) override
float get_pz () const override
void set_pz (float pz) override
float get_e () const override
void set_e (float e) override
SvtxTrack * get_track () const override
void set_track (SvtxTrack *track) override
std::vector< RawCluster * > get_eclusters () const override
void set_eclusters (const std::vector< RawCluster * > &ecluster) override
RawCluster * get_hcluster () const override
void set_hcluster (RawCluster *hcluster) override
float get_p () const override
float get_pt () const override
float get_et () const override
float get_eta () const override
float get_phi () const override
float get_mass () const override
Public Member Functions inherited from ParticleFlowElement
ParticleFlowElement ()
~ParticleFlowElement () override
ClassDefOverride (ParticleFlowElement, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (ParticleFlowElementv1, 1)
Private Attributes
unsigned int _id
unique identifier within container
ParticleFlowElement::PFLOWTYPE _type
float _mom [3]
pflow momentum vector (px,py,pz)
float _e
pflow energy
SvtxTrack * _track = nullptr
std::vector< RawCluster * > _ecluster
RawCluster * _hcluster = nullptr
Additional Inherited Members
Public Types inherited from ParticleFlowElement
enum PFLOWTYPE {
UNASSIGNED = -1, MATCHED_CHARGED_HADRON = 0, UNMATCHED_CHARGED_HADRON = 1, UNMATCHED_EM_PARTICLE = 2,
UNMATCHED_NEUTRAL_HADRON = 3, LEFTOVER_EM_PARTICLE = 4
}
Detailed Description
Definition at line 18 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 18 of file ParticleFlowElementv1.h
Constructor & Destructor Documentation
ParticleFlowElementv1::ParticleFlowElementv1 ()
Definition at line 6 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 6 of file ParticleFlowElementv1.cc
References _id, _mom, _type, and i.
ParticleFlowElementv1::~ParticleFlowElementv1 () inline override
Definition at line 22 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 22 of file ParticleFlowElementv1.h
Member Function Documentation
ParticleFlowElementv1::ClassDefOverride (ParticleFlowElementv1 , 1) private
float ParticleFlowElementv1::get_e () const inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 47 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 47 of file ParticleFlowElementv1.h
References _e.
Referenced by get_et(), get_mass(), and identify().
std::vector<RawCluster*> ParticleFlowElementv1::get_eclusters () const inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 53 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 53 of file ParticleFlowElementv1.h
References _ecluster.
float ParticleFlowElementv1::get_et () const override virtual
Reimplemented from ParticleFlowElement.
Definition at line 53 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 53 of file ParticleFlowElementv1.cc
References get_e(), get_p(), and get_pt().
float ParticleFlowElementv1::get_eta () const override virtual
Reimplemented from ParticleFlowElement.
Definition at line 58 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 58 of file ParticleFlowElementv1.cc
References get_pt(), and get_pz().
RawCluster* ParticleFlowElementv1::get_hcluster () const inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 56 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 56 of file ParticleFlowElementv1.h
References _hcluster.
unsigned int ParticleFlowElementv1::get_id () const inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 35 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 35 of file ParticleFlowElementv1.h
References _id.
Referenced by identify().
float ParticleFlowElementv1::get_mass () const override virtual
Reimplemented from ParticleFlowElement.
Definition at line 68 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 68 of file ParticleFlowElementv1.cc
References get_e(), get_px(), get_py(), and get_pz().
float ParticleFlowElementv1::get_p () const override virtual
Reimplemented from ParticleFlowElement.
Definition at line 43 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 43 of file ParticleFlowElementv1.cc
References get_px(), get_py(), and get_pz().
Referenced by get_et().
float ParticleFlowElementv1::get_phi () const override virtual
Reimplemented from ParticleFlowElement.
Definition at line 63 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 63 of file ParticleFlowElementv1.cc
References get_px(), and get_py().
float ParticleFlowElementv1::get_pt () const override virtual
Reimplemented from ParticleFlowElement.
Definition at line 48 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 48 of file ParticleFlowElementv1.cc
References get_px(), and get_py().
Referenced by get_et(), and get_eta().
float ParticleFlowElementv1::get_px () const inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 38 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 38 of file ParticleFlowElementv1.h
References _mom.
Referenced by get_mass(), get_p(), get_phi(), get_pt(), and identify().
float ParticleFlowElementv1::get_py () const inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 41 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 41 of file ParticleFlowElementv1.h
References _mom.
Referenced by get_mass(), get_p(), get_phi(), get_pt(), and identify().
float ParticleFlowElementv1::get_pz () const inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 44 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 44 of file ParticleFlowElementv1.h
References _mom.
Referenced by get_eta(), get_mass(), get_p(), and identify().
SvtxTrack* ParticleFlowElementv1::get_track () const inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 50 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 50 of file ParticleFlowElementv1.h
References _track.
ParticleFlowElement::PFLOWTYPE ParticleFlowElementv1::get_type () const inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 32 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 32 of file ParticleFlowElementv1.h
References _type.
Referenced by identify().
void ParticleFlowElementv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from ParticleFlowElement.
Definition at line 16 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 16 of file ParticleFlowElementv1.cc
References get_e(), get_id(), get_px(), get_py(), get_pz(), and get_type().
int ParticleFlowElementv1::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from ParticleFlowElement.
Definition at line 32 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 32 of file ParticleFlowElementv1.cc
References _e, _mom, and i.
void ParticleFlowElementv1::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 26 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 26 of file ParticleFlowElementv1.cc
References _e, _mom, and i.
void ParticleFlowElementv1::set_e (float e) inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 48 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 48 of file ParticleFlowElementv1.h
References _e, and Acts::UnitConstants::e.
void ParticleFlowElementv1::set_eclusters (const std::vector< RawCluster * > & ecluster) inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 54 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 54 of file ParticleFlowElementv1.h
References _ecluster.
void ParticleFlowElementv1::set_hcluster (RawCluster * hcluster) inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 57 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 57 of file ParticleFlowElementv1.h
References _hcluster.
void ParticleFlowElementv1::set_id (unsigned int id) inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 36 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 36 of file ParticleFlowElementv1.h
References _id, and train_ambiguity_solver::id.
void ParticleFlowElementv1::set_px (float px) inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 39 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 39 of file ParticleFlowElementv1.h
References _mom.
void ParticleFlowElementv1::set_py (float py) inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 42 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 42 of file ParticleFlowElementv1.h
References _mom.
void ParticleFlowElementv1::set_pz (float pz) inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 45 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 45 of file ParticleFlowElementv1.h
References _mom.
void ParticleFlowElementv1::set_track (SvtxTrack * track) inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 51 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 51 of file ParticleFlowElementv1.h
References _track.
void ParticleFlowElementv1::set_type (ParticleFlowElement::PFLOWTYPE type) inline override virtual
Reimplemented from ParticleFlowElement.
Definition at line 33 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 33 of file ParticleFlowElementv1.h
References _type, and parse_cmake_options::type.
Member Data Documentation
float ParticleFlowElementv1::_e private
pflow energy
Definition at line 77 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 77 of file ParticleFlowElementv1.h
Referenced by get_e(), isValid(), Reset(), and set_e().
std::vector<RawCluster*> ParticleFlowElementv1::_ecluster private
Definition at line 80 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 80 of file ParticleFlowElementv1.h
Referenced by get_eclusters(), and set_eclusters().
RawCluster* ParticleFlowElementv1::_hcluster = nullptr private
Definition at line 81 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 81 of file ParticleFlowElementv1.h
Referenced by get_hcluster(), and set_hcluster().
unsigned int ParticleFlowElementv1::_id private
unique identifier within container
Definition at line 68 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 68 of file ParticleFlowElementv1.h
Referenced by get_id(), ParticleFlowElementv1(), and set_id().
float ParticleFlowElementv1::_mom[3] private
pflow momentum vector (px,py,pz)
Definition at line 74 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 74 of file ParticleFlowElementv1.h
Referenced by get_px(), get_py(), get_pz(), isValid(), ParticleFlowElementv1(), Reset(), set_px(), set_py(), and set_pz().
SvtxTrack* ParticleFlowElementv1::_track = nullptr private
Definition at line 79 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 79 of file ParticleFlowElementv1.h
Referenced by get_track(), and set_track().
ParticleFlowElement::PFLOWTYPE ParticleFlowElementv1::_type private
Definition at line 71 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 71 of file ParticleFlowElementv1.h
Referenced by get_type(), ParticleFlowElementv1(), and set_type().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/particleflow/ParticleFlowElementv1.h
coresoftware/blob/master/offline/packages/particleflow/ParticleFlowElementv1.cc