Analysis Software: ODBCConnection Class Reference
ODBCConnection Class Reference
#include <RDBC/blob/master/odbc/ODBCConnection.h>
Public Member Functions
Bool_t GetAutoCommit ()
void SetAutoCommit (Bool_t autoCommit=kTRUE)
TString GetCatalog ()
void SetCatalog (const TString &catalog)
Bool_t IsReadOnly ()
void SetReadOnly (Bool_t readOnly=kTRUE)
Bool_t GetTrace ()
void SetTrace (Bool_t trace=kTRUE)
void SetTraceFile (const TString &filename)
TString GetTraceFile ()
Int_t GetTransactionIsolation ()
void SetTransactionIsolation (Int_t level)
TString NativeSQL (const TString &sql)
void Close ()
void Commit ()
void Rollback ()
TSQLStatement * CreateStatement ()
TSQLStatement * CreateStatement (Int_t resultSetType, Int_t resultSetConcurrency)
TSQLPreparedStatement * PrepareStatement (const TString &sql)
TSQLPreparedStatement * PrepareStatement (const TString &sql, Int_t resultSetType, Int_t resultSetConcurrency)
TSQLCallableStatement * PrepareCall (const TString &sql)
TSQLCallableStatement * PrepareCall (const TString &sql, Int_t resultSetType, Int_t resultSetConcurrency)
TSQLDatabaseMetaData * GetMetaData ()
Bool_t HasBatchSupport ()
ODBCConnection (const TString &url, const TString &username, const TString &password)
methods below are private ...
ODBCConnection (const TString &connectString)
Public Member Functions inherited from TSQLConnection
virtual Bool_t IsClosed ()
TList * GetListOfStatements () const
virtual const char * GetName () const
virtual const char * GetTitle () const
virtual void Print (Option_t *option="") const
virtual void ls (Option_t *option="") const
Public Member Functions inherited from TSQL
TSQL (void *imp=0)
virtual ~TSQL ()
virtual void Throw (TSQLException *e)
TList * GetWarnings () const
void ClearWarnings ()
virtual Bool_t IsValid () const
Static Public Member Functions
static Int_t GetLoginTimeout ()
static void SetLoginTimeout (Int_t seconds)
static void Shutdown ()
static TList * RefreshDataSources (TList *datasoures)
static TList * RefreshDrivers (TList *drivers)
Private Member Functions
virtual ~ODBCConnection ()
Additional Inherited Members
Protected Member Functions inherited from TSQLConnection
TSQLConnection (const TString &url, const TString &username, const TString &password)
TSQLConnection (const TString &connectString)
void SetURL (const TString &url)
virtual ~TSQLConnection ()
Protected Attributes inherited from TSQLConnection
TSQLDatabaseMetaData * fMetaData
TList * fListOfStatements
Detailed Description
Definition at line 15 of file ODBCConnection.h.
View newest version in sPHENIX GitHub at line 15 of file ODBCConnection.h
Constructor & Destructor Documentation
ODBCConnection::~ODBCConnection () private virtual
Definition at line 260 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 260 of file ODBCConnection.cxx
References con, Acts::UnitConstants::e, TSQL::fImp, TSQLConnection::fListOfStatements, TSQLConnection::fMetaData, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_CSTR, and TSQL::Throw().
ODBCConnection::ODBCConnection (const TString & url, const TString & username, const TString & password)
methods below are private ...
Definition at line 217 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 217 of file ODBCConnection.cxx
References Acts::UnitConstants::e, TSQL::fImp, TSQLConnection::fMetaData, odbc::DriverManager::getConnection(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Connection::getMetaData(), odbc::SQLException::getSQLState(), gSQLDriverManager, ODBCXX_STRING_C, ODBCXX_STRING_CSTR, and TSQL::Throw().
ODBCConnection::ODBCConnection (const TString & connectString)
Member Function Documentation
void ODBCConnection::Close () virtual
Reimplemented from TSQLConnection.
Definition at line 751 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 751 of file ODBCConnection.cxx
References TSQLConnection::Close(), con, Acts::UnitConstants::e, TSQL::fImp, TSQLConnection::fMetaData, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCConnection::Commit () virtual
Implements TSQLConnection.
Definition at line 694 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 694 of file ODBCConnection.cxx
References odbc::Connection::commit(), con, Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TSQLStatement * ODBCConnection::CreateStatement () virtual
Implements TSQLConnection.
Definition at line 293 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 293 of file ODBCConnection.cxx
References TSQL::ClearWarnings(), con, odbc::Connection::createStatement(), Acts::UnitConstants::e, TSQL::fImp, TSQLConnection::fListOfStatements, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TSQLStatement * ODBCConnection::CreateStatement (Int_t resultSetType, Int_t resultSetConcurrency) virtual
Implements TSQLConnection.
Definition at line 335 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 335 of file ODBCConnection.cxx
References TSQL::ClearWarnings(), con, odbc::Connection::createStatement(), Acts::UnitConstants::e, TSQL::fImp, TSQLConnection::fListOfStatements, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCConnection::GetAutoCommit () virtual
Implements TSQLConnection.
Definition at line 663 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 663 of file ODBCConnection.cxx
References con, Acts::UnitConstants::e, TSQL::fImp, odbc::Connection::getAutoCommit(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TString ODBCConnection::GetCatalog () virtual
Implements TSQLConnection.
Definition at line 899 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 899 of file ODBCConnection.cxx
References con, Acts::UnitConstants::e, TSQL::fImp, odbc::Connection::getCatalog(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_CSTR, str, and TSQL::Throw().
Int_t ODBCConnection::GetLoginTimeout () static
Definition at line 1109 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 1109 of file ODBCConnection.cxx
References odbc::DriverManager::getLoginTimeout().
TSQLDatabaseMetaData * ODBCConnection::GetMetaData () virtual
Implements TSQLConnection.
Definition at line 778 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 778 of file ODBCConnection.cxx
References con, Acts::UnitConstants::e, TSQL::fImp, TSQLConnection::fMetaData, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Connection::getMetaData(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCConnection::GetTrace () virtual
Implements TSQLConnection.
Definition at line 992 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 992 of file ODBCConnection.cxx
References con, Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::Connection::getTrace(), TSQLConnection::IsClosed(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TString ODBCConnection::GetTraceFile () virtual
Implements TSQLConnection.
Definition at line 1037 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 1037 of file ODBCConnection.cxx
References con, Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::Connection::getTraceFile(), TSQLConnection::IsClosed(), ODBCXX_STRING_CSTR, str, and TSQL::Throw().
Int_t ODBCConnection::GetTransactionIsolation () virtual
Implements TSQLConnection.
Definition at line 962 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 962 of file ODBCConnection.cxx
References con, Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::Connection::getTransactionIsolation(), TSQLConnection::IsClosed(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCConnection::HasBatchSupport () virtual
Implements TSQLConnection.
Definition at line 1084 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 1084 of file ODBCConnection.cxx
Bool_t ODBCConnection::IsReadOnly () virtual
Implements TSQLConnection.
Definition at line 843 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 843 of file ODBCConnection.cxx
References con, Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), odbc::Connection::isReadOnly(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TString ODBCConnection::NativeSQL (const TString & sql) virtual
Implements TSQLConnection.
Definition at line 585 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 585 of file ODBCConnection.cxx
References TSQL::ClearWarnings(), con, Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), odbc::Connection::nativeSQL(), ODBCXX_STRING, ODBCXX_STRING_C, ODBCXX_STRING_CSTR, physmon_simulation::s, str, and TSQL::Throw().
TSQLCallableStatement * ODBCConnection::PrepareCall (const TString & sql) virtual
Implements TSQLConnection.
Definition at line 434 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 434 of file ODBCConnection.cxx
References TSQL::ClearWarnings(), con, Acts::UnitConstants::e, TSQL::fImp, TSQLConnection::fListOfStatements, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, odbc::Connection::prepareCall(), and TSQL::Throw().
TSQLCallableStatement * ODBCConnection::PrepareCall (const TString & sql, Int_t resultSetType, Int_t resultSetConcurrency) virtual
Implements TSQLConnection.
Definition at line 535 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 535 of file ODBCConnection.cxx
References TSQL::ClearWarnings(), con, Acts::UnitConstants::e, TSQL::fImp, TSQLConnection::fListOfStatements, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, odbc::Connection::prepareCall(), and TSQL::Throw().
TSQLPreparedStatement * ODBCConnection::PrepareStatement (const TString & sql) virtual
Implements TSQLConnection.
Definition at line 379 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 379 of file ODBCConnection.cxx
References TSQL::ClearWarnings(), con, Acts::UnitConstants::e, TSQL::fImp, TSQLConnection::fListOfStatements, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, odbc::Connection::prepareStatement(), and TSQL::Throw().
TSQLPreparedStatement * ODBCConnection::PrepareStatement (const TString & sql, Int_t resultSetType, Int_t resultSetConcurrency) virtual
Implements TSQLConnection.
Definition at line 486 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 486 of file ODBCConnection.cxx
References TSQL::ClearWarnings(), con, Acts::UnitConstants::e, TSQL::fImp, TSQLConnection::fListOfStatements, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, odbc::Connection::prepareStatement(), and TSQL::Throw().
TList * ODBCConnection::RefreshDataSources (TList * datasoures) static
Definition at line 1179 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 1179 of file ODBCConnection.cxx
References Acts::UnitConstants::e, odbc::DriverManager::getDataSources(), odbc::DataSource::getDescription(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::DataSource::getName(), odbc::SQLException::getSQLState(), gSQLDriverManager, i, ODBCXX_STRING_CSTR, TSQL::Throw(), and summary::url.
TList * ODBCConnection::RefreshDrivers (TList * drivers) static
Definition at line 1136 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 1136 of file ODBCConnection.cxx
References description, Acts::UnitConstants::e, gDrivers, odbc::DriverManager::getDrivers(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), gSQLDriverManager, i, ODBCXX_STRING_CSTR, TSQL::Throw(), and ambiguity_solver_full_chain::x.
void ODBCConnection::Rollback () virtual
Implements TSQLConnection.
Definition at line 723 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 723 of file ODBCConnection.cxx
References con, Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_CSTR, odbc::Connection::rollback(), and TSQL::Throw().
void ODBCConnection::SetAutoCommit (Bool_t autoCommit = kTRUE) virtual
Implements TSQLConnection.
Definition at line 624 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 624 of file ODBCConnection.cxx
References con, Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_CSTR, odbc::Connection::setAutoCommit(), and TSQL::Throw().
void ODBCConnection::SetCatalog (const TString & catalog) virtual
Implements TSQLConnection.
Definition at line 872 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 872 of file ODBCConnection.cxx
References con, Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, odbc::Connection::setCatalog(), and TSQL::Throw().
void ODBCConnection::SetLoginTimeout (Int_t seconds) static
Definition at line 1097 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 1097 of file ODBCConnection.cxx
References odbc::DriverManager::setLoginTimeout().
void ODBCConnection::SetReadOnly (Bool_t readOnly = kTRUE) virtual
Implements TSQLConnection.
Definition at line 813 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 813 of file ODBCConnection.cxx
References con, Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_CSTR, odbc::Connection::setReadOnly(), and TSQL::Throw().
void ODBCConnection::SetTrace (Bool_t trace = kTRUE) virtual
Implements TSQLConnection.
Definition at line 1016 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 1016 of file ODBCConnection.cxx
References con, Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_CSTR, odbc::Connection::setTrace(), and TSQL::Throw().
void ODBCConnection::SetTraceFile (const TString & filename) virtual
Implements TSQLConnection.
Definition at line 1063 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 1063 of file ODBCConnection.cxx
References con, Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, odbc::Connection::setTraceFile(), and TSQL::Throw().
void ODBCConnection::SetTransactionIsolation (Int_t level) virtual
Implements TSQLConnection.
Definition at line 928 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 928 of file ODBCConnection.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), TSQLConnection::IsClosed(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCConnection::Shutdown () static
Definition at line 1121 of file ODBCConnection.cxx.
View newest version in sPHENIX GitHub at line 1121 of file ODBCConnection.cxx
References Acts::UnitConstants::e, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), gSQLDriverManager, ODBCXX_STRING_CSTR, odbc::DriverManager::shutdown(), and TSQL::Throw().
The documentation for this class was generated from the following files:
RDBC/blob/master/odbc/ODBCConnection.h
RDBC/blob/master/odbc/ODBCConnection.cxx