Analysis Software: Jetscape::CausalLiquefier Class Reference
Jetscape::CausalLiquefier Class Reference
#include <JETSCAPE/blob/main/src/liquefier/CausalLiquefier.h>
Public Member Functions
CausalLiquefier ()
CausalLiquefier (double dtau, double dx, double dy, double deta)
~CausalLiquefier ()
void Init ()
void smearing_kernel (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real eta, const Droplet drop_i, std::array< Jetscape::real, 4 > &jmu) const
double dumping (double t) const
double kernel_rho (double t, double r) const
double rho_smooth (double t, double r) const
double rho_delta (double t, double r) const
double kernel_j (double t, double r) const
double j_smooth (double t, double r) const
double j_delta (double t, double r) const
double get_t (double tau, double eta) const
double get_z (double tau, double eta) const
double get_ptau (double px, double pz, double eta) const
double get_peta (double px, double pz, double eta) const
void set_t_delay (double new_tau_delay)
Public Member Functions inherited from Jetscape::LiquefierBase
LiquefierBase ()
~LiquefierBase ()
void add_a_droplet (Droplet droplet_in)
int get_drop_stat () const
int get_miss_stat () const
int get_neg_stat () const
Droplet get_a_droplet (const int idx) const
void check_energy_momentum_conservation (const std::vector< Parton > &pIn, std::vector< Parton > &pOut)
void filter_partons (std::vector< Parton > &pOut)
void add_hydro_sources (std::vector< Parton > &pIn, std::vector< Parton > &pOut)
const bool get_GetHydroCellSignalConnected ()
void set_GetHydroCellSignalConnected (bool m_GetHydroCellSignalConnected)
int get_dropletlist_size () const
Jetscape::real get_dropletlist_total_energy () const
void get_source (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real eta, std::array< Jetscape::real, 4 > &jmu) const
virtual void Clear ()
Public Attributes
double dtau
double dx
double dy
double deta
double tau_delay
double time_relax
double d_diff
double width_delta
double c_diff
double gamma_relax
Public Attributes inherited from Jetscape::LiquefierBase
sigslot::signal5< double,
double, double, double,
std::unique_ptr< FluidCellInfo >
&, sigslot::multi_threaded_local > GetHydroCellSignal
Core signal to receive information from the medium.
Detailed Description
Definition at line 31 of file CausalLiquefier.h.
View newest version in sPHENIX GitHub at line 31 of file CausalLiquefier.h
Constructor & Destructor Documentation
Jetscape::CausalLiquefier::CausalLiquefier ()
Definition at line 27 of file CausalLiquefier.cc.
View newest version in sPHENIX GitHub at line 27 of file CausalLiquefier.cc
References c_diff, d_diff, deta, dtau, dx, dy, gamma_relax, Init(), JSWARN, tau_delay, time_relax, VERBOSE, and width_delta.
Jetscape::CausalLiquefier::CausalLiquefier (double dtau, double dx, double dy, double deta)
Definition at line 50 of file CausalLiquefier.cc.
View newest version in sPHENIX GitHub at line 50 of file CausalLiquefier.cc
References c_diff, d_diff, deta, dtau, dx, dy, gamma_relax, JSINFO, tau_delay, time_relax, VERBOSE, and width_delta.
Jetscape::CausalLiquefier::~CausalLiquefier () inline
Definition at line 52 of file CausalLiquefier.h.
View newest version in sPHENIX GitHub at line 52 of file CausalLiquefier.h
Member Function Documentation
double Jetscape::CausalLiquefier::dumping (double t) const
Definition at line 168 of file CausalLiquefier.cc.
View newest version in sPHENIX GitHub at line 168 of file CausalLiquefier.cc
References gamma_relax.
Referenced by kernel_j(), and kernel_rho().
double Jetscape::CausalLiquefier::get_peta (double px, double pz, double eta) const
Definition at line 242 of file CausalLiquefier.cc.
View newest version in sPHENIX GitHub at line 242 of file CausalLiquefier.cc
Referenced by smearing_kernel(), and TEST().
double Jetscape::CausalLiquefier::get_ptau (double px, double pz, double eta) const
Definition at line 237 of file CausalLiquefier.cc.
View newest version in sPHENIX GitHub at line 237 of file CausalLiquefier.cc
Referenced by smearing_kernel(), and TEST().
double Jetscape::CausalLiquefier::get_t (double tau, double eta) const
Definition at line 227 of file CausalLiquefier.cc.
View newest version in sPHENIX GitHub at line 227 of file CausalLiquefier.cc
Referenced by smearing_kernel(), and TEST().
double Jetscape::CausalLiquefier::get_z (double tau, double eta) const
Definition at line 232 of file CausalLiquefier.cc.
View newest version in sPHENIX GitHub at line 232 of file CausalLiquefier.cc
Referenced by smearing_kernel(), and TEST().
void Jetscape::CausalLiquefier::Init ()
Definition at line 79 of file CausalLiquefier.cc.
View newest version in sPHENIX GitHub at line 79 of file CausalLiquefier.cc
References d_diff, deta, dtau, dx, dy, Jetscape::JetScapeXML::GetElementDouble(), Jetscape::JetScapeXML::Instance(), JSINFO, tau_delay, time_relax, and width_delta.
Referenced by CausalLiquefier().
double Jetscape::CausalLiquefier::j_delta (double t, double r) const
Definition at line 222 of file CausalLiquefier.cc.
View newest version in sPHENIX GitHub at line 222 of file CausalLiquefier.cc
References c_diff, and rho_delta().
Referenced by kernel_j().
double Jetscape::CausalLiquefier::j_smooth (double t, double r) const
Definition at line 189 of file CausalLiquefier.cc.
View newest version in sPHENIX GitHub at line 189 of file CausalLiquefier.cc
References c_diff, f, gamma_relax, physmon_ckf_tracking::u, and ambiguity_solver_full_chain::x.
Referenced by kernel_j().
double Jetscape::CausalLiquefier::kernel_j (double t, double r) const
Definition at line 163 of file CausalLiquefier.cc.
View newest version in sPHENIX GitHub at line 163 of file CausalLiquefier.cc
References dumping(), j_delta(), and j_smooth().
Referenced by smearing_kernel().
double Jetscape::CausalLiquefier::kernel_rho (double t, double r) const
Definition at line 158 of file CausalLiquefier.cc.
View newest version in sPHENIX GitHub at line 158 of file CausalLiquefier.cc
References dumping(), rho_delta(), and rho_smooth().
Referenced by smearing_kernel(), and TEST().
double Jetscape::CausalLiquefier::rho_delta (double t, double r) const
Definition at line 205 of file CausalLiquefier.cc.
View newest version in sPHENIX GitHub at line 205 of file CausalLiquefier.cc
References c_diff, gamma_relax, physmon_track_finding_ttbar::r, t, width_delta, and ambiguity_solver_full_chain::x.
Referenced by j_delta(), kernel_rho(), and TEST().
double Jetscape::CausalLiquefier::rho_smooth (double t, double r) const
Definition at line 173 of file CausalLiquefier.cc.
View newest version in sPHENIX GitHub at line 173 of file CausalLiquefier.cc
References c_diff, f, gamma_relax, physmon_ckf_tracking::u, and ambiguity_solver_full_chain::x.
Referenced by kernel_rho(), and TEST().
void Jetscape::CausalLiquefier::set_t_delay (double new_tau_delay)
Definition at line 247 of file CausalLiquefier.cc.
View newest version in sPHENIX GitHub at line 247 of file CausalLiquefier.cc
References tau_delay.
Referenced by TEST().
void Jetscape::CausalLiquefier::smearing_kernel (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real eta, const Droplet drop_i, std::array< Jetscape::real, 4 > & jmu) const virtual
Reimplemented from Jetscape::LiquefierBase.
Definition at line 112 of file CausalLiquefier.cc.
View newest version in sPHENIX GitHub at line 112 of file CausalLiquefier.cc
References dtau, get_peta(), Jetscape::Droplet::get_pmu(), get_ptau(), get_t(), Jetscape::Droplet::get_xmu(), get_z(), kernel_j(), kernel_rho(), t, tau_delay, and physmon_track_finding_ttbar::z.
Referenced by TEST().
Member Data Documentation
double Jetscape::CausalLiquefier::c_diff
Definition at line 44 of file CausalLiquefier.h.
View newest version in sPHENIX GitHub at line 44 of file CausalLiquefier.h
Referenced by CausalLiquefier(), j_delta(), j_smooth(), rho_delta(), rho_smooth(), and TEST().
double Jetscape::CausalLiquefier::d_diff
Definition at line 41 of file CausalLiquefier.h.
View newest version in sPHENIX GitHub at line 41 of file CausalLiquefier.h
Referenced by CausalLiquefier(), and Init().
double Jetscape::CausalLiquefier::deta
Definition at line 38 of file CausalLiquefier.h.
View newest version in sPHENIX GitHub at line 38 of file CausalLiquefier.h
Referenced by CausalLiquefier(), and Init().
double Jetscape::CausalLiquefier::dtau
Definition at line 38 of file CausalLiquefier.h.
View newest version in sPHENIX GitHub at line 38 of file CausalLiquefier.h
Referenced by CausalLiquefier(), Init(), smearing_kernel(), and TEST().
double Jetscape::CausalLiquefier::dx
Definition at line 38 of file CausalLiquefier.h.
View newest version in sPHENIX GitHub at line 38 of file CausalLiquefier.h
Referenced by CausalLiquefier(), and Init().
double Jetscape::CausalLiquefier::dy
Definition at line 38 of file CausalLiquefier.h.
View newest version in sPHENIX GitHub at line 38 of file CausalLiquefier.h
Referenced by CausalLiquefier(), and Init().
double Jetscape::CausalLiquefier::gamma_relax
Definition at line 45 of file CausalLiquefier.h.
View newest version in sPHENIX GitHub at line 45 of file CausalLiquefier.h
Referenced by CausalLiquefier(), dumping(), j_smooth(), rho_delta(), and rho_smooth().
double Jetscape::CausalLiquefier::tau_delay
Definition at line 39 of file CausalLiquefier.h.
View newest version in sPHENIX GitHub at line 39 of file CausalLiquefier.h
Referenced by CausalLiquefier(), Init(), set_t_delay(), smearing_kernel(), and TEST().
double Jetscape::CausalLiquefier::time_relax
Definition at line 40 of file CausalLiquefier.h.
View newest version in sPHENIX GitHub at line 40 of file CausalLiquefier.h
Referenced by CausalLiquefier(), and Init().
double Jetscape::CausalLiquefier::width_delta
Definition at line 42 of file CausalLiquefier.h.
View newest version in sPHENIX GitHub at line 42 of file CausalLiquefier.h
Referenced by CausalLiquefier(), Init(), and rho_delta().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/liquefier/CausalLiquefier.h
JETSCAPE/blob/main/src/liquefier/CausalLiquefier.cc