Analysis Software: FitterTester Struct Reference
FitterTester Struct Reference
#include <acts/blob/sPHENIX/Tests/UnitTests/Core/TrackFitting/FitterTestsCommon.hpp>
Public Types
using Rng = std::default_random_engine
Public Member Functions
template<typename fitter_t , typename fitter_options_t , typename parameters_t >
void test_ZeroFieldNoSurfaceForward (const fitter_t &fitter, fitter_options_t options, const parameters_t &start, Rng &rng, const bool expected_reversed, const bool expected_smoothed, const bool doDiag) const
template<typename fitter_t , typename fitter_options_t , typename parameters_t >
void test_ZeroFieldWithSurfaceForward (const fitter_t &fitter, fitter_options_t options, const parameters_t &start, Rng &rng, const bool expected_reversed, const bool expected_smoothed, const bool doDiag) const
template<typename fitter_t , typename fitter_options_t , typename parameters_t >
void test_ZeroFieldWithSurfaceBackward (const fitter_t &fitter, fitter_options_t options, const parameters_t &start, Rng &rng, const bool expected_reversed, const bool expected_smoothed, const bool doDiag) const
template<typename fitter_t , typename fitter_options_t , typename parameters_t >
void test_ZeroFieldWithSurfaceAtExit (const fitter_t &fitter, fitter_options_t options, const parameters_t &start, Rng &rng, const bool expected_reversed, const bool expected_smoothed, const bool doDiag) const
template<typename fitter_t , typename fitter_options_t , typename parameters_t >
void test_ZeroFieldShuffled (const fitter_t &fitter, fitter_options_t options, const parameters_t &start, Rng &rng, const bool expected_reversed, const bool expected_smoothed, const bool doDiag) const
template<typename fitter_t , typename fitter_options_t , typename parameters_t >
void test_ZeroFieldWithHole (const fitter_t &fitter, fitter_options_t options, const parameters_t &start, Rng &rng, const bool expected_reversed, const bool expected_smoothed, const bool doDiag) const
template<typename fitter_t , typename fitter_options_t , typename parameters_t >
void test_ZeroFieldWithOutliers (const fitter_t &fitter, fitter_options_t options, const parameters_t &start, Rng &rng, const bool expected_reversed, const bool expected_smoothed, const bool doDiag) const
template<typename fitter_t , typename fitter_options_t , typename parameters_t >
void test_ZeroFieldWithReverseFiltering (const fitter_t &fitter, fitter_options_t options, const parameters_t &start, Rng &rng, const bool expected_reversed, const bool expected_smoothed, const bool doDiag) const
template<typename fitter_t , typename fitter_options_t , typename parameters_t >
void test_GlobalCovariance (const fitter_t &fitter, fitter_options_t options, const parameters_t &start, Rng &rng) const
Static Public Member Functions
static std::vector
< Acts::SourceLink > prepareSourceLinks (const std::vector< TestSourceLink > &sourceLinks)
Public Attributes
Acts::GeometryContext geoCtx
Acts::MagneticFieldContext magCtx
Acts::CalibrationContext calCtx
CubicTrackingGeometry geometryStore {geoCtx}
std::shared_ptr< const
Acts::TrackingGeometry > geometry = geometryStore()
TestSourceLink::SurfaceAccessor surfaceAccessor {*geometry}
MeasurementResolution resPixel = {MeasurementType::eLoc01, {25_um, 50_um}}
MeasurementResolution resStrip0 = {MeasurementType::eLoc0, {100_um}}
MeasurementResolution resStrip1 = {MeasurementType::eLoc1, {150_um}}
MeasurementResolutionMap resolutions
Acts::Propagator
< Acts::StraightLineStepper,
Acts::Navigator > simPropagator
Static Public Attributes
static constexpr size_t nMeasurements = 6u
Detailed Description
Definition at line 113 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 113 of file FitterTestsCommon.hpp
Member Typedef Documentation
using FitterTester::Rng = std::default_random_engine
Definition at line 114 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 114 of file FitterTestsCommon.hpp
Member Function Documentation
static std::vector<Acts::SourceLink> FitterTester::prepareSourceLinks (const std::vector< TestSourceLink > & sourceLinks) inline static
Definition at line 146 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 146 of file FitterTestsCommon.hpp
References Acts::Test::transform.
template<typename fitter_t , typename fitter_options_t , typename parameters_t > void FitterTester::test_GlobalCovariance (const fitter_t & fitter, fitter_options_t options, const parameters_t & start, Rng & rng) const inline
Definition at line 579 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 579 of file FitterTestsCommon.hpp
References Acts::Test::createMeasurements(), Acts::eBoundSize, geoCtx, Acts::detail::globalTrackParametersCovariance(), magCtx, ckf::options, Acts::Test::prepareSourceLinks(), Acts::Test::resolutions, start, and tracks().
template<typename fitter_t , typename fitter_options_t , typename parameters_t > void FitterTester::test_ZeroFieldNoSurfaceForward (const fitter_t & fitter, fitter_options_t options, const parameters_t & start, Rng & rng, const bool expected_reversed, const bool expected_smoothed, const bool doDiag) const inline
Definition at line 160 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 160 of file FitterTestsCommon.hpp
References Acts::Test::createMeasurements(), geoCtx, Acts::MultiTrajectoryTraits::kInvalid, magCtx, ckf::options, Acts::Test::prepareSourceLinks(), Acts::Test::resolutions, cpp.ast::reversed(), start, tracks(), and physmon_ckf_tracking::u.
template<typename fitter_t , typename fitter_options_t , typename parameters_t > void FitterTester::test_ZeroFieldShuffled (const fitter_t & fitter, fitter_options_t options, const parameters_t & start, Rng & rng, const bool expected_reversed, const bool expected_smoothed, const bool doDiag) const inline
Definition at line 368 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 368 of file FitterTestsCommon.hpp
References CHECK_CLOSE_ABS, Acts::Test::createMeasurements(), Acts::UnitConstants::e, geoCtx, Acts::MultiTrajectoryTraits::kInvalid, magCtx, ckf::options, Dataset::parameters, Acts::Test::prepareSourceLinks(), Acts::Test::resolutions, cpp.ast::reversed(), conftest::rng(), start, tracks(), and physmon_ckf_tracking::u.
template<typename fitter_t , typename fitter_options_t , typename parameters_t > void FitterTester::test_ZeroFieldWithHole (const fitter_t & fitter, fitter_options_t options, const parameters_t & start, Rng & rng, const bool expected_reversed, const bool expected_smoothed, const bool doDiag) const inline
Definition at line 432 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 432 of file FitterTestsCommon.hpp
References Acts::Test::createMeasurements(), geoCtx, i, Acts::MultiTrajectoryTraits::kInvalid, magCtx, next, ckf::options, Acts::Test::prepareSourceLinks(), Acts::Test::resolutions, cpp.ast::reversed(), start, tracks(), and physmon_ckf_tracking::u.
template<typename fitter_t , typename fitter_options_t , typename parameters_t > void FitterTester::test_ZeroFieldWithOutliers (const fitter_t & fitter, fitter_options_t options, const parameters_t & start, Rng & rng, const bool expected_reversed, const bool expected_smoothed, const bool doDiag) const inline
Definition at line 478 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 478 of file FitterTestsCommon.hpp
References Acts::Test::createMeasurements(), geoCtx, i, Acts::MultiTrajectoryTraits::kInvalid, magCtx, ckf::options, Acts::OutlierFlag, Acts::Test::prepareSourceLinks(), Acts::Test::resolutions, cpp.ast::reversed(), start, filter::state, tracks(), and physmon_ckf_tracking::u.
template<typename fitter_t , typename fitter_options_t , typename parameters_t > void FitterTester::test_ZeroFieldWithReverseFiltering (const fitter_t & fitter, fitter_options_t options, const parameters_t & start, Rng & rng, const bool expected_reversed, const bool expected_smoothed, const bool doDiag) const inline
Definition at line 532 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 532 of file FitterTestsCommon.hpp
References Acts::Test::createMeasurements(), geoCtx, magCtx, ckf::options, Acts::Test::prepareSourceLinks(), Acts::Test::resolutions, cpp.ast::reversed(), start, and tracks().
template<typename fitter_t , typename fitter_options_t , typename parameters_t > void FitterTester::test_ZeroFieldWithSurfaceAtExit (const fitter_t & fitter, fitter_options_t options, const parameters_t & start, Rng & rng, const bool expected_reversed, const bool expected_smoothed, const bool doDiag) const inline
Definition at line 323 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 323 of file FitterTestsCommon.hpp
References Acts::Test::createMeasurements(), geoCtx, Acts::MultiTrajectoryTraits::kInvalid, magCtx, ckf::options, Acts::Test::prepareSourceLinks(), Acts::Test::resolutions, cpp.ast::reversed(), start, tracks(), and physmon_ckf_tracking::u.
template<typename fitter_t , typename fitter_options_t , typename parameters_t > void FitterTester::test_ZeroFieldWithSurfaceBackward (const fitter_t & fitter, fitter_options_t options, const parameters_t & start, Rng & rng, const bool expected_reversed, const bool expected_smoothed, const bool doDiag) const inline
Definition at line 268 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 268 of file FitterTestsCommon.hpp
References Acts::Direction::Backward, Acts::Test::createMeasurements(), Acts::ePos0, geoCtx, Acts::MultiTrajectoryTraits::kInvalid, magCtx, ckf::options, Acts::ParticleHypothesis::pion(), Acts::Test::prepareSourceLinks(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::referenceSurface(), Acts::Test::resolutions, cpp.ast::reversed(), tracks(), and physmon_ckf_tracking::u.
template<typename fitter_t , typename fitter_options_t , typename parameters_t > void FitterTester::test_ZeroFieldWithSurfaceForward (const fitter_t & fitter, fitter_options_t options, const parameters_t & start, Rng & rng, const bool expected_reversed, const bool expected_smoothed, const bool doDiag) const inline
Definition at line 213 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 213 of file FitterTestsCommon.hpp
References Acts::Test::createMeasurements(), Acts::Direction::Forward, geoCtx, Acts::MultiTrajectoryTraits::kInvalid, magCtx, ckf::options, Acts::Test::prepareSourceLinks(), Acts::Test::resolutions, cpp.ast::reversed(), start, tracks(), and physmon_ckf_tracking::u.
Member Data Documentation
Acts::CalibrationContext FitterTester::calCtx
Definition at line 119 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 119 of file FitterTestsCommon.hpp
Acts::GeometryContext FitterTester::geoCtx
Definition at line 117 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 117 of file FitterTestsCommon.hpp
std::shared_ptr<const Acts::TrackingGeometry> FitterTester::geometry = geometryStore()
Definition at line 123 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 123 of file FitterTestsCommon.hpp
CubicTrackingGeometry FitterTester::geometryStore {geoCtx}
Definition at line 122 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 122 of file FitterTestsCommon.hpp
Acts::MagneticFieldContext FitterTester::magCtx
Definition at line 118 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 118 of file FitterTestsCommon.hpp
constexpr size_t FitterTester::nMeasurements = 6u static
Definition at line 128 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 128 of file FitterTestsCommon.hpp
MeasurementResolutionMap FitterTester::resolutions
Initial value:
= {
      {Acts::GeometryIdentifier().setVolume(2), resPixel},
      {Acts::GeometryIdentifier().setVolume(3).setLayer(2), resStrip0},
      {Acts::GeometryIdentifier().setVolume(3).setLayer(4), resStrip1},
      {Acts::GeometryIdentifier().setVolume(3).setLayer(6), resStrip0},
      {Acts::GeometryIdentifier().setVolume(3).setLayer(8), resStrip1},
  }
Definition at line 134 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 134 of file FitterTestsCommon.hpp
MeasurementResolution FitterTester::resPixel = {MeasurementType::eLoc01, {25_um, 50_um}}
Definition at line 131 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 131 of file FitterTestsCommon.hpp
MeasurementResolution FitterTester::resStrip0 = {MeasurementType::eLoc0, {100_um}}
Definition at line 132 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 132 of file FitterTestsCommon.hpp
MeasurementResolution FitterTester::resStrip1 = {MeasurementType::eLoc1, {150_um}}
Definition at line 133 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 133 of file FitterTestsCommon.hpp
Acts::Propagator<Acts::StraightLineStepper, Acts::Navigator> FitterTester::simPropagator
Initial value:
=
      makeStraightPropagator(geometry)
Definition at line 143 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 143 of file FitterTestsCommon.hpp
TestSourceLink::SurfaceAccessor FitterTester::surfaceAccessor {*geometry}
Definition at line 125 of file FitterTestsCommon.hpp.
View newest version in sPHENIX GitHub at line 125 of file FitterTestsCommon.hpp
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Tests/UnitTests/Core/TrackFitting/FitterTestsCommon.hpp