Analysis Software: CaloAna Class Reference
CaloAna Class Reference
#include <analysis/blob/master/Calo_Validation_Package/src/CaloAna.h>
Public Member Functions
CaloAna (const std::string &name="CaloAna", const std::string &fname="MyNtuple.root")
constructor
virtual ~CaloAna ()
destructor
int Init (PHCompositeNode *)
full initialization
int process_event (PHCompositeNode *)
event processing method
int End (PHCompositeNode *)
end of run method
int process_g4hits (PHCompositeNode *)
int process_g4cells (PHCompositeNode *)
int process_towers (PHCompositeNode *)
int process_clusters (PHCompositeNode *)
void Detector (const std::string &name)
void set_timing_cut_width (const int &t)
void set_vertex_cut (const float &v)
void apply_vertex_cut (bool Vtx_cut)
CaloAna (const std::string &name="CaloAna", const std::string &fname="MyNtuple.root")
constructor
virtual ~CaloAna ()
destructor
int Init (PHCompositeNode *)
full initialization
int process_event (PHCompositeNode *)
event processing method
int End (PHCompositeNode *)
end of run method
int process_g4hits (PHCompositeNode *)
int process_g4cells (PHCompositeNode *)
int process_towers (PHCompositeNode *)
int process_clusters (PHCompositeNode *)
void Detector (const std::string &name)
void set_timing_cut_width (const int &t)
void set_vertex_cut (const float &v)
void apply_vertex_cut (bool Vtx_cut)
std::pair< double, double > fitHistogram (TH1F *h)
void fitEtaSlices (std::string infile, std::string outfile, std::string cdbFile)
CaloAna (const std::string &name="CaloAna", const std::string &fname="MyNtuple.root")
constructor
virtual ~CaloAna ()
destructor
int Init (PHCompositeNode *)
full initialization
int process_event (PHCompositeNode *)
event processing method
int End (PHCompositeNode *)
end of run method
int process_g4hits (PHCompositeNode *)
int process_g4cells (PHCompositeNode *)
int process_towers (PHCompositeNode *)
int process_clusters (PHCompositeNode *)
void Detector (const std::string &name)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int Getpeaktime (TH1 *h)
int Getpeaktime (TH1 *h)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
std::string detector
std::string outfilename
Fun4AllHistoManager * hm = nullptr
TFile * outfile = nullptr
TH2F * h_emcal_mbd_correlation = nullptr
TH2F * h_ohcal_mbd_correlation = nullptr
TH2F * h_ihcal_mbd_correlation = nullptr
TH2F * h_emcal_hcal_correlation = nullptr
TH2F * h_emcal_zdc_correlation = nullptr
TH1F * h_InvMass = nullptr
TH2F * h_cemc_etaphi = nullptr
TH2F * h_hcalin_etaphi = nullptr
TH2F * h_hcalout_etaphi = nullptr
TH2F * h_cemc_etaphi_wQA = nullptr
TH2F * h_hcalin_etaphi_wQA = nullptr
TH2F * h_hcalout_etaphi_wQA = nullptr
TH1 * h_totalzdc_e
TProfile2D * h_cemc_etaphi_time = nullptr
TProfile2D * h_hcalin_etaphi_time = nullptr
TProfile2D * h_hcalout_etaphi_time = nullptr
TH2F * h_cemc_e_chi2 = nullptr
TH2F * h_ohcal_e_chi2 = nullptr
TH2F * h_ihcal_e_chi2 = nullptr
TProfile2D * h_cemc_etaphi_badChi2 = nullptr
TProfile2D * h_hcalin_etaphi_badChi2 = nullptr
TProfile2D * h_hcalout_etaphi_badChi2 = nullptr
TH1 * hzdctime
TH1 * hmbdtime
TH1 * hemcaltime
TH1 * hihcaltime
TH1 * hohcaltime
TH1 * hzdctime_cut
TH1 * hmbdtime_cut
TH1 * hemcaltime_cut
TH1 * hihcaltime_cut
TH1 * hohcaltime_cut
TH1 * hvtx_z_raw
TH1 * hvtx_z_cut
TH1 * hzdcSouthraw
TH1 * hzdcNorthraw
TH1 * hzdcSouthcalib
TH1 * hzdcNorthcalib
TH1F * h_clusE
TH2F * h_etaphi_clus
TNtuple * g4hitntuple = nullptr
TNtuple * g4cellntuple = nullptr
TTree * towerntuple = nullptr
TNtuple * clusterntuple = nullptr
std::vector< float > m_energy
std::vector< int > m_etabin
std::vector< int > m_phibin
std::vector< int > m_time
std::vector< float > m_hcalin_energy
std::vector< int > m_hcalin_etabin
std::vector< int > m_hcalin_phibin
std::vector< int > m_hcalin_time
std::vector< float > m_hcalout_energy
std::vector< int > m_hcalout_etabin
std::vector< int > m_hcalout_phibin
std::vector< int > m_hcalout_time
std::vector< float > m_zdc_energy
std::vector< int > m_zdc_index
std::vector< int > m_zdc_side
std::vector< float > m_bbc_energy
std::vector< int > m_bbc_type
std::vector< int > m_bbc_side
int _eventcounter
int _range = 1
float _vz = 0.
bool m_vtxCut = false
bool dynMaskClus = true
TH1F * h_InvMassMix = nullptr
TH1F * h_pt1
TH1F * h_pt2
TH1F * h_nclusters
TH1F * h_mass_eta_lt [96]
TH1F * h_emcal_e_eta
float target_pi0_mass = 0.145
TNtuple * towerntuple = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Detailed Description
Definition at line 17 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 17 of file CaloAna.h
Constructor & Destructor Documentation
CaloAna::CaloAna (const std::string & name = "CaloAna", const std::string & fname = "MyNtuple.root")
constructor
Definition at line 58 of file CaloAna.cc.
View newest version in sPHENIX GitHub at line 58 of file CaloAna.cc
References _eventcounter.
CaloAna::~CaloAna () virtual
destructor
Definition at line 66 of file CaloAna.cc.
View newest version in sPHENIX GitHub at line 66 of file CaloAna.cc
References clusterntuple, g4cellntuple, g4hitntuple, hm, and towerntuple.
CaloAna::CaloAna (const std::string & name = "CaloAna", const std::string & fname = "MyNtuple.root")
constructor
virtual CaloAna::~CaloAna () virtual
destructor
CaloAna::CaloAna (const std::string & name = "CaloAna", const std::string & fname = "MyNtuple.root")
constructor
virtual CaloAna::~CaloAna () virtual
destructor
Member Function Documentation
void CaloAna::apply_vertex_cut (bool Vtx_cut) inline
Definition at line 44 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 44 of file CaloAna.h
References m_vtxCut.
Referenced by Fun4All_Calo(), Fun4All_EMCal(), and Fun4All_EMCal_Hist().
void CaloAna::apply_vertex_cut (bool Vtx_cut) inline
Definition at line 44 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 44 of file CaloAna.h
References m_vtxCut.
void CaloAna::Detector (const std::string & name) inline
Definition at line 35 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 35 of file CaloAna.h
References perf_headwind::name.
void CaloAna::Detector (const std::string & name) inline
Definition at line 41 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 41 of file CaloAna.h
References perf_headwind::name.
Referenced by Fun4All_CaloAna().
void CaloAna::Detector (const std::string & name) inline
Definition at line 41 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 41 of file CaloAna.h
References perf_headwind::name.
int CaloAna::End (PHCompositeNode *) virtual
end of run method
Reimplemented from SubsysReco.
int CaloAna::End (PHCompositeNode *) virtual
end of run method
Reimplemented from SubsysReco.
Definition at line 568 of file CaloAna.cc.
View newest version in sPHENIX GitHub at line 568 of file CaloAna.cc
References Fun4AllHistoManager::dumpHistos(), hm, outfile, and outfilename.
int CaloAna::End (PHCompositeNode *) virtual
end of run method
Reimplemented from SubsysReco.
void CaloAna::fitEtaSlices (std::string infile, std::string outfile, std::string cdbFile)
Definition at line 399 of file CaloAna.cc.
View newest version in sPHENIX GitHub at line 399 of file CaloAna.cc
References TowerInfoDefs::encode_emcal(), fitHistogram(), CDBTTree::GetFloatValue(), i, j, and target_pi0_mass.
Referenced by doFitAndCalibUpdate().
std::pair< double, double > CaloAna::fitHistogram (TH1F * h)
Definition at line 372 of file CaloAna.cc.
View newest version in sPHENIX GitHub at line 372 of file CaloAna.cc
References fitFunc, mean(), and target_pi0_mass.
Referenced by fitEtaSlices().
int CaloAna::Getpeaktime (TH1 * h) protected
Definition at line 579 of file CaloAna.cc.
View newest version in sPHENIX GitHub at line 579 of file CaloAna.cc
References Acts::PhysicalConstants::c.
Referenced by process_towers().
int CaloAna::Getpeaktime (TH1 * h) protected
int CaloAna::Init (PHCompositeNode *) virtual
full initialization
Reimplemented from SubsysReco.
int CaloAna::Init (PHCompositeNode *) virtual
full initialization
Reimplemented from SubsysReco.
Definition at line 75 of file CaloAna.cc.
View newest version in sPHENIX GitHub at line 75 of file CaloAna.cc
References h_cemc_e_chi2, h_cemc_etaphi, h_cemc_etaphi_badChi2, h_cemc_etaphi_time, h_cemc_etaphi_wQA, h_clusE, h_emcal_hcal_correlation, h_emcal_mbd_correlation, h_emcal_zdc_correlation, h_etaphi_clus, h_hcalin_etaphi, h_hcalin_etaphi_badChi2, h_hcalin_etaphi_time, h_hcalin_etaphi_wQA, h_hcalout_etaphi, h_hcalout_etaphi_badChi2, h_hcalout_etaphi_time, h_hcalout_etaphi_wQA, h_ihcal_e_chi2, h_ihcal_mbd_correlation, h_InvMass, h_ohcal_e_chi2, h_ohcal_mbd_correlation, h_totalzdc_e, hemcaltime, hemcaltime_cut, hihcaltime, hihcaltime_cut, hm, hohcaltime, hohcaltime_cut, hvtx_z_cut, hvtx_z_raw, hzdcNorthcalib, hzdcNorthraw, hzdcSouthcalib, hzdcSouthraw, hzdctime, hzdctime_cut, LogYHist2D(), Fun4AllBase::Name(), outfile, and outfilename.
int CaloAna::Init (PHCompositeNode *) virtual
full initialization
Reimplemented from SubsysReco.
int CaloAna::process_clusters (PHCompositeNode *)
int CaloAna::process_clusters (PHCompositeNode * topNode)
Definition at line 189 of file CaloAna.cc.
View newest version in sPHENIX GitHub at line 189 of file CaloAna.cc
References clusterntuple, clusters, detector, Fun4AllReturnCodes::EVENT_OK, and RawClusterContainer::getClusters().
int CaloAna::process_clusters (PHCompositeNode *)
int CaloAna::process_event (PHCompositeNode *) virtual
event processing method
Reimplemented from SubsysReco.
int CaloAna::process_event (PHCompositeNode * topNode) virtual
event processing method
Reimplemented from SubsysReco.
Definition at line 142 of file CaloAna.cc.
View newest version in sPHENIX GitHub at line 142 of file CaloAna.cc
References _eventcounter, Fun4AllReturnCodes::EVENT_OK, and process_towers().
int CaloAna::process_event (PHCompositeNode *) virtual
event processing method
Reimplemented from SubsysReco.
int CaloAna::process_g4cells (PHCompositeNode *)
int CaloAna::process_g4cells (PHCompositeNode * topNode)
Definition at line 111 of file CaloAna.cc.
View newest version in sPHENIX GitHub at line 111 of file CaloAna.cc
References detector, KF_timing::etabin, Fun4AllReturnCodes::EVENT_OK, g4cellntuple, PHG4CellDefs::get_binning(), PHG4CellDefs::ScintillatorSlatBinning::get_column(), PHG4CellDefs::SpacalBinning::get_etabin(), PHG4CellDefs::SizeBinning::get_phibin(), PHG4CellDefs::SpacalBinning::get_phibin(), PHG4CellDefs::ScintillatorSlatBinning::get_row(), PHG4CellDefs::SizeBinning::get_zbin(), PHG4CellContainer::getCells(), PHG4CellDefs::scintillatorslatbinning, PHG4CellDefs::sizebinning, and PHG4CellDefs::spacalbinning.
int CaloAna::process_g4cells (PHCompositeNode *)
int CaloAna::process_g4hits (PHCompositeNode *)
int CaloAna::process_g4hits (PHCompositeNode * topNode)
Definition at line 83 of file CaloAna.cc.
View newest version in sPHENIX GitHub at line 83 of file CaloAna.cc
References detector, Fun4AllReturnCodes::EVENT_OK, g4hitntuple, and PHG4HitContainer::getHits().
int CaloAna::process_g4hits (PHCompositeNode *)
int CaloAna::process_towers (PHCompositeNode *)
int CaloAna::process_towers (PHCompositeNode * topNode)
Definition at line 151 of file CaloAna.cc.
View newest version in sPHENIX GitHub at line 151 of file CaloAna.cc
References _eventcounter, _range, _vz, Fun4AllReturnCodes::ABORTEVENT, GlobalVertexMap::begin(), channel(), dynMaskClus, GlobalVertexMap::empty(), TowerInfoContainer::encode_key(), Fun4AllReturnCodes::EVENT_OK, RawTowerGeom::get_bineta(), RawTowerGeom::get_binphi(), TowerInfo::get_chi2(), RawCluster::get_chi2(), TowerInfo::get_energy(), TowerInfo::get_isBadChi2(), MbdPmtContainer::get_npmt(), MbdPmtContainer::get_pmt(), MbdPmtHit::get_q(), TowerInfo::get_time(), TowerInfo::get_time_float(), TowerInfoContainer::get_tower_at_channel(), RawTowerGeomContainer::get_tower_geometry(), RawCluster::get_towers(), GlobalVertex::get_z(), RawClusterContainer::getClusters(), RawClusterUtility::GetECoreVec(), Getpeaktime(), TowerInfoContainer::getTowerEtaBin(), TowerInfoContainer::getTowerPhiBin(), h_cemc_e_chi2, h_cemc_etaphi, h_cemc_etaphi_badChi2, h_cemc_etaphi_time, h_cemc_etaphi_wQA, h_clusE, h_emcal_hcal_correlation, h_emcal_mbd_correlation, h_emcal_zdc_correlation, h_etaphi_clus, h_hcalin_etaphi, h_hcalin_etaphi_badChi2, h_hcalin_etaphi_time, h_hcalin_etaphi_wQA, h_hcalout_etaphi, h_hcalout_etaphi_badChi2, h_hcalout_etaphi_time, h_hcalout_etaphi_wQA, h_ihcal_e_chi2, h_ihcal_mbd_correlation, h_InvMass, h_ohcal_e_chi2, h_ohcal_mbd_correlation, h_totalzdc_e, hemcaltime, hemcaltime_cut, hihcaltime, hihcaltime_cut, hohcaltime, hohcaltime_cut, hvtx_z_cut, hvtx_z_raw, hzdcNorthcalib, hzdcNorthraw, hzdcSouthcalib, hzdcSouthraw, hzdctime, hzdctime_cut, i, m_vtxCut, Fun4AllBase::Name(), PHWHERE, TowerInfoContainer::size(), and size.
Referenced by process_event().
int CaloAna::process_towers (PHCompositeNode *)
void CaloAna::set_timing_cut_width (const int & t) inline
Definition at line 42 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 42 of file CaloAna.h
References _range, and t.
Referenced by Fun4All_Calo(), Fun4All_EMCal(), and Fun4All_EMCal_Hist().
void CaloAna::set_timing_cut_width (const int & t) inline
Definition at line 42 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 42 of file CaloAna.h
References _range, and t.
void CaloAna::set_vertex_cut (const float & v) inline
Definition at line 43 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 43 of file CaloAna.h
References _vz, and testSigmaEff::v.
Referenced by Fun4All_Calo(), Fun4All_EMCal(), and Fun4All_EMCal_Hist().
void CaloAna::set_vertex_cut (const float & v) inline
Definition at line 43 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 43 of file CaloAna.h
References _vz, and testSigmaEff::v.
Member Data Documentation
int CaloAna::_eventcounter protected
Definition at line 131 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 131 of file CaloAna.h
Referenced by CaloAna(), process_event(), and process_towers().
int CaloAna::_range = 1 protected
Definition at line 132 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 132 of file CaloAna.h
Referenced by process_towers(), and set_timing_cut_width().
float CaloAna::_vz = 0. protected
Definition at line 133 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 133 of file CaloAna.h
Referenced by process_towers(), and set_vertex_cut().
TNtuple * CaloAna::clusterntuple = nullptr protected
Definition at line 106 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 106 of file CaloAna.h
Referenced by process_clusters(), and ~CaloAna().
std::string CaloAna::detector protected
Definition at line 47 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 47 of file CaloAna.h
Referenced by process_clusters(), process_g4cells(), and process_g4hits().
bool CaloAna::dynMaskClus = true protected
Definition at line 135 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 135 of file CaloAna.h
Referenced by process_towers().
TNtuple * CaloAna::g4cellntuple = nullptr protected
Definition at line 104 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 104 of file CaloAna.h
Referenced by process_g4cells(), and ~CaloAna().
TNtuple * CaloAna::g4hitntuple = nullptr protected
Definition at line 103 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 103 of file CaloAna.h
Referenced by process_g4hits(), and ~CaloAna().
TH2F* CaloAna::h_cemc_e_chi2 = nullptr protected
Definition at line 72 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 72 of file CaloAna.h
Referenced by Init(), and process_towers().
TH2F * CaloAna::h_cemc_etaphi = nullptr protected
Definition at line 60 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 60 of file CaloAna.h
Referenced by Init(), and process_towers().
TProfile2D * CaloAna::h_cemc_etaphi_badChi2 = nullptr protected
Definition at line 76 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 76 of file CaloAna.h
Referenced by Init(), and process_towers().
TProfile2D * CaloAna::h_cemc_etaphi_time = nullptr protected
Definition at line 68 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 68 of file CaloAna.h
Referenced by Init(), and process_towers().
TH2F * CaloAna::h_cemc_etaphi_wQA = nullptr protected
Definition at line 63 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 63 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1F * CaloAna::h_clusE protected
Definition at line 100 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 100 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1F* CaloAna::h_emcal_e_eta protected
Definition at line 140 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 140 of file CaloAna.h
TH2F * CaloAna::h_emcal_hcal_correlation = nullptr protected
Definition at line 55 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 55 of file CaloAna.h
Referenced by Init(), and process_towers().
TH2F * CaloAna::h_emcal_mbd_correlation = nullptr protected
Definition at line 52 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 52 of file CaloAna.h
Referenced by Init(), and process_towers().
TH2F * CaloAna::h_emcal_zdc_correlation = nullptr protected
Definition at line 56 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 56 of file CaloAna.h
Referenced by Init(), and process_towers().
TH2F * CaloAna::h_etaphi_clus protected
Definition at line 101 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 101 of file CaloAna.h
Referenced by Init(), and process_towers().
TH2F * CaloAna::h_hcalin_etaphi = nullptr protected
Definition at line 61 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 61 of file CaloAna.h
Referenced by Init(), and process_towers().
TProfile2D * CaloAna::h_hcalin_etaphi_badChi2 = nullptr protected
Definition at line 77 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 77 of file CaloAna.h
Referenced by Init(), and process_towers().
TProfile2D * CaloAna::h_hcalin_etaphi_time = nullptr protected
Definition at line 69 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 69 of file CaloAna.h
Referenced by Init(), and process_towers().
TH2F * CaloAna::h_hcalin_etaphi_wQA = nullptr protected
Definition at line 64 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 64 of file CaloAna.h
Referenced by Init(), and process_towers().
TH2F * CaloAna::h_hcalout_etaphi = nullptr protected
Definition at line 62 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 62 of file CaloAna.h
Referenced by Init(), and process_towers().
TProfile2D * CaloAna::h_hcalout_etaphi_badChi2 = nullptr protected
Definition at line 78 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 78 of file CaloAna.h
Referenced by Init(), and process_towers().
TProfile2D * CaloAna::h_hcalout_etaphi_time = nullptr protected
Definition at line 70 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 70 of file CaloAna.h
Referenced by Init(), and process_towers().
TH2F * CaloAna::h_hcalout_etaphi_wQA = nullptr protected
Definition at line 65 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 65 of file CaloAna.h
Referenced by Init(), and process_towers().
TH2F* CaloAna::h_ihcal_e_chi2 = nullptr protected
Definition at line 74 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 74 of file CaloAna.h
Referenced by Init(), and process_towers().
TH2F * CaloAna::h_ihcal_mbd_correlation = nullptr protected
Definition at line 54 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 54 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1F * CaloAna::h_InvMass = nullptr protected
Definition at line 58 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 58 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1F* CaloAna::h_InvMassMix = nullptr protected
Definition at line 62 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 62 of file CaloAna.h
TH1F* CaloAna::h_mass_eta_lt[96] protected
Definition at line 139 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 139 of file CaloAna.h
TH1F* CaloAna::h_nclusters protected
Definition at line 138 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 138 of file CaloAna.h
TH2F* CaloAna::h_ohcal_e_chi2 = nullptr protected
Definition at line 73 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 73 of file CaloAna.h
Referenced by Init(), and process_towers().
TH2F * CaloAna::h_ohcal_mbd_correlation = nullptr protected
Definition at line 53 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 53 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1F* CaloAna::h_pt1 protected
Definition at line 136 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 136 of file CaloAna.h
TH1F* CaloAna::h_pt2 protected
Definition at line 137 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 137 of file CaloAna.h
TH1 * CaloAna::h_totalzdc_e protected
Definition at line 66 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 66 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1 * CaloAna::hemcaltime protected
Definition at line 82 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 82 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1 * CaloAna::hemcaltime_cut protected
Definition at line 88 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 88 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1 * CaloAna::hihcaltime protected
Definition at line 83 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 83 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1 * CaloAna::hihcaltime_cut protected
Definition at line 89 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 89 of file CaloAna.h
Referenced by Init(), and process_towers().
Fun4AllHistoManager * CaloAna::hm = nullptr protected
Definition at line 50 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 50 of file CaloAna.h
Referenced by End(), Init(), and ~CaloAna().
TH1 * CaloAna::hmbdtime protected
Definition at line 81 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 81 of file CaloAna.h
TH1 * CaloAna::hmbdtime_cut protected
Definition at line 87 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 87 of file CaloAna.h
TH1 * CaloAna::hohcaltime protected
Definition at line 84 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 84 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1 * CaloAna::hohcaltime_cut protected
Definition at line 90 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 90 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1 * CaloAna::hvtx_z_cut protected
Definition at line 93 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 93 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1 * CaloAna::hvtx_z_raw protected
Definition at line 92 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 92 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1 * CaloAna::hzdcNorthcalib protected
Definition at line 98 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 98 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1 * CaloAna::hzdcNorthraw protected
Definition at line 96 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 96 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1 * CaloAna::hzdcSouthcalib protected
Definition at line 97 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 97 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1 * CaloAna::hzdcSouthraw protected
Definition at line 95 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 95 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1 * CaloAna::hzdctime protected
Definition at line 80 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 80 of file CaloAna.h
Referenced by Init(), and process_towers().
TH1 * CaloAna::hzdctime_cut protected
Definition at line 86 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 86 of file CaloAna.h
Referenced by Init(), and process_towers().
std::vector< float > CaloAna::m_bbc_energy protected
Definition at line 128 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 128 of file CaloAna.h
std::vector< int > CaloAna::m_bbc_side protected
Definition at line 130 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 130 of file CaloAna.h
std::vector< int > CaloAna::m_bbc_type protected
Definition at line 129 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 129 of file CaloAna.h
std::vector< float > CaloAna::m_energy protected
Definition at line 107 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 107 of file CaloAna.h
std::vector< int > CaloAna::m_etabin protected
Definition at line 108 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 108 of file CaloAna.h
std::vector< float > CaloAna::m_hcalin_energy protected
Definition at line 112 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 112 of file CaloAna.h
std::vector< int > CaloAna::m_hcalin_etabin protected
Definition at line 113 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 113 of file CaloAna.h
std::vector< int > CaloAna::m_hcalin_phibin protected
Definition at line 114 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 114 of file CaloAna.h
std::vector< int > CaloAna::m_hcalin_time protected
Definition at line 115 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 115 of file CaloAna.h
std::vector< float > CaloAna::m_hcalout_energy protected
Definition at line 117 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 117 of file CaloAna.h
std::vector< int > CaloAna::m_hcalout_etabin protected
Definition at line 118 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 118 of file CaloAna.h
std::vector< int > CaloAna::m_hcalout_phibin protected
Definition at line 119 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 119 of file CaloAna.h
std::vector< int > CaloAna::m_hcalout_time protected
Definition at line 120 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 120 of file CaloAna.h
std::vector< int > CaloAna::m_phibin protected
Definition at line 109 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 109 of file CaloAna.h
std::vector< int > CaloAna::m_time protected
Definition at line 110 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 110 of file CaloAna.h
bool CaloAna::m_vtxCut = false protected
Definition at line 134 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 134 of file CaloAna.h
Referenced by apply_vertex_cut(), and process_towers().
std::vector< float > CaloAna::m_zdc_energy protected
Definition at line 123 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 123 of file CaloAna.h
std::vector< int > CaloAna::m_zdc_index protected
Definition at line 124 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 124 of file CaloAna.h
std::vector< int > CaloAna::m_zdc_side protected
Definition at line 125 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 125 of file CaloAna.h
TFile * CaloAna::outfile = nullptr protected
Definition at line 51 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 51 of file CaloAna.h
Referenced by End(), and Init().
std::string CaloAna::outfilename protected
Definition at line 48 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 48 of file CaloAna.h
Referenced by End(), and Init().
float CaloAna::target_pi0_mass = 0.145 protected
Definition at line 142 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 142 of file CaloAna.h
Referenced by fitEtaSlices(), and fitHistogram().
TNtuple* CaloAna::towerntuple = nullptr protected
Definition at line 44 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 44 of file CaloAna.h
TTree * CaloAna::towerntuple = nullptr protected
Definition at line 105 of file CaloAna.h.
View newest version in sPHENIX GitHub at line 105 of file CaloAna.h
Referenced by ~CaloAna().
The documentation for this class was generated from the following files:
analysis/blob/master/Calo_Validation_Package/src/CaloAna.h
analysis/blob/master/EMCal_pi0_Calib_2023/src/CaloAna.h
tutorials/blob/master/CaloAna/src/CaloAna.h
analysis/blob/master/Calo_Validation_Package/src/CaloAna.cc
analysis/blob/master/EMCal_pi0_Calib_2023/src/CaloAna.cc
tutorials/blob/master/CaloAna/src/CaloAna.cc