Analysis Software: ckf_tracks Namespace Reference
ckf_tracks Namespace Reference
Functions
def runCKFTracks
Variables
tuple srcdir Path(__file__)
tuple field acts.ConstantBField(acts.Vector3(0, 0, 2 * u.T))
tuple inputParticlePath Path("particles.root")
geometrySelection srcdir
digiConfigFile srcdir
outputCsv True,
truthSmearedSeeded False,
truthEstimatedSeeded False,
tuple outputDir Path.cwd()
Function Documentation
def ckf_tracks.runCKFTracks (trackingGeometry, decorators, geometrySelection)
Definition at line 16 of file ckf_tracks.py.
View newest version in sPHENIX GitHub at line 16 of file ckf_tracks.py
References acts.examples.reconstruction.addCKFTracks(), acts.examples.simulation.addDigitization(), acts.examples.simulation.addFatras(), acts.examples.simulation.addParticleGun(), acts.examples.reconstruction.addSeeding(), acts.examples.simulation.EtaConfig, acts.examples.simulation.ParticleConfig, acts.examples.reconstruction.ParticleSmearingSigmas, acts.examples.simulation.PhiConfig, acts.examples.reconstruction.SeedFinderConfigArg, acts.examples.reconstruction.SeedFinderOptionsArg, str, acts.examples.reconstruction.TruthEstimatedSeedingAlgorithmConfigArg, and acts.examples.reconstruction.TruthSeedRanges.
Variable Documentation
ckf_tracks.digiConfigFile srcdir
Definition at line 150 of file ckf_tracks.py.
View newest version in sPHENIX GitHub at line 150 of file ckf_tracks.py
ckf_tracks.field acts.ConstantBField(acts.Vector3(0, 0, 2 * u.T))
Definition at line 138 of file ckf_tracks.py.
View newest version in sPHENIX GitHub at line 138 of file ckf_tracks.py
ckf_tracks.geometrySelection srcdir
Definition at line 148 of file ckf_tracks.py.
View newest version in sPHENIX GitHub at line 148 of file ckf_tracks.py
ckf_tracks.inputParticlePath Path("particles.root")
Definition at line 140 of file ckf_tracks.py.
View newest version in sPHENIX GitHub at line 140 of file ckf_tracks.py
ckf_tracks.outputCsv True,
Definition at line 152 of file ckf_tracks.py.
View newest version in sPHENIX GitHub at line 152 of file ckf_tracks.py
tuple ckf_tracks.outputDir Path.cwd()
Definition at line 156 of file ckf_tracks.py.
View newest version in sPHENIX GitHub at line 156 of file ckf_tracks.py
tuple ckf_tracks.srcdir Path(__file__)
Definition at line 134 of file ckf_tracks.py.
View newest version in sPHENIX GitHub at line 134 of file ckf_tracks.py
ckf_tracks.truthEstimatedSeeded False,
Definition at line 154 of file ckf_tracks.py.
View newest version in sPHENIX GitHub at line 154 of file ckf_tracks.py
ckf_tracks.truthSmearedSeeded False,
Definition at line 153 of file ckf_tracks.py.
View newest version in sPHENIX GitHub at line 153 of file ckf_tracks.py