Analysis Software: TpcLoadDistortionCorrection Class Reference
TpcLoadDistortionCorrection Class Reference
#include <coresoftware/blob/master/offline/packages/tpc/TpcLoadDistortionCorrection.h>
Public Member Functions
TpcLoadDistortionCorrection (const std::string &="TpcLoadDistortionCorrection")
constructor
int InitRun (PHCompositeNode *) override
global initialization
int process_event (PHCompositeNode *) override
event processing
void set_distortion_filename (const std::string &value)
distortion filename //deprecated
void set_correction_filename (int i, const std::string &value)
correction filename
void set_node_name (const std::string &value)
node name
void set_node_name (int i, const std::string &value)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
std::string m_correction_filename [3] ={"","",""}
correction filename
bool m_correction_in_use [3] ={false,false,false}
flag to indicate correction in use
std::string m_node_name [3] = {"TpcDistortionCorrectionContainerStatic","TpcDistortionCorrectionContainerAverage","TpcDistortionCorrectionContainerFluctuation"}
distortion object node name
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 19 of file TpcLoadDistortionCorrection.h.
View newest version in sPHENIX GitHub at line 19 of file TpcLoadDistortionCorrection.h
Constructor & Destructor Documentation
TpcLoadDistortionCorrection::TpcLoadDistortionCorrection (const std::string & name = "TpcLoadDistortionCorrection")
constructor
Definition at line 45 of file TpcLoadDistortionCorrection.cc.
View newest version in sPHENIX GitHub at line 45 of file TpcLoadDistortionCorrection.cc
Member Function Documentation
int TpcLoadDistortionCorrection::InitRun (PHCompositeNode * topNode) override virtual
global initialization
Get the RUN node and check
Reimplemented from SubsysReco.
Definition at line 50 of file TpcLoadDistortionCorrection.cc.
View newest version in sPHENIX GitHub at line 50 of file TpcLoadDistortionCorrection.cc
References Fun4AllReturnCodes::ABORTRUN, assert, Fun4AllReturnCodes::EVENT_OK, extension, PHNodeIterator::findFirst(), i, j, m_correction_filename, m_correction_in_use, m_node_name, and Fun4AllBase::Verbosity().
int TpcLoadDistortionCorrection::process_event (PHCompositeNode *) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 115 of file TpcLoadDistortionCorrection.cc.
View newest version in sPHENIX GitHub at line 115 of file TpcLoadDistortionCorrection.cc
References Fun4AllReturnCodes::EVENT_OK.
void TpcLoadDistortionCorrection::set_correction_filename (int i, const std::string & value) inline
correction filename
Definition at line 37 of file TpcLoadDistortionCorrection.h.
View newest version in sPHENIX GitHub at line 37 of file TpcLoadDistortionCorrection.h
References i, m_correction_filename, m_correction_in_use, and value.
Referenced by set_distortion_filename().
void TpcLoadDistortionCorrection::set_distortion_filename (const std::string & value) inline
distortion filename //deprecated
Definition at line 33 of file TpcLoadDistortionCorrection.h.
View newest version in sPHENIX GitHub at line 33 of file TpcLoadDistortionCorrection.h
References set_correction_filename().
Referenced by TrackingInit().
void TpcLoadDistortionCorrection::set_node_name (const std::string & value) inline
node name
Definition at line 43 of file TpcLoadDistortionCorrection.h.
View newest version in sPHENIX GitHub at line 43 of file TpcLoadDistortionCorrection.h
References m_node_name, and value.
void TpcLoadDistortionCorrection::set_node_name (int i, const std::string & value) inline
Definition at line 45 of file TpcLoadDistortionCorrection.h.
View newest version in sPHENIX GitHub at line 45 of file TpcLoadDistortionCorrection.h
References i, m_node_name, and value.
Member Data Documentation
std::string TpcLoadDistortionCorrection::m_correction_filename[3] ={"","",""} private
correction filename
Definition at line 51 of file TpcLoadDistortionCorrection.h.
View newest version in sPHENIX GitHub at line 51 of file TpcLoadDistortionCorrection.h
Referenced by InitRun(), and set_correction_filename().
bool TpcLoadDistortionCorrection::m_correction_in_use[3] ={false,false,false} private
flag to indicate correction in use
Definition at line 54 of file TpcLoadDistortionCorrection.h.
View newest version in sPHENIX GitHub at line 54 of file TpcLoadDistortionCorrection.h
Referenced by InitRun(), and set_correction_filename().
std::string TpcLoadDistortionCorrection::m_node_name[3] = {"TpcDistortionCorrectionContainerStatic","TpcDistortionCorrectionContainerAverage","TpcDistortionCorrectionContainerFluctuation"} private
distortion object node name
Definition at line 57 of file TpcLoadDistortionCorrection.h.
View newest version in sPHENIX GitHub at line 57 of file TpcLoadDistortionCorrection.h
Referenced by InitRun(), and set_node_name().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/tpc/TpcLoadDistortionCorrection.h
coresoftware/blob/master/offline/packages/tpc/TpcLoadDistortionCorrection.cc