Analysis Software: RhoFluct Class Reference
RhoFluct Class Reference
#include <analysis/blob/master/JS-Jet/FastJetMedianBkg/src_JetMedianTree/macro/plot/RhoFluct.h>
Public Member Functions
RhoFluct (TTree *tree=0)
virtual ~RhoFluct ()
virtual Int_t Cut (Long64_t entry)
virtual Int_t GetEntry (Long64_t entry)
virtual Long64_t LoadTree (Long64_t entry)
virtual void Init (TTree *tree)
virtual void Loop (string)
virtual Bool_t Notify ()
virtual void Show (Long64_t entry=-1)
int get_ip_decile (float ip)
RhoFluct (const std::string &outputfilename="RhoFluct.root", const float _jet_R=0.4)
virtual ~RhoFluct ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void add_input_Sub1 (JetInput *input)
void add_input_rhoA (JetInput *input)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Attributes
TTree * fChain
Int_t fCurrent
pointer to the analyzed TTree or TChain
Float_t rho
current Tree number in a TChain
Float_t rho_sigma
Float_t cent
Float_t cent_mdb
Float_t cent_epd
Float_t impactparam
Float_t emb_1TeV_phi
Float_t emb_1TeV_eta
Bool_t sub1_ismatched
Float_t sub1JetPhi
Float_t sub1JetEta
Float_t sub1JetPt
Float_t sub1Jet_delPt
Bool_t rhoA_ismatched
Float_t rhoAJetPhi
Float_t rhoAJetEta
Float_t rhoAJetPt
Float_t rhoAJetArea
Float_t rhoAJetPtLessRhoA
Float_t rhoAJet_delPt
TBranch * b_rho
TBranch * b_rho_sigma
TBranch * b_cent
TBranch * b_cent_mdb
TBranch * b_cent_epd
TBranch * b_impactparam
TBranch * b_emb_1TeV_phi
TBranch * b_emb_1TeV_eta
TBranch * b_sub1_ismatched
TBranch * b_sub1JetPhi
TBranch * b_sub1JetEta
TBranch * b_sub1JetPt
TBranch * b_sub1Jet_delPt
TBranch * b_rhoA_ismatched
TBranch * b_rhoAJetPhi
TBranch * b_rhoAJetEta
TBranch * b_rhoAJetPt
TBranch * b_rhoAJetArea
TBranch * b_rhoAJetPtLessRhoA
TBranch * b_rhoAJet_delPt
const std::array< float, 11 > IP_DEC
Private Attributes
TRandom3 rand3 {}
long long int nevent { 0 }
long long int outevent { 0 }
const std::string m_outputfilename
const float jet_R
const std::string m_truthJetName
const std::string m_Sub1JetName
int i_truthset = 0
std::string m_recoJetName
TTree * m_T
Output Tree variables.
float m_rho
float m_rho_sigma
float m_cent_mdb { -1. }
float m_cent { -1. }
float m_cent_epd { -1. }
float m_impactparam { -1. }
float m_1TeV_phi
float m_1TeV_eta
bool m_rhoA_ismatched
float m_rhoAJetPhi
float m_rhoAJetEta
float m_rhoAJetPt
float m_rhoAJetArea
float m_rhoAJetPtLessRhoA
float m_rhoAJet_delpt
bool m_Sub1_ismatched
float m_Sub1JetPhi
float m_Sub1JetEta
float m_Sub1JetPt
float m_Sub1Jet_delpt
float mBGE_mean_area { 0 }
float mBGE_empty_area { 0 }
float mBGE_n_empty_jets { 0 }
unsigned int mBGE_n_jets_used { 0 }
std::vector< JetInput * > m_input_Sub1
std::vector< JetInput * > m_input_rhoA
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 17 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 17 of file RhoFluct.h
Constructor & Destructor Documentation
RhoFluct::RhoFluct (TTree * tree = 0)
virtual RhoFluct::~RhoFluct () virtual
RhoFluct::RhoFluct (const std::string & outputfilename = "RhoFluct.root", const float _jet_R = 0.4)
Definition at line 41 of file RhoFluct.cc.
View newest version in sPHENIX GitHub at line 41 of file RhoFluct.cc
virtual RhoFluct::~RhoFluct () virtual
Member Function Documentation
void RhoFluct::add_input_rhoA (JetInput * input) inline
Definition at line 38 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 38 of file RhoFluct.h
References m_input_rhoA.
Referenced by Fun4All_RhoFluct().
void RhoFluct::add_input_Sub1 (JetInput * input) inline
Definition at line 37 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 37 of file RhoFluct.h
References m_input_Sub1.
Referenced by Fun4All_RhoFluct().
virtual Int_t RhoFluct::Cut (Long64_t entry) virtual
int RhoFluct::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
int RhoFluct::get_ip_decile (float ip) inline
Definition at line 91 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 91 of file RhoFluct.h
Referenced by Loop().
virtual Int_t RhoFluct::GetEntry (Long64_t entry) virtual
int RhoFluct::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
virtual void RhoFluct::Init (TTree * tree) virtual
int RhoFluct::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
virtual Long64_t RhoFluct::LoadTree (Long64_t entry) virtual
Referenced by Loop().
void RhoFluct::Loop (string out_name) virtual
Definition at line 7 of file decile_RhoFluct.cc.
View newest version in sPHENIX GitHub at line 7 of file decile_RhoFluct.cc
References fChain, fout, get_ip_decile(), i, impactparam, IP_DEC, k, LoadTree(), rhoA_ismatched, rhoAJet_delPt, sub1_ismatched, sub1Jet_delPt, and voi_stem().
virtual Bool_t RhoFluct::Notify () virtual
int RhoFluct::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
virtual void RhoFluct::Show (Long64_t entry = -1) virtual
Member Data Documentation
TBranch* RhoFluct::b_cent
Definition at line 49 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 49 of file RhoFluct.h
TBranch* RhoFluct::b_cent_epd
Definition at line 51 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 51 of file RhoFluct.h
TBranch* RhoFluct::b_cent_mdb
Definition at line 50 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 50 of file RhoFluct.h
TBranch* RhoFluct::b_emb_1TeV_eta
Definition at line 54 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 54 of file RhoFluct.h
TBranch* RhoFluct::b_emb_1TeV_phi
Definition at line 53 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 53 of file RhoFluct.h
TBranch* RhoFluct::b_impactparam
Definition at line 52 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 52 of file RhoFluct.h
TBranch* RhoFluct::b_rho
Definition at line 47 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 47 of file RhoFluct.h
TBranch* RhoFluct::b_rho_sigma
Definition at line 48 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 48 of file RhoFluct.h
TBranch* RhoFluct::b_rhoA_ismatched
Definition at line 60 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 60 of file RhoFluct.h
TBranch* RhoFluct::b_rhoAJet_delPt
Definition at line 66 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 66 of file RhoFluct.h
TBranch* RhoFluct::b_rhoAJetArea
Definition at line 64 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 64 of file RhoFluct.h
TBranch* RhoFluct::b_rhoAJetEta
Definition at line 62 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 62 of file RhoFluct.h
TBranch* RhoFluct::b_rhoAJetPhi
Definition at line 61 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 61 of file RhoFluct.h
TBranch* RhoFluct::b_rhoAJetPt
Definition at line 63 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 63 of file RhoFluct.h
TBranch* RhoFluct::b_rhoAJetPtLessRhoA
Definition at line 65 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 65 of file RhoFluct.h
TBranch* RhoFluct::b_sub1_ismatched
Definition at line 55 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 55 of file RhoFluct.h
TBranch* RhoFluct::b_sub1Jet_delPt
Definition at line 59 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 59 of file RhoFluct.h
TBranch* RhoFluct::b_sub1JetEta
Definition at line 57 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 57 of file RhoFluct.h
TBranch* RhoFluct::b_sub1JetPhi
Definition at line 56 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 56 of file RhoFluct.h
TBranch* RhoFluct::b_sub1JetPt
Definition at line 58 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 58 of file RhoFluct.h
Float_t RhoFluct::cent
Definition at line 27 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 27 of file RhoFluct.h
Float_t RhoFluct::cent_epd
Definition at line 29 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 29 of file RhoFluct.h
Float_t RhoFluct::cent_mdb
Definition at line 28 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 28 of file RhoFluct.h
Float_t RhoFluct::emb_1TeV_eta
Definition at line 32 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 32 of file RhoFluct.h
Float_t RhoFluct::emb_1TeV_phi
Definition at line 31 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 31 of file RhoFluct.h
TTree* RhoFluct::fChain
Definition at line 19 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 19 of file RhoFluct.h
Referenced by Loop().
Int_t RhoFluct::fCurrent
pointer to the analyzed TTree or TChain
Definition at line 20 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 20 of file RhoFluct.h
int RhoFluct::i_truthset = 0 private
Definition at line 50 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 50 of file RhoFluct.h
Float_t RhoFluct::impactparam
Definition at line 30 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 30 of file RhoFluct.h
Referenced by Loop().
const std::array<float,11> RhoFluct::IP_DEC
Initial value:
{{
         0.,
         4.86409,
         6.84237,
         8.34927,
         9.61087,
         10.722 ,
         11.7247,
         12.6486,
         13.5242,
         14.4868,
         22.
   }}
Definition at line 78 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 78 of file RhoFluct.h
Referenced by Loop().
const float RhoFluct::jet_R private
Definition at line 46 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 46 of file RhoFluct.h
float RhoFluct::m_1TeV_eta private
Definition at line 66 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 66 of file RhoFluct.h
float RhoFluct::m_1TeV_phi private
Definition at line 65 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 65 of file RhoFluct.h
float RhoFluct::m_cent { -1. } private
Definition at line 60 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 60 of file RhoFluct.h
float RhoFluct::m_cent_epd { -1. } private
Definition at line 61 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 61 of file RhoFluct.h
float RhoFluct::m_cent_mdb { -1. } private
Definition at line 59 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 59 of file RhoFluct.h
float RhoFluct::m_impactparam { -1. } private
Definition at line 62 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 62 of file RhoFluct.h
std::vector<JetInput *> RhoFluct::m_input_rhoA private
Definition at line 89 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 89 of file RhoFluct.h
Referenced by add_input_rhoA().
std::vector<JetInput *> RhoFluct::m_input_Sub1 private
Definition at line 89 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 89 of file RhoFluct.h
Referenced by add_input_Sub1().
const std::string RhoFluct::m_outputfilename private
Definition at line 45 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 45 of file RhoFluct.h
std::string RhoFluct::m_recoJetName private
Definition at line 52 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 52 of file RhoFluct.h
float RhoFluct::m_rho private
Definition at line 57 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 57 of file RhoFluct.h
float RhoFluct::m_rho_sigma private
Definition at line 58 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 58 of file RhoFluct.h
bool RhoFluct::m_rhoA_ismatched private
Definition at line 69 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 69 of file RhoFluct.h
float RhoFluct::m_rhoAJet_delpt private
Definition at line 75 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 75 of file RhoFluct.h
float RhoFluct::m_rhoAJetArea private
Definition at line 73 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 73 of file RhoFluct.h
float RhoFluct::m_rhoAJetEta private
Definition at line 71 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 71 of file RhoFluct.h
float RhoFluct::m_rhoAJetPhi private
Definition at line 70 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 70 of file RhoFluct.h
float RhoFluct::m_rhoAJetPt private
Definition at line 72 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 72 of file RhoFluct.h
float RhoFluct::m_rhoAJetPtLessRhoA private
Definition at line 74 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 74 of file RhoFluct.h
bool RhoFluct::m_Sub1_ismatched private
Definition at line 77 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 77 of file RhoFluct.h
float RhoFluct::m_Sub1Jet_delpt private
Definition at line 81 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 81 of file RhoFluct.h
float RhoFluct::m_Sub1JetEta private
Definition at line 79 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 79 of file RhoFluct.h
const std::string RhoFluct::m_Sub1JetName private
Definition at line 48 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 48 of file RhoFluct.h
float RhoFluct::m_Sub1JetPhi private
Definition at line 78 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 78 of file RhoFluct.h
float RhoFluct::m_Sub1JetPt private
Definition at line 80 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 80 of file RhoFluct.h
TTree* RhoFluct::m_T private
Output Tree variables.
Definition at line 54 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 54 of file RhoFluct.h
const std::string RhoFluct::m_truthJetName private
Definition at line 47 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 47 of file RhoFluct.h
float RhoFluct::mBGE_empty_area { 0 } private
Definition at line 85 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 85 of file RhoFluct.h
float RhoFluct::mBGE_mean_area { 0 } private
Definition at line 84 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 84 of file RhoFluct.h
float RhoFluct::mBGE_n_empty_jets { 0 } private
Definition at line 86 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 86 of file RhoFluct.h
unsigned int RhoFluct::mBGE_n_jets_used { 0 } private
Definition at line 87 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 87 of file RhoFluct.h
long long int RhoFluct::nevent { 0 } private
Definition at line 43 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 43 of file RhoFluct.h
long long int RhoFluct::outevent { 0 } private
Definition at line 44 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 44 of file RhoFluct.h
TRandom3 RhoFluct::rand3 {} private
Definition at line 41 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 41 of file RhoFluct.h
Float_t RhoFluct::rho
current Tree number in a TChain
Definition at line 25 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 25 of file RhoFluct.h
Float_t RhoFluct::rho_sigma
Definition at line 26 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 26 of file RhoFluct.h
Bool_t RhoFluct::rhoA_ismatched
Definition at line 38 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 38 of file RhoFluct.h
Referenced by Loop().
Float_t RhoFluct::rhoAJet_delPt
Definition at line 44 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 44 of file RhoFluct.h
Referenced by Loop().
Float_t RhoFluct::rhoAJetArea
Definition at line 42 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 42 of file RhoFluct.h
Float_t RhoFluct::rhoAJetEta
Definition at line 40 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 40 of file RhoFluct.h
Float_t RhoFluct::rhoAJetPhi
Definition at line 39 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 39 of file RhoFluct.h
Float_t RhoFluct::rhoAJetPt
Definition at line 41 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 41 of file RhoFluct.h
Float_t RhoFluct::rhoAJetPtLessRhoA
Definition at line 43 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 43 of file RhoFluct.h
Bool_t RhoFluct::sub1_ismatched
Definition at line 33 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 33 of file RhoFluct.h
Referenced by Loop().
Float_t RhoFluct::sub1Jet_delPt
Definition at line 37 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 37 of file RhoFluct.h
Referenced by Loop().
Float_t RhoFluct::sub1JetEta
Definition at line 35 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 35 of file RhoFluct.h
Float_t RhoFluct::sub1JetPhi
Definition at line 34 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 34 of file RhoFluct.h
Float_t RhoFluct::sub1JetPt
Definition at line 36 of file RhoFluct.h.
View newest version in sPHENIX GitHub at line 36 of file RhoFluct.h
The documentation for this class was generated from the following files:
analysis/blob/master/JS-Jet/FastJetMedianBkg/src_JetMedianTree/macro/plot/RhoFluct.h
analysis/blob/master/JS-Jet/FastJetMedianBkg/src_JetMedianTree/RhoFluct.h
analysis/blob/master/JS-Jet/FastJetMedianBkg/src_JetMedianTree/macro/plot/decile_RhoFluct.cc
analysis/blob/master/JS-Jet/FastJetMedianBkg/src_JetMedianTree/macro/plot/RhoFluct.cc
analysis/blob/master/JS-Jet/FastJetMedianBkg/src_JetMedianTree/RhoFluct.cc