Analysis Software: SingleZdcInput Class Reference
SingleZdcInput Class Reference
#include <coresoftware/blob/master/offline/framework/fun4allraw/SingleZdcInput.h>
Classes
struct PacketInfo
Public Member Functions
SingleZdcInput (const std::string &name, Fun4AllPrdfInputPoolManager *inman)
~SingleZdcInput () override
void FillPool (const unsigned int nevents) override
Public Member Functions inherited from SinglePrdfInput
SinglePrdfInput (const std::string &name, Fun4AllPrdfInputPoolManager *inman)
~SinglePrdfInput () override
Eventiterator * GetEventIterator ()
int RunNumber () const
void RunNumber (const int irun)
int fileopen (const std::string &filename) override
int fileclose () override
int AllDone () const
void AllDone (const int i)
void EventNumberOffset (const int i)
int EventNumberOffset () const
Fun4AllPrdfInputPoolManager * InputMgr ()
void MakeReference (const bool b)
bool ReferenceFlag () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Print (const std::string &what="ALL") const
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from InputFileHandler
InputFileHandler ()=default
virtual ~InputFileHandler ()=default
int OpenNextFile ()
int AddListFile (const std::string &filename)
int AddFile (const std::string &filename)
void AddToFileOpened (const std::string &filename)
void Print (const std::string &what="ALL") const
int IsOpen () const
void IsOpen (const int i)
void SetVerbosity (const int i)
int GetVerbosity () const
void UpdateFileList ()
void FileName (const std::string &fn)
const std::string FileName () const
Private Member Functions
int majority_eventnumber ()
int majority_beamclock ()
void adjust_eventnumber_offset (const int decided_evtno)
Private Attributes
Packet ** plist = nullptr
unsigned int m_NumSpecialEvents = 0
int * m_PacketEventNumberOffset = nullptr
std::map< int, std::vector
< Packet * > > m_PacketMap
std::set< int > m_EvtSet
std::vector< std::pair< int,
int > > m_Event
std::array< unsigned int, 100 > rollover
std::array< int, 100 > previous_eventnumber
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Detailed Description
Definition at line 17 of file SingleZdcInput.h.
View newest version in sPHENIX GitHub at line 17 of file SingleZdcInput.h
Constructor & Destructor Documentation
SingleZdcInput::SingleZdcInput (const std::string & name, Fun4AllPrdfInputPoolManager * inman) explicit
Definition at line 16 of file SingleZdcInput.cc.
View newest version in sPHENIX GitHub at line 16 of file SingleZdcInput.cc
References m_PacketEventNumberOffset, Acts::UnitConstants::min, plist, previous_eventnumber, and rollover.
SingleZdcInput::~SingleZdcInput () override
Definition at line 25 of file SingleZdcInput.cc.
View newest version in sPHENIX GitHub at line 25 of file SingleZdcInput.cc
References m_PacketEventNumberOffset, and plist.
Member Function Documentation
void SingleZdcInput::adjust_eventnumber_offset (const int decided_evtno) private
Definition at line 262 of file SingleZdcInput.cc.
View newest version in sPHENIX GitHub at line 262 of file SingleZdcInput.cc
References i, m_Event, m_PacketEventNumberOffset, and Fun4AllBase::Verbosity().
Referenced by FillPool().
void SingleZdcInput::FillPool (const unsigned int nevents) override virtual
Reimplemented from SinglePrdfInput.
Definition at line 31 of file SingleZdcInput.cc.
View newest version in sPHENIX GitHub at line 31 of file SingleZdcInput.cc
References Fun4AllPrdfInputPoolManager::AddBeamClock(), Fun4AllPrdfInputPoolManager::AddPacket(), adjust_eventnumber_offset(), SinglePrdfInput::AllDone(), Packet::convert(), DATAEVENT, SinglePrdfInput::EventNumberOffset(), SinglePrdfInput::fileclose(), SinglePrdfInput::GetEventIterator(), Event::getEvtSequence(), Event::getEvtType(), Packet::getIdentifier(), Eventiterator::getNextEvent(), Event::getPacketList(), Event::getRunNumber(), i, Event::identify(), SinglePrdfInput::InputMgr(), Packet::iValue(), m_Event, m_EvtSet, m_NumSpecialEvents, m_PacketEventNumberOffset, m_PacketMap, majority_beamclock(), majority_eventnumber(), nevents(), InputFileHandler::OpenNextFile(), PHWHERE, plist, previous_eventnumber, SinglePrdfInput::ReferenceFlag(), rollover, SinglePrdfInput::RunNumber(), Fun4AllPrdfInputPoolManager::SetReferenceClock(), Fun4AllPrdfInputPoolManager::UpdateDroppedPacket(), and Fun4AllBase::Verbosity().
int SingleZdcInput::majority_beamclock () private
Definition at line 299 of file SingleZdcInput.cc.
View newest version in sPHENIX GitHub at line 299 of file SingleZdcInput.cc
References m_Event, and Fun4AllBase::Verbosity().
Referenced by FillPool().
int SingleZdcInput::majority_eventnumber () private
Definition at line 279 of file SingleZdcInput.cc.
View newest version in sPHENIX GitHub at line 279 of file SingleZdcInput.cc
References m_Event.
Referenced by FillPool().
Member Data Documentation
std::vector<std::pair<int, int> > SingleZdcInput::m_Event private
Definition at line 38 of file SingleZdcInput.h.
View newest version in sPHENIX GitHub at line 38 of file SingleZdcInput.h
Referenced by adjust_eventnumber_offset(), FillPool(), majority_beamclock(), and majority_eventnumber().
std::set<int> SingleZdcInput::m_EvtSet private
Definition at line 37 of file SingleZdcInput.h.
View newest version in sPHENIX GitHub at line 37 of file SingleZdcInput.h
Referenced by FillPool().
unsigned int SingleZdcInput::m_NumSpecialEvents = 0 private
Definition at line 34 of file SingleZdcInput.h.
View newest version in sPHENIX GitHub at line 34 of file SingleZdcInput.h
Referenced by FillPool().
int* SingleZdcInput::m_PacketEventNumberOffset = nullptr private
Definition at line 35 of file SingleZdcInput.h.
View newest version in sPHENIX GitHub at line 35 of file SingleZdcInput.h
Referenced by adjust_eventnumber_offset(), FillPool(), SingleZdcInput(), and ~SingleZdcInput().
std::map<int, std::vector<Packet *> > SingleZdcInput::m_PacketMap private
Definition at line 36 of file SingleZdcInput.h.
View newest version in sPHENIX GitHub at line 36 of file SingleZdcInput.h
Referenced by FillPool().
Packet** SingleZdcInput::plist = nullptr private
Definition at line 33 of file SingleZdcInput.h.
View newest version in sPHENIX GitHub at line 33 of file SingleZdcInput.h
Referenced by FillPool(), SingleZdcInput(), and ~SingleZdcInput().
std::array<int,100> SingleZdcInput::previous_eventnumber private
Definition at line 40 of file SingleZdcInput.h.
View newest version in sPHENIX GitHub at line 40 of file SingleZdcInput.h
Referenced by FillPool(), and SingleZdcInput().
std::array<unsigned int,100> SingleZdcInput::rollover private
Definition at line 39 of file SingleZdcInput.h.
View newest version in sPHENIX GitHub at line 39 of file SingleZdcInput.h
Referenced by FillPool(), and SingleZdcInput().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4allraw/SingleZdcInput.h
coresoftware/blob/master/offline/framework/fun4allraw/SingleZdcInput.cc