Analysis Software: ActsExamples::TrackFitterPerformanceWriter Exception Reference
ActsExamples::TrackFitterPerformanceWriter Exception Reference final
#include <acts/blob/sPHENIX/Examples/Io/Performance/ActsExamples/Io/Performance/TrackFitterPerformanceWriter.hpp>
Classes
struct Config
Public Types
using HitParticlesMap = IndexMultimap< ActsFatras::Barcode >
Public Member Functions
TrackFitterPerformanceWriter (Config config, Acts::Logging::Level level)
~TrackFitterPerformanceWriter () override
ProcessCode finalize () override
Finalize plots.
const Config & config () const
Get readonly access to the config parameters.
Public Member Functions inherited from ActsExamples::WriterT< TrajectoriesContainer >
WriterT (std::string objectName, std::string writerName, Acts::Logging::Level level)
std::string name () const override
Provide the name of the writer.
ProcessCode write (const AlgorithmContext &context) override
Read the object and call the type-specific member function.
ProcessCode finalize () override
No-op default implementation.
Public Member Functions inherited from ActsExamples::IWriter
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Fulfil the algorithm interface.
Public Member Functions inherited from ActsExamples::SequenceElement
virtual ~SequenceElement ()=default
const std::vector< const
DataHandleBase * > & writeHandles () const
const std::vector< const
DataHandleBase * > & readHandles () const
Private Member Functions
ProcessCode writeT (const AlgorithmContext &ctx, const TrajectoriesContainer &trajectories) override
Private Attributes
Config m_cfg
ReadDataHandle
< SimParticleContainer > m_inputParticles {this, "InputParticles"}
ReadDataHandle< HitParticlesMap > m_inputMeasurementParticlesMap
std::mutex m_writeMutex
Mutex used to protect multi-threaded writes.
TFile * m_outputFile {nullptr}
ResPlotTool m_resPlotTool
Plot tool for residuals and pulls.
ResPlotTool::ResPlotCache m_resPlotCache
EffPlotTool m_effPlotTool
Plot tool for efficiency.
EffPlotTool::EffPlotCache m_effPlotCache
TrackSummaryPlotTool m_trackSummaryPlotTool
Plot tool for track hit info.
TrackSummaryPlotTool::TrackSummaryPlotCache m_trackSummaryPlotCache {}
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::WriterT< TrajectoriesContainer >
const Acts::Logger & logger () const
Detailed Description
Write out the residual and pull of track parameters and efficiency.
Efficiency here is the fraction of smoothed tracks compared to all tracks.
A common file can be provided for the writer to attach his TTree, this is done by setting the Config::rootFile pointer to an existing file
Safe to use from multiple writer threads - uses a std::mutex lock.
Definition at line 42 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 42 of file TrackFitterPerformanceWriter.hpp
Member Typedef Documentation
using ActsExamples::TrackFitterPerformanceWriter::HitParticlesMap = IndexMultimap<ActsFatras::Barcode>
Definition at line 45 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 45 of file TrackFitterPerformanceWriter.hpp
Constructor & Destructor Documentation
ActsExamples::TrackFitterPerformanceWriter::TrackFitterPerformanceWriter (Config config, Acts::Logging::Level level)
Construct from configuration and log level.
Parameters
config The configuration
level The logger level
Definition at line 32 of file TrackFitterPerformanceWriter.cpp.
View newest version in sPHENIX GitHub at line 32 of file TrackFitterPerformanceWriter.cpp
References ActsExamples::EffPlotTool::book(), ActsExamples::TrackSummaryPlotTool::book(), ActsExamples::ResPlotTool::book(), ActsExamples::TrackFitterPerformanceWriter::Config::filePath, ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::TrackFitterPerformanceWriter::Config::inputMeasurementParticlesMap, ActsExamples::TrackFitterPerformanceWriter::Config::inputParticles, m_cfg, m_effPlotCache, m_effPlotTool, m_inputMeasurementParticlesMap, m_inputParticles, m_outputFile, m_resPlotCache, m_resPlotTool, m_trackSummaryPlotCache, m_trackSummaryPlotTool, and path.
ActsExamples::TrackFitterPerformanceWriter::~TrackFitterPerformanceWriter () override
Definition at line 71 of file TrackFitterPerformanceWriter.cpp.
View newest version in sPHENIX GitHub at line 71 of file TrackFitterPerformanceWriter.cpp
Member Function Documentation
const Config& ActsExamples::TrackFitterPerformanceWriter::config () const inline
Get readonly access to the config parameters.
Definition at line 73 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 73 of file TrackFitterPerformanceWriter.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::TrackFitterPerformanceWriter::finalize () override virtual
Finalize plots.
Implements ActsExamples::SequenceElement.
Definition at line 82 of file TrackFitterPerformanceWriter.cpp.
View newest version in sPHENIX GitHub at line 82 of file TrackFitterPerformanceWriter.cpp
References ACTS_INFO, and SUCCESS.
ActsExamples::ProcessCode ActsExamples::TrackFitterPerformanceWriter::writeT (const AlgorithmContext & context, const TrajectoriesContainer & t) override private virtual
Type-specific write function implementation this method is implemented in the user implementation
Parameters
[in] context is the algorithm context that guarantees event consistency
Template Parameters
[in] is the templated collection to be written
Implements ActsExamples::WriterT< TrajectoriesContainer >.
Definition at line 97 of file TrackFitterPerformanceWriter.cpp.
View newest version in sPHENIX GitHub at line 97 of file TrackFitterPerformanceWriter.cpp
References ACTS_ERROR, ACTS_WARNING, ActsExamples::AlgorithmContext::geoContext, ActsExamples::identifyContributingParticles(), it, particle, particles, SUCCESS, and Acts::MultiTrajectoryHelpers::trajectoryState().
Member Data Documentation
Config ActsExamples::TrackFitterPerformanceWriter::m_cfg private
Definition at line 79 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 79 of file TrackFitterPerformanceWriter.hpp
Referenced by config(), and TrackFitterPerformanceWriter().
EffPlotTool::EffPlotCache ActsExamples::TrackFitterPerformanceWriter::m_effPlotCache private
Definition at line 93 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 93 of file TrackFitterPerformanceWriter.hpp
Referenced by TrackFitterPerformanceWriter().
EffPlotTool ActsExamples::TrackFitterPerformanceWriter::m_effPlotTool private
Plot tool for efficiency.
Definition at line 92 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 92 of file TrackFitterPerformanceWriter.hpp
Referenced by TrackFitterPerformanceWriter().
ReadDataHandle<HitParticlesMap> ActsExamples::TrackFitterPerformanceWriter::m_inputMeasurementParticlesMap private
Initial value:
{
      this, "inputMeasurementParticlesMap"}
Definition at line 82 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 82 of file TrackFitterPerformanceWriter.hpp
Referenced by TrackFitterPerformanceWriter().
ReadDataHandle<SimParticleContainer> ActsExamples::TrackFitterPerformanceWriter::m_inputParticles {this, "InputParticles"} private
Definition at line 81 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 81 of file TrackFitterPerformanceWriter.hpp
Referenced by TrackFitterPerformanceWriter().
TFile* ActsExamples::TrackFitterPerformanceWriter::m_outputFile {nullptr} private
Definition at line 87 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 87 of file TrackFitterPerformanceWriter.hpp
Referenced by TrackFitterPerformanceWriter().
ResPlotTool::ResPlotCache ActsExamples::TrackFitterPerformanceWriter::m_resPlotCache private
Definition at line 90 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 90 of file TrackFitterPerformanceWriter.hpp
Referenced by TrackFitterPerformanceWriter().
ResPlotTool ActsExamples::TrackFitterPerformanceWriter::m_resPlotTool private
Plot tool for residuals and pulls.
Definition at line 89 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 89 of file TrackFitterPerformanceWriter.hpp
Referenced by TrackFitterPerformanceWriter().
TrackSummaryPlotTool::TrackSummaryPlotCache ActsExamples::TrackFitterPerformanceWriter::m_trackSummaryPlotCache {} private
Definition at line 96 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 96 of file TrackFitterPerformanceWriter.hpp
Referenced by TrackFitterPerformanceWriter().
TrackSummaryPlotTool ActsExamples::TrackFitterPerformanceWriter::m_trackSummaryPlotTool private
Plot tool for track hit info.
Definition at line 95 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 95 of file TrackFitterPerformanceWriter.hpp
Referenced by TrackFitterPerformanceWriter().
std::mutex ActsExamples::TrackFitterPerformanceWriter::m_writeMutex private
Mutex used to protect multi-threaded writes.
Definition at line 86 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 86 of file TrackFitterPerformanceWriter.hpp
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Io/Performance/ActsExamples/Io/Performance/TrackFitterPerformanceWriter.hpp
acts/blob/sPHENIX/Examples/Io/Performance/ActsExamples/Io/Performance/TrackFitterPerformanceWriter.cpp