Analysis Software: macros/blob/master/common/G4_KFParticle.C File Reference
G4_KFParticle.C File Reference
#include <GlobalVariables.C>
#include <kfparticle_sphenix/KFParticle_sPHENIX.h>
#include <decayfinder/DecayFinder.h>
#include <qa_modules/QAG4SimulationKFParticle.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace KFPARTICLE
namespace KFParticleBaseCut
Macros
#define MACRO_G4KFPARTICLE_C
#define HomogeneousField
Functions
std::pair< float, float > KFPARTICLE::UpsilonMassRange (8, 11)
std::pair< float, float > KFPARTICLE::D0MassRange (1.75, 1.95)
std::pair< float, float > KFPARTICLE::LambdacMassRange (2.15, 2.45)
void KFParticle_Upsilon_Reco ()
void KFParticle_D0_Reco ()
void KFParticle_Lambdac_Reco ()
void KFParticle_QA ()
Variables
bool Enable::KFPARTICLE = false
bool Enable::KFPARTICLE_SAVE_NTUPLE = false
bool Enable::KFPARTICLE_APPEND_TO_DST = true
bool Enable::KFPARTICLE_TRUTH_MATCH = false
bool Enable::KFPARTICLE_DETECTOR_INFO = false
int Enable::KFPARTICLE_VERBOSITY = 0
std::string Enable::KFPARTICLE_TRACKMAP = "SvtxTrackMap"
std::string Enable::KFPARTICLE_VERTEXMAP = "SvtxVertexMap"
bool KFPARTICLE::QA = false
bool KFPARTICLE::runUpsilonReco = false
std::string KFPARTICLE::UpsilonName = "Upsilon"
std::string KFPARTICLE::UpsilonDecayDescriptor = UpsilonName + " -> e^+ e^-"
bool KFPARTICLE::UpsilonTrigger = false
bool KFPARTICLE::runD0Reco = false
std::string KFPARTICLE::D0Name = "D0"
std::string KFPARTICLE::D0DecayDescriptor = "[" + D0Name + " -> K^- pi^+]cc"
bool KFPARTICLE::D0Trigger = false
bool KFPARTICLE::runLambdacReco = false
std::string KFPARTICLE::LambdacName = "Lambdac"
std::string KFPARTICLE::LambdacDecayDescriptor = "[" + LambdacName + " -> proton^+ K^- pi^+]cc"
bool KFPARTICLE::LambdacTrigger = false
float KFParticleBaseCut::minTrackPT = 0.5
float KFParticleBaseCut::maxTrackchi2nDoF = 2
float KFParticleBaseCut::minTrackIPchi2 = 15
float KFParticleBaseCut::maxVertexchi2nDoF = 2
float KFParticleBaseCut::maxTrackTrackDCA = 0.05
float KFParticleBaseCut::minMotherPT = 0
Macro Definition Documentation
#define HomogeneousField
Definition at line 6 of file G4_KFParticle.C.
View newest version in sPHENIX GitHub at line 6 of file G4_KFParticle.C
#define MACRO_G4KFPARTICLE_C
Definition at line 2 of file G4_KFParticle.C.
View newest version in sPHENIX GitHub at line 2 of file G4_KFParticle.C
Function Documentation
void KFParticle_D0_Reco ()
Definition at line 100 of file G4_KFParticle.C.
View newest version in sPHENIX GitHub at line 100 of file G4_KFParticle.C
References KFParticle_sPHENIX::constrainToPrimaryVertex(), KFPARTICLE::D0DecayDescriptor, KFPARTICLE::D0MassRange(), KFPARTICLE::D0Name, KFParticle_sPHENIX::doTruthMatching(), KFParticle_sPHENIX::getDetectorInfo(), Fun4AllServer::instance(), Enable::KFPARTICLE_APPEND_TO_DST, Enable::KFPARTICLE_DETECTOR_INFO, Enable::KFPARTICLE_SAVE_NTUPLE, Enable::KFPARTICLE_TRUTH_MATCH, Enable::KFPARTICLE_VERBOSITY, KFParticleBaseCut::maxTrackchi2nDoF, KFParticleBaseCut::maxTrackTrackDCA, KFParticleBaseCut::maxVertexchi2nDoF, KFParticleBaseCut::minMotherPT, KFParticleBaseCut::minTrackIPchi2, KFParticleBaseCut::minTrackPT, Fun4AllServer::registerSubsystem(), KFPARTICLE::runD0Reco, KFParticle_sPHENIX::saveDST(), KFParticle_sPHENIX::saveOutput(), KFParticle_sPHENIX::setContainerName(), KFParticle_sPHENIX::setDecayDescriptor(), KFParticle_sPHENIX::setMaximumDaughterDCA(), KFParticle_sPHENIX::setMaximumMass(), KFParticle_sPHENIX::setMaximumTrackchi2nDOF(), KFParticle_sPHENIX::setMaximumVertexchi2nDOF(), KFParticle_sPHENIX::setMinimumMass(), KFParticle_sPHENIX::setMinimumTrackIPchi2(), KFParticle_sPHENIX::setMinimumTrackPT(), KFParticle_sPHENIX::setMotherPT(), KFParticle_sPHENIX::setOutputName(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), and Fun4All_SinglePi0Gen_sPHENIX().
void KFParticle_Lambdac_Reco ()
Definition at line 138 of file G4_KFParticle.C.
View newest version in sPHENIX GitHub at line 138 of file G4_KFParticle.C
References KFParticle_sPHENIX::constrainToPrimaryVertex(), KFParticle_sPHENIX::doTruthMatching(), KFParticle_sPHENIX::getDetectorInfo(), Fun4AllServer::instance(), Enable::KFPARTICLE_APPEND_TO_DST, Enable::KFPARTICLE_DETECTOR_INFO, Enable::KFPARTICLE_SAVE_NTUPLE, Enable::KFPARTICLE_TRUTH_MATCH, Enable::KFPARTICLE_VERBOSITY, KFPARTICLE::LambdacDecayDescriptor, KFPARTICLE::LambdacMassRange(), KFPARTICLE::LambdacName, KFParticleBaseCut::maxTrackchi2nDoF, KFParticleBaseCut::maxTrackTrackDCA, KFParticleBaseCut::maxVertexchi2nDoF, KFParticleBaseCut::minMotherPT, KFParticleBaseCut::minTrackIPchi2, KFParticleBaseCut::minTrackPT, Fun4AllServer::registerSubsystem(), KFPARTICLE::runLambdacReco, KFParticle_sPHENIX::saveDST(), KFParticle_sPHENIX::saveOutput(), KFParticle_sPHENIX::setContainerName(), KFParticle_sPHENIX::setDecayDescriptor(), KFParticle_sPHENIX::setMaximumDaughterDCA(), KFParticle_sPHENIX::setMaximumMass(), KFParticle_sPHENIX::setMaximumTrackchi2nDOF(), KFParticle_sPHENIX::setMaximumVertexchi2nDOF(), KFParticle_sPHENIX::setMinimumMass(), KFParticle_sPHENIX::setMinimumTrackIPchi2(), KFParticle_sPHENIX::setMinimumTrackPT(), KFParticle_sPHENIX::setMotherPT(), KFParticle_sPHENIX::setOutputName(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void KFParticle_QA ()
Definition at line 175 of file G4_KFParticle.C.
View newest version in sPHENIX GitHub at line 175 of file G4_KFParticle.C
References DecayFinder::allowPhotons(), DecayFinder::allowPi0(), KFPARTICLE::D0DecayDescriptor, KFPARTICLE::D0MassRange(), KFPARTICLE::D0Name, KFPARTICLE::D0Trigger, Fun4AllServer::instance(), Enable::KFPARTICLE_VERBOSITY, KFPARTICLE::LambdacDecayDescriptor, KFPARTICLE::LambdacMassRange(), KFPARTICLE::LambdacName, KFPARTICLE::LambdacTrigger, Fun4AllServer::registerSubsystem(), KFPARTICLE::runD0Reco, KFPARTICLE::runLambdacReco, KFPARTICLE::runUpsilonReco, DecayFinder::saveDST(), DecayFinder::setDecayDescriptor(), DecayFinder::triggerOnDecay(), KFPARTICLE::UpsilonDecayDescriptor, KFPARTICLE::UpsilonMassRange(), KFPARTICLE::UpsilonName, KFPARTICLE::UpsilonTrigger, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void KFParticle_Upsilon_Reco ()
Definition at line 62 of file G4_KFParticle.C.
View newest version in sPHENIX GitHub at line 62 of file G4_KFParticle.C
References KFParticle_sPHENIX::constrainToPrimaryVertex(), KFParticle_sPHENIX::doTruthMatching(), KFParticle_sPHENIX::getDetectorInfo(), Fun4AllServer::instance(), Enable::KFPARTICLE_APPEND_TO_DST, Enable::KFPARTICLE_DETECTOR_INFO, Enable::KFPARTICLE_SAVE_NTUPLE, Enable::KFPARTICLE_TRUTH_MATCH, Enable::KFPARTICLE_VERBOSITY, KFParticleBaseCut::maxTrackchi2nDoF, KFParticleBaseCut::maxTrackTrackDCA, KFParticleBaseCut::maxVertexchi2nDoF, KFParticleBaseCut::minMotherPT, KFParticleBaseCut::minTrackPT, Fun4AllServer::registerSubsystem(), KFPARTICLE::runUpsilonReco, KFParticle_sPHENIX::saveDST(), KFParticle_sPHENIX::saveOutput(), KFParticle_sPHENIX::setContainerName(), KFParticle_sPHENIX::setDecayDescriptor(), KFParticle_sPHENIX::setMaximumDaughterDCA(), KFParticle_sPHENIX::setMaximumMass(), KFParticle_sPHENIX::setMaximumTrackchi2nDOF(), KFParticle_sPHENIX::setMaximumVertexchi2nDOF(), KFParticle_sPHENIX::setMinimumMass(), KFParticle_sPHENIX::setMinimumTrackIPchi2(), KFParticle_sPHENIX::setMinimumTrackPT(), KFParticle_sPHENIX::setMotherPT(), KFParticle_sPHENIX::setOutputName(), KFPARTICLE::UpsilonDecayDescriptor, KFPARTICLE::UpsilonMassRange(), KFPARTICLE::UpsilonName, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), and Fun4All_SinglePi0Gen_sPHENIX().