Analysis Software: ActsExamples::ParticleSelector::Config Struct Reference
ActsExamples::ParticleSelector::Config Struct Reference
#include <acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/ParticleSelector.hpp>
Public Attributes
std::string inputParticles
The input particles collection.
std::string inputMeasurementParticlesMap
Input measurement particles map (Optional)
std::string outputParticles
The output particles collection.
double rhoMin = 0
double rhoMax = std::numeric_limits<double>::infinity()
double absZMin = 0
double absZMax = std::numeric_limits<double>::infinity()
double timeMin = -std::numeric_limits<double>::infinity()
double timeMax = std::numeric_limits<double>::infinity()
double phiMin = -std::numeric_limits<double>::infinity()
double phiMax = std::numeric_limits<double>::infinity()
double etaMin = -std::numeric_limits<double>::infinity()
double etaMax = std::numeric_limits<double>::infinity()
double absEtaMin = 0
double absEtaMax = std::numeric_limits<double>::infinity()
double ptMin = 0
double ptMax = std::numeric_limits<double>::infinity()
double mMin = 0
double mMax = std::numeric_limits<double>::infinity()
std::size_t measurementsMin = 0
Measurement number cuts.
std::size_t measurementsMax = std::numeric_limits<std::size_t>::max()
bool removeCharged = false
Remove charged particles.
bool removeNeutral = false
Remove neutral particles.
bool removeSecondaries = false
Remove secondaries.
Detailed Description
Definition at line 33 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 33 of file ParticleSelector.hpp
Member Data Documentation
double ActsExamples::ParticleSelector::Config::absEtaMax = std::numeric_limits<double>::infinity()
Definition at line 55 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 55 of file ParticleSelector.hpp
Referenced by main(), and ActsExamples::ParticleSelector::ParticleSelector().
double ActsExamples::ParticleSelector::Config::absEtaMin = 0
Definition at line 54 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 54 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
double ActsExamples::ParticleSelector::Config::absZMax = std::numeric_limits<double>::infinity()
Definition at line 45 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 45 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
double ActsExamples::ParticleSelector::Config::absZMin = 0
Definition at line 44 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 44 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
double ActsExamples::ParticleSelector::Config::etaMax = std::numeric_limits<double>::infinity()
Definition at line 53 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 53 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
double ActsExamples::ParticleSelector::Config::etaMin = -std::numeric_limits<double>::infinity()
Definition at line 52 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 52 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
std::string ActsExamples::ParticleSelector::Config::inputMeasurementParticlesMap
Input measurement particles map (Optional)
Definition at line 37 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 37 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
std::string ActsExamples::ParticleSelector::Config::inputParticles
The input particles collection.
Definition at line 35 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 35 of file ParticleSelector.hpp
Referenced by main(), and ActsExamples::ParticleSelector::ParticleSelector().
std::size_t ActsExamples::ParticleSelector::Config::measurementsMax = std::numeric_limits<std::size_t>::max()
Definition at line 64 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 64 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
std::size_t ActsExamples::ParticleSelector::Config::measurementsMin = 0
Measurement number cuts.
Definition at line 63 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 63 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
double ActsExamples::ParticleSelector::Config::mMax = std::numeric_limits<double>::infinity()
Definition at line 61 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 61 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
double ActsExamples::ParticleSelector::Config::mMin = 0
Definition at line 60 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 60 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
std::string ActsExamples::ParticleSelector::Config::outputParticles
The output particles collection.
Definition at line 39 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 39 of file ParticleSelector.hpp
Referenced by main(), and ActsExamples::ParticleSelector::ParticleSelector().
double ActsExamples::ParticleSelector::Config::phiMax = std::numeric_limits<double>::infinity()
Definition at line 51 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 51 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
double ActsExamples::ParticleSelector::Config::phiMin = -std::numeric_limits<double>::infinity()
Definition at line 50 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 50 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
double ActsExamples::ParticleSelector::Config::ptMax = std::numeric_limits<double>::infinity()
Definition at line 58 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 58 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
double ActsExamples::ParticleSelector::Config::ptMin = 0
Definition at line 57 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 57 of file ParticleSelector.hpp
Referenced by main(), and ActsExamples::ParticleSelector::ParticleSelector().
bool ActsExamples::ParticleSelector::Config::removeCharged = false
Remove charged particles.
Definition at line 66 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 66 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
bool ActsExamples::ParticleSelector::Config::removeNeutral = false
Remove neutral particles.
Definition at line 68 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 68 of file ParticleSelector.hpp
Referenced by main(), and ActsExamples::ParticleSelector::ParticleSelector().
bool ActsExamples::ParticleSelector::Config::removeSecondaries = false
Remove secondaries.
Definition at line 71 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 71 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
double ActsExamples::ParticleSelector::Config::rhoMax = std::numeric_limits<double>::infinity()
Definition at line 42 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 42 of file ParticleSelector.hpp
Referenced by main(), and ActsExamples::ParticleSelector::ParticleSelector().
double ActsExamples::ParticleSelector::Config::rhoMin = 0
Definition at line 41 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 41 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
double ActsExamples::ParticleSelector::Config::timeMax = std::numeric_limits<double>::infinity()
Definition at line 48 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 48 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
double ActsExamples::ParticleSelector::Config::timeMin = -std::numeric_limits<double>::infinity()
Definition at line 47 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 47 of file ParticleSelector.hpp
Referenced by ActsExamples::ParticleSelector::ParticleSelector().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/ParticleSelector.hpp