Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Plugins/DD4hep/DD4hepCylinderVolumeStructureTests.cpp File Reference
DD4hepCylinderVolumeStructureTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Plugins/DD4hep/DD4hepVolumeStructure.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Utilities/Logger.hpp"
#include <fstream>
#include <string>
#include <DD4hep/DetElement.h>
#include <DD4hep/DetFactoryHelper.h>
#include <DD4hep/Detector.h>
#include <XML/Utilities.h>
#include <XMLFragments.hpp>
#include "DD4hepTestsHelper.hpp"
Functions
BOOST_AUTO_TEST_CASE (DD4hepPluginCylindricalVolumeStructure)
BOOST_AUTO_TEST_CASE (DD4hepPluginShiftedCylindricalVolumeStructure)
Variables
Acts::GeometryContext tContext
const char * beampipe_head_xml
const char * tail_xml
const char * indent_12_xml = " "
Function Documentation
BOOST_AUTO_TEST_CASE (DD4hepPluginCylindricalVolumeStructure)
Definition at line 40 of file DD4hepCylinderVolumeStructureTests.cpp.
View newest version in sPHENIX GitHub at line 40 of file DD4hepCylinderVolumeStructureTests.cpp
References beampipe_head_xml, bounds, Acts::Experimental::DD4hepVolumeStructure::builder(), end_xml, Acts::getDefaultLogger(), head_xml, indent_12_xml, Acts::Experimental::DD4hepVolumeStructure::Options::logLevel, Acts::Experimental::DD4hepVolumeStructure::Options::name, portalGenerator, tail_xml, Acts::Test::transform, physmon_ckf_tracking::u, and Acts::Logging::VERBOSE.
BOOST_AUTO_TEST_CASE (DD4hepPluginShiftedCylindricalVolumeStructure)
Definition at line 111 of file DD4hepCylinderVolumeStructureTests.cpp.
View newest version in sPHENIX GitHub at line 111 of file DD4hepCylinderVolumeStructureTests.cpp
References beampipe_head_xml, bounds, Acts::Experimental::DD4hepVolumeStructure::builder(), CHECK_CLOSE_ABS, Acts::UnitConstants::e, end_xml, Acts::getDefaultLogger(), head_xml, indent_12_xml, Acts::Experimental::DD4hepVolumeStructure::Options::logLevel, Acts::Experimental::DD4hepVolumeStructure::Options::name, portalGenerator, tail_xml, Acts::Test::transform, physmon_ckf_tracking::u, and Acts::Logging::VERBOSE.
Variable Documentation
const char* beampipe_head_xml
Initial value:
=
    R""""(
    <detectors>
        <detector id="0" name="BeamPipe" type="BarrelDetector">
            <type_flags type="DetType_TRACKER + DetType_BEAMPIPE"/>
)""""
Definition at line 29 of file DD4hepCylinderVolumeStructureTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file DD4hepCylinderVolumeStructureTests.cpp
const char* indent_12_xml = " "
Definition at line 35 of file DD4hepCylinderVolumeStructureTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file DD4hepCylinderVolumeStructureTests.cpp
const char* tail_xml
Initial value:
=
    R""""(
        </detector>
    </detectors>
)""""
Definition at line 32 of file DD4hepCylinderVolumeStructureTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file DD4hepCylinderVolumeStructureTests.cpp
Acts::GeometryContext tContext
Definition at line 27 of file DD4hepCylinderVolumeStructureTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file DD4hepCylinderVolumeStructureTests.cpp